### ISSUE TITLE
v1.10.6 y 1.10.8: Grabar Competencias, estudio y Títulos.

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1364]
Saludos,

En estas versiones se habilita el perfil extendido de los usuarios como competencias, que títulos tiene, qué sabe hacer. Estos aparecen en el perfil pero la información que se coloca no se muestra al público ni al usuario correspondiente, a pesar de grabar la información. Pero si aparece por debajo grabada la información en la base de datos.
Favor revisar.

**Comment by NicoDucou** [comment]
Los campos aparecen bien y pueden ser grabadas en la pagina main/auth/profile.php de edicion del perfil pero una vez grabadas no aparecen ni en main/social/home.php ni en main/social/profile.php 
Entonces grabas informacion en tu perfil pero no sirven de ningun lado.

**Comment by fergimon** [comment]
Buenos días este bug queda solucionado  se verifico en la versión  1.10.6

**Comment by ywarnier** [comment]
@NicoDucou en main/social/profile.php sí veo los datos en la columna de la derecha.
![extended](https://cloud.githubusercontent.com/assets/609839/17818294/8797b458-6608-11e6-8b47-ef9ef19b8888.png)
