### ISSUE TITLE
Sin datos en reporte detallado de tiempos

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1365]
Buenos días espero que me ayuden con este inconveniente que lo estoy presentando en la versión 1.10.6 no se si es un bug o un error de la plataforma, tengo problemas cuando quiero sacar un informe detallado del acceso de un profesor o alumno para realizarle un seguimiento de acceso a la plataforma le doy el rango de la fecha y por dia o por mes no me sale nada, no me sale todas las cantidades de veces detallas de sus accesos como me los mostraba en la versión 1.10.9

**Comment by ywarnier** [comment]
Hola @fergimon, gracias por reportar estos inconvenientes. Solo como recordatorio, esta es nuestra política en lo que se refiere a [soporte de versiones anteriores](https://github.com/chamilo/chamilo-lms/wiki/Estrategia-de-soporte-comunitario). En concreto, como vamos a publicar la 1.11.0 en los días muy próximos, vamos a revisar si este problema (y los demás reportados) se presenta en la 1.11.0. De no ser el caso, será considerado arreglado por disponibilidad de una versión que lo soluciona. En el enlace se explica de manera más detallada el porqué.

**Comment by ywarnier** [comment]
Arreglo  commit 608a869da , reportado en https://support.chamilo.org/issues/8405
