### ISSUE TITLE
User tool: teacher tab switches back to student tab on clicking next page

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1369]
![userlist_issue_chamilo](https://cloud.githubusercontent.com/assets/1659604/17776695/e074d00c-655d-11e6-8410-8cda1b2c482c.PNG)

When there are more than 20 teachers in a course and you want to find one or move to the next page, the view switches back to the student list. 

Tested on https://1.10.chamilo.org/main/user/user.php?cidReq=TEST123

Edit: if I select "ALL" in the page-count-dropdown, the view switches to.. the campus mainpage?

**Comment by ywarnier** [comment]
You should be able to fix that with the one-line fix I just sent (see links above)

**Comment by jderriks** [comment]
Almost works. Selecting "ALL" instead of 20 still crashes the tool and gives me the campus starting page.

**Comment by ywarnier** [comment]
This should be OK now (with the last patch sent)

**Comment by fergimon** [comment]
Cordial Saludo

Buenas tardes se realizo la prueba en la versión 1.10.6  y no me funciono , le doy en que me liste todos los estudiante y me manda a la pagina principal.

**Comment by ywarnier** [comment]
@jderriks, does this work for you now?

**Comment by jderriks** [comment]
Seems OK in 1.11 except for a small bug (or feature?): the page number last seen seems to be stored during the session.
This means that when you see users page "21 - 40 / 200" and you move away to another tool or course and then return to the user list, it will not start at the first item but at the page last seen of that course. That is not intuitive.

**Comment by ywarnier** [comment]
Yeah... that's a feature (until proven otherwise :-))
