### ISSUE TITLE
Bug Versión 1.10.6 y 1.10.8: Categorías, grupos y subgrupos en sesiones y curso principal

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1371]
Saludos,

Hemos creado un curso con sus diferentes sesiones. 
En el curso principal, en grupos, se crea una categoría y esta se muestra en cada sesión. 
En el curso principal se crean grupos en la respectiva categoría. Estos grupos no se muestran en la misma categoría en las sesiones.
Si creo subgrupos de los grupos en el principal, en las sesiones se muestra que se han creado sesiones pero no se muestra los subgrupos.
En las sesiones puedo crear grupos y subgrupos como también categorías.
Las categorías creadas en las sesiones se muestran en el curso principal y en todas las sesiones.
Puedo crear subgrupos en las sesiones, estas se muestran en el curso principal.
Si alguien borra los subgrupos de una sesión, estos se borran de todas las sesiones, inclusive del curso principal.
Si en el curso principal borro los subgrupos, estos se borran de todas las sesiones.

**Comment by ywarnier** [comment]
No entiendo el problema indicado. En Chamilo 1.10, no existen "Categorías de grupos" ni "subgrupos" en los cursos.
Si se tratan de "Clases", no se trata de la misma noción... de qué estamos hablando aquí? Una URL para explicar donde se encuentran estas categorías? Una captura de pantalla?

**Comment by ywarnier** [comment]
Algun feedback aquí?
