### ISSUE TITLE
Bug Versión 1.10.6 y 1.10.8: informes para el Tutor de sesión

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1372]
Saludos,

El Tutor de una Sesión no puede ver los informes detallados de un estudiante, a pesar de que se le ha dado los mismos privilegios del administrador del curso.

**Comment by ywarnier** [comment]
En 1.11 no tengo el problema
- creo una sesión (aaaa)
- asocio un curso a la sesión (Anglais niveau de base)
- registro un profesor (que *no* es profesor del curso ni admin de la plataforma) como tutor del curso dentro de esta sesión
- registro un alumno (Aimee Mann) como alumno de esta sesión
- como tutor, entro al curso+sesión
- voy a la pestaña "Informes" dentro del curso
- le doy clic al icono de detalles del alumno "Aimee Mann", lo cual me manda a la URL http://my.chamilo111.net/main/mySpace/myStudents.php?student=62&details=true&course=ENGLISH101&origin=tracking_course&id_session=1
- puedo ver la hoja de seguimiento detallado del alumno
![reporte-detallado](https://cloud.githubusercontent.com/assets/609839/19226327/561f7458-8e6f-11e6-8c4a-799bfe35d055.png)

Es posible que el problema exista en 1.10.8, pero estamos a punto de sacar la 1.11.0 y no lo puedo reproducir en esta versión. Sugiero se hagan las pruebas de actualización tan pronto como salga la versión estable para corregir el problema, o sino reportar otro procedimiento para reproducirlo en https://1.11.chamilo.org/
