### ISSUE TITLE
Portal News "more" button hidden by left-carousel-control if more than 1 portal news message

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1373]
IF a portal news message is more than some lines, a MORE button is added.
IF two portal messages or more are present, LEFT and RIGHT parts are defined as css class:
`
<a class="left carousel-control" href="#carousel-announcement" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
`
And those two combined mean you cannot click the "more" button in a portal news message.

**Comment by ywarnier** [comment]
This has been fixed through https://github.com/chamilo/chamilo-lms/commit/3244d1d3d2a1de7075ca7aa6eb1f8ae8b6d58153 and verified by a third party (me)
