### ISSUE TITLE
Bug en listar todos los usuarios en la sección  la v-1.10.6

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1374]
Cordial Saludos
![captura 1](https://cloud.githubusercontent.com/assets/20644209/17857359/18fc2cae-6847-11e6-9ee9-7e819a381eb9.JPG)

En el modulo de usuarios  en una sección cuando se requiere listar todos  los estudiantes  lo envía  a la pagina principal

**Comment by ywarnier** [comment]
Esto ya fue reportado y resuelto en #1369
