### ISSUE TITLE
Bug Versión 1.10.6 y 1.10.8 de Chamilo El Tutor no puede corregir ejercicios

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1378]
Saludos,

En las sesiones, el tutor no puede corregir ejercicios, a pesar, que tiene los derechos del administrador del curso.

**Comment by jmontoyaa** [comment]
Lo he probado en la última versión de chamilo 1.10.x y funciona correctamente.
Lo mejor sería intentar de replicar el error en nuestro portal de pruebas:

1.10.chamilo.org

login:pass admin/admin

**Comment by fergimon** [comment]
En el portal de pruebas  1.10.chamilo.org, sube el archivo, pero no se identifican las preguntas.
Revisa el curso con código  AAAAA. Ahí lo he subido en ejercicios.
