### ISSUE TITLE
Php notices on sub-language creation

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1384]
```
Notice: Undefined index: sub_language_id in .../main/inc/global.inc.php on line 364
Notice: Undefined index: dokeos_folder in .../main/inc/global.inc.php on line 400
Deprecated: Function split() is deprecated in .../main/inc/lib/sub_language.class.php on line 125
```

This happened with chamilo1.10.x when creating a sub-language word and save it.

**Comment by ywarnier** [comment]
PHP Notice-level is not supported and we will move from our current system to Gettext for Chamilo 2.0, so it is unlikely that we will attend this report.
You can avoid PHP Notices by adding " & ~E_NOTICE" to the error_reporting setting in your php.ini or with "php_admin_value error_reporting 8135" in your Apache vhost.

**Comment by jderriks** [comment]
Sorry, our admin config "Test Server" was selected instead of "production". That made the difference.
