### ISSUE TITLE
Problema creación tareas en grupos + sesiones - 1.10.6 & 1.10.8

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1385]
Cordial Saludo

No queda  registrada la tarea  cuando se maneja por grupos en secciones, cuando  se sube por el método enviar, si lo hace correctamente cuando se  selecciona por el método enviar (simple).

**Comment by jmontoyaa** [comment]
Hola, es posible de reproducir el error aquí?

https://1.10.chamilo.org/

admin/admin

**Comment by fergimon** [comment]
Cordial Saludo

Gracias por responder, si claro antes de colocar el caso realice la prueba  en ese sitio pero tampoco funciono.

**Comment by ywarnier** [comment]
Hemos hecho unas correcciones en 1.11 para la subida de tareas últimamente, pero no se si mejorarán también para este caso o no.

**Comment by ywarnier** [comment]
@fergimon la pregunta de @jmontoyaa era más de si nos puedes dar un enlace al ejemplo en la plataforma https://1.10.chamilo.org para ganar tiempo.

**Comment by fergimon** [comment]
Buenos días 
he realizado una prueba subiendo un documento en la https://1.10.chamilo.org en el curso Colombia  pero ahora ni siquiera me carga por los dos métodos, no es problema  de espacio del curso es un documento de word
![cargue de archivo](https://cloud.githubusercontent.com/assets/20644209/18588105/b5410e0c-7bea-11e6-8172-166941d29075.JPG)

**Comment by ywarnier** [comment]
@fergimon Podrías explicar como llegas a esta URL como administrador dentro de la *herramienta* de tareas? No logro encontrarme ahí, ni creando una tarea ni subiendo correcciones...

**Comment by jloguercio** [comment]
@ywarnier para llegar ahí se tiene que ser alumno, pero se pueden seguir los sgtes pasos como administrador:

1. Llegar a la lista de tareas
2. Cambiar a vista estudiante
3. Ingresar a la tarea
4. click en subir tarea
5. Cambiar a vista profesor

He probado creando una tarea y subiendo una archivo docx, en el mismo curso, la subida se realiza OK, lo único que si es que no me arroja ningún mensaje de éxito

![captura de pantalla de 2016-10-09 23-34-53](https://cloud.githubusercontent.com/assets/12191804/19227020/26b9f684-8e79-11e6-9c21-6bd733cb1c0b.png)

**Comment by fergimon** [comment]
@jloguercio 
@ywarnier  

Cordial Saludo
gracias por su colaboración con este caso, pero el problema se presenta cuando estas subiendo tareas por grupos y cuando manejas secciones.

**Comment by fergimon** [comment]
@jloguercio 
@ywarnier
El problema se presenta en la herramienta tareas cuando se crean los grupos de un curso. Igual sucede en la sesiones de un curso.

**Comment by jloguercio** [comment]
Estimado @fergimon podría hacer una bitácora o lista de pasos para poder reproducir el error en 1.11.chamilo.org?

Actualmente estoy en una session, dentro de un grupo creado en la session y sigo sin reproducir el error como puede ver en las imagenes:

![grupo1](https://cloud.githubusercontent.com/assets/12191804/19371241/3df5086a-9177-11e6-86b3-99dd7d1a5e1f.png)

![grupo2](https://cloud.githubusercontent.com/assets/12191804/19371246/429d960c-9177-11e6-842c-e24a21d65013.png)

**Comment by fergimon** [comment]
El archivo parece que sube, pero no se muestra a los estudiantes.
Anexo archivo con imágenes

[Tarea.pdf](https://github.com/chamilo/chamilo-lms/files/530455/Tarea.pdf)

**Comment by jloguercio** [comment]
Estimado @fergimon eso es debido a que la plataforma no admitía la duplicidad de tareas subidas con el mismo nombre de archivo, el problema surgía cuando se borraba la tarea subida y se intentaba subir de nuevo, pero eso fue corregido en la version 1.11.x más específicamente aquí : https://github.com/chamilo/chamilo-lms/commit/98aeb95b5384cd615996107d91e3b57ab1792971

Saludos
