### ISSUE TITLE
Bug Versión 1.10.6 y 1.10.8 de Chamilo No se ven las imágenes en ejercicios modo estudiante

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1387]
Saludos,

Se crea un ejercicio con preguntas que contienen imágenes en un curso o sesión. En el modo profesor se ve bien, pero en el modo estudiante no se ven las imágenes.
Anexo archivo.
[pregunta imágenes.docx](https://github.com/chamilo/chamilo-lms/files/447600/pregunta.imagenes.docx)

**Comment by ywarnier** [comment]
Estoy probando en el curso "Colombia" en https://1.10.chamilo.org/, ejercicio "f" (lo he dejado ahí para pruebas).
- creo una pregunta de respuesta única, con 3 respuestas de una imagen cada una (de las cuales la foto viene de la carpeta de documentos del curso y las imagenes vienen de la carpeta MyFiles, para estar seguro de ver todos los casos)
- creo una pregunta de tipo selección de imagen, usando la misma combinación de fotos/imágenes
- me conecto con el usuario "ernesto, eras" (alumno) y puedo ver las imágenes perfectamente bien.

![imagenes-ejercicio](https://cloud.githubusercontent.com/assets/609839/19226595/c11cf4f8-8e72-11e6-912e-836b240aca43.png)

![ejercicio-imagenes-2](https://cloud.githubusercontent.com/assets/609839/19226598/c3c8cbd2-8e72-11e6-95f1-c36572353be4.png)

Por lo tanto, declaro este bug "no habido", pero si hay un caso más preciso que nos permita reproducir el problema, lo revisaremos.
Ojo que los problemas de acceso pueden ser debidos a mala configuración del servidor web o del archivo .htaccess.

**Comment by fergimon** [comment]
En ejercicios, en modo estudiante no se ven las imágenes cuando sobrepasa los pixeles recomendados por Chamilo. 200x150 pixeles.

**Comment by ywarnier** [comment]
Bueno, por algo está indicado el tamaño de imágenes por subir, no?

**Comment by mansaya** [comment]
Me podrias ayudar con algo es que cuando creo una leccion y debo colocar una imagen en el modo profesor se ve la imagen, pero cuando voy a leccion por estudiante se ve un cuadro que pertenece a que no se puede ver la imagen, cuando le digo ver la imagen en otra pestalla sale que el documento esta protegido, a que se puede deber esta situacion, estoy con al version de chamilo chamilo-1.11.6, muchas gracias

**Comment by ywarnier** [comment]
@mansaya en una nueva "Issue", por favor. No mezclar los temas (en particular cuando están cerrados), esto nos hace imposible el seguimiento. Gracias.
