### ISSUE TITLE
show_simple_session_info configuration setting

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1388]
When turning this:

$_configuration['show_simple_session_info'] = true;

The session list doesnt show correct information

**Comment by ywarnier** [comment]
Para ser correctos, eso es más un problema para Alex que para Angel.
Cuando no activo nada:
![session-not-simple](https://cloud.githubusercontent.com/assets/609839/19226768/682af860-8e75-11e6-9249-42d1a8ef74c9.png)

Y cuando agrego $_configuration['show_simple_session_info'] = true;  en configuration.php, tengo esto:
![session-simple](https://cloud.githubusercontent.com/assets/609839/19226774/78b2505c-8e75-11e6-8732-83fb0e777399.png)

El problema principal aquí es que el modo "simple" quita el título de la sesión, que también es un enlace. Si se quita el nombre de la sesión, solo queda la fecha, que no sirve de nada por ella sola...

**Comment by ywarnier** [comment]
I sent a partial fix but it would be good to improve it a bit more before the release.

**Comment by aragonc** [comment]
Cambios enviados

**Comment by ywarnier** [comment]
Looks good.
