### ISSUE TITLE
Import users as CSV: incorrect example given

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1389]
A teacher complained he could not import students in his course. He had semicolons as shown in the example:
` username;
    jdoe;
    jmontoya;`

Removing the semicolons was the solution to his problem.
Wrong example is produced by main/user/user_import.php

`echo get_lang('CSVMustLookLike');
echo '<blockquote><pre>
    username;
    jdoe;
    jmontoya;
</pre>
</blockquote>';

echo get_lang('Or');
echo '<blockquote><pre>
    id;
    23;
    1337;
</pre>
</blockquote>';
`

**Comment by ywarnier** [comment]
Semi-columns is the accepted format. This is weird. Can you post a screenshot?
Any chance the Dutch translation would be the one causing this misinterpretation?

**Comment by ywarnier** [comment]
Fix approved.
