### ISSUE TITLE
Instalacion Chamilo

### ISSUE THREAD

**Issue by javibloem** [chamilo/chamilo-lms#1395]
Buenas, intento instalar chamilo siguiendo los pasos mencionados en la documentación pero de alguna forma faltan algunas cosas, la carpeta "install" no se encuentra, por lo que una vez ejecutado "composer update" no puedo ir a instalar chamilo, cabe mencionar que segui fielmente los pasos mencionados, y anteriormente habia instalado chamilo sin ningun inconveniente, solo que ahora quiero contribuir con chamilo

Salu2

**Comment by javibloem** [comment]
Pude ver que la rama 1.11.0 si tiene la carpeta install, pero en la rama master no.

**Comment by ywarnier** [comment]
La rama master es una rama de desarrollo demasiado inestable por ahora. Una vez la versión 1.11.0 liberada, se iniciará el desarrollo más estable en la rama master, y en esta oportunidad se desarrollará una guía de instalación válida :-)
