### ISSUE TITLE
Multiple selection on course's members

### ISSUE THREAD

**Issue by djoshy** [chamilo/chamilo-lms#1399]
Since 1.10.8, multiple selections on course's members is buggy.

I can select many users but when i do action, like "unsubscribe" it's going to home page and action is not working.
The same with "display all" when members are on several pages in course's members.

**Comment by ywarnier** [comment]
Are you using Apache or Nginx as the web server? I'm asking because the fact it goes to the homepage is generally due to an error in redirections, and the Nginx rules might still have issues.

**Comment by djoshy** [comment]
Hi Yannick
Yes Apache 2.4.7 on Ubuntu.

Plugins enabled :
- BBB
- Compilatio (custom code from the pull request https://github.com/chamilo/chamilo-lms/pull/1244)

**Comment by jderriks** [comment]
Looks like the select-all issue mentioned in
https://github.com/chamilo/chamilo-lms/issues/1369

**Comment by djoshy** [comment]
@jderriks : it could be ... but it's said that is corrected in 1.10.8 and I have this problem in this version.

However, I tested the folder "chamilo/main/user" of the branch 1.11 and that fixed the problem.

**Comment by ywarnier** [comment]
I'm closing it because it is fixed in 1.11 (as per @djoshy 's comment).
