### ISSUE TITLE
Lentitud consulta herramienta evaluaciones en sesiones en 1.10.6 y 1.10.8

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1400]
Cordial saludo,

Cuando se hace la consulta en la herramienta Evaluaciones en una sesión, tarda de 20 segundos a dos minutos en mostrar la información. Cómo lo puedo optimizar?. 

En el curso Raíz (Principal o Padre) funciona muy bien la consulta, el problema es en las sesiones.
Muchas Gracias.

**Comment by ywarnier** [comment]
@fergimon cuantas sesiones tienen en la base de datos? (es para tener una idea de como reproducir el problema)
Muestra algo durante estos 20 segundos el comando "SHOW FULL PROCESSLIST;" en la base de datos?

**Comment by fergimon** [comment]
Tenemos 109 sesiones por ahora en total.
Un curso tiene 25 sesiones.
Me dicen que se no muestra nada en el "SHOW FULL PROCESSLIST;"

**Comment by ywarnier** [comment]
No veo ninguna irregularidad en cuanto a las consultas en la base de datos. Lo pongo en espera hasta encontrar un caso similar que podamos reproducir.

**Comment by ywarnier** [comment]
Sin haber podido encontrar ningun caso similar hasta ahora, voy cerrando esta tarea. Ojo que en la versión 1.11.4 por llegar en unas semanas, existen varias optimizacions de eficiencia que hemos estado trabajando con un cliente en Bélgica. Si no soluciona este problema en particular, debería ayudar bastante, en todo caso. También la 1.11 soporta PHP 7.0 por completo, por lo que va otra optimización posible. Finalmente, hoy se acaba de añadir una optimización que debería producir ganancias de eficiencia en todas las páginas en las cuales aparecen listas.
