### ISSUE TITLE
DQL error in my progress, as student

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1401]
As a student, in 1.11.x, I enter a course and its learning path, then I go to the "my progress" tab and I click to see the details of the course.

I then get the following error, which suggests that something is wrong about the "PublicatedOn" field...

![errorlpprogress](https://cloud.githubusercontent.com/assets/609839/18413943/32590fe6-777e-11e6-8f38-8bc7c8bc84b5.png)

**Comment by AngelFQC** [comment]
This should already be corrected now

**Comment by jmontoyaa** [comment]
I don't have that error.

**Comment by ywarnier** [comment]
Fixed for me. It would be interesting to see why you don't have the issue, Julio, because the testing procedure described above works to reproduce it before Angel's patch.

**Comment by jmontoyaa** [comment]
@ywarnier Probably it was fixed when I test it.
