### ISSUE TITLE
Fresh 1.11.x install blows up in flames - PageableManagerInterface not found

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1403]
Freshly installed on https://1.11.chamilo.org/
After logging in as admin, I get this:

Fatal error: Interface 'Sonata\CoreBundle\Model\PageableManagerInterface' not found in /var/www/1.11.chamilo.org/www/vendor/sonata-project/user-bundle/Model/UserManagerInterface.php on line 24 
Call Stack: 
0.0009 292736 1. {main}() /var/www/1.11.chamilo.org/www/index.php:0 0.0030 419272 2. require_once('/var/www/1.11.chamilo.org/www/main/inc/global.inc.php') /var/www/1.11.chamilo.org/www/index.php:17 
1.0866 13291552 3. require('/var/www/1.11.chamilo.org/www/main/inc/local.inc.php') /var/www/1.11.chamilo.org/www/main/inc/global.inc.php:508 
1.1199 14605088 4. UserManager::getManager() /var/www/1.11.chamilo.org/www/main/inc/local.inc.php:269 
1.1217 14684312 5. spl_autoload_call() /var/www/1.11.chamilo.org/www/main/inc/local.inc.php:70 
1.1217 14684376 6. Composer\Autoload\ClassLoader->loadClass() /var/www/1.11.chamilo.org/www/main/inc/local.inc.php:70 
1.1218 14684528 7. Composer\Autoload\includeFile() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:301 
1.1219 14688848 8. include('/var/www/1.11.chamilo.org/www/src/Chamilo/UserBundle/Entity/Manager/UserManager.php') /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:412 
1.1219 14689160 9. spl_autoload_call() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:14 
1.1219 14689216 10. Composer\Autoload\ClassLoader->loadClass() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:14 
1.1220 14689368 11. Composer\Autoload\includeFile() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:301 
1.1225 14726080 12. include('/var/www/1.11.chamilo.org/www/vendor/sonata-project/user-bundle/Entity/UserManager.php') /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:412 
1.1402 14827360 13. spl_autoload_call() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:26 
1.1402 14827424 14. Composer\Autoload\ClassLoader->loadClass() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:26 
1.1404 14827584 15. Composer\Autoload\includeFile() /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:301 
1.1405 14832496 16. include('/var/www/1.11.chamilo.org/www/vendor/sonata-project/user-bundle/Model/UserManagerInterface.php') /var/www/1.11.chamilo.org/www/vendor/composer/ClassLoader.php:412

**Comment by jloguercio** [comment]
o.O

**Comment by ywarnier** [comment]
Fixed after a composer clear-cache + composer update...

**Comment by jmontoyaa** [comment]
Please use less stressful titles. :scream:

**Comment by ywarnier** [comment]
I have difficulties bearing with the errors caused by late changes in a beta (almost RC) version :smile:
