### ISSUE TITLE
El profesor no puede corregir ejercicios

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1410]
Hemos observado que en ejercicios, cuando se configura el apartado de mostrar resultados a los estudiantes en modo examen o modo ejercicio, el profesor no puede acceder a corregir el ejercicio ni ver las respuestas.
Si se hace clic en el icono de corregir, la pantalla que aparece solo muestra el resultado, sin opción de  ver respuestas, calificar o añadir comentarios.
Entiendo que este no debería ser un comportamiento normal, pues cuando el ejercicio incluye preguntas abiertas es necesario que el profesor las evalúe.

Lo hemos probado en diferentes instalaciones de la versión 1.10, y también en la 1.11 (podeis probar en el curso: https://1.11.chamilo.org/courses/TEST1/index.php )

**Comment by ywarnier** [comment]
Hola equipo de @nosolored, sí, hemos recibido una serie de reportes justo la semana anterior y esta semana sobre el mismo problema. Vamos a investigar lo que está pasando.

**Comment by fergimon** [comment]
Cordial Saludo

No se si esto te ayuda la única forma de que corregir los exámenes es que  en la configuración le des esta opción  
Mostrar la nota a cada intento, mostrar las respuestas correctas solo en el último intento solo funciona si hay un límite de intentos.

**Comment by nosolored** [comment]
Hola,
Hemos encontrado una solución provisional, que a nosotros nos funciona:
En /main/exercice/exercise_show.php en la línea 204 

     $result_disabled = $track_exercise_info['results_disabled'];

cambiar por:

if (!(api_is_platform_admin() || api_is_course_admin() || api_is_course_coach()) ) {
     $result_disabled = $track_exercise_info['results_disabled'];
 }else{
  $result_disabled = 0;
 }

**Comment by ywarnier** [comment]
Somehow related (not the same, but related): https://support.chamilo.org/issues/8428

**Comment by jmontoyaa** [comment]
I think I already fixed that one. The course in the description doesn't exist.
