### ISSUE TITLE
Bug Versión 1.10.6 y 1.10.8  chamilo no se puede discutir los wiki

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1411]
Saludos

Me han reportado los docentes que los estudiantes no les permite discutir  las paginas de  wiki  que ha subido a la plataforma,revisando esto lo he probado en las siguiente paginas de pruebas con el curso Colombia  y no ha  funcionado 
![mensaje al estudiante](https://cloud.githubusercontent.com/assets/20644209/18690086/11a395ec-7f52-11e6-8b33-ef06f4e83711.JPG)

https://1.11.chamilo.org
https://1.10.chamilo.org

**Comment by jmontoyaa** [comment]
Como profesor es necesario de desbloquear la página del wiki (ícono candado abierto).
Acabo de enviar una correción para que la opción de "discutir" sea activado por defecto.

**Comment by fergimon** [comment]
Saludos
Gracias por responder, se que actualizaste el código en la 1.11 y esta bien, realice la prueba remplazando los archivos en la versión 1.10 y al crear una pagina  y al dar guardar  el se queda en la misma pagina
