### ISSUE TITLE
Chamilo Versión 1.10.6 y 1.10.8 Auditorias borrado de ejercicios

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1414]
Cordial saludo,

Es posible que en el menú Administración/Estadísticas/Actividades_importantes o por base de datos  se pueda llevar la información de quien borra un ejercicio de parte de profesores, alumnos en cursos principales o sesiones.

Gracias.

**Comment by ywarnier** [comment]
Hola @fergimon, esta información, para los recursos de los cursos, se guarda (ya) en Curso X > Informes > 4to icono (reporte sobre recursos)
