### ISSUE TITLE
Bug Versión 1.10.6 y 1.10.8 Ejercicios Explota la base de datos

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1415]
Cordial saludo,

Cada que se coloca un ejercicio en línea a mas de 40 estudiantes usando sesiones, se explota (se cae) la base de datos de Chamilo.

Cuál es la solución?

**Comment by ywarnier** [comment]
Hola,
En Github no vemos problemas vinculados con la eficiencia de servidores. Creo que ya quedó claro en anteriores oportunidades que su servidor no es óptimo. Gracias.
