### ISSUE TITLE
Surveys and dropdown

### ISSUE THREAD

**Issue by djoshy** [chamilo/chamilo-lms#1417]
Hi
When you create a dropdown question in surveys tool, results doesn't seem to be saved.
It's only with dropdown question.

Test version : Chamilo 1.10.8

**Comment by jloguercio** [comment]
Tested in 1.10.chamilo.org (colombia course, "cry cry" survey, admin/admin user)

https://1.10.chamilo.org/main/survey/preview.php?survey_id=3&show=0

![captura de pantalla de 2016-10-09 23-44-22](https://cloud.githubusercontent.com/assets/12191804/19227095/7cc61fb6-8e7a-11e6-8fe3-98061f68b6b6.png)

Cant reproduce the error, can you provide more info?

Regards

**Comment by jloguercio** [comment]
Confirmed in 1.10.chamilo.org

**Comment by jloguercio** [comment]
After a few attempts
![captura de pantalla de 2016-10-09 23-49-13](https://cloud.githubusercontent.com/assets/12191804/19227142/1d2831ce-8e7b-11e6-8fea-aae5508f1944.png)

**Comment by jloguercio** [comment]
Fixed here! https://github.com/chamilo/chamilo-lms/pull/1459

You need to test to a new survey after apply this fix

Regards

**Comment by djoshy** [comment]
Thank you José
the fix seems to solve the problem.

**Comment by ywarnier** [comment]
Thanks for reviewing @djoshy
