### ISSUE TITLE
Many users in a course

### ISSUE THREAD

**Issue by djoshy** [chamilo/chamilo-lms#1419]
Hi
I have a class with about 28,000 registered users. When I associate this class to a course and return to "users" tool, it can't display the first 20 users.

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 94 bytes) in /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 108

**Comment by jmontoyaa** [comment]
What's the URL with the error?

**Comment by djoshy** [comment]
Hi Julio

it's 
http://myserver/chamilo/main/user/user.php?cidReq=YYYY&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by ywarnier** [comment]
Hi @djoshy, while your bug report is legitimate, I would suggest for now that you increase the amount of memory. Dealing with a 28,000 users class with only 128MB of RAM allowed for PHP should be OK, but this is a new case for us...

**Comment by ywarnier** [comment]
@djoshy any information you could share on the context of this 28000 users' class is an interesting use case to me. If you want to extend on that privately, you can write to me at ywarnier_at-chamilo.org

**Comment by ywarnier** [comment]
I'm unassigning this from our direct 1.11.0 objective, because it's more like an improvement than a big bug (although I do acknowledge that we shouldn't use that much memory to show 20 users)

**Comment by ywarnier** [comment]
This is not immediately related and will probably not solve the lack of memory issue (although it might have a considerable impact), but commit d4d819b647cae68 might give you some help there. You will have to adapt it to your version of Chamilo, though.

**Comment by jmontoyaa** [comment]
I couldn't reproduce the error. 1.11.x.
