### ISSUE TITLE
Adjuntos en anuncios en 1.10.8

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1420]
Hola,

En support hace ya algún tiempo abrimos una tarea con este asunto (https://support.chamilo.org/issues/8154)

Se arregló todo en la 1.11 pero acabo de comprobar que en la 1.10.8 no está funcionando el envío de adjuntos en anuncios.

Se arregla con esta corrección que hicísteis en la 1.11: https://github.com/chamilo/chamilo-lms/commit/308ab6fff5042f70d7eafb7fdaf4988bd4c91c89

Pero lo comento para que lo tengáis en cuenta.

Gracias. Un saludo.
Laura Guirao

**Comment by ywarnier** [comment]
Changes reviewed and accepted
