### ISSUE TITLE
In image uploader (ckeditor) in a course, hidden folders should be visible to teacher

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1425]
As a teacher:
* create a course
* create a hidden "images" folder
* go to course homepage and edit introduction
* select image upload
* select the course folder
* the "images" folder is not visible

**Comment by ywarnier** [comment]
@jmontoyaa I'm assigning this to you because I think you worked recently on elfinder, but let me know if it is a lot of work for you, and I'll reassign.

**Comment by ywarnier** [comment]
This related to https://github.com/chamilo/chamilo-lms/commit/c6c3215b10ac1609d44fc2a75f1a7c188211e68f

**Comment by jmontoyaa** [comment]
If you use a "invisible" image in a public space students won't see it.

**Comment by ywarnier** [comment]
Nothing to do with student here :-)
Digo que cuando el *profesor* abre elfinder, no puede ver las carpetas invisibles, y esto impide que haga uso de su contenido. El profesor siempre debería ver las carpetas invisibles de su propio curso, pues es el quien define si una carpeta es visible o invisible...

**Comment by jmontoyaa** [comment]
Haré el cambio, pero después habrán reportes que "la imagen X no está visible para los estudiantes".

**Comment by ywarnier** [comment]
Seguro que habrán reportes así, pero por ahora el problema principal es que si una imagen es visible pero está dentro de una carpeta invisible, no se puede acceder... Pero tienes razón, habrán reportes de que no se ven las imágenes. Voy a pensar en algo para que podamos hacerlo explícito. Gracias.
