### ISSUE TITLE
&lt; and &gt; get unescaped in intro code

### ISSUE THREAD

**Issue by moy** [chamilo/chamilo-lms#1433]
When setting the intro of a course, using `&lt;` and `&gt;` do not always work. In some situation, Chamilo unescapes them.

Examples (all entered in source forme, not the WYSIWYG editor):

```
vector&lt;int&gt; x
```

=> ends up as `vector<int>` in the HTML of the page, the `<int>` part is eaten by the browser, the user sees `vector x`

Adding a space after `&lt;`:
```
vector&lt; int&gt; x
```

Renders as `vector< int> x`, as expected.

One can double-escape the code to get the correct result:

```
vector&amp;lt;int&amp;gt; x
```

=> renders as `vector<int> x`.

**Comment by jmontoyaa** [comment]
Should be fixed now

**Comment by moy** [comment]
On 1.11.chamilo.org, the bug is partly fixed only:

If I enter `vector&lt;int&gt; x` and save, I do get `vector<int>` as expected, but if I click edit again, then the field contains this:

```
<p>vector<int> x </int></p>
```

**Comment by jmontoyaa** [comment]
Should be fixed now.

**Comment by moy** [comment]
Confirm, thanks.
