### ISSUE TITLE
Bug Chamilo 1.10.8 video chat

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1435]
Hay una errata en el archivo main/inc/lib/javascript/chat/video.php

En la línea 37, la ruta que aparece es web/assets/SimpleWebRTC/latest.js
Y debe ser: web/assets/simpleWebRTC/latest.js  (la s es minúscula)

Con la ruta correcta el video chat vuelve a funcionar.

En Chamilo 1.11 está corregido

**Comment by jloguercio** [comment]
Corregido aquí : https://github.com/chamilo/chamilo-lms/pull/1437

**Comment by ywarnier** [comment]
@jloguercio siempre deja que alguien más valide antes de cerrar porfa.

**Comment by ywarnier** [comment]
OK, cambio revisado y validado
