### ISSUE TITLE
I can't go into course in 1.10.8

### ISSUE THREAD

**Issue by sa-adebayo** [chamilo/chamilo-lms#1440]
### Expected behavior / Resultado esperado / Résultat attendu
Should navigate me to course detail where I can upload course contents and other information
### Actual behavior / Resultado real / Résultat réel
It keep throwing errors
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Install Chamilo 1.10.8 on SmarterASP.net to see issue

**Comment by ywarnier** [comment]
Hi @sa-adebayo, thank you for reporting.
Please indicate *what* error it is throwing.
Please note that, for Chamilo to work, the web server needs to understand rewrite rules and be programmed to use them. With Apache, this is done through the .htaccess file. With Nginx, this can be done using the configuration settings suggested in the installation guide.

**Comment by sa-adebayo** [comment]
@ywarnier, thanks as this is an issue with hosting server. .htaccess rewrite wasn't working as expected. You can close the issue thread. Thanks.
