### ISSUE TITLE
Learning Path uses default template instead of custom template

### ISSUE THREAD

**Issue by agreenennov** [chamilo/chamilo-lms#1441]
I've created a new template directory in main/template and specified its name in main/inc/lib/template.lib.php as instructed.

Any changes I make work fine apart from the learning path functionality. If I customise view.tpl in my custom template directory this is ignored, however if I customise view.tpl in the default directory the changes are reflected in the browser.

It seems that learning paths ignore custom templates - is this deliberate?

**Comment by jmontoyaa** [comment]
I just added a fix for 1.11.x

**Comment by agreenennov** [comment]
Excellent – thanks!



Andy



*From:* Julio [mailto:notifications@github.com]
*Sent:* 07 October 2016 12:48
*To:* chamilo/chamilo-lms <chamilo-lms@noreply.github.com>
*Cc:* agreenennov <agreen@ennov.com>; Author <author@noreply.github.com>
*Subject:* Re: [chamilo/chamilo-lms] Learning Path uses default template
instead of custom template (#1441)



I just added a fix for 1.11.x

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chamilo/chamilo-lms/issues/1441#issuecomment-252231960>,
or mute the thread

**Comment by agreenennov** [comment]
Hi Julio



Do you have any plans to stop using iframes in the learning paths?



As well as iframes being discouraged these days, I’m finding that there’s
no way to apply a css file.



I’m sure you have a good reason for using them though.



Thanks



Andy



*From:* Julio [mailto:notifications@github.com]
*Sent:* 07 October 2016 12:48
*To:* chamilo/chamilo-lms <chamilo-lms@noreply.github.com>
*Cc:* agreenennov <agreen@ennov.com>; Author <author@noreply.github.com>
*Subject:* Re: [chamilo/chamilo-lms] Learning Path uses default template
instead of custom template (#1441)



I just added a fix for 1.11.x

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/chamilo/chamilo-lms/issues/1441#issuecomment-252231960>,
or mute the thread

**Comment by ywarnier** [comment]
Hi @agreenennov, iframes are a necessary part of the SCORM support. There is no way to do without them (because of the possibility to have SCORM content load from another domain, that *has* to be supported by the LMS). Consider yourself lucky though... before iframes we used tables + iframes :-)

**Comment by agreenennov** [comment]
Thanks Yannick – makes sense!

**Comment by agreenennov** [comment]
Hi Yannick



Sorry to be super-annoying, but I just wondered if you might be able to
help with any of my un-answered support forum questions at all please? I
realise that you're not my personal support technician(!) but hoped you
might have a minute or two to share your expertise...



Cannot add test to assessment

https://chamilo.org/forum/viewtopic.php?f=52&t=10201



Applying CSS to Learning path content

https://chamilo.org/forum/viewtopic.php?f=52&t=10138



Any way to allow HR manager to create learners?

https://chamilo.org/forum/viewtopic.php?f=52&t=10134



To clarify, I'm now using version 1.9.10, as my sys admin has forced me to
switch over to this version.



Also, I notice that the forum has quite a lot of spam submissions - I'm not
sure whether you've seen these.



Thanks



Andy



*From:* Yannick Warnier [mailto:notifications@github.com]
*Sent:* 07 October 2016 18:29
*To:* chamilo/chamilo-lms <chamilo-lms@noreply.github.com>
*Cc:* agreenennov <agreen@ennov.com>; Mention <mention@noreply.github.com>
*Subject:* Re: [chamilo/chamilo-lms] Learning Path uses default template
instead of custom template (#1441)



Hi @agreenennov <https://github.com/agreenennov>, iframes are a necessary
part of the SCORM support. There is no way to do without them (because of
the possibility to have SCORM content load from another domain, that *has*
to be supported by the LMS). Consider yourself lucky though... before
iframes we used tables + iframes :-)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chamilo/chamilo-lms/issues/1441#issuecomment-252312346>,
or mute the thread

**Comment by ywarnier** [comment]
Hi @agreenennov, sorry, I only go to the forum when I'm done attending the customers that help sustain the development efforts of Chamilo (we couldn't do it without them). I will visit them and answer unanswered posts eventually, but can't do it for the next 2 weeks, that's certain (busy enough preparing the release of 1.11.4). Version 1.9 is not supported anymore (we only support the 2 last major versions at any given time, which now means 1.10 and 1.11). Maybe your sysadmin forces you to use 1.9 because he didn't read the installation manual in order to install 1.11? (that certainly can help)

**Comment by agreenennov** [comment]
Hi Yannick



Thanks for your reply – no worries, I understand what you’re saying.



Andy



*From:* Yannick Warnier [mailto:notifications@github.com]
*Sent:* 22 March 2017 14:54
*To:* chamilo/chamilo-lms <chamilo-lms@noreply.github.com>
*Cc:* agreenennov <agreen@ennov.com>; Mention <mention@noreply.github.com>
*Subject:* Re: [chamilo/chamilo-lms] Learning Path uses default template
instead of custom template (#1441)



Hi @agreenennov <https://github.com/agreenennov>, sorry, I only go to the
forum when I'm done attending the customers that help sustain the
development efforts of Chamilo (we couldn't do it without them). I will
visit them and answer unanswered posts eventually, but can't do it for the
next 2 weeks, that's certain (busy enough preparing the release of 1.11.4).
Version 1.9 is not supported anymore (we only support the 2 last major
versions at any given time, which now means 1.10 and 1.11). Maybe your
sysadmin forces you to use 1.9 because he didn't read the installation
manual in order to install 1.11? (that certainly can help)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/chamilo/chamilo-lms/issues/1441#issuecomment-288424095>,
or mute the thread
