### ISSUE TITLE
Importacion de preguntas en formato Aiken falla

### ISSUE THREAD

**Issue by lopezsalexander** [chamilo/chamilo-lms#1444]
[EJEMPLO.txt](https://github.com/chamilo/chamilo-lms/files/517784/EJEMPLO.txt)
### Expected behavior / Resultado esperado / Résultat attendu

Las preguntas deberian cargar correctamente

### Actual behavior / Resultado real / Résultat réel

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ponderation' cannot be null in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array) #1 /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(165): Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/www/html/main/inc/lib/database.lib.php(399): Doctrine\DBAL\Statement->execute(Array) #3 /var/www/html/main/exercice/answer.class.php(636): Database::insert('c_quiz_answer', Array) #4 /var/www/html/main/exercice/export/aiken/aiken_import.inc.php(213): Answer->save() #5 /var/www/html/main/exercice/export/aiken/aiken_import.inc.php(344): aiken_import_exercise(false) #6 /var/www/html/main/exercice/aiken.php(36): aiken_import_file(Array) #7 {main} Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'ponderation' cann in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 112

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Carga de Documento Aiken (Archivo TXT) Doy de peso total 100
![firefox_2016-10-08_11-00-41](https://cloud.githubusercontent.com/assets/5233755/19214349/8209135a-8d46-11e6-8e79-79efa6a47669.png)

**Comment by ywarnier** [comment]
Hola @lopezsalexander
En https://1.11.chamilo.org, puedo importar tu archivo sin problema. Parece que este problema se limita a la versión 1.10.8, la cual no estamos manteniendo salvo a través de soporte a clientes. La versión 1.11.0 debería ser publicada dentro de unos días, con un procedimiento de actualización sencillo. Esperamos sea suficiente para solucionar el problema con el cual te enfrentas ahora. Si sigue así con la versión 1.11, entonces seguro se trata de una diferencia de configuración y lo revisaremos contigo post-1.11.
