### ISSUE TITLE
Wiki: all pages - "Delete wiki" triggers SQL error

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1445]
### Expected behavior / Resultado esperado / Résultat attendu
In a course wiki, when I click on "All pages", then on the prominent red cross to delete the whole wiki and confirm, it should give me a confirmation message and delete the corresponding wiki's pages.

### Actual behavior / Resultado real / Résultat réel
At the moment it *does* delete the wiki pages but an error message appears.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
As an admin:
- create a course
- update the wiki
- create an additional page
- go to the "all pages" list
- click the "Delete wiki" red cross and confirm

**Comment by jmontoyaa** [comment]
All reports should be like this :)

**Comment by ywarnier** [comment]
I've added a template so all people actually get the same structure, so we have more chances of getting all reports like this :-)
Check the .github/ directory!

**Comment by ywarnier** [comment]
Checked. Thanks.
