### ISSUE TITLE
announcement creation:  user search will only work once

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1447]
Using the search field when selecting users for an announcement will work 1 time. When a user has been selected the select box (id=users-f) is not reset and keeps showing the result of the last search.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
The extreme case (chamilo 1.10): type a Q in the search field. If no user has a Q in the name, the select box will be cleared and there is no way to select additional users for the announcement.
Still a bug in 1.11: after double-clicking the name or adding the name to the box on the right, the select box is still showing the results of the last search. Typing another search letter will not give new results.

Extra issue: when you desperately hit ENTER/RETURN, an announcement is created. This key should be ignored to prevent accidental sending of announcements.

**Comment by jloguercio** [comment]
Confirmed and fixed here : https://github.com/chamilo/chamilo-lms/pull/1453

**Comment by ywarnier** [comment]
Looks good to me. Now it allows you to add the same user several times, but that's a minor issue to me.

**Comment by jderriks** [comment]
Now it works almost perfectly in 1.11 but  hitting ENTER after typing a word in the search field or subject field should NOT create the announcement without at least asking for confirmation. Too many people hit enter at the end of a line.
