### ISSUE TITLE
Delete unused branchs in repo

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1451]
The branch list start to being a bit messy. Some clean up will be fine.

**Comment by ywarnier** [comment]
I'll do that once we release 1.11. I'll move some of them to beeznest's repo and remove others. No problem.

**Comment by ywarnier** [comment]
Already deleted 3. Can I delete the "experimental" branch? (now that we'll start working on master, it doesn't seem to be very relevant anymore...)

**Comment by jmontoyaa** [comment]
I have some stuff there. I prefer to keep it until I use master as daily basis.
