### ISSUE TITLE
Merge BBB admin list changes from 1.10.x

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1460]
I have managed to merge until 7fd4780 on https://github.com/chamilo/chamilo-lms/commits/1.10.x but the next commit is conflicting with changes that Julio did to support multi-urls.
Could you finish merging your (and my) changes?

**Comment by AngelFQC** [comment]
Merged!

**Comment by ywarnier** [comment]
Looks good to me!
