### ISSUE TITLE
Session images are not cropped by cropper

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1465]
### Expected behavior / Resultado esperado / Résultat attendu
When I upload an image in the session creation screen and I crop it, it should generate a cropped image.

### Actual behavior / Resultado real / Résultat réel
The cropper is there, but the final image isn't cropped when submitting the form.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* go to the session creation form
* add an image
* crop it
* see the image: not cropped!

**Comment by jloguercio** [comment]
Fixed here :) https://github.com/chamilo/chamilo-lms/pull/1466

**Comment by ywarnier** [comment]
Tested and approved
