### ISSUE TITLE
Where is plugin.js for ckeditor plugin scayt

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#1469]
In 1.11 release oct 14, le fichier de config de scayt ne semble plus effectif (plugin.js) Je cherche où il est passé, pour mettre le plugin en autostart et en français par défault

**Comment by ywarnier** [comment]
Thanks for reporting this. I've added it back. Apparently it gets deleted when we Bower-update the Chamilo repo, so this will happen again in the future until it gets fixed at some other level (independent of Chamilo).
