### ISSUE TITLE
Problemas con el plugin de BBB en 1.10.8

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1470]
Comportamiento esperado:

Al actualizar Chamilo con los últimos cambios de la versión 1.10.8, aparecen varios problemas.
Según creo se ha mejorado la lista de sesiones de videoconferencia para poder filtrar las grabaciones, pero el cambio provoca otros errores.

Comportamiento real:

La lista de sesiones aparecen todas con enlace a grabación aunque no exista grabación. El enlace no lleva a nada, no se puede hacer click. Y estos enlaces aparecen incluso con la sala abierta.
Cuando existe grabación el enlace funciona correctamente.

Produce error en PHP al intentar acceder a la videoconferencia.

El error que produce es diferente en un servidor con PHP 5.4:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mibasededatos.plugin_bbb_room' doesn't exist' in /rutademichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91

Al que aparece en un servidor con PHP 7:
[Fri Oct 14 19:16:24 2016] [error] [client 79.148.105.119] PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /rutademichamilo/plugin/bbb/lib/bbb_api.php:77\nStack trace:\n#0 /rutademichamilo/plugin/bbb/lib/bbb_api.php(77): SimpleXMLElement->__construct('<html><head><ti...')\n#1 /rutademichamilo/plugin/bbb/lib/bbb_api.php(249): BigBlueButtonBN->_processXmlResponse('93.93.71.104/bi...')\n#2 /rutademichamilo/plugin/bbb/lib/bbb.lib.php(695): BigBlueButtonBN->endMeetingWithXmlResponseArray(Array)\n#3 /rutademichamilo/plugin/bbb/listing.php(80): bbb->endMeeting('1')\n#4 {main}\n  thrown in /rutademichamilo/plugin/bbb/lib/bbb_api.php on line 77

Cómo reproducir el error:

Acceder a la videoconferencia en un Chamilo actualizado a la 1.10.8 con los últimos cambios de Github y que tenga configurado el plugin.

Información adicional:

Hemos probado a desactivar y activar de nuevo el plugin, sin que cambie la situación.
El servidor de BBB funciona bien en otros Chamilos en los que lo usamos. La versión de BBB es la 0.91

En una demo de la 1.11 también actualizada funciona bien, aunque tras actualizar ha sido necesario desactivar y volver a activar el plugin.
Al hacer esto se borran todos los datos del plugin y hay que volver a configurar el servidor, desaparecen las sesiones anteriores y en los cursos hay que volver a marcar la opción de grabación en la configuración. El que desaparezcan las sesiones es un problema si se tratase de una plataforma en producción.
Por cierto, ¿la versión 1.11 va a requerir PHP 5.6 como mínimo?

Gracias.

**Comment by ywarnier** [comment]
Hola,

Chamilo 1.11.0 debería requerir PHP 5.4 como mínimo pero no lo hemos probado últimamente. No pienso que hayamos introducido dependencias estrictas para 5.5 o 5.6. Sin embargo, algunas de las librerías que usamos podrían haberlo hecho. Esperamos que no.

El mensaje de error indica que la tabla plugin_bbb_room no existe. Esta tabla debería ser creada cuando se desinstala y reinstala el plugin... (a mi me funciona). En todo caso, podeís crear la tabla a mano con las explicaciones en README.md que detallan los cambios de base de datos esperados con cada versión del plugin.

**Comment by jmontoyaa** [comment]
No sé que tengo que hacer aqui.  La tabla plugin_bbb_room debe ser agregado.

**Comment by ywarnier** [comment]
@nosolored para los plugins, no tenemos un sistema de migración todavía. Por lo tanto y por ahora, estamos añadiendo, dentro de README.md *del plugin mismo* los queries que hay que ejecutar a mano para actualizarlo.
Esperamos tener esto más automatizado para 2.0, pero por mientras es lo que hay.

**Comment by ywarnier** [comment]
Puedo cerrar este issue?

**Comment by nosolored** [comment]
Si, gracias

**Comment by dpsmwebs** [comment]
Hola Amigos, se que esto esta cerrado hace tiempo, pero es que he estado buscando ayuda y ya no se que mas hacer, he instalado la ultima version de chamilo, tengo bbb en un server externo tod bien instalado y testeado a la perfeccion, cuando intento hacer la llamada a video conferencia no muestra nada, solo que ha sido creada, pero al poner cerrar me envia este error...
Fatal error: Uncaught exception 'Exception' with message 'String could not be parsed as XML' in /hermes/.../chamilo-lms/plugin/bbb/lib/bbb_api.php:77 Stack trace: #0 /hermes.../chamilo-lms/plugin/bbb/lib/bbb_api.php(77): SimpleXMLElement->__construct('_processXmlResponse('ethulogin.com/b...') #2 /hermes/.../chamilo-lms/plugin/bbb/lib/bbb.lib.php(883): BigBlueButtonBN->endMeetingWithXmlResponseArray(Array) #3 /hermes/.../chamilo-lms/plugin/bbb/listing.php(81): bbb->endMeeting('1') #4 {main} thrown in /hermes/.../chamilo-lms/plugin/bbb/lib/bbb_api.php on line 77...
the true is that I dont know what to do :( please help
