### ISSUE TITLE
Add createdAt/updatedAt in course and others entities

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1474]
In order to know the when it was created or updated

**Comment by jloguercio** [comment]
:+1:

**Comment by ywarnier** [comment]
I agree. At the moment the tracking data for that is stored in track_e_default, but it would be nice to have at least the info for the creation and the last update in the table itself, yes.

**Comment by ywarnier** [comment]
Courses and resources are now represented by nodes, which include creation/update/author
