### ISSUE TITLE
Bug en Chamilo 1.10.x (proviene de actualizar desde 1.9.x)

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1475]
El profesor no puede insertar comentarios al corregir una tarea, y devuelve una pantalla en blanco y error en PHP.
El problema que hemos encontrado es que en la tabla c_student_publication_comment el campo iid no estaba configurado como auto incremental.
El primer comentario permite insertarlo pero se genera con iid=0 e id=NULL, por lo que un segundo comentario devuelve error de clave duplicada.
Se soluciona asignando a ese campo la configuración de auto-incremental, aunque habría que tenerlo en cuenta en las actualizaciones para que revise esto y lo corrija.

El error nos ha ocurrido en varias instalaciones de Chamilo 1.10.8, todas ellas habían sido actualizadas desde Chamilo 1.9.10.2 a la 1.10.6 y luego a la 1.10.8

En una instalación limpia de Chamilo 1.11 no se produce este error.

Pasos para reproducir el error:
En una instalación de Chamilo 1.10.8 proveniente de actualizar desde 1.9.10.2:
- Crear una tarea
- Responder a la tarea como alumno
- Acceder de nuevo como profesor, corregir la tarea y añadir un comentario
  Si no existen más tareas con comentarios en el aula, habrá que volver a realizar la operación para que devuelva el error, ya que se produce cuando hay al menos 1 comentario insertado.

**Comment by AngelFQC** [comment]
El proceso de migración ha sido corregido en 1.10.x y 1.11.x
