### ISSUE TITLE
Site crashes when adding demo content to new course.

### ISSUE THREAD

**Issue by JurgenG** [chamilo/chamilo-lms#1477]
### Expected behavior / Resultado esperado / Résultat attendu
A course with demo content gets created.
### Actual behavior / Resultado real / Résultat réel
Error message:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list'' in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71 PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list' in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 91 Call Stack: 0.0010 330920 1. {main}() /var/www/1.11.chamilo.org/www/main/admin/course_add.php:0 0.2911 10565504 2. CourseManager::create_course() /var/www/1.11.chamilo.org/www/main/admin/course_add.php:211 0.3102 11413296 3. CourseManager::fillCourse() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:103 0.3139 11417096 4. AddCourse::fill_db_course() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:6180 1.5903 16441352 5. Exercise->save() /var/www/1.11.chamilo.org/www/main/inc/lib/add_course.lib.inc.php:1017 1.5904 16444568 6. Database::insert() /var/www/1.11.chamilo.org/www/main/exercise/exercise.class.php:1675 1.5904 16451896 7. Doctrine\DBAL\Statement->execute() /var/www/1.11.chamilo.org/www/main/inc/lib/database.lib.php:421 1.5904 16451944 8. Doctrine\DBAL\Driver\PDOStatement->execute() /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:168 1.5904 16451992 9. PDOStatement->execute() /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list' in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 93 Call Stack: 0.0010 330920 1. {main}() /var/www/1.11.chamilo.org/www/main/admin/course_add.php:0 0.2911 10565504 2. CourseManager::create_course() /var/www/1.11.chamilo.org/www/main/admin/course_add.php:211 0.3102 11413296 3. CourseManager::fillCourse() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:103 0.3139 11417096 4. AddCourse::fill_db_course() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:6180 1.5903 16441352 5. Exercise->save() /var/www/1.11.chamilo.org/www/main/inc/lib/add_course.lib.inc.php:1017 1.5904 16444568 6. Database::insert() /var/www/1.11.chamilo.org/www/main/exercise/exercise.class.php:1675 1.5904 16451896 7. Doctrine\DBAL\Statement->execute() /var/www/1.11.chamilo.org/www/main/inc/lib/database.lib.php:421 1.5904 16451944 8. Doctrine\DBAL\Driver\PDOStatement->execute() /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:168 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'INSERT INTO c_quiz (c_id,start_time,end_time,title,description,sound,type,random,random_answers,active,results_disabled,max_attempt,feedback_type,expired_time,session_id,review_answers,random_by_category,text_when_finished,display_category_name,pass_percentage,save_correct_answers,propagate_neg,hide_question_title) VALUES (:c_id, :start_time, :end_time, :title, :description, :sound, :type, :random, :random_answers, :active, :results_disabled, :max_attempt, :feedback_type, :expired_time, :session_id, :review_answers, :random_by_category, :text_when_finished, :display_category_name, :pass_percentage, :save_correct_answers, :propagate_neg, :hide_question_title)' with params ["38", null, null, "Sample test", "\n \n
\n \n <\/td>\n 	Irony<\/td><\/tr>\n <\/table>", "", 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, "", 0, 0, 0, 0, 0]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list' in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71 Call Stack: 0.0010 330920 1. {main}() /var/www/1.11.chamilo.org/www/main/admin/course_add.php:0 0.2911 10565504 2. CourseManager::create_course() /var/www/1.11.chamilo.org/www/main/admin/course_add.php:211 0.3102 11413296 3. CourseManager::fillCourse() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:103 0.3139 11417096 4. AddCourse::fill_db_course() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:6180 1.5903 16441352 5. Exercise->save() /var/www/1.11.chamilo.org/www/main/inc/lib/add_course.lib.inc.php:1017 1.5904 16444568 6. Database::insert() /var/www/1.11.chamilo.org/www/main/exercise/exercise.class.php:1675 1.5904 16451896 7. Doctrine\DBAL\Statement->execute() /var/www/1.11.chamilo.org/www/main/inc/lib/database.lib.php:421 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1. Go to: https://1.11.chamilo.org/main/admin/course_add.php
2. Give a title to the course
3. Check the option "Fill with demo content"
4. Click "Create a course" button at the bottom
5. Wait a few seconds...

![error_message_chamilo1 11](https://cloud.githubusercontent.com/assets/691954/19704401/e121ac2a-9b07-11e6-856f-06bd124feb21.png)

**Comment by jmontoyaa** [comment]
This bug was already resolved. I'm fixing it in 1.11.chamilo.org
DB change:

`ALTER TABLE c_quiz ADD hide_question_title TINYINT(1) DEFAULT NULL;`
