### ISSUE TITLE
Error Chamilo 1.10.8 - crear modelos de evaluación

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1478]
No es posible crear modelos de evaluación porque los campos salen descolocados y no aparecen los botones.
Para reproducir el error: Acceder a la administración > cursos > Modelos de evaluación y pulsar el botón de crear nuevo modelo.
Se puede comprobar directamente aquí: https://1.10.chamilo.org/main/admin/grade_models.php?action=add

Por otra parte, en Chamilo 1.11 esto está corregido pero los campos no aparecen etiquetados con lo que no es nada intuitivo lo que hay que poner en cada campo.

**Comment by jmontoyaa** [comment]
Acabo de agregar una correción para ello en 1.10.x y en 1.11.x

**Comment by jmontoyaa** [comment]
https://github.com/chamilo/chamilo-lms/commit/d4df8bb93f42d330173dc96cc043a2fcf618bc71

**Comment by nosolored** [comment]
Probado en https://1.10.chamilo.org
Funciona correctamente
Gracias Julio
