### ISSUE TITLE
Chamilo 1.11 - Error PHP al crear un curso o crear un ejercicio

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1479]
Al crear un curso con datos de ejemplo aparece una página de error en el navegador, y se genera el siguiente error de PHP:

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list' in /rutachamilo/web/htdocs/111/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /rutachamilo/web/htdocs/111/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /rutachamilo/web/htdocs/111/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /rutachamilo/web/htdocs/111/main/inc/lib/database.lib.php(421): Doctrine\\DBAL\\Statement->execute(Array)\n#3 /rutachamilo/web/htdocs/111/main/exercise/exercise.class.php(1675): Database::insert('c_quiz', Array)\n#4 /rutachamilo/web/htdocs/111/main/inc/lib/add_course.lib.inc.php(1017): Exercise->save()\n#5 /rutachamilo/web/htdocs/111/main/inc/lib/course.lib.php(6178): AddCourse::fill_db_course(3, 'PRUEBA3', 'spanish' in /rutachamilo/web/htdocs/111/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71, referer: http://urlchamilo/main/create_course/add_course.php

El curso se crea, pero no se añaden los contenidos, ni ejercicios, ni foros..
Si se intenta crear un ejercicio manualmente devuelve el mismo error

La instalación donde lo hemos probado ha sido actualizada hoy mismo con lo último de GitHub

**Comment by jmontoyaa** [comment]
Ya está corregido ver https://github.com/chamilo/chamilo-lms/issues/1477

**Comment by jmontoyaa** [comment]
Ver: #1473

**Comment by nosolored** [comment]
Gracias Julio, vamos a probarlo.

**Comment by jmontoyaa** [comment]
Si hacen pruebas de migración revisar que la tabla "version" no exista.
