### ISSUE TITLE
Migration from 1.10.8 to 1.11.0

### ISSUE THREAD

**Issue by hichamon306** [chamilo/chamilo-lms#1480]
The migration took place successfully, but when I log in I have a blank page, the following log:
[error] 24828#24828: *556 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Property Chamilo\UserBundle\Entity\User::$chatcallUserId does not exist in /var/www/xxx.xxx/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80
Stack trace:
# 0          /vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php(80): ReflectionProperty->__construct('Chamilo\UserBun...', 'chatcallUserId')
# 1 /var/www/xxxx.xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php(964): Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getAccessibleProperty('Chamilo\UserBun...', 'chatcallUserId')
# 2 /var/www/xxxx.xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(721): Doctrine\ORM\Mapping\ClassMetadataInfo->wakeupReflection(Object(Doctrine\Common\Persistence\Mapping\RuntimeReflectionService))
# 3 /var/www/xxxx.xxx/vendor/doctrine/common/lib/Doctrine/Common/" while reading response header from upstream, client: [IP], server: xxx.xxx, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "xxx.xx", referrer: "http://xxx.xx/"

**Comment by jmontoyaa** [comment]
@AngelFQC 

There are calls of chatcallDate, and chatcalluserid here:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/CourseChatUtils.php#L356-L360

But the fields where removed here:

https://github.com/chamilo/chamilo-lms/commit/f64e6b89f7222cf3d94da127ac29d7ffac315187

**Comment by AngelFQC** [comment]
Fixes sent

**Comment by hichamon306** [comment]
Thank you  😊

**Comment by hichamon306** [comment]
After modifiying the 3 files, still have the same problem 
[error] 21446#21446: *168366 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Property Chamilo\UserBundle\Entity\User::$chatcallUserId does not exist in /var/www/xxxx.xx/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80

**Comment by ywarnier** [comment]
Mmm... you would have to launch a "composer install" to fix this. I suggest you wait for the release of 1.11.2 (I should have released it on Friday but we waited for a few days to confirm other fixes). This is coming out this week.

**Comment by jmontoyaa** [comment]
you can also try cleaning your doctrine metadata with:

`php bin/doctrine.php orm:clear-cache:metadata`

Or just clean the app/cache folder
