### ISSUE TITLE
1.11 : mail sent when new user created : Bug

### ISSUE THREAD

**Issue by damienlaborie** [chamilo/chamilo-lms#1485]
### Actual behavior / Resultado real / Résultat réel
L'adresse de Chamilo est :
Notice: Array to string conversion in C:\xampp\htdocs\lms\vendor\twig\twig\lib\Twig\Environment.php(413) : eval()'d code on line 56
Array
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create new user
choose to send e-mail
hit the ADD button

**Comment by jmontoyaa** [comment]
This works for me. I also tested in https://1.11.chamilo.org/

**Comment by damienlaborie** [comment]
Thanks Julio ...
hum hum... may be due to the french language ?

**Comment by jmontoyaa** [comment]
Works for me. Please try to reproduce it in 1.11.  maybe the error was already fixed.
Try also cleaning the cache

**Comment by ywarnier** [comment]
@damienlaborie ...or maybe you have defined a weird array in configuration.php for the portal url variable?

**Comment by damienlaborie** [comment]
I had disabled all languages except french... now I have english visible + french by default : It works fine
