### ISSUE TITLE
1.11 : statistics / last access : down

### ISSUE THREAD

**Issue by damienlaborie** [chamilo/chamilo-lms#1486]
NB: I use the multi urls fucntionnality : error on all portals 

### Expected behavior / Resultado esperado / Résultat attendu
show stats
### Actual behavior / Resultado real / Résultat réel
![image](https://cloud.githubusercontent.com/assets/23164751/19852880/4603ba2c-9f66-11e6-844a-0f4ea652ad8e.png)

Dernier accès >= 60 jours

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'c_id' in order clause is ambiguous' in C:\xampp\htdocs\lms\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:104 Stack trace: #0 C:\xampp\htdocs\lms\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(104): PDO->query('SELECT * FROM t...') #1 C:\xampp\htdocs\lms\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('SELECT * FROM t...') #2 C:\xampp\htdocs\lms\main\inc\lib\database.lib.php(350): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM t...') #3 C:\xampp\htdocs\lms\main\inc\lib\statistics.lib.php(806): Database::query('SELECT * FROM t...') #4 C:\xampp\htdocs\lms\main\admin\statistics\index.php(100): Statistics::printCourseLastVisit() #5 {main} Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'c_id' in order clause is ambiguous' in C:\xampp\ in C:\xampp\htdocs\lms\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 76

**Comment by jmontoyaa** [comment]
Should be fixed now.+

**Comment by damienlaborie** [comment]
yes, works fine !

thanks.
