### ISSUE TITLE
Error en la actualización de 1.10.8 a 1.11 

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1487]
cordial saludo

Buenos días actualizando la versión 1.11 desde la 1.10.8   me sale este mensaje en el paso 2  como lo muestra en la imagen, 
![error al actualizar](https://cloud.githubusercontent.com/assets/20644209/19861739/b8c5efa4-9f5b-11e6-8838-73db8992f170.JPG)

Los pasos que realizo es remplazando la versión  nueva en la vieja

**Comment by ywarnier** [comment]
Hola @fergimon, sí, en realidad no es un error sino una advertencia. Hay que hacer lo que dice el mensaje (en español bastante específico) para poder seguir :-)
