### ISSUE TITLE
social/home.php layout 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1489]
I found some problems in the layout see the images:

How it should be:

![selection_014](https://cloud.githubusercontent.com/assets/158935/19886086/15c9fcb0-a022-11e6-8131-5c146bb04865.png)

Bad:

![selection_013](https://cloud.githubusercontent.com/assets/158935/19886088/15cf2276-a022-11e6-9dc2-9412f12552e7.png)

Bad: And "Role" should be changed with "Profile" or "User"

![selection_015](https://cloud.githubusercontent.com/assets/158935/19886173/6dd93344-a022-11e6-981c-3bca3d422185.png)

**Comment by ywarnier** [comment]
I can't see what's bad.

**Comment by jmontoyaa** [comment]
Div alignments.

**Comment by jmontoyaa** [comment]
Fixed

**Comment by ywarnier** [comment]
Looks good, indeed.
