### ISSUE TITLE
Course catalog useless button

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1490]
When I'm in the course catalog there's this **button** (see image), when clicking nothing happens.
It should be removed it or just put the icon somewhere else and don't use a button.

![selection_016](https://cloud.githubusercontent.com/assets/158935/19887133/03ccd8ca-a027-11e6-8724-90f807746626.png)

**Comment by ywarnier** [comment]
If I remember well, it means that you are the teacher of this course. I'm releasing 1.11.2 now, so I'll leave it there for now.

**Comment by jderriks** [comment]
Please also look at the green "subscribe" button in the course catalog. 
The subscibe icon is the same as the "logout" icon and students compain that "logout" is not the button you would click when you want to ENTER a course. 
That makes sense.

**Comment by AngelFQC** [comment]
Convensado con @aragonc, él va a mover el botón

**Comment by jmontoyaa** [comment]
Nice!!   :smile: :sunglasses:

**Comment by ywarnier** [comment]
@aragonc esta tarea te está asignada desde hace rato

**Comment by aragonc** [comment]
Listo revisado y corregido

**Comment by ywarnier** [comment]
https://github.com/chamilo/chamilo-lms/pull/1859
