### ISSUE TITLE
Course catalog, course with many teachers UI problem

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1491]
See this url:

https://1.11.chamilo.org/main/auth/courses.php?action=subscribe&category_code=ALL&hidden_links=&pageCurrent=1&pageLength=12&search_term=&search_course=1&sec_token=3b953a1a72f86add676e5cbcd9f6952c

See the image:
![screenshot from 2016-11-01 11-37-45](https://cloud.githubusercontent.com/assets/158935/19887360/51b79dd0-a028-11e6-9a7d-8615f80d86b1.png)

**Comment by ywarnier** [comment]
@aragonc y esta tb

**Comment by aragonc** [comment]
Se solución con mi PR anteriormente enviado... para el catalogo de cursos

![analisi](https://cloud.githubusercontent.com/assets/2940509/25446278/b6d1ea6c-2a76-11e7-99ad-c5fe8d388bce.png)

**Comment by jmontoyaa** [comment]
@aragonc Agregar referencia de ese PR con este issue.

**Comment by ywarnier** [comment]
https://github.com/chamilo/chamilo-lms/pull/1862
