### ISSUE TITLE
Bug versión 1.11  Informe detallado estudiantes 

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1492]
Cordial Saludo
 
Este bug se había reportado ya con el caso #8405 se arreglo un 90% revisando la versión 1.11 todavía existe  este bug.  el problema consiste en que cuando aparece la información  se borra los datos Total, Promedio, Cantidad como lo muestra la imagen 3

![imagen 1](https://cloud.githubusercontent.com/assets/20644209/19892533/4c49d6ac-a013-11e6-9516-ed4996d1e62e.JPG)
![imagen 2](https://cloud.githubusercontent.com/assets/20644209/19892534/4c4a0af0-a013-11e6-8673-c9d3fea936c8.JPG)
![imagen 3](https://cloud.githubusercontent.com/assets/20644209/19892532/4c49ce8c-a013-11e6-8178-4a8922f8ece7.JPG)

**Comment by ywarnier** [comment]
Gracias por reportar. He podido reproducir un problema similar pero no exactamente el mismo. Arreglé el problema que encontré (que no aparecía nada de datos al seleccionar un rango de fechas) y hice que aparecieran todos los datos más el gráfico. Creo que con esto debería haber dado con el problema mencionado.

**Comment by fergimon** [comment]
muchas gracias @ywarnier  esta 100% arreglado
