### ISSUE TITLE
Exercise quiz list layout

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1494]
Something seems broken in the question list see:

https://1.11.chamilo.org/main/exercise/admin.php?cidReq=D2DMATHS&id_session=0&gidReq=0&gradebook=0&origin=&newQuestion=yes&answerType=1

I just did a composer update. I tested with Chrome and i got the error, in Firefox it works well.

![selection_017](https://cloud.githubusercontent.com/assets/158935/19922418/d0ea1398-a0e2-11e6-825c-793131f169e7.png)

**Comment by AngelFQC** [comment]
I tested the URL in Chrome... and I can't see the error

**Comment by jmontoyaa** [comment]
I just checked with Opera and it's working fine. I'm having some errors like:
"Request was blocked by DevTools: "about:blank"."
But this must be the fact I'm using chrome beta.

Closing issue.
