### ISSUE TITLE
Error importing users from CSV file

### ISSUE THREAD

**Issue by alejomejia1** [chamilo/chamilo-lms#1496]
### Expected behavior / Resultado esperado / Résultat attendu

After import csv file, existing users on file must be created on Chamilo.

### Actual behavior / Resultado real / Résultat réel

csv file did not contain headers (File is unmodified after export it from other Chamilo -1.9.10- )
First two lines...

"49";"Acero Díaz";"Aura";"xxx@gmail.com";"auraacerodiaz";"platform";"5";"AURAACERODIAZ";"";"1";"1";"1";
"1";"Alejandro";"Mejia";"alejomejia1@gmail.com";"admin";"platform";"1";"ADMIN";"xxx";"1";"1";"1";

After click on import users from CSV, Chamillo  returns error

Error output on Chamilo in test mode:

Fatal error: Uncaught exception 'Ddeboer\DataImport\Exception\DuplicateHeadersException' with message 'File contains duplicate headers: 1, 1, ' in /var/www/html/chamilo111/vendor/ddeboer/data-import/src/Reader/CsvReader.php:345 Stack trace: #0 /var/www/html/chamilo111/vendor/ddeboer/data-import/src/Reader/CsvReader.php(186): Ddeboer\DataImport\Reader\CsvReader->readHeaderRow(0) #1 /var/www/html/chamilo111/main/inc/lib/import.lib.php(32): Ddeboer\DataImport\Reader\CsvReader->setHeaderRowNumber(0) #2 /var/www/html/chamilo111/main/inc/lib/import.lib.php(60): Import::csv_reader('/tmp/phpJKsmtE') #3 /var/www/html/chamilo111/main/admin/user_import.php(248): Import::csvToArray('/tmp/phpJKsmtE') #4 /var/www/html/chamilo111/main/admin/user_import.php(385): parse_csv_data('/tmp/phpJKsmtE') #5 {main} thrown in /var/www/html/chamilo111/vendor/ddeboer/data-import/src/Reader/CsvReader.php on line 345

If Chamilo is not in Test Mode, returns Error 500

Output in Developers Mode

**General**
Request URL:http://chamilo.aulal.com/main/admin/user_import.php
Request Method:POST
Status Code:200 OK
Remote Address:192.168.2.29:80
**Response Headers**
view source
Cache-Control:no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Cache-Control:public
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html; charset=UTF-8
Date:Fri, 04 Nov 2016 20:46:44 GMT
Expires:Thu, 19 Nov 1981 08:52:00 GMT
Pragma:no-cache
Server:nginx
Transfer-Encoding:chunked
**Request Headers**
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:es,es-419;q=0.8,en;q=0.6
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:14564
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryZeXllZGXiz7GyKEV
Cookie:ch_sid=cpkfkpkjm41mv387k994sdnqo2; defaultMyCourseView1=0
Host:chamilo.aulal.com
Origin:http://chamilo.aulal.com
Referer:http://chamilo.aulal.com/main/admin/user_import.php
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
**Request Payload**
------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="import_file"; filename="export_users_2016-07-19_08-40-48.csv"
Content-Type: text/csv

------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="file_type"

csv
------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="sendMail"

0
------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="submit"

------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="_qf__user_import"

------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="formSent"

1
------WebKitFormBoundaryZeXllZGXiz7GyKEV
Content-Disposition: form-data; name="MAX_FILE_SIZE"

134217728
------WebKitFormBoundaryZeXllZGXiz7GyKEV--

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. Export users from other chamilo version  (In this case Chamilo 1.9.10)
2. Open Administration - Import Users from CSV file
3. Click on import

**Comment by jmontoyaa** [comment]
You should check the example csv file in order to import the file correctly.
The csv file need to have headers.

https://1.11.chamilo.org/main/admin/example.csv
