### ISSUE TITLE
Upgrade from 1.10.8 to 1.11.2

### ISSUE THREAD

**Issue by hichamon306** [chamilo/chamilo-lms#1497]
I  upgrad chamilo from 1.10.8 to 1.11.2  using rsync command (rsync  -avz /path/to/chamilo1.11.2 /path/to/chamilo1.10.8 )  i follow instruction in /main/install/ everything ok right here, I delete content of app/cache/*  and I make www-data owner of directory  (chown -R www-data:www-data /path/to/chamilo1.11.2) ,when I go to web page (login page ) I fill form with my login and password  after submit I get blank page, here is log : 
2016/11/06 15:41:34 [error] 8027#8027: *5101 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ReflectionException: Property Chamilo\UserBundle\Entity\User::$chatcallUserId does not exist in /home/www/xxx.xx/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80

I launch  this command as recommended by @jmontoyaa  (php bin/doctrine.php orm:clear-cache:metadata)  but still have the same problem 

Here is my server Configuration: 
Ubuntu server 16.04 
Nginx  nginx/1.10.0
PHP 7.0.4
MySQL 5.7.12

**Comment by jmontoyaa** [comment]
the chatcallUserId error was already fixed. Try to use the latest code from the 1.11.x branch.

**Comment by jmontoyaa** [comment]
see https://github.com/chamilo/chamilo-lms/issues/1480
