### ISSUE TITLE
BUG 1.11.2 visualisation de la correction d'un test

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1505]
### Information installation
Serveur débian - PHP 5.6.27-0+deb8u1 - Apache - mysql Ver 14.14 distrib 5.5.53
Chamilo 1.11.2 avec configuration 

### Expected behavior / Resultado esperado / Résultat attendu
Tests dans un parcours avec configuration : pas de feedback - mode exercice montrer le score uniquement
Connexion en tant que apprenant coach, voir les réponses des élèves et la correction du test

### Actual behavior / Resultado real / Résultat réel
le coach voit le test et les réponses des élèves mais il ne voit pas la correction du test pour les questions Remplir les blancs

**Comment by ywarnier** [comment]
Bien reçu, nous allons vérifier ça.

**Comment by AngelFQC** [comment]
I can't reproduce this. Can you try again, please?

**Comment by DidierR30** [comment]
Voici une image :

![test_image](https://cloud.githubusercontent.com/assets/22951810/23832185/33d57c0a-0730-11e7-8636-36540a755b2c.PNG)

**Comment by DidierR30** [comment]
Sur l'image la réponse de l'étudiant est visible vert juste et rouge faux
Par contre la correction n'est pas visible.

**Comment by ywarnier** [comment]
Il semblerait que ce soit maintenant résolu.
![Uploading fib-fixed.png…]()

**Comment by DidierR30** [comment]
Je confirme, cela fonctionne.
Merci!
Didier

**Comment by DidierR30** [comment]
Bonsoir,
Petit problème suite au remplacement des 2 fichiers :
J'ai remplacé les 2 fichiers sur ma version 1.11.2 : j'ai la visualisation de la correction mais les étudiants ont faux aux différents texte à trous : la réponse n'ai pas prise en compte comme si l'étudiant n'avait rien écrit!
Du coup j'ai remis les 2 fichiers de la version 1.11.2 et cette fois les réponses sont bien prises en compte.

**Comment by DidierR30** [comment]
Bonsoir,

Je viens de tester sur https://1.11.chamilo.org/index.php en créant un cours, un questionnaire et un utilisateur.
Cela fonctionne très bien.

Merci

Didier
