### ISSUE TITLE
BUG 1.11.2 création d'un nouveau test impossible

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1506]
###Installation
Serveur débian - PHP 5.6.27-0+deb8u1 - Apache - mysql Ver 14.14 distrib 5.5.53
Chamilo 1.11.2 avec configuration

### Expected behavior / Resultado esperado / Résultat attendu
Création d'un nouveau test, poursuivre avec la création des questions

### Actual behavior / Resultado real / Résultat réel
page blanche après avoir validé

http://www.jbdmecaauto.fr/chamilo/main/exercise/exercise_admin.php?cidReq=ZONE52&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by ywarnier** [comment]
Je confirme. L'erreur qui apparaît en mode de développement:
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list' in /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array) #1 /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/www/chamilo111x/main/inc/lib/database.lib.php(419): Doctrine\DBAL\Statement->execute(Array) #3 /var/www/chamilo111x/main/exercise/exercise.class.php(1675): Database::insert('c_quiz', Array) #4 /var/www/chamilo111x/main/exercise/exercise.class.php(2466): Exercise->save('') #5 /var/www/chamilo111x/main/exercise/exercise_admin.php(154): Exercise->processCreation(Object(FormValidator)) #6 {main} Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'hide_question_title' in 'field list' in /var/www/ch in /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71

**Comment by jmontoyaa** [comment]
Pour corriger ca:

`ALTER TABLE c_quiz ADD hide_question_title TINYINT(1) DEFAULT 0;`

Le changement a été ajouté dans 1.11.x

**Comment by DidierR30** [comment]
Je viens d'appliquer la modification via mysql en ligne de commande et cela fonctionne.

Merci!
