### ISSUE TITLE
BUG 1.11.2 duplication d'un test impossible

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1507]
###Installation
Serveur débian - PHP 5.6.27-0+deb8u1 - Apache - mysql Ver 14.14 distrib 5.5.53
Chamilo 1.11.2 avec configuration

### Expected behavior / Resultado esperado / Résultat attendu
Dupliquer un exercice

### Actual behavior / Resultado real / Résultat réel
page blanche quand on clique sur copier cet exercice comme un nouvel exercice

**Comment by DidierR30** [comment]
Pour information, cela fonctionne dans la version 1.11.0

**Comment by jmontoyaa** [comment]
Il faut mettre chamilo en mode test pour voir l'erreur. Je ne peux pas le reproduire ici:

https://1.11.chamilo.org/main/exercise/exercise.php?cidReq=ANATOMIE&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by ywarnier** [comment]
@DidierR30 pourrais-tu mettre ton portail en mode test pour reproduire le problème et nous indiquer le message d'erreur, s'il te plaît?
Sinon nous devrons clôturer ce rapport.

**Comment by DidierR30** [comment]
Bonjour,
Je viens de faire la mise à jour vers la version 1.11.2 aujourd'hui (22/12/2016)
et cela fonctionne (je suis sous linuxmint et mozilla)
Je ferme le ticket.
Merci
Didier
