### ISSUE TITLE
BUG 1.11.2 après erreur mot de passe - page blanche - impossibilité de réafficher le site

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1511]
###Installation
Serveur débian - PHP 5.6.27-0+deb8u1 - Apache - mysql Ver 14.14 distrib 5.5.53
Chamilo 1.11.2 avec configuration

### Expected behavior / Resultado esperado / Résultat attendu
affichage de la page d'accueil après avoir saisie un mauvais mot de passe

### Actual behavior / Resultado real / Résultat réel
page blanche, impossible de réafficher la page, il faut quitter le navigateur et le relancer

http://www.jbdmecaauto.fr/chamilo/index.php?loginFailed=1&error=user_password_incorrect

**Comment by DidierR30** [comment]
En mode test:
adresse :
http://www.jbdmecaauto.fr/chamilo/index.php?loginFailed=1&error=user_password_incorrect

Dans la page on a le message suivant :

Fatal error: Call to undefined method HTML_QuickForm_CAPTCHA::HTML_QuickForm_CAPTCHA() in /var/www/html/chamilo/main/inc/lib/pear/HTML/QuickForm/CAPTCHA/Image.php on line 59

Merci
Didier

**Comment by jmontoyaa** [comment]
L'erreur est déjà corrigé.
Il faut mettre à jour à la dernière version de chamilo 1.11.x 

Ou sinon mettre à jour les fichiers:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/pear/HTML/QuickForm/CAPTCHA.php
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/pear/HTML/QuickForm/CAPTCHA/Image.php

**Comment by DidierR30** [comment]
On peut utiliser la version 1.11.x dans un environnement de production?
Ou je dois rester sur la version 1.11.2 et mettre à jour les fichiers?

Merci pour cette précision,

Didier

**Comment by DidierR30** [comment]
J'ai fait la mise à jour vers la version 1.11.x

Cela fonctionne.

Merci
