### ISSUE TITLE
BUG 1.11.2 annonce système ne s'affiche pas sur la page d'accueil en mode invité

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1512]
###Installation
Serveur débian - PHP 5.6.27-0+deb8u1 - Apache - mysql Ver 14.14 distrib 5.5.53
Chamilo 1.11.2 avec configuration

### Expected behavior / Resultado esperado / Résultat attendu
création d'une annonce système dans administration/annonces système 
et la rendre visible pour les enseignants / apprenants / invité

### Actual behavior / Resultado real / Résultat réel
l'annonce ne s'affiche pas sur la page d'accueil en mode invité
l'annonce s'affiche sur la page d'accueil une fois connecté

**Comment by jmontoyaa** [comment]
"invité" c'est en fait des utilisateurs pas connectés dans la plateforme. Ca marche pour moi:

Voir ici:

https://1.11.chamilo.org/index.php

(admin/admin)

**Comment by DidierR30** [comment]
Je viens de chercher et de trouver mon erreur :

J'avais configuré Cacher annonces globales aux anonymes sur OUI dans les paramètres de configuration de chamilo..

Milles excuses et Merci,

Didier
