### ISSUE TITLE
Student-rights for deleting on files in own group-folder

### ISSUE THREAD

**Issue by rkvdmeer** [chamilo/chamilo-lms#1513]
### Expected behavior
Students must be able to delete files and folders in their own group-document-folder

### Actual behavior
They can only add files and folders. As a lecturer I do not have the possibilities to give them those rights

### Steps to reproduce 
Student: Go to student view and try
Lecturer: I can only give special rights to new groups

**Comment by jderriks** [comment]
Have you tried this in version 1.11? It should work now.

**Comment by ywarnier** [comment]
No feedback provided. Closing.
