### ISSUE TITLE
Upgrade 1.10->1.11 composer update error

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1514]
### Expected behavior / Resultado esperado / Résultat attendu
no errors 
### Actual behavior / Resultado real / Résultat réel
composer update fails
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
after git checkout 1.11.x the composer update fails:

composer update on branch 1.11.x fails on the latest addition chamilo/chash:

> Chamilo\CoreBundle\Composer\ScriptHandler::deleteOldFilesFrom19x
Loading composer repositories with package information                                                    
Updating dependencies (including require-dev)     
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for chamilo/chash dev-master -> satisfiable by chamilo/chash[dev-master].
    - chamilo/chash dev-master requires symfony/validator ~2.8 -> satisfiable by symfony/validator[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11,.8.12, v2.8.13, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9] but these conflict with your requirements or minimum-stability.
Package barryvdh/elfinder-builds is abandoned, you should avoid using it. Use studio-42/elfinder instead.
Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.

**Comment by jmontoyaa** [comment]
Its fixed now
