### ISSUE TITLE
Verscion Check message incorrect

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1515]
### Expected behavior / Resultado esperado / Résultat attendu
Version check 1.11.2 = 1.11.2 should say it's up-to-date.
### Actual behavior / Resultado real / Résultat réel
it says "Your version is not up-to-date"
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Upgrade to 1.11.2 (I used git), change app/conf/configuration.php line 
`$_configuration['system_version'] = '1.11.2';`
and when you look at the bottom left corner of the platform administration page it says "Your version is not up-to-date"
![chamiloversioncheck](https://cloud.githubusercontent.com/assets/1659604/20457101/49793ac4-ae84-11e6-9f52-cd7d9bdb5e3c.PNG)

**Comment by jmontoyaa** [comment]
Should be fixed now. Thanks for reporting.

**Comment by jderriks** [comment]
Tested and works - thanks!

- It does not work on systems that use http_proxy (outgoing) to protect the webserver. We have some.
- Do people know that statistics are sent every time this check is done? Is there some web page where this is shown?

**Comment by ywarnier** [comment]
The admin manuals in Spanish and French explain the statistics sent and how to disable it. The English manual is completely outdated. The community is welcome to update it.

**Comment by jderriks** [comment]
Bad community. 
This issue can be closed.
