### ISSUE TITLE
Error when deleting course

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1516]
### Expected behavior / Resultado esperado / Résultat attendu
Course deletion confirmation message

### Actual behavior / Resultado real / Résultat réel
Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`chamilo111x`.`skill_rel_user`, CONSTRAINT `FK_79D3D95A591CC992` FOREIGN KEY (`course_id`) REFERENCES `course` (`id`)) in /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104 Stack trace: #0 /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('DELETE FROM cou...') #1 /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('DELETE FROM cou...') #2 /var/www/chamilo111x/main/inc/lib/database.lib.php(363): Doctrine\DBAL\Connection->executeQuery('DELETE FROM cou...') #3 /var/www/chamilo111x/main/inc/lib/course.lib.php(2340): Database::query('DELETE FROM cou...') #4 /var/www/chamilo111x/main/admin/course_list.php(347): CourseManager::delete_course('NATGEO') #5 {main} Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[2300 in /var/www/chamilo111x/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 60

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
In 1.11.x, create skills, create a course, add an evaluation, link the evaluation to a skill, go to admin courses list. Try to delete a course.

**Comment by jmontoyaa** [comment]
I couldn't reproduce the error with those steps.
But I added a query to delete the items inside skill_rel_user

**Comment by ywarnier** [comment]
I changed your commit to avoid deleting the skill acquired by the user (which has a public page) and change the record to remove the course reference. Tested before pushing.
