### ISSUE TITLE
BigblueButton problem 

### ISSUE THREAD

**Issue by hichamon306** [chamilo/chamilo-lms#1518]
After success Upgrading from 1.10.8 to 1.11.2, the plugin BigBlueButton does not work any more 
Log File : 
[error] 5176#5176: *1968 FastCGI sent in stderr: "PHP message: An exception occurred while executing 'SELECT * FROM plugin_bbb_meeting  WHERE c_id = '12' AND session_id = '0' AND status = 1 AND access_url = '1'':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'access_url' in 'where clause'" while reading response header from upstream, client: 88.170.188.193, server: sandbox.ceusi.fr, request: "GET /plugin/bbb/listing.php?cidReq=UE29S5P133&id_session=0&gidReq=0 HTTP/1.1",

comparing database model of fresh install of 1.11.2 and upgraded database model , table "plugin_bbb_meeting" seem not been updated and "plugin_bbb_room" does not exist 

Thanks

**Comment by ywarnier** [comment]
There is a README.md in the plugin which contains the SQL commands you have to execute to get it to work.

**Comment by hichamon306** [comment]
thanks @ywarnier
