### ISSUE TITLE
course catalogue #3: course categories not selectable as filter

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1526]
### Expected behavior / Resultado esperado / Résultat attendu
View course catalogue on selected course categories
### Actual behavior / Resultado real / Résultat réel
Course categories cannot be selected
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
![chamilo-catelog-categories](https://cloud.githubusercontent.com/assets/1659604/20816426/7204ed88-b822-11e6-823e-891c7cc53208.png)

Here you cannot choose anything else but "all" or "none".

**Comment by jderriks** [comment]
More info: the categories seem to be gone completely but the course_category table still has them.
The query 

> SELECT t1.name, t1.code, t1.parent_id, t1.tree_pos, t1.children_count, COUNT(DISTINCT t3.code) AS nbr_courses FROM course_category t1 INNER JOIN access_url_rel_course_category a ON (t1.id = a.course_category_id) LEFT JOIN course_category t2 ON t1.code = t2.parent_id LEFT JOIN course t3 ON t3.category_code=t1.code WHERE 1 = 1 AND (t1.parent_id IS NULL OR t1.parent_id = '' ) AND a.access_url_id = 1 GROUP BY t1.name, t1.code, t1.parent_id, t1.tree_pos, t1.children_count ORDER BY t1.tree_posArray ( ) 

from course_category.lib.php does not return any rows because of the (t1.id = a.course_category_id).

Since when should the course_category t1 have an ID field? I think something went wrong with a database update. Even 
>php bin/doctrine.php orm:schema-tool:update --dump-sql
does not mention adding an ID to  course_category

**Comment by jderriks** [comment]
When the access_url_rel_course_category table is polulated another strange thing appears: the categories are displayed in the ptalform admin categories page but the number of courses is set to 1 in the php code: 

https://github.com/chamilo/chamilo-lms/blame/master/main/inc/lib/course_category.lib.php#L93

lines 93-95

Why? Remove these lines and the number of courses in the categories are displayed correctly.

**Comment by AngelFQC** [comment]
I fixed the number of sub-categories

**Comment by ywarnier** [comment]
Looks good to me now
![cata](https://cloud.githubusercontent.com/assets/609839/24213293/fb60fb10-0eff-11e7-9d3a-e8a3a7a18936.png)
