### ISSUE TITLE
Suppression impossible d'un cours Chamilo version 1.11.x du 02-12-2016

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1528]
### Expected behavior / Resultado esperado / Résultat attendu
Suppresion d'un cours - cours supprimé

### Actual behavior / Resultado real / Résultat réel
cours non supprimé - erreur suivante :

http://www.jbdmecaauto.fr/chamilo/main/admin/course_list.php?delete_course=TEST

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'chamilo.ticket_ticket' doesn't exist' in /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104 Stack trace: #0 /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('UPDATE ticket_t...') #1 /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(833): Doctrine\DBAL\Driver\PDOConnection->query('UPDATE ticket_t...') #2 /var/www/html/chamilo/main/inc/lib/database.lib.php(363): Doctrine\DBAL\Connection->executeQuery('UPDATE ticket_t...') #3 /var/www/html/chamilo/main/inc/lib/course.lib.php(2336): Database::query('UPDATE ticket_t...') #4 /var/www/html/chamilo/main/admin/course_list.php(347): CourseManager::delete_course('TEST') #5 {main} Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'chamilo.ticket_ticket' doesn't exist' in /var/ in /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 53

**Comment by DidierR30** [comment]
Pour information, cela fonctionne dans la version 1.11.0

**Comment by jmontoyaa** [comment]
Normally you should have a "ticket_ticket" table in the database.
You're coming from a migration or you installed a fresh version of Chamilo 1.11.x?

**Comment by DidierR30** [comment]
J'ai fait une installation de la version 1.11.0 et ensuite j'ai importé les cours.

La version 1.11.0 fonctionne pas trop mal. Sur la version 1.11.2 et la version 1.11.x cela ne fonctionne pas.

Merci 

Didier

**Comment by DidierR30** [comment]
Bonjour,
Je viens de faire une mise à jour de chamilo (1.11.0 vers la version 1.11.2) aujourd'hui
Je viens de refaire des tests, cela fonctionne sous LinuxMint / Mozilla
Merci
Didier
