### ISSUE TITLE
Impossible d'ajouter un document dans documents - chamilo v 1.11.x 02122016

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1529]
### Expected behavior / Resultado esperado / Résultat attendu
Ajouter un document dans le dossier Document

### Actual behavior / Resultado real / Résultat réel
Par Importer le fichier
Echec de l'envoi du fichier

Par Importer le fichier (simple) :
http://www.jbdmecaauto.fr/chamilo/main/document/upload.php?cidReq=CHALLENGE&id_session=0&gidReq=0&gradebook=0&origin=&id=0#tabs-2

Fatal error: Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded.' in /var/www/html/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54 Stack trace: #0 /var/www/html/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 /var/www/html/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 /var/www/html/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 /var/www/html/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(226): Doctrine\Com in /var/www/html/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54

**Comment by DidierR30** [comment]
Pour information cela fonctionne dans la version 1.11.0

**Comment by jmontoyaa** [comment]
This should be fixed when doing a "composer update"

**Comment by DidierR30** [comment]
OK merci, je vais attendre la version 1.11.4 et rester sur 1.11.0
