### ISSUE TITLE
Ldap external login: new users are not added

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1531]
### Expected behavior / Resultado esperado / Résultat attendu
A user that has LDAP auth but is not in the system yet should be added with newUser,ldap.php
### Actual behavior / Resultado real / Résultat réel
New users seem to login but are not created and do not get any error message.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Test it with an ldap system and try login with a user that has LDAP rights but is not yet added to chamilo.

FIX: this bug was introduced with a commit 3 october:
https://github.com/chamilo/chamilo-lms/commit/ee1efcb0ec9628b533665c1c716bc450268ac324

**Comment by Starbugstone** [comment]
Can confirm with a fresh install that LDAP login does not work. I get an error message with user not authorised to access this page and no user is created in the user table of the database.

I commented out the `break;` on line 580 from the commit https://github.com/chamilo/chamilo-lms/commit/ee1efcb0ec9628b533665c1c716bc450268ac324 to get things working again

**Comment by juronius** [comment]
I confirm, i commented out the break; on line 580 and now it work.
Thank very much.
