### ISSUE TITLE
Error in forum search

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1539]
### Expected behavior / Resultado esperado / Résultat attendu
Search results should appear

### Actual behavior / Resultado real / Résultat réel
"0 results" appear

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Apparently you just have to make a search.
A user tracked it down on the forum: https://chamilo.org/forum/viewtopic.php?f=50&t=8620

Please apply the fix immediately to master as well.

**Comment by jderriks** [comment]
Cannto reproduce the bug on our system (search works) but we don't use sessions yet so all our sessionId's are 0.

**Comment by jmontoyaa** [comment]
Already fixed in 1.11.x
https://github.com/chamilo/chamilo-lms/commit/8be9132fe3d58e0ce43e227404631e8790c41e37
