### ISSUE TITLE
Bouton pour la sélection du pré-requis mal positionné

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#1542]
Lors de l'ajout d'un prérequis dans un parcours, le bouton de sélection apparait par dessus l'icone de l'étape

Voir image jointe
Version 1.11x du 9 déc. 2016  sur https://1.11.chamilo.org/

![bug_pre-requis](https://cloud.githubusercontent.com/assets/22802716/21067148/6ca77bc4-be37-11e6-9c01-777798f369e5.jpg)

**Comment by andreboivin** [comment]
**Remove** style="margin-left:' . $item['depth'] * 10 . 'px
Line 8635 dans learnpath.class.php
and change line 8639, 8642
  $return .= Display::return_icon('lp_' . $icon_name . '.png');
**For**   $return .= Display::return_icon('lp_' . $icon_name . '.png','',array('style'=>'margin-right:5px;'));

**Comment by ywarnier** [comment]
@aragonc !

**Comment by aragonc** [comment]
Mejoras enviados en PR a Chamilo, para revisión

![prerequisitos](https://cloud.githubusercontent.com/assets/2940509/25453246/dee905dc-2a8d-11e7-9c03-2afdfb722bde.png)

**Comment by ywarnier** [comment]
Sigo teniendo problemas, @aragonc 
![lp-align-bad](https://cloud.githubusercontent.com/assets/609839/26022949/83174de4-3777-11e7-8ea0-2877fee7845d.png)

**Comment by ywarnier** [comment]
Much better. Thanks.
