### ISSUE TITLE
Liens vers forums de groupes dupliqués en "forum"

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#1544]
Bonjour,

Problème sur Chamilo 1.11.2. Problème reproduit sur https://1.11.chamilo.org

Etapes : 

- l'administrateur du site a paramétré les forums de groupes visibles dans l'outil forum.
- je créé des groupes
- je définis leurs forums comme "privés"
- lorsque les étudiants se connectent à l'outil forum, ils voient leurs "forums de groupes" dupliqués en x fois selon une logique qui m'échappe (3 fois concernant le group001 pour l'étudiant "tanchon" sur le site de test dont je donne le lien ci-dessous).
- pas de pb si c'est un administrateur ou enseignant qui se connecte à l'outil forum : le forum de chaque groupe apparaît bien, une seule fois.

**J'ai reproduit le problème ici** ("cours de test") : https://1.11.chamilo.org/main/forum/index.php?cidReq=COURSDETEST&id_session=0&gidReq=0&gradebook=0&origin=

Le problème n'est visible qu'avec un compte étudiant (concernant le lien ci-dessus : tanchon / tanchon). Chacun des liens dupliqués fonctionne bien et mène au forum de groupe.

Voici où voir une image du pb : https://support.chamilo.org/attachments/download/6192/Nouvelle%20image.jpg

Merci !

Tanchon

**Comment by jmontoyaa** [comment]
Peut être corrigé avec 

https://github.com/chamilo/chamilo-lms/commit/b9927396aaa3af336cf5cd90099c57122abb407e

**Comment by tanchon** [comment]
Merci jmontoyaa ! 

ça fonctionne nickel !
