### ISSUE TITLE
Learning Object Rearrange

### ISSUE THREAD

**Issue by mozesj** [chamilo/chamilo-lms#1553]
### Expected behavior / Resultado esperado / Résultat attendu
Normal arrangement after adding/editing a learning object or activity
### Actual behavior / Resultado real / Résultat réel
After creating and saving a learning object document, the arrangement is lost
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Add an object under a learning path and arrange learning path objects, pick one object edit and save

**Comment by ywarnier** [comment]
Hi @mozej, which version of Chamilo are you using? Could you post a screenshot?

**Comment by mozesj** [comment]
I'm using vesrion 1.11.2
![error](https://cloud.githubusercontent.com/assets/24265437/21711231/c2fda160-d3fe-11e6-94b1-26fc0b22cca5.PNG)

Before creating and saving Title 3, Section 1 was in between Title 1 and Title 2

**Comment by AngelFQC** [comment]
Please, try on 1.11.chamilo.org

**Comment by ywarnier** [comment]
Closing. Cannot reproduce and no feedback provided.
