### ISSUE TITLE
Change js and css path

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1564]
css and js paths should be under the web "public" path and not inside main/inc/lib/javascript

**Comment by ywarnier** [comment]
Agreed, but the process to have them in web/ shouldn't make like more complicated for developers or admins :-)

**Comment by jmontoyaa** [comment]
There are some problems with that: 
Some libs are big example: mathajax (70,5 MB) so we will have some paths duplicated
composer update takes some time to copy everytime from app/Resources to web and 
js/css libs are not updated that regularly ...

**Comment by jmontoyaa** [comment]
Follow #2320 instead
