### ISSUE TITLE
Error que bloquea el acceso ha camilo

### ISSUE THREAD

**Issue by mvallsru** [chamilo/chamilo-lms#1565]
### Expected behavior / Resultado esperado / Résultat attendu
Que se muestre la página

### Actual behavior / Resultado real / Résultat réel
[Tue Dec 20 10:13:35.195513 2016] [:error] [pid 3008] [client 195.235.176.225:61827] An exception occurred while executing 'SELECT id FROM access_url WHERE url = 'https://www.campuscivis.es/'':\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away, referer: https://www.campuscivis.es/main/admin/usergroups.php
[Tue Dec 20 10:13:35.201136 2016] [:error] [pid 3008] [client 195.235.176.225:61827] PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 64 bytes) in /home/admin/web/campuscivis.es/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 104, referer: https://www.campuscivis.es/main/admin/usergroups.php

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
uenos días,

El pasado 5 de Diciembre, migramos de la versión 1.9.10 a la versión 1.11.2 de chamilo. Desde entonces los alumnos y nosotros venimos sufriendo cortes en chamilo. Revisando los logs hemos visto que hay un montón de errores de

[Tue Dec 20 10:13:35.195513 2016] [:error] [pid 3008] [client 195.235.176.225:61827] An exception occurred while executing 'SELECT id FROM access_url WHERE url = 'https://www.campuscivis.es/'':\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away, referer: https://www.campuscivis.es/main/admin/usergroups.php

La pagina de chamilo cambia pero siempre da error al ejecutar la sentencia 'SELECT id FROM access_url WHERE url = 'https://www.campuscivis.es/' Al final después de muchos errores del anterior tipo da el error:

[Tue Dec 20 10:13:35.201136 2016] [:error] [pid 3008] [client 195.235.176.225:61827] PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 64 bytes) in /home/admin/web/campuscivis.es/public_html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 104, referer: https://www.campuscivis.es/main/admin/usergroups.php

Podeis ayudarme a saber que está pasando?. Los alumnos tienen un malestar creciente debido a este problema, lo que está dañando nuestra imagen.

Muchas gracias

**Comment by ywarnier** [comment]
Hola Manuel,

Chamilo 1.11 usa más recursos en general que Chamilo 1.9, y dependiendo de como lo has instalado y en qué versión de Chamilo, puede que impacte el rendimiento.

Sin embargo, el problema que indicas parece una mezcla de muchas cosas:
- "MySQL server has gone away" significa que tu servidor MySQL no responde. Puede que ahí esté un problema de un query que demora demasiado. Verifícalo lanzando un "SHOW PROCESSLIST;" en MySQL
- "Allowed memory size of 536870912 bytes exhausted" significa que Chamilo estaba necesitando un poco más de 512M de RAM en este momento (probablemente porque ha generado el primer error y que estás en modo de desarrollo, el cual consume más RAM) y se cuelga porque hay un límite a 512M
- El mismo query SELECT id FROM access_url WHERE url = 'https://www.campuscivis.es/' parece estar bien. Habría que ver qué resultado da este cuando lo lanzas directamente dentro de MySQL

**Comment by ywarnier** [comment]
@mvallsru, algún comentario antes de que cierre este reporte?

**Comment by mvallsru** [comment]
Buenas,
Gracias por la ayuda. Revisaré a a ver si puedo encontrar lo que está ocurriendo.

Puedes cerrar el post. Si encuentro el problema os lo haré saber.

Muchas gracias.
