### ISSUE TITLE
Updating 1.10.8 to 1.11.2

### ISSUE THREAD

**Issue by hichamon306** [chamilo/chamilo-lms#1575]
While upgrading from 1.10.8, I have this problem : 
ERROR: An exception occurred while executing 'ALTER TABLE c_quiz_question_rel_category ADD INDEX idx_qqrc_qid (question_id)':

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'idx_qqrc_qid'

**Comment by jmontoyaa** [comment]
I added a fix. Try with the latest 1.11.x code.
