### ISSUE TITLE
Asuntos de mensajes vacío si contienen acentos

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1577]
Si el nombre de la plataforma (api_get_setting('siteName')) contiene acentos al enviar mensajes en los que se usa el nombre de la plataforma en el asunto (ejemplo página de editar usuario) llegan vacíos, al abrir el mensaje con Thunderbird en el asunto aparece la cadena "_=?UTF-8?Q??=_"

**Comment by jmontoyaa** [comment]
Probar aqui: 

https://1.11.chamilo.org/

**Comment by nosolored** [comment]
Ya funciona correctamente, gracias

**Comment by nosolored** [comment]
Se reproduce el error en instalación con PHP 7. Si se mueve a PHP 5.6 con el mismo servidor de correo Postfix funciona correctamente.

Ocurre también si existe acentos en el asunto o en el nombre del usuario.

Saludos.

**Comment by jmontoyaa** [comment]
Revisar que exista el archivo:

`app/config/mail.conf.php`

con `SMTP_CHARSET = UTF-8`

**Comment by nosolored** [comment]
Si, el archivo existe y está configurado así.

**Comment by ywarnier** [comment]
Tengo el mismo problema en un servidor con PHP 7.0.

**Comment by ywarnier** [comment]
En una máquina local en Ubuntu 16.10 con PHP 7.1 no me aparece el problema. No estoy seguro de si la diferencia está entre 7.0 y 7.1 o si hay algo distinto, pero voy descartando poco a poco.

**Comment by ywarnier** [comment]
Tan pronto como se ponga un caracter como "ç", ya se bloquea en un portal con PHP7.0.15 en Ubuntu 16.04.
El título se remplaza por "=?utf-8?Q??=" (en la fuente, pero no aparece nada en un cliente de correo).

**Comment by ywarnier** [comment]
El problema yace en la línea 1779 de class.phpmailer.php, en la cual se hace un preg_replace() bastante oscuro que transforma una cadena de título en UTF-8 en... una cadena vacía.
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/phpmailer/class.phpmailer.php#L1779

**Comment by ywarnier** [comment]
Este parche arregla el problema para mi y, hasta donde he podido probarlo, el único impacto negativo que *podría* tener es que los correos podrían ser algo más largos (pero vamos, no creo que hablemos de más de 20% más) si están en UTF-8.
Había un código raro para optimizar el tamaño del texto codificado, que se estaba introduciendo un poco demasiado en la interpretación de los caracteres y convirtiendo demasiado. Primero intenté arreglar el código del método EncodeQ(), que dicho de paso usa una sintaxis deprecated de preg_replace(), pero tuve que abandonar porque son cambios manuales de codificación demasiado oscuros (ver tabla ASCII aquí: http://www.cpptutor.com/ascii.htm). Al final, decidí hacer un boycott de este método (tenía sentido) y me salió mucho mejor.

@nosolored tendraís una forma de probarlo? (el cambio es muy pequeño)

**Comment by nosolored** [comment]
Hemos aplicado los cambios y funciona correctamente.
Gracias!

**Comment by rtecpem32pda** [comment]
Buenas noches: antes que nada agradezco el tiempo que invierten en la resolución de problemas que benefician a muchos.

Reporto el mismo problema en Servidor de Web Hosting funcionando con PHP 7.3.

Chequie este parche
https://github.com/chamilo/chamilo-lms/commit/9c8528e4b3508670aedcefaab7a839a9c0e494a8

Aplicado a: main/inc/lib/phpmailer/class.phpmailer.php  y ya esta aplicado en mi versión de Chamilo 1.11.10

También chequie que app/config/mail.conf.php 

 SMTP_CHARSET = UTF-8

¿Alguna sugerencia?

**Comment by ywarnier** [comment]
Esperar la versión 1.11.12 de Chamilo, que esperamos publicar en unas semanas, porque incluye la nueva versión de PHPMailer que probablemente solucione el problema sin más esfuerzo.

**Comment by rtecpem32pda** [comment]
Buenos días, Ok. Gracias por la pronta respuesta!
Me tomo el atrevimiento de realizar otros aportes que tienen que ver con esta temática,  herramienta correo de  la red social. Yo lo he publicado en el foro de chamilo
https://forum.chamilo.org/viewtopic.php?f=15&t=11177
Nadie me ha sabido contestar aun y considero sería interesante lo tengan en cuenta en esta nueva actualización que me comentas.
En primer lugar detecto un error que se arrastra de versiones anteriores a mi parecer. El problema es el siguiente: cuando ingreso a la bandeja de salida veo todos los mensajes, pero en vez de ver el destinatario de mis mensajes veo mi nombre. Para poder ver a quien envío el mensaje debo abrir el mismo y encontrar esa información, lo cual es molesto para encontrar uno en particular sin necesidad de abrir varios mensajes antes de poder encontrarlo.

En segundo lugar estoy teniendo un problema que no le encuentro la vuelta. Cada vez que un profesor responde a un alumno me llegan a mi correo de administrador ese e-mail. No entiendo por que, quiero deshabilitar esto. Solo me interesaría recibir los e-mail que vengan dirigidos a mi casilla de administrador.

**Comment by rtecpem32pda** [comment]
> Esperar la versión 1.11.12 de Chamilo, que esperamos publicar en unas semanas, porque incluye la nueva versión de PHPMailer que probablemente solucione el problema sin más esfuerzo.

Buenos días:  encontré esta opción, quizá pueda ayudar en este problema.
![Servicio decodificar UTF](https://user-images.githubusercontent.com/64183101/80283398-91d13700-86ed-11ea-8f06-d05fa7bcdcfc.png)

Por defecto el parámetro esta desactivado, lo active y voy a ver que resultado me da.
