### ISSUE TITLE
utf8 encoding

### ISSUE THREAD

**Issue by emopan** [chamilo/chamilo-lms#1578]
Hi! Can anyone help us out?
We have recently migrated our main site and our e-learning site based on Chamilo to a new server with the same hosting company to sort out some speed and access problems. However, new problems occurred, mainly with character encoding. We need to use the Cyrillic alphabet beside Latin, but the new server default encoding is set to be cp1251. They advised us to check what init-connect Chamilo uses (I am not sure if I describe it correctly) and to find how to SET NAMES UTF8.
### Expected behavior
Correctly loaded Cyrillic alphabet everywhere - in Terms and Conditions, Glossary, Tests, etc. Custom course icons instead of green boards.
![course image](https://cloud.githubusercontent.com/assets/24916633/21644402/fa354968-d295-11e6-8047-4cfaa9f1e3b0.jpg)
![intro](https://cloud.githubusercontent.com/assets/24916633/21644460/39bd7a7e-d296-11e6-82bb-643671183af0.png)

### Actual behavior
![course icons](https://cloud.githubusercontent.com/assets/24916633/21644405/fd3bd1f4-d295-11e6-887b-2776a480e4de.jpg)
![intro](https://cloud.githubusercontent.com/assets/24916633/21644464/40eaf3b2-d296-11e6-9b39-bfc8c0d34fc4.jpg)
![terms](https://cloud.githubusercontent.com/assets/24916633/21644486/5c9badb8-d296-11e6-8281-0bb7813bc5e6.jpg)
![glossary](https://cloud.githubusercontent.com/assets/24916633/21644529/8040bcf4-d296-11e6-8262-40f04b37eb7d.jpg)

### Steps to reproduce
Is there a way to set the encoding from within the Chamilo (maybe by modifying some config files or whatever is necessary) so that it overwrites the server default character encoding and it starts displaying characters correctly or we will need to ask the hosting company for another migration to a new server?

Thanks beforehand for any suggestions!

**Comment by jmontoyaa** [comment]
It looks like a problem in the database charset. The database and tables should be created in UTF8.
Chamilo use UTF8 by default using Doctrine to handle the charset.

I tried in the glossary in a demo portal and is working:

login/pass: admin/admin

https://1.11.chamilo.org/main/glossary/index.php?cidReq=RUSSIAN&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by emopan** [comment]
Thank you. I guess we will have to ask the host to change the server.

**Comment by plamer** [comment]
Hello, here is some additional info about emopan's case:

In phpMyAdmin the encoding is fine - both the database and the tables are in utf-8: https://i.imgur.com/OP2fAZh.png - everything is readable, but when PHP connects to MySQL it uses MySQL's encoding (and doesn't set it's own), which is cp1251 (set in my.cnf) and because of this the site's encoding isn't visualized as it should: https://i.imgur.com/VRAf3VK.png

The question is: is there a way to explicitly set the encoding in the chamillio app? Something in the line of `mysql_set_charset('utf-8',$connect); `?

Thanks in advance!

**Comment by jmontoyaa** [comment]
To connect to the database we use Doctrine as a database layer.
The charset is set by default to utf8 here:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/database.lib.php#L155

What's the configuration of your my.cnf?

**Comment by plamer** [comment]
Regarding encoding:
```
init-connect='SET NAMES cp1251'
collation_server=cp1251_bulgarian_ci
character_set_server=cp1251
```

**Comment by jmontoyaa** [comment]
I tried to set this in my my.cnf and then restart the server and it still works correctly.
I cannot reproduce this error.


```

!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mysql.conf.d/

[mysql]
init-connect='SET NAMES cp1251'

[mysqld]
collation_server=cp1251_bulgarian_ci
character_set_server=cp1251
~                                 
```

**Comment by plamer** [comment]
I'm sorry, i've missed the following under `[mysql]`: `default-character-set = cp1251`
