### ISSUE TITLE
Error en la Configuración de pagina de registro con condiciones legales activadas

### ISSUE THREAD

**Issue by mvallsru** [chamilo/chamilo-lms#1582]
### Expected behavior / Resultado esperado / Résultat attendu
Yo tenía activado la aceptación de condiciones en la página de registro, después de migrar de la versión 1.19.10 a la 1.11.2 no podía editar la pagina de administración de registro ya que me daba el error:
[Fri Jan 06 11:19:11.435260 2017] [:error] [pid 24763] [client 80.102.152.164:57389] PHP Fatal error:  Uncaught exception 'Exception' with message 'Element 'extra_legal_accept' does not exist in HTML_QuickForm::addRule()' in /home/admin/web/campuscivis.es/public_html/main/inc/lib/pear/HTML/QuickForm.php:1053\nStack trace:\n#0 /home/admin/web/campuscivis.es/public_html/main/admin/configure_inscription.php(315): HTML_QuickForm->addRule('extra_legal_acc...', 'Contenido oblig...', 'required')\n#1 {main}\n  thrown in /home/admin/web/campuscivis.es/public_html/main/inc/lib/pear/HTML/QuickForm.php on line 1053, referer: https://www.campuscivis.es/main/admin/

Fui a la página configure_inscription.php y en la linea 315 venía el siguiente código. 
**$form->addRule('extra_legal_accept', get_lang('ThisFieldIsRequired'), 'required');**

Para solucionar el error en vez de poner extra_legal_accept, hay que poner el campo legal_acept. El código sería el siguiente:

if ($term_preview['type'] == 1) {
        $form->addElement(
            'checkbox',
            'legal_accept',
            null,
            get_lang('IHaveReadAndAgree').'&nbsp;<a href="inscription.php?legal" target="_blank">'.get_lang('TermsAndConditions').'</a>'
        );
        **$form->addRule('legal_accept', get_lang('ThisFieldIsRequired'), 'required');**
    } else {
        if (!empty($term_preview['content'])) {
            $preview = LegalManager::show_last_condition($term_preview);
            $form->addElement('label', get_lang('TermsAndConditions'), $preview);
        }
    }

Con esto se solucionaría el error.

### Actual behavior / Resultado real / Résultat réel
Se tendría que mostrar la página de configuración de página de registro.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Tener activado la opción de aceptar condiciones en la página principal del registro.

**Comment by jmontoyaa** [comment]
Gracias por el feedback. Acabo de enviar una correción.
