### ISSUE TITLE
Access not allowed to Learner Details In Course when allow_users_to_create_courses is disabled

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#1588]
### Expected behavior / Resultado esperado / Résultat attendu
Access to "Learner details in course" page when `allow_users_to_create_courses` is disabled

### Actual behavior / Resultado real / Résultat réel
Acess not allowed to "Learner details in course"

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1. In Configuration Settings, set `allow_users_to_create_courses` to `No`
2. Go to the User tool in any course
3. Go to the "Learner details in course" for any user

**Comment by AngelFQC** [comment]
@ywarnier this is a bug or a feature?

**Comment by ywarnier** [comment]
bug!

**Comment by AngelFQC** [comment]
Con `allow_users_to_create_courses` habilitada:
Cuando quito la condición relacionada a `allow_users_to_create_courses` en [/main/mySpace/myStudents.php:19](https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/mySpace/myStudents.php#L19), los profesores tampoco tienen acceso a menos que hayan sido puestos como tutores (líneas 27 a 33).
La pregunta es: ¿Este reporte es sólo visible para tutores del curso (en sesión y fuera de sesión), DRH, student boss y administradores? De ser así, habría que quitar el enlace en la lista de usuarios y mostrarlo sólo para estos roles
