### ISSUE TITLE
Error on DB on install 2.x via Github

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#1591]
### Expected behavior / Resultado esperado / Résultat attendu
Installation completes.

### Actual behavior / Resultado real / Résultat réel
The database initialization fails.
Some missing tranlation labels (not important).
![2017-01-09 16_37_59](https://cloud.githubusercontent.com/assets/1764993/21778616/e65ea8d0-d682-11e6-9a27-4db5bea8f218.png)
![2017-01-09 16_41_53-](https://cloud.githubusercontent.com/assets/1764993/21778615/e65c4a7c-d682-11e6-9974-dfef294e2b26.png)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
apache2 + php7 + mysql5.7 on xenial x64 (using same server as a 1.10.8 installation) 
1 Installed composer and download chamilo2 on github as writen.
2 Installed all dependencies and extensions needed.
3 composer update and and file permission set up.
4 Can't open the domain: (permission error on app_dev.php) editted on nano and commented some lines to see the errors.
5 Used the /web/install.php to access installation.
The follow error appears (buttons are greyed out)

**Comment by jmontoyaa** [comment]
When you did composer update did you setup your database environment correctly? (mysql user, pass, etc). Chamilo 2 is currently in development and is not stable. Only for test purposes.

**Comment by marshel** [comment]
I believe i did.
I use the PDO mysql driver (default option). i'd set the port 3306, the loopback ip and DB name, user and pass correctly. If this is set incorrectly, the composer shows a error.
I will try again later and report when I solve this. This looks like a config error but I need to find where.
 Best regards.

**Comment by jmontoyaa** [comment]
You should check your apache error logs and post here the result.
Thanks for reporting.

**Comment by jmontoyaa** [comment]
Closing, installer is not finished yet.
