### ISSUE TITLE
error Memcache en 1.11.2

### ISSUE THREAD

**Issue by profdamian** [chamilo/chamilo-lms#1594]
Estoy intentando actualizar de la version 1.9.10.2 a 1.11.2 y en el paso 4 me aparece la siguiente advertencia 

> Notice: Memcache::connect(): Server 192.168.0.57 (tcp 11211) failed with: Connection refused (111) in /www/tec17.edu.ar/chamilo-lms-1.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php on line 133
> 
> Warning: Memcache::connect(): Can't connect to 192.168.0.57:11211, Connection refused (111) in /www/tec17.edu.ar/chamilo-lms-1.11.0/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php on line 133

![image](https://cloud.githubusercontent.com/assets/25074395/21880813/aa8c6136-d87f-11e6-81df-af4c4b43868e.png)

**Comment by jmontoyaa** [comment]
Cuando se intenta actualizar de la version 1.9.10.2 a 1.11.2 no debería de aparecer esa pantalla.
Se tiene que hacer click aqui:

![selection_005](https://cloud.githubusercontent.com/assets/158935/21881015/3c53265a-d8a2-11e6-9cbb-be21734bd7e3.png)

**Comment by profdamian** [comment]
Si, disculpa, me equivoque de captura, estaba probando en una instalación nueva para ver si se repetía el error, te paso la captura de la actualización

![image](https://cloud.githubusercontent.com/assets/25074395/21901504/ce46ef68-d8d6-11e6-8b42-786984f0c7b7.png)

**Comment by ywarnier** [comment]
Algo tiene que haber sido mal configurado para que Memcache intente conectarse. No se usa Memcache en Chamilo 1.11.*

**Comment by ywarnier** [comment]
Falta feedback. Cerrando.
