### ISSUE TITLE
Bug en plugins en la actualización  1.10.6 a 1.11.2 

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1595]
Buenos días 

Estoy realizando la actualización de  chamilo de la version  1.10.6 a 1.11.2  y  he tenido un solo inconveniente hasta hora  en la parte  de administración en las opciones de plugins  me aparecen  en blanco y no me da la opción  de habilitar las plugins correspondientes.

**Comment by jmontoyaa** [comment]
Probar lo siguiente:

- Limpiar la cache
- Poner el servidor en modo de "desarrollo" y ejecutar la página.
- Revisar los error logs de apache

**Comment by fergimon** [comment]
Muchas gracias  por la ayuda
