### ISSUE TITLE
Not possible to generate personal API key

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1597]
### Expected behavior / Resultado esperado / Résultat attendu
When clicking the API key generator in user profile, it should generate an API key and when saving it should stay on my user profile edition page.

### Actual behavior / Resultado real / Résultat réel
When clicking the API key, the page is reloaded (not correct) and there is no API key generated (not correct).

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1. Go to admin panel, configuration settings, users section
2. Select the "API Key" checkbox and save
3. Go to your profile and edit it
4. At the end of the profile edition page, an "API key" field appears
5. Click the "Generate new API key" button
6. The page is reloaded but nothing happens

The user also reports the following error although he does not have any Google feature enabled: 
```
util.js:212 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
```

**Comment by jloguercio** [comment]
Fixed in this commit :
https://github.com/chamilo/chamilo-lms/commit/de747181190cefc3499e088ea01a150a6b19ecff

**Comment by ywarnier** [comment]
Confirmed and approved

**Comment by mesoshqip** [comment]
Hello Chamilo 

I want to enable google maps, but i can't find main/inc/lib/fckeditor/myconfig.php
I am using version 1.11.10
