### ISSUE TITLE
Sesión - Lista por categoría

### ISSUE THREAD

**Issue by michela85** [chamilo/chamilo-lms#1601]
### Expected behavior / Resultado esperado / Résultat attendu
Cuando doy click en el enlace de cantidad de sesiones en la página de lista de categorías de sesiones, debería listarme las sesiones que estan dentro de una categoría.

### Actual behavior / Resultado real / Résultat réel
Me parece la lista vacia.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Crear una categoría de sesión 
- Crear una sesión dentro de esta caategoría
- Ir a la lista de sesiones /main/session/session_category_list.php
- Entrar a una categoría por el enlace que indica la cantidad de sesiones /main/session/session_list.php?id_category=3
- No lista las sesiones de esta categoría 

Estoy usando Chamilo 1.11.x del 14 Enero 2017

**Comment by jmontoyaa** [comment]
Should be fixed now

**Comment by ywarnier** [comment]
Tested and approved
