### ISSUE TITLE
Copy course changes correct answers in Matching questions in quizzes

### ISSUE THREAD

**Issue by simbulu** [chamilo/chamilo-lms#1602]
### Expected behavior / Resultado esperado / Résultat attendu
'Copy course' should copy correct results in quizz questions correctly.

### Actual behavior / Resultado real / Résultat réel
'Copy course' sets all answers to 'A' in a copy of a 'Matching' question.  
The same happens with questions of the type 'Match by dragging'

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Verified on 1.10 and 1.11.chamilo.org in the courses Matching and MatchingCopycoures.

Create two courses named MATCHING and MATCHINGCOPYCOURSE
Enter MATCHING
Add a test
Add a Matching question and a Match be dragging question to the test 
Set all answers to B in both questions
save, ..., etc
From the course startpage, select Backup and use 'Copy course' to transfer a full copy of this course to the target course MATCHINGCOPYCOURSE

Enter MATCHINGCOPYCOURSE and verify that the answers of the two matching questions are 'A' rather than the expected answer 'B'.

**Comment by jmontoyaa** [comment]
I think this is already fixed.

**Comment by ywarnier** [comment]
@simbulu could you test this case again on https://1.11.chamilo.org (refresh if it hangs, the server is very slow sometimes) and tell us if this is fixed?

**Comment by ywarnier** [comment]
Considered fixed. Could not reproduce.
