### ISSUE TITLE
footer_extra_content is not saved anymore

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1604]
### Expected behavior / Resultado esperado / Résultat attendu
When going to page /main/admin/settings.php?category=Tracking, the second box is supposed to save the contents in app/home/footer_extra_content.txt and then to be read each time a page is loaded.

### Actual behavior / Resultado real / Résultat réel
The file is not created although permissions allow it, and no content is saved. When I click "save", nothing changes (no text appears in the box).
The file path is saved as ".../app/home//footer_extra_content.txt" so there is a useless double "/" there.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Install a new portal
- Go to /main/admin/settings.php?category=Tracking
- Type anything into the second box and save
- Nothing is saved

This probably also occurs with the header (first textarea box)

**Comment by jloguercio** [comment]
Arreglado y mergeado https://github.com/chamilo/chamilo-lms/pull/1615 
Lo que si vi curiosamente que el contenido extra del header se duplica, he visto que es un problema del tpl "show_header.tpl" que llama a un "head.tpl" y a un "page_header.tpl" el cual los dos llaman a la variable header_extra_content

Asigno a alex para que verifique

**Comment by jloguercio** [comment]
Bueno, considero que el header_extra_content no debería ir entre los tags de <head></head> (a menos que se quiera agregar archivos JS) lo he removido y ha quedado solo el que está en la cabecera.

este es el PR: https://github.com/chamilo/chamilo-lms/pull/1616

**Comment by jloguercio** [comment]
@aragonc puedes validar el cambio?

**Comment by ywarnier** [comment]
Looks good to me. I was afraid that this might remove variables set via the $htmlHeadXtra variable, but these are stored in the "extra_headers" constant for Twig, not the 'header_extra_content' constant that has been removed here.
