### ISSUE TITLE
Change the "view" button label <enhancement>

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#1605]
Sometimes, the label "Learner View" "Teacher View" is confusing as a user stand point also as sometimes the Chamilo changes the view without being asked by the user.

I suggest changing the button label respectively to "Viewing as: Learner" and "Viewing as: Teacher" and on mouse over use a descriptive pop-up "Change to the Teachers View" "Change to Learners View" or as general alternative: "View mode" "Edit mode" since is not always the teacher that changes the content.

This is easy to change both on translation, web design and on code but, as a change on usability and Chamilo core aspects, should be considered by the developers.

**Comment by ywarnier** [comment]
The text for those buttons is now (and since before your report I believe) "Switch to Student view" and "Switch to Teacher view", so I guess this can be closed. Thank you for your suggestion.
