### ISSUE TITLE
Style: Space between radio buttons and text

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1607]
### Expected behavior / Resultado esperado / Résultat attendu
Deberían haber unos 5 píxeles como mínimo entre el radio botón y el texto por seleccionar.

### Actual behavior / Resultado real / Résultat réel
En la edición de parámetros avanzados de un ejercicio, los textos aparecen pegados a los botones radio.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Crear un ejercicio. Desplegar parámetros avanzados.

**Comment by aragonc** [comment]
Listo arreglado verificar..
![lsti](https://cloud.githubusercontent.com/assets/2940509/25454052/cb49b906-2a90-11e7-9134-2cab51a61d62.png)

**Comment by ywarnier** [comment]
Lo siento, en Firefox los sigo viendo demasiado cerca, y no entiendo porque poner un margin-top (o margin con solo el primer elemento activo) mejora las cosas... Se trata de un espacio entre los radio buttons y el texto.
![align](https://cloud.githubusercontent.com/assets/609839/26029940/21747332-3808-11e7-809a-0db545f77f30.png)

**Comment by aragonc** [comment]
Arreglado verificarlo :+1:

**Comment by ywarnier** [comment]
Now radio buttons are OK but they are dis-aligned with checkboxes and dropdowns :-/

**Comment by ywarnier** [comment]
Not perfect, but better.
