### ISSUE TITLE
Design: social network: friends block - bad picture proportions

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1608]
### Actual behavior / Resultado real / Résultat réel
En la red social, al momento de buscar usuarios, las fichas de usuarios aparecen con la foto disproporcionada (menos ancha que lo correcto).

### Expected behavior / Resultado esperado / Résultat attendu
Que las fotos aparezcan bien en la búsqueda como en el perfil.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Ir a la red social
Buscar usuarios
Mirar las fotos

**Comment by jmontoyaa** [comment]
This was already fixed.

**Comment by ywarnier** [comment]
Tested and approved
