### ISSUE TITLE
Sessions catalogue broken

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1609]
### Expected behavior / Resultado esperado / Résultat attendu
Quiero ver las sesiones en el catálogo de sesiones.

### Actual behavior / Resultado real / Résultat réel
Página blanca.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Dar clic en "catálogo de sesiones".
- Aparece lo siguiente:
`
2017/01/26 23:59:42 [error] 1263#1263: *222 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\ORM\EntityNotFoundException: Entity was not found. in /var/www/chamilo111x/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php:177
Stack trace:
#0 /var/www/chamilo111x/app/cache/__CG__ChamiloCoreBundleEntitySession.php(428): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(DoctrineProxies\__CG__\Chamilo\CoreBundle\Entity\Session), 'getName', Array)
#1 /var/www/chamilo111x/app/cache/__CG__ChamiloCoreBundleEntitySession.php(428): Closure->__invoke(Object(DoctrineProxies\__CG__\Chamilo\CoreBundle\Entity\Session), 'getName', Array)
#2 /var/www/chamilo111x/vendor/twig/twig/lib/Twig/Template.php(672): DoctrineProxies\__CG__\Chamilo\CoreBundle\Entity\Session->getName()
#3 /var/www/chamilo111x/app/cache/twig/1/15/15bb646cb1738791ac66a3ccf2dba598e99cf81d362ec93c3e55b29f5852016e.php(355): Twig_Template->getAttribute(Object(DoctrineProxies\__CG__\Chamilo\CoreBundle\Entity\Session), 'name', Array)
#4 /var/www/chamilo111x/vendor/twig/twig/lib" while reading response header from upstream, client: 127.0.0.1, server: my.chamilo111.net, request: "GET /main/auth/courses.php?action=display_sessions&category_code=&hidden_links=&pageCurrent=1&pageLength=10 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "my.chamilo111.net"
`

**Comment by ywarnier** [comment]
@AngelFQC esta es urgente. La necesito para mañana temprano (hora Lima).

**Comment by AngelFQC** [comment]
Ok. Lo veo lleganso a la oficina

**Comment by AngelFQC** [comment]
@ywarnier No puedo reproducirlo. Puedes borrar caché de Symfony?

**Comment by ywarnier** [comment]
@AngelFQC He probado:
- git pull origin 1.11.x
- chash fct (limpieza de caché)
- composer install (limpieza de autoload)
- php bin/doctrine.php orm:schema-tool:update --dump-sql
...pero sigue saliendo el mismo error.
Te adjunto un dump de solo mi tabla session, por si te ayuda...
[sessions.sql.zip](https://github.com/chamilo/chamilo-lms/files/748023/sessions.sql.zip)

**Comment by AngelFQC** [comment]
Pues... tampoco
![sessions](https://cloud.githubusercontent.com/assets/1697880/22555739/b54812d2-e932-11e6-9739-67d71612edda.png)
Esas son todas?

**Comment by ywarnier** [comment]
Sí... entonces tiene que haber alguna diferencia en una tabla relacionada. Haz mirado si la estructura de la tabla session era la misma que la tuya?

**Comment by AngelFQC** [comment]
Están igual
Quizá sea algun foreing key?... He reinstalado mi chamilo y sin usuarios, cuando ejecuto tu sessions.sql luego me da este error. Que es porque no tengo session_admin
`
[Thu Feb 02 11:06:00.618967 2017] [:error] [pid 10971] [client 127.0.0.1:38582] PHP Fatal error:  Uncaught Doctrine\\ORM\\EntityNotFoundException: Entity was not found. in /var/www/chamilo111x/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php:177\nStack trace:\n#0 /var/www/chamilo111x/app/cache/__CG__ChamiloUserBundleEntityUser.php(428): Doctrine\\ORM\\Proxy\\ProxyFactory->Doctrine\\ORM\\Proxy\\{closure}(Object(DoctrineProxies\\__CG__\\Chamilo\\UserBundle\\Entity\\User), 'getCompleteName', Array)
#1 /var/www/chamilo111x/app/cache/__CG__ChamiloUserBundleEntityUser.php(428): Closure->__invoke(Object(DoctrineProxies\\__CG__\\Chamilo\\UserBundle\\Entity\\User), 'getCompleteName', Array)
#2 /var/www/chamilo111x/main/auth/courses_controller.php(815): DoctrineProxies\\__CG__\\Chamilo\\UserBundle\\Entity\\User->getCompleteName()
#3 /var/www/chamilo111x/main/auth/courses_controller.php(646): CoursesController->getFormatedSessionsBlock(Array)
#4 /var/www/chamilo111x/main/auth/courses.php(239): CoursesController->sessionsList('display_session...', 'Course sessions', Array)
#5 {main}\n  thrown in /var/www/chamilo111x/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php on line 177, referer: http://chamilo111x.dev/main/auth/courses.php
`

**Comment by AngelFQC** [comment]
@ywarnier encontraste el error?

**Comment by ywarnier** [comment]
No, voy a cerrar la tarea. Creo que en su momento estaba debido a una mala relación de FK entre sessions y las tablas de secuencialización (sequence_*)
