### ISSUE TITLE
Modo de mantenimiento | Maintenance (Offline) Mode

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1611]
https://support.chamilo.org/issues/6043 

Descripción

¿Sería posible añadir a Chamilo una opción para activar el modo de mantenimiento para actualizaciones a nuevas versiones, cambio de plantilla Web, etc. de modo que se desactivara el acceso al aula y apareciera un mensaje con información al respecto?

Esta opción ya está disponible en otra aula virtual, en Joomla, o en Wordpress. Sería útil que desde la Administración se pudiera desactivar el acceso al sitio.

English
-------

Maintenance mode is for preventing any users other than administrators from using the site while maintenance is taking place, though it's not designed to prevent user access during version upgrades.

When users attempt to access a course when your site is in maintenance mode, they obtain a message informing them that the site is in maintenance mode. If you wish, you can create a customized maintenance mode message, perhaps stating when the site will be available again or giving the reason for doing maintenance.

Note: The front page of your site will appear as normal when your site is in maintenance mode. Users will only see the maintenance mode message when they attempt to access a course.

**Comment by ywarnier** [comment]
Aunque esta funcionalidad esté deseada, en este momento no tenemos recursos para desarrollarla :'-(

**Comment by NicoDucou** [comment]
Esta funcionalidad ya fue integrada en 1.11.4

Hay un plugin Modo de Mantenimiento : 
![pluginmododemantenimiento](https://user-images.githubusercontent.com/6579268/37255435-a2e623fc-254c-11e8-9a70-3dce1ed990b0.png)

En la configuracion del plugin, se pone la IP del administrador, por defecto se auto rellena con la IP del usuario que esta activando el plugin. Hay que poner la IP correcta porque solo desde este IP se tendra accesso a la plataforma para poder regresarla del modo de mantenimiento.

En la parte baja se crea la pagina que los demas usuarios veran.

![pluginmododemantenimientoconfiguration](https://user-images.githubusercontent.com/6579268/37255697-4a03ca06-2550-11e8-9ea0-3bbd64c922ac.png)


This plugin allows administrators to set the portal in maintenance mode through the change of the .htaccess file located in the root folder of Chamilo.

As such, it requires the web server (user www-data, httpd or nobody) to temporarily have write access to the .htaccess file. Maintaining write access on this file is a security vulnerability, so please only set those permissions for the required time to put your site in maintenance mode, and then return them to non-writable by the web server.
