### ISSUE TITLE
After update. Old user does not appear in social network search.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1614]
When upgrading from chamilo 1.9.8 to 1.11.2.
Everything went well.
However, we are facing a problem in the social network.
We can not send a message, invitations, etc.
Because the search does not recognize any old users anymore.
When entering a name.
It says that you do not have this user.
Administration, in the courses, are all users.
User that is being registered after update.
Appear in social network search.
Someone knows how we can solve.
Thank you

**Comment by jmontoyaa** [comment]
Question: Are you using the "multiple urls"  feature?

- If no:
   Make sure that all your users ids exist in this table "access_url_rel_user" with access_url_id = 1.

- If yes:
Go here and edit the user access to the portal:
main/admin/access_url_edit_users_to_url.php

**Comment by bassuma** [comment]
Thank you so much
I backed up from "access url_rel user" table.
And it's working
We can close this work.
Thank you
