### ISSUE TITLE
Designer of the Social Network after searching.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1617]
Hello.
When performing a search in the social network.
Users appear in disorder.
Image attached.
It is not a search problem.
I think it's some configuration in "css."
Thank you
![social network designer](https://cloud.githubusercontent.com/assets/25286516/22553898/70a38e46-e945-11e6-8462-b5a5e21b160c.jpg)

**Comment by bassuma** [comment]
Hello.
I discovered what is causing the designer to break.
These are the names of the students.
If the student's name is complete.
Your carton is large.
I tested and decreased the name of the third student in the picture.
New image.
Thank you
![resolvido](https://cloud.githubusercontent.com/assets/25286516/22554782/88e6fa8a-e948-11e6-9621-0b9d64918b07.jpg)

**Comment by jmontoyaa** [comment]
I changed the layout a bit to avoid this kind of problems

**Comment by bassuma** [comment]
Hello.
I made the changes.
It was good to search.
But in the link friends.
You can no longer click on the names.
Look.
![search-ok](https://cloud.githubusercontent.com/assets/25286516/22607477/38304e14-ea3f-11e6-9cca-d93e09a00edc.jpg)
![friends](https://cloud.githubusercontent.com/assets/25286516/22607482/3c486d06-ea3f-11e6-8c7a-e3528f6a0d4e.jpg)

**Comment by jmontoyaa** [comment]
Fixed.

**Comment by bassuma** [comment]
Hi, Julio.
I made the file edits.
Now you can click on the name.
More then you go to a white page.
With this error in "test server" mode.

Fatal error: Call to undefined method CourseManager :: getUserInCourseStatus () in /home/public_html/chamilo/main/inc/lib/social.lib.php on line 495

**Comment by jmontoyaa** [comment]
it's better to update all files, are you using git?

**Comment by bassuma** [comment]
I made changes to all the files.
Main / inc / lib / display.lib.php
Main / inc / lib / social.lib.php
  Main / social / friends.php
  Main / social / groups.php
Main / social / search.php
Git? Is it a package for the server?

**Comment by jmontoyaa** [comment]
Also update main/inc/lib/course.lib.php

**Comment by bassuma** [comment]
Hello.
I updated the file.
Main / inc / lib / course.lib.php
The more it breaks the "catalog of courses".
Would you have other files to update?
![2017-02-06 13](https://cloud.githubusercontent.com/assets/25286516/22646522/fb7fcbfe-ec53-11e6-9d7a-8ad7c84ea06b.png)

**Comment by jmontoyaa** [comment]
If you're using 1.11.x i suggest to download the package here:

https://github.com/chamilo/chamilo-lms/tree/1.11.x

And update your files, don't forget to clean your temp/archive files.

**Comment by bassuma** [comment]
Ik.
Got it.
Thank you for your help.
We can close this ticket.
Thank you
