### ISSUE TITLE
Time-limited exercises are looping

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1618]
### Expected behavior / Resultado esperado / Résultat attendu
Cuando el límite de tiempo es alcanzado para un ejercicio, debe mostrarme un popup *legible* y después mandarme a la página de resultados.

### Actual behavior / Resultado real / Résultat réel
Cuando el límite de tiempo es alcanzado, me muestra un popup demasiado pequeño para que aparezca todo el texto. Agrandar popup. Luego, en vez de mandarme a los resultados, refresca la página y me re-aparece el popup y hace un bucle infinito.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- En 1.11.x
- Crear curso
- Crear ejercicio
- Crear 10 preguntas del primer tipo (por ejemplo). Pueden ser 9 copias de una misma pregunta inicial.
- Editar la configuración del ejercicio y seleccionar:
-- sin feedback
-- mostrar solo nota
-- aleatorio
-- 5 preguntas aleatorias
-- número de intentos ilimitado
-- tiempo límite de 1 minuto (no es necesario poner más)
- Registrar un alumno al curso
- Conectarse como alumno
- Entrar al curso + ejercicio y darlo por completo una primera vez
- Entrar nuevamente al ejercicio, responder 3 preguntas y, llegado a la 3ra, esperar que venza el tiempo
- El bucle empieza... (y refresca la página cada 5 segundos)

**Comment by ywarnier** [comment]
![exercise](https://cloud.githubusercontent.com/assets/609839/22554561/cf6aa4da-e960-11e6-9595-65b9979fc5c6.png)

**Comment by jmontoyaa** [comment]
No me aparece el bucle. Cuando terminé el ejercicio la primera vez, le di click al botón "Return to course homepage". Luego hice el ejercicio por segunda vez como se indica y me envia a la página de resultados.

**Comment by jmontoyaa** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/158935/22554959/5a7b8f8e-e962-11e6-93de-dbffe06b230e.png)

**Comment by jmontoyaa** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/158935/22554989/79bbadca-e962-11e6-80f7-27033c4b65f2.png)

**Comment by ywarnier** [comment]
Yes, the config seems correct.

**Comment by jmontoyaa** [comment]
I just sent a fix.

**Comment by ywarnier** [comment]
This fix seemed to have... well, fixed it. Thanks!
