### ISSUE TITLE
The box that displays the classes and narrows.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1625]
Hello.
In administration, link, class.
By clicking to add students.
There is no way to view the student's full name.
How can I change the size of the box.
Which displays the students' names.
In chamilo 1.9.8 it was bigger.
Already on cahmilo 1.11.2.
It's narrow.

I tried to change the file:
/web/assets/bootstrap/dist/css/bootstrap.css
To edit:
@media (min-width: 992px)
.col-md-7 {
     Width: 58.33333333%;
}
Per:
@media (min-width: 992px)
.col-md-7 {
     Width: 98.33333333%;
}
But he does not accept the change.
Thanks for the help.

![chamilo 1 9](https://cloud.githubusercontent.com/assets/25286516/22627800/1a35f3ba-ebb0-11e6-9993-d96c51578333.jpg)

![chamilo 1 11](https://cloud.githubusercontent.com/assets/25286516/22627808/2ef082de-ebb0-11e6-9722-83176c726479.jpg)

**Comment by jmontoyaa** [comment]
Fixed

**Comment by bassuma** [comment]
Hi, Julio.
It looks great.
I'm closing this ticket.
Thank you
