### ISSUE TITLE
In assignments, add the username to the filename

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1635]
### Actual behavior / Resultado real / Résultat réel
As a teacher, when downloading the student assigment files, it is impossible to know whom submitted each. While this might be a "feature" in some cases (to maintain neutrality), clearly in most case it is just hindering the speed of correction.

### Expected behavior / Resultado esperado / Résultat attendu
Add a checkbox inside the assignment definition that says "Add username to downloadable assignments" (requires a new field in the c_student_publication table). When the box is checked, all the names of all files downloaded are prefixed by the "{canonical_username}-".
This is also checked when re-importing the corrected files, so that the prefix is removed automatically (it only makes sense to have a username prefix *outside* Chamilo.

**Comment by ywarnier** [comment]
@jmontoyaa I believe this change was sent to Chamilo 1.11.4, right?

**Comment by jmontoyaa** [comment]
This is already added in 1.11.x the username is added in the filename.

**Comment by ywarnier** [comment]
The question is whether it was added before or after 1.11.4 :-)

**Comment by ywarnier** [comment]
OK, so because of the timeframe here, I'm marking this one as closed because now the supported version is 1.11.6
