### ISSUE TITLE
Exercises: one global comment when finished scoring a student

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1639]
### Current behavior
When scoring an exercise attempt, at the end of the process, we can choose to send an e-mail to the student, but you cannot add any global comment about the exercise for this student.

### Expected behavior
At the end of the test correction, add a textarea with the template of the e-mail that will be sent, so the teacher can edit it and send something different.

This doesn't require any database change: just a process change to make sure the e-mail contents appear and are editable before sending them to the student. We don't need to store that on the system as it will already be sent to the inbox of the user in the message table.

@NicoDucou this has also been requested for the ofaj branch.

**Comment by NicoDucou** [comment]
It has been done with commit https://github.com/chamilo/chamilo-lms/commit/e01349fca6b4d2032cdb6760be27ef089207b452 and validated
