### ISSUE TITLE
The submitted image is not responsive.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1640]
Hello
When adding an image on the portal homepage or above the course created.
If the student accesses through the tablet or cell phone.
The image breaks the layout of the chamilo.
I put this code.
Img {
   Max-width: 100%;
}
In the browser tool preview element.
The image looks good.
Greetings.

![block](https://cloud.githubusercontent.com/assets/25286516/22754665/808c4906-ee27-11e6-8877-c14cbfcd9f93.jpg)
![ok](https://cloud.githubusercontent.com/assets/25286516/22754670/854792f2-ee27-11e6-8dc1-be9b5a99f2cd.jpg)

**Comment by ywarnier** [comment]
In 1.11.2, there is a small checkbox in the preview window with no text next to it. Normally, checking it should make it responsive. The fact that the text didn't appear in 1.11.2 was a bug. It has been fixed in what will become 1.11.4.

**Comment by ywarnier** [comment]
You might need to remove the dimensions of the image (leave them empty) before saving the preview window.

**Comment by bassuma** [comment]
Hello,
Yannick.
I took the test here.
Has box for:
Image caption.
And a box with nothing, has no text.
I clicked on it and it worked.
Thank you for your help.
Closing the ticket.
