### ISSUE TITLE
Assignments: prevent double upload of documents with same names

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1648]
### Current behavior / Resultado actual / Résultat actuel
A student can upload the same document twice.

### Expected behavior / Resultado esperado / Résultat attendu
When a document of the same name is detected, block it and tell the user that document has already been uploaded (ideally, check the MD5 sum instead of just the name).
Apparently, this was already developed by @jloguercio  but disabled by @jmontoyaa by default, so to make everyone happy, this should go into a global setting (for now in configuration.php): 'assignment_prevent_duplicate_upload'

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

@p4pr8n for more info

**Comment by jloguercio** [comment]
Fixed ! https://github.com/chamilo/chamilo-lms/pull/1656

**Comment by jloguercio** [comment]
Olvidé agregarlo también a otros lugares de subida de tareas :
https://github.com/chamilo/chamilo-lms/pull/1658

**Comment by p4pr8n** [comment]
In 1.11.2 I've made the changes in the 5 concerned files (configuration.php, upload.php, upload_from_template.php and work.ajax.php). It works for upload but not for upload (simple). Still able to upload the same file.

**Comment by jloguercio** [comment]
I sent a patch to fix this https://github.com/chamilo/chamilo-lms/pull/1703

regards

**Comment by p4pr8n** [comment]
Patch applied, It works.
Thanks.
