### ISSUE TITLE
Gradebook: internationalization names order not taken into account in table

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1653]
### Current behavior / Resultado actual / Résultat actuel
In the gradebook or the assignment tool (not sure which), the order of firstname, lastname is not respected. Whatever you select, the contrary appears in the list.

### Expected behavior / Resultado esperado / Résultat attendu
This should respect the internationalization setting for that language (set in the name_order array somewhere).

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

@p4pr8n for more info

**Comment by p4pr8n** [comment]
I had to set it manually.


```
--- main/work/work.lib.php      2017-01-30 18:30:30.800000000 +0100
+++ main/work/work.lib.php.orig 2017-01-30 18:29:59.140000000 +0100
@@ -1911,7 +1911,7 @@
                         qualification,
                         weight,
                         allow_text_assignment,
-                        CONCAT (u.lastname," ",u.firstname) as fullname,
+                        CONCAT (u.firstname," ",u.lastname) as fullname,
                         u.username,
                         parent_id,
                         accepted,
```

**Comment by AngelFQC** [comment]
I sent a commit to use `api_get_person_name` function to show the fullname according to `$_configuration['name_order_conventions']`

**Comment by ywarnier** [comment]
Checked and approved.
