### ISSUE TITLE
Admin: add user form: "Add +" broken

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1657]
### Current behavior / Resultado actual / Résultat actuel
When adding a user through the admin form (main/admin/user_add.php), the button "Add+" should actually make you go back to the form (instead of the users list); but it's not.
This is essentially due to the conversion of the form to FormValidator and the use of a double "submit" button. On line 320, you find this:
```
// Submit button
$html_results_enabled[] = $form->createElement('button', 'submit', get_lang('Add'), 'plus', 'primary');
$html_results_enabled[] = $form->createElement('button', 'submit_plus', get_lang('Add').'+', 'plus', 'primary');
```

On line 431, you find this:
```
		if (isset($user['submit_plus'])) {
			//we want to add more. Prepare report message and redirect to the same page (to clean the form)
            Display::addFlash(Display::return_message($message));
			header('Location: user_add.php?sec_token='.$tok);
			exit;
		} else {
			$tok = Security::get_token();
            Display::addFlash(Display::return_message($message));
			header('Location: user_list.php?sec_token='.$tok);
			exit;
		}
```
However, if you dump the $user[] array for a page in French, you see this, even if you use the "Add+" button:
```
... [submit] => Ajouter\n    [submit_plus] => \n)
```

So there is obviously something wrong with the form. I thought maybe it was a question of priority and inverting the two lines at line 231 would help, but then you get:
```
... [submit_plus] => \n    [submit] => Ajouter\n)
```
So no difference in the values, just in the order of the index.

### Expected behavior / Resultado esperado / Résultat attendu
The button "Add" should send you back to the list. The button "Add+" should send you back to the form.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jmontoyaa** [comment]
For me it works well. After adding the user with "add+" i'm redirected to user_add.php using Chrome. 
You're using FF?

**Comment by ywarnier** [comment]
I'll reformulate then. It's the "Add" without "+" that's broken :-)
It doesn't send you back to the list, it sends you back to the form. The issue is that the two buttons do the same thing.

**Comment by ywarnier** [comment]
Yup, that happens with Chrome too.

**Comment by ywarnier** [comment]
Reviewed and approved. Tricky, this one :-)
