### ISSUE TITLE
Error with session courses, the column value (Generated certificate) is always No in admin Reporting page.

### ISSUE THREAD

**Issue by hi-rafa** [chamilo/chamilo-lms#1659]
### Current behavior / Resultado actual / Résultat actuel
The (Generated certificate) value is always NO on  Session courses row.

### Expected behavior / Resultado esperado / Résultat attendu
The (Generated certificate) value of a Session courses row should change if the student has displayed the certificate.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1 - Create a Course "Advanced Catalan Course" and assign an Assessments
2 - Create a Session and assign Course, Teacher, Student to session
3 - Login as a Student and complete the Assessment
4 - Display the certificate ('certificates/index.php?id=4')
5 - Login as an Admin
6 - Go to the Reports page ('main/mySpace/company_reports.php')

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
I think you shouldn't close this one. As I understand, it was merged before your 2 latest commits.
