### ISSUE TITLE
Missing data in Reporting page after creating a session

### ISSUE THREAD

**Issue by hi-rafa** [chamilo/chamilo-lms#1663]
### Current behavior / Resultado actual / Résultat actuel
After the creation of sessions when you go to the Reporting page you will see that the normal courses is missing. (Admin)

### Expected behavior / Resultado esperado / Résultat attendu
The admin should see the info/progress of all the courses and sessions.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1 - Create a Course "Advanced English Course" and assign teacher and student
2 - Go to the Reports page ('main/mySpace/company_reports.php') (you will see Advanced English Course )
3 - Create a Course "Free Italian lesson" 
4 - Create a Session and assign Course (Free Italian lesson), Teacher, Student
5 - Go to the Reports page ('main/mySpace/company_reports.php') (you will see Free Italian lesson but not Advanced English Course)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by hi-rafa** [comment]
Hi @ywarnier 
I would like to know if this is really an Issue or not. If it is an issue would it be correct to show all the courses and session to the admin?
Thank you

**Comment by ywarnier** [comment]
Yes, it would be correct to show all, although usually courses should appear *after* the sessions because the tracking of sessions is supposed to be more important at any present time than the tracking of courses.

**Comment by hi-rafa** [comment]
http://chiesi-enzyme-chamilo.loc/main/mySpace/company_reports.php

Hi @ywarnier 
I found out that the Cooperatives report page is not working with the supervisor role and I do not know which other roles have access to this page.

If I am not wrong the page should work like this: 
Admin
- the admin can see all students sessions
- the admin can see all students courses
Student's superior
- the supervisor can only see his students sessions 
- the supervisor can only see his students courses 

**## Please can you tell me if this is correct and if there is others roles with access to this page and which are their logic.**


Thank you

**Comment by ywarnier** [comment]
The behaviour you describe is correct but so far we have only ever really used it with the admin account.

**Comment by ywarnier** [comment]
@hi-rafa What's the status of this issue?

**Comment by hi-rafa** [comment]
Hi @ywarnier 
The pagination doesn't work properly anymore after I added my code but don't worry next week I will fix it.

**Comment by ywarnier** [comment]
@hi-rafa don't forget about this one (just pinging)

**Comment by ywarnier** [comment]
Moving to 1.11.6 for now unless a last minute intervention allows us to include it in 1.11.4

**Comment by hi-rafa** [comment]
Hi @ywarnier 
Sorry I won't be able to fix this until 2 or 3 weeks.

**Comment by NicoDucou** [comment]
Hi @hi-rafa
Any news on this one to be able to include it in 1.11.6 ?

**Comment by hi-rafa** [comment]
Hi @NicoDucou 
Sorry to not have notify you before but I can't work on this issue anymore.

**Comment by jmontoyaa** [comment]
Closing for lack of feedback.
