### ISSUE TITLE
CKeditor: iframes are not supported

### ISSUE THREAD

**Issue by p4pr8n** [chamilo/chamilo-lms#1666]
### Current behavior / Resultado actual / Résultat actuel
Iframes are not supported since upgrade.

CKeditor wipes iframe tags even if _Allow iframes in HTML Editor_ is set to yes in portal configuration.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Insert in src mode.

```<iframe src="http://www.erickirsch.be/manastrat/" width="1024" height="800"></iframe>```

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by ywarnier** [comment]
This occurs, I believe, since a change made by @jmontoyaa  after 1.11.2.
@jmontoyaa, could you check this? Since some change after 1.11.2, it is impossible to add any embed unless the "allow iframe" setting is set to "Yes".
This is not acceptable because it changes the default behaviour of Chamilo, unless we change the default value of the "allow iframe" setting before the next version (which would be complicated because it involves a database change).

**Comment by jmontoyaa** [comment]
"enable_iframe_inclusion" has to be set to true.

It works for me locally when I create a document here:

main/document/create_document.php

The problem could be that the browser blocks the iframe because it has a different protocol than Chamilo
https/http.

**Comment by jmontoyaa** [comment]
Blocked loading mixed active content “http://www.erickirsch.be/manastrat/”

**Comment by p4pr8n** [comment]
We moved Chamilo to https://. recently, the trouble was already present when we were in http:// with version 1.11.2.
Ckeditor wipes iframe tags when saving.
Were must I set enable_iframe_inclusion ?
The link is also valid with https://www.erickirsch.be/manastrat/ 
Thanks

**Comment by jmontoyaa** [comment]
After changing to "https" it works for me here:

https://1.11.chamilo.org/main/document/showinframes.php?cidReq=ANATOMIE&id_session=0&gidReq=0&gradebook=0&origin=&id=6495


The setting can be found here:

https://1.11.chamilo.org/main/admin/settings.php?search_field=enable_iframe_inclusion&category=search_setting

**Comment by p4pr8n** [comment]
Sorry but this option is already set in Chamilo.
![ckconfig](https://cloud.githubusercontent.com/assets/22977133/22884958/9cd612ee-f1f7-11e6-9aa3-2be50fac37d3.png)

1) Edition in src mode
![ckeditor1](https://cloud.githubusercontent.com/assets/22977133/22884777/eab998b0-f1f6-11e6-9a46-1e475cef463a.png)
2) Saving
![ckeditor2](https://cloud.githubusercontent.com/assets/22977133/22884849/39e7c290-f1f7-11e6-98c8-40e9abc1889a.png)
3) Open editor in src mode after saving
![ckeditor3](https://cloud.githubusercontent.com/assets/22977133/22884891/5ca0d628-f1f7-11e6-996f-78e05f046b17.png)
It's empty.

**Comment by jmontoyaa** [comment]
Now that you mention that this error appear in the introduction tool, this happens because that particular editor blocks iframes. If you want to allow that in your platform you have to add this in your configuration.php file.

`$_configuration['allow_course_introduction_low_security'] = true;`

**Comment by p4pr8n** [comment]
Sorry again. I've edited app/config/configuration.php and add the line. Restart Apache, made a logoff, logon in Chamilo and result is still the same for introduction tool but works effectively out of the introduction tool.

**Comment by jloguercio** [comment]
the configuration value : $_configuration['allow_course_introduction_low_security'] = true;
is added some weeks ago, so i think you need to apply this patch in main/inc/introductionSection.inc.php file :
https://github.com/chamilo/chamilo-lms/pull/1629/files

Regards

**Comment by p4pr8n** [comment]
Patch applied and it works :-).
Thanks a lot.
