### ISSUE TITLE
Announcement: Unable to send with select all option  

### ISSUE THREAD

**Issue by p4pr8n** [chamilo/chamilo-lms#1670]
### Current behavior / Resultado actual / Résultat actuel
Since last upgrade sending an annoucement with select all option makes Chamilo "freeze" (white page).
Certainely due to the number of users. 59 in my test case.
If you select a few users at the time, it works.

### Expected behavior / Resultado esperado / Résultat attendu
In 1.10.8 it was working.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by p4pr8n** [comment]
This is what I get when I try to publish.
Fatal error: Uncaught exception 'Doctrine\DBAL\Types\ConversionException' with message 'Could not convert database value "" to Doctrine Type array' in /var/www/chamilo2016/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php on line 46 Doctrine\DBAL\Types\ConversionException: Could not convert database value "" to Doctrine Type array in /var/www/chamilo2016/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php on line 46 Call Stack: 0.0001 274808 1. {main}() /var/www/chamilo2016/main/announcements/announcements.php:0 0.1438 7216320 2. AnnouncementManager::edit_announcement() /var/www/chamilo2016/main/announcements/announcements.php:505 1.5307 10430352 3. api_item_property_update() /var/www/chamilo2016/main/inc/lib/AnnouncementManager.php:690 1.5319 10434024 4. Doctrine\ORM\EntityManager->find() /var/www/chamilo2016/main/inc/lib/api.lib.php:3713 1.5319 10434776 5. Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadById() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:462 1.5319 10434824 6. Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:730 1.5325 10444760 7. Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:720 1.5325 10445096 8. Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:147 1.5325 10453040 9. Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:69 1.5331 10494864 10. Doctrine\DBAL\Types\ArrayType->convertToPHPValue() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:131

**Comment by ywarnier** [comment]
@p4pr8n what version of PHP do you use?
Does the following command (launched from the Chamilo root directory) show anything to you?
`php bin/doctrine.php orm:schema-tool:update --dump-sql`

**Comment by p4pr8n** [comment]
PHP 5.6.30 (Debian Jessie).
See output in attached file doctrine.txt.
[doctrine.txt](https://github.com/chamilo/chamilo-lms/files/786093/doctrine.txt)

**Comment by ywarnier** [comment]
This might be the issue. It looks (from the attached file) that the upgrade to 1.11.0 didn't go well. All the queries that appear have to be executed on your SQL database.
Take a dump of your current DB, then launch:
`php bin/doctrine.php orm:schema-tool:update --force`
Some of the queries might not work. If they don't, just paste the error messages here and we'll try to solve it.

**Comment by p4pr8n** [comment]
Updating database schema...


  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1':
  SQLSTATE[HY000]: General error: 1025 Error on rename of './chamilo2016/course_rel_user_catalogue' to './chamilo2016/#sql2-33e-11336d' (errno: 152)



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './chamilo2016/course_rel_user_catalogue' to './chamilo2016/#sql2-33e-11336d' (errno: 152)



  [PDOException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './chamilo2016/course_rel_user_catalogue' to './chamilo2016/#sql2-33e-11336d' (errno: 152)


orm:schema-tool:update [--complete] [--dump-sql] [-f|--force]

**Comment by ywarnier** [comment]
I need the details of the course_rel_user_catalogue table to understand the reason for this error (which requires you to execute this query in the DB):
`SHOW CREATE TABLE course_rel_user_catalogue;`

**Comment by p4pr8n** [comment]
```
mysql> SHOW CREATE TABLE course_rel_user_catalogue;
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table                     | Create Table
                                                                                                                                                    |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| course_rel_user_catalogue | CREATE TABLE `course_rel_user_catalogue` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `c_id` int(11) DEFAULT NULL,
  `visible` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `c_id` (`c_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
+---------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by ywarnier** [comment]
There doesn't seem to be any foreign key, so you should be able to skip the dropping of these keys, which means you would have to execute those SQL queries by hand, using:
`php bin/doctrine.php orm:schema-tool:update --dump-sql`
and executing them by little groups directly into SQL (or you would have to create those foreign key to simulate they were there to start with).

**Comment by p4pr8n** [comment]
```
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
```
If I want to recreate these, where can I find the structure ?

**Comment by p4pr8n** [comment]
I've executed all the 74 lines by hand :-)
Result is OK
```
Nothing to update - your database is already in sync with the current entity metadata.
```
But error is still present.
```
Fatal error: Uncaught exception 'Doctrine\DBAL\Types\ConversionException' with message 'Could not convert database value "" to Doctrine Type array' in /var/www/chamilo2016/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php on line 46 Doctrine\DBAL\Types\ConversionException: Could not convert database value "" to Doctrine Type array in /var/www/chamilo2016/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php on line 46 Call Stack: 0.0004 274736 1. {main}() /var/www/chamilo2016/main/announcements/announcements.php:0 0.1587 6802864 2. AnnouncementManager::add_announcement() /var/www/chamilo2016/main/announcements/announcements.php:540 1.5884 10034600 3. api_item_property_update() /var/www/chamilo2016/main/inc/lib/AnnouncementManager.php:482 1.5893 10038264 4. Doctrine\ORM\EntityManager->find() /var/www/chamilo2016/main/inc/lib/api.lib.php:3713 1.5894 10039016 5. Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadById() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:462 1.5894 10039064 6. Doctrine\ORM\Persisters\Entity\BasicEntityPersister->load() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:730 1.5898 10048976 7. Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php:720 1.5898 10049312 8. Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php:147 1.5898 10057320 9. Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:69 1.5903 10098512 10. Doctrine\DBAL\Types\ArrayType->convertToPHPValue() /var/www/chamilo2016/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php:131 
```

**Comment by p4pr8n** [comment]
Made de test with a brand new installation and it works.
Something went wrong with upgrade. What can I do now ? It is very embarrassing for us. :-(

Thanks

**Comment by p4pr8n** [comment]
At least. Some users had an empty value in row roles. Updating it with the default value 'a:0:{}' was the solution.

**Comment by ywarnier** [comment]
Sorry to come back on this... in which table was the "roles" row empty?

**Comment by p4pr8n** [comment]
In the user table.
I have also noticed some strange values for students accounts.
```
mysql> select lastname,roles from user where not roles='a:0:{}' ;
+-------------+------------------------------------+
| lastname    | roles                              |
+-------------+------------------------------------+
| BAGINSKA    | a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";} |
| GUANO GUANO | a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";} |
| DEFALQUE    | a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";} |
| Lecatenaire | a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";} |
| HEKSTER     | a:1:{i:0;s:16:"ROLE_SUPER_ADMIN";} |
+-------------+------------------------------------+
5 rows in set (0.00 sec)
```

**Comment by ywarnier** [comment]
@jmontoyaa is it normal that the "roles" column would have some real use in 1.11? Isn't that something meant *only* for 2.0 onwards?

**Comment by jmontoyaa** [comment]
Is used in ofaj.

**Comment by ywarnier** [comment]
Then maybe there's something missing in the upgrade process that could explain why it didn't complete this field for Philip... Can you check it's OK in the upgrade process?

**Comment by ywarnier** [comment]
Just as a note, doing an
```
update user set roles = 'a:0:{}' where roles = '';
```
should have fixed the issue above.
