### ISSUE TITLE
Sortie 1.11.4

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1672]
Bonjour,

Est-il possible de connaitre la date de sortie de la version 1.11.4 ?

En vous remerciant,

Didier

**Comment by ywarnier** [comment]
Pas encore de date prévue. J'espère personnellement pouvoir publier en mars 2017.

**Comment by DidierR30** [comment]
Merci beaucoup pour votre réponse.
Cordialement,
Didier
