### ISSUE TITLE
La copie d'un questionnaire "Apparier" cause une erreur de réponse

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#1675]
### Current behavior / Resultado actual / Résultat actuel
En copiant une questionnaire avec une question "Apparier'", le nouveau questionnaire n'a pas de bonne réponse
### Expected behavior / Resultado esperado / Résultat attendu
Les éléments appariés devraient demeurer les mêmes
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.12 et 1.11x du 14 février 2017
![apparier](https://cloud.githubusercontent.com/assets/22802716/22952895/d39f7bae-f2dc-11e6-9525-a8d90f78bff7.jpg)

**Comment by meuhland** [comment]
Sounds like like a duplicate of #1602 to me.

**Comment by simbulu** [comment]
Yes, #1602 describes this issue, and adds that the same happens with question of the type "Match by dragging". The problem is  triggered by running /main/coursecopy/copy_course.php

**Comment by jmontoyaa** [comment]
Fixed in 1.11.x

**Comment by andreboivin** [comment]
Problème corrigé. Merci Julio tu es génial!
