### ISSUE TITLE
Global announcements: date range is always rejected

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1681]
### Current behavior / Resultado actual / Résultat actuel
Since today, editing a global announcement cannot be edited or created: the date range is always rejected (it says "Information requise" in French and marks the dates range field in red).

### Expected behavior / Resultado esperado / Résultat attendu
Editing and creating announcements should be possible (unless, of course, the date is not valid)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* Go to admin section
* Click the "Global announcements" link
* try to create one, with any date range that you select
* error message appears and nothing is saved

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x at commit 1f691bf97750e65a4d

**Comment by ywarnier** [comment]
When I change line 161 of system_announcements.php to indicate that the daterangepicker element is *not* required, then no message appears anymore but the announcement is not created either, so I'm not sure where the problem comes from...

**Comment by jmontoyaa** [comment]
It's working for me

**Comment by ywarnier** [comment]
Yes, I think @jloguercio fixed it.
