### ISSUE TITLE
Announcements: Add feature to make announcement always visible

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1682]
### Current behavior / Resultado actual / Résultat actuel
At the moment, if you add an announcement, you always have to choose who you send it to. There is no feature to say "all students can see it, always", so when you create an annoucement for all and *then* subscribe a new user to the course, the new user cannot see past announcements.

### Expected behavior / Resultado esperado / Résultat attendu
When a new user joins a course, he should see announcements that were sent to all students earlier on.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* Create a course
* Subscribe 2 students
* Create an announcement and select all students as destinatories
* All students can see the announcement in the announcement tool
* Subscribe 1 new student
* Log in as the new student
* Enter the announcements tool: the announcement is not visible

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jderriks** [comment]
This would be nice!  We currently edit the course homepage to reach "late" students.
Should the same happen with announcements to groups? So that when you register for a group you should see all announcements that were sent to this group earlier?

**Comment by jderriks** [comment]
It appears that this already works as requested as long as the announcement is sent to a group or "EVERYONE" (i.e. empty addressee list) and not explicitly to x selected persons.

A message to x distinct people will be stored as x different rows in the property table but a message to 'everyone' is marked as such and a new course member will be able to see those messages.

However, the user interface for selecting "Everyone" is not clear on this. I think a seperate "ALL" group in the addressee select box would be more helpful than the current message to leave this box empty if you mean "everyone".

**Comment by ywarnier** [comment]
Assigne to Nicolas for thorough review of current situation in 2.0 before closing or reassigning.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 
When creating a course announcement the content block in the form (https://testing24.beeznest.com/main/announcements/announcements.php?cid=1&sid=0&gid=0&gradebook=0&origin=&action=add) do not allow to type any text, it does not respond when clicking in the blank part (the menu respond but nothing below).

![image](https://github.com/chamilo/chamilo-lms/assets/6579268/65d176f3-1bb4-4864-aacd-6e13a0196c89)

And if the content block is empty then it generates an error when validating the form : 
```
Warning: Array to string conversion
ExceptionLogs 1Stack Trace
ErrorException
in public/main/inc/lib/pear/HTML/QuickForm/Renderer/Default.php (line 382)
                $required,                $error            );            if ($error) {                $element->setAttribute('class', $element->getAttribute('class').' p-invalid ');            }            $this->_html .= str_replace('{element}', $element->toHtml(), $html);        } elseif (!empty($this->_groupElementTemplate)) {            $html = str_replace('{label}', $element->getLabel(), $this->_groupElementTemplate);
HTML_QuickForm_Renderer_Default->renderElement()
in public/main/inc/lib/pear/HTML/QuickForm/element.php (line 463)
HTML_QuickForm_element->accept()
in public/main/inc/lib/pear/HTML/QuickForm.php (line 1610)
HTML_QuickForm->accept()
in public/main/inc/lib/pear/HTML/QuickForm.php (line 1648)
HTML_QuickForm->toHtml()
in public/main/inc/lib/formvalidator/FormValidator.class.php (line 1276)
FormValidator->returnForm()
in public/main/announcements/announcements.php (line 782)

```

**Comment by NicoDucou** [comment]
For the visualization of announcement it stills works in Chamilo 2 as it was in Chamilo 1.11.x thant is to say that if you do not select any specific user to whom to send the announcement then it will be visible for new student subscribed to the course after the announcement was created.

**Comment by christianbeeznest** [comment]
Hi @NicoDucou,

Indeed, it is working the visualization of announcement for new student subscribed, about issue with editor , it needs be upgraded to last version or using vue for this tool. I think should be created other ticket for it.

**Comment by NicoDucou** [comment]
Announcement creation is now working since the correction of tinyMCE integration.
So I created an announcement and did not assign any users to send it to.
Then I subscribed a new student to the course and the student could see the announcement.
So all good with this feature.

Closing the task
