### ISSUE TITLE
Error in the creation of a new Learning path

### ISSUE THREAD

**Issue by hi-rafa** [chamilo/chamilo-lms#1694]
### Current behavior / Resultado actual / Résultat actuel
Php error in the creation of a new Learning path

<img width="1160" alt="1" src="https://cloud.githubusercontent.com/assets/3813277/23118621/1d1d3b78-f755-11e6-9d5f-2b80da8f0f70.png">
<img width="1223" alt="2" src="https://cloud.githubusercontent.com/assets/3813277/23118625/1f2dae34-f755-11e6-8e95-a2cf44ff515f.png">
<img width="1186" alt="3" src="https://cloud.githubusercontent.com/assets/3813277/23118633/20d00c64-f755-11e6-8691-4e3ee966c33a.png">

### Expected behavior / Resultado esperado / Résultat attendu
Step 1 Learning path

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
admin > courses > selected course > Learning path > new Learning path

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jmontoyaa** [comment]
You need to update chamilo with the latest code in 1.11.x 
Also execute a composer update

**Comment by hi-rafa** [comment]
<img width="1251" alt="screen shot 2017-02-22 at 9 31 41 am" src="https://cloud.githubusercontent.com/assets/3813277/23203232/f99c321a-f8e1-11e6-94f1-3b5cf434c174.png">
![screen shot 2017-02-22 at 9 29 05 am 2](https://cloud.githubusercontent.com/assets/3813277/23203233/fb11d000-f8e1-11e6-938f-30b5c01fef5c.png)
<img width="1275" alt="screen shot 2017-02-22 at 9 29 15 am" src="https://cloud.githubusercontent.com/assets/3813277/23203237/fc7c27e2-f8e1-11e6-8fab-946315aea48b.png">


Error still occurs.

**Comment by jmontoyaa** [comment]
Check if you have this file:
`
main/inc/lib/formvalidator/Element/DatePicker.php`

Check if the file is correctly added in the autoloader here:

vendor/composer/autoload_classmap.php

`'DatePicker' => $baseDir . '/main/inc/lib/formvalidator/Element/DatePicker.php',`

**Comment by jmontoyaa** [comment]
try also doing a git checkout of 1.11.x

**Comment by ywarnier** [comment]
Sometimes (when using development versions), composer mixes things up and deleting the whole vendor/ directory, then issuing a "composer update" again will do a cleaner job than just composer update.

**Comment by ywarnier** [comment]
Just as an additional note (to avoid forgetting about that detail), this is MAMP, so on a Mac OSX. Maybe that's causing another dependency issue somewhere (not sure any composer-loaded lib has dependencies on that, but it might).

**Comment by jderriks** [comment]
Tested this on Linux and Mac+brew with apache and php7.1 and the datepicker error is repeatable.

**Comment by jderriks** [comment]
Better workaround until the "compser update" or "composer dump-autoload" creates the right autoload files: edit and add these lines in vendor/composer files:
autoload_classmap.php:    'DatePicker' => $baseDir . '/main/inc/lib/formvalidator/Element/DatePicker.php',
autoload_static.php:        'DatePicker' => __DIR__ . '/../..' . '/main/inc/lib/formvalidator/Element/DatePicker.php',

Somehow these are not allways created by composer.

**Comment by ywarnier** [comment]
Interesting! Thanks for that.

**Comment by jderriks** [comment]
Finaly found the cause:
https://github.com/chamilo/chamilo-lms/pull/1897
