### ISSUE TITLE
Clear cache before database initialization failed

### ISSUE THREAD

**Issue by stonetwig** [chamilo/chamilo-lms#1707]
### Current behavior / Resultado actual / Résultat actuel
Clear cache before database initialization failed when installing Chamilo on Windowswith php 7.0.15, and with IIS as a web server.

I get the following exception:
`Cannot rename "..\Documents\Code\chamilo-lms\app\cache\dev" to "..\Documents\Code\chamilo-lms\app\cache\de~".`

I have added permissions on the cache folder for all users in the system, including the IUSR but it should run as the local administrator which should be fine.

### Expected behavior / Resultado esperado / Résultat attendu

It should be able to clear cache.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Install on php 7.0.15 on Windows Professional with IIS.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
2

Any ideas?

**Comment by ywarnier** [comment]
Are you sure you're using Chamilo 2? Chamilo 2 is a development version. There is no documented installation procedure that has been tried enough just yet...

**Comment by stonetwig** [comment]
Well yes, but since I found no solution to this issue I moved on with another project. Closing issue :)
