### ISSUE TITLE
[1.11.2] Menu Buttons not loading

### ISSUE THREAD

**Issue by aqblanco** [chamilo/chamilo-lms#1714]
This issue started happening after upgrading our platform **from 1.9.6 to 1.11.2**, on a **PHP 7.1.2** server,  When loading pages like the admin settings one (_/main/admin/settings.php_), we couldn't get the menu icons to load. The img tag was being inserted without any attribute on it. 

The scripts were throwing an _Illegal string offset_ warning on lines **839, 842 and 845** from _main/inc/lib/display.lib.php_ script, being that lines where the image url, title and alternative text are set. 

I replaced line **839** (_$additional_attributes['src'] = $image_path;_) with _$additional_attributes = array('src' => $image_path);_ and the issue got solved

**Comment by jmontoyaa** [comment]
Can you copy and paste the all PHP error?

**Comment by aqblanco** [comment]
Sure, this are the three warnings:

_Warning: Illegal string offset 'src' in /var/www/aula/main/inc/lib/display.lib.php on line 839
Warning: Illegal string offset 'alt' in /var/www/aula/main/inc/lib/display.lib.php on line 842
Warning: Illegal string offset 'title' in /var/www/aula/main/inc/lib/display.lib.php on line 845_

**Comment by aqblanco** [comment]
Working for me using the attached commit.

**Comment by Nganyu** [comment]
I had that similar problem and used your solution. It just worked perfectly. Thanks very much aqblanco.
