### ISSUE TITLE
array(1) { ["expired_on"]=> NULL } string(73) "UPDATE c_lp SET expired_on = :expired_on WHERE c_id = '3' AND id = '3' " array(1) { ["expired_on"]=> NULL } array(1) { ["c_id = ? AND id = ?"]=> array(2) { [0]=> string(1) "3" [1]=> int(3) } }

### ISSUE THREAD

**Issue by kikesandi** [chamilo/chamilo-lms#1715]
### Current behavior / Resultado actual / Résultat actuel

Una vez que he creado una lección, si deseo modificarle los parámetros (añadir una fotografía, cambiar una hoja de estilo, o cualquier configuración interna de la lección), aparece este mensaje al guardar la configuración:

array(1) { ["expired_on"]=> NULL } string(73) "UPDATE c_lp SET expired_on = :expired_on WHERE c_id = '3' AND id = '3' " array(1) { ["expired_on"]=> NULL } array(1) { ["c_id = ? AND id = ?"]=> array(2) { [0]=> string(1) "3" [1]=> int(3) } } Notice: Undefined property: scorm::$id in /home/educaci6/public_html/main/lp/lp_controller.php on line 983 Warning: Cannot modify header information - headers already sent by (output started at /home/educaci6/public_html/main/inc/lib/database.lib.php:456) in /home/educaci6/public_html/main/lp/lp_controller.php on line 1020

### Expected behavior / Resultado esperado / Résultat attendu

Se espera que se guarde la configuración nueva, y se continúe con la edición normal.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Ingreso al curso
Entro a lecciones
En lecciones selecciono la acción de "Configuración del curso"
En este punto selecciono cualquier parámetro y lo cambio
Le doy "Guardar parámetros de la lección"
Aparece esta leyenda: 
`array(1) { ["expired_on"]=> NULL } string(73) "UPDATE c_lp SET expired_on = :expired_on WHERE c_id = '3' AND id = '3' " array(1) { ["expired_on"]=> NULL } array(1) { ["c_id = ? AND id = ?"]=> array(2) { [0]=> string(1) "3" [1]=> int(3) } } Notice: Undefined property: scorm::$id in /home/educaci6/public_html/main/lp/lp_controller.php on line 983 Warning: Cannot modify header information - headers already sent by (output started at /home/educaci6/public_html/main/inc/lib/database.lib.php:456) in /home/educaci6/public_html/main/lp/lp_controller.php on line 1020`

La nueva configuración se guarda, pero es inconveniente ver este mensaje.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.2

**Comment by jmontoyaa** [comment]
This was already fixed in Chamilo

**Comment by kikesandi** [comment]
Solo actualizo y listo?

**Comment by jmontoyaa** [comment]
Si con la última version 1.11.x y un composer update

**Comment by kikesandi** [comment]
Perfecto... gracias

**Comment by Wajalot** [comment]
Hola. Pues yo tengo la versión 1.11.2 y me salta el mismo el error.

**Comment by kikesandi** [comment]
He estado dándole seguimiento a mi plataforma y sucede cuando tengo una lección creada y modifico los parámetros (imagen de la lección, fecha de publicación, fecha de fin de la publicación, asignarle una categoría... etc)

**Comment by Wajalot** [comment]
Exacto. Es al editarla, aunque los cambios los hace, devuelve ese error.

**Comment by kikesandi** [comment]
Mi plataforma es la 1.11.2

**Comment by kikesandi** [comment]
Como se hace el composer update @jmontoyaa ?

**Comment by ywarnier** [comment]
@kikesandi Checkea los README.md y CONTRIBUTING.md en la carpeta principal de la rama 1.11.x de Chamilo. Ojo, eso *no es* un procedimiento para iniciantes en programación (no digo que lo seas) y requiere el control total de su máquina/servidor y por lo mínimo 2GB de RAM. Si no conoces composer, es mejor esperar la versión 1.11.4 dentro de unas semanas.
Por mientras cierro la tarea. Si llegas a actualizar a la versión de desarrollo o una vez publicada la 1.11.4 y ves que el problema subsiste, puedes reabrir esta tarea, pero nosotros por ahora en la versión de desarrollo no llegamos a reproducirlo.
