### ISSUE TITLE
Defining a prerequisite on a test with minimum of 0/20 blocks progress

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1718]
### Current behavior / Resultado actual / Résultat actuel
When a student takes a test in a learning path with a prerequisite for the next step set to a minimum of 0/20 (so whatever result is OK) and he gets 40% (8/20), he is blocked.

### Expected behavior / Resultado esperado / Résultat attendu
The prerequisite should take into account the minimum score.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Create a test scored on a max of 20 points (can be only one question, no problem)
- Create a learning path with 3 documents
- Add the exercise after the 1st document and before the 2nd document
- Set the prerequisite for the 2nd document to be the test, but do not change the minimum or maximum score
- Take the learning path as a student and fail
- You cannot move to document 2 (prerequisites not completed)
 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x of the 17th of Feb 2017

**Comment by AngelFQC** [comment]
Prerequisitos
![prerequisites](https://cloud.githubusercontent.com/assets/1697880/24048950/82bbeec8-0af8-11e7-87a4-8f87d1ca8674.png)
Failed test
![page-shot-2017-3-17 my organisation - my campus - plex placement exam](https://cloud.githubusercontent.com/assets/1697880/24048990/a4d3eca4-0af8-11e7-807a-08e85bc9beb2.png)
Next item
![page-shot-2017-3-17 my organisation - my campus - plex placement exam 1](https://cloud.githubusercontent.com/assets/1697880/24049027/bd729f62-0af8-11e7-9f91-ff4a872914c8.png)
