### ISSUE TITLE
Exercises not editable when included in LP - Add explanation

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1720]
### Current behavior / Resultado actual / Résultat actuel
When an exercise is included in a learning path, the list of questions cannot be edited (you cannot add more questions). This is OK in terms of behaviour, but it confuses the user because there is no explanation as to why it is frozen.

### Expected behavior / Resultado esperado / Résultat attendu
Add a message to indicate the exercise is frozen because it is included in "the following learning paths" and give the list of learning paths in which it is included.

For example:
"This exercise cannot be edited because it is currently included in a learning path, which means that editing it can have unexpected consequences. If you are absolutely sure you need to edit it, you can either remove it from the learning path, edit it and include it again, or you can generate a copy of this exercise and edit the copy, then decide whether you want to use the copy or this item in the same or in another learning path. Removing an item from the learning path will also remove students tracking for this item. The current learning paths that include this exercise are:
- Learning path 1 title
- Learning path 2 title
"

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Create an exercise with 1 question
- Create a learning path
- Include the exercise into the learning path
- Return to the exercises tool
- Click the pencil icon to edit the exercise
- Edition options are greyed out

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by AngelFQC** [comment]
Agregué el mensaje que aparece en la lista de ejercicios cuando están en lecciones
"This exercise has been included in a learning path, so it cannot be accessed by students directly from here. If you want to put the same exercise available through the exercises tool, please make a copy of the current exercise using the copy icon."

**Comment by ywarnier** [comment]
Tested and approved
