### ISSUE TITLE
As a session general coach, the tracking user icon doesn't show

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1723]
### Current behavior / Resultado actual / Résultat actuel
In the users list in a session-course, I cannot see the "tracking" icon next to the students if I am a general session coach (the course-session coach can see it).

### Expected behavior / Resultado esperado / Résultat attendu
A general coach should see the icon.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Create a session and set yourself as general coach
- Add a course to the session but do *not* set yourself as a course coach
- Add students to this session
- Enter the session-course and go to the users list
- Next to the "Unsubscribe" button for students, you cannot see the "tracking" icon. You should.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x (2/3/2017)

**Comment by jmontoyaa** [comment]
1. If i'm login as a platform admin and I'm the general coach, I can see the unsubscribe and and the reporting button:

![selection_004](https://cloud.githubusercontent.com/assets/158935/23601374/74f9637a-024b-11e7-9b09-c64f29bcdc38.png)

2. If I'm login as teacher and I'm a general coach I can't see the unsubscribe or the reporting button:

![selection_005](https://cloud.githubusercontent.com/assets/158935/23601385/7c278bcc-024b-11e7-81e5-91454a527387.png)

**Comment by ywarnier** [comment]
Sorry, in this second case, I should see the reporting icon (not the unsubscribe button). There was a little flaw in my procedure to reproduce.
The first case is OK, don't change it.

**Comment by ywarnier** [comment]
Checked and approved.
