### ISSUE TITLE
PHPMailer 5.1

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#1732]
### Current behavior / Resultado actual / Résultat actuel
currently, prebundled packages still ship with vulnerable phpmailer
### Expected behavior / Resultado esperado / Résultat attendu
at least the phpmailer folder could be upgraded to latest version until new releas ships with swiftmailer
(yes, have seen the changes)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
always, just visit main/inc/lib/phpmailer/changelog.txt

### Chamilo Version / Versión de Chamilo / Version de Chamilo
latest version linked from associations website

**Comment by jmontoyaa** [comment]
We have a patched version of PHPMailer that was report some time ago:
https://github.com/chamilo/chamilo-lms/commit/069845f08759cce4aa3693235e8d0a9a131ca35b
The current class has different modifications made in Chamilo.

**Comment by ywarnier** [comment]
We should be releasing 1.11.4 at the end of the month, which is why we have not released a new version just for the (2) security patches so far. See https://support.chamilo.org/projects/chamilo-18/wiki/Security_issues (I just update the last issue with links to the different patches)
