### ISSUE TITLE
Chamilo 1.11.2: Cache problem with css changes

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1735]
### Current behavior / Resultado actual / Résultat actuel

Si se realizan modificaciones CSS en un tema (editando el archivo default.css) éstas desaparecen cuando se ejecuta la limpieza del directorio archive.

### Expected behavior / Resultado esperado / Résultat attendu

Los cambios realizados en un CSS no deberían ser afectados por la limpieza de archive

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Modificar cualquier estilo del archivo default.css del tema activo en Chamilo.
Ejecutar después la limpieza del directorio archive. Los cambios habrán desaparecido.

Este comportamiento se produce porque existe una duplicidad de las hojas de estilo, ya que se encuentran en dos rutas diferentes:
web/css/themes/
app/Resources/public/css/themes/

No entendemos el sentido de que exista esta duplicidad, pero al parecer, el borrado del directorio archive restablece los valores de CSS existentes en la segunda ruta, cuando normalmente los CSS se localizan en la primera.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by ywarnier** [comment]
Hola, es porque usan el método equivocado para actualizar los estilos.
Los estilos dentro de web/ nunca se modifican. Esta carpeta es actualizada automáticamente por el proceso de limpieza del directorio archive (que se *tiene* que ejecutar después de cambiar un estilo).
Donde se *tiene* que modificar es dentro de app/Resources/public/css/themes/ :-)

**Comment by ywarnier** [comment]
Alternativamente (y la mejor solución cuando aplican caché a nivel del servidor web) pueden cambiar el estilo en local y subir una nueva versión del estilo cada vez, con un nombre de carpeta con un sufijo numérico.

**Comment by nosolored** [comment]
Ok, tendremos en cuenta que esa es la ruta para actualizar los CSS
La opción de subir cada vez una versión de la hoja de estilos diferente es engorrosa, si se tiene acceso FTP es mucho más cómodo hacerlo directamente, especialmente si son pequeños cambios.
Lo que no me queda muy claro es la utilidad que tiene el tener los estilos duplicados en dos rutas, creo que es confuso y ocupan un espacio innecesario, ¿no lo veis así?

**Comment by ywarnier** [comment]
Es una regla de Symfony, y se basa en que una de las carpetas es más protegida (normalmente, eso todavía no está en Chamilo) que la otra. La idea es que la carpeta web/ contenga *únicamente* recursos estáticos (imágenes, CSS y demás) y pueda ser identificada claramente como tal.
Ya en Chamilo 2.0 debería empezar a evidenciarse más.
