### ISSUE TITLE
Erreur lors de la suppression d'un cours auquel est inscrite une classe.

### ISSUE THREAD

**Issue by lzebdi** [chamilo/chamilo-lms#1736]
### Current behavior / Resultado actual / Résultat actuel

Une erreur se produit lors de la suppression d'un cours auquel est inscrite une classe. Cette manipulation imprudente crée "un cours fantôme" provoquant une "fatal error" lors de la la modification de la liste des cours de la classe.

### Expected behavior / Resultado esperado / Résultat attendu

Peut-être une indication sur le guide administrateur Chamilo, précisant qu'il est nécessaire de désinscrire le cours à la classe avant sa suppression pour éviter l'erreur bloquant les futurs inscriptions des cours à cette même classe.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Créer classe
- Inscrire des utilisateurs dans la classe
- Créer cours 
- Inscrire des cours à la classe
- Allez à Administration 
- puis Liste des cours
- Supprimer cours 
- Revenir à Administration
- Classe
- Inscrire des cours à la classe
- Fatal error

### Chamilo Version / Versión de Chamilo / Version de Chamilo

https://1.11.chamilo.org/main/admin/add_courses_to_usergroup.php?id=4 

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND user_id IN (3)' at line 2' in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 90 PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND user_id IN (3)' at line 2 in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 104 Call Stack: 0.0004 318128 1. {main}() /var/www/1.11.chamilo.org/www/main/admin/add_courses_to_usergroup.php:0 0.2211 18796384 2. UserGroup->subscribe_courses_to_usergroup() /var/www/1.11.chamilo.org/www/main/admin/add_courses_to_usergroup.php:82 0.2214 18799072 3. UserGroup->unsubscribe_courses_from_usergroup() /var/www/1.11.chamilo.org/www/main/inc/lib/usergroup.lib.php:680 0.2263 20290456 4. CourseManager::unsubscribe_user() /var/www/1.11.chamilo.org/www/main/inc/lib/usergroup.lib.php:711 0.2264 20291528 5. Database::query() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:386 0.2264 20291528 6. Doctrine\DBAL\Connection->executeQuery() /var/www/1.11.chamilo.org/www/main/inc/lib/database.lib.php:363 0.2264 20291896 7. Doctrine\DBAL\Driver\PDOConnection->query() /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:852 0.2264 20292440 8. PDO->query() /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104 Doctrine\DBAL\Driver\PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND user_id IN (3)' at line 2 in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 106 Call Stack: 0.0004 318128 1. {main}() /var/www/1.11.chamilo.org/www/main/admin/add_courses_to_usergroup.php:0 0.2211 18796384 2. UserGroup->subscribe_courses_to_usergroup() /var/www/1.11.chamilo.org/www/main/admin/add_courses_to_usergroup.php:82 0.2214 18799072 3. UserGroup->unsubscribe_courses_from_usergroup() /var/www/1.11.chamilo.org/www/main/inc/lib/usergroup.lib.php:680 0.2263 20290456 4. CourseManager::unsubscribe_user() /var/www/1.11.chamilo.org/www/main/inc/lib/usergroup.lib.php:711 0.2264 20291528 5. Database::query() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:386 0.2264 20291528 6. Doctrine\DBAL\Connection->executeQuery() /var/www/1.11.chamilo.org/www/main/inc/lib/database.lib.php:363 0.2264 20291896 7. Doctrine\DBAL\Driver\PDOConnection->query() /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:852 Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM c_group_rel_user WHERE c_id = AND user_id IN (3)': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND user_id IN (3)' at line 2 in /var/www/1.11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 90 Call Stack: 0.0004 318128 1. {main}() /var/www/1.11.chamilo.org/www/main/admin/add_courses_to_usergroup.php:0 0.2211 18796384 2. UserGroup->subscribe_courses_to_usergroup() /var/www/1.11.chamilo.org/www/main/admin/add_courses_to_usergroup.php:82 0.2214 18799072 3. UserGroup->unsubscribe_courses_from_usergroup() /var/www/1.11.chamilo.org/www/main/inc/lib/usergroup.lib.php:680 0.2263 20290456 4. CourseManager::unsubscribe_user() /var/www/1.11.chamilo.org/www/main/inc/lib/usergroup.lib.php:711 0.2264 20291528 5. Database::query() /var/www/1.11.chamilo.org/www/main/inc/lib/course.lib.php:386 0.2264 20291528 6. Doctrine\DBAL\Connection->executeQuery() /var/www/1.11.chamilo.org/www/main/inc/lib/database.lib.php:363

**Comment by jmontoyaa** [comment]
I added a fix. It should work now.

**Comment by lzebdi** [comment]
Merci jmontoyaa
