### ISSUE TITLE
Autoevaluación (retroalimentación inmediata)

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1737]
Hello.
In:
https://1.11.chamilo.org
I created the course:
https://1.11.chamilo.org/courses/AAFI/index.php
To test the exam template:
"Autoevaluación (retroalimentación inmediata)"
Congratulations on adding this model to Chamilo.
However, I am facing some problems.
As :
Slow to go to the next question.
And then the end of the test. He does not score.
Thanks for listening.
![nao_pontua](https://cloud.githubusercontent.com/assets/25286516/23823783/b6eeec18-0648-11e7-91fb-830281fad939.jpg)

**Comment by jmontoyaa** [comment]
I just add several fixes. Now it should work.

**Comment by bassuma** [comment]
Hello.
I did the file exchange:
"exercise.lib.php  = 9fb2207"
I cleared the cache in the chamilo.
I used the firefox browser.
The problems of:
1 - Transition to another question is fast and normal.
2 - Test result is working.
3 - Unfortunately, there is a delay to appreciate the feedback box.
I did this test video.
https://youtu.be/BnrhrB7AqX8
Thanks for the quick response.

**Comment by ywarnier** [comment]
The slowliness issue should be a *new* issue (so we can close this one). Otherwise it makes it complicated to track.

**Comment by bassuma** [comment]
ok
