### ISSUE TITLE
Responsive Images

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#1738]
Just did a fresh clean install on 1.11.2 and the issue of responsive images has re-appeared.  We know that a check box was added to insert responsive images (Caption for this in 1.11.4?)  but this seems to have no effect in the Learning Path.  It works in the Tool Introduction.

Is it still not possible to add a resonive image into a Learning Path?

**Comment by jmontoyaa** [comment]
Can you provide an example here?

https://1.11.chamilo.org

Please follow the guidelines for contributing.

**Comment by ConsultPW** [comment]
Thanks Julio,

Cannot repeat on 1.11.chamilo as it seems we don't have trainer access now ( If you change Consult.PW to trainer access we can replicate there.)

**Meanwhile there is full admin access and an example on the clean install we did for test purposes at www.paulwolstencroft.com    User: Julio  Pass: Chamilo1303**

### Current behavior / Resultado actual / Résultat actuel
Unable to set a responsive image in the Learning Path.  Using non-captioned tick box works in introduction tools but not in main Learning Path.
All other platform functions seem to work OK

### Expected behavior / Resultado esperado / Résultat attendu
Selecting the check box should make the image responsive when adding images in the Learning Path.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Tested on a clean new install and  course area to ensure issue not related to any mods on our production platform.
Insrted image at 1280 wide to intro tools , checking box for responsive image.  Worked eveywhere except in Learning Path
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2 using  Parallels Plesk 12 on Ubuntu 14.04  PHP 5.5.9

**Comment by bassuma** [comment]
Hello.
I hope you can contribute with this information.
In the prnts I took.
It shows that in the chamilo https://1.11.chamilo.org.
You do not have the option in the picture box to choose "responsive".
At my installation when choosing an image.
For front cover or a course.
You only have the space to dial.
It does not have the "responsive" caption.
As Yannick Warnier explained to me.
However, only the cover for the course works.
On the learning route does not work.
Thank you

![01](https://cloud.githubusercontent.com/assets/25286516/23947736/dbb71552-095e-11e7-9e77-99629e186c7a.png)
![02](https://cloud.githubusercontent.com/assets/25286516/23947738/dbb80638-095e-11e7-8421-0b0640f240b8.png)
![003](https://cloud.githubusercontent.com/assets/25286516/23947739/dbb9769e-095e-11e7-91ec-239d59b230d9.png)
![04](https://cloud.githubusercontent.com/assets/25286516/23947737/dbb78bd6-095e-11e7-82e2-a8e2eebf69ca.png)

![meu-01](https://cloud.githubusercontent.com/assets/25286516/23947754/e90fd644-095e-11e7-844b-dfc304e6993c.jpg)
![ok-02](https://cloud.githubusercontent.com/assets/25286516/23947762/ed106e66-095e-11e7-8783-d3e44405334b.jpg)
![aprendizagem-no](https://cloud.githubusercontent.com/assets/25286516/23947769/f196bd00-095e-11e7-97ae-b48f7a0635c9.jpg)
![no-worg](https://cloud.githubusercontent.com/assets/25286516/23947771/f589153e-095e-11e7-88ea-1657376d3cda.jpg)

**Comment by ConsultPW** [comment]
Yes, this is confirming what we are saying.  It is not currently possible (1.11.2) to laod a responsive image into a Learning Path.   Courses do not therefore display correctly on mobile devices.
Video example at : https://www.youtube.com/watch?v=p2RBOuHjeOM

**Comment by ConsultPW** [comment]
Please can you change the access of ConsultPW at  <https://1.11.chamilo.org> https://1.11.chamilo.org to ‘trainer’ so we can provide examples there.

Thanks,
Paul

 

 



Paul Wolstencroft BSc, DipM, Chartered FCIM, MIEP, MIoD

Mob:   07887 800822

Web:    <http://www.consult.pw/> www.consult.pw 

Email:   <mailto:paul@consult.pw> paul@consult.pw 

Skype:  paul_wolstencroft

LinkedIn:  <http://www.linkedin.com/in/consultpw> www.linkedin.com/in/consultpw

**Comment by bassuma** [comment]
Hi,
Paul.
Just create a trainer account.
Go in:
Https://1.11.chamilo.org/main/auth/inscription.php
Choose your profile:
"create course areas".
I hope I have helped.

**Comment by ConsultPW** [comment]
Example added on 1.11,chamilo - 'Responsive Images in Learning Paths'

**Comment by ywarnier** [comment]
This is related to 03b5452264b. I believe a later refresh of the library might have deleted the checkbox again.

**Comment by ConsultPW** [comment]
Yes, the refresh probably deleted the checkbox but what we did not realise earlier was that the checkbox worked in all other areas but NOT in the Learning Path.    It is possible in 1.11.2 to add a responsive image for tool introductions or path intros but checking the box has no effect in the Learning Path where it is crucial.

 

This is related to  <https://github.com/chamilo/chamilo-lms/commit/03b5452264b8624f09e95bf54d4cbe1220a0de13> 03b5452. I believe a later refresh of the library might have deleted the checkbox again..  <https://github.com/notifications/beacon/AUO88xKZTQIe3fV6cpjj0mEEm9L9e_o5ks5rnp9PgaJpZM4MaQb5.gif>

**Comment by ConsultPW** [comment]
Have been experimenting with CK Editor DOCUMENT EDITOR as opposed to the ARTICLE EDITOR to get back to what we had in 1.10.8.  This seems to work OK and is the same as in the Joomla installations we use.  Can this eiditor be uses rather than the article editor to get back the facility for responsibe images with space set around them.   (MB.  It has been upgraded since 1.11.2 launch.  https://github.com/ckeditor/ckeditor-docs-samples/tree/master/editors

**Comment by ConsultPW** [comment]
Thanks Angel - That seems to work fine.  Are we limited to the CK ARTICLE editor or is it possible to get back the DOCUMENT editor as in 1.10.8?

**Comment by ywarnier** [comment]
Hi @ConsultPW, article vs document are just different lists of tools and CSS as far as we are aware. Editor's tools can be configured in your template (for example for the default template: main/template/default/javascript/editor/ckeditor/config_js.tpl). The customization of CKeditor should be done following your needs on *your* portal, not in Chamilo.
In the vas majority of cases, we need the article mode (without a page appearance) rather than the document mode. For a specific implementation, please contact our development team for a quote: info@beeznest.com
