### ISSUE TITLE
bug  V. 1.10.6 al crear pagina de wiki 

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1743]
Buenas tardes tengo un bug  en la parte de wiki  el docente no puedo añadir una pagina, sales este mensaje 
![error en wiki](https://cloud.githubusercontent.com/assets/20644209/23863944/14d9d7f6-07df-11e7-956a-ba0815776b90.JPG)

Reproducido en la version 1.10.6

**Comment by ywarnier** [comment]
Hola, parece que algun administrador bloqueó la edición de este wiki. Solo un administrador puede desbloquearlo, según una mirada rápida al código que se encuentra en main/wiki/wiki.inc.php, función check_addnewpagelock().

**Comment by fergimon** [comment]
Cordial Saludo

Gracias yannick por  su colaboración revisando el archivo de esta version y con 1.10.8  no veo ningún cambio, incluso remplace toda la carpeta y sigue sin funcionar.

**Comment by ywarnier** [comment]
Cuando se publique la versión 1.11.4, sugiero actualizar e intentar nuevamente. Por mientras, no podemos reproducirlo en la versión de desarrollo para la 1.11.4.

**Comment by NicoDucou** [comment]
@fergimon Se pudo actualizar a 1.11.4 o 1.11.6 para probar si se resolvio el problema ?
Gravias por la respuesta para poder cerrar este tarea.

**Comment by ywarnier** [comment]
Cerrando por no poder reproducir. No dudar en abrir nuevamente si tiene mayor información.
