### ISSUE TITLE
Part of the ticket does not translate.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1744]
Hello.
By putting the chamilo in my language.
There is a problem with the ticket.
Even containing all the translation of the ticket in:
Trad4all.inc.php
It shows in English.
The strange thing is that even I translating the file into English for your language.
It continues showing in English.
Thanks for your help.
Thank you.

![ticket-01](https://cloud.githubusercontent.com/assets/25286516/23880742/5becdd8c-0834-11e7-8837-c45a57868db3.jpg)

**Comment by jmontoyaa** [comment]
You have to update the categories edition setting here:

ticket_allow_category_edition

`main/admin/settings.php?search_field=ticket_allow_category_edition&submit_button=&_qf__search_settings=&category=search_setting
`

Then you should go here to edit the categories:

`main/ticket/categories.php?project_id=1`

**Comment by bassuma** [comment]
OK.
Got it.
Not anymore for the file "trad4all.inc.php".
Thanks for your help.
Closing the ticket.
Thank you.
