### ISSUE TITLE
Deprecated phpunit?

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1750]
I found here that phpunit classes are deprecated ...

https://github.com/chamilo/chamilo-lms/blob/1.11.x/tests/README.md#phpunit

So we can delete those files?

**Comment by ywarnier** [comment]
Yes, considering now we have a much more functional Behat setup. Unit testing is still important, but we will re-introduce it in due time.

**Comment by jmontoyaa** [comment]
Got it.

**Comment by jmontoyaa** [comment]
I'm going to delete also "simpletest" (unused since 2009)
