### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by SatyanJ** [chamilo/chamilo-lms#1751]
## Context 
We are three students in a Grenoble's IT engineering school. During this semester we'll be participating on a open source project (Chamilo). We've decide to improve accessibility in Chamilo's app base on ARIA's guideline and various plugins that detect such issues. 
As of right now, I've already done simple fixes (both merged) to familiarize with the projet. 
I'm not sure openning a issue is the right thing to do so if we should consider another approach let us know ! :+1: 

## Issues found so far ( I'll update that list as we found them). 
1. No label in some forms, these are useful to know which edittext or spinner does what.
![no_label_for_edittext](https://cloud.githubusercontent.com/assets/19304198/23917498/d4c62ef0-08ef-11e7-90df-e8f4e1ff3b3f.png) _Words marked yellow should be label of the red forms_

 

_(cc @moy)_

**Comment by ywarnier** [comment]
Hi @SatyanJ and @moy,
It depends on what you want to do. Your IRC message was seen this morning but you didn't leave us much time to answer.

1.11.x is the right branch to work on for now, although we might soon be moving to the master branch. If we move to the master branch soon, we will make a merge to ensure that we have most of 1.11.x in it.

Opening issues is alright and it will allow you to build a Pull Request referring to that issue (with the hash sign and the issue ID). We will label those issues with "Enhancement" as they do not affect the working state of Chamilo and they do not provide a "new feature" in the sense in which we usually understand it (although they do provide improvements for people with special needs).

Anything else I can help you with?

**Comment by SatyanJ** [comment]
Sorry for this morning I had internet issue and the service kept on timing out. So we'll be working on 1.11.X. 

I don't have any questions right know. 
By the way, @moy is the teacher which is following our project.

**Comment by ywarnier** [comment]
I'm closing this now. Just send PR or issues whenever you have a specific topic :-)
