### ISSUE TITLE
vChamilo plugin file upload

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1758]
### Current behavior / Resultado actual / Résultat actuel
When enabling the vChamilo plugin, in an instance, when uploading an image in the root directory of the popup window, the image is not linked correctly. All subfolders work correctly.

### Expected behavior / Resultado esperado / Résultat attendu
The images should show correctly in the root folder.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* Setup vChamilo
* Create an instance
* Connect on the instance
* Create a course (as admin)
* In the course introduction, upload an image and save

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

![file-upload](https://cloud.githubusercontent.com/assets/609839/24010174/1402c046-0a45-11e7-9f62-b6af985abfb7.png)
![file-upload2](https://cloud.githubusercontent.com/assets/609839/24010178/1757baee-0a45-11e7-9253-aaceb8777461.png)

**Comment by ywarnier** [comment]
@jmontoyaa didn't you already solve that with PACA?

**Comment by jmontoyaa** [comment]
@ywarnier  yes

You have to configure the URLs:

* Archive URL 
* Home URL 
* Upload URL 

Here:

plugin/vchamilo/views/editinstance.php?vid=XXX

**Comment by ywarnier** [comment]
When I do that, I get this:
```
[Fri Mar 17 18:05:21.987776 2017] [:error] [pid 3598] [client 190.117.193.98:39880] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'archive_url' in 'field list'' in /var/www/capa.beeznest.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/capa.beeznest.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/capa.beeznest.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/capa.beeznest.com/www/main/inc/lib/database.lib.php(488): Doctrine\\DBAL\\Statement->execute(Array)\n#3 /var/www/capa.beeznest.com/www/plugin/vchamilo/views/editinstance.php(55): Database::update('vchamilo', Array, Array, false)\n#4 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'archive_url' in 'field list'' in /var/www/capa.beeznest.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93\nSta in /var/www/capa.beeznest.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71, referer: https://capa.beeznest.com/plugin/vchamilo/views/editinstance.php?vid=19
```
The README.md has some upgrade procedures but none that talk about an archive_url field.

**Comment by ywarnier** [comment]
I've added that in 3720bd89 (pushing soon)
