### ISSUE TITLE
Add hooks to delete users in user-related plugin tables

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1767]
### Current behavior / Resultado actual / Résultat actuel
At the moment, when the BigBlueButton conference plugin is enabled and we delete a user that was previously in a meeting, a FOREIGN KEY database error is avoided through this patch: https://github.com/chamilo/chamilo-lms/commit/73c79d2d52a319ec7f944bbbe4999455fa952aaa#diff-54a0e60306c5293cc3e5e0579ea80b89R723

### Expected behavior / Resultado esperado / Résultat attendu
This prevents the proper, independent, development of a plugin, as each plugin would need its own patch in the core. Instead, use the hook mechanism (already exists for user creation) to make sure the user record is deleted from the plugin table.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Install the BBB plugin
Open a conference
Join with a user you will later delete
As admin, delete the corresponding user
(actually, to reproduce an issue this should be done with any plugin creating a foreign key on the users table)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by AngelFQC** [comment]
Currently in BBB plugin has no foreign key from user or other table. 904f6b72f28aec9c91a3c552f1681d5f552d57bc

But I sent a twice commits related to this issue.

c51a213e5e360bf1d0ee4d1072b55acf9c0d456d To add a method that will be executed when deleting course, session or user. Without the hooks system. But each plugin must implement them when they are creating tables with foreign keys from user, course, and session tables.
2898d5ff9ca785f7d171b41dbee2ddd76d06a84b  To implement the new methods in LTI and StudentFollowUp plugins to avoid issues related to foreign keys

**Comment by ywarnier** [comment]
This seems to have worked for the production portals we tested it on, so I'm approving this (with the special observation that these new functions should be transferred to hooks for 2.0)
