### ISSUE TITLE
Add math formula editors to CKeditor of answers 

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1768]
### Current behavior / Resultado actual / Résultat actuel
When the math formula editors are enabled for questions in exercises, they are not enabled for answers. This has been reported to me by a teacher (don't remember whom) and it seem to make a lot of sense.

### Expected behavior / Resultado esperado / Résultat attendu
For any type of science courses, it is useful to have a formula editor (Mathjax?) in the answer editors, to allow students to answer with formulas.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Answer any question that lets you type text.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
This file seems like a good place to start: https://github.com/chamilo/chamilo-lms/commit/c3d3f9501861abb2a11184c870980817241be907

**Comment by AngelFQC** [comment]
MathJax works with `include_asciimathml_script` and `enabled_mathjax` settings enabled

But when save a question or doc, the formula does not works, because the formula need a backslash but in database the backslash is escaped

**Comment by NicoDucou** [comment]
AngelFQC it has already been added with this commit : https://github.com/chamilo/chamilo-lms/commit/887119debe446121d7c16a541ba598dd91a07aec

Is it something different that you were trying ? Because it worked for me and for the client who ask for this feature. Otherwise tell me how to reproduce the problem to test it again.

**Comment by ywarnier** [comment]
The commit indeed fixes it.
