### ISSUE TITLE
Error al instalar chamilo con la última versión del repositorio 

### ISSUE THREAD

**Issue by miky96es** [chamilo/chamilo-lms#1769]
### Current behavior / Resultado actual / Résultat actuel
Fallo al instalar chamilo desde el repositorio de github de la rama 1.11.x 
![image](https://cloud.githubusercontent.com/assets/17494657/24145795/1e8bdd6c-0e33-11e7-9c9c-fa03c1aa69cc.png)

### Expected behavior / Resultado esperado / Résultat attendu
Instalar correctamente chamilo
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1.Descargar el ultimo repositorio de chamilo de Github
![image](https://cloud.githubusercontent.com/assets/17494657/24145909/a3336c24-0e33-11e7-9e23-9e970655fc6b.png)

2.Ponerse en la rama 1.11.x y hacer un pull
![image](https://cloud.githubusercontent.com/assets/17494657/24145970/e7ece6ce-0e33-11e7-82f2-bf7c103d078f.png)

3.Instalar los componentes de composer
![image](https://cloud.githubusercontent.com/assets/17494657/24145996/fb662c4c-0e33-11e7-8fa2-3fce554f41bf.png)

4.Instalar Chamilo  
En el paso 7 es cuando sale el fatal error.
![image](https://cloud.githubusercontent.com/assets/17494657/24145795/1e8bdd6c-0e33-11e7-9c9c-fa03c1aa69cc.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.X

**Comment by AngelFQC** [comment]
@miky96es qué versión de PHP tienes instalado en tu servidor?

**Comment by miky96es** [comment]
Esto pasa con windows 7, XAMP y php versión 7.0 y versión 5.4 (probado con ambas)
Cuando aparece un error de instalación hecho por el annotation exception , debemos hacer los siguientes comandos: 

composer clearcache 
composer dump-autoload 
composer require indigophp/doctrine-annotation-autoload 
composer dump-autoload 
composer update 
composer install

**Comment by ywarnier** [comment]
Gracias @miky96es por dar el seguimiento. Nosotros no usamos Windows para instalar ni probar Chamilo como servidor. No nos da suficientes libertades.

**Comment by diomedes05** [comment]
hola, disculpen la molestia pero tengo el mismo error que @miky96es con el archivo "\lib\Doctrine\Common\Annotations\AnnotationException.php" me da un error fatal y no encuentro la manera de solucionarlo 
![untitled](https://user-images.githubusercontent.com/25284416/30188464-7b0acb44-93fc-11e7-8f09-0f364a36378a.png)
