### ISSUE TITLE
Error while trying to install Chamilo-lms-1.11.2-308MB + patch chamilo-1.11.x-94,62MB.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1776]
Hello.
When installing the original 1.11.2 chamilo.
And upload the patch later.
He breaks the chamilo.
So I tried to join the two on the server and try to install.
But he gives an error in the end.
Not letting me complete the installation.
I would have a way to circumvent that mistake.
Thanks for listening

![installation-process-execution](https://cloud.githubusercontent.com/assets/25286516/24203700/364c7f02-0ef5-11e7-9efc-02dc04c8761c.jpg)

**Comment by ywarnier** [comment]
Hi @bassuma, making partial updates without following the right procedure (look into the CONTRIBUTING.md) is not recommended and can lead to this kind of errors; which then require more time from us to help you. This is not sustainable.
Please wait for 1.11.4 beta (in a few days) or use https://1.11.chamilo.org to test

**Comment by bassuma** [comment]
ok
