### ISSUE TITLE
Autoevaluación - Slow response.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1778]
Hello.
When creating a self-assessment exam.
The delay in restoring the response.
Tested on:
https://1.11.chamilo.org/courses/ATE/index.php?id_session=0
https://youtu.be/BnrhrB7AqX8
Thank you

**Comment by ywarnier** [comment]
Speed issues are not usually something we fix as a community as they require many hours and very specific contexts.
I will leave this open for later scrutiny, but don't expect a swift answer on this. You can hire Chamilo official providers services to look into this faster if you want.

**Comment by bassuma** [comment]
I look forward to the next version to see how the tool behaves.
Closing the ticket.
