### ISSUE TITLE
Issues with FIB questions - refs #1505

### ISSUE THREAD

**Issue by DidierR30** [chamilo/chamilo-lms#1784]
Application du correctif #1505
Petit problème suite au remplacement des 2 fichiers :
J'ai remplacé les 2 fichiers sur ma version 1.11.2 : j'ai la visualisation de la correction mais les étudiants ont faux aux différents texte à trous : la réponse n'ai pas prise en compte comme si l'étudiant n'avait rien écrit!
Du coup j'ai remis les 2 fichiers de la version 1.11.2 et cette fois les réponses sont bien prises en compte.

**Comment by ywarnier** [comment]
Didier, il est fort probable que le problème soit causé par les dépendances envers d'autres librairies qui ont été modifiées entretemps.
Pourrais-tu tester ton cas d'utilisation sur https://1.11.chamilo.org? (compte admin/admin)
Tu peux commenter simplement dans la #1505 pour que nous la ré-ouvrions, mais il nous faut d'abord un cas concret sur une plateforme commune, ce pourquoi je t'envoie vers https://1.11.chamilo.org

**Comment by DidierR30** [comment]
voir #1505 
Cela fonctionne
Merci
