### ISSUE TITLE
Not possible to edit drawings from SVGedit

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1785]
### Current behavior
As a teacher, I cannot re-edit an SVG image initially created with SVGEdit. An error message tells me I am not authorized on this page.
Furthermore, I get completely disconnect from the platform when I try.
This last point is particularly worrying to me, given we recently talked about small changes in the error message to send you back to the previous page. I hope this doesn't affect all users getting an access error message in any context.

### Expected behavior
Be able to use the pencil icon on an SVG image to edit it.

### Steps to reproduce
As a teacher:
- Create a course
- Go to documents
- Click the "Drawing" tool
- Create a drawing
- Save (default option "image.svg" is fine)
- In the list of document, click the "pencil" icon (edit) on the SVG image
- You get an error message saying you are not allowed, and your session is completely deleted

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.* 20170323

**Comment by jmontoyaa** [comment]
I tried here and it works for me: 

https://1.11.chamilo.org/main/document/document.php?cidReq=SVGTESTJULIO&id_session=0&gidReq=0&gradebook=0&origin=&curdirpath=%2F

Tested with latest chrome.

**Comment by ywarnier** [comment]
Works for me too now. I don't know what it was.
