### ISSUE TITLE
Add text-less illustrations about WebRTC activation

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1787]
When using the global chat to start a videoconference, the WebRTC activation process (to allow webcam and microphone to be used) is still relatively new to most users, so it should be illustrated to make it easier (like BigBlueButton does) or like the image in this section: https://medium.com/@pastith/feeling-safer-online-with-firefox-b9fe13af6600#74f9

**Comment by ywarnier** [comment]
Something like this:
$WebRTCDialogHelp = "To enable WebRTC in your browser (if it supports it), make sure you click on the information icon on the left of the URL and then authorize the use of the webcam and microphone.";
With the following image:
![webrtc-fr](https://cloud.githubusercontent.com/assets/609839/26041939/ad15462a-38f6-11e7-9005-0c06d0150df0.png)

**Comment by AngelFQC** [comment]
Upgrade simpleWebRTC to v2.2
And show message to allow browser permissions

**Comment by ywarnier** [comment]
Translations imported. Tested and approved. Thanks!
