### ISSUE TITLE
PHPMailer uses deprecated preg_replace() syntax for apparently no reason

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1788]
### Current behavior
In class.phpmailer.php::EncodeQ() method, and apparently in other methods as well, the class makes use of a deprecated syntax of preg_replace('/.../e', x, y) where "e" means eval. Then 'x' is a form that apparently needs to be eval'ed. However, 'x' is usually something like this:
```
"'='.sprintf('%02X', ord('\\1'))"
```
which, as far as I can see, could very well be translated to something like this:
```
'='.sprintf('%02X', ord('\\1'))
```
(and the 'e' could be removed)
The calls deprecation alerts are "hidden" by a `@` sign, but... obviously this is not ideal. Maybe just updating the PHPMailer library would do.

**Comment by jmontoyaa** [comment]
PHPMailer is not used anymore in Chamilo2

**Comment by wladimiravila** [comment]
@ywarnier please update your composer
