### ISSUE TITLE
Wiki: editing a page that is not the homepage sends back to wiki homepage without change

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1790]
### Current behavior / Resultado actual / Résultat actuel
When editing a wiki page that is not the homepage, the wiki tool sends you back to the wiki's homepage and does not take the change into account.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- as admin
- create course
- open wiki tool
- edit homepage and create link to secondary page
- edit secondary page
- save
- you're back to wiki home. The other page is not saved.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jderriks** [comment]
Cannot reproduce the issue if you save the home page first. If you don't, I get this screen where where hitting the plus icon doesn't help:
<img width="540" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/25990108/cf5533ca-36fe-11e7-9c79-4d0aeca97a83.png">

**Comment by ywarnier** [comment]
Indeed. Issue not happening anymore. The usability issue the "+" button should be registered as an enhancement for future versions, but not really a big deal for now.
