### ISSUE TITLE
Timeout on exercise won't show on the report

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#1791]
### Current behavior / Resultado actual / Résultat actuel
As admin, on previewing an test/exercise with a time limit and not completing the preview, the timer will continue, the result will not be on the report and so, not allowing to erase the result,  and trying to preview it again causes a loop on the timeout warning.

Needed to directly remove the row from database.

### Expected behavior / Resultado esperado / Résultat attendu
The try/preview is showed on the report as a test or at least recorded so it could be erased.
The 'finalize' button on the pop-up warning ends the test and allows for future previews.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a test.
Put some time limit.
Save it and start the preview. - do not finish it
After time set as limit, try to preview it again.
an error pop-up shows, but cannot finalize the test;
![2017-03-29 14_08_42-cob - gestores iob - fundamentos da administracao esportiva](https://cloud.githubusercontent.com/assets/1764993/24467060/5f0aacfe-1489-11e7-8a6a-90d50d4d32c0.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by ywarnier** [comment]
I like the proposal, and I didn't catch that unfinished exercises didn't appear in the report.
I'm not sure we'll fix it exactly how you suggest, but we'll make those tests that have passed their due time appear in the results and offer the teacher an option to mark them as "Finished".

**Comment by ywarnier** [comment]
I have added support for 2 "unfinished" states in the exercises report screen.

![new-quiz-states](https://cloud.githubusercontent.com/assets/609839/24488773/e51dc8b2-14de-11e7-966a-cbd421207228.png)

This doesn't change much for the final user, but it does for the teachers, who can now see all unfinished attempts and close them if not "ongoing" anymore.

Is that enough for you, or do you still think we should modify something else for the students?

**Comment by marshel** [comment]
Great solution my view. Will try to update my systems ASAP. Thanks.
