### ISSUE TITLE
Skills wheel = Gray page.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1793]
### Current behavior / Resultado actual / Résultat actuel
Hello.
In social network, when accessing the Skills wheel.
You go to a gray page.
### Expected behavior / Resultado esperado / Résultat attendu
When should you go for a wheel with courses
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Access.
https://1.11.chamilo.org/main/social/home.php.
In Skill.
Click Skills wheel.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by bassuma** [comment]
I tested today on:
Https://1.11.chamilo.org/
Problem has been resolved.
Closing the ticket.

**Comment by jloguercio** [comment]
Yep fixed here : https://github.com/chamilo/chamilo-lms/commit/b90565686e5228720f5515920368c0e370622f92

Regards
