### ISSUE TITLE
Quiz: Distribution of questions by categories doesn't work

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1795]
### Current behavior
When I create questions in categories and establish a distribution by categories in the quiz configuration and select only a few questions for each category, it still shows me all the questions.

### Expected behavior
If I select only 2 questions randomly by category, and I have 2 categories, it should show me only 4 questions in total.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- create a quiz
- create 1 question and copy it 5 times (you now have 6 questions)
- create 2 question categories ("easy" and "difficult" for example)
- assign 3 questions to the "easy" category, and 3 questions to the "difficult" category
- edit the quiz configuration
- set distribution of questions "by categories randomly, with random questions"
- configure 2 questions (instead of -1) for category "easy", 2 questions for category "difficult" and 0 question for "General"
- preview the test
- you get 6 questions (instead of 2x2=4)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x 1/4/2017

**Comment by ywarnier** [comment]
OK, this is much better *but* I can see 2 remaining related issues:

1) when editing the questions list as a teacher, I can only see 4 questions (in the case described above, in the questions list (where I can edit questions) I should still see my 6 questions. It's when I *take* the test (in preview mode or as a student) that I can only see 4 (2 of each category).
![questions-list](https://cloud.githubusercontent.com/assets/609839/24621136/1cca0110-1866-11e7-966a-0d203a6a2db6.png)
(there are 6 questions in my list, normally, and there should always be 6 questions for the teacher in the "edit" list)

2) when selecting the last mode (random categories with random questions), the test still shows random questions but questions by categories... ordered. I mean: if I selected 2 questions of category "easy" and 2 questions of category "difficult", the *category* is selected at random, and so if it picks "difficult" and then "basic", I will first see all the questions of the "difficult" category, and then all the questions of the "easy" category. Like this (questions 1-3 are easy, and questions 4-6 are difficult):
![questions](https://cloud.githubusercontent.com/assets/609839/24621057/be9a1ba2-1865-11e7-958b-9c7dcdfb937d.png)
Instead, I should get (sometimes) all questions of all categories mixed. Something like:
* Easy - Question 1
* Difficult - Question 5
* Easy - Question 3
* Difficult - Question 4

(alternance between easy and difficult)

**Comment by jmontoyaa** [comment]
1. I added a fix for that.
2. I don't remember exactly how that feature should work. It seems is a new feature currently it works like this:

- Easy Question a
- Easy Question b
- Difficult  Question c
- Difficult  Question d

or

- Difficult  Question c
- Difficult  Question d
- Easy Question a
- Easy Question b

The "category random"  feature is about the order of the categories:
"Easy", "Difficult" or "Difficult",  Easy.

What you want here is a new type ... alternate categories between questions.
I don't remember adding that at least in 1.11.x

I found some other ordering options that are not implemented in 1.11.x:

EX_Q_SELECTION_CATEGORIES_RANDOM_QUESTIONS_ORDERED_NO_GROUPED
EX_Q_SELECTION_CATEGORIES_RANDOM_QUESTIONS_RANDOM_NO_GROUPED
EX_Q_SELECTION_CATEGORIES_ORDERED_BY_PARENT_QUESTIONS_ORDERED
EX_Q_SELECTION_CATEGORIES_ORDERED_BY_PARENT_QUESTIONS_RANDOM

The one in this case is 

EX_Q_SELECTION_CATEGORIES_RANDOM_QUESTIONS_RANDOM

**Comment by ywarnier** [comment]
Yes, maybe it's a new type. You can leave it like it is for now. It is likely we will have some budget soon to rework a little on the exercises (like we did a few years ago, in a simpler form).

**Comment by ywarnier** [comment]
I'll review the task before closing it (but not right now).
