### ISSUE TITLE
Error Api Learning Paths scorm

### ISSUE THREAD

**Issue by hi-rafa** [chamilo/chamilo-lms#1796]
### Current behavior / Resultado actual / Résultat actuel
At the end of the scorm exercise chamilo set progress 100% independently of the result.

### Expected behavior / Resultado esperado / Résultat attendu
The progress value should remain 0% if the students has failed
 
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. Create course and Set up  a new learning path by importing a SCORM
2. Assign Student to the course
3. Login as Student
4. Courses > Learning paths > click on the activity 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

<img width="1210" alt="screen shot 2017-04-03 at 10 58 58 am" src="https://cloud.githubusercontent.com/assets/3813277/24602992/6f99ff8c-185f-11e7-8eef-4ee4996c91fa.png">
<img width="1213" alt="screen shot 2017-04-03 at 11 00 46 am" src="https://cloud.githubusercontent.com/assets/3813277/24602993/7242070c-185f-11e7-8b41-b288cb6887df.png">
<img width="1212" alt="screen shot 2017-04-03 at 11 01 25 am" src="https://cloud.githubusercontent.com/assets/3813277/24603000/757fab90-185f-11e7-81c6-3616e23601e3.png">
<img width="1220" alt="screen shot 2017-04-03 at 11 03 56 am" src="https://cloud.githubusercontent.com/assets/3813277/24603003/7786f3f8-185f-11e7-8fda-b39af99684ad.png">

<hr>

![screen shot 2017-04-03 at 12 06 26 pm](https://cloud.githubusercontent.com/assets/3813277/24605161/06ab50a8-1868-11e7-913e-3d620d034b1a.png)

![screen shot 2017-04-03 at 12 07 32 pm](https://cloud.githubusercontent.com/assets/3813277/24605166/09e16f96-1868-11e7-8a7e-daa61ef4930c.png)

![screen shot 2017-04-03 at 12 08 11 pm](https://cloud.githubusercontent.com/assets/3813277/24605168/0d030cd4-1868-11e7-92b8-bc18ba8c7449.png)

![screen shot 2017-04-03 at 12 08 22 pm](https://cloud.githubusercontent.com/assets/3813277/24605176/10f6f04e-1868-11e7-9c78-abbc5e6eade0.png)

![screen shot 2017-04-03 at 12 26 02 pm](https://cloud.githubusercontent.com/assets/3813277/24605370/dc685cea-1868-11e7-81be-ff36e522bd86.png)

**Comment by ywarnier** [comment]
@hi-rafa it is very likely the issue here is the SCORM content. It has to return a status of "success" or "completed" specifically. Obtaining 100% is not enough, as per rules of the SCORM 1.2 Runtime Environment.

**Comment by hi-rafa** [comment]
Hi @ywarnier but shouldn't chamilo set Progress 0% if SCORM activity is not "success" or "completed"?

**Comment by hi-rafa** [comment]
Hi @ywarnier,
Sorry but I am almost 100% sure that the problem is the API of chamilo. 
I found out that the status is not updated after the first activity attempt.
**Example**
The student does the activity for first time but he fails so the status is saved as Failed.
The second time the student does the activity and he Pass/Complete but chamilo api does save the result.

**Comment by hi-rafa** [comment]
Hi @ywarnier 
I can't send you the SCORM package 1.2 because of privacy content, but I have been told that this error occurs with any other SCORM package 1.2. I am very aware of the complexity of SCORM API, I have spent already more than 16h trying to fix this bug. 

Please try this User case scenario on your own and let me know.

1. The student does the activity in "Learning path"
2. The student failed/suspend the activity 
3. The student does for second time the activity
4. The student pass/complete the activity successfully

**Comment by hi-rafa** [comment]
My chamilo user case TEST:

![screen shot 2017-04-06 at 3 58 56 pm](https://cloud.githubusercontent.com/assets/3813277/24759995/8be1ec88-1ae7-11e7-81e5-9539cc5fa80a.png)

![screen shot 2017-04-06 at 3 59 16 pm](https://cloud.githubusercontent.com/assets/3813277/24760002/90ee48d4-1ae7-11e7-97ca-bc4190ab955f.png)


![screen shot 2017-04-06 at 4 01 56 pm](https://cloud.githubusercontent.com/assets/3813277/24760934/52cdded6-1aea-11e7-90cc-1d6db6754101.png)


<img width="663" alt="screen shot 2017-04-06 at 4 00 41 pm" src="https://cloud.githubusercontent.com/assets/3813277/24760945/5946395c-1aea-11e7-890b-f0882ae56e63.png">


![screen shot 2017-04-06 at 4 02 26 pm](https://cloud.githubusercontent.com/assets/3813277/24760953/5f65396e-1aea-11e7-8858-a31d8bf7637b.png)



![screen shot 2017-04-06 at 4 03 20 pm](https://cloud.githubusercontent.com/assets/3813277/24760959/646ce308-1aea-11e7-9c74-6b6bdac8e180.png)



![screen shot 2017-04-06 at 4 04 30 pm](https://cloud.githubusercontent.com/assets/3813277/24760972/6d52282a-1aea-11e7-8250-7d33de6c84f6.png)



![screen shot 2017-04-06 at 4 09 04 pm](https://cloud.githubusercontent.com/assets/3813277/24760987/77005c02-1aea-11e7-98e2-346a2d39b420.png)

**Comment by ywarnier** [comment]
@hi-rafa this was not my question. My question was whether you have actually gone through the RTE for SCORM 1.2. Feel free to download it from here: https://drive.google.com/open?id=0B7wXPLicqnqXcUxPcGJTWjRDejg
I'm asking because I understand the current rules might be frustrating, but there are very specific rules in SCORM 1.2 that might feel buggy but that are actually *rules* so if you go around them, other processes will fail to comply with SCORM 1.2.
And I'm not saying this is not a bug. I'm just a bit cautious about spending hours reviewing the SCORM rules to finally get to nothing because it would infringe the SCORM rules.

**Comment by ywarnier** [comment]
But yes, your report looks like a bug at first glance.

**Comment by hi-rafa** [comment]
@ywarnier I will try to find another SCORM Package and try again I will also read in deep the rules for SCORM 1.2 you sent me.

**Comment by ywarnier** [comment]
There's a section about status in the code (lp_ajax_save_item.php I think) that makes a series of references to the SCORM 1.2 RTE to explain why decisions are taken this way. Maybe that will help.

**Comment by hi-rafa** [comment]
Hi @ywarnier,
I would like to know if you received the email I sent you about this problem? 
The fact that the student can only complete once the course,  independently of his result (Failed or passed) its a very important matter for us please let us know if Chamilo is planing to do something about it or not. 
Thank you.

**Comment by hi-rafa** [comment]
We also found another problem and is that the time spent in the course doesnt sum up.
Each time the student does a course attempt it resets the time spent.

<img width="1257" alt="screen shot 2017-04-11 at 10 19 36 am" src="https://cloud.githubusercontent.com/assets/3813277/24899607/2b371d32-1ea1-11e7-8499-bc0112ba39cd.png">

<img width="1278" alt="screen shot 2017-04-11 at 10 20 20 am" src="https://cloud.githubusercontent.com/assets/3813277/24899624/41a5e684-1ea1-11e7-9884-718e0ae38986.png">



<img width="1274" alt="screen shot 2017-04-11 at 10 20 37 am" src="https://cloud.githubusercontent.com/assets/3813277/24899629/45310d38-1ea1-11e7-95bb-ec6f6fb40aef.png">




<img width="1279" alt="screen shot 2017-04-11 at 10 21 14 am" src="https://cloud.githubusercontent.com/assets/3813277/24899632/48de2a1a-1ea1-11e7-9f80-5aa56b1b1718.png">

**Comment by ywarnier** [comment]
Hi @hi-rafa,
Yes, I received it. I haven't been able to work on that yet, sorry (too much work coordinating the release and attending customers). I will get back to you on this before the 1.11.4 release.

**Comment by NicoDucou** [comment]
About the other problem that the time spent in the course doesnt sum up.

There is a global parameter to define this:

> Cumulative session time for SCORM
> Yes  
> No  
> 
> When enabled, the session time for SCORM learning paths will be cumulative, otherwise, it will only be counted from the last update time. This is a global setting. It is used when creating a new learning path but can then be redefined for each learning path.
>

**Comment by hi-rafa** [comment]
Hi @NicoDucou 
I am aware of this option and when I did the test it was enabled.

<img width="1210" alt="screen shot 2017-04-13 at 11 31 36 am" src="https://cloud.githubusercontent.com/assets/3813277/24999188/e7cea446-203c-11e7-958e-0e43d5a46467.png">

**Comment by hi-rafa** [comment]
Hi @ywarnier , @NicoDucou  
Good news!!! is not a bug, after hours of debugging I found out that there is a main variable that controls if the student can repeat the course or not. If the SCORM doesn't have a limit of attempts Chamilo logic is to limit the students to only one attempt.

**Comment by ywarnier** [comment]
Hi @hi-rafa
Great. Does this close the entire issue then, or is there still something pending (like the cumulative time)?

**Comment by hi-rafa** [comment]
Yes the cumulative time works now. There is one thing left that we think that it should be change. The progress bar shouldn't be 100% when the course is failed, specially if you can repeat it. 
What do you think?

**Comment by ywarnier** [comment]
@hi-rafa I agree that the item should not be considered a "success" if the item is failed. However, this has to be balanced with all the other rules of SCORM, so if you want to change it, be very careful about it :-)
I'm removing the 1.11.4 milestone though. Not really a critical issue anymore, and I'd like to publish 1.11.4 soon (it already has about 1000 commits since 1.11.2)

**Comment by ywarnier** [comment]
Please open a new issue for the "success" behaviour fix.
