### ISSUE TITLE
Problema progreso y tiempo empleado en el curso

### ISSUE THREAD

**Issue by vfvf122** [chamilo/chamilo-lms#1804]
### Current behavior / Resultado actual / Résultat actuel

1-No me coincide el porcentaje de progreso en el apartado de Mi progreso con el porcentaje realizado en el apartado de lecciones del curso. Me aparece siempre la mitad del porcentaje. Esto me sucede al realizar una actualización de chamilo 1.9.10 a 1.11.2  y solo me sucede con cursos creados antiguos, los cursos creados nuevos no tengo este error.

2- Sigo en el apartado de mi progreso:  El tiempo de permanencia en el curso me suma bien, pero si
despliego los detalles, me aparecen los ejercicios y me viene sin puntuación, ni tiempo y el numero de intentos 0 , y abajo en la barra del tiempo empleado me aparece 0 y la puntuacion 0. Solo me pasa con cursos antiguos creados en la version 1.9.10

### Expected behavior / Resultado esperado / Résultat attendu

1- Debería de coincidir el mismo porcentaje de progreso en el apartado de Mi progreso con el porcentaje en el apratdo de lecciones del curso.

2-Debería de aparecer el tiempo empleado y la puntuacion.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1- Actualizar chamilo 1.9.10 a 1.11.2
2- Una vez actualizado, crear un usuario y asignarle un curso que se creo en la version 1.9.10 y realizar un par de ejercicios o lecciones
3- Ir a mi progreso y ver el porcentaje

### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo 1.11.2 

![foto_duda_tiempo_empleado](https://cloud.githubusercontent.com/assets/26923335/24700715/505e96d8-19f8-11e7-9d1f-bc0888da017f.png)

**Comment by AngelFQC** [comment]
Hola @vfvf122 nuestro esfuerzo como comunidad se limita a probar con las última versión en desarrollo. Probar una migración nos tomaría bastante tiempo. Por favor, prueba intentanto actualizar con los últimos cambios de la rama 1.11.x para 1.11.4.
También puedes corregirlo tú mismo y enviarnos el código o contactar con un proveedor oficial para que solucione el problema como un trabajo de desarrollo

**Comment by ywarnier** [comment]
No se ha obtenido mayor información sobre el problema en varios meses. Cerrando.
