### ISSUE TITLE
1.11x current cross-origin issue with embed.php

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#1808]
### Current behavior / Resultado actual / Résultat actuel
Learning portal is running in https when user wants to consult an embeded ressource (as defined by main/lp/embed.php) browser prompts that it wants to load unsafe content.

### Expected behavior / Resultado esperado / Résultat attendu

Embed should upgrade to https

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Add Youtube Video to a learningPath and try to access it on a https portal

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11x current from GitHub

**Comment by meuhland** [comment]
Issue is more or less that the $src parameter in lines 15 and 21 in main/lp/embed.php are hard coded to http:// they at the very least should be converted to either https:// or simply // to allow the browser to use whatever protocol the page is served with.

**Comment by ywarnier** [comment]
Do you use the youtube button of ckeditor, the media button of ckeditor, the embed includer of ckeditor or are you including the embed manually from the source?

**Comment by meuhland** [comment]
It's a link in a learningPath.

![image](https://cloud.githubusercontent.com/assets/6123610/24720075/e4d45bc0-1a09-11e7-9743-4330f1bf7076.png)

This was happens when I'm leaving the embed.php as-is
![image](https://cloud.githubusercontent.com/assets/6123610/24720130/17619f44-1a0a-11e7-9daf-ff07854d9dc5.png)

Modifying the embed.php
    case 'youtube':
        $src = '//www.youtube.com/embed/'.$src;

![image](https://cloud.githubusercontent.com/assets/6123610/24720182/35a78fea-1a0a-11e7-9c88-dee74b0742c4.png)

<Opinion>
Anyway seems like it's a bit silly to hardcode the http in any form of url that could be used in an https environment don't you think?
</Opinion>

**Comment by meuhland** [comment]
https://github.com/meuhland/chamilo-lms/commit/570becbd0300de68ab9f2dc6733f078162199d19 seems to do the trick just fine.

**Comment by jmontoyaa** [comment]
That change looks good for me @ywarnier

**Comment by ywarnier** [comment]
Included here 8b37c098f30
Thanks for the contribution!
