### ISSUE TITLE
Problem with ticket for students

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1810]
Hello.
When housing the ticket for students.

### Current behavior / Current result / Résultat actuel
The green button does not appear to open the ticket

### Expected behavior / Expected result / Résultat attendu
You should pop the button without a warning:
"An error has occurred, please inform your system administrator."

### Steps to Reproduce / Steps to Reproduce / Étapes pour reproduire
Please login or register.
https://1.11.chamilo.org/
As a student.
Login: demo
Password: 123456

### Chamilo Version / Chamilo Version / Chamilo Version
1.11.x

![ticket](https://cloud.githubusercontent.com/assets/25286516/24730366/aba97bf2-1a39-11e7-8d13-7cf6251c3500.jpg)

**Comment by jmontoyaa** [comment]
I just added a fix for that.

**Comment by bassuma** [comment]
OK.
Working perfectly.
greetings
