### ISSUE TITLE
Exercises exam ends even without setting a time limit

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#1811]
### Current behavior / Resultado actual / Résultat actuel

The student do only part of the questions and then closes the browser and try to do the remaining questions on the next day.
When accessing on the next day, the student is show the warning of exceeded number of attempts.
On the report, the end date for the exam shows the new access try.
There is no constraints on time, start or end date, only there is the limit of one execution of the exam.

Maybe there is some error in math check/logic, when the day changes or the session has expired.

### Expected behavior / Resultado esperado / Résultat attendu
If there is no constraints on time, start or end date, the student should be able to do partially the test and then come back and finish it on other days.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
A exercise is set on a learning path without any constraints of time, start or end date.
The exercise is a single try exam with only 5 multiple choice questions.
Once the exam is started, the student do only part of the questions and then closes the browser and try to do the remaining questions on the next day.
When accessing on the next day, the student is show the warning of exceeded number of attempts.
On the report, the end date for the exam shows the new access try.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by marshel** [comment]
@AngelFQC  What info would be useful?

**Comment by AngelFQC** [comment]
A better (detailed) description of step to reproduce 😃

**Comment by ywarnier** [comment]
Also moving to 1.11.8. The use case is relatively limited and difficult to reproduce.

**Comment by ywarnier** [comment]
No more details provided. Closing.
