### ISSUE TITLE
Install from git fails

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#1816]
### Current behavior / Resultado actual / Résultat actuel
V: Chamilo 1.11.alpha4
Following all steps on install from git gives a error on settings check from installer. 
Cannot finish install.
.
![captura de tela 10](https://cloud.githubusercontent.com/assets/1764993/24800537/defb445c-1b76-11e7-931f-4c05b809c158.png)

With official 1.11.2 installation concludes without errors.

### Expected behavior / Resultado esperado / Résultat attendu
Installation concludes.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Fresh ubuntu 16.10 server.
Apache/2.4.18 (Ubuntu)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 
PHP version: 7.0.15-0ubuntu0.16.10.4

**Comment by jmontoyaa** [comment]
Should be fixed now.

**Comment by marshel** [comment]
Made a test. It went Ok.
