### ISSUE TITLE
Passo 7 – Installation process execution  - Chamilo 1.11.4 alpha = failure

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1824]
Hi.
I performed all the steps to download.
Chamilo 1.11.4 alpha.
In:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/README.md

All installation phases follow normal.
More in phase 7.
Give this error:

Warning: Can not modify header information - headers already sent by (output started at /home/public_htmlchamilo/main/install/index.php:310) in /home/public_html/chamilo/main/inc/lib/template.lib.php on Line 1043

Warning: Can not modify header information - headers already sent by (output started at /home/public_html/chamilo/main/install/index.php:310) in /home/public_html/chamilo/main/inc/lib/template.lib. Php on line 1046

-------------------------------
I appreciate the support

![bug_1 11 4-1](https://cloud.githubusercontent.com/assets/25286516/24889541/e76f129a-1e40-11e7-8f7e-67b045ca8ba4.jpg)
![bug_1 11 4](https://cloud.githubusercontent.com/assets/25286516/24889551/ee2fd83a-1e40-11e7-9e4c-ab8673c72126.jpg)

**Comment by jmontoyaa** [comment]
Can you check if there's an error in your server logs (apache)?

**Comment by bassuma** [comment]
Hi.
Yes.
In chamilo / main / install.
Generate this log.

[11-Apr-2017 01:27:45 UTC] An exception occurred while executing 'CREATE TABLE IF NOT EXISTS version (id int unsigned NOT NULL AUTO_INCREMENT, version varchar(255), PRIMARY KEY(id), UNIQUE(version));':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
[11-Apr-2017 01:27:45 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/serve/public_html/chamilo/main/install/index.php:310) in /home/serve/public_html/chamilo/main/inc/lib/template.lib.php on line 1043

[11-Apr-2017 01:27:45 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/serve/public_html/chamilo/main/install/index.php:310) in /home/serve/public_html/chamilo/main/inc/lib/template.lib.php on line 1046

**Comment by ywarnier** [comment]
@jmontoyaa I think I've seen that before (with you). The UNIQUE key on the version does not handle well the fact that it's a varchar(255) or something like that.

See reference here: https://dev.mysql.com/doc/refman/5.7/en/create-index.html
"Prefix support and lengths of prefixes (where supported) are storage engine dependent. For example, a prefix can be up to 767 bytes long for InnoDB tables or 3072 bytes if the innodb_large_prefix option is enabled. For MyISAM tables, the prefix limit is 1000 bytes. The NDB storage engine does not support prefixes (see Section 20.1.6.6, “Unsupported or Missing Features in NDB Cluster”)."

It seems like a good choice might be to simply forget about the UNIQUE constraint (not sure it serves any purpose anyway).

**Comment by ywarnier** [comment]
One reference that confirms my previous comment: https://dba.stackexchange.com/questions/28219/sqlstate42000-syntax-error-or-access-violation-1071-specified-key-was-too-lo

**Comment by ywarnier** [comment]
@bassuma What operating system + distribution + version do you have? I want to replicate your case but I'm not sure how to do it.

**Comment by bassuma** [comment]
Hello @ywarnier.
I took this print.
It's a vps.
Would there be any link, to lower the chamilo, in the traditional way?
In zip or tar.
Thank you
![2017-05-18](https://cloud.githubusercontent.com/assets/25286516/26209806/3889b5ae-3bc4-11e7-8462-0f60306e7bfa.png)

**Comment by ywarnier** [comment]
I will probably be pushing the first alpha today, so you should be able to download it from there, but I don't think it's a download version problem. I think it's related to your version of MySQL, but with the details you gave me above I cannot really make sure I have the right VM to test.

**Comment by bassuma** [comment]
I expect the alpha release.
If everything goes well.
I report here.
Greetings.

**Comment by bassuma** [comment]
Hello.
I downloaded the chamilo-lms-1.11.4-releases.zip version.
But unfortunately, I no longer install the chamilo on my server.
The error in the log is this now:

[22-May-2017 18:56:21 UTC] An exception occurred while executing 'CREATE TABLE IF NOT EXISTS version (id int unsigned NOT NULL AUTO_INCREMENT, version varchar(255), PRIMARY KEY(id), UNIQUE(version));':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
[22-May-2017 18:56:21 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/chamilo/public_html/chamilo.com/educa/main/install/index.php:310) in /home/chamilo/public_html/chamilo.com/educa/main/inc/lib/template.lib.php on line 1062

[22-May-2017 18:56:21 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/chamilo/public_html/chamilo.com/educa/main/install/index.php:310) in /home/chamilo/public_html/chamilo.com/educa/main/inc/lib/template.lib.php on line 1065

**Comment by ywarnier** [comment]
I just released Chamilo 1.11.4 alpha 2, but it is unlikely to solve this issue.
Could you try the following for me?
*Before* installing/updating, edit the app/Migrations/Schema/V111/Version111.php file. Go to line 406, and change the `CREATE TABLE version` query to `id bigint unsigned` instead of `id int unsigned`, to see if that fixes the issue.

**Comment by ywarnier** [comment]
After thinking a bit more about it, I don't think this is going to work because you are not doing an upgrade but a fresh install...
@jmontoyaa, where is the `version` table created? I understand this is a requirement of Doctrine::Migrations, but I cannot find it.

**Comment by bassuma** [comment]
Hi @ywarnier.
I did the above test.
That works. :)
More did not give :(
Gave this error:
___________________________________
Warning: Cannot modify header information - headers already sent by (output started at /home/main/install/index.php:310) in 
/home/main/inc/lib/template.lib.php on line 1062

Warning: Cannot modify header information - headers already sent by (output started at /home/main/install/index.php:310) in 
/home/main/inc/lib/template.lib.php on line 1065
___________________________________

I do not know if it helps.
I created an account on my server.
Could you test?
Follows in:

https://tecnoltech.com:2083/
Login: chamilo
Password: 123456

**Comment by ywarnier** [comment]
Can you take a screenshot (including URL last part) of where it happens?
The "Warning" messages are not important, you can avoid them in Chamilo, but the installation process forces them to appear, so they should appear for me too if it was a Chamilo-only issue.

**Comment by bassuma** [comment]
![2017-05-23](https://cloud.githubusercontent.com/assets/25286516/26366476/a1149dfe-3fc1-11e7-8263-c1c3c4650e99.png)

**Comment by bassuma** [comment]
The strange thing is that it creates the entire database.
More on returning home.
It will enter the installation screen.

**Comment by ywarnier** [comment]
Does it take a long time (after you load the page) before the warning appears?

Seeing from the screenshot, it might be that the warning is when the install is supposed to receive a message back from a JS that shows the report on the installation. If you say it creates the entire database, that makes even more sense.

So if it takes a very long time to return (because your system is very slow, maybe because it's busy with some other thing), then it makes sense that you would see the "unauthorized" message as a sign that the PHP session has expired...

**Comment by bassuma** [comment]
Hello.
I made this video of all the steps
https://youtu.be/tvClV_BCBY8
Here you can see what happens in my installation.
Can it be then problem on my server?
Do not accept this new version of chamilo?
Thank you

**Comment by jmontoyaa** [comment]
I saw the video, you have to check the apache error logs 
I fixed the "CREATE TABLE IF NOT EXISTS version" error in latest 1.11.x

**Comment by bassuma** [comment]
Hello.
I performed the installation procedure.
Chamilo version chamilo-lms-1.11.4-releases.zip.
At first without editing the file.
App / Migrations / Schema / V111 / Version111.php
id int unsigned
/main/install/error_log:
_______________________________________________
[24-May-2017 15:18:49 UTC] An exception occurred while executing 'CREATE TABLE IF NOT EXISTS version (id int unsigned NOT NULL AUTO_INCREMENT, version varchar(255), PRIMARY KEY(id), UNIQUE(version));':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
[24-May-2017 15:18:49 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/public_html/educa/main/install/index.php:310) in /home/public_html/educa/main/inc/lib/template.lib.php on line 1062

[24-May-2017 15:18:49 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/public_html/educa/main/install/index.php:310) in /home/public_html/educa/main/inc/lib/template.lib.php on line 1065
_______________________________________________

Then changing the file.
/main/install/error_log:
________________________________________________
[24-May-2017 15:36:32 UTC] An exception occurred while executing 'CREATE TABLE IF NOT EXISTS version (id int unsigned NOT NULL AUTO_INCREMENT, version varchar(255), PRIMARY KEY(id), UNIQUE(version));':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
[24-May-2017 15:36:32 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/public_html/educa/main/install/index.php:310) in /home/public_html/educa/main/inc/lib/template.lib.php on line 1062

[24-May-2017 15:36:32 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/public_html/educa/main/install/index.php:310) in /home/public_html/educa/main/inc/lib/template.lib.php on line 1065
________________________________________________

App / Migrations / Schema / V111 / Version111.php
id bigint unsigned

**Comment by bassuma** [comment]
Hi.
Just for more information.
I sent the chamilo 1.11.2.
And I installed normally without problems.
![2017-05-24](https://cloud.githubusercontent.com/assets/25286516/26417141/aa024f56-408e-11e7-94f6-9782749c2829.png)

**Comment by ywarnier** [comment]
@jmontoyaa, I repeat my question from above: where is the version table created? I understand this is a requirement of Doctrine::Migrations, but I cannot find it.
I think this is the issue here... the ID is bigger than the SQL "INT" type for the configuration of @bassuma 

See also links to MySQL doc above: https://dev.mysql.com/doc/refman/5.7/en/create-index.html
"Prefix support and lengths of prefixes (where supported) are storage engine dependent. For example, a prefix can be up to 767 bytes long for InnoDB tables or 3072 bytes if the innodb_large_prefix option is enabled. For MyISAM tables, the prefix limit is 1000 bytes. The NDB storage engine does not support prefixes (see Section 20.1.6.6, “Unsupported or Missing Features in NDB Cluster”)."

So changing the ID to bigint should be OK, but we need to find where this is created.

@bassuma, following indications here: https://stackoverflow.com/questions/11847815/error-specified-key-was-too-long-max-key-length-is-1000-bytes it seems that the issue might be because the InnoDB table engine is not enabled.

Could you send me the output of this command in your database?:
`SHOW TABLE STATUS;`
This is a long output, but it might help us identify if your database server is (as I believe) trying to convert all InnoDB tables to MyISAM on the fly. In this case, all your tables should says "MyISAM" in the engine column, instead of what should be for Chamilo: InnoDB.

**Comment by jmontoyaa** [comment]
I just added some fixes. Now Chamilo creates the version table first, because doctrine migrations creates the table if it doesn't exists. Now it should work.

**Comment by bassuma** [comment]
Hello.
As you can see in the picture.
@Jmontoyaa's solution did.
Work for me.
I was able to install and test the main tools.
Many thanks to all for the help.

![2017-05-25](https://cloud.githubusercontent.com/assets/25286516/26454850/a4a348fc-413e-11e7-80cf-3343620197a1.jpg)

**Comment by ywarnier** [comment]
Great, thanks to all of you (for reporting and fixing)

**Comment by ywarnier** [comment]
This still happens when upgrading from 1.9.8 to 1.11.8:
```
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/-/www/main/inc/lib/database.lib.php:415
Stack trace:
#0 /var/www/-/www/main/inc/global.inc.php(122): Database::connect(Array)
#1 /var/www/-/www/index.php(19): require_once('/var/www/...')
#2 {main}
  thrown in /var/www/-/www/main/inc/lib/database.lib.php on line 415
```

**Comment by ywarnier** [comment]
This can be fixed by removing the "UNIQUE" term on lines 46 and 47 of vim app/Migrations/Schema/V110/Version110.php
