### ISSUE TITLE
Unwanted \r\n\r\n in extra fields for courses

### ISSUE THREAD

**Issue by ric373** [chamilo/chamilo-lms#1825]
### Current behavior / Resultado actual / Résultat actuel
We've tried using extra fields (type textarea) but whenever text is saved through the course settings, extra \r's  and \n's  are stored in the database. We use the content of these fields on a page and there it also shows the extra characters.

I've traced the issue to the file "main/inc/lib/extra_field_value.lib.php". Line 333.

The method Database::escape_string returns the value with the \r\n as string values (with single quotes '\r') instead of newlines (with double quotes "\r"). For our situation we added the line 

$value_to_insert = str_replace(array('\r', '\n', '\t'), '', $value_to_insert);

to line 336, this way the string characters are removed, but the actual newlines stay intact.

### Expected behavior / Resultado esperado / Résultat attendu
Not storing extra characters in the string.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Add extra fields (type textarea) to a course. Edit the course and insert text with returns, then save the course. Edit the course again, and it will show it added the extra characters in the database.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by jmontoyaa** [comment]
I just added a fix for that.
