### ISSUE TITLE
Announcements: rows per page wrong

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1856]
### Current behavior / Resultado actual / Résultat actuel
When announcements are sent to many groups at once, the number of announcements shown is lower than the numRow (page size) specifies.
### Expected behavior / Resultado esperado / Résultat attendu
If you select 20, 50 or 100 rows in the announcement tool, that should be the number to show.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create many announcements to many groups and look at the pages. Numbers are totally wrong. (See picture where 20 is the page size but only 4 rows are shown)
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x latest git checkout 2017-04-22

Caused by changes in function getAnnouncements in main/inc/lib/AnnouncementManager class.

![afbeelding](https://cloud.githubusercontent.com/assets/1659604/25308181/a675f948-27af-11e7-91d3-c2c74d926f05.png)

![afbeelding](https://cloud.githubusercontent.com/assets/1659604/25308644/a4d8ee7e-27b9-11e7-8894-9d2db628226f.png)

**Comment by AngelFQC** [comment]
See my Announcements page 
https://pageshot.net/1cQZlcgZRfPZwfxI/chamilo111x.dev
https://pageshot.net/oAuElNlr5DZJ8rbk/chamilo111x.dev

Try replicate this in 1.11.chamilo.org

**Comment by ywarnier** [comment]
Will be left open 3 more days for feedback.

**Comment by jderriks** [comment]
Cannot use https://1.11.chamilo.org/courses/CURSO/ because of errors like:
<img width="355" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/26152887/3f924eb2-3b09-11e7-9392-978015e68dc8.png">

I will test it again on a fresh git checkout but the issue can be reproduced for sure.

**Comment by jderriks** [comment]
Here you go:

![afbeelding](https://cloud.githubusercontent.com/assets/1659604/26153533/11d6b550-3b0c-11e7-8f7b-5d77c8c72b4b.png)
<img width="518" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/26153561/33b05d52-3b0c-11e7-855e-949298bf2a20.png">

Make sure you have some announcements that are sent to many groups at once and to some users.
The code to add the "group" label causes the count of the number of announcements to go wrong.

**Comment by jderriks** [comment]
Another way to reproduce it with only 2 announcements:
<img width="1216" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/26153890/ab415b5e-3b0d-11e7-824b-b41869b036c7.png">

Steps:
1. use fill data to create some users and courses
2. create 80 groups with 2 users (use random filler)
3. sent 1 announcement to all 80 groups.
4. sent another one to all 80 groups

These are 2 accouncements but the count will be 160 and the list will show one per page even if the page size is set to 20.

All because of a change in a SQL select query to add the "group" label to the list...

**Comment by jderriks** [comment]
Announcement bad  dead code example: test on 0:
<img width="823" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/26173127/074ea9f0-3b4b-11e7-840f-18a20fa2d036.png">

**Comment by jderriks** [comment]
Even on the chamilo campus the issue appears:
https://campus.chamilo.org/main/announcements/announcements.php?cidReq=TEST9&id_session=0&gidReq=0&gradebook=0&origin=

(you have to login to see announcements)

**Comment by ywarnier** [comment]
campus.chamilo.org is version 1.10, so it shouldn't be used as an example.
I'm not sure we're going to be able to fix this one in time for 1.11.4. We'll see, but otherwise we'll move it to 1.11.6.

**Comment by AngelFQC** [comment]
@jderriks try with the last 1.11.x changes

**Comment by ywarnier** [comment]
Considered fixed. Please don't hesitate to report back (we'll reopen it and reschedule for 1.11.6) if it wasn't fixed for you in 1.11.4 (to be released today).

**Comment by jderriks** [comment]
If only this bug were that easy to fix :-)

https://1.11.chamilo.org/main/announcements/announcements.php?cidReq=TESTHVA&gidReq=0&id_session=0

**Comment by jmontoyaa** [comment]
This was already fixed:

https://11.chamilo.org/main/announcements/announcements.php?cidReq=TESTHVA&gidReq=0&id_session=0
