### ISSUE TITLE
Error importar Enlaces

### ISSUE THREAD

**Issue by gatogeek** [chamilo/chamilo-lms#1860]
Hola, en la versión 1.11.2, al exportar enlaces que tienen el parámetro de abrir en una ventana nueva, al importarlos en otro curso quedan abriendo en la misma ventana.

Saludos!

**Comment by ywarnier** [comment]
hola @gatogeek, podrías hacer la prueba en https://1.11.chamilo.org/ para ahorrarnos el tiempo de verificar si el problema persiste en 1.11.x? (1.11.4 por publicar pronto)
Hemos hecho unos cambios en la herramienta de enlaces, así que *puede* que haya sido arreglado el problema, aunque no recuerdo este en particular.

**Comment by gatogeek** [comment]
Hola, ya probé en esa página, el error persiste.

Adicional, cuando se crea un enlace sin categoría aparece una "Categoria" que se llama "general", y no se puede borrar, creé una categoría y se creó dos veces.

![captura](https://cloud.githubusercontent.com/assets/7724158/25394131/0349a0b2-29a3-11e7-92be-d3d3278167b8.PNG)

Saludos!

**Comment by AngelFQC** [comment]
La categoría "general" que aparece, es para agrupar los enlaces que **no tienen categoría**

**Comment by gatogeek** [comment]
Sería bueno poder borrarla si está vacía, gracias.

**Comment by AngelFQC** [comment]
Ahora la _categoría general_ no debería mostrarse si no hay enlaces a mostrar. Y debe aparecer _sólo_ cuando hay otras categorías

**Comment by gatogeek** [comment]
Muchas gracias :)
