### ISSUE TITLE
Error Anuncios

### ISSUE THREAD

**Issue by gatogeek** [chamilo/chamilo-lms#1861]
Hola, en la versión 1.11.2, al enviar en Anuncios el parámetro ((official_code)), en realidad se envía el link del curso.

Saludos!

**Comment by ywarnier** [comment]
Igual sobre la prueba en https://1.11.chamilo.org/ porfa

**Comment by jderriks** [comment]
Same problem in 1.11.4.
check on tags it seems a line is shifted:

username - ok
firstname - ok
lastname - ok
teachername - wrong, is username
teachermail - wrong
coursetitle - wrong, is NOREPLY@domain.com
courselink - wrong, is coursetitle
officialcode - wrong, is courselink

**Comment by gatogeek** [comment]
Confirmo pruebas, varias etiquetas están equivocadas, también reporto fallas en la página, adjunto capturas:

![0](https://cloud.githubusercontent.com/assets/7724158/25394495/ccf3e8c8-29a3-11e7-8170-bcef0a5ae735.PNG)

![1](https://cloud.githubusercontent.com/assets/7724158/25394504/d05e3a0e-29a3-11e7-883e-908ac5435820.PNG)

![2](https://cloud.githubusercontent.com/assets/7724158/25394512/d433e1f6-29a3-11e7-9392-8d366a88c032.PNG)

**Comment by jmontoyaa** [comment]
Acabo de agregar una correción, ahora debería de funcionar.
