### ISSUE TITLE
Announcements: possible to send empty title and body

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1863]
### Current behavior / Resultado actual / Résultat actuel
Empty-title announcements can be sent. That is undesired because you cannot click the message anymore.
### Expected behavior / Resultado esperado / Résultat attendu
In older versions Chamilo used to check on empty title and refude to send. That is still the expected bahaviour.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
click create announcement icon and hit "send announcement" without entering anyting
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 (git pull 24-4-2017)

![afbeelding](https://cloud.githubusercontent.com/assets/1659604/25360364/0aab198a-2949-11e7-83ac-18d088dd9e6e.png)

**Comment by SatyanJ** [comment]
I've made a fix for that bug.  #1890

(cc @moy)

**Comment by jderriks** [comment]
Very good!
Maybe add the rule on the body also:
$form->addRule('content', get_lang('ThisFieldIsRequired'), 'required');

Just to prevent people forgetting entering a message.

**Comment by SatyanJ** [comment]
@jderriks Maybe instead of making the field required it would be preferable to print a warning message ? 
Like when you are sending a empty mail in most of mails boxes (Gmail, etc).

**Comment by jderriks** [comment]
Sure, go ahead. It's more code.

**Comment by SatyanJ** [comment]
I tried using some javascript on the validating butting but I didn't find a way to access the html editor text of content. 
They must be a way since 'required' verify if a field is filled. Does anyone knows where it is defined ?

**Comment by jderriks** [comment]
Content is set by: 
       $form->addHtmlEditor(    'content',

**Comment by jmontoyaa** [comment]
I just added a fix for the announcement description.

**Comment by jderriks** [comment]
Works.
