### ISSUE TITLE
Announcements: email_sent icon and database field not updated 

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1865]
### Current behavior / Resultado actual / Résultat actuel
When an announcement is sent by mail, the email icon used to appear in the announcement list but it doesn't anymore.
### Expected behavior / Resultado esperado / Résultat attendu
Email icon should be shown when announcement was sent by email and c_announcement table field sent_email should NOT be NULL
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Send an announcement, check "send by email", watch it send by mail and look at the announcement list: no icons anymore. 
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2+ (somehere in 2016 this got broken and still broken in 1,11.4alpha)

This is what the email icon in announcements look like when email_sent is not null:

![afbeelding](https://cloud.githubusercontent.com/assets/1659604/25360852/429266b2-294b-11e7-8266-1dae155eb42f.png)

**Comment by SatyanJ** [comment]
@jderriks What is the purpuse of the icon: 
- To notify when the announcement has been sent ?
OR
- To see the field below is checked ? 
![image](https://cloud.githubusercontent.com/assets/19304198/25532008/f902780a-2c2b-11e7-8b5a-20946b6a9841.png)

**Comment by jderriks** [comment]
@SatyanJ 
Good question. In older 1.11 versions it used to mark messages that have been sent BY EMAIL.
So the purpose is indeed to see if the "send by email" was used and the announcement was send by mail instead of just posted in the chamilo box.
There is code to set this field but it is never called (dead code).

**Comment by ywarnier** [comment]
Postponing to 1.11.6 because not critical. Very likely to be fixed soon after 1.11.4 release.

**Comment by jmontoyaa** [comment]
Fix added.

**Comment by ywarnier** [comment]
It looks good to me now. Closing.
