### ISSUE TITLE
Bug o Error al autenticar usuario LDAP

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1866]
Cordial saludo

Buenas noches tengo un problema con la version  11.2   en la parte de autenticación  de usuarios nuevos, me sale que no tengo permisos para ver esta pagina al  ingresar a chamilo, no se si es algún permiso o un bug de la version  anexo imagen del error.   
![error eldap](https://cloud.githubusercontent.com/assets/20644209/25362422/7339ef74-2919-11e7-9072-3e16454e52b1.JPG)

**Comment by ywarnier** [comment]
Hola @fergimon 
Es demasiado poca información para que podamos ayudar. Aun así, los problemas de LDAP suelen ser complejos.

**Comment by fergimon** [comment]
Buenas noches  si claro  pero si lo creo en la base de datos y le digo que autentique con el ldap no tiene problemas en ingresar el usuario

**Comment by ywarnier** [comment]
...y entonces cual es el caso en el cual no funciona? (de manera detallada por favor).
Ojo, hay un formato para reportar errores, que ayuda a proveer la información de manera más acorde a nuestras expectativas. Por favor respetarlo.

**Comment by fergimon** [comment]
hola @ywarnier  gracias por tu ayuda, el objetivo es configurar la autenticacion a la plataforma con mi servidor ldap, ya he configurado el archivo _/var/www/html/app/config/auth.conf.php_ con todos los parametros ldap y chamilo puede encontrar los usuarios de ldap con el usuario administrador local en las opciones "_Administracion / Buscar usuarios LDAP_", tambien se han habilitado las lineas en el archivo _/var/www/html/app/config/configuration.php_
_$extAuthSource["extldap"]["login"] = $_configuration['root_sys']."main/auth/external_login/login.ldap.php";
$extAuthSource["extldap"]["newUser"] = $_configuration['root_sys']."main/auth/external_login/newUser.ldap.php";_ 
el problema es que cuando el usuario LDAP intenta conectarse a la plataforma, muestra el siguiente error, como si chamilo no pudiese leer el usuario ldap  o simplemente falta algun parametro para permitir la conexion del usuario a la plataforma:
![error eldap](https://cloud.githubusercontent.com/assets/20644209/25408416/82545606-29d3-11e7-8a3c-e748512fccb8.JPG)

agradezco la atención y colaboracion

**Comment by fergimon** [comment]
Cordial Saludo ya se soluciono gracias cierro el caso

**Comment by ywarnier** [comment]
En estos casos, es de buena costumbre explicar porqué y cómo se solucionó, cosa que sirva para otros de la comunidad. Tal como revisamos e intentamos solucionar sus problemas, se espera que puedan contribuir también al proyecto aportando información cuando la tiene.

**Comment by fergimon** [comment]
Buenas tardes @ywarnier  si claro y que pena el caso se soluciono  remplazando el archivo local.php  ubicado en la ruta main/inc/local.inc.php que fue descargado de la ultima actualización de la rama 11x este caso tiene como relación con el caso #1531 que fue solucionado anteriormente. 
agradezco tu ayuda y colaborarcion

**Comment by ywarnier** [comment]
Perfecto, gracias!
