### ISSUE TITLE
phpoffice/phpword doesn't works with PHP7

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#1871]
### Current behavior / Resultado actual / Résultat actuel
When try export to doc file the gradebook flatview, an exception about PHPWord is trown
```
Fatal error: Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name in /var/www/chamilo111x/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php on line 20
```
See PHPOffice/PHPWord#736

(I tried update the composer.json but there are dependencies conflicts)
### Expected behavior / Resultado esperado / Résultat attendu
Export gradebook to doc
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a gradebook with evaluations
Go to flat view
Try export to doc file
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jmontoyaa** [comment]
Works for me with PHP 7.1.1
We can't upgrade zendframework/zend-config libs because they used PHP 5.5.

**Comment by ywarnier** [comment]
@AngelFQC do you still have the issue?

**Comment by AngelFQC** [comment]
Yes, the issue continues when exporting gradebook to docx

**Comment by ywarnier** [comment]
I have the issue too, with PHP 7.1.5.
It looks like there is something we don't use in Composer that could help us: http://stackoverflow.com/questions/34210002/composer-json-should-uses-different-packages-versions-depending-of-php-version, so something like this could work and would let Composer decide based on the PHP version:
```
            "phpoffice/phpword": "^0.12.1|^0.13.0",
```

**Comment by AngelFQC** [comment]
Works for me with `PHP 7.0.15-0ubuntu0.16.04.4`

**Comment by ywarnier** [comment]
That looks good to me now on `PHP 7.1.5-1+deb.sury.org~xenial+1`

![docx-export](https://cloud.githubusercontent.com/assets/609839/26321558/dd260dee-3eec-11e7-8893-2aee37a1c17b.png)

**Comment by ekohendratno** [comment]
> ### Current behavior / Resultado actual / Résultat actuel
> When try export to doc file the gradebook flatview, an exception about PHPWord is trown
> 
> ```
> Fatal error: Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name in /var/www/chamilo111x/vendor/phpoffice/phpword/src/PhpWord/Style/AbstractStyle.php on line 20
> ```
> 
> See [PHPOffice/PHPWord#736](https://github.com/PHPOffice/PHPWord/issues/736)
> 
> (I tried update the composer.json but there are dependencies conflicts)
> 
> ### Expected behavior / Resultado esperado / Résultat attendu
> Export gradebook to doc
> 
> ### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
> Create a gradebook with evaluations
> Go to flat view
> Try export to doc file
> 
> ### Chamilo Version / Versión de Chamilo / Version de Chamilo
> 1.11.x

fix this my branch https://github.com/ekohendratno/phpWord php 7 support

**Comment by iory861215** [comment]
gracias amigo funciona muy bien, podrias decirme que hiciste para que funcionara, soy novato programando, grcias
