### ISSUE TITLE
Migración de Chamilo 1.9 a 1.11.x muestra warning y parse error

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1874]
Hola.
Al simular una migración de Chamilo 1.9 a 1.11.x no permite finalizar mostrando los mensajes que se indican a continuación:

### Current behavior / Resultado actual / Résultat actuel

Entorno Chamilo 1.9.10.2 (Apache, PHP 5.6.27, MySQL 5.6.34).
Se inicia la actualización a Chamilo 1.11.x y en el apartado Paso 7 – Ejecución del proceso de actualización
../main/install/index.php?running=1&installType=update&updateFromConfigFile=main%2Finc%2Fconf%2Fconfiguration.php
en Detalles muestra el mensaje:

Warning: Unsupported declare 'strict_types' in .../vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
Parse error: syntax error, unexpected ':', expecting ';' or '{' in .../vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 97

paralizando la migración 1.9 a 1.11.

Se ha usado el último código github 1.11.x y generado las carpetas /vendor y /web con composer update

### Expected behavior / Resultado esperado / Résultat attendu

Migración a Chamilo 1.11.x

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Instalación Chamilo 1.9.10.2 o 1.9.10.4
Sobreescribir archivos con el código de github más el contenido de vendor y web
Simular el proceso de actualización a Chamilo 1.11.x

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x

**Comment by jmontoyaa** [comment]
Una vez copiado y pegado los archivos de 1.9.x a 1.11.x
Se ha realizado un composer update?

**Comment by nosolored** [comment]
El composer update se ha realizado previamente a copiar y pegar (sobreescribir) los archivos y carpetas.

**Comment by nosolored** [comment]
En una VM con PHP 5.6 he creado un snapshot y actualizado PHP a 7.1.4. 
Ejecutado git pull origin 1.11.x
y composer update
que genera al final una versión nueva de ocramius/proxy-manager

Chamilo\CoreBundle\Composer\ScriptHandler::deleteOldFilesFrom19x
Loading composer repositories with package information
Updating dependencies (including require-dev)           
  - Removing ocramius/proxy-manager (2.0.4)
  - Installing ocramius/proxy-manager (2.1.0)
    Downloading: 100%

He copiado y pegado esos archivos sobre la instalación Chamilo 1.9 para actualizar a 1.11 y muestra el mensaje siguiente:

Warning: Unsupported declare 'strict_types' in .../vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 19
Parse error: syntax error, unexpected ':', expecting ';' or '{' in ../vendor/ocramius/proxy-manager/src/ProxyManager/Configuration.php on line 87

Saludos.

**Comment by jmontoyaa** [comment]
Cual es el resultado de:

`composer info | grep proxy`

**Comment by nosolored** [comment]
Al ejecutar info | grep proxy muestra
ocramius/proxy-manager              2.0.4              A library providing utilities to generate, instantiate and generally operate with Object Proxies

o 2.1.0 si se ejecuta en el otro snapshot.

**Comment by nosolored** [comment]
Lo he intentado en una instalación nueva de Chamilo 1.11.4.

Creado el repositorio según indican en https://github.com/chamilo/chamilo-lms/tree/1.11.x

Clonada la rama 1.11.x y tras composer update, he utilizado el contenido de ficheros/carpetas en una instalación de Chamilo 1.11.4 nueva con otra base de datos y en otra ruta.

El mensaje que muestra en el Paso 7 – Ejecución del proceso de instalación es el siguiente:

Fatal error: Uncaught exception 'Doctrine/Common/Annotations/AnnotationException' with message '[Semantical Error] The annotation "@Symfony/Component/Validator/Constraints/NotBlank" in property Chamilo/CoreBundle/Entity/Course::$title does not exist, or could not be auto-loaded.' in .../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54 Stack trace: #0 

.../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(734): Doctrine/Common/Annotations/AnnotationException::semanticalError('The annotation ...') #1 

.../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine/Common/Annotations/DocParser->Annotation() #2 

.../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine/Common/Annotations/DocParser->Annotations() #3 

../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 54

- He probado también a realizar el mismo proceso limpiando previamente la caché de composer, eliminando vendor, etc. tal como se indica:

rm composer.lock
rm -rf web/ vendor/
composer clear-cache
composer update

Un saludo.

**Comment by jmontoyaa** [comment]
Cual es el resutado en la consola de este comando?

`php -v `

**Comment by jmontoyaa** [comment]
ocramius/proxy-manager 2.0.4 solo funciona con PHP 7, parece que la consola (php cli) tiene una versión diferente que el servidor web (apache + php).

**Comment by nosolored** [comment]
En las máquinas virtuales utilizo entornos con PHP 5.6.30, 7.0.18 y 7.1.4

El servidor donde hago las pruebas de actualización o de migración es PHP 5.6.30.

Si la librería ocramius/proxy-manager 2.0.4 solo funciona con PHP 7, ¿la versión Chamilo 1.11.4 sólo se podrá usar en servidores con PHP 7.0 o 7.1? 

Un saludo.

**Comment by jmontoyaa** [comment]
A ver ... como indico revisar que php CLI sea el correcto.

Es decir, si el portal es usado por un PHP 5.6, **pero** se ejecuta un composer update con un php cli de version *7.0* entonces existirá problema.

Ser coherente con el PHP del portal y el PHP CLI del servidor. Esto me sucedió con un portal de Noa.

Chamilo 1.11.x funciona a partir de PHP 5.4.

**Comment by ywarnier** [comment]
Para ver la versión del CLI de PHP, simplemente hacer `php -v`

**Comment by nosolored** [comment]
Gracias a ambos 

Estoy probando en una instalación de PHP 5.6 con la misma versión php-cli y con Chamilo también alojado en PHP 5.6.

Consulta: ¿De qué manera realizáis entonces el proceso con composer para que el zip o tar.gz de la versión final estable de Chamilo sea válido para varias versiones de PHP (5.4 a 7)?

Saludos.

**Comment by ywarnier** [comment]
Al momento de hacer el packaging de la versión beta (y luego estable), se hace en una versión de Ubuntu con PHP 5.4 (que ahora que lo pienso, va a ser un lío para esta versión 1.11.4 porque ya nada corre con PHP 5.4). Así las dependencias se generan sobre 5.4, pero ya veremos como nos va. En el peor caso subiremos la dependencia a PHP 5.5 o PHP 5.6 para esta versión 1.11.4 porque lamentablemente no tenemos los hombros suficientemente fuertes para soportar tantas versiones a la vez.

**Comment by nosolored** [comment]
Gracias.

Finalmente se resolvió en la máquina virtual con PHP 5.6 y con el servidor en la misma versión. 
La versión PHP 5.6 quizás debería ser la mínima para Chamilo 1.11.4 ya que según http://php.net/supported-versions.php tendrá correcciones hasta Diciembre 2018.

Voy a montar una máquina con Ubuntu/PHP 5.4 y os avanzo comentarios por ayudar.

**Comment by nosolored** [comment]
Montada la máquina virtual con Ubuntu y PHP 5.4.45.
Se genera correctamente el composer. Si necesitáis la salida completa que genera os las envío a correo.
Indica que el paquete facebook/php-sdk-v4 que está abandonado y sugiere utilizar facebook/graph-sdk
Cierro comentarios.

**Comment by pilar31** [comment]
Hola
He instalado xampp v 7.1 y al intentar instalar chamilo 1.11.4 me marca error de libreria obsoleta o deprecada mcrypt_module_open ¿Cómo puedo solucionar este error? , hasta el momento no he logrado encontrar como solucionarlo

**Comment by ywarnier** [comment]
Es probable que la versión 1.11.4 tenga unas dependencias equivocadas para PHP 7.1, pues fue preparada en base a PHP 5.5. Para la versión 1.11.6, es probable que tengamos un paquete en descarga para PHP 5 y otro para PHP 7, para evitar este tipo de problema.
En tu caso, si Xampp trae composer, puedes lanzar en línea de comando de Xampp, dentro de la raíz de Chamilo, un `composer update` para que actualice todas las dependencias. Posiblemente lo solucionaría.

**Comment by pilar31** [comment]
hola. Ya hice composer update y sigo teniendo problemas. ¿la única solución posible,  será tener un xampp con php 5+?

**Comment by jmontoyaa** [comment]
Indicar exactamente la version de PHP y el error en el que aparece el error. Yo tengo PHP 7.1.10 y no veo ese error.

**Comment by pilar31** [comment]
Me sigue saliendo error, y eso que ya me cambié a php 7.0.23

Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded. in C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(226): Doctrine\Common\Annotations\ in C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54

**Comment by jmontoyaa** [comment]
Estás usando la última versión de 1.11.x. Me parece que este error ya fue corregido. Y era un problema específico de XAMPP en windows.
