### ISSUE TITLE
Courses filler not working correctly

### ISSUE THREAD

**Issue by sjcqs** [chamilo/chamilo-lms#1881]
### Current behavior / Resultado actual / Résultat actuel
Two errors: 
1. PHP Error: `add_course.lib.inc.php:852` 
`setId` does not exists. It should be replaced with `setTool`
2. MySQLError: `add_course.lib.php:952`
`course_code` is not a field of gradebook table, should use `c_id` instead. 
### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0
### NB
The fix is done and I'll make a PR

( cc @moy)

**Comment by jmontoyaa** [comment]
I added some fixes for this. Now it should work.

**Comment by ywarnier** [comment]
No feedback provided. Closing.
