### ISSUE TITLE
Bug  terminar ejercicio 11.2

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1883]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes  en la version 11.2   realizando una  prueba/ejercicio con un limite de tiempo, si un estudiante no termina la prueba le sale un mensaje "ha llegado al tiempo limite, un momento por favor .Sera redirigido a otra pagina" hasta ahora esta correcto 
### Expected behavior / Resultado esperado / Résultat attendu
El problema es cuando el estudiante procede a dar terminar ejercicio  en el mensaje, este no realiza ninguna acción y sigue en un bug  
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Crear Una prueba. 
Ponga Un poco de Tiempo Límite. 
Guardarlo y Comenzar la previa Vista. - No la Terminan
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

![captura](https://cloud.githubusercontent.com/assets/20644209/25458668/6d7ffd34-2aa0-11e7-9822-ab5fec4da8fa.JPG)

**Comment by NicoDucou** [comment]
Recuerdo a ver visto este problema reportado anteriormente y que ha sido arreglado.

Acabo de probar aqui :+1: 
https://1.11.chamilo.org/main/exercise/exercise_result.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&exe_id=304&origin=&learnpath_id=0&learnpath_item_id=0&learnpath_item_view_id=0 

Me parece todo conforme ahora.

Puedes mirar y confirmar o crear un ejemplo para repoducir el problema en la plataforma de desarollo que prove la ultima version en desarollo aqui : https://1.11.chamilo.org/ 

Si pienses que no lo ha probado de la buena forma, mandanos el link donde se puede reproducir el problema en la plataforma de desarollo para revisarlo de nuevo. Sino en unos dias se cierrara este tarea.

Saludos

**Comment by ywarnier** [comment]
Sí, problema arreglado en 1.11.4 (que todavía no se publica pero será dentro de poco)
