### ISSUE TITLE
Announcements: title field should not submit on enter

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1888]
### Current behavior / Resultado actual / Résultat actuel
When you enter a subject title and  hit enter (yes, people are strange), the announcement is sent.
And unfortunately in 1.11.4 this is to all users of the course while in 1.11.2 it is not.
### Expected behavior / Resultado esperado / Résultat attendu
Don;t let the input field respond to enter (fix below)
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
See above
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 alpha

Shortest fix without using jquery:
/main/announcements/announcements.php
@@ -486,7 +486,7 @@ switch ($action) {

        //$form->addElement('text', 'title', get_lang('EmailTitle'));
        $form->addElement('text', 'title', get_lang('EmailTitle'),  array( "onkeypress" => "return event.keyCode != 13;") ); // ignore enter key

**Comment by ywarnier** [comment]
Your patch has been included. Thanks!
