### ISSUE TITLE
Undefined index when clicking on a course (2.0)

### ISSUE THREAD

**Issue by sjcqs** [chamilo/chamilo-lms#1891]
### Current behavior / Resultado actual / Résultat actuel
You cannot see a course. An error is thrown `Undefined index 'english'`. This error is due to the fact that api_get_language_isocode is not implemented and returns 'english'
### Expected behavior / Resultado esperado / Résultat attendu
Course page should appear.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Click on a course with a teacher.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0

(A fix is incoming ) 

(cc @moy)

**Comment by jmontoyaa** [comment]
I added different fixes for this ... To check

**Comment by ywarnier** [comment]
No feedback provided. Closing.
