### ISSUE TITLE
Impossible to add a user (2.0) 

### ISSUE THREAD

**Issue by SatyanJ** [chamilo/chamilo-lms#1894]
### Current behavior / Resultado actual / Résultat actuel
When a new user is added: 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'UNIQ_8D93D649A0D96FBF'
### Expected behavior / Resultado esperado / Résultat attendu
The user should be correctly added.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a new user.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0
### Useful part of the stacktrace:
```
at DoctrineORMEntityManager_000000005d8569f90000000058711e67e5139c916d21af4abfe5ffe5dd20d49e->flush()
 in /var/www/html/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Doctrine/UserManager.php line 100
at FOS\UserBundle\Doctrine\UserManager->updateUser(object(User), true)
 in /var/www/html/main/inc/lib/usermanager.lib.php line 405

```

**Comment by jmontoyaa** [comment]
Fixed. Reinstall or execute manually:

`DROP INDEX UNIQ_8D93D649A0D96FBF ON user;`
