### ISSUE TITLE
Reading comprehension question type

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1896]
We are considering the development of a new question type which would allow a teacher to (easily) test the reading speed and comprehension of his/her students. This would enable a better identification of students with reading issues, one of the fundamental criteria for a better education as reading is (still) a necessary skill for self-learning.

The new question type would work this way:

- teacher selects the question type
- enters a question description that is a long text
- enters an expected reading speed (the difficulty field can be used for that for now) in terms of "words per minute". A 1st-grader (secondary school) student is supposed to read at about 173w/m, on average people read at 250w/m and a speed-reader will read at 650w/m, up to 2000w/m. Given we have 5 difficulties and we don't focus on speed readers, we could use 50, 100, 173, 250 and 400 for now.
- enters one question that verifies the understanding of the text (we hope to be able to add more than one question in the future, but a preliminary version will only have one question)

The student enters the test and a text area appears with a button to "start reading" on top of a partially hidden text, like this example from http://projects.wsj.com/speedread/.

![speed-reading](https://cloud.githubusercontent.com/assets/609839/25543737/5cea5f4a-2c1d-11e7-989c-512fb1972af7.png)

Depending on the number of words and the time allowed, a small rectangle would appear around the current line and go down slowly.

![speed-reading](https://cloud.githubusercontent.com/assets/609839/25543928/06a7d332-2c1e-11e7-848d-5e78d5d2d25f.png)

When the line reaches the bottom of the text, it disappears and the text is not visible anymore. At this point, the real question appears and the student selects the right answer.
If the student got it right, he/she officially obtains his results, including the reading speed he/she obtained. If not, a message indicates that he failed to read at this speed (the speed shows).

**Comment by AngelFQC** [comment]
The `processText` function works with text plain, no HTML like now. Because str_word_count does not understand the HTML tags (like `<p>`, `</p>`)

**Comment by AngelFQC** [comment]
Question type created here https://github.com/chamilo/chamilo-lms/pull/1909
