### ISSUE TITLE
Error upgrade 1.9.x to 1.11.2

### ISSUE THREAD

**Issue by fgauttron** [chamilo/chamilo-lms#1898]
### Current behavior / Resultado actual / Résultat actuel
We have this error when we want make upgrade /main/install/

Parse error: syntax error, unexpected '[' in /var/www/chamilo1961/vendor/react/promise/src/functions.php on line 15 Call Stack: 0.0019 1095520 1. {main}() /var/www/chamilo1961/main/install/index.php:0 0.0020 1096720 2. require_once('/var/www/chamilo1961/vendor/autoload.php') /var/www/chamilo1961/main/install/index.php:27 0.0020 1100824 3. ComposerAutoloaderInitc5ab92fb525abd7df320d51085e0b2ec::getLoader() /var/www/chamilo1961/vendor/autoload.php:7 0.0268 1987616 4. composerRequirec5ab92fb525abd7df320d51085e0b2ec() /var/www/chamilo1961/vendor/composer/autoload_real.php:45 0.0269 1988784 5. require('/var/www/chamilo1961/vendor/react/promise/src/functions_include.php') /var/www/chamilo1961/vendor/composer/autoload_real.php:55

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo 1.9.8

**Comment by fgauttron** [comment]
I have upgraded to php 5.6, but i have another error 👍 
Warning: require_once(/var/www/html/chamilo/vendor/symfony/doctrine-bridge/Validator/Constraints/UniqueEntity.php): failed to open stream: No such file or directory in /var/www/chamilo/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 64

**Comment by jmontoyaa** [comment]
"composer update" was executed before the upgrade?

**Comment by fgauttron** [comment]
When i want make composer update, i have these error 

PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/chamilo/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 104

**Comment by jmontoyaa** [comment]
I recommend to install the latest 1.11.x code which contains lots of fixes from 1.11.2

https://github.com/chamilo/chamilo-lms/tree/1.11.x (download button)

**Comment by ywarnier** [comment]
A safer recommendation would be to wait for 1.11.4, hopefully to be released by the end of May

**Comment by ywarnier** [comment]
@fgauttron, if your portal is not too large, you might want to try 1.11.4 alpha 2: https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.4-alpha.2. This might already fix a number of issues you might have found in 1.11.2.

**Comment by ywarnier** [comment]
No feedback provided in months. Closing.
