### ISSUE TITLE
I have a 404 error during installation

### ISSUE THREAD

**Issue by MichaelMejiaMora** [chamilo/chamilo-lms#1900]
### Current behavior / Resultado actual / Résultat actuel
I have a 404 error during installation
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
![1](https://cloud.githubusercontent.com/assets/19955080/25565867/28085b26-2d8d-11e7-87d0-d639f9b23154.JPG)
![2](https://cloud.githubusercontent.com/assets/19955080/25565868/280b0f06-2d8d-11e7-85b6-2c6bf22c211d.JPG)
### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0

**Comment by ywarnier** [comment]
Version 2.0 is not alpha yet. The installation process is not supposed to work at this point. Please use the 1.11.x branch (if you're going to use a development version anyway).

**Comment by MichaelMejiaMora** [comment]
Thanks.
