### ISSUE TITLE
groups: unable to subscribe to group (v 1.11.4)

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1901]
### Current behavior / Resultado actual / Résultat actuel
works in 1.11.2 but not in 1.11.4alpha:

- teacher wants to add himself to a group but his name is not in the left select box to choose his own name.
- student cannot subscribe because subscribe button is not shown in group list
### Expected behavior / Resultado esperado / Résultat attendu
Expected to work as in 1.11.2: both should be able to add or register in a group
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
see behavior.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4alfa git dd april 28 2017

Suspect regression change: https://github.com/chamilo/chamilo-lms/commit/3c285f525fa271ab8ea34da7be72d64ea9f50bc9

**Comment by jderriks** [comment]
fix:
https://github.com/chamilo/chamilo-lms/pull/1902/commits/217f44a9a920883661933fadc66a3edfde0e3a29

**Comment by jmontoyaa** [comment]
Should be fixed now.
