### ISSUE TITLE
Horas de "Mi progreso" e "Informes" no es correcto cuando un curso tiene Lección y Ejercicio a la vez

### ISSUE THREAD

**Issue by miky96es** [chamilo/chamilo-lms#1910]
### Current behavior / Resultado actual / Résultat actuel
![image](https://cloud.githubusercontent.com/assets/17494657/25658790/f311eae8-3004-11e7-89e9-407cb128c567.png)
Aparecen las horas a 0 cuando en realidad si que hay horas dentro.

![image](https://cloud.githubusercontent.com/assets/17494657/25658908/7fd2c4b6-3005-11e7-87c9-3f77802f5ca9.png)
Cuando doy clic a detalles si que aparecen las horas empleadas en el curso correctamente.

### Expected behavior / Resultado esperado / Résultat attendu
Lo que espero es que  en ambos lados salga el dato de horas empleadas correctamente sin necesidad de clicar a detalles.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Para reproducir este error debemos crear un curso con lecciones y ejercicios, también debemos crear  un usuario que este asignado a este curso recién creado, una vez asignado,se debe acabar la lección y el ejercicio , una vez acabado el ejercicio y la lección, nos vamos a "Mi progreso" y veremos que el contador de horas no es correcto.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
Sí, confirmo que este es un problema grave que hay que corregir antes de la 1.11.4. Me pasó a mi también pero no he tenido tiempo para registrar la tarea. Es muy sencillo reproducir con un nuevo usuario entrando a un curso cualquiera -> no se registra su tiempo de conexión. Esto parece haber sido causado por algo entre 1.11.2 y ahora, porque me parece que no estaba en 1.11.2.

**Comment by AngelFQC** [comment]
I got this
![page-shot-2017-5-25 my organisation - my campus - progress](https://cloud.githubusercontent.com/assets/1697880/26455893/1cceb568-4131-11e7-8de1-4055ff7c6310.png)

Can you replicate it in 1.11.chamilo.org?

**Comment by ywarnier** [comment]
No feedback provided. Pushing back to 1.11.6.
