### ISSUE TITLE
Registration emails not multi-language

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#1912]
When using email templates for registration, the sent emails don't use the specified values from the backend.
Instead variable $MailTemplateRegistrationMessage is used.
Would not be that problem, but it seems to be language-independent, since it will always be used english.

**Comment by ywarnier** [comment]
The normal behaviour is to send e-mails in the language of the student. When the student has no language (as is the case for the registration), the default platform language is used.
Could you confirm that this is *not* happening at the moment?

**Comment by lonesomewalker** [comment]
Well, these emails even don't use the translated strings from the language files.
So i guess the problem lies there.

**Comment by lonesomewalker** [comment]
Current alpha no emails sent... :-(
(mail.conf.php is set up)

**Comment by jmontoyaa** [comment]
The variable $MailTemplateRegistrationMessage is not used anymore.
You need to clean your cache app/cache/twig/*

**Comment by ywarnier** [comment]
No feedback provided in months (not even a thank you). Closing.
