### ISSUE TITLE
Field Lastname|Firstname not exported in exercise reporting if option "Only best attempts" is checked

### ISSUE THREAD

**Issue by baelmyhu** [chamilo/chamilo-lms#1914]
### Current behavior / Resultado actual / Résultat actuel
When exporting quiz results in Excel/csv checking the option "Only best attempts"
fields Lastname, Firstname and Email are not exported in exported file

### Expected behavior / Resultado esperado / Résultat attendu
Display fields Lastname, Firstname and Email in export file even if option "Only best attempts" has been checked. 

Solution :
Edit file main/exercise/exercise_result.class.php
In function public function getExercisesReporting
Replace
```
       }

        if ($this->onlyBestAttempts) {
            $results = $bestAttemptPerUser;
        }

        $filter_by_not_revised = false;
```
with
```
       }

        if ($this->onlyBestAttempts) {
            // do an array merge to start $bestAttemptPerUser array key from 0
            // otherwise, we got no user info
            $results = array_merge($results, $bestAttemptPerUser);
        }

        $filter_by_not_revised = false;

```

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Pass a test, and select Export in Excel/csv and check the option "Only best attempts" 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Given you have added the OnlyBestAttempt option, @jmontoyaa, I insist :-)

**Comment by ywarnier** [comment]
Tested and approved, except I've made a change in the way the array indexes are removed:
```
        if ($this->onlyBestAttempts) {
            // Remove userId indexes to avoid issues in output
            foreach ($bestAttemptPerUser as $attempt) {
                $results[] = $attempt;
            }
            // This could also be done by any of the 3 following methods, but
            // the load over small data sets proved to be lower with foreach
            //$results = array_values($bestAttemptPerUser);
            //$results = array_merge([], $bestAttemptPerUser);
            //$results = array_merge($results, $bestAttemptPerUser);
        }
```
