### ISSUE TITLE
Bug V. 11.2 al entrar a los curso mas populares 

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1919]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes  estoy realizando una prueba en la ultima version de chamilo, en la pagina principal nos arroja un error  en la pagina principal Fatal error: Call to undefined method SessionManager::searchCourseInSessionsFromUser() in /var/www/html/main/inc/local.inc.php on line 1324

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Nos ubicamos en la pagina principal,
No se inicia sesión  
En los cursos mas populares  le damos un click a uno de ellos 
esto nos dirige a un error 

![pagina principal](https://cloud.githubusercontent.com/assets/20644209/25766855/d7a11a6a-31ba-11e7-8c0b-53fb12b52def.JPG)
![error](https://cloud.githubusercontent.com/assets/20644209/25766865/e22bd98e-31ba-11e7-94b0-9b9980986f41.JPG)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
11.2 x el archivo local.ini.php  se descargo y se remplazo

**Comment by jmontoyaa** [comment]
Agregar :

En main/inc/lib/sessionmanager.lib.php

```

/**
     * @param int $userId
     * @param int $courseId
     *
     * @return array
     */
    public static function searchCourseInSessionsFromUser($userId, $courseId)
    {
        $table = Database::get_main_table(TABLE_MAIN_SESSION_COURSE_USER);
        $userId = (int) $userId;
        $courseId = (int) $courseId;
        if (empty($userId) || empty($courseId)) {
            return [];
        }

        $sql = "SELECT * FROM $table 
                WHERE c_id = $courseId AND user_id = $userId";
        $result = Database::query($sql);

        return Database::store_result($result, 'ASSOC');
    }
```

**Comment by fergimon** [comment]
Buenas tardes @jmontoyaa  y @ywarnier   funciono correctamente la  adición del código, doy por cerrado el caso.
