### ISSUE TITLE
Users tool: too many columns for student view

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1924]
### Current behavior / Resultado actual / Résultat actuel
A student can see the userID of course members (and more) if the users tool is visible for learners. The first UserID column is sensitive and not needed. Other columns may show sensitive user data also.
<img width="857" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/25808587/da1819d6-340a-11e7-972b-c05d74464f84.png">

### Expected behavior / Resultado esperado / Résultat attendu
Show only photo, firstname, lastname,  and group column in the student view. The rest may be sensitive info and is not a need-to-know for students. 
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Login as a student on a course with many other students and click on the user tool
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jderriks** [comment]
And some coding bugs in the parsing of the configuration variable in api.lib.php:
   // Check if variable exists
    if (isset($_configuration[$variable])) {
        if (is_array($_configuration[$variable])) {
            // Check if it exists for the sub portal
            **if (array_key_exists($urlId, $_configuration[$variable])) {**
                return $_configuration[$variable][$urlId];
            }
        }

Well, array_key 1 will exist in any array that has more than 1 entry but we don't use urlId's.

Chamilo needs regression tests. Badly.

**Comment by jderriks** [comment]
And another bug in user.php:
$table->set_header($header_nr++, get_lang('OfficialCode'));
$indexList['official_code'] = $header_nr;

if ($is_western_name_order) {
    $indexList['firstname'] = $header_nr;

So index firstname and official_code both get header number 3. That's wrong.

Are there any Behat/Mink test templates available?

**Comment by jmontoyaa** [comment]
I remove the user id. In order to hide other columns you can use in configuration.php

`$_configuration['hide_user_field_from_list'] = ['username'];`

You're welcome to add behat tests here:

https://github.com/chamilo/chamilo-lms/tree/1.11.x/tests/behat/features

You can read the documentation about it here:

https://github.com/chamilo/chamilo-lms/tree/1.11.x/tests/behat

**Comment by jderriks** [comment]
Almost fixed. Try this for a test:
$_configuration['hide_user_field_from_list'] = ['username', 'official_code'];
and it fails because array index 1 is now set (api.lib.php function api_get_configuration_value)

**Comment by jmontoyaa** [comment]
I just added a fix the setting now it should be:

`$_configuration['hide_user_field_from_list'] = ['fields' => ['username']];`

**Comment by jderriks** [comment]
Maybe I have the wrong git repo but the indexList for the hode fields had a duplicate index 3 for Firstname and officialcode:
<img width="200" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/26260224/b7e2678e-3ccc-11e7-8985-b6faeea60f29.png">

**Comment by jmontoyaa** [comment]
I fixed that,  but it does not affect the behaviour of the hide fields funcionality.
