### ISSUE TITLE
Permitir exportar cebeceras tambien a formato XLS 

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#1933]
### Current behavior / Resultado actual / Résultat actuel
No tiene sentido marca la opción exportar cabeceras de CSV si no me lo permite en XLS, la variable de idioma solo deberia decir Exportar cabeceras
![export](https://cloud.githubusercontent.com/assets/2940509/25874375/e94985ac-34d7-11e7-9c7c-70524f99ab03.png)

### Expected behavior / Resultado esperado / Résultat attendu
Exportar cabceras tambien en formato XLS
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by aragonc** [comment]
Solo falta renombrar la variables de idioma para que solo diga Exportar cabeceras... @ywarnier

**Comment by ywarnier** [comment]
Variables de idiomas actualizadas en en/fr/es
