### ISSUE TITLE
Error al corregir ejercicio 11.2

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1936]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes revisando  la version 11.2  en la parte de calificacion de examen  me arroja un error " 
Fatal error: Call to undefined method ExerciseLib::getEmailNotification() in /var/www/html/main/exercise/exercise_show.php on line 943"

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Se crea una prueba para que el docente la pueda corregir
El docente procede a corregir  el examen y en la parte final de esta sale este mensaje
"Fatal error: Call to undefined method ExerciseLib::getEmailNotification() in /var/www/html/main/exercise/exercise_show.php on line 943"   

### Chamilo Version / Versión de Chamilo / Version de Chamilo
![error](https://cloud.githubusercontent.com/assets/20644209/25921605/b51c13a2-359b-11e7-8721-1a46bb161da6.JPG)

11.2 x el archivo  exercise_show.php se descargo  y se actualizo.

**Comment by jmontoyaa** [comment]
El archivo main/inc/lib/exercise.lib.php también ha sido modificado.

**Comment by fergimon** [comment]
muchas gracias @jmontoyaa  ya se soluciono el problema, se da por cerrado ticket
