### ISSUE TITLE
Wrong result function is_certificate_available()

### ISSUE THREAD

**Issue by hi-rafa** [chamilo/chamilo-lms#1938]
### Current behavior / Resultado actual / Résultat actuel
When you complete the learning path of a session course the function still returns false
meaning that the certificate is not available.
<img width="1216" alt="screen shot 2017-05-11 at 9 40 15 am" src="https://cloud.githubusercontent.com/assets/3813277/25938154/99115094-362e-11e7-96cf-3fbe6d42c098.png">
<img width="1277" alt="screen shot 2017-05-11 at 9 42 51 am" src="https://cloud.githubusercontent.com/assets/3813277/25938160/9d561f68-362e-11e7-999b-0334cde3a405.png">
<img width="1223" alt="screen shot 2017-05-11 at 8 58 58 am" src="https://cloud.githubusercontent.com/assets/3813277/25938170/a5cfab3c-362e-11e7-9410-d191af35b869.png">
<img width="1201" alt="screen shot 2017-05-11 at 8 58 00 am" src="https://cloud.githubusercontent.com/assets/3813277/25938178/ac3e8e84-362e-11e7-8df1-c97bc0d2c4e2.png">

### Expected behavior / Resultado esperado / Résultat attendu
When you complete the learning path of session course the function should returns true
meaning that the certificate is available.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. Create a course with a scorm
2. Create a session with the previous course created and import it with the gradebook
3. Admin user - View page (Corporate report) 
4. Student user - View page (My courses)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by hi-rafa** [comment]
I know where the issue is but I wanted to share it anyway before I do any pull request.
<img width="1179" alt="screen shot 2017-05-11 at 8 59 24 am" src="https://cloud.githubusercontent.com/assets/3813277/25938333/218b3674-362f-11e7-83a8-ba282138a445.png">
<img width="1187" alt="screen shot 2017-05-11 at 8 59 15 am" src="https://cloud.githubusercontent.com/assets/3813277/25938340/24f701e4-362f-11e7-9489-be7f04fb1e67.png">

**Comment by ywarnier** [comment]
Commit added. Closing.
