### ISSUE TITLE
FBCKComplete is not supported anymore

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1941]
### Current behavior
As admin, looking at a skills wheel with some skills, the search box for skills calls the skill.ajax.php file and gets a list of results but does not offer auto-complete.

### Expected behavior
A list of the different possibilities should appear in a dropbox.

### Steps to reproduce
Create a few skills.
Go to the skills wheel.
Search for one of the skills created.
No auto-complete takes effect (it did in version 1.11.2).

### Chamilo Version
1.11.x

**Comment by AngelFQC** [comment]
Search by ajax from FCBKComplete stopped working maybe by jQuery version

**Comment by AngelFQC** [comment]
FCBKcomplete is deprecated 😢 I'm switching to select2.
But there are more places where we are using FCBKComplete, like extrafield of type tag

**Comment by AngelFQC** [comment]
FBCKComplete now is replaced with Select2

**Comment by jmontoyaa** [comment]
Something is wrong after this changes. Try creating a user and you will see a lot of warnings/notices:

Warning: PDO::quote() expects parameter 1 to be string, array given in /var/www/html/chamilo_111/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 115
Call Stack
#	Time	Memory	Function	Location
1	0.0011	389456	{main}( )	.../user_add.php:0
2	0.3365	10146600	UserManager::create_user( )	.../user_add.php:436
3	0.4772	12125840	UserManager::update_extra_field_value( )	.../usermanager.lib.php:394
4	0.4772	12127224	ExtraFieldValue->save( )	.../usermanager.lib.php:2095
5	0.4777	12131384	ExtraFieldValue->getAllValuesByItemAndFieldAndValue( )	.../extra_field_value.lib.php:398
6	0.4777	12131384	Database::escape_string( )	.../extra_field_value.lib.php:832
7	0.4777	12131384	Doctrine\DBAL\Connection->quote( )	.../database.lib.php:241
8	0.4777	12131384	Doctrine\DBAL\Driver\PDOConnection->quote( )	.../Connection.php:771
9	0.4777	12131384	quote ( )	.../PDOConnection.php:115


Notice: Undefined index: display_text in /var/www/html/chamilo_111/main/inc/lib/extra_field_option.lib.php on line 768

Notice: Undefined index: id in /var/www/html/chamilo_111/main/inc/lib/extra_field_value.lib.php on line 461

**Comment by jmontoyaa** [comment]
In the user form I cannot add new tags also ...
![selection_004](https://cloud.githubusercontent.com/assets/158935/26108704/9bf038ac-3a4d-11e7-8a11-e743c20702cb.png)

**Comment by jmontoyaa** [comment]
I did a composer update too ...

**Comment by AngelFQC** [comment]
Try now with the last commit

**Comment by ywarnier** [comment]
Looks good to me now. Closing.

**Comment by jmontoyaa** [comment]
I confirm, now I don't see the warnings and the js error.
