### ISSUE TITLE
Course settings: every user can access all non-private courses

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1942]
### Current behavior / Resultado actual / Résultat actuel
The 1.11 manual says in chapter 7:
--------------
"Open : means all users registered on the portal can access the course **as long as they have previously subscribed to it (they can do this through the courses catalog)**. This is the default option."
----------------
But when a link is published or you type ...courses/name-of-course every user can view documents and other tools just like subscribed users.

### Expected behavior / Resultado esperado / Résultat attendu
Only if a user subscribed to the course he should be able to view documents and other tools

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Register as student on https://1.11.chamilo.org/courses/CQT and goto that URL. Access without subscribing to the course.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x and possibly older versions too.

This could be considered a security issue.

**Comment by jmontoyaa** [comment]
Open - access allowed for users registered on the platform. 
Private access (access authorized to group members only)  

I think there's an error in the manual @ywarnier

**Comment by jderriks** [comment]
This means that subscribing to a course is a fake action. If you have the link to a course and you want to stay "hidden" as a student, just follow the link. Teachers may be unaware that their documents are visible for all platform users. Making the course private is not an option if you want students to register. Moodle and Blackboard do it like the manual says: you must subscribe.

Changing the manual is the easiest way to solve this issue of course :-) 
The manual should then explain what benefits subscribing has, like receiving email announcements and being part of groups and listed as a course user.

**Comment by ywarnier** [comment]
Didn't we develop a configuration setting for this? I believe we saw the issue and developed a patch.
I agree 100% with @jderriks that an open course (as opposed to a public course) should not allow you to enter without subscribing, but we've had the discussion with other people who think that it's OK for someone subscribed to the platform to enter an open course without subscribing to it explicitly.
As a result, I believe we came to the "patch solution" of having a configuration option decide which behaviour it is.
There we go (I couldn't find it befire):
```
// Security: block direct access from logged in users to contents in OPEN (but not public) courses. Set to true to block
//$_configuration['block_registered_users_access_to_open_course_contents'] = false;
```
This is available in configuration.dist.php. It is then checked in local.inc.php.

I believe we can thus close this task?

**Comment by jderriks** [comment]
Nice!  Also useful info to put in the manual.

**Comment by ywarnier** [comment]
We tend not to document these until they get into the settings_current table. Many times they change a bit before getting there. It's like our "beta version" of configuration settings because we can't add them to the database between minor versions.

**Comment by ywarnier** [comment]
This being said, you can also contribute to the manual here: https://github.com/chamilo/docs/tree/master/1.11/en/teacher for the teacher guide. For the admin guide, there's still no change from the 1.9 version, but if you want to help on any of these, I'm glad to let you send as many updates as you like.

**Comment by SamMaesschalck** [comment]
We are setting up Chamilo within our environment, and we are running into the same issue as described here. When we apply the fix provided by Yannick the user gets a message they do not have access to the course when going to the course through the course catalog. This behavior is no different from when we make the course private. If the user goes via the homepage they do get the about page with the option to subscribe. We want all our users to get the about page with the option to subscribe when they access an open course they are not subscribed to. Similar to the experience with Moodle.

Has there been any more work on this issue since the patch in configuration.dist.php?
