### ISSUE TITLE
Upload SCORM 1.2 impossible

### ISSUE THREAD

**Issue by ChloeV** [chamilo/chamilo-lms#1948]
L'import d'un package SCORM 1.2 / SCORM 2004 / AICC ne fonctionne pas.

Un message d'erreur apparait :
![capture d ecran 2017-05-15 a 14 32 34](https://cloud.githubusercontent.com/assets/28706818/26057794/5b436e14-397b-11e7-9713-29470baa145e.png)
[debug_information.docx](https://github.com/chamilo/chamilo-lms/files/1001075/debug_information.docx)

Voici le fichier SCORM que je souhaite importer : 
[la-creation-de-grains-pedagogiques-scorm12-l1m3Hxiv.zip](https://github.com/chamilo/chamilo-lms/files/1001050/la-creation-de-grains-pedagogiques-scorm12-l1m3Hxiv.zip)

Version Chamilo : 1.10.8

**Comment by ywarnier** [comment]
Bonjour, Chamilo ne supporte que AICC et SCORM 1.2, pas SCORM 2004, qui est le format du fichier utilisé ici, d'après les messages d'erreur du document .docx.
La plupart des outils permettant de générer du SCORM 2004 permettent également de générer les (mêmes) paquets en SCORM 1.2. Le développement du support pour SCORM 2004 représente environ 200 heures de travail et SCORM 2004 a maintenant été rendu obsolète par TinCan (xAPI), raison pour laquelle nous ne développerons pas le support de SCORM 2004, à moins qu'un généreux mécène ne finance le travail correspondant. Nous avons l'intention d'implémenter TinCan dans les prochains mois, mais sans deadline ferme (il nous manque également un ou plusieurs mécènes de ce côté).

S'il n'y a pas de commentaire supplémentaire au sujet du support 2004, je me permettrai de clôturer ce ticket d'ici 3 jours environ.

**Comment by ChloeV** [comment]
Bonjour,


Je vous remercie pour cette réponse aussi rapide ! Il me semble cependant que le format du SCORM que je tente d'uploader est bien SCORM 1.2. Je vous joins l'ims manifest en question.


Cordialement,



Chloé VANBERKEL
Conceptrice pédagogique

+33(0)4 76 26 62 82





6 av Pierre de Coubertin
38170 Seyssinet-Pariset

www.omendo.com




ATTENTION : Changement d’adresse de l’antenne à Paris
Désormais, il vous faudra adresser vos correspondances au 10-18 Villa Saint Michel - 75018 Paris




________________________________
De : Yannick Warnier <notifications@github.com>
Envoyé : lundi 15 mai 2017 17:18
À : chamilo/chamilo-lms
Cc : Chloé Van berkel; Author
Objet : Re: [chamilo/chamilo-lms] Upload SCORM 1.2 impossible (#1948)


Bonjour, Chamilo ne supporte que AICC et SCORM 1.2, pas SCORM 2004, qui est le format du fichier utilisé ici, d'après les messages d'erreur du document .docx.
La plupart des outils permettant de générer du SCORM 2004 permettent également de générer les (mêmes) paquets en SCORM 1.2. Le développement du support pour SCORM 2004 représente environ 200 heures de travail et SCORM 2004 a maintenant été rendu obsolète par TinCan (xAPI), raison pour laquelle nous ne développerons pas le support de SCORM 2004, à moins qu'un généreux mécène ne finance le travail correspondant. Nous avons l'intention d'implémenter TinCan dans les prochains mois, mais sans deadline ferme (il nous manque également un ou plusieurs mécènes de ce côté).

S'il n'y a pas de commentaire supplémentaire au sujet du support 2004, je me permettrai de clôturer ce ticket d'ici 3 jours environ.

**Comment by ywarnier** [comment]
Indépendamment du imsmanifest.xml, le code de debug envoyé dans le document .docx montre que le parcours détecte de façon erronée que Chamilo fonctionne en SCORM 2004, et ensuite se plante en essayant d'envoyer des commandes à Chamilo dans cette version 2004.
Il semblerait que le cours essaie d'abord SCORM2004 et puis SCORM 1.2. Je vois des références au moteur du SCORM cloud de Rustici software. Il faudrait voir de ce côté s'il est possible de forcer le mode SCORM 1.2. Sinon, il serait nécessaire de faire une modification au code de Chamilo pour s'assurer qu'il réponde bien "faux" à toute tentative de communication en SCORM 2004 (ce qu'il faudrait étudier auparavant).

**Comment by ChloeV** [comment]
Je vais donc soumettre ces informations à notre équipe de développeur afin de voir s'ils arrivent à forcer tout ça !

Je vous remercie vivement pour votre rapidité et vos conseils et vous souhaite une bonne continuation. Je saurais vous tenir au courant de l'issue du problème ;)


Excellent fin de journée.



Chloé VANBERKEL
Conceptrice pédagogique

+33(0)4 76 26 62 82





6 av Pierre de Coubertin
38170 Seyssinet-Pariset

www.omendo.com




ATTENTION : Changement d’adresse de l’antenne à Paris
Désormais, il vous faudra adresser vos correspondances au 10-18 Villa Saint Michel - 75018 Paris




________________________________
De : Yannick Warnier <notifications@github.com>
Envoyé : lundi 15 mai 2017 17:40
À : chamilo/chamilo-lms
Cc : Chloé Van berkel; Author
Objet : Re: [chamilo/chamilo-lms] Upload SCORM 1.2 impossible (#1948)


Indépendamment du imsmanifest.xml, le code de debug envoyé dans le document .docx montre que le parcours détecte de façon erronée que Chamilo fonctionne en SCORM 2004, et ensuite se plante en essayant d'envoyer des commandes à Chamilo dans cette version 2004.
Il semblerait que le cours essaie d'abord SCORM2004 et puis SCORM 1.2. Je vois des références au moteur du SCORM cloud de Rustici software. Il faudrait voir de ce côté s'il est possible de forcer le mode SCORM 1.2. Sinon, il serait nécessaire de faire une modification au code de Chamilo pour s'assurer qu'il réponde bien "faux" à toute tentative de communication en SCORM 2004 (ce qu'il faudrait étudier auparavant).
