### ISSUE TITLE
Calculated questions enhancement for 1.11.4

### ISSUE THREAD

**Issue by baelmyhu** [chamilo/chamilo-lms#1952]
cf. https://chamilosimsu.wordpress.com/2017/04/20/refonte-des-questions-calculees/

I work on it this week, if it can be ok for you

best regards

**Comment by ywarnier** [comment]
It is possible that we'll have to push that back to 1.11.6. I'm trying to do a feature freeze today, so this would come a bit too late, but there *will* be a 1.11.6 anyway (and I don't think it will be as long to release as 1.11.4), so no big issue.

**Comment by ywarnier** [comment]
Any update on this?

**Comment by ywarnier** [comment]
Any update?
