### ISSUE TITLE
Migración de 1.10.8 a 1.11.4 - Reporte

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1954]
### Current behavior / Resultado actual / Résultat actuel
La migración se ha realizado en una instalación Chamilo 1.10.8 con PHP 5.6.x. que se ha ido actualizado conforme se liberaban las ramas estables (desde 1.8).

**Fichero error_log:**
Al inicio de la migración muestra:
Starting migration process from 1.9.10.4 (2017-05-17 18:06:37)
El proceso termina con 
Upgrade 1.10.x process concluded! (2017-05-17 18:06:39). There was an error during running migrations. Check error.log

**Errores:**
El proceso de migración se realiza pero al final muestra un error en la pantalla de .../main/install en detalle que genera el proceso.

```
VERSION: 20160808110200
----------------------------------------------
UPDATE c_forum_post SET post_parent_id = NULL WHERE post_parent_id = 0

DONE!
ERROR: An exception occurred while executing 'ALTER TABLE ticket_category_rel_user ADD CONSTRAINT FK_5B8A98712469DE2 FOREIGN KEY (category_id) REFERENCES ticket_category (id)':
```

Se elimina el directorio /main/instal y al entrar en la Web muestra un error 500:
- PHP Fatal error:  Class 'Skype' not found in .../plugin/skype/plugin.php on line 9, referer: .../main/admin/
Eliminando el plugin/skype se soluciona y permite el acceso.

**- Activación de plugins en la Administración**
Al intentar activar cualquier plugin muestra en el error_log:
An exception occurred while executing 'CREATE TABLE plugin_buycourses_paypal_account (id INT UNSIGNED AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, signature VARCHAR(255) NOT NULL, sandbox TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'plugin_buycourses_paypal_account' already exists, referer: .../main/admin/settings.php?category=Plugins

**- Red social (main/messages/inbox.php)**
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e1_.visible_to_self' in 'where clause'' in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)\n#1 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(847): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 .../vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\\DBAL\\Connection->executeQuery('SELECT e0_.id A...', Array, Array, NULL)\n#3 .../vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\\ORM\\Query\\Exec\\SingleSelectExecutor->execute(Object(Doctrine\\DBAL\\Connection), Array, Array)\n#4 .../vendor/doctrine/ in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71, referer: http://www.dominio.com/courses/INFO17/index.php

**- Clic en Mis cursos (user_portal.php?nosession=true):**
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 's0_.profile_id' in 'field list'' in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104\nStack trace:\n#0 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT s0_.id A...')\n#1 .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\\DBAL\\Driver\\PDOConnection->query('SELECT s0_.id A...')\n#2 .../vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\\DBAL\\Connection->executeQuery('SELECT s0_.id A...', Array, Array, NULL)\n#3 .../vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\\ORM\\Query\\Exec\\SingleSelectExecutor->execute(Object(Doctrine\\DBAL\\Connection), Array, Array)\n#4 /.../ht in .../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71, referer: http://www.dominio.com/courses/INFO17/index.php

**- Error en lecciones (main/newscorm/lp_controller.php?**cidReq=IB&id_session=0&gidReq=0&gradebook=0&origin=)
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.email_canonical' in 'field list'' in /.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)\n#1 /.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(847): Doctrine\\DBAL\\Driver\\PDOStatement->execute()\n#2 /.../vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(748): Doctrine\\DBAL\\Connection->executeQuery('SELECT t0.id AS...', Array, Array)\n#3 /.../vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(411): Doctrine\\ORM\\Persisters\\BasicEntityPersister->load(Array)\n#4 /.../vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php(15 in /.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 71, referer: http://www.dominio.com/courses/IB/index.php

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Desde Chamilo 1.10.8 utilizar código git, composer update y simular la migración a 1.11.4.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Chamilo 1.10.8

**Comment by jmontoyaa** [comment]
What the result of:

`select * from version;`

**Comment by nosolored** [comment]
`110
20150423093100
20150504182600
20150505132304
20150505142900
20150507152600
20150511133949
20150519153200
20150521113600
20150522112023
20150522222222
20150527101600
20150527114220
20150527120703
20150528103216
20150529164400
20150603142550
20150603151200
20150603181728
20150604145047
20150608104600
20150609113500
20150610143426
20150615171900
20150616093200
20150624164100
20150625155000
20150706135000
20150709083710
20150713132630
20150803163400
20150803171220
20150805161000
20150810132615
20150812230500
20150813143000
20150813200000
20150819095300
20150821150000
20150825141100
20151101082200
20151101082300
20151119082400
20151214164000
20151214170800
20151221150100
20160707131900
20160808110200`

**Comment by jmontoyaa** [comment]
Your installation was never migrated to 1.11.x 
The latest version id "20160808110200" it corresponds to 1.10.x
I adde a fix for the "ALTER TABLE ticket_category_rel_user ".

**Comment by nosolored** [comment]
Gracias.

He aplicado los cambios del git y probado de nuevo la migración con Chamilo 1.10.x

Muestra el error siguiente:

```
VERSION: 20160808110200
----------------------------------------------
UPDATE c_forum_post SET post_parent_id = NULL WHERE post_parent_id = 0

DONE!
ERROR: An exception occurred while executing 'ALTER TABLE ticket_category_rel_user ADD CONSTRAINT FK_5B8A98712469DE2 FOREIGN KEY (category_id) REFERENCES ticket_category (id)':

SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```

**Comment by ywarnier** [comment]
A ver si podeis probar con la 1.11.4 alpha, por si arregla algo:
https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.4-alpha.1

**Comment by jmontoyaa** [comment]
Cual es el resultado de:

`show create table ticket_category_rel_user;`

antes y después de la migración.

**Comment by nosolored** [comment]
Lo probamos de nuevo ayer por la tarde con el último código de la 1.11.x (nos queda pendiente revisar con el de hoy y con la 1.11.4 alpha).

¿Hay que convertir previamente toda la base de datos de MyISAM a InnoDB y el cotejamiento (collate) a ut8_general_ci? ¿En el proceso de migración debería comprobar estos parámetros?

¿Puede ser debido a esto?
No se puede crear una Foreign Key entre una tabla MyISAM y una InnoDB
¿el proceso de migración o instalación debería forzar el innoDB ya que en algunos hosting puede estar por defecto en MyISAM?
y también forzar el utf-8 a utf_8_general o utf_8_unicode_ci ya que hay hosting con otra codificación c omo latin1_spanish u otras y esto puede crear inconsistencias.

Os indico resultados:

En 1.10 no existe la tabla.
plugin_ticket_category --> MyISAM > latin1_spanish_ci
```
En 1.11.x

Table
Create Table
ticket_category_rel_user
CREATE TABLE `ticket_category_rel_user` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `category_id` int(11) DEFAULT NULL,
 `user_id` int(11) DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `IDX_5B8A98712469DE2` (`category_id`),
 KEY `IDX_5B8A987A76ED395` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```
```
CREATE TABLE `ticket_category` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `project_id` int(11) DEFAULT NULL,
 `name` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
 `description` longtext COLLATE latin1_spanish_ci,
 `total_tickets` int(11) NOT NULL,
 `course_required` tinyint(1) NOT NULL,
 `sys_insert_user_id` int(11) NOT NULL,
 `sys_insert_datetime` datetime NOT NULL,
 `sys_lastedit_user_id` int(11) DEFAULT NULL,
 `sys_lastedit_datetime` datetime DEFAULT NULL,
 PRIMARY KEY (`id`),
 KEY `IDX_8325E540166D1F9C` (`project_id`)
) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci
```
Saludos.

**Comment by jmontoyaa** [comment]
Es verdad esas tablas debería de ser innodb, acabo de enviar otro cambio.

**Comment by nosolored** [comment]
Hemos convertido la totalidad de la base de datos de Chamilo de MyISAM a InnoDB
también se ha cambiado el collate a utf8_unicode_ci

Con el último código de github, con el composer actualizado muestra el mensaje siguiente:

Entorno PHP 5.6.30 y MySQL 5.6.34

```
ERROR: An exception occurred while executing 'ALTER TABLE ticket_message_attachments RENAME INDEX ticket_message_id_fk TO IDX_70BF9E26537A1329;':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INDEX ticket_message_id_fk TO IDX_70BF9E26537A1329' at line 1
```
Revisando lo que indican en https://www.techonthenet.com/mysql/indexes.php quizás podría ser debido a la versión de MySQL 5.6 o 5.7.

```
Syntax

The syntax to rename an index using the ALTER TABLE statement in MySQL 5.6 and later is:

ALTER TABLE table_name
  DROP INDEX index_name,
  ADD INDEX new_index_name [ USING BTREE | HASH ]
    (index_col1 [(length)] [ASC | DESC], 
     index_col2 [(length)] [ASC | DESC],
     ...
     index_col_n [(length)] [ASC | DESC]);
OR

The syntax to rename an index in MySQL 5.7 or newer is:

ALTER TABLE table_name
  RENAME INDEX index_name TO new_index_name;
```

**Comment by jmontoyaa** [comment]
Acabo de agregar un correctivo para ese "rename index"

**Comment by nosolored** [comment]
Git actualizado con parche, composer update.

[ERROR: There is no table with name 'nombrebasededatos.ticket_message_attachments' in the schema.](url)

No existe esa tabla en la base de datos.

En la tabla version el último registro muestra 20160707131900

**Comment by jmontoyaa** [comment]
Qué muestra el error en apache?

**Comment by jmontoyaa** [comment]
Acabo de agregar otra correción

**Comment by nosolored** [comment]
En el error log de Apache no muestra ninguna información adicional que ayude.
Vamos a revisar de nuevo con los últimos parches.

**Comment by nosolored** [comment]
Con los últimos muestra: 

`ERROR: There is no table with name 'basededatos.ticket_ticket' in the schema.`

Saludos.

**Comment by jmontoyaa** [comment]
Acabo de agregar una otra correción

**Comment by nosolored** [comment]
Reiniciando el proceso con la aplicación de la corrección muestra:

```
ERROR: An exception occurred while executing 'ALTER TABLE ticket_message_attachments ADD CONSTRAINT FK_70BF9E26700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket_ticket (id)':

SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```

**Comment by jmontoyaa** [comment]
Acabo de agregar otra corrección.

**Comment by nosolored** [comment]
Reiniciado el proceso con los últimos cambios muestra el mensaje siguiente:

```
Notice:  Undefined variable: fixTableMessage in ../app/Migrations/Schema/V111/Version111.php on line 329

ERROR: An exception occurred while executing 'UPDATE ticket_ticket t SET priority_id = (SELECT id FROM ticket_priority t2 WHERE t2.code = t.priority_id)':

SQLSTATE[21000]: Cardinality violation: 1242 Subquery returns more than 1 row
```

Parece que hay un error en la consulta. Por lo que hemos podido revisar el campo code en la tabla ticket_priority no puede ser igual al campo priority_id en la tabla ticket_ticket, ya que este último es numérico y el campo code contiene texto.

Por otro lado no parece existir en la tabla ticket_ticket ningun campo que guarde relación con el campo code de la tabla ticket_priority.

**Comment by jmontoyaa** [comment]
Es posible tener el backup de la 1.10 para probarlo localmente?

**Comment by nosolored** [comment]
Envíanos un correo a nosolored y remitimos un enlace para descargar la base de datos.

**Comment by ywarnier** [comment]
La 1.11.4 alpha 2 está disponible, pero no creo que ayude para este último problema preciso (pero ya corrige varios otros de migración)

**Comment by nosolored** [comment]
Usamos el código git de la rama 1.11.x https://github.com/chamilo/chamilo-lms/tree/1.11.x que se genera y actualiza con git pull origin 1.11.x y se aplica después composer update.

**Comment by ywarnier** [comment]
@nosolored, si pones un "LIMIT 1" al fin del subquery (entre las parenthesis en el query de la línea 329 de app/Migrations/Schema/V111/Version111.php), esto soluciona todo?
@AngelFQC lo está probando aquí, pero por si lo tienes a la mano...

**Comment by AngelFQC** [comment]
@nosolored intenta con estos commits
https://github.com/AngelFQC/chamilo-lms/commit/86111673557c7e2cbc92015adc2e52a834047de5
https://github.com/AngelFQC/chamilo-lms/commit/56f360835827d7a19e6c8dfb1b847fb232915fd6
https://github.com/AngelFQC/chamilo-lms/commit/58dc1367841910885341b8e9de247f00ffb736f0

**Comment by jmontoyaa** [comment]
Acabo de agregar unas correciones. Lo he probado con la DB mandada y la migración terminó sin errores.

**Comment by jmontoyaa** [comment]
Probar con  https://github.com/chamilo/chamilo-lms/tree/1.11.x

**Comment by nosolored** [comment]
Confirmamos que se realiza correctamente ahora la migración 1.10.x a 1.11 indicada con el último código de https://github.com/chamilo/chamilo-lms/tree/1.11.x
tanto con la versión con tablas latin1_spanish_ci, MyISAM e InnoDB como con la misma base de datos convertida totalmente a utf8_unicode_ci e InnoDB.

Vamos a realizar migraciones más complejas y os reportamos (de 1.9 a 1.11 y de 1.10 a 1.11).

Muchas gracias por todo.

**Comment by LJSancibrian** [comment]
Hola. He realizado una migración (sin errores en la migración) de la versión 1.9.10 a la versión 1.11.4. Todo parecía estar correcto hasta que intentamos acceder a unos resultados de unos ejercicios. 
El sistema arrija el siguiente error:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND ref_id_second_level=0 LIMIT 1' at line 6' in /home/saveccal/public_html/plataforma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104 Stack trace: #0 /home/saveccal/public_html/plataforma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT *\n ...') #1 /home/saveccal/public_html/plataforma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(852): Doctrine\DBAL\Driver\PDOConnection->query('SELECT *\n ...') #2 /home/saveccal/public_html/plataforma/main/inc/lib/database.lib.php(369): Doctrine\DBAL\Connection->executeQuery('SELECT *\n ...') #3 /home/saveccal/public_html/plataforma/main/lp/learnpathItem.class.php(194): Database::query('SELECT *\n ...') #4 /home/saveccal/public_html/pla in /home/saveccal/public_html/plataforma/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 90

¿Alguna idea de como solucionarlo?

**Comment by LJSancibrian** [comment]
Hola... la solución esta en añadir unas comillas simples en las lineas 178 y 179 del archivo lp/learnpathItem.class.php. 
Donde pone:
 `SELECT *
                FROM %s
                WHERE course_code=\'%s\'
                    AND tool_id=\'%s\'
                    AND ref_id_high_level=%s
                    AND ref_id_second_level=%d
                LIMIT 1`
 poner:
`SELECT *
                FROM %s
                WHERE course_code=\'%s\'
                    AND tool_id=\'%s\'
                    AND ref_id_high_level=\'%s\'
                    AND ref_id_second_level=\'%d\'
                LIMIT 1`

**Comment by huba80** [comment]
After updating from Chamilo 1.9.10.2 to 1.11.14 when I click on a course I get the following error:
`Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'e1_.visible_to_self' in 'where clause' in /home/tolokapu/public_html/vizsga/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117 Stack trace: #0 /home/tolokapu/public_html/vizsga/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL) #1 /home/tolokapu/public_html/vizsga/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(905): Doctrine\DBAL\Driver\PDOStatement->execute() #2 /home/tolokapu/public_html/vizsga/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(50): Doctrine\DBAL\Connection->executeQuery('SELECT e0_.id A...', Array, Array, NULL) #3 /home/tolokapu/public_html/vizsga/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(338): Doctrine\ORM\Query\Exec\SingleSelectExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array) #4 /home/tolokapu/public_html/vizsga/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1000): Doctrine\ORM\Query->_doExe in /home/tolokapu/public_html/vizsga/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 60`
