### ISSUE TITLE
Text to speech not working

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1956]
### Current behavior
Text to speech doesn't seem to work (it returns an empty file) with Pediaphon nor Google. A file_get_contents() warning appears briefly and then the audio files are generated but with a 0 bytes size. This might be related to the remote services we are using.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* enable text to speech feature in admin settings (search for "speech")
* in documents, click the loudspeaker icon
* select any method and generate the audio file
* go back to the documents list

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by AngelFQC** [comment]
* The https://www.pediaphon.org/ server is down
* The Google API for translate returns a JSON file, then Chamilo try save it as mp3.
```json
{
  "data": {
    "translations": [
      {
        "translatedText": "hello-how-are-you",
        "detectedSourceLanguage": "en"
      }
    ]
  }
}
```
But there is no way to get a mp3 with the text audio

**Comment by jmontoyaa** [comment]
Pediaphon is down, it doesn't convert text to audio in French.

**Comment by jmontoyaa** [comment]
I suggest we deprecated this pediaphone option and only use google (I tried it and it works).

**Comment by ywarnier** [comment]
When I try Google audio, I get this:
Warning: file_get_contents(https://www.googleapis.com/language/translate/v2?key=&amp;en&amp;target=en&amp;q=Hello-guys): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden in /var/www/chamilo111x/main/document/create_audio.php on line 367

You don't?

**Comment by jmontoyaa** [comment]
It works for me locally ... I will check it in 11.chamilo.org

**Comment by ywarnier** [comment]
This might be a territorial limit... (not allowing Latin America, this wouldn't be the first of such type of limitation). 11.chamilo.org is physically located in Belgium, but I'm not sure what other context I have available to test from other latinamerican locations...

**Comment by ywarnier** [comment]
On https://11.chamilo.org, I get the same issue:
Warning: file_get_contents(https://www.googleapis.com/language/translate/v2?key=&en&target=en&q=Hello): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden in /var/www/11.chamilo.org/www/main/document/create_audio.php on line 367

**Comment by ywarnier** [comment]
Here (just in case): https://11.chamilo.org/main/document/create_audio.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by jmontoyaa** [comment]
You are right, there's a PHP warning. I found that there was a setting not included in  configuration.dist.php.

But now I reached my limit of "tech to speech limit": 
I will try tomorrow

```
{
  "error": {
    "code": 403,
    "message": "Daily Limit Exceeded",
    "errors": [
      {
        "message": "Daily Limit Exceeded",
        "domain": "usageLimits",
        "reason": "dailyLimitExceeded"
      }
    ]
  }
}
```

**Comment by ywarnier** [comment]
OK, let's remove Pediaphon in any case... (delete corresponding files completely)
