### ISSUE TITLE
apc cache too agressive when updating profile

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1959]
When apc is enabled student's can't update their profile.
Actually the changes are saved in the database but the contents are not refreshed because apc still cache the old user data. More info here:

https://task.beeznest.com/issues/12768

**Comment by ywarnier** [comment]
The fix looks a bit weird: I would rather update the session *and* the cache every time something updates a user, but maybe it's a bit more complicated for now (that not everything is in an entity).
