### ISSUE TITLE
Wrong LDAP Information

### ISSUE THREAD

**Issue by sercon** [chamilo/chamilo-lms#1961]
In portal settings https://mychamilo/main/admin/settings.php?category=LDAP 
it says:
![image](https://cloud.githubusercontent.com/assets/12449415/26241993/18896376-3c87-11e7-993c-5eb476b2ee6a.png)

especially the line Edit file "main/inc/conf/configuration.php"
In a clean setup of the 1.11.2 version (latest stable) this file - or even that directory - does not exist ?

It seems LDAP / Active directory integration changed somewhat in different version ?

What is the correct procedure to enable user authentication against an active directory domain ?

**Comment by ywarnier** [comment]
Right... The file is now at app/config/configuration.php. I'll edit that language variable before 1.11.4 is released. Thanks for reporting!
Note that you should also (probably) modify app/config/auth.conf.php to finetune your LDAP settings.

**Comment by ywarnier** [comment]
Updated in 1.11.4. Thanks for reporting!
