### ISSUE TITLE
Wrong display on IE

### ISSUE THREAD

**Issue by AurelieGuy** [chamilo/chamilo-lms#1962]
Hi everyone!

### Current behavior / Resultado actual / Résultat actuel

I have the mobile version display when I use my chamilo platform on IE 11. 

![image](https://cloud.githubusercontent.com/assets/28803818/26242695/99572d6a-3c89-11e7-8740-048709911342.png)

### Expected behavior / Resultado esperado / Résultat attendu

The computer version display on IE 11.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.2

Thanks for helping me!

**Comment by ywarnier** [comment]
Hi, could you check on https://1.11.chamilo.org/ (don't mind the page load error if they appear)

**Comment by AurelieGuy** [comment]
Hi Yannick, it appears well :
![image](https://cloud.githubusercontent.com/assets/28803818/26250397/27547bd4-3caa-11e7-80d9-7a0b7220a5d3.png)


I guess that means the problem is with my plateform? 
Do you know how to fix it?

**Comment by ywarnier** [comment]
Upgrading to 1.11.4 or changing the CSS stylesheet used is likely to solve the issue. If that works with another stylesheet (for example the default "chamilo" stylesheet) on your current, 1.11.2 portal, then you can ask a web designer to have a look at it for you and he should be able to find a solution.
If the issue remains, then it is likely to be a Chamilo 1.11.2, and upgrading to 1.11.4 should be a solution (it's currently in alpha version and should be stable by the 31st of May).
