### ISSUE TITLE
Cannot remove an empty class from a course

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1964]
### Current behavior
When trying to remove an empty class from a course, a message says "Deleted" but the class is not removed. When there is at least one student in the class, it can be removed easily.

### Expected behavior
The class should disappear from the list of classes in the course.

### Steps to reproduce
* Enter a course
* go to Users
* click the "Classes" tab. Click on "Add class". No class is present.
* click on "Create class". Confirm.
* in the list of classes (to be subscribed to the course), the new class appears (with 0 student)
* click the green icon to add the class to the course. It is added.
* now click the red cross to deleted. It says "deleted" but the class is not removed from the course.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x 2017/05/21

**Comment by erdvillegas** [comment]
Hi, I would like to review this, I'm new on the community, I try to check for a solution @ywarnier how can I contribute with ?

**Comment by jloguercio** [comment]
Fixed here https://github.com/chamilo/chamilo-lms/pull/2174

**Comment by NicoDucou** [comment]
Just check here https://11.chamilo.org/main/user/class.php?cidReq=200STUDENTS&id_session=0&gidReq=0&gradebook=0&origin= and I could add a class and then remove it with no problem, so I close this issue
