### ISSUE TITLE
Bug Vr 1.10.8 al exportar reporte de estudiante  

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#1969]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes  estoy manejando chamilo 1.10.8   deseo sacar un reporte de ultimo acceso al curso del mis estudiante y  al exportar  el archivo veo que la columna  ultimo acceso al curso se encuentra vacía. se anexa la ruta del informe http://virtual3.usc.edu.co/main/tracking/courseLog.php?id_session=120&cidReq=P217TI11ATI10317A&origin=resume_session&hide_course_breadcrumb=1  
![falta columna en informe](https://cloud.githubusercontent.com/assets/20644209/26373032/ac9b860c-3fc5-11e7-9253-505feb10a831.JPG)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* se tiene un curso con estudiante 
*se entra a informes 
* en el informe encontramos  una serie de campos como datos del estudiante, el progresos en el curso, el primer acceso  y el ultimo acceso a la plataforma
* se exporta el archivo en excel 
 ### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.10x  se descarga la ultima version del archivo  courselog.php

**Comment by jmontoyaa** [comment]
Al parecer este error ya fue resuelto en chamilo 1.11.x

**Comment by ywarnier** [comment]
Por favor @fergimon revisar en https://11.chamilo.org/ para confirmar la existencia (o no) del bug en esta versión.

**Comment by ywarnier** [comment]
Sin feedback por meses. Cerrando.
