### ISSUE TITLE
Wrong path used in pictures on exercises

### ISSUE THREAD

**Issue by sercon** [chamilo/chamilo-lms#1971]
When adding a picture in an exercise (eg Unique answer image) with the 
![image](https://cloud.githubusercontent.com/assets/12449415/26394850/91511a48-406e-11e7-9d60-3be034ae4fcd.png) button, it uses the wrong src
<img style="width: 234px; height: 215px;" alt="" src="/courses/TEST/document/images/AngryBirdy.jpg">
in stead of 
<img style="width: 234px; height: 215px;" alt="" src="/app/courses/TEST/document/images/AngryBirdy.jpg">

**Comment by sercon** [comment]
not displaying right. Missing the leading '/app'

src="/courses/TEST/document/images/AngryBirdy.jpg"
in stead of
src="/app/courses/TEST/document/images/AngryBirdy.jpg"

**Comment by jmontoyaa** [comment]
"app" is not needed.

`src="/courses/TEST/document/images/AngryBirdy.jpg"`

Should work because there's a .htaccess rule. Check if your server has mod_rewrite module on.

**Comment by ywarnier** [comment]
Please check https://1.11.chamilo.org/documentation/installation_guide.html#1._Pre-requisites, "Apache's redirect".
