### ISSUE TITLE
Not open course page

### ISSUE THREAD

**Issue by rogeriomq** [chamilo/chamilo-lms#1974]
I installed version 1.11.12 in localhost, installation 100% ok! I created a course normally, but when I click on the course it does not find the course page:

> http://localhost/ensino/courses/CURSO001/index.php?id_session=0

`Object not found!

The requested URL was not found on this server. The link on the referenced page appears to be out of error or outdated. Please inform the author of this page about the error.

If you believe you have encountered a problem with the server, please contact the webmaster.

Error 404

localhost
Apache/2.4.25 (Unix) OpenSSL/1.0.2j PHP/7.1.1 mod_perl/2.0.8-dev Perl/v5.16.3`

**Comment by ywarnier** [comment]
This is probably because you have not read the installation guide. In particular the part related to .htaccess. In 1.11.4, there is an additional warning in the installation process about that.

**Comment by ywarnier** [comment]
See "Apache's redirects" here https://1.11.chamilo.org/documentation/installation_guide.html#1._Pre-requisites (or in the documentation/ subfolder of your Chamilo portal). You don't need to reinstall your portal for that, just update your Apache's config
