### ISSUE TITLE
Migración 1.9.x a 1.10.x y 1.11.x - Tipos enum

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#1980]
### Current behavior / Resultado actual / Résultat actuel
Migración de 1.9.x a 1.11.x con el código de 
https://github.com/chamilo/chamilo-lms/tree/1.11.x 

Muestra error Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

Migración de 1.9.x inicial a 1.10.x - No muestra error
Código utilizado https://github.com/chamilo/chamilo-lms/tree/1.10.x

Migración posterior del sitio actualizado a 1.10.x a la versión 1.11.x - No muestra errores.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Instalación inicial Chamilo 1.9
Actualizar a 1.11 - Migración con errores.

- Instalación Chamilo 1.9 - Migrar a 1.10.x - Migración sin errores.
Posteriormente la instalación resultante de 1.10.x se actualiza a 1.11.x - Migración sin errores.

¿Es recomendable realizar el proceso de 1.9 a 1.10 y posteriormente a 1.11, en lugar de realizar el salto directo de 1.9 a 1.11 o no deberían producirse esos errores?

**Comment by ywarnier** [comment]
No, deberías poder hacer el salto directo. En 1.11 usamos Doctrine más a fondo, y no le gusta los tipos ENUM porque no son muy portables entre todos los sistemas de gestión de bases de datos que soporta. Por eso no creo que usemos más tipos ENUM en 1.11, pero quizás haya algo en 1.10 que todavía los acepta. @jmontoyaa le puedes echar un vistaso?

**Comment by jmontoyaa** [comment]
Para ahorrarnos tiempo ... dump de la BD?

**Comment by nosolored** [comment]
No es posible enviar el dump de la base de datos por temas de privacidad.

Los campos con tipo enum en la BD 1.9 son los siguientes:

Tabla c_blog_rating: rating_type - enum('post','comment')
Tabla c_link: on_homepage - enum('0','1')
Tabla c_quiz_answer: hotspot_type - enum('square','circle','poly','delineation','oar')
Tabla c_survey: anonymous - enum('0','1')
Tabla c_tool: target - enum('_self','_blank')
Tabla course_category: auth_course_child - enum('TRUE','FALSE')
Tabla course_category: auth_cat_child - enum('TRUE','FALSE')

**Comment by jmontoyaa** [comment]
En qué momento de la migración aparece este mensaje?

`Muestra error Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.`

**Comment by jmontoyaa** [comment]
Los enum normalmente son eliminados cuando se migra de 1.9.x a 1.10.x

**Comment by jmontoyaa** [comment]
Acabo de agregar una correción si la version 1.9.x era una 1.9.10.6

**Comment by nosolored** [comment]
Con el último código agregado a 1.11.x si realiza la migración de 1.9.10.2 a 1.11.4 sin mostrar errores.

En la tabla version muestra los valores
111
20170522120000
Muchas gracias.
Saludos.

**Comment by LJSancibrian** [comment]
Hola. Estoy intentando actualizar de la versión 1.9.10.2 a la 1.11.4, pero me marca el mismo error de este tema. ¿como puedo solucionarlo? ¿realizo el paso previo por la v1.10?

**Comment by ywarnier** [comment]
Este problema fue corregido como parte de la versión 1.11.4. No debería aparecerte el mismo error...
Técnicamente usar la versión 1.10 en el medio es peor porque incluso en la 1.11.4 todavía teníamos unas correcciones para la migración de 1.9 a 1.10 que no están en la última versión estable de 1.10 (porque sucedieron después).
Cuales son tus versiones de MySQL y de PHP?

**Comment by LJSancibrian** [comment]
Solucionado. Añadí dos sentencias más, similares a las que modifican los campos con tipo enum para las tablas 'cs_options_history' y 'cs_payment_option' que existian en la base de datos.
Gracias por la celeridad en la respuesta.

**Comment by ywarnier** [comment]
cs_ ... creo que estas son tablas adicionales, no me suenan a nada en Chamilo...

**Comment by LJSancibrian** [comment]
Es una instalación que ha pasado por cuatro programadores... es fácil que estén añadidas por ellos.

**Comment by ywarnier** [comment]
Sí, eso lo explicaría.
