### ISSUE TITLE
Error trying to edit certificate.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#1981]
Testing in:
Https://1.11.chamilo.org/
![01](https://cloud.githubusercontent.com/assets/25286516/26468428/c60b40fc-416c-11e7-96c1-951595b7a557.jpg)
![02](https://cloud.githubusercontent.com/assets/25286516/26468432/cb0c26c0-416c-11e7-9746-e02318cd8cf0.jpg)
![03](https://cloud.githubusercontent.com/assets/25286516/26468438/d08fc9d0-416c-11e7-8516-436aa69a9cc6.jpg)

In my installation only a line of error appears:
Fatal error: [] operator not supported for strings in /home/public_html/chamilo/main/inc/lib/document.lib.php on line 6022

**Comment by AngelFQC** [comment]
Fixed
