### ISSUE TITLE
Migration issues from 1.9, 1.10 and 1.11

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#1983]
The people at Softaculous report the following about 1.11.4 alpha 2:

1. WHILE UPGRADING FROM 1.11.2
     i. Constraints for table `promotion` is not getting generated
    ii. Version number in configuration.php is still not updating.

2. WHILE UPGRADING FROM 1.10.x
     i. Constraints for following tables are not getting generated.
      `promotion`
      `skill`
      `skill_level`
      `skill_rel_user`
      `skill_rel_user_comment`

3. WHILE UPGRADING FROM 1.9.10.2
      i. Column `category` from `session_rel_course` table is not being deleted.
     ii. Constraints for following tables are not getting generated.
       `access_url_rel_user`
       `c_student_publication`
       `language
       `promotion`
       `skill`
       `skill_level`
       `skill_rel_user`
       `skill_rel_user_comment`

Please review and see if we can improve this.

**Comment by jmontoyaa** [comment]
I added some fixes for those issues.

**Comment by ywarnier** [comment]
No feedback provided from Softaculous so far. Considered fixed.
