### ISSUE TITLE
Can't attach a certificate 

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#1985]
### Current behavior / Resultado actual / Résultat actuel
Created a course
Inserted 2 manual evaluation. (weight of 50% each)
Click on Attach Certificate button.
Got error 500.

Apache log:
`[Fri May 26 15:41:41.026311 2017] [:error] [pid 2008] [client 179.176.63.198:52362] PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /var/www/santanapb/main/inc/lib/document.lib.php:6022\nStack trace:\n#0 /var/www/santanapb/main/document/document.php(1887): DocumentManager::build_edit_icons(Array, 3, 0, '0', true)\n#1 {main}\n  thrown in /var/www/santanapb/main/inc/lib/document.lib.php on line 6022, referer: https://santanapb.asdnet.com.br/main/gradebook/index.php?visibleeval=2&set_visible=&selectcat=1&cidReq=AV001&id_session=0&gidReq=0`

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 beta 20170525
PHP 7

**Comment by AngelFQC** [comment]
Duplicated, this was fixed in #1981
