### ISSUE TITLE
Display issue with confirmation message after remove the introduction text content.

### ISSUE THREAD

**Issue by iflorespaz** [chamilo/chamilo-lms#1987]
### Current behavior / Resultado actual / Résultat actuel
After remove course introduction text, the message is displayed on the top page
### Expected behavior / Resultado esperado / Résultat attendu
Normally the text message should be displayed inside the content template
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a course, go inside course and add intro text, then delete the intro text and you will see the message in the top page.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo 1.11.4 beta 1
![my organisation my campus innovation management](https://cloud.githubusercontent.com/assets/26859617/26517473/fb7d54f8-425e-11e7-9d64-6bc52f690c6e.png)

**Comment by AngelFQC** [comment]
This was already fixed here 31fd2c945baf8a4d6c54fc70d1db70e79915acad
Please try with the latest code from 1.11.x
