### ISSUE TITLE
Plugins: RSS feed uses google deprecated api

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#1988]
### Current behavior / Resultado actual / Résultat actuel
RSS feed plugin doesn't work
### Expected behavior / Resultado esperado / Résultat attendu
RSS feed to show on hoepage if configured as such through admin->plugins->rss feed
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Config->admin->plugins->rss feed enable it and choose main screen as content area
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 but probably all because the google feed api is deprecated:
<img width="1107" alt="afbeelding" src="https://cloud.githubusercontent.com/assets/1659604/26527599/7331128a-4397-11e7-8696-38f2eb915d33.png">

**Comment by jmontoyaa** [comment]
Should be fixed now .

**Comment by ywarnier** [comment]
@jderriks any chance you could review this and tell us if that's OK now before next Monday?
