### ISSUE TITLE
Replace bower with yarn

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#1990]
bower will be deprecated

See:
https://github.com/bower/bower/issues/2298

better to use 

https://yarnpkg.com/en/

Change could be done for 2.0

**Comment by AngelFQC** [comment]
👍

**Comment by jmontoyaa** [comment]
I added a readme file here:

https://github.com/chamilo/chamilo-lms/blob/master/assets/README.md

**Comment by jmontoyaa** [comment]
Related to  #2324

**Comment by ywarnier** [comment]
I think we could close this task now, no?

**Comment by jmontoyaa** [comment]
yes!
