### ISSUE TITLE
Moving folders in Documents makes content inoperative  

### ISSUE THREAD

**Issue by p4pr8n** [chamilo/chamilo-lms#1991]
### Current behavior / Resultado actual / Résultat actuel
Moving a folder and its contents moves only the contents and  doesn't (re)create the tree.
In Chamilo it seems ok but all the content is unreachable.
On the server you can clearly see that only the documents (files) have been moved.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
create folder1 and folder2
In folder1 create subfolder1
In subfolder1 upload some files
Move subfolder1 in folder2 and try to preview or dowload files from subfolder1

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by AngelFQC** [comment]
Please try with the latest code form 1.11.x branch or 1.11.4 RC1 https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.4-rc.1

**Comment by p4pr8n** [comment]
Sorry to be late but we are using de latest 1.11.4 with te same issue.
Only the files are physically moved when moving folder and its content.

**Comment by p4pr8n** [comment]
Works perfect on 1.11.8
