### ISSUE TITLE
Multiple E_NOTICES appear when course homepage design is Three columns view

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#1996]
### Current behavior / Resultado actual / Résultat actuel
With the `homepage_view` set to `3column` appear multiple E_NOTICES

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Set the *Course homepage design* (`homepage_view`) setting to *Three columns view* (`3column`)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by nosolored** [comment]
@ywarnier you can close this issue
