### ISSUE TITLE
Preview of Stylesheets

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#1998]
### Current behavior / Resultado actual / Résultat actuel
When changing styles, the Preview button does not work.  The logo changes but not the colour scheme.
Clicking on SAVE SETTINGS does change the stylesheet.

### Expected behavior / Resultado esperado / Résultat attendu
Preview should show what the selected style will look like.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
In admin/stylesheet, select a new style from the drop down list and click on PREVIEW.  Only logo changes.
Click on SAVE SETTINGS and all changes are then shown

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4
(Ubuntu 14.04 - PHP 5.5.9)

**Comment by ConsultPW** [comment]
Tested this fix on 2 platforms (Ubuntu and Centos) and it works fine.

**Comment by nosolored** [comment]
@ywarnier you can close this issue, it works fine

**Comment by nmeigs** [comment]
I have version 1.11.4 and I have the same issue.

How do we find what is the latest version of Chamilo available?

Is this sissue fixed in a later version?

**Comment by jmontoyaa** [comment]
You can get it here https://github.com/chamilo/chamilo-lms/releases

Version 1.11.6

**Comment by ywarnier** [comment]
(not official yet, though)

**Comment by nmeigs** [comment]
Can we use it, install it right away?
