### ISSUE TITLE
Tool Introductions

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#1999]
### Current behavior / Resultado actual / Résultat actuel
Whatever is entered into the editor for ANY tool in a course is repeated on ALL tool headers.
If different text/pics are used on another tool, this copy overwrites all others.

### Expected behavior / Resultado esperado / Résultat attendu
Different text/pics should be avle to be inserted for each tool.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Ensure that 'Enable Tool Introduction' is set to YES in Admin
Create a new course.
Go to any tool and add some text/pics to tool introduction.
Go to any other tool and the same introduction appears.
Change any other tool introduction and it will appear on all tools, overwriting anything there.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4
(Ubuntu 14.10 PHP 5.5.9)

**Comment by AngelFQC** [comment]
@ConsultPW try with this commit  0c33cb1

**Comment by ConsultPW** [comment]
Fast work Angel - Checked on two different installs and now working fine.

**Comment by AngelFQC** [comment]
Great!
