### ISSUE TITLE
YouTube video added in course description appears in course catalogue but not c. desc.

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2000]
### Current behavior
A video set in course description appear in the course catalogue (info icon) but not in the course description tool.

### Expected behavior
The video should appear in both places.

### Steps to reproduce
- create a course
- create a first item of course description with a YouTube video (mark it as "Responsive", although we are not sure this serves for anything)
- save
- when viewing the result from inside the course description, the video does not appear
- go to course catalogue
- click the "info" (i) icon on the course card
- the video appears...

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
I just fixed this issue. Now the youtube video doesn't appear when clicking the "info" button.
If you want to see the video you have to enabled "iframes" in the portal:

https://11.chamilo.org/main/admin/settings.php?search_field=iframe&category=search_setting
