### ISSUE TITLE
Switching to trainer in preview mode

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#2004]
### Current behavior / Resultado actual / Résultat actuel
When viewing a page in prview mode the 'switch to trainer' button and breadcrumb bar are not visible.  Navigation is in top left with no margins.
### Expected behavior / Resultado esperado / Résultat attendu
Switch button should be visible and navigation in a better position

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
In any course select preview mode for a sinle page

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Could you send us a screenshot?

**Comment by ConsultPW** [comment]
![preview](https://cloud.githubusercontent.com/assets/21216499/26778021/61ff6f7a-49d7-11e7-8f86-b86188cdbd76.jpg)

**Comment by ConsultPW** [comment]
Update from further testing;

- Buttons appearing top left is in Firefox only and appears to be caused by a recent Firefox update.  They appear on the right (with space around them in Safari on iPad, Chrome and Opera.
- Checked all settings and install and cannot get the breadcrumb bar to appear ib preview mode in any browser.

Regards,
Charlotte Cook - Consult.PW

**Comment by jmontoyaa** [comment]
This was a voluntary UI change, not sure when it happened. @ywarnier ?

**Comment by ywarnier** [comment]
This was done to reduce complex inconsistencies generated in the view mode when teachers would access the course and switch to student view, then try to come back to edit mode. Nightmare UI workflow had to be avoided. This will not be re-enabled. It stays as is unless proper financing is provided to cover and test all the possible behaviors mixed with all possible user roles.
