### ISSUE TITLE
Migración de 1.10.x a 1.11 - Plugin Skype

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2005]
### Current behavior / Resultado actual / Résultat actuel
Al finalizar la migración de 1.10 a 1.11.4 al entrar en la Administración de plugins muestra un error.
PHP Fatal error:  Class 'Skype' not found in .../plugin/skype/plugin.php on line 9, referer: .../main/admin/index.php
[Mon Jun 05 17:05:17.185258 2017] [:error] [pid 13444] [client xxx] PHP Fatal error:  Class 'Skype' not found in .../plugin/skype/plugin.php on line 9

### Expected behavior / Resultado esperado / Résultat attendu

En cuánto se elimina el directorio /plugin/skype permite entrar en la Administración de 1.11.4.
Quizás sería aconsejable insertar un aviso en el proceso de instalación cuando se elimina

/plugin/ticket
/main/exercice
/main/newscorm
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Realizar una migración de 1.10.4 a 1.11.4 estable

**Comment by ywarnier** [comment]
He añadido un intento de borrado + una advertencia junto con la de tickets. Creo que con esto podemos cerrar la tarea?

**Comment by nosolored** [comment]
Gracias @ywarnier 
Podéis cerrar la tarea.
Haremos pruebas.

**Comment by nosolored** [comment]
Tests realizados y pasados.
Gracias.
