### ISSUE TITLE
Upgrading to 1.11.4 from 1.10.x

### ISSUE THREAD

**Issue by softaculous** [chamilo/chamilo-lms#2009]
### Current behavior / Resultado actual / Résultat actuel
While upgrading from 1.10.8 version, I am getting following syntax error.

ERROR: An exception occurred while executing 'ALTER TABLE sequence_rule ADD description LONGTEXT NOT NULL, DROP text;':

SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'text'; check that column/key exists

and also version number in configuration.php doesn't change to latest value.

### Expected behavior / Resultado esperado / Résultat attendu
Upgrade should complete without giving any error.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Extracting new zip to existing installation and visiting main/install, confirming installation details and upgrading gives error.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
Fixed.
