### ISSUE TITLE
Chamilo 1.11.4 - profiling pagination error

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2011]
### Current behavior / Resultado actual / Résultat actuel

En el apartado de Gestionar los campos de usuario (Profiling) de la Administración, aparece siempre página 1 de 1 aunque haya más de 20 registros que son los que se muestran por defecto, y no permite avanzar de página. También abajo a la derecha indica que solo hay 20 registros en total aunque no sea asi.
Para ver todos los registros solo se puede elegir en el desplegable la opción de mostrar todos.

### Expected behavior / Resultado esperado / Résultat attendu

Al final de la relación de campos debería aparecer el número de páginas correcto y estar activas las flechas para avanzar de página si el número de registros supera a los mostrados.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Entrar en https://1.11.chamilo.org/main/admin/extra_fields.php?type=user
Comprobar que solo se muestran 20 registros y abajo indica página 1 de 1 con el avance inactivo.
Elegir en el desplegable "Mostrar todos", comprobaremos que hay 24 en total.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4

**Comment by jmontoyaa** [comment]
Acabo de corregirlo

**Comment by nosolored** [comment]
Perfecto gracias
