### ISSUE TITLE
Pics for Courses Catalogue

### ISSUE THREAD

**Issue by ConsultPW** [chamilo/chamilo-lms#2014]
### Current behavior / Resultado actual / Résultat actuel
Inserting a picture to appear in the catalogue results in white space to right.

### Expected behavior / Resultado esperado / Résultat attendu
If cropped and sized correctly, the picture shouls fill the area.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
In course settings, add a picture and crop to size.
View the courses catalogue and the pic appears with white space to the right.  Changing the proportions of the pic or cropping has no effect.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
I think this was already fixed. Can you tried here:

https://11.chamilo.org/ (admin/admin)

**Comment by ywarnier** [comment]
No user feedback since October. Closing.
