### ISSUE TITLE
Problème déplacer un fichier dans l'outil Document des Groupes

### ISSUE THREAD

**Issue by dguenard** [chamilo/chamilo-lms#2015]
### Current behavior / Resultado actual / Résultat actuel
La liste des répertoires sont Document pour l'ensemble des select
![outildocgroupe](https://user-images.githubusercontent.com/8669687/26980059-3f44899a-4d31-11e7-85d6-8acd70fd803b.JPG)
### Expected behavior / Resultado esperado / Résultat attendu
Avoir la liste des repertoire rep1 et rep2
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Déplacer un document dans l'outil document des groupes
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2 et 1.11.4

### Correctif
fichier document.lib.php ligne 6157 ->
ajout de $group_dir2= self::get_titles_of_path($group_dir);
$display_folder = substr($path_displayed, strlen($group_dir2));

**Comment by ywarnier** [comment]
Je n'ai pas le problème dans 1.11.x et, manque de plus d'info, je dois supposer que ça a été réglé depuis.

![docs-list](https://user-images.githubusercontent.com/609839/33556938-ab25c416-d8d3-11e7-8174-54bfdc45d9f1.png)
