### ISSUE TITLE
Navegación lenta dentro de las lecciones

### ISSUE THREAD

**Issue by MiguelTVG** [chamilo/chamilo-lms#2016]
Buenas,

Recientemente estoy instalando Chamilo 1.11.2, vengo de versiones anteriores, 1.9.x. Y en esta versión más moderna veo que se demora mucho el tiempo dentro de las lecciones cuando se pasa de un artículo a otro. He observado que el articulo se carga rápidamente, pero no aparece, la pantalla está en blanco, sin embargo, es posible hacer click a enlaces que existen en el artículo. Es decir que está ahí pero no se ve.

Se observa como el navegador piensa un rato antes de mostrar el articulo dentro de la lección. Esto sucede cuando se avanza o se retrocede. Cuando se mira el artículo en la vista preliminar dentro del Modo profesor se carga rápidamente.

Hay un bonito efecto de fadein & fadeout, puede que esté allí el problema. Sea como fuere, hay algo que impide una correcta navegación entre los artículos de una lección. En ocasiones la demora ha sido de más de 1 minuto. En versiones anteriores 1.9.x esto funcionaba correcta y rápidamente.

Es algun tipo de bug? Gracias por su respuesta. Aprovecho para felicitarles por su excelente trabajo ya que Chamilo es un proyecto muy importante dentro de la comunidado Open Source. Sigan así!

Saludos,

Miguel

**Comment by rhubenariel** [comment]
Hola,
Tengo el mismo problema con las lecciones demoran hasta 2 minutos y no responde el navegador.
¿Puede que tenga que ver con alguna característica del navegador web?

Saludos
Rubén

**Comment by MiguelTVG** [comment]
Hola Rubén,

Si, yo he tenido que volver a instalar la versión 1.9.x que funciona rapidísimo. Es una lastima porque la nueva versión tiene un aspecto muy lindo y muchas más funcionalidades.

Pero más allá de eso, para mi lo más importante de este software es que la navegación dentro del curso sea rápida. Todo lo demás es secundario. Confío que lo arreglen para futuras versiones. 

Saludos,

Miguel

**Comment by ywarnier** [comment]
Estaremos trabajando en este aspecto de la celeridad dentro de poco (todavía no tengo fecha en concreto). Mucha gente nos ha reportado lo mismo y siempre ha sido una preocupación nuestra que funcione bien en ambientes de pocos recursos, así que no queda otra para nosotros.

**Comment by MiguelTVG** [comment]
Gracias Yannick por tu respuesta. Si, echadle un vistazo, parece como si hubiera algún tipo de bucle o algo así que retrasase la aparición del artículo. Y no estamos hablando de pocos recursos.
Chamilo me parece un software fenomenal, soy un gran entusiasta. Adelante con ello! : ) +1: 

Saludos,

Miguel

**Comment by rhubenariel** [comment]
Hola, paso a contarles mi experiencia con la lecciones, agregue uno pdf con formularios en las lecciones y se queda sin mostrar el pdf interactivo en chrome desde un sistema operativo ubuntu, pero si realizo los siguientes pasos, si muestra en chrome el pdf interactivo. 1) clic sobre la lección y aparece el fondo negro, 2).- F5 e inmediatamente aparece el contenido.
**Conclusión**: solo la primera vez que se llama a mostrar el contenido de una lección lo muestra inmediatamente(con F5 se logra ese efecto). Lo que me lleva a pensar que en las transiciones entre contenidos de una lección hay un error de programación.
Saludos
Ruben

**Comment by ywarnier** [comment]
Uno de los problemas principales es que los queries hacia las tablas c_lp* no han sido actualizados para utilizar los índices que han migrado del campo "id" al campo "iid".
Así se genera una lentitud en la ejecución de queries, que solo se evidencia cuando hay muchos registros (o una base de datos en un servidor muy lento).

La solución rápida es añadir índices temporales:
```
alter table c_lp add index idx_clp_temp_id (id);
alter table c_lp_item add index idx_clpi_temp_id (id);
alter table c_lp_item_view add index idx_lpiv_temp_id(id);
```

La solución *correcta* es modificar todos los queries correspondientes para que se hagan sobre el campo `iid`, ya que el campo `id` será eliminado en la próxima versión mayor de Chamilo.

**Comment by ywarnier** [comment]
@jmontoyaa te dejo esto de tarea. Hay que cambiar todos los `id` (verificar con cuidado que todos han sido traducidos a iid) en `iid` para (todos) los queries de la carpeta main/lp/ que tienen que ver con las tablas `c_lp*`.
Urgente.

**Comment by ywarnier** [comment]
WIP

**Comment by ywarnier** [comment]
To the best of my knowledge and my ability, all references to c_lp.id, c_lp_item.id, c_lp_view.id and c_lp_item_view.id have now been changed to iid. Everything seems to work but this should be kept on watch in case of new issues appearing as a result of these changes.
@jmontoyaa be very aware, in particular with CD's portals over there ;-)
