### ISSUE TITLE
Course settings Picture Size

### ISSUE THREAD

**Issue by sercon** [chamilo/chamilo-lms#2017]
In course settings is says you need a picture of 104pxx96px. This sizes wrong when viewed by student.
![image](https://user-images.githubusercontent.com/12449415/27037460-5a544424-4f88-11e7-917b-9dc27abbf14c.png)

Probably should be 64px by 64px (like the default one). That works ok.

**Comment by ywarnier** [comment]
Thanks for reporting. I've updated the image (and added an additional fix in the documentation regarding a bad Nginx redirect for that image).

**Comment by ywarnier** [comment]
![course_setting_layout](https://user-images.githubusercontent.com/609839/33561591-15bd0e6c-d8e1-11e7-86d1-0a301805721e.png)
