### ISSUE TITLE
Installing a new 1.11.4 from scratch

### ISSUE THREAD

**Issue by vfremaux** [chamilo/chamilo-lms#2018]
### Current behavior / Resultado actual / Résultat actuel

break at stage 7 with : 

Fatal error: Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded.' in C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\do in C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54

### Expected behavior / Resultado esperado / Résultat attendu

Installs completely

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Using the last github 1.11.4-releases through a ZIP download. Install on Windows 8 / Mysql

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4

**Comment by ywarnier** [comment]
Hi, we have published a fix for that (in two different, necessary commits), which only requires the replacement of one file: 9388119a8 and 036d6559a. You can just download and replace main/inc/lib/database.lib.php from here and your issue should be fixed: https://raw.githubusercontent.com/chamilo/chamilo-lms/036d6559ac9c41b3b28a81de898241678a0e749a/main/inc/lib/database.lib.php

The issue only seems to happens on Windows + Xampp or something like that. Please confirm to help us locate the issue more precisely.

**Comment by bsenyuva** [comment]
Hi,
I've experienced same issue on Win 10 x64 + xampp. Fix is worked, thanks.

**Comment by JacquesPOUREAU** [comment]
Hi,
I've experienced same issue on Win 10 x64 + Wamp. Fix is worked, thanks.

**Comment by Bytemx0** [comment]
Thank you :) this work for me, Win 10 x64 + xampp
