### ISSUE TITLE
Le pied de page masque l'outil annonce

### ISSUE THREAD

**Issue by dguenard** [chamilo/chamilo-lms#2020]
![pied de page](https://user-images.githubusercontent.com/8669687/27041524-85ceae08-4f94-11e7-82ef-7a95ed24693d.JPG)
### Current behavior / Resultado actual / Résultat actuel

Le pied de page cache l'envoi d'annonce si il y a trop d'enseignants responsable du cours...

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by jmontoyaa** [comment]
You can hide the teacher information in the footer changing the setting "show_teacher_data" here:

`main/admin/settings.php?search_field=show_teacher_data&submit_button=&_qf__search_settings=&category=search_setting`
