### ISSUE TITLE
Búsqueda de cursos falla

### ISSUE THREAD

**Issue by druiza** [chamilo/chamilo-lms#2021]
La búsqueda de cursos en el catálogo no funciona, en la actualización de chamilo 1.11.2 a 1.11.4

**Comment by jmontoyaa** [comment]
Indicar la URL.
Tratar de reproducir el error en https://11.chamilo.org/ (admin/admin)

**Comment by ywarnier** [comment]
Sin respuesta del usuario en más de 2 meses. Cerrando.
No reporter answer for more than 60 days. Closing.
