### ISSUE TITLE
La inscripción/subscripción a los cursos falla

### ISSUE THREAD

**Issue by druiza** [chamilo/chamilo-lms#2022]
**En la actualización de chamilo 1.11.2 a 1.11.4**, la autoinscripción o subscripción a cursos con contraseña, no solicita la contraseña, solo indica que el curso requiere la contraseña. Los usuarios/alumnos no pueden inscribirse a los cursos.

**Comment by andreslongui** [comment]
Solucionaste esto? es que me pasa lo mismo

**Comment by jmontoyaa** [comment]
Esto ya fue corregido en otra tarea. #2141
