### ISSUE TITLE
Error: Undefined variable: force_download_html in /var/www/html/main/inc/lib/document.lib.php on line 5542

### ISSUE THREAD

**Issue by sercon** [chamilo/chamilo-lms#2024]
Clean install of stable 1.11.4 version on centos7 using MariaDB in an Active Directory Environment. on server 2012R2

Error: Undefined variable: force_download_html in /var/www/html/main/inc/lib/document.lib.php on line 5542

**Comment by ywarnier** [comment]
@sercon does it really print "Error:"? This is weird. Normally undefined variables are "Notice" level messages, not "Errors"...

**Comment by sercon** [comment]
Sorry, forgot to mention i activated debugging to display error messages. Probably just an undeclared value.

**Comment by jmontoyaa** [comment]
Already fixed here:

https://github.com/chamilo/chamilo-lms/commit/78dd01fe183def8d48046d8a1c334cf21b8e96f7
