### ISSUE TITLE
Announcements: UX issue

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#2029]
### Current behavior / Resultado actual / Résultat actuel
New button too close to DeleteAll button
### Expected behavior / Resultado esperado / Résultat attendu
More space between them
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Let 200 teachers use announcements a lot and 0.5% of them will delete all announcements one or more times...
![afbeelding](https://user-images.githubusercontent.com/1659604/27120282-3a77979e-50e3-11e7-849e-07831f88d018.png)

![afbeelding](https://user-images.githubusercontent.com/1659604/27120239-1713be72-50e3-11e7-89b9-9db633c1a4ef.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
>=1.9

To prevent this problem I allways remove the "delete all" button. You can delete announcements by selecting them.

**Comment by jmontoyaa** [comment]
:+1: Agree with this change.

**Comment by jmontoyaa** [comment]
There's an option you need to add, to hide that button:

`$_configuration['disable_delete_all_announcements'] = true;`

**Comment by jderriks** [comment]
Works!
Should be documented somewhere (is there no configuration.dist.php?).
Then this can be closed.

**Comment by ywarnier** [comment]
There is a configuration.dist.php in main/install/ and it contains the setting :-)
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/install/configuration.dist.php
