### ISSUE TITLE
Assignments: settings: New documents are visible for all users  

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#2030]
### Current behavior / Resultado actual / Résultat actuel
the setting will not save, sometimes it will work, but most often not

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Try turning "New documents are visible for all users " on and off.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
https://11.chamilo.org

**Comment by ywarnier** [comment]
Hi @annickvdp, this is a very vague report coming from you. Could you track it down to a more reproducible use case?

**Comment by annickvdp** [comment]
Sorry to not be more specific, I'll try to clarify.
When you go to settings for assignments, you can change the setting to "new documents are visible to all users" or "new documents are only visible to the teacher".
![image](https://user-images.githubusercontent.com/15210140/33563459-52297e58-d918-11e7-9bb1-5ffb54e82287.png)

However, when I save this and go back to settings, the new setting was not saved.

**Comment by jmontoyaa** [comment]
I confirm that error. It should be fixed now.

**Comment by annickvdp** [comment]
Fix works perfectly. Thanks.
