### ISSUE TITLE
Detect session changes in local.inc.php

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2035]
### Current behavior
When switching manually the URL from one session to another (in the same course), there is no detection in place in local.inc.php (permission checks) to verify the session change.
As such, a coach from course A in session 1 can freely see the contents of course A in session 2 although he is not subscribed to it.
This is relatively minor, considering he cannot add or alter content (for some reason) and it is limited to users already having access to the same course in another context (base course or session), but it is still a (minor) security issue.

### Expected behavior
A coach from course A in session 1 should not be able to see the contents of course A in session 2.
This should be done through an additional check of session change ($sidReset?) at the beginning of local.inc.php (just below the first check on $cidReset).
This should then be checked when the cidReset is checked, to ensure there is a new check on the role of the user inside the given course.

### Steps to reproduce

- Create course A
- Create session 1 with course A and user X assigned (only) as tutor of course A inside this session (user X is not subscribed to any other course nor session in any capacity)
- Create session 2 with course A and no-one assigned as coach
- Connect as user X
- Enter course A of session 1
- Change the url (session_id=2)
- You can see the contents of course A in session 2

### Chamilo Version
1.11.4

**Comment by ywarnier** [comment]
This one can be considered a security issue. It's important for it to be included in 1.11.6.

**Comment by jmontoyaa** [comment]
@ywarnier I thought that the teacher of the course was the "master" (complete admin of the course) so he can see any session that's using his course. Are you sure about this change?

**Comment by ywarnier** [comment]
"I thought that the teacher of the course was the "master" (complete admin of the course) so he can see any session that's using his course. Are you sure about this change?"
Absolutely sure. The teacher of the course is the master of his own course but he has no authority on the sessions (at all) unless he's also registered as a course coach in that session.

This being said, my report is different. So I have modified the description. This is not about the teacher of the course, it is *only* about coaches of a course in a session.

**Comment by jmontoyaa** [comment]
I just tried again and it works good for me. 

The "source" course visibility must be set to "private". If it's public then coaches have access to that course/session.

**Comment by ywarnier** [comment]
(this is another issue I'll register after this, but there's again a problem with the access to sessions and the UTC vs local time)

**Comment by jmontoyaa** [comment]
@ywarnier  yes another issue and maybe an example in 11.chamilo.org

**Comment by ywarnier** [comment]
Haha, don't remove yourself just yet :-)

So you say "I just tried again and it works good for me."... And I just tried it and it still doesn't work. I'm creating this on 11.chamilo.org so you can test it.

https://11.chamilo.org/courses/BADACCESS/index.php is a private course. The "admin" user is teacher in that course (nobody else).

Session "badaccess-s1" is owned by mmosquera and she's a coach in course "Bad access" *in that session*: https://11.chamilo.org/main/session/resume_session.php?id_session=47

Session "badaccess-s2" is owned by jmontoya and he's a coach in course "Bad access" *in that session": https://11.chamilo.org/main/session/resume_session.php?id_session=48

Now, *as jmontoya* I go into course "Bad access" in my session "badaccess-s2", because this is the only place where I have access to this course.

I go to the documents tool and upload a session file: google-speech.png. The file is clearly indicated as session-specific file.
![session2](https://user-images.githubusercontent.com/609839/33997672-2546b64c-e0b3-11e7-8a6e-785810d62728.png)

I disconnect and login as "mmosquera" and enter course Bad access from session badaccess-s1, which is the only possibility I have from the interface:
![mmosquera](https://user-images.githubusercontent.com/609839/33997787-7e9b7548-e0b3-11e7-9a1a-89e05aad7f6a.png)

I enter the documents tool of the course, and I cannot see the google-speech.png file. Now I changed the session ID from 47 to 48:
https://11.chamilo.org/main/document/document.php?cidReq=BADACCESS&id_session=47&gidReq=0&gradebook=0&origin=
to 
https://11.chamilo.org/main/document/document.php?cidReq=BADACCESS&id_session=48&gidReq=0&gradebook=0&origin=

I can now see all the documents of session badaccess-s2, as coach mmosquera which should have no access whatsoever to that session.

![sessionbadaccesss2](https://user-images.githubusercontent.com/609839/33998445-7ec89b16-e0b5-11e7-8857-055a50dfbb2d.png)

**Comment by jmontoyaa** [comment]
I could reproduce the error. The thing is that **first** I have to enter to my course session, then i go to the the course session and I have access. It was tricky to find out.

**Comment by ywarnier** [comment]
It was in the initial description ;-)
But yes, tricky!

**Comment by jmontoyaa** [comment]
Should work now. Please try different cases.

**Comment by jmontoyaa** [comment]
When entering to a tool like this:

main/course_description/index.php

will show a warning message because cidReq is not provide the URL should be:

main/course_description/index.php?cidReq=XXX

**Comment by ywarnier** [comment]
If cidReq is not defined, it should stick to the previous cidReq (stored in session)

**Comment by ywarnier** [comment]
I'm not sure it's related, but today I started having this... :-)

https://youtu.be/uFgoHTY3v_Q

**Comment by jmontoyaa** [comment]
I cannot reproduce that error. Can you check in 11.chamilo.org? Maybe clean your twig template files?

**Comment by ywarnier** [comment]
@jmontoyaa you have to connect as a session course coach. As admin, it doesn't appear.

**Comment by ywarnier** [comment]
Perfect! (I mean it)
