### ISSUE TITLE
Mauvais lien dans le bandeau "lien Importer des quiz HotPotatoes"

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2036]
### Current behavior / Resultado actual / Résultat actuel
Not Found

The requested URL /main/.exercise/exercise.php was not found on this server.

### Expected behavior / Resultado esperado / Résultat attendu
Retour au menu

### Solution
Erreur à la ligne 34, un point (.) de trop avant exercise/exercise.php:
      'url' => api_get_path(WEB_CODE_PATH).'.exercise/exercise.php?'.api_get_cidreq(),

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
C'est corrigé. Merci! (il manquait le nom du fichier affecté mais j'ai trouvé facilement)
