### ISSUE TITLE
Timer in test incorrect at GMT +5:30

### ISSUE THREAD

**Issue by codez266** [chamilo/chamilo-lms#2038]
### Current behavior / Resultado actual / Résultat actuel
When I open a test with a time of 1:00hr I expect the countdown to start from 1:00hr
### Expected behavior / Resultado esperado / Résultat attendu
The countdown however starts from 6:30hr
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
This was reported at - https://support.chamilo.org/issues/4707 and I can verify that the issue is not fixed.
After debugging on the php end I found out that the time_left variable generated by php is indeed correct in the below file
`https://github.com/chamilo/chamilo-lms/blob/master/main/exercise/exercise.class.php#L3105`

The problem is with the epiclock library, a same issue there - https://code.google.com/archive/p/epiclock/issues/24

I wrote to the epiclock developer Eric Garside and he mentioned that the project isn't being maintained from a long time and suggested switching to some other timing library.
Hence I'm opening a bug here as to why chamilo, an actively maintained project is using such an outdated library for timing which is having a known issue.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.10

**Comment by ywarnier** [comment]
Hi @codez266, and thanks for reporting (with the link to historical info).

Yes, we know of the half-hour issue (for other topics too). As mentioned in the linked task, we hope the (Indian in this case) community can come together and provide a patch for this.

We will keep this issue opened but, with more than 1000M people in India and only less than 100M people in the 3 countries with Chamilo developers *combined*, I would hope that someone could offer a solution to this (that we can review and integrate) without us having to do it. After all, this is only about a very limited set of features of Chamilo. I would bet someone already has a fix for that somewhere but just didn't feel it necessary to contribute it.

**Comment by ywarnier** [comment]
@jmontoyaa The Zend framework provides a datetime class that manages half-hour timezone. Is there something similar in Symfony? PHP doesn't seem to manage those half-hours yet.

**Comment by jmontoyaa** [comment]
I don't see the error. I setup my timezone in chamilo to "Indian/Cocos"

My time in Paris is 12:12:06 and the time with that timezone is 17:42:06.
Then I setup an exercise with a max time of 60 min, and the counter appears correctly 59:59 minutes left.

I'm using latest chamilo 1.11.x with PHP 7.2

**Comment by ywarnier** [comment]
I think your timezone on your computer (not only Chamilo) has to be the Indian/Cocos too (`sudo dpkg-reconfigure tz-config` or something like that)

**Comment by apochr** [comment]
We had a lot of Indian students, and we solved this by changing 
https://github.com/chamilo/chamilo-lms/blob/58179597f5ae0f9c45047c567a5cfe3134c76802/main/exercise/exercise.class.php#L3297
to:
`format: 'x:C:s',`
instead of 
`format: 'x:i:s',`
I think I found this in an old forum post talking about the epiclock library, can't find the post anymore. But it is confirmed working. The problem affects all users having set a timezone with half-hours. It doesn not have to do with the server timezone. Previously we were asking them to change their timezone when they took the tests.

**Comment by AngelFQC** [comment]
Quoting a @apochr 
> to:
> `format: 'x:C:s',`

From the epiclock [documentation](https://code.google.com/archive/p/epiclock/wikis/DateFormatting.wiki)

The `C` 

> | Character | Description | Example | 
> |:--------------|:----------------|:------------|
>  | Timer Formatting* | -- | -- | 
> |...|
>  | x | Number of hours since epoch, padded to two digits | 00 to 23 | 
> |...|
>  | C | Number of minutes since epoch, padded to two digits | 00 to 59 | 
> |...|
> | Time Formatting | -- | -- |
> |...|
> | s | Seconds, padded to two digits. | 00 to 59 | 
> |...|
>
>  \* These rules are used for displaying timer information, working under the assumption that a timer is represented by subtracting the start time of the timer from the date the timer was started, thus offsetting the working date the the epoch, and counting the displacement as the seconds from that offset value.

I changed my timezone to Indian/Cocos in my SO. And I tested with the format  `x:i:s` then changing to `x:C:s`. And the exercise with 60 minutes works fine.

**Comment by ywarnier** [comment]
@codez266 any chance you can test this before our next release? (by pulling the changes from our repository, or by using https://11.chamilo.org/)
