### ISSUE TITLE
Alerte "Les prérequis n'ont pas été complétés" ne s'affiche pas

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2040]
Dans un parcours, une page blanche est affichée si le prés requis n'est pas complété

Avec la version 1.11.4 et aussi sur la 1.11.x du 21 juin.
Sur serveur ubuntu 16.04.2 et php7

Les autres alertes tel que "Information requise" s'affichent normalement.

**Comment by ywarnier** [comment]
J'ai constaté la même chose et c'est assez gênant. Voyons ce que @jmontoyaa peut faire pour nous sur ce coup-là.

**Comment by jmontoyaa** [comment]
This is problem of the Display::addFlash changes. I just added a fix.

**Comment by andreboivin** [comment]
Fonctionne bien,  
Merci, vous êtes super!
