### ISSUE TITLE
Shebang for cli-only scripts should be set

### ISSUE THREAD

**Issue by jwarnier** [chamilo/chamilo-lms#2041]
### Current behavior / Resultado actual / Résultat actuel
Executing any PHP script of Chamilo through the command-line (cli) requires running the interpreter manually, including from cronjobs.

### Expected behavior / Resultado esperado / Résultat attendu
The scripts that are meant only to be executed from the command-line (cli), such as the cron jobs, should have a proper shebang set.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11

**Comment by ywarnier** [comment]
Can we assume PHP will always be at /usr/bin/php ?

**Comment by ywarnier** [comment]
@jwarnier ping

**Comment by ywarnier** [comment]
Never received an answer. Closing.
