### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by AurelieGuy** [chamilo/chamilo-lms#2042]
### Current behavior / Resultado actual / Résultat actuel
![image](https://user-images.githubusercontent.com/28803818/27435484-a615377a-575c-11e7-99b3-ced6215253df.png)

My Chamilo platform can't get connected to your versions server. Could you give me his URL in order to configure my network please? I can't find it :-(

Thanks a lot!

**Comment by ywarnier** [comment]
http://version.chamilo.org/version.php

See here https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/ajax/admin.ajax.php#L159 (you can decide to comment it and return a fixed value, if you like)
