### ISSUE TITLE
Toujours des élèves avec "Inscrire des utilisateurs par lots"

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2045]
Par l'outil "Inscrire des utilisateurs par lots", lorsque j'importe une liste csv d'enseignants, ceux-ci seront inscrits comme apprenants dans le cours.
J'utilise la liste Enseignants.csv générée par l'outil "Export CSV".

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo 1.11.4

**Comment by ywarnier** [comment]
Patch envoyé. Je te laisse tester sur https://11.chamilo.org?
Note qu'il faut que les utilisateurs existent sur le portail Chamilo avant de pouvoir les importer dans un cours, et que le format d'import ne demande *que* une colonne username ou une colonne "id", mais c'est déjà bien indiqué sur la page d'upload (et je pense que ça fonctionne avec les fichiers complets, c'est juste que ça ne prend pas en compte les autres colonnes).

**Comment by andreboivin** [comment]
Super! Fonctionne très bien. 
Merci Yannick
