### ISSUE TITLE
Bug en evaluaciones V 1.11.4

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#2046]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes 
estoy probando la ultima version de chamilo 1.11.4   y me encuentro que en la parte de evaluaciones  se ha desaparecido  el icono de editar  Reglas de puntuación, en las anteriores versiones lo tenían

![image](https://user-images.githubusercontent.com/20644209/27500522-6d0e536c-582e-11e7-8c8d-d7235dbcf92f.png)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
*crear un curso 
*ir al icono de evaluaciones 
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
You need to update the setting:

`teachers_can_change_score_settings`

main/admin/settings.php?search_field=teachers_can_change_score_settings&category=search_setting

**Comment by fergimon** [comment]
Buenos días @jmontoyaa  gracias  por la respuesta, disculpa mirando el archivo settings.php  en que linea adiciono lo que me enviaste
