### ISSUE TITLE
WebService - create user

### ISSUE THREAD

**Issue by enjoyinformatica** [chamilo/chamilo-lms#2047]
The WSUser.CreateUser service does not save the value entered for user_id_field_name in version 1.11.4, in version 1.11.2 works.

### Chamilo Version 1.11.4
`
//code in php
...
$user = [ 
 'firstname' => 'ANDREIA',
  'lastname' => 'PARREIRAS' ,
  'status' => 5,
  'email' => 'andreia.parreiras@dominio.com',
  'username' => '2017045' ,
  'loginname' => '2017045' ,
  'language' => 'brazilian' ,
  'encrypt_method' => 'sha1' ,
  'active' => '1' ,
  'visibility' => '1' ,
  'password' => '123456789', 
  'phone' => '(31) 9999-9999' ,
  'expiration_date' => '2030-12-31',
  'original_user_id_name' => 'matricula_sa' ,
  'original_user_id_value' => '1A2017045' ,
  'user_id_field_name' => 'matricula_sa' ,
  'user_id_value' => '1A2017045' ,
  'extras' => []
];
$client->call('WSUser.CreateUser',  array_merge(array('secret_key'=>'secret'), $user));

`
Configuration in Administer user fields
![01](https://user-images.githubusercontent.com/16032449/27501828-3ed37460-5846-11e7-85a0-63614729ad95.png)

After exporting the person
![02](https://user-images.githubusercontent.com/16032449/27501829-3ed5f794-5846-11e7-9d44-03a133147686.png)

**Comment by jmontoyaa** [comment]
That's not the correct webservice try with 

webservices/registration.soap.php


See the example here:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/webservices/client_soap.php#L86
