### ISSUE TITLE
Catalogo de cursos si se cambia de categoría no encuentra cursos si la CurrentPage no es correcta

### ISSUE THREAD

**Issue by miky96es** [chamilo/chamilo-lms#2050]
### Current behavior / Resultado actual / Résultat actuel
En catalogo de cursos si filtramos por una categoría que genere paginación, pasamos a la siguiente página y luego cambiamos de categoría se mantiene el CurrentPage, si esta nueva categoría no tiene esa página aparece que "No existen cursos en la categoría actual" y eso no es correcto ya que si existen con esa categoría . ¿Cuando se cambie de categoría se debería volver a la CurrentPage 1 ? 

### Expected behavior / Resultado esperado / Résultat attendu
Al cambiar de categoría que vaya a la CurrentPage 1 así no aparece el mensaje de "No existen cursos en la categoría actual".

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Para reproducir esto se deben tener unos 13 cursos y tener al menos uno metido en una categoría diferente así se puede tener paginación de cursos en la categoría "Mostrar todos", vamos a catalogo de cursos ponemos la categoría "Mostrar todos" luego cambiamos a la página 2 y cambiamos de categoría al curso que tiene la categoría diferente, veremos que muestra el "No existen cursos en la categoría actual" cuando realmente si existen cursos con esa categoría. 

![screencapture-devfork-loc-main-auth-courses-php-1498466550976](https://user-images.githubusercontent.com/17494657/27531744-116d003a-5a5e-11e7-981b-faf93e55ee61.png)
Aquí se mostraría la categoría "Mostrar todos" con la paginación disponible.

![screencapture-devfork-loc-main-auth-courses-php-1498466570063](https://user-images.githubusercontent.com/17494657/27531748-12934fd2-5a5e-11e7-9802-aa2dc64b4937.png)
Aquí hemos pasado a la página 2 de la categoría "Mostrar todos".

![screencapture-devfork-loc-main-auth-courses-php-1498466582128](https://user-images.githubusercontent.com/17494657/27531750-13dd0086-5a5e-11e7-994a-8ade3421aee2.png)
Aquí hemos cambiado a la categoría que no hace páginación y vemos que muestra el mensaje de No existen cursos en la categoría actual"

PD: No hagáis caso del chat que sale descuadrado ya que lo provoca el plugin que me genera la captura de pantalla.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jmontoyaa** [comment]
Cannot reproduce, this was probably already fix it.
