### ISSUE TITLE
uft-8 dans administation/configuration des paramètres

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2052]
### Current behavior / Resultado actual / Résultat actuel
impossible de cocher la case uft-8 dans la configuration des paramètres de chamilo.
Quand on coche la case utf-8 et que l'on enregistre les paramètres, le paramètre n'est pas enregistré et la case n'est plus cochée

### Expected behavior / Resultado esperado / Résultat attendu
pouvoir cocher la case utf-8 et avoir le paramètre enregistré

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Aller dans administration, paramètre utf-8, cocher la case puis enregistrer les paramètres

### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo 1.11.4/ ubuntu 16.04/apache/php7

**Comment by ywarnier** [comment]
Bonjour @alexiye, pourrais-tu nous envoyer une capture d'écran de l'option dont tu parles? Je ne la vois pas dans Chamilo 1.11. Je ne vois que "Services web: décodifier UTF-8". Tu parles de ça?

**Comment by alexiye** [comment]
C'est bien ça. Quand je clique sur Services web :  décodifier UTF-8, la case ne reste pas cochée quand je reviens sur la page.
Comme il y a des problèmes de caratères dans les exercices avec des blancs (à) j'ai pensé qu'il y avait peut-être un lien de cause à effet et j'ai jugé bon de vous le signifier.

Au plaisir

**Comment by ywarnier** [comment]
@alexiye Que donne  le query suivant (dans la DB)?
`SELECT id, variable, subkey FROM settings_current WHERE variable = 'registration.soap.php.decode_utf8';`

**Comment by alexiye** [comment]
je veux bien essayer de faire mais là c'est du chinois pour moi

**Comment by alexiye** [comment]
je dois aller dans phpmyadmin ?

**Comment by ywarnier** [comment]
Oui, c'est ça. La commande va vérifier (principalement) combien de lignes il y a qui correspondent au paramètre. Parfois on a le problème d'un paramètre dupliqué suite à une mauvaise mise à jour, et ça donne le genre de comportement que tu mentionnes

**Comment by alexiye** [comment]
comment je fais la commande ?

**Comment by alexiye** [comment]
id | variable | subkey |  
-- | -- | -- | --
343 | registration.soap.php.decode_utf8 | NULL

**Comment by ywarnier** [comment]
Bon, je confirme le bug. En attendant qu'on le corrige tu peux lancer la commande suivante (aussi dans phpMyAdmin): 
`UPDATE settings_current SET selected_value = 'true' WHERE variable = 'registration.soap.php.decode_utf8';`

**Comment by ywarnier** [comment]
Oui, c'est bien ça, ce paramètre ne fonctionne pas à cause des points. Il faudra modifier le paramètre, mais cela veut dire qu'il faudra attendre la version 2.0 de Chamilo (pas de modification de base de données entre versions mineures, sauf pour les mises à jour depuis la version majeure antérieure).
Attention qu'à chaque sauvegarde de la première page des settings, il risque de revenir à false.

**Comment by NicoDucou** [comment]
Julio, tu peux déjà faire le changement dans master pour être sur de ne pas oublié.

**Comment by jmontoyaa** [comment]
Corrigé.
