### ISSUE TITLE
erreurs utf-8 

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2053]
version chamilo 1.11.4 
ubuntu 16.04 
apache
php7

Lors de la création d'un exercice remplir les blancs j'ai utilisé le choix entre plusieurs réponses :
Je vais [a|à] la mer.
![exercice a ou a](https://user-images.githubusercontent.com/24505996/27518601-f16a172a-59e3-11e7-8073-6a39e5a75106.png)

Quand l'étudiant passe l'exercice il voit cela :
![a ou a](https://user-images.githubusercontent.com/24505996/27518608-1a9bcab2-59e4-11e7-853f-267b5433043b.png)
On voit que le caractère "à" ne s'affiche pas correctement et le champ est disproportionné.

De plus le score est faux :

![score exercice](https://user-images.githubusercontent.com/24505996/27518609-2d1001b8-59e4-11e7-8e96-f74426f0e5c0.png)

Ces erreurs n'étaient pas présentes sur la 1.11.2
(ça y est, j'ai retrouvé ma boussole)

**Comment by andreboivin** [comment]
Effectivement, je confirme l'erreur est aussi présente sur https://1.11.chamilo.org du 1juillet même sans la condition ou. Par contre les é ne présentent pas de problème. 
Je ne comprend pas l'histoire de la boussole?

**Comment by jmontoyaa** [comment]
Je confirme l'erreur aussi. 
Il est possible que l'erreur a été ajouté ici:

https://github.com/chamilo/chamilo-lms/commit/0143b2bc5e481dfd23ffcdb81fe15f6ade5fef47

**Comment by jmontoyaa** [comment]
@AngelFQC can you check this one?

**Comment by AngelFQC** [comment]
Working on this

**Comment by NicoDucou** [comment]
To be able to ckeck rapidly if it works, I just added a test case here : 
https://11.chamilo.org/main/exercise/exercise_submit.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=707&learnpath_id=&learnpath_item_id=&learnpath_item_view_id=&preview=1

And for the moment it still doesn't work.

**Comment by jmontoyaa** [comment]
This happens because of this change by @AngelFQC 

https://github.com/chamilo/chamilo-lms/commit/0143b2bc5e481dfd23ffcdb81fe15f6ade5fef47

I don't know why there's this trimOption there's no documentation about what it does.
There are many uses of that function. There' should be just:

`trim($text);`

But I'm worry if I change this probably something else won't work ...  @AngelFQC ?

**Comment by AngelFQC** [comment]
@jmontoyaa see https://task.beeznest.com/issues/12630 there was a bug with Fill In Blanks questions about white spaces than `trim` cannot clean, so `trimOption` clean this characters here https://github.com/chamilo/chamilo-lms/commit/0143b2bc5e481dfd23ffcdb81fe15f6ade5fef47#diff-f5bb73da6adebfabf20f5e27dd738477R564

**Comment by ywarnier** [comment]
@jmontoyaa I need you to do it. @AngelFQC is on holiday for 2 weeks.

**Comment by jmontoyaa** [comment]
The problem is that the "value" inside the select is a string. 
It should be instead an integer, this generates other complications in the code.

![selection_006](https://user-images.githubusercontent.com/158935/34260787-4a43e442-e667-11e7-9f50-a634b8a76c96.png)

**Comment by ywarnier** [comment]
Indeed. Although if the page definition is in UTF-8, that should work... but in any case yes... we could move that to integers. Do you think you can do that this week or should I postpone to 1.11.8 (or 2.0)?

**Comment by jmontoyaa** [comment]
I just applied some changes. But this requires lot of tests. I tried with this text and it's working now:

```
Answer à [à|a|á]
Answer é [é|e|è]
Russian Ж [Ж]
Russian Ж1 [Ж1|Ж2|Ж3]
müssen [müssen]
müssen0 [müssen0|müssen1|müssen2]
Ärger [Ärger]
Ärger [Ärger|arger]

```

If you find an error please provide the "fill in blanks" text you're using as my example above.

**Comment by ywarnier** [comment]
Seems to be working very well for me.

![test](https://user-images.githubusercontent.com/609839/34329294-f11c7b36-e8c8-11e7-9a10-44b8a9eaf02c.png)

![test-correction](https://user-images.githubusercontent.com/609839/34329295-f3b9af12-e8c8-11e7-87db-8d0480a6644a.png)
