### ISSUE TITLE
Chamilo installation never finishes - Azure Web App

### ISSUE THREAD

**Issue by mredison** [chamilo/chamilo-lms#2057]
### Current behavior / Resultado actual / Résultat actuel
I am trying to install chamilo in Azure Web App, I updated the[ db fix](https://github.com/chamilo/chamilo-lms/issues/1997) for the new version and that fixed the error in the installation process. The problem is that this process never finishes. It is hanging forever without php error logs or some messages to understand what is happening.

### Expected behavior / Resultado esperado / Résultat attendu
I double checked that the installation was creating db tables successfully.
![chamilo_database](https://user-images.githubusercontent.com/12384552/27808053-c4ffb596-600a-11e7-8e31-e12e4b70e7f3.JPG)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire 
-Downloaded it from here: https://github.com/chamilo/chamilo-lms/releases/download/v1.11.4/chamilo-lms-1.11.4.tar.gz 
-Unzipped inside azure web app and then configure db.
-I followed all steps in the installation, it is just loading...
![chamilo_installation](https://user-images.githubusercontent.com/12384552/27808038-b037f592-600a-11e7-8039-70af87dd97aa.JPG)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo LMS 1.11.4

Do you have any idea of what is happening in this scenario? Is there any log that I can activate to see the installation process?

Thanks

Best Regards

**Comment by ywarnier** [comment]
There should be 243 tables in total, finishing with the table "version" after "usergroup_rel_usergroup". Does phpMyAdmin say you have 243?
The normal PHP error log is the default for Chamilo, so maybe the Azure setup is putting the real error_log somewhere unexpected?
Is the Azure Web App that thing where it doesn't really tell you what operating system it uses, or do you have that info?

**Comment by mredison** [comment]
Hi Yannick, thanks for your reply. 
-I just verified there are just 239 tables right now. I am not sure if that is because of the new version or it is an error in my installation.
![chamilo_2](https://user-images.githubusercontent.com/12384552/27809378-b6ba6904-6014-11e7-9a0f-3d7ac45fbb2b.JPG)

-I am seeing the "version" and "usergroup_rel_usergroup" tables but I am suspecting that Azure Network is cutting the connection after 4 mins without response from the installation request, so it is getting stuck in that process. 

![chamilo_1](https://user-images.githubusercontent.com/12384552/27809443-3747be3c-6015-11e7-8fd0-d998f268d221.JPG)

I have enabled php error log, but it is still in blank. 

Thanks

**Comment by ywarnier** [comment]
I cannot really check that at the moment (I have no account to test the context) but:
* Chamilo shouldn't take that long to install the initial structure (on my laptop without any particular type of optimization it takes less than one minute)
* I'm using 1.11.4 but I might have a few tables created by plugins. I'll have to do a new install to make sure of the tables count. Sorry about that wrong info before, I just thought about that when I saw your tables count.

Let me know if you manage to get more info from the log. In any other case, did you try just loading your Chamilo portal without the main/install/ path? Maybe it was completely installed but your web browser hung?

**Comment by gvalverdes** [comment]
Hi yannick
I have the same problem with the version 1.11.4. The installation never finished.
I try install in this site:
![2017-07-14](https://user-images.githubusercontent.com/30187525/28233061-7d49e7d0-68b1-11e7-99c0-ee2e9d2177dc.png)

I try load my Chamilo portal without the main/install/ path; and it restart the installation.

Thanks

**Comment by jmontoyaa** [comment]
Can you please, copy and paste the error in the apache logs

**Comment by ywarnier** [comment]
It is difficult to help here without having more context. We thank you for your contribution, but unless you can provide us with more information, I have to close this issue for now. Sorry.

**Comment by ziaongit** [comment]
![screencapture-localhost-rettsacademy-main-install-index-php-1517168710570](https://user-images.githubusercontent.com/6294965/35486285-33803120-046c-11e8-8daa-d6e0efdbe2e8.png)
I have this issue

**Comment by ywarnier** [comment]
@ziaongit you are probably using PHP 7.0. We will  be releasing an updated package version this week to support PHP 7.0 (we already support 5.6, 7.1 and 7.2)

**Comment by ziaongit** [comment]
I am using PHP Version 5.6.31

Getting the following errors

Fatal error: Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded.' in C:\xampp\htdocs\2018\MyAcademy\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 C:\xampp\htdocs\2018\MyAcademy\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 C:\xampp\htdocs\2018\MyAcademy\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 C:\xampp\htdocs\2018\MyAcademy\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 C:\xampp\htdocs\2018\MyAcademy\vendor\doctrine\annotations\lib\Doctrin in C:\xampp\htdocs\2018\MyAcademy\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54
