### ISSUE TITLE
Bug Vr 1.11.4 no muestra el usuario con el rol asignado

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#2058]
### Current behavior / Resultado actual / Résultat actuel
Buenos días acabo de instalar la version 1.11.4 de esta direccion https://github.com/chamilo/ Chamilo LMS / releases / descarga / v1.11.4 / chamilo-LMS-1.11.4. tar.gz  todo se instalo normal lo que veo es que un docente como un estudiante no mira la session que se le fue asignada, 
en esta imagen se ve que el docente tiene asignado  su respectiva session

![image](https://user-images.githubusercontent.com/20644209/27841680-14bec004-60c9-11e7-87ca-bd810bd67720.png)
en esta imagen es cuando el docente ingresa a su perfil y no encuentra su session asignada 

![image](https://user-images.githubusercontent.com/20644209/27841743-89e335d6-60c9-11e7-9cf3-afaddda94a2e.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
 1.11.4

**Comment by jmontoyaa** [comment]
Hola, tratar de reproducir el error aquí:

https://1.11.chamilo.org/ Acceso (admin/admin)

Tal vez hay un filtro por la fecha de la sesión.

**Comment by fergimon** [comment]
gracias por responder @jmontoyaa   si claro faltaba un parámetro en la parte de administratorio  que se pudo evidencia el curso en los dos roles
