### ISSUE TITLE
Problème d'installation Chamilo 1.11.4

### ISSUE THREAD

**Issue by Kokosakasaka** [chamilo/chamilo-lms#2061]
Bonjour,
Serait-il possible d'avoir de l'aide pour l'installation de Chamilo, svp ? Merci.

### Current behavior / Resultado actual / Résultat actuel
Messages à l'étape 2 
Deprecated: Function mcrypt_module_open() is deprecated in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 75

Deprecated: Function mcrypt_enc_get_block_size() is deprecated in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 76

Deprecated: Function mcrypt_enc_get_iv_size() is deprecated in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 77

Deprecated: Function mcrypt_module_close() is deprecated in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\ircmaxell\random-lib\lib\RandomLib\AbstractMcryptMixer.php on line 86

Message à l'étape 7 :
Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded. in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\doctrine\anno in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Bonjour,
La première erreur est un avertissement qui peut être ignoré.
La seconde vient d'un problème de chemin de fichiers qui ne se produit que sous Windows. Il est réglé par le remplacement du fichier main/inc/lib/database.lib.php par cette version-ci: https://raw.githubusercontent.com/chamilo/chamilo-lms/036d6559ac9c41b3b28a81de898241678a0e749a/main/inc/lib/database.lib.php

Le tout a été détaillé (encore que majoritairement en espagnol) ici: #1997

**Comment by Kokosakasaka** [comment]
Merci beaucoup pour l'aide ! J'ai réussi l'installation !Amicalement,Julien
 

    Le Mercredi 5 juillet 2017 21h46, Yannick Warnier <notifications@github.com> a écrit :
 

 Bonjour,
La première erreur est un avertissement qui peut être ignoré.
La seconde vient d'un problème de chemin de fichiers qui ne se produit que sous Windows. Il est réglé par le remplacement du fichier main/inc/lib/database.lib.php par cette version-ci: https://raw.githubusercontent.com/chamilo/chamilo-lms/036d6559ac9c41b3b28a81de898241678a0e749a/main/inc/lib/database.lib.phpLe tout a été détaillé (encore que majoritairement en espagnol) ici: #1997—
