### ISSUE TITLE
SCORM 1.2: format of cmi.core.student_name is incorrect

### ISSUE THREAD

**Issue by moloko** [chamilo/chamilo-lms#2062]
The value returned when `LMSGetValue('cmi.core.student_name')` is called is `"John Doe"`.

According to the SCORM 1.2 Run Time Environment documentation, the correct format for this is:
> Format: Last name, first name and middle initial.  Last name and first name are separated by a comma
> Example Return Values:  "Student, Joseph A." "Student, Mike A. Jr." 

The LMS should therefore be returning this as `"Doe, John"`.

The majority of SCORM 1.2 conformant Learning Management Systems adhere to this rule, therefore code that is set to retrieve and use the value of this field will be expecting it to be in "lastname, firstname" format.

**Comment by ywarnier** [comment]
This is a perfect bug report... Sorry for the inconvenience. I believe the syntax was correct a few years ago, then we changed the function that returns the "full name" without seeing it broke the SCORM requirement. Few providers we know actually use this value, hence why nobody ever reported this.

Thanks. I just sent a patch for this in branch 1.11.x (our latest stable branch)

**Comment by ywarnier** [comment]
I would leave the task open so you can approve the patch, but there's virtually no way the patch could be wrong (the issue was very clear and so was the solution). Just let me know if you find something off.

**Comment by moloko** [comment]
Yeah, I see what you mean - very simple solution like you say!

The annoying thing is that in SCORM 2004 both variants are correct because the SCORM 2004 spec doesn't go into specifics about how the name should be formatted.

Thanks for the quick fix.
