### ISSUE TITLE
No carga curso "Captura horas SIHO"

### ISSUE THREAD

**Issue by malspraxis** [chamilo/chamilo-lms#2064]
Se carga la página de inicio del curso pero sin iniciar las lecciones

Cargar pantalla con pdf del curso

Ir al menú mis cursos-Seleccionar el curso Captura Horas SIHO
![captura de pantalla de 2017-07-06 18-04-09](https://user-images.githubusercontent.com/29963471/27936187-246638ae-6275-11e7-9d79-f01ed35aaefd.png)

**Comment by ywarnier** [comment]
Hola @malspraxis,
Cual es el error exactamente?

**Comment by jmontoyaa** [comment]
Cerrando por falta de feedback.
