### ISSUE TITLE
Bug Vr. 1.11.4 al cargar imágenes al curso

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#2065]
### Current behavior / Resultado actual / Résultat actuel

realizando una prueba en la version 1.11.4 tengo un problema al agregar una imagen en el escritorio del curso  se anexa imágenes  del problema,  

![image](https://user-images.githubusercontent.com/20644209/27963017-44bc85ac-62f9-11e7-92f2-60c6b96b3175.png)

![image](https://user-images.githubusercontent.com/20644209/27962659-3092e658-62f8-11e7-95ff-8cc42c5bff45.png)
Al abrir la imagen no la encuentra 

![image](https://user-images.githubusercontent.com/20644209/27962701-52e61860-62f8-11e7-9a29-c510199a7ed5.png)

En la carpeta de mis documentos  ingreso a imágenes y ahí si las visualizo y el ojo si se encuentra abierto 

![image](https://user-images.githubusercontent.com/20644209/27962819-ac787b66-62f8-11e7-9644-0f7d943bb5e3.png)

*también se verifico en la maquina la ruta de la imagen en en curso y si se encontraba.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

*se crea un curso de prueba 
*se procede a modificar el escritorio 
*Se procede a cargar un imagen 
*se busca en documentos la carpeta de imágenes 
*Se procede a agregar la imagen 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Hola @fergimon, en la URL que usas para acceder directamente a la imagen, falta "/chamilo" que aparece como carpeta base en la URL de la ventana del navegador de archivos.

**Comment by fergimon** [comment]
Buenas tardes @ywarnier  gracias por tu colaboración   es que no muestra la imagen  para cargarla, como lo muestra la segunda imagen  y ahí si  esta la dirección ip/chamilo

**Comment by mansaya** [comment]
A mi me pasa igual, lo que note es que falta una parte en la url(carpeta donde esta alojado el sitio), el problema es donde podre configurar para que esta ruta quede completa, me podrian ayudar

**Comment by ywarnier** [comment]
app/config/configuration.php:
```
// Path to the webroot of system, example: /var/www/
$_configuration['root_sys'] = '/var/www/chamilo111x/';

// Path from your WWW-root to the root of your Chamilo installation,
// example: chamilo (this means chamilo is installed in /var/www/chamilo/
$_configuration['url_append'] = '';
```

Usualmente estos problemas ocurren luego de haber modificado la ruta de un portal Chamilo (de una subcarpeta a una ruta sin subcarpeta, o al revés)

**Comment by mansaya** [comment]
Muchas gracias por su colaboracion, he revisado en la ruta y todo esta correcto, el tema que tengo actualmente surge cuando se crea una leccion y a esta agregamos  un nuevo documento, cuando se realiza esto aparece un formulario donde podemos agregar informacion, es un editor donde podemos seleccionar imagenes, flash etc. Al agregar una imagen seleccionando el icono sale una pantalla donde debemos colocar un ruta y tambien hay un boton que dice servidor, en este boton se despliega una pantalla para navegar dentro del curso, yo puedo cargar sin problemas imagenes pero cuando necesito seleccionar una esta me sale como si no existiera, revisando encuentro que es que a la url le falta la palabra chamilo(Esto por que mi sitio se creo en esta carpeta). El problema que veo es como en el editore(el finder creo que se llama). El problema es exactamente al que pasa cuando se inicia este hilo de preguntas. Muchas gracias por su ayuda.

**Comment by ywarnier** [comment]
Hola @mansaya 
Esto te pasa en un Chamilo 1.11.4, verdad?

**Comment by mansaya** [comment]
En este momento tengo Camilo 1.11.6 será que debo instalarlo en la ruta principal.sin carpeta que lo contenga?, Gracias

**Comment by ywarnier** [comment]
No, debería funcionar con una subcarpeta. Por eso te pedía confirmación. Podrías abrir un nuevo "Issue" para ello, indicando que tienes una 1.11.6 con una subcarpeta, para que la podamos gestionar de manera independiente? (aquí no era exactamente el mismo problema)

**Comment by ywarnier** [comment]
Igual instalando en la carpeta raíz sí lo va a solucionar.

**Comment by mansaya** [comment]
Listo que pena es que leyendo el problema inicial se parece mucho por qué al colocar la subcarpeta de una vez conecta las imagenes, pero la persona que hace el curso cuando agrega la imagen manualmente debería colocarla para que aparezca voy a probar en la raíz y abro un nuevo caso, muchas gracias

**Comment by ywarnier** [comment]
Para la historia, proveemos el modo de funcionamiento en una subcarpeta para los que no tienen las competencias para definirse un subdominio para su portal, pero es un modo de funcionamiento menos soportado (porque requiere considerablmente más trabajo de parte de los desarrolladores) y algunas cosas como la que mencionas pueden que funcionen menos bien. El mejor contexto para asegurar un funcionamiento óptimo es como subdominio, porque a parte de simplemente una elección estética, permite un mucho mejor control a nivel del servidor web.
No quiere decir que no nos interese corregir los problemas con subcarpetas, pero pueden demorrar un poco más porque no es nuestra prioridad.

**Comment by mansaya** [comment]
Muchas gracias por su explicación voy a instalarlo en la raíz gracias
