### ISSUE TITLE
Missing links at learnpath after course copy

### ISSUE THREAD

**Issue by CesarCavazos97** [chamilo/chamilo-lms#2066]
### Current behavior
Copied course with missing links (url) at learnpaths

### Expected behavior
Correct functionality of each link at learnpaths 

### Steps to reproduce
After creating a new course, when you copy an existing course (with backup or copy course option) all current links created are empty on each learnpath, if want to visualize that link on the student view only shows a blank screen.

### Chamilo Version 
1.11.2

**Comment by CesarCavazos97** [comment]
At links tool, all links works correctly, this is only at learnpaths

**Comment by jmontoyaa** [comment]
Hi can you try to reproduce the error here? 

https://1.11.chamilo.org/ (admin/admin)

**Comment by CesarCavazos97** [comment]
I already did it, the original course name is: Test links course (TLC1) and I copied to the course Test links course copy (TLC2), at the moment of enter at learnpath in this version of chamilo shows this error: 

**Notice: Undefined index: url in /var/www/1.11.chamilo.org/www/main/lp/learnpath.class.php on line 8393**

**Comment by CesarCavazos97** [comment]
Other thing, when you copy a course it's possible to include the learnpath categories created?

**Comment by jmontoyaa** [comment]
i just added a fix, can you try again?

**Comment by ywarnier** [comment]
Hi @CesarCavazos97 could you tell us if @jmontoyaa 's fix solves the issue for you on https://11.chamilo.org/ ?

**Comment by CesarCavazos97** [comment]
@jmontoyaa @ywarnier Thanks, it works!
