### ISSUE TITLE
Fallos en las herramientas de exportación en CSV de informes

### ISSUE THREAD

**Issue by xenonfactory** [chamilo/chamilo-lms#2067]
### Current behavior / Resultado actual / Résultat actuel
Diferentes errores al utilizar las herramientas de exportación de Informes en CSV.

### Expected behavior / Resultado esperado / Résultat attendu
Documentos CSV sin errores de codificación y otros problemas detectados.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

**(Con rol de Director de RRHH)**

- Informes > "Profesores seguidos" > Sobre el listado de usuarios
	Al exportar en CSV se muestra una pantalla en blanco.

- Informes > "Estudiantes seguidos" > Sobre el listado de usuarios
	Fallo de codificación de caracteres al exportar el informe en CSV.

- Informes > "Profesores seguidos" > Escoger un usuario de la lista
	Fallo de codificación de caracteres al exportar el informe en CSV.

- Informes > "Estudiantes seguidos" > Escoger un usuario de la lista
	Fallo de codificación de caracteres al exportar el informe en CSV.

- Informes > "Profesores seguidos" o "Directores de RRHH seguidos" > Escoger un usuario de la lista
	En el breadcrumb indica "Informes / Mis estudiantes / Detalles del estudiante".

- Un curso cualquiera creado > Informes > Sobre el listado de alumnos
	Fallo de codificación de caracteres al exportar el informe en CSV.

- Un curso cualquiera creado > Informes > Escoger un alumno de la lista
	Fallo de codificación de caracteres al exportar el informe en CSV.

- Un curso cualquiera creado > Informes > "Seguimiento del curso"
	Al realizar una exportación en CSV, recarga la página pero no se inicia la descarga del documento.

- Un curso cualquiera creado > Informes > "Informe sobre recursos"
	Al realizar una exportación en CSV, recarga la página pero no se inicia la descarga del documento.

- Un curso cualquiera creado > Informes > Escoger un alumno de la lista > Detalles de cualquier lección
	Error 500 al intentar exportar en CSV

### Chamilo Version / Versión de Chamilo / Version de Chamilo
v.1.11.4

Gracias ;-)

**Comment by jmontoyaa** [comment]
Hola es posible de copiar la URL con el problema?
O tal vez tratar de reproducir el error aqui:

https://1.11.chamilo.org/ (admin/admin)

**Comment by xenonfactory** [comment]
Buenos días, Julio.

Si te parece bien, te puedo dar indicaciones sobre [https://1.11.chamilo.org](https://1.11.chamilo.org)

Respecto a simular los problemas de codificación UTF-8, necesitaría cambiar el idioma para mostrarte los fallos en acentos y otros caracteres.

Por otra parte, he probado los otros errores:

- Informes > "Profesores seguidos" > Sobre el listado de usuarios
Al exportar en CSV se muestra una pantalla en blanco.
Url: [https://1.11.chamilo.org/main/mySpace/teachers.php](https://1.11.chamilo.org/main/mySpace/teachers.php)

- Un curso cualquiera creado > Informes > Escoger un alumno de la lista > Detalles de cualquier lección
Error 500 al intentar exportar en CSV
No logro que se reproduzca en este entorno.

Respecto a "problema" de lo indicado aquí:

- Informes > "Profesores seguidos" o "Directores de RRHH seguidos" > Escoger un usuario de la lista
En el breadcrumb indica "Informes / Mis estudiantes / Detalles del estudiante".
Url: [https://1.11.chamilo.org/main/mySpace/myStudents.php?student=67](https://1.11.chamilo.org/main/mySpace/myStudents.php?student=67)

Gracias ;-)

**Comment by AngelFQC** [comment]
Hola @xenonfactory he enviado dos commits para corregir el primer y tercer punto. El segundo no puedo reproducirlo, prueba revisando tus permisos de usuarios o logs de tus servidor

**Comment by xenonfactory** [comment]
Hola @AngelFQC

Gracias por ir avanzando con esos dos errores. Procuraré investigar porque en mi entorno no se reproducen el segundo fallo.

¿Respecto a la codificación de los caracteres al exportar los citados CSV, como se puede gestionar una solución?

Gracias ;-)

**Comment by nosolored** [comment]
Creo que esta tarea se puede cerrar @ywarnier, no detecto errores en la exportación de los CSV que indica @xenonfactory. 
Pienso que lo que comenta de los caracteres es la codificación UTF-8, los CSV se exportan así y si los abres en Excel se ven caracteres extraños, pero es lógico. Una vez exportado puedes convertirlo a ANSI o Unicode con cualquier editor de texto en tu ordenador.

**Comment by ywarnier** [comment]
Gracias @nosolored.
@xenonfactory espero la respuesta de @nosolored te ayude en el cambio de codificación.
