### ISSUE TITLE
require errors being generated when displaying SCORM package in 'embedded' mode

### ISSUE THREAD

**Issue by moloko** [chamilo/chamilo-lms#2069]
As you'll have seen from #2062 and #2063 I've been doing some testing of the [Adapt Learning Framework](https://github.com/adaptlearning/adapt_framework) in Chamilo

Whilst testing, I noticed that if I set the course to launch in 'embedded' view mode (the default), it doesn't display and require.js is generating an error in the console:
![chamilp-require-error-firefox](https://user-images.githubusercontent.com/1249597/28036319-bb3f334c-65af-11e7-945d-d6068f3d9243.png)

We've done a bit of digging and it seems that Chamilo is injecting some <script> tags into our content
![chamilo-script-injection](https://user-images.githubusercontent.com/1249597/28036394-05bf89a8-65b0-11e7-979b-7451d217d53d.png)

Specifically the problem seems to be originating from https://1.11.chamilo.org/main/glossary/glossary.js.php which uses jquery-ui.min.js - which has a define statement with a missing name - and  because Adapt uses requirejs, the module is trying to register with Adapt's requirejs library but with no name, which isn't allowed - hence the error.

If you want to see this for yourself go to the aabbb course on 1.11.chamilo, select learning paths > Adapt Version 2.0 demonstration.

Is there a reason for injecting stuff into the course content? This seems to us to be a bit of a risky thing to do as it can cause problems exactly like this.

I also got similar problems using all other view modes except fullscreen.

**Comment by jmontoyaa** [comment]
Yes, Chamilo injects those js and also loads the glossary js .php file ... I think we need an option in the LP in order to don't pre load those files.

**Comment by ywarnier** [comment]
Let's add this option to v2.0 (scheduled for 2018).

**Comment by sinozzuke** [comment]
Hi, I'm trying to use scorms from Adapt Learning and can reproduce the problems @moloko had. As the release of Chamilo 2.0 didn't happen yet, is there a workaround so we can patch this on our Chamilo 1.11.8 installation and be able of using these scorms?

**Comment by sinozzuke** [comment]
Some advances in my investigations:
Doing some research I have used campus.chamilo.org for uploading a SCORM test file, and it works like a charm. So, I have emailed them to know what version of chamilo are using but has not answer yet. 

[build.zip](https://github.com/chamilo/chamilo-lms/files/2827758/build.zip)

**Comment by christianbeeznest** [comment]
It had errors displaying the scorm in lp view as iframe, the ressources as css , js, weren't loaded, It is fixed with this PR https://github.com/chamilo/chamilo-lms/pull/4403 .

**Comment by ywarnier** [comment]
PR approved but testing pending.

**Comment by NicoDucou** [comment]
I can not import a Scorm package in Chamilo2, when importing the file I get the following error : 

```
PhpZip\Exception\
ZipException
in vendor/nelexa/zip/src/ZipFile.php (line 101)
ZipFile->openFile()
in public/main/lp/learnpath.class.php (line 1472)
            ])) {            return 'woogie';        }        $zipFile = new ZipFile();        $zipFile->openFile($filePath);        $zipContentArray = $zipFile->getEntries();        $package_type = '';        $manifest = '';        $aicc_match_crs = 0;        $aicc_match_au = 0;
learnpath::getPackageType()
in public/main/lp/lp_upload.php (line 57)
require_once('/var/www/testing24.beeznest.com/www/public/main/lp/lp_upload.php')
in public/main/upload/upload.scorm.php (line 11)
require('/var/www/testing24.beeznest.com/www/public/main/upload/upload.scorm.php')
in public/main/upload/upload.php (line 16)
```
So I can not test for the moment.
Tried it here :  https://testing24.beeznest.com/main/upload/index.php?cid=1&sid=0&gid=0&gradebook=0&origin=&curdirpath=/&tool=learnpath

I also tried it in Chamilo 1.11.x  and the build.zip Scorm package indicated in this task works fine.

@christianbeeznest could you check the scorm package import in Chamilo 2 to be able to upload the zip file and test this issue.

**Comment by moloko** [comment]
`return 'woogie';` 
?! 🤣

**Comment by christianbeeznest** [comment]
Hi @NicoDucou ,

I found an error when a lp or scorm is imported, it is about default value of next_lp_id , it is fixed in this PR https://github.com/chamilo/chamilo-lms/pull/4727 . I tested in my local chamilo 2 and imported the scorm build.zip  . When I try in portal testing24 I get this Error: Maximum execution time of 30 seconds exceeded. 

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest

**Comment by NicoDucou** [comment]
No queria cerrar la tarea era un error de teclado.

Por lo de la creation he acdeptado tu PR #4727 y ahora funciona pero el importe de Scorm todavia da errores.

He modificado la configuration en testing24 para el max_execution_time y ahora puedes acceder a https://testing24.beeznest.com/main/upload/index.php?cid=1&sid=0&gid=0&gradebook=0&origin=&curdirpath=/&tool=learnpath

Pero al carga un zip me da el mismo error que antes :

```
File does not exist.
ExceptionLogs 2Stack Trace
PhpZip\Exception\
ZipException
in vendor/nelexa/zip/src/ZipFile.php (line 101)
ZipFile->openFile()
in public/main/lp/learnpath.class.php (line 1474)
            ])) {            return 'woogie';        }        $zipFile = new ZipFile();        $zipFile->openFile($filePath);        $zipContentArray = $zipFile->getEntries();        $package_type = '';        $manifest = '';        $aicc_match_crs = 0;        $aicc_match_au = 0;
learnpath::getPackageType()
in public/main/lp/lp_upload.php (line 59)
require_once('/var/www/testing24.beeznest.com/www/public/main/lp/lp_upload.php')
in public/main/upload/upload.scorm.php (line 11)
require('/var/www/testing24.beeznest.com/www/public/main/upload/upload.scorm.php')
in public/main/upload/upload.php (line 16)
```

Si lo puedes revisar.

**Comment by NicoDucou** [comment]
It was a configuration issue on the server that did not allowed file bigger than 2Mo, once the configuration was adapted the import worked perfectly and the scorm build.zip worked fine.
So I'm closing this issue.
Good work
