### ISSUE TITLE
BUG: Matching / Draggable questions loose correct answers after course copy

### ISSUE THREAD

**Issue by CesarCavazos97** [chamilo/chamilo-lms#2072]
### Current behavior
When copying a course the exercises with questions of type draggable doesn't copy the correct answer

### Expected behavior 
Correct copy of exercises

### Steps to reproduce
Create a course
Add an exercise
Add a matching or match by dragging question
Create another course
Backup it (fully or selecting only the exercise)
Check the exercise

I already did an example at 1.11.chamilo,org (admin/admin) with the course: Draggable questions 1 copied to Draggable questions2

### Chamilo Version
Tested on Chamilo 1.11.2 and 1.11.4

**Comment by jmontoyaa** [comment]
I test it locally and it works for me. Probably it was already fixed.

**Comment by aqblanco** [comment]
For me, something similar it is happening when copying a question (using the copy button in the question list). 
# 
**Steps to reproduce**
Copy a question using the copy question button in the question list.
Edit the newly created question.
Add a new answer.
Save changes and edit it again, references to the linked question will be lost (an `UPDATE c_quiz_answer SET correct = 0 WHERE iid = x ` query is executed).

**Comment by jmontoyaa** [comment]
It works for me. Can you try in 11.chamilo.org in a new course?

**Comment by aqblanco** [comment]
Yes, sure. https://11.chamilo.org/courses/TESTCOURSE/index.php?id_session=0 If you try to add a new answer in any of both questions it will reproduce the bug (already created one, so right now it's happening)

**Comment by jmontoyaa** [comment]
Should be fixed now.
