### ISSUE TITLE
Number of users online in session does not appear

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2084]
### Current behavior

One of the options for showing online users in the top-right side of the page is about users currently inside the session (in any course). However, the corresponding number does not appear (it does for courses and portal).

### Steps to reproduce

Connect to a course inside a session and watch the top-right corner of the page: you get 1 for portal, 1 for course but nothing for session.

### Chamilo Version
1.11.x

**Comment by nosolored** [comment]
He probado en varias demos y funciona correctamente, se puede cerrar la tarea
