### ISSUE TITLE
Bug en Vr 1.11.4, se borra usuario al ampliar el curso

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#2085]
### Current behavior / Resultado actual / Résultat actuel
realizando una prueba en la version 1.11.4   me doy cuenta  que cuando  se aumenta  el espacio al curso, el automáticamente elimina los docentes que tiene inscritos, también los elimina  si el curso tiene sesiones  añadidas, 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* Crear un curso de prueba
*Por defecto el curso se crea con 100 M
*Se añade un usuario docente  al curso 
*Después se edita el curso y se amplia a 150 M
*se va a usuario y el docente no se encuentra ya registrado  

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
No puedo reproducir el problema.  Tal vez ya fue corregido.
Probarlo en:

https://11.chamilo.org/ (admin/admin)

**Comment by ywarnier** [comment]
Sin feedback desde más de un mes y no podemos reproducir. Cerrando.
