### ISSUE TITLE
Removing one user from course in session add to users count in course

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2087]
### Current behavior
On the session details page, removing a user from one course from the courses list block icon works fine.
When removing one course from a user in the users list block icon adds users in the users count column to other courses instead of removing from the given course.
It seems like it's not deleting anything *before* adding back again...

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Create 3 students
- Create 2 courses
- Create 1 session
- Add all 2 courses to the session
- Add all 3 students
- in the session details page, both courses show "3" as the number of users
- use the user icon next to course 1 to remove user 1
- in the session details page, the lines now show "2" and "3" as the number of users
- use the course icon next to user 2 in the list below
- move course 1 from left to right (put it in "exclude") and save
- go back to the session details page
- now the list of courses show "2" and "4": instead of removing from course 1, it added one session_rel_course_rel_user record for course 2...

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
@AngelFQC ping

**Comment by nosolored** [comment]
@ywarnier, bug fixed, you can close this issue
