### ISSUE TITLE
Ejercicios con control de tiempo

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2090]
### Current behavior / Resultado actual / Résultat actuel
Al configurar un ejercicio con control de tiempo, si un usuario sale del ejercicio el cronómetro se detiene y puede volver a entrar y continuar donde se detuvo.
Este funcionamiento puede ser coherente si se trata de autoevaluaciones o ejercicios normales, pero en el caso de un examen no parece lógico, ya que el alumno tendría todo el tiempo que quisiera para hacer el examen, podría entrar, ver las preguntas, salir, consultar sus apuntes y volver después a realizarlo. De esta forma el límite de tiempo no tiene ningún sentido.

### Expected behavior / Resultado esperado / Résultat attendu
Al menos en los ejercicios configurados como examen, con control de tiempo y con un sólo intento, el que un usuario abandone el ejercicio debería implicar que ha perdido el intento, y no debería poder acceder de nuevo.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Crear un ejercicio, configurar con control de tiempo. Acceder como alumno al ejercicio, salir del mismo y volver a entrar, para comprobar que el crono continúa donde se quedó.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.10.x, 1.11.x

**Comment by ywarnier** [comment]
El comportamiento normal es que el tiempo *no* se detenga (jamás hasta llegar al final) cuando el usuario ha empezado un ejercicio. El comportamiento que indicas no es lo que debería suceder. Algo está muy mal si así está funcionando ahora. Estaremos revisando este caso tan pronto como podamos.

**Comment by nosolored** [comment]
Actualización: en la 1.11.4 actualizada con lo último de Github ya no se nos produce este problema, el crono continúa aunque el alumno no esté en el ejercicio y cuando vuelve a entrar se muestra el tiempo que debería, es correcto.

**Comment by NicoDucou** [comment]
Todo esta correcto entonces se cierra la tarea.
