### ISSUE TITLE
Work Report show time in GMT instead of Server time

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2091]
### Current behavior / Resultado actual / Résultat actuel

In /main/work/work_list_all.php
The time showed in the table is GMT, but it should show the Server time.
The mouse over show the correct time thou. 

![2017-07-24 09_23_54-](https://user-images.githubusercontent.com/1764993/28523340-5413f402-7052-11e7-8014-35c642d50241.png)

### Expected behavior / Resultado esperado / Résultat attendu
It should show the result in the Server time.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
This was fixed already. Will be available in the next minor version of Chamilo.

You can test it here: https://11.chamilo.org/ (admin/admin)
