### ISSUE TITLE
Bug V 1.11.4 se distorsiona template al agregar mas de 20 usuarios a un curso

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#2092]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes esoty manejando la version 1.11.4 y encontrado que cuando se inscribe mas de 20 usuario a un curso o profesores el template de la aplicacion se corta y no muestra todos los usuarios
Se anexa foto del problema 
![captura](https://user-images.githubusercontent.com/20644209/28737151-c87976d8-73b2-11e7-9ed6-d1c62306c850.JPG)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

*Se crea un curso
*Se agrega mas de 50 usuario o profesores 
*No muestra completo la información

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4

**Comment by jmontoyaa** [comment]
Acabo de probarlo localmente y ahora si se ve correctamente la tabla con los usuarios.
El footer sigue siendo ancho pues hay muchos profesores.

**Comment by jmontoyaa** [comment]
![image](https://user-images.githubusercontent.com/158935/30377182-2413630e-988f-11e7-9a98-784a7530dd06.png)

**Comment by aqblanco** [comment]
He encontrado el mismo problema con el footer. En mi caso, la página principal aparece cortada, no pudiendo leerse los nombres de las herramientas de administración del curso.

**Comment by jmontoyaa** [comment]
Tratar de reproducir el error aqui:

https://11.chamilo.org/ (admin/admin)

**Comment by aqblanco** [comment]
Lo he probado en [este](https://11.chamilo.org/courses/DEMOCOURSE/) curso y pasa exactamente lo mismo, aunque al no tener dos apellidos la mayor parte de los usuarios usados como ejemplo, necesite añadir bastantes más de veinte para provocar el problema. Gracias y un saludo

**Comment by aragonc** [comment]
Ahora quedara con puntos suspensivos, si desean ver mas info sera dentro del propio curso.
![teachers_footer](https://user-images.githubusercontent.com/2940509/34385439-d664acee-eaf0-11e7-8ada-437a9bf42286.png)

**Comment by ywarnier** [comment]
Dentro de la lista de usuarios?
Porque el problema es que la lista de usuarios (la herramienta) no siempre está disponible para el alumno. No se podría hacer que cuando le des clic a un "[+]" se despliega y cuando le das clic de nuevo (en un [-] o algo) se vuelve a doblar?

**Comment by ywarnier** [comment]
@jmontoyaa Alex tiene un poco de dificultad con hacer el cambio sugerido en mi respuesta anterior. Podrías encargarte tu, porfa?

**Comment by ywarnier** [comment]
Bien, ahora fue corregido por @aragonc en e7f61cbff31fdf02b. Cierro
