### ISSUE TITLE
Bug de migration du 1.10.8 vers 1.11.4

### ISSUE THREAD

**Issue by amedlang** [chamilo/chamilo-lms#2094]
Les étapes de mise à jour se termine (sans problème) mais réellement  la base de données n'est pas mis à jour correctement.

Résultat : impossible d'accéder au cours (Lorsqu'on sélectionne un cours un page blanche qui s'affiche ).

**Comment by ywarnier** [comment]
Bonjour @amedlang, bien qu'ayant beaucoup de mal à les documenter (et ce rapport ne nous aide malheureusement pas du tout à le faire), nous savons que certaines structures ne sont pas bien mises à jour de la version 1.10 à la version 1.11. Nous savons comment éviter que cela ne se produise à nouveau de la 1.11 vers la 2.0, mais pour l'instant, et à moins de nous donner des exemples très spécifiques, nous ne pouvons pas faire grande chose qui n'implique pas des dizaines d'heures de travail (que les développeurs volontaires n'ont pas la possibilité de fournir pour l'instant).
2 solutions:
1) utiliser en ligne de commande `php bin/doctrine.php orm:schema-tool:update --dump-sql` pour voir quels changements de base de données sont manquants (plusieurs centaines peuvent apparaître, mais nombreux d'entre eux, si pas tous, sont des détails d'ordre de champs ou d'index accessoires qui doivent être détruits et recréés). On peut alors exécuter ces changements avec la même commande avec `--force` au lieu de `--dump-sql`
2) contacter l'un des fournisseurs officiels de Chamilo pour qu'ils puissent vous offrir le travail d'épluchage commercialement et prendre le temps de trouver et corriger les problèmes correspondants
