### ISSUE TITLE
Bug Chamilo 1.11.4 - Ejercicio con pregunta de Coincidencia Arrastrable

### ISSUE THREAD

**Issue by Dolespa** [chamilo/chamilo-lms#2095]
### Current behavior / Resultado actual / Résultat actuel
Si en un ejercicio tenemos alguna pregunta de Coincidencia Arrastrable, al realizarla, unimos cualquier opción con cualquier respuesta (para verificar el error es deseable unir con opciones incorrectas), la marcamos para Revisar y luego al volver a mostrarnos la pregunta (ya en la etapa final de revisión), en lugar de mostrar nuestras respuestas, muestra el ejercicio resuelto (con las respuestas correctas, definidas por el profesor).

### Expected behavior / Resultado esperado / Résultat attendu
Lo esperado es que al volver a revisar una pregunta de este tipo, nos muestre las selecciones hechas por el alumno, y no las respuestas correctas configuradas por el profesor.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1 - Crear dentro de un ejercicio una pregunta del tipo Coincidencia Arrastrable.
![imagen](https://user-images.githubusercontent.com/30670961/28896178-be838738-77b1-11e7-9841-60cf339fc73b.png)

2 - Realizar el ejercicio, y marcar cualquier pregunta con cualquier respuesta (es deseable, fines de comprobar el error, que las respuestas dadas sean incorrectas)
![imagen](https://user-images.githubusercontent.com/30670961/28896221-ea5dcf80-77b1-11e7-846e-470b84f5d7dc.png)

3 - Marcarla para revisar antes de finalizar
![imagen](https://user-images.githubusercontent.com/30670961/28896240-ff88a484-77b1-11e7-8fff-6c4c3fb5ed1e.png)

4 - Al volver a mostrarnos la pregunta para revisar (más allá de que las muestre en otro orden porque está con la opción mezclar habilitada), en lugar de mostrarnos lo seleccionada en el punto 3, nos muestra las respuestas correctas, es decir, el ejercicio con las respuestas como fueron configuradas y no con las opciones marcadas.

![imagen](https://user-images.githubusercontent.com/30670961/28896349-6b61c0c8-77b2-11e7-9786-c0fae4e3838b.png)

5 - Y luego en la corrección, ya como profesor, lo muestra obviamente como todo correcto

![imagen](https://user-images.githubusercontent.com/30670961/28896542-38f61624-77b3-11e7-9756-6719b17b7d94.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo Versión 1.11.4

![imagen](https://user-images.githubusercontent.com/30670961/28896552-432a8170-77b3-11e7-8759-4324b75943c5.png)

**Comment by nosolored** [comment]
Nosotros lo hemos probado en 11.chamilo.org y funciona correctamente
Se puede ver aqui: https://11.chamilo.org/main/exercise/overview.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=676

**Comment by ywarnier** [comment]
Gracias por la validación!
