### ISSUE TITLE
Mise à jour 1.9.10.2 ----> 1.11.4

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2096]
### Current behavior / Resultado actual / Résultat actuel
![echec](https://user-images.githubusercontent.com/24505996/28907951-215cbf4a-7821-11e7-8ef2-4d44a85a36b2.png)
Le processus de mise à jour s'arrête et j'ai le message suivant: 
"there is no column with name 'c_id' on table 'access_url_rel_course'
Quand je clique sur aller directement sur votre nouveau portail, je retourne sur la page d'installation 1.11.4 !
### Expected behavior / Resultado esperado / Résultat attendu
mise à jour de ma plateforme 1.9.10.2 vers 1.11.4
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
mise à jour décrite dans le manuel d'installation 1.11.4
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.9.10.2 et 1.11.4
apache 2
php 5.5.9
ubuntu 14.04

**Comment by ywarnier** [comment]
Bonjour, ce genre de cas peut se produire lorsque la mise à jour a été exécutée (entièrement ou partiellement) lors d'une tentative antérieure. La base de données se trouve alors dans un état qui n'est pas celui attendu par le code de mise à jour de Chamilo et il échoue.
Pour éviter ce genre de problème, il faut veiller à *supprimer complètement* la base de données en 1.9 et à restaurer la copie de sauvegarde d'avant toute tentative de migration. Ensuite seulement, tu pourras relancer la mise à jour et espérer un résultat positif.

Les logs (Apache, en général) de Chamilo donnent également des informations très utiles sur le processus et où il en est arrivé. Cela permet d'essayer de comprendre le problème initial et d'avancer à parir de là en corrigeant progressivement.

Cela dit, bien que nous recevions quelques rapports d'échecs, le système de migration fonctionne maintenant généralement assez bien.

**Comment by ywarnier** [comment]
Pas de feedback. Fermeture.
