### ISSUE TITLE
Bug des plugins "Ticket" et "Skype" après la migration du 1.10.8 vers 1.11.4

### ISSUE THREAD

**Issue by a-karoui** [chamilo/chamilo-lms#2098]
### Résultat actuel

Les plugins ne s'affiche pas dans "main/admin/settings.php?category=Plugins".

### Expected behavior / Resultado esperado / Résultat attendu

Affichage des "Plugins".
 
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Migration de la version 1.10.8 vers 1.11.4 
- Administration / Plugins 

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4

**Comment by ywarnier** [comment]
Les deux plugins ont été intégrés au coeur de Chamilo. Ils n'apparaissent donc plus dans la liste des plugins. Le système de migration de 1.10 à 1.11 devrait avoir altéré les tables comme il faut pour que les fonctionnalités de "ticket" soient accessibles depuis une entrée de la page d'administration, tandis que le champ additionnel pour skype apparaît maintenant automatiquement dans la  gestion des "champs de profil" et doit simplement être rendu visible et éditable pour l'utilisateur, pour couvrir la fonctionnalité telle qu'elle était offerte via le plugin skype.
