### ISSUE TITLE
Me sale error 403 al tratar de ver un documento en modo estudiante

### ISSUE THREAD

**Issue by mecavito** [chamilo/chamilo-lms#2103]
### Current behavior / Resultado actual / Résultat actuel

Se muy poco de programación, explico mi situación
Al pasar al modo estudiante y ver un documento sale error 403 de hostgator

![imagen](https://user-images.githubusercontent.com/18124431/29007637-10092982-7acd-11e7-996a-a75c6ac74a39.png)

### Expected behavior / Resultado esperado / Résultat attendu

Debería verse el documento, video, imágen o lo que se haya realizado

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. Paso a modo estudiante
2. Abre carpeta de documentos
3. Aparece error 403

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4

**Comment by jmontoyaa** [comment]
Es posible que sea un problema de permisos en la carpeta app/courses.
Revisar los error logs del servidor Apache.
Consultar con su proveedor de servicios.

**Comment by mecavito** [comment]
Ok reviso a ver si encuentro el problema

**Comment by mecavito** [comment]
Ya revisé, si aparece un tipo de permiso diferente, yo ya había cambiado este tipo de permiso en el area de permisos de chamilo, significa que cad vez que se cree un curso debo ir a cambiar el tipo de permiso?

**Comment by mecavito** [comment]
Cambié el tipo de permiso en la carpeta y aún así sigue saliendo el mismo error

**Comment by mecavito** [comment]
en servicio al cliente de hostgator me dicen que parece ser un error de reescritura del archivo .htaccess, y que no me pueden ayudar más

**Comment by ywarnier** [comment]
Hola @mecavito, el problema que reportas es problema de configuración del hosting. Puedes usar Instalatron o Softaculous para instalar tu portal Chamilo (ellos se encargan normalmente de los permisos) o sino contratar los servicios de algún proveedor oficial de Chamilo como BeezNest o Nosolored para tener un soporte especializado.
Nosotros tratamos problemas masivos de Chamilo que aparecen para varios usuarios, no los casos particulares de uno u otro, porque (lamentablemente) no tenemos la capacidad de asistir a cada uno de los usuarios de Chamilo gratuitamente. Este canal (Github) está reservado para bugs en el código de Chamilo, no problemas de configuración.

**Comment by mecavito** [comment]
Ok, mejor me cambio a moodle o claroline, muchas gracias

**Comment by ywarnier** [comment]
Perfecto, mucha suerte.
