### ISSUE TITLE
Vinculos rotos de fuentes

### ISSUE THREAD

**Issue by mecavito** [chamilo/chamilo-lms#2104]
### Current behavior / Resultado actual / Résultat actuel
![imagen](https://user-images.githubusercontent.com/18124431/29007652-92b32ff4-7acd-11e7-9fa3-ee806c618e67.png)

No muestra los símbolos de fuente (creo que son awesome)

### Expected behavior / Resultado esperado / Résultat attendu

Símbolos de la fuente

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

En cualquier lugar donde estén fuentes tipo fa - fa...

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4

**Comment by jmontoyaa** [comment]
Me parece que ya fue corregido.
Tratar de reproducir el error aquí:

https://11.chamilo.org/ (admin/admin)

**Comment by mecavito** [comment]
La plataforma está instalada en un servidor externo de hostgator

**Comment by ywarnier** [comment]
Tarea cerrada por imposibilidad de reproducir, obvio problema a nivel de permisos en el servidor y no cobertura del problema por el proveedor de hosting.
