### ISSUE TITLE
Fichier manquant main/img/course_progress_na.png

### ISSUE THREAD

**Issue by MrGabatt** [chamilo/chamilo-lms#2105]
### Current behavior / Resultado actual / Résultat actuel
Image manquante lors de l'affichage de la page du cours, quand l'affichage de la  "Progression du cours" est désactivé

### Expected behavior / Resultado esperado / Résultat attendu
L'image devrait s'afficher

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Mode SCG des icônes désactivé
- Afficher un cours / désactiver la progression du cours

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Le terme "cours" n'est pas très clair ici, de même que la notion de progression (il en existe plusieurs). Une petite capture d'écran?

**Comment by MrGabatt** [comment]
Exact. petite précision (et copies d'écran jointes) : réglage de la "vue page d'accueil" dans la configuration des cours en "vue activité".

<img width="983" alt="capture d ecran 2017-08-09 a 12 16 16" src="https://user-images.githubusercontent.com/27726274/29117085-2fd42f8c-7cfd-11e7-8a9c-b2ca702ea0ec.png">
<img width="595" alt="capture d ecran 2017-08-09 a 12 15 59" src="https://user-images.githubusercontent.com/27726274/29117086-2ff9058c-7cfd-11e7-84ee-c36cb4f37ba3.png">

**Comment by MrGabatt** [comment]
Le fichier 'main/img/course_progress_na.png' est absent de l'archive téléchargée (et de l'arborescence github).

**Comment by ywarnier** [comment]
J'ai ajouté #2107 comme corrolaire à ceci parce que ça m'a rappelé ce point "à faire".

En attendant, j'ai envoyé les (2) images manquantes en .gif:
![home-gifs](https://user-images.githubusercontent.com/609839/29126188-f5de4f76-7d1d-11e7-8650-66f6d269b819.png)

**Comment by MrGabatt** [comment]
Merci :)
