### ISSUE TITLE
Icône "Sujets" en mode SVG ne s'affiche pas

### ISSUE THREAD

**Issue by MrGabatt** [chamilo/chamilo-lms#2106]
### Current behavior / Resultado actual / Résultat actuel
L'icône "Sujets" (main/img/icons/svg/topics.svg) ne s'affiche pas dans la description du cours. Lors de l'affichage de l'image, l'erreur suivante s'affiche
"This page contains the following errors:

error on line 17 at column 33: Attribute viewBox redefined
Below is a rendering of the page up to the first error."

### Expected behavior / Resultado esperado / Résultat attendu
Il faut modifier le fichier main/img/icons/svg/topics.svg en supprimant la ligne 15
"viewBox="0 0 128 128" -> à supprimer

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Activer le mode SVG des icônes
Afficher le cours
Afficher la description du cours

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Fixed (will be part of 1.11.6). Thanks for reporting and submitting a solution!

**Comment by ywarnier** [comment]
On a side note, SVG support is not fully complete yet, so I wouldn't recommend using it on large-scale production portals, but you're very welcome to help us get there.
