### ISSUE TITLE
New user registration redirection page blank

### ISSUE THREAD

**Issue by alfadlah** [chamilo/chamilo-lms#2111]
Pls I need an urgent help now, I installed chamilo on my site and enabled users registration, but when ever a new user signup the information will be stored on my database but instead of redirecting user to welcome page after successful registration, the page will become blank

I think the problem should be from main/auth/inscription.php file

the version of my chamilo lms is chamilo 1.11.4

**Comment by ywarnier** [comment]
Hi @alfadlah, this is a community bug-reporting page. For urgent support, please contact one of the Chamilo official (commercial) providers: https://chamilo.org/providers

**Comment by GabrielaTepor** [comment]
Hi, @alfadlah, could you please let me know how you have solved this issue, please? I am getting the same and I did not find yet a resolution. Thanks a lot! Best regards, Gabriela
