### ISSUE TITLE
adresses non accessibles, création de répertoires impossible 

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2112]
### Current behavior / Resultado actual / Résultat actuel
1. Répertoires
Dans un cours, je peux créer des répertoires à partir de documents et y télécharger des fichiers.
Par contre, dans l'éditeur en ligne des parcours, il est impossible de créer des répertoires sauf dans "mes fichiers" :
![creation repertoire](https://user-images.githubusercontent.com/24505996/29239582-6118788a-7f52-11e7-92f5-8b54b8b2a274.png)
2. Problème de lecture des fichiers à cause des adresses : 
Si je veux qu'une video soit accessible, je dois rajouter dans l'editeur en ligne, devant l'adresse: http://localhost/chamilo-1.11/app
![adresse](https://user-images.githubusercontent.com/24505996/29239711-b3ac11b8-7f54-11e7-851d-e2ca5b858217.png)
Dans l'éditeur en ligne, si j'importe une vidéo dans "mes fichiers" et que je veux l'intégrer dans un cours, l'editeur en ligne met comme adresse : http://localhost/chamilo-1.11/app/........ et cela fonctionne.

### Expected behavior / Resultado esperado / Résultat attendu
Pouvoir créer des répertoires dans l'éditeur en ligne lors de la création des parcours et avoir les adresses, les liens qui fonctionnent 
### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo 1.11.x

**Comment by ywarnier** [comment]
@alexiye, il se peut que ceci ait été corrigé par le commit  4673586d6bb3cc159ac9f848b15ca07265430470 pour la #2231.
Pourrais-tu vérifier si c'est bien le cas?

**Comment by jmontoyaa** [comment]
Si votre URL est http://localhost/chamilo-1.11/

Il faut ajouter/modifier dans le fichier app/config/configuration.php
`
$_configuration['url_append'] = '/chamilo-1.11/';`

Par ailleurs, il n'est pas recommandé d'installer chamilo dans un dossier, il faudra utiliser un domain ou subdomain:

http://chamilo.net 
http://my.chamilo.net

**Comment by ywarnier** [comment]
"Par ailleurs, il n'est pas recommandé d'installer chamilo dans un dossier, il faudra utiliser un domain ou subdomain"
-> c'est préférable

**Comment by jmontoyaa** [comment]
See #2231
