### ISSUE TITLE
Error Instalación en jelastic (PaaS) "An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory"

### ISSUE THREAD

**Issue by betocustom** [chamilo/chamilo-lms#2117]
Estoy instalando chamilo en un servicio nube PaaS (jelastic), estoy usando el archivo chamilo-lms-1.11.4.tar.gz, el error salta en el paso 4...

### Current behavior / Resultado actual / Résultat actuel
Paso 4 de 6 – Parámetros de las bases de datos MySQL: Al dar clic al botón "comprobar conexión con la base de datos" me arroja el siguiente error y no se habilita el botón para seguir avanzando:

"La conexión con la base de datos ha fallado. Puede que el nombre de usuario, la contraseña o el prefijo de la base de datos sean incorrectos. Por favor, revise estos datos y vuelva a intentarlo.
An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory"

**Gracias de antemano por sus comentarios.**

**Comment by betocustom** [comment]
Otra prueba: Ahora indiqué 127.0.0.1 en lugar de localhost y el error cambió a:

La conexión con la base de datos ha fallado. Puede que el nombre de usuario, la contraseña o el prefijo de la base de datos sean incorrectos. Por favor, revise estos datos y vuelva a intentarlo.
An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused

**Comment by ywarnier** [comment]
Hola @betocustom, ambos mensajes de error son relacionados a la base de datos y no a Chamilo. Intenta isolar el problema del lado de la base de datos, conectándote con los mismos usuario y contraseña pero desde una aplicación de gestión de base de datos como phpMyAdmin o Adminer. Una vez que funcione en estos, ya podrás usar los mismos datos para Chamilo.

**Comment by betocustom** [comment]
hola @ywarnier , desde phpMyAdmin no tengo problemas para conectarme con las mismas credenciales.  Tal como comentas o es algún parámetro o configuración del ambiente o bd, o también podrían faltar considerar algo en el wizard de la instalación de chamilo, para este tipo de ambientes claro (PaaS). sigo intentando...

**Comment by ywarnier** [comment]
phpMyAdmin está instalado en el mismo servidor que Chamilo? El error `SQLSTATE[HY000] [2002] Connection refused` indica claramente que sí encuentra un servidor MySQL/MariaDB pero que la conexión quedó rechazada. Si los datos de conexión son los mismos entre ambos programas, quizás el servidor desde el cual se conectan sea distinto (es decir que la IP como vista *por* MySQL cambia) y eso en MySQL implica otros privilegios de usuario.

**Comment by betocustom** [comment]
Hola, si apache y mysql en este ambiente PaaS se genera cada uno con su ip distinta, lo que implicó dar privilegios al usuario chamilo@apache_ip, con eso ya logró conectar e instalar.
