### ISSUE TITLE
No me  crear nuevo curso

### ISSUE THREAD

**Issue by MarcoVanegas** [chamilo/chamilo-lms#2118]
(en https://campus.chamilo.org)

**Comment by MarcoVanegas** [comment]
![captura de pantalla de 2017-08-18 09-46-47](https://user-images.githubusercontent.com/31140920/29473243-a53561b2-841c-11e7-8fe5-ad622b17ca57.png)

**Comment by ywarnier** [comment]
Hola Marco, has creado tu cuenta como estudiante, lo cual no te permite crear cursos.
![estudiante](https://user-images.githubusercontent.com/609839/29486010-a735c63a-84dc-11e7-9a98-a41484c7e697.png)

Acabamos de cambiar tu cuenta a profesor. Ahora debería funcionar.
