### ISSUE TITLE
Error al subir imagen para marca de agua (Call to undefined function imagecreatefrompng())

### ISSUE THREAD

**Issue by betocustom** [chamilo/chamilo-lms#2119]
1.- Instalé chamilo 1.11.4 (usando el tar.gz), en la nube jelastic (servicio PaaS, MySQL 5.7.16, Apache 2.4.6-40, php 7.1)
2.- Luego de instalar fuí "AdministraciónParámetros de configuración de Chamilo". 
3.- Cargué una imagen para marca de agua, archivo png de 290x272px. (la misma que ya había cargado sin problema en otra instalación chamilo en un hosting compartido, cpanel).
4.- Al dar clic en "Guardar configuración" se genera el siguiente error:
Esta página no funciona

La página academia.jl.serv.net.mx no puede procesar esta solicitud ahora.
HTTP ERROR 500

**Luego verifiqué el archivo php_errors.log, en él se registró lo siguiente:**

[22-Aug-2017 13:59:11 UTC] PHP Fatal error: Uncaught Error: Call to undefined function imagecreatefrompng() in /var/www/webroot/ROOT/main/inc/lib/image.lib.php:314
Stack trace:
#0 /var/www/webroot/ROOT/main/inc/lib/image.lib.php(117): GDWrapper->set_image_wrapper()
#1 /var/www/webroot/ROOT/main/inc/lib/image.lib.php(293): ImageWrapper->__construct('/tmp/phpV9RjTS')
#2 /var/www/webroot/ROOT/main/inc/lib/image.lib.php(22): GDWrapper->__construct('/tmp/phpV9RjTS')
#3 /var/www/webroot/ROOT/main/inc/lib/pdf.lib.php(594): Image->__construct('/tmp/phpV9RjTS')
#4 /var/www/webroot/ROOT/main/admin/settings.php(225): PDF::upload_watermark('1_pdf_watermark...', '/tmp/phpV9RjTS')
#5 {main}
thrown in /var/www/webroot/ROOT/main/inc/lib/image.lib.php on line 314

Gracias por sus comentarios.

**Comment by ywarnier** [comment]
Parece que te falta la librería GD. Es sorprendente porque el instalador de Chamilo normalmente la solicita. A menos que hayas cambiado algo de configuración de PHP luego de instalar... no se.

El error `Call to undefined function imagecreatefrompng()` indica que no ha encontrado tal función. La función imagecreatefrompng() se encuentra en PHP 7 y es parte de la librería GD: http://php.net/imagecreatefrompng

**Comment by betocustom** [comment]
Estimado, recuerdo haber visto que no estaba GD (apareció en rojo cuando el asistenta verificó los requerimientos), pero como no sabía que podía afectar continué, además el asistente completa la instalación igual.
Según lo que dices se supone que si tengo php 7.1, ¿debería tener GD?...
Tendré que ver como instalar dicha librería en esta nube (uno ve un dashboard del ambiente donde se hacen ciertas cosas en el ambiente), no es que se entre directamente vía consola. :(

**Comment by betocustom** [comment]
Solucionado:
![image](https://user-images.githubusercontent.com/5564967/29588779-2dd661ca-8769-11e7-8ade-b0fe986561d9.png)

**Comment by ywarnier** [comment]
Cuidado con eso porque son varias, las extensiones necesarias para Chamilo, y si hace lo mismo con las demás, es probable que encuentres otros problemas similares ("Call to undefined function/method")

**Comment by ywarnier** [comment]
Y gracias por indicar la solución. Servirá para otros seguramente.
