### ISSUE TITLE
Bug de migration de 1.10.8 vers 1.11.4

### ISSUE THREAD

**Issue by a-karoui** [chamilo/chamilo-lms#2120]
La migration de la version 1.10.8 vers la version 1.11.4 se déroule normalement mais la base de données ne se met pas à jour correctement.

Il en résulte que lorsque l'on veut accèder aux cours, une page blanche s'affiche.

Fichiers de correction à considérer ci-joints.

[Version111.diff.gz](https://github.com/chamilo/chamilo-lms/files/1245728/Version111.diff.gz)
[Version20160706182000.diff.gz](https://github.com/chamilo/chamilo-lms/files/1245727/Version20160706182000.diff.gz)

**Comment by ywarnier** [comment]
Je n'ai pas encore révisé en détail mais selon les patches que tu envoies, il semblerait que ta base de données de 1.10.8 n'est pas tout à fait "pure". En d'autres mots, on dirait qu'une première tentative de migration a été exécutée avant, et qu'elle a laissé une partie des modifications.
Si une première tentative de migration échoue, pour une raison ou pour une autre, ce que nous recommandons généralement (c'est discutable, selon le contexte), c'est de *dropper* toute la base de données et la restaurer depuis un dump antérieur à la première tentative de migration.
Je pense que dans ce cas tu n'aurais pas les erreurs que tu rapportes. Cela dit, modifier un CREATE TABLE avec un IF NOT EXISTS n'est généralement pas un problème. Je laisse donc l'issue ouverte.

**Comment by a-karoui** [comment]
Bonjour,
Le "IF NOT EXISTS" est effectivement une petite amélioration qui nous a évité des réinstallations de la base 1.10.8 lors du débogage.
En revanche, les patchs contiennent également les corrections des bugs de migration.
Par exemple "course_rel_user_catalogue" n'existe pas dans le fichier "Version111.php" et est nécessaire, ou alors il faut executer le fichier "Version20160706182000.php" avant le fichier "Version111.php" sinon la migration n'aboutit pas.
	$this->addSql(
+             'CREATE TABLE IF NOT EXISTS course_rel_user_catalogue (id int NOT NULL AUTO_INCREMENT, user_id int DEFAULT NULL, c_id int DEFAULT NULL, visible int NOT NULL, PRIMARY KEY (id), KEY (user_id), KEY (c_id), CONSTRAINT FOREIGN KEY (c_id) REFERENCES course (id) ON DELETE CASCADE, CONSTRAINT FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;'
+        );
+		
         if ($schema->hasTable('course_rel_user_catalogue')) {
             $table = $schema->getTable('course_rel_user_catalogue');
 
@@ -506,7 +524,7 @@
                 $this->addSql('ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT FK_79CA412E91D79BD3 FOREIGN KEY (c_id) REFERENCES course (id);');
             }
         }
Merci de relire les patchs pour intégrer la correction des bugs existants.
Cordialement,

**Comment by ywarnier** [comment]
OK, ce sera fait, merci!

**Comment by a-karoui** [comment]
Ok ça marche, il fonctionne bien maintenant merci.
