### ISSUE TITLE
Chamilo No envía emails

### ISSUE THREAD

**Issue by betocustom** [chamilo/chamilo-lms#2121]
Hola, resulta que estoy "testeando" la mejor plataforma para mi despliegue de chamilo, un "hosting compartido" vs una "nube" (jelastic - PaaS).
Al instalar en mi hosting vía cpanel/softaculous chamilo empezó a enviar emails inmediatamente una vez instalado sin yo configurar nada, claro es el hosting de mi dominio y al admin le puse una cuenta de mi dominio al instalar así que era "esperable". El tema es que en la "nube" hice lo mismo al instalar, le puse la misma cuenta de mi dominio al admin pero al estar un servidor de esta nube distinto al host de mi dominio no esperaba que enviara los emails, bueno... no envía nada.
Busqué por ahí y encontré donde creí que había que configurar, archivo /var/www/webroot/ROOT/app/config/mail.conf.php
En él puse mi smtp:
$platform_email['SMTP_HOST'] = 'mi smtp';
$platform_email['SMTP_USER'] = 'mi cuenta';
$platform_email['SMTP_PASS'] = 'mi pass';

Aun así no envía emails, ví los log de apache y php y no hay ningún error relacionado al envío fallido de emails, sigo buscando pero por ahora no se que más hacer.
Se agradecen los comentarios!.

**Comment by jmontoyaa** [comment]
Tal vez falta esto;

platform_email['SMTP_MAILER'] = 'smtp'; // mail, sendmail or smtp (Windows probably only supports smtp)

**Comment by betocustom** [comment]
Exacto @jmontoyaa , no había visto esa línea decía 'mail', lo cambié a 'smtp' y me empezó a registrar este error:

[25-Aug-2017 15:53:11 UTC] ERROR: mail not sent to alberto (super2t@hotmail.com) because of SMTP Error: The following recipients failed: super2t@hotmail.com<p>SMTP server error: 5.7.1 <super2t@hotmail.com>: Relay access denied

Entonces vi que en esta línea tenía un 0: $platform_email['SMTP_AUTH'] = 0; 
Así que cambié a 1 y el error desapareció, pero ahora me aparece este otro error y volví a quedar detenido nuevamente:
[25-Aug-2017 15:56:56 UTC] ERROR: mail not sent to super 2t (super2t@hotmail.com) **because of Language string failed to load: tls**<p>SMTP server error:

Este es el archivo completo:
![image](https://user-images.githubusercontent.com/5564967/29721941-469638e2-8995-11e7-8e5d-608e1570c7f3.png)

Gracias por la ayuda!

**Comment by ywarnier** [comment]
@betocustom este problema es un problema específico a tu configuración. Los correos de Chamilo funcionan en muchos casos comprobados (incluyendo en Amazon Web Services), por lo que no podemos dedicarle mucho tiempo a revisar este caso. Dejo la tarea abierta por si deseas publicar la solución una vez encontrada, pero por razones de prioridades no podremos acompañarte en la resolución (en un plazo razonable, por lo menos).

**Comment by betocustom** [comment]
Hola @ywarnier , si está claro que Chamilo envía mails (no tengo problema en otra instalación en un hosting compartido), y como dices es problema en mi ambiente.
Dejaré el tema abierto para publicar la solución si es que la encuentro y así ayudar a quienes tengan el mismo problema. 
Entiendo que no pueden dedicar tiempo a ayudarme en esto, espero solucionarlo pronto, ya que sería lamentable abandonar chamilo por no lograr configurarlo en este ambiente (PaaS).

**Comment by ywarnier** [comment]
Todavía puedes dejar un comentario aun con la tarea cerrada, así que voy cerrando (porque parece que estuviste ocupado con otras cosas :smile: )

**Comment by EthicalHackingCOP** [comment]
Hola a tod@s. 

En que archivo puedo modificar el cuerpo del correo que se envía? por ejemplo al registrar un usuario .

**Comment by ywarnier** [comment]
@EthicalHackingCOP el cuerpo de los correos se define como variables de idioma, las mismas que se definen en main/lang/spanish/trad4all.inc.php.
Modificar estos archivos directamente es una mala práctica, no obstante, porque son sobreescritos a cada actualización de Chamilo. Para evitar el problema, te recomiendo usar sub-idiomas. Para entender el mecanismo, busca la sección sub-idiomas aquí: https://docs.chamilo.org/es/admin/unidad_administrador/administracion_de_la_plataforma.html

**Comment by EthicalHackingCOP** [comment]
Mil gracias ywarnier :D

**Comment by NicoDucou** [comment]
@xini32 Para la ocnfiguracion del envio de correo puede ver la documentacion aqui  : https://docs.chamilo.org/es/admin/apendice/preguntas_frecuentes.html

**Comment by xinita23** [comment]
coloque mi chamilo a una web pero sigue sin enviar mail

**Comment by vjdenis** [comment]
Hola!,
una consulta, quiero hacer que el correo de bienvenida ( el que envia cuando un usuario se registra) no aparezca mi nombre y apellido, sino que salga un: área de comunicación. y en lo posible en vez de salir de mi correo que salga desde el de no responder.
intente modificar main/lang/spanish/trad4all.inc.php.  borrando en la linea 851 \n\nAtentamente:\n((admin_name)) ((admin_surname)).";  y al probar registrar a alguien denuevo le sigue el correo llegando con los datos.
Como se podría realizar? ya que la idea es que la plataforma no me presente a mi sino al área
gracias de antemano

**Comment by ywarnier** [comment]
Normalmente muestra ahí los datos que tu registraste en la configuración de la plataforma. Puedes ir en "Parámetros de configuración" y los primeros parámetros que encuentras ahí deberían decir el nombre/apellido que ves aparecer en el correo. Remplázalos ahí y debería funcionar para el correo.

Y también... mejor no agregues mensajes a tareas cerradas. Mejor abres otra nueva y pones una referencia a esta.

**Comment by R0sy** [comment]
Buen día yo tengo el mismo problema cuando agrego un usuario nuevo o quiero reenviar su acceso o se envían anuncios no les llegan a sus correos electrónicos, como lograron resolver el problema, la versión de la plataforma es: 1.11.12, y esta actualmente montada en un servidor de Amazon. 

De antemano gracias por su atención.
