### ISSUE TITLE
Add global option to enable quiz edition if included in LP

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2122]
### Current behavior

If a quiz is included in a learning path, it cannot be edited (or at least questions cannot be edited).

### Expected behavior

If the portal admin really wants to act crazy and allow teachers to modify their quizzes against all integrity principles, let him do so.
Create an additional variable:
```
$_configuration['quiz_allow_edit_although_embedded'] = false;
```
and use it to go against the current lock in exercises.

### Chamilo Version

1.11.4+

**Comment by NicoDucou** [comment]
This has already been done but not with the same variable name. Do we leave it as it is or does it need to be modify to use the correct variable ?

```
// If true exercises added in LP can be modified.
//$_configuration['force_edit_exercise_in_lp'] = false;

```

**Comment by ywarnier** [comment]
Leave it as is :-)
