### ISSUE TITLE
Please update trad4all Brazilian from translate.chamilo.org

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2123]
### Current behavior / Resultado actual / Résultat actuel
Some blank translations strings. Some errors in strings.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6 dev

I'd filled some new blank strings on translate.chamillo.org and fixed for example "none" which was "nome" ("name" in english) by the correct "nenhum".

**Comment by marshel** [comment]
there are some strings with blank "english"  translations as well, please complete them so I can also fill brazilian.

**Comment by jmontoyaa** [comment]
I just updated the variables based in translate.chamilo.org:

https://github.com/chamilo/chamilo-lms/commit/8c2a184d2e3ac444d80f08cabb23a28a22ade5e8

**Comment by marshel** [comment]
I will keep the fixes and cleanup when possible and warn you when I'd made a bunch of changes.

best regards.
