### ISSUE TITLE
Are users allowed to delete questions attempts by ajax or browser manipulation?

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2124]
I got a course ongoing, on the lp there is a exercise inside with 10 random questions with random answers.

I became in doubt on seeing the important activities list on https://www.....r/main/admin/statistics/index.php?report=activities .

There it showed some qst_attempt_deleted | exercise_a_q_id

![2017-08-31 11_08_22-estatisticas](https://user-images.githubusercontent.com/1764993/29927457-d24358ba-8e3c-11e7-82d2-aa4d4e12af18.png)
(there are more lines...)

on this file there is the code: chamilo-lms/main/inc/ajax/exercise.ajax.php

```
 // Deleting old attempt
                if (isset($attempt_list) && !empty($attempt_list[$my_question_id])) {
                    if ($debug) {
                        error_log("delete_attempt  exe_id : $exe_id, my_question_id: $my_question_id");
                    }
                    Event::delete_attempt(
                        $exe_id,
                        api_get_user_id(),
                        $course_id,
                        $session_id,
                        $my_question_id
                    );

```

So, Am I mistaken and the users are deleting its wrong attempts someway or,
they are just returning to a previous question and changing the value?

If it is the second, should the error log contain this strings ( qst_attempt_deleted | exercise_a_q_id) ? should not be better to change this?

If this is really a cheat attempt, should not be better to the  Event::delete_attempt check if the user is a teacher or admin?

**Comment by jmontoyaa** [comment]
Is not a cheat attempt. In some cases when teacher edits the exercise and remove some questions, but the student already tried the exam (but didn't finish) then some attempts will be removed because they are not present any more in the question list.

**Comment by marshel** [comment]
As the exercise is on a LP, it can't be edited. So the doubts remains.

**Comment by mcastillogt** [comment]
I have the same problem, I need to know the reason this event loads, because, I have a  problem with an exam, I need help.

**Comment by ywarnier** [comment]
Closing a very old issue here.
The confusion, I believe, was that the attempt was deleted, not the question or exercise itself, and that is allowed if the exercise is in a learning path.
