### ISSUE TITLE
No se ve la pagina principal del curso en chamilo

### ISSUE THREAD

**Issue by ftello** [chamilo/chamilo-lms#2126]
Hola, tengo un problema, cuando creo un curso en chamilo, se crea correctamente, pero al momento de dar click en el curso creado para ir a la pagina principal de esté, aparece la siguiente pagina con este mensaje:

"¡Enhorabuena, ha instalado satisfactoriamente su portal de e-learning!
Ahora puede completar la instalación siguiendo tres sencillos pasos:
Configure el portal: vaya a la sección de Administración de la plataforma, y seleccione Plataforma -> Parámetros de configuración de Chamilo.
De vida a su portal con la creación de usuarios y cursos. Puede hacerlo invitando a otros usuarios a crear su cuenta, o creándolas usted mismo a través de las secciones de usuarios y cursos de la página de adminstración.
Edite esta página a través de la entrada Configuración de la página principal en la sección de administración.
Siempre podrá encontrar más información sobre de este software en nuestro sitio web: http://www.chamilo.org.

Diviértase, no dude en unirse a la comunidad y denos su opinión a través de nuestro foro."

Y no puedo ver el contenido del curso ni nada parecido, sea como estudiante o profesor
la versión de Chamilo que se probo fue:   1.11.2   y   1.11.4

Porfa alguien ayudeme. Gracias.
![captura](https://user-images.githubusercontent.com/31607029/30011016-e939d61a-90f9-11e7-9624-5744c2902117.JPG)

**Comment by ywarnier** [comment]
Parece un error de redirecciones. En Chamilo 1.11.4, es muy importante autorizar la interpretación del archivo .htaccess. El manual de instalación de Chamilo (carpeta /documentation/installation_guide.html) lo especifica claramente.
Si usas Nginx, necesitas modificar la configuración de tu vhost (también el manual de instalación te da la configuración específica).

**Comment by ywarnier** [comment]
Sin respuesta del usuario en 3 meses. Cerrando.
