### ISSUE TITLE
Function mcrypt_module_open() is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2127]
### Current behavior / Resultado actual / Résultat actuel
When installing appear this messages about `ircmaxell/RandomLib` library
This was filed in ircmaxell/RandomLib#55

```
Deprecated: Function mcrypt_module_open() is deprecated in /var/www/chamilo111x/vendor/ircmaxell/random-lib/lib/RandomLib/AbstractMcryptMixer.php on line 75
```

### Expected behavior / Resultado esperado / Résultat attendu
Don't see E_NOTICE

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Install PHP 7.1
Start Chamilo installer

### Chamilo Version / Versión de Chamilo / Version de Chamilo
v1.11.6 dev

**Comment by jmontoyaa** [comment]
I cannot reproduce this error. I have also PHP 7.1 and I don't have any PHP notice or warning.

**Comment by ywarnier** [comment]
@AngelFQC can you still reproduce it?

**Comment by jmontoyaa** [comment]
I tried again with:

PHP 7.1.12-2+ubuntu17.10.1+deb.sury.org+2 (cli) (built: Dec  7 2017 20:13:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group

In: main/install/index.php

I don't have any errors. Closing for lack of feedback.

**Comment by AngelFQC** [comment]
I'm the only one with this problem
https://screenshots.firefox.com/2edJNIaGB5y2y3yA/chamilo111x.dev

`PHP Version 7.1.12-1+ubuntu16.04.1+deb.sury.org+1`

**Comment by ywarnier** [comment]
I have the same issue with libapache2-mod-php7.1                      7.1.11-1+ubuntu17.04.1+deb.sury.org+1.
I've changed composer.json to rely on alternative paragonie/random-lib as suggested in https://github.com/ircmaxell/RandomLib/issues/55#issuecomment-334613476  (referenced by @AngelFQC)
