### ISSUE TITLE
Outil Annonce : Fatal error

### ISSUE THREAD

**Issue by dguenard** [chamilo/chamilo-lms#2129]
### Current behavior / Resultado actual / Résultat actuel
Fatal error: Uncaught exception 'Doctrine\DBAL\Types\ConversionException' with message 'Could not convert database value "" to Doctrine Type array' in /DATA/cham-web/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:46 Stack trace: #0 /DATA/cham-web/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ArrayType.php(60): Doctrine\DBAL\Types\ConversionException::conversionFailed('', 'array') #1 /DATA/cham-web/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(131): Doctrine\DBAL\Types\ArrayType->convertToPHPValue('', Object(Doctrine\DBAL\Platforms\MySqlPlatform)) #2 /DATA/cham-web/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php(69): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateRowData(Array, Array) #3 /DATA/cham-web/www/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(147): Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator->hydrateAllData() #4 /DATA/cham-web/www/vendor/doctrine/orm/lib/Doc in /DATA/cham-web/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php on line 46
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Envoie d'une annonce a beaucoup d'utilisateur (supérieur à 150)
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.2

**Comment by NicoDucou** [comment]
Je viens de tester ici https://11.chamilo.org/main/announcements/announcements.php?cidReq=200STUDENTS&id_session=0&gidReq=0&gradebook=0&origin=&action=view&id=55 et tout a fonctionné correctement.

Merci de tester sur la plateforme de test 11.chamilo.org pour reproduire le problème ou de confirmer que le problème est corrigé dans la nouvelle version de Chamilo.

Sinon nous fermerons cette tâche prochainement.
