### ISSUE TITLE
Problema de instalacion

### ISSUE THREAD

**Issue by wearelife** [chamilo/chamilo-lms#2130]
Hola, estoy teniendo problemas para instalar chamilo.
Estoy utilizando WampServer Version 3.0.6 64bit (Apache 2.4.23 - PHP 7.0.10 - MySQL 5.7.14
PHP 5.6.25 for CLI (Command-Line Interface) )
Relicé la descarga del zip,lo descomprimí en la carpeta correspondiente y cuando quise instalarlo a través del navegador me tira error en el paso 7 
el error dice: 

Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded. in C:\wamp64\www\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54

Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded. in C:\wamp64\www\chamilo-lms-1.11.4\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54

Alguien podría ayudarme por favor?

**Comment by marshel** [comment]
Estás a utilisar el código del Github o el ZIP disponible en el sitio?

Una cosa que puedes hacer és executar lo "composer update". 
No lo sé, pero lhe digo que creo que acá é un local mas adecuado para desenvolvimiento qué soporte donde el forum pode adecuarse en esto: https://chamilo.org/forum/.

"perdoname por mi español."

**Comment by ywarnier** [comment]
@wearelife hay un parche conocido para la 1.11.4 bajo Windows.
Hay que remplazar el archivo main/inc/lib/database.lib.php por este: https://raw.githubusercontent.com/chamilo/chamilo-lms/9388119a8c1826098579f6711be19c9922536d14/main/inc/lib/database.lib.php
Estará arreglado en la 1.11.6. Esto solo afecta la 1.11.4 y solo bajo Windows :-/

**Comment by ywarnier** [comment]
El problema (y otro más que ya no debería afectarte) está descrito en inglés en el issue #1997
