### ISSUE TITLE
please run letsencrypt updates as cron

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2132]
https://1.11.chamilo.org/ uses LE with a certificate that is outdated since July.

Chrome browser refuses to open.

Thanks

**Comment by nosolored** [comment]
Try it in https://11.chamilo.org/

**Comment by lonesomewalker** [comment]
This certificate is not trusted in my mobile phone (Android, latest Chrome)...

**Comment by ywarnier** [comment]
The current one from 11.chamilo.org? This is the same wildcard as https://chamilo.org!

**Comment by lonesomewalker** [comment]
I was traveling with Deutsche Bahn, and as it looks, they do SSL interception... Nasty one :-1: 

But this means, there should be a redirect from 1.11.chamilo.org to 11.chamilo.org since there are many references to the first one out there...

**Comment by ywarnier** [comment]
There is, only that we don't have a certificate for 1.11.chamilo.org, so redirection works in http, not in https. Honestly I don't have the time to deal with this. Letsencrypt only works in a limited number of server configs, and it doesn't here. It means hours and hours of work. 11.chamilo.org is only a test platform. Developers asking about it will get the right answer. Other people shouldn't need it.

**Comment by ywarnier** [comment]
> Honestly I don't have the time to deal with this
Better said: there are better uses of my time that would benefit the Chamilo project than looking into this.
