### ISSUE TITLE
Impossible to embbed videos in courses' description

### ISSUE THREAD

**Issue by fxguenan** [chamilo/chamilo-lms#2133]
### Current behavior / Resultado actual / Résultat actuel
There's an error message : "Your browser doesn't support video.
Please download the file: video/mp4 video/mp4"

### Expected behavior / Resultado esperado / Résultat attendu
Video should be embbeded

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Go to https://11.chamilo.org then insert video in any courses' description

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.10.x to 1.11.x

![image](https://user-images.githubusercontent.com/31760339/30201348-c11f267e-947a-11e7-9d2c-54503120ad42.png)

**Comment by jmontoyaa** [comment]
Works for me using latest Firefox:

https://11.chamilo.org/main/document/showinframes.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=&id=9063

See:

https://screenshots.firefox.com/8tNzy7GrGxIcNHAU/11.chamilo.org

**Comment by fxguenan** [comment]
Hello and thank you for your answer,

What you've done there is creating a document and then embed a video, which works OK for me.

The thing I'm trying to do, is to embed a video straight in the course description : https://11.chamilo.org/main/course_description/?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=

Try to edit and insert a video there to reproduce the bug.

Sincerely,

**Comment by jmontoyaa** [comment]
I added some other fixes:

https://github.com/chamilo/chamilo-lms/commit/805b0aa5d67233d8e6ccc555e91c595a82c048f9

**Comment by jmontoyaa** [comment]
It's working now with my mp4 example here:

https://11.chamilo.org/main/course_description/index.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=&

**Comment by kahuitel** [comment]
Thank you very very (...) very much. Problem solved by replacing patched files.

Regards,
