### ISSUE TITLE
Change HTML icons

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2134]
The HTML icons are different:

https://11.chamilo.org/main/img/icons/22/file_html.png

https://11.chamilo.org/main/img/icons/64/file_html.png

I guess the "64" version should be the correct one.

**Comment by ywarnier** [comment]
We can probably have something more sexy than the current 64 version (although not as commercial as the 22 version)

**Comment by aragonc** [comment]
Enviado quedaria asi.

![filehtml](https://user-images.githubusercontent.com/2940509/31287758-00c273ee-aa88-11e7-97f6-522b0e571707.png)
