### ISSUE TITLE
Database - Table 'legal'

### ISSUE THREAD

**Issue by dauzeine** [chamilo/chamilo-lms#2137]
After migrating from 1.9.x to 1.11.2 (see other issue...), I did a:

php bin/doctrine.php orm:schema-tool:update --dump-sql  

in the root of my chamilo.
It said:
 There is no column with name 'id' on table 'legal'.

I check here: https://support.chamilo.org/attachments/download/5481/chamilo-110-db.png

And there is no column 'Id' in 'legal'. This column is present almost in every table. I don't know if it's a bug or not...

David

**Comment by jmontoyaa** [comment]
It's better to make the migration with the latest 1.11.4 or even better with the latest code in the 1.11.x branch.
"legal" should have the "id" field.

**Comment by dauzeine** [comment]
Thx,
I'm making a new upgrade with the latest code...

**Comment by ywarnier** [comment]
@dauzeine nice to see you around

**Comment by dauzeine** [comment]
Long time! I'll try to be active on the forum...

**Comment by ywarnier** [comment]
Yes, that would be great. The forum needs some love in English and French and we've all been pretty busy growing the software.
