### ISSUE TITLE
Recommend PHP 7 in documentation

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2139]
In: https://11.chamilo.org/documentation/installation_guide.html#1._Pre-requisites

We should recommend PHP 7.0 or even better PHP 7.1
The minimun version should still be PHP 5.5

**Comment by lonesomewalker** [comment]
Better NOT recommending PHP 5.5 since there are dependencies which are not met...
Had this already in an issue here.
At least, the support for PHP 5.6 is alive, 5.5. is outdated.

**Comment by ywarnier** [comment]
@lonesomewalker could you point me to what dependencies do not allow for PHP 5.5?

**Comment by ywarnier** [comment]
@jmontoyaa OK to recommend PHP 7.1 and leave the minimum requirement until @lonesomewalker explains. Please update other languages as well.

**Comment by lonesomewalker** [comment]
We had 2 packages in the vendor folder which did not run smooth with PHP 5.5.
(threw some stuff in error log)

But i didn't write them down, better upgraded the customer to PHP 7.
Should i have a look? PHP 5.5 is EOL.

**Comment by jmontoyaa** [comment]
Maybe we should improve the documentation and add 2 blocks
"Minimum requirements" (PHP 5.5) and "Recommended requirements" (PHP 7.1)

**Comment by ywarnier** [comment]
It seems like a table would be the right direction to go. Like in the installer between "current" and "recommended".

| Dependencies | Minimum version required | Recommended |
| PHP | 5.5 | 7.1 |
| MySQL/MariaDB | 5.1 | 5.6/10.2 |
