### ISSUE TITLE
Adding courses to classes shows duplicate entries

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2142]
### Current behavior / Resultado actual / Résultat actuel
When adding courses to a class, also added courses are shown on the left side (courses on the platform).
You can also remove courses from classes back to the platform, so there will be duplicate entries in the left side.

### Expected behavior / Resultado esperado / Résultat attendu
Courses which are already attached to a class should be filtered out.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
https://11.chamilo.org/main/admin/add_courses_to_usergroup.php?id=9

### Chamilo Version / Versión de Chamilo / Version de Chamilo
latest

**Comment by ywarnier** [comment]
No user feedback in almost 3 months. Patch provided. Assuming this is solved.
