### ISSUE TITLE
Page in page

### ISSUE THREAD

**Issue by nielsarts** [chamilo/chamilo-lms#2143]
### Chamilo Version / Versión de Chamilo / Version de Chamilo

![image](https://user-images.githubusercontent.com/31060548/30376620-5aeec834-988d-11e7-8b84-4d6e22343a09.png)

after a few minutes chamilo signs out. when I clicked on sign in again. the website opened the page in the current page

**Comment by jmontoyaa** [comment]
You should check if your apache server is reading correctly the htaccess file.

https://11.chamilo.org/documentation/installation_guide.html#16._Rewrite

**Comment by ywarnier** [comment]
No user feedback after roughly 80 days. Closing.
