### ISSUE TITLE
Course catalog block with many teachers breaks UI

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2144]
See the image:

![image](https://user-images.githubusercontent.com/158935/30480409-dfdff210-9a19-11e7-99df-54452fdfa2bd.png)

Or see here:

https://11.chamilo.org/main/auth/courses.php

**Comment by aragonc** [comment]
Ahora se vera así cuando el número de profesores exeda de 6 personas.

![lista](https://user-images.githubusercontent.com/2940509/31299415-e3b0e958-aab3-11e7-8a48-875ffe0971a9.png)

**Comment by jmontoyaa** [comment]
Se ve bien pero he actualizado 11.chamilo y mi instalación local, pero no funciona.

**Comment by aragonc** [comment]
En mi local se ve bien, borraste el cache del twig?

**Comment by aragonc** [comment]
![02](https://user-images.githubusercontent.com/2940509/31349563-5d76de00-ace9-11e7-9634-6e6d4f97c2fd.png)

**Comment by jmontoyaa** [comment]
He hecho el merge. Y funciona. Pero el error aparece tambien en hot courses:
Ver:

https://11.chamilo.org/

**Comment by aragonc** [comment]
![hot_course](https://user-images.githubusercontent.com/2940509/31397814-994f9e08-adac-11e7-9a1c-2eeb4ac64f62.png)

Corregido en Hot Course

**Comment by aragonc** [comment]
Ya aplique los cambios en el repositorio principal

**Comment by jmontoyaa** [comment]
Funciona bien :+1:
