### ISSUE TITLE
New courses are not created

### ISSUE THREAD

**Issue by triquetrix** [chamilo/chamilo-lms#2151]
I fill in the form in order to create a new course, but when I submit it the page is reloaded and nothing happens.

No errors, no new folder, nothing.

I use Chamilo 1.11.4 fresh installed from scratch.

**Comment by ywarnier** [comment]
Hi @triquetrix, we need to see what appears in your web server (Apache?) logs. Can you provide them? Do you have access (/var/log/apache2/[something]error_log, error-logs or something like that, depending on what you use as a hosting solution)

**Comment by rojas9112** [comment]
Hola estimados buenas tardes, tengo el siguiente problema en un servidor windows server 2012 R2, al momento de crear un curso, dejo el vídeo del problema. https://www.youtube.com/watch?v=kStPY755hLU , espero puedan ayudarme a solucionarlo

**Comment by ywarnier** [comment]
@rojas9112 gracias por no reportar dentro del mismo reporte que otra persona, esto hace mucho más complicado seguirlo todo. En tu caso, necesitas referirte al manual de instalación (https://11.chamilo.org/documentation/installation_guide_es_ES.html) en particular sobre la sección relativa a la configuración de redirecciones de Apache y el soporte de archivos .htaccess.

**Comment by ywarnier** [comment]
No answer received from @triquetrix in about 2 months. Closing.
