### ISSUE TITLE
Anonymous users can send messages to teachers in popular courses block

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2152]
### Current behavior
In the popular courses block, as anonymous user, when teachers appear, their name can be clicked and an internal message can be sent to them.

### Expected behavior
Anonymous users shouldn't be authorized to send messages to any platform user. They need to register first.

### Steps to reproduce
Enable popular courses block
Create an open course
Assign a teacher
Logout
Check homepage
Click the teacher link/picture
![link-on-trainer](https://user-images.githubusercontent.com/609839/30661115-40247f60-9e43-11e7-847b-253e192adcc7.png)

A message box appears. Send a message. A confirmation message appears ("Sent!")

### Chamilo Version
1.11.x 2017/09/20

**Comment by jmontoyaa** [comment]
I think this was already fixed. 
I can't reproduce the error here:

https://11.chamilo.org/

**Comment by ywarnier** [comment]
Might be. I was looking at it on a 1.11.4 I think. Thanks and sorry for the noise.
