### ISSUE TITLE
File missing file_zip.png

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2153]
/main/img/file_zip.png
/main/img/icons/22/file_zip.png

**Comment by aragonc** [comment]
Se cierra?

**Comment by jmontoyaa** [comment]
No, ese zip es bien pequeno y feo lo puse de emergencia. Normalmente era una caja asi:

https://11.chamilo.org/main/img/file_zip.gif

Falta agregar las otras tallas tambien 32, 64, etc.

**Comment by aragonc** [comment]
![file](https://user-images.githubusercontent.com/2940509/31286666-8912a77c-aa84-11e7-80de-0d3ab5b02fec.png)
Listo ahora queda así...
