### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by ptcampinspvg** [chamilo/chamilo-lms#2154]
Se recibe un error 500 al ejecutar funciones en la base de datos, en concreto creemos que sucede en la función **$em->flush()** . La plataforma se ha actualizado desde la versión 1.9 a la 1.11.4 sin problema. Después de dicha actualización empezamos a tener el problema. Los archivos se reflejan en el FTP pero no en la plataforma.

### Current behavior / Resultado actual / Résultat actuel
Cuando se sube un documento (también pasa con certificados) se recibe un error 500.

### Expected behavior / Resultado esperado / Résultat attendu
Subir archivos y actualizar la base de adtos correctamente.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Subir un archivo o crear archivo en la plataforma.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
Indicar el mensaje que aparece en los error logs de Apache.

**Comment by ptcampinspvg** [comment]
[Mon Sep 18 16:26:46.617496 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.phtml, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.617227 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.jsp, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.617145 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.cgi, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.616906 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.pl, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.616746 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.php3, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.616666 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.php4, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.616586 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.php5, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es
[Mon Sep 18 16:26:46.616462 2017] [access_compat:error] [pid 5309:tid 140329485289216] [client 80.24.144.182:53739] AH01797: client denied by server configuration: /home/privileg/public_html/chamillo/app/upload/users/1/1/my_files/index.php, referer: http://www.instruccion.privilegestyle.com/main/inc/lib/elfinder/filemanager.php?cidReq=SMS03&id_session=0&gidReq=0&gradebook=1&origin=&CKEditor=content&CKEditorFuncNum=0&langCode=es

This is our last Error Log.

**Comment by ptcampinspvg** [comment]
Creo que los errores en el log que podemos acceder por cPanel no se corresponden con el error que tenemos. 
Hemos comprobado que si eliminamos **$em->flush()** la plataforma no devuelve dicho error. 

Puede ser por la falta del paquete APCU ??

**Comment by ywarnier** [comment]
La falta de APCU no debería generar problemas (lo contrario quizás, pero la falta no).
$em es el Entity Manager de Doctrine (layer Object-Relational-Mapping para consultas a la base de datos) y flush() es el método que escribe la info del objeto en la base de datos, por lo que si lo eliminas, probablemente te estés perdiendo de algo que tiene que ser inscrito en la base de datos.

Efectivamente, los logs no parecen reflejar el problema que estáis teniendo. Un error HTTP 500, en general, indica simplemente que el servidor encontró un error y no te puede mostrar el error mismo (por distintas configuraciones que pueden existir). Si tenéis este hosting con algun proveedor con soporte, quizás ellos puedan ayudar con una inspección del problema?
Como se relaciona con el $em->flush(), yo diría que parece ser algun problema con un query SQL. En este caso, el log de Apache debería registrar el error.

Otra forma de obtener el error (que *puede* funcionar dependiendo de otras configuraciones) es pasar el portal en modo de desarrollo. Esto se hace en la primera página de parámetros de configuración, el octavo parametro o algo así. Después de haber pasado en modo de desarrollo, repites el procedimiento para generar el error y debería aparecer el error. Luego desactivar el modo desarrollo porque no quieres que tus usuarios vean esto ;-)

**Comment by ptcampinspvg** [comment]
Muchas gracias por las recomendaciones @ywarnier ! Vamos a probar de repetir el error en modo desarrollo para ver qué podemos hacer. En cuanto tenga noticias reflejaré el resultado.

**Comment by ptcampinspvg** [comment]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'id' cannot be null' in /home/privileg/public_html/chamillo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /home/privileg/public_html/chamillo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL) #1 /home/privileg/public_html/chamillo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL) #2 /home/privileg/public_html/chamillo/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\DBAL\Statement->execute() #3 /home/privileg/public_html/chamillo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(966): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts() #4 /home/privileg/public_html/chamillo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata)) in /home/privileg/public_html/chamillo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 112


Este es el error reflejado después de repetir el error. Como puede ser que el 'id' esté vacío??

**Comment by ptcampinspvg** [comment]
Buenos días, hemos conseguido tener un buen funcionamiento. Cambiando la estructura de la Base de Datos en 'c_item_property', concretamente la columna 'id' ya que la definición era NOT NULL predeterminado 0 y hemos podido comprobar que esta columna se crea como NULL y predeterminado NULL. De esta manera la plataforma no escupe el error 500.

No sabemos si será un cambio definitivo, pero esperamos que funcione correctamente. Las primera pruebas reflejan resultados correctos.

**Comment by ywarnier** [comment]
Gracias. Cierro.
