### ISSUE TITLE
No se pueden crear cursos en Chamilo 1.11 en windows server 2012 R2

### ISSUE THREAD

**Issue by rojas9112** [chamilo/chamilo-lms#2157]
Se a instalado chamilo 1.11 en un windows server 2012 r2, esta corriendo todo con normalidad, pero al momento de crear el curso de sale error 404 "No se encuentra el index" de la capeta que tiene por nombre el curso, dejo un vídeo del error, espero puedan ayudarme: https://www.youtube.com/watch?v=kStPY755hLU

**Comment by ywarnier** [comment]
Hola, por favor revisa el manual de instalación de Chamilo (última sección de "Prerequisitos"). Aunque puedas crear el curso, si tu servidor web no soporta los .htaccess (con Apache), no redirijirá correctamente la página home del curso.

Si usas IIS, no estoy seguro de como hacer, porque no lo soportamos oficialmente, pero estamos dispuestos a ayudar para lograrlo.

https://11.chamilo.org/documentation/installation_guide_es_ES.html#1._Pre-requisites

**Comment by AngelFQC** [comment]
Para IIS se tendría que "traducir" las reglas del archivo `.htaccess` a un archivo `Web.config`
https://blogs.msdn.microsoft.com/azureossds/2015/04/23/converting-apache-htaccess-rules-to-iis-web-config-using-iis-manager-for-azure-websites/

**Comment by rojas9112** [comment]
ywarnier y AngelFQC, quedo muy agradecido a ustedes dos, realice lo de importar el .htaccess y funciono de maravilla, gracias por sus aportes, buenos consejos y su trabajo constante por hacer de esta plataforma de educación una de las mejores a nivel mundial, :)

**Comment by ywarnier** [comment]
:+1:
