### ISSUE TITLE
Chamillo 1.11.06:  Next question hangs

### ISSUE THREAD

**Issue by leninkster** [chamilo/chamilo-lms#2161]
### Chamilo Version / Versión de Chamilo / Version de Chamilo

Just installed clean install of Chamilo 1.11.06 on Centos 6.9 using PHP 5.6 and MySQL 5.6.37.

I imported a course with just a test and description inside of a course (no learning path etc.) This course is used for practice examinations only.

Randomised 10 questions out of 739.

 First question is answered and Upon hitting "Next Question"the wait icon just spins.

### Expected behavior / Resultado esperado / Résultat attendu

Next question should populate.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Created new course, populated with test data.   Added description and 3 more tests.

Same thing.

Contents of the access log is:

_76.69.135.106 - - [28/Sep/2017:13:12:38 -0400] "GET /main/inc/ajax/message.ajax.php?a=get_count_message HTTP/1.1" 200 1 "http://campus.ontarioachi.ca/main/exercise/overview.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&isStudentView=true" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

76.69.135.106 - - [28/Sep/2017:13:12:38 -0400] "GET /main/inc/ajax/online.ajax.php?a=get_users_online HTTP/1.1" 200 465 "http://campus.ontarioachi.ca/main/exercise/overview.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&isStudentView=true" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

76.69.135.106 - - [28/Sep/2017:13:12:56 -0400] "GET /main/exercise/exercise_submit.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&origin=&learnpath_id=&learnpath_item_id=&learnpath_item_view_id= HTTP/1.1" 200 63926 "http://campus.ontarioachi.ca/main/exercise/overview.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&isStudentView=true" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

76.69.135.106 - - [28/Sep/2017:13:13:03 -0400] "GET /main/inc/ajax/online.ajax.php?a=get_users_online HTTP/1.1" 200 465 "http://campus.ontarioachi.ca/main/exercise/exercise_submit.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&origin=&learnpath_id=&learnpath_item_id=&learnpath_item_view_id=" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

76.69.135.106 - - [28/Sep/2017:13:13:03 -0400] "GET /main/inc/ajax/message.ajax.php?a=get_count_message HTTP/1.1" 200 1 "http://campus.ontarioachi.ca/main/exercise/exercise_submit.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&origin=&learnpath_id=&learnpath_item_id=&learnpath_item_view_id=" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"

76.69.135.106 - - [28/Sep/2017:13:13:15 -0400] "POST /main/inc/ajax/exercise.ajax.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&a=save_exercise_by_now HTTP/1.1" 200 24117 "http://campus.ontarioachi.ca/main/exercise/exercise_submit.php?cidReq=CCHIPRACTICE&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=1&origin=&learnpath_id=&learnpath_item_id=&learnpath_item_view_id=" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"_

Error_log reported no associated errors with this transaction.

Running an strace -p on the HTTP gave no more information.

I checked on the process log and found /main/inc/ajax/message.ajax.php was taking 124% of the daily process.

Running 'top' I discovered that upon hitting the 'next question' button php-cgi was using 29% of the CPU

Any other info needed?

**Comment by leninkster** [comment]
The problem was solved by disabling full text search.  This appears to be connected to the Xapian search function.

**Comment by ywarnier** [comment]
Thanks for your follow-up. The fulltext search / Xapian feature does not work in Chamilo 1.10 and 1.11. This is documented in the Changelog. We need time to re-write the module completely as the Xapian library has had a few changes over the years that we couldn't follow yet. We cannot remove it from the interface before the next major version because of our no-database-change-in-minor-versions policy (documented in the wiki).
