### ISSUE TITLE
Course copy does not keep quiz questions order

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2162]
### Current behavior
Copy a course (with quizzes and quiz questions) to another. The questions order is lost.

### Expected behavior
The copy should maintain the order of the questions.

### Steps to reproduce
- create course A
- create quiz A
- create questions A, B, C, D, E
- create course B
- copy course A to course B (full copy)
- go to course B
- look at the questions list

### Chamilo Version
1.11.0

I still need to check that in 1.11.x before this can be considered a real report

**Comment by AngelFQC** [comment]
I can't reproduc it on 1.11.x
