### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by mvalencia2017** [chamilo/chamilo-lms#2163]

**Comment by mvalencia2017** [comment]
Hola

**Comment by mvalencia2017** [comment]
Tengo el siguiente: Hola buenas tardes, 

Tengo el siguiente inconveniente me sale el siguiente mensaje. El directorio "archive" utilizado por esta herramienta no tiene habilitado los permisos de escritura. Contacte al administrador de la plataforma. E ingreso Limpieza del directorio archive, pero no pasa nada. Aún sigue saliendo el mensaje y no me permite ver los cursos. Y si entro como alumno no me carga saliendo el error La página corporacionph.com no puede procesar esta solicitud ahora. HTTP ERROR 500

**Comment by ywarnier** [comment]
Hola @mvalencia2017, este sitio es para reportar errores técnicos con un sustento técnico, y supone también que uno pueda leer las reglas de reporte indicadas para hacerlo. Sin esto, no podemos garantizar la calidad ni un tiempo de respuesta.
Abrir dos reportes para el mismo error podría ser considerando como una falta de respeto del tiempo de los desarrolladores de este proyecto. Tratémonos con respeto. Estoy cerrando este ticket ya que está duplicado por el #2163
