### ISSUE TITLE
error 500

### ISSUE THREAD

**Issue by mvalencia2017** [chamilo/chamilo-lms#2164]

**Comment by mvalencia2017** [comment]
Hola buenas tardes, 

Tengo el siguiente inconveniente me sale el siguiente mensaje. El directorio "archive" utilizado por esta herramienta no tiene habilitado los permisos de escritura. Contacte al administrador de la plataforma. E ingreso Limpieza del directorio archive, pero no pasa nada. Aún sigue saliendo el mensaje y no me permite ver los cursos. Y si entro como alumno no me carga saliendo el error La página corporacionph.com no puede procesar esta solicitud ahora. HTTP ERROR 500

**Comment by ywarnier** [comment]
Hola @mvalencia2017, el mensaje indica que contactes al administrador de la plataforma. Si eres tu y no sabes como solucionarlo, puedes aprender sobre esto dentro del manual de instalación de Chamilo (ver enlaces en la página de administración de tu portal Chamilo o aquí: https://11.chamilo.org/documentation/installation_guide.html), o sino puedes solicitar asistencia de quien te ofrece el servidor para este portal Chamilo. Por ende, si no tienes solución con ninguno de estos canales, quizás necesites soporte de proveedores oficiales de la asociación Chamilo, que son empresas que emplean expertos en Chamilo para ofrecer servicios profesionales, y colaboran continuamente al desarrollo de Chamilo: https://chamilo.org/providers
