### ISSUE TITLE
Chamilo 1.11.4 - impossible to import a course from previous Chamilo version

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#2165]
*default format ignored by user*

**Comment by Coursenligne** [comment]
Using Chamilo platform localy on my computer (WAMP64 // Firfox latest version) I try to upload a course I created 3 years ago.
The course seems to upload, no error message, but when I go to the course, it's all empty.

Eric

**Comment by jmontoyaa** [comment]
You can try to upload the course here:

https://11.chamilo.org/ (admin/admin)

**Comment by Coursenligne** [comment]
Situation, on my computer....
I download 1.11.4 from chamilo.org.
When ungz/untar, I have errors on symbolic links (no problem with 1.11.2, sae environment).
Impossible to install 1.11.4, I have to first install 1.11.2 then copy/past 1.11.4. Then Import/export and course creation don't work.
On your platform, no issue. I created a course and uploaded it without issue.
Note that 1.11.2 works fine on my computer, only 1.11.4 don't... The upload bar stops and I get a blank page then error messages
WAMP 64 // Firefox or Opera, same thing.
I hope this helps
![chamilo_1-11-4issue](https://user-images.githubusercontent.com/32436850/31097723-9a2d3bf6-a7c0-11e7-8e0d-267360824ac9.PNG)

**Comment by ywarnier** [comment]
This has been resolved since release 1.11.4 + 1 day and been reported here several times already :-) Please search for "Annotation" in the issues list to find it.
This is another issue than the one previously reported. Please use only one problem per issue and use the default format provided to speed up processing. Thank you.

**Comment by Coursenligne** [comment]
Sorry !
I couldn't find any issue related to course import/export on 1.11.4.
This is why I did reported the issue and even added the install issue in case these were linked (cascade of issues).

Thanks for your time

**Comment by ywarnier** [comment]
My comment was about the installation error: https://github.com/chamilo/chamilo-lms/issues?utf8=%E2%9C%93&q=is%3Aissue%20annotation
