### ISSUE TITLE
- learning path shows 96% completed while 100% of the items are clicked.

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2166]
Situation:
upgrade from chamilo 1.9.10.4 to chamilo 1.11.4 / upgrade from php 5.6 to 7.1
### Current behavior / Resultado actual / Résultat actuel
- Tutorial shows 96% completed while 100% of the items are clicked.
### Expected behavior / Resultado esperado / Résultat attendu
- Tutorial shows 100% completed while 100% of the items are clicked.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by marshel** [comment]
I confirm the existence of a bug like that, but cant reproduce. I had it multiple times.
I believe is something SCORM related, like a change of files without changing the manifest. And/or adding forums or exercises inside a LP.
The percentage of the linepath completion is on a different table than the lp item view, so maybe one of these entries of the user, besides being completed/passed, was not in account when the system added/updated the percentage to the table.
@jmontoyaa  Is there a way to add a function to the report page when the teacher/admin can refresh all the percentages of these LP/course?

**Comment by ywarnier** [comment]
Although we acknowledge there might be issues with SCORM in some very specific contexts, those are very time consuming (sometimes several hundred hours to find how to reproduce and fix). As such, if this is critical to your business, we recommend you hire an official provider or a skilled PHP developer to look at it.
