### ISSUE TITLE
Complete crash after playing with language settings: only repair possible after restore of database backup.

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2167]
Situation:
upgrade from chamilo 1.9.10.4 to chamilo 1.11.4 / upgrade from php 5.6 to 7.1
### Current behavior / Resultado actual / Résultat actuel
Complete crash after playing with language settings: only repair possible after restore of database backup.
### Expected behavior / Resultado esperado / Résultat attendu
No crash
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
play with the language settings, try the options and buttons
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
This task requires more information. You mean editing the languages here: ?

`main/admin/languages.php`
