### ISSUE TITLE
After upgrade of chamilo: assigned courses to classes can not be deleted.

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2169]
Situation:
upgrade from chamilo 1.9.10.4 to chamilo 1.11.4 / upgrade from php 5.6 to 7.1
### Current behavior / Resultado actual / Résultat actuel
- After upgrade of chamilo: assigned courses to classes can not be deleted. After deletion and new build of classes, this is again possible.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jloguercio** [comment]
I think this https://github.com/chamilo/chamilo-lms/pull/2174/commits/45a334fb6d88c2d9ebf8d49dfecd62a5bb25410a may fix the problem

**Comment by ywarnier** [comment]
No user feedback. No more pizza. Closing.
