### ISSUE TITLE
Old users (already existing before upgrade) can not be added to old classes (already existing before upgrade)

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2170]
Situation:
upgrade from chamilo 1.9.10.4 to chamilo 1.11.4 / upgrade from php 5.6 to 7.1
### Current behavior / Resultado actual / Résultat actuel
- Old users (already existing before upgrade) can not be added to old classes (already existing for upgrade). After deleting classes completely and rebuilding, this is again possible.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
This seems related to #2169, and we have no easy way to test. Closing.
