### ISSUE TITLE
DB Schema (was: After upgrade: Some mp4 movies in a learning path can not be viewed by users (not enough rights) while admins can)

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2171]
Situation:
upgrade from chamilo 1.9.10.4 to chamilo 1.11.4 / upgrade from php 5.6 to 7.1
### Current behavior / Resultado actual / Résultat actuel
- After upgrade: Some mp4 movies in a learning path can not be viewed by users (not enough rights) while admins can. Some other mp4 movies can be viewed by normal users.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Hi @Morepizza1,

Thank you for taking the time to report those issues.

We will probably not be able to look into these issues, as looking into the upgrade issues can be very time-consuming and very data-specific. There have been a large number of issues with the migration from 1.9 to 1.11, which we have fixed over the last 2 years, but we are now moving on and cannot look into issues linked to version 1.9 anymore. The developers community has very little spare time to look into this and it is much less entertaining than developing new features.

You could try (if you have command-line access to your server) to launch from the root of your Chamilo directory:
`php bin/doctrine.php orm:schema-tool:update --dump-sql`
to see if any SQL query was missing to get a database structure as would be expected in 1.11. There might be a few hundred queries there, but most of them will be useless renaming of indexes. However, some of these will really be important and might fix some of the issues you reported.

If this doesn't fix it and it is a business requirement, you might want to contact BeezNest (see https://chamilo.org/providers) for specialized support, where we will look into this in more detail and provide fixes for these issues.

Finally, all the migration code is in app/Resources/Migrations/ and you might find the way out of these issues by yourself if you have the time. If you do and you can share them here, we'd be happy to include them in the upcoming 1.11.6 minor fix version (to be published this week).

**Comment by Morepizza1** [comment]
Hello,

Thank you for your fast reply. 

The issues are collected from my students in a period of 1 month (september). Not all the issues are related to the transition from 1.9 to 1.11, like the issue with turning pictures.

If you talk about the database structure as would be expected in 1.11, is it possible to document the database structure like here for the 1.10 version:
https://support.chamilo.org/documents/93

It would be a great help for solving migration issues.

To make sure, the students can see what they have to see, I have now relaunched the rock solid and fast 1.9.10.4 version parallel with the new 1.11.4 version. I hope 1.11.6 solves a lot of issues.

Keep up the good work!

**Comment by ywarnier** [comment]
@Morepizza1 I've asked for help on the dev mailing list for an updated database schema. However, I'm prtty sure I'm going to have to do that myself (I'm the author of the two diagrams you see there). I've partially started that but it's not complete yet (I'm afraid it's more than 10h of work, so to schedule that into a busy schedule is a bit of a challenge, but I'm motivated by the fact that this might help you contribute).

**Comment by ywarnier** [comment]
Here you go, @Morepizza1 : I've added a Database structure page in the wiki and the files into the Git version of Chamilo (branch 1.11.x).
https://github.com/chamilo/chamilo-lms/wiki/Database-structure
I hope you will find your way into it because I tried recording a screencast but two different tools are failing for different reasons, so I have to move on.
