### ISSUE TITLE
Error al subir documentos a la carpeta Mis archivos de la red social

### ISSUE THREAD

**Issue by CarlosBarriuso** [chamilo/chamilo-lms#2175]
### Current behavior / Resultado actual / Résultat actuel
Unable to upload "rufus-2.15.exe". File type not allowed. (application/x-ms-dos-executable)
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Presionar red social. Presionar Mis archivos. Presionar subir archivo. Seleccionar archivo(.docx, .xlxs, .exe, .txt)
### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo-lms-1.11.4

**Comment by aragonc** [comment]
No seria mejor colocarlo en un zip, por seguridad no se puede subir .exe  :-1:

**Comment by ywarnier** [comment]
Hola @CarlosBarriuso,
Este error parece específico a la configuración de tu portal (si no me equivoco). En particular, como administrador, en la sección de parámetros de configuración de la plataforma, parámetros de seguridad (gorro de policía), probablemente que el blackllist esté activado con por lo menos "exe" en la lista de extensiones prohibidas (o al revés, quizás el whitelist esté activado).

**Comment by CarlosBarriuso** [comment]
Gracias @ywarnier, por su pronta respuesta. He revisado los parametros de seguridad, como me indicas. Adjunto el estado de esta configuración.
![captura](https://user-images.githubusercontent.com/8830218/31269107-6bf430fc-aa7f-11e7-9d49-14aa86022ab8.png)
La instalación la realice siguiendo las indicaciones de la documentación, sobre Windows 7 con wampserver64. Pensando que podría ser un problema de sistema operativo, monté una maquina virtual con Oracle Virtualbox, en la que instalé Ubuntu 16.04 LTS y LAMP, y el error sigue.
Gracias por su seguimiento.

**Comment by jmontoyaa** [comment]
La solución más fácil es de poner en un zip el archivo .exe

El mecanismo pasar subir archivos en "main/social/myfiles.php" depende de la librería elfinder.

**Comment by CarlosBarriuso** [comment]
Gracias por el aporte @jmontoyaa , pero tampoco me acepta el formato zip.
Los formatos que si me admite son jpg, csv, pdf, png, odt, .gif, .wmv.
Los formatos que no me admite son los Microsoft (.doc, .docx, xls, xlxs...), .zip, .rar, .jar, .exe, .txt.

**Comment by ywarnier** [comment]
@CarlosBarriuso usamos la librería elfinder para esto. Es un problema de su lado. Nosotros no lo podemos corregir sin hackear la librería.
