### ISSUE TITLE
Funcionalidad - Verificar integridad de base de datos para actualizaciones

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2177]
### Current behavior / Resultado actual / Résultat actuel

Si fuera posible sería muy útil introducir en la Administración un proceso de chequeo de integridad de la base de datos y en caso de no tener la estructura adecuada que se pueda corregir desde un botón o que muestre las sentencias SQL que se tendrían que ejecutar para corregirlo.

### Expected behavior / Resultado esperado / Résultat attendu

Al chequear la integridad de la base de datos contra la versión superior (misma rama o salto entre ellas) se facilitaría el proceso de migración si alguna tabla o campo no tiene la estructura correcta.

Se adjuntan capturas del software Joomla, el cuál dispone de una opción en la Administración para comprobar la integridad de las tablas y dispone de un botón (fix) para corregir la estructura (Extensiones > Manage > Database).

De esta forma si una actualización no se ha realizado por completo se podría corregir la estructura de la base de datos (tablas y campos) conforme a la versión Chamilo que se use, sea la rama 1.11.x o en ramas superiores.

Dado que es habitual realizar pruebas desde git o desde versiones estables (zip o tar.gz) de esta forma se garantizaría que la estructura de la base de datos siempre estuviera actualizada.

![db1](https://user-images.githubusercontent.com/5868981/31217704-32ba37a4-a9b8-11e7-89a0-a2881b838c67.jpg)
![db2](https://user-images.githubusercontent.com/5868981/31217714-3c62107e-a9b8-11e7-9342-c4f776cedb37.jpg)
![db3](https://user-images.githubusercontent.com/5868981/31217723-41c8df2a-a9b8-11e7-9de0-0edd60f2afa2.jpg)
![db4](https://user-images.githubusercontent.com/5868981/31217733-47682d50-a9b8-11e7-84d2-4fc20eb441b5.jpg)

**Comment by ywarnier** [comment]
Esta tarea está relacionada (aunque no un duplicado) con #2159

**Comment by ywarnier** [comment]
No le pongo versión porque la verdad no lo veo prioritario por ahora (aunque sí importante y útil).

**Comment by ywarnier** [comment]
@nosolored Sabes que puedes usar el comando `php bin/doctrine.php orm:schema-tool:update --dump-sql` para esto, verdad?

**Comment by nosolored** [comment]
Gracias, @ywarnier no lo habíamos usado. 

Al ejecutarlo `php bin/doctrine.php orm:schema-tool:update --dump-sql`
nos indica que hay que configurar un archivo. Por avanzar, nos podías indicar el contenido del fichero cli-config.php o config/cli-config.php que usáis.

Muchas gracias.

```
You are missing a "cli-config.php" or "config/cli-config.php" file in your
project, which is required to get the Doctrine Console working. You can use the
following sample as a template:

<?php
use Doctrine\ORM\Tools\Console\ConsoleRunner;

// replace with file to your own project bootstrap
require_once 'bootstrap.php';

// replace with mechanism to retrieve EntityManager in your app
$entityManager = GetEntityManager();

return ConsoleRunner::createHelperSet($entityManager);
```

**Comment by jmontoyaa** [comment]
Ese archivo ya existe en chamilo. No es necesario crearlo. Se tiene que ejecutar en la raiz de chamilo.

https://github.com/chamilo/chamilo-lms/blob/1.11.x/cli-config.php

**Comment by nosolored** [comment]
Gracias, @ywarnier y @jmontoyaa 

al ejecutar `php bin/doctrine.php orm:schema-tool:update --dump-sql`
en una demo Chamilo 1.11.x nos mostró 
`ALTER TABLE c_quiz_question CHANGE type type INT NOT NULL;`

Lo hemos insertado en la base de datos.  Es muy útil. 

Si fuera posible añadir el chequeo en el proceso de instalación/actualización, así se podría corregir en la base de datos antes de iniciarlo. Podría lanzar un mensaje que mostrara las sentencias SQL o si fuera posible añadir un botón FIX para ejecutar las sentencias SQL.

En una instalación de Chamilo también podría aparecer en main/admin/system_status.php en el apartado de Dabase para comprobar si la estructura de la base de datos es correcta.

Un saludo.

**Comment by nosolored** [comment]
Por comentaros @ywarnier y @jmontoyaa

En una demo Chamilo 1.11.6 dev (github) que usamos desde la 1.8 y con migraciones realizadas a 1.9, 1.10 y 1.11 nos ha mostrado 551 diferencias el Doctrine. Entre ellas 4 tablas que no estaban presentes
group_rel_group
group_rel_tag
group_rel_user
groups

Hemos probado a forzar la actualización de la base de datos con php bin/doctrine.php orm:schema-tool:update --force y el resultado muestra

```
Updating database schema...
  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'DROP INDEX language_parent ON language':
  SQLSTATE[HY000]: General error: 1553 Cannot drop index 'language_parent': needed in a foreign key constraint
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1553 Cannot drop index 'language_parent': needed in a foreign key constraint
  [PDOException]
  SQLSTATE[HY000]: General error: 1553 Cannot drop index 'language_parent': needed in a foreign key constraint
orm:schema-tool:update [--complete] [--dump-sql] [--force]
```

Se ha generado las sentencias SQL para corregirlo. Las hemos ejecutado en MySQL en 4 pasos y finalmente sólo muestra 2 índices que no concuerdan

```
php bin/doctrine.php orm:schema-tool:update --dump-sql
ALTER TABLE extra_field_options ADD CONSTRAINT FK_A572E3AE443707B0 FOREIGN KEY (field_id) REFERENCES extra_field (id);
ALTER TABLE extra_field_values ADD CONSTRAINT FK_171DF924443707B0 FOREIGN KEY (field_id) REFERENCES extra_field (id);
```

Los insertamos en MySQL pero no afecta a ninguna columna.
Al ejecutar de nuevo php bin/doctrine.php orm:schema-tool:update --dump-sql sigue indicando que no están presentes los índices.

De todas formas nos vendrá muy bien para las pruebas de migraciones desde 1.9 y 1.10.

**Comment by ywarnier** [comment]
Estoy cerrando esta tarea porque en Chamilo 2.0 tendremos más herramientas parte de Symfony para evaluar estos problemas.
