### ISSUE TITLE
Additional users for surveys

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2179]
### Current behavior / Resultado actual / Résultat actuel
When additional email addresses entered in the designated field, these recipients don't get a survey invitation. Also the result page only counts the registered platform users as sent.

### Expected behavior / Resultado esperado / Résultat attendu
The field should be parsed and additional emails should be sent to the addresses.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Add a survey in a course, set it up properly (start date, end date, questions, ...), add another email address below the platform user selection, check for "yes, send to all users", and then click "send".

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by NicoDucou** [comment]
I just did a test on the test platform here : 
https://11.chamilo.org/main/survey/survey.php?survey_id=30&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&

I selected 1 user from the course and added 1 email in the additional email field. On the result page I got 2 invitations sent which is correct.

We can also see in the list of surveay that the number of invited users is 2.

I also received the mail correctly to my email address.

There have been some correction done between 1.11.4 and 1.11.6 so I guess it solved your problem.

@lonesomewalker can you confirmed it's all good for you and that we can close this task ?

**Comment by lonesomewalker** [comment]
Confirmed, working in 1.11.6
