### ISSUE TITLE
Survey questions - one question per page

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2180]
### Current behavior / Resultado actual / Résultat actuel
When the survey is started, all questions are listed on a single page.
The checkbox "one question per page" was set.
When looking in the database, the column "one_question_per_page" is empty.
Even when setting this manually to 1 (in the database), the questions are still displayed on a single page.

### Expected behavior / Resultado esperado / Résultat attendu
Questions should be asked one by page.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Set up a survey, tick the checkbox for one question per page.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by NicoDucou** [comment]
I just has the same problem on 1.11.x today.
I created a simple survey checking the box "one question per page" but it does not work. it can be checked here : http://chamilo111x.loc/main/survey/survey.php?survey_id=8&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=

I also tried to put the registry in the database to 1 and it stil displays all the questions on 1 page. So 2 problems here :
* The setting with the checkbox "one question per page" is not saved in the database.
* Even if the registry in the database is set to 1, all the questions still appear on 1 page when it should be a question per page.

**Comment by NicoDucou** [comment]
> So 2 problems here :
> 
>     * The setting with the checkbox "one question per page" is not saved in the database.
To solve this problem I think this is enough, but before sending it I need to understand why it was only for survey_type == 1 that Chamilo is saving the settings, is there a reason for that  ?

```
diff --git a/main/survey/survey.lib.php b/main/survey/survey.lib.php
index 91796cfd07..3d699623a6 100755
--- a/main/survey/survey.lib.php
+++ b/main/survey/survey.lib.php
@@ -280,10 +280,12 @@ class SurveyManager
                 $extraParams['form_fields'] = '';
             }
 
+           $extraParams['shuffle'] = 0;
+           $extraParams['one_question_per_page'] = 0;
+           if (isset($values['shuffle'])) $extraParams['shuffle'] = $values['shuffle'];
+           if (isset($values['one_question_per_page'])) $extraParams['one_question_per_page'] = $values['one_question_per_page'];
             if ($values['survey_type'] == 1) {
                 $extraParams['survey_type'] = 1;
-                $extraParams['shuffle'] = $values['shuffle'];
-                $extraParams['one_question_per_page'] = $values['one_question_per_page'];
                 $extraParams['parent_id'] = $values['parent_id'];
 
                 // Logic for versioning surveys

```

>     * Even if the registry in the database is set to 1, all the questions still appear on 1 page when it should be a question per page.

I will look at this one now.

**Comment by NicoDucou** [comment]
Even if it gets correctly registered in the database after the creation with the modification in the previews comment, then if we edit the survey the checkbox for one question per page does not appears and the setting is reset to 0 in the database when validating.

If the setting is correct in the database then the survey seems to be presented correctly with one question per page.

Julio I let you have a look a the modification I proposed in the previous comment and then add the checkbox on the edit form so that it does not get resetted every time.

**Comment by NicoDucou** [comment]
Even if the setting is correct in the database, there is still a problem when showing the survey on main/survey/fillsurvey.php?course=ENQUETEDESATISFACTION&invitationcode=auto&scode=enquetesatisfaction&id_session=0 because it present the first question and a button to finish the survey instead of showing the button to go to the next question.

**Comment by jmontoyaa** [comment]
I'm working on this one

**Comment by NicoDucou** [comment]
It works, but I think the option of "One question per page" should be editable when editing a survey.
For example i checked the setting when I created the survey by mistake and now I want to uncheck this setting, but when I got to the editing page the setting "One question per page" does not appear so I can not change it, for example here : https://11.chamilo.org/main/survey/create_new_survey.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&action=edit&survey_id=16 in the advanced parameter there should be the option "One question per page" to be able to edit it (I do not see any reason not to show it here).

It is not directly related but I found a problem with a question type in the survey tool, if you create a Multiple Response type question and you set it to vertical then i shows it horizontal. You can see it here : https://11.chamilo.org/main/survey/preview.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&survey_id=16
There are 2 questions 1 horizontal and 1 vertical and both show the answers horizontal.

**Comment by NicoDucou** [comment]
One more problem with the "One question par page" option. It's not saved when doing a backup of the course, when importing the course then the survey has lost the setting "One question per page".

**Comment by jmontoyaa** [comment]
> One more problem with the "One question par page" option. It's not saved when doing a backup of the course, when importing the course then the survey has lost the setting "One question per page".

I had to update the question :)

![selection_003](https://user-images.githubusercontent.com/158935/49151058-178d5f00-f30f-11e8-83a1-3291ec9488a3.png)

**Comment by jmontoyaa** [comment]
I fixed the other 2 issues (edit and backup/restore).

**Comment by NicoDucou** [comment]
Good work Julio, it is all working perfect. Closing this issue.
