### ISSUE TITLE
Tests links inside Grade book are wrong

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2184]
### Current behavior / Resultado actual / Résultat actuel

On users grade book, a graded test that is inside a LP, when clicked, goes to the exercise tool instead of the respective LP itemID;

As by default, the tests when on LP are hidden to the user, the user can't see the correct test result and feedback.
The suggestion is when adding the grading on grade book add the possibility to select the exercise inside a LP or make some kind of check when the users grade book is opened.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
We cannot really link to a specific learning path ID from some other place (there was some progress made about this by @jmontoyaa for a customer and this has been integrated into Chamilo, but I'm not sure how extensive that is)

**Comment by AngelFQC** [comment]
Teachers are redirect to learning path that contains the exercises, but not the students.

The PR #2762  allow redirect to students to learning path when it contains the exercise

**Comment by ywarnier** [comment]
Closing (lack of user feedback)
