### ISSUE TITLE
sub languages are not always available

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2186]
### Current behavior / Resultado actual / Résultat actuel
For example in sessions overview, the button to subscribe to a session does not use the value of the sub language.
Also in case of surveys, the variables used for building the email are not taken from the sub language.

### Expected behavior / Resultado esperado / Résultat attendu
System should ALWAYS check for correct language, if translated variable is not available, base language of sub should be used, otherwise fallback to default (english).

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
I cannot reproduce this in the session overview page. I use URL /session/3/about on my system, with a sub-language, and the button appears in the sub-language (as long as I, as a user, have configured that sub-language in my profile).
In the case of surveys, announcements and others: specific markers (to be replaced by a dynamic value) do not manage translations at this time.
