### ISSUE TITLE
I can not install chamilo.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2188]
Hello.
Dear Support
I am getting error when trying to install chamilo 1.11.4 on new VPS
VPS configuration.
CentOS Linux 7.4.1708 (Core)
mysql.png MySQL localhost (default for MySQL) 3306 10.1.28.
PHP version: 7.0.24
I follow all the installation steps.
But when you get to the database configuration it appears.
#
Warning: Redis :: connect (): connect () failed: Connection refused in /var/www/vhosts/domain.com/sub.domain.com/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup. php online 137
#
Follow the picture.
Thanks for listening
att.
Marcelo
![chamilo erro bd](https://user-images.githubusercontent.com/25286516/31409323-d7e8176e-ade1-11e7-8bf8-b2e0973cb6db.PNG)

**Comment by bassuma** [comment]
Just updating the server support failed to resolve.
It has something to do as Regis module in plesk php 7.
See answer.
Hi,

It seems the clone version of chamilo from github is expecting redis in the server. Can see similar error posted in the below url for memcache.

At this moment what I suggest is contact the support team of chamilo and mention below are the error we getting during MySQL connection test.

https://github.com/chamilo/chamilo-lms/issues/1594

Warning: Redis::connect(): connect() failed: Connection refused in /var/www/vhosts/enempassei.com/sala.enempassei.com/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php. Below are the lines of redis related from Setup.php

++++++++++++++++++++
} elseif (extension_loaded('redis')) {
$redis = new \Redis();
$redis->connect('127.0.0.1');
$cache = new \Doctrine\Common\Cache\RedisCache();
$cache->setRedis($redis);
} else {
$cache = new ArrayCache();
}
} elseif ($cache === null) {
$cache = new ArrayCache();
}
++++++++++++++++

Regards,
Minos JL
Level 3 Support

**Comment by ywarnier** [comment]
It seems like you have the Redis extension of PHP installed but you don't have a Redis server running.
You might just as well remove the php-redis extension, and that should work.

Either way, that's a *warning* message, meaning it doesn't really matter (Chamilo will not stop working just for that).

**Comment by bassuma** [comment]
Hello.
@ywarnier.
Many thanks for the quick response.
I will try again the vps support again.

Greetings,
Marcelo Bassuma
;)

**Comment by jmontoyaa** [comment]
:+1:

**Comment by ywarnier** [comment]
@bassuma you'll be happy to know that we have looked deeper into this issue, found that it was a Doctrine problem and sent a Pull Request to doctrine (https://github.com/doctrine/doctrine2/pull/6777) and, in the meantime, have applied a change of configuration in Chamilo so that production mode does not check (at all) for the existence of Redis or Memcache (which also presented the same issue).
Your report allowed us to detect an issue that might have affected other hosting users. Thanks.
