### ISSUE TITLE
Prerrequisitos con test - nota máxima error - y solución

### ISSUE THREAD

**Issue by montsemocholi** [chamilo/chamilo-lms#2189]
Hola,

Contexto:
- Indicar la nota mínima y máxima de un ejercicio como prerrequisito en un item de una lección.
- Ejercicio: 20 preguntas aleatorias de un banco de 30, cada pregunta correcta 1 punto.
- Lección:
Aviso de text (documento html)
Ejercicio
Test finalizado (documento html) Prerrequisito: Ejercicio min:10 max:20
El sistema no permite poner 20, sólo 19.

SOLUCIÓN
archivo exercise.class.php
#7177
#7197 
ERRÓNEO
`for ($i = 1; $i <= count($questionList); $i++) { `

CORRECTO:
`for ($i = 0; $i <= count($questionList); $i++) { `

(le faltaba sumar el $questionList[0])

**Comment by marshel** [comment]
I confirm this bug,
because I had to workarounds this issue in multiple LP, using an item before the test as a prerequisite.
Even with direct DB intervention it seems that the prerequisites wont work.

**Comment by jmontoyaa** [comment]
I just added a fix. Can you try to reproduce the error here?:

https://11.chamilo.org/

**Comment by montsemocholi** [comment]
Ok, Do I need user and password?

**Comment by jmontoyaa** [comment]
@montsemocholi 

user: admin
pass: admin

**Comment by montsemocholi** [comment]
@jmontoyaa tested ok
