### ISSUE TITLE
File duplicated on upload

### ISSUE THREAD

**Issue by aliand** [chamilo/chamilo-lms#2190]
### Current behavior / Resultado actual / Résultat actuel
L'Halloween approche, les vieux fantômes refont surface !
Les doublons réapparaissent au chargement d'une nouvelle version d'un fichier dans le même dossier (Voir l'image jointe).
![doublons](https://user-images.githubusercontent.com/28765227/31467364-b2a9e254-aea7-11e7-8f9c-5d94d9ea268f.png)

Ce problème existait dans la version 1.9.10. https://support.chamilo.org/issues/7244

Il me semble que si nous désirons renommer un fichier, la nouvelle version devrait toujours reprendre le nom d'origine car si je fais appel à ce fichier via un hyperlien, ce n'est jamais la version la plus récente qui est affiché!

### Expected behavior / Resultado esperado / Résultat attendu
Le fichier existant devrait être écrasé et remplacé par le plus récent.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Upload le même fichier plusieurs fois
### Chamilo Version / Versión de Chamilo / Version de Chamilo
Installation à partir de zéro - 1.11.4 - et dans un nouveau cours fraîchement créé.

Merci,

Alain Deschênes
alain.deschenes@cegeplimoilou.ca

**Comment by jmontoyaa** [comment]
Je pense qu'il y a un erreur les fichiers doivent s'appeller Document.txt,  Document_2.txt et Document_3.txt. 

J'ai corrigé ca.

**Comment by jmontoyaa** [comment]
Dans Chamilo on l'option "Mode de chargement par défaut des documents":

https://11.chamilo.org/main/admin/settings.php?search_field=document_if_file_exists_option&category=search_setting

Donc on peut choisir le comportement par defaut: "Renommer" ou "Écraser"

**Comment by aliand** [comment]
Excellent, on peut donc considérer ce événement comme étant clos. Pour ma part, j'opèrerai dorénavant en mode "Écraser".
Merci !
Alain

**Comment by jmontoyaa** [comment]
:+1:
