### ISSUE TITLE
translating buy-couses Dutch

### ISSUE THREAD

**Issue by learningcentrum** [chamilo/chamilo-lms#2192]

**Comment by learningcentrum** [comment]
We have translate  we hebben buy-couses vertaald

**Comment by ywarnier** [comment]
Could you attache the translation file here so we can integrate it?
Did you do that based on Git or based on the 1.11.4? A few improvements have been added since 1.11.4 which required new terms.

**Comment by learningcentrum** [comment]
# transalation
how can I upload it, can I sent to a email or ftp server

**Comment by learningcentrum** [comment]
chamilo 1,11,4

**Comment by jmontoyaa** [comment]
You can upload a file here.

**Comment by learningcentrum** [comment]
[english-md.zip](https://github.com/chamilo/chamilo-lms/files/1386795/english-md.zip)
dutch translation for buy couses

**Comment by jmontoyaa** [comment]
I added to chamilo, but I removed all the learningcentrum references.
