### ISSUE TITLE
Connected users appear offline on the chamilo

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2193]
Hello.
Please, I need a support.
I installed a new chamilo v1.11.4 on the server.
But when registering users.
It appears they are all offine.
It will be.
What is missing some configuration in php7?
Configuration in php.ini?
Thanks for listening
Marcelo
![admin off](https://user-images.githubusercontent.com/25286516/31587337-e86423c2-b1be-11e7-9129-0ce55e45a777.PNG)

![amigos off](https://user-images.githubusercontent.com/25286516/31587338-edb94140-b1be-11e7-9db1-0a2e50e84a3f.PNG)

![list de user off](https://user-images.githubusercontent.com/25286516/31587376-a79c0732-b1bf-11e7-9da7-8884dfd0e708.PNG)

Chamilo in Test Server Mode Error:
![serve-de-test](https://user-images.githubusercontent.com/25286516/31587359-4adcff38-b1bf-11e7-9589-a8327dbfbdba.jpg)

**Comment by jmontoyaa** [comment]
This was already fixed in latest code in chamilo 1.11.x 
I also added a fix for the notices.

**Comment by bassuma** [comment]
Hi,
@jmontoyaa.
I had downloaded the 1.11.x patch.
Fixed some bugs, but this continued
With this #2193 correction, which you have increased, you are working now.
We can close the ticket.
Thanks for your help.
Greetings,
Marcelo

![erro corrigido](https://user-images.githubusercontent.com/25286516/31613512-1a8d1216-b262-11e7-87bd-5db05db32307.PNG)
