### ISSUE TITLE
Exportar certificados a PDF

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2194]
### Current behavior / Resultado actual / Résultat actuel
El PDF resultante no se ve bien, no se ven las imágenes (aparece un cuadradito con una x roja) y no reconoce formatos simples de HTML como el texto centrado o el borde de tabla.

### Expected behavior / Resultado esperado / Résultat attendu

El PDF debería parecerse al aspecto del certificado en la vista previa en pantalla, debería respetar al menos los formatos sencillos y las imágenes como logotipos, etc.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. En un curso, crear algún ejercicio o tarea para calificar y poder generar el certificado, configurar en evaluaciones este ejercicio con ponderación suficiente para obtener el certificado
2. En evaluaciones marcar la casilla de generar certificados
3. En certificados, crear una plantilla simple o bien utilizar la plantilla que tiene Chamilo y asignar el certificado por defecto
3. Realizar el ejercicio con algún alumno para poder generar al menos un certificado
4. En evaluaciones, acceder a la lista de certificados, pulsar en generar certificados y después en exportar certificados a PDF
Se puede probar aquí: https://11.chamilo.org/main/gradebook/gradebook_display_certificate.php?cidReq=123333&id_session=0&gidReq=0&gradebook=1&origin=gradebook&cat_id=43

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x
Ocurre tanto con el certificado por defecto que incluye Chamilo como generando una plantilla nueva manualmente.

**Comment by jmontoyaa** [comment]
Acabo de agregar una correción

**Comment by nosolored** [comment]
Hola,
Hemos actualizado nuestra demo y probado los certificados.
El certificado por defecto de Chamilo sale perfecto, esta parte genial y soluciona muchos problemas.
![certificadodefecto](https://user-images.githubusercontent.com/5868981/31678386-4d94b634-b36e-11e7-880c-69f3cf79649c.jpg)

Sin embargo un certificado realizado con el propio editor HTML no. El certificado solo contiene una tabla añadida con el editor, y un texto sin formato centrado en la tabla. 
![certificadohtml](https://user-images.githubusercontent.com/5868981/31678399-5a336f16-b36e-11e7-9a19-857776f56204.jpg)

En este ultimo caso en la vista en pantalla se ve bien pero al exportar a PDF no tiene ninguna tabla y no centra el texto, los dos diplomas salen en la misma hoja, mezclados.
![mezclados](https://user-images.githubusercontent.com/5868981/31678410-644a42cc-b36e-11e7-936c-5935268ed7cd.jpg)

**Comment by jmontoyaa** [comment]
Acabo de agregar una correción. Tratar de reproducirlo en https://11.chamilo.org/ (admin/admin)

**Comment by nosolored** [comment]
Lo acabo de probar en https://11.chamilo.org:
El certificado en PDF sale sin imagenes, con la plantilla por defecto de Chamilo
![pdfdefecto](https://user-images.githubusercontent.com/5868981/31706358-f81d7d5a-b3e8-11e7-8ab9-5b3f261a5da0.jpg)

El certificado con una plantilla personalizada muestra la imagen pero sale todo el texto en una esquina
![pdfplantilla](https://user-images.githubusercontent.com/5868981/31706364-fe61f196-b3e8-11e7-90b5-0110699653ff.jpg)

Puedes verlo aqui:
https://11.chamilo.org/main/gradebook/index.php?cidReq=123333&id_session=0&gidReq=0&gradebook=1&origin=gradebook&&

**Comment by jmontoyaa** [comment]
En esa URL, entrando con el user "admin", me aparece todo correctamente.

**Comment by nosolored** [comment]
Te aparece correcto al exportar a pdf los certificados?
A mi no, te adjunto el PDF exportado
[Certificates.pdf](https://github.com/chamilo/chamilo-lms/files/1394186/Certificates.pdf)

**Comment by jmontoyaa** [comment]
Supongo que te refieres al centrado del texto.

Ese no es un tema de Chamilo. La librería mpdf no reconoce ese HTML ver el comentario:

https://stackoverflow.com/questions/32164402/mpdf-text-align-with-p-h1-h6-in-table-not-work

He modificado la plantilla para tener el texto centrado.

**Comment by nosolored** [comment]
Ok, habrá que tenerlo en cuenta entonces a la hora de generar los certificados, lo normal es que los usuarios le den al boton de centrar texto en el editor html, y es así como lo hace.
Cierro entonces la tarea ya que las imágenes si que cargan.

**Comment by gigiotibaduiza** [comment]
Hola buen día, 

Estoy siguiendo este hilo y el error aún se presenta. Podría indicarme si hay algún otro Issue abierto sobre el tema?

Gracias de antemano

**Comment by regredu79** [comment]
Saludos a todos, por lo visto aun hay problemas en este tema de certificados.  Entiendo que algunos sean de configuracion....html al exportar, etc.  Pero en general en la herramienta EVALUACIONES, yo tengo 2 problemas:

1) No muestra el icono de evaluacion a los alumnos  a pesar de estar activado
2) No genera los certificados de forma automática a pesar de tener la configuración para hacerlo

En el archivo adjunto constan las pruebas realizadas y evidencias,

Versión actual que tengo: "Su versión está actualizada: Chamilo 1.11.10"

Gracias
[problemas evaluaciones.docx](https://github.com/chamilo/chamilo-lms/files/4466055/problemas.evaluaciones.docx)


[problemas evaluaciones.docx](https://github.com/chamilo/chamilo-lms/files/4466052/problemas.evaluaciones.docx)
