### ISSUE TITLE
Imposible ocultar certificados

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2195]
### Current behavior / Resultado actual / Résultat actuel

El alumno siempre puede ver un botón para acceder a su certificado aunque en el curso no se haya marcado la opción de "Generar certificados" en la herramienta de evaluaciones.
Incluso si se borra la plantilla de certificado por defecto, es decir, no existiendo un certificado definido, también aparece este botón y el alumno accede al certificado.
También puede acceder desde el apartado de "Mis certificados" en la página de mis cursos

### Expected behavior / Resultado esperado / Résultat attendu

Si el profesor no desea emitir certificados en el curso y no marca por tanto la casilla de "Generar certificados" en la configuración de la herramienta de Evaluaciones, no debería el alumno ver el botón de certificado ni poderlo abrir, ni en evaluaciones ni en Mis certificados.
Si no existe una plantilla de certificado definida, igualmente no debería aparecer este botón.
Por ahora la única forma de que no aparezca este botón es indicar para la certificación una calificación inalcanzable.

Sería muy bueno si, además de solucionar este problema, se pudiera añadir una opción a nivel de administración para simplemente no usar certificados, y que no apareciera ni ese botón ni el apartado de Mis certificados 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Configurar la herramienta de Evaluaciones desmarcando la casilla de "Generar certificados"
Acceder con un alumno que haya superado el curso a la herramienta de evaluaciones, podrá ver el botón de certificado
![certificate](https://user-images.githubusercontent.com/5868981/31628002-89b5ae80-b2af-11e7-912c-1b6870856fa0.jpg)

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x

**Comment by nosolored** [comment]
Hola,
Lo acabo de probar en una demo recién actualizada con los cambios. Te comento:
Si en evaluaciones del curso no marcas la opción de generar certificados, el botón de ver certificado ya no se le muestra al alumno, esto está correcto. También funciona en sesiones.
Sin embargo el certificado sigue apareciendo en el apartado de "Mis certificados" de la página de Mis cursos.

**Comment by jmontoyaa** [comment]
Buen dato, lo reviso.

**Comment by nosolored** [comment]
Perfecto, ya funciona bien.
Gracias
