### ISSUE TITLE
Remove unused main/reports

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2198]
The code inside main/reports/index.php is not used.
The code of main/inc/lib/rights.lib.php is also unmaintained

**Comment by ywarnier** [comment]
This was a development by @aligot-cblue too, but given it has been left unmaintained (and unused for years), it makes sense to have removed it. Thanks.
Since you've removed it (~45 days ago), nobody seems to have had a reason to complain.
