### ISSUE TITLE
error trying to install plugins

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2200]
Hello.
When trying to install a plug-ins on the chamilo.
Generates an unexpected error.

To replicate.
Goes to administration.
https://11.chamilo.org/main/admin/settings.php?category=Plugins
Click Plug-ins.
Choose any one and click install.

```
Besides this error above in the image.
At my installation when leaving in test server mode.
Show this error in the plugins area.
chamilo v1.11.4
```
---------------------------------------
Warning: is_dir(): open_basedir restriction in effect. File(/var/squidGuard/blacklists) is not within the allowed path(s): (/var/www/vhosts/chamilo.com/:/tmp/) in /var/www/vhosts/chamilo.com/plugin/olpc_peru_filter/lib/olpc_peru_filter_plugin.class.php on line 77

---------------------------------------

Greetings;
Marcelo

**Comment by ywarnier** [comment]
Hi @bassuma 
Some plugins have some specific requirements. They are usually documented in their README. Some of them might be out of date (like the olpc_peru plugin which we should be removing in the next major version).
Please try to do one report per plugin. Redirection is a plugin that has been added a few days ago. It is not yet ready for production. You shouldn't use Chamilo 1.11.x from Git for a production portal, if this is something you are trying to do now...

**Comment by ywarnier** [comment]
It turns out you were right about the redirection plugin. I'm taking the opportunity to clean up plugins a bit to avoid the same issue happening to others on the release date.

**Comment by bassuma** [comment]
Hello.
@ Ywarnier.
Would you be able to provide a beta of Chamilo 1.11.6?
For as you can see in the picture.

![bug novo com 11x](https://user-images.githubusercontent.com/25286516/31832865-45bd8ac2-b5a7-11e7-8de9-7f9840295382.PNG)

There is no way for me to test using chamilo 1.11.4 + patch 1.11.x.
When I test and with a specific bug.
And I use file-to-file.
Not to give problem.
In this case file to file.
Or
And pacth 1.11.x
Gave an error like the one in the picture.
Thanks for listening;
Bassuma

**Comment by bassuma** [comment]
Hello.
I downloaded the chamilo via linux terminal.
I installed it and it works perfectly.
At the moment the bugs I reported.
Do not exite for me.
I'll close the ticket.
Thanks for listening
