### ISSUE TITLE
Change language.dokeos_folder to folder

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2201]
DB structure change required

**Comment by jmontoyaa** [comment]
The dokeos folder is not used anymore, the field was removed from the language table.

**Comment by christianbeeznest** [comment]
Tested in chamilo 2, it is working,  dokeos_folder is not used in code and database.

**Comment by christianbeeznest** [comment]
It is changed and checked migration in this commit https://github.com/chamilo/chamilo-lms/commit/89c870377b168a747b5bb5abf06f67f55bbace67#diff-86d0367cb4e3e44e484a7d67c004d75772de7b8df367bab5fdd78e96b444b082 , file Version20.php
