### ISSUE TITLE
Online users result in PHP notice

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2203]
### Current behavior / Resultado actual / Résultat actuel
When clicking on the number of users live active, you get:
Notice: Undefined index: user_is_online_in_chat in /main/inc/lib/social.lib.php on line 1180

**Comment by ywarnier** [comment]
Hi @lonesomewalker, could you test with this fix?

**Comment by lonesomewalker** [comment]
fixed. :-)
