### ISSUE TITLE
Mathjax in CKeditor breaks with multiple editors on page

### ISSUE THREAD

**Issue by raggar** [chamilo/chamilo-lms#2205]
### Current behavior / Resultado actual / Résultat actuel
When multiple texteditors are loaded the formula editor shows up, but when clicking on a image it doesn't show in the input field.
If only one editor is loaded this does work, the image is displayed as Latex in the input field above the formula images.

### Expected behavior / Resultado esperado / Résultat attendu
I would expect showing the different parts of the formula in Latex in the input field. 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Make sure you have enabled the mathjax and ASCIIMathML mathematical editor in the global settings. 
Go to a page with multiple editors, for example: main/exercise/exercise_admin.php (create a new exercise)
Tryout the formula editor and try to click on the images. 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
tested with 1.11.2 and 1.11.4

**Comment by jmontoyaa** [comment]
I found an error, it should be fixed with:

https://github.com/chamilo/chamilo-lms/commit/4c5c989c058ee13fd657dded349dc894ecfbe45a
https://github.com/chamilo/chamilo-lms/commit/0081424e0cbc5540a6a52c5df6fb6a63e0c201f9

**Comment by ywarnier** [comment]
@raggar any feedback you'd like to provide before I close this task?

**Comment by ywarnier** [comment]
@raggar Could you let us know if that solves the issue for you? (you can test it on https://11.chamilo.org if you have no way to update your own portal). I'd like to have everything wrapped up by next Monday...
