### ISSUE TITLE
chat.ajax.php causes 100% cpu

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2206]
### Current behavior / Resultado actual / Résultat actuel
After some time, a portal uses 100% cpu; when investigatig:
GET /main/inc/ajax/chat.ajax.php?action=chatheartbeat
seems to cause this strange behaviour.
But not always, that's the strange part; only when the platform is idle.

Chat is globally activated.

### Expected behavior / Resultado esperado / Résultat attendu
cpu consumption should only be that high when there is real action.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 running on an apache2 with php5-fpm system.

**Comment by jmontoyaa** [comment]
We did some changes to chat.ajax.php for 1.11.x seems to work ok in https://11.chamilo.org/ (admin/admin)
