### ISSUE TITLE
Migración de Chamilo 1.10 a 1.11.x

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2214]
### Current behavior / Resultado actual / Résultat actuel

Migración de Chamilo 1.10.8 a 1.11.6 dev
Una vez terminada la actualización sin incidencias aparentes, se generan muchas líneas de SQL cuando se ejecuta la revisión de Doctrine, no sabemos si esto es normal, o no deberían salir tantas diferencias entre las bases de datos inmediatamente después de actualizar.

### Expected behavior / Resultado esperado / Résultat attendu

Migración 1.11.6 
Entendemos que al actualizar se tendría que haber normalizado la estructura de la base de datos.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Indicamos los pasos que hemos seguido: 

- En una instalación con Chamilo 1.10.8 con PHP 5.6 se ejecuta php bin/doctrine.php orm:schema-tool:update --dump-sql que genera

```
CREATE INDEX idx_efv_fiii ON extra_field_values (field_id, item_id);
ALTER TABLE language CHANGE parent_id parent_id INT DEFAULT NULL;
CREATE INDEX idx_cqa_q ON c_quiz_answer (question_id);
```
Se actualiza la base de datos MySQL con ese código a través de PHPMyAdmin.
No hemos utilizado `php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml`

- Posteriormente se actualiza la instalación Chamilo 1.10.8 con el último código de github https://github.com/chamilo/chamilo-lms/tree/1.10.x
generado con git y composer update desde una máquina virtual con entorno PHP 5.5.

Con el código generado se sobreescribe la instalación Chamilo 1.10.8 y se ejecuta php bin/doctrine.php orm:schema-tool:update --dump-sql que genera

`ALTER TABLE c_quiz CHANGE start_time start_time DATETIME DEFAULT NULL, CHANGE end_time end_time DATETIME DEFAULT NULL;`

Se inserta este código en la base de datos a través de PHPMyadmin.

Chamilo 1.11.6 dev
---------------------
- Se genera con el git de https://github.com/chamilo/chamilo-lms/tree/1.11.x y composer update
- Se sobreescribe la instalación Chamilo 1.10.6 con él.
- Se inicia el proceso de migración con .../main/install y siguiendo las instrucciones se eliminan los directorios
/main/exercice/
/main/newscorm/
/plugin/ticket/
/plugin/skype/

- Se detecta la versión anterior y se sigue el proceso. La actualización se realiza correctamente y log muestra DONE.

Tras la misma y al ejecutar el php bin/doctrine.php orm:schema-tool:update --dump-sql genera 86 sentencias SQL (presentes en el archivo **diff1.txt**). Las 4 primeras para crear 4 tablas:

```
CREATE TABLE group_rel_group (id INT AUTO_INCREMENT NOT NULL, group_id INT NOT NULL, subgroup_id INT NOT NULL, relation_type INT NOT NULL, INDEX group_id (group_id), INDEX subgroup_id (subgroup_id), INDEX relation_type (relation_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE group_rel_tag (id INT AUTO_INCREMENT NOT NULL, tag_id INT NOT NULL, group_id INT NOT NULL, INDEX group_id (group_id), INDEX tag_id (tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE group_rel_user (id INT AUTO_INCREMENT NOT NULL, group_id INT NOT NULL, user_id INT NOT NULL, relation_type INT NOT NULL, INDEX group_id (group_id), INDEX user_id (user_id), INDEX relation_type (relation_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE groups (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, picture_uri VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, visibility INT NOT NULL, updated_on VARCHAR(255) NOT NULL, created_on VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
```

Al ejecutar la salida SQL en el PHPMyAdmin de la base de datos nos daba un error de campo inexistente en la línea 9

```
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
```
Ejecutando después php bin/doctrine.php orm:schema-tool:update --dump-sql genero de nuevo la salida en el archivo **diff2.txt** e inserto el contenido en el PHPMyAdmin.

Al ejecutar de nuevo php bin/doctrine.php orm:schema-tool:update --dump-sql ya muestra
`Nothing to update - your database is already in sync with the current entity metadata.`

Se adjunta archivo error_log de la actualización del servidor Apache y resultado de ejecutar sobre la 1.11.6 dev php bin/doctrine.php orm:schema-tool:update --dump-sql

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo 1.10.8
Chamilo 1.11.6 dev

Saludos.
[error_log-Apache110a111.txt](https://github.com/chamilo/chamilo-lms/files/1441021/error_log-Apache110a111.txt)
[Chamilo-log 1.10 a 1.11.txt](https://github.com/chamilo/chamilo-lms/files/1441022/Chamilo-log.1.10.a.1.11.txt)

[diff2.txt](https://github.com/chamilo/chamilo-lms/files/1441025/diff2.txt)
[diff1.txt](https://github.com/chamilo/chamilo-lms/files/1441026/diff1.txt)

**Comment by ywarnier** [comment]
El commit anterior por ahora solo soluciona los 3 queries iniciales.
Según mi investigación, el problema proviene de la introducción de Entities de Symfony (o mejor dicho de Doctrine) dentro de Chamilo.
Cuando antes teníamos un enlace directo entre el query SQL y la base de datos, ahora tenemos un intermedio (que tiene como objetivo deshacernos del vínculo fuerte con MySQL) que es la definición de los datos ORM en los entities, como aquí: 
https://github.com/chamilo/chamilo-lms/blob/1.11.x/src/Chamilo/CoreBundle/Entity/Skill.php#L89

De ahí Doctrine "gestiona" la creación de índices y foreign keys, y se nos escapa (un poco) de las manos.
También es Doctrine que se encarga del orm:schema-tool:update, por lo que si Doctrine ve un índice en una tabla, que no tiene una descripción dentro del Entity, considera que está demás, e intenta borrarlo.
Esto es lo que nos da:
```
DROP INDEX c_id ON course_rel_user_catalogue;
```
en vuestro diff2.txt, por ejemplo. Este índice debería estar ahí, porque ayuda en términos de eficiencia, pero como no tiene una declaración explícita aquí:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/src/Chamilo/CoreBundle/Entity/CourseRelUserCatalogue.php#L48
...pues no considera que sea necesario y lo elimina.

Para corregir esto, hay un trabajo considerable que hacer de revisión de todos estos queries reportados por orm:schema-tool:update, pero creo que vale la pena porque ahora estamos generando incoherencias numerosas (aunque sin impacto mayor en muchos casos) entre distintas instalaciones de Chamilo.

**Comment by ywarnier** [comment]
Marco esto como "Requires structure change" aunque técnicamente no sea un "require", porque tiene que ver con la estructura en todo caso.

**Comment by nosolored** [comment]
Muchas gracias.

Hemos utilizado el último código de Github de hoy y repetido la migración sobre la misma instalación 1.10 siguiendo el mismo proceso descrito anteriormente. Se adjunta resultados en ficheros adjuntos.

En la instalación de 1.10 se aplicado el último código de Github y ejecutado el Doctrine. Se ha insertado en la base de datos el cambio que indicaba

ALTER TABLE c_quiz CHANGE start_time start_time DATETIME DEFAULT NULL, CHANGE end_time end_time DATETIME DEFAULT NULL;

======
Consultas:
======
¿Después de actualizar Chamilo 1.10 a 1.11 es aconsejable aplicar después los cambios que indica el Doctrine en la base de datos?
¿Se debería insertar esas sentencias SQL en los ficheros de migración Migrations/Schema/ para que proceso de actualización los aplicara?

Según el Doctrine se no se han creado las 4 tablas indicadas anteriormente (se adjunta archivo Chamilo111-doctrine.txt con la salida que genera en consola).

CREATE TABLE group_rel_group ...
CREATE TABLE group_rel_tag ...
CREATE TABLE group_rel_user ...
CREATE TABLE groups ...

Las hemos creado en la base de datos y hemos insertado el código SQL del fichero Chamilo111-doctrine.txt eliminando previamente todas las sentencias relacionadas con índices como 
DROP INDEX
DROP INDEX UNIQ
CREATE INDEX
... AD CONSTRAINT

No las hemos aplicado porque al hacerlo muestra algún error indicando que ya existe el índice, que no es posible cambiarlo, etc.

El archivo índices muestra el resultado final de ejecutar php bin/doctrine.php orm:schema-tool:update --dump-sql 

Un saludo.
[indices.txt](https://github.com/chamilo/chamilo-lms/files/1562396/indices.txt)
[Chamilo111-doctrine.txt](https://github.com/chamilo/chamilo-lms/files/1562397/Chamilo111-doctrine.txt)
[error.log](https://github.com/chamilo/chamilo-lms/files/1562398/error.log)

**Comment by nosolored** [comment]
Os marco aviso a @ywarnier y a @jmontoyaa

**Comment by ywarnier** [comment]
A raíz de esta tarea, se agregó la sección siguiente a las convenciones de código: https://github.com/chamilo/chamilo-lms/wiki/Coding-conventions#entities

Sin embargo, y después de un detallado análisis de las capabilidades de Doctrine, cambiar la definición en los entities *ahora* para corregir los problemas de DROP INDEX solo causaría más daño que lo que repara, por lo que he decidido postergarla para la versión 2.0, el objetivo siendo tener todos los índices nombrados de una manera más coherente.

Ahora estoy revisando los demás queries que no se vieron ejecutados en la migración en base a sus archivos diff1 y 2.

**Comment by ywarnier** [comment]
Sobre tus consultas:
 - ¿Después de actualizar Chamilo 1.10 a 1.11 es aconsejable aplicar después los cambios que indica el Doctrine en la base de datos?
 -- Sí, es aconsejable
 - ¿Se debería insertar esas sentencias SQL en los ficheros de migración Migrations/Schema/ para que proceso de actualización los aplicara?
 -- Sí, esto es lo que estoy viendo ahora, pero es un proceso delicado (toma tiempo). El proceso es verificar el cambio propuesto por doctrine y luego ver si algo en Schema intenta aplicarlo. De no ser el caso, se añade como una migration nueva.

**Comment by ywarnier** [comment]
En lo que se refiere a las tablas groups, group_rel_group, group_rel_tag y group_rel_user, estas fueron específicamente eliminadas en 

https://github.com/chamilo/chamilo-lms/blob/7621d9e42e7ca2d7537196bd4fcb21af7b827fb6/app/Migrations/Schema/V111/Version111.php#L153-L156

Tampoco existen como entidades en 1.11, por lo que parece que el problema es que, al aplicar el código de la 1.11 por encima de la 1.10 (proceso recomendado, ya lo se) en vez de hacer un git pull de la nueva rama, el proceso deja estos archivos (entre otros src/Chamilo/CoreBundle/Entity/GroupRelGroup.php) ahí, lo cual hace que Doctrine piense que las tablas correspondientes tienen que existir.

He corregido esta parte con el commit indicado arriba.

**Comment by ywarnier** [comment]
El resto de los queries de cambios de tablas ha sido enviado en https://github.com/chamilo/chamilo-lms/commit/8d019c0431a06bb4144feed7fc01c1baa2329166 pero me equivoqué de referencia, apunté a otra tarea

**Comment by ywarnier** [comment]
https://github.com/chamilo/chamilo-lms/commit/8d019c0431a06bb4144feed7fc01c1baa2329166

**Comment by ywarnier** [comment]
Con esto solo faltaría nombrar los índices, que tengo que dejar para la v2.0.
Os dejo probar una migración de 1.10 a 1.11. Deberían quedar solamente cosas de índices y foreign keys en `php bin/doctrine.php orm:schema-tool:update --dump-sql` algo así:
```
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT FK_79CA412EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT FK_79CA412E91D79BD3 FOREIGN KEY (c_id) REFERENCES course (id);
DROP INDEX user_id ON course_rel_user_catalogue;
CREATE INDEX IDX_79CA412EA76ED395 ON course_rel_user_catalogue (user_id);
DROP INDEX c_id ON course_rel_user_catalogue;
CREATE INDEX IDX_79CA412E91D79BD3 ON course_rel_user_catalogue (c_id);
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT course_rel_user_catalogue_ibfk_1 FOREIGN KEY (c_id) REFERENCES course (id) ON DELETE CASCADE;
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT course_rel_user_catalogue_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE language DROP FOREIGN KEY language_parent;
DROP INDEX language_parent ON language;
CREATE INDEX IDX_D4DB71B5727ACA70 ON language (parent_id);
ALTER TABLE language ADD CONSTRAINT language_parent FOREIGN KEY (parent_id) REFERENCES language (id);
CREATE INDEX idx_message_user_receiver_status ON message (user_receiver_id, msg_status);
ALTER TABLE skill_rel_user_comment ADD CONSTRAINT FK_7AE9F6B6484A9317 FOREIGN KEY (skill_rel_user_id) REFERENCES skill_rel_user (id);
ALTER TABLE skill_rel_user_comment ADD CONSTRAINT FK_7AE9F6B63AF3B65B FOREIGN KEY (feedback_giver_id) REFERENCES user (id);
CREATE INDEX IDX_7AE9F6B6484A9317 ON skill_rel_user_comment (skill_rel_user_id);
CREATE INDEX IDX_7AE9F6B63AF3B65B ON skill_rel_user_comment (feedback_giver_id);
CREATE INDEX idx_select_su_giver ON skill_rel_user_comment (skill_rel_user_id, feedback_giver_id);
CREATE INDEX user_sco_course_sv ON track_stored_values (user_id, sco_id, course_id, sv_key);
CREATE INDEX user_sco_course_sv_stack ON track_stored_values_stack (user_id, sco_id, course_id, sv_key, stack_order);
DROP INDEX UNIQ_8D93D64992FC23A8 ON user;
CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username);
DROP INDEX exercice ON c_quiz_rel_question;
CREATE INDEX exercise ON c_quiz_rel_question (exercice_id);
DROP INDEX idx_ctool_name ON c_tool;
ALTER TABLE skill_level ADD CONSTRAINT FK_BFC25F2FCCFA12B8 FOREIGN KEY (profile_id) REFERENCES skill_level_profile (id);
CREATE INDEX IDX_BFC25F2FCCFA12B8 ON skill_level (profile_id);
```

**Comment by nosolored** [comment]
Hola @ywarnier y @jmontoyaa 
He simulado la migración de Chamilo 1.10 a 1.11.x con el último código del github y muestra el error siguiente en ...main/install/index.php?running=1&installType=update&updateFromConfigFile=app%2Fconfig%2Fconfiguration.php

```
ERROR: An exception occurred while executing 'ALTER TABLE language CHANGE id id INT AUTO_INCREMENT NOT NULL':
SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'language_parent' of table 'chamilo.language'
```

ese sentencia está en el fichero app/Migrations/Schema/V111/Version20171227120000.php en la línea 37.

**Comment by ywarnier** [comment]
OK, ya está listo para otra prueba.
Es probable que falle lo mismo sobre category_id un poco más a bajo.

**Comment by nosolored** [comment]
Hola @ywarnier / @jmontoyaa 
realizada la migración con el último código del github se realiza sin mostrar errores y finaliza en pantalla con DONE!
El resultado de ejecutar php bin/doctrine.php orm:schema-tool:update --dump-sql muestra lo siguiente:

```
CREATE TABLE group_rel_group (id INT AUTO_INCREMENT NOT NULL, group_id INT NOT NULL, subgroup_id INT NOT NULL, relation_type INT NOT NULL, INDEX group_id (group_id), INDEX subgroup_id (subgroup_id), INDEX relation_type (relation_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE group_rel_tag (id INT AUTO_INCREMENT NOT NULL, tag_id INT NOT NULL, group_id INT NOT NULL, INDEX group_id (group_id), INDEX tag_id (tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE group_rel_user (id INT AUTO_INCREMENT NOT NULL, group_id INT NOT NULL, user_id INT NOT NULL, relation_type INT NOT NULL, INDEX group_id (group_id), INDEX user_id (user_id), INDEX relation_type (relation_type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE groups (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, picture_uri VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, visibility INT NOT NULL, updated_on VARCHAR(255) NOT NULL, created_on VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE course_category CHANGE auth_course_child auth_course_child VARCHAR(40) DEFAULT NULL;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_1;
ALTER TABLE course_rel_user_catalogue DROP FOREIGN KEY course_rel_user_catalogue_ibfk_2;
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT FK_79CA412EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id);
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT FK_79CA412E91D79BD3 FOREIGN KEY (c_id) REFERENCES course (id);
DROP INDEX user_id ON course_rel_user_catalogue;
CREATE INDEX IDX_79CA412EA76ED395 ON course_rel_user_catalogue (user_id);
DROP INDEX c_id ON course_rel_user_catalogue;
CREATE INDEX IDX_79CA412E91D79BD3 ON course_rel_user_catalogue (c_id);
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT course_rel_user_catalogue_ibfk_1 FOREIGN KEY (c_id) REFERENCES course (id) ON DELETE CASCADE;
ALTER TABLE course_rel_user_catalogue ADD CONSTRAINT course_rel_user_catalogue_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE;
ALTER TABLE language DROP FOREIGN KEY language_parent;
ALTER TABLE language CHANGE id id INT AUTO_INCREMENT NOT NULL;
DROP INDEX language_parent ON language;
CREATE INDEX IDX_D4DB71B5727ACA70 ON language (parent_id);
ALTER TABLE language ADD CONSTRAINT language_parent FOREIGN KEY (parent_id) REFERENCES language (id);
CREATE INDEX idx_message_user_receiver_status ON message (user_receiver_id, msg_status);
ALTER TABLE skill_rel_user_comment ADD CONSTRAINT FK_7AE9F6B6484A9317 FOREIGN KEY (skill_rel_user_id) REFERENCES skill_rel_user (id);
ALTER TABLE skill_rel_user_comment ADD CONSTRAINT FK_7AE9F6B63AF3B65B FOREIGN KEY (feedback_giver_id) REFERENCES user (id);
CREATE INDEX IDX_7AE9F6B6484A9317 ON skill_rel_user_comment (skill_rel_user_id);
CREATE INDEX IDX_7AE9F6B63AF3B65B ON skill_rel_user_comment (feedback_giver_id);
CREATE INDEX idx_select_su_giver ON skill_rel_user_comment (skill_rel_user_id, feedback_giver_id);
CREATE INDEX user_sco_course_sv ON track_stored_values (user_id, sco_id, course_id, sv_key);
CREATE INDEX user_sco_course_sv_stack ON track_stored_values_stack (user_id, sco_id, course_id, sv_key, stack_order);
DROP INDEX UNIQ_8D93D64992FC23A8 ON user;
CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON user (username);
DROP INDEX exercice ON c_quiz_rel_question;
CREATE INDEX exercise ON c_quiz_rel_question (exercice_id);
DROP INDEX idx_ctool_name ON c_tool;
ALTER TABLE skill_level ADD CONSTRAINT FK_BFC25F2FCCFA12B8 FOREIGN KEY (profile_id) REFERENCES skill_level_profile (id);
CREATE INDEX IDX_BFC25F2FCCFA12B8 ON skill_level (profile_id);
```
Hemos aplicado en la base de datos todas las sentencias SQL excepto las indicadas de CREATE TABLE.

**Comment by ywarnier** [comment]
Sí, en concreto, durante la migración debería haber borrado las entidades (groups, group_rel_group, group_rel_tag y group_rel_user) pero probablemente no pudo por falta de permisos sobre la carpeta src/Chamilo/. Debería haber reportado el problema en el error_log.

De ahí lo que queda son cosas de INDEX y FK, lo cual no importa para la migración. Puede tener un impacto sobre la eficiencia, pero en este caso ejecutar el bin/doctrine con --force en vez de --dump-sql es un paso aceptable en consideración de la complejidad de hacer otra cosa por ahora dentro de 1.11.6.

**Comment by nosolored** [comment]
¿Se debería mientras tanto mostrar un aviso previo en la migración para que se eliminen manualmente esas carpetas de src/Chamilo?
al igual que ocurre cuando se muestra el aviso de eliminar las carpetas
/main/exercice
/main/newscorm
/plugin/skype
/plugin/ticket

para así continuar la actualización de Chamilo 1.10 a 1.11 y luego utilizar php bin/doctrine.php orm:schema-tool:update --dump-sql para insertar los índices manualmente en la base de datos.

Probaremos también la opción php bin/doctrine.php orm:schema-tool:update --force --dump-sql

La carpeta que indicas src/Chamilo/ no tiene problemas de permisos por lo que si debe eliminarse en la actualización no tendría problemas en que el proceso la borre o muestre un aviso el error_log.

La última prueba la hemos realizado en un servidor Windows que también usamos con otros software que también crean/eliminan carpetas.

Cuando reportamos habitualmente realizamos pruebas en distintos equipos locales (Windows), máquinas virtuales con Ubuntu y en servidores Debian con permisos/usuarios/grupos más restrictivos como 700 para directorios y 600 para archivos.

¿Necesitáis que realizaremos más pruebas de migración?

**Comment by ywarnier** [comment]
De nuevo es un poco complicado hacer esto, porque entre otras cosas el instalador avisa sobre el borrado de 4 carpetas. Sin embargo, la carpeta src/Chamilo no puede ser borrada. A penas 4 archivos de varios cientos tienen que ser eliminados, pero los términos de idioma mencionan "carpetas".

Aquí he puesto el código para eliminar estos archivos de manera automática. Los permisos tienen que permitir que el usuario web (www-data en Debian/Ubuntu) borre estos 4 archivos. Al finalizar la actualización, deberías poder verificar si estos archivos están ahí o no (no deberían).

https://github.com/chamilo/chamilo-lms/blob/c94f7cf2f92799d27ca5140d7f7461c2c3ca15b1/main/install/update-files-1.10.0-1.11.0.inc.php#L47-L62

**Comment by nosolored** [comment]
Hemos realizado pruebas adicionales de migración.

En /main/install el instalador muestra el aviso de la existencia de
/main/exercice/
/main/newscorm/
/plugin/ticket/
/plugin/skype/

pero no permite avanzar ya que el botón de "Actualizar la versión de Chamilo LMS" no está activo. Sólo se muestra si eliminas previamente esas carpetas manualmente. Al hacerlo si es posible continuar.

Si en el fichero /main/install/install.lib.php comentamos la línea 1135

//$error = true;

permite continuar ya que el botón si está activo.

Al finalizar este proceso si elimina los directorios
/main/exercice/
/main/newscorm/
/plugin/ticket/
/plugin/skype/

pero no los archivos
src/CoreBundle/Entity/Groups.php
src/CoreBundle/Entity/GroupRelGroup.php
src/CoreBundle/Entity/GroupRelTag.php
src/CoreBundle/Entity/GroupRelUser.php

que se muestran en update-files-1.10.0-1.11.0.inc.php

Hemos insertado código para ver el valor que toma api_get_path(SYS_PATH) en el error_log y lo muestra vacío.
sys_path: SYS_PATH, referer: http://..../main/install/index.php?running=1&installType=update&updateFromConfigFile=app%2Fconfig%2Fconfiguration.php

**Comment by ywarnier** [comment]
@jmontoyaa te podrías encargar de verificar si Chamilo puede borrar las carpetas (is_writeable() de la carpeta de nivel superior) para decidir si bloquear el botón o no?

Lo de los archivos Entity no lo vamos a indicar. Solo genera un problema para los que usan versiones de desarrollo de Chamilo.

Luego no cierres la tarea, pásala a 2.0.

**Comment by jmontoyaa** [comment]
Pero no entiendo el problema de las carpetas:

/main/exercice/
/main/newscorm/
/plugin/ticket/
/plugin/skype/

Está bien que bloquée la actualización, esas carpetas no deberían de existir. Y el mensaje indica que deberían ser eliminadas or renombradas ...

**Comment by nosolored** [comment]
Ya existe código que elimina esas carpetas al final de la migración de 1.10 a 1.11.

En /main/install se chequea la existencia de esos directorios. No permite avanzar hasta que se eliminan.

Revisando en /main/install/install.lib.php en la línea 1135 existe una variable 
`$error = true;`
que si se comenta a
`//$error = true;`
permite continuar la actualización a Chamilo 1.11. Sigue mostrando el mensaje pero permite actualizar ya que se activa el botón de actualizar.

En ../main/install/update-files-1.10.0-1.11.0.inc.php existe código para eliminar los directorios con rmdir (línea 20 a 45).

```
/main/exercice/
/main/newscorm/
/plugin/ticket/
/plugin/skype/
```
En la prueba realizada no se eliminaron previamente esos directorios y el proceso de actualización los borró posteriormente.

Para los ficheros src no los elimina ya envíe la ruta con un error (es necesario añadir /Chamilo). Disculpad.

```
src/**Chamilo**/CoreBundle/Entity/Groups.php
src/**Chamilo**/CoreBundle/Entity/GroupRelGroup.php
src/**Chamilo**/CoreBundle/Entity/GroupRelTag.php
src/**Chamilo**/CoreBundle/Entity/GroupRelUser.php
```

En https://github.com/chamilo/chamilo-lms/blob/c94f7cf2f92799d27ca5140d7f7461c2c3ca15b1/main/install/update-files-1.10.0-1.11.0.inc.php#L47-L62 

hay que revisar la ruta ya que muestra

```
api_get_path(SYS_PATH).'src/CoreBundle/Entity/Groups.php',
api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelGroup.php',
api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelTag.php',
api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelUser.php'
```
y añadir la ruta correcta.

**Comment by jmontoyaa** [comment]
Acabo de agregar una correción para no bloquer el upgrade.

No entiendo el error de:

"api_get_path(SYS_PATH).'src/CoreBundle/Entity/Groups.php'"

Esta ruta si debería de existir ...

Si no puede ser eliminado entonces hay un error log:
```

$entitiesToRemove = [
        api_get_path(SYS_PATH).'src/CoreBundle/Entity/Groups.php',
        api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelGroup.php',
        api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelTag.php',
        api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelUser.php'
    ];
    foreach ($entitiesToRemove as $entity) {
        if (file_exists($entity)) {
            $success = unlink($entity);
            if (!$success) {
                error_log('Could not delete '.$entity.', probably due to permissions. Please delete manually to avoid entities inconsistencies');
            }
        } else {
            error_log('Could not delete. It seems the file '.$entity.' does not exists.');
        }
    }
```

**Comment by nosolored** [comment]
Las líneas 49 a 52 del archivo **main/install/update-files-1.10.0-1.11.0.inc.php**

api_get_path(SYS_PATH).'src/CoreBundle/Entity/Groups.php',
api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelGroup.php',
api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelTag.php',
api_get_path(SYS_PATH).'src/CoreBundle/Entity/GroupRelUser.php'

deben ser cambiadas

a

api_get_path(SYS_PATH).'src/Chamilo/CoreBundle/Entity/Groups.php',
api_get_path(SYS_PATH).'src/Chamilo/CoreBundle/Entity/GroupRelGroup.php',
api_get_path(SYS_PATH).'src/Chamilo/CoreBundle/Entity/GroupRelTag.php',
api_get_path(SYS_PATH).'src/Chamilo/CoreBundle/Entity/GroupRelUser.php'

Ya que falta /Chamilo/ en la ruta y por eso no los borra.

**Comment by ywarnier** [comment]
Ah pues sí. No lo había visto. Enviado!

**Comment by ywarnier** [comment]
La muevo a 2.0 para lo que queda.

**Comment by ywarnier** [comment]
Creo que hemos terminado aquí...
