### ISSUE TITLE
Log the deletion of user results in exercises

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2215]
### Current behavior
When a teacher goes to the results page of an exercise and deletes a student attempt, this is not registered in track_e_default and does not appear on main/tracking/course_log_resources.php?cidReq=INTRODUCCIONAGROLINO&id_session=0 (the tracking page of the course itself, "Informe sobre recursos")

### Expected behavior
Deletion of any exercise result (or learning path result/progress) should log this action in the resources log (track_e_default).

### Steps to reproduce
- create a quiz
- take the quiz
- delete your results
- go to resources report in the course
- no log shows the result was deleted

### Chamilo Version
1.11.x

**Comment by marshel** [comment]
+suggestion,
 When removing a Exercise from LP also do not auto delete the results (at least without a prompt).

**Comment by jmontoyaa** [comment]
That page "course_log_resources.php" shows only contents from the "item property" table, not from "track_e_default".

The data of "track_e_default" appears here: /main/admin/statistics/index.php?report=activities

**Comment by ywarnier** [comment]
You're right. This should still go into track_e_default though. So we need an additional page in the course statistics page (under the "important activities" link, something saying "Global activities affecting this course")

**Comment by jmontoyaa** [comment]
I added the page here:

https://11.chamilo.org/main/tracking/course_log_events.php?cidReq=01&id_session=0&gidReq=0&gradebook=0&origin=

Some questions about:

- Title of that page (Course logs ?)
- And the icon that represents it ("default.png" ?)

**Comment by ywarnier** [comment]
I'll see about the icon with Alex.
For the title, inside the context of the course, this should be "Audit report"
$EventsReport = "Audit report";
$EventsReport = "Reporte de auditoría";
$EventsReport = "Rapport d'audit";

**Comment by ywarnier** [comment]
OK, so now the page is fine but the deletion of the exercise results does not appear in the list (probably not in track_e_default either). Could you add it, pretty please? :smile:

**Comment by ywarnier** [comment]
Oh, and also: it is showing events from other courses. Only the current course (and session if any) please.

**Comment by jmontoyaa** [comment]
I have the event saved as "exe_attempt_deleted". Maybe you didn't see it because of the table order.
Now I changed it in order to order it by date.

**Comment by jmontoyaa** [comment]
Can you provide a link with that error? I cannot reproduce it. The api_get_cidReq is always sent.

**Comment by ywarnier** [comment]
OK, so exercise results do appear now, so that's one point.

**Comment by ywarnier** [comment]
I have the creation of other courses that appear in my list.
![course](https://user-images.githubusercontent.com/609839/34044309-7fa20a50-e172-11e7-8cc2-aba5027a0c8e.png)
I haven't checked on 11.chamilo.org just yet but maybe that screenshot helps?

**Comment by jmontoyaa** [comment]
Your track_default  table could have old information.

**Comment by ywarnier** [comment]
...which relates to the same course c_id, yes, that might be.
Yes, apparently that's the case... mmmm... that's interesting, because it means we're facing a new issue (for 2.0, that is).
OK, then I'm good with this development, thanks!
