### ISSUE TITLE
Problema con al finalizar un ejercicio.

### ISSUE THREAD

**Issue by acerdasq** [chamilo/chamilo-lms#2218]
### Current behavior / Resultado actual / Résultat actuel
Cuando se trata de terminar un ejercicio, justo a la par del botón de terminar se muestra una imagen de error (wrong.gif) no da ningún mensaje o código de error, simplemente no avanza más y no deja terminar el ejercicio.

### Expected behavior / Resultado esperado / Résultat attendu
El resultado correcto recibir la retroalimentación de las respuestas dadas y la calificación final.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1. Crear un ejercicio nuevo, agregar una pregunta y respuesta.
2. Ir al curso e iniciar el ejercicio.
3. Colocar las respuestas requeridas.
4. Presionar el botón de "Terminar Ejercicio."

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

![configuracion del ejercicio](https://user-images.githubusercontent.com/33468272/32520766-bb9ea342-c3d6-11e7-8ba0-6e1bf8118d52.PNG)

![error en el ejercicio](https://user-images.githubusercontent.com/33468272/32520798-e59f62ee-c3d6-11e7-878c-50437af67768.PNG)

**Comment by ywarnier** [comment]
Hola @acerdasq,
Este problema suele ocurrir por causas relativas al servidor mismo, en el cual la consulta AJAX (JavaScript) que se manda al servidor cuando presionas el botón no resulta en una respuesta exitosa.
Puedes analizar más sobre el problema leyendo los logs de PHP (usualmente dentro de los logs de Apache, el servidor web).
Con la información proveida hasta el momento, no podremos solucionar este problema. Es demasiado incompleta.

**Comment by symphodus** [comment]
Hola @ywarnier actualmente tengo el mismo problema, ya verifique con soporte del servidor pero todo esta bien, les comente lo que tu comentaste en la ultima respuesta, intente actualizar chamilo, pero no fue posible, el estado de actualización de la version menciona"Su versión está actualizada: Chamilo HTTP/1.1 404 Not Found Server: nginx/1.6.2 Date: Fri, 26 Oct 2018 02:02:17 GMT Content-Type: text/html Content-Length: 168 Connection: keep-alive
404 Not Found
nginx/1.6.2"
Si me pudieras ayudar, guíame con la información necesaria a proveerte.

**Comment by ywarnier** [comment]
Puedes mirar en [tu-url]/documentation/changelog.html cual es la primera versión de Chamilo que te aparece en la página?

**Comment by symphodus** [comment]
es "Chamilo 1.11.4 - Uyuni, 31st of May 2017"

**Comment by ywarnier** [comment]
Si puedes, actualiza a Chamilo 1.11.8, debería solucionar este problema.
Si no puedes o no lo soluciona, obtener los logs de errores de Apache nos ayudará a determinar la causa exacta.
