### ISSUE TITLE
Announcements: to and from fields should be kept sorted

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#2226]
### Current behavior / Resultado actual / Résultat actuel
when you move receipieants (groups and users) from the left to right select box and back they are at the end of the list.
### Expected behavior / Resultado esperado / Résultat attendu
groups first, names after that and sorted alphabeticaly.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
move some receipiants from left to right and back and to the right again. Unsorted
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x git november 20 2017

I have a PR for this fix:
https://github.com/chamilo/chamilo-lms/pull/2224

**Comment by jmontoyaa** [comment]
Should be fixed with:
https://github.com/chamilo/chamilo-lms/commit/80aa54d5839e6ce649c895378a96ec9b958881b5

**Comment by ywarnier** [comment]
Tested and approved
