### ISSUE TITLE
Unable to create folder in course from ckEditor

### ISSUE THREAD

**Issue by baelmyhu** [chamilo/chamilo-lms#2231]
### Current behavior / Resultado actual / Résultat actuel
Got error message "Unable to create folder" in course directory from ckEditor, from image upload popup, for exemple.

See https://content.screencast.com/users/hborderi/folders/Jing/media/d3b59ad7-024f-427f-99ff-bd5c530e59b0/2017-11-28_1714.png

It works in the "Mes fichiers" area
I tried to put all my -R app/courses directory in 777, but it is the same error.

### Expected behavior / Resultado esperado / Résultat attendu
Able to create folder from ckEditor

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Go to New Document in Document tool > Add new Document > Upload image > in ckEditor path choose the course, not the user folder > right click  New folder

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by ywarnier** [comment]
@baelmyhu, tu as pu tester si le patch de @jmontoyaa fonctionnait?

**Comment by bassuma** [comment]
Hello.
I use this patch.
https://github.com/chamilo/chamilo-lms/issues/2231
And he's working very well.
![before](https://user-images.githubusercontent.com/25286516/33626121-d311cf7a-d9e0-11e7-8849-1f75e59e58b4.PNG)

![after](https://user-images.githubusercontent.com/25286516/33626136-d82271e0-d9e0-11e7-84ce-e33982357a57.PNG)

Thank you

**Comment by AulaBit** [comment]
yes it works! thanks
