### ISSUE TITLE
Desaparecen archivos y cambios realizados en días anteriores

### ISSUE THREAD

**Issue by betocustom** [chamilo/chamilo-lms#2235]
### Current behavior / Resultado actual / Résultat actuel
Me había pasado en días anteriores que realizaba cambios en algún contenido como lección y luego al día siguiente no lo veía, como estaba haciendo muchos cambios asumía que yo estaba equivocado y  "me había parecido" haberlo hecho, pero hoy ya fue muy evidente.
Resulta que veo contenidos antiguos en algunas lecciones que había modificado días atrás y no veo los nuevos, es más, han desaparecido carpetas físicas y archivos (desde apache).
Tenía toda una serie de videos en 6 lecciones, ahora sólo tengo videos en 3 de ellas..  como si hubiera vuelto atrás 1 semana de trabajo aproximadamente.
He reportado esto a mi proveedor  Jelastic (nube SaaS), donde alojo mi chamilo, dado por que pareciera que se hubiera restaurado un respaldo de hace unos días atrás.
pero de todas formas lo publico acá por si a alguien le ha pasado algo similar, me sería de mucha ayuda cualquier comentario o información que me ayude a esclarecer que está pasando.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Mi chamilo indica tener La última actualizada: 1.11.0.6

**Comment by ywarnier** [comment]
Hola @betocustom, no parece que Chamilo tenga algo que ver en lo que reportas. Efectivamente, si recuperas contenido anterior después de haber visualizado el cambio tu mismo, es que se restauró un backup anterior. Si el proveedor no te puede dar detalles sobre esto, un consejo: cambia de proveedor. Es importantísimo tener confianza en tu proveedor, y hemos visto en el pasado que algunos proveedores se hayan equivocado (o hayan tenido un fallo hardware) y hayan borrado el campus de nuestros usuarios, y luego hayan intentado recuperar el error sin decir nada. Esto puede volverse gravísimo en el caso de tener datos críticos ahí (como exámenes, por ejemplo).

En todo caso, Chamilo no tiene la *capacidad técnica* de recuperar datos antiguos en las lecciones, porque no almacena un historial.

Las versiones de Chamilo son 1.10.6 o 1.11.6 (esta última todavía no ha sido publicada)

**Comment by betocustom** [comment]
Gracias @ywarnier mi proveedor ya está viendo este "extraño" comportamiento.
¿Conoces Jelastic?, es un servicio que brinda ambientes en base a contenedores y dockers (Plataform-as-a-service), ahí tengo mi ambiente "academia" donde tengo mi chamilo. 
¿Será que tal vez hay incompatibilidad entre Chamilo y un servicio como este como hosting?
La arquitectura del ambiente que he "armado con contenedores" tiene las siguientes características:
1 Servidor Nginx 1.10.1 como balanceador para distribuir el tráfico en los nodos apache
1 Servidor apache 2.4.6-40, con PHP 5.6, este servidor tiene 2 nodos.
1 Servidor MySql 5,7,16

Acabo de hacer un cambio en una lección y veo que en los 2 nodos apache solo se vió reflejado el cambio en el archivo físicamente en disco sólo en 1 de ellos, en el otro permaneció la versión antigua.

¿Será que no puedo trabajar con chamilo y este tipo de plataformas, hay problemas conocidos?
Gracias nuevamente!

**Comment by ywarnier** [comment]
Hola @betocustom, bueno, aquí vienes con *mucho más* información que en tu post inicial, y esto cambia todo el contexto y mis conclusiones rápidas anteriores.

No hay ningún conflicto ni incompatibilidad con Docker. El problema aquí es que cuando quieras usar 2 nodos de cualquier sistema web que *grabe* en un disco, tienes que tener un disco compartido entre estos 2 nodos. No puedes dejarlos grabar en su propio disco cada uno.

Esto se llama un "volumen" y es un contenedor distinto. Aquí puedes encontrar un ejemplo de implementación: https://hub.docker.com/r/chamilo/docker-chamilo/

**Comment by betocustom** [comment]
Gracias de nuevo @ywarnier,la verdad al inicio no aporté tanto por pensar que el problema era tan sólo por que habían restaurado algún backup de días anteriores por error. Ahora bien, aunque desconocía lo que me indicas si lo entiendo, he visto un "contenedor de almacenamiento" en la interfaz donde uno configura su ambiente, pensaba que era sólo para agregar espacio adicional.
En estricto rigor no estoy usando docker así que al parecer no me será tan sencillo apuntar a este "almacenamiento" compartido, bueno espero que con la ayuda de soporte lo pueda lograr y sólo sea ese mi problema. De todas formas esto no explica el hecho de que desaparecieron carpetas y archivos, en ninguno de los 2 nodos se ven reflejados.
¿Tienen fecha para liberar ese docker-chamilo?

**Comment by ywarnier** [comment]
No hay plan para liberar docker-chamilo, no, está todavía en pañales y tenemos otras prioridades por ahora. Nuestro plan en lo inmediato es publicar Chamilo 1.11.6 y después trabajar en la 2.0. La imagen de contenedor docker es un proyecto paralelo pero no prioritario. Debería estar involucrado @jwarnier en esto también.

**Comment by betocustom** [comment]
Entiendo lo del docker estimado, ¿y tienen fecha para las 1.11.16? (no te quiero presionar.. jeje).

**Comment by ywarnier** [comment]
Esperamos que 1.11.6 salga la semana del 15/12. Es solo una esperanza, no un compromiso. En software libre, el software está listo cuando... está listo, no cuando hay una fecha que definir, porque una versión estable tiene que ser estable y no se controlan todos los aspectos.
