### ISSUE TITLE
Assignments: added documents displays incorrect in student view

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#2237]
### Current behavior / Resultado actual / Résultat actuel
when you add a document to an assignment, in student view this will show up in the list of uploads from the student and it will mess up the table (i.e. columns, buttons behind an upload change (i.e. correct and rate instead of view)).

Here's a student view with an added document
![image](https://user-images.githubusercontent.com/15210140/33659933-5692e40a-da82-11e7-8c35-1ae86209586f.png)

Here's a student view without an added document
![image](https://user-images.githubusercontent.com/15210140/33660112-fccb3246-da82-11e7-9c50-1811be7965b6.png)

### Expected behavior / Resultado esperado / Résultat attendu
Student view should be like teacher's view, with document(s) listed beneath the decription :
![image](https://user-images.githubusercontent.com/15210140/33660005-a5847164-da82-11e7-985e-4c36b6cb0a57.png)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
create assignment > add document > view as a student

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 (tested on 11.chamilo.org)

**Comment by jmontoyaa** [comment]
Thanks for the report. I added a fix. It can be tested in: 

https://11.chamilo.org/ (admin/admin)

**Comment by annickvdp** [comment]
The added document still shows up in the student's uploads:
![image](https://user-images.githubusercontent.com/15210140/33838715-954c6254-de90-11e7-8312-265079b83925.png)

But that's not a big issue. Thanks for the fix!

**Comment by jmontoyaa** [comment]
Yes, that's correct. That document (cvo-volt-logo.png) works as a "template" of the students task.
That's why there's a green "plus icon".

**Comment by annickvdp** [comment]
OK, makes sense ;-)
