### ISSUE TITLE
wiki: print button returns blank screen

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#2238]
### Current behavior / Resultado actual / Résultat actuel
print button for a Wiki page returns a blank screen

### Expected behavior / Resultado esperado / Résultat attendu
wiki page content in screen 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
create a wiki page and click the print button

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 (tested on 11.chamilo.org in Chrome)

**Comment by ywarnier** [comment]
@annickvdp hopefully you could test it and let us know by next Monday?

**Comment by nosolored** [comment]
Nosotros lo hemos probado en https://11.chamilo.org y funciona bien

**Comment by annickvdp** [comment]
perfect! It works
