### ISSUE TITLE
php_errors.log: SQLSTATE[42000]: Syntax error or access violation

### ISSUE THREAD

**Issue by betocustom** [chamilo/chamilo-lms#2240]
### Current behavior / Resultado actual / Résultat actuel
A pesar de que no se manifiesta un error en el uso de chamilo (por lo mismo no he podido identificar que produce esto), revisando los archivos de log de apache me doy cuenta que se registran los siguientes mensajes de error en el archivo php_errors.log:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
[07-Dec-2017 00:14:54 UTC] An exception occurred while executing 'SELECT * FROM c_lp
WHERE id = '73' AND c_id = ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
[07-Dec-2017 00:15:00 UTC] An exception occurred while executing 'SELECT * FROM c_lp
WHERE id = '73' AND c_id = ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
[11-Dec-2017 02:21:30 UTC] An exception occurred while executing 'SELECT * FROM c_lp
WHERE id = '72' AND c_id = ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
[11-Dec-2017 02:21:31 UTC] An exception occurred while executing 'SELECT * FROM c_lp
WHERE id = '72' AND c_id = ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
Cargando...

### Expected behavior / Resultado esperado / Résultat attendu
Que no se registren errores en el log.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
No he identificado en que momento se produce el registro del error en el log.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by ywarnier** [comment]
Usualmente los queries de selección de Learning Path (c_lp solo) ocurren en la página de lista de lecciones, pero el hecho que no haya un c_id sugiere que el usuario está con dos pestañas distintas, una fuera de un curso y la otra dentro de un curso y tiene una navegación parcial de un lado al otro, lo cual tiene como efecto anular el c_id usado en el query.

Si llegas a identificar de donde viene, podremos corregirlo.

**Comment by jmontoyaa** [comment]
Es posible que ya haya sido corregido aqui:

https://github.com/chamilo/chamilo-lms/commit/b7bfd0940798d89c946e67137d7d6ac2ecaac553

**Comment by NicoDucou** [comment]
@betocustom dejanos saber si actualizando a Chamilo 1.11.6 los registros en el error_log dejaron de aparecer.

**Comment by ywarnier** [comment]
No hemos obtenido feedback. Cosiderando cerrada.
