### ISSUE TITLE
New user cannot upload a video file

### ISSUE THREAD

**Issue by nmeigs** [chamilo/chamilo-lms#2241]
I want to upload a video file that is my course I recorded, I am new to Chamilo and I don't see anywhere I can upload such as a SCROM so I assume I need to upload a video file in the document area for my student to view.

I use Camtasia to record, I have video file format .mp4

I see you are using FLV media player. What I know is that FLV media player should read more than 40 types of files, I am trying to upload a mp4. The system tells me there was no file chosen to upload.

How do I solve this.

I need to use video file that student look at and learn our different applications through a demo of mine.

Regards
nmeigs@logistec.com

**Comment by ywarnier** [comment]
@nmeigs this space is reserved for bug reports or features requests. For use questions, please ask on https://chamilo.org/forum and/or document yourself in our online documentation: https://docs.chamilo.org/ (there is a search box in the upper left corner).

"SCORM" means Shareable Content Object Reference Model, not SCROM (which probably does not mean anything).

You can find *SCORM*-related features in the "Learning paths" tool. See the corresponding section in our documentation referred to above.

If uploading a video, please note that the FLV uploader is specifically meant for the FLV format, NOT the MP4 format. For that, you have *another* video uploader just next to the FLV upload icon.

**Comment by nmeigs** [comment]
thank you ywarnier, but I do not see any other video uploader next to the FLV upload icon is the YouTube insert button witch requires a URL and previous to that FLV button is insert/modify an image. I have hover over all of the icons, non of them is for other video type such as mp4. (perhaps it has to do with my version(1.9.10.2) ?

**Comment by ywarnier** [comment]
Oh yes, it certainly has to do with your version! I didn't realize you had such an old one, sorry!
Yes, 1.9.10.2 is quite old in many terms, but in particular when talking about more recent video formats. I really suggest you update to a later version (1.11.6 is about to come out).

You can see a history of versions here: https://beeznest.com/blog/2011/09/27/history-of-chamilo-releases/

Updating from 1.9.10.2 to 1.11.4 or 1.11.6 is a little tedious but it should be feasible for anyone if you read the installation guide carefully: https://11.chamilo.org/documentation/installation_guide.html

**Comment by ywarnier** [comment]
Oh yes, it certainly has to do with your version! I didn't realize you had such an old one, sorry!
Yes, 1.9.10.2 is quite old in many terms, but in particular when talking about more recent video formats. I really suggest you update to a later version (1.11.6 is about to come out).

You can see a history of versions here: https://beeznest.com/blog/2011/09/27/history-of-chamilo-releases/

Updating from 1.9.10.2 to 1.11.4 or 1.11.6 is a little tedious but it should be feasible for anyone if you read the installation guide carefully: https://11.chamilo.org/documentation/installation_guide.html

Also, we do not support 1.9* versions anymore (only 1.11* and up to a certain point 1.10*).
