### ISSUE TITLE
Move all "skills" code inside main/skills

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2243]
### Current behavior / Resultado actual / Résultat actuel

Currently the skills code is in:

main/admin/
main/badge/

### Expected behavior / Resultado esperado / Résultat attendu

Code should be inside:

main/skills

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Copy and move code.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by christianbeeznest** [comment]
The request is done in this PR https://github.com/chamilo/chamilo-lms/pull/4375 , it requires more testing.

Thanks for confirmation.
