### ISSUE TITLE
terms and conditions - not working

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2244]
### Current behavior / Resultado actual / Résultat actuel
Enabling terms and conditions option is not working at all at 11.chamilo.org
In Chamilo 1.10.6 Enabling terms and conditions works only one time, and can't change it (error)

Error on version 1.10.6
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-61' for key 'PRIMARY'' in /var/sites-www/*****/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /var/sites-www/*****/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array) #1 /var/sites-www/*****/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(165): Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/sites-www/*****/main/inc/lib/database.lib.php(399): Doctrine\DBAL\Statement->execute(Array) #3 /var/sites-www/*****/main/inc/lib/legal.lib.php(44): Database::insert('legal', Array) #4 /var/sites-www/*****/main/admin/legal_add.php(68): LegalManager::add('61', '

### Expected behavior / Resultado esperado / Résultat attendu
enabling and changeing terms and conditions is working.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
11.chamilo.org ->Enable terms and conditions->create new user->log in as new user (student)
1.10.6 -> create terms and conditions->edit existing
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x (11.chamilo.org)
1.10.6

**Comment by jmontoyaa** [comment]
I cannot reproduce the error in 11.chamilo.org maybe it was already fixed?

**Comment by ywarnier** [comment]
@xam1234 could you issue the following query (and give us the results) on your Database, to check the structure of your "legal" table (which stores the legal terms):
```show create table legal;```
I believe your database, for some reason, was not properly updated. The "legal" table should have a primary key defined only on *one* field. The error message you get (Duplicate entry '0-61' for key PRIMARY) suggests there is an issue with the primary key trying to store itself as a combined 2-elements key.

My own legal table definition:
```
CREATE TABLE `legal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `date` int(11) NOT NULL,
  `content` longtext COLLATE utf8_unicode_ci,
  `type` int(11) NOT NULL,
  `changes` longtext COLLATE utf8_unicode_ci NOT NULL,
  `version` int(11) DEFAULT NULL,
  `language_id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
```

**Comment by xam1234** [comment]
@ywarnier @jmontoyaa 
I know about a bug in my local chamilo version (1.10.6), but I suggest to focus on 11.chamilo.org becouse I want to update to 1.11.6 as soon as possible. 
Again, to reproduce:
Activate Terms and conditions->create terms and conditions content language->create a Learner with the same language as terms and conditions->Log in as Learner and nothing happens, where there should be info just when you log in.

**Comment by jmontoyaa** [comment]
I cannot see the error that it's reported here.

When entering here:

https://11.chamilo.org/main/auth/inscription.php

You can see the "terms and conditions" text:

![selection_005](https://user-images.githubusercontent.com/158935/34152925-82f46018-e4b0-11e7-8234-cccdd73b94c3.png)

**Comment by xam1234** [comment]
@jmontoyaa It works if someone registers himself/herself, but try to do it according to my instructions. Add a new user and log on to him. The first time you log in to him, the terms and conditions should be displayed.

**Comment by jmontoyaa** [comment]
I just added a fix to show that page. It should work now in 1.11.x

**Comment by xam1234** [comment]
It's working now but one more thing, it works also for admins (admin/admin) I do not know whether it should also work for them?
Is there a option to add abutton to remove old changes in terms and condition ?

![obraz](https://user-images.githubusercontent.com/32258255/34156725-c4d098f4-e4be-11e7-8877-b27c1105081b.png)

**Comment by jmontoyaa** [comment]
I don't see the problem that admins have to agree with terms and conditions.
Currently there's no option to delete the terms. You have to update them.
