### ISSUE TITLE
Badges in social network do not appear in blocks anymore

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2245]

**Comment by aragonc** [comment]
Se restauro el estilo anterior que fue borrado cuando se coloco, la jerarquía de competencias.

![competencias](https://user-images.githubusercontent.com/2940509/34387501-86881e7a-eafc-11e7-8293-12ef93929384.png)

**Comment by ywarnier** [comment]
Todavía existe el problema en https://11.chamilo.org/main/admin/user_information.php?user_id=1 (admin / admin) al finaaaaal de la página.
![user-info](https://user-images.githubusercontent.com/609839/34388458-b2b149fe-eb01-11e7-998f-077a93b57f6a.png)

**Comment by aragonc** [comment]
Listo, revisar cambios

**Comment by ywarnier** [comment]
:+1:
