### ISSUE TITLE
Changes to clean database for 2.0

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2247]
Replace queries where we use c_id + id instead by *only* iid.
Remove all fields (c_id +) id in corresponding tables.

- [x] delete track_e_uploads.upload_cours_id (c_id already there)
- [x] delete track_e_hotspot.hotspot_course_code (c_id already there)
- [x] convert track_stored_values_stack.course_id to c_id and change type (varchar to int)
- [x] convert track_stored_values.course_id to c_id and change type
- [x] convert track_e_exercises.session_id from smallint to int
- [x] convert course_category.parent_id from varchar(40) to int
- [x] templates.course_code to template.c_id
- [x] gradebook_category.course_code to c_id
- [x] gradebook_evaluation.course_code to c_id
- [x] gradebook_link.course_code to c_id
- [x] gradebook_result_log.id_result to result_id
- [x] add c_quiz_question_category.session_id
- [x] rename track_e_exercises.exe_weighting to track_e_exercises.max_score
- [x] rename track_e_exercises.exe_result to track_e_exercises.score
- [x] add extra_field.helper_text for adding helper texts under form elements
- [x] alter table gradebook_category add index idx_gb_cat_parent (parent_id);
- [x] alter table gradebook_evaluation add index idx_ge_cat (category_id);
- [x] alter table gradebook_result add index idx_gb_uid_eid (user_id, evaluation_id);
- [x] alter table gradebook_link add index idx_gl_cat (category_id);
- [x] drop course column from personal_agenda table (deprecated)

**Comment by jmontoyaa** [comment]
> add extra_field.comment_text for adding helper texts under form elements

I added the extra_field.description is that the same?

I'm not sure if this is worth it for now:

```
rename track_e_exercises.exe_weighting to track_e_exercises.max_score
rename track_e_exercises.exe_result to track_e_exercises.score
```
There are many calls of those fields... are you sure?

**Comment by ywarnier** [comment]
>>    add extra_field.comment_text for adding helper texts under form elements

> I added the extra_field.description is that the same?

I guess. Do you use the extra_field.description field to show the description below the option (like we do in the administration settings)? That's what it should have done for the "comment_text".

> I'm not sure if this is worth it for now:
>   rename track_e_exercises.exe_weighting to track_e_exercises.max_score
>   rename track_e_exercises.exe_result to track_e_exercises.score
> There are many calls of those fields... are you sure?

It's like everything: I think the most we postpone that, the most it's going to bother us. I also think that, because of the very specific name of those fields at the moment (exe_weighting and exe_result) it should be a quick and reliable replacement in the code. The only problem I can see is if *another* max_score or score field exists in the same queries that we are changing, but if we make sure they all have prefixes, that should work just fine.

**Comment by ywarnier** [comment]
By the way, what about the other fields, @jmontoyaa ? Did you already change them (c_id etc). Because I think those are much more tricky than weighting.

**Comment by jmontoyaa** [comment]
Most of the c_id changes were already done in 1.11.x and I finished them in this commit:

https://github.com/chamilo/chamilo-lms/commit/09b14176350ee77c417f46e37533bddb3fe92872

**Comment by jmontoyaa** [comment]
Mmm well you proposed "extra_field.description"  here: 
https://github.com/chamilo/chamilo-lms/issues/2551
So I'm not sure it's the same or not.

**Comment by ywarnier** [comment]
I've added some observations to https://github.com/chamilo/chamilo-lms/commit/09b14176350ee77c417f46e37533bddb3fe92872

**Comment by ywarnier** [comment]
This task is done now. I've also added a helper_text to extra_field, so now maybe we have a duplicate usage, but I believe it is OK to have a description *and* a helper text, so we can store a description only for admins and use the helper text for normal users.
