### ISSUE TITLE
Unsubscribe user from information page do not work

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2248]
In 1.11.x when looking at a user information page, if the user is subscribe to a course, when clicking on the X to unsubscribe the user to the course, nothing happens.
It can be reproduced here https://11.chamilo.org/main/admin/user_information.php?user_id=13 clicking on the X on the right in the course list.
It sends to the page https://11.chamilo.org/main/admin/user_information.php?action=unsubscribe&course_code=SPANISH101&user_id=13

**Comment by ywarnier** [comment]
Works for me!
