### ISSUE TITLE
Error al corregir ejercicios con preguntas de combinación exacta

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2249]
### Current behavior / Resultado actual / Résultat actuel

En un ejercicio con preguntas de combinación exacta, cuando el profesor accede al resultado de un alumno, las calificaciones mostradas son erróneas y aparecen preguntas como incorrectas aunque no lo sean.
Tanto en la lista de intentos como cuando el alumno accede a ver su intento la puntuación se muestra bien.

### Expected behavior / Resultado esperado / Résultat attendu

El profesor debería ver las preguntas con las respuestas que ha dado el alumno, y no es asi

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

-Crear un ejercicio con preguntas de combinación exacta, con un par de opciones como correctas.
-Acceder como alumno, realizar el ejercicio correctamente.
-Acceder como profesor a revisar el intento, aparecen preguntas incorrectas.

Se puede probar aqui: https://11.chamilo.org/main/exercise/exercise_report.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=736

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x

**Comment by ywarnier** [comment]
@nosolored necesitaremos una validación suya antes del lunes en la noche. Gracias.

**Comment by nosolored** [comment]
Ya funciona correctamente, gracias
