### ISSUE TITLE
Course group report do not work

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2251]
On 1.11.x on the course reporting page clicking on the second icon the report do not show anything : https://11.chamilo.org/main/tracking/course_log_groups.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=reporting

Even if there are groups created and the users of those groupes have has some actions in the course.

**Comment by jmontoyaa** [comment]
Now it works

**Comment by ywarnier** [comment]
All good for me (with the given initial 
![group](https://user-images.githubusercontent.com/609839/34329354-bf4cfb88-e8ca-11e7-803e-6162f81e0be5.png)
example)
