### ISSUE TITLE
Adding users to a group generates errors

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2252]
In a course, when getting to the page to add users to a group, it generates a lot of notices and warning

https://11.chamilo.org/main/group/member_settings.php?cidReq=NICODU&id_session=0&gradebook=0&origin=&gidReq=12

and once saving the changes we get to a white page with notices and warning like those below and no way to continue on Chamilo :

> 
> Notice: Undefined variable: max_member in /var/www/chamilo111x.loc/main/group/member_settings.php on line 207
> 
> Warning: Cannot modify header information - headers already sent by (output started at /var/www/chamilo111x.loc/main/inc/lib/groupmanager.lib.php:2174) in /var/www/chamilo111x.loc/main/group/member_settings.php on line 213

**Comment by jmontoyaa** [comment]
Should be fixed with:

https://github.com/chamilo/chamilo-lms/commit/bab80c91f81e140a26c7b8f67db0ccb4463307b9

**Comment by NicoDucou** [comment]
All good to me.
