### ISSUE TITLE
Grid view is not working

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2253]
Adding the configuration in app/config/configuration.php does not make the grid view visible : 

```
// New grid view the list of courses
$_configuration['view_grid_courses'] = true;
``` 

It should be visible in grid on My course page.

**Comment by jmontoyaa** [comment]
Works for me. Be sure that the value is true and not 'true'.
It should be a boolean and not a string.

I changed it in https://11.chamilo.org/

**Comment by NicoDucou** [comment]
It's working and the configuration.dist.php is correct so it can be closed
