### ISSUE TITLE
Test generates a lot of errors in the end, question bug

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2254]
Taking a test by a learner generates a lot of errors also one anwsered questions are marked as correct (green) see on 11.chamilo.org
Login here as: test123/test123
https://11.chamilo.org/main/exercise/exercise.php?cidReq=TEST123&id_session=0&gidReq=0&gradebook=0&origin=&

![obraz](https://user-images.githubusercontent.com/32258255/34158305-193ed918-e4c5-11e7-9e3a-6b2c913dc0b7.png)

**Comment by jmontoyaa** [comment]
Cześć @xam1234 :)

I just fixed that with:
https://github.com/chamilo/chamilo-lms/commit/1e3ab837387470d2b09eeeb00821fb21e8e283d9

**Comment by xam1234** [comment]
Dzięki:)
Can you also look at the questions with score set to "0" , they are marked as correct, see below.

![obraz](https://user-images.githubusercontent.com/32258255/34159437-94cc3748-e4c9-11e7-9a66-52234f4a6159.png)

**Comment by jmontoyaa** [comment]
It works well for me, probably i was updating the platform during that moment...

**Comment by xam1234** [comment]
ok, I don't have time to test this, thanks!!!
