### ISSUE TITLE
Sessions are not immediately available after creation

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2257]
### Current behavior
In a different timezone than UTC (GMT minus something, like GMT-5), when I create a session, it is created in the database with the UTC time. Everything is fine there.
However, when I then connect (immediately after) with the course-session coach, the session-course does not appear in my courses list.
This seems to be because the query that selects the available sessions does not do it in UTC time and rather uses local time. So if it's 5am in GMT-5 and I create a session, it is set as 10am in the database (using the default time settings when creating the session). However, when I connect at 5:01am local time, I cannot see the session. I should see it, because it's set to start at 5:00 local time (or 10:00 UTC time).

### Steps to reproduce
 - Set your server on GMT-5
 - login as admin
 - create a session with all default options
 - assign a course
 - assign a teacher or student to the session
 - logout
 - connect as the user assigned to the session
 - nothing appears in your courses list

### Chamilo Version
1.11.x 20171219

**Comment by jmontoyaa** [comment]
I cannot reproduce this error. Works for me.
Maybe you have some special settings in  configuration.php ?

**Comment by ywarnier** [comment]
Fixed
