### ISSUE TITLE
Assignments: button "download" also appears when there's no upload on view.php

### ISSUE THREAD

**Issue by annickvdp** [chamilo/chamilo-lms#2258]
### Current behavior / Resultado actual / Résultat actuel
when opening a submitted assignment, the button "download" will show at the the top even if there's no upload
![image](https://user-images.githubusercontent.com/15210140/34210612-ca18dfc8-e596-11e7-9401-47c5d5d6a17b.png)

when clicked,  the following message will display
![image](https://user-images.githubusercontent.com/15210140/34210630-dafc5176-e596-11e7-9794-2ee8e59c321b.png)

### Expected behavior / Resultado esperado / Résultat attendu
no "download" button when there is no upload

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
submit an assignment only using online text (editor), no upload, then view the submitted assignment, you'll see the "download" button at the top

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4 (tested on https://11.chamilo.org/)

**Comment by ywarnier** [comment]
@annickvdp, is that OK with you?

**Comment by annickvdp** [comment]
yes! Perfect!
