### ISSUE TITLE
ERROR INSTALACION ANNOTATION

### ISSUE THREAD

**Issue by zedimit** [chamilo/chamilo-lms#2259]
### Chamilo Version / Versión de Chamilo / Version de Chamilo
TENGO EL ULTIMO XAMPP Y CHAMILO EN MI WINDOWS 7 Y ESTOY INTENTANDO INSTALAR CHAMILO LMS Y ME APARECE EL SIGUIENTE ERROR EL CUAL NO SE COMO PROCEDER PARA COMPONERLO. HE BUSCADO Y LEIDO QUE SE DEBE HAER UN REEMPLAZO DE main/inc/lib/database.lib.php Y ALGUNOS ARCHIVOS, PERO COMO SE REALIZA DICHO REEMPLAZO???? HAY ALGUN PROGRAMA O ALGUNA PAGINA ONLINE O SI ALGUIEN TIENE DICHO PHP ALOJADO EN PAGINA PARA VOLVER A DESCARGAR Y QUE NO ME SALGA DICHO ERROR.

GRACIAS ANTICIPADAS. DEBAJO DESCRIBO EL ERROR

Fatal error: Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded.' in C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54 Stack trace: #0 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') #1 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation() #2 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations() #3 C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\do in C:\wwwroot64\chamilo-ene-atrium111-prod\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54

**Comment by ywarnier** [comment]
Este error ha sido corregido en 1.11.6. Sugerimos esperes hasta la publicación de la 1.11.6 el 18/1/2018

**Comment by amelo1709** [comment]
Para cuando esta planificada la publicación de la 1.11.6??? Si no puedo instalar pronto entonces tendré que buscar otra plataforma...

**Comment by NicoDucou** [comment]
La version 1.11.6 ha sido publicada el 18 de enero como indicado en el comentario anterior.
Esta disponible aqui : https://github.com/chamilo/chamilo-lms/releases
Cuidado con plataforma con php 7.0 hay un problema, mirar la tarea https://github.com/chamilo/chamilo-lms/issues/2347

Saludos
