### ISSUE TITLE
Backslashes added to blogs titles & subtitles

### ISSUE THREAD

**Issue by Alphabc** [chamilo/chamilo-lms#2260]
Hi,
When trying to create a blog inside a new course, ' are escaped when displayed (in French)

Page:
/main/blog/blog_admin.php?action=add

Behaviour:
![image](https://user-images.githubusercontent.com/24738945/34225461-e015d526-e5c6-11e7-8857-ca292412989f.png)

Version:
Chamilo 1.11.4

However, if we edit the page and remove the backslashes, it works... pb is only on creation...

Thx

**Comment by jmontoyaa** [comment]
I added a fix for this. It should work now

**Comment by Alphabc** [comment]
Thx!
