### ISSUE TITLE
En lecciones, la opción "esconder zona de tabla de contenidos" no parece funcionar

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2261]
### Current behavior / Resultado actual / Résultat actuel

Si al editar la configuración de una lección marcamos la casilla "Esconder zona de tabla de contenidos" no causa ningún efecto en la visualización de la lección.

### Expected behavior / Resultado esperado / Résultat attendu

Según creíamos, esta opción debería ocultar la zona izquierda donde aparecen los ítems de contenido de la lección.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Editar una lección, y en la configuración marcar esta opción.
Guardar cambios y acceder a la vista previa de la lección.
Se puede probar aquí: https://11.chamilo.org/main/lp/lp_controller.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=&action=edit&lp_id=86

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x

**Comment by ywarnier** [comment]
Efectivamente, debería esconder la tabla de contenidos por defecto.

**Comment by jmontoyaa** [comment]
Solo la tabla de contenidos o toda la columna de la izquierda?

**Comment by ywarnier** [comment]
Toda la columna

**Comment by nosolored** [comment]
Lo acabo de probar en 11.chamilo.org 
La opción funciona, oculta la columna lateral, pero esto provoca que el contenido de la lección se muestre en una banda muy estrecha, generando scroll vertical

**Comment by AngelFQC** [comment]
Acabo de enviar un commit para corregir los estilos del visor de lecciones.
Por favor, probarlo en pantallas pequeñas

**Comment by nosolored** [comment]
Ya funciona bien, gracias
