### ISSUE TITLE
Al "Enviar mi Tarea" con audio no muestra reproductor

### ISSUE THREAD

**Issue by luis-rj** [chamilo/chamilo-lms#2265]
### Current behavior / Resultado actual / Résultat actuel

Luego de completar una tarea subiendo un archivo de audio , en lugar de mostrar el reproductor de audio muestra la leyenda:

_Su navegador no soporta AUDIO.
Por favor, descargue el fichero: audio/mp3_

Sin embargo, un archivo de audio subido como Comentario si muestra el reproductor. (En la misma tarea/pagina que no lo muestra en la sección Descripción )

### Expected behavior / Resultado esperado / Résultat attendu

Renderizacion adecuada del tag <audio>

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Crear tarea "X"

Pasar a "Vista de Estudiante" / Ir a  tarea "X"  

Click en "Enviar mi Tarea" / Enviar (Simple)

Agregar archivo .mp3 mediante Icono "Audio"

Enviar 

Click en icono "Ver" de la tarea "X"

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.4  ( anteriores ? ...)

**Comment by ywarnier** [comment]
Es probable (porque hemos tocado este código hace poco) que esto haya sido resuelto en el código para la versión 1.11.6 por ser publicada el 18/01. Puedes reproducir el problema en https://11.chamilo.org/ (puedes entrar como admin/admin). De ser el problema, nos puedes dar un enlace directo? Esto acelera nuestro trabajo considerablemente.

**Comment by luis-rj** [comment]
Aqui esta tanto en Descripcion (error) como Comentario (ok):

https://11.chamilo.org/main/work/view.php?id=98&cidReq=AUDIOPLAYER&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by AngelFQC** [comment]
En una revisión rápida... `Security::removeXSS` remueve los tags `audio` pero deja los tags `source`

**Comment by AngelFQC** [comment]
HTMLPurifier no soporta la etiqueta `audio`, por lo que las elimina del texto que se pase por `Security::removeXSS`.

Lo mismo pasaba con la etiqueta `video` pero @jmontoyaa agregó el soporte en db815152d646aada31cd3ab55f72cb6e7e5170c4 y 1f34a8deb1608e3c804a66caafc1486ac49fb27b.

Ahora estoy agregando el soporte para `audio` de igual forma.

**Comment by luis-rj** [comment]
He probado con éxito reemplazar en instalación propia de versión 1.11.4 los archivos   inc/lib/security.lib.php e  inc/lib/formvalidator/Rule/allowed_tags.inc.php por los archivos modificados segun [faf0d7e]
(https://github.com/chamilo/chamilo-lms/commit/faf0d7e528a06575d47b7180686b81cee5a79238)

Habiéndose solucionado el problema. Creo  que el caso puede ser cerrado.

Corresponde que lo cierre yo ?
