### ISSUE TITLE
"Tools shortcuts" and "Course navigation menu" : impossible to hide "Progress Module" for teachers

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#2268]
### Current behavior / Resultado actual / Résultat actuel

In the administration panel i defined "Progress" as an "inactive module upon course creation" + "hidden" from teachers.

When the teacher creates a new course and go to the course homepage the "course progress module" is not hidden at all : the teacher can see the course progress icon in the "tools shortcuts" (in the banner). AND he can see the course progress icon in the "course navigation menu". It is possible for him to do modifications. 
**And it is impossible to desactivate the module** (because the icon of the module doesn't appears in the "list" of tool (in "ipad view") : impossible to click on the eye of the module, it doesn't appears !).
So, the students can access to the module by clicking on the "tool shortcuts" or in "the course navigation menu" !

If i defined "Progress" as an inactive module upon course creation + "NOT hidden" from teachers, there is a similar issue. When a teacher creates a new course, he can see the tool both in "ipadview" and in the tools shorcuts (+in the navigation menu). **But the module is Active !** (possibility to desactivate it by clicking on the eye).

There is no way to hide the "course progress" module both for teachers and students.

### Expected behavior / Resultado esperado / Résultat attendu

If i defined "Progress" as an "hidden module" from teachers it shouldn't appears anywhere (tools shortcuts + navigation menu + ipadview...).

If i defined "Progress" as an "Inactive module upon course creation" + "NOT hidden module" it should appears  in grey in the ipad view and it should be impossible for the students to see it.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Issue reproduced both with "ipad view" and "view activity".

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Issue reproduced both with 1.11.2 and 1.11.4

**Comment by tanchon** [comment]
If i modify the database, it's ok : i go in the "c_tool" table and i modify the "visibility" field from "1" to "0" for "course progress" tool lines. Then, the tool is really hidden !

It seems that when we create the course, the paramaters defined in the "administration menu" of the platform ("hidden" or "not hidden") are not considered into the c_tool table (the visibility is always defined with the "1" value).

This issue has been reproduced here : https://11.chamilo.org

**Comment by ywarnier** [comment]
Please always give the full URL of the course on 11.chamilo.org

**Comment by jmontoyaa** [comment]
I just added a fix. Can you try to reproduce the error in 11.chamilo.org (admin/admin)?

**Comment by ywarnier** [comment]
@tanchon same here, please test and let us know.

**Comment by tanchon** [comment]
OK. It is better now ! But there is still an issue.

As admin I set"course progress" as a hidden module (before creating a new course), it's ok now ! : it is really hidden for the students and for the teachers.

But if I set "course progress" as an "Inactive module upon course creation" (and "not hidden") there is still an issue : it is still "active" both for admin, teachers and students.
With these settings it should be visible with a "closed eye" (in  grey) for admin/teacher and it shouldn't be visible for the students.

I made tests by creating this course : [https://11.chamilo.org/courses/COMPTABILITEFINANCIERE/](url)

Thanks for the job !

**Comment by NicoDucou** [comment]
I confirm that there is an issue here, the tool still appears as visible.
Just to add an information, ti works for tool "Attendances"
It is unchecked in option "Modules active upon course creation" (https://11.chamilo.org/main/admin/settings.php?search_field=Modules+active+upon+course+creation&submit_button=&_qf__search_settings=&category=search_setting) and it appears invisible as it is supposed.
The Progress tool has the same configuration and eventhough it appears visible.

**Comment by jmontoyaa** [comment]
I just added a fix.

**Comment by NicoDucou** [comment]
I just tested it with a new course here https://11.chamilo.org/courses/NEWTESTTOOLVISIBILITY/index.php and it's all good to me.
@tanchon can you confirm aswell ?

**Comment by tanchon** [comment]
I create a new course : https://11.chamilo.org/courses/TESTDELOUTILCOURSEPROGRESS/index.php

Everything is ok now !

Thanks for the job !
