### ISSUE TITLE
No se muestran las encuestas del curso

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2272]
### Current behavior / Resultado actual / Résultat actuel
Al acceder al apartado de encuestas de un curso no aparece ninguna aunque sabemos que en el curso hay 3 encuestas.
En PHP se genera un error:

Call to a member function getCode() on null in /main/survey/surveyUtil.class.php on line 2786,

### Expected behavior / Resultado esperado / Résultat attendu

Deberían aparecer las encuestas existentes en el curso

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Acceder a un curso al apartado de encuestas, crear una encuesta si no existe ninguna, comprobar que no aparece ninguna en la lista.
Esto no sucede con instalaciones nuevas, creemos que puede tener que ver con los campos iid y  survey_id de la tabla c_survey ya que en las instalaciones de Chamilo en las que ocurre ambos campos tienen diferente valor y son instalaciones que provienen de actualizar versiones anteriores de Chamilo

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.6

**Comment by ywarnier** [comment]
Parece que por alguna razón no reciben un $survey_id.
Pueden reproducirlo en 11.chamilo.org? Es una instalación que ha sido actualizada muchas veces...

**Comment by nosolored** [comment]
Ya no nos da error ni en nuestras demos ni en 11.chamilo.org, se debe haber corregido en algun momento desde que lo publicamos.
