### ISSUE TITLE
erreur prévisualisation d'un document d'un parcours

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2275]
### Current behavior / Resultado actual / Résultat actuel
Impossibilité de prévisualiser un document dans un parcours.
la page s'ouvre et cela indique : une erreur s'est produite, veuillez contacter l'administrateur.
cliquer sur la loupe :
![bugprevisualiser](https://user-images.githubusercontent.com/24505996/34555085-4818648a-f130-11e7-8654-919dc18cec14.png)
résultat :
![bugprevisualiser2](https://user-images.githubusercontent.com/24505996/34555053-1e87b382-f130-11e7-88cb-861e0d07211d.png)

### Expected behavior / Resultado esperado / Résultat attendu
dans la création d'un parcours, cliquer sur la loupe pour prévisualiser un document
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
créer un document dans un parcours et cliquer sur la loupe
### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo 1.11.6.alpha1

**Comment by alexiye** [comment]
sur le portail chamilo 1.11.x :
Notice: Undefined variable: tbl_lp in /var/www/11.chamilo.org/www/main/lp/lp_view_item.php on line 64

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE iid = 188' at line 1 in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104 Stack trace: #0 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(104): PDO->query('SELECT * FROM ...') #1 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(912): Doctrine\DBAL\Driver\PDOConnection->query('SELECT * FROM ...') #2 /var/www/11.chamilo.org/www/main/inc/lib/database.lib.php(381): Doctrine\DBAL\Connection->executeQuery('SELECT * FROM ...') #3 /var/www/11.chamilo.org/www/main/lp/lp_view_item.php(65): Database::query('SELECT * FROM ...') #4 /var/www/11.chamilo.org/www/main/lp/lp_controller.php(771): require('/var/www/11.cha...') #5 {main} Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[ in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 94

**Comment by nosolored** [comment]
@jmontoyaa  
Al aplicar el último código muestra en el error_log
 PHP Fatal error:  Class 'Session' not found in ../main/lp/lp_view_item.php on line 21, referer: .../main/newscorm/lp_controller.php?cidReq=ABCD&id_session=0&gidReq=0&gradebook=0&origin=&action=add_item&type=step&lp_id=153&isStudentView=false

**Comment by nosolored** [comment]
Testeado. 
Ya no muestra error.
Gracias.

**Comment by alexiye** [comment]
:+1: cela fonctionne à nouveau.
Bravo !
