### ISSUE TITLE
impossibilité d'importer un cours chamilo 1.9.10 dans chamilo 1.11.6.alpha1

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2276]
### Current behavior / Resultado actual / Résultat actuel
rien ne se passe (sauf si je coche sur "Me laisser selectionner les sections de cours" et que je ne choisisse pas d'importer les exercices !)
### Expected behavior / Resultado esperado / Résultat attendu
le cours importé
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
dans un cours, aller dans maintenance et importer les informations de sauvegarde du cours
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6.alpha1
( Si j'importe les informations de sauvegarde d'un cours chamilo 1.9.10.2 dans chamilo 1.11.4 cela fonctionne, si j'exporte une sauvegarde de ce cours à partir de chamilo 1.11.4 vers chamilo 1.11.6.alpha1 cela fonctionne aussi !)

P.S. Bonne année et meilleurs voeux pour cette nouvelle année à tous ceux qui contribuent au développement de chamilo.

**Comment by alexiye** [comment]
essai sur le portail : Création d'un cours puis essai d'importation et affichage suivant :
Notice: Undefined property: stdClass::$save_correct_answers in /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php on line 1803

Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'save_correct_answers' cannot be null in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105 Stack trace: #0 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(Array) #1 /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(Array) #2 /var/www/11.chamilo.org/www/main/inc/lib/database.lib.php(450): Doctrine\DBAL\Statement->execute(Array) #3 /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(1824): Database::insert('c_quiz', Array) #4 /var/www/11.chamilo.org/www/src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php(188): Chamilo\CourseBundle\Component\CourseCopy\CourseRestorer->restore_quizzes(0, false, '') #5 /var/www/11.chamilo.org/www/main/coursecopy/import_backup.php(101): Chamilo\CourseBun in /var/www/11.chamilo.org/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 118

**Comment by ywarnier** [comment]
Bien que je reconnaisse qu'il est probable qu'il y ait une erreur dans ce cas, nos ressources communautaires ne nous permettent pas de prendre ce bug en charge (parce qu'il est relativement moins prioritaire considérant que la version 1.9.10 a originellement été publiée le 25/1/2015 - il y a donc une série d'éléments plus prioritaires sur lesquels travailler pour nous).
Tu peux trouver un fournisseur officiel sur la page de Chamilo: https://chamilo.org/providers si c'est quelque chose d'important/urgent.
Alternativement, tu peux essayer de résoudre le problème toi-même en nous posant des questions (ici ou sur slack #chamilo) et nous soumettre la solution pour l'inclure dans Chamilo.

**Comment by ywarnier** [comment]
Pas de réponse. Je clôture ce rapport dont la quantité d'information fournie ne nous permet pas d'implémenter une correction.
