### ISSUE TITLE
Taille des blancs (avec menu déroulant) dans exercices 

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2278]
### Current behavior / Resultado actual / Résultat actuel
la taille des blancs n'est pas modifiée
![regler la taille des blancs](https://user-images.githubusercontent.com/24505996/34561391-04ce3460-f14a-11e7-9d31-bf40bc26d375.png)
![resultat taille des blancs](https://user-images.githubusercontent.com/24505996/34561399-0adb9d5c-f14a-11e7-8ab8-4831ee76e747.png)

### Expected behavior / Resultado esperado / Résultat attendu
la taille des blancs adaptée à la largeur du texte
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
créer un exercice avec des blancs et utiliser le menu déroulant [a|à|as] par exemple
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by alexiye** [comment]
Cool, cela fonctionne super ! Merci beaucoup.

**Comment by louuuba** [comment]
Bonjour, 
J'aurais une question concernant la correction automatique sur Chamilo : 
Comment choisir la bonne réponse quant on a un menu déroulant ?

**Comment by NicoDucou** [comment]
Quand on a un menu déroulant, on met la liste des options séparées par le caractère | et c'est la première option qui est considérée comme la bonne réponse. Ensuite quand on réalise l'exercice les options de réponses sont mélangées biensur.
