### ISSUE TITLE
Soap Web Service DeleteUser and Copy Course - Chamilo 1.11.2

### ISSUE THREAD

**Issue by AldoAbdiel** [chamilo/chamilo-lms#2279]
### Consume WS.DeleteUser SOAP

Greetings, I have been trying to consume the webservice to delete users, but I dont fully undertand the parameters needed from this request.

When I call it, the following error appers. I used "die and dump" to view the response log.

![image](https://user-images.githubusercontent.com/15349059/34580001-d71138a4-f150-11e7-97a0-a70d00e4df54.png)

This is my code:

        if($client!=null){
            $user_id = $account->db_sid;
               
            $response = $client->call("WSUser.DeleteUser", array(
                'secret_key' => $secret_key,
                //'user_id_field_name' => 'external_user',
                'user_id_value' => $user_id,
            ));
            dd($response); 
            return $response;
            
        } else {
            return null;
        }

I dont know if the parameter "user_id_field_name" has to be used or not, neither his purpose.

### CourseCopy feature

As I have see there is no web service for the copycourse feature, but there are files about it in 'main/coursecopy'.

I would gladly aprecciate if someone could explain me how to make use of this feature, or if it's possible it would be awesome to have the function of copycourse implemented as a Soap Web Service.

**Comment by CesarCavazos97** [comment]
I also need these webservices, if someone have them please share them

**Comment by jmontoyaa** [comment]
I suggest you use main/webservices/registration.soap.php there's an example how to use it here:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/webservices/client_soap.php

```
 $params = [
        'secret_key' => $secret_key,
        'ids' => [
            'original_user_id_value' => $random_user_id,
            'original_user_id_name' => $user_field,
        ]
    ];
    // Delete user
    $result = $client->call('WSDeleteUsers', ['user_ids' => $params]);
```

**Comment by AldoAbdiel** [comment]
Yeah thanks, using the registration.soap.php works like a charm. 👍 :)
