### ISSUE TITLE
erreur calcul des points exercices remplir les blancs avec menu déroulant- chamilo 1.11.x

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2292]
### Current behavior / Resultado actual / Résultat actuel
Errreur dans le calcul des points dans exercices remplir les blancs avec menu déroulant
### Expected behavior / Resultado esperado / Résultat attendu
le  calcul des points est correct
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
créer un exercice remplir les blancs avec plusieurs blancs en menu déroulant [réponse bonne|réponse fausse 1|réponse fausse 2] . Essayer l'exercice et ne remplir qu'un blanc avant de valider. Le résultat donne tout bon bien que toutes les réponses n'ont pas été données.
![erreur exercices blancs](https://user-images.githubusercontent.com/24505996/34659804-84952bf4-f43d-11e7-8425-121ce201bbf2.png)
Si j'essaye l'exercice et que je ne remplis aucun blanc avant de valider, là tout va bien
![blancs](https://user-images.githubusercontent.com/24505996/34659822-a99f60cc-f43d-11e7-87bb-24be1636469a.png)
Si je fais l'exercice et que je mets toutes les bonnes réponses :
![reponse](https://user-images.githubusercontent.com/24505996/34660107-2670b8ec-f440-11e7-9fd0-ad613c606973.png)
Là aussi il y a des erreurs au niveau du calcul des points, vu que certaines réponses enregistrées ne correspondent pas à celles qui ont été données avant validation par fin du test :
![erreur](https://user-images.githubusercontent.com/24505996/34660115-3d8bcad0-f440-11e7-895f-77e7d06626a8.png)

https://11.chamilo.org/main/exercise/admin.php?cidReq=LESHOMOPHONESDUVERBESAVOIRAUPRESEN&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=762&deleteQuestion=1823

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
Je n'arrive pas à reproduire le problème (j'ai copié ton dernier exercice). J'ai essayé les différents cas et tout va bien.
![results](https://user-images.githubusercontent.com/609839/35014637-9b1ecd28-fb11-11e7-9a5e-27b9a89be0b4.png)

**Comment by ywarnier** [comment]
Pas de feedback. Je clôture la tâche. N'hésite pas à la réouvrir si le problème persiste et est reproductible facilement.
