### ISSUE TITLE
Error on importing students

### ISSUE THREAD

**Issue by Alphabc** [chamilo/chamilo-lms#2300]
Hi,
Trying to import a csv file with check on email unicity on a Chamilo 1.11.4 with multiple url.
Upload done on mother website.
As many administrators could do, I simply added new students to a previous file and tried to import it again
Then, I got this:
URL:
https://chamilo.XXXX.com/main/admin/user_import.php

`Fatal error: Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'herbertfran' for key 'UNIQ_8D93D649F85E0677' in /var/sites/chamilo.XXXX.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91 Stack trace: #0 /var/sites/chamilo.XXXX.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL) #1 /var/sites/chamilo.XXXX.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(168): Doctrine\DBAL\Driver\PDOStatement->execute(NULL) #2 /var/sites/chamilo.XXXX.com/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\DBAL\Statement->execute() #3 /var/sites/chamilo.XXXX.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(966): Doctrine\ORM\Persisters\BasicEntityPersister->executeInserts() #4 /var/sites/chamilo.XXXX.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata)) #5 /var/sites/chamilo. in /var/sites/chamilo.XXXX.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 66`

I 1st thought it was due to special character that hadn't been sanitized in the csv file ("herbertfrançois" becoming "herbertfran"), but I have other usernames with same case and no fatal error, just warning message handled normally like this one:
![image](https://user-images.githubusercontent.com/24738945/34691928-8c083b8e-f4be-11e7-82d5-0e0cedcf920b.png)
or maybe "ç" is not considered the same was as accentuated characters?

- Could it be possible to sanitize the usernames from csv file when importing? (characters with accents, spaces, dash) otherwise admin teams need to use a vb function in Excel to do it ;)
and why dash is not allowed in usernames?

- Could you handle accentuated characters a bit better if possible?
![image](https://user-images.githubusercontent.com/24738945/34691824-2af4ce3e-f4be-11e7-8376-a7bb08a01f3a.png)

- if we have a rule with "namesurname" as username, when trying to import the file, it only says "this username is already used on this platform"
Could it maybe add a 1, 2, etc? after the usersame?
Thinking of "jeandupond" in french which could be common :)

Many thanks

Cheers (and happy new year :) )

**Comment by ywarnier** [comment]
There have been many improvements in the CSV user import, ready to be published in 1.11.12 next week. Hopefully, this solves your issue.
