### ISSUE TITLE
Accents in multiple registrations

### ISSUE THREAD

**Issue by Alphabc** [chamilo/chamilo-lms#2302]
Hi,

following an issue in which I had accents issues (https://github.com/chamilo/chamilo-lms/issues/2300) I have another place where accents are not handled the right way:
/main/admin/add_users_to_usergroup.php?id=27

When I want to add users in a classroom, names & surnames with accents are not displayed
![image](https://user-images.githubusercontent.com/24738945/34696700-13f54c2e-f4d0-11e7-8203-d0b67cac76ec.png)

1-> the firstname is "éric" and it has been removed entirely because it starts with an accentuated characted
2- the firstname there is "Agnès" and you can see we have only "Agn"

Thx!

PS: all names are not real and there for testing purposes... blabla coincidences, blabla :)

**Comment by tanchon** [comment]
It seems like #2266 when importing users on the platform by csv files...

**Comment by jmontoyaa** [comment]
This looks like an issue when inserting users to the platform when using a csv file. 
Can you provide an example of the file?

**Comment by Alphabc** [comment]
Sure...
BE CAREFUL: I needed to rename .csv to .xlsx to be able to upload the file...
It has been used with .csv extension :-)

It seems however " ' " are correctly handled :-)
![image](https://user-images.githubusercontent.com/24738945/34711408-9cbe84ea-f51f-11e7-8ae6-bcbe00fe0519.png)

but accentuated characters are not, be it in names, surnames or in usernames (but in usernames, I did it another time with sanitized usernames: this is what you can see in screenshots when you have 2 lines... 1st one is the result of the 1st insert, without sanitized username, second is with sanitized username, and of course other email)
You'll find hereafter what is displayed in the list:

![image](https://user-images.githubusercontent.com/24738945/34711371-82708070-f51f-11e7-8f89-5e2f4c29dcbb.png)

![image](https://user-images.githubusercontent.com/24738945/34711459-c6009bcc-f51f-11e7-8446-c29e7ee6c391.png)

![image](https://user-images.githubusercontent.com/24738945/34711512-efdfe74a-f51f-11e7-8fc8-e91fa33eac2c.png)

![image](https://user-images.githubusercontent.com/24738945/34711568-1bd2aedc-f520-11e7-9597-a48334cefbe1.png)

![image](https://user-images.githubusercontent.com/24738945/34711651-730acf0e-f520-11e7-8386-f40991d02bbd.png)

![image](https://user-images.githubusercontent.com/24738945/34712427-171ecda0-f523-11e7-9b7f-81a1ff75e026.png)

[example-users-import-2018-debug.xlsx](https://github.com/chamilo/chamilo-lms/files/1614434/example-users-import-2018-debug.xlsx)

Thx

**Comment by xam1234** [comment]
Works for me on 11.chamilo.org
![obraz](https://user-images.githubusercontent.com/32258255/34769072-0da29466-f5fd-11e7-9a9c-d2b53c58f9bb.png)

Your file wasn't utf8
Try this one:

[example-users-import-2018-debug1.zip](https://github.com/chamilo/chamilo-lms/files/1618456/example-users-import-2018-debug1.zip)

**Comment by Alphabc** [comment]
Hi,
Sorry for the delay...
Thanks for your answer!
Still trying to deal with it as the file you kindly uploaded doens't even allow import...
I have a message saying "File imported", but noone is added
I've even tried with only 1 user line...
Not working, no error message :(
I've checked my tables: all are with utf8 encoding system

I've tried on my own file, checking this option on Excel
![image](https://user-images.githubusercontent.com/24738945/35097757-bc55ca50-fc51-11e7-90f4-7198939df987.png)
this time, the file is imported, but still with the accent issue :(
![image](https://user-images.githubusercontent.com/24738945/35097823-1a31b40e-fc52-11e7-82c2-5ee0e81b9b6a.png)

Very strange :(

Trying on 11.chamilo.org:
ok, the class Id doesn't exist, meaning I have an issue about that, but the accent is not well handled neither on this platform...
![image](https://user-images.githubusercontent.com/24738945/35098058-002d9f04-fc53-11e7-9358-09aed5339694.png)

Same issue as on my platform if I remove the classId
![image](https://user-images.githubusercontent.com/24738945/35098191-776788d2-fc53-11e7-8e42-30b3351c39cf.png)
[example-users-import-2018-debug3.zip](https://github.com/chamilo/chamilo-lms/files/1642803/example-users-import-2018-debug3.zip)



Maybe my file is still not utf8?
I cannot send it to linux & run iconv: the end users won't do it :)

**Comment by jmontoyaa** [comment]
The file is still not in utf8:

I have this information when doing the command:

`file  example-users-import-2018-debug3.csv`

Result: 
`
example-users-import-2018-debug3.csv: ISO-8859 text, with CRLF line terminators`

**Comment by Alphabc** [comment]
Many thanks...
I'll try again after lunch ;-)

**Comment by Alphabc** [comment]
Thx!
It works...
Needed to open it in txt editor, then change file from DOS to Unix...

**Comment by jmontoyaa** [comment]
great!

**Comment by Alphabc** [comment]
To help those who could face same issue, here is what I need to do from Excel:

Let's find the format:
`# file testfile.csv`
-> gives the current format, generally "ISO-8859 text, with CRLF line terminators"

Once I have the format, convert it through iconv:
`# iconv -f ISO-8859-1 -t utf-8 testfile.csv -o testfile-utf8.csv
`
but it is not finished:
Let's check the format:
`# file testfile-utf8.csv
`-> "UTF-8 Unicode text, with CRLF line terminators" (which is better, but not good ;-) )

`# dos2unix testfile-utf8.csv
`
and finally:
`# file testfile-utf8.csv
`->"UTF-8 Unicode text"
We're ready to upload and have no accent nor " ' " issue...

**Comment by ywarnier** [comment]
Thanks for the detailed procedure.
I want to say the other solution is to use Open Source, but hey... freedom of choice :-)

**Comment by Alphabc** [comment]
I agree, but I'm not the end user, and the administrative team has old habits... ;-)
