### ISSUE TITLE
Wrong Learning path icon using Chrome

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2307]
I have this icon loading in 11.chamilo.org and in my local installation. 
It works well with Firefox but fails with Chrome.
Is it just me? 

![screenshot from 2018-01-11 10-48-31](https://user-images.githubusercontent.com/158935/34819398-e97873c8-f6bd-11e7-9113-b912287df629.png)

**Comment by tanchon** [comment]
All the icons are ok for me (in 11.chamilo.org, as in my platforms).

Chrome Version 63.0.3239.132 (Build officiel) (64 bits).

**Comment by ywarnier** [comment]
Looks of for me too.
Chromium 63.0.3239.84 and Google Chrome 60.0.3112.78

![icons](https://user-images.githubusercontent.com/609839/35012665-d65038b6-fb0a-11e7-8486-0e97f2d9f27b.png)

**Comment by jmontoyaa** [comment]
thanks for you feedback

**Comment by jmontoyaa** [comment]
This issue is real, reported by others here:

https://task.beeznest.com/issues/14004

**Comment by ywarnier** [comment]
However, it doesn't appear in Firefox. I believe this is something linked *only* to Chrome.

**Comment by nosolored** [comment]
The bug only appears in Chrome, but it's annoying for users.
We solved the problem with a new icon, I attach it
![scorms](https://user-images.githubusercontent.com/5868981/36196345-c0137f0a-1170-11e8-8ac8-ea609f47e738.png)

**Comment by NicoDucou** [comment]
@jmontoyaa is it all good for you with Angel's fix ?
Can we close this issue ?

**Comment by jmontoyaa** [comment]
Works for me.
