### ISSUE TITLE
Kiddy theme unconfigured.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2309]
Hello.
In the Chamilo version 1.11.6.
The kiddy theme has setup problem.
![tema kiddys](https://user-images.githubusercontent.com/25286516/34883004-65f14b78-f79f-11e7-96c3-24537dd5bc8e.PNG)
Test. https://11.chamilo.org/

Thank you

**Comment by aragonc** [comment]
Fix css kiddy in repository :)
![fix](https://user-images.githubusercontent.com/2940509/34895278-fe1e8628-f7b2-11e7-993d-c95fa0300dcb.png)

**Comment by bassuma** [comment]
Hi.
Perfect.
Thank you so much

**Comment by ywarnier** [comment]
This was done through commit 2a4f588a9326b6a3b826da0a99be7006ea66bef4
