### ISSUE TITLE
Chamilo 2.x issue list

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2319]
1. Update composer.json to use upgraded Symfony (3.4/4 version) components.
2. Use Symfony 4 directory structure. #2320 
2b. Apply all pending database structure changes (see tag "Requires structure change")
3. Common login between legacy and Symfony login. #2322
4. Use Webpack Encore to create css/js in public/build/ #2324
5. Use gettext to handle translations #2323
6. Use new data layer to access files in courses/ uploads #2321
7. Fix c_item_property table #2326
8. Use SwiftMailer instead of PHPMailer #2325
9. Use header and footer from legacy in new Symfony views #2328
10. New system settings handler. #2329 
11. Use sonata dashboard
12. Upgrade process from 1.11.x  #2327

**Comment by AngelFQC** [comment]
Why not create a GitHub Project? https://github.com/chamilo/chamilo-lms/projects

**Comment by jmontoyaa** [comment]
@AngelFQC good idea

**Comment by jmontoyaa** [comment]
Follow https://github.com/chamilo/chamilo-lms/projects/3

**Comment by jmontoyaa** [comment]
Visit this link instead of this issue: https://github.com/chamilo/chamilo-lms/projects/3
