### ISSUE TITLE
Use Symfony Mailer component instead of PHPMailer 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2325]

**Comment by jmontoyaa** [comment]
Mails are working now in master, tested in 2.chamilo.org when adding/editing a user.

**Comment by ywarnier** [comment]
I'm assigning myself for testing because there have been new developments in the use of PHPMailer in 1.11.x in 2020, which would need to remain in 2.0.

**Comment by christianbeeznest** [comment]
I just checked and tested the code and see it is not using anymore PHPMailer, it is now SiftMailer, a symfony bundle, the change is in this commit https://github.com/chamilo/chamilo-lms/commit/406adc0b7921832ef22cf80742c14cae1356bf80 .  Tested in 2.chamilo.org when adding/editing a user .
