### ISSUE TITLE
Separate c_item_property table (Use Resources entities)

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2326]
Split of the c_item_property table into 3 purpose-specific tables (to make objects management faster and more flexible)
 
Table are: ResourceNode, ResourceLink, ResourceRights

**Comment by ywarnier** [comment]
@jmontoyaa would you say this is completely finished? What is missing? Do you want to open other tasks for the missing bits and close this one?

**Comment by jmontoyaa** [comment]
Yes, the core structure was added in v2. The missing part is the integration with other tools.
