### ISSUE TITLE
 New system settings handler. 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2329]
Instead of adding system configuration all the time with inserts in "settings_current" table.
We will use https://github.com/chamilo/SyliusSettingsBundle to handle system settings using classes.

For example, the settings of the "Agenda" category will be handle with this class:

[src/CoreBundle/Settings/AgendaSettingsSchema.php](https://github.com/chamilo/chamilo-lms/blob/master/src/CoreBundle/Settings/AgendaSettingsSchema.php)

### Variable definition:

We say that the variable "allow_personal_agenda" will have by default value of "true" and it's a string.
We say that the variable "default_calendar_view" will have by default value of "month" and it's a string.

```
    /**
     * {@inheritdoc}
     */
    public function buildSettings(SettingsBuilderInterface $builder)
    {
        $builder
            ->setDefaults(
                [
                    'allow_personal_agenda' => 'true',      
                    'default_calendar_view' => 'month'          
                ]
            );
        $allowedTypes = [
            'allow_personal_agenda' => ['string'],
            'default_calendar_view' => ['string'],
        ];
        $this->setMultipleAllowedTypes($allowedTypes, $builder);
    }
```

### Variable type

Here we say that the type of this variable is a "yes/no" form type, it could be a text/choice or any of the [Symfony form types](https://symfony.com/doc/current/reference/forms/types.html). The yes/no type was specially created in order to handle our classic yes/no radio buttons.

YesNoType:
https://github.com/chamilo/chamilo-lms/blob/master/src/CoreBundle/Form/Type/YesNoType.php

In this case the "default_calendar_view" have 2 options "month" and "week".
```

/**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder)
    {
        $builder
            ->add('allow_personal_agenda', YesNoType::class)            
            ->add(
                'default_calendar_view',
                'choice',
                [
                    'choices' => [
                        'month' => 'Month',
                        'week' => 'Week'
                    ]
                ]
            )
        ;
    }

```

**Comment by jmontoyaa** [comment]
Translations are missing. First we need to implement translations in chamilo v2 then later we can integrate the translations of the settings.

**Comment by ywarnier** [comment]
@jmontoyaa are we ok with this one? Do we need something more (except styling of the new settings section)

**Comment by jmontoyaa** [comment]
Yes, it was added in v2
