### ISSUE TITLE
Problemas al generar certificados

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2332]
### Current behavior / Resultado actual / Résultat actuel
Cuando deseo generar los certificados de los alumnos, presiono el boton generar certificado y este hace una acción pero en pantalla no muestra nada, se tiene que hacer un F5 para ver el resultado.

![generar_certificados](https://user-images.githubusercontent.com/2940509/35005882-f6c41614-fac2-11e7-8e27-a7a65efc4626.png)

### Expected behavior / Resultado esperado / Résultat attendu

Se tienen que mostrar los resultados al cargar la pagina.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Generar certificados, por exámenes presenciales.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.6

**Comment by ywarnier** [comment]
Lo he visto el otro día. No se porque pero cuando le das clic una segunda vez, sí funciona. Hay que corregirlo.
No asignes varias personas a la vez (dejala sin asignar), porque sino nadie la va a hacer.

**Comment by aragonc** [comment]
Listo corregido y validado por mi parte :+1:
