### ISSUE TITLE
Al editar el certificado este no guarda. generar certificado en blanco

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2333]
### Current behavior / Resultado actual / Résultat actuel
Cuando se desea modificar el certificado, este no permite guardar los cambios, en la 1.11.6
![editar](https://user-images.githubusercontent.com/2940509/35006614-04960336-fac5-11e7-8f25-20a92511bc1a.png)
Adicional mente en la 1.11.4 cuando llega a guardar las etiquetas html se sobre ponen.
![edit](https://user-images.githubusercontent.com/2940509/35007054-5bff62b0-fac6-11e7-8f59-4fad09e52c29.png)
Evitando que al generar el alumno su certificado en PDF este aparezca vacio
### Expected behavior / Resultado esperado / Résultat attendu
- Guardar certificado al editar.
- Generar certificado
### Chamilo Version / Versión de Chamilo / Version de Chamilo
la 1.11.4 y la 1.11.6

**Comment by ywarnier** [comment]
OK, esto es importante y urgente (espero poder publicar la 1.11.6 el jueves). @jmontoyaa te la confío.

**Comment by jmontoyaa** [comment]
No puedo reproducir el error en 1.11.x
Creo un certificado y luego lo edito, el HTML aparece correcto.

**Comment by nosolored** [comment]
A nosotros nos ocurre igual en un Chamilo actualizado con lo último de GitHub y también lo he probado aqui:
https://11.chamilo.org/main/document/edit_document.php?id=9780&cidReq=123333&id_session=0&gidReq=0&gradebook=1&origin=gradebook&curdirpath=/certificates&selectcat=1

Si editas el certificado, ya sea en la vista de codigo HTML o bien en la vista normal, le das a guardar y parece haberlo hecho pero no cambia nada.

**Comment by jmontoyaa** [comment]
Acabo de corregir la edición del document.

**Comment by nosolored** [comment]
Ya funciona bien en nuestra demo y en 11.chamilo.org
Al abrir la vista previa del certificado en 11.chamilo.org me ha dado un error:
Warning: A non-numeric value encountered in /var/www/11.chamilo.org/www/main/inc/lib/certificate.lib.php on line 335

Podeis verlo en:
https://11.chamilo.org/main/document/document.php?cidReq=123333&id_session=0&gidReq=0&gradebook=0&origin=gradebook&curdirpath=%2Fcertificates&set_preview=9780

**Comment by jmontoyaa** [comment]
Corregido
https://github.com/chamilo/chamilo-lms/commit/febb1e43e9cfcaea90f2eeaea0c9124419e86d48

**Comment by nosolored** [comment]
Perfecto, gracias

**Comment by aragonc** [comment]
Ahora si esta guardando correctamente y no sobre escribe etiquetas html cuando se edita.

**Comment by tomling278** [comment]
When I try to edit, it does not allow me to select to replace. the first time I was able to replace the links, but when I tried to save the changes I was not allowed. What I can do
