### ISSUE TITLE
No se muestran las imágenes en los certificados

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2334]
### Current behavior / Resultado actual / Résultat actuel
![certificado-chamilo-1](https://user-images.githubusercontent.com/2940509/35007214-e9274c3e-fac6-11e7-8956-b5c4f439ef8e.png)
No se visualizan las imagenes al generar pdf con certificados
### Expected behavior / Resultado esperado / Résultat attendu
Imagenes dentro del certificado
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Generar certificado con PDF
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by jmontoyaa** [comment]
Favor de indicar un ejemplo en:

http://11.chamilo.org/

**Comment by AngelFQC** [comment]
I sent a commit to fix this... try again

**Comment by aragonc** [comment]
Verificado y corregido

**Comment by martincasalis** [comment]
Sigue con problemas.
![image](https://user-images.githubusercontent.com/17132951/80229032-3e47e600-8626-11ea-8b3d-cb960d2f23f4.png)
