### ISSUE TITLE
Bug  Vr.1.11.4 al crear una copia de seguridad de un curso

### ISSUE THREAD

**Issue by fergimon** [chamilo/chamilo-lms#2342]
### Current behavior / Resultado actual / Résultat actuel
Buenas tardes  estoy queriendo realizar una una copia de seguridad a un curso respectivo, al crear un copiar se queda ahí  en blanco y no muestra nada para descargar se adjunta imagen, se descargo el ultimo cogido de Github la carpeta cousecopy pero no funciono  

![error en la copia](https://user-images.githubusercontent.com/20644209/35067830-368b743c-fba3-11e7-8c5e-ae395b7040ba.JPG)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1. Estar dentro del curso 
2. En la sección de administraron, mantenimiento del curso
3. Escojer la opción de crear una copia de seguridad 
4. Click en crear una copia de seguridad 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by NicoDucou** [comment]
Hola fergimon

Acabo de probar en la plataforma de pruebas aqui : https://11.chamilo.org/main/coursecopy/create_backup.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=

Y la copia de seguridad se creo sin problema.
Tendria que ver en el error_log de tu servidor para saber lo que bloquea.

Veo que indicas que actualisaste solamente la carpeta cousecopy desde github. Entonces puede ser que en esta carpeta se esta llamando a una funcion que no existe en el resto del codigo porque no lo actualisaste. No es buena idea actualizar solo una carpeta. Cuando actualizas tienes que actualizar toda el codigo, o unicamente un commit si es que sabes lo que haces y que no hay dependancias.

Para actualizar tu plataforme, si no usas git en tu instalacion, te indico que la version 1.11.6 esta para salir hoy dia normalemente entonces podras actualizar toda tu plataforma y esto deberia de solucionar tu problema.

**Comment by fergimon** [comment]
Buenos días 
Gracias por tu colaboración, este problema me sucede únicamente con un solo curso, con los demás si la realiza normal la copia.

**Comment by NicoDucou** [comment]
@fergimon si se realiza correctamente con los demas cursos se necitaria mirar en tus error.log para ver cual es el error que esta generado con este curso especifico porque no lo puedo reproducir.

Si no tienes acceso al error.log, lo que se puede hacer tambien es de poner tu plataforma en modo de desarrollo. En la pagina de gestion de los parametros del sistema, busca la opcion "Tipo de servidor" y selecciona  "Servidor de desarrollo", lanza la copia del curso y el error puede aparecer directamente en la pantalla. Una vez que tienes el error regresas la configuracion de "Tipo de servidor" para que no aparecen cosas extranas a los demas usuarios.

**Comment by ywarnier** [comment]
Sin feedback. Cerrando. No dudar en volver a abrir si el problema se evidencia de alguna manera que nos permita analizarlo con más detalle.
