### ISSUE TITLE
Bug creation d'exercices à partir de la banque de questions

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2343]
### Current behavior / Resultado actual / Résultat actuel
![vue1](https://user-images.githubusercontent.com/24505996/35081590-55ae4ffc-fc15-11e7-825f-2a8411139f2c.png)
J'ai créé des exercices avec des questions et des catégories. Quand je veux créer un autre exercice en allant piocher dans les catégories il est annoncé : il n' y a aucune question actuellement
### Expected behavior / Resultado esperado / Résultat attendu
Voir les questions par catégorie pour les choisir et les intégrer dans un exercice
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
https://11.chamilo.org/main/exercise/question_pool.php?cidReq=CATEGORIESDEQUESTIONSPROBLEME&id_session=0&gidReq=0&gradebook=0&origin=&fromExercise=772
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.X

**Comment by NicoDucou** [comment]
Je viens de tester et en fait le problème se pose uniquement quand on est dans le cours de base.
À partir du moment où l'on sélectionne une session sur la page https://11.chamilo.org/main/exercise/question_pool.php?cidReq=CATEGORIESDEQUESTIONSPROBLEME&id_session=49&gidReq=0&gradebook=0&origin=&selected_course=183&courseCategoryId=42&exerciseId=0&exerciseLevel=-1&answerType=-1&session_id=49&recup=2125&fromExercise=772 alors les questions de la session apparaissent.

C'est probablement juste un problème de session_id dans la requête qui doit retourner la liste de questions quand aucune session n'est sélectionné dans le formulaire.

**Comment by alexiye** [comment]
Cela fonctionnait avant de faire une mise à jour de 1.11.X ce week-end.

**Comment by alexiye** [comment]
C'est ok pour moi, cela fonctionne à nouveau.
