### ISSUE TITLE
Replace strings that are using get_lang() to use English instead of a label

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2346]
We will use gettext in chamilo 2, the strings should be changed using "english" instead of a label.

For example, in the chamilo code if this is found:

`get_lang('UserMustHaveTheDrhRole')`

Then it should be replaced to:

`get_lang('Users must have the HR director role')`

In case the text is very long and contains a big paragraph we will leave it as a label. 

For example for variable "HelpUsersFolder" we will leave it like this:

```
$HelpUsersFolder = "INFORMATION VISIBLE TO THE TEACHER ONLY:\nThe users folder contains a folder for each user who has accessed it through the documents tool, or when any file has been sent in the course through the online editor. If neither circumstances has occurred, then no user folder will have been created. In the case of groups, files that are sent through the editor will be added in the folder of each group, which is only accessible by students from this group.
<br /><br />
The users folder and each of the included folders will be hidden by default in for all students, but each student can see the contents of his/her directory through the online editor. However, if a student knows the address of a file or folder of another student, he may be able to access it.
<br /><br />
If the folder of a student is visible, other students can see what it contains. In this case, the student that owns the folder can also (from the documents tool and only in his/her folder): create and edit web documents, convert a document into a template for personal use, create and edit drawings in SVG and PNG formats, record audio files in WAV format, make audio files in MP3 from a text, make snapshops from a webcam, send documents, create folders, move folders and files, delete folders and files, and download backup of his/her folder.
<br /><br />
Moreover, the documents tool is synchronized with the file manager of the online editor, so changes in the documents triggered in any one of these will affect both.
<br /><br />
As such, the user folder is not only a place to deposit files, it becomes a complete manager of the documents students use during the course. Also, remember that any user can copy a file that is visible from any folder in the documents tool (whether or not he is the owner) to his/her portfolios or personal documents area of social network, which will be available to him/her for use in other courses.";
```

The idea of this issue is to create a script that replaces all the "get_lang" uses in chamilo.
It should be send via a PR.

**Comment by jmontoyaa** [comment]
Any updates?

**Comment by ywarnier** [comment]
I'm progressing on that in main/cron/lang/switch_files_to_gettext.php.
Tricky business ;-)

**Comment by ywarnier** [comment]
@jmontoyaa I added the script to the master branch, *but* I need it to be able to load libraries from Chamilo to work, and at the moment I cannot get the master installer to work.

This being said, you have to test that in a branch, otherwise it will modify all of your php and tpl files and you might not want that on your working copy.

Could you test it?
- create a gettext branch
- open the script
- remove the "die()" call at the beginning
- check if api_get_path(SYS_PATH) actually returns the root path of your Chamilo install
- get out of the script
- change to a user that can execute a change on all the code files of your Chamilo install
- call it (php switch...)
- let it run for ~3 minutes

Normally, all get_lang() (or get_lang filter) calls should have been replaced by the English string, and everything should work.

**Comment by jmontoyaa** [comment]
I follow the instructions above and there are some issues:
Note: I'm using PHP 7.2

In api.lib.php I have:

```php
<?p'h'p
/* For licensing terms, see /license.txt */

use C'h'amilo\CoreBundle\Entity\SettingsCurrent;
use C'h'amilo\CoreBundle\Framework\Container;
use C'h'amilo\CourseBundle\Entity\CItemProperty;
use C'h'amilo\UserBundle\Entity\User;
use C'h'amiloSession as Session;
use Symfony\Component\Finder\Finder;

/**
 * T'h'is is a code library for C'h'amilo.
 * It is included by default in every C'h'amilo file (t'h'roug'h' including t'h'e global.inc.p'h'p)
 * T'h'is library is in process of being transferred to src/C'h'amilo/CoreBundle/Component/Utils/C'h'amiloApi.
 * W'h'enever a function is transferred to t'h'e C'h'amiloApi class, t'h'e places w'h'ere it is used s'h'ould include
 * t'h'e "use C'h'amilo\CoreBundle\Component\Utils\C'h'amiloApi;" statement.
 *
 * @package c'h'amilo.library
 */
```

In main/admin/access_url_add_courses_to_url.php

```php
$tool_name = get_lang(''Add courses to an URL'');
$interbreadcrumb[] = ['url' => 'index.php', 'name' => get_lang(''Administration'')];
$interbreadcrumb[] = ['url' => 'access_urls.php', 'name' => get_lang(''Multiple access URL / Branding'')];
```


In certificates/index.php
```php
$action = isset($_GET['action']) ? $_GET['action'] : null;
$certificate = new 'Certificate'($_GET['id']);
...

echo Display::return_message(
        get_lang(''Certificate'ExistsButNotPublic'),
        'warning'
);

```

In main/dashboard/dashboard_controller.php

```php
class 'Dashboard'Controller
{
    private $user_id;

```

etc ...

**Comment by jmontoyaa** [comment]
I changed this:

```
system("sed -i \"s#$term#'$translation'#g\" $file");

```

To this:

```
system("sed -i \"s#$term#$translation#g\" $file");

```

And it works well ... but there are some issues:

because of some text with apostrophes but there are not many cases.

In api.lib.php

```php
$msg = Display::return_message(
            get_lang('Sorry, you are not allowed to access this page, or maybe your connection has expired. Please click your browser's "Back" button or follow the link below to return to the previous page.').'
            <script>function goBack(){window.history.back();}</script>',
            'error',
            false
        );
....
    if ($seconds == -1) {
        return
            get_lang('Unknown').
            Display::return_icon(
                'info2.gif',
                get_lang('The datas about this user were registered when the calculation of time spent on the platform wasn't possible.'),
                ['align' => 'absmiddle', 'hspace' => '3px']
            );
    }


```

**Comment by jmontoyaa** [comment]
The fix works well (after that change), we can manually fix those issues apostrophes issues, because the script fix most of the other cases.

Or maybe fix the apostrophes in the english/trad4all and then run the script ...

**Comment by ywarnier** [comment]
Yes, we could simply do a `$translation = str_replace("'", "\\'", $translation);` before using $translation in the sed command.

**Comment by ywarnier** [comment]
I still have a doubt concerning whether it works when there are 2 get_lang() calls on the same line, but I haven't been able to find an example yet.

**Comment by jmontoyaa** [comment]
you're right:

in learnpath.class.php:

```php

$return .= Display::return_message(
    '<strong>'.get_lang('Warning ! ! !').' !</strong><br />'.get_lang('Warning ! ! !EditingDocument'),
    false
);

// trad4all

$Warning = "Warning !";
$WarningEditingDocument = "When you edit an existing document in Courses, the new version of the document will not overwrite the old version but will be saved as a new document. If you want to edit a document definitively, you can do that with the document tool.";

```

**Comment by ywarnier** [comment]
Oh, but that's a completely different issue to what I was thinking. That's because of the quotes: it checks for the string without surrounding quotes and it gets the second one :smile: 
So we need the quotes in the first part of the sed expression.
That was the point of the quotes there, but the quotes can also be double quotes. OK, so back to the quotes, something like this should work?:
```
system("sed -i \"s#['\"]$term['\"]#'$translation'#g\" $file");
```

**Comment by ywarnier** [comment]
I sent a fix. Now it should work perfecly enough. I'm not sure when you want to make the change, because we won't be able to merge from 1.11.x anymore, and I feel like we still have around 1 month of very active 1.11 development to go before we slow down.
Or will merges happen smoothly?

**Comment by jmontoyaa** [comment]
That's the issue I mention some time ago ... If we still have to do stuff in 1.11.x, merges will be very hard/slow to do ... but behat tests can't work for master for now ... so they are connected ...
