### ISSUE TITLE
Instalación Chamilo 1.11.6 - Test en entornos PHP

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2347]
### Current behavior / Resultado actual / Résultat actuel
Instalación de Chamilo en entornos de PHP 5.6, 7.0, 7.1 y 7.2
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Instalación Chamilo 1.11.6
Servidor Windows (Apache, MySQL 5.6 y 5.7)
PHP 5.6. Ok, instalar, crear curso con y sin datos de ejemplo (chamilo-1.11.6-php5.zip)
PHP 7.1. Ok, instalar, crear curso con y sin datos de ejemplo (chamilo-1.11.6-php7.zip)
PHP 7.2. Ok, instalar, crear curso con y sin datos de ejemplo (chamilo-1.11.6-php7.zip)
PHP 7.0 - Error - (ficheros utilizados chamilo-1.11.6-php7.zip y chamilo-1.11.6-php7.tar.gz) ¿Composer generado (vendor y web) en PHP 7.1?
PHP 7.0 - OK - En un entorno PHP 5.5 y 5.6 clonando el git de la rama 1.11 y ejecutando composer permite realizar la instalación sin errores en PHP 7.0.

Log de error en PHP 7.0

**[Fri Jan 19 13:57:03.556444 2018] [:error] [pid 12532:tid 948] [client 192.168.1.111:33162] PHP Fatal error:  Uncaught TypeError: Return value of Doctrine\\Common\\Annotations\\AnnotationRegistry::registerFile() must be an instance of Doctrine\\Common\\Annotations\\void, none returned in ...\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationRegistry.php:67\nStack trace:\n#0 ...\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\Configuration.php(152): Doctrine\\Common\\Annotations\\AnnotationRegistry::registerFile('......')\n#1 ...\vendor\\doctrine\\orm\\lib\\Doctrine\\ORM\\Tools\\Setup.php(71): Doctrine\\ORM\\Configuration->newDefaultAnnotationDriver(Array, false)\n#2 ...\main\\inc\\lib\\database.lib.php(744): Doctrine\\ORM\\Tools\\Setup::createAnnotationMetadataConfiguration(Array, true, '...-...', NULL, false)\n#3 ...\main\\inc\\lib\\database.lib.php(141): Database::getDoctrineConfig('...-...')\n#4 ... in ...\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationRegistry.php on line 67, referer: .../main/install/index.php?running=1&installType=&updateFromConfigFile=**

**Sugerencia para el proceso de instalación:**
En ... main/install/index.php?running=1&installType=new&updateFromConfigFile=

**Modificar el texto de creación de bases de datos.**

Paso 4 de 6 – Parámetros de las bases de datos MySQL
El script de instalación creará las principales bases de datos de Chamilo. Por favor, recuerde que Chamilo necesitará crear varias bases de datos. Si sólo puede tener una base de datos en su proveedor, Chamilo no funcionará.

**Propuesta:**
Se aconseja crear la base de datos previamente a la instalación de Chamilo. 
Consulte con su proveedor si tiene dudas sobre estos parámetros.

Realizaremos pruebas adicionales en Linux (Debian y Ubuntu).

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Chamilo 1.11.6 estable

**Comment by ywarnier** [comment]
Sí, es cierto, fue generado en PHP 7.1. No tengo sistema en PHP 7.0. Podrías hacer el paquete sobre 7.0? (te pasaría las instrucciones)

**Comment by ywarnier** [comment]
Eso es buena noticia porque si es solo esto entonces no tengo que hacer nuevos cambios en Git.

**Comment by nosolored** [comment]
Envía las instrucciones y generamos el paquete para PHP 7.0.

**Comment by v4ld3rr4m4** [comment]
Buenas tardes no tuve  ningun problema en instalar en chamilo1.11.6 en windows 7 sin ebargo cuando hago login en el portal me aparece: **No está autorizado a ver esta página o su conexión ha caducado**.

Algiuna idea de como resolverlo?
![login_err](https://user-images.githubusercontent.com/31418580/36284456-b7634326-1275-11e8-84a9-8f8065154876.jpg)

**Comment by ywarnier** [comment]
@v4ld3rr4m4 por favor registra otra tarea con este tema. Solo un tema por "issue". Gracias.

**Comment by ywarnier** [comment]
@nosolored El procedimiento para re-compilar el paquete completo con soporte para PHP 7.0 es el siguiente.
Por favor hacerlo todo sobre una máquina PHP 7.0 que tiene composer instalado.
```
git clone -b 1.11.x https://github.com/chamilo/chamilo-lms chamilo-1.11.6
cd chamilo-1.11.6
git reset --hard 040e963c
composer update
rm -rf tests
cd ..
tar zcf chamilo-1.11.6-php7.tar.gz chamilo-1.11.6
```
Este .tar.gz resultante *es* el paquete de Chamilo 1.11.6 compatible con PHP 7.0. De ahí hay que probar instalarlo (de preferencia en 7.0 *y* 7.1 y 7.2 para ver si todo bien.

**Comment by nosolored** [comment]
Ok @ywarnier  generamos y reportamos.

**Comment by nosolored** [comment]
@ywarnier hemos realizamos los test

Lo generamos en Ubuntu con PHP 7.0.27
Se eliminan directorios test, .git y .github antes de generar el tar.gz

Testeado chamilo-1.11.6-php7.tar.gz en Windows 
PHP 7.0.27 - OK
PHP 7.1.14 - OK
PHP 7.2.2 - OK

Pruebas realizadas:
Se crea una base de datos específica para cada prueba.
Se instala en cada versión de PHP.
Se crea curso con contenidos de ejemplo.
Se navega por el curso creado y por la plataforma.

**Comment by v4ld3rr4m4** [comment]
AGradezco  , verificare en Windows y luego en  el Anterggos(ArchLinux)

**Comment by nosolored** [comment]
@ywarnier revisa correo.

**Comment by ywarnier** [comment]
@nosolored Probé el paquete en Ubuntu 16.04 con PHP 7.0 y 17.10 con PHP 7.1 y todo bien. Subo el archivo como remplazo del actual ahora.

**Comment by ywarnier** [comment]
Hecho!

**Comment by ywarnier** [comment]
He cambiado también la versión en https://version.chamilo.org/version.txt para que indique que la versión 1.11.6 es la última estable y que la gente pueda empezar a migrar.

**Comment by v4ld3rr4m4** [comment]
La pruebo de una vez, haciendo la descarga

**Comment by ywarnier** [comment]
@v4ld3rr4m4 que fue?

**Comment by v4ld3rr4m4** [comment]
https://github.com/chamilo/chamilo-lms/releases     (descargue la de aqui) como verifico si efectivamente es la que comentas has subido?

**Comment by rcarhuaricra** [comment]
esto se llego a corregir ???

**Comment by ywarnier** [comment]
Por nuestro lado consideramos que sí, pero no importa porque ahora la estable es la 1.11.10 y no se debería instalar la 1.11.6
