### ISSUE TITLE
infección con malware

### ISSUE THREAD

**Issue by fdizonno** [chamilo/chamilo-lms#2348]
Tengo Chamilo instalado en mi servidor hospedado en GoDaddy y recibi el siguiente mensaje:

We recently completed a routine security checkup of our servers and platforms. Our scans flagged your zonaelectronica.org hosting accounts as containing possible malware.

Please sign in to your hosting account and review the following content and remove or fix the files listed below:
php.backdoor.COOKIE_eval.005.02 - /public_html/zonaelectronica.com/campus/main/admin/db.php
php.backdoor.uploader.006.03 - /public_html/zonaelectronica.com/campus/main/auth/profile.php
php.malware.include.006 - /public_html/zonaelectronica.com/campus/main/auth/shibboleth/init.php
php.backdoor.uploader.006.03 - /public_html/zonaelectronica.com/campus/main/forum/forumfunction.inc.php
php.backdoor.uploader.006.03 - /public_html/zonaelectronica.com/campus/main/inc/lib/blog.lib.php

Estoy utilizando la versión 1.11.2 de chamilo

Me puede alguien indicar si esto es posible,
Saludos cordiales
Francisco Di Zonno

**Comment by jmontoyaa** [comment]
Han existido unos problemas de seguridad en unas versiones de Chamilo que ya han sido corregidas.

Lista de issues y sus correciones:
https://support.chamilo.org/projects/1/wiki/Security_issues

Se recomienda actualizar Chamilo a su última version 1.11.6

**Comment by bassuma** [comment]
Hi.
@jmontoyaa
Is chamilo 1.11.6 now available for download?
Thank you
:)

**Comment by jmontoyaa** [comment]
@bassuma yes, here:

https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.6

**Comment by bassuma** [comment]
Thank you
;)

**Comment by NicoDucou** [comment]
@fdizonno can you tell us if this task can be close with the indication from Julio ?
