### ISSUE TITLE
Course category in multiple urls config

### ISSUE THREAD

**Issue by Alphabc** [chamilo/chamilo-lms#2350]
Hi,

Using Chamilo 1.11.4 with multiple urls, I created a course category on 1 child platform
PHY / Physique
Then, I thought it would have been better to create it on the mother platform. Therefore, I tried to create a new course category in the "mother platform" with same requirements
PHY / Physique
The issue is that I cannot do it, but the system tells me that the category has been created

1- category list on child platform:
![image](https://user-images.githubusercontent.com/24738945/35235046-53789954-ffa3-11e7-86c9-5aff499b7dea.png)

2- trying to create it on mother platform, with success message:
![image](https://user-images.githubusercontent.com/24738945/35235112-815136a6-ffa3-11e7-93a8-e2de18f35ed8.png)
(BTW, there is a small translation issue: we are on "course category" but the label means "question category", see in blue)

3- list showing the category has not been created:
![image](https://user-images.githubusercontent.com/24738945/35235190-b25322b4-ffa3-11e7-9fc7-df562548325c.png)

(It works if I delete the category on the child platform though... So the issue is mainly because of the **success message** which should be at least "category not created" or better if possible "this category already exists on child platform and cannot be created")

Thx!

**Comment by jmontoyaa** [comment]
I added a fix for this, now you can only edit categories of your own portal.
I fix the language variable too:

https://github.com/chamilo/chamilo-lms/commit/0684dd5717e20023cfe382a0c080ebc29fbdb5f8

**Comment by NicoDucou** [comment]
I just check and it seems all good for me.
If I create a course category on one of the URL, then if I try to create the same category on another URL then I get an error message indicating : 
"Le code de cette catégorie est déjà utilisé !"

@Alphabc to have this working on your plateform you will have to update to the last Chamilo version.
Let us know if it works for you so we can close this issue.

**Comment by ywarnier** [comment]
No feedback provided after fix. Considering closed.
