### ISSUE TITLE
Duplicate MathJax

### ISSUE THREAD

**Issue by jwarnier** [chamilo/chamilo-lms#2353]
### Issue detail
MathJax, which is the largest (176MB) single external module/plugin/whatever used in Chamilo, is present twice, and identical:
- web/assets/ 
- app/Resources/public/assets/

It should be possible to remove one of them, shrinking Chamilo's footprint dramatically (about 20% overall).

This would particularly help in constrained environments such as Docker images.

### Chamilo Version
Noticed at least in Chamilo LMS 1.11.4.

**Comment by jmontoyaa** [comment]
For version 2.x there will be only one place. Already working on it here  #1990 #2324
