### ISSUE TITLE
Which version of SCORM does Chamilo support?

### ISSUE THREAD

**Issue by lilit1141** [chamilo/chamilo-lms#2369]
I'm using Chamilo 1.11.4 version. Which version of SCORM Chamilo have support?

     SCORM 1.1
     SCORM 1.2
    SCORM 2004 2nd Edition
    SCORM 2004 3rd Edition
    SCORM 2004 4th Edition

**Comment by NicoDucou** [comment]
@lilit1141 Chamilo support Scorm 1.2
You should always try to get your content in this format.
