### ISSUE TITLE
Error al iniciar instalación en la base de datos.

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2370]
### Current behavior / Resultado actual / Résultat actuel
Aparece el siguiente error al momento de iniciar la instalación.

![captura](https://user-images.githubusercontent.com/2940509/35768406-14209b42-08c9-11e8-87b1-bd0e7723797f.JPG)

Se borro el vendor y el composer.lock y sigue igual

### Expected behavior / Resultado esperado / Résultat attendu
Siguiente paso del instalador
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Una instalación limpia
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jmontoyaa** [comment]
Qué versión de PHP usas?
Has hecho un composer update?
Parece un problema de código de php7 en un php5...

```
private function getNamespacedId(string $id) : string
{
```

**Comment by aragonc** [comment]
Tenia PHP 5 luego le instale PHP7, tengo que hacer adicional algo extra para que no haiga conflicto, porque ahora me sale que tiene PHP7 y no 5, aunque no recuerdo que quiere el php5 ![ddd](https://user-images.githubusercontent.com/2940509/35810674-81a2a36c-0a5a-11e8-82e4-23667b35e648.png)

**Comment by jmontoyaa** [comment]
This looks is not a Chamilo issue, check your phpinfo. Try to delete all php and re install only with php 7.1 packages.

**Comment by hichamon306** [comment]
Hi,
PHP 7.1 only available on ppa repo , there is no officiel package for ubuntu 14.04. why do you recommend php  7.1 packages ?
Best regards

**Comment by jmontoyaa** [comment]
@hichamon306 I recommended in this case because @aragonc installed php 7.1 in his PC.

**Comment by hichamon306** [comment]
Ok thanks

**Comment by ywarnier** [comment]
@hichamon306 we know of an issue with *only* PHP 7.0 (not PHP 5.6, nor 7.1, nor 7.2), so we recommend using PHP 7.1 instead of 7.0 until we fix the issue.
