### ISSUE TITLE
How to configure HTTPS?

### ISSUE THREAD

**Issue by sadagoban** [chamilo/chamilo-lms#2371]
### Current behavior / Resultado actual / Résultat actuel

I bought SSL Certificate Recently for my website : www.pharmdinfo.com  

Hosting:  GoDaddy Sharing Host

Chamilo Application  Path Route: http://www.pharmdinfo.com/elearn/index.php

At present HTTPS redirection is not working for Chamilo Application. 

I am a Pharmacist, Kindly help me to configure the HTTPS redirection coding 

Regards

SADAGOBAN

**Comment by bassuma** [comment]
HI.
See if this is what you are looking for.
![capturar](https://user-images.githubusercontent.com/25286516/35780717-c7704b22-09c6-11e8-9332-f9b46c63125b.PNG)
![capturar2](https://user-images.githubusercontent.com/25286516/35780718-cb4d308e-09c6-11e8-956d-8a814a413586.PNG)

**Comment by ywarnier** [comment]
If you had already Chamilo installed previously in HTTP, then you need to update several things.
The *easiest* procedure is to actually install a fresh Chamilo directly in HTTPS, but if your portal is already in use, then you will have to modify app/config/configuration.php and find the "root_web" configuration param and change it to https://.
Explaining redirects and more complete stuff is actually a hell of a work if you don't have an idea of how to configure a web server manually, so I'll assume you don't want to do that and changing configuration.php is enough for you.

**Comment by hichamon306** [comment]
@sadagoban are you working on apache or nginx web server ?

**Comment by sadagoban** [comment]
Thank you all for your response. 

@bassuma  I did that already. 
@ywarnier  At present i excluded HTTPS redirection for Chamilo Directory Folder. 
@hichamon306  Apache.

**Comment by hichamon306** [comment]
@sadagoban  you can enable first rewrite mode `sudo a2enmod rewrite` restart apache then  you have tow possibilities : 

1. edit your virtualhost by adding this line 
`    <VirtualHost *:80>
    .....
    Redirect permanent / http://www.pharmdinfo.com/elearn/
    ....
    </VirtualHost>`

2. add htaccess file to  your root path with this few lines
`    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}`

**Comment by sadagoban** [comment]
@hichamon306  I tried second one already and i got Mixed Content error

  How to implement the first one ? I need some technical help.

**Comment by hichamon306** [comment]
if you got mixed content error , you should just configure chamilo to use https url 
edit app/config/configuration.php and replace 
```php
$_configuration['root_web'] = 'http://www.pharmdinfo.com/elearn/';

```
by this 
```php
$_configuration['root_web'] = 'https://www.pharmdinfo.com/elearn/';

```
this should work 

you can also  edit virtualhost file  in /etc/apache2/site-available/_yoursite_.conf
put this 
```XML   
 <VirtualHost *:80>  
    .....  
    Redirect permanent / https://www.pharmdinfo.com/elearn/  
    ....  
    </VirtualHost>  
```
restart apache
`apachectl restart` or `service apache2 restart`

hope this work for you

**Comment by sadagoban** [comment]
Thanks @bassuma . I will try and i will let you know the status soon.

**Comment by sadagoban** [comment]
Thanks @hichamon306  i will try the codes i will let you know the status soon.

**Comment by ywarnier** [comment]
Even with the fix above, the "mixed content" error comes because you show content coming from an HTTP page on an HTTPS page.
To avoid that, make sure you check all links on your page that point to HTTP instead of HTTPS, edit them to HTTPS and try again.
You can see a list of all media loaded on your page in Firefox through the HTTPS URL symbol (keylock) -> View -> More information -> Media

**Comment by NicoDucou** [comment]
@sadagoban did this solve your problem ?

**Comment by ywarnier** [comment]
Considered fixed. Thanks all for your help.

**Comment by ricdanlu** [comment]
Obrigado pela ajuda

**Comment by shiddugmail** [comment]
Hello Friends, 
My scenarios was follows:
we installed Chamilo on godaddy by selected https://www.domain.com
we could open the website on https://www.domain.com without any issue and all working.

But we open the link http://www.domain.com or http://domain.com or domain.com or any combination without using s to http as suffix, the pages dont look good my suspect is assets are not referred correctly. 

I landed up on this issue page and tried to remove the s suffix to the http at line 100 
Changed the file /public_html/konnurselearn.com/app/config/configuration.php
what was it: $_configuration['root_web'] = 'https://www.konnurselearn.com'; at line 29
Changed to: $_configuration['root_web'] = 'http://www.konnurselearn.com'; at line 29

Now it is the other way i.e. with https it does not show pages correctly and does not use the assets. 

please help how to ensure that whether I use any of the following urls the assets should be applied:
https://www.domain.com
https://domain.com
http://www.domain.com 
http://domain.com 
domain.com

Thanking you in advance.
Regards,
Shiddu

**Comment by ywarnier** [comment]
Hi @shiddugmail 
Using both HTTP and HTTPS is bad practice (offering HTTP will reduce your protection to the level of this insecure protocol).
The root_web config is exclusive: you can only set one URL. You could go around that with the techniques explained here: https://beeznest.com/blog/2013/01/15/answering-to-different-addresses-with-chamilo/ but I would simply suggest you put a redirection in place at the Apache configuration level (or in your CPanel or tool you use for that) to force the redirection from HTTP to HTTPS for all users. Also, audio recording in Chamilo will *not* work in a recent browser without HTTPS.
