### ISSUE TITLE
How to set hosting_limit_disk_space ?

### ISSUE THREAD

**Issue by sadagoban** [chamilo/chamilo-lms#2375]
Hello there,

I am using Godaddy Shared Hosting for my website. 

Installed Chamilo using Installatron Application .

Kindly help me with coding to expand its hosting_limit_disk_space from 1.7 GB to 15 GB.

Thanks in advance.

Regards,

SADAGOBAN

**Comment by ywarnier** [comment]
Dear @sadagoban, your question is difficult to understand. Please clarify. It seems like you want us to help you go against the limits set by your hosting provider.

**Comment by sadagoban** [comment]
Dear Ywarnier, Yes i requested for help. Its not an issue or bug.  Thanks for your suggestions.
