### ISSUE TITLE
trojan alert + troubles with upgrade to 1.11.6

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2380]
### Current behavior / Resultado actual / Résultat actuel
After upgrade from 1.11.4 to 1.11.6 (overwriting 1.11.4 files from server with files from 1.11.6 zip file from php5 version)
trojan alert (+deleting) from comodo anti virus from file:
main/inc/lib/javascript/ViewerJS/webodf.js

In the learning paths, only the folders are ok, the most files under the folders are gone
The name of the learning path has also changed to another existing learning path.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
upgrade from 1.11.4 to 1.11.6
![capture](https://user-images.githubusercontent.com/26413828/36255457-6b919b08-124f-11e8-8189-4ba173d90027.JPG)

**Comment by jmontoyaa** [comment]
That file didn't change from 1.11.4:

These are the changes of the file, nothing change since 2014

https://github.com/chamilo/chamilo-lms/commits/1.11.x/main/inc/lib/javascript/ViewerJS/webodf.js

**Comment by Morepizza1** [comment]
I have turned off the antivirus and I uploaded this file with the same result.
Learning paths are scrambled:
- Learning path titles are switched
- Learning path folder names are often gone
- Learning path files are 95% gone

**Comment by jmontoyaa** [comment]
Those are different issues. Please open a new issue for the upgrade problems.

**Comment by Morepizza1** [comment]
ok, done.

**Comment by jmontoyaa** [comment]
Can you check if your antivirus detects something with the official ViewerJS package here?

http://www.webodf.org/download/wodotexteditor-0.5.1.zip

**Comment by jmontoyaa** [comment]
Can you check also with the latest version 0.5.9?

http://www.webodf.org/download/webodf.js-0.5.9.zip

**Comment by Morepizza1** [comment]
0.5.1 gives an trojan, see picture, 0.5.9 is clean.
![capture](https://user-images.githubusercontent.com/26413828/36300177-6effc9b6-1300-11e8-90d5-c1a17dc71e9e.JPG)

**Comment by jmontoyaa** [comment]
Then this is an issue of that js library. I just updated to the latest version in chamilo

**Comment by NicoDucou** [comment]
Hi @Morepizza1 

We do not have the antivirus to check with the latest version of Chamilo. Can you test it and tell us if everything is fine now ?

**Comment by Morepizza1** [comment]
The anti virus I use is free. You can find it here:
https://www.comodo.com/home/internet-security/free-internet-security.php

I have scanned the 2 zip files from chamilo 1.11.6 (php5 & php7) from this link:
https://chamilo.org/chamilo-lms/

The trojans are present, see pics.

![scan ch php5](https://user-images.githubusercontent.com/26413828/36940450-5b9871da-1f43-11e8-8917-fdd8652d97a6.JPG)
![scan ch php7](https://user-images.githubusercontent.com/26413828/36940451-5bb14a20-1f43-11e8-9a4a-e54199c8184f.JPG)

**Comment by NicoDucou** [comment]
@Morepizza1 The change done by Julio was not included in the 1.11.6 release it is on the last version of Chamilo on Github. you can download the code from here (but it's just the code) : https://github.com/chamilo/chamilo-lms/archive/1.11.x.zip

And passed it to your antivirus for scan.
I can not install your antivirus because it is not available for Ubuntu Linux.

Let me know if it's all correct now so that it will be fine for the next release.

**Comment by Morepizza1** [comment]
Scan is ok.
![scan ch 1 11 x](https://user-images.githubusercontent.com/26413828/37007439-9af15f22-20dd-11e8-9975-79ea3f6bccf2.JPG)

**Comment by NicoDucou** [comment]
Thank you @Morepizza1
So I close this task.
If you have trouble with the installation or upgrade open a new issue as indicated by Julio so as not to mix everything and to have a better organization of issues.
