### ISSUE TITLE
troubles with upgrade to 1.11.6

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2381]
### Current behavior / Resultado actual / Résultat actuel
After upgrade from 1.11.4 to 1.11.6 (overwriting 1.11.4 files from server with files from 1.11.6 zip file from php5 version)

Learning paths are scrambled:

Learning path titles are switched
Learning path folder names are often gone
Learning path files are 95% gone

**Comment by Morepizza1** [comment]
Extra info: same learning path before and after upgrade:
![lp](https://user-images.githubusercontent.com/26413828/36300521-f9912e7a-1301-11e8-876a-3e83a8e51388.jpg)

**Comment by jmontoyaa** [comment]
Well it looks that you have an old chamilo installation, maybe from 1.9.x?
Only if you can manage backups and running scripts.

**Make a backup of your database, before any change. If something goes wrong you can restore it**

You may fix this running this script: (remove the "exit" part).
https://github.com/chamilo/chamilo-lms/tree/1.11.x/tests/scripts/fix_lp_id_to_iid.php
Better to run this in a test/development environment.

**Comment by Morepizza1** [comment]
The pictures are from 1.11.4 (works ok) and 1.11.6 (wrong) as mentioned above.
The 1.11.4 was an upgrade from 1.9.10.4

Is it possible to integrate this script in the installation procedure of 1.11.6?

**Comment by jmontoyaa** [comment]
Yes, we are making some tests in order to add it later.

**Comment by ywarnier** [comment]
Goal of this issue: make sure that the script to fix LP IDs is integrated into the migration process from 1.11 to 2.0

**Comment by ywarnier** [comment]
A good way to do this more easily would be to detect issues with lp_id and block the migration if there is a detected issue

**Comment by christianbeeznest** [comment]
I did testing of migration from 1.11.4 to 1.11.6  and error is not detected.
