### ISSUE TITLE
Missing icon main/img/icons/22/calculated_answer.png

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2382]
Files missing:

main/img/icons/22/calculated_answer.png
main/img/icons/22/calculated_answer_na.png 

The icon should have the correct size.

![selection_002](https://user-images.githubusercontent.com/158935/36257960-433d2898-1259-11e8-93a6-854863734836.png)

**Comment by aragonc** [comment]
Se agrego el icono que faltaba.
