### ISSUE TITLE
Wrong icon color main/img/icons/22/matchingdrag.png

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2383]
This file is in black and white, it should have color:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/img/icons/22/matchingdrag.png

![selection_003](https://user-images.githubusercontent.com/158935/36258230-4260285c-125a-11e8-910c-0478bf3d4584.png)

**Comment by aragonc** [comment]
error in the icon when creating it in black and white
![icons_colors](https://user-images.githubusercontent.com/2940509/37118633-e24eaee2-2222-11e8-8128-a6bd4ced53cc.png)

**Comment by jmontoyaa** [comment]
:+1:
