### ISSUE TITLE
Visibilidad de documentos en sesión desde curso base - refs BT#14009

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2388]
### Current behavior / Resultado actual / Résultat actuel
Al poner un documento como visible en una sesión, estando oculto en el curso base, el documento desaparece de la sesión

### Expected behavior / Resultado esperado / Résultat attendu
Poner  como visible el documento estando invisible en curso base

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Subir documento en curso base
- Ponerlo como oculto
- Entrar en una sesión
- Poner el documento como visible

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by NicoDucou** [comment]
@AngelFQC , BT#14009 esta cerrado y parece que todo funciona bien ahora. Se puede cerrar este issue ?

**Comment by AngelFQC** [comment]
Sí :smile:
