### ISSUE TITLE
Affichage des résultats d'un exercice remplir les blancs avec plusieurs solutions possibles

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2391]
### Current behavior / Resultado actual / Résultat actuel
L'affichage des résultats n'est pas très lisible et il prête à confusion. ( sauts à la ligne et non affichage de toutes les possibilités, réponses correctes barrées..)
### Expected behavior / Resultado esperado / Résultat attendu
Si on a plusieurs réponses possibles, voir toutes les possibilités dans l'affichage des résultats
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
créer un exercice remplir les blancs  avec plusieurs possibilités de réponses. 
exemple : [On||Je||Il||Elle]
![exercice remplir les blancs avec parfois plusieurs possibilites](https://user-images.githubusercontent.com/24505996/36368755-0b12653e-1559-11e8-86ba-9640fd728630.png)
![affichage des resultats](https://user-images.githubusercontent.com/24505996/36368760-0e891b5e-1559-11e8-8a9d-ee99f1157478.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
Voilà une excellente occasion (vu le niveau de détail auquel nous arrivons) de contribuer à Chamilo: soit en fournissant un patch, soit en contribuant économiquement :-)

**Comment by alexiye** [comment]
Qu'est-ce qu'un patch ?
Dans la versions 1.9.10.2 cela fonctionnait correctement  il me semble :-)

**Comment by ywarnier** [comment]
Un patch est un correctif de code (PHP ou JavaScript) basé sur le code actuel de Chamilo, et qui corrige le problème, et que nous vérifions (pour nous assurer qu'il respecte les [conventions](https://github.com/chamilo/chamilo-lms/wiki/Coding-conventions) et qu'il n'introduise pas de vulnérabilité de sécurité) avant de l'intégrer.
Il est possible que cela ait fonctionné en 1.9.10.2 mais que, suite à l'ajout d'autres fonctionnalités, celle-ci ait été légèrement endommagée.
Chamilo, c'est un projet Open Source, mais le gens qui y travaillent ont besoin de vivre, comme tout le monde. Pour toi, c'est peut être ton employeur qui couvre cela. Pour nous, ce sont une série d'entreprises [https://chamilo.org/providers/] qui contribuent sans relâche au projet et qui assurent que des développeurs continuent de contribuer à une base unique et gratuite de Chamilo pour le monde entier.

**Comment by alexiye** [comment]
Je suis professeur des écoles et , par an, j'ai un budget d'environ 1000 euros pour couvrir toutes les fournitures de la classe. J'ai moi-même installé les rideaux dans la classe vu que cela n'est pas une priorité pour la municipalité.
Depuis plusieurs années j'ai introduit l'utilisation de chamilo dans ma classe. J'ai réussi à mobiliser les parents d'élèves pour nous acheter du matériel informatique.
N'étant pas informaticien, je me suis autoformé et j'ai réussi à installer un serveur. Je propose des exercices d'automatisation en français, des exercices de compréhension orale, des cours d'anglais... Cela fonctionne à merveille et cela aide à faire progresser les élèves.
Je souhaite faire une transition vers chamilo 1.11.x pour utiliser les roues de compétences. Je n'ai pas de connaissance en php et mon budget et très réduit. 
J'essaye d'être volontaire et d'aller de l'avant et je contribue, à ma manière (en notant les bugs), à votre merveilleux projet.
Je suis désolé ne pas pouvoir en faire plus. 
Sincèrement.

**Comment by ywarnier** [comment]
Pas de problème, c'est le genre de situations dans lesquelles que nous espérons aider avec Chamilo. Nous risquons cependant de prendre un peu de temps pour la correction de ces petits défauts, simplement, faute de budget. Je t'invite cependant à continuer à rapporter ce que tu trouves, ça ne fait de mal à personne. Mais simplement: merci de ne pas en espérer trop de notre part: avec plus de 40.000 installations de Chamilo dans le monde (dont plus de 99,9% gratuites et sans support), notre équipe est un peu surchargée et doit définir des priorités.

**Comment by alexiye** [comment]
Je comprend parfaitement, à chacun sa peine :-)

**Comment by ywarnier** [comment]
Cela étant dit, nous participons avec plaisir à des concours d'innovation qui permettent parfois aux écoles d'obtenir plus de budget pour ce genre de projet. En attendant, simplement parler de Chamilo à d'autres permet de faire passer le message et nous faire participer à plus de projets rémunérés.

**Comment by alexiye** [comment]
J'ai, par le passé, utilisé scenari. Il y a aussi canoprof. Mais ces solutions ne permettent pas de récupérer les résultats des élèves et de noter leur progression. Je suis attaché à Chamilo puisqu'il permet de se rendre compte de l'évolution, de la progression des élèves pour chacune des compétences travaillées. 
Si vous avez des pistes pour ces concours d'innovation, je suis preneur.
En ce moment je suis en train d'étendre mon offre éducative en proposant aux élèves et aux parents un site Chamilo qu'ils peuvent utiliser à la maison. Une sorte de lien entre l'école et la maison.

**Comment by ywarnier** [comment]
Je n'ai pas de piste pour le moment. Dans quelle région travaillez-vous?
J'ai entendu dire que certaines de nos écoles utilisatrices proposent directement un budget aux associations de parents pour l'accès depuis la maison. Il s'agit d'un outil additionnel qui leur fait gagner du temps, et parfois c'est bien vu (tant que ça reste sous pilotage de l'école). Peut être une piste à explorer.

**Comment by alexiye** [comment]
Bienvenue chez les Cthis !
En tout cas, en trois semaines, proposer 80 exercices de conjugaison avec Chamilo, contre 10 exercices dans un manuel, il n'y a pas photo et les résultats sont à la hauteur de mon investissement ( surtout pour les élèves les plus faibles).
Mais il y a encore des réticences à l'utilisation de l'informatique en classe et une méconnaissance de son utilisation. C'est un peu comme la chasse aux sorcières.

**Comment by alexiye** [comment]
![avant](https://user-images.githubusercontent.com/24505996/36407055-ae6c1016-15fb-11e8-9d05-f3d5858e7c30.png)
version chamilo 1.11.x de je sais plus quand. C'est quand même plus lisible non ?

**Comment by alexiye** [comment]
problèmes corrigés sur la version 1.11.x téléchargée le 24/02/2018
Merci beaucoup
