### ISSUE TITLE
Multiple answer true/false/don't know Score Fields reversed

### ISSUE THREAD

**Issue by sercon** [chamilo/chamilo-lms#2392]
### Current behavior / Resultado actual / Résultat actuel
When creating a Multiple answer true/false/don't know question, the fields for score are misinterpreted.
![image](https://user-images.githubusercontent.com/12449415/36381349-8ede2926-1585-11e8-8856-e797db29cbab.png)

### Expected behavior / Resultado esperado / Résultat attendu
I created a test with 10 questions. If i choose the values Correct=1, Wrong=0,5 and Don't Know=0 and then fill in the test making 1 Don't know answer on purpose and all others correct, i get scored 8,5/10 as if the answer was wrong instead of don't know..
I then change the score values to Correct=1, Wrong=0 and Don't Know=0,5, and again answer 9 question correctly and one don't know, i get a score of 9/10. I suppose the fields Wrong and Don't know have their label reversed.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Just create a question and test.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by NicoDucou** [comment]
I just did a test on the test platform 11.chamilo.org and all seems to work correctly.
The example is here : https://11.chamilo.org/main/exercise/admin.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&type=11&myid=1&editQuestion=2439

You can see the result of the user admin here : https://11.chamilo.org/main/exercise/overview.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=850&preview=1

And as you can see the score is correct.

Please provide an example on 11.chamilo.org or close the issue if everything is fine.

Best regards
