### ISSUE TITLE
Test Type "Multiple answer True/False/Don't know" error

### ISSUE THREAD

**Issue by JanKudera** [chamilo/chamilo-lms#2393]
### Current behavior / Resultado actual / Résultat actuel
I select empty answer box, click "delete"...new empty answer appears
### Expected behavior / Resultado esperado / Résultat attendu
It should delete the box, not add new one
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Select default empty box in column answer (or in column comment), than click delete
### Chamilo Version / Versión de Chamilo / Version de Chamilo
online chamillo.org

**Comment by jmontoyaa** [comment]
It works well for me, can you try here:

login/pass: admin/admin

http://11.chamilo.org/

**Comment by JanKudera** [comment]
Hello, unfortunately I am quite lost here...can I add new question?
Here is screenshot from my test...

There are 4 boxes by default, I am not able delete empty rows 

[https://ctrlv.cz/m72f](url)

Here is link to test:
[https://campus.chamilo.org/main/exercice/admin.php?cidReq=NCSTEST&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=83870](url)

login: jan.kudera
password: X2naQkfK

**Comment by ywarnier** [comment]
@JanKudera we really cannot understand what you are trying to do here. Maybe expressing yourself in your mother tongue (and us translating from there) would help?

**Comment by jmontoyaa** [comment]
Closing for lack of feedback.
