### ISSUE TITLE
Still phpmailer 5.1 in actual package 1.11.6

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2402]
@jmontoyaa & @ywarnier :
How can this happen?
Version 5.2 latest is compatible and can be used as a drop-in replacement :-(

And yes, i know there is #1732 where you have written that the shipped version is a patched one...
Wouldn't it be better to change to the official one?
And to be honest: PHPMailerAutoload.php is the way to go ;-)

**Comment by ywarnier** [comment]
Well, don't hesitate to send us a Pull Request with that and we will review it and integrate it if it's OK.
In the meantime, it's safe and working, so I don't see why all the fuss.

**Comment by lonesomewalker** [comment]
Touche, instead of wasting time i should have made a commit :-(

Well, there are situations, where Chamilo can't be run smoothly, because the hosting provider scans actively for vulnerable versions of known libraries...

Will send a Pull Request in a few days for the old version. As i've seen, the new Chamilo uses a new library :-)

**Comment by ywarnier** [comment]
OK, feel free to add new comments here. In the meantime, I consider this fixed. Community support is for the latest stable version only.
