### ISSUE TITLE
Extrafields no filtrado en el catalogo de cursos.

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2412]
### Current behavior / Resultado actual / Résultat actuel
El extrafield del video para el catalogo de cursos aparece dentro del extrafields del usuario tutor, cuando este solo debe aprecer en el curso 
![extrafields](https://user-images.githubusercontent.com/2940509/37131583-00898f38-2257-11e8-818c-5a50e94af0db.png)

### Expected behavior / Resultado esperado / Résultat attendu
Mal filtrado de extrafields
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Colocar un video a una sesion para el catalogo de curso
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by AngelFQC** [comment]
@aragonc Especificar pasos para reproducirlo o probarlo directamente en 11.chamilo.org

**Comment by aragonc** [comment]
@AngelFQC  Ni yo mismo puedo replicarlo ahora, capaz es un error con una versión anterior de 1.11.x que ya se arreglo pero de todas maneras voy a probarlo con una instalación limpia.

**Comment by aragonc** [comment]
@AngelFQC  el error sale cuando se agrega y se quita dos coach a la sesión.

![error](https://user-images.githubusercontent.com/2940509/38428309-1acec110-3981-11e8-9c01-3dca99b1f949.png)

**Comment by ywarnier** [comment]
@aragonc apruebas el cambio?

**Comment by ywarnier** [comment]
Lo apruebo yo porque @aragonc es un hombre muy ocupado.
