### ISSUE TITLE
Memory Limit Shows -1 Not the Actual Set Memory Limit

### ISSUE THREAD

**Issue by july8six** [chamilo/chamilo-lms#2416]
### Current behavior / Resultado actual / Résultat actuel
During the installation check, the memory limit shows -1.
### Expected behavior / Resultado esperado / Résultat attendu
The actual memory limit from the php.ini should be shown.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6 stable PHP 7.1

**Comment by ywarnier** [comment]
@jmontoyaa could you keep the memory_limit value (with ini_get) *before* we do the ini_set, and show that one in this particular table of data?

**Comment by jmontoyaa** [comment]
This is a duplicate of #2230
