### ISSUE TITLE
Bug d’affichage du lien "Page d'accueil" en mode déconnecté

### ISSUE THREAD

**Issue by lzebdi** [chamilo/chamilo-lms#2420]
**Comportement actuel / Résultat actuel / Résultat actuel**

Défaut d'affichage du lien "Page d'accueil" en mode déconnecté après avoir inséré un lien lors de la configuration de la page d'accueil.

**Comportement attendu / Résultat esperado / Résultat attendu**

Affichage correcte du lien "Page d'accueil" en mode déconnecté.

**Étapes à suivre pour reproduire / Pasos para reproducir / Étapes pour reproduire**

- Administration
- Configurer la page d'accueil
- Insérer un lien
- Ne pas cocher la case «Ajouter au menu»
- Enregistrer
- Quitter

Le défaut d'affichage disparaît si ce même lien créé est ajouté au menu ou supprimé.

**Version Chamilo / Version de Chamilo / Version de Chamilo**

1.11.x 
Test https://11.chamilo.org

**Comment by NicoDucou** [comment]
Un peu de précision pour la compréhension du bug.

Si on va sur la page d'accueil de chamilo sans être identifié ici : https://11.chamilo.org/index.php
Le menu n'apparaît pas correctement. Le mot homepage n'apparait pas.
 
Si on se connecte comme admin et que l'on va sur la page :
https://11.chamilo.org/main/admin/configure_homepage.php?action=edit_tabs&link_index=0
On coche la case "Ajouter au menu" et on enregistre pour toutes les langues.

On se déconnecte et on retourne sur la page d'accueil. Le menu est cette-fois bien présent avec homepage et également le lien vers la page que nous avons créé.

**Comment by ywarnier** [comment]
This is somehow due to this:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/banner.lib.php#L521

Fix under way...

**Comment by ywarnier** [comment]
Could someone check the fix and approve please?

**Comment by lzebdi** [comment]
Vérification faite, le correctif est concluant. 
Merci ywarnier

**Comment by ywarnier** [comment]
Merci pour la révision!
