### ISSUE TITLE
Groups: adding too many in a group generates unclear error message

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#2460]
### Current behavior / Resultado actual / Résultat actuel
Wrong error message (in English/Spanish/German and French) saying you canbchange the max nr of users "below" while there is nothing below.

### Expected behavior / Resultado esperado / Résultat attendu
Either make it so or change the text in all languages.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
When you try to add too many users to a group, it says "you can change that below" but there is nothing below.  Go to groups, create a group and try adding many (more than 8 default) users.
![image](https://user-images.githubusercontent.com/1659604/37700555-4b8da786-2cec-11e8-860d-54afda967f27.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x on 11.chamilo.org

**Comment by nosolored** [comment]
Efectivamente sale ese mensaje. 
La variable de idioma es `$GroupTooMuchMembers`
Lo ideal sería cambiar el mensaje que aparece entre paréntesis e indicar que desde la pestaña parámetros puede cambiarse el límite de miembros del grupo.

**Comment by ywarnier** [comment]
Changed to:
en: Number proposed exceeds max. that you allowed (you can modify in the group settings). Group composition has not been modified
fr: Le nombre de membres proposé excède le nombre maximum que vous avez fixé. La composition du groupe n'a pas été modifiée. Vous pouvez modifier le nombre maximum dans la configuration du groupe.
nl: Het aantal deelnemers overschrijdt het maximumaantal dat u bepaald had. De samenstelling van de groep werd niet gewijzigd. U kan het maximum aantal in de groepsinstellingen wijzigen.
es: El número propuesto excede el máximo que Ud. autoriza (puede modificarlo en los parámetros del grupo). La composición del grupo no se ha modificado

**Comment by ywarnier** [comment]
I'm closing the issue myself because it has a very low complexity :-)
