### ISSUE TITLE
SEPE plugin foreign key constraint fails

### ISSUE THREAD

**Issue by antton** [chamilo/chamilo-lms#2461]
### Current behavior / Resultado actual / Résultat actuel
Recibo un error de base de datos "foreign key constraint fails" al no introducir ningun dato en la parte de Participante de la acción formativa en la seccion de CONTRATO DE FORMACIÓN: 

No creo que todos los certificados de profesionalidad tengan por detras esta obligación.
### Expected behavior / Resultado esperado / Résultat attendu
Deberia de dejar no introducir nada en ciertos campos

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1.- Crear una accion formativa.
2.- Crear participantes
3.- Al no rellenar la parte de CONTRATO DE FORMACIÓN:  recibiremos el error mencionado.

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Version del producto 1.11.6

**Comment by nosolored** [comment]
PR: https://github.com/chamilo/chamilo-lms/pull/2479
Si tienes datos en las tablas del plugin y no puedes reinstalar el plugin del SEPE deberás modificar manualmente la estructura de la tabla **plugin_sepe_participants** asignando el atributo Nulo (null) a las columnas **company_tutor_id** y **training_tutor_id**

**Comment by ywarnier** [comment]
@nosolored esta información debe estar en el README.md (o alternativamente en un archivo CHANGELOG.md) del plugin. Ver el de BBB como ejemplo.

**Comment by nosolored** [comment]
PR: https://github.com/chamilo/chamilo-lms/pull/2481 He creado el fichero CHANGELOG.md

**Comment by nosolored** [comment]
@ywarnier , esta tarea podría ser cerrada
