### ISSUE TITLE
Problema en lecciones al actualizar a 1.11.6

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2462]
### Current behavior / Resultado actual / Résultat actuel
En una plataforma Chamilo 1.11.4 que proviene de versiones anteriores actualizadas progresivamente desde la 1.9.x, tras actualizar a la 1.11.6, las lecciones dejan de funcionar, no cargan los contenidos y no se visualizan los ítems (sco) de la lección.

Está relacionado con la incidencia #2381   

Hemos probado el script que se indica en esa tarea, pero solo corrige algunos de los problemas.
Parece que solo se modifica correctamente el lp_id en algunos items, pero en otros no
Creemos que esto ocurre porque el script, conforme va actualizando nuevos ítems vuelve a sobreescribir algunos que ya estaban actualizados.
Intento explicarlo con un ejemplo:
Una lección tiene estos datos en la tabla c_lp:
c_id: 60
id: 2
iid: 14

Entonces el script va buscando los registros de la tabla c_lp_item en los que c_id=60 y lp_id=2 para sustituir el 2 por el 14, pero esa búsqueda también afectaría a un registro en el que ya se hubiera actualizado el lp_id para la lección con iid=2, sobreescribiendo ese cambio

### Expected behavior / Resultado esperado / Résultat attendu
Lo ideal sería que el proceso de actualización hiciese estas comprobaciones y reparase los problemas.
Si aún no es posible incluir este script en la actualización, al menos mejorarlo para que repare los ítems correctamente.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
No podemos reproducirlo en una demo, se requiere una plataforma que venga de versiones antiguas y que contenga lecciones creadas en esas versiones, para que el id sea diferente del iid

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

Podemos ayudar haciendo las pruebas que se necesiten.

**Comment by jmontoyaa** [comment]
En esta condición si los valores c_lp.iid y c_lp.id son iguales entonces no lo toma en cuenta:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/tests/scripts/fix_lp_id_to_iid.php#L42

**Comment by jmontoyaa** [comment]
He agregado una condición más:

https://github.com/chamilo/chamilo-lms/commit/cb84d1d6b3066a1314e9d289af8c6f043f6583fb

**Comment by nosolored** [comment]
Hemos probado el script con los cambios y arregla algunas lecciones, pero otras siguen sin verse.

**Comment by jmontoyaa** [comment]
Necesitaría un backup de esa base de datos para hacer pruebas de mi lado.

**Comment by nosolored** [comment]
Ok, te la pasaremos en la tarea ref BT#14174
Es una de las plataformas en la que nos pasa, aunque nos ocurre en varias.

**Comment by nosolored** [comment]
@jmontoyaa Puede cerrarse. Hemos realizado varias pruebas con las correcciones (migraciones, sobreescribir con código github, etc.) y se han realizado de forma correcta.

**Comment by nosolored** [comment]
@jmontoya, este script se ha integrado ya en la actualización a la 1.11.8 o hay que ejecutarlo manualmente?

**Comment by ywarnier** [comment]
Se integró en la 1.11.8 pero de lo que yo sepa sigue siendo necesario ejecutarlo a mano luego de una actualización de 1.11.* a 1.11.8, no?

**Comment by nosolored** [comment]
Salvo error por nuestra parte. Tras actualizar a 1.11.8 sigue siendo necesario actualizar a mano ejecutando el script desde tests/scripts/fix_lp_id_to_iid.php

Quizás sería bueno añadirlo en un fichero en app/Migrations/Schema/V111/
para cuando finalice la migración si detecta un cambio de id a iid en los scorm lo aplique.

**Comment by juliocampomanes** [comment]
Hola a todos, en la versión 1.11.10. tengo problemas solo cuando estoy haciendo el banco de preguntas en el ejercicio. sale errores, alguien sabe si esto se corrigió?, Gracias

**Comment by NicoDucou** [comment]
Hola @juliocampomanes 
Por favor no escribir en una tarea que no tiene nada que ver. Crear una nueva issue y respectar el template de reporte para facilitar el tratamiento.
Por lo del banco de preguntas no tenemos reportes de error, todo parece funcionar bien en 1.11.x
