### ISSUE TITLE
Invasion

### ISSUE THREAD

**Issue by f4rr3ll10** [chamilo/chamilo-lms#2465]
### Current behavior / Resultado actual / Résultat actuel

Attempted to invade and thereby overthrown MySQL

181.222.166.9 - - [22/Mar/2018:16:03:36 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:37 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:37 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:37 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:37 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:37 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:38 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:38 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:38 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:38 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:39 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:39 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:39 -0300] "POST /index.php HTTP/1.1" 302 0 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"
181.222.166.9 - - [22/Mar/2018:16:03:39 -0300] "GET /index.php?loginFailed=1&error=user_password_incorrect HTTP/1.1" 200 30401 "-" "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.1; WebCruiser/3.5)"

### Expected behavior / Resultado esperado / Résultat attendu

Has anyone experienced this and knows how to solve it?

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Chamilo 1.10.6

**Comment by nosolored** [comment]
You can block the attack from the firewall (you need access as root) or if you use Apache as a Web server from the .htaccess file. WebCruiser is a vulnerability scanner.

Firewall
---------
iptables -I INPUT 1 -s 181.222.166.9 -j DROP;

Apache
---------
You must insert the following content in .htaccess file:

deny from 181.222.166.9 
# BLOCK USER AGENTS
RewriteEngine on
RewriteCond %{HTTP_USER_AGENT} WebCruiser [NC]
RewriteRule !^robots\.txt$ - [F]
# BLOCK BLANK USER AGENTS
RewriteCond %{HTTP_USER_AGENT} ^-?$
RewriteRule ^ - [F]

info: http://incredibill.me/htaccess-block-user-agent

**Comment by jmontoyaa** [comment]
You can try using the captcha login option.

As admin find the configuration here:
main/admin/settings.php?search_field=captcha&category=search_setting

But this is not an error or bug of Chamilo.
