### ISSUE TITLE
Hotpotatoes exercice: unable to delete attempt

### ISSUE THREAD

**Issue by p4pr8n** [chamilo/chamilo-lms#2466]
version 1.11.4  

Clicking on the big red cross seems to delete attempt but not in real.

In file main/inc/lib/exercise.lib.php line 1590

` $url = $urlBase.$data[id].'&path='.$data['exe_name'];`

**$data[id]** gives as result the row  **exe_user_id** from table **track_e_hotpotatoes** and not the **id** row of the attempt.

My quick and dirty hack to allow deletion was to replace **[id]** with **[0]**.

` $url = $urlBase.$data[0].'&path='.$data['exe_name'];`

**Comment by AngelFQC** [comment]
I sent a commit to fix this. Please test it @p4pr8n

**Comment by ywarnier** [comment]
Given the fact that we want to release on friday, a quick check from you would be highly appreciated @p4pr8n (otherwise I will forcibly check and close the issue myself before that)

**Comment by p4pr8n** [comment]
A quick check on our 1.11.4 version where this bug was discovered seems to give a good result.
You know what ? I'm happy. :-)

Thanks a lot.
