### ISSUE TITLE
Course Importation does not import Scorm included in the course Backup

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2470]
### Current behavior / Resultado actual / Résultat actuel
I created a course on Chamilo, including a Scorm Learning Path, I exported this course :
[COURSDEDEMO.zip](https://github.com/chamilo/chamilo-lms/files/1855413/COURSDEDEMO.zip)

When importing this course on another Chamilo Plateform the scorm is not imported.

I did an example here https://11.chamilo.org/main/lp/lp_controller.php?cidReq=TESTIMPORTDECOURSINCLUANTUNPARCOUR&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=248&isStudentView=true

I've imported the course with the backup indicated above but the scorm is not included.

We can see in the course directory on the server that there is nothing in the scorm subfolder.

### Expected behavior / Resultado esperado / Résultat attendu
The scorm included in the Course backup should be imported.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a new course and import the course backup above.
The second learning path which was a scorm is not imported.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by jmontoyaa** [comment]
After some tests it's working for me:

https://11.chamilo.org/main/lp/lp_controller.php?cidReq=JULIOTEST&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=249&isStudentView=true

**Comment by jmontoyaa** [comment]
According to this issue:

**Comment by xam1234** [comment]
Can't import course backup from 1.10.6 to 1.11.6.

**Comment by NicoDucou** [comment]
@xam1234 please create a new issue for your request, because not to get mixed up with the original issue here. And do not forget to give the file that you are trying to import or the link to the plateform with the original course to be able to generate an export.

**Comment by NicoDucou** [comment]
@Julio I've seen the issue you mentioned:
https://support.chamilo.org/issues/7029

But it was just left like this not to block 1.9.8 to be released and postponed to the next version.
From what you said the problem would be that we would need to validate the scorm before importing. 
But since it's a Chamilo course Backup, it comes from a Chamilo installation where the scorm had already been imported and validated and where it was in use. So just copying the folder should create the same situation. The only problem is if the course comes from an earlier version of Chamilo that was not verifying the scorm as well as the latest versions.

**Comment by ywarnier** [comment]
I'm bumping this to version 2.0. This is not something critical in the sense that it should not affect many users and that SCORM are usually mostly used in the business world (so not on our priority list for "Improving the availability of quality education world wide").

**Comment by NicoDucou** [comment]
It has been done for task https://task.beeznest.com/issues/14324 and tested there so it is now available and must be enabled with this option : 
`$_configuration['allow_import_scorm_package_in_course_builder'] = true;`

So the issue can be closed from my point of view.

**Comment by ywarnier** [comment]
Review that it is included in 2.0

**Comment by ywarnier** [comment]
The course backup functions still have to be modified in Master to match the new structure of item properties -> resources

**Comment by ywarnier** [comment]
I'm closing this issue. While it's true that we still have to test it on Chamilo 2, it will be part of the normal process now.
