### ISSUE TITLE
API REST fails when saving course

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2471]
### Current behavior / Resultado actual / Résultat actuel
Get warning and e_notices when adding a course with REST api.
Currently in `Rest::addCourse` there are undefined variables that generate warnings. And unused variables also. For example:
```
Notice: Undefined index: original_course_id_name in /var/www/chamilo111x/main/inc/lib/webservices/Rest.php on line 1065
```

### Expected behavior / Resultado esperado / Résultat attendu
Save a course by using REST api

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Try register a course with REST v2.php

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by AngelFQC** [comment]
ping @wariosolis

**Comment by ywarnier** [comment]
Looks good (but untested by me). Closing because no feedback from original developer.
