### ISSUE TITLE
Error with CKEditor

### ISSUE THREAD

**Issue by fretelweb** [chamilo/chamilo-lms#2482]
### Current behavior / Resultado actual / Résultat actuel
Cant browse server files in CKEditor

### Expected behavior / Resultado esperado / Résultat attendu
Upload files and navigate it from CKEditor
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
PHP 7.0
mysql  Ver 14.14 Distrib 5.6.35-80.0,
cPanel
### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo v1.11.6
![chamilo_screenshot_5](https://user-images.githubusercontent.com/4341136/38429373-c4822f60-3983-11e8-896d-7a10591908da.png)

**Comment by ywarnier** [comment]
Did you install the Chamilo v1.11.6 specific to PHP7?

**Comment by fretelweb** [comment]
thanks for your answer. 
I install it throught softaculous the cpanel was with php 5.6 but softaculous require me PHP 7 so I change to it and install

**Comment by fretelweb** [comment]
would you like to access chamilo?? in my domain to check it?

**Comment by ywarnier** [comment]
It might be related to #1574. Your safest bet is to contact your hosting provider or even Softaculous about that. This is most likely just a security configuration issue and there's not much we can do about it. This feature seems to work fine in most installations. Unless you get us more info about the web server logs when this issue appears, we cannot help you (even then, I'm not sure we can). Your hosting provider charges you for that, and Softaculous charges your hosting provider, so please consider asking support from the people whom you support (financially) first (then tell us what the conclusion is so we can fix it in Chamilo and make others benefit).
