### ISSUE TITLE
index.php on course folder missing

### ISSUE THREAD

**Issue by ullfindsmit** [chamilo/chamilo-lms#2489]
### Current behavior / Resultado actual / Résultat actuel

Install Chamilo on Windows using the wizard
Create Course
Click on home icon
404
http://training.simplebusinesssuite.com/chamilo/courses/DEMO/index.php?id_session=0

### Expected behavior / Resultado esperado / Résultat attendu
Expect the page to load

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Click link above or go to http://training.simplebusinesssuite.com/chamilo/courses/DEMO/index.php?id_session=0

### Chamilo Version / Versión de Chamilo / Version de Chamilo
 1.11.6

**Comment by ywarnier** [comment]
What do your apache logs say?
The link seems to be good. Any chance you *didn't* check the installation guide, in particular the part about "Require all granted"?

**Comment by ullfindsmit** [comment]
Its windows (hence the challenge)
Everything said A-OK before proceeding... I can try a third time, but wondering if there is a simple way to fix it without a new deployment

**Comment by ywarnier** [comment]
Windows still uses a web server. Do you use IIS?
Maybe there is a way to fix it, but not if you don't provide us with more info from the logs of your web server.

**Comment by ullfindsmit** [comment]
IIS does not use .htaccess
It uses web.config to rewrite path
Not sure if that is the issue or not
But, the problem it seems is that its expecting a index.php file on each course's root folder which it does not have

Where is the app expected to run the index.php from if the rewrite was working?

**Comment by ullfindsmit** [comment]
The logs show 404 for index.php for the course
I am guessing its missing a rewrite rule somewhere

**Comment by ullfindsmit** [comment]
So finally got it figured out

You have to use a web.config to do what htaccess does

Below is the code

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>        	
        <rewrite>
            <rules>
				<rule name="rule 1v" stopProcessing="true">
					<match url="^certificates/$"  />
					<action type="Rewrite" url="/certificates/index.php?id=%1"  />
				</rule>
				<rule name="rule 2v" stopProcessing="true">
					<match url="^courses/([^/]+)/?$"  />
					<action type="Rewrite" url="/main/course_home/course_home.php?cDir={R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 3v" stopProcessing="true">
					<match url="^courses/([^/]+)/index.php$"  />
					<action type="Rewrite" url="/main/course_home/course_home.php?cDir={R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 4v" stopProcessing="true">
					<match url="^courses/([^/]+)/scorm/(.*)$"  />
					<action type="Rewrite" url="/main/document/download_scorm.php?doc_url=/{R:2}&amp;cDir={R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 5v" stopProcessing="true">
					<match url="^courses/([^/]+)/document/certificates/(.*)$"  />
					<action type="Rewrite" url="/app/courses/{R:1}/document/certificates/{R:2}"  appendQueryString="true" />
				</rule>
				<rule name="rule 6v" stopProcessing="true">
					<match url="^courses/([^/]+)/document/(.*)$"  />
					<action type="Rewrite" url="/main/document/download.php?doc_url=/{R:2}&amp;cDir={R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 7v" stopProcessing="true">
					<match url="^courses/([^/]+)/upload/([^/]+)/(.*)$"  />
					<action type="Rewrite" url="/main/document/download_uploaded_files.php?code={R:1}&amp;type={R:2}&amp;file={R:3}"  appendQueryString="true" />
				</rule>
				<rule name="rule 8v" stopProcessing="true">
					<match url="^courses/([^/]+)/work/(.*)$"  />
					<action type="Rewrite" url="/main/work/download.php?file=work/{R:2}&amp;cDir={R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 9v" stopProcessing="true">
					<match url="^courses/([^/]+)/course-pic85x85.png$"  />
					<action type="Rewrite" url="/main/inc/ajax/course.ajax.php?a=get_course_image&amp;code={R:1}&amp;image=course_image_source"  appendQueryString="true" />
				</rule>
				<rule name="rule 10v" stopProcessing="true">
					<match url="^courses/([^/]+)/course-pic.png$"  />
					<action type="Rewrite" url="/main/inc/ajax/course.ajax.php?a=get_course_image&amp;code={R:1}&amp;image=course_image_large_source"  appendQueryString="true" />
				</rule>
				<rule name="rule 11v" stopProcessing="true">
					<match url="^courses/([^/]+)/(.*)$"  />
					<action type="Rewrite" url="/app/courses/{R:1}/{R:2}"  appendQueryString="true" />
				</rule>
				<rule name="rule 12v" stopProcessing="true">
					<match url="^session/(\d{1,})/about/?$"  />
					<action type="Rewrite" url="/main/session/about.php?session_id={R:1}"  />
				</rule>
				<rule name="rule 13v" stopProcessing="true">
					<match url="^badge/(\d{1,})"  />
					<action type="Rewrite" url="/main/badge/issued.php?issue={R:1}"  />
				</rule>
				<rule name="rule 14v" stopProcessing="true">
					<match url="^skill/(\d{1,})/user/(\d{1,})"  />
					<action type="Rewrite" url="/main/badge/issued_all.php?skill={R:1}&amp;user={R:2}"  />
				</rule>
				<rule name="rule 15v" stopProcessing="true">
					<match url="^badge/(\d{1,})/user/(\d{1,})"  />
					<action type="Rewrite" url="/main/badge/issued_all.php?skill={R:1}&amp;user={R:2}"  />
				</rule>
				<rule name="rule 16v" stopProcessing="true">
					<match url="^main/exercice/(.*)$"  />
					<action type="Rewrite" url="/main/exercise/{R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 17v" stopProcessing="true">
					<match url="^main/newscorm/(.*)$"  />
					<action type="Rewrite" url="/main/lp/{R:1}"  appendQueryString="true" />
				</rule>
				<rule name="rule 18v" stopProcessing="true">
					<match url="^service/(\d{1,})$"  />
					<action type="Rewrite" url="/plugin/buycourses/src/service_information.php?service_id={R:1}"  />
				</rule>
				<rule name="rule 19v" stopProcessing="true">
					<match url="^([^/.]+)/?$"  />
					<action type="Rewrite" url="/user.php?{R:1}"  />
				</rule>
				<rule name="rule 20v" stopProcessing="true">
					<match url="^(tests|.git)"  ignoreCase="true" />
					<action type="Rewrite" url="/-"  />
				</rule>

            </rules>
        </rewrite>

    </system.webServer>
</configuration>

**Comment by ywarnier** [comment]
That's great @ullfindsmit, nobody submitted the rules for IIS before.
Can you help me with where the web.config file has to be added? Does it go into the root folder of Chamilo or into a folder specific to the IIS configuration folder?
This is to add this documentation to the Chamilo installation guide.

**Comment by ullfindsmit** [comment]
Add it to the root chamilo directory.
In my case it was under the chamilo-1.11.6 folder
