### ISSUE TITLE
No title in LPs

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2492]
### Current behavior / Resultado actual / Résultat actuel
LP title dissapear
### Expected behavior / Resultado esperado / Résultat attendu
LP title must appear 
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
behat test fail 
Scenario: Enter LP                                                   # features/toolLp.feature:44
    Given I am on "/main/lp/lp_controller.php?cidReq=TEMP&action=list" # FeatureContext::visit()
    And I follow "LP 1"                                                # FeatureContext::clickLink()
    And wait for the page to be loaded                                 # FeatureContext::waitForThePageToBeLoaded()
    Then I should see "LP 1"                                           # FeatureContext::assertPageContainsText()
      The text "LP 1" was not found anywhere in the text of the current page.
      
      +--[ http://localhost/main/lp/lp_controller.php?cidReq=TEMP&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=1&isStudentView=true | Selenium2Driver ]
      |

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by aragonc** [comment]
Envié un commit colocando el titulo, adicionalmente mejore la nueva vista de acordeón de la lista lp
![lp_view](https://user-images.githubusercontent.com/2940509/38834276-97a252ec-418d-11e8-9920-26170d1ac557.png)
