### ISSUE TITLE
count() warnings in learnpath.class.php

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2494]
I've installed on ubuntu 16 chamilo 1.11.6 php 7.2.4
When logged in to chamilo in dev mode it shows some errors in the main page.

I had to go back to php 7.0 so I don't have a printscreen to show.

**Comment by jmontoyaa** [comment]
Installation should work in php 7.2

You need to run "composer update" to update the "vendors" folder.

**Comment by xam1234** [comment]
no change. 

![aaa](https://user-images.githubusercontent.com/32258255/38922073-9b2f4670-42f7-11e8-8657-b585d378bafc.png)

**Comment by xam1234** [comment]
I know that production mode will hide those warnings, but I don't know if it will not couse some problems:/

**Comment by ywarnier** [comment]
We hope to release 1.11.8 during the month of June

**Comment by ywarnier** [comment]
Please be more specific in your issue titles, so we can find them faster, later on

**Comment by ywarnier** [comment]
It's nice of you to report these, but don't let them confuse you: deprecate type messages are only there for debug. That's just for PHP to alert developers that they should slowly change the code, but that won't be an issue in production environment.

**Comment by xam1234** [comment]
ok, couse it's already fixed i'm closing it.
