### ISSUE TITLE
Exercise error on configure

### ISSUE THREAD

**Issue by paulmtztorres** [chamilo/chamilo-lms#2506]

**Comment by paulmtztorres** [comment]
I have problems with the configuración of exercises, i can't reuse other exams of older courses. Do you know why is the problem?

**Comment by ywarnier** [comment]
Please respect our format to report your error. This report is far too short and too imprecise to be able to help you.

**Comment by paulmtztorres** [comment]
Hello, ghanés for your atetion.
I been working on chamilo campus plataform since 2012 and lately i been
suffer problems in there. In this week i used the exercise tool for make
exams but i can't configure properties how time, valué, random cuestions,
number of cuestions and other things. Can you check whatsapp happened with
the site please?
Ólso if i wang reuse exams i can't do it because apear a Message that says,
don't have  permissions to continúe, back to initial page.
I whait you can repair this problem because use a lot the site to Work with
my students and need aply grades ti them in this days.
Thanks again

**Comment by ywarnier** [comment]
@paulmtztorres Your name suggests your mother tongue is Spanish. You can express yourself in Spanish here if you want. Your report does not give the minimum precision we expect, so if you can give us more details in Spanish, *please do*.

**Comment by paulmtztorres** [comment]
An apology, the corrector of words is in Spanish and makes me a mess.
The problem that there is with chamilo is that it does not allow me to do
the configuration of the parameters of the exercises to apply exam like,
date, time, duration time, qualification and other parameters.
I have been using the platform for a long time since 2012 and I had not had
such serious problems with it.
I have to apply exams on these dates and the problem with the platform
prevents me from continuing with the evaluation of the students that I have
registered.
I hope it can be resolved to continue and apply qualifications to my groups.
I am currently working with 3 in different courses.
Thank you very much.

Una disculpa, el corrector de palabras esta en español y me hace un lio.
El problema que hay con chamilo es que no me permite hacer la configuracion
de los parametros de los ejercicios para aplicar examen como, fecha, hora,
tiempo de duracion, calificacion y otros parametros.
Empleo la plataforma desde hace mucho 2012 y no habia tenido problemas con
ella tan graves.
Tengo que aplicar examenes en estas fechas y el problema con la plataforma
me impide continuar con la evaluacion de los alumnos que tengo registrados.
Espero que se pueda resolver para continuar y aplicar calificaciones a mis
grupos.
Actualmente estoy trabajando con 3 en diferentes cursos.
Muchas gracias




2018-04-25 12:25 GMT-05:00 Yannick Warnier <notifications@github.com>:

**Comment by ywarnier** [comment]
@paulmtztorres primero por favor respeta nuestra plantilla de reporte de problemas. Está ahí (incluso en español) para que puedas estructurar el problema y darnos la información necesaria, y te pasaste todo por alto lo que nos hace difícil ayudarte, porque no sabemos de qué Chamilo estás hablando (versión) ni de qué pasó en la historia de tu portal para que estés teniendo estos problemas. Actualizaste a alguna versión nueva últimamente?

**Comment by paulmtztorres** [comment]
[Reporte de errores chamilo.docx](https://github.com/chamilo/chamilo-lms/files/1948629/Reporte.de.errores.chamilo.docx)
Ready, I send you a document with the problem. Thanks

**Comment by ywarnier** [comment]
Hola @paulmtztorres, he revisado tu documento. El campus de Chamilo es un servicio gratuito ofrecido con objetivo de ayudar, pero no tenemos en este momento los recursos para ofrecer soporte a todos nuestros usuarios (que son 600K en este portal). Si este exámen es crítico, deberían realmente usar su propio portal de Chamilo y contar con un equipo de soporte (quizás con los proveedores oficiales de Chamilo). Lo siento.

**Comment by paulmtztorres** [comment]
Hola. Atendiendo a tu respuesta y agradeciendo que aun se encuentren interesados en resolver el problema. Te indico que reduje el nuemero de preguntas, elimine cursos creados anteriormente y que ya no usaba y he tratado de editar tanto el examen que tenia pendiente como a otros de los que tenia ya en los cursos anteriores pero no me da acceso a la opcion de configuracion de parametros avanzados.

Saludos y gracias nuevamente

________________________________
De: Yannick Warnier <notifications@github.com>
Enviado: miércoles, 6 de junio de 2018 10:26 p. m.
Para: chamilo/chamilo-lms
CC: paulmtztorres; Mention
Asunto: Re: [chamilo/chamilo-lms] Exercise error on configure (#2506)


Hola @paulmtztorres<https://github.com/paulmtztorres>, he revisado tu documento. El campus de Chamilo es un servicio gratuito ofrecido con objetivo de ayudar, pero no tenemos en este momento los recursos para ofrecer soporte a todos nuestros usuarios (que son 600K en este portal). Si este exámen es crítico, deberían realmente usar su propio portal de Chamilo y contar con un equipo de soporte (quizás con los proveedores oficiales de Chamilo). Lo siento.
