### ISSUE TITLE
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Question::save(), 0 passed in chamilo\main\exercise\upload_exercise.php 

### ISSUE THREAD

**Issue by smellwing** [chamilo/chamilo-lms#2508]
### Current behavior
Si se importa el archivo en Excel XLS de ejemplo en los ejercicios, y cualquier XLS que respete el formato, el sistema arroja un error fatal.

> 
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Question::save(), 0 passed in C:\xampp\htdocs\chamilo\main\exercise\upload_exercise.php on line 471 and exactly 1 expected in C:\xampp\htdocs\chamilo\main\exercise\question.class.php:923 Stack trace: #0 C:\xampp\htdocs\chamilo\main\exercise\upload_exercise.php(471): Question->save() #1 C:\xampp\htdocs\chamilo\main\exercise\upload_exercise.php(33): lp_upload_quiz_action_handling() #2 {main} thrown in C:\xampp\htdocs\chamilo\main\exercise\question.class.php on line 923

El sistema importa tan solo la primera pregunta del ejercicio antes de dar error.
![2018-04-25 2](https://user-images.githubusercontent.com/7376472/39274905-dc13b474-48b9-11e8-950a-aff513ed2fb2.png)

### Expected behavior 

Después de enviar el archivo, Chamilo importa todas las preguntas con la configuración deseada. Luego redirige a la pantalla de configuración del ejercicio con el resultado de la operación.
![2018-04-25](https://user-images.githubusercontent.com/7376472/39274868-bbaab7f0-48b9-11e8-9778-00eac97deb51.png)

.

### Steps to reproduce 

En cualquier Curso / Ejercicios / Importar ejercicio via Excel subir el excel de ejemplo.

### Chamilo Version

Chamilo 1.11.6 

### Nota:

Al parecer este error tiene relación con otros similares en la importación.

**Comment by smellwing** [comment]
La causa es que el método Save($exercise) de la clase Question en main/exercise/question.class.php espera un argumento y no se le da. En el Script chamilo\main\exercise\upload_exercise.php no se declara en ningún momento el objeto $exercise, por lo que no es un error.

Entonces en el comentario del objeto Save($exercise) dice:

>  * if an exercise ID is provided, we add that exercise ID into the exercise list

**Comment by smellwing** [comment]
El problema se corrige modificando el método Save($exercise) de la clase Question en main/exercise/question.class.php de modo que se declare un valor nulo si no se le envía un argumento.

public function save($exercise=null)

Y cuidando que el método no se rompa al envía null.

**Comment by ywarnier** [comment]
En efecto, esto proviene de un cambio mandado hacen 11 meses por @jmontoyaa. Julio, algún argumento en tu defensa? :grin: 
https://github.com/chamilo/chamilo-lms/commit/41c164230f46b59cdceb524dac1aba45e42ce354#diff-837ad3f301bfd915c92f3945c44c0d8bR917
Al eliminar el valor por defecto, es necesario validar que *ninguna* llamada (estática o dinámica) a este método se hace sin argumentos. Hay otros cambios así en el mismo commit que me preocupan ahora...

**Comment by jmontoyaa** [comment]
Acabo de corregirlo. He agregado también un test de behat, que he implementado y agregado ... que pena que nadie me ayude :grin:

**Comment by ywarnier** [comment]
No es que no querramos eh... es que hay demasiado cosas que hacer para Chamilo.
So much to do, so little time... :grinning:

**Comment by smellwing** [comment]
oye y así por decir, quien tiene que validar esto pa cerrarlo??

**Comment by ywarnier** [comment]
Tu :smile: 
La persona que reporta el problema u otra persona que se siente particularmente habilitada para considerar que se fue el error. El desarrollador quién lo corrigió no puede el mismo determinar de manera omnipotente que lo corrigió, a menos que también haya sido el quién lo abrió. Si me sigues?

**Comment by ywarnier** [comment]
Bueno, pues como no lo haces, lo hago yo.
Acabo de probar con el Excel de ejemplo y todo va bien.
Gracias por el reporte preciso @smellwing!
