### ISSUE TITLE
Invisible LP step

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2509]
### Current behavior / Resultado actual / Résultat actuel
Some left menu items are not visible.

![screenshot from 2018-04-27 09-53-27](https://user-images.githubusercontent.com/158935/39351144-e0ce5364-4a00-11e8-9487-6ca4a6e78759.png)

This was discussed here:
https://github.com/chamilo/chamilo-lms/commit/8b3d27dc41a26fbdfa094a504cf31b1eb6ae8db2

This should be tested in many cases
When a LP has different kind of items (exercise, forum,) inside a chapter, etc.
It was working very well before.

### Expected behavior / Resultado esperado / Résultat attendu
All left menu items should be visible.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a lp with one HTML step.
Enter the LP.
The item is invisible.
The error appear when you enter for **the first time** to the LP.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by AngelFQC** [comment]
I reproduce it the first time I entered the lesson. Then I went out and went back in and it was right.

**Comment by aragonc** [comment]
Logre replicar lo que menciono angel que se visualiza en blanco a la primera vez, luego cambie a diferentes tipos de lecciones y se ve normal con el commit que mande.

Por favor verificar si esta todo correcto en un portal de producción

![Uploading list02.png…]()
![list01](https://user-images.githubusercontent.com/2940509/39387713-bb25f384-4a40-11e8-8aa1-5fb72a1c2303.png)

**Comment by aragonc** [comment]
![list02](https://user-images.githubusercontent.com/2940509/39387748-0d5e15f0-4a41-11e8-9173-a0388b29be0e.png)

**Comment by jmontoyaa** [comment]
Funciona.
