### ISSUE TITLE
Documentation: Updating views

### ISSUE THREAD

**Issue by MonteiroJ** [chamilo/chamilo-lms#2510]
Bonjour,
Je suis actuellement un newbie sur chamilo. De plus, je ne suis pas au point sur php, ni-même les framwork existant. 

Vous proposez un outil merveilleux. Mais, par manque de connaissances sur le projet, en php ainsi que ses framwork, je viens vers où en espérant que vous puissiez m'éclairer ^^.

Pour le moment, j'ai réussi à modifier le header et le footer du mail.

Pour la suite, j'aurais besoin de modifier le template de la page d'accueil/connexion. Mais aussi; changer le pack d'icone ainsi que d'espacer les icônes de modification de contenu.
![capture](https://user-images.githubusercontent.com/33484244/39363864-1aa7a768-4a2c-11e8-83a8-18e532fc3c40.PNG)

J'ai tenté de mettre le nez dans chamilo/index.php. Histoire de voir les contrôles qu'il faisait et ce qu'il appelait. Hélas, je n'ai que très peu de connaissances en PHP. Bien entendu, je n'ai pas réussi à trouver.

Je pense avoir trouvé le pack d'icone qui se situe :  /main/img/icons/[16,22,32,48,64,128,svg]. 
J'ai beau remplacer les images par d’autres (en gardant le même nom/extensions), puis de vider le cache de Chamilo via l'interface. Mais aucun changement n'apparaît.

Je n'ai pas encore investigué quant à l'espacement des icônes de modification.

Si vous avez des liens me permettant de comprendre le cheminement du site, je suis preneur ^^.

Il m'est possible de faire un tuto pour chacune de ces 3 "parties". 
Où devrait-je les poster ? A qui devrais-je les donner ?

En résumer, je voudrais : 
     - Modifier le css de la page d'accueil/connexion
     - Changer le pack d'icones
     - Ajuster l'espacement entre les icônes

Merci d'avance :) !!

Debian 9 Stretch
Chamilo 1.11.6
Apache 2.4.25
PHP 7.0

**Comment by ywarnier** [comment]
Bonjour @MonteiroJ , le premier pas correct pour tout ce que tu demandes est le manuel du développeur (en anglais mais bien illustré) ici: https://docs.chamilo.org -> English -> tout à la fin.
Tu y trouveras des infos pour la définition de "custom pages" (pour la page de login), la redéfinition du set d'icônes au sein d'un style CSS personnalisé, etc.

Pour les icônes, n'oublie pas que certains navigateurs modernes enregistrent des éléments en cache qui résistent à un simple CTRL+F5, donc il faut aussi veiller à cela en nettoyant bien la mémoire cache.
Pour ce qui est des styles CSS, l'upload via la page web d'administration rafraîchit également le style au bon endroit (qui passe de app/Resources/public/css/themes/x vers web/css/themes/x). Si tu changes ça à la main, il faut veilleur à toujours terminer une mise à jour par un "composer install" à la racine du projet.

Si nous avons effectivement de la documentation de base en anglais, n'oublies pas que Chamilo est un projet très étendu (avec des centaines de fonctionnalités inter-liées). Chez BeezNest, nous sommes une dizaine de personnes travaillant sur le projet depuis des années (à temps plein) et c'est proposer nos services de spécialistes qui nous permet aussi de financer le développement du projet. Je ne voudrais donc pas te donner de fausses idées sur la dfficulté de l'effort de modification (parce que tu parles de PHP, de frameworks, etc): apprendre prend du temps!

Cela dit, les types de modifications documentés dans le guide devraient suffire pour ce que tu indiques vouloir changer, et des tutoriels sont les bienvenus (on peut en discuter ici, mais en termes généraux les publier sur un blog ou sur youtube est tout ce que nous demandons).

Si, en cours de chemin, tu as de bonnes idées sur comment simplifier le processus, nous sommes toujours preneurs.

N'oublies pas de fermer cette tâche quand tu considéreras qu'elle a été solutionnée.

**Comment by MonteiroJ** [comment]
Modification of the different elements

1 - Modify the Mail template

To modify the mail, it is necessary to copy the file /main/template/default  in  /main/template/[custom], where custom is the name of your file.
`cd /var/www/[folder_chamilo]`
`cp main/template/default/ main/template/custom -r`

Then you have to tell the configuration to use this template
`nano app/config/configuration.php`

Look for the line, on debian made CTRL + W it will look for a string in a file:
`$_configuration['default_template'] = 'default';`

Then replace 'default' with 'custom' :
`$_configuration['default_template'] = 'custom';`

Then to modify the template go to the folder /main/template/custom/mail/
`cd /main/template/custom/mail/`

Here you will find several templates for the mail, you choose the one you want to change 😊.
Once finished, you have to clean chamilo cache, using his interface.

> Log in admin -> Administration -> Clean of cache and temporary files -> Proceed with cleanup

From here the changes should be applied
To verify this, you can create a new account (if you have enabled this feature).

2 - Edit the CSS && template of the icon pack

For that, log into admin, Go in the configuration of style sheets and download the current theme :

> Administration -> Configuration settings -> Style sheet icon -> Download -> Download the file

You will get a zip file containing the following path:

> _\var\www\[chamilo]\app\Resources\public\css\themes\[theme_name]

Extract the folder [theme_name]. From here you can change the font that is applied by replacing the existing files. But, you can also change the css.
To change the icon pack, just add a folder icons, you can also copy/paste the folder icons: 

> [chamilo]/main/img/icons.

If you do not copy the folder, you must create the folder where the icon you want to edit is located.
An example to be clearer.
If you want to modify the following icons :

![image](https://user-images.githubusercontent.com/33484244/39429800-4fab4f16-4c8c-11e8-8c6e-8171762548bb.png)

What interests us is the path of the image in order to be able to modify it

If you inspect the image "inbox", you will have the following code:
`<img src = "http://192.168.136.138/main/img/icons/22/inbox.png" alt = "Inbox" title = "Inbox">`

So in the folder icons, create a folder 22, we put the image that we want and we change its name so that it corresponds, here to inbox.png.
The procedure is the same for each image.

When finished, compress the [theme_name] folder to .zip and return to style sheet management.
Click on **"New stylesheet File"**. From here you have to choose the name of your theme, import the file [name_theme] .zip.
Click on imports the file.
Finally select your theme.

![image](https://user-images.githubusercontent.com/33484244/39429980-d841c602-4c8c-11e8-9567-03ee7934086c.png)

**Comment by ywarnier** [comment]
If your guide is nice, I'm not sure I really want some of that to be published: we fixed in what's going to become 1.11.8 an issue that was preventing the templates to be "cascading", in the sense that now a new template should *only* have the files that are *not* the same as in the default. As such, I think the documentation (if it is published around the release of 1.11.8 in June) should rather say that and that versions <1.11.8 were an exception). The problem with copying the whole directory is that, when new template files are added to Chamilo (like nex links to new features) they are ignored in the user interface because the copied template is not updated. Of course, this also happens in 1.11.8 for the specific files that have been modified, but the scale is much less worrying in this case.

I would definitely add more precision to the part saying that you "only have to add an icons/ directory", because you are not precise about *where* to add it.

**Comment by diah22** [comment]
Bonjour, est ce quelqu'un pourrait m'aider? on m'a confier une tâche, c'est de proposer une solution intranet pour mon entreprise...
J'ai beau chercher et essayer des tas de projet open source et j'ai compris que chamilo s'adapte le mieux avec ce que cherche mon entreprise... juste que j'ai envie de modifier certains page... comme au lieu de cours je peux mettre formation.. en gros je veux modifier la barre de menu, et de désactiver certains paramètres. Donc je cherche une bonne documentation pour la fonctionnement de la totalité du site.. je suis débutante pour php :) Merci d'avance

**Comment by ywarnier** [comment]
Le manuel du développeur (en anglais à la fin de la table des matières) ici: https://docs.chamilo.org/ et le manuel admin en français (liste dépliante quand on clique sur le nom du guide Chamilo 1.11 English en haut) sur les langues (et jargons/sous-langues) devraient t'aider.

**Comment by diah22** [comment]
Merci beaucoup mais on dirait que çà ne m'a vraiment pas aider... j'ai du mal à comprendre le cheminement du répertoire et tout..
Est ce que vous pouvez me donner quelques indices.. j'aimerai changer 'Mes cours' dans le menu ci dessous par 'Formation'
Comment pourrait-je y accéder ? Merci.
![navbar](https://user-images.githubusercontent.com/49787671/91412146-05c54c80-e852-11ea-87a4-8956831b5638.JPG)

**Comment by diah22** [comment]
@ywarnier

**Comment by NicoDucou** [comment]
> Merci beaucoup mais on dirait que çà ne m'a vraiment pas aider... j'ai du mal à comprendre le cheminement du répertoire et tout..
> Est ce que vous pouvez me donner quelques indices.. j'aimerai changer 'Mes cours' dans le menu ci dessous par 'Formation'
> Comment pourrait-je y accéder ? Merci.
> ![navbar](https://user-images.githubusercontent.com/49787671/91412146-05c54c80-e852-11ea-87a4-8956831b5638.JPG)

Dans ce cas, il suffit de créer un jargon (sous langue) et de redéfinir le terme "Mes cours" par "Formation". Vous pouvez vous reporter à la partie langues de la documentation pour voir cela : https://docs.chamilo.org/v/1.11.x-fr/guide-administrateur/administration/administrer_la_plateforme#langues

**Comment by ywarnier** [comment]
This has become too much of a melting pot and most of its initial topic has been attended. Closing.
