### ISSUE TITLE
Add speed plugin to mediaelement.js

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2511]
### Current behavior
No way to watch a video faster than its intended speed

### Expected behavior
Possibility to watch a video at 0.75, 1, 1.25, 1.50 and 2.0 times the speed.
Use the speed plugin for that: https://github.com/mediaelement/mediaelement-plugins/blob/master/docs/speed.md
This should be enabled only through a new option:
```
// Enable speed controller in video player
// $_configuration['video_player_speed_controller'] = false;
```

### Steps to reproduce
Watch a video uploaded to Chamilo

### Chamilo Version
1.11.x 20180429

**Comment by jmontoyaa** [comment]
I added the option using this setting:

`$_configuration['video_features'] = ['features' => ['speed']];`

**Comment by ywarnier** [comment]
Do I need a bower install or something like that to see it?

**Comment by ywarnier** [comment]
Ah, I found it with the right click button, but I was hoping for something more visual to appear in the video toolbar at the bottom. Did you see a way to add this, by any chance?

**Comment by jmontoyaa** [comment]
Right click button? I have this:

![screenshot from 2018-05-01 08-13-29](https://user-images.githubusercontent.com/158935/39463332-b61fb71a-4d17-11e8-96fc-8657ab8793cc.png)

**Comment by ywarnier** [comment]
No tengo esto en campus.chamilo.org. Puedes checkear si me faltó algo? (bower update?)

**Comment by jmontoyaa** [comment]
campus.chamilo have a custom template so the new settings are not added correctly.

I modified this file in the server:

`main/template/campus/layout/footer.js.tpl`

Now it works.

**Comment by jmontoyaa** [comment]
I tested it here:

https://campus.chamilo.org/main/document/showinframes.php?cidReq=TESTJULIOMM&id=3377556

**Comment by ywarnier** [comment]
Yes, that would explain it. Excellent!
