### ISSUE TITLE
Tous les membres du groupe sont désinscrits (version1.11.4 à 1.11.6)

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2515]
Dans un cours, en effectuant une recherche dans un groupe, Membres du groupe, par le champ de droite, donc ceux déjà inscrits, on trouve l'utilisateur que l'on désire désinscrire, on le sélectionne et lorsque l'on enregistre les paramètres, tout le groupe se vide.
Par contre si on effectue la même manœuvre avec le champ de droite: recherche d'un utilisateur à ajouter au groupe, sélection et enregistrement, tout est ok. 

Problème présent sur https://campus.chamilo.org/

**Comment by ywarnier** [comment]
Special gift to @jmontoyaa :smile:

**Comment by jmontoyaa** [comment]
Can be tested in 11.chamilo.org, if an error is found please provide the link with the error.

**Comment by andreboivin** [comment]
Excellent, problème réglé sur 11.chamilo.org. Merci!
