### ISSUE TITLE
Integrate VR/360° video player

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2519]
Allow Chamilo to recognize and provide a VR/360° video player in the documents and learning paths tool.
Add support for a new document type ("video360"?) to documents and, whenever trying to display it, show the proper video player.
There is a [vrview](https://github.com/mediaelement/mediaelement-plugins/blob/master/docs/vrview.md) plugin in mediaelement.js, but we'd have to test it to see if it provides what we need.

**Comment by AngelFQC** [comment]
Related to #2622

**Comment by jmontoyaa** [comment]
See #2622
