### ISSUE TITLE
Show Export to PDF button in learnpath list when hide_scorm_pdf_link is disabled

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2521]
### Current behavior / Resultado actual / Résultat actuel
With the new design for students in learnpath list, when `hide_scorm_pdf_link` is disabled, the button to export to pdf only appears to teacher and not for students

### Expected behavior / Resultado esperado / Résultat attendu
Allow students export the learnpath to pdf when `hide_scorm_pdf_link` is disabled

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
- Disable `hide_scorm_pdf_link` in settings page
- See the learnpath list in a course as teacher. Then see the Export To PDF button
- See the learnpath list in a course as student view

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x branch

**Comment by aragonc** [comment]
![pdf_button](https://user-images.githubusercontent.com/2940509/40553256-aa389130-6007-11e8-8967-8f25ee167630.png)
Listo...

**Comment by ywarnier** [comment]
The fix works for me.
I added a "I shoud see an icon with title 'X'" to the available Behat feature contexts
