### ISSUE TITLE
database

### ISSUE THREAD

**Issue by learningcentrum** [chamilo/chamilo-lms#2522]

**Comment by learningcentrum** [comment]
This portal is currently experiencing database issues. Please report this to the portal administrator. Thank you for your help. 
after a backup / restore the site is not longer available

**Comment by learningcentrum** [comment]
http://lms.learningcentrum.nl/
the test version work fine http://a-lms.learningcentrum.nl/

**Comment by learningcentrum** [comment]
I can not login the site

**Comment by learningcentrum** [comment]
nothing in the server log
in with file is the database settings

**Comment by learningcentrum** [comment]
Fount the problem
configuration.php 
databse user
main database

greetings
Martin Doornbos

**Comment by learningcentrum** [comment]
Fount the problem

configuration.php 

databse user

main database

 

greetings

Martin Doornbos

 

Van: Yannick Warnier [mailto:notifications@github.com] 
Verzonden: dinsdag 8 mei 2018 17:23
Aan: chamilo/chamilo-lms
CC: learningcentrum.nl; Author
Onderwerp: Re: [chamilo/chamilo-lms] database (#2522)

 

Then back to the first solution: in the web server's logs, you should have more info.
Maybe this helps if you don't know where to find the logs: https://askubuntu.com/questions/14763/where-are-the-apache-and-php-log-files/146071#146071

**Comment by ywarnier** [comment]
Did your configuration.php change? Was it corrupted? Unaccessible because of permissions?

**Comment by ywarnier** [comment]
OK, thanks.
This was not *just* a backup/restore then (as specified initially). Please be precise in your issue reports as this helps us be more efficient in helping you.

**Comment by learningcentrum** [comment]
we make a total backup / restore on a other disk

**Comment by alexeiol** [comment]
Thank you, @learningcentrum (Martin Doombs)! Your post saved my job today! Merry Christmas for you and yours!
