### ISSUE TITLE
Assignment "visible to all users" settings should be in course settings

### ISSUE THREAD

**Issue by jderriks** [chamilo/chamilo-lms#2523]
### Current behavior / Resultado actual / Résultat actuel
Case: A teacher wants to share some assignments in a group with all users of the GROUP and uses this form:
<img width="625" alt="afbeelding" src="https://user-images.githubusercontent.com/1659604/39782401-5b0a834a-5312-11e8-8716-e94b2ebe16b2.png">

The teacher thinks this is a GROUP assignment setting (look at the top wher it says GROUP area) and clicks "new documents visible to all users". This text also suggests that OLD assignment access rights are not changed (the spanish text does not mention the word "new")

HOWEVER: this setting opens up ALL assignments in ALL groups of the course, including top-level assignments on course level. Students love this misstake since now they can look at all assignments handed in by their fellow students. And never use Chamilo again.

### Expected behavior / Resultado esperado / Résultat attendu

There are two ways out of this. Since the database course field setting 'show_score' is responsible for the given assignment setting it seems logical to put this in the course SETTINGS tool where a teacher that is working with (group) assignments cannot change it by accident.
A more complicated solution is that a teacher can indeed change the "visible for all users" setting for every assignment as the above form suggests but I guess that requires database structure changes and it should be very clearly visible to the teacher if an assignment is "public" or "private" work.
The last option is to completely remove the "visible to all" feature for assignments. We never use it.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Try changing this setting from a group assignment and you will find that ALL assignemnts in the course are now visible to others. Pretty dangerous setting and not easy to spot for teachers. 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11, tested on 11.chamilo.org today.

**Comment by ywarnier** [comment]
The best solution to me (pending a check on the fact that the setting change is indeed the one in course_settings) would be to move the setting to the course configuration page, indeed.

**Comment by ywarnier** [comment]
@jmontoyaa, want to take this one?

**Comment by jmontoyaa** [comment]
Makes sense.

**Comment by ywarnier** [comment]
Added a minor change to set a default value in case the setting doesn't exist yet (blank radio box options are confusing).
