### ISSUE TITLE
How to allow teacher's audio recorder in Chamilo 1.11.6

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2527]
### Current behavior / Resultado actual / Résultat actuel
In config file it is possible to allow audio recorder for the learner and it is possible to create exercises where the learner records his speech.

### Expected behavior / Resultado esperado / Résultat attendu
How the recorder is allowed for the teacher to give audio feedback for the learner?

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by ywarnier** [comment]
I'll consider this closed (no answer from reporter).
