### ISSUE TITLE
Stylize new document / Use documents from other courses

### ISSUE THREAD

**Issue by MonteiroJ** [chamilo/chamilo-lms#2529]
Hi !

I actually have 2 questions :
- Is there a way to stylize the creation of a new document ? ( Actually power point template )
![2018-05-24_14h57_13](https://user-images.githubusercontent.com/33484244/40486829-af97db90-5f62-11e8-9ea6-504498abd445.png)

- Can I use documents from another course to avoid duplication?

Thanks a lot !

**Comment by NicoDucou** [comment]
For your first question you can create a new document and then when you are in the document tool on the line of your document in the action column there is a icon that appears for html files that says "add as a template" as on the picture below : 
![chamilo 1 11 x 24 05 2018 18 04 gmt 2 validation portal nicodu](https://user-images.githubusercontent.com/6579268/40498106-535021e6-5f7e-11e8-841d-787f0c7349cc.png)

Once you've done this your template will appear in the bloc you indicated.

For the second question about using a document from another course this is a feature that will be added to version 2 of Chamilo, this requires a big structure change that is already planned for version 2 of Chamilo.

If this answers your question please close the task or don't hesitate to ask for more information.
