### ISSUE TITLE
How to change the chamilo logo with another logo ?

### ISSUE THREAD

**Issue by Lindswell** [chamilo/chamilo-lms#2530]
i cant change the logo, i've tried to change the logo via new stylesheet file, update logo, and changing the file via cpanel. can someone help me please ?
Chamilo Version Chamilo 1.11.6

**Comment by ywarnier** [comment]
Please make sure your logo has *exactly* the dimensions indicated in the message above the logo upload form. That should do it because the feature itself works for me.

![logo-upload](https://user-images.githubusercontent.com/609839/41071474-8136e678-69bd-11e8-8026-665fb7d8a48e.png)

**Comment by Netrixdesigns** [comment]
If you change and its not displaying try clearing your browser cache as well. restart your Chamilo then it should reflect your update

**Comment by sparksthe6** [comment]
Hi, kindly how do i change pdf export logo header for chamilo

**Comment by ywarnier** [comment]
@sparksthe6 the logo in PDF documents is the logo from the applicable CSS selected in administration > configuration settings > stylesheets

**Comment by alshershaby** [comment]
it doesn't work for me too, I keep trying to change the logo with the dimensions required but it still doesn't work ...
