### ISSUE TITLE
How to add new role in chamilo 1.11.6? I have to add new role of user to chamilo. For example current we have HR, Learner, trainer, etc.  How to set permissions for the role? 

### ISSUE THREAD

**Issue by akshaybande81** [chamilo/chamilo-lms#2531]
Hi, 
I am trying to add new role to chamilo 1.11.6. I want to set permissions to that role. For ex. I want to add new role Head of Department. How to add rights to that role. Only admin is allowed assign this role to user. 
Thank you.

**Comment by NicoDucou** [comment]
In Chamilo 1.11.6 you can not add new role. You have to use the existing roles that can be completed by specific access in a specific environment. For example à student can be granted the role of assistant in a particular course.

In Chamilo 2.x there is a feature request to make role more flexible and have à table to assign rights to a role.

But Chamilo is really flexible already to adapt to many use cases, so may be if you explain à bit more what you want to do with the role Head of Department we can help you to find a solution.

Best regards

**Comment by akshaybande81** [comment]
Thank you NicoDucou. 

I am using chamilo for my college university. My college university has hierarchical roles like Chanceller-> Vice Chanceller-> Principle -> Vice Principle -> Head of Department-> Teacher. 

I want to add roles for everyone in chamilo. when teacher add new course to chamilo, that course should be approved by Head of Department. 

Head of Department should get information about all teachers. 

Vice Principle should be able to list all Head of Departments, get information about them.

Principle Should be able to get all information about Vice Principle. But  vice versa is not true. 

Chancellor should be able to get all information about Vice Chancellor, Principle, Vice Principle, Head of Departments, Teachers.

**Comment by akshaybande81** [comment]
Thank you Nicolas. 

Be able to access the user information means able to access their courses. As mentioned I added HR manager to teacher, I tried to access course under teachers but it said "you are not allowed access this page" can you help me on that. 

I want HR managers to access Teacher's courses. 



Thank you.

**Comment by NicoDucou** [comment]
You can not add permission to rôle, this will be added in Chamilo V2.x

But the problem you are reporting that the HR manager can not access the course of the user they are following as been corrected for the next version of Chamilo.
You can test it here on the test plateform with the user hrmanager/hrmanager
enter https://11.chamilo.org/main/mySpace/myStudents.php?student=65
when you click on the name of the course for exemple "nicodu" in the session "multi courses" then you get to this course even if the hrmanager is not subscribed to this course.

I let you check and close this task if all is correct.

**Comment by ywarnier** [comment]
Reporter stopped providing feedback. Closing.

**Comment by akshaybande81** [comment]
Thank you. It helped a lot.
