### ISSUE TITLE
Security Vulnerability Contact

### ISSUE THREAD

**Issue by indianamoreau** [chamilo/chamilo-lms#2532]
I have discovered a serious security vulnerability in Chamilo LMS, who should I privately contact about it?

I've attempted to email info@chamilo.org but the email seems to be no longer working.

**Comment by jmontoyaa** [comment]
Hi, you can contact support@beeznest.com

**Comment by ywarnier** [comment]
We are currently having some issues with mails to the @chamilo.org domain. We are working on this (hopefully a fix should be reached by early June). In the meantime, an alternative e-mail to the company developing most of Chamilo, as specified by Julio above, would be the next right way.

**Comment by ywarnier** [comment]
This has been reviewed and approved by the reporter, @indianamoreau
