### ISSUE TITLE
Erro no texto da pagina inicial

### ISSUE THREAD

**Issue by LuisGSVasconcelos** [chamilo/chamilo-lms#2533]
### Current behavior / Resultado actual / Résultat actuel
![image](https://user-images.githubusercontent.com/21109178/40548155-4698d4e8-600a-11e8-842b-0d9a49f44759.png)

Na figura o  termo adiministração  está faltando o "s"
### Expected behavior / Resultado esperado / Résultat attendu
Alterar o termo "adiminitração" para "adiministração"
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Entrar na pagina http://signpat.com.br/cursos 
### Chamilo Version / Versión de Chamilo / Version de Chamilo

Versão 1.11.4

**Comment by NicoDucou** [comment]
I just corrected the main translation on https://translate.chamilo.org/ for the variable PortalHomepageDefaultIntroduction 
So in the next release of Chamilo it will be corrected.
