### ISSUE TITLE
How to enable course validation in chamilo 1.11.6? 

### ISSUE THREAD

**Issue by akshaybande81** [chamilo/chamilo-lms#2534]
Hello,
I want to enable course validation in chamilo 1.11.6. 

A teacher is not able to create a course alone. He/she fills a course request. A platform administrator (or a HR manager with rights as a platform administrator) reviews the request and approves the request and after that the requested course is really created. Also, the platform administrator can reject course requests.

**Comment by ywarnier** [comment]
This feature exists in Chamilo. Use the "Allow non admin to create courses" (or something like that). See https://docs.chamilo.org/en/admin/appendix/configuration_settings_list.html and search "allow non admin" -> put this setting to "no". Then look for "course validation" or "training validation" and set it to "yes".
The course creation link should then change (for the teachers) from "Create course" to "Request course" in their left menu.
