### ISSUE TITLE
Missing value for course content

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2535]
### Current behavior / Resultado actual / Résultat actuel
After migrating from 1.9.10.2 to 1.11.6 some courses can't be opened since it seems that they miss a parameter/value

```
Fatal error: Uncaught Error: Call to a member function getForumThread() on null in /home/clients/web/main/lp/learnpath.class.php:6084
Stack trace:
#0 /home/clients/web/main/lp/lp_add_item.php(213): learnpath->return_new_tree(NULL, true)
#1 /home/clients/web/main/lp/lp_controller.php(480): require('/home/clients/w...')
#2 {main} thrown in /home/clients/web/main/lp/learnpath.class.php on line 6084
```

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by ywarnier** [comment]
Does "php bin/doctrine orm:schema-tool:update --dump-sql" show you a lot of queries?
It might be useful to wait for 1.11.8 (or use a Git version) for learning paths issues as we have recently introduced a series of additional checks and fixes for old portals migrations. Keep a backup of your unaltered version 1.9 somewhere.

**Comment by opensourcecompany** [comment]
Okay, then we will restore the old one :-)
Annoying that the error message got truncated and also the hosting company stores no valuable information about this ...

Thx

**Comment by opensourcecompany** [comment]
Since we have 2 versions (PHP5 and 7), is there a difference with normal git checkout?

**Comment by ywarnier** [comment]
No, but a git checkout always requires you to run the `composer update` command. If you're familiar with this process, then it's exactly the same. Otherwise let us know, I think we have info in the README.md or CONTRIBUTING.md
