### ISSUE TITLE
Error al intentar dar de baja una cuenta

### ISSUE THREAD

**Issue by mauriciobaeza** [chamilo/chamilo-lms#2544]
### Current behavior / Resultado actual / Résultat actuel
Error al dar de baja una cuenta con el mensaje:
 Notice: Array to string conversion in /var/www/campus.chamilo.org/www/main/inc/lib/pear/HTML/QuickForm/button.php on line 139

### Expected behavior / Resultado esperado / Résultat attendu
Mensaje de baja correcto

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
1) Editar perfil
2) Click en la opción Dar de Baja (https://campus.chamilo.org/main/auth/unsubscribe_account.php)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Versión web, supongo es la ultima: https://campus.chamilo.org/main/

Gracias

**Comment by ywarnier** [comment]
Hola @mauriciobaeza, gracias por reportar.
Se eliminó el usuario (a parte del mensaje que apareció)?

**Comment by mauriciobaeza** [comment]
Si, el usuario se elimino.

**Comment by ywarnier** [comment]
Está arreglado en el código. Dentro de poco actualizaremos el campus.chamilo.org para que se aplique este cambio. Gracias por reportarlo!
