### ISSUE TITLE
Normalize the position of tool introduction in all course tools

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2546]
### Current behavior / Resultado actual / Résultat actuel
When `enable_tool_introduction` is enabled
In all course tools, the introduction section is displayed before the action bar, except in Learning Path and Forums

### Expected behavior / Resultado esperado / Résultat attendu
Display the introduction section between the breadcrumb and actionbar in LP and Forum tool

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
* Enable `enable_tool_introduction`
* In Document tool set the introduction and see the position between breadcrumb and actionbar
* In Learning Path set the introduction and see the position between actionbar and content

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by aragonc** [comment]
Ahora si se ve mejor

![introduction_section](https://user-images.githubusercontent.com/2940509/41242205-83333454-6d64-11e8-8e3f-d2af9274df0e.png)

**Comment by ywarnier** [comment]
Looks good to me!
