### ISSUE TITLE
Automatic message modification

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2548]
### Current behavior / Resultado actual / Résultat actuel
When a new user is created (either on the Portal or CSV), Chamilo sends an automatic message to a new user.
### Expected behavior / Resultado esperado / Résultat attendu
How to modify this automatic message?
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by ywarnier** [comment]
Hi @Elearner2018,
We're meaning well for all our users, but this is a bit extreme in terms of uselessness. Please *read* the interface:
In the user creation form:
![new-user-1](https://user-images.githubusercontent.com/609839/41103454-d219b23e-6a2e-11e8-8aa5-9f3894ed32a5.png)

On the CSV import page:
![add-user-2](https://user-images.githubusercontent.com/609839/41103466-d917ae42-6a2e-11e8-9a2f-0e4dfb5643e9.png)

These options allow you to control whether an e-mail is sent or not.
