### ISSUE TITLE
Move exercise results alert e-mail contents to main/template/x/mail/exercise_result_alert_body.tpl

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2549]
### Current behavior / Resultado actual / Résultat actuel
Chamilo sends an automatic message to a learner from a validated exercise. There is an automatically added link for the learner to click on in the message. The link is also shown for the teacher when he is checking the exercises before sending the automatic message to the learner.
### Expected behavior / Resultado esperado / Résultat attendu
How to delete this link from the message? The teacher can do it before sending the message to the learner by hand but it is quite consuming.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by jmontoyaa** [comment]
You can change the settings of the course here:

https://11.chamilo.org/main/course_info/infocours.php?cidReq=A001&id_session=0&gidReq=0&gradebook=0&origin=

![selection_001](https://user-images.githubusercontent.com/158935/41098394-8006f682-6a5b-11e8-95ef-9584de02f24c.png)

**Comment by jmontoyaa** [comment]
"There is an automatically added link for the learner to click on in the message."

What's the link?

**Comment by Elearner2018** [comment]
It says above the link: Click the link below to access your account and view your commented Examsheet. It is followed by a long and complicated link that finally leads to the Portal's main page where the user can log in. 
It's been confusing for many learners as they think they see the feedback straight from the link which is why I would not like to have the automatic link added to every feedback that is written.

**Comment by ywarnier** [comment]
There are several places where this link can come from.
In this case, you can find the text "Click the link below to access  your account and view your commented Examsheet." in the language file in main/lang/english/trad4all.inc.php and identify it as the language variable "ClickLinkToViewComment", then look for the use of that variable in Chamilo, and you'll find it in main/inc/lib/exercise.lib.php, used only once in the whole Chamilo code, so it's easy to hack.

To remove it, you can just edit main/inc/lib/exercise.lib.php, remove the line containing that variable and get done with it.
Please note that this procedure, however, is not update-compatible, and whenever you update your Chamilo installation the next time, you will have to do that again.
There is an ongoing (but slow) effort in Chamilo to move the contents of all e-mails to the templates directory (main/template/[your-template]/mail/) to allow for greater customization of e-mails. This might require a bit more time, though.

I am transforming/hacking this task into one to put that e-mail text into a template. I consider your question solved, but feel free to update us if that is not the case.

**Comment by aragonc** [comment]
I'm confused, what do I have to do in this task?

**Comment by ywarnier** [comment]
Create a new template for the e-mail defined in exercise.lib.php around "ClickLinkToViewComment"

**Comment by aragonc** [comment]
You are ready to try

**Comment by ywarnier** [comment]
5a80a12c58e3864cead851c43ad10d0048b7acd6 introdujo un error grave porque cambió el nombre de un elemento HTML (form id=...) que estaba usado dentro del mismo archivo por el código JavaScript a cargo de registrar los cambios en el formulario para guardarlos.
Fue corregido a través de https://github.com/chamilo/chamilo-lms/commit/302ec74db1002edb053ea0f8fc6b9aa0903674c9

**Comment by ywarnier** [comment]
El resto se ve bien pero no he podido verificar la recepción del correo todavía. Tu?

**Comment by ywarnier** [comment]
Checked and approved.
