### ISSUE TITLE
Automatic message content modification

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2550]
### Current behavior / Resultado actual / Résultat actuel
I did not explain clearly the question in the previous thread. I'm sorry about that.
Chamilo sends automatic messages to new users. 
### Expected behavior / Resultado esperado / Résultat attendu
Where to modify the content of this automatic message? Somewhere in App/config?
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

**Comment by ywarnier** [comment]
That is clearer indeed, sorry for being so quick on the other issue.
You can some answers here: https://github.com/chamilo/chamilo-lms/issues/2510#issuecomment-385403141 and in the rest of the thread. Note that edition of e-mail texts is not yet a feature in Chamilo. We hope to include this in future versions.

**Comment by ywarnier** [comment]
Please continue the topic in the #2510 issue if you have further questions
