### ISSUE TITLE
EUGDPR: Link terms and conditions to personal data page (both ways)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2553]
- The personal data page should be linked to the general (current) terms and conditions.
 - The terms and conditions should have an independent page (even if already approved by user) (only accessible from the personal data page for now)
 - The terms and conditions page should have a link to the personal data page

**Comment by jmontoyaa** [comment]
> The terms and conditions page should have a link to the personal data page

You mean here?

![selection_007](https://user-images.githubusercontent.com/158935/43583944-49a74146-9661-11e8-945b-4c708d1120ad.png)

There's already a link there ... That page should be available for anon users?

**Comment by jmontoyaa** [comment]
What I have to do?

**Comment by NicoDucou** [comment]
For me it is all good for this task because the last missing link is not needed as indicated in my comment above. I let @ywarnier confirm what was in my previous comment and if so close the task.

**Comment by ywarnier** [comment]
I made a few changes to the visual aspect, but otherwise all good for me. Closing. Good job.
