### ISSUE TITLE
EUGDPR: Admin report on withdrawal of consent

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2555]
If users withdraw their consent to store data, information should be stored to report about it so the admin knows it happened, from whom (although this is arguably an issue) and when.

Storing this info in track_e_default should be enough to generate the report afterwards.

The report should available in a new "Personal Data Privacy" block on the admin page.

The interface should also receive "requests for erasure" (right to be forgotten) and enable the admin to take action (with e-mail reminders because it cannot take longer than a month).

Particularly specific information about the right to be forgotten available here: https://ico.org.uk/for-organisations/guide-to-the-general-data-protection-regulation-gdpr/individual-rights/right-to-erasure/
Our admin page should point there or to the closest equivalent on the EU website to allow for the admin to be informed before taking a decision.

**Comment by jmontoyaa** [comment]
> If users withdraw their consent to store data, information should be stored to report about it so the admin knows it happened, from whom (although this is arguably an issue) and when.

Right now the only way to use the platform is to accept it, otherwise the user can't continue.
I'm talking about this page:

![selection_007](https://user-images.githubusercontent.com/158935/43584406-984d6504-9662-11e8-9e08-8b849d2efe12.png)

**Comment by NicoDucou** [comment]
On the personal data page https://11.chamilo.org/main/social/personal_data.php there is a bloc at the bottom with "Permissions you gave us". In this bloc there is legal accepted with the last line being a button "Delete legal agreement" that link to https://11.chamilo.org/main/social/personal_data.php?action=delete_legal&user_id=65

When the user click on this button the legal extra field should be updated to remove acceptance. There should be a registry of this removal of acceptance in the track_e_default table and the user should be disconnected from Chamilo because he can not have access anymore. Then when he will log again the terms and conditions should be presented to him as if he did not accept them yet.

On the administration page of Admin report on withdrawal of consent there should be the list of user that withdraw their consent and the date at which they did it.

**Comment by ywarnier** [comment]
Yes it's a withdrawal (so he accepted it first, then decides he doesn't want to anymore).
It's actually a bit more complicated than just removing it: it should be considered as a *request* for removal (not sure how we can handle that) so the admin gets notified (by e-mail and internal messaging) that a user asked for withdrawal, and then takes one of 4 manual actions:
 - contact the user by message + e-mail (to get more info)
 - remove terms and conditions acceptance
 - anonymize the user
 - delete the user

When the user withdraws consent, he should actually have the opportunity to explain why (so we avoid option 1 above in most cases).
I haven't thought that through yet, but I imagine adding *another* extra_field (or 2 including the justification) could do the trick?

**Comment by jmontoyaa** [comment]
Question:

A user can send "Delete legal agreement" and also send for a "Erase account"?

**Comment by jmontoyaa** [comment]
I added all the workflow except the crons and the "Erase account" button.

**Comment by NicoDucou** [comment]
>Question:
>A user can send "Delete legal agreement" and also send for a "Erase account"?
Yes the user can request 2 things : 
* Request to delete legal agreement
* Request to erase account

So there should be 2 buttons.

**Comment by NicoDucou** [comment]
There is a problem, I've connected with user amann/amann on https://11.chamilo.org/main/social/personal_data.php
And I clicked on the button to ask for legal agreement removal.
The admin received a notification, and the user is correctly in the list on the page https://11.chamilo.org/main/admin/user_list_consent.php

Then I logged out of Chamilo with amann and logged in again. I've been redirected to the legal agreement, whereas no action has been taken yet. For the moment Amann asked for removal but the admin did not yet removed it. So Amann should still have access to the plateform until the admin accept the removal

**Comment by NicoDucou** [comment]
On the admin report https://11.chamilo.org/main/admin/user_list_consent.php there should be a column with the name of the user request (Delete legal agreement or Erase account) the name of the request should be a link to show the justification text entered by the user.

**Comment by jmontoyaa** [comment]
I just added all in your comments (No cron yet).

**Comment by NicoDucou** [comment]
When the user click on delete legal agreement he is added correctly to the list and he can still have access until the admin removes the legal agreement. Once the admin removes the legal agreement then the user disappear from the list and on next login the user has to accept the terms and condition again, so all good for this.

On the page https://11.chamilo.org/main/admin/user_list_consent.php there is the column with RequestType which is correct but we are missing the link on the request type to be able to se the explanation of why the user ask for deletion of legal agreement.

There is also a problem, I just created an account test2555 and went on the page https://11.chamilo.org/main/social/personal_data.php, I entered a text in the box "ExplanationDeleteAccount" and validated by clicking on "DeleteAccount.

Then as admin I went to https://11.chamilo.org/main/admin/user_list_consent.php and I have to registry for user test2555, one to delete legal agreement and the other to delete account, when there should be only one to delete account. Once you click on delete the account then the 2 request of this user disappear.

So there is 2 things to do : 
* When a user clicks on delete account there should be only a request for delete account and not for terms removal.
* In the list of user requesting there should be a link on the request type to see the justification of the request.

**Comment by NicoDucou** [comment]
I created a user test2555d, the logged as this user and went to the personal data page https://11.chamilo.org/main/social/personal_data.php. I've put a text in the box for delete legal agreement explanation and click on the delete legal agreement button.

The user appear on the admin report list and I can see in the user edit page the content of the explanation box.

Then as user test2555d I went again on the personal data page and this time I put a text in the Explanation for delete account box and clicked on the Delete Account button.

On the admin report page there is no more the delete agreement request, only the delete account request. The problem that I reported before is that when the user only click on the delete account then the 2 request where generated when only one request should be generated. But if the user requested before to delete legal agreement  then this request should still appear, it should not be deleted.

and when we go on the user edit page there is no field for Request for delete user account explanation, so I can not see it as an admin. For this last problem maybe it is just that the extra field is not created on 11.chamilo.org

**Comment by jmontoyaa** [comment]
Ahhh ok, it should be fixed now. Both issues.

**Comment by NicoDucou** [comment]
Ok, it's all good now for this.
I just realized that we should show in the admin report the date when the user did the request. Since there is a limit of 4 weeks to take into account the request.

@jmontoyaa can you add a column in the admin report with the date of when the user sent the request.

Then the only missing part of this task would be the cron.

**Comment by jmontoyaa** [comment]
> if a user has requested for removal of legal agreement since 1 week and none of the 3 options (Remove terms and conditions acceptance, Anonymize user or Delete user) has been taken

If admin executes any of this 3 actions, all the extra fields values should be removed/clean for that user?

request_for_legal_agreement_consent_removal_justification
request_for_legal_agreement_consent_removal
request_for_delete_account_justification
request_for_delete_account

**Comment by NicoDucou** [comment]
>If admin executes any of this 3 actions, all the extra fields values should be removed/clean for that user?
>request_for_legal_agreement_consent_removal_justification
>request_for_legal_agreement_consent_removal
>request_for_delete_account_justification
>request_for_delete_account

I would say yes because if an action is taken I guess the DPO or the Admin will have taken the correct action for the user.

**Comment by jmontoyaa** [comment]
I added the cron, new lang variables are needed:
```

$subject = get_lang('UserRequestWaitingForAction');
$content = sprintf(
                get_lang('TheUserXIsWaitingForAnActionGoHereX'),
                $userInfo['complete_name'],
                $link
            );
```

**Comment by NicoDucou** [comment]
All good for the new column in the report. I will check the cron later and add all the missing translations on translate.chamilo.org

**Comment by ywarnier** [comment]
Regarding deletion of the extra fields: OK for now to delete them. Maybe in the future we will be asked to keep some info about the request itself, but this seems contradictory to the fact that the user may ask for his/her data to be removed :smile:

**Comment by ywarnier** [comment]
@NicoDucou I've fixed that, but URLs should *always* be out of the translation term, because they tend to change (not based on the language but based on some regulation change or external site change).
Once they have been translated, it is *very* difficult to go and change all the different versions of the translated string.

**Comment by ywarnier** [comment]
I've moved things around a bit and placed a temporary icon for RemoveTerms but @aragonc showed me a first idea of icon, he will send it later on.
I'm closing this task prematurely. I will ensure the only step missing (the icon) is sent in a few hours.
