### ISSUE TITLE
Chamilo 1.9

### ISSUE THREAD

**Issue by ivlevi** [chamilo/chamilo-lms#2556]
### Current behavior / Resultado actual / Résultat actuel
I cant edit answers to tests. I try to add a new quiz to a cours, something simple, I can add (edit) the question but cant edit answer!

### Expected behavior / Resultado esperado / Résultat attendu
 I shoud be able to edit the answer yo the question I am authoring

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Add new test in learning path and attempt to add question and edit answers
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.9
Installed with Softaculos on a subdomain.
Using Chrome to edit.

**Comment by ivlevi** [comment]
![lms](https://user-images.githubusercontent.com/40044266/41130893-7cfc749c-6ac1-11e8-9fc2-5aabe61a7d88.png)

It looks like that

**Comment by ywarnier** [comment]
The mechanism to lock exercises from edition is meant to protect the exercises agains erroneous changes which can mess up the whole progress of students. You can edit your exercises by removing them from the learning path and editing them separately, then place them again in the learning path. I believe the text explaining why you cannot edit has been reviewed in the last year to be more explicit, but just so you know, version 1.9 is no longer supported (the latest stable version of that branch was more than 2 years ago).

**Comment by ivlevi** [comment]
Thank you ywarnier!
Two questions:
How I get an update to Chamiloo? I instaled the lms from cpanel using Softaculos...

I tried to produce a test from admin panel - see screen capture. Same result...
![lms1](https://user-images.githubusercontent.com/40044266/41131042-2ae053ee-6ac2-11e8-87e5-8cd36936fbf3.png)

**Comment by ivlevi** [comment]
PS: in the System status it says database is version 1.11.0.6...

**Comment by ivlevi** [comment]
This is a nightmare!...

I downloaded an excel template and edit around a bit and uploaded.

Back in Chamilo trying to edit - no dice...

This is insane!
![lms2](https://user-images.githubusercontent.com/40044266/41131574-0b65d22a-6ac5-11e8-96c0-d2c465bc1f56.png)

**Comment by ivlevi** [comment]
I cant find a manual to guide me step by step - an idiot guide - maybe that will help....

**Comment by ywarnier** [comment]
Like https://docs.chamilo.org, you mean?

**Comment by ywarnier** [comment]
You can probably also find a lot of interesting content on youtube

**Comment by ivlevi** [comment]
I know that manual.
Strange thing thwgh: in the manual the icons have a green cross in thlist of question type. 
In my interface those have an orange star...

That means the item is not available?

I did the steps exactly as in the manual - no go....

**Comment by ivlevi** [comment]
Solution:
Delete all - subdomanin included from hosting.
Re-create sub-domain. Instal Chamilo (Softaculos).
DO NOT configure ANYTHING!
Create a mock course.
Start creating a quiz - IT WORKS!

Geeee......
