### ISSUE TITLE
Convert user_api_key.api_service to 'default'

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2560]
### Current behavior
By default, it is set to 'dokeos'.

### Expected behavior
Instances of that keyword have been almost completely removed and we don't want to introduce another dependency on a name. Better use 'default'.
The API keys are still used in some connections to other platforms (like the Drupal module).

### Chamilo Version
1.11.6, but we need to remember to migrate this in the process to upgrade to 2.0

Something like `UPDATE user_api_key SET api_service = 'default' WHERE api_service = 'dokeos'`.
And also update the code to use 'default'. See usermanager.lib.php::get_api_keys() and main/auth/profile.php, at least.

**Comment by ywarnier** [comment]
Eliminar user_api_key si no se usa (donde se guarda el token para rest/v2.php?)

**Comment by AngelFQC** [comment]
En chamilo 1.11.x user_api_key se usa para guardar el api v2.php, pero no se usa como "dokeos" sino como `MsgREST`
En chamilo 2 no se usa un api key, sino que se genera un json web token.

**Comment by ywarnier** [comment]
Entonces eliminar el campo user_api_key en master (y asegurarse que la migración lo toma en cuenta)

**Comment by jmontoyaa** [comment]
La tabla UserApiKey no existe en master, el campo user.user_api_key no existe en master, solo queda el campo api_token.

**Comment by jmontoyaa** [comment]
Revisando el código de rest/v2.php, se necesita esa tabla UserApiKey para validar a los usuarios. Lo más simple sería restaurar esa tabla.

**Comment by ywarnier** [comment]
Still pending:
- [ ] change creation of user_api_key records to use 'default' by default
- [ ] add a migration to convert existing values
- [ ] change code to check for 'default'

**Comment by christianbeeznest** [comment]
Changed default for user_api_key in this PR https://github.com/chamilo/chamilo-lms/pull/4371
