### ISSUE TITLE
Edición de etiquetas y video url en herramienta configuración del curso

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2563]
### Current behavior / Resultado actual / Résultat actuel
Actualmente el docente que crea su propio curso no puede añadir etiquetas y una url de video sin pasar por administrador (en el caso que se use chamilo para MOOC)

![extrafields](https://user-images.githubusercontent.com/2940509/41382067-1aed7f1c-6f30-11e8-8bb6-c6d4efb52b2c.png)

### Expected behavior / Resultado esperado / Résultat attendu
Que el docente puede agregarlos
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
En configuración del curso
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
I approved this development as a test to see if this generates chaos for institutions who use the course catalogue, or if everything looks good.

**Comment by ywarnier** [comment]
Looks good so far. Tested and approved.
