### ISSUE TITLE
Al cambiar el puntaje de una pregunta se modifica en todos los ejercicios.

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#2565]
### Current behavior / Resultado actual / Résultat actuel
Cuando se utiliza una pregunta desde el almacen en un ejercicio nuevo, al cambiar el puntaje en el nuevo ejercicio se modifica también en el/los anterior/res. Además, no aparece ningún mensaje que advierta que la edición de la pregunta se va a propagar a otros ejercicios.

### Expected behavior / Resultado esperado / Résultat attendu
Cuando una pregunta se comparte entre varios ejercicios, el puntaje debería ser propio de cada uno. Salvo en caso de error, no sería necesario cambiar el texto de una pregunta, por lo que se podría compartir, pero el puntaje no tiene por qué ser igual en varios ejercicios diferentes. En otras palabras, no sería necesario duplicar el texto de la pregunta, pero sí se debería llevar un registro aparte para el puntaje en cada ejercicio.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

1. Crear el ejercicio A con la pregunta A.1.
2. Crear el ejercicio B e importar la pregunta A.1 desde el almacen de preguntas.
3. Modificar el puntaje en B.1.
4. Comprobar que el puntaje también se modificó en A.1, sin ninguna advertencia. 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6

Gracias.

**Comment by ywarnier** [comment]
Sí, es el comportamiento por defecto. Tenemos que volver a introducir el diferencial entre el concepto de vinculación y el concepto de copia. Ahora es vinculación a menos que la copies de un curso a otro, pero entiendo la confusión.

**Comment by jolufe** [comment]
Comprendo. Muchas gracias por la respuesta. Tal vez, por ahora, se podría mostrar un mensaje advirtiendo que al editar una pregunta tomada del almacén se está modificando el original. Sería una modificación menor, pero muy útil. Saludos.

**Comment by jolufe** [comment]
Perdón, cerré el tema por equivocación.

**Comment by ywarnier** [comment]
Sí. Primero tenemos que verificar el comportamiento exacto en el contexto del mismo curso, de cursos distintos y sesiones distintas, para estar claros en la descripción.

**Comment by AngelFQC** [comment]
Las preguntas _sólo se reutilizan_ dentro del mismo curso base. En los demás casos, las preguntas _se copian_. Por ejemplo: Un curso en sesión puede reutilizar las preguntas de su curso base, pero copia la pregunta de otro curso en la misma sesión u otro curso base.
