### ISSUE TITLE
No se pueden eliminar las preguntas huérfanas

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#2566]
### Current behavior / Resultado actual / Résultat actuel
Las preguntas huéfanas no pueden ser eliminadas.

### Expected behavior / Resultado esperado / Résultat attendu
Una opción para eliminar las preguntas huéfanas que ocupan un espacio innecesario en la base de datos. 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Abrir el almacén de preguntas.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.6
Gracias.

**Comment by ywarnier** [comment]
This has been implemented in 1.11.14 with https://github.com/chamilo/chamilo-lms/commit/154dbe881a20b5053af0eb4e152a8572bed86470
