### ISSUE TITLE
EUGDPR: Add data display + export screen (art.20)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2568]
Article 20 requires the possibility for any user to require a structured format of all the personal data the organization keeps about the user.

We should have an export button on the data info page that generates a JSON file with all that data.

The data info page should contain the data specified in #2503

**Comment by jmontoyaa** [comment]
This is not the same as #2606 ?

**Comment by NicoDucou** [comment]
#2606 includes this task.
But from what I can see of the page on main/social/personal_data.php there are still some information missing as referenced to the list in #2503

**Comment by ywarnier** [comment]
Yes, it is a bit confusing now, I admit that. #2606 is the PR ID. It should have been associated with this issue here, so it's kind of a duplicate that will disappear when we merge (which I will do as soon as I have checked your changes).

**Comment by ywarnier** [comment]
There you go, branch 2568 merged and #2606 closed.
We can continue for the missing info from #2503 here.

**Comment by ywarnier** [comment]
Now when I go to the personal_data.php page, I get this circular reference error:
![serializer-error](https://user-images.githubusercontent.com/609839/43536177-907c329c-9581-11e8-90e1-16dfc468bc21.png)

Fatal error: Uncaught Symfony\Component\Serializer\Exception\CircularReferenceException: A circular reference has been detected when serializing the object of class "Chamilo\UserBundle\Entity\User" (configured limit: 1) in /var/www/chamilo111x/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php on line 226
Symfony\Component\Serializer\Exception\CircularReferenceException: A circular reference has been detected when serializing the object of class "Chamilo\UserBundle\Entity\User" (configured limit: 1) in /var/www/chamilo111x/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php on line 226

**Comment by jmontoyaa** [comment]
I don't have that error. I added a fix just in case.

**Comment by ywarnier** [comment]
Now it works for me.
Now we need to fill the data with the related collections (call foreach on each relation, as you suggested?) for #2503

**Comment by jmontoyaa** [comment]
Which collections? All of them? I add it the extra fields here:

https://github.com/chamilo/chamilo-lms/commit/a7567be9c54fbd1ed16779479b7a051c76c3a282

**Comment by NicoDucou** [comment]
>Which collections? All of them?
@jmontoyaa in task #2503 I've listed all the personal data related to a user.
We need to present all of them on this page.
You can present it in groups like I did in task #2503

**Comment by jmontoyaa** [comment]
Mamma mia!

**Comment by ywarnier** [comment]
Yes... it's literally *all* the personal data that we keep about the user, so the idea is to be the most comprehensive we can be about the information we give. I'm not sure it's a good idea to give it on screen immediately, but we should maybe have a link to click to extend the info and see everything.
The JSON format should export everything directly.

**Comment by ywarnier** [comment]
This one has to be extended a bit, still...

**Comment by ywarnier** [comment]
Actually, this should be continued from #2503. I'm closing this task here.
