### ISSUE TITLE
Erro al Fianl de la instalacion

### ISSUE THREAD

**Issue by Bathosay** [chamilo/chamilo-lms#2570]
Fatal error: Uncaught Doctrine\Common\Proxy\Exception\UnexpectedValueException: Your proxy directory "/opt/lampp/htdocs/app/cache/" must be writable in /opt/lampp/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/Exception/UnexpectedValueException.php:40 Stack trace: #0 /opt/lampp/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php(299): Doctrine\Common\Proxy\Exception\UnexpectedValueException::proxyDirectoryNotWritable('/opt/lampp/htdo...') #1 /opt/lampp/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(220): Doctrine\Common\Proxy\ProxyGenerator->generateProxyClass(Object(Doctrine\ORM\Mapping\ClassMetadata), '/opt/lampp/htdo...') #2 /opt/lampp/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/AbstractProxyFactory.php(119): Doctrine\Common\Proxy\AbstractProxyFactory->getProxyDefinition('Chamilo\\CoreBun...') #3 /opt/lampp/htdocs/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2682): Doctrine\Common\Proxy\AbstractProxyFactory->getProxy('Chamilo\\CoreBun. in /opt/lampp/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/Exception/UnexpectedValueException.php on line 40

**Comment by ywarnier** [comment]
El mensaje dice: "Your proxy directory "/opt/lampp/htdocs/app/cache/" must be writable" lo cual se traduce por "la carpeta "/opt/lampp/htdocs/app/cache/" tiene que ser escribible". Tienes que cambiar los permisos en esta carpeta para que el usuario del servidor web pueda escribir ahí. Como no se cual es este usuario en tu sistema, puedes usar:
```
chmod -R 0777 /opt/lampp/htdocs/app/cache
```

**Comment by Bathosay** [comment]
ok ya estoy corriendo la instalacion con ese cambio, gracias te comento q pasa

**Comment by salvadoracostaharo** [comment]
hola

**Comment by salvadoracostaharo** [comment]
hola cuando instalo chamilo me aparece este Warning alguien sabe?
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\chamilo\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php on line 2640

**Comment by cristancho7** [comment]
> hola cuando instalo chamilo me aparece este Advertencia alguien sabe? 
> Advertencia: el interruptor de orientación "continuar" es equivalente a "romper". ¿Querías usar "continuar 2"? en C: \ xampp \ htdocs \ chamilo \ vendor \ doctrine \ orm \ lib \ Doctrine \ ORM \ UnitOfWork.php en la línea 2640

![image](https://user-images.githubusercontent.com/37870089/63134257-4a0ae500-bf8e-11e9-8245-9b2249532d23.png)

Igual me sale amigo, talvez lograste solucionarlo ?

**Comment by ywarnier** [comment]
Este es otro error que el reportado inicialmente.
Parece que estáis usando una versión de Chamilo para PHP 5 sobre un servidor con PHP 7.3. Puede ser? Les recuerdo que la página de descargas de Chamilo ofrece 2 opciones: una para PHP 5.6 y una para "7.0 o superior". https://chamilo.org/es/descargar/

**Comment by danieldocumentos** [comment]
No, sigue igual
