### ISSUE TITLE
Bug lors de la consultation du catalogue de cours

### ISSUE THREAD

**Issue by lzebdi** [chamilo/chamilo-lms#2571]
### Current behavior / Resultado actual / Résultat actuel

Quand on alterne la navigation entre **Catalogue de cours** et **Catégories de cours** à plus d’une page, cela affiche : Aucun cours dans la catégorie courante.

### Expected behavior / Resultado esperado / Résultat attendu

Affichage correcte des cours en naviguant entre Catalogue de cours et Catégories de cours.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

- Page d’accueil
- Catalogue de cours
- Cliquez sur page 2 ou plus 
- Revenir à Catégories de cours et cliquez sur « PC Skills » par exemple
- **Aucun cours dans la catégorie courante !**

https://11.chamilo.org/main/auth/courses.php?action=display_courses&pageCurrent=2&pageLength=12&category_code=PC

### Chamilo Version / Versión de Chamilo / Version de Chamilo

https://11.chamilo.org

**Comment by ywarnier** [comment]
The issue is not present in Chamilo 1.11.18 anymore as far as I can see. We'll check on 2.0.

**Comment by lzebdi** [comment]
@ywarnier , je vous confirme que le problème n'est plus reproductible sur la plateforme "My campus [202110121313] (https://11.chamilo.org/). Merci pour votre intervention.
