### ISSUE TITLE
Problema en IOS con ejercicios en lecciones

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2572]
### Current behavior / Resultado actual / Résultat actuel
Con Ipad o Iphone resulta imposible realizar ejercicios en Chamilo cuando están incluidos dentro de lecciones y tienen más de 3 preguntas en una sola página. Al pulsar el botón de Terminar ejercicio, éste no se envía, sino que la página vuelve al principio.

Curiosamente esto no ocurre si el ejercicio se configura para mostrar una pregunta por página o si sólo tiene 1 o 2 preguntas. En ese caso se envía correctamente. Es como si hubiera un límite de caracteres o de contenido a partir del cual deja de responder Javascript.

### Expected behavior / Resultado esperado / Résultat attendu
El comportamiento debería ser normal, como en ordenadores o en dispositivos Android, permitiendo enviar el ejercicio.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Crear un ejercicio en un curso, con unas 6 preguntas, por ejemplo de opción múltiple. Configurar el ejercicio para que aparezcan todas en una página.
Crear una lección en el curso y agregar este ejercicio.
Acceder a la lección con un Ipad o Iphone e intentar realizar el ejercicio.
Se puede probar aquí:
https://11.chamilo.org/main/lp/lp_controller.php?cidReq=NSRCURSOPRUEBA&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=358&isStudentView=true

### Chamilo Version / Versión de Chamilo / Version de Chamilo

Versiones 1.11.4 - 1.11.6
Comprobado con IOS 11.4 y diferentes navegadores: Safari, Google Chrome, Mozilla Firefox, Ms Edge

**Comment by ywarnier** [comment]
Ya hemos tenido este problema antes y me parece que lo arreglamos. Un rato más tarde lo busco.
Estás segur@ que todavía existe en 1.11.6?

**Comment by nosolored** [comment]
Si, lo hemos probado hace un rato en 11.chamilo.org (más arriba he pegado el enlace del curso donde lo he probado)
También lo hemos probado en una demo nuestra de la 1.11.6

**Comment by ywarnier** [comment]
BT14596

**Comment by ywarnier** [comment]
Esto se ha resuelto para FF y Chrome en iOS pero no para Safari (todavía)

**Comment by nosolored** [comment]
A nosotros no nos funciona en Chrome
Sí funciona correctamente en Firefox y Ms Edge

**Comment by ywarnier** [comment]
Perdón, En FF y Edge funciona. No en Chrome ni Safari. Seguimos avanzando...

**Comment by ywarnier** [comment]
Ya no encontramos el error en Safari tampoco. Alguna noticia opuesta de su lado antes de cerrar?

**Comment by nosolored** [comment]
En Ipad sigue el problema en Chrome y en Safari, a nosotros no se nos ha arreglado. Hemos probado en 11.chamilo.org.
Tened en cuenta que el error solo aparece si el ejercicio tiene varias preguntas en una página, porque hay que hacer scroll, y es cuando da problemas el evento click.

**Comment by NicoDucou** [comment]
He podido reproducir el bug en Iphone X con Chrome en browserstack with the link provided by nosolored (https://11.chamilo.org/main/lp/lp_controller.php?cidReq=NSRCURSOPRUEBA&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=358&isStudentView=true)

The direct link on browserstack is :
https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+X&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2F11.chamilo.org%2Fmain%2Flp%2Flp_controller.php%3FcidReq%3DNSRCURSOPRUEBA%26id_session%3D0%26gidReq%3D0%26gradebook%3D0%26origin%3D%26action%3Dview%26lp_id%3D358%26isStudentView%3Dtrue&speed=1

**Comment by ywarnier** [comment]
Asignando a Julio por si encuentra alguna cosa más que nos ayude

**Comment by jmontoyaa** [comment]
El problema es el mismo que ya comenté en otra tarea y en otros lugares, es debido a estas condiciones especiales, el código fue agregado por @AngelFQC 

https://github.com/chamilo/chamilo-lms/commit/eff98c5f4273bf3b5b11e590dac5e33b4dabe129


main/template/default/learnpath/view.tpl

```

if (/iPhone|iPod|iPad/.test(navigator.userAgent)) {
            document.getElementById('wrapper-iframe')
                .setAttribute(
                    'style',
                    'width:100%; overflow:auto; position:auto; -webkit-overflow-scrolling:touch !important;'
                );
        }
```

**Comment by nosolored** [comment]
Julio, creo que lo que tu comentas es para el scroll en IOS, que efectivamente daba problemas en los frames, pero el problema de ahora no es ese, funciona el scroll, pero no reconoce el evento click.
Alex agregó un cambio que lo arregló para Firefox y Edge, también funciona en Puffin (ref. BT#14596). Para nosotros con esto ya nos vale para salir del paso, aunque estaría bien que funcionase en Chrome y Safari, pero al menos ya no impide a los usuarios hacer el ejercicio, puede hacerlo en otros navegadores.

**Comment by ywarnier** [comment]
Para tratar de organizar un poco este proceso de debug, lo que necesito es lo siguiente:
 - 1 ejercicio con mínimo 5 preguntas a elección única con 2 respuestas, con todas las preguntas en una página (porque es un tema que afecta solo las preguntas después de un cierto nivel de scroll)
 - 1 lección
 - el ejercicio colocado en esta lección
 - un iPhone o iPad con Safari o Chrome

Lo que se observa es que:
 - en la herramienta de ejercicios, todo va bien. Puedo marcar y guardar preguntas
 - pero cuando estoy en la herramienta de lecciones, al dar clic en el 4to botón de guardar, me manda al inicio de la página (scroll arriba) y no guarda
 - si pongo el iPhone en modo horizontal (en vez de vertical), el problema aparece a la 3ra pregunta
 - el botón de fin del ejercicio siempre está bloqueado también (y también requiere JS)
 - marcar las respuestas no da problemas (ni para las preguntas 4-5-6), y esto no requiere javascript
 - no importa si la barra de índice está abierta a la derecha o no
 - hay un comportamiento ligeramente distinto según marcamos respuestas o no, pero hasta ahora no es muy evidente: si *no* marco la respuesta 4, sí me deja guardar la respuesta vacía, pero tan pronto como la marque, ya no me deja guardarla.

Lo que sabemos:
 - para guardar las respuestas intermedias, Chamilo llama a un proceso javascript declarado aquí (y un poco más a bajo para guardar todo el ejercicio):
https://github.com/chamilo/chamilo-lms/blob/f2c97adaef715105e0a3670b01f49f47a27a8e20/main/exercise/exercise_submit.php#L1238-L1278
 - no puede ser que el JS en sí no esté funcionando o esté bloqueado porque (1) la pregunta que se bloquea es distinta en modo horizontal/vertical y (2) si no se puede guardar, el mismo AJAX devuelve un error pero no tiene el efecto de enviar arriba de la página
 - tampoco tiene que ver con el número de la pregunta, porque puede ser 3 o 4 según la orientación del celular
 - el ejercicio en lecciones se visualiza dentro de un iframe, que tiene las siguientes propiedades:

 - tiene que mantener alguna relación de causa-efecto con el iframe o la barra de menú, pues no se produce el error en los ejercicios solos

Debido al comportamiento, puedo imaginar las razones siguientes:
 - puede existir algún tipo de altura máxima de página (que varía según la orientación del dispositivo) en la cual pueda funcionar el JS necesario para guardar la pregunta
 - el contexto de iframe está afectando al ejercicio, posiblemente poniendo una altura máxima en la cual el contenido aparece sin el efecto negativo

**Comment by ywarnier** [comment]
These commits are related to a previous appearance of this issue (or something *very* similar):
https://github.com/chamilo/chamilo-lms/commit/82ff09884a07c93ad188329b375bb056acab952f
https://github.com/chamilo/chamilo-lms/commit/a8b575064027c99958aebacefa19d537e6b22fea
https://github.com/chamilo/chamilo-lms/commit/23f0e5d55c80e374630731237032e177f15f1f4f
https://github.com/chamilo/chamilo-lms/commit/ed163930d08716fe476133ac5be584d6cc44c896
https://github.com/chamilo/chamilo-lms/commit/9f9e5278a7bf6bc5585600e84a52956513d78670

**Comment by ywarnier** [comment]
Al parecer los iframes y Safari mobile son un gran problema: https://stackoverflow.com/search?q=safari+iframe+click+event

**Comment by ywarnier** [comment]
El parche anterior corrige el problema de guardar las preguntas pero no corrige el rebote arriba de la página (hay que escrolear o dejar de guardar pregunta por pregunta y solo guardar el ejercicio al final para evitarlo :smile: )

**Comment by ywarnier** [comment]
@nosolored podríais validar que este parche no rompe el funcionamiento en otros navegadores? He verificado en Linux + FF y iOS + iPad + Safari/Chrome y no cambió nada para FF y corrige el guardado para iOS.

**Comment by AngelFQC** [comment]
El problema, creo yo, es por el diseño actual de lp_view.php, ya que utiliza posiciones absolutas para ordernar la disposición de los paneles superiores, barra de íncide, y bloque de contenido. 
Al tener posiciones absolutas, se limita la altura del iframe. Lo que no tiene efecto en otros navegadores, pero con iOS sí, ya que este considera que la altura del documento padre incluye la altura del documento en el iframe [1], [2]. Y quizás por ahí no logra hacer que funcione todo bien.
Probé poniendo el ejercicio dentro de un iframe en una archivo html separado, y los botones funcionan bien dentro del iframe.

[1]: https://davidwalsh.name/scroll-iframes-ios
[2]: http://andyshora.com/iframes-responsive-web-apps-tips.html

**Comment by ywarnier** [comment]
Estoy cerrando la tarea, pues se encontró una solución para guardar las preguntas. El problema de salto arriba de la página debería ser objeto de otro issue si queremos realmente arreglarlo (la solución sencilla es poner una pregunta por página)
