### ISSUE TITLE
Parámetros avanzados en los ejercicios 

### ISSUE THREAD

**Issue by warc131830** [chamilo/chamilo-lms#2577]
Hola 
Los parámetros avanzados en los ejercicios no me funcionan, él botón no abre las opciones en ninguno de mis ejercicios.
Yo trabajo con mac y en iOS pero también ha intenté desde un pc con Windows y tampoco 
Por favor necesito corregir urgente esto pues tengo todas mis evaluaciones paradas por este detalle

**Comment by warc131830** [comment]
![6886f7e5-dad4-4607-ae9b-a85e42c4c4c1](https://user-images.githubusercontent.com/39733007/42070494-45725a44-7b1c-11e8-85e6-bd73fc1b1ffc.png)

**Comment by warc131830** [comment]
También he intentado utilizando distintos navegadores 
Mozilla, safari Google chrome

**Comment by jmontoyaa** [comment]
Cambia el tema del curso:

https://campus.chamilo.org/main/course_info/infocours.php?cidReq=EDUCACIONARTISTICAGRADOS9ORNVPM&id_session=0&gidReq=0&gradebook=0&origin=

A "Chamilo"

**Comment by ywarnier** [comment]
@aragonc alguna noticia?

**Comment by AngelFQC** [comment]
@ywarnier esto no es bug de chamilo, sólo pasa en campus chamilo por dependencia de librerías que no están en todos los temas css de campus chamilo

**Comment by aragonc** [comment]
@ywarnier se soluciono quitando la opción cambiar hoja de estilo en el curso a deshabilitada
