### ISSUE TITLE
Too many write operations per second and high DB CPU uses on Learning path lessons

### ISSUE THREAD

**Issue by jainpm1** [chamilo/chamilo-lms#2578]
Hi,

We are doing testing of Chamilo LMS in our production AWS environment (With m5.large as Web server (2 vCPU and 8 GB RAM) and m4.large DB server (2 vCPU and 8 GB RAM). The initial testing was performed with 5 concurrent users viewing different chapters in Learning path. It was a 5 mins continuous testing and CPU uses on Web server was as max as 2% during that time, RAM was free upto 75%.
In DB server, RAM was free more than 6 GB (80%) but the CPU uses went high upto 75%.
We previously used Amazon aurora with Multi A-Z deployment and that was hanging on just 8 user testing. We then change it to MySQL RDS, its working fine (Just for 5 user testing for now), as response time was still better but the CPU uses was going to alarming limit (75%). We identify that there are many write operation happening during the testing (almost 80-100 write OPs per second), that may be the reason of DB server consuming so much CPU.

Can you suggest a specific configuration for the DB server so that it can work normally without consuming too much CPU? and any way to reduce the no. of write operations.

Chamilo version: 1.11.4

Thanks,
Paras

**Comment by ywarnier** [comment]
Hi @jainpm1 
1.11.4 had a few missing indexes. Did you check the optimization.html page in the documentation folder of your Chamilo? This might provide a few elements to boost your queries. However, this should mostly be about read queries, not write queries, so not sure this will help, but keep us informed (optimization.html has a few queries to add indexes).

**Comment by jainpm1** [comment]
Hi @ywarnier ,

I'll check and import optimization suggestions however, for now, my question is specific to write queries. I'm having almost 88 write queries per second on RDS log with just 5 users testing on Learning path. The issue is specifically with so many write operations happening without that much user interactivity. Do you know what exactly is getting written in DB? I've contacted AWS support for the same and will be creating a separate query log shell script to identify which queries are written there. But do you know why so many write queries executing for 5 users in single page load? and any way to reduce that? I can see the Read operations for the same time, and it is going 1 or 2 read operation per second only.

Thanks,
Paras

**Comment by ywarnier** [comment]
Each page load generates a series of DB writes. These are mostly to let Chamilo know that the user entered a new page (a "log" registered in the track_e_course_access tables). Other operations might include writing in the global chat (if that's enabled on your portal) but 88 queries/s seems high, indeed.
The learning paths tool is an exception as it has to register a series of stuff sent by SCORM content (which has the ability to generate more queries in Chamilo and is built independently from Chamilo), but you didn't mention you used one of those.
Most queries should be read queris, in almost all cases.

**Comment by jainpm1** [comment]
Ah ok, the issue was with indexing only and the no. of queries written in DB is not 88/second (My bad), its 88 per min with 3 users. The optimization technique worked for me and now the DB query time is reduced to 2-3 miliseconds only.

Thanks for your help.
