### ISSUE TITLE
Received marker in global chat

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2579]
### Current behavior

In the global chat (still a little beta), there is no way to know if the other person has received the message.

### Expected behavior

When the message is actually *printed* inside the chat window of the destinatory user, register the fact that the message was received, and show it back on the sender's chat window as a small check mark.

### Steps to reproduce

Make a friend
Enable global chat
Send a message

### Chamilo Version

1.11.x 20180709

**Comment by NicoDucou** [comment]
This as been included in Chamilo 1.11.x in may 2019 so I'm closing this task
Reference BT#15177
