### ISSUE TITLE
Very first global chat messages do not get to destination

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2581]
### Current behavior

As a user who never used the global chat
I add a friend (invite+accept) who's already connected to the global chat
I go to my friends list in social network
I click my friend's name
I click my friend's "Chat (Connected)" link
(here the global chat tab automatically passes from disconnected to connected and a new chat box appears and I'm connected)
I write two messages
These messages do not appear to my friend
I stay on the same page
I close the chat box
I disconnect the global chat
I reconnect the global chat
I click on the "Chat (Connected)" link of my friend again
The chat box appears
I write a message
My friend receives all 3 (2+1) messages immediately

### Expected behavior

My friend should receive my messages immediately.

### Chamilo Version

Chamilo 1.11.x 20180709

**Comment by ywarnier** [comment]
I believe this was fixed in 1.11.12... @AngelFQC can you confirm?

**Comment by AngelFQC** [comment]
I sent two messages to my friend in social network and he received them (almost) immediately

**Comment by NicoDucou** [comment]
This was fixed and some enhancement have been done to show a check to indicate that the message has been sent and a double check to indicate that the message has been received by the friend and in blue when viewed.

So closing this issue.
