### ISSUE TITLE
Definición/corrección de permisos 0777 en archivos y carpetas

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2582]
### Current behavior / Resultado actual / Résultat actuel

Hemos observado que aunque Chamilo tiene en la administración dos opciones para indicar los permisos para los nuevos directorios y archivos (/main/admin/settings.php?category=Security), en algunas partes del código hay definidas llamadas a carpetas con permisos 0777 cuando se crean o se modifican, lo que supone un problema de seguridad.

### Expected behavior / Resultado esperado / Résultat attendu

El código debería tomar los permisos definidos en la administración o bien de algún parámetro insertado en el archivo app/config/configuration.php para unificarlo en todo sitio como

// Permisos para los nuevos directorios
$_configuration['directorypermissions'] = '0700';
o
$_configuration['directorypermissions'] = '0755';
### Chamilo Version / Versión de Chamilo / Version de Chamilo

Chamilo 1.11.x

**Comment by ywarnier** [comment]
Hola @nosolored 
Podrías dar referencias de donde existen estos lugares? Acabo de hacer una búsqueda y los únicos que encuentro son parte de vendor/, que no está bajo nuestro control.

**Comment by nosolored** [comment]
Hola @ywarnier 

Nombre fichero: línea donde se muestra

`app/bootstrap.php.cache:2759:if (false === @mkdir($dir, 0777, true) && !is_dir($dir)) {
main/inc/lib/security.lib.php:320:                mkdir($cache_dir, 0777);
main/inc/lib/certificate.lib.php:157:                mkdir($path_info, 0777, true);
main/inc/lib/certificate.lib.php:160:                mkdir($this->certification_user_path, 0777);
main/inc/lib/api.lib.php:5116:        $permissions = octdec(!empty($permissions) ? $permissions : '0777');
main/inc/lib/phpseclib/Net/SFTP.php:1178:        $attr = pack('N2', NET_SFTP_ATTR_PERMISSIONS, $mode & 07777);
main/inc/lib/phpseclib/Net/SFTP.php:1354:        $attr = $mode == -1 ? "\0\0\0\0" : pack('N2', NET_SFTP_ATTR_PERMISSIONS, $mode & 07777);
main/lp/openoffice_document.class.php:126:            @chmod($this->base_work_dir, 0777);
main/lp/openoffice_document.class.php:127:            @chmod($this->base_work_dir.$this->created_dir, 0777);
main/lp/openoffice_document.class.php:128:            @chmod($this->base_work_dir.$this->file_path, 0777);
main/lp/openoffice_document.class.php:161:            chmod($this->base_work_dir.$this->created_dir, api_get_permissions_for_new_directories());
main/lp/openoffice_document.class.php:166:                    @chmod($image_path.'/'.$image, 0777);
main/lp/openoffice_document.class.php:190:            chmod($this->base_work_dir, api_get_permissions_for_new_directories());
main/lp/openoffice_document.class.php:242:            @chmod($this->base_work_dir, $permissionFolder);
main/lp/openoffice_document.class.php:243:            @chmod($this->base_work_dir.'/'.$this->file_path, $permissionFile);
main/lp/openoffice_document.class.php:253:            @chmod($this->base_work_dir.'/'.$this->created_dir, $permissionFile);
main/lp/openoffice_document.class.php:282:            chmod($this->base_work_dir.$this->created_dir, api_get_permissions_for_new_directories());
main/lp/openoffice_document.class.php:287:                    @chmod($image_path . '/' . $image, 0777);
main/cron/import_csv.php:2969:    $command = "sudo find ".api_get_path(SYS_COURSE_PATH)." -type d -exec chmod 777 {} \; ";
main/cron/import_csv.php:2973:    $command = "sudo find ".api_get_path(SYS_CODE_PATH)."upload/users  -type d -exec chmod 777 {} \;";
plugin/vchamilo/lib/Virtual.php:607:            mkdir($tempDir, 0777, true);
plugin/vchamilo/lib/Virtual.php:1284:            mkdir($courseDir, 0777, true);
plugin/vchamilo/lib/Virtual.php:1317:                if (!mkdir($dir, 0777, true)) {
plugin/vchamilo/install.php:77:    mkdir($_configuration['root_sys'].'plugin/vchamilo/templates', 0777, true);
plugin/vchamilo/views/manage.controller.php:135:            $result = mkdir($backupDir, 0777, true);
plugin/vchamilo/views/manage.controller.php:150:                mkdir($absolute_datadir, 0777, true);
plugin/vchamilo/views/manage.controller.php:151:                mkdir($absolute_datadir.'/home', 0777, true);
plugin/vchamilo/vcron.php:44:    mkdir($_configuration['root_sys'].'plugin/vchamilo/log', 0777, true);
plugin/pens/pens.php:38:            mkdir($path_to_archives, 0777, true);`

**Comment by ywarnier** [comment]
Por alguna razón no me salían con una búsqeda sencilla, pero sí veo, y por lo visto la mayoría (si no todos) pueden ser modificados para usar los permisos de la base de datos. Solo el phpseclib parece un poco complicado.

**Comment by ywarnier** [comment]
Con estos dos cambios debería estar todo bien. El único que no cambié es el de la librería FTP porque es librería externa y para ser sincero no creo que se usen estos métodos dentro de Chamilo (he buscado, no encontré).

Por favor su aprobación para cerrar el issue...

**Comment by nosolored** [comment]
Muchas gracias @ywarnier por las modificaciones.

He localizado en 
main/lp/openoffice_document.class.php:290:                    @chmod($image_path . '/' . $image, 0777);
main/install/install.lib.php:978:    $perms_dir = [0777, 0755, 0775, 0770, 0750, 0700];
main/install/install.lib.php:981:    $dir_perm_verified = 0777;
main/install/data.sql:99:('permissions_for_new_directories', NULL, 'textfield', 'Security', '0777', 'PermissionsForNewDirs', 'PermissionsForNewDirsComment', NULL, NULL, 0),
main/inc/lib/api.lib.php:5122:        // The default value 0777 is according to that in the platform administration panel after fresh system installation.
main/inc/lib/api.lib.php:5123:        $permissions = octdec(!empty($permissions) ? $permissions : '0777');

Saludos.

**Comment by ywarnier** [comment]
Los de main/install/ van a quedar, porque a este punto no existen los parámetros de base de datos que permiten obtener los permisos a setear.
Lo de openoffice está en un comentario. Lo de api.lib.php también, salvo el último que es un valor por defecto de la misma función api_get_permissions_for_new_directories().

Gracias por la revisión. Ahora cierro la tarea.

**Comment by esef4** [comment]
ywarnier, me podrás contactar para asesoramiento privado? esef4@hotmail.com o +542664564435

**Comment by ywarnier** [comment]
@esef4 trabajo para la empresa BeezNest: https://beeznest.com/ No hago asesoramiento privado, lo siento. Recomiendo edites tu post anterior para eliminar tu correo y tu teléfono. Son datos abusados en estos canales públicos.
