### ISSUE TITLE
Define a global JS confirmation() function

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2584]
### Current behavior

To avoid an immediate deletion of an item, we use a small "confirmation()" function in JavaScript, that we often create through a simple added JS header, like this:
```
        global $htmlHeadXtra;
        $htmlHeadXtra[] = "<script>
        function confirmation(name) {
            if (confirm(\" ".trim(get_lang('AreYouSureToDeleteJS'))." \"+name+\"?\")) {
                return true;
            } else {
                return false;
            }
        }
        </script>";
```
This code for the confirmation function is repeated at least 23 times through Chamilo's code, while it could just be added once, in a generic Chamilo JS file loaded on every page.

### Expected behavior

Have a generic "chamilo.js" in which we put at least this very broad function.
Ideally, we could also add an association with a specific class (CSS class="chamilo-delete-confirmation") to all elements that require a confirmation, then add a document event to catch the "onclick" event on those.

### Chamilo Version

1.11.x 20180710

**Comment by ywarnier** [comment]
@jmontoyaa no querrás tomar esta?

**Comment by jmontoyaa** [comment]
A ver ... hay 2 issues aquí, lo de confirmation() y el otro el de mover código js en chamilo.js
Para lo primero si lo puedo hacer, para lo segundo si se quiere hacer se tiene que ver que sea "compatible" con chamilo v2.

**Comment by jmontoyaa** [comment]
Y como es una creación de nuevo archivo no sé si sea bueno ponerlo a 1.11.x

**Comment by ywarnier** [comment]
La creación de nuevos archivos no causa problemas. Lo que los causa es el movimiento de archivos (porque al aplastar el código, quedan los en la anterior ubicación).
El issue 2 de mover otro código JS en chamilo.js es para otro día, lo puedes ignorar, pero sí me gustaría que por lo menos exista ya el chamilo.js (con confirmation()) en el lugar que tu creas más conveniente (por eso te pedía) y en el orden más correcto dentro de la carga de archivos .js en el header, y de ahí moveremos cosas en este achivo progresivamente.

**Comment by ywarnier** [comment]
Ooooooooooh! Woaaaaaw! Que limpio quedó mi fuente de index.php!!!! :heart_eyes: 
OK, el showConfirmationPopup() está bien pero solo funcionaría para documentos porque checkea info de documentos, no?
Yo hablabla de la función confirmation(), pero veo que también hay llamadas directas a confirm() que es una función JavaScript del mismo lenguahe, y llamadas a showConfirmationPopup(). Debemos intentar uniformizar esto, pero con el trabajo ya hecho ahora me parece que ya tenemos un buen paso hecho y podríamos trasladar la uniformización a la versión 2.0.

Un problema: el main.js que se genera, se genera en el idioma del que lo carga por primera vez. Hay una decena de strings de confirmación que aparecen en el main.js.
Estuve pensando en como solucionar esto, y creo que lo más correcto es hacer distintas versiones de main.js, una para cada idioma, con el isocode del idioma: main.en.js, main.fr.js, main.es.js, etc.

**Comment by ywarnier** [comment]
This fixes the language issue. I'm closing this task now. Well done! Let's keep a watch on this to see if it breaks anything, and try to move a few more stuff in there to reduce the size of the HTML file sent to the user even further.

As  a result of this optimization, the weight of the pure HTML file generated for the dashboard page (the page with the less elements of all the main tab pages) passed from 11.36K to just 4.86K (saving 6.5K on the first page load). While this does not affect the total load of the page, this is certainly a huge improvement for speed testing, for one because it allows web/build/main.[language].js to be stored in cache, and on the other side because it allows the PHP pages to be handled to the user faster, already showing them data before the full page is loaded.

Excellent job on this!

The next step on the optimization side will be to concatenate all JS files (currently 19 files before main.js), to enable caching and transferring of one single file.

**Comment by jmontoyaa** [comment]
It should impact performance too, because twig won't be called every time to generate that js code at every call, just only once when the js file is created.

**Comment by jmontoyaa** [comment]
About your last commit, we should use iso code to load the js code, en.js, es.js, instead of the full name "todo".
