### ISSUE TITLE
Certainty degree question icon and styles

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2593]
Review styles and regenerate SVG icon and all sizes for certainty degree questions. See certainty branch.

**Comment by ywarnier** [comment]
```
git checkout -b certainty
git pull origin certainty
```
https://github.com/chamilo/chamilo-lms/tree/certainty
The icons are mccert.png (for example main/img/icons/64/mccert.png)

**Comment by aragonc** [comment]
Se agrego el icono solicitado y adicional  los iconos que faltan en escala de grises de las demás herramientas de preguntas cuando se usa el modo SVG

**Comment by ywarnier** [comment]
Perfecto, gracias!
