### ISSUE TITLE
travis-ci: sun java 8 cannot be downloaded

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2594]
There's an issue with the builds on travis since yesterday: the java 8 installer can apparently not download Java, and the build gets broken right there.

I tried updating Ubuntu to bionic (18.04) and xenial (16.04).
Bionic failed for the same reasons, but xenial seemed to work and then failed on launching chromedriver.

I think that's because Oracle removed the download of Java 8 from their site.
You can check the travis reports here:
 - 14.04: https://www.travis-ci.org/chamilo/chamilo-lms/builds/405106823
 - 16.04: https://www.travis-ci.org/chamilo/chamilo-lms/jobs/405127985
 - 18.04: https://www.travis-ci.org/chamilo/chamilo-lms/builds/405127238

**Comment by jmontoyaa** [comment]
There's a message in travis after I logged in:

> Dynamic Oracle JDK installations are currently unavailable due to a problem with our upstream provider. In the meantime, container-based builds come with JDKs preinstalled.

**Comment by jmontoyaa** [comment]
Travis builds are working now.
