### ISSUE TITLE
Fatal error: can't use function return value in write context in /var/www/html/chamilo/main/inc/lib/api.lib.php on line 1772

### ISSUE THREAD

**Issue by akshaybande81** [chamilo/chamilo-lms#2597]
Hello, 

I am getting the following error while installing chamilo version 1.11.6. 

Fatal error: can't use function return value in write context in /var/www/html/chamilo/main/inc/lib/api.lib.php on line 1772

**Comment by jmontoyaa** [comment]
The 1.11.x branch requires PHP 5.5, probably you're using php 5.3 or 5.4

**Comment by akshaybande81** [comment]
Thank you.

I have updated my php to 7.2 still it says same.

**Comment by akshaybande81** [comment]
Thank you

**Comment by ywarnier** [comment]
I'm closing this. This has also been answered (in a longer way) here https://stackoverflow.com/questions/51420262/fatal-error-cant-use-function-return-value-in-write-context-in-var-www-html-c/51460243#51460243
