### ISSUE TITLE
Internal: UserRepository exists twice

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2599]
There are two UserRepository classes:
 - \Chamilo\UserBundle\Repository\UserRepository
 - \Chamilo\UserBundle\Entity\Repository\UserRepository

From checking it quickly, it looks like the one in \Chamilo\UserBundle\Entity\Repository\UserRepository is used more often, but I think it is confusing to have 2. PHPStorm certainly gets confused with that.

Shouldn't we remove one and only leave the other one? Would that imply a change to the database?

**Comment by jmontoyaa** [comment]
Interesting! Good eye! There should be only one. I will fix it. No database changes are needed.

**Comment by ywarnier** [comment]
Are you sure this is the correct direction?
In CoreBundle and CourseBundle, the Repository folder is *inside* the Entity folder:
 - Chamilo/CoreBundle/Entity/Repository/
 - Chamilo/CourseBundle/Entity/Repository/

So we are in doubt here...

**Comment by jmontoyaa** [comment]
Yes, It should be "Chamilo\UserBundle\Repository\UserRepository", according to Symfony:

https://symfony.com/doc/3.4/doctrine/repository.html

I will make some changes, but better to wait for Chamilo v2?

**Comment by ywarnier** [comment]
Yes, wait for v2!
