### ISSUE TITLE
Improve CSS for certainty degree questions

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2600]
- change colors
 - move CSS from MultipleAnswerTrueFalseDegreeCertainty.php to base.css
 - improve the presentation of HTML table (colors and borders)

**Comment by aragonc** [comment]
![ddd](https://user-images.githubusercontent.com/2940509/43107147-4f23fdfc-8ea1-11e8-85e6-5bd43facdc58.png)
Enviado la nueva vista

**Comment by ywarnier** [comment]
Me parece bien. Aprobado.
