### ISSUE TITLE
Install: different way to check app/courses/ is writeable

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2601]
### Current behavior

When installing, a test directory is created in app/courses/_XxTESTxX_ (+ a file "test.php" in it) to check if we have the right permissions and if the file is accessible and executable through the web.
However, this is now getting blocked by the recommended security settings in documentation/security.html which prevent execution of PHP from app/courses/

### Expected behavior

In recent versions, it is not necessary anymore to execute PHP code from app/courses, so the check of execution doesn't make sense anymore either.
We should only check the creation of the directory and access to a simple .html file.

### Steps to reproduce

 - configure security settings from security.html
 - restart web server
 - try to install chamilo
 - creation of test dir fails (because of check_course_script_interpretation() in install.lib.php)

### Chamilo Version

1.11.x 2018-07-21

**Comment by jmontoyaa** [comment]
I confirm the bug, it should be fixed now.

**Comment by ywarnier** [comment]
Looks all good to me. Tested and approved. Thanks!
