### ISSUE TITLE
Si tiene el mismo problema

### ISSUE THREAD

**Issue by AulaBit** [chamilo/chamilo-lms#2603]
Tengo el mismo problema. como se puede solucionar? al parecer veo todo correcto la ruta pero cuando trata de poner una imagen no me deja.

**Comment by ywarnier** [comment]
Este reporte es totalmente inútil. Por favor respetar el formato de plantilla de reporte, sino no podemos ayudar de ninguna manera. Existen por lo mínimo 10 herramientas en las cuales se pueden subir imágenes, por lo que un reporte tan corto no nos permite identificar el problema.
Ver formato de plantilla, incluyendo versión de Chamilo.
