### ISSUE TITLE
Problemas con postear imagenes en cursos

### ISSUE THREAD

**Issue by AulaBit** [chamilo/chamilo-lms#2604]
Saludos, 
Necesito que me ayuden con lo siguiente:
Tengo un inconveniente con poner imágenes dentro de la cabecera de un curso o con cargar las mismas.
Datos:
- chamilo-1.11.6-php7 y php5 | chamilo-lms-1.11.4 (intente con estas dos versiones en localhost pero sucede lo mismo).
- Wampserver64 (instalado en el disco D), y todo aparentemente esta bien con figurado.

Lo que sucede es un tema de enrutamiento. No sale la ruta completa a la hora de cargar la imagen y postear la imagen.

En esta primera imagen se puede ver que en la carpeta "mis archivos" a la hora de subir una imagen esta carga un icono pequeño de previsualización y si le doy clic derecho y doy en abrir archivo me abre la imagen con toda la url completa (http://localhost/chamilo/app/upload/users/1/1/my_files/img/av.png)
![chamilo inconveniente curso 1](https://user-images.githubusercontent.com/38405735/43051874-31b895b4-8de5-11e8-8944-5e86701f9ab2.JPG)

Sin embargo en la segunda imagen dentro la carpeta de un curso, creo una carpeta "imagenes" ahi dentro pongo la misma imagen y esta no carga su icono pequeño y cuando trato de abrirla me sale error, y me percato que la url no esta completa.
![chamilo inconveniente curso 2](https://user-images.githubusercontent.com/38405735/43051945-04d9597e-8de6-11e8-8b1f-171262d9b7ac.JPG)

Este inconveniente es similar al siguiente:
[https://github.com/chamilo/chamilo-lms/issues/2065](url)
Ya verifique que este bien configurado y esta en la raiz,
D:\wamp64\www\chamilo
\www\chamilo\app\config\configuration.php

Yo creo que este inconveniente tiene que ver con algun parametro (archivo.php?) que dentro tenga que configurar, sin embargo no se cual podria ser.
Y este problema me sucede tanto en las ultimas version de chamilo y es mas tambien lo provee en un servidor y me sale el mismo problema

Referencias:
https://forum.chamilo.org/viewtopic.php?f=15&t=10673

Desde ya agradezco su tiempo por la ayuda.
Gracias

**Comment by jmontoyaa** [comment]
Como estás cargando tu portal desde un directorio debes de agregar esta configuración:

En configuration.php

`$_configuration['url_append'] = 'chamilo';`

Lo recomendable es instalar chamilo en una URL.

**Comment by ywarnier** [comment]
Might be loosely related to #2586

**Comment by AulaBit** [comment]
Si bien el inconveniente con visualizar imagenes se soluciona, solo es para la vista con el profesor, cuando trato de ver con la vista de estudiante este ya no se aprecia,
Segun vi en otros lugares hay que cambiar unos permisos a unas carpetas del sistema en seguridad:
referencia:
https://beeznest.com/es/2012/04/21/problemas-al-crear-cursos-en-chamilo-despues-de-la-instalacion-error-500/

Permisos para los nuevos directorios (0755)
Permisos para los nuevos archivos (0644)
pero aun poniendo esos valores y verificando que esten con el ojito marcado para el alumno no se ven las imagenes. Yo cree una carpeta "imagenes" dentro del curso a traves de su interfaz grafica para folders, pero aun asi no se puede visualizar con la vista alumno y nada. Incluso  cree una cuenta de estudiante y nada.

**Comment by ywarnier** [comment]
Los permisos probablemente no tengan que ver. El problema de permisos de alumnos surge en general cuando usas imágenes de un curso B dentro de tu curso A. Si los alumnos tienen acceso al curso A pero no al curso B, por protección de recursos no podrán visualizar las imágenes correspondientes al curso B.

**Comment by ywarnier** [comment]
Sin seguimiento desde más de 1 año y por nuestra parte se trata de un problema de configuración.
