### ISSUE TITLE
Corregir funcionamiento de setting gradebook_detailed_admin_view 

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2609]
### Current behavior / Resultado actual / Résultat actuel
En la vista de estudiante de la herramienta de Evaluaciones, por defecto no deberían verse las columnas _Clasificación_, _Mejor calificación_ ni _Promedio_ por defecto, ya que el parámetro de configuración `gradebook_detailed_admin_view` está deshabilitado por defecto desde la instalación. Pero este parámetro de configuración sólo funciona en la vista plana de evaluaciones y no tiene efecto sobre la vista de estudiante de evaluaciones.

También hay una variable de configuración `disable_gradebook_stats` (3fe40cafab07d9b31205072fa32532ab18411417) que oculta las columnas _Promedio_ y _Clasificación_, dejando sólo la columna de _Mejor calificación

Por lo que éstas dos entran en conflicto.

### Expected behavior / Resultado esperado / Résultat attendu
Por defecto no se deberían mostrar ninguna de las 3 columnas mencionadas arriba.
Si se habilita `gradebook_detailed_admin_view` se deberían ver las 3.
Habilitar otra variable de configuración para sólo mostrar la columna de _Mejor calificación_

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Ir a parámetros de configuración y comprobar el funcionamiento según la descripción de `gradebook_detailed_admin_view`. Habilitarla y probar vista de estudiante estudiante. Deshabilitarla y probar vista de estudiante estudiante.
Editar configuration.php y habilitar `disable_gradebook_stats`. 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
@jmontoyaa y @NicoDucou, para los portales que hayan usado este parámetro `disable_gradebook_stats`, será necesario aplicar el cambio a mano al momento de actualizarlos luego de la 1.11.8.

**Comment by ywarnier** [comment]
@NicoDucou please review this at the application level and let us know if it looks like what is expected, for example for FormaSc.

**Comment by NicoDucou** [comment]
Todo esta foncionando como @AngelFQC lo ha indicado, pero creo que eso va a ser un problema para los usuarios porque : 
Antes de los cambios de esta tarea, el parametro  `gradebook_detailed_admin_view` no estaba funcionando correctamente, es decir que aun estaba en "no" por defecto, se estaban monstrando las columnas de posicion, mejor resultado y promedio. Entonces cuando una plataforma va a ser actualizada de pronto las columnas van a desaparecer. Por ejemplo por FormaSc que estan usando estas columnas al momento de actualizar haria que ir a poner este parametro en "Si" sino las columnas van a desaparecer. Por este plataforma sabemos que usan estas columnas entonces lo podemos gestionar pero por otros van a ser sorpredidos que desapareciara estas columnas.

El funcionamiento propuesto por Angel es mas logico y permite reducir la carga en el servidor por defecto en lo que estas columnas estan desabilitadas por defecto asi que me parece bien, pero no se si el hecho de soprender porque desaparecen las columnas va a ser mas problematico.

Yo creo que si las plataformas usan estas columnas van a encontrar el parametro de configuracion para activarlas. Tal vez hacer una nota especifica en el changelog sobre esto.

@ywarnier que prefieres ?

**Comment by ywarnier** [comment]
Ya lo había conversado con Angel para llegar a la decisión que era mejor corregir este comportamiento erróneo de una vez. Acabo de mandar un commit para indicarlo en "Possibly breaking changes". Como conversado ayer con @NicoDucou no conocemos de portales que usen específicamente este parámetro, pero estamos listos para atender las consultas al respecto.
