### ISSUE TITLE
How to Modify GUI

### ISSUE THREAD

**Issue by shubham-matale** [chamilo/chamilo-lms#2610]
How can i Design my own GUI for Chamilo. Not from the provided tool. But from the CSS files. Or Can you tell me which files need to be modified to change GUI

**Comment by ywarnier** [comment]
Hi @shubham-matale 
You can find information about CSS and TPL in our developer guide: https://docs.chamilo.org/en/ (just scroll down to the bottom of the table of contents and scroll back up 2 pages and you should see "Theming through templates" and "Theming through CSS". These are relatively short reads and should give you the basic tools to do that.
Let us know how that works out for you.

**Comment by ywarnier** [comment]
Considering the lack of follow-up from your side, I consider this issue closed.

**Comment by nathnaelmogesk** [comment]
the link on top doesn't work.use https://docs.chamilo.org/developer-guide/theming_through_templates
