### ISSUE TITLE
CKEditor not appearing in 1.11.8 beta fresh install

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2617]
When installing 1.11.8 beta package on a PHP 7.2 VM, CKEditor does not appear and I get the following error message.
Should I do something more in preparing the package?

![ckeditor-invisible](https://user-images.githubusercontent.com/609839/43691790-ce60dc62-98e6-11e8-8d1e-8a4c659a8b28.png)

**Comment by AngelFQC** [comment]
I got this message in error log
```
[Mon Aug 06 18:40:31.786833 2018] [php7:notice] [pid 21319] [client 190.117.161.191:59372] Error: /var/www/chamilo/www/app/config/auth.conf.php could not be written. Please check permissions. The web server must be able to write there., referer: http://test72.localhost/
```
With the build file for php 7.2 the main.$language.js file is not created.

With the recent changes on global.inc.php it was fixed

0683b23602b5fd0505e4d96442f573095c299597
cb48bbd5819e7cdb90784a1291df53355997042e
178dfb909152f166cf40d967007469f71ed4ec34

**Comment by ywarnier** [comment]
It's mostly https://github.com/chamilo/chamilo-lms/commit/178dfb909152f166cf40d967007469f71ed4ec34 that fixed it. Thanks. Beta 2 works straight away.
