### ISSUE TITLE
time() used in Exercise::is_visible()

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2618]
This section of the code uses time()

https://github.com/chamilo/chamilo-lms/blob/000f4032bf8fbfa0e9ae961b39afe166aedee6ef/main/exercise/exercise.class.php#L6230

And later compares the generated time with a time in UTC.
In the case the local server is configured in another timezone than UTC, we are adding an undesired timeshift in the comparison.

time() should be replaced by some form of api_get_utc_datetime()

**Comment by carlangas159** [comment]
Line change 6534

<pre>
if ($limitTimeExists) {
            $timeNow = time();
            $existsStartDate = false;
            $nowIsAfterStartDate = true;
            $existsEndDate = false;
            $nowIsBeforeEndDate = true
</pre>

**Comment by carlangas159** [comment]
By @AngelFQC 's recommendation, it is better to change the time () by api_get_utc_datetime () therefore the time () would be changed in this file

**Comment by ywarnier** [comment]
Yes, exactly as I suggested above :wink:

**Comment by AngelFQC** [comment]
Citando a @jmontoyaa 
> time(); ya retorna UTC, porqué cambiarlo?

En https://www.php.net/manual/en/function.time.php#100220 se indica que time() es independiente de la zona horaria

**Comment by carlangas159** [comment]
> 
> 
> Citando a @jmontoyaa en [800501b#commitcomment-44909606](https://github.com/chamilo/chamilo-lms/commit/800501bb1e408b9dcf0e6cc88deb887a674a7ab6#commitcomment-44909606)
> 
> > time(); ya retorna UTC, porqué cambiarlo?
> 
> En https://www.php.net/manual/en/function.time.php#100220 se indica que time() es independiente de la zona horaria

Lo que comenta julio es que time devuelve un int, en cambio api devuelve un string a modo 'Y-m-d H:i:s'. 

La intencion es hacer un standar para tiempo a api_get_utc_datetime(). Por los momentos espero la resolucion de esta duda para mandar el pr. Ya que si se usa como string podria dar fallos en acciones posteriores

**Comment by ywarnier** [comment]
As noted by @jmontoyaa, `time()` indeed returns a UTC time, making this issue useless. The confusing part is that `date(time())` will return different dates depending on the timezone configured in PHP.
