### ISSUE TITLE
Session about page doesn't show course description properly

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2619]
### Current behavior / Resultado actual / Résultat actuel
If course descriptions are filled in base course, the about page show these. But if there are descriptions filled in session course then the base course descriptions are ignored.

### Expected behavior / Resultado esperado / Résultat attendu
Show both descriptions (from base and session course)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Fill course description in base course
Create a session with this course and see its about page
Fill course descriptions in session course and see its about page

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
Given you reported it, you can also close it yourself if you believe this fixes it.
