### ISSUE TITLE
ERROR 500 al crear curso despues de instalar Chamilo 1.11.6

### ISSUE THREAD

**Issue by R0sy** [chamilo/chamilo-lms#2621]
Hola, tengo un problema recientemente en un hosting he instalado la versión 1.11.6 de chamilo la instalación no presenta problemas ni nada por el estilo, pero una vez que tengo la plataforma y creo un curso me aparece el siguiente error. 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, webmaster@campusvirtual.epdemexico.mx and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
Apache Server at campusvirtual.epdemexico.mx Port 80
 
Ya modifique los permisos de las carpetas como lo mencionan en los foros, pero el error persiste, me podrían apoyar indicandome si tengo que configurar algo más?

**Comment by ywarnier** [comment]
Hola @R0sy, como explicado por otro canal, esto usualmente trata de un problema de configuración de servidor, en particular de permisos en las carpetas correspondientes. 
La mejor referencia para esto es https://beeznest.com/es/2012/04/21/problemas-al-crear-cursos-en-chamilo-despues-de-la-instalacion-error-500/

**Comment by R0sy** [comment]
Hola, ya he verificado esas cuestiones de los permisos los he cambiado e incluso he creado cursos después de los cambios pero el error persiste, no sé si tenga que hacer alguna otra configuración dentro de la plataforma para que pueda visualizar mis cursos creados. 
También revisando la información de los cursos que me creo estos no tienen index php, eso también puede ser una causa del porque no puedo visualizarlo??
De antemano agradezco por su ayuda.

**Comment by ywarnier** [comment]
El hecho que no exista el index.php está cubierto por el .htaccess a la raíz del sitio.
El .htaccess y su proceso de activación están ámpliamente explicado en el manual de instalación de Chamilo aquí: https://campus.chamilo.org/documentation/installation-guide.html (que también aparece como enlace en las páginas del instalador de Chamilo).
El .htaccess o alguna alternativa a nivel de la configuración del servidor web es imprescindible a la instalación de Chamilo desde la versión 1.11.0 publicada en octubre del 2016.

**Comment by wollmanmq** [comment]
Si no han podido solucionar ese problema, revisen dentro de los archivos que instalaron en el server una carpeta llamada chamilo 1.XX (XX  es la version, puede variar según la instalada) dentro de ella hay un archivo .htaccess el cual deben mover a la carpeta principal de la plataforma chamilo, y listo﻿.

**Comment by ywarnier** [comment]
Problema de configuración. Sin seguimiento desde más de un año. Cerrando.

**Comment by migsauceda** [comment]
A mi me pasó ese error 500 en la versión 1.11.10 al seleccionar al momento de la instalación como idioma de la aplicación "Español latino", los primeros signos de algún error es que no sale el logo de Chamilo sobre el menú, luego en la ventana "mis cursos" al pulsar el lápiz para agregar una imagen del curso... error 500.
Otro signo de error es cuando en configuración, en el apartado de idioma se presiona el botón "desactivar todos los idiomas excepto el idioma de la aplicación" se desmarcan (ojo cerrado) todos los idiomas.

Lo solucioné instalando de nuevo y seleccionando español como idioma de la aplicación.

Este error es el que me trajo a este post, espero sirva para la version 1.11.12
