### ISSUE TITLE
Can't load site /main/admin/user_list.php

### ISSUE THREAD

**Issue by yourKatharsis** [chamilo/chamilo-lms#2623]
### Current behavior / Resultado actual / Résultat actuel

Get this error when I try to access /main/admin/user_list.php (see screenshot).
![screen](https://user-images.githubusercontent.com/29522268/43913754-3907cb8a-9c06-11e8-86c7-33d92bcca00c.PNG)

"An error has occurred. Please contact the system administrator."

Apache Error Log, when try to access:

`[Thu Aug 09 15:02:19.886284 2018] [:error] [pid 4585] [client localhost:60625] An exception occurred while executing 'SELECT u.id AS col0, u.official_code AS col2, u.firstname AS col3, u.lastname AS col4,  u.username AS col5,\n                    u.email AS col6,\n                    u.status AS col7,\n                    u.active AS col8,\n                    u.id AS col9,\n                    u.registration_date AS col10,\n                    u.expiration_date AS exp,\n                    u.password\n                FROM user u ORDER BY col1 ASC  LIMIT 0,20':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'col1' in 'order clause', referer: http://localhost/main/admin/`

### Expected behavior / Resultado esperado / Résultat attendu

Should show the User List.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Worked fine before I added a new user (teacher) and he creates a course.
I also deleted the user fields "skype" and "LinkedIn".
I added a new field (drop-down).

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.4

**Comment by yourKatharsis** [comment]
Hey Yannick,

thanks for your response. I just start chamilo a few minutes ago and now the page loads. I didn't change anything since Thursday. On Thursday I get the error, without doing something with the columns (not conscious). 

I think I will upgrade to chamilo 1.11.8 in the next days. I started with 1.11.4 cause I read somewhere, that there could be problems with 1.11.8 and PHP7.0.

I'll watch it for a few days and when that happens again, I'll try to find a better reproduction.
Here ist line 205-234 of main/admin/user_list.php

Thanks for your help.

**Comment by ywarnier** [comment]
Part of this query is generated from prepare_user_sql_query() in main/admin/user_list.php but the "order by" part that is at fault is in get_user_data(), where it is not aware that col1 does not exist.
