### ISSUE TITLE
1.11.8 Fresh Installation Error

### ISSUE THREAD

**Issue by mozesj** [chamilo/chamilo-lms#2631]
### Current behavior / Resultado actual / Résultat actuel

![image](https://user-images.githubusercontent.com/24265437/44036149-cd8c4612-9f19-11e8-8df6-ce03df0d47b3.png)

### Expected behavior / Resultado esperado / Résultat attendu
![image](https://user-images.githubusercontent.com/24265437/44038707-09c44db8-9f20-11e8-8e1d-98b9d0fc2b60.png)

Connection Result and Next Button

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
clone git version and install

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

## Operating System
Ubuntu 16.04 Apache 2.4 php 7.0 mariadb 10

**Comment by nosolored** [comment]
Chamilo 1.11.8 
https://github.com/chamilo/chamilo-lms/releases/download/v1.11.8/chamilo-1.11.8-php7.zip

@ywarnier  Has Chamilo been generated in a PHP 7.1 or 7.2 environment?

Installation environment: PHP 7.0 - MySQL 5.6 - 5.7

Error: 

Fatal error: Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned in /.../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:67 Stack trace: #0 /.../vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php(152): Doctrine\Common\Annotations\AnnotationRegistry::registerFile('/......') #1 /.../vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Setup.php(71): Doctrine\ORM\Configuration->newDefaultAnnotationDriver(Array, false) #2 /.../main/inc/lib/database.lib.php(771): Doctrine\ORM\Tools\Setup::createAnnotationMetadataConfiguration(Array, true, '/......', NULL, false) #3 /.../main/inc/lib/database.lib.php(145): Database::getDoctrineConfig('/...') #4 /.../web in /.../vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 67

**Comment by ywarnier** [comment]
It was generated in a PHP 7.2 environment but using composer's trick to fake the PHP version. Apparently that wasn't enough. I will be re-packaging in the next few hours.

**Comment by ywarnier** [comment]
In 7.1 and 7.2 it works fine, as far as the reports that have come to me until now. Will update this task as soon as it is re-packaged.

**Comment by nosolored** [comment]
Okay. We will perform tests. Thank you very much.

**Comment by nosolored** [comment]
With the github version https://github.com/chamilo/chamilo-lms/tree/1.11.x and PHP 7.0.31/MySQL 5.7 it works correctly.

**Comment by ywarnier** [comment]
Versions for PHP 5.6 have been uploaded again too.

**Comment by ywarnier** [comment]
OK, I have tested both those new .tar.gz versions in their respective expected version of PHP (5.6 and 7.0) and everything worked fine. I'm waiting for your review but I consider it enough to start announcing the release.

**Comment by ywarnier** [comment]
@mozesj please download again from the "releases" page (the file with the php version in its name) and let us know if that solved the issue. Sorry about the packaging error and I hoe you enjoy Chamilo from now on.

**Comment by mozesj** [comment]
@ywarnier it works! the installation completed successfully
