### ISSUE TITLE
Restaurar medialement.js y plugins

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2634]
### Current behavior / Resultado actual / Résultat actuel
Aparentemente no se puede cargar medialement con yarn. Pero hay una versión no-oficial day-mediaelement. Pero parece que no carga los plugins de vrview y speed

### Expected behavior / Resultado esperado / Résultat attendu
Cargar mediaelement + plugins

### Chamilo Version / Versión de Chamilo / Version de Chamilo

v2

**Comment by ywarnier** [comment]
Looks good to me.
There are still some details around the placing of the player, but this is only very loosely related and I will report them somewhere else.
