### ISSUE TITLE
v2m: Transform CSS to Bootstrap 4

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2636]
By passing to Bootstrap 4, a lot of CSS definitions have to be modified. @aragonc will be taking this in charge.

**Comment by jmontoyaa** [comment]
Some menus are displayed thanks to the "mopa_bootstrap_menu" twig extension. 
I added a fix in order to show the menus properly:

Class Menu/NavBuilder.php

https://github.com/chamilo/chamilo-lms/commit/2c2f4792865e483ddaa5123549a5699d1bc06bff#diff-7743d8cb326c6301cffae57e4d6daeb1R64

**Comment by ywarnier** [comment]
Continued in #2681
