### ISSUE TITLE
v2m: Configuration settings migration

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2637]
*This issue is really a duplicate of #2682 and the development should be registered in #2682, not here*

Move all settings from settings_current and configuration.dist.php (except the ones we don't want to be modified by non-expert admins like multi-url, hosting limits and CDNs) to src/CoreBundle/Settings.

Also, ensure that settings are set to the right *value* upon migration from a previous version.

**Comment by ywarnier** [comment]
@jmontoyaa do you already manage the migration of values from version 1.11.x (both settings_current and configuration.php)? If not, how would that work?

**Comment by jmontoyaa** [comment]
I have to check again (settings_current) now that 1.11.8 is released.

I didn't move values from configuration.php to the new structure, I created a wiki of how to do it:

https://github.com/chamilo/chamilo-lms/wiki/Add-a-new-Chamilo-setting

**Comment by ywarnier** [comment]
Great, thanks!

**Comment by jmontoyaa** [comment]
Migration is not ready yet. I will test the upgrade process.

**Comment by jmontoyaa** [comment]
I just added a fix and now the new settings are added after migration.
Requires testing:

https://github.com/chamilo/chamilo-lms/commit/ea927109c977aa52ce7d6485c40b6aea9a206519

**Comment by ywarnier** [comment]
v2 migration

**Comment by ywarnier** [comment]
Make a list of settings moved and review during migration process

**Comment by ywarnier** [comment]
Duplicate of #2682. Closing.
