### ISSUE TITLE
Erreur function each() deprecated sur 1.11.x

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#2643]
### Current behavior / Resultado actual / Résultat actuel
Function each() deprecated
![ordre alphabetique](https://user-images.githubusercontent.com/24505996/44509964-8ecdaa00-a6b3-11e8-8ff3-7fc4aa93b55e.png)

### Expected behavior / Resultado esperado / Résultat attendu
Pouvoir afficher les exercices hotpotatoes
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Aller sur 
https://11.chamilo.org/courses/ORDREALPHABETIQUE/index.php?id_session=0 puis dans parcours et séance d'exercices 1
### Chamilo Version / Versión de Chamilo / Version de Chamilo
chamilo 1.11.x chamilo 1.11.8 php5 et chamilo 1.11.8 php7

**Comment by ywarnier** [comment]
@jmontoyaa this one should be in "Required testing", right?

**Comment by jmontoyaa** [comment]
Well hotpotatoes won't be available in v2 as far as I remember.

**Comment by Coursenligne** [comment]
Is there something that will replace it as there are some nice exercises in HP :) ?

**Comment by ywarnier** [comment]
Not initially. It is likely HP will be re-integrated later on, but it will not be available in the first release of Chamilo 2.0
