### ISSUE TITLE
Add GraphQL webservices

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2644]
@ywarnier proposed converting services to the REST API.
But there is also the option to integrate GraphQL. Since GraphQL can reduce the response load in each request.

I was working (in free time) to change the current API to GraphQL in 1.11.x (before 1.11.8) https://github.com/chamilo/chamilo-lms/compare/1.11.x...AngelFQC:graphql

https://github.com/overblog/GraphQLBundle seems like a good option, but I have my doubts about how to use a context class to indicate in which course or session the user is currently. And also each type of data should be (re) written in yaml files. overblog's graphql bundle use internally the webonyx/graphql-php (graphql port to php), the same I used for my 1.11.x tests.

ToDo: 
- [x] Authenticate
  - [ ] Get sender ID for push notifications
- [ ] Save GCM Id (for push notifications)
- [x] Get user info
- [x] Get user messages
- [x] Send message to friend
  - [x] Get friends list
- [x] Get user courses
- [x] Get course info
- [x] Get course description
- [x] Get course documents
  - [ ] Allow download files with Rest's api_key
- [x] Get course announcements
- [x] Get course announcement info
- [x] Get course agenda
- [x] Get course notebook
- [x] Get course forum categories
- [x] Get course forums
- [x] Get course forum threads
- [x] Get course learning paths
  - [x] See learning path in browser (with autologin)
- [x] Get user sessions
- [x] Create a course
- [x] Create a user
- [x] Subscribe user to course
- [x] Create a forum thread
- [x] Create forum post
- [x] Create note in notebook

**Comment by jmontoyaa** [comment]
I added a comment here:

https://github.com/chamilo/chamilo-lms/commit/5ffaf25e9ee07a071d37d3a15e56239dabc28cbd

Please avoid the use of Container, and create services.

**Comment by AngelFQC** [comment]
Restore soap files and don't delete them

**Comment by ywarnier** [comment]
@AngelFQC we need to discuss this to see what is missing and how it mixes with the Julio's API

**Comment by jmontoyaa** [comment]
This was added when using Api platform it can be tested now here:

https://2.chamilo.org/api/graphql

https://github.com/chamilo/chamilo-lms/commit/f9226074609f8fdbb852fd32c40bfb68112b1001

In order to query I'm using Vue with the apollo client for example here:

https://github.com/chamilo/chamilo-lms/blob/master/assets/vue/views/user/courses/List.vue#L43-L66

The doctrine entities should be fine tune in order to get the right information.

**Comment by jmontoyaa** [comment]
See also:

https://github.com/chamilo/chamilo-lms/issues/3811

**Comment by AngelFQC** [comment]
@jmontoyaa I think this issue can be closed in favor of the Platform API implementation
