### ISSUE TITLE
Buy Course plugin: disable 3rd party application from downloading video

### ISSUE THREAD

**Issue by mozesj** [chamilo/chamilo-lms#2646]
Hi what approach can i take in disabling 3rd party applications like IDM (internet download manager) from downloading a course video(s)?

**Comment by opensourcecompany** [comment]
Use an external streaming server.

**Comment by ywarnier** [comment]
Our objective with Chamilo is to increase the availability of quality education for all, all around the globe. Restricting access to the free (as in freedom) choice of playing a video on an open software platform goes against that objective.
Restricting the download possibility for a video will inevitably (as has been proven time and time again over the last 15 years-or-so) make it harder for people with less resources or with disabilities to access the videos.

Plus, in the end, anybody that can reproduce the video can always record audio and video flows from where they appear on their own device (put the video in full-screen mode and record it while it is playing), like some people will do with Netflix, for example. If there is a strong motivation to copy your videos, people will always find a way, no matter the protections you put on top.

For these reasons, our philosophy about videos access has always been the following: if you are worried about video download, make sure that the videos are clearly indicated as yours, with clear brand logos or mentions (in-stream) throughout the video pointing at your company or website. This will ensure that, even if the videos are copied, people getting access to your videos will always know who made them and who is the expert, really.

Finally, as @opensourcecompany mentioned, if you really think this is the best solution, use an external streaming server that offers that in a way, but I am personally doubtful any such service can protect your videos completely.
