### ISSUE TITLE
Upgrade from 1.11.6 to 1.11.8

### ISSUE THREAD

**Issue by erhapp** [chamilo/chamilo-lms#2647]
### Current behavior / Resultado actual / Résultat actuel
After copying all 1.11.8 files over the 1.11.6 and emptying the cache folder the version control notice in the admin panel keeps telling me that I'm using 1.11.6

### Expected behavior / Resultado esperado / Résultat attendu

Confirmation that I've upgraded to 1.11.8

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Install and configure 1.11.6. , copy 1.11.8 files over the previous installation

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.6

**Comment by jmontoyaa** [comment]
After you copied the files, you need to change manually the file:

app/config/configuration.php

`$_configuration['system_version'] = '1.11.8';`

**Comment by erhapp** [comment]
Oh, ok.

How do you check that the upgrade was successful?

**Comment by jmontoyaa** [comment]
The upgrade from 1.11.6 to 1.11.8 don't implies database changes, so there's no need to execute an extra step. Simply copy and paste the files and clean/delete the cache files and it should be good to go.

**Comment by erhapp** [comment]
OK. Thank you for the quick reply.

I was hoping to find the GPDR features in 1.11.8. However I was unable to find any new options.

**Comment by jmontoyaa** [comment]
Logging as admin in main/admin/index.php you should have a new block called

"Personal data protection"

https://11.chamilo.org/main/admin/

And as a student you can have access to your data here:

https://11.chamilo.org/main/social/personal_data.php

The demo portal access is admin/admin.
