### ISSUE TITLE
Duplicate results of evaluations in classrom activity

### ISSUE THREAD

**Issue by rbencho** [chamilo/chamilo-lms#2648]
### Current behavior 

Duplicate scores.

### Expected behavior

One score per student

### Steps to reproduce

Create a classrom activity and add results in /gradebook_add_result.

When the results have been added and show /gradebook_view_result, in the browser, click on the back button.

Re-enter notes in /gradebook_add_result.

The results are doubled.

To correct this problem, a validation must be added to verify that there is no result with the same user_id and evaluation_id in the gradebook_result table. And if it exists, you should only modify it and not add a new one.

### Chamilo Version 

1.11.x

**Comment by ywarnier** [comment]
Patch submitted in #4483

**Comment by ywarnier** [comment]
This has been fixed indeed.
There is another issue now recorded in #5231
