### ISSUE TITLE
Erreur 404 accès au cours

### ISSUE THREAD

**Issue by HerouardJ** [chamilo/chamilo-lms#2649]
### Current behavior / Resultado actual / Résultat actuel

Erreur 404 lorsque je dois accéder au fichier /MONCOURS/index.php

### Expected behavior / Resultado esperado / Résultat attendu

Je souhaiterais pouvoir modifier les cours que je crée sans avoir ce type d'erreur

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

J'ai essayé de modifier mon fichier .htaccess en insérant le code _redirect "/courses" "app/courses"_ mais cela me donne désormais une erreur 403

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.8 hébergé sur serveur FTP 1&1 avec base SQL

**Comment by ywarnier** [comment]
Pour que .htaccess soit pris en compte, il faut que la configuration du serveur web le permette (AllowOverride On ou Require all granted, dépendant de la version d'Apache). Est-ce le cas?

**Comment by ywarnier** [comment]
Pour que .htaccess soit pris en compte, il faut que le serveur web le permette (à un niveau supérieur). Si vous ne savez pas de quoi il s'agit, pourriez-vous contacter votre hébergeur pour lui demander si c'est le cas? (voir mon message précédent)

**Comment by HerouardJ** [comment]
Bonjour,

Mon hébergement est prévu pour accepter les fichiers .htaccess

**Comment by HerouardJ** [comment]
Bonsoir,

Mon application est hébergé sur l'adresse http://formation.adpse76.fr/

Je viens d'essayer ce que vous m'avez conseillé avec mon nom d'utilisateur (formation.adpse76.fr/herouardj) et il en ressort une erreur 404

Pourtant la fonction redirect en fin de fichier  .htaccess fonctionne puisqu'il me redirige sur une erreur 403 après la création de cours.

**Comment by ywarnier** [comment]
Vous avez accès aux logs du serveur web?
Entre 404 et [403](https://en.wikipedia.org/wiki/HTTP_403), il peut tout de même s'agir d'un problème de .htaccess (erreur de permissions d'accès) qui emêcherait éventuellement de comprendre les règles qui suivent.
Je vous recommanderais de revenir vers la version originale du .htaccess, qui fonctionne tout de même bien pour des milliers d'autres portails sous Apache... (passer de 404 à 403 n'est pas vraiment un progrès à mon sens).

**Comment by HerouardJ** [comment]
Je viens de revenir sur la version originale du .htaccess (en retirant donc la commande redirect)

J'ai donc à nouveau l'erreur 404 lorsque je viens de créer un cours.

**Comment by ywarnier** [comment]
et les logs du serveur? Que disent-ils?

**Comment by ywarnier** [comment]
L'erreur 403 en chargeant http://formation.adpse76.fr/app/courses/ESSAIDECREATION/ (c'est à dire l'URL "traduite" comme l'aurait fait le .htaccess) suggère qu'il y a des problèmes de permissions dans le répertoire app/courses/. Est-ce que le répertoire ESSAIDECREATION a réellement été créé à cet endroit?

**Comment by HerouardJ** [comment]
Je ne sais pas comment les consulter

Quand je crée le cours, j'ai une erreur 404 juste après avec pour lien : http://formation.adpse76.fr/courses/ESSAINOUVEAU/

Quand je rajoute le dossier app, donnant : http://formation.adpse76.fr/app/courses/ESSAINOUVEAU/

J'atterri sur une erreur 403

Après vérification dans l'espace web, le répertoire à bien été créé dans app/courses

**Comment by ywarnier** [comment]
Ça a l'air d'un problème assez spécifique au hosting. C'est quel fournisseur?

**Comment by HerouardJ** [comment]
Le fournisseur est 1&1

**Comment by ywarnier** [comment]
Il me semble que c'était aussi chez eux que Stratice faisait des tests d'installation de Chamilo et en avait conclu que c'était difficile à installer. Arf... si c'est bien le cas, ils ont vraiment quelque chose de différent des autres hébergements, qui bloque l'utilisation des répertoires. Est-ce que vous pourriez me faire une capture d'écran des 3 pages du gestionnaire de fichiers qui montrent les permissions sur le répertoire app/, le répertoire app/courses et le répertoire app/courses/ESSAINOUVEAU/ ? Il y a forcément quelque chose qui ne va pas mais je ne sais pas ce que c'est. J'aurais tendance à recommander un autre hébergement si possible.

**Comment by ywarnier** [comment]
Pour info, par rapport au "Redirect" ci-dessus, la section:
```
# Redirect all courses/ to app/courses/
RewriteRule ^courses/([^/]+)/(.*)$ app/courses/$1/$2 [QSA,L]
```
du .htaccess par défaut fait déjà cette redirection, sauf que le "Redirect" en soi est plus (et trop) large.

Peut-être le problème est-il lié au fait que l'extension "Rewrite" d'Apache n'est pas disponible?

**Comment by ywarnier** [comment]
Pour référence (et, ma foi, pas très utile): https://www.1and1.com/digitalguide/hosting/technical-matters/http-403-forbidden-what-is-error-403-and-how-do-i-fix-it/

**Comment by HerouardJ** [comment]
L'extension URL rewriting est disponible chez 1&1

Il faut l'activer selon leur centre d'assistance : https://m.assistance.1and1.fr/hebergement-c65619/programmation-c65626/htaccess-c65664/activer-l-url-rewriting-a703954.html

**Comment by ywarnier** [comment]
À activer alors!

**Comment by HerouardJ** [comment]
Bonjour,

J'ai activer l'URL rewriting et l'application fonctionne parfaitement désormais.

Merci énormément pour l'aide et le temps que vous avez consacré afin de trouver d'où venait le problème.
