### ISSUE TITLE
Adding question with zone on image

### ISSUE THREAD

**Issue by DrMickArtisan** [chamilo/chamilo-lms#2656]
### Current behavior / Resultado actual / Résultat actuel
This seems to be a regression, because it worked on version 1.11.6 
On an existing test (created on 1.11.6), I'm adding a question  with a zone on a image. 
At first it seems to work, I can enter a zone description and a comment, and I can draw an entire zone on image 
![capture du 2018-09-06 11-15-26](https://user-images.githubusercontent.com/11190698/45147898-50adab80-b1c6-11e8-828c-374540970478.png)

But when I click "Add question to test", I'm redirect to the same page with a message "Veuillez donner une réponse" (please give an answer). The drawed zone has disappeared, and I'm no  more allowed to draw  a new one. 
![capture du 2018-09-06 11-16-17](https://user-images.githubusercontent.com/11190698/45147937-691dc600-b1c6-11e8-8976-eb0a551078a6.png)

Firefox console says 
![capture du 2018-09-06 11-06-21](https://user-images.githubusercontent.com/11190698/45147601-9322b880-b1c5-11e8-878f-1e3e00b1222f.png)

### Expected behavior / Resultado esperado / Résultat attendu
By cliquing on add question to test, I was expecting to record my question and be allowed to edit it later.
(as on version 1.11.6)
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Open an existing test  (created with 1.11.6), add question with zone on image, add image, add zone, click on "add question to test"
### Chamilo Version / Versión de Chamilo / Version de Chamilo
V1.11.8 (this just follow an upgrade from 1.11.6)
firefox version 61.0.1 (64 bits).

**Comment by jmontoyaa** [comment]
I think this was already fixed in 1.11.8  
Can you try to reproduce the error here?

https://11.chamilo.org/ admin/admin

It's working for me.

**Comment by DrMickArtisan** [comment]
Aie, in fact it works on your portal. So it must be a problem on my installation

Maybe a problem during update from 1.11.6 to 1.11.8 ? I just
* copy all files from archive 1.11.8 (except for home/, courses)
* modify the version number in app/config/configuration.php
* copy every files in template/default in my newtemplate (and re-do modifications on layouts)
* delete cache.

Is there something I failed ? In files access right maybe ?

You said it was fixed in 1.11.8, by working on which part ?

**Comment by alexiye** [comment]
la correction a été faite dans 1.11.x mais pas dans la 1.11.8. Il y a un correctif dans le fichier admin.php qui se trouve dans main/exercice

**Comment by alexiye** [comment]
main/exercise

**Comment by DrMickArtisan** [comment]
OK, je teste ca tout de suite.

**Comment by DrMickArtisan** [comment]
Ca marche ! Many thanks !
