### ISSUE TITLE
Use iso code as language instead of English name

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2657]
### Current behavior / Resultado actual / Résultat actuel
User language is saved as a English name in the database

### Expected behavior / Resultado esperado / Résultat attendu
Thé ISO code should be saved.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
V2

**Comment by ywarnier** [comment]
In the master branch, user.language has been transformed into user.locale, which is represented by the ISO code of the language.
Check the migration is operational and close this issue.

**Comment by christianbeeznest** [comment]
It is fixed and checked for migration in this commit https://github.com/chamilo/chamilo-lms/commit/04cd48602e71bc7e252ac15562018ab35d9847d8
It is checked and working.
