### ISSUE TITLE
Remove "freemind flash browser"

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2660]
Was added here:

https://github.com/chamilo/chamilo-lms/commit/2268228de1db57de495d40162c67b4a492c8ae03

Seems abandoned code. 

I suggest we remove it.

main/inc/lib/freemindflashbrowser

**Comment by ywarnier** [comment]
Removal approved. I don't know of any person or organization using it. It is to view mindmaps in-browser, but I don't think there is any standard format yet (despite this being 10+ years old). Hopefully we will add a better mind-mapping tool in the future.
