### ISSUE TITLE
Chamilo v2 install issues

### ISSUE THREAD

**Issue by rudzboy** [chamilo/chamilo-lms#2679]
### Current behavior / Resultado actual / Résultat actuel

Symfony throws 404 : No route found for "GET /main/install/index.php"

### Expected behavior / Resultado esperado / Résultat attendu

Symfony throws 200

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Following the installation steps on the readme page 
Then access http://{{chamilo.local}}/main/install/index.php

### Chamilo Version / Versión de Chamilo / Version de Chamilo

commit 190e8ae1768015eed9d500797ae1989c855fa269 (HEAD -> master, origin/master, origin/HEAD)
Author: Julio <gugli100@gmail.com>
Date:   Mon Sep 17 18:26:37 2018 +0200

**Comment by rudzboy** [comment]
From Symfony profiler :

Log messages 

ERROR14:49:34 | request | Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /main/install/index.php"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 139
-- | -- | --

Doctrine Entites Mapping 

Chamilo\CoreBundle\Entity\AccessUrl -->
The association Chamilo\CoreBundle\Entity\AccessUrl#courseCategory refers to the owning side field Chamilo\CoreBundle\Entity\CourseCategory#url which does not exist.

**Comment by ywarnier** [comment]
Chamilo 2.0 is not alpha yet. The installation procedure in the README.md should now work though (but do not expect a stable installation). Make sure you read the guide carefully as there are still several steps.
