### ISSUE TITLE
Cannot override main.js.tpl in templates

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#2683]
### Current behavior / Resultado actual / Résultat actuel

Make a modification in overrides for this file and it will not be applied after cache rebuild

### Expected behavior / Resultado esperado / Résultat attendu
It should apply the changes like any other templates

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Modify main.js.tpl in overrides (in my case remove the animation for the ticket system), empty cache and the javascript will be the same
 
### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

**Comment by meuhland** [comment]
Issue seems to be from the if in global.inc.php (main/inc/) at line 665

If I delete the cache the 1st condition (!file_exists) becomes true and it hard codes the path to default/layout/main.js.tpl instead of checking if there is an override.

**Comment by ywarnier** [comment]
main.js.tpl is indeed a very special case. What kind of change do you want to apply there?

**Comment by meuhland** [comment]
Altering the behavior of the ticket tool hide/collapse. (hover/leave)
