### ISSUE TITLE
Difficulties with playing mp4 files (as mentioned in #2171)

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#2686]
### Current behavior / Resultado actual / Résultat actuel
If you want to play as normal user a mp4 movie (visible in the folder structure) in a learning path what is put in an hidden folder, you get the following message:
Sorry, you are not allowed to access this page, or maybe your connection has expired. Please click your browser's "Back" button or follow the link below to return to the previous page.

If you play the same file as admin, there is no problem.

This is only a problem for mp4 files, not for pdf's or jpg's.

### Expected behavior / Resultado esperado / Résultat attendu
If a visible mp4 file in a hidden folder is played in a learning path, it should work. 

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Make a hidden folder in the documents map, put a visible pdf in it and put a visible mp4 file in it. Put both files in a learning path. Change to normal user, The pdf will be visible, the mp4 gives an error. 

Make the hidden folder now visible, the pdf and mp4 are now for a normal user visible in the learning path.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8 installed from scratch (no update).

Is it not possible to remove the visible/hidden check from the inserted files in the learning path. It has no added value to check if the files are hidden in the folder, it gives only troubles. If you put a file in the learning path, you always want it to be seen, otherwise you remove it.

**Comment by AngelFQC** [comment]
I can't reproduce this issue

I uploaded two visibles files (1 pdf and 1 mp4) inside a hidden folder, added to learning path. And as student I can see the learning path with these files.

Test with `acostea` user in https://11.chamilo.org/main/lp/lp_controller.php?cidReq=TESTINGDOCUMENTSHIDDENFOLDER&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=39
