### ISSUE TITLE
Course About Page shows Subscription button even if Course doesn't allow to be subscribed to

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#2687]
### Current behavior / Resultado actual / Résultat actuel
About : 
![image](https://user-images.githubusercontent.com/6123610/46166145-7a577100-c260-11e8-88f3-0cc592f360f4.png)

Course Setting : 
![image](https://user-images.githubusercontent.com/6123610/46166129-67dd3780-c260-11e8-8768-0c3032daa338.png)

Result : 
![image](https://user-images.githubusercontent.com/6123610/46166182-90fdc800-c260-11e8-9f47-931d26e2d3c2.png)

### Expected behavior / Resultado esperado / Résultat attendu

Not being allowed to subscribe as per course setting in the first place.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Create a public course that doesn't allow subscription by the user, and as a non-admin try to enrol via the about page of the course.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

**Comment by ywarnier** [comment]
Hi @meuhland 
Could you describe your use case? Is that useful in some cases to have a public course to which you cannot subscribe? They can still access the course even without subscribing, right?
It's just to be able to judge the priority...

**Comment by meuhland** [comment]
That’s exactly my point as of right now you can set a public course that
only administrator can subscribe to but the button will still be visible in
the about page of the course (via the course catalog).
Which results in a redirection to the class with an error saying something
generic like unknown error contact the portal admin.

More or less it boils down to adding the logic to check if you can
subscribe to the course then display the subscribe button in the about page.

**Comment by meuhland** [comment]
It’s a 6 or 7 line fix if you just hide it when not allowed I can PR it
tomorrow (got it running on our internal staging server)

**Comment by ywarnier** [comment]
I was going to suggest to help you out for the patch (not because we don't want to do it but because we'd like to help our community to be more participative). Will gladly review and merge your PR.

**Comment by meuhland** [comment]
You know the organization I work for and know of our plans going forwards
with Chamilo. So you know we’re working a common goal here. :)

**Comment by ywarnier** [comment]
True... I always forget :-)
