### ISSUE TITLE
Looking for a professional to implement BigBlueButton Chamilo plugin on my Chamilo

### ISSUE THREAD

**Issue by iustiny** [chamilo/chamilo-lms#2691]
### Current behavior / Resultado actual / Résultat actuel
I have no idea how to do that!
### Expected behavior / Resultado esperado / Résultat attendu
I need a professional to do it for me.
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Please point me to a willing and able person
### Chamilo Version / Versión de Chamilo / Version de Chamilo
Latest

**Comment by ywarnier** [comment]
Hi @iustiny
The members of the Chamilo development will point you to the official providers list, because these are the people who contribute to Chamilo and offer professional services around it. You can contact them all at once with the e-mail address shown here: https://chamilo.org/en/providers/

**Comment by iustiny** [comment]
Thank you!
Sorry for cluttering this forum with my nonsense - I just didnt know where else to look...

**Comment by ywarnier** [comment]
No problem. Happy to help.
