### ISSUE TITLE
No se puede eliminar secuencia y desvincular recursos de secuencias

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2693]
### Current behavior / Resultado actual / Résultat actuel

Al crear una secuencia y asignar requisitos, luego no puedo eliminarlas y eso me impide eliminar las tambien las sesiones de formación creadas.

### Expected behavior / Resultado esperado / Résultat attendu

Eliminar secuencia
Eliminar sesiones

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Crear sesion de formación A y B
Crear una secuencia
Asignar el requisito A a la sesion B en la secuencia
Eliminar los requisitos y secuencia

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x
2.0

**Comment by ywarnier** [comment]
This is working well now. I can delete elements in the sequence and the whole sequence too.

![resources-sequencing](https://user-images.githubusercontent.com/609839/52386050-3700e080-2a52-11e9-91a6-df664e42135c.png)

*However*, I can create several sequences but I cannot switch from one sequence to another (when I select another sequence, nothing happens except that I can delete it). There should be a button saying "Display" or something like that next to the "Delete" button for the sequence.

**Comment by ywarnier** [comment]
![delete-sequence](https://user-images.githubusercontent.com/609839/52386147-babacd00-2a52-11e9-8626-fa4f8856d8c3.png)

**Comment by AngelFQC** [comment]
> _However_, I can create several sequences but I cannot switch from one sequence to another (when I select another sequence, nothing happens except that I can delete it). There should be a button saying "Display" or something like that next to the "Delete" button for the sequence.

@ywarnier El funcionamiento ahora es que el selector de sencuencia sólo establece la secuencia de referencia para el bloque "Configuración de la secuencia". Para "cambiar de sencuencia" tendrías que seleccionar una sesión y luego hacer click en "Usar como referencia" para que el contexto de esa sesión cambie en base a la secuencia seleccionada. Agregar un botón de "display sequence" sería una nueva funcionalidad que muestre la secuencia por completo.

**Comment by ywarnier** [comment]
Que pasa si la sesión seleccionada ("A") está e dos secuencias distintas (seq1 y seq2)? Qué "contexto" de secuencia se seleccionaría al seleccionar la sesión ("A")? Seq1? Seq2? No quiero que se muestre nada al seleccionar la secuencia, pero sí que actue como filtro para la selección de sesión.

**Comment by ywarnier** [comment]
He puesto mi idea de una manera un poco más "visual". Espero ayude.

![sequences-changes](https://user-images.githubusercontent.com/609839/53839439-7b09d700-3f65-11e9-98ad-96ea1d5fb884.png)

Por lo visto, en main/template/default/admin/resource_sequence.tpl ya hay un poco de JS para hacer cosas similares.

**Comment by AngelFQC** [comment]
> Que pasa si la sesión seleccionada ("A") está e dos secuencias distintas (seq1 y seq2)? Qué "contexto" de secuencia se seleccionaría al seleccionar la sesión ("A")? Seq1? Seq2? No quiero que se muestre nada al seleccionar la secuencia, pero sí que actue como filtro para la selección de sesión.

En este caso, si hay secuencias creadas, entonces aparecerán en la lista de secuencias, por lo que se tomará el contexto de la secuqncia que aparezca seleccionada (la primera siempre aparece seleccionada de manera predeterminada).

Estoy agregando código para hacer que el flujo de crear una sencuencia sea paso por paso. Y mostrar el nombre de la secuencia en la vista previa.

**Comment by ywarnier** [comment]
Very nice. I'm also moving the sequence link to the sessions block, I think it's time to abandon the idea (for now) that it will have more than sessions.
