### ISSUE TITLE
Argument 1 passed to Twig_Environment::addExtension() must implement interface Twig_ExtensionInterface, boolean

### ISSUE THREAD

**Issue by mfrederico** [chamilo/chamilo-lms#2694]
### Current behavior / Resultado actual / Résultat actuel
php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
Dumping exposed routes.

[file+] public/js/fos_js_routes.json

In Environment.php line 670:
                                                                                                                                            
  Argument 1 passed to Twig_Environment::addExtension() must implement interface Twig_ExtensionInterface, boolean given, called in /var/ww  
  w/html/default/lms.controlpad/var/cache/dev/ContainerVssmkxd/srcDevDebugProjectContainer.php on line 6849 

### Expected behavior / Resultado esperado / Résultat attendu
It works

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
PHP: 7.1.20
Ubuntu Linux

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Latest Master: 2018-10-02

**Comment by jmontoyaa** [comment]
Should be fixed with :

1. git pull
2. delete cache content inside "var/cache"
3. Run composer update
