### ISSUE TITLE
Responsive issue in learnpath

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2695]
### Current behavior / Resultado actual / Résultat actuel
Le titre apparait sur les outils d'édition voir sur https://11.chamilo.org (voir image)
![11_chamilo_org](https://user-images.githubusercontent.com/22802716/46535812-7fc54480-c87a-11e8-837d-254da3e7e95d.jpg)

Sur https://campus.chamilo.org l'affichage est ok: 
![campus_chamilo_org](https://user-images.githubusercontent.com/22802716/46535887-b8fdb480-c87a-11e8-87a8-cfc103790510.jpg)

En modifiant la dimension de l'affichage, le titre se replace au bon endroit, ça semble un problème de responsive.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Version 1.11.8

**Comment by andreboivin** [comment]
ajouter   #scorm-info{
        padding: 2px;
        margin-bottom: 2px;
		height: 210px;
    } à web/css/scorm.css la ligne 598 après de :@media (min-width: 768px) {

**Comment by andreboivin** [comment]
Le problème apparait seulement si la table des matières du parcours est assez longue pour faire afficher l'ascenseur. Avec un ou seulement quelques  éléments dans le parcours, l'affichage est ok.

**Comment by ywarnier** [comment]
These latest changes should fix the issue for you @andreboivin 
Any chance you could give us your approval by testing on https://11.chamilo.org ?

**Comment by andreboivin** [comment]
Fonctionne bien.
Merci!
