### ISSUE TITLE
SPF issues with api_mail_html

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#2696]
### Current behavior / Resultado actual / Résultat actuel

If from email is defined there is an high risk that a SPF failure will occur and the email will be rejected.
https://en.wikipedia.org/wiki/Sender_Policy_Framework

### Expected behavior / Resultado esperado / Résultat attendu
From email should always be the portal or admin, worst case re-use the from as a reply-to. So that the email is delivered even if the domain has SPF enabled.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Any

**Comment by NicoDucou** [comment]
There is an option in app/config/mail.conf.php : 

`$platform_email['SMTP_UNIQUE_SENDER'] = 0; // to send all mails from the same user`

That enable to always send the mail with the account define to connect to the smtp server. This can be an option to avoid this problem.

**Comment by meuhland** [comment]
Yeah but then if the teacher replies with that setting wouldn't it all just go to the admin of the portal?

**Comment by NicoDucou** [comment]
If you leave the configuration 
`$platform_email['SMTP_UNIQUE_REPLY_TO'] = 0;`
Then it will not change the reply_to configuration and use the real user email if defined. The previous configuration only modifies the From field.
This is what it is supposed to do.

**Comment by meuhland** [comment]
Merci Nico je test ça.

**Comment by meuhland** [comment]
It didn't work ... ended just changing the logic in api.lib.php to replace the mailFrom of any email as a reply-to.
