### ISSUE TITLE
security flaw with accessing different courses they are not apart of.

### ISSUE THREAD

**Issue by m4dunlop** [chamilo/chamilo-lms#2700]
### Current behavior / Resultado actual / Résultat actuel
When logged in with a student account (or higher) an active user is able to utilize the naming convention of classes to hop from one course to another with out being given access by the admin or manger account.

### Expected behavior / Resultado esperado / Résultat attendu
User is denied access to a different class that they are not apart of.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
In the url link if they change the url to reflect the class before or after theirs they are brought to the page and can see anything that a student can see even if your access is higher than a student.
website.com/courses/class012018/index.php
website.com/courses/class022018/index.php

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Latest 1.11.8

**Comment by AngelFQC** [comment]
I can't reproduce this issue

I created 5 courses (open, closed, invisible, private and public)
I'm logged-in as one student. And I only can see the content from the public course.
I'm logged-in as another student subscribed to private course. And I only can see the content from the private course.
