### ISSUE TITLE
Use Accept-Range to allow for pseudo-streaming of video

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#2701]
### Current behavior / Resultado actual / Résultat actuel
Video has to have buffer up to the point you want to fast forward

### Expected behavior / Resultado esperado / Résultat attendu
If the video is 6 hours long I would expect that from load I could view any part of it without having to wait.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Load any larger-ish video and try to click around the end of the timeline.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

I'm more or less opening this for a discussion about if this should be included or not in the core, I'm using it on my deployment and it's working nicely with a minimal amount of code change so if there is interest in this I'll push a PR for the world to enjoy and review,

**Comment by opensourcecompany** [comment]
First of all, this is NO Chamilo issue.
Better use a streaming server OR google for "moov atom".

**Comment by meuhland** [comment]
Yeah I know about those but Chamilo is using specifically php's native readFile (as per document.lib.php) to serve files which afaik don't support a byte-range or partial download fonctions which would allow for such pseudo-streaming to work right out of the box.

http://php.net/manual/en/function.readfile.php

**Comment by meuhland** [comment]
@ywarnier  Awesome I'll get back to you by the end of the week with the PR I'm a bit swamped here... it's been running for multiple months in our environment and I didn't feel that much of a hit.

**Comment by NicoDucou** [comment]
Hi @meuhland and happy new year.
It seems the end of the week has been really full. :)

Since we are now in the last part before releasing 1.11.10 is there any chance you would have a bit of time to send the PR so that it could get included ?

**Comment by ywarnier** [comment]
The PR has been accepted. I guess this can be closed now. Thanks for your contribution @meuhland !
