### ISSUE TITLE
Chamilo adds a ? after the link

### ISSUE THREAD

**Issue by AndrewHobson** [chamilo/chamilo-lms#2702]
### Current behavior / Resultado actual / Résultat actuel
In a course, under the tool Links, I created a new link.
Under the Link tool, the new link works great and brings me to the correct webpage
But if I edit the link and click on the check mark : On the home page (To display the link on the home page of the course). The link is broken because Chamilo adds the ? character at the end of the link when used from the course homepage.

### Expected behavior / Resultado esperado / Résultat attendu
Do not add the '?' character when the link is used from the course homepage.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
See the explanation under current behavior.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Latest 1.11.8

**Comment by jmontoyaa** [comment]
This was already reported and fixed here: #2655 
It's include in the latest code in branch 1.11.x

The change:

https://github.com/chamilo/chamilo-lms/commit/1bd460081735ce4c320de7d023c820608373cc94
