### ISSUE TITLE
Email Editor (contact administrator)

### ISSUE THREAD

**Issue by hichamon306** [chamilo/chamilo-lms#2704]
I'm using mailjet to send emails, when students send message to administrator, mailjet doesn't deliver message because sender is address email of the student and not de address of the plateforme thad i set in admin settings

chamilo should use email that i set in admin setting instead of student email

to reproduce that connect as student and click in admin link located at the footer of the page

Chamilo 1.11.8 php 7 ngix.

I update this file /main/inc/email_editor.php, I think that i haven't enough permission to create a pull request, how can i contribute to chamilo repo ?

Thanks,

Best regards

**Comment by opensourcecompany** [comment]
Have you had a look at /app/config/mail.conf.php ?

**Comment by hichamon306** [comment]
@opensourcecompany I have already make changes in app/config/mail.conf.php and everything works, except mails send through email_editor to administrator, here is the solution : 
I replace this : 
`if (!empty($_user['mail'])) {
        api_mail_html(
            '',
            $email_administrator,
            $title,
            $text,
            api_get_person_name($_user['firstname'], $_user['lastname']),
            $_user['mail']
        );`
by this 
`if (!empty($_user['mail'])) {
        api_mail_html(
            '',
            $email_administrator,
            $title,
            $text,
            api_get_person_name($_user['firstname'], $_user['lastname'])
        );`

**Comment by ywarnier** [comment]
This is a bit old now but I think this issue has been attended (albeit in a different way). See:

https://github.com/chamilo/chamilo-lms/blob/1970f0ca3735ccb37102a56aa7e630dcf9d0149e/main/inc/email_editor.php#L74-L87
