### ISSUE TITLE
Duplicate configuration setting `limit_session_admin_role`

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2708]
### Current behavior / Resultado actual / Résultat actuel
Exists a conf variable `limit_session_admin_role` and a setting `limit_session_admin_role` related to doing the same.
The setting description doesn't indicate the correct feature.

### Expected behavior / Resultado esperado / Résultat attendu
Should only be the setting (without the conf variable)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Check uses for `api_get_configuration_value('limit_session_admin_role')` and `api_get_setting('limit_session_admin_role')`

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
I think we can close this issue. The fact that it exists will let us find it later on anyway.
