### ISSUE TITLE
? al cargar imagen en documento de lección

### ISSUE THREAD

**Issue by vlobaco** [chamilo/chamilo-lms#2710]
### Current behavior / Resultado actual / Résultat actuel
Al añadir una imagen en un documento aparece ?
### Expected behavior / Resultado esperado / Résultat attendu
Al selecionar la imagen debería aparecer la imagen
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Seleccionar imagen en la barra de herramientas del editor de documento. Se abre el cuadro de diálogo. Seleccionar Ver Servidor. En la ventana emergente, seleccionar el archivo .jpg, haciendo doble click. Se carga el link y se selecciona Aceptar.

![screen shot 2018-10-27 at 06 51 34](https://user-images.githubusercontent.com/44517971/47600172-e4287f00-d9b4-11e8-8f67-10af5f36616b.png)
![screen shot 2018-10-27 at 06 51 47](https://user-images.githubusercontent.com/44517971/47600173-e4287f00-d9b4-11e8-9705-d12908bbb695.png)
![screen shot 2018-10-27 at 06 52 24](https://user-images.githubusercontent.com/44517971/47600174-e4287f00-d9b4-11e8-9d3f-dd44601dd969.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

**Comment by vlobaco** [comment]
He encontrado la causa. El link que genera el navegador es: 
`/courses/AGENTEDELAAUTORIDAD/document/img/jerarquia.jpg`
pero debería de ser: 
`/app/courses/AGENTEDELAAUTORIDAD/document/img/jerarquia.jpg`
¿Cómo puedo corregir esto? Gracias por adelantado.

**Comment by ywarnier** [comment]
Este link debería ser transformado automáticamente por el .htaccess. Puedes buscar en el .htaccess por la regla correspondiente, pero lo más probable es que tu servidor no tenga la configuración correcta para entender y ejecutar el .htaccess. Leiste el manual de instalación antes de instalar tu portal Chamilo?
https://campus.chamilo.org/documentation/installation_guide.html (enlace hacia la versión española en la introducción)

**Comment by vlobaco** [comment]
Thank you Yannick. I have checked my configuration: the rewrite module is running, and the .htaccess file is there with all the rules. ¿Any other ideas?

**Comment by PhilAZUser** [comment]
Hi,
Exact same problem here.
Some more info :
- Chamilo is installed in a subfolder of the test server "http://192.168.xxx.xxx/chamilo"
- All URL Rewriting redirections are working as expected (in httpd.conf file)
- After importing an image, on the CKEditor as well as on the course page, the image path is set server-root relative :
"http://192.168.xxx.xxx/courses/TESTCOURS/document/image1.jpg"
- It should be :
"http://192.168.xxx.xxx/chamilo/courses/TESTCOURS/document/image1.jpg"
(it misses the "chamilo/" sub-folder)
Hop it helps a bit...
Thanks a lot to the dev team ! Keep up the good work 👍
Phil

**Comment by NicoDucou** [comment]
Hi @PhilAZUser 
In your case when you install Chamilo in a sub folder you have to add the information of the sub folder in the configuration file. You have to edit app/config/configuration.php and edit the following line : 
```
// Path from your WWW-root to the root of your Chamilo installation,
// example: chamilo (this means chamilo is installed in /var/www/chamilo/
$_configuration['url_append'] = '';
```
It should be in your case 
```
$_configuration['url_append'] = 'chamilo';
```
