### ISSUE TITLE
Many errors cause by fixAbusiveTime

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2711]
### Current behavior / Resultado actual / Résultat actuel
Plusieurs erreurs signalé dans le log php du genre:
[Mon Oct 29 15:05:28.697680 2018] [:error] [pid 31682] [client 204.19.80.254:51065] fixAbusiveTime: Total time is too big: 23858 replaced with: 300, referer: https://www.ticformation.ca/main/lp/lp_controller.php?action=view&lp_id=22&id_session=0&cidReq=298244&id_session=0&gidReq=0&gradebook=0&origin=

[Mon Oct 29 15:05:28.697746 2018] [:error] [pid 31682] [client 204.19.80.254:51065] item_id : 2070 lp_item_view.iid: 2213652, referer: https://www.ticformation.ca/main/lp/lp_controller.php?action=view&lp_id=22&id_session=0&cidReq=298244&id_session=0&gidReq=0&gradebook=0&origin=

Les erreurs sont toujours en double pour le même item du lp

### Expected behavior / Resultado esperado / Résultat attendu
Plus de message d'erreur...
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
La plupart des erreurs sont causées par l'affichage de simple page html mais je ne réussis pas à recréer. Par contre j'ai réussi à produire l'erreur à chaque fois avec un quiz hotpotatoes auquel j'ai mis l'option timer, directement par l'interface de hotpotatoes
### Chamilo Version / Versión de Chamilo / Version de Chamilo
Version 1.11.8

**Comment by ywarnier** [comment]
Bien que rapportées comme erreur de par le mécanisme que nous utilisons, il s'agit simplement d'un enregistrement d'un événement que nous souhaitons garder à disposition étant donné une multiplication des cas de mauvais contenus SCORM rencontrés dernièrement, et de problèmes de tracking rencontrés avec des doubles sessions dans Chamilo (usages non-linéaires).
Tu peux supprimer l'enregistrement de ces messages en commentant les deux lignes vers la ligne 1894 de main/lp/learnpathItem.class.php.
Nous les supprimerons dans une prochaine version.
