### ISSUE TITLE
fixAbusiveTime: Total time is too big

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2713]
Got error 'PHP message: fixAbusiveTime: Total time is too big: 319820 replaced with: 300
PHP message: item_id : 12 lp_item_view.iid: 13\n', referer: /main/lp/lp_controller.php?cidReq=FSA0001FACHK&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=12&isStudentView=true

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

**Comment by ywarnier** [comment]
This is specific error logging. You can mute it manually in main/lp/learnpathItem.class.php line 1894 or so, but it represents issues with time tracking and we believe it is important to register it in a non-permanent space until we find a better solution.

**Comment by lonesomewalker** [comment]
Hello Yannick,

sorry for responding late, but in another issue i have seen this is related to SCORM?
I have this issue in Chamilo generated content :-(
