### ISSUE TITLE
First login results in error, second try works

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2714]
### Current behavior / Resultado actual / Résultat actuel
Login with valid user/pass combination.
System says: You are not allowed to see this page. Either your connection has expired or you are trying to access a page for which you do not have the sufficient privileges.
Second try with same credentials works perfect.

### Expected behavior / Resultado esperado / Résultat attendu
System should be log in immediately or at least produce an entry in the error log why no login possible.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.8

**Comment by opensourcecompany** [comment]
Finally, error is found:
Multi-URL installation.
Main portal is using www.domainname.tld.
When users are entering the URL into the browser, you get a mismatch between sessions/submit because they enter it WITHOUT www.

Solution: creating a rewrite rule for ALL used URLs.
That's somewhat frustrating, but not an Chamilo issue :-(

**Comment by ZAAC15** [comment]
Como lo dice @opensourcecompany ¿como puedo crear un regla de reescritura para todas las URL?

**Comment by zentery** [comment]
Please, how to address it? I encountered this problem after installing and logging in. How can I solve it?
