### ISSUE TITLE
New course tracking charts

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2717]
### Current behavior

The /main/tracking/courseLog.php?cidReq=XYZ page is awfully non-illustrated. In comparison to most other major LMSes, this looks quite textual:

![course-chart-orig](https://user-images.githubusercontent.com/609839/47793419-3555ad00-dcec-11e8-87df-dde7304592ba.png)

### Expected behavior

We should illustrate all that a little with measures we already have but that are only textual for now:

![course-chart-mod](https://user-images.githubusercontent.com/609839/47793455-4c949a80-dcec-11e8-930f-6b6e131e1f6a.png)

- average score in tests (for the course/session)
- average progress in learning paths (for the course/session)
- a chart of the distribution of average tests scores in the whole course (by 10%) (this should be a link to the gradebook "flat view" page)
- the number of certificates already delivered in comparison with the number of students registered (this should be a link to the gradebook)

### Chamilo Version

This can be added to 1.11.x and then moved to master

**Comment by opensourcecompany** [comment]
looks much better :+1:

**Comment by ywarnier** [comment]
This page's presentation could also be slightly improved at the same time.

**Comment by ywarnier** [comment]
There's stil an issue when a coach or teacher is subscribed as a student too: the counting of some of the data gets "off-by-1" issues.

**Comment by ywarnier** [comment]
Pues acabo de revisarlo y parece que ya pasé la mayoría a master así que solo te queda hacer la transición de los TPLs, no?

**Comment by ywarnier** [comment]
This has been implemented and now looks like this:

![tracking-chart-course](https://user-images.githubusercontent.com/609839/49178518-f1bb8680-f31d-11e8-9053-bb869777c3b7.png)

**Comment by ywarnier** [comment]
I added a few of these to decorate a bit for the admin.

![stats-charts-u](https://user-images.githubusercontent.com/609839/49673013-0a711e00-fa3b-11e8-91b8-076b974291c4.png)

![stats-charts-l](https://user-images.githubusercontent.com/609839/49673019-0e9d3b80-fa3b-11e8-84c4-c0cc8f2fc3b9.png)
