### ISSUE TITLE
No cursor after image insertion using ckeditor

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2718]
The problem seems to be in the image2_chamilo plugin ...

### Current behavior / Resultado actual / Résultat actuel
The cursor doesn't appear:
link:

https://11.chamilo.org/main/document/create_document.php?cidReq=20180413EBM&id_session=0&gidReq=0&gradebook=0&origin=&id=

![one](https://user-images.githubusercontent.com/158935/47844653-3574ac00-ddc3-11e8-9daf-d1a554694b5f.gif)

### Expected behavior / Resultado esperado / Résultat attendu
The cursor appears correctly:
Tested in https://sdk.ckeditor.com/samples/standardpreset.html

![two](https://user-images.githubusercontent.com/158935/47844675-4b826c80-ddc3-11e8-98cb-61b55b70823a.gif)

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x

**Comment by jmontoyaa** [comment]
Reported originally in https://task.beeznest.com/issues/15021

**Comment by AngelFQC** [comment]
Es por el plugin que usamos ahora image2. En el ejemplo en donde se muestra correctamente el curso, el plugin es image.

**Comment by jmontoyaa** [comment]
Si, exacto. El comportamiento que se desea es como en como en el segundo gif, o de alguna manera mostrar correctamente el cursor.

**Comment by AngelFQC** [comment]
El error está registrado aquí ckeditor/ckeditor-dev#2134.

No encuentro solución con código por ahora :disappointed:. Pero para ver el curso hay que hacer click en el lado derecho a la altura de la mitad de la imagen.

**Comment by jmontoyaa** [comment]
ping?

**Comment by ywarnier** [comment]
Esto es importante, @jmontoyaa ? Hasta yo no le veo mucha importancia...

**Comment by jmontoyaa** [comment]
@ywarnier Me piden feedback en:

https://task.beeznest.com/issues/15021

**Comment by AngelFQC** [comment]
Aunque Chamilo esté usando una versión modificada del plugin, éste es un bug del propio plugin image2 que viene con ckeditor. Puede reproducirse aquí https://ckeditor.com/ckeditor-4/

Una "solución rápida" es hacer click a la derecha de la línea base de la imagen (al rededor de la esquina inferior derecha de la imagen), entonces el curso aparecerá. Y otra, es presionar la tecla de la flecha derecha después de insertar la imagen.

**Comment by ywarnier** [comment]
Discussed with customer that this can be left as is, as fixing without an upstream fix would take too long and not be a resilient fix.
I'm tempted to close this issue, but let's leave it open for a bit in case someone finds a better solution.
