### ISSUE TITLE
Actualizar y configurar el Cropper por el Cropperjs

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2722]
### Current behavior / Resultado actual / Résultat actuel
En el sitio web del proyecto Cropper menciona que ahora se usara Cropperjs
Verificar y actualizar los modulos en Chamilo que usan esta libreria.
### Expected behavior / Resultado esperado / Résultat attendu
Cortar una imagen al cargar
### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Actualemte esta roto.
### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0

**Comment by jmontoyaa** [comment]
modificar el package.json de chamilo y usar cropperjs

https://yarnpkg.com/en/package/cropperjs

**Comment by aragonc** [comment]
Creo que no es necesario actualizarlo, al parecer el problema es que el css del actual cropper no era cargado en app.css y para evitar retrasos con actualizar el codigo... lo dejo asi.

Todo funciona bien probado y adjuntado en master
