### ISSUE TITLE
Wrong SCORM result gives 100% in Assesments

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2724]
### Current behavior / Resultado actual / Résultat actuel
SCORM courses are sending a "non passed", but Chamilo tracks that as 100% in Assesments, and gives certificate.

### Expected behavior / Resultado esperado / Résultat attendu
Chamilo should recognise that value as 0, since the course says "not passed".

### Chamilo Version / Versión de Chamilo / Version de Chamilo
latest stable for PHP7

**Comment by NicoDucou** [comment]
Could you create a case on 11.chamilo.org with the scorm that is sending the data to be able to reproduce your problem and analyse it.

**Comment by NicoDucou** [comment]
@opensourcecompany we can not reproduce the problem for the moment with the scorm packages that we tried with. So please create a case on 11.chamilo.org or upload you SCORM package here otherwise if there is no feedback we will have to close the issue.

Best regards
