### ISSUE TITLE
Possible bug in Chamilo 1.11.8 - attach doc to work task

### ISSUE THREAD

**Issue by mumarcar** [chamilo/chamilo-lms#2725]
### Current behavior / Resultado actual / Résultat actuel
Icomplete load of add_document script in attaching document to work/task. No footer loaded and no nothing occurs when expanding or collapsing documents tree.
 
### Expected behavior / Resultado esperado / Résultat attendu
I suppose should be possible to select an existing document to attach it to a work

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Create a task/work in a course, access as teacher or admin to edit the task and click de option "Add document" in the upper menu 

### Chamilo Version / Versión de Chamilo / Version de Chamilo
Chamilo 1.11.8

**Comment by andreboivin** [comment]
Look #2712 Probably the same problem. Tried to edit document.lib

**Comment by NicoDucou** [comment]
I just tested it here https://11.chamilo.org/main/work/work_list_all.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&id=177

I clicked on the ![image](https://user-images.githubusercontent.com/6579268/48703829-414ed380-ebf5-11e8-8467-263ab78ec140.png) icon and then clicked on the name of the document. I got added to the assignment and now we can see the 2 document I added as attached document of the assignment.

Could you create a case on 11.chamilo.org (you can access with user admin/admin) to be able to reproduce your problem or explain a bit more the procedure to be able to reproduce it.

**Comment by mumarcar** [comment]
Hi Nico,

I've just test in 11.chamilo.org in your test course and I can attach a document located in the Documents main level, but in that enviroment **I can't expand the folders tree to select a document** inside, for example, images folder.

In our installation the problem is the same. It seems that if the document is at root level we can attach it, but as directory expand does not work, we can't select any other file uploaded in a subdirectory.

Please, let me know if you need more info.

**Comment by andreboivin** [comment]
The problem is caused by document.lib.php. It seems to have used the same function as for documents in a LP. At line 6590, after $ onclick = ''; , we expect to have the $ lp_id that is not present in the work section. Currently, I commented  the lines:
6590: // if ($ lp_id) {
and 6595: //} 
and now it's ok in the "works" section

**Comment by NicoDucou** [comment]
I confirm that we can not open sub folder to add a doccument to an assignment (work). It can be tested here : https://11.chamilo.org/main/work/add_document.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&id=177

@jmontoyaa can you see the solution proposed by andreboivin in the previous comment and if it's good for you apply it to 1.11.x ?

**Comment by ywarnier** [comment]
@mumarcar podrías verificar que los cambios enviados por @jmontoyaa (Fix document preview) solucionan el problema para ti?

**Comment by andreboivin** [comment]
Fonctionne correctement avec cette dernière version de document.lib.php de Julio

**Comment by mumarcar** [comment]
Hola @ywarnier,

Sí, los he desplegado en nuestra versión y funcionan correctamente.
Gracias!

**Comment by ywarnier** [comment]
Thanks to both of you for confirming.
