### ISSUE TITLE
Borrar imagen cargada en categoría de cursos (Administración)

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2726]
### Current behavior / Resultado actual / Résultat actuel
Sube la imagen pero cuando quiero editar y cambiarla por otra no se puede borrarla o reemplazarla
![borrar_imagen](https://user-images.githubusercontent.com/2940509/48379944-d9076b80-e6a3-11e8-8e2e-166e450c6bab.png)

### Expected behavior / Resultado esperado / Résultat attendu
Borrar la imagen al momento de guardar si esta marcado el check borrar imagen
Esto sirve para cambiar las portadas de las categorias en Chamilo
![categorias](https://user-images.githubusercontent.com/2940509/48379967-f6d4d080-e6a3-11e8-9ad8-906f7603d99e.png)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Tienes que activar en configuration.php
$_configuration['my_courses_list_as_category'] = true;

Para mostrar estas opciones.

### Chamilo Version / Versión de Chamilo / Version de Chamilo
2.0

**Comment by jmontoyaa** [comment]
Funciona para mi aqui:

main/course_info/infocours.php

Tal vez es un tema de permisos? 

Dar 777 a "var/courses"

**Comment by aragonc** [comment]
No era en infocours.php era en **main/admin/course_category.php** pero ya estoy enviando un cambio...
