### ISSUE TITLE
Extender la funcionalidad de display_two_col_template()

### ISSUE THREAD

**Issue by joelmatiassilva** [chamilo/chamilo-lms#2727]
hola,

Necesito extender la funcionalidad del método **display_two_col_template()** que se encuentra en main/inc/lib/template.lib.php. Tengo que devolver los grupos de estudios públicos.

¿Existe alguna forma normalizada para extender los cambios? Así como existe los **overrides** de los **templates**

**Comment by joelmatiassilva** [comment]
Se decidió modificar la función display_two_col_template() para devolver los get_groups_by_popularity() de UserGroup.

**Comment by ywarnier** [comment]
No existe una forma de extender los métodos de la librería template, no, así que lo hiciste bien. Lo único es que tendrás que volver a aplicar esta modificación luego de la actualización de este sistema Chamilo a la siguiente versión.
