### ISSUE TITLE
Las lecciones SCORM no se copian al hacer copias seguridad

### ISSUE THREAD

**Issue by alumnodemo** [chamilo/chamilo-lms#2728]
Hola a todos,

Tengo un problema al restaurar una copia de seguridad o cuando hago una copia de un curso a otro.

La version que estoy utilizando es 1.11.8 aunque tambien pasa con 1.11.4.

Mi problema es que cuando realizo una copia de seguridad y luego con esta copia creo otro curso y restauro con la copia el curso se restaura correctamente excepto las lecciones SCORM que sólo se restaura la estructura pero no el contenido.

He comprobado la copia de seguridad y esta si que contiene los archivos SCORM por lo que el fallo viene en la importación de la copia de seguridad.

Tambien he intentado hacer una copia del curso y pasa lo mismo, se crea una copia correcta con todos lo ejercicios y lecciones excepto las lecciones con SCORM que sólo se copia la estructura pero no los archivos de contenido.

Me pueden indicar como puedo solucionar este problema. ¿Hay algo que no hago correctamente?

Gracias

**Comment by jmontoyaa** [comment]
Puedes probar con:

archivo: app/config/configuration.php

`$_configuration['allow_import_scorm_package_in_course_builder'] = true;`

Aunque es recomendable re importar el paquete scorm en el nuevo curso, para evitar problemas.

**Comment by ywarnier** [comment]
Lo que quiere decir @jmontoyaa es que se trata de un proceso experimental.

**Comment by ywarnier** [comment]
@alumnodemo por favor, podrías darnos algo de feedback?
De lo contrario cerraremos esta tarea.

**Comment by NicoDucou** [comment]
Este es exactamente lo que esta descrito en la tarea #2470 y que ha sido validado.

dado que no hay noticias de @alumnodemo desde mas de 1 mes y medio, cierro la tarea.
