### ISSUE TITLE
Course toolbar in wrong position

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2732]
### Current behavior / Resultado actual / Résultat actuel

![20181120bandeau02](https://user-images.githubusercontent.com/158935/48764988-86384000-ecb1-11e8-917f-05e4cb5665c7.JPG)

### Expected behavior / Resultado esperado / Résultat attendu

![20181120bandeau01](https://user-images.githubusercontent.com/158935/48764993-8c2e2100-ecb1-11e8-9cf5-972dfc7aa21b.JPG)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Active option "show_toolshortcuts" in settings

### Chamilo Version / Versión de Chamilo / Version de Chamilo

1.11.x

**Comment by jmontoyaa** [comment]
Note to myself: task to be updated
BT#13954

**Comment by aragonc** [comment]
Cambien a una mejor ubicación debajo del breadcrumb
