### ISSUE TITLE
whoisonline after login

### ISSUE THREAD

**Issue by EthicalHackingCOP** [chamilo/chamilo-lms#2736]
### Current behavior / Resultado actual / Résultat actuel
Hola a todos.
Tengo chamilo unido a LDAP, cuando ingresó obtengo un error que dice "Lo sentimos, no le está permitido acceder a esta página o su conexión ha caducado. Para volver a la página anterior pulse el enlace inferior o haga clic en el botón Atrás de su navegador.", luego le doy atras y este me carga en el index normalmente (logueado) y puedo navegar en los cursos.  

Hi guys.
I've chamile joined to LDAP, when I try to login I got the below error "Sorry, you are not allowed to access this page or your connection has expired. To return to the previous page, click on the link below or click on the "Back" button of your browser." Later, I click on the Return button and it reload the index normally and i able to navigate in the courses.

![image](https://user-images.githubusercontent.com/33833733/49040051-82179100-f18f-11e8-8b3f-21a6b864b118.png)

![image](https://user-images.githubusercontent.com/33833733/49040092-9b204200-f18f-11e8-89c3-3b89f8be5866.png)

### Expected behavior / Resultado esperado / Résultat attendu
El resultado esperado es que ingrese y sea redirigido al index 

The Expected behavior is that it login correctly and go to the index

![image](https://user-images.githubusercontent.com/33833733/49040143-be4af180-f18f-11e8-90be-dbe26b855d5a.png)

![image](https://user-images.githubusercontent.com/33833733/49040129-b428f300-f18f-11e8-8dfd-948b8eee726e.png)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Vi de que este error no aparece si vamos a la parte de "Parámetros de configuración de Chamilo" y habilitamos todos los check de ¿ Quién está en línea ? , el error no aparece, pero si se quitan aparece de nuevo

I did see that this error doesn't show if go to the "Chamilo configuration params" and enable all the checkbox in "Who is on line", the error doesn't show, but if we disable the online options the error shows again.

![image](https://user-images.githubusercontent.com/33833733/49040190-dcb0ed00-f18f-11e8-9a05-e42325feffc4.png)
![image](https://user-images.githubusercontent.com/33833733/49040203-e63a5500-f18f-11e8-83d8-34d27549f9af.png)
![image](https://user-images.githubusercontent.com/33833733/49040219-efc3bd00-f18f-11e8-8650-4190241e7edd.png)

### Chamilo Version / Versión de Chamilo / Version de Chamilo

La version que estoy trabajando es chamilo 1.11.8

I'm working on 1.11.8 chamilo version

![image](https://user-images.githubusercontent.com/33833733/49040265-0c5ff500-f190-11e8-9f84-3f9572f0e1db.png)
![image](https://user-images.githubusercontent.com/33833733/49040279-14b83000-f190-11e8-8dcc-2c4d4ca3267f.png)

**Comment by spacecabbie** [comment]
Hi there i am having a simulair issue this very likely due to incorrect rewrite rules in .htaccess.
Its most likely not creating those rewrite rules.  check the installation_guide.html#16._Rewrite section.
If you want a quick fix you can add them manually. Can you post the url that it wants to go to after login ?

**Comment by EthicalHackingCOP** [comment]
Hi spacecabbie. thank you man , i will try to check the guide.

**Comment by xinita23** [comment]
tengo los mismos errores y no puedo solucionarlos
![error de usuario](https://user-images.githubusercontent.com/45883431/50095519-578f8580-01db-11e9-9843-c752323cdab7.jpg)
![error de usuario 2](https://user-images.githubusercontent.com/45883431/50095534-5eb69380-01db-11e9-8092-c6d13b6ada65.jpg)

**Comment by ywarnier** [comment]
@xinita23 el error que se evidencia es vinculado con el plugin buycourses, pero no me queda claro si instalaste desde un Chamilo original descargable o si haces actualizaciones a través de Git, porque el error que tu muestras, que es distinto del @EthicalHackingCOP, lo hemos provocado y arreglado la semana pasada en Git y si es que tu lo tienes con el paquete 1.11.8 original, entonces es otro y tenemos que saberlo.

**Comment by ywarnier** [comment]
@EthicalHackingCOP thanks for reporting. Due to the complexity of setting up a portal where we can test the whole context of LDAP and its connection to Chamilo, we do not provide assistance (more than reviewing and applying patches you could send us) as a "community support". If you really need that fixed, and considering that this will introduce a requirement of confidentiality, you should talk to any official provider of Chamilo so you can have a commercial agreement with contract terms: https://chamilo.org/providers

**Comment by xinita23** [comment]
Gracias el chamilo que descargue era de la misma página de chamilo y ya solucioné el problema igual muchas gracias

El dic. 17, 2018 1:59 PM, Yannick Warnier <notifications@github.com> escribió:

@xinita23<https://github.com/xinita23> el error que se evidencia es vinculado con el plugin buycourses, pero no me queda claro si instalaste desde un Chamilo original descargable o si haces actualizaciones a través de Git, porque el error que tu muestras, que es distinto del @EthicalHackingCOP<https://github.com/EthicalHackingCOP>, lo hemos provocado y arreglado la semana pasada en Git y si es que tu lo tienes con el paquete 1.11.8 original, entonces es otro y tenemos que saberlo.

**Comment by ywarnier** [comment]
@xinita23 bien, me alegro. En el espíritu de la comunidad, cuando encuentras una solución, te invitamos a que la compartas públicamente, cosa que si otros encuentran este mismo problema, la solución esté más fácil encontrar para ellos.

**Comment by opensourcecompany** [comment]
Indeed, this would be helpfull.
We also run in this problem.

Administrative users can login without problems, simple users get this annoying error screen.
Cookies are fine, redirection rewrite rules also checked.
Running Chamilo 1.11.8, setting the start page as the redirect target after login, and finally landing on whoisonline.php :-(

**Comment by ywarnier** [comment]
@opensourcecompany this is a bit old already. I don't really understand if this is an issue in Chamilo or not and how we can help...

**Comment by ZAAC15** [comment]
Hola amigos, yo estoy presentando el mismo problema, despues de colocar el usuario y contraseña, me sale: No está autorizado a ver esta página o su conexión ha caducado.
