### ISSUE TITLE
Exercise score UI

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2737]
### Current behavior / Resultado actual / Résultat actuel

![selection_002](https://user-images.githubusercontent.com/158935/49143041-74cae580-f2fa-11e8-9c94-697a65f8c7c3.png)

### Expected behavior / Resultado esperado / Résultat attendu

The UI of the score is broken.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire

Make a test with an open question, resolve it, make the teacher correct it.
Then the wrong ribbon will appear.

You can see the error here:

https://11.chamilo.org/main/exercise/exercise_show.php?cidReq=JULIO11&id_session=0&gidReq=0&gradebook=0&origin=&action=edit&id=929

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by aragonc** [comment]
Listo, aunque entendi que era cambiar el color  :smile: :laughing: 

Asi queda 

![review_exercise](https://user-images.githubusercontent.com/2940509/49241518-0a877300-f3d6-11e8-8f51-a716b5c7a37c.png)
