### ISSUE TITLE
mod rewrite for add a tab not working

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#2742]
### Current behavior 
When creating a tab and specifying a url it should go to that url (create a rewrite or have dynamic one)
it goes to /whoisonline.php
### Expected behavior 
Should go to whats input in the url field example /newpage
### Steps to reproduce
As far as i know its a bug i went trough both installation guide rewrite suggestions and the default installed.
### Chamilo Version 1.11.8

Note:
<Directory> should not be used in .htaccess files  http://httpd.apache.org/docs/current/mod/core.html#directory

Also the dutch translation is literally:: "Add a hyperlink." Kinda confusing you would think that only adds a hyper link somewhere.( spend 1 hour looking for the damn make a page feature LOL)  I would like to suggest to change it to: "Maak een nieuwe tab aan." (its called tab now right ?) or if we go with page: "Maak een nieuwe pagina aan"

**Comment by spacecabbie** [comment]
If i may one more quick tip github allows for lovely templates when creating a issue. ([see here](https://github.com/stevemao/github-issue-templates))
It allows for making your questions and selection of version mandatory if wished i could make one.  Let me know where to send it and what you want in it.

**Comment by ywarnier** [comment]
The linking feature for a tab will be completely rewritten in Chamilo 2.0. It is *very* old stuff that has been left there for practical reasons (it should work though). It is unlikely we will work on fixing that, Chamilo 2.0 being planned for the first half of next year. This would only distract us.

Thanks for the link to the issue reporting template. Will check that soon.

**Comment by spacecabbie** [comment]
Alrighty i'll add the rewrite rules manualy for now then.

**Comment by spacecabbie** [comment]
Resolved.

**Comment by ywarnier** [comment]
Even if we don't fix them now, don't hesitate to share your solution with the rest of the community.

**Comment by ywarnier** [comment]
The issues templates should be better now.

**Comment by ywarnier** [comment]
I'll answer this soon. Just didn't find the time yet.

**Comment by ywarnier** [comment]
> Ideally a validator would disable the editor when a value is enterd in the url field.

Yes, you could create a new (clean) issue with that, and only that, and that could be considered for inclusion in 1.11.10.

> I figured it was a rewrite url generator that would generate a link like www.mysite.com/custompage

The directory custompages/ is actually for a very specific feature that you have to enable, but there's no .htaccess rule linked to that.

> Also the translation is definitely wrong i fixed it in the local lang file

Fixing language terms is done (for 1.11.*) in https://translate.chamilo.org/. You have to create an account there, choose to help translating from English to Dutch and then ping me to enable your authorization to do that. We should be switching to another translation platform for chamilo 2.0, but we have not decided yet on which platform to use, as we're switching to Gettext and looking for an open-source-friendly platform for that.

You *cannot* (we will refuse them) send pull requests with changes to the main/lang/ directory. We export new translations from translate.chamilo.org and import them in Chamilo ourselves. It is the only channel to do that.

> May i ask what was changed ?

I followed the guides you sent and defined 6 templates (one for bug reports, one for feature requests, in 3 languages each), so now when you click "New issue" you have something in a language that is more familiar to you *only*. I also fixed a series of links that appear on the right side of the report page (contributing.md and support.md).

If you have other suggestions, let me know.

**Comment by spacecabbie** [comment]
> > Ideally a validator would disable the editor when a value is enterd in the url field.
> 
> Yes, you could create a new (clean) issue with that, and only that, and that could be considered for inclusion in 1.11.10.
> 
Wil do that like to take a crack at implenting it as wel.

> > I figured it was a rewrite url generator that would generate a link like [www.mysite.com/custompage](http://www.mysite.com/custompage)
> 
> The directory custompages/ is actually for a very specific feature that you have to enable, but there's no .htaccess rule linked to that.

Perhaps a suggestion for 2.0 ? or 3 ? I have made a mod rule now to rewrite the html pages to /pages/name and am using it as a basic CMS its a perfect solution for when you don't want to install a 2th cms but need some basic pages. It would be nice to have a bit wider scale of options.

> 
> > Also the translation is definitely wrong i fixed it in the local lang file
> 
> Fixing language terms is done (for 1.11.*) in https://translate.chamilo.org/. You have to create an account there, choose to help translating from English to Dutch and then ping me to enable your authorization to do that. We should be switching to another translation platform for chamilo 2.0, but we have not decided yet on which platform to use, as we're switching to Gettext and looking for an open-source-friendly platform for that.
>

Check with the people from drupal https://localize.drupal.org/ not sure that system is opensource but it allows for translation of everything drupal related plugins distubutions and drupal.

> You _cannot_ (we will refuse them) send pull requests with changes to the main/lang/ directory. We export new translations from translate.chamilo.org and import them in Chamilo ourselves. It is the only channel to do that.

Do not worry i will not place pull request without explicit permission i know how busy you and the team are my goal is to help not to cause more worries :)

> 
> > May i ask what was changed ?
> 
> I followed the guides you sent and defined 6 templates (one for bug reports, one for feature requests, in 3 languages each), so now when you click "New issue" you have something in a language that is more familiar to you _only_. I also fixed a series of links that appear on the right side of the report page (contributing.md and support.md).
> 
> If you have other suggestions, let me know.

Ah yes looks nice its a shame github is still limited when it commes to issues you can't define custome fields which is what i was referring to but i realize now that's on (drupal issue tracker) got confused there. May i suggest something like: 

## Your issue may already be reported! Please search on the issue track before creating one.
**Note: for support questions, please use forum.chamilo.org This repository's issues are reserved for feature requests and bug reports.**

And close tickets that are support requests it will force people to use the forum and clean issues here. 
If that's what you want off-course.

My old job was customer service manager so i would recommend to redirect it all to the forum. Getting the distractions away from you as a coder.

**Comment by ywarnier** [comment]
I'm closing this issue now. Thanks for the hints. I hope you stick around.
