### ISSUE TITLE
Remove option "My Certificates"

### ISSUE THREAD

**Issue by 480419140** [chamilo/chamilo-lms#2743]
How to remove the "My Certificates" link from the Chamilo platform menu, do not students need to get certificates?

Can someone help me?

**Comment by spacecabbie** [comment]
You can find the menu template here: main/template/default/layout/menu.tpl
If you copy that to: main/template/overrides/layout/menu.tpl 
Then remove or uncommend:
`                                {% if certificate_url %}
                                    <li class="user-body">
                                        <a title="{{ "MyCertificates"|get_lang }}" href="{{ certificate_url }}">
                                            <em class="fa fa-graduation-cap"
                                                aria-hidden="true"></em> {{ "MyCertificates"|get_lang }}
                                        </a>
                                    </li>
                                {% endif %}`

AFAIK there no toggle for it in the admin gui.
Assuming your using 1.11.8 since you din't specify a version :)

**Comment by 480419140** [comment]
Good morning, 

Thank you for support @spacecabbie @ywarnier,

In this configuration file I find the option to hide the block of courses_block, which is on the home page on the left, below profile edit?

<div class="panel panel-default" id="courses_block">
        <div class="panel-heading" role="tab">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#courses" href="#coursesCollapse">/a>........ 

Sincerely.

**Comment by 480419140** [comment]
> Good morning,
> 
> Thank you for support @spacecabbie @ywarnier,
> 
> In this configuration file I find the option to hide the block of courses_block, which is on the home page on the left, below profile edit?
> 
> #### [/a> ](#coursesCollapse)
> [ ](#coursesCollapse)
> [ ](#coursesCollapse)
> [ Sincerely.](#coursesCollapse)

**Comment by ywarnier** [comment]
Hi @480419140 
No, you would have to use the overrides technique mentioned by @spacecabbie to hide the courses block
