### ISSUE TITLE
500 Error on BuyCourses plugin

### ISSUE THREAD

**Issue by tian2992** [chamilo/chamilo-lms#2748]
**Describe**
After changes in config on purchase plugin I get 500 error when trying to purchase a course.
The server reports Uncaught Error: Call to a member function getContent() on null at <mychamilo dir>/plugin/buycourses/src/buy_course_plugin.class.php:596

#0 <my chamilo dir>/plugin/buycourses/src/process.php(41): BuyCoursesPlugin->getCourseInfo('2')

**To Reproduce**
1. Install Chamilo
2. Activate BuyCourses plugin
3. Enabled and Disabled payment methods

**Expected behavior**
Purchase screen effectively

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium and Firefox

**Server
 - OS: Linux
 - Version of Chamilo:  1.11.8
 - Version of PHP: 7.2
-  Nginx and FCGI

**Additional context**
It worked out fine until some configs were changed and error then appeared.

**Comment by tian2992** [comment]
Seems it was fixed on 5dd524f6ac52408646cd77df7c26984c45b7060e
Will upgrade to that version...

**Comment by ywarnier** [comment]
The fix is also in the 1.11.x branch: https://github.com/chamilo/chamilo-lms/commit/835d62620a9aa5276765bd6b7299a71f06dca0f7

**Comment by adriano162** [comment]
Na inscrição de usuario em ...chamilo/main/auth/inscription.php apos clicar em REGISTRAR USUARIO, e na tela seguinte em AVANÇAR, deveria ir para a pagina de pagamento do Paypal porem, a pagina fica duplicada da seguinte forma   .../chamilo//chamilo/plugin/buycourses/src/process.php?i=1&t=1  Alguem poderia me ajudar?

**Comment by hostgweb** [comment]
Hi guys,
Congrats for plugin, is nice idea.
I installed Chamilo 1.11.16 and just "Buy Courses plugin"

I used https://pastebin.com/kmisW6bh and
ALTER TABLE plugin_buycourses_global_config ADD COLUMN info_email_extra TEXT;
 and download 2 files in https://github.com/chamilo/chamilo-lms/commit/5dd524f6ac52408646cd77df7c26984c45b7060e
but i have 500 Error, yet
Any suggestion?
