### ISSUE TITLE
servidor chamilo en red LAN

### ISSUE THREAD

**Issue by CesarAToro** [chamilo/chamilo-lms#2749]
Compañeros buenas tardes.

Ante todo me disculpo por introducir estas problemáticas a este plataforma que es dirigido a otros fines.
Pero la verdad he buscado y he escrito en el foro oficial pero no me dan alguna respuesta aun de como lo puedo hacer.
El punto es que estoy en la instalación de chamilo 1.11.8 en windows 8.1 pro x64 bits, con wampserver 3.1.4. que lo componen APACHE 2.4.35,   PHP 7.2.10, y  MySQL 5.7.23

En la instalación local, no he tenido ningún tipo problema, se instala sin errores
Mi interés es compartir, o mas bien que mi servidor sea alcanzado desde cualquier equipo de mi red LAN, para simular chamilo en producción y crear otros usuarios para crear contenidos (cursos).
Como dije anteriormente ya he escrito en el foro oficial pero aun no me dan alguna respuesta que me pueda ayudar. Anexo el link.

https://forum.chamilo.org/viewtopic.php?f=15&t=10775&sid=17dcd27bb3cce7bfa9640297acfc44e0

Los pasos de instalación que he visto, son con versiones de Apache y php anteriores a las que utilizo, ya que he movido la configuración del httpd-vhosts.conf sin ningún resultado.
Espero me puedan ayudar con este problema, y una vez mas me disculpo con ustedes.

gracias

**Comment by ywarnier** [comment]
Creo que no habrás visto esto: https://beeznest.com/es/2016/12/22/como-compartir-chamilo-en-el-aula/

**Comment by CesarAToro** [comment]
Hola @ywarnier muchas gracias por el link, lo revisare y te comento como me fue.

**Comment by CesarAToro** [comment]
Muchas gracias, @ywarnier  seguí los pasos del documento y lo pude resolver.

**Comment by ywarnier** [comment]
Excelente, que te vaya bien !
