### ISSUE TITLE
Add a Page disable editor when making hyperlink.

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#2750]
**Describe**
When making a hyperlink on edit homepage its not always clear that is not a rewrite url for the cms page.
So any content in the editor is lost when saving since it only saves the hyperlink.

**To Reproduce**
1. Go to 'main/admin/configure_homepage.php'
2. Click on 'Add A Page (cms)'
3. 

**Expected behavior**
Recommendation:
Rename to Add a page/hyperlink
Disable editor when a value is entered in the hyperlink field.

**Additional context**
Bug is confirmed for version 1.11.8

**Comment by ywarnier** [comment]
Fair point.
We've updated the term. Thanks for reporting.

![add-a-pag](https://user-images.githubusercontent.com/609839/53928829-8c341000-4059-11e9-826a-b4a249b210ba.png)
