### ISSUE TITLE
Do not open to qualify forum thread after upgrade to 1.11.8

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#2753]
After upgrade from 1.11.4 to 1.11.8, the option to qualify thread is not open and its not possible to put weight or activate qualify. Always set to 0 because the input still display:none.

The file to reproduce error is main/forum/editthread.php

See the screenshot attached below

![error_forum](https://user-images.githubusercontent.com/36703444/49748653-74810180-fc8d-11e8-8a21-66f3b014cf9d.png)

**Comment by fabiowoj** [comment]
I dont make the entire solution, but to make work again is to put the div block always displayable.
the file
/main/forum/editthread.php
on line 129 to 151

`/* Header */
$htmlHeadXtra[] = <<<JS
    <script>
    $(document).on('ready', function() {
        if ($('#thread_qualify_gradebook').is(':checked') == true) {
            document.getElementById('options_field').style.display = 'block';
        } else {
            document.getElementById('options_field').style.display = 'block';
        }
        $('#thread_qualify_gradebook').click(function() {
            if ($('#thread_qualify_gradebook').is(':checked') == true) {
                document.getElementById('options_field').style.display = 'block';
            } else {
                document.getElementById('options_field').style.display = 'block';
                $("[name='numeric_calification']").val(0);
                $("[name='calification_notebook_title']").val('');
                $("[name='weight_calification']").val(0);
                $("[name='thread_peer_qualify'][value='0']").prop('checked', true);
            }
        });
    });
    </script>
JS;`

That way the qualify forum always appear and can be configurable. But not solve the problem of the button. Appear to be a javascript problem, but in my console not appear any error.

**Comment by AngelFQC** [comment]
Hi @fabiowoj I sent a commit to resolve the issue. Please apply the changes on your installation to confirm the solution

**Comment by fabiowoj** [comment]
@AngelFQC, yes, it work. Thanks
