### ISSUE TITLE
Keep track of migration steps

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2754]
**Is your feature request related to a problem? Please describe.**
When upgrading from one version to another, Chamilo keeps a log of the steps it executes, but it doesn't keep a clear reference that the migration process could then use to "start again". We should be keeping a "step number" or something like that during any migration, so that a failure can then be recovered from without having to re-run the whole migration process again.

**Describe the solution you'd like**
Store a "migration step" number for each line executed during the migration. This means adding such number inside the migration scripts *or* considering only one operation per migration method (currently identified by a timestamp).
Also store some value if the migration was completed without error.
This value should be stored in a file rather than the database. Something like chamilo/var/log/upgrade-version.log

Then make sure the migration script can find the previous number

**Comment by christianbeeznest** [comment]
It is added a track of migration steps in this PR https://github.com/chamilo/chamilo-lms/pull/4817 .

**Comment by NicoDucou** [comment]
Tested due to errors in database and restarting the migration it continued from where it stopped and it was possible to find where it stopped.
