### ISSUE TITLE
landscape view course - Mobile

### ISSUE THREAD

**Issue by 480419140** [chamilo/chamilo-lms#2755]
When viewing a skin created in the iSpring software, and exporting the scorm to the chamilo, in the landscape view, the course is appearing in half, a gray element is inserted on top of the training, preventing full screen viewing.

Chamilo LMS 1.11.8

Some help?

**Comment by ywarnier** [comment]
Hi @480419140 
I have no idea of what you are talking about from your description :-)
Could you share a screenshot?
We don't intervene in SCORM content, so unless there is some element of screen resizing that is affecting your course, that might be something coming from iSpring.

**Comment by 480419140** [comment]
Hello @ywarnier , in landscape mode, the training stays with this gray bar, which does not let the training occupy the entire screen.

Below the image.

https://drive.google.com/open?id=1ODveImAFRQ2mdUyYOzPJHbahg2-LkIxB

I also forward a test copy of a scorm content for that analysis.

https://we.tl/t-wqqSsg0vci

Thank you.

**Comment by ywarnier** [comment]
Thanks @480419140, that's a good example. It can work by switching from landscape to portrait and back but it's indeed not working that well. We'll try to do something about it but I'm not sure we can make it for 1.11.10.

**Comment by Haboubi92** [comment]
Hi @480419140
I also use ispring version 9.3.2 (elearning authoring tool) for making elearning content in SCORM format
but I didn't experienced any grey bar
I try it for both Chamilo 1.11.4 and 1.11.8
![photo_](https://user-images.githubusercontent.com/48198054/53741401-5818ed80-3ea7-11e9-83bb-51e25bc90fc7.jpg)

I couldn't download your SCORM file because your link is expired
my email: haboubi92@gmail.com

> Hello @ywarnier , in landscape mode, the training stays with this gray bar, which does not let the training occupy the entire screen.
> 
> Below the image.
> 
> https://drive.google.com/open?id=1ODveImAFRQ2mdUyYOzPJHbahg2-LkIxB
> 
> I also forward a test copy of a scorm content for that analysis.
> 
> https://we.tl/t-wqqSsg0vci
> 
> Thank you.

**Comment by aragonc** [comment]
Apparently after doing internal tests the scorm has loading errors of javascripts. In a few words it is a problem of the file, and as it mentions @Haboubi92 , everything is fine

**Comment by ywarnier** [comment]
Apart from the little syntax issue I mentioned in 9d2f24a, this looks fine from the code perspective.
From a style perspective, the buttons now float on top of the SCORM content, which looks really nice.
At a functional perspective, I just tried a monoSCO and a multiSCO and they worked just fine.

The changes have been applied to https://campus.chamilo.org/ and the example given above is now fixed.
This change is approved for me. We just need some feedback from @480419140 now...

**Comment by Haboubi92** [comment]
@ywarnier 
I tried the new changes in Chamilo Campus
here is an image of the effect on mobile browser (using chrome on android)
![git](https://user-images.githubusercontent.com/48198054/53807671-409e3b00-3f61-11e9-888f-4693dd375298.jpg)
now the SCORM content beautifully take full advantage of the screen
but the expand, home and reporting icons are above the content
unfortunately the slides outline button is underneath these icons, so I have no access for it

this is the SCORM file that I have used (made with third party authoring tool ispring), it has responsive player so try it on mobile device to see the problem
https://drive.google.com/file/d/1LLRqV8ar9doGC_PeW9G7y-lOxO0vRdqK/view 

I also have some suggestion to offer SCORM view with no icons on top
![suggestion](https://user-images.githubusercontent.com/48198054/53808294-ec945600-3f62-11e9-8225-3232a173b18a.jpg)

**Comment by aragonc** [comment]
I made some changes, now it looks like this.

![nuevo_menu](https://user-images.githubusercontent.com/2940509/53829711-c1a00700-3f4e-11e9-9075-0ee747c07a06.png)

![new91](https://user-images.githubusercontent.com/2940509/53829722-c49af780-3f4e-11e9-992d-5a74268cfb94.png)

**Comment by Haboubi92** [comment]
@aragonc 
very Beautiful

**Comment by ywarnier** [comment]
The last commit for this was wrongly registered into another issue.
36d39ecd567daee0de50faff62ccf6939b3867e1

**Comment by ywarnier** [comment]
Approved for me. I have applied the changes to campus.chamilo.org
@480419140 any chance you could check your example course and confirm resolution?
I will close this task in 24h otherwise.

**Comment by 480419140** [comment]
@ywarnier @aragonc 

Good Morning,

Thank you for the dedication of all those involved.

I made the changes in the files below, but now you are not opening the courses.

Is there any way to update my file database with the official files of chamilo?

I downloaded the git repository, but I noticed that the file structure is different, my version is 1.11.8.

Sincerely,

Leonardo

**Comment by ywarnier** [comment]
Hi @480419140 
Could you test it on the campus.chamilo.org, first?
We will release 1.11.10 in a few days, so don't worry too much about updating through Git (which is a complicated process if you've never done it).

**Comment by 480419140** [comment]
Hi @ywarnier , 

I went to campus.chamilo.org, I tested the VETESTISPRING course and it works perfectly after the adjustments made.
Is it possible to inform you step by step how to upgrade my version 1.11.8, since I am being impacted because all my training is performed in Ispring software?

What is the average time to release the 1.11.10 file?

Thanks.

**Comment by ywarnier** [comment]
Hi @480419140 
No, it would take too long to explain because there have been several modifications of the files between 1.11.8 and now, so it's probably not *just* applying the changes in the different commits, and it deviates time we have to work on 1.11.10 to your specific case.
1.11.10 should be released on, or before, the 15th of March.
You can also hire official providers to do the update on your portal for you, but given the short time that remains, it's probably going to take the same time to get into a support contract with a provider anyway, so I suggest you wait and upgrade when we publish 1.11.10.

**Comment by 480419140** [comment]
@ywarnier  Thank you.

Will this version be posted on the site along with the update from previous updates?

Sincerely.

**Comment by ywarnier** [comment]
All of our versions are published on our website.
The installation and upgrade procedures are always available from the download page, through the "Installation guide" button: https://chamilo.org/en/download/

**Comment by ywarnier** [comment]
The upgrade from one minor version to another (1.11.8 to 1.11.10) are usually very easy: just overwrite the previous installation with the new code, then run the "Clear cache" feature from your admin panel.

**Comment by 480419140** [comment]
@ywarnier 

I will be waiting for this new installation.

Thank you very much for your support.

**Comment by AngelFQC** [comment]
Cuando un item de lección tiene un foro asociado, en la vista móvil se ve un margen en la parte superior y desaparecen las pestañas para ver el foro.

Vista escritorio con pestaña para foro:
![Vista escritorio con pestaña para foro](https://user-images.githubusercontent.com/1697880/53899194-a80ec600-4007-11e9-923a-8d4b3e19d618.png)

Vista móvil sin pestaña para foro:
![imagen](https://user-images.githubusercontent.com/1697880/53899414-24a1a480-4008-11e9-9ac3-fe6ecd3ba2e4.png) -- ![imagen](https://user-images.githubusercontent.com/1697880/53899371-10f63e00-4008-11e9-88ef-9eedc91c9cf1.png)

**Comment by aragonc** [comment]
![fix](https://user-images.githubusercontent.com/2940509/53919225-6138c480-4037-11e9-8fa3-9267c147d85b.png)
Super Fix 
![2](https://user-images.githubusercontent.com/2940509/53919298-96ddad80-4037-11e9-888c-ef473713acce.png)

**Comment by ywarnier** [comment]
I've asked @aragonc to move the forum/content tab-icons to the right now, given otherwise the mini-menu would hover above those otherwise (and it's better than having the mini-menu jumping up and down depending on whether there is a forum or not).
![menu-down](https://user-images.githubusercontent.com/609839/53920129-1ff5e400-403a-11e9-87fe-ea4e46d21132.png)

**Comment by ywarnier** [comment]
Looks good to me now. Closing again.

**Comment by AngelFQC** [comment]
There is a little issue in mobile view :) En la esquina superior derecha.

![imagen](https://user-images.githubusercontent.com/1697880/53968176-90e1de00-40c4-11e9-95a4-c7ffe0509245.png)

Replicated here https://11.chamilo.org/main/lp/lp_controller.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=1&isStudentView=true

**Comment by aragonc** [comment]
Cambio enviado 
![fix_mobile](https://user-images.githubusercontent.com/2940509/54050325-e396c500-41ac-11e9-8201-5ec1b5196650.png)

**Comment by AngelFQC** [comment]
Se ve bien
