### ISSUE TITLE
Mixed Content 

### ISSUE THREAD

**Issue by 480419140** [chamilo/chamilo-lms#2756]
Good night, include a proper domain in configuration.php, however some files are being loaded with the address of the server, I would like to know where I locate these notes so that it replaces the old path with the new one?

Mixed Content: The page at 'https://testestes.com.br/main/lp/lp_controller.php?cidReq=TESTE&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=2&isStudentView=true' was loaded over HTTPS, but requested an insecure script 'http://25.68.65.248/lms/main/inc/lib/javascript/jquery.highlight.js'. This request has been blocked; the content must be served over HTTPS.

Chamilo 1.11.8.

Help me please?

**Comment by ywarnier** [comment]
app/config/configuration.php $_configuration['root_web'] should be the right one.
If you have set https://testestes.com.br there but main/inc/lib/javascript/jquery.highlight.js is still being loaded from the fixed IP, it probably means you need to clean the cache. You can find a "clean cache" or "clean archive" link on the main/admin/index.php page.

**Comment by 480419140** [comment]
Hello @ywarnier, yes!
In $ _configuration ['root_web'] is the correct path, however some JS are being loaded by IP.

I did not understand when you informed ""clean archive" link on the main/admin/index.php page.".

What should I do with this file?

**Comment by 480419140** [comment]
error image.

https://drive.google.com/open?id=1YF5iPybCF4COysJlq54ef_WJBDbUDwsh

**Comment by AngelFQC** [comment]
> Hello @ywarnier, yes!
> In $ _configuration ['root_web'] is the correct path, however some JS are being loaded by IP.
> 
> I did not understand when you informed ""clean archive" link on the main/admin/index.php page.".
> 
> What should I do with this file?
> 
> What file lists the system javascript so that I can edit the fixed IP manually?

@480419140  You can look into `template.lib.php`. Methods like `set_js_files` and `setCssFiles` are the responsible to load the js and css
