### ISSUE TITLE
skills.php missing in Reports for HRM

### ISSUE THREAD

**Issue by yourKatharsis** [chamilo/chamilo-lms#2761]
**Describe**
As a human resources manager, when going to Reporting section and 'skills' gives a 'Not Found'-page.

**To Reproduce**
1. Log in as HRM
2. Go to 'my Reporting'
3. Click on 'students', then on 'teacher' and then again 'students' (you are now at .../main/mySpace/student.php)
4. as last Item there is now the button 'skills' (see screenshot)
5. Click on this brings you to .../main/mySpaces/skills.php and the 'Not Found'-page

**Expected behavior**
I'm not sure. I think something like a skill overview should be shown.

**Screenshots**
![skillsissue](https://user-images.githubusercontent.com/29522268/50344925-7a000680-052d-11e9-9cfe-b584655d04bf.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browse rchrome, firefox, edge

**Server
 - OS: Ubuntu 16.04
 - Version of Chamilo: 1.11.8
 - Version of PHP: 7.0.32

**Additional context**
---

**Comment by ywarnier** [comment]
Confirmed. There is a link in student.php that points to skills.php, but the only "skills.php" in the whole system is main/admin/skills.php. Not sure that's where we want the HR guy to go... We will investigate what happened.

**Comment by ywarnier** [comment]
We found a deep history going 4 years back, of an incomplete development that was dropped (but even in its incomplete form, it looks useful), so we will restore that soon.
References:

https://github.com/chamilo/chamilo-lms/commit/41380c91c313dbcbc047657c7a155aeea36d16d6

https://github.com/chamilo/chamilo-lms/commit/eaec0034a9f49af5e8eb0032d0757e42a42d9106#diff-253c27ae68fc3a8ab147fe0607c3a92c

**Comment by AngelFQC** [comment]
> References:
> 
> [41380c9](https://github.com/chamilo/chamilo-lms/commit/41380c91c313dbcbc047657c7a155aeea36d16d6)
> 
> [eaec003#diff-253c27ae68fc3a8ab147fe0607c3a92c](https://github.com/chamilo/chamilo-lms/commit/eaec0034a9f49af5e8eb0032d0757e42a42d9106#diff-253c27ae68fc3a8ab147fe0607c3a92c)

**Comment by AngelFQC** [comment]
his co

**Comment by AngelFQC** [comment]
> References:
> 
> [41380c9](https://github.com/chamilo/chamilo-lms/commit/41380c91c313dbcbc047657c7a155aeea36d16d6)
> 
> [eaec003#diff-253c27ae68fc3a8ab147fe0607c3a92c](https://github.com/chamilo/chamilo-lms/commit/eaec0034a9f49af5e8eb0032d0757e42a42d9106#diff-253c27ae68fc3a8ab147fe0607c3a92c)

The code in these commits exists in `main/social/my_skills_report.php` by this commit 3cf13a775da9d95407767735705c6d0802886381.

I'm fixing the link to my_skills_report.php

**Comment by NicoDucou** [comment]
I just tested it with user ptook/ptook and following the instruction in the issue's description and I get to the page https://11.chamilo.org/main/mySpace/student.php with the Skills button and now it gets to https://11.chamilo.org/main/social/my_skills_report.php so it seems all good.

@yourKatharsis can you confirm that it is all good for you so that we can close this issue for the next release ?

**Comment by yourKatharsis** [comment]
He now redirects to main/social/my_skills_report.php correctly.

Not so nice: The First Click on icon "students" bring you to main/mySpace/index.php?view=drh_students&display=yourstudents .
Then click some other icon and "students" again: main/mySpace/student.php .

One icon brings you to different sites. I think that can be confusing.

**Comment by yourKatharsis** [comment]
@NicoDucou I think it's just a cosmetic change, so we can close that issue.

**Comment by NicoDucou** [comment]
The problem from this issue is fixed, but you are wright there is something wrong in the links for the different icons, so I will open a new issue #2786 about this not to be confusing this task and I close this task. Thanks for your report and answer.
