### ISSUE TITLE
Add help questions for RGPD's boxes in Terms en Conditions' edition page

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2763]
On the page https://11.chamilo.org/main/admin/legal_add.php since 1.11.8 there are new boxes to describe the different part of Terms and Conditions needed to comply with RGPD. To ease the work of the user there should be a list of question to answer to fill every box as in the exemple below.

![image](https://user-images.githubusercontent.com/6579268/50598672-c5aa9c80-0eab-11e9-9a63-e82bb6d37cac.png)

Here is the list of boxes titles and for everyone the questions in english, spanish and french.

Box title | English questions | Spanish questions | French questions | Variable 
------------ | ------------- | ------------ | ------------- | ------------ |
Profile/personal data | What do we consider personal data? | ¿Qué es lo que consideramos datos personales? | Que considérons-nous comme des données personnelles? | $PersonalDataMainQuestion
Personal data collection | Why do we collect this data? | ¿Porqué recolectamos estos datos? | Pourquoi recueillons-nous ces données? | $PersonalDataCollectionQuestion
Personal data recording | Where do we record the data? (in which system, hosted where, accessible for which company that handles the servers, etc.) | ¿Dónde registramos los datos? (en qué sistema, alojado dónde, accesible para qué empresa que se encarga de los servidores, etc.) | Où enregistrons-nous les données? (dans quel système, hébergé où, accessible pour quelle entreprise qui gère les serveurs, etc.) | $PersonalDataRecordingQuestion
Personal data organization  | How are the data structured? (To what extent does the organization of the data protect your security? ... do you have established processes that ensure that a hacker will not be able to collect all the personal data on the first attempt? Are they encrypted?) | ¿Cómo están estructurados los datos? (¿en qué medida la organización de los datos protege su seguridad?... ¿tiene procesos establecidos que aseguran que un hacker no podrá recolectar todos los datos personales en el primer intento? ¿están cifrados?) | Comment sont structurées les données? (Dans quelle mesure l'organisation des données protège-t-elle votre sécurité? ... avez-vous mis en place des processus garantissant qu'un pirate informatique ne sera pas en mesure de collecter toutes les données personnelles à la première tentative? Sont-elles cryptées?) | $PersonalDataOrganizationQuestion
Personal data structure | How is the data structured in Chamilo? (one tab for all the data, it has some categorization / label, ...) | ¿Cómo se estructuran los datos en Chamilo? (una solo ficha para todos los datos, tiene alguna categorización / etiqueta, ...) | Comment les données sont-elles structurées dans Chamilo? (un onglet pour toutes les données, il y a une catégorisation / étiquette, ...) | $PersonalDataStructureQuestion
Personal data conservation | How long do we save the data? (Are there data that expires even though the account is still active? How much time do we save them after the last use of the system?) | ¿Cuánto tiempo guardamos los datos? (¿existen datos que expiran a pesar de que la cuenta siga activa? ¿Cuánto tiempo los guardamos después del último uso del sistema?) | Combien de temps sauvegardons-nous les données? (Y a-t-il des données qui expirent même si le compte est toujours actif? Combien de temps les gardons-nous après la dernière utilisation du système?) | $PersonalDataConservationQuestion
Personal data adaptation or modification | What changes can we make to the data? What changes can be made to the data without affecting the service? | ¿Qué cambios podemos hacer a los datos? ¿Qué cambios se pueden hacer a los datos sin afectar el servicio? | Quels changements pouvons-nous apporter aux données? Quelles modifications peuvent être apportées aux données sans affecter le service? | $PersonalDataAdaptationQuestion
Personal data extraction | For what do we extract data (towards other internal processes) and which data are they? | ¿Para qué extraemos datos (hacia otros procesos internos) y cuáles son? | Pourquoi y-a-il extraction de données (vers d'autres processus internes) et quelles sont ces données? | $PersonalDataExtractionQuestion
Personal data queries | Who can consult the personal data? For what purpose? | ¿Quién puede consultar los datos personales?, ¿Con qué propósito? | Qui peut consulter les données personnelles, dans quel but? | $PersonalDataQueriesQuestion
Personal data use | How and for what can we use the personal data? | ¿Cómo y para qué podemos usar los datos personales? | Comment et pourquoi pouvons-nous utiliser les données personnelles? | $PersonalDataUseQuestion
Personal data communication and sharing | With whom can we share them? In what opportunities? Through what processes (safe or not)? | ¿Con quién podemos compartirlos?, ¿En qué oportunidades?, ¿A través de qué procesos (seguros o no)? | Avec qui pouvons-nous les partager, dans quelles opportunités, à travers quels processus (sécurisés ou non)? | $PersonalDataCommunicationQuestion
Personal data interconnection | Do we have another system with which Chamilo interacts? What is the interconnection process? What are the data exchanged and in what way? | ¿Tenemos otro sistema con el cual Chamilo interactúa? ¿Cuál es el proceso de interconexión? ¿Cuáles son los datos intercambiados y de qué manera? | Avons-nous un autre système avec lequel Chamilo interagit? Quel est le processus d'interconnexion? Quelles sont les données échangées et de quelle manière? | $PersonalDataInterconnectionQuestion
Personal data limitation | What are the limits that we will always respect when using personal data? How far can we go? | ¿Cuáles son los límites que respetaremos siempre al usar datos personales? ¿Hasta qué punto podemos llegar? | Quelles sont les limites à respecter lors de l'utilisation de données personnelles? Jusqu'où pouvons-nous aller? | $PersonalDataLimitationQuestion
Personal data deletion | After how long do we erase the data? (event, last use, contract validity, etc.) What are the elimination processes? | ¿Después de cuánto tiempo borramos los datos? (evento, último uso,  vigencia del contrato, etc.) ¿Cuáles son los procesos de eliminación? | Après combien de temps effaçons-nous les données? (événement, dernière utilisation, validité du contrat, etc.) Quels sont les processus d'élimination? | $PersonalDataDeletionQuestion
Personal data destruction | What happens if the data is destroyed as a result of a technical failure? (unauthorized deletion or loss of material, for example) | ¿Qué pasa si los datos son destruidos como consecuencia de una fallo técnico? (borrado no autorizado o pérdida de material, por ejemplo) | Que se passe-t-il si les données sont détruites à la suite d'une défaillance technique? (suppression non autorisée ou perte de matériel, par exemple) | $PersonalDataDestructionQuestion
Personal data profiling | For what purpose do we process personal data? Do you change the access you have to certain parts of our application? (negative or positive discrimination) | ¿Con qué propósito hacemos un tratamiento de datos personales? ¿Cambia el acceso que Ud. tiene a ciertas partes de nuestra aplicación? (discriminación negativa o positiva) | Dans quel but traitons-nous les données personnelles? Modifiez-vous l'accès que vous avez à certaines parties de notre application? (discrimination négative ou positive) | $PersonalDataProfilingQuestion

**Comment by aragonc** [comment]
Esos campos son extrafields, modifique un poco el code para que sea para todos los ExtraFields en los formularios.

![help_array](https://user-images.githubusercontent.com/2940509/53663850-dcb00580-3c34-11e9-94d9-9cd418178d63.png)

Pero ahora tendras que renombrar tus variables a "PersonalDataCollectionTitleHelp" para que sea una variable de Ayuda aumnete el valor "Help" despues de valor displaytext que se jala de la base de datos.

Reenombra todas las variables  de la siguiente forma.
PersonalDataCollectionTitleHelp
PersonalDataRecordingTitleHelp
PersonalDataOrganizationTitleHelp
PersonalDataStructureTitleHelp
PersonalDataConservationTitleHelp

y asi consecutivamente.

**Comment by ywarnier** [comment]
Looks good to me now.
![rgpd-form](https://user-images.githubusercontent.com/609839/53682988-96f14c80-3cc9-11e9-8aac-65ae8729d75e.png)
