### ISSUE TITLE
works_in_session_report.php

### ISSUE THREAD

**Issue by 480419140** [chamilo/chamilo-lms#2764]
Good evening, is there an option that activates inside the chamilo that allows to export all the information of the students of the sessions at a single time? Or turn the field into multi select?

For the options that I found in the chamilo it is possible to export only one session at a time.

Sessions monitored, assignment report, research.

file that does the query: works_in_session_report.php

version 1.11.x

Sincerely

**Comment by ywarnier** [comment]
Hi @480419140 
We usually avoid this type of massification, but could you give us more info about how you currently get there and be a bit more precise about what you would like? (give us a process to access to the screen, a number of sessions that you have, etc, so we can quantify).
Maybe you can hack the file yourself with a little help? Do you know PHP?

**Comment by ywarnier** [comment]
Closing because of a lack of feedback from reporter @480419140
