### ISSUE TITLE
La variable global $htmlHeadXtra[] no esta cargando en ningún template.

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2765]
**Describe**
No carga ningun JS interno asignado ala variable global $htmlHeadXtra[] dentro de los templates actuales en 2.0

**To Reproduce**
Varias funcionalidades con js se ven afectadas

**Expected behavior**
aunque existe su valor en twig asignado dentro de head.html.twig

**Screenshots**
![exta](https://user-images.githubusercontent.com/2940509/50699456-ebec4b80-1015-11e9-9bbe-2e05c80a19b9.png)

**Additional context**

**Comment by AngelFQC** [comment]
Todo los javascript deberían estar dentro de app.js generado desde webpack

Y de igual forma los css que necesites deberían incluirse en el css de app.css( o como se llame ahora)

**Comment by aragonc** [comment]
osea que hay que pasar todos los js que estan dentro de $htmlHeadXtra[] a app.js?? pero si estos se cargan segun la web no?.

Hay el lidema...

**Comment by AngelFQC** [comment]
No pasar. Sino que deberian haber varios archivos js. Y luego éstos se importan dentro del app.js

**Comment by jmontoyaa** [comment]
Para los archivos "legacy" (dentro de main), la variable debería ser cargada $htmlHeadXtra[ ].
Voy a revisarlo.
Tiene que ir a app.js cosas bien genéricas que son usadas en todas las páginas.

**Comment by ywarnier** [comment]
@aragonc para revisión

**Comment by christianbeeznest** [comment]
Esta corregido con este commit https://github.com/chamilo/chamilo-lms/commit/46e8ea151326d777eff4edb229363f572fbed161
Probado con el código legacy.
