### ISSUE TITLE
Ejercicio HotSpot roto

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2766]
**Describe**
Cuando creas un ejercicio HotSpot, sale error al hacer el siguiente paso de guardar y cargar la imagen.

**To Reproduce**
Crear una pregunta HotSpot, cargar la imagen, clic en el siguiente paso.

**Expected behavior**

**Screenshots**
![hotpot](https://user-images.githubusercontent.com/2940509/50715869-0b529b00-104d-11e9-98cb-010e54ecea24.png)

**Additional context**
![ddd](https://user-images.githubusercontent.com/2940509/50715892-29200000-104d-11e9-8fe6-9bec6b03fdb1.jpeg)

**Comment by ywarnier** [comment]
This is fixed in the master branch. There are still display improvements to be done, but this is something else.
