### ISSUE TITLE
drag question error en js, no arrastable

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2767]
**Describe**
La pregunta relacionada no es arrastablem debido a que solo genera el 1er punto y los demás no

**To Reproduce**
1. Crear una pregunta arrastable para relacionar.

**Expected behavior**
Se rompe la funcionalidad del ejercicio

**Screenshots**
![pregunta_drag](https://user-images.githubusercontent.com/2940509/50780856-fefb5780-1271-11e9-88df-46364189a0d3.png)

**Comment by ywarnier** [comment]
This now works in 2.0
