### ISSUE TITLE
No se pueden crear hilos de foros, error en variable _user

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2768]
**Describe**
Al momento de crear un nuevo hilo de conversación dentro de un foro de curso, este se rompe.

**To Reproduce**
1. Crea una categoria de foro
2. Crea un foro como docente
3. Crea una respuesta o hilo de foro.

**Expected behavior**
A parece pantalla de error.

**Screenshots**
![variable_user](https://user-images.githubusercontent.com/2940509/50782200-649d1300-1275-11e9-9ba4-90b75d68f60f.png)

**Comment by jmontoyaa** [comment]
This issue should be fixed now. Try reinstalling chamilo 2.

**Comment by aragonc** [comment]
El error sigue cuando se crea un 2do hilo del foro.

![user_](https://user-images.githubusercontent.com/2940509/53344904-bfe89a80-38e1-11e9-96b5-822848622794.png)

Ya reinstale Chamilo 2

**Comment by jmontoyaa** [comment]
Debería de funcionar ahora

**Comment by aragonc** [comment]
Problema al responder el hilo
![show_template](https://user-images.githubusercontent.com/2940509/53423951-49ff3480-39b0-11e9-8d88-9ab76e5fb691.png)

**Comment by jmontoyaa** [comment]
Corregido

**Comment by aragonc** [comment]
Ahora si esta bien :+1:
