### ISSUE TITLE
No access to ¨Exercise¨ icon . HELP! 

### ISSUE THREAD

**Issue by aapulido242** [chamilo/chamilo-lms#2769]
Inside a Chamilo Course I have two problems currently. It is urgent, so help is appreciated! 

1. I have students that are unable to access the exercise icon, to take quizzes. The mouse just hovers over it without giving the option of entering into the quiz.  It was working when I first opened the course, so I know I am not imagning things. Tried all the administrative and configuration settings, to no avail. 

2.  I have a separate course and my students are not able to enter. I just created it today and sent out the invites, but the course does not appear to students under their ¨My Courses¨ section.

**Comment by ywarnier** [comment]
1. There is no option in Chamilo to show-but-disable the exercise icon to students. If your exercise has time limits though, then it might appear but not be clickable. Time limits can be modified as teacher in the quiz details.

2. Assuming you do *not* use sessions, then you might want to check the visibility of the course. If the course is visible and accessible to you as teacher, just enter the course, go to "Course settings" and set the visibility to "Private" or "Open". If the students have been subscribed, then they should see it. There is no such thing as an "invite" in Chamilo though, so I'm not sure what you are referring to (you can subscribe them and let them know, or ask them to subscribe by themselves from the courses catalogue). 

Please be more specific in your issues description, separate them in separate issues (so we can consider one closed - when it is - and move on).

Do not hesitate to post images to illustrate your case. There is a template for reporting issues. Please use it. This is out of respect for us providing you free help.

**Comment by aapulido242** [comment]
Thanks so much for your help Ywarnier. I apologize I am a first time user, I meant no disrespect. I will be sure to use the template next time around. Gracias

**Comment by ywarnier** [comment]
Considering it's been a month now, I assume this issue is fixed.
