### ISSUE TITLE
Error al llamar lista de opciones de settings

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2770]
**Describe**
No se puede visualizar el panel administrador 

**To Reproduce**
Click en el menu administrador -> All options

**Expected behavior**
No se visualiza

**Screenshots**
![get_block](https://user-images.githubusercontent.com/2940509/50795355-f750a880-129b-11e9-9041-340f84526fb1.png)

**Comment by AngelFQC** [comment]
Esto está relacionado con tu cambio e956ccb3eba5cd2f6d45e762ad2df0220b2169d6, creo. Porque ya había corregido el index aquí https://github.com/chamilo/chamilo-lms/commit/b03f6816c25b790d6b966eb7efa38640b1186f25 :smiley:

**Comment by aragonc** [comment]
Arreglado enviado en el commit https://github.com/chamilo/chamilo-lms/commit/d83ed00811dee40366933974a10bf13b17232b93
