### ISSUE TITLE
No se puede crear grupos en la herramienta grupo

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2771]
**Describe**
Revisando el modulo de grupos, no se puede crear  grupos

**To Reproduce**
Ir en herramienta grupos,
Crear grupos

**Expected behavior**
Sale el siguiente error en la pantalla.
Cannot use object of type Chamilo\CourseBundle\Entity\CDocument as array

**Screenshots**
![cannet_object](https://user-images.githubusercontent.com/2940509/50840655-003f8980-1331-11e9-8356-e3d1d3780d54.png)

**Comment by AngelFQC** [comment]
@aragonc Ahora debería crear y eliminar grupos normalmente.

**Comment by aragonc** [comment]
Todo bien :+1:
