### ISSUE TITLE
Error al crear documentos de lecciones y crear documentos

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2773]
**Describe**
Al crear un documento de leccion, sale el siguiente error.
Lo mismo pasa para los documentos creados en la herramienta documentos.

**To Reproduce**
Herramientas Lecciones, Crear Leccón, Agregar un documento de lección.

**Screenshots**
![error-lecciones](https://user-images.githubusercontent.com/2940509/50977641-aff73180-14c0-11e9-9af6-e19bc2b54a92.png)

**Comment by jmontoyaa** [comment]
Should be fixed now. Please reinstall chamilo 2

**Comment by aragonc** [comment]
Listo arreglado y comprobado
