### ISSUE TITLE
Error trying to install two plugins when both use main menu tab

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#2775]
**Describe**
I create another plugin using buycourses a base for. 
I use the function construct whit show_main_menu_tab
See below
```
protected function __construct()
    {
        parent::__construct(
            '1.0',
            'Owner',
            [
                'tool_enable' => 'boolean',
                'show_main_menu_tab' => 'boolean',
                
            ]
        );

        $this->isAdminPlugin = true;
    }
```
The problem is, both use custom_tab_1 in DB->settings_current
If remove this option from construct and add manually in DB with custom_tab_2, thats OK.
I cannot find where to specify number of custom_tab, appear not to set next number automatically.

**To Reproduce**
1. Go to Admin/Extensions
2. Install buycourse plugin and other plugin simple with main_menu_tab function
3. See error

**Server
 - OS: XAMPP
 - Version of Chamilo:  1.11.8
 - Version of PHP: 7.2

**Comment by fabiowoj** [comment]
The error is the other plugin create. The installation file is wrong. I fix and no errors at all.
How can i delete this issue?

**Comment by rajeekum** [comment]
Hi Fabio

How did you fix this issue. I am also facing similar issue and because of this my Portal became unstable. Please help.

Raised a new Issue at - https://github.com/chamilo/chamilo-lms/issues/3228
