### ISSUE TITLE
Missing pending surveys menu

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2785]
**Describe**
Error al mostrar encuestas pendientes.

**To Reproduce**
Aparece el siguiente error.
![date](https://user-images.githubusercontent.com/2940509/51499498-8aa7d480-1d98-11e9-8ca3-90e7a5e1df1e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**

**Comment by ywarnier** [comment]
I'm closing this issue and opening a new one as the pending survey screen is completely missing after the redesign.
