### ISSUE TITLE
Error Pantalla en Blanco al Crear un Curso

### ISSUE THREAD

**Issue by Antoniomv** [chamilo/chamilo-lms#2792]
**Describe el problema**
El problema está al crear un curso, me crea el nombre y todos sus accesos, pero a la hora de entrar en la página principal esta se queda en blanco y no puedo ni subir lecciones ni documentos ni absolutamente nada.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a página principal
2. Dar clic crear curso
3.Escribo título y pulso en añadir curso
4.Directamente se queda en blanco al entrar en su página principal.

**Comportamiento esperado**
Carga de las opciones para poder editar y cargar un curso.

**Capturas de pantalla**
simplemente se queda en blanco

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador: Firefox

**Servidor
 - Sistema operativo :  ubuntu
 - Versión de Chamilo:  1.11.0.6
 - Versión de PHP: 7.2

**Contexto adicional**
Leí por ahi que cambiando en parametros de configuración - seguridad los permisos para nuevos directorios a 0755 y los archivos a 0644 se solucionaba, pero sigo teniendo el mismo problema y no se como solucionarlo.

Podrían ayudarme?

**Comment by ywarnier** [comment]
Hola @Antoniomv, pon tu portal en modo de prueba (creo que es la 7ma opción en la página de parámetros de configuración) y vuelve a intentarlo. Deberías ver un mensaje más detallado, pues nosotros con solo esta información no te podemos ayudar.

**Comment by ywarnier** [comment]
Recuerda siempre usar las plantillas al reportar un error, pues las hemos hecho con cariño para guiarte sobre como hacer un reporte útil y te las pasaste por completo, lo cual es frustrante para nosotros.

**Comment by Antoniomv** [comment]
Tiene ustes toda la razón del mundo y le pido mil disculpas.

Lo tengo en modo de prueba(desarrollo), pero no me sale ningún error, simplemente se queda en blanco.

**Comment by Antoniomv** [comment]
he actualizado mi post correctamente, disculpenme de nuevo

**Comment by Antoniomv** [comment]
alguna solución o idea? Les he pedido al hosting que me aumenten el limite de memoria por si pudiera ser ese el problema, pero no se ha arreglado y lo tengo en 256M

**Comment by aragonc** [comment]
Como dice @ywarnier , tienes que activar el modo servidor desarrollo en Chamilo, y probar nuevamente quer error te sale, en vez de la pantalla en blanco que no da mucha información.
Lo puedes hacer en Administración > Parametros de configuración 

![servidor_desarrollo](https://user-images.githubusercontent.com/2940509/52014757-60e46100-24ae-11e9-9add-e18cd6171c77.png)

Pero creo que es con permisos del  del archivo .htaccess donde tiene el RewriteRule y no esta activado el modulo rewrite en tu servidor, pero para mas detalle haz los pasos anteriores para visualizar mejor el error.

**Comment by Antoniomv** [comment]
Gracias por responder @aragonc pero ya lo tenia en modo desarrollador y como le digo, cuando se crea y se traslada a la página principal del curso se queda en blanco, no da ningun error.

Puede que sea lo que usted dice pues en el htaccess el curso se redirecciona a la carpeta inicial, en mi caso es Aula/courses/nombredelcurso en la dirección, pero en el ftp está en Aula/app/courses/nombredelcurso

Voy a probar y digo, gracias!

**Comment by Antoniomv** [comment]
Vale ahora mismo no se que he tocado pero me salen los siguientes errores cuando pulso en pantalla principal.

Strict Standards: date_default_timezone_get(): We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php on line 584

Strict Standards: date_default_timezone_get(): We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php on line 386

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php:584) in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/template.lib.php on line 1568

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php:584) in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/template.lib.php on line 1570

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php:584) in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/template.lib.php on line 1568

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php:584) in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/template.lib.php on line 1570

Warning: Cannot modify header information - headers already sent by (output started at /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/internationalization.lib.php:584) in /homepages/1/d769828605/htdocs/aulasanitaria/aula/main/inc/lib/userportal.lib.php on line 2056


pero es solo ahí, me deja entrar para crear un curso nuevo, y cuando voy a entrar en el curso sale en blanco y sin errores

**Comment by nosolored** [comment]
Hola @Antoniomv

En tu servidor web en la carpeta de log localiza el archivo error.log o error_log (es probable que se llame de otra forma). En él te indica información adicional sobre los errores de tu sitio

`Warning: Cannot modify header information - headers already sent by (output started at `

Si la insertas en un buscador te va a aparecer información al respecto.

Los mensajes del tipo pueden ser debidos a varios factores, entre otros.

- Espacios o líneas en blanco en archivos entre las etiquetas de PHP `<?php y ?>`

- Caracteres que no son UTF-8 al abrir archivos los archivos con editores que no lo soportan.

- Archivos dañados.

Si has modificado los archivos se ha podido insertar caracteres extraños o se ha modificado el php y no se interpreta correctamente.

Un saludo.

**Comment by Antoniomv** [comment]
Lo de los errores era porque metí un php.ini dentro del ftp aparte del que tenia propio el server, lo he quitado y ya no hay errores.

voy a poner una captura de lo que me sucede y todo en modo desarrollador
![1](https://user-images.githubusercontent.com/38557726/52094013-9fb50c80-25bd-11e9-847b-ad4d60b48adb.PNG)
![2](https://user-images.githubusercontent.com/38557726/52094019-a6dc1a80-25bd-11e9-9e34-6de244e47336.PNG)
![3](https://user-images.githubusercontent.com/38557726/52094023-a8a5de00-25bd-11e9-9952-b9b5930f266a.PNG)
![4](https://user-images.githubusercontent.com/38557726/52094026-ab083800-25bd-11e9-8325-2bee8b167e53.PNG)


Como podeis ver sale en blanco al darle a crear curso, pero luego si voy al listado si que aparece.

**Comment by ywarnier** [comment]
Hola @Antoniomv, usar subcarpetas no es un modo recomendado. Es más seguro usar subdominios.
Podrías intentar cargar http://autoniosv.es/aulasanitaria/aula/app/courses/CURSODEPRUEBA/ y ver si te da algún resultado distinto?

**Comment by Antoniomv** [comment]
también sale en blanco usando esa dirección

**Comment by Antoniomv** [comment]
también sale en blanco usando esa dirección

**Comment by Antoniomv** [comment]
hola, acabo de cambiar todo a subdominio y tengo el mismo problema

**Comment by AngelFQC** [comment]
@Antoniomv tienes acceso a los logs de apache de tu servidor? Si lo revisas ahí debería estar el mensaje de error que ayude a ubicar el problema.

**Comment by Antoniomv** [comment]
no, no tengo acceso, estoy con 1and1 (ionos), acabo de instalarlo en otro subdominio diferente, y nada, mismo problema.

**Comment by ywarnier** [comment]
Me parece que ya hemos tenido problemas (por permisos, justamente) con 1and1 (problemas que nos fueron imposibles resolver por la falta de posibilidades).
Hay muchos otros proveedores ahí fuera. Necesitas quedarte con ellos?

**Comment by ywarnier** [comment]
En todo caso, podrías pegar aquí el archivo php.ini, si existe en la raíz de tu proyecto? (me interesa más que todo una línea que dice "display_errors")

**Comment by Antoniomv** [comment]
Muchas gracias a todos por responder.

El problema es totalmente de 1and1 (ionos) , que es donde tengo alojados mis proyectos antes de darselo al cliente o subirlos a otro hosting. 

En este caso lo he subido a un hosting OVH y sin ningún problema, ni página en blanco ni nada de nada.

Menudos días me han echo perder estos de 1and1 y lástima no haber podido comprobar hasta ayer en otro servidor si funcionaba.


Conclusión - Solución = Chamilo no es compatible con el hosting de 1and1

**Comment by opensourcecompany** [comment]
Unfortunately, if you had submitted your ticket in english, i would have told you that before :-(
1&1/Ionos have a special setup for PHP which breaks most applications which are not common for them.
Better switch to a managed server with them or in general another hosting provider. ;-)

**Comment by ywarnier** [comment]
I have sent 1and1 a Twitter message to try and solve this (this is also one of the reasons why we got bad scores in a study in French, because the guy testing could not test fully and would only try on that same hosting provider :angry: )

**Comment by opensourcecompany** [comment]
:-D good luck with this.
We had SEVERAL issues with them, and they were not really interested to solve this.
(it is not really a Chamilo issue; there are many other scripts which can't be run there)
But now they have renamed to IONOS, which should communicate a fresh new brand ;D

**Comment by ywarnier** [comment]
I'm closing this issue because it is not really something related to Chamilo indeed, but I will follow this up and update if I ever get an answer from them.
