### ISSUE TITLE
Self Evaluation Exercise comes with Feedback Modal Screen and Freezes

### ISSUE THREAD

**Issue by visiomart** [chamilo/chamilo-lms#2793]
**Describe**
When you click "proceed with the test" the feedback screen comes up with only the comment not showing whether it is correct or not. It stops there. no button to click continue to next question etc. when you close the modal window it comes back to the same question you had answered still asking you to proceed with the test.

**To Reproduce**
1. Go to 'test'
2. Click on 'a sample self evaluation feedback exercise'
3. Scroll down to 'Click proceed with the test'

**Expected behavior**
It should show whether the option you chose is correct or wrong then give you the option to go to the next question. 

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**
Any swift assistance to this anomaly is deeply favored

**Comment by visiomart** [comment]
I have realized in sessions that the link needed to be clicked on is coming in session as "<br> </a>" I did a follow up on the file exercise_submit_modal and hope you can test this and see the feedback Type Direct Modal is not coming up with the link to continue.

**Comment by visiomart** [comment]
![image](https://user-images.githubusercontent.com/47247026/52166788-d9932980-2709-11e9-9a75-8407e734713d.png)

**Comment by visiomart** [comment]
![image](https://user-images.githubusercontent.com/47247026/52166803-fe879c80-2709-11e9-8f6b-65a53eaa0c20.png)

**Comment by visiomart** [comment]
I have added screenshots of the issue i have with the self evaluation test. it come with comment for correct answers and just come blank with Feedback for wrong answers. no button to continue test. this is on campus.chamilo.org...

**Comment by ywarnier** [comment]
Hi @visiomart,
From the looks of it, you didn't specify an outcome to your question.
When you edit an exercise in "immediate feedback" mode, you are absolutely required to put one type of outcome to each question (at least). If you only have one question, I think the only option you have is "Finish" or something like that.
You have to think about immediate feedback tests as decisional trees. Usually you draw the tree on paper and then set all the possible outcomes for each question from the question edition page.

**Comment by ywarnier** [comment]
Thanks for using our template, by the way. Really makes it much more efficient.

**Comment by visiomart** [comment]
![image](https://user-images.githubusercontent.com/47247026/52195588-87a8eb80-2850-11e9-84c9-59a629842243.png)
![image](https://user-images.githubusercontent.com/47247026/52195631-b0c97c00-2850-11e9-8580-d6001b9dd5ff.png)
![image](https://user-images.githubusercontent.com/47247026/52195641-b757f380-2850-11e9-9c7f-6b9cf5fdb277.png)
Dear Ywarnier,
I have selected the correct question and added comment to all the possible answers including the wrong options but it still comes as it is. if you can help me with the type of outcome to each question option in the program.
Thank you for responding and the firm support.

**Comment by visiomart** [comment]
https://campus.chamilo.org/main/exercise/overview.php?cidReq=TESTING123&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=101273

**Comment by visiomart** [comment]
Dear Ywarnier,
I have finally seen the outcome in the scenario option. if correct then go to next question etc.
Thank you so much for the eye opening.
Cheers,
Martin
