### ISSUE TITLE
Add GeSHi to ckeditor (at least for learning path editor)

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2794]
**Is your feature request related to a problem? Please describe.**
Since this is an official supported addon to CKEditor, it would be very handy to see this in the next release. :-) It is an usefull plugin which offers improvement of usability.

**Describe the solution you'd like**
Add support for syntax highlighting.

**Comment by opensourcecompany** [comment]
It would be in general a good idea to give the admins the possibility to extend the editor to the needs of their platform.
Instead of fumbling around in core files it would be very handy to get them passed by in the admin section or configuration files.
I would prefer the later one since it would be easier to have a single field where all the active plugins are listed which can be activated for which scenario instead of src\CoreBundle\Component\Editor\CkEditor\Toolbar\Basic.php and all the other files.

Sure, "if you know where to look" it is an easy thing, but i have gotten feedback twice now that users are not really satisfied with the way the editor is created and how complicated it is to modify it.

**Comment by ywarnier** [comment]
Agreed. Nice one. We will look into GeSHi. If we manage to get that in time for 1.11.10, then it will be a configuration.php option for now.

**Comment by opensourcecompany** [comment]
GeSHi is already delivered with Chamilo now, but not activated :-)

**Comment by AngelFQC** [comment]
Hi @opensourcecompany 

I've testing geshi with ckeditor in chamilo on my own branch [AngelFQC/chamilo-lms/2794](https://github.com/AngelFQC/chamilo-lms/tree/2794).

But it seems like Geshi plugin for CKeditor, only show the syntax when the content is being edited, but the syntax is not sent when saving the content edited.

![imagen](https://user-images.githubusercontent.com/1697880/53651527-d7db5980-3c14-11e9-8449-c3758c311ee7.png)

![imagen](https://user-images.githubusercontent.com/1697880/53651612-00635380-3c15-11e9-8c7f-ea903122d6e8.png)

I tested Ckeditor out of chamilo with the same result.

**Comment by ywarnier** [comment]
@AngelFQC it looks like you need to include a client-side lib highlight.js or something like that to make it appear for users. Did you try that?

**Comment by AngelFQC** [comment]
@ywarnier No, I don't try with highlight.js because the codesnippetgeshiusar PHP server-side script instead of client-side.
