### ISSUE TITLE
Chamilo Association announcements on top of admin page

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2796]
**Is your feature request related to a problem? Please describe.**
We (the Chamilo Association) need a better way to communicate info to our users (the Chamilo admins).
WordPress does it by having a box at the top of the dashboard or the plugins list, and it feels like a good way (if a little bit upsetting sometimes) to do that. There should be a way to disable it (for professional customer implementations), but not too easy otherwise there's not point in trying to communicate at all.

Admin users who never read the installation of admin manual should not be able to disable it easily, because reading the manual is an expected behaviour from a healthy contributing member of our community.

**Describe the solution you'd like**
In the admin TPL (admin/settings_index.tpl), add a call to an AJAX action (in main/inc/ajax/admin.ajax.php) "get_latest_news" that will get JSON-encoded data from https://version.chamilo.org/news/latest.php?language=english (or any current language).
This will be displayed in a box like this at the top (forgive the bad spacing):
```
<div id="tabs-0" class="settings-block col-md-12">
  <div class="panel panel-default block-admin-chamilo">
    <div class="panel-heading">
      <img src="{ _p.web }/main/img/icons/32/platform.png" alt="Chamilo.org" title="Chamilo.org"> Chamilo.org
     </div>
     <div class="panel-body" style="background-color: lightyellow;">
       <div class="block-items-admin">
{ message }
       </div>
     </div>
   </div>
</div>
```
The option to disable that should go to configuration.php (and should NOT move to settings_current in v2):
```
// Disable Chamilo.org announcements at the top of the admin page
//$_configuration['admin_chamilo_announcements_disable'] = false;
```

**Comment by opensourcecompany** [comment]
:+1:  usefull feature

**Comment by ywarnier** [comment]
Tested and approved. The first announcement points to Chamilo Providers and recommends hiring them. @opensourcecompany make sure you send me the equivalent text in German.
