### ISSUE TITLE
Error 500 al acceder a los foros de un curso

### ISSUE THREAD

**Issue by josegmedina** [chamilo/chamilo-lms#2797]
Al acceder a los foros de cualquier curso de la plataforma, esta me devuelve un error 500. Los ficheros .htaccess están aparentemente correctos. ¿Alguien tiene idea de por qué se puede estar produciendo este problema?

**Comment by ywarnier** [comment]
Gracias por usar nuestras plantillas...
Por favor revisar la plantilla y darnos más información sobre el contexto de tu pregunta (versión de Chamilo, mensajes de error, etc).
