### ISSUE TITLE
Simplify forum post view (remove threaded and flat view)

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2800]
**Is your feature request related to a problem? Please describe.**
Lot of code duplication in different forum views.

**Describe the solution you'd like**
Use one single php file and use a twig to change the UI

**Comment by ywarnier** [comment]
@jmontoyaa do you believe we could include this (as optional) in 1.11.10?

**Comment by jmontoyaa** [comment]
It's already done in ofaj, but I'm waiting it's validated so I can add it in 1.11.x.

@NicoDucou can I do the update from ofaj to 1.11.x already (the forum part) ?

**Comment by NicoDucou** [comment]
The update from ofaj is in process, I assign this task to Julio for the moment because he is doing the update. I will be checking if everything works fine after.

**Comment by jmontoyaa** [comment]
PR merged

**Comment by NicoDucou** [comment]
Revision in progress in BT#15173, will be updated here when finished.

**Comment by NicoDucou** [comment]
All as been validated and work fine, so I close this task.
