### ISSUE TITLE
actualizar y migrar jqGrid + soporte de Bootstrap  a yarn

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2803]
**Tu solicitud está relacionado con alguna molestia? Describe...**
Me siento molesto porque el JqGrid es antiguito y feito, por eso hay que migrarlo a su versión más reciente con soporte para Bootstrap 4 indicado en esta web. esto es para la versión Chamilo 2

https://gijgo.com/grid/demos/jquery-grid-bootstrap

**Describe la solución que te gustaría encontrar**
Migrar JqGrid

**Contexto adicional**
Nada más.. Gracias

**Comment by jmontoyaa** [comment]
Lo de feito, se puede mejorar los CSS no?
Lo de antiguo se resuelve mejorando el aspecto visual.

**Comment by aragonc** [comment]
Me referia a quitarlo del main/inc/javascripts al webpack

**Comment by AngelFQC** [comment]
La útlima versión de jqGrid soporta Bootstrap 4 pero parece que la licencia ahora cambio a CC non-comercial por lo que no podremos seguir usándola en Chamilo.

**Comment by jmontoyaa** [comment]
jqGrid no está siendo actualizado, dudo que exista una versión para webpack.
Como no está siendo soportado no existe soporte para bootstrap, menos lo de responsive.
Pero todo eso se puede mejorar via CSS, por lo menos en la apariencia.

**Comment by AngelFQC** [comment]
https://github.com/tonytomov/jqGrid

**Comment by jmontoyaa** [comment]
no es open source ...

**Comment by aragonc** [comment]
Actualmente este es su licencia http://guriddo.net/?page_id=103334 (Dice sin fines de lucro)

**Comment by jmontoyaa** [comment]
No es open source.

**Comment by aragonc** [comment]
Y si usamos DataTable para los filtros que necesitan en las sesiones? https://datatables.net/examples/api/regex.html

**Comment by AngelFQC** [comment]
Sí, la versión que tiene ahora chamilo 4.6.0 no es MIT / GPL
Pero la última versión 5.3.2 es CC

**Comment by ywarnier** [comment]
Enfocados en soluciones, chicos.
Queremos algo más bonito para la tabla? Sí
Necesitamos absolutamente que sea Open Source y compatible con GPLv3? Sí (las librerías que no lo sean ni siquiera deberían llegar en nuestro historial Git!)
Necesitamos que la solución final permita buscar sobre campos extra field de sesiones? Sí
Necesitamos que sea jqGrid o similar? No necesariamente
Podemos desarrollar un mecanismo en JS que nos permita lanzar filtros para actualizar una tabla HTML? Creo que sí
En este caso, podríamos usar el mismo mecanismo de tablas que en otros lados, pero simplemente usar un pequeño mecanismo de filtro JS adicional? Creo que sí

Entonces concluyo que si no nos funciona jqgrid para todo esto, podemos simplemente ir en la dirección de usar una tabla "normal" (la misma que usamos en lista de cursos y lista de usuarios) y simplemente hackearla un poco para que se pueda refrescar por AJAX en base a una serie de parámetros de filtro.

**Comment by aragonc** [comment]
Esta es la versión Free Actual han echo un fork del otro proyecto https://github.com/free-jqgrid/jqGrid/tree/v4.15.5

**Comment by jmontoyaa** [comment]
Utilizar ese fork me parece mucho más razonable que reescribir todo a otra librería, bien @aragonc ! :)

**Comment by AngelFQC** [comment]
Desde el punto de visual, free-jqgrid no se ve mejor que el jqgrid que tenemos ahora (estándo configurado con Bootrap).
Las letras siguen pequeñas. Y no es responsive.

Se ve así, en local
![imagen](https://user-images.githubusercontent.com/1697880/53207405-a1dd1a80-3601-11e9-92d5-f3c5e8e2c54c.png)

Y @aragonc tendrías que cambiar mucho css

Estoy viendo como configurarlo con webpack y que cargue los archivos de traducción dinámicamente.

**Comment by ywarnier** [comment]
La pregunta es si se puede mejorar/contribuir para hacerlo mejor en upstream y no solo para nosotros, cosa que podamos ser varios en aprovecharlo. @aragonc tiene las competencias para hacerlo responsive y hacer que la letra sea configurable. Quizás el autor original no.

**Comment by jmontoyaa** [comment]
@AngelFQC no faltará algun css? :/

**Comment by AngelFQC** [comment]
@jmontoyaa No, tiene (más o menos) la misma hoja de estilos de jqGrid. Su soporte de bootstrap no es usando exclusivamente los estilos de bootstrap, sino que hace mezcla de jquery ui con bootstrap

Este es el ejemplo https://jsfiddle.net/OlegKi/07ousnfk/

**Comment by AngelFQC** [comment]
free-jqGrid usa las clases de font-awesome 4, por lo que no se ven algunos íconos, ya que en chamilo se usa font-awesome 5

**Comment by ywarnier** [comment]
He clonado el repositorio en https://github.com/chamilo/jqGrid
Como tenemos este problema de los iconos, el problema de los idiomas y el problema del CSS, creo que vale la pena tener nuestro fork y poder hacer unos releases. Luego mandaremos los cambios como un PR al proyecto principal, pero por ahora quiero que puedan avanzar con esto.

**Comment by AngelFQC** [comment]
Falsa alarma para FA5, sí lo soporta :sweat_smile: (Pero es una integración, parcial o algo así)
Estoy enviando el PR #2819  para ir cambiando cada lugar en donde se use jqgrid. Por ahora cambié session_list.php
Y por ahora estoy haciendo los cambios del fork de jqGrid en la rama bs4 https://github.com/chamilo/jqGrid/tree/bs4/

**Comment by AngelFQC** [comment]
![imagen](https://user-images.githubusercontent.com/1697880/53277470-036cba00-36d2-11e9-994d-b8b2c067423d.png)
Falta corregir lo de mostrar HTML también

**Comment by aragonc** [comment]
![frree](https://user-images.githubusercontent.com/2940509/55893904-caec4700-5b7e-11e9-86ff-d68e7e0a1e44.png)
Sigue saliendo error

**Comment by AngelFQC** [comment]
Ahora

![imagen](https://user-images.githubusercontent.com/1697880/55908748-dac85300-5b9f-11e9-85b6-6980c511d6f5.png)

![imagen](https://user-images.githubusercontent.com/1697880/55908992-7fe32b80-5ba0-11e9-8ab1-957fe0918c1c.png)

![imagen](https://user-images.githubusercontent.com/1697880/55909056-a5703500-5ba0-11e9-86ca-f82cf60d800f.png)

**Comment by ywarnier** [comment]
@AngelFQC cual es el status de esto? Fue incorporado en 1.11? en master? Falta algo?

**Comment by AngelFQC** [comment]
> @AngelFQC cual es el status de esto? Fue incorporado en 1.11? en master? Falta algo?

Está en master, pero Julio estuvo cambiando a las tablas de bootstrap-vue.

**Comment by jmontoyaa** [comment]
free-jqgrid será usado para las tablas de 1.11.x que usan jqgrid

**Comment by jmontoyaa** [comment]
Lo de bootstrap-vue es solo para la parte de los Resources en documentos

**Comment by ywarnier** [comment]
Entonces supongo que puedo cerrarla :smile_cat:
