### ISSUE TITLE
Forbidden lp_controller.php

### ISSUE THREAD

**Issue by walterm128** [chamilo/chamilo-lms#2806]
**Describe**
My problem is forbidden  /cursos/main/lp/lp_controller.php or /cursos/main/document/create_document.php in subfolder

**To Reproduce**
1. Go to 'course->Lessons'
2. Click on 'Create New Document'
3.  You don't have permission to access /cursos/main/lp/lp_controller.php on this server.

**Expected behavior**
Create a new document

**Screenshots**
![document](https://user-images.githubusercontent.com/47644901/52817023-65e60a80-3081-11e9-996c-4e4e921e4b2f.jpg)
![document2](https://user-images.githubusercontent.com/47644901/52817024-667ea100-3081-11e9-8707-fdfaef7d4da7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser opera, firefox

**Server
 - OS: Linux c143a.dattaweb.com 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
 - Version of Chamilo:  chamilo-1.11.8-php7
 - Version of PHP: 7.2

**Additional context**
In .htaccess
Add line RewriteBase /cursos/
No change

In configiguration.php added `$_configuration['url_append'] = 'cursos'
No change

Only create document problem.
In paint, upload document, sound file, etc no problem.

**Comment by walterm128** [comment]
Hello, the problen are the web hosting config only.

**Comment by walterm128** [comment]
The problem is fixed by hoting privider.

**Comment by GomezMorales** [comment]
i have the same problem. Any fix?
