### ISSUE TITLE
Learning path prerequisities bug

### ISSUE THREAD

**Issue by michalet** [chamilo/chamilo-lms#2809]
**Describe**
Even when all prerequisites are fulfilled, the material is still locked. The message shown is this:

> This learning object cannot display because the course prerequisites are not completed. This happens when a course imposes that you follow it step by step or get a minimum score in tests before you reach the next steps.

[This seems to be similar, if not identical to an old issue I found on the old tracker.](https://support.chamilo.org/issues/1159)

**To Reproduce**
1. Create a learning path
2. Add two categories
3. Add two items in first category (no prereqs) & four items in 2nd (previous item as prereq)
4. See error for the first item with a prerequisite

**Expected behavior**
Items in the learning path unlock when prerequisites are met.

**Desktop (please complete the following information):**
 - tried on two machines
 - OS: Windows 10 & Windows 7
 - Browser: Opera 54 & Firefox Quantum 65.0.1

**Server**
 - OS: Ubuntu 14.04.5 LTS
 - Version of Chamilo:  1.11.8
 - Version of PHP: 7.3

**Additional context**
I tried it with both admin & learner accounts, no difference. When I recreated the path, everything seemed fine, until I returned to it a bit later and this issue happened again.

**Comment by AngelFQC** [comment]
Can you try replicating it on https://11.chamilo.org?

**Comment by michalet** [comment]
Ok, tried to replicate.

1. Couldn't create a new test in https://11.chamilo.org, message given:

> Sorry, you are not allowed to access this page, or maybe your connection has expired. Please click your browser's "Back" button or follow the link below to return to the previous page.

2. Tried without a test, everything worked as it should.
3. The only thing I can add is that in the "My progress" screen, the first item with prerequisites shows with 0 time and as "incomplete". 
4. I also noticed that the problem is always the first item with prerequisites, so it does not seem to depend on any specific item within the learning path.

Wish I could add more information.

**Comment by ywarnier** [comment]
Assigning to @jmontoyaa for a quick review if anything can be improved on that respect (time = 0 for 1st item) before 1.11.x.
Thanks for reporting.

**Comment by NicoDucou** [comment]
I just create a case here https://11.chamilo.org/main/lp/lp_controller.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=38 login with amann/amann

I created 2 categories and added é items to the first category with no prerequisite, and then created 4 items in the second category and add a prerequisite on the previous item for items 2, 3 and 4 of the second category.

And as we can see in the screenshot below once I got to the first item with prerequisite, which is the second item of the second category I get the item as completed and I got some time registered.

![image](https://user-images.githubusercontent.com/6579268/53952426-f76cf900-40d0-11e9-92fc-94c7bf9d69a1.png)

**Comment by ywarnier** [comment]
OK, so if we don't get a functional procedure from @michalet, we'll just close this task in a few days
