### ISSUE TITLE
Survey - mandatory questions feature

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#2815]
Survey in Chamilo should have option to create mandatory questions.

**Comment by AngelFQC** [comment]
It exists! But only for yes/no and multiple choice types.

See https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/install/configuration.dist.php#L513

**Comment by xam1234** [comment]
@AngelFQC 
Can't find it on 11.chamilo in a test survey ?
![obraz](https://user-images.githubusercontent.com/32258255/53176325-1efe9480-35ee-11e9-948b-80c8195a4919.png)

**Comment by AngelFQC** [comment]
You need activate it in your `configuration.php` file. And running the  indicated database changes above of the line.

**Comment by xam1234** [comment]
@AngelFQC 
Thanks for the anwser.
Wouldn't it be easier to add this option as a extra button in new version when adding questions in the survey?

**Comment by AngelFQC** [comment]
This will be integrated in Chamilo v2, currently master branch
