### ISSUE TITLE
 /main/admin/user_export.php was not found on this server

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2816]
**Describe**
When trying to export users in the backend, a:
Not Found
The requested URL /main/admin/user_export.php was not found on this server.
is thrown.

11.chamilo.org works as expected, so it shouldn't be an always occuring issue.
Installed server is a Debian stable, latest Chamilo, and in other installations there are also no issues.
Is there a specific rewrite or server side module neccessary?

**Comment by AngelFQC** [comment]
Please review your installation files.

The `main/admin/user_export.php` file should exist in this path.

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/admin/user_export.php

**Comment by opensourcecompany** [comment]
File is there :-)
Otherwise it would not be clickable in the admin backend.
The assistant shows up where you can select XML/CSV but when clicking for output...

**Comment by AngelFQC** [comment]
Are you in a sub-directory installation?

**Comment by opensourcecompany** [comment]
Nope.
Finally found the issue: XSendFile should be set up correctly, otherwise Apache is not able to deliver the desired file.
