### ISSUE TITLE
config?cidReq used when loading CKEditor generates error

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2817]
**Describe**
El CKEditor no carga completo sus configuraciones extras (Estilos) por este error.

![ckeditor](https://user-images.githubusercontent.com/2940509/53268775-02795f80-36b5-11e9-9163-fdc16bb072ac.png)

![ckeditor_urlextra](https://user-images.githubusercontent.com/2940509/53268823-1e7d0100-36b5-11e9-9681-a44669a7e3d6.png)

**To Reproduce**
Abrir un CKEditor y inspeccionar el codigo que lo genera.
Este carga el config por medio de un cidReq en su parametro "customConfig":
http://chamilo2.test/public/editor/config?cidReq=INTRODUCCIONALDISENOUX&id_session=&gidReq=&gradebook=&origin=

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**

**Comment by jmontoyaa** [comment]
CKEditor was replaced with tinymce

**Comment by perillas18** [comment]
Deleting the web folder and uploading it again has ended the problem
