### ISSUE TITLE
No se muestran sub categorias y categorias padre, cuando los cursos estan en subcategorias

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2822]
**Describe**
En el catalogo de cursos no se puede filtrar por subcategorias y solo muestra el contenido general de la misma

**To Reproduce**
Cree cursos y asignarlos en sub categorias

**Screenshots**
![categoria](https://user-images.githubusercontent.com/2940509/53528118-a9e00300-3ab6-11e9-9d01-4546c89dfad9.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**
Tiene que ser para Chamilo 1.11.x y Chamilo 2.0

**Comment by ywarnier** [comment]
Quedaban unas vulnerabilidades pero ya están filtradas.
Creo que en la lista de categorías para la creación de cursos deberíamos poner las categorías jerarquizadas pero sin la cantidad de cursos que contienen (para evitar sobrecargar esta lista). Será para otra versión.
