### ISSUE TITLE
PENS

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2824]
**Is your feature request related to a problem? Please describe.**
Since SCORM should be fine with Chamilo 2.0 i wonder if there would be the possibility to have a look at PENS (https://en.wikipedia.org/wiki/PENS_(software) )

**Comment by opensourcecompany** [comment]
Nevermind, since it is solved as a plugin...

**Comment by ywarnier** [comment]
Indeed...
