### ISSUE TITLE
Replace "jtsternberg/oauth1-php" lib

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#2825]
The lib "jtsternberg/oauth1-php" is not updated since 3 years ago, better use an updated library maybe:

https://oauth2.thephpleague.com/
https://github.com/hwi/HWIOAuthBundle

See comments:

https://github.com/chamilo/chamilo-lms/commit/a19db6227ed848bd478c8a344490f444935f1d89#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by jmontoyaa** [comment]
That lib was removed from v2.

The lib to be use is: 

https://github.com/knpuniversity/oauth2-client-bundle

Which integrates the lib https://oauth2-client.thephpleague.com/ in Symfony.

**Comment by ywarnier** [comment]
Related to #2645
