### ISSUE TITLE
Error al subir un scorm o crear una lección en Chamilo

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2828]
**Describe**
Subiendo un zip de scorm aparece el siguiente error, el mismo archivo funciona correctamente en 1.11.x
También ocurre cuando se crea una lección chamilo normal

**To Reproduce**
Descargar y subir scorm de ejemplo.
https://drive.google.com/open?id=1tqnQ4QwRt2AoCmtmnC0iJXCwUGwvTT_-

**Screenshots**
![error_scorm](https://user-images.githubusercontent.com/2940509/53830175-dcbf4680-3f4f-11e9-9b08-2198a792ad47.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**

**Comment by ywarnier** [comment]
Ahora es posible crear una lección y subir un SCORM.
Tested and invalidated. Closing.
