### ISSUE TITLE
Problemas con los usuarios admin

### ISSUE THREAD

**Issue by jcarlosccdev** [chamilo/chamilo-lms#2830]
**Describe**
buenas tardes, tengo problemas para entrar como administrador a mi plataforma chamilo, estube revise la base de datos y efectivamente los ID estan en la tabla de Admin, pero a liniciar sesion solo me aparecen algunas opciones pero no puede administrar la plataforma

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  1.9
 - Version of PHP: 5.6

**Additional context**

**Comment by NicoDucou** [comment]
Hola @jcarlosccdev 
No se puede replicar el problema. Favor de completar el template de reporte de bug porque con lo que indicas no podemos reproducir el problema.
Dejo la tarea abierta unos dias mas y si no hay mas detalles la cerraremos.
