### ISSUE TITLE
No se visualiza certificado en los cursos

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2834]
**Describe**
Cuando se quiere visualizar el certificado, este no se visualiza, parece que no se copia cuando se crea el curso.

**To Reproduce**
Visualizar certificado en gradebook

**Screenshots**
![certificate](https://user-images.githubusercontent.com/2940509/54056823-38433b80-41bf-11e9-8602-37290d08d594.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**

**Comment by ywarnier** [comment]
This is still true in the master branch.
![Capture d’écran du 2022-06-10 11-09-43](https://user-images.githubusercontent.com/609839/173032493-0a004c0f-264c-4e61-8b8e-8135233b0eed.png)

**Comment by ywarnier** [comment]
The certificate can now be *seen* in the courses. There are numerous other issues still (see #5074), but the part of seeing them is now OK
