### ISSUE TITLE
A New Cloze Test Text Field Type

### ISSUE THREAD

**Issue by Elearner2018** [chamilo/chamilo-lms#2836]
Chamilo's Cloze Test Exercise's short text field is useful for tests that have only a few words (sentence 1) that need to be added. When a longer answer e.g. a whole sentence or more words (sentence 2) are needed for the text field, it disappears inside the field and can't be seen before submitting the answer. It is difficult for the student to perceive the whole answer. 

A new Cloze Test Exercise type with a longer text field for exercises that need more words to be written in the text field or even better would be a dynamic field that adjusts to the answer length.

![image](https://user-images.githubusercontent.com/39308234/54083211-5331bf00-4329-11e9-947c-2b7ed436317e.png)

![image](https://user-images.githubusercontent.com/39308234/54083217-72c8e780-4329-11e9-84bd-315c29c7452c.png)

**Comment by ywarnier** [comment]
The dynamic field has been added since this issue was reported (or even earlier, actually)
