### ISSUE TITLE
Creating a new group does not take into account the number of place

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2839]
**Describe**
When Creating a new group, you can enter a number of place for the group, but after you will see that there will always be 8 places.

**To Reproduce**
* As admin create a group here https://11.chamilo.org/main/group/group_creation.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=
* Put 15 places and validate
in the list of group you will see that the group has 8 places
It should have 15 places.

When editing the group the modification of the number of place works in this case.

**Comment by jmontoyaa** [comment]
It's because the default category has a limit of 8 users.

**Comment by NicoDucou** [comment]
You are right.
Sorry for not seeing it :(
