### ISSUE TITLE
Fatal error on master (Chamilo 2) installation

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#2840]
**Describe**

When lunching the installation on the last step of installation (web insterface install) I get this error : 
```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes in /var/www/chamilomaster.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:88 Stack trace: #0 /var/www/chamilomaster.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(88): PDO->query('CREATE TABLE cl...') #1 /var/www/chamilomaster.loc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(908): Doctrine\DBAL\Driver\PDOConnection->query('CREATE TABLE cl...') #2 /var/www/chamilomaster.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/SchemaTool.php(96): Doctrine\DBAL\Connection->executeQuery('CREATE TABLE cl...') #3 /var/www/chamilomaster.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/CreateCommand.php(84): Doctrine\ORM\Tools\SchemaTool->createSchema(Array) #4 /var/www/chamilomaster.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Console/Command/SchemaTool/AbstractCommand.php(70): Doctrine\ORM\Tools\Console\Command\Schem in /var/www/chamilomaster.loc/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/ToolsException.php on line 34
```

**To Reproduce**
Follow the installation's steps indicate on  https://github.com/chamilo/chamilo-lms#quick-install
* git clone https://github.com/chamilo/chamilo-lms.git chamilo2
* cd chamilo2
* composer install (If composer asks to accept recipes, just press enter or "n")
* php bin/console fos:js-routing:dump --format=json --target=public/js/fos_js_routes.json
* yarn install
* yarn run encore dev
* chmod -R 777 .

Then enter the main/install/index.php and follow the UI instructions (database, admin user settings, etc).

In the last step click on finish to launch the installation and it generates this error.

**Server
 - OS: Ubuntu 18.10
 - Webserver : Apache 2.4.34-1ubuntu2
 - Version of Chamilo:  master on 20190311
 - Version of PHP: PHP 7.2.15-0ubuntu0.18.10.1

**Comment by AngelFQC** [comment]
You need then make sure your database supports large prefixes... 

Look https://github.com/chamilo/chamilo-lms#installation-guide-dev-environment-stable-environment-not-yet-available about

**Comment by NicoDucou** [comment]
Thank you, I could finish the installation
