### ISSUE TITLE
Error al abrir un tema en el botón de foro

### ISSUE THREAD

**Issue by jalopezte** [chamilo/chamilo-lms#2844]
**Describe el problema**
He creado un foro social y he iniciado un tema de presentación personal. Solo algunos estudiantes pudieron participar, despues de un tiempo no se puede ingresar y aparece un mensaje de erro ("Fatal error: Uncaught Error:")

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'el icono de foro en el apartado de interacción'
2. Dar clic en 'Foro Social y luego en el tema de presentación personal'
3. Bajar hasta 'el final para realizar la participación'
4. Ver el error que dice 'se abre la ventana con un mensaje de error.'

**Comportamiento esperado**
Se esperaba que el estudiante pudiera ingresar al tema de foro y realizar su participación. Aparece el siguiente URL: https://campus.chamilo.org/main/forum/viewthread.php?cidReq=MATEMATICASIEGRANCOLOMBIAGRADO&id_session=0&gidReq=0&gradebook=0&origin=&forum=50554&thread=48845&search=

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/48501877/54250103-6e125800-4510-11e9-8a65-953ed7de3fb7.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador chrome Versión 72.0.3626.121 (Build oficial) (64 bits)

**Servidor
 - Sistema operativo : Windows 10
 - Versión de Chamilo:  1.11.8
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by jmontoyaa** [comment]
Gracias por reportar este error. Acabo de corregirlo:

https://github.com/chamilo/chamilo-lms/commit/152fddee6306b26189ddcf3c266509e9cd883d30
https://github.com/chamilo/chamilo-lms/commit/dce27340580c769d8a670c46b5385a5d8d755369
https://github.com/chamilo/chamilo-lms/commit/7de3a3499a401fa4bd625b9a363d2e3f257261cb
https://github.com/chamilo/chamilo-lms/commit/5eb426eac640740c00ee502906efb664389b4242

**Comment by jalopezte** [comment]
Gracias por la respuesta, pero no entiendo que hacer con esos códigos. Inclusive ahora desde el icono de foro ya aparece el error con el siguiente URL: https://campus.chamilo.org/main/forum/index.php?cidReq=MATEMATICASIEGRANCOLOMBIAGRAD&id_session=0&gidReq=0&gradebook=0&origin=

![image](https://user-images.githubusercontent.com/48501877/54293481-101c5980-457e-11e9-9b53-2af203e9db47.png)

**Comment by jmontoyaa** [comment]
@AngelFQC tu commit ocasiona esto nuevamente!

**Comment by jmontoyaa** [comment]
@AngelFQC no revertir mi commit por favor.

**Comment by jmontoyaa** [comment]
Corregido con: https://github.com/chamilo/chamilo-lms/commit/4b26ef5a86b9496db0668ccbcec160daa76d2836

**Comment by jmontoyaa** [comment]
Gracias por reportar @jalopezte ahora ya funciona los posts en Chamilo.
