### ISSUE TITLE
Social: See More Posts button doesn't work 

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2846]
**Describe**
The button for "see more" posts in social wall it not working.

**To Reproduce**
Create 6+ posts in social network.
Click "see more" button, on page bottom.
You will see a blank page.

**Expected behavior**
See more posts in social wall

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04]
 - Browser: firefox

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  1.11.x
 - Version of PHP: 7.3

**Comment by NicoDucou** [comment]
The see more post button do not exist anymore. The posts appear as you go down the page, so this task can be closed.
