### ISSUE TITLE
Error para acceder a Foros

### ISSUE THREAD

**Issue by jalopezte** [chamilo/chamilo-lms#2848]
**Describe el problema**
No puedo ingresar a foros porque me sale un mensaje de error.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'icono de foros en el espacio de interacción"
2. Dar clic en '....'
3. Bajar hasta '....'
4. Ver el error que dice 'Fatal error: Uncaught Error: Call to undefined method __TwigTemplate_f3b2484df192395039073450f071c5e9de6ab3687b1e097961418adf0e331216::getpanel() in /furanet/sites/campus.chamilo.org/web/htdocs/app/cache/twig/1/2e/2e500ec9bd543627a21cd79688ad67c9e62118512c1cac9c0611aba123f4ae79.php:408 Stack trace: #0 /furanet/sites/campus.chamilo.org/web/htdocs/vendor/twig/twig/src/Template.php(216): __TwigTemplate_ec7691dc4a4d3f88a559a169e22a067b501ed5978964f6b2faddf9afe650418a->block_content(Array, Array) #1 /furanet/sites/campus.chamilo.org/web/htdocs/app/cache/twig/1/b9/b9c5aa7e2386eded505c1e48549e617b8feb3c8c595835cbdddd5940f3dd479a.php(78): Twig\Template->displayBlock('content', Array, Array) #2 /furanet/sites/campus.chamilo.org/web/htdocs/vendor/twig/twig/src/Template.php(216): __TwigTemplate_7f573a38f1e86df8d0632f98dbe88d998788e5eac77aa6316b50628a70bb4ba1->block_body(Array, Array) #3 /furanet/sites/campus.chamilo.org/web/htdocs/app/cache/twig/1/0b/0b2e4665c830243e079e2b3ffa6c7134dcca38225ff513225f7b8ef9e30555a4.php(279): Twig\Tem in /furanet/sites/campus.chamilo.org/web/htdocs/app/cache/twig/1/2e/2e500ec9bd543627a21cd79688ad67c9e62118512c1cac9c0611aba123f4ae79.php on line 408'

**Comportamiento esperado**
Que se pudiera acceder a participar en los foros
**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.
![image](https://user-images.githubusercontent.com/48501877/54399901-7e504180-468e-11e9-98bc-983a5e6ab15c.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador chrome

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by jmontoyaa** [comment]
Ya está reportado en #2848

**Comment by jmontoyaa** [comment]
Ya debería de funcionar ahora.
