### ISSUE TITLE
Data range doesn't work in Arabic

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2849]
**Describe**
inability to add events in agenda tool using data range when the language is Arabic

this problem is probably  happening in portal news too because it also use data range to set global news.

**To Reproduce**
1. change your language to Arabic and Create new course.
2. in agenda tool (جدول الأعمال or التقويم) click on add event (اضافة حدث).
3. fill event name (عنوان الحدث) and choose any data range (مدى التاريخ) then click on add event (اضافة حدث) button.
4. an error would appear which ask to Validate dates (التحقق من التواريخ).

**Server
 - Version of Chamilo:  1.11.10 on https://11.chamilo.org

**Additional context**
I don't have technical background but I think the problem is because of  the direction of Arabic Numbers format in data range
may be if we force the data range to always use the English format would be a suitable solution.
![arabic](https://user-images.githubusercontent.com/48198054/54480956-c5c9ff80-483f-11e9-92cd-43e3f8f41703.PNG)
![english](https://user-images.githubusercontent.com/48198054/54480957-c6629600-483f-11e9-84ce-87ffbda31877.PNG)

**Comment by AngelFQC** [comment]
I sent a commit to force to save the date range in EN locale (format)

**Comment by Haboubi92** [comment]
I tired it on https://11.chamilo.org
and it WORKED
Thank you so much @AngelFQC  ❤
I think this issue should be closed now
