### ISSUE TITLE
Changing Arabic language flag

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2850]
Arabic language doesn't belong to any specific Arabic country
the current Arabic flag in Chamilo ♥ is the flag of United Arab Emirates which is one of 22 other Arab countries
![f2](https://user-images.githubusercontent.com/48198054/54481210-d465e600-4842-11e9-9cc7-fa738f07fb21.PNG)

so in order to avoid bias to any Arabic country,  I suggest this flag which doesn't represent a specific country, but represent Arabic language in very clear way, it includes a unique Arabic letter (ض) that has a sound only exist in Arabic language.

https://commons.wikimedia.org/wiki/File:Flag_of_the_Arabic_language.svg
![Flag_of_the_Arabic_language svg](https://user-images.githubusercontent.com/48198054/54481207-c3b57000-4842-11e9-8420-20e3b82f4b82.png)

**Comment by ywarnier** [comment]
Thanks. @aragonc please replace the current UAE flag by this one in Chamilo

**Comment by aragonc** [comment]
Se cambio la bandera :+1: 
![cambio](https://user-images.githubusercontent.com/2940509/54623672-ff665a80-4a39-11e9-9a13-68e66f0cc400.png)

**Comment by Haboubi92** [comment]
@aragonc @ywarnier  Thanks  ♥

**Comment by ywarnier** [comment]
This has to be changed at another level. Still working on it...

**Comment by aragonc** [comment]
:confused:

**Comment by jmontoyaa** [comment]
I think it's better to create a PR to this project and add the flag there ... https://github.com/lipis/flag-icon-css

**Comment by Haboubi92** [comment]
I tested it on http://11.chamilo.org
and the flag for Arabic flag has been changed 👍 
thanks everyone 🌹
I suggest closing this issue @ywarnier

**Comment by ywarnier** [comment]
Thanks for the review

**Comment by AngelFQC** [comment]
> PR sent to lipis/flag-icons-css

PR closed :(

https://github.com/lipis/flag-icon-css/pull/538#issuecomment-487147466

**Comment by Haboubi92** [comment]
sorry for reopening this issue @AngelFQC 
but I'd like to report that on https://11.chamilo.org/ the Arabic flag is reverted back to UAE Flag.

![image](https://user-images.githubusercontent.com/48198054/88987757-92c2c780-d2df-11ea-8d1a-b486a220a602.png)

**Comment by jmontoyaa** [comment]
Maybe we should remove the flag from that menu, that menu represents languages and not countries.
