### ISSUE TITLE
check boxes are above text in Arabic

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2851]
check boxes and radio button is always above text (check out the images below)
![a1](https://user-images.githubusercontent.com/48198054/54481508-76d39880-4846-11e9-969d-d9dfe70ebb45.PNG)
![a2](https://user-images.githubusercontent.com/48198054/54481509-76d39880-4846-11e9-822d-154fff22a63e.PNG)
![a3](https://user-images.githubusercontent.com/48198054/54481510-776c2f00-4846-11e9-9dc3-1ae92b7e4b35.PNG)
![a4](https://user-images.githubusercontent.com/48198054/54481512-7804c580-4846-11e9-82b8-c686caa2b14c.PNG)
![a5](https://user-images.githubusercontent.com/48198054/54481513-7935f280-4846-11e9-8656-f3c91c181ce4.PNG)
![a6](https://user-images.githubusercontent.com/48198054/54481514-7935f280-4846-11e9-91d8-814fd2797f74.PNG)

I took these screenshots form various tools inside a course
and I think this problem exist in administration panel too

**Server
 - Version of Chamilo: 1.11.10 on https://11.chamilo.org

**Comment by aragonc** [comment]
arreglado... 
![ddd](https://user-images.githubusercontent.com/2940509/54625182-c976a580-4a3c-11e9-8a6e-c7a9f620c67a.png)

**Comment by aragonc** [comment]
Arreglado en el siguiente commit 

https://github.com/chamilo/chamilo-lms/commit/fe1f86ed49839b90d27fb7ab6f1011db06006dc2

**Comment by Haboubi92** [comment]
Thanks @aragonc  ❤
I tested it on http://11.chamilo.org
and now works perfectly
I suggest closing this issue @ywarnier

**Comment by ywarnier** [comment]
Thanks for the review
