### ISSUE TITLE
For teachers, in courses, classes do not appear

### ISSUE THREAD

**Issue by fgrueau** [chamilo/chamilo-lms#2853]
In My courses, if i am not an administrator, I can't add classes in members of the course.

The problem appear with the 1.11.8 version it does not appear in previous version.

**Comment by NicoDucou** [comment]
I just tested it with user agarcia/agarcia in the course nicod I can see the classes here in the user tool of the course here :
https://11.chamilo.org/main/user/class.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=

I then tested on a local installation and I reproduced the problem.

It comes from this setting :

```
// Teachers can CRUD classes
// ALTER TABLE usergroup ADD author_id INT DEFAULT NULL;
//$_configuration['allow_teachers_to_classes'] = false;
```

This setting is to enable teacher to CRUD classes, but it changed the original behaviour which is to let the teacher see the classes in the user tool of the course.

To try it change app/config/configuration.php to have $_configuration['allow_teachers_to_classes'] = false; on 11.chamilo.org and then log in with user agarcia/agarcia and go to https://11.chamilo.org/main/user/class.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin= and a class should appear in the list.

**Comment by fgrueau** [comment]
Hello Nicolas,

I try on my Chamilo server, i did not find the line “//$_configuration['allow_teachers_to_classes']” in the configuration.php file.
So I add it : no change.
I add the raw to the table “usergroup” : no change.

Do you have an idea ?


De : Nicolas Ducoulombier [mailto:notifications@github.com]
Envoyé : mercredi 20 mars 2019 10:07
À : chamilo/chamilo-lms <chamilo-lms@noreply.github.com>
Cc : GRUEAU Francois <fgrueau@imea.cci.fr>; Author <author@noreply.github.com>
Objet : Re: [chamilo/chamilo-lms] For teatchers, in courses, classes does not appear (#2853)


I just tested it with user agarcia/agarcia in the course nicod I can see the classes here in the user tool of the course here :
https://11.chamilo.org/main/user/class.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=

I then tested on a local installation and I reproduced the problem.

It comes from this setting :

// Teachers can CRUD classes

// ALTER TABLE usergroup ADD author_id INT DEFAULT NULL;

//$_configuration['allow_teachers_to_classes'] = false;

This setting is to enable teacher to CRUD classes, but it changed the original behaviour which is to let the teacher see the classes in the user tool of the course.

To try it change app/config/configuration.php to have $_configuration['allow_teachers_to_classes'] = false; on 11.chamilo.org and then log in with user agarcia/agarcia and go to https://11.chamilo.org/main/user/class.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin= and a class should appear in the list.

**Comment by NicoDucou** [comment]
In your app/config/configuration.php file did you put the line without the comment and with the value true which would be : 

`$_configuration['allow_teachers_to_classes'] = true;`

**Comment by fgrueau** [comment]
I put the value on true, and  now it’s work.

Thank you very very much



De : Nicolas Ducoulombier [mailto:notifications@github.com]
Envoyé : lundi 25 mars 2019 16:30
À : chamilo/chamilo-lms <chamilo-lms@noreply.github.com>
Cc : GRUEAU Francois <fgrueau@imea.cci.fr>; Author <author@noreply.github.com>
Objet : Re: [chamilo/chamilo-lms] For teachers, in courses, classes do not appear (#2853)


In your app/config/configuration.php file did you put the line without the comment and with the value true which would be :

$_configuration['allow_teachers_to_classes'] = true;

**Comment by sadagoban** [comment]
In my case it is working still. 

I added the followings 

//$_configuration['allow_teachers_to_classes'] = true;

configuration.php

**Comment by AngelFQC** [comment]
> //$_configuration['allow_teachers_to_classes'] = true;
`$_configuration['allow_teachers_to_classes'] = true;` Without `//`

**Comment by sadagoban** [comment]
Changed to $_configuration['allow_teachers_to_classes'] = true;

Same issue. Any Suggestions?
