### ISSUE TITLE
responsive images in social wall

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2854]
in Chamilo 1.11.10 (in https://11.chamilo.org)
there is a nice feature in social wall that enable users to upload images
but these images are not responsive on mobile devices
so it would be nice if these images would be resized on small screen
![ezgif-4-6148ba7d2498](https://user-images.githubusercontent.com/48198054/54686248-e0df8c80-4b29-11e9-9bfa-b9ca2683907a.gif)

**Comment by aragonc** [comment]
![movil](https://user-images.githubusercontent.com/2940509/54695600-4155d600-4af8-11e9-906c-7ca1b4a1139a.png)
No solo era arreglar el thumbnail tambien modifique el text area y el btn publicar que estaban descuadrados en movil, y las parte de fecha.

**Comment by Haboubi92** [comment]
I tested it on http://11.chamilo.org
and now all images in social wall are responsive 👍
I suggest closing this issue @ywarnier

**Comment by ywarnier** [comment]
Thanks for the review
