### ISSUE TITLE
hiding Global Chat button from mobile view

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2855]
in Chamilo 1.11.10 (https://11.chamilo.org/)
there is a significant improvement in global chat, clicking on chat button would open friend list, from there you can choose who you want to chat with (it's very similar to Facebook)
but the problem is that you can't use it properly with mobile device (see images below)
![chat2](https://user-images.githubusercontent.com/48198054/54706289-9e30ab00-4b4f-11e9-8201-26d25aa68b34.gif)

![chat3](https://user-images.githubusercontent.com/48198054/54706640-6d9d4100-4b50-11e9-9393-1634c5aa316e.gif)

so I suggest hiding global chat button **only** when accessing Chamilo from mobile

**Comment by ywarnier** [comment]
I agree with your appreciation. I'm just not sure it's the right decision for all users and it's a bit complicated to implement efficiently. We will discuss that internally.

**Comment by Haboubi92** [comment]
@ywarnier this is not critical enhancement
due to my lack of technical background, I have no idea  whether my suggestions are easy to implement or require hundreds of working hours

**Comment by ywarnier** [comment]
@Haboubi92 don't worry, we only work hundreds of hours for major redesigns between major versions or on customer requests ($) :smile:
