### ISSUE TITLE
Settings que sólo existen al actualizar a 1.11.x

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2859]
**Describe el problema**
Los settings `configure_exercise_visibility_in_course`  y `exercise_invisible_in_session` sólo se crean al actualizar a 1.11.x pero en una instalación limpia no existen.

**Cómo reproducir**
En `main/course_info/infocours.php` se obtienen los valores de estos settings relacionados a ejercicios, pero si se tratan de cambiar en el panel de administración, no existen.

Parece que fueron agregados directamente en la migración a 1.11.x pero no están en data.sql para instalación limpia. 

Commit de referencia*
https://github.com/chamilo/chamilo-lms/commit/a79264162dbec5253f2d1545dc279afba57642f5#diff-dc886cdbaa08a5ba33b00fa1d23d50df

**Comment by ywarnier** [comment]
Esto se tiene que poner en data.sql de 1.11 *y* en master, *y* se tiene que colocar un código de verificación en la migración de 1.11 a 2.0 para primero verificar si el setting existe antes de agregarlo.

**Comment by AngelFQC** [comment]
Falta pasar a master

**Comment by AngelFQC** [comment]
Enviado a master
