### ISSUE TITLE
Pagina Inicial no carga el contenido de forma correcta

### ISSUE THREAD

**Issue by fabian50** [chamilo/chamilo-lms#2866]
**Describe el problema**
Al acceder a chamilo desde un equipo de la red, la pagina no carga imagenes y solo aparece texto.
Desde el localhost si se muestra de forma correcta

**Cómo reproducir**
Pasos para reproducir el problema:
realizar logon

**Comportamiento esperado**
desde los equipos de la red la visualziacion deberia ser correcta.

**Capturas de pantalla**
![chamilo](https://user-images.githubusercontent.com/36686605/55209095-e59de380-51ae-11e9-9c23-e9fd6ade13db.JPG)

![image](https://user-images.githubusercontent.com/36686605/55209215-6c52c080-51af-11e9-859b-0c891ad068ec.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : windows 10
 - Navegador chrome, firefox,

**Servidor
 - Sistema operativo :windows 10
 - Versión de Chamilo:  1.11.8
 - Versión de PHP: 7.2.14

**Comment by jmontoyaa** [comment]
No es recomendable instalar chamilo en un subdirectorio. 
Modificando el archivo app/config/configuration.php se puede corregir este problema

`$_configuration['url_append'] = 'chamilo';`

**Comment by fabian50** [comment]
Muchas gracias jmontoya.
cuando dices subdirectorio te refieres a uno del directorio www??. 
He ajustado el parametro que me indicaste ene el archivo y he reiniciado el servidor web y aun asi persiste la falla. Como te comento la falla solo sucede cuando ingreso desde otro equipo en la red, desde el localhost la visualizacion se muestra bien.

Saludos.

**Comment by fabian50** [comment]
Hola, ya he logrado corregor el error, el problema estaba en la instalacion ya que estaba especifincaod como url localhost, la he reemplaado con la IP de servidor y ya funciona de forma correcta

**Comment by ywarnier** [comment]
@fabian50 probablemente esto te pueda servir para cuando cambies de IP: https://beeznest.com/blog/2013/01/15/answering-to-different-addresses-with-chamilo/
