### ISSUE TITLE
Inconveniente al habilitar complemento facebook

### ISSUE THREAD

**Issue by fabian50** [chamilo/chamilo-lms#2867]
**Describe el problema**
He habilitado el complemento de facebook pero al tratar d hacer logon genera error.
existe posibilidad de deshabiltarlo por medio de consola??

**Cómo reproducir**
logon

**Comportamiento esperado**
correcto ingreso

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/36686605/55264929-1bd97280-5244-11e9-9f86-179cd7218c25.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : windows 10
 - Navegador :chrome

**Servidor
 - Sistema operativo :windows 10
 - Versión de Chamilo:  1.11.8
 - Versión de PHP: 7.2.14

**Comment by ywarnier** [comment]
Hola @fabian50 
Como lo activaste? Seguiste las instrucciones en la sección "Facebook" de los parámetros de configuración, o solo activaste el plugin?

**Comment by ywarnier** [comment]
Prueba esto en la base de datos:
```
delete from settings_current where variable = 'login_bottom' and subkey = 'add_facebook_login_button';
```

**Comment by fabian50** [comment]
Mil gracias ywarnier  ya logré solucionarlo con el delete que me indicaste.

Saludos.
