### ISSUE TITLE
can't import user list in Arabic

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2868]
**Describe**
I tied to import user list that contain first  and last name written in Arabic
here is an image of my list

![image](https://user-images.githubusercontent.com/48198054/55356685-fcf10f80-54d3-11e9-996a-c508df28f656.png)

here is the csv file

![image](https://user-images.githubusercontent.com/48198054/55356749-2447dc80-54d4-11e9-8d82-662ef213a4cf.png)

I was able to add the users, but the name in Arabic was not recognized by Chamilo

![image](https://user-images.githubusercontent.com/48198054/55356843-548f7b00-54d4-11e9-9595-0a6dbd7164f0.png)

as a result the user would have no first or last name

![image](https://user-images.githubusercontent.com/48198054/55356921-83a5ec80-54d4-11e9-9eee-7c3676470687.png)

**Server
Chamilo 1.11.10 (https://11.chamilo.org) 

**Additional context**
this is not critical bug since I can add users in Arabic manually without any issue

**Comment by ywarnier** [comment]
I think this is more of a character codification issue. Could you make sure that the file is in UTF-8? If you don't know how to do it, maybe attach the file here and we can review that for you.

**Comment by Haboubi92** [comment]
my csv file was in ANSI  coding
after changing it to UTF-8
It worked!!
![image](https://user-images.githubusercontent.com/48198054/55420490-d7214480-557f-11e9-97f8-b8a5fcea2842.png)

thanks ♥

**Comment by ywarnier** [comment]
No problem
