### ISSUE TITLE
adding right to left text alignment in text editor

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2869]
currently there is only align to left and center options in text editor
so I suggest putting align to right to suit languages which right to left like Arabic
![image](https://user-images.githubusercontent.com/48198054/55391139-6c511880-5541-11e9-9821-1897cfe42883.png)

![image](https://user-images.githubusercontent.com/48198054/55391195-8985e700-5541-11e9-9d80-f70b90b2f62c.png)

**Comment by ywarnier** [comment]
Just sent a fix for that. Sorry, we didn't realize that was a hindrance to RTL writers. Thanks for reporting it.
Whenever needed to keep the size minimal (in the minimal editor bars), I have replaced "Align block" by "Align right". The "Align block" option is still always available in the maximized version of the editor, which I believe is still very natural.
I haven't tested all the interfaces, but I have modified all the corresponding files, so maybe some interface got one additional line of icons with just one icon. This can be fixed along the way and in the worst case we could remove the "center align" option, which shouldn't be used in any proper quick text (meaning with the minimal editor) anyway.

Please review, give us your comments and we'll be able to close it.

**Comment by Haboubi92** [comment]
Thanks @ywarnier  ♥  that was a quick fix!
I tested and it worked fine
I would also like to suggest removing the flash icon form mini editor (because it's old technolgy and won't work on mobile devices or tablets)
![image](https://user-images.githubusercontent.com/48198054/55417193-df29b600-5578-11e9-8ee5-a34fff53bf43.png)
 
I would also like to know the scheduled release date for Chamilo ♥ 1.11.10

**Comment by Haboubi92** [comment]
I think it would be a good idea to include smiley faces in the mini editor
this would suit younger learners who are addicted to use them in other social apps (facebook, whatsup, telegram...etc.)

![image](https://user-images.githubusercontent.com/48198054/55418079-9410a280-557a-11e9-860e-a8d95a3e44f5.png)

**Comment by ywarnier** [comment]
The Flash icon (and the smiley icon) should be 2 separate issues (because they are not as important as the RTL issue and should be treated separately). I'll let you do that when you have time. Thanks for confirming the fix.
