### ISSUE TITLE
add audio from documents in lp

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#2873]
Impossible de joindre un fichier audio à un élément du parcours si celui-ci est dans un dossier. Par contre si le fichier audio est à la racine "Document", pas de problème il est sélectionné mais il ne sera pas lu car il doit être dans le dossier audio pour être lu, le chemin n'est pas pris en compte dans c_lp_item. Si je le déplace vers le dossier "audio" il sera lu parfaitement dans le parcours. 

**To Reproduce**
Créer un fichier audio dans le dossier audio avec l'enregistreur en ligne dans la section Document.
Dans un parcours, sélectionnez un élément, cliquez sur le haut-parleur et en bas dans la section Sélectionner un fichier audio à partir des documents, ouvrez le dossier audio et sélectionnez le fichier audio.
J'obtiens alors ce message: Désolé, vous n'êtes pas autorisé à accéder à cette page, ou votre connexion a expiré. Veuillez cliquez sur le bouton "Précédent" de votre navigateur ou suivre le lien ci-dessous pour retourner à la page précédente.  
Dans la barre d'adresse j'ai : http://chamilo-1.11.8/main/lp/lp_controller.php?action=add_audio&cidReq=AAAAAAA&id_session=0&document_id=85779

Expériementé avec Edge, firefox et chrome...
Sur serveur ubuntu 1604 et en local sur wamp64

**Comment by AngelFQC** [comment]
Which user role are you using to attach the audio file?

Can you replicate the error on 11.chamilo.org?

**Comment by andreboivin** [comment]
Admin.
Impossible to reproduce on 11.chamilo.org, I registered you in my test course. On this chamilo, there is only the learnpath folder that appears to add an audio file from the document. In addition, if I try to upload an ogg file in this folder, I have an error message. See the 2 attached images.
![image](https://user-images.githubusercontent.com/22802716/55955640-eebb9580-5c2f-11e9-94d1-1f63dea9436b.png)
![image](https://user-images.githubusercontent.com/22802716/55955659-f9762a80-5c2f-11e9-9463-3ae0d1c60665.png)

**Comment by andreboivin** [comment]
I realized that the error message appears when the audio file is in a folder. If the file is at the root, there is no error but the audio file is not read because the system expects to see it in the audio folder ...

**Comment by AngelFQC** [comment]
Hi @andreboivin Try updating your chamilo with this new commits. Then move yours audio files to the audio folfer in your documents.

**Comment by andreboivin** [comment]
Yes, it works fine, thank you Angel.
It remains to replace the text and only display the audio folder to prevent people from using an audio file other than those in the audio folder
![audio1](https://user-images.githubusercontent.com/22802716/56736969-6eb92380-6737-11e9-8b97-e493f0add7f5.jpg)

**Comment by AngelFQC** [comment]
:thinking:  The files tree should show you only the audio folder, actually...

![imagen](https://user-images.githubusercontent.com/1697880/56744086-754a9980-673d-11e9-8834-1e8bb5648540.png)

**Comment by andreboivin** [comment]
Ho! Sorry, I skipped a line in lp_add_audio.php. All is ok I close the issue, thank you again.
