### ISSUE TITLE
No se abren los PDF en móvil Android

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#2876]
**Describe**
Esto me ocurre accediendo a mi campus desde un móvil Android. Cuando quiero ver un archivo PDF incluido en una lección, solamente aparece la opción de descargarlo, pero no se ve el contenido en la pantalla. Tampoco hay mensajes de error o advertencia.

**To Reproduce**
1. Entrar a https://uttamayoga.com/campus/index.php desde un móvil Android.
- Usuario: github
- Password: abcd1234
2. Ingresar al curso de prueba (hay uno solo).
3. Intentar abrir el PDF dentro de la única lección.
4. La pantalla de visualización aparece en blanco.

**Expected behavior**
Ver el contenido del PDF en pantalla, además de poder descargarlo.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 6.0.1 - Móvil Galaxy J2 Prime 16G
 - Browser: Samsung 9.2.00.70 y Chrome 73.0.3683.90 (igual respuesta en ambos).

**Server
 - OS: Linux (no sé la versión).
 - Version of Chamilo:  1.11.8
 - Version of PHP: 7.1.28

**Additional context**
Varios alumnos reportan el mismo problema.
No lo probé con iOS.
Consulté en el foro Chamilo, pero no obtuve ninguna respuesta.

**Comment by AngelFQC** [comment]
De momento no hay navegadores móviles que tengan integrado un lectro de pdf como en los navegadores de escritorio.

Pero quizás se pueda integrar viewerjs (que ahora está integrado en la herramienta de documentos) en las lecciones para archivos pdf, sólo para móviles. 
![índice](https://user-images.githubusercontent.com/1697880/56510556-cb2a0200-64ef-11e9-8bdf-6ae05f466478.jpeg)

**Comment by jolufe** [comment]
Muchas gracias Ángel por tu respuesta.
Por el momento le diré a mis alumnos que accedan al campo desde la pc.
Saludos cordiales.
José Luis, desde Argentina.

**Comment by Haboubi92** [comment]
how about uploading your pdf to google drive and making the file public
then you can embed your file via editor (insert html)
you can do that in the document tool
![image](https://user-images.githubusercontent.com/48198054/56557684-b8bdd000-65a4-11e9-86b9-e3714f1d7adf.png)

**Comment by jolufe** [comment]
Thank you very much Haboubi92.
Excellent idea. I'm going to solve it that way.
Greetings,
José Luis.

**Comment by Haboubi92** [comment]
you're welcome ❤
@ywarnier  I think it's time to close the issue

**Comment by jolufe** [comment]
Sorry, you're right. Thank you.
