### ISSUE TITLE
Mejora de Informe detallado de usuario

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2878]

**Comment by aragonc** [comment]
Así quedaría el nuevo reporte de usuario.
![informe](https://user-images.githubusercontent.com/2940509/56249836-dce45300-6072-11e9-9527-a34f01cdc481.png)

**Comment by jmontoyaa** [comment]
Tener cuidado con los issues de performance. Tratar de probarlo en un curso con 200 usuarios o más, para detectar posibles problemas en los queries o en los foreach.

**Comment by aragonc** [comment]
No hice ningun cambio en query solo movi y cambie el diseño de los datos tal como estaba...

**Comment by aragonc** [comment]
![informe_por_estudiante](https://user-images.githubusercontent.com/2940509/56326396-79722800-613b-11e9-9177-beb075e5b0ca.png)
Falta arreglar esta vista por estudiante seguido
