### ISSUE TITLE
Plugin to create a custom exercise

### ISSUE THREAD

**Issue by TmmmmmR** [chamilo/chamilo-lms#2879]
I'm trying to write a plugin to create a custom exercise type for courses.

The developer documentation provide only a guideline on how to introduce new feature without touching the existing ones.

Is there any similar plugin to start with ?

Thanks for your help.

**Comment by ywarnier** [comment]
Hi @TmmmmmR 
Could you be a bit more specific about what you want to do?
Do you want to add a question type or an exercise type?
In both cases, if you want to modify the current behaviour, you should rather try to modify the code and submit a PR (after all, we're open).
A plugin serves more to introduce an independent feature.
