### ISSUE TITLE
making extra field in the registration page as a required field

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2882]
I suggest offering the ability to make extra field  in the registration page as a Required field

![suggestion](https://user-images.githubusercontent.com/48198054/56739676-f2930000-6777-11e9-810c-5e588e771f25.png)

**Comment by ywarnier** [comment]
I believe this already exists but requires a maual configuration in app/config/configuration.php
Maybe @jmontoyaa could confirm?

**Comment by Haboubi92** [comment]
thanks  @ywarnier  ❤

**Comment by NicoDucou** [comment]
Hi @Haboubi92 

In the last Chamilo Version 1.11.10 there is this option :
```
// Set extra fields as required in the inscription.php page
/*$_configuration['required_extra_fields_in_inscription'] = [
    'options' => [
        'terms_ville',
        'terms_paysresidence',
    ],
];*/
```
It should be what you are looking for.

Best regards

**Comment by Haboubi92** [comment]
thanks @NicoDucou  ❤

**Comment by giulianomandotti** [comment]
great to hear! unlikely just tryed but doesn't work on cham 1.11.12... any idea why not?
thanks

**Comment by NicoDucou** [comment]
Hi @giulianomandotti and @ashishkpaul 
What out that it is only for extra fields. Those extra field must have been created by the administrator in the profiling entry of the user bloc in the administration page. The option in the configuration must correspond to the column "Field label" of the extra field and the extra field must be set with the permission "Can be changed by the user".
If you follow the requirements it works fine.
Best regards
