### ISSUE TITLE
Extra fields for test questions

### ISSUE THREAD

**Issue by 22phuber** [chamilo/chamilo-lms#2883]
**Is your feature request related to a problem? Please describe.**
Extra fields can be created for test questions. These extra field do not show up in any question type and can not be used through the Chamilo webinterface.

**Describe the solution you'd like**
Show extra fields for test questions under advanced settings. It should also be possible to display the extra fields in the test results.

**Additional context**
For courses it's already possible to use the extra fields in the course settings
Chamilo Version: 1.11.8

**Comment by 22phuber** [comment]
Related forum post: https://forum.chamilo.org/viewtopic.php?f=52&t=10811&p=35712

**Comment by ywarnier** [comment]
This feature (extra fields for anything else than users, courses and sessions) is mostly available for plugins to extend upon.
This is a nice suggestion, but we won't be able to implement it for 1.11

**Comment by ywarnier** [comment]
I also answered in your forum post, but for development requests we don't work with sponsorship yet (hopefully we'll do that when there is a little bit more people contributing). You can contact official Chamilo providers, however: https://chamilo.org/providers

**Comment by ywarnier** [comment]
This feature was made available in 1.11.12 (in the advanced settings view of each question)
