### ISSUE TITLE
Dashboard plugins

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2884]
Hello.
Chamilo 1.11.10 Beta 1.
In: Test Server.
By clicking on plugins and activating Dashboard plugins.
This error appears.

img1
![Dashboard plugins](https://user-images.githubusercontent.com/25286516/56854733-c8754580-6911-11e9-8128-f62b7289466b.png)

Attempt to replicate at 11.chamilo.org.
It's not possible.

img 2
![Dashboard plugins 11 chamilo](https://user-images.githubusercontent.com/25286516/56854734-d034ea00-6911-11e9-8c04-149198f4c76f.jpg)

**Server vps
 - OS: CentOS Linux 7.6.1810 (Core)
 - Version of Chamilo:  [1.11.10 Beta 1.]
 - Version of PHP: [7.2, ...]

Note: It still installs the plugins.

**Comment by ywarnier** [comment]
@bassuma that was due to an issue with the automated update of 11.chamilo.org. The issue you reported is fixed now. Thanks for reporting!
