### ISSUE TITLE
Create folder in documents

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2885]
Hello.
Chamilo 1.11.10 Beta 1.
In: Test Server.
When going on a course and click on the documents folder.
img1
![doc1](https://user-images.githubusercontent.com/25286516/56855047-9e725200-6916-11e9-9e55-fae75ed20b8c.jpg)

Click on Create folder.
The folder is created but returns with this error:
main / inc / lib / fileUpload.lib.php on line 1726
img2
![doc2](https://user-images.githubusercontent.com/25286516/56855051-a7fbba00-6916-11e9-9173-41e1560cee0d.png)

img3
![doc3](https://user-images.githubusercontent.com/25286516/56855055-ad590480-6916-11e9-9e1e-69717bce48c4.png)

It is not possible to replicate at https://11.chamilo.org.

NOTE: It still creates the folder.

**Server vps
OS: CentOS Linux 7.6.1810 (Core)
Version of Chamilo: [1.11.10 Beta 1.]
Version of PHP: [7.2, ...]

**Comment by ywarnier** [comment]
Thanks for the report! We've found the issue and are working on it now.

**Comment by AngelFQC** [comment]
I sent a commit to fix it

**Comment by bassuma** [comment]
@AngelFQC.
I have already updated the file.
No problem now
greetings

**Comment by ywarnier** [comment]
This also relates to #2887
