### ISSUE TITLE
Problem creating a certificate.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2887]
Hello.
When creating a course in Learning paths.
You click certificate.
After creating it is impossible to edit.
tested at https://11.chamilo.org/
Greetings.

![cert](https://user-images.githubusercontent.com/25286516/56865834-c7dbbe00-69a8-11e9-9a95-593ca4011b29.png)
![erro certificado](https://user-images.githubusercontent.com/25286516/56865835-cca07200-69a8-11e9-8b58-d4499389edbb.png)

**Comment by AngelFQC** [comment]
Commit sent! Fixing the position when creating/editing certificate in LP

**Comment by bassuma** [comment]
@AngelFQC.
I have already updated the file.
No problem now
greetings

**Comment by ywarnier** [comment]
This one also has to be applied:
64b42e92053cfa875cf8c93295dd70e54670349a
