### ISSUE TITLE
Support help on how to proceed.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2889]
Dear Support;
I downloaded the chamilo-lms-1.11.10-beta.1 = Source code (zip) because I use plesk it does not accept final .tar files.
By leaving Chamilo in test server mode.
By creating a learning path.
Creating portal news and back to edit.
Appears warning, I think, that is from php.
Examples in pictures.
1ª Learning paths:
![Learning paths](https://user-images.githubusercontent.com/25286516/56906748-42740e80-6a79-11e9-924d-c6f1bc2dc8f5.png)

2ª  Portal news creating and editing.
![ao criar portal news](https://user-images.githubusercontent.com/25286516/56906774-528bee00-6a79-11e9-92ee-c73976bdf428.png)

![ao ediar portal news](https://user-images.githubusercontent.com/25286516/56906808-633c6400-6a79-11e9-8fd9-354fdf60aa8a.png)

3ª  Notice when editing portal news  at 11.chamilo.org
![testado em chamilo](https://user-images.githubusercontent.com/25286516/56907534-d7c3d280-6a7a-11e9-8394-693e20b699fa.png)

My doubt is:
I must ignore these warnings.
Why be on server test?
Greetings.
Note: I do not have these warnings in chmailo 1.11.8.

**Comment by ywarnier** [comment]
Hi @bassuma 
Chamilo doesn't officially support/cover all "Notice" messages. This being said, we are happy to review the ones your mentioned to have a better stable release. However, you should definitely ignore Notice messages. This can be done by modifying the error_reporting setting of PHP to include & ^E_NOTICE or, in your vhost, adding a "php_admin_value error_reporting 6135" (if you use Apache and mod-php)

**Comment by bassuma** [comment]
@ywarnier.
Many thanks for the reply.
I will proceed as stated above.
greetings

**Comment by AngelFQC** [comment]
It should be fixed now!

**Comment by bassuma** [comment]
@AngelFQC
I updated the file.
And the warnings are gone.
Thank you very much
