### ISSUE TITLE
I can no longer change the profile created for HR

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2892]
Hello.
Yesterday I changed a profile for HR.
To do test.
After the tests I changed the profile again to an administrator teacher.

Today I tried to change the profile of any user for HR.
And I get this warning.

![2019-04-30 (1)](https://user-images.githubusercontent.com/25286516/56965472-c8549000-6b33-11e9-93d7-d0bd4510f19c.png)

![2019-04-30 (2)](https://user-images.githubusercontent.com/25286516/56965479-cb4f8080-6b33-11e9-85a1-406f395b030a.png)

![2019-04-30 (3)](https://user-images.githubusercontent.com/25286516/56965483-cd194400-6b33-11e9-91b9-68caa0a53841.png)

Note: I could not rejoin 11.chamilo.org

Greetings

**Comment by bassuma** [comment]
Hello.
I changed an HR profile.
For 'Student's superior'
By clicking on the Reporting link.
He's getting in trouble.
Like this:
img
![2019-04-30 (7)](https://user-images.githubusercontent.com/25286516/56967228-33539600-6b37-11e9-9c8a-c0618afd1c6a.png)

![2019-04-30 (8)](https://user-images.githubusercontent.com/25286516/56967235-364e8680-6b37-11e9-82af-819348885a87.png)

Greetings

Rating: Tested on 11.chamilo.org

**Comment by bassuma** [comment]
I think I figured out the problem.
When you create the profile as HR.
You can switch to another profile.
Then you want to change back to the HR profile.
You can not.
![2019-04-30 (9)](https://user-images.githubusercontent.com/25286516/56968399-7b73b800-6b39-11e9-9d21-46ecfd7ca582.png)

Rating: Tested on 11.chamilo.org

**Comment by bassuma** [comment]
Hello
The problem in the profile, Student's superior, has been solved.
When you change the files.
https://github.com/chamilo/chamilo-lms/issues/2892
https://github.com/chamilo/chamilo-lms/issues/2892
Thank you

**Comment by AngelFQC** [comment]
The issue reported about to change the user role to HR, is the normal behaviour in Chamilo.
Technically, you can change any user role to HR if and when this user is not subscribed to any course

**Comment by bassuma** [comment]
OK.
Got it.
Once you have created a profile for HR.
You can switch to another.
More will not be able to return to HR.
Right?
Thank you very much for the information.

**Comment by AngelFQC** [comment]
> Once you have created a profile for HR.
> You can switch to another.
> More will not be able to return to HR.
> Right?
No... The user could be again HR if and when the user are not enrolled in courses or sessions

**Comment by bassuma** [comment]
> > Depois de criar um perfil para RH. 
> > Você pode mudar para outro. 
> > Mais não será capaz de retornar ao RH. 
> > Certo? 
> > Não ... O usuário pode ser novamente HR se e quando o usuário não estiver inscrito em cursos ou sessões

Got it.
I tested it here and it worked.
Thank you
