### ISSUE TITLE
Possibilité d'insérer du code dans les questions d'un test

### ISSUE THREAD

**Issue by NouvelleTechno** [chamilo/chamilo-lms#2893]
Lors de la création de questions pour un test relatif à du développement web, il est parfois nécessaire d'insérer du code (HTML, CSS, Javascript...).
Actuellement, ce code est interprété et l'utilisation de la balise code, faîte pour citer justement des extraits de code, ne fonctionne pas.

Serait-il possible d'introduire cette possibilité ?

Merci

**Comment by AngelFQC** [comment]
Related to #2794

**Comment by ywarnier** [comment]
Bonjour @NouvelleTechno 
Comme suggéré par @AngelFQC , cette tâche est liée à une autre enregistrée précédemment. Comme développeurs, nous sommes évidemment très intéressés par le fait de pouvoir faire de la mise en page de code, mais il nous faut pour cela une librairie libre qui s'intègre (de préférence) à notre éditeur en ligne. Une possibilité est Geshi (voir autre tâche), mais celle-ci semble n'afficher la mise en page *que* en mode édition (ce qui ne représente aucune utilité pour l'apprenant de Chamilo).
