### ISSUE TITLE
Add a page/hyperlink

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2898]
Hello.
You can create a page in Add a page / hyperlink.
And add on the menu.
More if you want to put the private page.
It returns a locked page.
And when you try to edit it again.
It erases everything you've done.
I tried to test on 11.chamilo.org
I get one more page with warnings.
greetings

Nota: 1.11.10 Beta 1

![2019-05-04 (4)](https://user-images.githubusercontent.com/25286516/57185056-5ebde400-6e9b-11e9-8029-5ac20addfe1f.png)

![2019-05-04 (1)](https://user-images.githubusercontent.com/25286516/57185052-52d22200-6e9b-11e9-94f7-7ee29843583c.png)

![2019-05-04 (2)](https://user-images.githubusercontent.com/25286516/57185054-59609980-6e9b-11e9-913c-a01226f5b2aa.png)

Optional
Use ::private at the end of the link to show it only to logged-in users
![2019-05-04 (3)](https://user-images.githubusercontent.com/25286516/57185075-6aa9a600-6e9b-11e9-8a53-b544a0d19697.png)

![2019-05-04 (5)](https://user-images.githubusercontent.com/25286516/57185087-75643b00-6e9b-11e9-8969-ea6d105df99f.png)

Test em 11.chamilo.org

![2019-05-04 (7)](https://user-images.githubusercontent.com/25286516/57185092-81e89380-6e9b-11e9-8b38-900f9acb7123.png)

**Comment by bassuma** [comment]
Hello.
Sorry I was putting:
private
In the wrong place.
greetings

note: in 11.chamilo.org even changing appears the same page with warnings.

![2019-05-04 (9)](https://user-images.githubusercontent.com/25286516/57185202-857d1a00-6e9d-11e9-8904-c373371b555d.png)

**Comment by bassuma** [comment]
Hello.
The Good would be if you could create sub links
Passing the mouse would appear the links to cliclar.
Example:

![links](https://user-images.githubusercontent.com/25286516/57185292-e822e580-6e9e-11e9-8217-4e7fe9422345.jpg)

**Comment by ywarnier** [comment]
I'm not big fans of submenus. The example of the language switcher is a bad example: not a default option and should never be used with more than 3-4 languages.

There is a lot of talk about usability and accessibility of submenus. One example here https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/

We're a learning application, not a CMS, so having many submenus would just be opening the door to a complexification of the interface, in my opinion.

**Comment by bassuma** [comment]
@ywarnier
OK.
Got it.
So here is only the problem that is on 11.chamilo.org.
Thank you

**Comment by ywarnier** [comment]
That was a permissions issue on that server. Fixed.

**Comment by bassuma** [comment]
OK.
I went to test this one without problems ..
Now deleting the created links.
They remain fixed on the flap.
This only happened with the old links.
New links delete without problem
![deletar](https://user-images.githubusercontent.com/25286516/57197976-d2b3c700-6f43-11e9-816f-3cea438f5931.png)

![links fixos](https://user-images.githubusercontent.com/25286516/57197977-d6474e00-6f43-11e9-9898-571d4f805b11.png)

**Comment by bassuma** [comment]
NOTE: In 1.11.10 beta you do not experience this problem.
Working perfectly.

**Comment by ywarnier** [comment]
It depends on your language. When removing them, ensure you are in the right language.
