### ISSUE TITLE
custom pages support

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2899]
Hello.
I followed all the steps to enable the custom pages option.
But by going to the login page.
It goes unformatted.
Does anyone have this problem too?
Would it be possible to leave functional for chamilo 1.11.10?
Thank you

![cust](https://user-images.githubusercontent.com/25286516/57200182-cee16e00-6f5e-11e9-8a8a-eb89b3219f02.png)

![2019-05-05 (3)](https://user-images.githubusercontent.com/25286516/57200183-d30d8b80-6f5e-11e9-9b1b-5f6a95bba1c4.png)

![login](https://user-images.githubusercontent.com/25286516/57200184-d86ad600-6f5e-11e9-942f-165fa2bf4e63.png)

**Comment by fabiowoj** [comment]
This php is only for your understand how to do it. Create your own login page, and user all the specifications of this example file. Take a look the url of your CSS.
