### ISSUE TITLE
v1.11.10: Wrong german translation in Administration tab 

### ISSUE THREAD

**Issue by 22phuber** [chamilo/chamilo-lms#2902]
**Describe**
Administration tab: Snack bar message at the bottom has wrong Umlaute
=> mixed umlaute, some are correct others have `^` instead of `¨`

**To Reproduce**
1. Fresh installation of chamilo lms 1.11.10
2. First login as admin in German
3. Administration tab: Snack bar message at the bottom has wrong Umlaute

**Expected behavior**
The text should be: 
```
Haben Sie ein Problem? Benötigen Sie Hilfe, oder wünschen Sie sich ein bestimmtes Feature? Die Nachhaltigkeit des Chamilo-Projekts ist nur dank Beiträgen einer kleinen Anzahl außergewöhnlicher Personen von einigen wenigen Unternehmen möglich, die sich mit dessen Entwicklung befassen. Diese Personen sind EXPERTEN in allem, was mit Chamilo zu tun hat, von E-Learning-Beratung bis hin zu Cloud Hosting, von Kursdesign über Chamilo-Training bis zu kundenspezifischen Entwicklungen. Wenn Ihre Organisation Chamilo nutzt und professionelle Unterstützung benötigt, ist die Zusammenarbeit mit einem dieser Unternehmen die beste Entscheidung die Sie treffen können. Sie erhalten dadurch alle Services die Sie benötigen mit einem zertifizierten Qualitätsniveau und dadurch auch ein beschleunigtes Wachstum Ihrer Plattform. Entscheiden Sie verantwortungsvoll und kontaktieren Sie einen offiziellen Chamilo Provider.
```

**Screenshots**
<img width="1154" alt="Bildschirmfoto 2019-05-08 um 20 30 12" src="https://user-images.githubusercontent.com/17426101/57400147-25ef7900-71d3-11e9-8b03-6cbffc2e3d84.png">

**Desktop & Server (please complete the following information):**
 - OS X mojave (10.14.4) with docker-compose setup from https://github.com/22phuber/docker-compose-chamilo-lms

**Browser**
- chrome 
- firefox
- safari
(all latest stable releases)

**Additional context**
I also changed some sentences in the provided text above.

**Comment by ywarnier** [comment]
Hi @22phuber thanks for the report. We've just prepared the packaging so it's a bit too late to report it for this version (it's been in beta for a week), but I will fix it in the language package so it's on for the next version (in a few months).

**Comment by 22phuber** [comment]
Hi @ywarnier
Sadly i didn't found time to check out the beta release.
I just wanted to report this because it was the first thing i saw. Maybe you can point me to the right place to fix this on my own next time.. cause i'm not that familiar with the code and language package you mentioned.

**Comment by ywarnier** [comment]
Nevermind, this should work now. The message comes from our server.

**Comment by 22phuber** [comment]
oh i see. thank you.
