### ISSUE TITLE
Upgrade breaks installation from 1.11.8

### ISSUE THREAD

**Issue by opensourcecompany** [chamilo/chamilo-lms#2903]
**Describe**
AAfter upgrade from 1.11.8 with package for PHP7, the campus is throwing an error 500

**Server
Debian latest
Chamilo latest 1.11.10 PHP7 release tar.gz
PHP7.0 Debian default

**Additional context**
[Tue May 07 09:41:32.325968 2019] [proxy_fcgi:error] [pid 9787:tid 140274713954048] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function generate() on null in /var/www/main/inc/ajax/form.ajax.php:19\nStack trace:\n#0 {main}\n  thrown in /var/www/main/inc/ajax/form.ajax.php on line 19\n', referer: http://localhost/main/auth/inscription.php
[Tue May 07 10:34:55.033666 2019] [proxy_fcgi:error] [pid 9789:tid 140274831451904] AH01071: Got error 'PHP message: An exception occurred while executing 'SELECT * FROM c_course_description\n                WHERE c_id =  AND session_id = 0\n                ORDER BY id':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND session_id = 0\n                ORDER BY id' at line 2\n', referer: http://localhost

**Comment by ywarnier** [comment]
The query is missing a c_id. Is it possible you're doing something strange between two tabs in two different courses?

**Comment by ywarnier** [comment]
We do not support PHP 7.0 anymore (the package is for PHP 7.1 as explained in the intro) but that should be the issue here

**Comment by ywarnier** [comment]
I see you're using fcgi. Are you using the .htaccess redirections or are you adding these in your web server configuration? (if so, did you adapt them to this new version)

**Comment by opensourcecompany** [comment]
First of all, Debian OS is a widespread system running Apache as webserver. And unfortunately PHP7.0 is the default version.
This means, we get A LOT of bugged systems.

No, the .htaccess should get parsed by apache by default, PHP-FPM running.

**Comment by ywarnier** [comment]
Well, PHP 7.0 is completely unsupported by PHP (https://php.net/supported-versions.php), so this is a Debian decision that affects security. We use Debian for a lot of servers too, but their support of PHP is lacking, so we use ondrej's repositories https://deb.sury.org/ (you should too).

**Comment by ywarnier** [comment]
Can you enter the admin panel of your Chamilo, or is that completely blocked by the error above?

**Comment by opensourcecompany** [comment]
Completely blocked.
And yes, i know about the PHP security problems, but we should keep in mind: other users see it is broken -> Chamilo is not working.
They don't realize it is a server issue. :-(

**Comment by ywarnier** [comment]
I don't think this is a PHP 7.0-related issue. I did mention it.

This comes from here:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/course_description.lib.php#L88

The error suggests $this->course_id is not defined *and* api_get_course_int_id() returns an empty result, which suggests your current user has (for some reason) a "_real_cid" para in its session that is empty (which should not happen).

Could you load http://localhost/index.php?logout=logout ? This will log you out of your account, which might be having a stale state...

**Comment by ywarnier** [comment]
Checking the differences between 7.0 and 7.1 (https://www.php.net/manual/en/migration71.php), there is little chance this would prevent using 7.0 anyway.

**Comment by ywarnier** [comment]
Oh, and feel free to send us more of your error_log if there is any change in there. That helps understand the issue.

**Comment by ywarnier** [comment]
I'm closing this issue. We could not reproduce it in anyway and you've not reported any additional information in several days. Julio sent something that might help you (not sure). Feel free to re-open if you can provide more info.
