### ISSUE TITLE
Chamilo multiple Developers

### ISSUE THREAD

**Issue by korderoman** [chamilo/chamilo-lms#2904]
Hi I trying to install a chamilo platform with multiple developers, i am newbie about chamilo, my team trying to make   the roles  (students, teachers and administrators)  in differents branches and when we are satisfied merge this branches, but  it's possible work this way with chamilo?, we have a doubt about the how to update the database o maybe we can't see some other problems

**Comment by fabiowoj** [comment]
Hello Korderoman, the roles is a little fixed roles, i think in next versions could be to set new roles, i don't think i understand you question. To update database, use functions already have in main/inc/lib/database.lib.php
Like Database::fetch_row($result)
To see others api, go to main/inc/lib/api.lib.php
If is not the answer you need, tell us.

**Comment by ywarnier** [comment]
No additional feedback (it's been a year). Closing.
