### ISSUE TITLE
  Help with the chamilo maintenance plugin

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2905]
Hello.
Please.
I need help with maintenance plugins.
I follow the steps that are informed.
Copy the admin ip.
But after activated.
Already tried.
https: // ip number
https: // domain / ip
https: // ip: 8080
only the ip in the browser bar
I no longer have access to the platform.
I have to go the server is edit the .htaccess.
To disable the plugins.
I went to 11.chamilo.org to see if it was the same ip.
But.

![2019-05-16](https://user-images.githubusercontent.com/25286516/57854880-aad42700-77bf-11e9-85bf-83978652b2a3.png)

This one has problems with 11.chamilo.org.
Greetings.
nota: chamilo v1.11.10  php 7.3

**Comment by jmontoyaa** [comment]
I just run "composer update" now it should work in 11.chamilo.org

**Comment by bassuma** [comment]
@jmontoyaa.
Hello.
11.chamilo.org problem.
sorted out.
But I'm afraid to activate the plugins.
Even though .htaccess  is not recordable.
Could you tell me how to access with ip?

![2019-05-16 (2)](https://user-images.githubusercontent.com/25286516/57855894-2040f700-77c2-11e9-88bc-bd6852a9a321.png)

**Comment by NicoDucou** [comment]
Hi @bassuma 
The maintenance plugin is to block access to the plateform to all user except for the specific IP that you specify in the administration page of the plugin.
So in your navigator you do not need to change anything, you still have access to the same plateform.

When you get to the configuration page of the plugin by defaut it sets the configuration with you IP, but then you can edit the bloc htaccess to put a different IP if needed.

Then in the maintenance box you can put the message that all the user coming from a different IP than the one you set in the htaccess box will see when getting to your plateform.

Best regards

**Comment by bassuma** [comment]
> Oi @bassuma
> O plugin manutenção é bloquear o acesso ao plateform para todos os usuários, exceto para o IP específico que você especificar na página de administração do plugin. 
> Então no seu navegador você não precisa mudar nada, você ainda tem acesso ao mesmo plateform.
> 
> Quando você chegar na página de configuração do plugin, defaut configura a configuração com seu IP, mas você pode editar o bloc htaccess para colocar um IP diferente, se necessário.
> 
> Em seguida, na caixa de manutenção, você pode colocar a mensagem informando que todo o usuário vindo de um IP diferente daquele que você definiu na caixa htaccess verá ao chegar ao seu plateform.
> 
> Cumprimentos

Hello
@NicoDucou.
As you can see in the picture.
I follow every step.
Do not mess with anything.
After activating the plugins.
I also lose access as an admin.

![conf1](https://user-images.githubusercontent.com/25286516/57941462-6a4ed900-78a5-11e9-90b5-be2cc7a8dc5a.png)

![conf2](https://user-images.githubusercontent.com/25286516/57941467-6d49c980-78a5-11e9-9728-a755d67a3d98.png)

![img01](https://user-images.githubusercontent.com/25286516/57941500-7c307c00-78a5-11e9-885a-c3983bf23ed2.png)

![semacesso](https://user-images.githubusercontent.com/25286516/57941504-7e92d600-78a5-11e9-84b5-ffcd919ebebf.png)

**Comment by NicoDucou** [comment]
It works perfectly for me, so it must be a problem with the IP.
Our you sure your IP is 201.92.184.35 when you are accessing you Chamilo Plateform ?
You can check it by going to https://www.whatsmyip.org/ and verify that your IP correspond to what you put in the configuration of the plugin in the htaccess field.

**Comment by bassuma** [comment]
Hello.
@NicoDucou.
unhappily for me it does not work.
Yes I have already verified my ip with:
https://www.speedtest.net
http://www.meuip.com
etc.
Of course my ip is dynamic.
If I reboot the modem it changes.
Oh, just go htaccess and change.

### @@ This part was generated by the edit_htaccess plugin @@ ##
RewriteCond% {REQUEST_URI}! /Maintenance.html$
RewriteCond% {REMOTE_HOST}! ^ xxx \ .xx \ .xx \ .xx
RewriteRule \. * $ /Maintenance.html [R = 302, L]
### @@ End @@ ##
  Activating the plugin loses access too.
Thank you

**Comment by bassuma** [comment]
Hello
I'm closing this ticket.
Because it can not be played on 11.chamilo.org.
Thank you
