### ISSUE TITLE
Error al subir un ejercicio en formato xls con una respuesta en blanco

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#2907]
**Describe el problema**
Al subir un ejercicio de respuesta única en formato xls, si una respuesta quedó accidentalmente vacía, por ejemplo "Answer2;;" devuelve un mensaje Error 500 y crea el ejercicio truncado. 

**Cómo reproducir**
Pasos para reproducir el problema:
1. Crear un ejercicio en formato xls con varias preguntas de respuesta única.
2. Dejar una de las respuestas en blanco "AnswerXX;;", por ejemplo en la pregunta número 4.
3. Cargar el ejercicio en Chamilo.
4. Devuelve "Error 500", sin ningún otro detalle.
5. Chamilo crea el ejercicio parcialmente, sin ninguna advertencia, hasta la pregunta anterior, en este ejemplo hasta la pregunta número 3.

**Comportamiento esperado**
Dos opciones:
1) Que no cree el ejercicio y devuelva un mensaje explicativo del error, dentro de la plataforma. 
2) Que cree el ejercicio completo con una respuesta vacía y un mensaje de advertencia para completar manualmente la respuesta dentro de Chamilo. 

**Capturas de pantalla**
![2019-05-17 11 43 12 uttamayoga com 1370a32a79d8](https://user-images.githubusercontent.com/40075497/57985236-648afc00-7a3b-11e9-8d70-42cd467658bf.jpg)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 7 Service Pack 1 Build 7601
 - Navegador: Vivaldi | 2.5.1525.40 (Stable channel) (32 bits)

**Servidor**
 - Sistema operativo : Linux (no sé cuál es la distribución)
 - Versión de Chamilo:  1.11.8
 - Versión de PHP: 7.2.7

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
Hola @jolufe 
Tienes acceso a los logs de error de tu servidor web? (el error 500 debería haber dejado otros mensajes en los logs)
O en todo caso, puedes compartir el Excel que usas (puedes cambiar el contenido para más privacidad si quieres, pero asegúrate que siga generando el error).
También te informo que tenemos publicada (aunque no promocionada todavía) la versión 1.11.10 en la cual se hicieron cambios en la importanción por Excel, así que quizás resuelva tu problema sin que hagamos nada. La puedes probar en https://11.chamilo.org/

**Comment by jolufe** [comment]
Hola @ywarnier 
Gracias por responder. Tengo acceso parcial al servidor web. No encontré ningún log de error. Consulté con mi proveedor de hosting y me respondió que no se registran errores en el server al la hora que realicé las pruebas. 
Al principio no me había dado cuenta de que faltaba el texto de una respuesta. Cuando lo encontré, la completé y el error no apareció más.
Adjunto el archivo xls tal como es. La respuesta en blanco está en la línea 66. Volví a probar y generó el error.
¿Qué usuario y contraseña se utilizan en el servidor de prueba de Chamilo? No pude acceder.

Un cordial saludo.
José Luis.

[ejercicio-para-prueba.zip](https://github.com/chamilo/chamilo-lms/files/3195595/ejercicio-para-prueba.zip)

**Comment by ywarnier** [comment]
Puedes usar admin/admin. Es un sitio de desarrollo.

**Comment by jolufe** [comment]
Muchas gracias.

**Comment by ywarnier** [comment]
Debido a la falta de feedback, supongo que este problema se arregló de alguna manera. Cierro la tarea.
