### ISSUE TITLE
Ticket only appears for admin.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2909]
Hello
After activating the ticket.
And set up for students to create tickets.
The ticket only appears for admin.
test on 11.chamilo.org.
I solved by creating a cms help links.
The ticket icon has to appear for students, right?
Greetings.
Chamilo 1.11.10 php7.3

![admin](https://user-images.githubusercontent.com/25286516/58128630-79f45780-7bee-11e9-9d14-9195a2f309c2.png)

![aluno](https://user-images.githubusercontent.com/25286516/58128635-7cef4800-7bee-11e9-996d-8da044ecf637.png)

**Comment by NicoDucou** [comment]
Hi @bassuma
There is a new configuration in app/config/configuration.php to define which type of user have access to the ticket system it is : 
```
$_configuration['ticket_project_user_roles'] = [
    'permissions' => [
        1 => [17,1], // project_id = 1 STUDENT_BOSS = 17
    ]
];
```
I think on 11.chamilo.org this setting has been activated that's why it does not appear for  students.

I think we can close this task, I let you confirm.

**Comment by bassuma** [comment]
Hi
But in my installation it also does not appear.
And for me to change in my chamilo.
So that the student can create ticket.
And just change that code?

**Comment by bassuma** [comment]
> Hi @bassuma
> There is a new configuration in app/config/configuration.php to define which type of user have access to the ticket system it is :
> 
> ```
> $_configuration['ticket_project_user_roles'] = [
>     'permissions' => [
>         1 => [17,1], // project_id = 1 STUDENT_BOSS = 17
>     ]
> ];
> ```
> 
> I think on 11.chamilo.org this setting has been activated that's why it does not appear for students.
> 
> I think we can close this task, I let you confirm.

Hello.
NicoBoco.
I edited the configuration.php.
// Allow ticket projects to be access by specific chamilo roles
I did not.
Unfortunately it did not work for me.

**Comment by bassuma** [comment]
Hello, @NicoBoco.
I got a print.
Note that it's the same as yours.
I already tried to change.
Inside the Brackets:
[1]
[17]
[17,1],
[17.1]
None worked.
Am I doing something wrong?

![ticket-config](https://user-images.githubusercontent.com/25286516/61242995-6b717a80-a71d-11e9-8308-644a2e375a31.jpg)

**Comment by NicoDucou** [comment]
In the configujration fila, the first 1 indicates the project, you can have miore than One project in the ticket system.
Then the numbers in the brakets indicates the user's roles that are allowed to access the ticket project.
So if you have in between the brackets 1 and 17 that means that user role admin (1) and Student boss (17) have access to project 1 of the ticket system.
So if you want students to also have access to the ticket system you should add 5 so you would have : 
```
$_configuration['ticket_project_user_roles'] = [
    'permissions' => [
        1 => [17,1,5] // project_id = 1, STUDENT_BOSS = 17
    ]
```
Best regards

**Comment by bassuma** [comment]
Oi...@NicoDucou.
working now.
Thank you
