### ISSUE TITLE
 Profiling Duplicating Options.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2910]
Hello
I'm having a problem editing fields.
Profiling.

![02](https://user-images.githubusercontent.com/25286516/58206759-bdff5f00-7cb7-11e9-99d3-3a5be09ed786.png)

![03](https://user-images.githubusercontent.com/25286516/58206775-c22b7c80-7cb7-11e9-916d-d52e4f5e1b1c.png)

When typing all the requirements.
You have this problem.
Duplicate options.
img
![2019-05-22 (8)](https://user-images.githubusercontent.com/25286516/58206522-3285ce00-7cb7-11e9-8772-373ddb597725.png)

I went to 11.chamilo.org.
I did not find this problem.
Only the problem in:
Edit this field's workflow.
![2019-05-22 (6)](https://user-images.githubusercontent.com/25286516/58206993-32d29900-7cb8-11e9-8e43-5c6f36e27d76.png)

That when clicking this appears.
img
![2019-05-22 (7)](https://user-images.githubusercontent.com/25286516/58206657-82fd2b80-7cb7-11e9-8c4f-9dc22c790878.png)
Thank you

**Comment by bassuma** [comment]
Hi.
@jmontoyaa
This issue has been resolved.
Fix extra field workflow page #2910
Thank you
![2019-05-23](https://user-images.githubusercontent.com/25286516/58263227-00757a00-7d52-11e9-932e-2d911ea09a20.png)


Unfortunately in my chamilo continues the problem of duplicating.
The problem occurs only in:
Select drop-down.
greetings

**Comment by jmontoyaa** [comment]
Please provide a link with the error.

**Comment by bassuma** [comment]
> Please provide a link with the error.

Hello.
@jmontoyaa
This is the link.
When you click on add.
And choose -> Select drop-down.
https://ead.tecnoltech.com/main/admin/extra_fields.php?action=add&type=user
Be able to test.
login: admin
password: admin
Thank you

**Comment by jmontoyaa** [comment]
The tests should be done in 11.chamilo.org that has the latest code.

**Comment by bassuma** [comment]
> The tests should be done in 11.chamilo.org that has the latest code.

Ok. This version is.
https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.10
At 11.chamilo.org.
This problem does not occur.

**Comment by jmontoyaa** [comment]
The error was probably already fixed after the release of 1.11.10 here:

https://github.com/chamilo/chamilo-lms/tree/1.11.x

**Comment by bassuma** [comment]
I am downloading.
And I'll test.

**Comment by bassuma** [comment]
@jmontoyaa
Thanks a lot for the help.
Worked perfectly.
I'm closing the ticket.
