### ISSUE TITLE
How to change Chamilo shortcut icon?

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2912]
Hi Chamilo Team ❤
I need to change Chamilo shortcut icon whether making a shortcut in a computer browser or a mobile browser

the current shortcut icon is the green transparent logo of Chamilo:
![image](https://user-images.githubusercontent.com/48198054/58274976-b1086b80-7d9c-11e9-8f21-f866acc68f7a.png)

![Screenshot_20190523-205339](https://user-images.githubusercontent.com/48198054/58275113-f9278e00-7d9c-11e9-9d14-2b0025898a00.png)

I need to know the location of this image in the installation folder in order to change it

note: I used chrome browser for computer and android

**Comment by disgregador** [comment]
List of files with name favicon.ico
------------------------------------
web/css/themes/chamilo/images/favicon.ico
web/css/themes/medical/images/favicon.ico
web/assets/select2/docs/images/favicon.ico
app/Resources/public/css/themes/chamilo/images/favicon.ico
app/Resources/public/css/themes/medical/images/favicon.ico
app/Resources/public/assets/select2/docs/images/favicon.ico
favicon.ico
vendor/ocramius/proxy-manager/html-docs/favicon.ico

Info: https://forum.chamilo.org/ - Chamilo Community Forum

**Comment by Haboubi92** [comment]
I finally figured that out
I changed this file in the main directory
apple-touch-icon.png
![apple-touch-icon2](https://user-images.githubusercontent.com/48198054/58353602-9525c800-7e77-11e9-9a69-5e744ce6a47c.png)
then I cleaned browser cache and it worked
![image](https://user-images.githubusercontent.com/48198054/58353689-d918cd00-7e77-11e9-9a58-f461a72527d2.png)
