### ISSUE TITLE
 Chamilo 11.chamilo.org link progess not responsive.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2915]
Dear support.
When you use chamilo on a smartphone.
In the link my student progress.
He is not resposivo.
Video attachment.
Is it possible to be responsive?
Obrgigado by the attention

![chamilo-progess-no-resposive](https://user-images.githubusercontent.com/25286516/58483174-3772d380-8136-11e9-95d7-f9bae978dc87.gif)

**Comment by ywarnier** [comment]
We sent a slight modification, but in general terms, we will try to drop this visualization (this library, actually) in a future majore version of Chamilo and use something else (vertical timeline, maybe).
Thanks for reporting.
