### ISSUE TITLE
Can't change manual - gitbook changed 

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2918]
**Describe**
Access and suggesting changes to documentation is on discontinued legacy.gitbook.com .
After creating account on gitbook I cant find/access/suggest changes on documentation.

**Suggestion**
Add the base docs on github or other places and add again old docs on chamilo website.

**Comment by ywarnier** [comment]
@marshel sorry we lost sight of this. The documentation project is now available at https://github.com/chamilo/docs/tree/1.11.x
Feel free to fork and send a pull request. I would *love* to have documentation contributions.

**Comment by marshel** [comment]
I'm between jobs, on 2 weeks notice (crazy world) . If I am able I will try to help after that.
