### ISSUE TITLE
Dos cosas que me parecen errores de instalacion

### ISSUE THREAD

**Issue by jubach** [chamilo/chamilo-lms#2919]
En la instalacion de Chamilo ver. 1.11.10, he creado unas lecciones con eXe y lo he importado con SCORM, me notifica que las lecciones importadas no son visibles para los alumnos. ¿Es algo de configuracion?

El segundo problema, es un error en la carga de lecciones, no puedo arrastrar las plantillas, los iconos no se ven, y me marca errores:

Failed to load resource: the server responded with a status of 500 () ->flash.gif:1 

¿A que es debido?

**Comment by NicoDucou** [comment]
Hola @jubach 

Para el primer error, podrias reproducirlo en https://11.chamilo.org para poder analizar el problema ? Porque normalemente deberia de estar visible, pero puede ser una configuracion que indica poner la herramienta invisble por defecto por ejemplo. Asi que mejor lo reproduce en la plataforma de pruebas y asi podremos entender mejor lo que pasa.

Para el segundo punto parece un problema de derechos en las carpetas de tu instalacion. Podrias reproducir el problema y mira en los error logs del servidor web para ver que te dice. Deberias tener mas informacion sobre la carpeta a la cual ha intentado acceder y asi saber los derechos de cual carpeta/archivos tienes que verificar.

**Comment by ywarnier** [comment]
Sin feedback por 1 año. Cerrando.
