### ISSUE TITLE
Error migración Chamilo - Symfony - Filesystem - Archivo con 2 puntos (.) en nombre bloquea la migración

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2922]
**Describe el problema**
Migración de Chamilo 1.9 a 1.10.8.
Posteriormente a 1.11.10 da error ya que un archivo contiene 2 puntos en el nombre. 
Provoca un error de Symfony en el componente Filesystem y no lo mueve de course a app/course paralizando la migración con un error.

Ruta/Archivo: **/courses/DHGI/document/learning_path/Modulo_1-_La_salud_mental_en_el_entorno_educativo-_herramienta_para_su_atencion_/Lecturas_Complementarias/LECTURA_COMPLEMENTARIA_DETERMINANTES_DE_LA_SALUD._IMPORTANCIA_DE_LA_PREVENCION.pdf**

Probado con versión estable y con código github rama 1.11.x.

**Error:**
PHP Fatal error:  Uncaught exception 'Symfony\\Component\\Filesystem\\Exception\\IOException' with message 'Unable to guess ".../courses/DHGI/document/learning_path/Modulo_1-_La_salud_mental_en_el_entorno_educativo-_herramienta_para_su_atencion_/Lecturas_Complementarias//LECTURA_COMPLEMENTARIA_DETERMINANTES_DE_LA_SALUD._IMPORTANCIA_DE_LA_PREVENCION.pdf" file type.' in /vendor/symfony/filesystem/Filesystem.php:on
thrown in /vendor\\symfony/filesystem/Filesystem.php on line 500, referer: .../main/install/index.php?running=1&installType=update&updateFromConfigFile=main%2Finc%2Fconf%2Fconfiguration.php

**Comportamiento esperado**
- Renombrar/filtrar previamente el nombre el archivo cuando se suba a lecciones, tareas, etc. para que no contenga caracteres extraños.
- Que permita trasladar el archivo aunque contenga 2 puntos en el nombre.

NOTAS:
No he hecho la prueba pero en teoría le afectaría también a archivos del tipo **fichero.tar.gz, nombre..pdf, .fichero.archivo.txt, etc.**

**Comment by jmontoyaa** [comment]
El problema está en la librería Filesystem de Symfony en la función "mirror".

He tratado de reproducir y no obtengo el error.

Tal vez es un tema de permisos de ese archivo.

He hecho esta prueba:

```
$fs = new Filesystem();
$fs->mirror('test1', 'test2');
```

En la carpeta "test1" colocar un archivo con nombre:

`LECTURA_COMPLEMENTARIA_DETERMINANTES_DE_LA_SALUD._IMPORTANCIA_DE_LA_PREVENCION.pdf`

Y no obtengo el error.

**Comment by nosolored** [comment]
Gracias, Julio.
Se mostró en 2 ocasiones en pruebas de migración. Los permisos si están correctos.
Revisaremos de nuevo.
Saludos

**Comment by nosolored** [comment]
Gracias.
