### ISSUE TITLE
Warning:continue targeting swicht is equivalet to break?

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#2923]
Please.

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/admin/public_html/escola.tecnoltech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640

Thank you

**Comment by bassuma** [comment]
Please.
In a new installation this appears.
What you mean.
Can I continue with the installation?

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/admin/public_html/escola.tecnoltech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640

**Comment by jmontoyaa** [comment]
The problem is in the **doctrine/orm** package, installed in Chamilo is version **2.4.x**, it should be updated to 2.5 or higher, but those versiones required PHP 7.x.
Currently in Chamilo we still support PHP 5.6.

**Comment by bassuma** [comment]
> The problem is in the **doctrine/orm** package, installed in Chamilo is version **2.4.x**, it should be updated to 2.5 or higher, but those versiones required PHP 7.x.
> Currently in Chamilo we still support PHP 5.6.

Hello.
I'm using Chamilo LMS 1.11.10 for PHP 7.3.
I said I had solved more but not solved.
I hope the next version will solve this problem.
Thanks for answering.

**Comment by mtf786** [comment]
> I solved this problem change here?
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home/admin/public_html/escola.tecnoltech.com/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
> 
> line 2640
> continue2;
> }
> 
> ```
>                 if ( ! isset($hints['fetchMode'][$class->name][$field])) {
>                     $hints['fetchMode'][$class->name][$field] = $assoc['fetch'];
>                 }
> ```

I also solved this problem , Thanks brother

**Comment by danieldocumentos** [comment]
lo arreglé cambiando en la linea 2640 de chamilo//vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php, donde decía continue; lo cambié por break; y funcionó.
