### ISSUE TITLE
Tu manga online

### ISSUE THREAD

**Issue by amai-kun** [chamilo/chamilo-lms#2925]
En Tachiyomi la extensión de TuMangaOnline no funciona 

El problema es que no deja leer manga ni descarga

1. descargar la extensión de TuMangaOnline en la apk de Tachiyomi
2. Buscar un manga 
3. Seleccionar cualquier capítulo 
4. Saltará un mensaje 

No me esperaba que la extensión de tu manga online en Tachiyomi fallara ya que llevo un año con ella 

![Screenshot_20190606-211338_Tachiyomi](https://user-images.githubusercontent.com/51460900/59064471-9957d980-88aa-11e9-85a9-a3617a5e0d04.jpg)

 - Samsung j6+ 
 - apk Tachiyomi

**Comment by AngelFQC** [comment]
:neutral_face:

**Comment by amai-kun** [comment]
Sabes porque pasa

**Comment by jloguercio** [comment]
@amai-kun Este repositorio es de la aplicación web ChamiloLMS, creo que deberías hacer la pregunta en este repo : https://github.com/inorichi/tachiyomi

Saludos

**Comment by amai-kun** [comment]
Gracias
