### ISSUE TITLE
Actualización 1.11.10

### ISSUE THREAD

**Issue by DanielZambranoC** [chamilo/chamilo-lms#2929]
**Describe el problema**
Actualice mi chamilo desde la 1.11.8 a la 1.11.10 siguiendo estas instrucciones
https://11.chamilo.org/documentation/installation_guide.html#3._Upgrade

Al parecer todo bien, pero cuando voy a la sección Administración -> Version Check me sigue diciendo:

> Your version is not up-to-date
> The latest version is Chamilo 1.11.10. 
> Your version is Chamilo 1.11.8. 
> Please visit our website: http://www.chamilo.org

Sin embargo veo algo nuevo, este mensaje que antes no lo había visto (creo)

`Are you having some issue? Do you need help? Are you dreaming of some very specific new feature? Chamilo project's sustainability is only possible thanks to the contributions of a small number of exceptional people and of businesses engaged with its development. These companies are EXPERTS in everything related to Chamilo, from e-learning consulting to cloud hosting, from courses design to Chamilo training to custom developments. If your organization uses Chamilo and needs professional support, working with one of these companies is the best decision you can take. It will bring you all the services you need with a certified quality level and ensure the accelerated growth of your platform. Be responsible, choose Official Chamilo Providers.`

Si borre el cache utilizando la opción dentro del sistema.

**Comportamiento esperado**
Que el version check me indicara que todo estaba correcto

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/28786672/59465951-0fec5e00-8dfa-11e9-8033-58cdb7ece32b.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador Chrome 75.0.3770.80 (Official Build) (64-bit)

**Servidor**
 - Sistema operativo : Ubuntu 18.04
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 7.2

**Comment by AngelFQC** [comment]
Hola @DanielZambranoC si ya reemplazaste los archivos de la nueva versión en tu portal, sólo falta actualizar `$_configuration['system_version']` de '1.11.8' a '1.11.10' en el fichero de configuración `app/config/configuration.php`

**Comment by fernandocrb** [comment]
Instale Chamilo en Softaculous y me aparece ese mismo mensaje:
Are you having some issue? Do you need help? Are you dreaming of some very specific new feature? Chamilo project's sustainability is only possible thanks to the contributions of a small number of exceptional people and of businesses engaged with its development. These companies are EXPERTS in everything related to Chamilo, from e-learning consulting to cloud hosting, from courses design to Chamilo training to custom developments. If your organization uses Chamilo and needs professional support, working with one of these companies is the best decision you can take. It will bring you all the services you need with a certified quality level and ensure the accelerated growth of your platform. Be responsible, choose Official Chamilo Providers.

Como lo remuevo?

**Comment by nosolored** [comment]
Esto está explicado en el foro: https://forum.chamilo.org/viewtopic.php?f=15&t=11000

**Comment by juliocampomanes** [comment]
A mi me sale este error:
Warning: Declaration of UniqueAnswer::return_header($exercise, $counter = NULL, $score = NULL) should be compatible with Question::return_header(Exercise $exercise, $counter = NULL, $score = Array) in /home4/jcampomanes/public_html/roomclass/main/exercise/unique_answer.class.php on line 19

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home4/jcampomanes/public_html/roomclass/main/exercise/unique_answer.class.php:19) in /home4/jcampomanes/public_html/roomclass/main/inc/lib/chamilo_session.class.php on line 98
DJL CONSULTING EXPRESS

Warning: Declaration of UniqueAnswer::return_header($exercise, $counter = NULL, $score = NULL) should be compatible with Question::return_header(Exercise $exercise, $counter = NULL, $score = Array) in /home4/jcampomanes/public_html/roomclass/main/exercise/unique_answer.class.php on line 19

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home4/jcampomanes/public_html/roomclass/main/exercise/unique_answer.class.php:19) in /home4/jcampomanes/public_html/roomclass/main/inc/lib/chamilo_session.class.php

No se a que se debe, que puedo hacer?

**Comment by NicoDucou** [comment]
Hola @juliocampomanes 
Par favor no escribir en un issue que no esta relacionado con lo que reportas y  aun menos en una issue que ya esta cerrada. Te invito  que ya estan cerradas. Te invito a reportar una nueva issue y a respectar el template de reporte para que te podamos ayudar.
Por lo warning les puedes desactivar en la configuracion de tu servidor web.
