### ISSUE TITLE
Premature end of script headers: php72.cgi, referer: https://#####/main/admin/index.php

### ISSUE THREAD

**Issue by DanielZambranoC** [chamilo/chamilo-lms#2930]
**Describe el problema**
Basicamente tengo errores 500 muy constantes, y en console log se puede ver cada vez que navego que hay archivos que no carga indicando de igual forma errores 500.

Por donde quiera que navego tengo entre 1 y 3 console logs con errores 500, y en oportunidades la pagina completa suelta el error 500 sin mostrar nada.

Al revisar los errores de apache, tengo ese error en diferentes rutas replicado

```
Fri Jun 14 10:29:39 2019] [error] [client 190.124.30.251] File does not exist: /home/dzambrano_campusneb/web.com.com/internal_error.html, referer: https://web.com.com/main/lp/lp_controller.php?cidReq=CLOUDPROFESSIONALEXAM&id_session=0&gidReq=0&gradebook=0&origin=
[Fri Jun 14 10:30:43 2019] [error] [client 190.124.30.251] Premature end of script headers: php72.cgi, referer: https://web.com.com/
[Fri Jun 14 10:30:43 2019] [error] [client 190.124.30.251] File does not exist: /home/dzambrano_campusneb/web.com.com/internal_error.html, referer: https://web.com.com/
[Fri Jun 14 10:30:49 2019] [error] [client 190.124.30.251] Premature end of script headers: php72.cgi, referer: https://web.com.com/main/lp/lp_controller.php?action=add_item&type=step&lp_id=19&cidReq=CLOUDPROFESSIONALEXAM&id_session=0&gidReq=0&gradebook=0&origin=
[Fri Jun 14 10:30:49 2019] [error] [client 190.124.30.251] File does not exist: /home/dzambrano_campusneb/web.com.com/internal_error.html, referer: https://web.com.com/main/lp/lp_controller.php?action=add_item&type=step&lp_id=19&cidReq=CLOUDPROFESSIONALEXAM&id_session=0&gidReq=0&gradebook=0&origin=
[Fri Jun 14 10:30:57 2019] [error] [client 190.124.30.251] Premature end of script headers: php72.cgi, referer: https://web.com.com/index.php
[Fri Jun 14 10:30:57 2019] [error] [client 190.124.30.251] File does not exist: /home/dzambrano_campusneb/web.com.com/internal_error.html, referer: https://web.com.com/index.php
[Fri Jun 14 10:52:16 2019] [error] [client 190.124.30.251] Premature end of script headers: php72.cgi, referer: https://web.com.com/main/admin/index.php
[Fri Jun 14 10:52:16 2019] [error] [client 190.124.30.251] File does not exist: /home/dzambrano_campusneb/web.com.com/internal_error.html, referer: https://web.com.com/main/admin/index.php
[Fri Jun 14 12:14:30 2019] [error] [client 190.124.30.251] Premature end of script headers: php72.cgi, referer: https://web.com.com/main/admin/index.php
[Fri Jun 14 12:14:30 2019] [error] [client 190.124.30.251] File does not exist: /home/dzambrano_campusneb/web.com.com/internal_error.html, referer: https://web.com.com/main/admin/index.php
```

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/28786672/59533132-92d3ee00-8eb8-11e9-9e61-6ab6be9d5a4a.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador: Chrome Version 75.0.3770.90 (Official Build) (64-bit)

**Servidor**
 - Sistema operativo : Ubuntu 18.04
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 7.2

**Comment by ywarnier** [comment]
Necesitaríamos más logs de error para ayudarte. Si puedes instalar la extensión php-xdebug, debería darte más información sobre lo que está mal. Lo de "Premature end of script" solo indica que hubo un problema en la ejecución, pero no nos da ninguna información concreta (como lo imaginaste).

**Comment by DanielZambranoC** [comment]
Hola @ywarnier, gracias por responder,

Lamentablemente no puedo instalar php-xdebug, ya que estoy en un servidor compartido. Voy a tener que hacer otras cosas para poder elevar el nivel de detalle entonces y poder determinar que esta pasando.

Adicionalmente comparto con ustedes el status del sistema en la pestaña php, a ver si esto ayuda con la identificacion del problema

![image](https://user-images.githubusercontent.com/28786672/59615821-34de1b00-90f1-11e9-903a-b1377241ac36.png)

**Comment by disgregador** [comment]
Hola @DanielZambranoC ¿Has cambiado de hosting? 

- Comprueba app/config/configuration.php
y revisa que las rutas Web y Linux son correctas en

```
$_configuration['root_web']  
$_configuration['root_sys']  
```

Se muestran entradas distintas 
https://web.com.com
https://campus.nebusis.com/
y la ruta Linux
/home/dzambrano_campusneb/web.com.com/ en los errores.

Revisa también los parámetros de PHP como
memory_limit
max_input_time
max_execution_time
short_open_tag
session.gc_maxlifetime
ya que no son los recomendados.
