### ISSUE TITLE
Template para certificado personalizado roto 

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#2931]
**Describe el problema**
El template `main/template/default/gradebook/custom_certificate.tpl`, viene de la rama ofaj, tiene rutas que apuntan a imágenes que no existen en 1.11.x y se genera un certificado roto. Incluso tiene variables de idioma que no existen en chamilo 

**Cómo reproducir**
Pasos para reproducir el problema:
1. Crear un curso que genere certificados, pero no seleccionar un certificado predeterminado
2. Crear al meno una evaluación y asignarle una nota a un estudiante para que genere el certificado.
3. Ver como estudiante o profesor, el certificado generado.

**Comportamiento esperado**
Generar un certificado correcto

Versión Chamilo: 1.11.x
PHP: 7.3

**Contexto adicional**
No es encesario tener habilitado el plugin de _Certificado personalizado_
La solución manual sería seleccionar como certificado predeterminado al certificado que se crea al crear el curso.

**Comment by jmontoyaa** [comment]
Puedes poner un caso en 11.chamilo.org?

**Comment by jmontoyaa** [comment]
He enviado un pequeño cambio para ver el documento que esta siendo usado como certificado:

https://github.com/chamilo/chamilo-lms/commit/be5e637cd6facd417edb7a8fc3e868a321f43a88

![Screenshot_20190621_160044](https://user-images.githubusercontent.com/158935/59927882-c3c69c80-943d-11e9-9c51-1101ac07b69a.png)

**Comment by AngelFQC** [comment]
> Puedes poner un caso en 11.chamilo.org?

Aquí https://11.chamilo.org/certificates/index.php?id=13234
Si inicias sesión con cualquier usuario y entras con esa url o cualquier id, parece que se genera un certificado para el usuario actual.

**Comment by jmontoyaa** [comment]
Me refiero a un curso donde aparece el error.

**Comment by jmontoyaa** [comment]
Ese link ya es de un certificado generado

**Comment by AngelFQC** [comment]
Ok. Pero así le cambies el id, por uno que no existe, te muestra el certificado ofaj
Y en 11.chamilo.org no está habilitado el plugin custom certificates.

**Comment by jmontoyaa** [comment]
He enviado algunos cambios ahora debería de funcionar. Para ver ese esos templates de ofaj se tiene que activar:

`
//$_configuration['allow_general_certificate'] = true;`

**Comment by AngelFQC** [comment]
Corregido
