### ISSUE TITLE
no puedo ver el avance de cada alumno 

### ISSUE THREAD

**Issue by Equinoterapia2018** [chamilo/chamilo-lms#2932]
https://campus.chamilo.org/main/mySpace/myStudents.php?details=true&cidReq=MODULO1ELCABALLO&course=MODULO1ELCABALLO&origin=tracking_course&id_session=0&student=817288

Fatal error: Uncaught Error: Call to undefined method __TwigTemplate_50604abbdf7078a85cd386f6e6353c1833697c5e540ba378fb95f11725302767::getpanel() in /furanet/sites/campus.chamilo.org/web/htdocs/app/cache/twig/1/4c/4cdf5008b6e16d4785d6dc91bc0a7b3403739171367f94e1aa83d4a2f6c66ee9.php:122 Stack trace: #0 /furanet/sites/campus.chamilo.org/web/htdocs/vendor/twig/twig/src/Template.php(443): __TwigTemplate_f31f53811d0f815eafdfffc7308b0deb1f119774b088a048a67ac088577cc2ed->doDisplay(Array, Array) #1 /furanet/sites/campus.chamilo.org/web/htdocs/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array) #2 /furanet/sites/campus.chamilo.org/web/htdocs/vendor/twig/twig/src/Template.php(422): Twig\Template->display(Array) #3 /furanet/sites/campus.chamilo.org/web/htdocs/main/inc/lib/template.lib.php(942): Twig\Template->render(Array) #4 /furanet/sites/campus.chamilo.org/web/htdocs/main/mySpace/myStudents.php(994): Template->fetch(Object(__TwigTemplate_f31f53811d0f815eafdfffc7308b0deb1f119774b088a048a67 in /furanet/sites/campus.chamilo.org/web/htdocs/app/cache/twig/1/4c/4cdf5008b6e16d4785d6dc91bc0a7b3403739171367f94e1aa83d4a2f6c66ee9.php on line 122

**Comment by Equinoterapia2018** [comment]
gracias

**Comment by jmontoyaa** [comment]
Corregido
