### ISSUE TITLE
ERRO: plugin/buycourses/src/process.php?i=1&t=2 - DIRETORIO DUPLICADO

### ISSUE THREAD

**Issue by adriano162** [chamilo/chamilo-lms#2933]
Na inscrição de usuario em ...chamilo/main/auth/inscription.php apos clicar em REGISTRAR USUARIO, e na tela seguinte em AVANÇAR, deveria ir para a pagina de pagamento do Paypal porem, a pagina fica duplicada da seguinte forma   .../chamilo//chamilo/plugin/buycourses/src/process.php?i=1&t=1  Alguem poderia me ajudar?

**Comment by ywarnier** [comment]
@adriano162 do you still have this issue?
