### ISSUE TITLE
New question type: Description

### ISSUE THREAD

**Issue by hakangur** [chamilo/chamilo-lms#2934]
"Description" is a question type that is already present in Moodle. It is described in Moodle as: "This is not actually a question. Instead it is a way to add some instructions, rubric or other content to the activity. This is similar to the way that labels can be used to add content to the course page." It is also available in ILIAS and FormaLMS. Currently, I cannot create test like this with Chamilo:
Page 1: Listening Passage (only a photo and an audio file)
Page 2: Question 1 (multiple choice)
Page 3: Question 2 (multiple choice)
Page 4: A short passage from the Listening Passage (a different photo or a graphic and an audio file)
Page 5: Question 3 (multiple choice)
etc.
When there is a listening passage, there should be no question - and this is not possible with Chamilo.
I accomplished this by "sacrificing" the question type called Annotation. In /main/lib/exercise.lib.php file, I removed the lines 1566-1586 (these lines included) altogether and saved the file. I also replaced the icon for Annotation (main/img/icons/xx/annotation.png) with an icon that would fit our purposes. Now, I am able to add descriptions, instructions, reading passages, listening texts, etc. between two questions (the "Score" for this question should be set as "0", of course). In short, "Description" can be created by making a few small changes on Annotation.

**Comment by shabsshab** [comment]
I do have Tests with  Descriptive type as senior class students will have thoery paper.
So In test I need an option of typing the text in the given area or uploading the image as answers.

Most of the students are slow in typing and school will prefer writing exam in a paper and upload the anwsers as a image .

Can I have one question type as similar to  assignment type

**Comment by shabsshab** [comment]
iam attaching the snapshot here : https://prntscr.com/vdeip7
Can we make it with small customisation ?

**Comment by ywarnier** [comment]
The feature request from @hakangur is, in all aspects that I can see, similar to #2676, so I'm closing this feature request as duplicate.
@shabsshab your request has nothing to do with that. Please open a new request with just your topic so we can discuss it, but I would invite you to rather use the assignments tool than ask for a change that I see as complex and avoidable.
