### ISSUE TITLE
Time Counter for Oral Expression

### ISSUE THREAD

**Issue by hakangur** [chamilo/chamilo-lms#2935]
In "Oral expression" (question type), there should be a time counter. It would be nice to see how many seconds have gone by since the start of the recording (this is present for Poodll plugin for Moodle, as well as for Audio Recorder [https://h5p.org/audio-recorder] for H5P; however, with H5P, unlike Chamilo, the student's response cannot be automatically saved on the Chamilo server).

**Comment by ywarnier** [comment]
I believe this has recently been implemented by @jmontoyaa in 1.11.14, right?

**Comment by NicoDucou** [comment]
I confirm that now it is like this with the timer : 
![image](https://user-images.githubusercontent.com/6579268/104140537-0f3ef380-53b2-11eb-83c2-25a7910bc578.png)
