### ISSUE TITLE
Time Limit for Individual Questions

### ISSUE THREAD

**Issue by hakangur** [chamilo/chamilo-lms#2938]
_This should not be confused with the overall timing for the test!_ It should be possible to set a specific time limit for **individual** **questions** (already present in FormaLMS, for example). For instance, if the time limit for question 1 is 10 seconds, at the end of this time limit the student will be forced to move on to the next question (or the next question will appear automatically).

**Comment by ywarnier** [comment]
This is something we definitely want to add, but it might last a bit longer still before we have an opportunity to add it.

**Comment by ywarnier** [comment]
Recently implemented in 1.11.14 by @jmontoyaa
