### ISSUE TITLE
1.11.10 - les images ne s'affichent pas dans le parcours

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#2940]
Les images ne s'affichent pas dans le document en tant que stagiaire. En prévisualisation, l'image s'affiche correctement.

1.11.10 (mise à jour de 1.11.8, puis installation "clean").
Rollback en 1.11.8, les images s'affichent.

Constat : dans l'URL générée, il manque /app/ dans le chemin.
Un chemin relatif devrait régler le problème ;)

Contournement en urgence : je vais faire ma démo sous 1.11.8

**Comment by Coursenligne** [comment]
Je confirme. le lien généré est du type 127.0.0.1/chamilo/course/document..... Le chemin devrait être 127.0.0.1/chamilo/app/course....

**Comment by NicoDucou** [comment]
C'est étrange car normalement dans le fichier .htaccess il y a : 
`RewriteRule ^courses/([^/]+)/document/(.*)$ main/document/download.php?doc_url=/$2&cDir=$1 [QSA,L]`
Donc de toute façon ça devrait être redirigé.

Je n'ai pas de test avec un sous dossier pour l'installation de Chamilo, je l'ai à chaque fois installé directement sur le domaine (ce qui est recommandé), c'est peut-être uniquement dans ce cas là qu'il y a le problème, car sur https://11.chamilo.org/ le problème ne se reproduit pas.

**Comment by Coursenligne** [comment]
Oui mais ça ne l'est pas (1.11.10 installation). La version 1.11.8 est OK.
J'ai encore fait le test aujourd'hui, car pour chaque ressource, je dois ajouter /chamilo/app au début du chemin.
Info importante je parle d'image que je vais chercher sur mon ordi via l'éditeur (upload soit par le bouton, soit par glisser/déposer qui marche du tonner :) ).
Pas de domaine ni de sous-dossier.
Install pour démo en clientèle sur mon ordi portable avec un WAMP pour faire le boulot.
Si c'était un souci de domaine, 1.11.8 aurait le même comportement :)

**Comment by Coursenligne** [comment]
1.11.10 installation fraîche. Je sais d'où vient le souci, je ne sais pas le régler...
Le chemin généré est /courses/<nom_du_cours>/document...
C'est un chemin absolu, il manque donc /chamilo/app/ et le reste de l'URL.
Vivement la création en mode chemin relatif (beaucoup plus exportable :) )

**Comment by Coursenligne** [comment]
Je pense avoir la solution....
Dans chamilo/app/config
configuration.php il faut renseigner $_configuration['url_append']:
$_configuration['url_append'] = 'chamilo';
Par défaut cette variable est vide.

**Comment by ywarnier** [comment]
Si tu installes Chamilo en utilisant l'URL complète (incluant le /chamilo/), l'installateur devrait se charger de remplir url_append tout seul. Si tu installes sans le /chamilo/ puis que tu changes ça, effectivement, Chamilo s'y perd.
