### ISSUE TITLE
Chamilo 1.19

### ISSUE THREAD

**Issue by Netrixdesigns** [chamilo/chamilo-lms#2942]
Good day
please kindly upload full chamilo 1.9 into the Release Section, only the source code is available, please its the only stable version with reduced bugs i have ever used,please i need back

**Comment by disgregador** [comment]
Downloads Chamilo 1.11.10, 1.10.8 and 1.9.10.4 
https://github.com/chamilo/chamilo-lms/releases 

https://github.com/chamilo/chamilo-lms/releases/tag/v1.9.10.4
https://github.com/chamilo/chamilo-lms/archive/v1.9.10.4.zip
https://github.com/chamilo/chamilo-lms/archive/v1.9.10.4.tar.gz

**Comment by ywarnier** [comment]
Hi @Netrixdesigns we only started uploading the packaged versions to Github after 1.9. Also, 1.9 is a major version, it has many minor versions so it is not clear to which specific version you are referring.
Finally, Chamilo 1.9 did not support PHP 7 very well, with PHP 5 being completely deprecated now... so I'm not judging but it might not be the best idea.
Anyway, to "compile" the package from the sources, just download the sources on a PHP 5 computer, download and install `composer` on the computer, get into the main directory of the uncompressed sources and launch "composer update". This will give you the equivalent of the packaged version.

**Comment by Netrixdesigns** [comment]
Thanks
