### ISSUE TITLE
certificates not working

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2947]
**Describe**
When using the assessment tool to generate certificates, a 500 error is thrown.

**Additional context**
PHP Fatal error:  Uncaught Error: Call to undefined function mb_regex_encoding() in /var/www/chamilo/vendor/mpdf/mpdf/mpdf.php:1232\nStack trace:\n#0 /var/www/chamilo/main/inc/lib/pdf.lib.php(72): mPDF->__construct('UTF-8', 'A4', '', '', 15, 15, 30, 30, 8, 8, 'P')\n#1 /var/www/chamilo/main/gradebook/lib/GradebookUtils.php(1625): PDF->__construct('A4', 'P', Array)\n#2 /var/www/chamilo/main/gradebook/index.php(72): GradebookUtils::generateTable(Array, 3, Array)\n#3 {main}\n  thrown in /var/www/chamilo/vendor/mpdf/mpdf/mpdf.php on line 1232, referer: http://192.168.43.139/main/gradebook/index.php?cidReq=GYFKURS001&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by Coursenligne** [comment]
I made a test (well a double test) and didn't find any issue.
After course created, I go to the graduation part, create the certificate, and then create a link where I choose the way to earn the certificate (e.g.: learning path).
I ensure the total of the graduation marks is equal to 100 and don't forget to tick the box to get the certificate generated.
Certificates are working my side, even simultaneously with the wheel of skills.
Last but not least, I had quite a lot of trouble using Chamilo 1.11.10 if extracted from the zip file. Using the TGZ instead did cure some issues, even though there are still some issues existing.

**Comment by NicoDucou** [comment]
I know of an issue with the mpdf library when putting chamilo in test server mode (this setting can be changed in the general settings configuration. The error you report could be related to it so make sure your server is in production mode and not in test mode: 
![image](https://user-images.githubusercontent.com/6579268/60961470-88b4dc00-a30c-11e9-904e-50a11b8a6b75.png)

**Comment by opensourcecompany** [comment]
Hi Nicolas,
unfortunately it is already in production mode.

Could be the same as [this issue](https://github.com/mpdf/mpdf/issues/440)
Will investigate this and report.

**Comment by AngelFQC** [comment]
Please check if your server has installed and enabled the mbstring module for PHP.

> PHP Fatal error: Uncaught Error: Call to undefined function mb_regex_encoding() in /var/www/chamilo/vendor/mpdf/mpdf/mpdf.php:1232\nStack trace:\n#0 /var/www/chamilo/main/inc/lib/pdf.lib.

It means that PHP doesn't find the `mb_regex_encoding` function.

**Comment by ejimor** [comment]
i get this error message from error log when trying to rate and correct assignment that has the files upload file type selected for assignment but when i use text only error is not there, please i need help on what to do.

[15-May-2020 18:07:45 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mime_content_type() in /home/deltacar/public_html/elearning/main/work/work.lib.php:143
Stack trace:
#0 /home/deltacar/public_html/elearning/main/work/view.php(10): get_work_data_by_id(261)
#1 {main}
  thrown in /home/deltacar/public_html/elearning/main/work/work.lib.php on line 143

**Comment by lonesomewalker** [comment]
Please do not hijack other support threads.
Open your own.

**Comment by achanga** [comment]
Please help me, i am getting this error message when trying to access the certificate that i have configure to pick from  online assessment and completion on learning path "An error has occured. Please contact your system administrator."
TCPDF library is present and running well, i have enabled to view the logs but there is nothing on my error logs.
