### ISSUE TITLE
official provider overlay repeatedly shown

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#2948]
**Describe**
Even if the overlay is closed, everytime the admin site opens it is still there.

Chamilo version 1.11.10

**Comment by ywarnier** [comment]
It is meant to be that way. You can remove it for your customers by adding this to their config files:
```
// Disable Chamilo.org announcements at the top of the admin page
$_configuration['admin_chamilo_announcements_disable'] = true;
```
