### ISSUE TITLE
ckeditor not showing

### ISSUE THREAD

**Issue by proftug4** [chamilo/chamilo-lms#2949]
**Describe**
It's not possible to use ckeditor. Can't write messages or other field texts like questions in quizzs

Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "qmarkersrolls" was not found at "https://colegioscaju.com/evirtual/web/assets/ckeditor/plugins/qmarkersrolls/plugin.js?t=H0CF".
at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.<anonymous> (ckeditor.js:9)
at g (ckeditor.js:8)
at Array.n (ckeditor.js:8)
at v (ckeditor.js:8)
at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:8)

![Screenshot_2019-07-08 Plataforma E-Learnig do Colégio CAJU - E-Virtual Colégio CAJU - Compor mensagem](https://user-images.githubusercontent.com/20543813/60909232-9c613380-a275-11e9-871c-bc3c9f00e9a8.png)

**Comment by AngelFQC** [comment]
Hi @proftug4 
Do you installed your portal from github sources or from a released package.
In any case, you can install composer on your server, and then run
`composer install` in your chamillo directory. Or copy the missing directory in your `web/assets` directory from `app/Resources/public/assets`.

**Comment by Coursenligne** [comment]
Just to ensure (I know it sound silly!) did you downloaded the zip or the tgz version of chamilo (from chamilo.org)?
I did had the same issue using th zip. testing with the tgz cured the issue.

**Comment by proftug4** [comment]
installed from softaculous. Will try to copy

**Comment by proftug4** [comment]
@AngelFQC 
Well, it's a shared host, don't have ssh access :(.
I uploaded ckeditor from app/Resources/public/assets to web/assets and no changes

**Comment by proftug4** [comment]
Solved.

I Have lite speed cache on the same server (chamilo is a subfolder of main site).  Purged teh cache and voilá! Began working
