### ISSUE TITLE
Error después de crear un curso en Chamilo, no se puede acceder.

### ISSUE THREAD

**Issue by huamolle** [chamilo/chamilo-lms#2950]
Muy buenas tardes, saludos desde Loreto - Perú.
El problema surge después de la instalación de Chamilo versión chamilo-1.11.8-php7, después de realizar dicha instalación y querer crear un curso demostrativo, lo crea pero me redirige a la pantalla principal, cuando deseo acceder al curso no me permite, es como que solo creo el enlace pero no el curso, antes ya sucedio ese problema pero se solucionaba dando los permisos tanto en carpetas como en archivos dentro de la misma configuración de chamilo para Nuevo directorios 755 y archivos 644, pero aun así persiste el error.
El hosting que estoy utilizando es Hostgator.
Espero su ayuda, gracias.

**Comment by AngelFQC** [comment]
Hola @huamolle 
Puedes ver los logs de error de apache y también revisar el status de tu portal en /main/admin/system_status.php

**Comment by aragonc** [comment]
O capas tu mod_rewrite no esta activado

**Comment by huamolle** [comment]
Gracias voy a observar sus sugerencias un comercial y regreso

**Comment by huamolle** [comment]
![001](https://user-images.githubusercontent.com/10541420/61010402-b1a09580-a33b-11e9-9c50-9bef0968b585.png)
![002](https://user-images.githubusercontent.com/10541420/61010403-b2d1c280-a33b-11e9-8498-8fe2cc864055.png)
![003](https://user-images.githubusercontent.com/10541420/61010404-b36a5900-a33b-11e9-9f5e-bf3ecf1e7a38.png)
Como se puede observar salen algunos errores, pero no son para no poder visualizar los cursos, despues de haberlos creado.

**Comment by aragonc** [comment]
y tu mod_rewrite de apache2 esta activado? @huamolle

**Comment by huamolle** [comment]
Voy a verificar, un momento.

**Comment by huamolle** [comment]
si puedo visualizar mi .htaccess

**Comment by huamolle** [comment]
solo tengo esto :
# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

# END WordPress

**Comment by disgregador** [comment]
Ese .htaccess corresponde a WordPress

Busca ese fichero en el directorio de Chamilo (carpeta, subdominio)

En hostinger revisa en tu panel hosting o en tu apartado de logs los errores que te muestran.

Activa el modo Servidor de desarrollo en Chamilo (desde la Administración) para que te muestre más información.

**Comment by huamolle** [comment]
Voy a revisar y colocar el Chamilo en modo de desarrollo, porque estoy muy interesado en este error

**Comment by huamolle** [comment]
Hasta ahora amigos no puedo encontrar el error, aun sigue en lo mismo

**Comment by ywarnier** [comment]
@huamolle 
No deberías poder "ver" tu .htaccess en tu navegador web. El .htaccess son reglas especiales *para* el servidor web. Si puedes ver el contenido de .htaccess en tu navegador, es que definitivamente no leíste el manual de instalación de Chamilo que tiene una sección especial sobre esto. Además te lo hemos puesto en Español, solo para ti.

También hay que resaltar que el que muestras arriba es uno de WordPress, y esto significa que estás mezclando dos carpetas (una de WordPress y una de Chamilo), y esto tampoco puedes hacerlo.

Recomendación: lee el manual de instalación de Chamilo. Te va a tomar 40 minutos quizás, que serán más rápido que buscar algo para copiar y pegar y olvidarte del problema.
