### ISSUE TITLE
Automatic certificate generation

### ISSUE THREAD

**Issue by JeanLAlves** [chamilo/chamilo-lms#2952]
Hello, dears! 
I'd like to know if there is a way to generate a certificate automatically after the student finishes his/her task set up in assessment option.

I've already realized that it is necessary to go to certificate panel and click "generate certificates". However my question is about generating certificates without going to this panel. That is, right after the student finishes his/her task, the certificate is available to him/her.

Thanks.

**Comment by NicoDucou** [comment]
Hi @JeanLAlves 
It is possible to deliver the certificates automatically to the student using the learningpath tool.
You can put you assessment as a step of the learning path then after put the certificate item and on the certificate item put a requirement for the assessment item to be done to be able to access it.

In the gradebook you should have the learning path as a requisite for the validation of the gradebook and also validate the checkbox for the certificate generation.

That the way to proceed.

Best regards

**Comment by opensourcecompany** [comment]
How does this work without an assessment? :-)

**Comment by JeanLAlves** [comment]
> Hi @JeanLAlves
> It is possible to deliver the certificates automatically to the student using the learningpath tool.
> You can put you assessment as a step of the learning path then after put the certificate item and on the certificate item put a requirement for the assessment item to be done to be able to access it.
> 
> In the gradebook you should have the learning path as a requisite for the validation of the gradebook and also validate the checkbox for the certificate generation.
> 
> That the way to proceed.
> 
> Best regards

Hello, @NicoDucou!
Thanks for replying. 
I've already set up a step of the learning path as my assessment. But it still doesn't generate the certificates automatically. As the student finishes his/her course and accomplishes the step which has been configurated as an assessment, it is still necessary to go to "Assessment > See List of Certificates > Click on "Generate Certificates".

I've tried to drag and drop the certificate as a sequence of the learning path (in learning path tool) as you can seen in the image attached, but it didn't work properly (labels don't appear).

![image](https://user-images.githubusercontent.com/53061593/61539134-33b24d80-aa11-11e9-9caa-3e2d2044b9c2.png)

**Comment by JeanLAlves** [comment]
> Hi @JeanLAlves
> It is possible to deliver the certificates automatically to the student using the learningpath tool.
> You can put you assessment as a step of the learning path then after put the certificate item and on the certificate item put a requirement for the assessment item to be done to be able to access it.
> 
> In the gradebook you should have the learning path as a requisite for the validation of the gradebook and also validate the checkbox for the certificate generation.
> 
> That the way to proceed.
> 
> Best regards

Hi, Nico!
Firtly, thank you for your reply. 
I think it is the version. I was searching for more information and I checked that the new version already generates certificates automatically.

All the best.
