### ISSUE TITLE
Show learnpath menu by default

### ISSUE THREAD

**Issue by sabkos** [chamilo/chamilo-lms#2953]
For course users, there is only the 3 line menu to click.
It would be nice to have a setting to somewhat customize this or at least set default settings.

**Comment by NicoDucou** [comment]
The configuration now exists. It has to be set in the app/config/configuration.php file :

```
$_configuration['lp_view_settings'] = [
    'display' => [
        //'show_reporting_icon' => true,
        //'hide_lp_arrow_navigation' => false,
        'show_toolbar_by_default' => true, // <<<<<<<< new setting
    ],
];
```

**Comment by lonesomewalker** [comment]
In which commit was this solved/implemented? :-/

**Comment by ywarnier** [comment]
https://github.com/chamilo/chamilo-lms/commit/815e3acafd449e75fce33067fb367f3a9448df24
