### ISSUE TITLE
Donde puedo encontrar los archivos html de chamilo

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#2955]
quiero cambiar el diseño de chamilo por lo tanto forzosamente necesito encontrar sus archivos html

**Comment by Katamiaw1** [comment]
quiero cambiar el diseño de chamilo y necesito forzosamente encontrar las carpetas de archivos html

**Comment by aragonc** [comment]
los archivos HTML??,  creo que te refieres a las plantillas, eso lo ubicas en main/template/default

**Comment by Katamiaw1** [comment]
quiero agregar algunas pestañas al menu, además de agregar alguna informacion en la pagina principal, necesito encontrar el diseño de la home page o la plantilla

**Comment by ywarnier** [comment]
main/template/default/layout.
Ojo que tienes que limpiar el caché (ver entrada dentro del bloque "sistema" de la página de administración) para que tome efecto.
Ojo también que puedes agregar elementos de menú y contenido de la página principal directamente desde la interface de administración ("edición de la página principal" dentro del bloque "plataforma")

**Comment by Katamiaw1** [comment]
Muchas gracias a todo por su ayuda
