### ISSUE TITLE
Se puede añadir a la barra de menu una imagen que a su vez funcione como link? 

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#2956]
Necesito añadir a la barra de menu de chamilo una imagen que funcione como link, soy nueva en chamilo

**Comment by disgregador** [comment]
Plantea estas cuestiones en el foro de la comunidad Chamilo https://forum.chamilo.org/ donde te podrán ayudar.

Normalmente github se usa para los desarrolladores para reportar errores, plantear nuevas funcionalidades, enviar sugerencias, corregir código, etc. 

Gracias.
