### ISSUE TITLE
Warning después de instalar Chamilo

### ISSUE THREAD

**Issue by salvadoracostaharo** [chamilo/chamilo-lms#2961]
**Describe**
Hola, despues de instalar chamilo me aparece el siguiente Warning, aguien sabrá como resolverlo?
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\chamilo\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php on line 2640

**Comment by ywarnier** [comment]
Tengo el mismo warning con PHP 7.3 durante el checkeo del acceso a la base de datos al momento de instalar. Parece que deberíamos actualizar la dependencia sobre Doctrine.
Es un warning, así que no es grave, pero sí se ve un poco feo.
Asigno esto a nuestro especialista.

**Comment by jmontoyaa** [comment]
La librería esta atada a chash y unas dependencias de doctrine. Lo mas simple sería de poner display_errors = off para ocultar ese warning en main/install/index.php

**Comment by ywarnier** [comment]
Necesitamos la dependencia de Chash dentro de Chamilo? Se que en algún momento queríamos tenerlos juntos por un tema de scripts de cambios de base de datos, pero no creo que siga vigente... o sí?

**Comment by jmontoyaa** [comment]
No, pero Chash necesita a Chamilo con unas dependencias de doctrine.
Cambiar las dependencias implica probar que chash instale chamilo correctamente y que todo el flujo funcione bien.

**Comment by spacecabbie** [comment]
Perhaps this helps:
`[chamilo][cronjob] Starting cron jobs as process 468509
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /*********/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640
[chamilo][cronjob] Ending cron jobs of process 468509
`
Happend when doing php run.php

**Comment by ywarnier** [comment]
Nope, doesn't help :smile:

**Comment by ywarnier** [comment]
Esto ya debería estar arreglado con el cambio de dependencia de Chamilo 1.11.14 (que ya no soporta PHP 5.6).
