### ISSUE TITLE
error al usar el file manager

### ISSUE THREAD

**Issue by woody-2019** [chamilo/chamilo-lms#2962]
Tengo el siguiente error al hacer click al boton VER SERVIDOR en el file manager:

Unable to connect to backend.
HTTP error 406

cuál puede ser la solucion

Windows 10
Chamillo 1.11.6

**Comment by ywarnier** [comment]
Deberías tratar de ver los logs del servidor web. Deberían darte más detalles sobre el error. El error HTTP 406 es un resumen de un error más profundo que, según la documentación de microsoft, tiene que ver con el juego de caracteres que tu servidor ofrece frente a lo que el usuario (navegador) acepta: https://developer.mozilla.org/fr/docs/Web/HTTP/Status/406

Nunca he visto este error antes en Chamilo, así que una vez que hayas encontrado de qué se trata, estoy interesado en saberlo.
