### ISSUE TITLE
New session doesn't copy test from course

### ISSUE THREAD

**Issue by NitAGE** [chamilo/chamilo-lms#2964]
Hello everyone,

with the previous version (1.9.x) when you created a new session adding a course, the session automatically copied the tests from the course, making them exclusive for the session.
While, after the update (1.11.x) it doesn't happen anymore.

Could you help me?

Thanks

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome

**Server
 - OS: Windows 10
 - Version of Chamilo: 1.11.x
 - Version of PHP: 7.3

**Comment by ywarnier** [comment]
If you have created the tests in the course itself (not in another session), then those tests should be visible in the newly-created session. You can the hide or delete them from the course (in which case they will disappear from all sessions), or you can hide them in your session (in which case they disappear for students in this session but remain everywhere else).

Could you describe more precisely (given the explanation above) what you are seeing that doesn't match that behaviour?

**Comment by NitAGE** [comment]
Hello ywarnier,

thanks for your reply.

Yes i have created the test in the course, but (as I said before) when you created a new session, in the before version (1.9.x), the test created was duplicate such as exclusive for the session, but now (Version 1.11.10) it doesn't happen, i see the the test but i can't edit this inside the session directly because it is not exclusive for the session.

**Comment by ywarnier** [comment]
Hi,
I'm not sure how it worked in 1.9.x (this is very old now) but it is possible indeed that it worked that way. If you want the resource to be session-exclusive now, you'll have to copy the test from inside the session (use the CD icon). This should make a local copy. The local copy will be marked with a :star: to show it's exclusive to the session. You can then (or earlier) hide the base-course resource to avoid duplicates for students.

**Comment by NitAGE** [comment]
Hi,

When i copy the test (CD icon) this isn't exclusive for session but is simple test for a course.

any ideas?

**Comment by NitAGE** [comment]
anyone?

**Comment by Coursenligne** [comment]
Answered on the Forum :)
It is the normal behaviour, I did the test 1.11.10.
1.9 (even 1.8.8) had the same behaviour, but displayed differently, that's why it is confusing.
If you set a test both in course and a copy in a session, students that are registered in both session and course (which is a non sens and should never be ;) ) will see bith tests in the course, but only test-copy in the session.
The session test is therfore local to the session.
Again previous versions didn't display exactly the same way, but I assume this  as "a bug"...
Hope this helps.

**Comment by NitAGE** [comment]
Going deeply, the issue seems to be between the 1.9.10.4 and the 1.10.0:

1.9.10.4 copying a test from inside a session adds a row in the c_quiz table with the Id of the session as sessionId value, and it puts a star near the test

1.9.10 copying a test from inside a session adds a row in the c_quiz table with 0 as sessionId value and so the system will consider the test as a course test and not as a session test

I'm trying to understand where it loses the id of the session with no luck

**Comment by NitAGE** [comment]
Found it!

in main/exercice/exercise.class.php row 778 (1.10)

`$session_id = $this->sessionId;`

replaced with:

`$session_id = api_get_session_id();`

and it works as expected (for me...)

**Comment by AngelFQC** [comment]
I changed the `Exercise::copyExercise` method to assign the current session id to the new quiz created

**Comment by ywarnier** [comment]
Looks good to me now
![session-exe-copy](https://user-images.githubusercontent.com/609839/80311925-b529de00-87e2-11ea-9841-d29107651dbb.png)
