### ISSUE TITLE
php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml no finaliza

### ISSUE THREAD

**Issue by disgregador** [chamilo/chamilo-lms#2965]
**Describe el problema**

Campus Chamilo 1.11.10 actualizado desde versiones anteriores 1.8, 1.9 y 1.10
Al ejecutar desde consola Linux 
php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml
no finaliza el proceso. No es posible pararlo con ctrl+c y se elimina con kill -9.
Se adjunta la salida generada más abajo.
En la base de datos no se ha producido ningún cambio. No había sentencias SQL ejecutándose.

**Comportamiento esperado**

Que se ejecutarán las consultas SQL y la estructura de la bases de datos coincidiera con la de Doctrine al chequear posteriormente.

**Servidor
 - Sistema operativo: Debian
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 5.6.30
- Consola Linux

**Contexto adicional**
Campus Chamilo 1.11.10 actualizado desde versiones anteriores 1.8, 1.9 y 1.10
Tabla version: 20170626091800

**Salida consola Linux:**

```
php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml
Loading configuration from command option: app/config/migrations.yml
                                                          
                    Chamilo Migrations                    
                                                          

WARNING! You have 48 previously executed migrations in the database that are not registered migrations.
    >>  (110)
    >> 2015-04-23 09:31:00 (20150423093100)
    >> 2015-05-04 18:26:00 (20150504182600)
    >> 2015-05-05 13:23:04 (20150505132304)
    >> 2015-05-05 14:29:00 (20150505142900)
    >> 2015-05-07 15:26:00 (20150507152600)
    >> 2015-05-11 13:39:49 (20150511133949)
    >> 2015-05-19 15:32:00 (20150519153200)
    >> 2015-05-21 11:36:00 (20150521113600)
    >> 2015-05-22 11:20:23 (20150522112023)
    >> 2015-05-22 22:22:22 (20150522222222)
    >> 2015-05-27 10:16:00 (20150527101600)
    >> 2015-05-27 11:42:20 (20150527114220)
    >> 2015-05-27 12:07:03 (20150527120703)
    >> 2015-05-28 10:32:16 (20150528103216)
    >> 2015-05-29 16:44:00 (20150529164400)
    >> 2015-06-03 14:25:50 (20150603142550)
    >> 2015-06-03 15:12:00 (20150603151200)
    >> 2015-06-03 18:17:28 (20150603181728)
    >> 2015-06-04 14:50:47 (20150604145047)
    >> 2015-06-08 10:46:00 (20150608104600)
    >> 2015-06-09 11:35:00 (20150609113500)
    >> 2015-06-10 14:34:26 (20150610143426)
    >> 2015-06-15 17:19:00 (20150615171900)
    >> 2015-06-16 09:32:00 (20150616093200)
    >> 2015-06-24 16:41:00 (20150624164100)
    >> 2015-06-25 15:50:00 (20150625155000)
    >> 2015-07-06 13:50:00 (20150706135000)
    >> 2015-07-09 08:37:10 (20150709083710)
    >> 2015-07-13 13:26:30 (20150713132630)
    >> 2015-08-03 16:34:00 (20150803163400)
    >> 2015-08-03 17:12:20 (20150803171220)
    >> 2015-08-05 16:10:00 (20150805161000)
    >> 2015-08-10 13:26:15 (20150810132615)
    >> 2015-08-12 23:05:00 (20150812230500)
    >> 2015-08-13 14:30:00 (20150813143000)
    >> 2015-08-13 20:00:00 (20150813200000)
    >> 2015-08-19 09:53:00 (20150819095300)
    >> 2015-08-21 15:00:00 (20150821150000)
    >> 2015-08-25 14:11:00 (20150825141100)
    >> 2015-11-01 08:22:00 (20151101082200)
    >> 2015-11-01 08:23:00 (20151101082300)
    >> 2015-11-19 08:24:00 (20151119082400)
    >> 2015-12-14 16:40:00 (20151214164000)
    >> 2015-12-14 17:08:00 (20151214170800)
    >> 2015-12-21 15:01:00 (20151221150100)
    >> 2016-07-07 13:19:00 (20160707131900)
    >> 2016-08-08 11:02:00 (20160808110200)
Are you sure you wish to continue? (y/n)y
WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating up to 20171227120000 from 20170522120000

  ++ migrating 20170608164500

```
Se ha esperado más de 15 minutos. No muestra porcentaje de progreso ni la salida de la ejecución de sentencias SQL si son correctas o no.

**Comment by opensourcecompany** [comment]
I suggest to use a recent PHP version.
We also had several issues with PHP 5.6, PHP 7 is default in Debian 10 (which you should upgrade to...).

**Comment by disgregador** [comment]
Thank you.
I have tried with PHP 7.1, 7.2 and 7.3
It generates the vendor and web directories but when executing 

php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml

it does not change the structure of the database and does not finish the update process.

_According to the page:_
https://github.com/chamilo/chamilo-lms/tree/1.11.x

You can also print the differences between your database and what it should be by issuing the following command from the Chamilo base folder:

php bin/doctrine.php orm:schema-tool:update --dump-sql

In my case it shows the following differences:

```
ALTER TABLE course_category CHANGE name name VARCHAR(100) NOT NULL;
ALTER TABLE extra_field_options ADD CONSTRAINT FK_A572E3AE443707B0 FOREIGN KEY (field_id) REFERENCES extra_field (id);
ALTER TABLE extra_field_values ADD CONSTRAINT FK_171DF924443707B0 FOREIGN KEY (field_id) REFERENCES extra_field (id);
ALTER TABLE c_quiz CHANGE title title VARCHAR(255) NOT NULL;
ALTER TABLE c_tool CHANGE name name VARCHAR(255) NOT NULL;
ALTER TABLE c_lp_category CHANGE name name VARCHAR(255) NOT NULL;
ALTER TABLE c_thematic CHANGE title title VARCHAR(255) NOT NULL;
ALTER TABLE c_survey_invitation DROP answered_at;
ALTER TABLE c_course_description CHANGE title title VARCHAR(255) DEFAULT NULL;
ALTER TABLE c_lp DROP accumulate_work_time;
ALTER TABLE c_glossary CHANGE name name VARCHAR(255) NOT NULL;
```
Best regards.

**Comment by opensourcecompany** [comment]
Could you have a look in your database?

If you are not familiar with SQL, these queries are not hard to understand ;-)
Please use phpmyadmin or similar tools (or mysql shell) to execute them one after another.

Does it break already at the first?
If so, have a look at the table course_category, there should be a column name.
Is this already type VARCHAR with limit of 100 symbols?

I guess it breaks at line 2 or/and 3 where the constraints are.
In this case you should search professional help, since this is not always easy to solve.

**Comment by disgregador** [comment]
Thank you.
I can insert the SQL queries with mysql shell or with phpmyadmin. There are not many, they can be copied and pasted without problems by external tools.

The reason for my query is that when using the console with Chamilo to verify the integrity of the database as defined in Doctrine, it does not execute these queries and updates the Chamilo database with the latest version.

The execution of php bin / doctrine.php migrations is blocked: migrate --configuration = app / config / migrations.yml stops.

It is necessary to subsequently insert the SQL queries in other ways so that when rechecking it matches the output of php bin / doctrine.php orm: schema-tool: update --dump-sql

The code should check that there is an integrity problem in the database and / or correct it by Linux shell or in the process of updating Chamilo through PHP, the Web update with the browser or through some option in the Administration that validates the integrity of the database and the version to which it is updated by making the necessary adjustment.

It would be advisable to show a message in the linux shell indicating the reason why the migration does not continue. On the contrary, it stops and you can only eliminate the process with kill -9 or allow the continuation of the migration via the Web or on the contrary if it stops at one point in the process.

Greetings.

**Comment by ywarnier** [comment]
I'm no expert in that particular script but I believe we don't support migrations.yml in v1.10.* of Chamilo.
Why are you trying to give it a particular config file?
Actually, I'm not sure the migrate command works at all (it is planned for use in Chamilo 2.0).
@jmontoyaa might have more updated info on this...

**Comment by jmontoyaa** [comment]
That script is only for development purposes (to check integrity of database, add/remove fields, etc). 
It should not be used to upgrade Chamilo from one version to another. 

The current upgrade process is using the Chamilo page (main/install/index.php) and follow the steps.

**Comment by disgregador** [comment]
Ok, the indicated scripts are for test and development purposes.

The Chamilo classroom has already been updated from 1.8, 1.9, 1.10 to 1.11.10 via main/install/index.php
It was updated without any apparent error.

However, if you write
php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml

shows that there have been no previous migrations.
WARNING! You have 48 previously executed migrations in the database that are not registered migrations.
(2015, 2016).

Questions: 
Does the script fail to verify?
Why does the previous message show?

The virtual classroom is updated 1.11.10. When writing in linux console
php bin/doctrine.php orm:schema-tool:update --dump-sql
It shows 11 SQL statements of what should be and what the database contains.

Questions:
Should the update process correct the ALTER TABLE statements when updating from the web browser?
Is that database structure of the stable version or only of the development of the git 1.11 branch?

After a successful update to Chamilo 1.11.10 via main/install/index.php is it necessary to insert the SQL statements so that the database is consistent?

Thank you.

**Comment by jmontoyaa** [comment]
First of all you don't need to run that script after or before the migration. That script is only for tests and for developers. There's only one way to upgrade Chamilo and is using the GUI as I mentioned before.

To answer your questions:

> Does the script fail to verify?

I don't see exactly what's the fail.

> Why does the previous message show?

I dont know what the status of your database or what migrations happened. That script is used only for dev purposes.

> Should the update process correct the ALTER TABLE statements when updating from the web browser?

No. Some changes could happen in the DB because of some plugin installation or some special configuration, specially if you come from a very old 1.8.x. The doctrine and the chamilo structure is not always the same because of some special changes. 

> Is that database structure of the stable version or only of the development of the git 1.11 branch?

The database structure didn't changed. All the 1.11.x (1.11.0, 1.11.2, 1.11.4, etc) versions have the same database structure

The 1.11.x branch doesn't have new database changes.

**Comment by jmontoyaa** [comment]
Where did you find that command? It should be removed from the instructions list.

**Comment by disgregador** [comment]
Gracias por las explicaciones.

Los comandos
**php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml**
y
**php bin/doctrine.php migrations:execute 20150527120703 --up --configuration=app/config/migrations.yml**

se muestran en las repositorios siguientes:
https://github.com/chamilo/chamilo-lms/tree/1.10.x
https://github.com/chamilo/chamilo-lms/tree/1.11.x
https://github.com/chamilo/chamilo-lms/tree/1.11.10-releases
https://github.com/chamilo/chamilo-lms/tree/compilatio
https://github.com/chamilo/chamilo-lms/tree/experimental2
https://github.com/chamilo/chamilo-lms/tree/forge
https://github.com/chamilo/chamilo-lms/tree/forge2
https://github.com/chamilo/chamilo-lms/tree/immediate_popup
https://github.com/chamilo/chamilo-lms/tree/lp_item_title_as_html
https://github.com/chamilo/chamilo-lms/tree/ofaj-new
https://github.com/chamilo/chamilo-lms/tree/ofaj_dev
https://github.com/chamilo/chamilo-lms/tree/ofaj
https://github.com/chamilo/chamilo-lms/tree/ofajdev2017
https://github.com/chamilo/chamilo-lms/tree/ofajpreprod
https://github.com/chamilo/chamilo-lms/tree/preprodparkur
https://github.com/chamilo/chamilo-lms/tree/whispeak

en el apartado **For developers and testers only**

```
Updating your database from new code
Since the 2015-05-27, Chamilo offers the possibility to make partial database upgrades through Doctrine migrations.

To update your database to the latest version, go to your Chamilo root folder and type

php bin/doctrine.php migrations:migrate --configuration=app/config/migrations.yml
If you want to proceed with a single migration "step" (the steps reside in src/Chamilo/CoreBundle/Migrations/Schema/V110/), then check the datetime of the version and type the following (assuming you want to execute Version20150527120703)

php bin/doctrine.php migrations:execute 20150527120703 --up --configuration=app/config/migrations.yml
You can also print the differences between your database and what it should be by issuing the following command from the Chamilo base folder:

php bin/doctrine.php orm:schema-tool:update --dump-sql
```

**Comment by opensourcecompany** [comment]
I must admit i also run this:
php bin/doctrine.php orm:schema-tool:update

But without the parameter (app/config/migrations.yml), and after several upgrades there was none which upgraded flawless by using only the webbased install/upgrade process.

**Comment by ywarnier** [comment]
No veo como dar una conclusión feliz a esta tarea. Veo que @disgregador tiene problemas con migraciones antigua(za)s que no debería ejecutar usando un script de prueba, pero que igual las quiere ejecutar :-)
Creo que hay mejores formas de ocupar nuestro tiempo que de argumentar sobre esto, así que cierro la tarea.
