### ISSUE TITLE
Certificat - Export PDF ne prend pas en compte les images

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#2967]
J'utilise le certificat par défaut et l'assigne à un test.
Lorsque le test est passé, le certificat est généré.
La prévisualisation fonctionne OK, mais l'export PDF ne prend pas en compte certaines images
Je joins l'image de prévisualisation + le PDF généré
![certificat_visualise](https://user-images.githubusercontent.com/32436850/62698579-c37a6480-b9dd-11e9-8fd5-224fea326ea8.PNG)
[Certificat(1).pdf](https://github.com/chamilo/chamilo-lms/files/3481372/Certificat.1.pdf)

**Comment by Coursenligne** [comment]
Update 
Après plusieurs tests, j'ai recréé un certificat.
Si les images sont importées localement au cours, alors elles sont bien prises en compte.
Les images qui proviennent du répertoire par défaut sont celles qui sont ignorées.
Espérant aider.
Merci à vous.

**Comment by ywarnier** [comment]
Oui, c'est un problème connu mais nous n'avons pas de solution à court terme. Nous espérons que ce sera corrigé par la remanipulation forte que nous faisons par rapport à la gestin des ressources dans la version 2.0.

**Comment by Coursenligne** [comment]
OK => possible de clore celle-là ; j'en crée une autre sur l'export PDF :)
Merci Yannick
