### ISSUE TITLE
Export PDF Learning path - une image "cassée"

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#2968]
Lors de la création d'un LP, si on laisse la possibilité d'exporter le cours en PDF, l'entête de l'export contient le nom de la personne qui exporte (EXCELLENT !)
Mais à gauche du nom, il y a l'image d'une croix rouge (image cassée, non exportée).
Impossible de trouver comment éviter la présence de cette image (un fichier PHP à éditer ?) pour ne pas avoir ce désagrément.

Merci à vous.

**Comment by Coursenligne** [comment]
Peut-être pas de lien direct, mais si j'exporte en tant qu'étudiant, mon nom n'est pas mentionné dans l'entête, alors que l'enseignant est bien noté.
Le fait d'avoir le nom de la personne qui exporte est un réel intérêt pour les clients.

**Comment by ywarnier** [comment]
> Le fait d'avoir le nom de la personne qui exporte est un réel intérêt pour les clients.
À demander dans une nouvelle issue :-)

**Comment by ywarnier** [comment]
In the learning path export to PDF, remove the little red cross from a missing image coming from some HTML somewhere.

**Comment by AngelFQC** [comment]
The little red cross is the platform logo. 
I change the code to generate PDF to display the platform logo

**Comment by Coursenligne** [comment]
Hi Angel,
I need to retreive the files and put them on my latform.
I tell you when I made the test.

**Comment by Coursenligne** [comment]
OK;
I modified the files and nothing changed.
I occur that now the name of the loggedin user is not included anymore.

**Comment by AngelFQC** [comment]
Hi @Coursenligne 
I got this when exporting a learning path exported to PDF
![imagen](https://user-images.githubusercontent.com/1697880/89372342-82c63180-d6ab-11ea-8351-5143846d776d.png)

**Comment by Coursenligne** [comment]
Hi Angel,
In order to ensure....
Could you please provide me with the modified files (in case I missed something), as, if you get the pdf you attached this would be GREAT estpecially if at the mentime you fixed the name not exported issue :)
I can't get it working on my test installed platform.
Thanks in advance for yous help

**Comment by AngelFQC** [comment]
Hi  @Coursenligne 
You can test it here https://11.chamilo.org/main/lp/lp_controller.php?cidReq=TESTING&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by ywarnier** [comment]
@Coursenligne The only change made is this one: https://github.com/chamilo/chamilo-lms/commit/c623b960becf9b415faf034ebe900c4099c94a8d but it applies to 3 different files. Testing it on 11.chamilo.org should be enough for you to approve it, as we can't check manual changes on your install to see if everything checks out.
