### ISSUE TITLE
Oposite selected users on notify inactive users since never

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#2971]
**Describe**
On course Report, when you select to notify users that "never" accessed the course before, you are directed to course announcement with the recipients selected.
But the selected users are wrong. The users selected are the ones that "already accessed" the course.
Must be a logic error when passing arguments on php code.
I'll try to search for it in the libs and report back for you.

**To Reproduce**
1. Go inside a course > Reports (Curso/Relatórios)
2. Click on 'Remember inactive users since [Never]'  (Lembre alunos inativos desde Nunca)
3. See that the list generated is opposite as it should be.

 - Version of Chamilo: 1.11.8, 

**Additional context**

**Comment by marshel** [comment]
Sorry but I was unable to solve this.

The bug tracking started at:
tracking/courseLog.php
then the scripts calls
announcements/announcements.php
that for itself call the class
Tracking::getInactiveStudentsInCourse

That uses this query:

public static function getInactiveStudentsInCourse(
 //... line 4371 ////
                     `$sql = 'SELECT course_user.user_id
                        FROM '.$table_course_rel_user.' course_user
                        LEFT JOIN '.$tbl_track_login.' stats_login
                        ON course_user.user_id = stats_login.user_id AND
                        relation_type<>'.COURSE_RELATION_TYPE_RRHH.'
                        INNER JOIN '.$tableCourse.' c
                        ON (c.id = course_user.c_id)
                        WHERE
                            course_user.c_id = '.$courseId.' AND
                            stats_login.login_course_date IS NULL
                        GROUP BY course_user.user_id';`

Getting the query and putting the ids/tables manually on phpmyadmin gives the correct users ids of inactive users, but somehow after that the opposite of users are auto selected on the announcements page.

On the other way, day based inactive notifications seem to work correctly...

**Comment by carlangas159** [comment]
hello @marshel 

users who have not logged in are shown on the right while users who have already logged in are shown on the left,

![image](https://user-images.githubusercontent.com/18097392/86160825-f59f2400-bad1-11ea-9070-bab4e263aed9.png)


Also note that if I log in as administrator and then,  log in as a user who never logged in, logging into the course is not registered as if I had logged in

![image](https://user-images.githubusercontent.com/18097392/86160923-22533b80-bad2-11ea-9eca-98dafc078f81.png)

thus, the following query

SELECT course_user.user_id FROM '.$table_course_rel_user.' course_user LEFT JOIN '.$tbl_track_login.' stats_login ON course_user.user_id = stats_login.user_id AND relation_type<>'.COURSE_RELATION_TYPE_RRHH.' INNER JOIN '.$tableCourse.' c ON (c.id = course_user.c_id) WHERE course_user.c_id = '.$courseId.' AND stats_login.login_course_date IS NULL GROUP BY course_user.user_id

it shows me the result as if that user did not enter the course.

However, if I enter the system as the student of the course in the normal way and then enter the course, if I register to enter it.

The users of the report who never entered the course were made through the administrator login? Or did they normally enter the system?

**Comment by ywarnier** [comment]
Closing for lack of feedback
