### ISSUE TITLE
chamilo 1.9 marca error con mysql que necesita mysqli

### ISSUE THREAD

**Issue by felipecabada** [chamilo/chamilo-lms#2976]
Hace una semana mi chamilo 1.9.8 dejo de funcionar debido a que las consultas mysql_connect no funcionan, que debia usar mejor mysqli. Tengo instalado PHP5 y PHP7 por que pense que con PHP7 se resolveria, pero nada.

En el directorio main/inc/lib encontre un archivo llamado database.mysqli.lib.php y leyendo decia que si sustituia ese archivo por el database.lib.php se reseulve el problema, pero me marca errores en muchas partes, que mas hay que hacer en ese archivo a parte de renombrar una clase que se llamaba MYSQLDatabase a Database.

Tengo muchos problemas con esto, ya que mucha funcionalidad no ingresa y marca errores raros.

**Cómo reproducir**
Quisiera haber renombrado el archivo y que funcionara

**Comportamiento esperado**
Que funcionara tan bien como lo estaba desde hace 3 años. No he migrado a ninguna otra version

**Servidor
 - Sistema operativo : Ubuntu 16.04
 - Versión de Chamilo:  1.9.8 instalado 2017
 - Versión de PHP: 5 y 7

**Comment by ywarnier** [comment]
Hola @felipecabada 
Hemos dejado de soportar 1.9 en 2015: https://github.com/chamilo/chamilo-lms/wiki/Supported-versions
La manera más ahorradora de tiempo que tienes para solucionar este problema es actualizar a Chamilo 1.11.10.

Esto siendo dicho, las migraciones desde versiones 1.9 son unas de las más complejas hasta la fecha. No tanto porque el proceso es complejo, sino porque hay muchas posibilidades de que algunos datos (no muchos, quizás 5% o menos, pero a veces molesta) queden mal migradas porque se interrumpe el proceso a medio camino o algo así.

Por eso es importante preparar bien el proceso, tomar un backup que no toques más (de base de datos y archivos) y lanzar la actualización según el manual de actualización https://11.chamilo.org/documentation/installation_guide_es_ES.html

Siempre puedes acercarte a un proveedor oficial que se puede encargar de esta migración por ti (contra presupuesto, obviamente): https://chamilo.org/providers

Sin embargo, en esta tarea no podemos ayudarte, aquí es un espacio de intercambio sobre el desarrollo y el de 1.9 se terminó en 2015.
