### ISSUE TITLE
Chamilo 1.11,10 Themes

### ISSUE THREAD

**Issue by Haboubi92** [chamilo/chamilo-lms#2977]
the options of inbox, my certificates and logout doesn't appear in certain themes **when viewed form mobile** (may be a font color problem)

![Screenshot_20190826-105429](https://user-images.githubusercontent.com/48198054/63676229-25ff9d00-c7f3-11e9-9fd9-f782b030da4e.png)

I will list here the effected themes 

cool blue
![Screenshot_20190826-105738](https://user-images.githubusercontent.com/48198054/63676779-5b58ba80-c7f4-11e9-8016-6c024d208629.png)

corporate
![Screenshot_20190826-105804](https://user-images.githubusercontent.com/48198054/63676786-5eec4180-c7f4-11e9-9167-4972737bdaf2.png)

cosmic campus
![Screenshot_20190826-105848](https://user-images.githubusercontent.com/48198054/63676795-63b0f580-c7f4-11e9-8b41-9e3242eaa77c.png)

delicious Bordeaux
![Screenshot_20190826-105933](https://user-images.githubusercontent.com/48198054/63676807-6875a980-c7f4-11e9-87e4-fa01929b1a9e.png)

fruity orange
![Screenshot_20190826-110037](https://user-images.githubusercontent.com/48198054/63676816-6d3a5d80-c7f4-11e9-8d38-6ee9261281c0.png)

journal
![Screenshot_20190826-110140](https://user-images.githubusercontent.com/48198054/63676839-75929880-c7f4-11e9-9ae0-bbb8956bc198.png)

kiddy
![Screenshot_20190826-110238](https://user-images.githubusercontent.com/48198054/63676844-79beb600-c7f4-11e9-85ee-c55932a0af89.png)

medical
![Screenshot_20190826-110316](https://user-images.githubusercontent.com/48198054/63676852-7d523d00-c7f4-11e9-83be-37b795450d1d.png)

royal blue
![Screenshot_20190826-110413](https://user-images.githubusercontent.com/48198054/63676857-80e5c400-c7f4-11e9-86fe-1e5d4a6a71e4.png)

sober brown
![Screenshot_20190826-110540](https://user-images.githubusercontent.com/48198054/63676870-85aa7800-c7f4-11e9-89b2-bbbe2ceebbd1.png)

steel grey
![Screenshot_20190826-110713](https://user-images.githubusercontent.com/48198054/63676875-893dff00-c7f4-11e9-935d-499f5e9f0e26.png)

I knew about this issue when 1.11.10 was released but I didn't report it because
1- Chamilo version 2 would have a brand new interface. 
2- this is not critical issue
but since there would be version 1.11.12 than I thought it would suitable to report it since it's effecting many themes.

note: I used 11.chamilo.org to reproduce the problem

**Comment by jmontoyaa** [comment]
I just updated the 11.chamilo.org styles (using composer update)

**Comment by Haboubi92** [comment]
Thanks @jmontoyaa & @aragonc ❤
I tested the themes with Firefox mobile Browser (I didn't use Chrome mobile browser because I had to Clear Cache first)
and Now the Problem is fixed for all effected themes (except "delicious Bordeaux")

**Comment by Haboubi92** [comment]
@ywarnier I suggest listing this bug within Chamilo 1.11.12 Milestone
