### ISSUE TITLE
Logo not shown in emails

### ISSUE THREAD

**Issue by farhadbarati** [chamilo/chamilo-lms#2979]
hi
in emails sent by chamilo LMS the logo is not shown. is there any solution for this problem?
thanks.

![image](https://user-images.githubusercontent.com/47290937/63824735-6c790700-c96d-11e9-84e0-b7537566a282.png)

**Comment by ywarnier** [comment]
Can you view the source of the e-mail? The logo should be in a public path, and in the source you should have an "img" tag with an "src" attribute that contains the path. If you logout from Chamilo and load that path, you should see the logo.

**Comment by farhadbarati** [comment]
thank you. i've checked it. it seems only in outlook logo not shown and in web mail the logo is shown.

**Comment by farhadbarati** [comment]
can i use another logo (different logo that i uploaded) in here:
(replace logo section with url of my image)
![image](https://user-images.githubusercontent.com/47290937/64071879-5636b800-cc99-11e9-8765-73556c72e7f3.png)

**Comment by ywarnier** [comment]
Yes. The "{{ logo }}" marker is normally replaced by an HTML code generated in https://github.com/chamilo/chamilo-lms/blob/1.11.x/src/Chamilo/CoreBundle/Component/Utils/ChamiloApi.php#L117
So it's not just a URL, but you could make a quick hack for that.
Also, to avoid overwriting the default Chamilo template and maintain updatability, you should check how to create a custom template here: https://docs.chamilo.org/en/developer/theming_through_templates/

**Comment by farhadbarati** [comment]
thank you very much :)
