### ISSUE TITLE
Inconveniente Autenticación LDAP

### ISSUE THREAD

**Issue by fabian50** [chamilo/chamilo-lms#2984]
**Describe el problema**
Se aplicaron las configuraciones en los ficheros para la autenticación contra LDAP.
La opción Añadir usuarios LDAP" ya aparece pero al efectuar la busqueda no retorna ningun usuario.

**Cómo reproducir**
Pasos para reproducir el problema:
En administracion-Añadir usuarios LDAP-.
Se ingresa un codigo de usuario que existe en LDAP , al buscar no retorna nada.

**Comportamiento esperado**
Recuperar el usuario buscado y agregarlo al chamilo

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/36686605/64213876-f9432980-ce73-11e9-8e9c-29fa2c341016.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : windows 10
 - Navegador [ej. chrome,

**Servidor
 - Sistema operativo : windows server 2016
 - Versión de Chamilo:  1.11.8. 
 - Versión de PHP: 7.2.14

**Contexto adicional**
En los log access   apache no aparece ningun indicio del inconveniente.

**Comment by alejandroalborno** [comment]
Hola Fabian, Lograste Solucionar la conexion
????

**Comment by fabian50** [comment]
Hola @alejandroalborno  nunca lo pude solucionar, en este momento la plataforma sigue trabajando con la autenticación propia de la aplicación.

**Comment by ywarnier** [comment]
Hola @fabian50 
Como indicado en la #2983, puedes cambiar el valor de la variable $debug en main/auth/external_login/login.ldap.php (o modificar cualquier de los scripts de esta carpeta) para obtener más feedback de parte del código y saber lo que puede estar pasando.
Las implementaciones de LDAP pueden variar y las configuraciones entre servidores pueden tener muchos tipos de problemas distintos, pero tenemos varias configuraciones funcionales en producción que usan LDAP. Sin embargo, cada configuración toma mucho tiempo todavía.
En cada nueva versión de Chamilo, tratamos de mejorar un poco esta parte.

Cierro la tarea porque de nuestro punto de vista no es un problema de Chamilo, pero aceptamos contribuciones al código si llegas a mejorar alguna parte. Somos como tu, a veces tenemos problemas y los vamos solucionando, analizando con tranquilidad.
