### ISSUE TITLE
Usuarios se confunde al cambiar contraseña, por información no acertada

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2985]
**Describe**
En ítem Mi Perfil, al tratar de modificar la contraseña, la plataforma no me indica o no me alerta que primero debo ingresar la clave actual y luego ingresar la nueva clave para que pueda modificar.

Iintente cambiar mi clave, solamente ingresando la nueva contraseña, la plataforma me dice que guardo los cambios, pero finalmente no me guarda la nueva clave.

**Screenshots**
![contrasena](https://user-images.githubusercontent.com/2940509/64226654-d92c5e00-cea5-11e9-8664-0aca3026970c.png)

Chamilo 1.11.x

**Comment by aragonc** [comment]
He creado las siguientes variables de idioma para traducción.

$ChangePasswordCurrent= "Si deseas cambiar su contraseña, deberas escribir tu contraseña actual, de lo contrario dejar el campo vacío";
$EnterNewPassword="Ingresar tu nueva contraseña, solo si deseas cambiarla";
$RepeatYouNewPassword="Repite tu nueva contraseña ingresada anteriormente";

![pass_word_nuevo](https://user-images.githubusercontent.com/2940509/64227118-cfa3f580-cea7-11e9-8887-495f96fae863.png)

**Comment by ywarnier** [comment]
OK para los dos de a bajo, pero el texto de arriba es solamente un error de traducción en español. La versión en inglés está muy clara y no es necesario modificar nada del primer campo.
Estoy corrigiendo también los nombres de variables en inglés porque... bueno... ya. Buen intento en todo caso.

**Comment by ywarnier** [comment]
Afinado un poco en 38fb5b656577 y el update de términos de idiomas que siguió.
