### ISSUE TITLE
How to customize the first admin login page

### ISSUE THREAD

**Issue by djparida** [chamilo/chamilo-lms#2986]
I want to customize the first admin login page but I am not getting the file where I can Add or edit.

**Comment by ywarnier** [comment]
This is a bit old and in Spanish, but hopefully there are enough screenshots to help you find your way around:
https://www.youtube.com/watch?reload=9&v=swCojMHtbYA

In short: use the /custompages folder and replicate all ".dist" files that you need as non-dist files and enable the custompages option in the settings.

**Comment by visiojd** [comment]
Hi Yannick,
A bit old post to ask you if it's possible to use the custom pages in a multi-url environnement ? In order to customize every portal login page.
Thank you.
