### ISSUE TITLE
Buy course plugin : Pagination for courses/sessions list

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2987]
On the free campus, there are so many courses that the listing page doesn't load anymore (it either reaches memory_limit or explodes the load time of the page in the browser).

**Describe the solution you'd like**
We should use pagination (and a search box by title and code)

**Additional context**
The script involved is /plugin/buycourses/src/configuration.php and it loads getCoursesForConfiguration() here https://github.com/chamilo/chamilo-lms/blob/c3b5235396783b7d4238069788e04fd647987e37/plugin/buycourses/src/buy_course_plugin.class.php#L531-L550

The view is here: https://github.com/chamilo/chamilo-lms/blob/c3b5235396783b7d4238069788e04fd647987e37/plugin/buycourses/view/configuration.tpl#L40-L95

So a pagination mechanism could be added as parameters to give a search term, a start and an number of pages to getCoursesForConfiguration(), for example, but the template would still need to be updated to add previous-next buttons.

Also, the current view of courses, sessions and services in 3 different tabs can be changed. There's no fixed requirement for that presentation.

**Comment by jmontoyaa** [comment]
What's the URL with the problem?

**Comment by ywarnier** [comment]
The URL is /plugin/buycourses/src/configuration.php on the free campus.
You need about 36K courses for that to happen (which is a real case we have on the campus).

**Comment by ywarnier** [comment]
This is very nice! Thank you.
Next we could add a search box, but for now it's enough.
