### ISSUE TITLE
Issue cmi.core.entry

### ISSUE THREAD

**Issue by miguelvdb** [chamilo/chamilo-lms#2988]
Hello, I hope someone can help me with the following issue:

### Current behavior
When I quit a course, the LMS sets the value cmi.core.exit to "suspend". When you re-enter the course, the value for cmi.core.entry returned 'ab-initio'

### Expected behavior
Regarding the Scorm 1.2 documentation, the expected return value for cmi.core.entry is 'resume'

### Steps to reproduce
Upload a SCORM 1.2 file and open it. If you turn on the debug information you can see dat when you reopen the course, you see the following statement:

SCORM: LMSGetValue
	('cmi.core.entry') returned 'ab-initio'

### Chamilo Version
1.11.4

Kind Regards,
Miguel van den Branden

**Comment by miguelvdb** [comment]
Does anyone have a solution / explenation for the behavior mentioned above?

Kind Regards,
Miguel

**Comment by ywarnier** [comment]
Hi @miguelvdb 
You should definitely use the latest version of Chamilo for SCORM-related stuff, as we update SCORM support over time (even for SCORM 1.2).

You can find the code corresponding to cmi.core.entry here:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/lp/scorm_api.php#L453

As you can see, if Chamilo saved the previous value as 'suspend', it will return 'resume'.

The value itself comes from learnpathItem.class.php, where core_exit is set to the value of core_exit in the c_lp_item_view table where... nothing writes it. So basically you seem to be absolutely right, as I haven't been able to locate the place where we change that in the database, and I cannot explain it.

Is there a chance you could test the code change I'm sending in a branch here? It's just a 3-4 lines change, so you should be able to apply it manually and see if it works. I'm not sure I have a SCORM that uses cmi.core.exit, so if you're still around and can test it, that would be super appreciated.

Note that the rest of the code seems to be OK to return you the correct cmi.core.entry with that change, so there's nothing to be changed there.

**Comment by ywarnier** [comment]
You'll have to apply both commit to check.

**Comment by ywarnier** [comment]
I'm assuming this works now...
