### ISSUE TITLE
Deleting questions from question pool shows wrong count afterwards

### ISSUE THREAD

**Issue by 22phuber** [chamilo/chamilo-lms#2991]
**Describe**
Deleting question from question pool shows wrong count afterwards.

**To Reproduce**
0. Install chamilo-lms 1.11.10
1. Create a course
2. Download the quiz_template.xls and imported it twice in the created course without a change.
3. Go to course->tests and click the question pool
4. Count the questions you see.
5. Delete a random question
6. Count the questions after the page reloads again (the count should now be wrong, not displaying all question minus the delete one)
7. Go to course->tests and click on the question pool again.
8. Count the questions again. The count should be correct now displaying all remaining questions.

**Expected behavior**
After deleting a question from the question pool, it shows the correct count of questions minus the delete one.

**Screenshots**
![ChamiloLMS_DeletingQuestionsBUG](https://user-images.githubusercontent.com/17426101/64527641-c4692380-d306-11e9-8b82-ad69be44bf25.gif)

**Desktop (please complete the following information):**
 - OS: OS X Mojave
 - Browser: Chrome --> version: Version 76.0.3809.132 (Offizieller Build) (64-Bit)

**Server
 - OS: OS X Mojave with [docker-compose setup](https://github.com/22phuber/docker-compose-chamilo-lms) / Docker Community v2.1.0.2 (37877) / Compose v1.24.1
 - Version of Chamilo:  1.11.x (1.11.10)
 - Version of PHP: PHP 7.3.6 (cli) (built: Jun 28 2019 01:27:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.6, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.6, Copyright (c) 1999-2018, by Zend Technologies

**Additional context**
Could be a caching issue and i'm not shure if other (not dockerized) installations are affected as well.

**Comment by michel3141** [comment]
Hi, I encountred the same issue. 

The pool lists all questions from both exercices.
Then you delete one question from exercice#1.
On reload, the pool lists the remaining questions from exercice#1 (but the combobox still display : 'All')

[_I'm new here. I hope this comment is the way to do_]

**Comment by 22phuber** [comment]
@michel3141 Did you use also a Docker image?

**Comment by michel3141** [comment]
@22phuber No, it's a version 1.11.10 of Chamilo, installed from unpacking chamilo-1.11.10-php7.tar.gz.
(to be true : i don't know about doker images)

**Comment by ywarnier** [comment]
Hi @22phuber 
The commit https://github.com/chamilo/chamilo-lms/pull/3433/commits/5104308e5fce0f755693e14f6db135ae44222f3d should fix the issue. I've seen it work now, but we'd like to get your approval too, if you can.

**Comment by ywarnier** [comment]
It's a one-liner, so you should be able to apply the patch even without knowledge of Git (just follow the link and see at which line we insert a new line and do that on your code before testing)

**Comment by ywarnier** [comment]
Feel free to comment later on. In the meantime, I'm taking the liberty to approve it as I've seen it work and have checked the patch.

**Comment by 22phuber** [comment]
Sorry for the late answer. This is working now! Thank you 🙏
