### ISSUE TITLE
SVG icons mode: social network and plugin icons not available in SVG format

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#2992]
En la red social, los 3 iconos debajo de la foto del usuario siguen en PNG a pesar de activar el modo de iconos SVG. Algo está mal ahí (por lo menos algunas tienen una versión SVG así que debe ser algo de TPL).
El icono main/img/icons/32/plugins.png no existe en SVG por lo que se ve mal en modo SVG en el panel de administración (cuando un plugin lo usa).

**Comment by aragonc** [comment]
Cambios enviados y hice unos pequeños arreglos.

![perfil_avatar](https://user-images.githubusercontent.com/2940509/64636446-59cbec80-d3c7-11e9-9186-35e6d6de6ebf.png)
