### ISSUE TITLE
nuevos css de paises

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#2994]
En la rama css_educations, se crearón  nuevos css de paises.

![header_mexico](https://user-images.githubusercontent.com/2940509/64727639-e4334f80-d49e-11e9-8cb2-1196e8bc8fcc.png)

![educa_colombia](https://user-images.githubusercontent.com/2940509/64727648-e72e4000-d49e-11e9-8e71-057f26ea3c33.png)

![educa_peru](https://user-images.githubusercontent.com/2940509/64727653-ea293080-d49e-11e9-8e37-b2a48466a548.png)
![educa_chile](https://user-images.githubusercontent.com/2940509/64727654-ebf2f400-d49e-11e9-88a6-b65531a19c43.png)

**Comment by jmontoyaa** [comment]
El chullo es chileno ??
