### ISSUE TITLE
Mobile View: User Profile Drop down like logout inbox buttons not visible. 

### ISSUE THREAD

**Issue by rajeekum** [chamilo/chamilo-lms#2995]
**Describe**
After login from mobile device, observed that Login, Inbox and My certification is not visible from drop down.

**To Reproduce**
1. Login as user from Mobile device
2. Click on username -->> Drop down will display with Name and email and with additional information like inbox, my certificate and logout. Which is not visible. Desktop version it works fine.
3. I have made to default.css and base.css but it didnt work.
4. Attached screen shot

**Expected behavior**
Mobile device should able to see all the user profile options.

**Screenshots**
Attached
![Screenshot_20190915_215513](https://user-images.githubusercontent.com/55356819/64924571-d1ed4480-d803-11e9-900e-be34c0966a92.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - All 

**Server
 - OS: Windows 10
 - Version of Chamilo: 1.11.10
 - Version of PHP: 7.2

**Additional context**
NA

**Comment by AngelFQC** [comment]
Solved in #2977
