### ISSUE TITLE
Uncaught PDOException: SQLSTATE[42000]: during chamilo 1.11.10 installation #1

### ISSUE THREAD

**Issue by chinovelasco** [chamilo/chamilo-lms#2996]
I am receving the following error messages when trying to install Chamilo version 1.11.10 in a new VPS running php 7.3 using runcloud framework

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'grupolarichamilobdu'@'%' to database 'grupolarichamilobd' in /home/runcloud/webapps/grupolarichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41 Stack trace: #0 /home/runcloud/webapps/grupolarichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(41): PDO->exec('CREATE DATABASE...') #1 /home/runcloud/webapps/grupolarichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1060): Doctrine\DBAL\Driver\PDOConnection->exec('CREATE DATABASE...') #2 /home/runcloud/webapps/grupolarichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(1030): Doctrine\DBAL\Connection->executeUpdate('CREATE DATABASE...') #3 /home/runcloud/webapps/grupolarichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(412): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql('CREATE DATABASE...') #4 /home/runcloud/webapps/grupolarichamilo/vendor in /home/runcloud/webapps/grupolarichamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 93

**Comment by nosolored** [comment]
Hi.

The message seems to indicate the user does not have permissions to create database.

You must previously create a database and then you must give permissions on it.

I have simulated the installation of Chamilo 1.11.10 on Ubuntu 19.04, Apache 2.4.41 and PHP 7.3.9 does not show any error message.

I have downloaded the file from https://github.com/chamilo/chamilo-lms/releases/download/v1.11.10/chamilo-1.11.10-php7.zip

What software versions do you use Apache, MySQL, PHP, etc. with Runcloud?

**Comment by ywarnier** [comment]
As specified in the installation guide (https://campus.chamilo.org/documentation/installation_guide.html#1._Pre-requisites):
"You will need a login and password allowing you to manage and drop+create a database. Usually, the default configuration on local computers is to allow you to connect as root with an empty password. It is HIGHLY RECOMMENDED to change the password and define a user with access to only a specific database. Please refer to the MySQL or MariaDB documentation in order to do this."

**Comment by ywarnier** [comment]
One way to test it is to connect from the command line, but I'm not sure you can do this on Runcloud. If you can, you could simply test this command:
```mysql -u grupolarichamilobdu -p grupolarichamilobd```
and see what it tells you. Not sure the "u" at the end of grupolarichamilobdu is what you were trying to do.

**Comment by chinovelasco** [comment]
We finally realized that it was our fault.
Fortunately everything is working fine now with the exception of this issue
https://github.com/chamilo/chamilo-lms/issues/3003

**Comment by ywarnier** [comment]
@chinovelasco could you explain the solution for other people who might have the same issue in the future, please?

**Comment by schoubi** [comment]
Hi

Maybe there is a bug somewhere in the sql user password treatment.

I uncounter the same behaviour on a new install : `SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'chamilodb'@'localhost' to database 'chamilo'`

Via CLI all was fine : i can connect, drop/create database, drop/create tables....After a few headscratching, i chane the user sql password to something less complicated (from` &8dVZzQq7ti!$!` to `test123`) and the installation finally goes through.

So my guess is there's something wrong during the password handling (size of the password and/or managing of special characters).

HTH,
