### ISSUE TITLE
Chamilo - Corregir textos de multi-base de datos y root en proceso de instalación

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#2997]
**Describe el problema**
En la instalación de Chamilo se indica que va a crear las bases de datos y parece inducir a que es necesario usar el usuario root de MySQL/MariaDB. No es correcto.
Sería aconsejable cambiar los textos ya que induce a error (varios comentarios en foros).
Se puede instalar Chamilo en hosting en una sola base de datos y no se necesita usuario root para ello.

**Cómo reproducir**
En main/install/index.php?running=1&installType=new&updateFromConfigFile=

Textos:
The install script will create the Chamilo main database(s). Please note that Chamilo will need to create several databases. If you are allowed to use only one database by your Hosting Service, Chamilo will not work, unless you chose the option "One database".

Nueva instalación
Paso 4 de 6 – Parámetros de las bases de datos MySQL
El script de instalación creará las principales bases de datos de Chamilo. Por favor, recuerde que Chamilo necesitará crear varias bases de datos. Si sólo puede tener una base de datos en su proveedor, Chamilo no funcionará.

**Comportamiento esperado**
Modificar los textos en español e inglés para indicar que Chamilo necesita una base de datos y debe ser creada previamente.
El instalador no creará la base de datos salvo que se use root (algo no recomendado en sistemas en producción).

Los campos deberían estar en blanco sin ningún contenido y no poner como ejemplo root.

**Capturas de pantalla**
Se adjuntan.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**

En el foro de Chamilo se han dado varios casos indicando que se necesita el usuario root de MySQL/MariaDB o múltiples bases de datos para instalarlo.

Confunde a los usuarios.
![19-09-2019 13-49-27](https://user-images.githubusercontent.com/5868981/65242529-875f1700-dae6-11e9-8397-4d0664efadf7.png)
![19-09-2019 13-51-13](https://user-images.githubusercontent.com/5868981/65242530-875f1700-dae6-11e9-9ce6-cb18366ccf61.png)

**Comment by ywarnier** [comment]
Wow, this is a very old message (creating several databases). Thanks for reporting.

**Comment by ywarnier** [comment]
Just a detail: The database *is* created if it does not exist. The user root is not mandatory to do that, but the user has to have the right to create the database. This can be done with:
```grant all privileges on testchamilo.* to testchamilo@localhost identified by 'testchamilo';```
(for example).
(obviously not with those user and password)
Some hosting services, however, will not give "all privileges" on a given database to a given user, making it impossible for Chamilo to create said database. This is not a Chamilo issue, though.

**Comment by ywarnier** [comment]
cf94f8cef6ac49d2981b09be6ef187ed0304588a fixes the issue for English, Spanish and French. Other languages should be updated by their translators.

**Comment by nosolored** [comment]
@ywarnier: "Some hosting services, however, will not give "all privileges" on a given database to a given user, making it impossible for Chamilo to create said database. "
In this case, you can create the database previously and then install Chamilo, but some users don't know that

**Comment by ywarnier** [comment]
Indeed, but we can't educate the whole world :-)
Users who don't know that should probably not install Chamilo themselves and rather use Installatron, Softaculous or DigitalOcean installers
