### ISSUE TITLE
Cuando compras una sesión o estás inscrito en el catalogo aún te permite comprar la sesión

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#3000]
**Describe**
Es normal que me permita comprar nuevamente una sesión donde ya estoy inscrito?
![compra_hecha](https://user-images.githubusercontent.com/2940509/65362466-1a727c80-dbcd-11e9-95a7-9bdded1dd607.png)

Si voy a dar clic al enlace de la sesión donde veo el about del curso.
me permite comprar de nuevo, debería decir Ya te encuentras inscrito en dicha sesión?
![session_comprar_de_nuevo](https://user-images.githubusercontent.com/2940509/65362498-3e35c280-dbcd-11e9-8f20-1f944e9aaaac.png)

**To Reproduce**
Compras una sesión y vuelve a comprar por about?

**Comment by ywarnier** [comment]
@aragonc Tuviste la oportunidad de probar el cambio de Angel?

**Comment by ywarnier** [comment]
Assuming this is fixed (no feedback). Closing
