### ISSUE TITLE
Is the support of SCORM 2004 planned ?

### ISSUE THREAD

**Issue by AndrewHobson** [chamilo/chamilo-lms#3001]
Hello,
Our teachers create content for one of our customer's eLearning platform and we would like to reuse this content in our own chamilo eLearning system.
But the two plaforms are using different versions of SCORM.
Chamilo uses version 1.2 and the customer platform uses SCORM v2004.
My questions are :
Is it planned for chamilo to support SCORM v2004 ?
Is there some easy way to convert from SCORM 1.2 to 2004 ? And vice versa ?
Thanks a lot for explaining the plan on this subject.

**Comment by ywarnier** [comment]
Hi @AndrewHobson, 

There are no plans to support SCORM 2004. This version of SCORM is largely considered (in the LMS world) a very specific re-implementation of SCORM that adds great features that... are never used.
As such, many people have been tricked into developing their contents in "the latest version", while using pretty much all the feature set of SCORM 1.2 (which we support) and nothing more.

For us, the extra work required to support SCORM 2004 is just not worth it. There is now a new standard (xAPI with CMI5) that is more widely accepted as the future of shared learning objects and communications, and that we plan to support in Chamilo 2.

Thankfully, the common tools used to generate content in SCORM usually offer an option to export to SCORM 1.2 *or* SCORM 2004. This can be found as an option at the time of exporting to SCORM.

**Comment by ywarnier** [comment]
I should add that, if you have the budget for the development of the support of SCORM 2004 (this is a major development though), feel free to contact our official service providers: https://chamilo.org/providers

**Comment by AndrewHobson** [comment]
Thank you for taking the time to reply and explain the situation.
