### ISSUE TITLE
Course dont get setup properly 

### ISSUE THREAD

**Issue by christophergilchrist** [chamilo/chamilo-lms#3004]
When creating a course it creates the directory in /app/courses but the course homepage doesnt get created and the url doesnt work in the browser I get a not found error ?

**Comment by ywarnier** [comment]
Hi @christophergilchrist 
Did you check the installation guide?
You need to allow your web server to interpret .htaccess files, or define redirections directly into your vhost definition (if using Nginx or wanting more speed in Apache).
The course folder is created to hold the course data files, but the course homepage is a redirection to main/course_home/course_home.php. If it doesn't work for you, it probably means your .htaccess file is not interpreted. Please check the installation guide (provided as a permanent link/button during the whole installation process) or use a server with .htaccess authorized by default.

**Comment by christophergilchrist** [comment]
Well Ive added all  the rewrite rules in the virtualhost definition?
There were no .htaccess files in the zip file so none of the folder s have .htaccess files at all?

Below is my virtualhost file

<VirtualHost *:80>
     ServerAdmin christopher.gilchrist@outlook.com
     DocumentRoot /var/www/healthoppurtunitiesteamchamilo.theworkpc.com/
     ServerName healthoppurtunitiesteamchamilo.theworkpc.com
     ServerAlias www.healthoppurtunitiesteamchamilo.theworkpc.com

    <Directory />
        AllowOverride All
        Require all granted
    </Directory>


     <Directory /var/www/html/healthoppurtunitiesteamchamilo.theworkpc.com/>

        RewriteEngine On
        RewriteCond %{QUERY_STRING} ^id=(.*)$
    RewriteRule ^certificates/$ certificates/index.php?id=%1 [L]
    RewriteRule ^courses/([^/]+)/?$ main/course_home/course_home.php?cDir=$1 [QSA,L]
    RewriteRule ^courses/([^/]+)/index.php$ main/course_home/course_home.php?cDir=$1 [QSA,L]
    RewriteRule ^courses/([^/]+)/scorm/(.*([\.js|\.css|\.png|\.jpg|\.jpeg|\.gif]))$ app/courses/$1/scorm/$2 [QSA,L]
    RewriteRule ^courses/([^/]+)/scorm/(.*)$ main/document/download_scorm.php?doc_url=/$2&cDir=$1 [QSA,L]
    RewriteRule ^courses/([^/]+)/document/certificates/(.*)$ app/courses/$1/document/certificates/$2 [QSA,L]
    RewriteRule ^courses/([^/]+)/document/(.*)$ main/document/download.php?doc_url=/$2&cDir=$1 [QSA,L]
    RewriteRule ^courses/([^/]+)/upload/course_home_icons/(.*([\.js|\.css|\.png|\.jpg|\.jpeg|\.gif]))$ app/courses/$1/upload/course_home_icons/$2 [QSA,L]
    RewriteRule ^courses/([^/]+)/upload/([^/]+)/(.*)$ main/document/download_uploaded_files.php?code=$1&type=$2&file=$3 [QSA,L]
    RewriteRule ^courses/([^/]+)/work/(.*)$ main/work/download.php?file=work/$2&cDir=$1 [QSA,L]
    RewriteRule ^courses/([^/]+)/course-pic85x85.png$ main/inc/ajax/course.ajax.php?a=get_course_image&code=$1&image=course_image_source [QSA,L]
    RewriteRule ^courses/([^/]+)/course-pic.png$ main/inc/ajax/course.ajax.php?a=get_course_image&code=$1&image=course_image_large_source [QSA,L]
    RewriteRule ^courses/([^/]+)/(.*)$ app/courses/$1/$2 [QSA,L]
    RewriteRule ^session/(\d{1,})/about/?$ main/session/about.php?session_id=$1 [L]
    RewriteRule ^course/(\d{1,})/about/?$ main/course_info/about.php?course_id=$1 [L]
    RewriteRule ^badge/(\d{1,}) main/badge/issued.php?issue=$1 [L]
    RewriteRule ^skill/(\d{1,})/user/(\d{1,}) main/badge/issued_all.php?skill=$1&user=$2 [L]
    RewriteRule ^badge/(\d{1,})/user/(\d{1,}) main/badge/issued_all.php?skill=$1&user=$2 [L]
    RewriteRule ^main/exercice/(.*)$ main/exercise/$1 [QSA,L]
    RewriteRule ^main/newscorm/(.*)$ main/lp/$1 [QSA,L]
    RewriteRule ^service/(\d{1,})$ plugin/buycourses/src/service_information.php?service_id=$1 [L]
    RewriteRule ^lti/os$ plugin/ims_lti/outcome_service.php [L]
    RewriteRule ^([^/.]+)/?$ user.php?$1 [L]
    RewriteRule ^(tests|.git) - [F,L,NC]

     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/healthoppurtunitiesteamchamilo.error.log
     CustomLog ${APACHE_LOG_DIR}/healthoppurtunitiesteamchamilo.access.log combined


</VirtualHost>


Do you have working example of the virtuahost file?

Chris

**Comment by ywarnier** [comment]
> Do you have working example of the virtuahost file?
Not immediately available,no.
You don't have any .htaccess file at the root of your Chamilo folder? Which version did you download?

**Comment by christophergilchrist** [comment]
I installed chamilo-1.11 apache 2.4 php7.3 on ubuntu 18.04.

Chris

**Comment by christophergilchrist** [comment]
I installed chamilo-1.11.10 apache 2.4 php7.3 on ubuntu 18.04.
When it creates the courses app/courses/(course_name/) there is no index.phpfile created?
Also there is no index.php file in /course/?

I've added .htaccess to  / and to/courses/
Still does a not found error?

Chris

**Comment by ywarnier** [comment]
ok, so only .htaccess in / is important.
Do you have a /courses directory? (or do you mean /app/courses/?) /courses should not exist (it prevents the redirection rules to work as it find a folder of which the absence triggers the redirect)
Also, try removing the redirect rules from Apache (except the AllowOverride All and the Require all granted) if you already have the .htaccess. They might conflict somehow (I don't think so, but better be on the safe side).

**Comment by christophergilchrist** [comment]
ywarnier thanks for the help. I have managed to get it working on my development machine and did what you said and it has worked. I will apply the same work around on the live machine to get it working 
Thanks for your help.
Chris

**Comment by ywarnier** [comment]
No problem. It has already happened before. People install it without the redirect working, then see an issue and think creating the /courses/ folder will help, and then as it doesn't help they find .htaccess is probably not working, they fix this one, but now the /courses/ folder gets in the way :-)

**Comment by yemanlin1st** [comment]
> ok, so only .htaccess in / is important. Do you have a /courses directory? (or do you mean /app/courses/?) /courses should not exist (it prevents the redirection rules to work as it find a folder of which the absence triggers the redirect) Also, try removing the redirect rules from Apache (except the AllowOverride All and the Require all granted) if you already have the .htaccess. They might conflict somehow (I don't think so, but better be on the safe side).

hi ywarnier, 
i am facing an issue with my chamilo
this is the message i am having " training.pefy-consulting.com/.htaccess does not exists"

i am actually running chamilo 1.11.18

**Comment by yemanlin1st** [comment]
my online host is running PHP : 7.4.33

**Comment by GenApophis** [comment]
Hi there, i'm facing the same error with the courses.
i've attached the .htaccess of the main folder.
i'm hosting the website via ionos, they told me that everything should work as intended.
[htaccess.txt](https://github.com/chamilo/chamilo-lms/files/14862281/htaccess.txt)

**Comment by razorchris** [comment]
Hello! Im new in here, can i have any working .htaccess adding course on chamilo fresh install?

Thank you
