### ISSUE TITLE
Error BigBlueButton with chamilo 1.11.10 and php 7.3.9

### ISSUE THREAD

**Issue by NitAGE** [chamilo/chamilo-lms#3005]
Hi,

When i launch the conference (clicking the button "Enter the conference") return the following error:

Fatal error: Uncaught Exception: String could not be parsed as XML in /xxx/xxx/xxx/xxx/plugin/bbb/lib/bbb_api.php:77 Stack trace: #0 /xxx/xxx/xxx/xxx/plugin/bbb/lib/bbb_api.php(77): SimpleXMLElement->__construct('<html>\r\n<head><...') #1 /xxx/xxx/xxx/xxx/plugin/bbb/lib/bbb_api.php(165): BigBlueButtonBN->_processXmlResponse('videoconference...') #2 /xxx/xxx/xxx/xxx/plugin/bbb/lib/bbb.lib.php(389): BigBlueButtonBN->createMeetingWithXmlResponseArray(Array) #3 /xxx/xxx/xxx/xxx/plugin/bbb/start.php(77): bbb->createMeeting(Array) #4 {main} thrown in /xxx/xxx/xxx/xxx/plugin/bbb/lib/bbb_api.php on line 77

could you help me please?

Thanks

**Comment by ywarnier** [comment]
Did you, by any chance, update Chamilo from Git, while not following the README info for upgrades of the BBB plugin?

**Comment by NitAGE** [comment]
I have installed the BBB plugin after updating Chamilo manually from 1.9.x to 1.11.x

**Comment by NitAGE** [comment]
I have modified the line 77
from return (new SimpleXMLElement($data); 
to return (new SimpleXMLElement($data,true,false)); 
because the second param is "data_is_url"

This work only for close meeting but when i start a new meeting it causing a infinite loading. I have to clear cookies because the platform is not accesible.

**Comment by ywarnier** [comment]
Could you check this file and see if you effectively have all the required fields in your plugin tables?
https://github.com/chamilo/chamilo-lms/blob/1.11.x/plugin/bbb/README.md

**Comment by NitAGE** [comment]
I have checked and It's all ok

**Comment by ywarnier** [comment]
Do you have a recent version of 1.11.x now? (trying to figure out what could be wrong)
What version of BBB do you use? The latest code works (at least) with v2 of BBB

**Comment by NitAGE** [comment]
I have Chamilo 1.11.10 and BBB 2.7

**Comment by NitAGE** [comment]
any suggestion?

**Comment by ywarnier** [comment]
Nope. Can't look into it in more detail right now, but hopefully @jmontoyaa can check at some point before 1.11.12

**Comment by GhaziTriki** [comment]
@NitAGE Are you sure your BigBlueButton is correctly configured. The error you see is because your are getting an HTML answer from the server instead of XML from the API. Can you please check your nginx logs in BigBlueButton and telle us?

**Comment by moraddenhaag** [comment]
Hi everyone, I have the same problem with  Chamilo 1.11.10 and  Videoconference v 2.7 . My bigbluebutton server(Release 2.0) works fine with moodle, wordpress and greenlight. I test that everywhere. Only Chamilo plugin has this problem. It create meeting on the list  but when i want remove it manually. Nothing happens. It give me red message "fault". Second problem  if i click on the meeting it take along time and then give me the error 521.  I can t acces to the website . I must remove everything from the cache to access to the website again. 
My server where chamilo is installed 10.1.44-MariaDB-0ubuntu0.18.04.1 - Ubuntu 18.04 and PHP Version is 7.3.16 . The second server where bigbluebutton is installed, it is Ubuntu 16.04.

The logfile  of server 1 (chamilo) : (70007)The timeout specified has expired: AH01075: Error dispatching request to : (polling).
The logfile of server 2 (Bigbluebutton):
GET /bigbluebutton//bigbluebutton/api/create?name=GROEP4B-0&meetingID=15e8a1f2ad64564.84437292&attendeePW=GROEP4B&moderatorPW=GROEP4Bmod&dialNumber=&voiceBridge=35784&webVoice=&logoutURL=https%3A%2F%2F(mywebsite)%2Fplugin%2Fbbb%2Flisting.php%3FcidReq%3DGROEP4B%26id_session%3D0%26gidReq%3D0&maxParticipants=-1&record=false&duration=300&checksum=a237f56a9f1f456d965ad88fa6b702dc4cc8ff03 HTTP/1.1" 404 194 "-" "-"
--

Thank you for your support.

**Comment by lonesomewalker** [comment]
As you can see, you get an error 404.

Also, BBB is actually at 2.2.3.
We have several working instances with Chamilo and BBB, none of them is showing these errors.

So i tend to say: misconfigured Chamilo or BBB.

**Comment by ywarnier** [comment]
@lonesomewalker I think they are talking about the version of the integration plugin, not BBB itself (hence the v2.7)

**Comment by ywarnier** [comment]
@NitAGE and @moraddenhaag 
We have made a series of improvements to the BBB plugin lately (it is in v2.8.1 now). Any chance you could try it on your systems before our next release?
I believe one of those changes might have fixed the issues you reported.

**Comment by moraddenhaag** [comment]
Hi @ywarnier . I think the plugin BBB of Chamilo has something. My second server with Latest Bigbluebutton version works fine. I tested it with Moodle LMS , Wordpress and my own custimized Greenlight.

 My first server(with Plesk Obsidian) works also fine. When i installed there Chamilo all important requirement for installing was green. I disabled also Mod_security for test but without success. My own salt secret bigbluebutton server is also correct. I think something to do with The plugin BBB chamilo,  The CRUD of the plugin BBB has problem. Because when i create meeting and i want remove that.  I click on red cross nothing happens. I can make video screen for that if you want to see that. Thank you for your time and effort.

**Comment by moraddenhaag** [comment]
@ywarnier You said The BBB plugin (it is in v2.8.1 now) . On my list version i see only  Videoconference v 2.7 on the list of my chamilo platform

**Comment by NicoDucou** [comment]
Hi @moraddenhaag 
To have BBB plugin in v2.8.1 you have to update your Chamilo from git not from the released package. I don't know if it's possible for you.
If you can not update, you can send a screenshot of your plugin configuration to try it on a test platform with Chamilo update with today's code to see if I can reproduce your problem.
Best regards

**Comment by NicoDucou** [comment]
Looking at the error you indicated we can see :
> GET /bigbluebutton//bigbluebutton/api/create?name
It looks like there is doble bigbluebutton so it might be a problem of configuration.

**Comment by ywarnier** [comment]
Chamilo adds the trailing "/bigbluebutton/" automatically. In Chamilo version 1.10.12 (plugin v2.8.1), this is automatically corrected (if you put the /bigbluebutton/, it adds nothing). But in your version (plugin v2.7), this is not automatically corrected. It *always* adds /bigbluebutton/ at the end.

This is probably because the explanatory text is not insisting in a clear enough way. Here is an example (alway in the text under the box) to help you get how to configure it.
![bbb-host](https://user-images.githubusercontent.com/609839/79081014-d5a16500-7d19-11ea-9f80-5e9b45e09c10.png)

**Comment by moraddenhaag** [comment]
Hi i reinstalled Chamilo 2.0(dev version) with git with version BBB 2.8.1. But i cant see webconference on the course and i can't edit in the configuration those settings Global conference link only visible for this user roles,
Default Interface,
Client launch choice.
link virtueleschool.com
user:admintest pass:Test1234

**Comment by ywarnier** [comment]
@moraddenhaag 
Chamilo 2.0 is not ready yet (it will still be a few months before it is usable).
When we said you should install the latest git code, we meant branch 1.11.x. Sorry for the confusion.
```
git clone -b 1.11.x https://github.com/chamilo/chamilo-lms
cd chamilo-lms
composer update
```
(and then install it following the normal installation procedure)

**Comment by moraddenhaag** [comment]
Thanks @ywarnier for the advice. It works now fine. with git installation and the latest version of BBB chamilo plugin 2.8.1. Thank you again for your effort and support. Have a nice day.

**Comment by SMG3000** [comment]
> @moraddenhaag
> Chamilo 2.0 n'est pas encore prêt (il faudra encore quelques mois avant qu'il ne soit utilisable).
> Quand nous avons dit que vous devriez installer le dernier code git, nous voulions dire la branche 1.11.x. Désolé pour la confusion.
> 
> ```
> git clone -b 1.11.x https://github.com/chamilo/chamilo-lms
> cd chamilo-lms
> composer update
> ```
> 
> (puis installez-le en suivant la procédure d'installation normale)

Bonsoir 
J'ai le même problème avec la partie video Conférence

**Comment by SMG3000** [comment]
Bonsoir j ai le meme probleme quand je clique sur le lien pour entrer dans la salle ça m'affiche cette erreur: Fatal error: Maximum execution time of 60 seconds exceeded in C:\xampp\htdocs\Projet\chamilo\chamilo\plugin\bbb\lib\bbb_api.php on line 70

![image](https://user-images.githubusercontent.com/64156307/80020516-7a216500-84d9-11ea-826a-e26708789df6.png)

**Comment by SMG3000** [comment]
> Bonsoir j ai le meme probleme quand je clique sur le lien pour entrer dans la salle ça m'affiche cette erreur: Erreur fatale: Délai d'exécution maximal de 60 secondes dépassé dans C: \ xampp \ htdocs \ Projet \ chamilo \ chamilo \ plugin \ bbb \ lib \ bbb_api.php sur la ligne 70
> 
> ![image](https://user-images.githubusercontent.com/64156307/80020516-7a216500-84d9-11ea-826a-e26708789df6.png)

J'ai la version 1.11.10 de chamilo
comme vous l'avez dit en haut monsieur qu'il faut la dernière version du plugin BBB chamilo 2.8.1 j'arrive a le trouver pour le télécharger 
s'il peut y avoir une solution

**Comment by ywarnier** [comment]
[bbb-2.8.1.zip](https://github.com/chamilo/chamilo-lms/files/4518551/bbb-2.8.1.zip)

Voici la version 2.8.1 en zip. Elle remplace le répertoire plugin/bbb/
Il n'est pas garanti qu'elle fonctionne avec la version 1.11.10. Merci de prende une copie du répertoire plugin/bbb/ *avant* d'essayer de le remplacer avec le fichier joint.

Pour du support urgent, merci de contacter un fournisseur de Chamilo pour soutenir le projet Chamilo: https://chamilo.org/providers

**Comment by SMG3000** [comment]
ils me disent que:
Le serveur de vidéoconférence n'est pas configuré correctement

**Comment by SMG3000** [comment]
J’ai remplacé ça m’affiche que le serveur de vidéo conférence n’est pas configuré correctement

**Comment by SMG3000** [comment]
![image](https://user-images.githubusercontent.com/64156307/80030764-f1aac080-84e8-11ea-8150-8d43436bb6ed.png)

**Comment by ywarnier** [comment]
Et donc, qu'est-ce que vous en concluez? :-)

**Comment by SMG3000** [comment]
La configuration 
Au niveau du Host BBB je doit mettre quoi?
![image](https://user-images.githubusercontent.com/64156307/80036113-6e419d00-84f1-11ea-8655-dfd2c4488180.png)

**Comment by SMG3000** [comment]
Oubien je dois faire une mise a jour de chamilo laquelle 
Si oui si je peux avoir le lien de telechargement

**Comment by ywarnier** [comment]
@SMG3000 Je pense que vous êtes à un niveau un peu trop non-technique pour demander de l'aide sur cette plateforme-ci, qui est essentiellement réservée aux développeurs et contributeurs.

L'utilisation de BigBlueButton demande l'installation, sur un *autre* serveur, du logiciel de vidéoconférence BigBlueButton (voir http://docs.bigbluebutton.org/2.2/install.html)

Une fois installé, il permet d'obtenir une adresse et une clef d'activation qui doivent être utilisées dans le plugin Chamilo.

Il s'agit d'un plugin, qui permet de connecter un système externe à Chamilo. Chamilo lui-même ne *contient* pas de serveur de vidéoconférence.

Je suggère que vous utilisiez plutôt le forum de Chamilo pour poser vos questions: https://forum.chamilo.org/
Le niveau y est plus accessible et les développeurs ici ont de grandes et nombreuses responsabilités et ne peuvent pas répondre à tout qui débute avec Chamilo. Merci de votre compréhension.

**Comment by SMG3000** [comment]
Merci
