### ISSUE TITLE
Announcement of inactive users inverted

### ISSUE THREAD

**Issue by evandro-asd** [chamilo/chamilo-lms#3007]
On line 434 of main/announcements/announcements.php, the value (int) $_GET['since'] is set true when the students "never" accessed the course, but the (int) statement crashes the code and the value is set as 0, so all the users subscribed to the course that already accessed are selected.

Code fixed below:

```
                if ($_GET['since'] == 'never') {
                    $since = $_GET['since'];
                } else {               
                $since = isset($_GET['since']) ? (int) $_GET['since'] : 6;
                } 
```

Please create a Pull request.
Chamilo version 1.11.x

tks.

**Comment by ywarnier** [comment]
@evandro-asd thanks for reporting.
Our patch procedure requires a third-party (preferrably the person who reported the issue) to confirm that the patch (which may vary slightly from what you sent us) solved the problem. Any chance you could update a non-production system or test it on https://11.chamilo.org to confirm it works as you would expect now? (before we release 1.11.12 in a few days)
