### ISSUE TITLE
Hide information home page chamilo

### ISSUE THREAD

**Issue by 480419140** [chamilo/chamilo-lms#3010]
Good afternoon, I would like to know how to hide the "Personal data", "My global certificate", "Manage Skills" option from the chamilo homepage? Is there any configuration in configuration.php that hides this information?

Version Chamilo LMS 1.11.10 for PHP 7.0

Sincerely.

![image](https://user-images.githubusercontent.com/45467948/66931730-e8f2a280-f00c-11e9-99cf-8d090e3f0622.png)

**Comment by ywarnier** [comment]
You should be able to disable skills management from the platform settings page by searching for "skills"

**Comment by ywarnier** [comment]
Personal data is something related to GDPR. You can find related options in app/config/configuration.php (or if it's an upgraded version of Chamilo, in main/install/configuration.dist.php as templates that you have to copy to app/config/configuration.php for them to take effect). One of them says "disable_gdpr" if I'm not mistaken.

**Comment by 480419140** [comment]
About the skills I managed to disable, thanks.

About personal data, I disabled it in $ _configuration ['disable_gdpr'] = true; but just hid the menu option "Restricted Area" block "Personal data protection".

In profile still keeps appearing.

![image](https://user-images.githubusercontent.com/45467948/66933273-3bcd5980-f00f-11e9-9833-f77270421f30.png)

**Comment by Nellmat** [comment]
can someone please help me hide this notification?

Are you having some issue? Do you need help? Are you dreaming of some very specific new feature? Chamilo project's sustainability is only possible thanks to the contributions of a small number of exceptional people and of businesses engaged with its development. These companies are EXPERTS in everything related to Chamilo, from e-learning consulting to cloud hosting, from courses design to Chamilo training to custom developments. If your organization uses Chamilo and needs professional support, working with one of these companies is the best decision you can take. It will bring you all the services you need with a certified quality level and ensure the accelerated growth of your platform. Be responsible, choose Official Chamilo Providers.



![Captura de ecrã 2020-03-31, às 05 36 11](https://user-images.githubusercontent.com/22569234/77988059-4fe1ea80-7313-11ea-8493-8839fd49dc04.png)

**Comment by ywarnier** [comment]
@480419140 you should modify the code (in main/admin/index.php) to remove that link. There is no other way to remove it at this time (the main admin page does not use templates yet).

**Comment by oliveiraped** [comment]
You can hide the Block by editing the file

chamilo-1.11.12/main/template/default/layout/layout_2_col.tpl

In 


Best
