### ISSUE TITLE
Show PDF in video Lesson frame

### ISSUE THREAD

**Issue by chinovelasco** [chamilo/chamilo-lms#3014]
When we insert a PDF file in Lesson, the browser sends a downloaded command, however we believe that it would be better to show it in the blank box that is usually used for loading videos as can be seen in the attached picture
![pdf-chamilo](https://user-images.githubusercontent.com/55451742/67624497-cd4e7f80-f7f6-11e9-9f7f-0a20b13a047f.jpg)

**Comment by Coursenligne** [comment]
Hi,
Just a quick remark.
You just posted the same request on the forum.
I answered it.
The main issue is that PDF is a plugin, so the resource is out of Chamilo (such as would be a zip file).
You request means that a PDF reader has to be integrated to the platform wich, I guess, is a real full-time job.

**Comment by alenguav** [comment]
That's correct we have realized that the problem was our web server configuration that uses
NGNIX in front of Apache web server. We have disabled it and everything is working fine now.
