### ISSUE TITLE
Usar los ID de categorías de cursos al crear cursos

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#3017]
**Describe el problema**
En la creación/edición de cursos se usa el código de las categorías

**Cómo reproducir**
Crear categoría de cursos
Crear curso con esa categoría

**Comportamiento esperado**
Usar los ID de las categorías dentro de la tabla `course`.

**Escritorio:**
 - Sistema operativo : Linux Ubuntu 19.10
 - Navegador Firefox

**Servidor
 - Sistema operativo : Ubuntu 19.10
 - Versión de Chamilo:  2
 - Versión de PHP: 7.3

**Contexto adicional**
- [x] Modificar tabla `course` para agregar FK de `course_category`
- [x] Modificar creación/edición de cursos
- [x] Agregar migración de base de datos
- [x] Revisar "course request"

**Comment by AngelFQC** [comment]
b2310e95d32d9c526d1be336fea7fa19958049d9
b59c35836a943b8a3e57b50ab246944dc3aee9bb

**Comment by ywarnier** [comment]
There's another issue #2807 and a corresponding PR #3466 that might mean this is already done.
There's an item in this issue to review course requests. Still missing that test.

**Comment by christianbeeznest** [comment]
Checked and fixed category in course request with this PR https://github.com/chamilo/chamilo-lms/pull/4372
