### ISSUE TITLE
Removing chapter in learning path doesn't remove contents of chapter

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3019]
**Describe**
Removing chapter in learning path doesn't remove contents of chapter but makes it an orphan in c_lp_item, which makes it invisible for students but is still counted as one step (so it makes it impossible for students to reach 100% progress)

**To Reproduce**
Create a LP with 2 chapters and one document in each chapter
Remove the second chapter
Enter the learning path (for the first time)
You only get up to 50% progress
The c_lp_item table still contains the item that was inside the chapter, with an incorrect reference to parent_item_id, but the chapter is not there anymore.

**Expected behavior**
Removing the chapter should remove elements under it in c_lp_item

**Server
 - Version of Chamilo:  1.11.x of 2019/10/07
 - Version of PHP: 7.2

Refs BT#16321

**Comment by BorjaSanchezBeezNest** [comment]
Check in Chamilo master (V2), and this bug doesn't occur. When a section that had a document its delete, the document parent change to the course, and the student can finish the LP correctly
