### ISSUE TITLE
Exportar reporte de ventas

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#3020]
Se realiza el siguiente reporte de ventas.

![reporte_ventas](https://user-images.githubusercontent.com/2940509/68143766-248fd680-ff00-11e9-82f9-04d2cbf71e4e.png)

Que exporta para el área conveniente que desea un reporte detallado.
![reporte_xls](https://user-images.githubusercontent.com/2940509/68143832-4e48fd80-ff00-11e9-9cd4-dc6aae7f2959.png)

**Comment by ywarnier** [comment]
Reviewed, improved in 99fabe49ac21fafaed26d92cfb97a44dd69ba4d0 and approved.
