### ISSUE TITLE
Nuevos filtros de reportes de ventas de cursos

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#3021]
Se agregó 2 nuevos filtros.

Por Email de usuario y por rango de fecha de compras.

![reporte_filtro](https://user-images.githubusercontent.com/2940509/68156460-e1426180-ff19-11e9-9b5e-ec25c60b678b.png)

**Comment by aragonc** [comment]
@ywarnier @jmontoyaa  Revisarlo

**Comment by ywarnier** [comment]
Reviewed, improved in 99fabe49ac21fafaed26d92cfb97a44dd69ba4d0 and approved.
