### ISSUE TITLE
Composer json file sorting

### ISSUE THREAD

**Issue by marvil07** [chamilo/chamilo-lms#3022]
**Is your feature request related to a problem?**
Dependencies are easier to find if sorted alphabetically.

**Describe the solution you'd like**
Use alphabetical order for all things inside composer.json.

**Additional context**
When merging and when searching dependencies or other things in the file, it is easier if things are sorted.

**Comment by marvil07** [comment]
@ywarnier Thanks for reviewing and merging #3023. 
Now I opened an analogous PR #3064 for `master` (`2.x`).

**Comment by ywarnier** [comment]
This has been merged. Thanks for the PR.
