### ISSUE TITLE
Pagination links not working

### ISSUE THREAD

**Issue by miguelvdb** [chamilo/chamilo-lms#3026]
**Describe**
On the resultpage of an exercise you can't navigate through the results, because the navigation is not working.

**To Reproduce**
1. Go to an exercise
2. Click on 'results'
3. Scroll down to the pagination navigation
4. Click on the arrows // These are not working

**Expected behavior**
Navigate through the results with the pagination arrows

![Knipsel](https://user-images.githubusercontent.com/39825423/68938115-f6cb4d00-079d-11ea-967b-fcf9c613c3a0.JPG)

**Comment by ywarnier** [comment]
@miguelvdb This has been fixed (I just tested your procedure and it worked as expected). I remember someone else reported this, but I couldn't find the precise change that fixes it. This will be in 1.11.12, though.
