### ISSUE TITLE
BBB activation pb in multi URL

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3027]
**Describe**
On a multi URL context, if you activate the BBB plugin on the main URL then the videoconference tool appears on courses on all URLs. But on sub URL since the plugin is not configured it does not work.

**To Reproduce**
Have a multi URL setup.
On the main URL activate the BBB plugin and configure it.
Go to a sub URL see that the BBB plugin is activated but not configured.
Enter a course on this sub URL and click on the video conference tool and it will show 
> Videoconference server is not configured

**Expected behavior**
If the BBB plugin is not configured, that is to say that on a sub URL in the plugin's configuration if "BigBlueButton videoconference tool enabled" is not set to "yes" then the videoconference tool should not appear in the course on this sub URL.

**Server
 - Version of Chamilo:  1.11.x (2019/11/18)

**Comment by NicoDucou** [comment]
Refs BT#15965

**Comment by ywarnier** [comment]
@jmontoyaa you talked about a similar issue recently. Maybe you can update this at the same time?

**Comment by jmontoyaa** [comment]
The problem is about the install and uninstall plugin process in multiple URLs.

What should be the behaviour?

Right now if you're in portal 2, you can install and uninstall plugins and they will affect all portals.
Maybe the install/uninstall process should be only available in the main portal?
The rest of portals can still edit the status of the plugin as enabled/disabled.

**Comment by ywarnier** [comment]
Yes, for now plugins should be locked in children portals, until we figure out a better way.
Can you implement that soon?

> The rest of portals can still edit the status of the plugin as enabled/disabled.

Yes.

**Comment by ywarnier** [comment]
@jmontoyaa your commit seems to be generating an issue with the selection of plugins on a portal without multi-url. @NicoDucou  left you a comment.

**Comment by jmontoyaa** [comment]
Fixed here https://github.com/chamilo/chamilo-lms/commit/a780e07b4c8ca75755479b33d7a5d92117d2d8c7
