### ISSUE TITLE
Se puede cambiar el nombre que vienen por default en las etiquetas del menú???

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#3028]
Se puede cambiar el nombre q de las etiquetas que vienen por default en el menú? es decir que Mis cursos lo pueda cambiar por Mis materias, etc... Si es así alguien me podría guiar en como lo puedo realizar???

**Comment by AngelFQC** [comment]
Hola @Katamiaw1 

Sí, puedes crear un sub-idioma (en base al español) desde el panel de adminstración, y definir tus propios términos.

Puedes encontrar más información en https://docs.chamilo.org/en/admin/platform_administration/chamilo_configuration_settings/languages/

**Comment by Katamiaw1** [comment]
muchas gracias por tu aportación @AngelFQC me fue de gran ayuda

**Comment by Katamiaw1** [comment]
otra pregunta @AngelFQC  se pueden quitar algunas etiquetas del menú q no utilicemos???

**Comment by AngelFQC** [comment]
Sí, puedes entrar en los parámetros de configuración de chamilo y buscar el setting "Pestañas en la cabecera". Luego podrás elegir qué enlaces mostrar.

**Comment by Katamiaw1** [comment]
@AngelFQC Nuevamente muchas gracias me salvaste de tremendo lío, Gracias!!!!
