### ISSUE TITLE
Difficulty level in questions

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#3030]
Is it possible to increase the number of difficulty levels in questions from 5 to e.g. 10?

![obraz](https://user-images.githubusercontent.com/32258255/69334084-41474080-0c5a-11ea-9a5d-68edb82f4b5c.png)

**Comment by ywarnier** [comment]
Difficulty is just a text indicator, it has no bearing on anything else than displaying it to the teacher.
But apart from that, 10 levels of difficulty seem to be a lot. Are you sure you want that?
Anyway... you can change that on your side here: https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/exercise/question.class.php#L2319
If you want to change that in Chamilo, please come with some academic paper or something that suggests more than 5 levels of difficulty is something that makes sense for questions ;-)

**Comment by xam1234** [comment]
Thanks, I thought it was more usable:) Categories are enough. 
A topic to close.
When will 1.11.12 come out? ;)
