### ISSUE TITLE
Quiz - display all results

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#3031]
Because chamilo reporting is poor, it was useful to have a feature that displayed all the results in a quiz on one page.
Unfortunately, in the latest version of 1.11.x it is not available. 
It was still available in version 1.10.8.

Ver. 1.11.x (21.11.2019)
![obraz](https://user-images.githubusercontent.com/32258255/69346840-c4c15b80-0c73-11ea-8cb6-c660f9ae8996.png)

Ver. 1.10.8
![obraz](https://user-images.githubusercontent.com/32258255/69346675-7744ee80-0c73-11ea-86cf-ee7365d252d0.png)

**Comment by ywarnier** [comment]
I'm not sure why the option to select the number of items on the page has disappeared though. I don't remember any change doing specifically that. We'll check.

**Comment by xam1234** [comment]
@ywarnier Any news when 1.11.12 will be out ?
PHP 7.4 will be supported ?

**Comment by ywarnier** [comment]
@xam1234 This has been fixed.
Would you like to extend on what you mean by "Because chamilo reporting is poor"? Do you have examples of what you expect for it not to be poor?

**Comment by xam1234** [comment]
@ywarnier First of all, thank you for solving the problem! 

Remember the problem described here: [https://github.com/chamilo/chamilo-lms/issues/3013] :)

Regarding reports:
For Example, is there a report where all exercise results (points and percentages) of all users from all courses are collected in one place with the possibility to export?
