### ISSUE TITLE
Chamilo 1.11.x - Versiones PHP

### ISSUE THREAD

**Issue by disgregador** [chamilo/chamilo-lms#3033]
En una instalación de prueba con PHP 5.6.40 muestra el mensaje que se indica más abajo al ejecutar composer update

¿La próxima versión de Chamilo no será compatible con PHP 5.6 y 7.1? 
Son ramas a las que no se les da ya soporte https://www.php.net/supported-versions.php

¿Chamilo 1.11.x necesitará como mínimo PHP 7.2 o superior?
¿Tendrá versiones específicas para PHP 7.3 y 7.4?
Gracias.

> Chamilo\CoreBundle\Composer\ScriptHandler::deleteOldFilesFrom19x
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpunit/phpunit 8.4.3 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
    - phpunit/phpunit 8.4.2 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
    - phpunit/phpunit 8.4.1 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
    - phpunit/phpunit 8.4.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
    - Installation request for phpunit/phpunit ^8.4 -> satisfiable by phpunit/phpunit[8.4.0, 8.4.1, 8.4.2, 8.4.3].

**Comment by NicoDucou** [comment]
phpunit acaba de ser aggregado ayer y no nos dimos cuenta que necesitaba php 7.2 por la version 8.4, estamos revisando para permitir usar una version otra que phpunit 8.4 y asi no bloquear a una version php 7.2

**Comment by sebastiendu** [comment]
You would need to replace 8.4 by 5 at line 124 of file composer.json as PHPUnit 5 supports PHP 5.6. But better remove this line altogether, you probably won't need it anyway.

This is a only a "require-dev", normal production installs do not need PHPUnit.

However using PHP 5.6 in production is a security issue now, according to https://www.php.net/supported-versions.php

**Comment by AngelFQC** [comment]
Maybe `"phpunit/phpunit": "^5 || ^8.4"`?

**Comment by ywarnier** [comment]
@disgregador 

> ¿La próxima versión de Chamilo no será compatible con PHP 5.6 y 7.1?

La versión 1.11.12 (por llegar pronto) todavía soportará PHP 5.6 y 7.1.
La versión 2.0 (inicios de 2020) solo soportará 7.2 y más recientes.

El agregado de phpunit en require-dev no debería afectar una instalación en producción. Lanzar `composer --no-dev update` debería arreglar el problema.
Y efectivamente, usar PHP 5.6 es una (muy) mala idea.

**Comment by disgregador** [comment]
¡Gracias!
