### ISSUE TITLE
Wheel of skill or competence is not responsive.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#3037]
Hi.
Support.
Please would there be any possibility of the skill or skills tool being responsive.
Is there any css code that can be applied.
This is how the student sees it.
It's just an idea.
And if you replace the wheel.
By links.
That would look the same color on the wheel.
Remember it's just an idea.
If not you can not be responsive.
Thank you so much for your attention.

![teste-01](https://user-images.githubusercontent.com/25286516/69832344-7f210780-120c-11ea-9ef4-48002d8c83cf.png)
![teste-02](https://user-images.githubusercontent.com/25286516/69832347-821bf800-120c-11ea-8342-ba33505d93ac.png)
![teste-03](https://user-images.githubusercontent.com/25286516/69832350-847e5200-120c-11ea-95a5-d4d2c9e1323d.png)

Or maybe something like this:
![skill](https://user-images.githubusercontent.com/25286516/69832388-bc859500-120c-11ea-9e86-83dc78f1ccde.jpg)

**Comment by ywarnier** [comment]
We depend on a library on which we do not have much control, for this feature.
Not an urgent issue for us, although I agree it would be great.

**Comment by AngelFQC** [comment]
I added the `viewBox` attribute to skill wheel to allow maintain the apect ratio

Viewport for an iPad min:
![chamilo1 test_main_admin_skills_wheel php_(iPad Mini)](https://user-images.githubusercontent.com/1697880/86189261-af17ec80-bb06-11ea-8c19-ae3af96cea4b.png)

**Comment by ywarnier** [comment]
![wheel](https://user-images.githubusercontent.com/609839/86417214-abce5d80-bccc-11ea-8985-da1134a8f232.png)

Looks good to me. Tried both in admin and student mode, full-screen and in 405px wide.

![wheel-user](https://user-images.githubusercontent.com/609839/86417324-e9cb8180-bccc-11ea-873c-1d06f62ea7d3.png)
