### ISSUE TITLE
En Chamilo LMS Se puede dar de alta a un alumno y q x default este inscrito a un curso obligatorio? 

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#3041]
Hola buenas noches no se si ya se pueda realizar, pero e creado un curso el cual quiero q sea obligatorio para cualquier alumno. Lo que deseo es q al darse de alta el alumno en la plataforma este ya este inscrito al curso obligatorio por default

**Comment by AngelFQC** [comment]
Hola
Como administrador, puedes crear o editar tu curso y marcarlo como "Curso especial". Esto hace que todos los usuarios tengan acceso a este curso.

![imagen](https://user-images.githubusercontent.com/1697880/70058207-7a61a800-15ac-11ea-8c2e-d1f3b84f5741.png)

**Comment by Katamiaw1** [comment]
Gracias por tu ayuda 🤗

Enviado desde mi iPhone
