### ISSUE TITLE
problema en lecciones relacionado con el #2381

### ISSUE THREAD

**Issue by centrocis** [chamilo/chamilo-lms#3042]
**Describe el problema**
En una plataforma Chamilo 1.11.4 que proviene de versiones anteriores actualizadas progresivamente desde la 1.9.x, tras actualizar a la 1.11.6, las lecciones dejan de funcionar, no cargan los contenidos y no se visualizan los ítems (sco) de la lección. Puede pulsar el el seguidor de la izquierda pero no se carga nada en el visualizador.

Gracias,

Está relacionado con la incidencia #2381

**Cómo reproducir** NO es reproducible
Pasos para reproducir el problema:
1. Ir a '...'
2. Dar clic en '....'
3. Bajar hasta '....'
4. Ver el error que dice '...'

**Comportamiento esperado**
Una descripción concisa y clara de lo que esperabas que ocurriera.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
Hola @centrocis 
Este es un problema conocido (la descripción detallada que das definitivamente ayuda) que puede ser solucionado corriendo un script que se encuentra aquí: https://github.com/chamilo/chamilo-lms/blob/1.11.x/tests/scripts/fix_lp_id_to_iid.php
(ojo: la versión 2 resuelve un caso distinto - no es una versión más avanzada)
Este script ha sido mejorado progresivamente, así que sería recomendable usar la versión en este enlace. También sería recomendable usar la versión 1.11.10 en vez de la 1.11.6, pero es otro tema.

**Comment by centrocis** [comment]
Hola,
Muchas gracias por vuestra respuesta. y como corro el script? el problema es que no tengo programador...
    En lunes, 9 de diciembre de 2019 18:09:46 CET, Yannick Warnier <notifications@github.com> escribió:  
 
 
Hola @centrocis
Este es un problema conocido (la descripción detallada que das definitivamente ayuda) que puede ser solucionado corriendo un script que se encuentra aquí: https://github.com/chamilo/chamilo-lms/blob/1.11.x/tests/scripts/fix_lp_id_to_iid.php
(ojo: la versión 2 resuelve un caso distinto - no es una versión más avanzada)
Este script ha sido mejorado progresivamente, así que sería recomendable usar la versión en este enlace. También sería recomendable usar la versión 1.11.10 en vez de la 1.11.6, pero es otro tema.

**Comment by ywarnier** [comment]
Hola @centrocis 
Este espacio (Github) es exclusivamente para contribuidores (y asume un cierto nivel técnico de sus participantes). Para solicitudes sin tener conocimientos técnicos, por favor hacerlas en el foro de Chamilo: https://forum.chamilo.org/
Existen proveedores oficiales de Chamilo aquí: https://chamilo.org/providers que podrán brindarle el servicio (por un fee), o sino le recomendamos encuentre algún conocido con experiencia en servidores y PHP para aplicarlo en su portal.
Los servicios de los proveedores de Chamilo (incluyendo servicios de hosting) están orientados precisamente en aliviar el peso de la labor técnica para las organizaciones que no tienen alguien a la mano para gestionar problemas cuando surjan.
El ejecutar este script en su servidor implica intercambio de credenciales (que deben permanecer en canales confidenciales), análisis de su servidor (para no romper más las cosas y poder ejecutar el script como se debe), y validar con Ud que todo quedó bien. Toma tiempo y es trabajo pesado, por lo que de costumbre no es contribuido gratuitamente (aunque hayamos visto excepciones).
