### ISSUE TITLE
Question categories are skipped (randomly)

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#3047]
Hello.
Has anything changed in the category draw between version 1.11.10 and 1.11.X (11.chamilo.org) ?
In the older (currently available) version, the category draw does not work properly, some categories are skipped (randomly), but at 11.chamilo.org categories work ok.

Is there any deadline for 1.11.12 to be released ?

Thanks in advance for your help.

**Comment by Coursenligne** [comment]
No clue for categories, but the 1.11.12 should be issued very soon....
Stay tuned!

**Comment by xam1234** [comment]
Any news on the latest version 1.11.12 ?
In the present times of remote learning, the new version would be very useful.

**Comment by ywarnier** [comment]
@xam1234 Can you reproduce this issue on https://11.chamilo.org? (if so, could you give us a link?)
