### ISSUE TITLE
PHP Fatal error:  Cannot use isset() on the result of an expression

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3050]
**Describe el problema**
Al acceder a las lecciones de un curso

/main/lp/lp_controller.php?cidReq=EJM&id_session=0&gidReq=0&gradebook=0&origin=

muestra

PHP Fatal error:  Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in ../main/lp/learnpath.class.php on line 3238, referer: ../main/lp/lp_controller.php?cidReq=EJM&id_session=0&gidReq=0&gradebook=0&origin=

Con el último fichero /main/lp/learnpath.class.php descargado con git no se puede acceder a las lecciones y muestra el error anterior.
Con la versión del archivo 22/11/2019 si se muestran.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a '...'
2. Dar clic en '....'
3. Bajar hasta '....'
4. Ver el error que dice '...'

**Comportamiento esperado**
Una descripción concisa y clara de lo que esperabas que ocurriera.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
Entorno: chamilo 1.11.10 con git y composer actualizados.
Aula migrada desde 1.9 y 1.10 hasta 1.11.10.
Ejecutada sentencias SQL de doctrine

**Contexto adicional**
revisando con git log -p main/lp/learnpath.class.php muestra los

commit 37d6e8d7883fb05530f4dfdc27a53ecf22ec8e0e
commit e0787a5ad82abe1ebb54fe2bbf3f8bf8151d5162
Minor - Fix HTML tag param - refs BT#19432
LP: Fix prerequisites min/max for decimals - refs BT#16432
commit 07cdc3eed854e69502a48f17d1ec1a46ed56bd4c
Fixed learning path item order - refs BT#16360

¿Hay que insertar alguna variable en configuration.php?
¿Hay que añadir alguna sentecia SQL en la base de datos?

**Comment by AngelFQC** [comment]
Efectivamente, la línea 3238 tiene una sintaxis válida a partir de PHP 7.0

**Comment by nosolored** [comment]
Gracias @AngelFQC 
Lo hemos probado y nos reporta:

```
Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in ../main/lp/learnpath.class.php on line 3296
Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in ../main/lp/learnpath.class.php on line 3350
```
le hemos cambiado al fichero main/lp/learnpath.class.php
la línea 3296 a
if (array_key_exists($subtree['status'], self::STATUS_CSS_CLASS_NAME)) {

y la línea 3350 a 
if (array_key_exists($item['status'], self::STATUS_CSS_CLASS_NAME)) {

y ya se muestran las lecciones.

Lo revisas y si está ok. Lo modificáis.
Muchas gracias.
