### ISSUE TITLE
composer update - Versiones PHP - Error doctrine/data-fixtures | phpunit

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3055]
**Describe el problema**
En Chamilo 1.11.x - git de https://github.com/chamilo/chamilo-lms/tree/1.11.x
con PHP 5.6 y 7.1 no es posible utilizar composer update o (composer --no-dev update) ya que muestra errores en consola (se indican más abajo).

Se ha modificado la línea 124 de composer.json para compatibilidad con PHPUnit a las distintas ramas pero sigue sin funcionar.
composer.json en línea 124 
"phpunit/phpunit": "^5"
"phpunit/phpunit": "^7"
"phpunit/phpunit": "^8.4"

Cuestiones:
1. ¿Es tema de los test actuales de PHPUnit que se basan como mínimo en PHP 7.2?
2. ¿Qué versiones de PHP soportará la próxima versión de Chamilo 1.11.x?
3. ¿Es por otro tipo de cuestiones?
Muchas gracias.

**Cómo reproducir**
Pasos para reproducir el problema:
Usar versiones PHP 5.6 y 7.1.

**Comportamiento esperado**
Una descripción concisa y clara de lo que esperabas que ocurriera.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
Entorno de pruebas
Chamilo 1.11.x - con git https://github.com/chamilo/chamilo-lms/tree/1.11.x
Versiones PHP: 5.6.40, 7.1.32, 7.2.25, 7.3.12 y 7.4.0

**Contexto adicional**
Errores en consola:
------------------

Con PHP 7.1:
------------
```

- phpunit/phpunit 8.4.3 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
- phpunit/phpunit 8.4.2 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
- phpunit/phpunit 8.4.1 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
- phpunit/phpunit 8.4.0 requires php ^7.2 -> your PHP version (5.6.40) does not satisfy that requirement.
- Installation request for phpunit/phpunit ^8.4 -> satisfiable by phpunit/phpunit[8.4.0, 8.4.1, 8.4.2, 8.4.3].

Loading composer repositories with package information
Updating dependencies (including require-dev)
                                                                              
  [Composer\DependencyResolver\SolverProblemsException]                       
  Problem 1                                                                   
      - The requested package doctrine/data-fixtures could not be found in a  
  ny version, there may be a typo in the package name.                        
                                                                              
  Potential causes:                                                           
   - A typo in the package name                                               
   - The package is not available in a stable-enough version according to your minimum-stability setting                                                
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.                                                                 
   - It's a private package and you forgot to add a custom repository to find it   
```

- Con PHP 5.6 composer update muestra
```
PHP Warning:  Unsupported declare 'strict_types' in /vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 3

Warning: Unsupported declare 'strict_types' in /vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 3
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 77

Parse error: syntax error, unexpected ':', expecting ';' or '{' in /vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 77
```
ocramius sólo está disponible para PHP 7.0 o superior según https://packagist.org/packages/ocramius/package-versions#1.0.0 la compatibilidad es para PHP 7.0.

Solución:
Para PHP 7.1 o superior hay que modificar versiones en composer.json

cambiar línea 43
     "doctrine/data-fixtures": "~1.0@dev",
por  "doctrine/data-fixtures": "^1.3@dev",

cambiar línea 124
   "phpunit/phpunit": "^8.4"
por "phpunit/phpunit": "^7.0"

**Comment by nosolored** [comment]
Internal: Fix CI issue with PHP version < 7.2 and PHPUnit version == 8.4 - 7d14205

**Comment by ywarnier** [comment]
@nosolored el commit lo arregla entonces, cierto?

**Comment by ywarnier** [comment]
Suponiendo que se arregló... (sin feedback)
