### ISSUE TITLE
exercice remplir les blancs 1.11.X

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#3056]
### Résultat actuel
Remplir les blancs avec permettre la permutation des réponses autorisée coché

100 % de réussite avec seulement une réponse bonne sur les trois (quand je remplis un seul blanc sur les trois). Cela semble être dû à l'autorisation de la permutation des réponses.
Normalement pour avoir 100% on doit rentrer 3 réponses : 
7+1
6+2
5+3
### Résultat attendu
Calcul correct du score
###  Étapes pour reproduire
https://11.chamilo.org/main/exercise/overview.php?cidReq=BILLARD&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=161
![billard](https://user-images.githubusercontent.com/24505996/70860551-5a72a280-1f23-11ea-83d3-6871ae6c95b0.png)

###  Version de Chamilo
1.11.X en ligne

**Comment by carlangas159** [comment]
salut @alexiye 

Dans la version actuelle de chamilo 1.11.10 sur 11.chamilo.org, je n'ai pas pu répliquer ce bogue, essayez "6 + 2" vide " ", plusieurs blancs "    " et cela m'a montré des réponses erronées.

![image](https://user-images.githubusercontent.com/18097392/86183217-25acee00-baf7-11ea-834b-07824e4b7b8c.png)


Voici une bonne réponse pour 6 + 2 avec 4 espaces vides et 1 espace vide.

![image](https://user-images.githubusercontent.com/18097392/86183442-9bb15500-baf7-11ea-8cbe-f96b38358bce.png)


Pourriez-vous vérifier si le problème persiste?

**Comment by AngelFQC** [comment]
Duplicated of #3195

**Comment by alexiye** [comment]
Bonjour,
Cela a été corrigé normalement. Le problème avait été résolu. 

Bonne journée
