### ISSUE TITLE
Cursos públicos no permiten acceso a usuarios no registrados

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3058]
**Describe el problema**
Si configuramos un curso como público debe permitir el acceso a usuarios no registrados en la plataforma, pero no es así. 
Si intentan acceder redirige al formulario de registro si éste está activo en la administración.
Si el registro no está activo, no aparece el botón de acceder al curso ni suscribirse.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Crear un curso o editar uno existente y configurar el acceso como "público". Marcar también la opción de permitir la suscripción.
2. Comprobar que el catálogo está visible o bien que el curso aparece en los cursos destacados en la portada para que usuarios no registrados puedan verlo.
3. Sin acceder ni registrarse en la plataforma, hacer clic en el curso configurado como público. Aparecerá la página de información del curso.
Si está habilitado el registro en la plataforma, aparecerá un botón de suscribirse que redirige al formulario de registro. Si no está habilitado no hay botón.
En cualquier caso no permite el acceso al curso a menos que se haya registrado el usuario.

**Comportamiento esperado**
Un curso público debería permitir el acceso de usuarios no registrados en la plataforma con solo hacer clic en el curso. 

**Contexto adicional**
Probado en Chamilo 1.11.10, en diferentes instalaciones y verificado en https://11.chamilo.org/
Se puede comprobar con este curso: https://11.chamilo.org/course/27/about

**Comment by ywarnier** [comment]
@nosolored  si tenéis algún tiempo para revisar que estéis conforme con el parche (ya aplicado a 1.11.x)... Para poder cerrar la tarea.

**Comment by ywarnier** [comment]
Assuming this is fixed (no feedback)
