### ISSUE TITLE
New Installation - Step 4 issue

### ISSUE THREAD

**Issue by antobosco1** [chamilo/chamilo-lms#3060]
![Capture](https://user-images.githubusercontent.com/59388181/71616063-5492e780-2bda-11ea-8025-fa713dc3d4e2.PNG)
I am unable to move further with the installation. There is an error as shown in the screen shot and I am not sure what message it gives. 
Can Some one help me to go forward. I need urgent help.

**Comment by opensourcecompany** [comment]
Looks like you are using Windows...

What system stats do you run?
(you know, the support template here has some reasons...)
Which os?
What webserver?
Which PHP version?
Which PHP modules activated?

**Comment by ywarnier** [comment]
@antobosco1 at first glance your error looks like a PHP version problem. What version are you using? Chamilo 1.11.10 only supports PHP 5.6 and above if I'm not mistaken.
PHP 5.* is not supported at all anymore, so installing a new system with a version 5 is not supported by us.

**Comment by ywarnier** [comment]
No apparent further involvement from the user. Closing.
