### ISSUE TITLE
aferrandini/phpqrcode is abandoned

### ISSUE THREAD

**Issue by marvil07** [chamilo/chamilo-lms#3061]
**Describe**
A dependency, https://github.com/aferrandini/phpqrcode, is marked as **abandoned** upstream, see the link. 

**To Reproduce**
No operation.

**Expected behavior**
Chamilo should try to avoid using abandoned dependencies if possible.
The listed alternative is https://github.com/endroid/qr-code, but it seems to change the API, so depending on how many places that code is used it would need other changes.

**Desktop (please complete the following information):**
 - OS: any
 - Browser: any

**Server**
 - OS: any
 - Version of Chamilo:  `1.11.x` of 2020-01-06
 - Version of PHP: any

**Additional context**
* In order to create a debian package for `1.11.x`, dependencies need to be packaged.
* ~~In order for debian to accept new packages of php software, it should not be abandoned code unless there are good reasons.~~ Nevermind this, it is packaged already as [phpqrcode](https://packages.debian.org/buster/phpqrcode).

**Comment by ywarnier** [comment]
This is fixed now.
