### ISSUE TITLE
Bug $time_for_total in tracking.lib.php + solution

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#3062]
Temps total passé dans un parcours diffère entre les 2 vues: dans la vue **Montrer toutes les tentatives**, le temps $time_for_total ne cumule pas toutes les tentatives pour un même item.
J'ai corrigé avec 
tracking.lib.php line 495: 
$time_for_total1 = $row['mytime'];
$time_for_total=$time_for_total+$time_for_total1;

Le problème est présent aussi dans les versions  tracking.lib.php 1.11.10-releases et 1.11.x du18 Oct 2019

**Comment by ywarnier** [comment]
@andreboivin si tu as l'occasion de vérifier le fix envoyé par Julio...

**Comment by andreboivin** [comment]
Excellent, comme toujours!
