### ISSUE TITLE
Paréntesis. Política de cookies

### ISSUE THREAD

**Issue by EloFran** [chamilo/chamilo-lms#3068]
**Tu solicitud está relacionado con alguna molestia? Describe...**
Me sucede que cuando se muestra la política de cookies aparecen las opciones "(Aceptar)" y "saber más" entre paréntesis

**Describe la solución que te gustaría encontrar**
Me gustaría saber si estoy haciendo algo mal, y de qué manera puedo hacer para que no aparezcan esos paréntesis.

**Contexto adicional**

**Comment by ywarnier** [comment]
Estas paréntesis se encuentran en main/template/default/layout/show_header.tpl y main/template/default/layout/page.tpl.
Para modificarlos, puedes copiar estos archivos en main/template/overrides/layout/ (hay que crearla) y limpiar el caché en la página de administración.

**Comment by EloFran** [comment]
Gracias por la respuesta. Ya había mirado los .tpl, pero según veo ahí no aparece entre paréntesis el "Accept", ni el "More". En cambio en la web sí, es por eso que no lo entiendo. En mi web me aparece "(Accept)" y "(More)". Aquí está mi código de esas páginas:

`
        <div class="toolbar-cookie alert-warning">
            <form onSubmit="$(this).toggle('slow')" action="" method="post">
                <input value=1 type="hidden" name="acceptCookies"/>
                <div class="cookieUsageValidation">
                    {{ "YouAcceptCookies" | get_lang }}
                    <span style="margin-left:20px;" onclick="$(this).next().toggle('slow'); $(this).toggle('slow')">
                                ({{"More" | get_lang }})
                            </span>
                    <div style="display:none; margin:20px 0;">
                        {{ "HelpCookieUsageValidation" | get_lang}}
                    </div>
                    <span style="margin-left:20px;" onclick="$(this).parent().parent().submit()">
                                ({{"Accept" | get_lang }})
                            </span>
                </div>
            </form>
        </div>
        `
