### ISSUE TITLE
Learning paths: use SCORM monosco score info as Chamilo progress

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3069]
Despite this going against the SCORM (1.2) standard, it seems that a series of other LMSes are now offering an option (when configuring an imported SCORM path with only one item - usually called a mono-SCO) to ask for the score of the item to be considered as progress in the progress bar.
This is because Chamilo decides on the progress of a learning path based on the *number of items* that have been completed vs the total number of items. If uploading a mono-SCO, there is only one item, and thus the progress in Chamilo can only be 0% or 100%, meaning you only ever see any minor progress once you've completed the whole SCORM, thus removing a nice degree of possible visual feedback for the learner.

**Describe the solution you'd like**
Implement a solution similar to other LMS where an option is given to "Use score as progress". This option could be limited to learning paths where there is only one item (otherwise it is bound to generate inconsistencies in progress measurements).

* Add in configuration.dist.php: 
```
// Enable learning paths with only one SCO item to use the score returned by the SCO as an indicator of progress of the whole learning path
// $_configuration['lp_score_as_progress_enable'] = false;
```
* Add a INT "use_score_as_progress" column to the c_lp table (give instructions in configuration.dist.php and make sure this field is checked then added when migrating to Chamilo 2.0)
* In the learning path editing form, only if the LP has 1 single item and it is of type 'sco', make the option to "set the score as progress" appear. When checked (and form submitted), change the 'use_score_as_progress' field is set to 1.
* Alter the code in learnpathItem.class.php, learnpath.class.php and scorm_api.php (update_toc()) to make sure that, when the option is set and we get a score (LMSSetValue() or LMSCommit() or LMSFinish() received), we automatically update the progress based on the max score and the score received. It is assumed that the rest (gradebooks and other possible stuff using the progress) will simply work as we now change the effective progress in the c_lp_view table.

Strings to use (already declared in translate.chamilo.org):
$LearnpathUseScoreAsProgress = "Use score as progress?"
$LearnpathUseScoreAsProgressComment = "Use the score returned, by the only SCO in this learning path, as the progress indicator in the progress bar. This modifies the SCORM behaviour in the strict sense, but improves visual feedback to the learner.";

BT#16486

**Comment by opensourcecompany** [comment]
+1

**Comment by marshel** [comment]
+1

**Comment by ywarnier** [comment]
Implemented through https://github.com/chamilo/chamilo-lms/pull/3085

**Comment by NicoDucou** [comment]
In the description of the task you indicated :

>     * Add a INT "use_score_as_progress" column to the c_lp table (give instructions in configuration.dist.php and make sure this field is checked then added when migrating to Chamilo 2.0)

But in your commit 3c12fc9 you add the configuration but not the indication for the field to be added.
I think you are using the field so it should be added to the config file otherwise it will be difficult to activate this feature.

**Comment by ywarnier** [comment]
Fixed in 43c0c71709780f45c21a6d7dcc56fac125f95ee7.
Thanks for the report.

**Comment by lonesomewalker** [comment]
I have questions about this...

Enabled the config.
Added the new column to the database table c_lp.

![image](https://github.com/chamilo/chamilo-lms/assets/856110/b50e65d4-ddbc-4674-82e4-ae86b9471649)

In some courses i have now the possibility to set this value, but not in all.
But in the end it does not matter, because even when set and saved, after opening the config page again, the check is removed.
Even when directly adding this to the respective database field, nothing changes in the shown backend of Chamilo.

**Comment by lonesomewalker** [comment]
@ywarnier @NicoDucou 

After checking some output, i can now see that a checkbox should have the attribute "checked".
As far as i can see, the described way and current solution does not create valid HTML output.

Sure, the "value" is set to 1, but not shown as "checked".

Consider re-opening this.
