### ISSUE TITLE
Poder cambiar el estilo de fuente en chamilo.

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#3071]
Hay manera de cambiar el estilo de fuente de chamilo?

**Comment by ywarnier** [comment]
Para esto tendrías que definir un nuevo estilo customizado. Puedes hacerlo a partir de la interfaz de administración -> Parámetros de configuración -> Descargar -> descomprimes -> cambias el nombre de la carpeta -> modificas el default.css o el base.css (según lo que quieres afectar) -> comprimes la carpeta en zip -> subes el nuevo estilo (en la misma página donde descargaste el por defecto) ->lo seleccionas y ya. Puede que te tome unos intentos, por lo que recomendamos usar nombres de carpeta con números de versión.

**Comment by ywarnier** [comment]
https://docs.chamilo.org/en/developer/theming_through_css/
