### ISSUE TITLE
Error NOT FOUND -The requested URL /courses/AMBDE201811/index.php was not found on this server.

### ISSUE THREAD

**Issue by luisroman80** [chamilo/chamilo-lms#3072]
Buenas tardes amigos:

Comentarles que hasta el dia de ayer (lunes 20 ), el Chamilo trababaja muy  normal, hasta que hoy  martes ingrese para crear dos nuevos cursos  y  revisando uno de los cursos creados al ingresar me sale el siguiente error:

Not Found
The requested URL /courses/AMBDE201811/index.php was not found on this server.

La url es esta: http://virtual.ils.edu.pe/courses/AMBDE201811/index.php

La verdad he buscado  este error y encontrado una posible solucion en en redireccionar apache en la siguiente  direccion:  https://campus.chamilo.org/documentation/installation_guide_es_ES.html
  ; pero  igual nada

espero me pueda ayudar si alguien le pasolo mismo,  
Mi version de S.O: centos 7
Version apache: Apache/2.4.6 (CentOS) PHP/7.1.14
version chamilo:hamilo 1.11.6

Desde ya muchas gracias por su  ayuda.

Luis Roman

**Comment by ywarnier** [comment]
Hola Luis,
No podemos hacer mucho para tu problema aquí. Indicas que funcionaba hasta el lunes y este espacio es un espacio de trabajo sobre el desarrollo del software, y no sobre soporte a instalaciones ajenas, lo cual no podríamos ofrecer en nuestra capacidad actual (ya estamos muy atareados con el desarrollo).
Te invito a consultar el foro de Chamilo: https://forum.chamilo.org (consejos gratuitos) o a contratar uno de los proveedores oficiales de Chamilo (servicios de pago) (lista disponible aquí: https://chamilo.org/providers).
Gracias por tu comprensión.
