### ISSUE TITLE
`Formatted` Blocks: Format Isn't Preserved

### ISSUE THREAD

**Issue by pukkita** [chamilo/chamilo-lms#3073]
**Describe**
Formatted Blocks look fine while editing, but format is lost after saving.

**To Reproduce**

1.- Create a new document, add a `Formatted` text block. 
2.- Fill it with content (e.g. c&p from a linux terminal window with monospaced fonts).
3.- Save it
4.- Re-open the document: format (Carrier Retuns, blanks etc) in the block are lost

**Expected behavior**
Keep the Formatted block as originally edited.

**Screenshots**
While editing:

![Captura de pantalla 2020-01-22 a las 11 28 53](https://user-images.githubusercontent.com/32773513/72887192-80057f80-3d0b-11ea-8494-a374a66c4a92.png)

After saving and re-opening:

![Captura de pantalla 2020-01-22 a las 11 29 28](https://user-images.githubusercontent.com/32773513/72887214-885dba80-3d0b-11ea-8614-38c9447a664d.png)

Back to Edit, format is gone:

![Captura de pantalla 2020-01-22 a las 11 40 02](https://user-images.githubusercontent.com/32773513/72887497-189bff80-3d0c-11ea-992b-539d742056ba.png)

**Desktop:**
 - OS: OS X High Sierra 10.13.6 and Mojave)
 - Happens on all Browsers I've tried: Safari, Firefox and Chrome.

**Server**
 - OS: Ubuntu 18.04
 - Version of Chamilo: 1.11.10
 - Version of PHP: 7.2

**Additional context**
- Tried several Themes just in case, same problem on all of them.
- No customization has been made to any php nor css.
- Seems that when saving, all carriage returns,  newlines blanks or tabs are removed.
- On Administration > System Status, Chamilo requirements status are all green but for the ddbb (blue); same goes for PHP Requirements, everything in green.

**Update**
Been trying to enable codesnippet and although its icon doesn't appear on CKEditor, `formatted` blocks now offer the possibility of setting the highlight language etc.

**Workaround**
Not sure if codesnippet made the difference, but noticed that

- Editing via Course > Documents File Explorer mangles the `formatted` block.
- Editing a Document via Learning Path > Document tree, mousing over the Document, then  clicking on the pencil icon, *doesn't* mangle the `formatted` block, so **using this method in the meanwhile as a workaround**.

![Captura de pantalla 2020-01-26 a las 14 49 41](https://user-images.githubusercontent.com/32773513/73136200-51f5a780-404b-11ea-9188-5db18f6ac659.png)

**Comment by pukkita** [comment]
Added workaround

**Comment by ywarnier** [comment]
Thanks for reporting. This is not really a priority (as you could have guessed from my response time), and we are likely to switch the online editor in future versions, so I will leave this here but there are no plans to provide a fix in the short term.
