### ISSUE TITLE
Se pueden dar una posición diferente a unos extrafields que agregue al formulario de registro???

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#3074]
Quiero ver si se puede de forma nativa los campos extrafields q agregue a mi formulario de registro, es decir siempre los campos extrafields aparecen por default al final de los campos nativos de los formularios en este caso quiero ver si pueden aparecer despues del campo perfil

**Comment by marshel** [comment]
Inside app/config/configuration.php there is a custom option to dictate the extra fields you want in the registration page and its position, but, regardless it is always after the base chamilo fields.

Dentro del archivo app/config/configuration.php si tiene una opción de selectar los campos que aparecen y cuál posición la quiera, pero, siempre la posición será después de los campos base del chamilo.

**Comment by ywarnier** [comment]
Indeed, just as @marshel said. Thanks.
