### ISSUE TITLE
I cannot install Chamilo

### ISSUE THREAD

**Issue by Afroserve** [chamilo/chamilo-lms#3078]
### Chamilo Version 
chamilo-1.11.10

![chamilo error](https://user-images.githubusercontent.com/32187148/73759743-aa742580-476c-11ea-8423-5dfe4d117fc2.png)

**Comment by lonesomewalker** [comment]
Which server system?
PHP version...?
No input, no output...

**Comment by serhio-w02** [comment]
log from picture clearly said "access denies for user afroserve_cmi" so check that database exists and that the user has rights to access the database
