### ISSUE TITLE
Etiqueta de estado incorrecta en las secciones de una lección.

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3079]
**Tu solicitud está relacionado con alguna molestia? Describe...**
En **"Informes/Detalles del estudiante en el curso/Detalles de la lección"** el nombre de cada sección aparece con una etiqueta de estado **"Sin intentar"**, aunque el estudiante haya completado la lección.

**Describe la solución que te gustaría encontrar**
Alguna de las siguientes opciones:

1. Que la etiqueta de estado de las secciones sea coherente con el estado general de la lección. En un color diferente, para identificarla fácilmente.
2. Que las secciones no tengan etiqueta de estado y se muestren simplemente como un encabezado o título.

![2020-02-04](https://user-images.githubusercontent.com/40075497/73771719-a1c82300-475d-11ea-9e58-8616ac8529d0.jpg)

**Contexto adicional**
Versión de Chamilo 1.11.10

**Comment by ywarnier** [comment]
Creo que la solución 2 es la más adecuada. Gracias por reportar.

**Comment by ywarnier** [comment]
Tested and approved.
