### ISSUE TITLE
Increase extra fields value size to TEXT

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3082]
The extra_field_values.value field is VARCHAR(255), which is too short for textarea fields.
Convert this to TEXT during the migration from 1.11 to 2.0

This is causing an issue at the moment with GDPR terms, but it is not limited to this case.
I believe I've read somewhere the efficiency of a VARCHAR(x) field vs a TEXT field is irrelevant because both are of variable-length, so (if this is correct) this change shouldn't be negative in any aspect.

**Comment by jmontoyaa** [comment]
It's already the case. extra_field_values.value is a longtext.

**Comment by ywarnier** [comment]
Not in 1.11.x apparently. OK, closing.
