### ISSUE TITLE
Plugins page can't open

### ISSUE THREAD

**Issue by mesoshqip** [chamilo/chamilo-lms#3083]
**Describe**
I am trying to install plugins but I can't access in the plugins page. Before worked, but after I installed the SSL Certificate I can't access anymore: 

**To Reproduce**
1. Go to https://mesonjetore.mesoshqip.net/main/admin/settings.php?category=Plugins
2. See error
Uncaught ReferenceError: $ is not defined
    at settings.php?category=Plugins:2
(anonymous) @ settings.php?category=Plugins:2
![image](https://user-images.githubusercontent.com/59404111/74086579-6b9fe180-4a84-11ea-8f61-2fae50454bb1.png)

When I am going back te administration page I have these errors:
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://mesonjetore.mesoshqip.net/web/css/themes/MesoShqip/fonts/OpenSans.woff2
(index):1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://mesonjetore.mesoshqip.net/web/assets/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0
VM1581:1 GET https://mesonjetore.mesoshqip.net/main/inc/ajax/online.ajax.php?a=get_users_online 500 (Internal Server Error)
(anonymous) @ VM1581:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.fn.load @ jquery.min.js:4
(anonymous) @ main.albanian.js:346
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
VM1581:1 GET https://mesonjetore.mesoshqip.net/main/inc/ajax/message.ajax.php?a=get_count_message 500 (Internal Server Error)
(anonymous) @ VM1581:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
n.<computed> @ jquery.min.js:4
(anonymous) @ (index):146
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
VM1581:1 GET https://mesonjetore.mesoshqip.net/main/inc/ajax/admin.ajax.php?a=version 500 (Internal Server Error)
(anonymous) @ VM1581:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
(anonymous) @ (index):297
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
VM1581:1 GET https://mesonjetore.mesoshqip.net/main/inc/ajax/admin.ajax.php?a=get_latest_news 500 (Internal Server Error)
(anonymous) @ VM1581:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
(anonymous) @ (index):333
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
VM1581:1 GET https://mesonjetore.mesoshqip.net/main/inc/ajax/chat.ajax.php?action=startchatsession&_=1581170259196 500 (Internal Server Error)
(anonymous) @ VM1581:1
send @ jquery.min.js:4
ajax @ jquery.min.js:4
startChatSession @ chat.js:131
(anonymous) @ chat.js:68
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
J @ jquery.min.js:2
extension.js:24 onMessage extension
ial.js:425 Clean the cache of the scraper (new onComplete event)

![image](https://user-images.githubusercontent.com/59404111/74086516-d866ac00-4a83-11ea-8b12-004a3f01ee9d.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser: chrome 79.0.3945.130

**Server
 - OS: Linux Ubuntu 18.04
 - Version of Chamilo: 1.11.10
 - Version of PHP: 7.2,

**Additional context**

**Comment by serhio-w02** [comment]
If you did not fix it yet, remove plugin ticket_old code from the file system ( rm -r $chalo_inst$/plugin/ticket_old ) . It's removed from github repo already.

**Comment by mesoshqip** [comment]
Thank you.
Can I ask about an issue?

The platform is just for one organization or can manage multi-organizations? 
For example:
I have a domain: my school.com
this domain can be used only for school 1 or it's possible to open different accounts:
My school 1
My school 2
etc.
or each organization must have its server and domain?

Best Regards
.:

**Comment by lonesomewalker** [comment]
Please open a separate issue for different topics :-)
But yes, in general you can use ONE Chamilo installation for multiple domains/projects.
The feature you are looking is "multi url".
Enable this in your config (search for multi), then you can add another url in the backend of your instance.

**Comment by mesoshqip** [comment]
Ok, thank you. 
I just open another topics: multi_url for multi organizations #3144

**Comment by serhio-w02** [comment]
> Thank you.
is the deletion mentioned above fixed your issue, please let as know clearly. thanks.

**Comment by mesoshqip** [comment]
Thank yoi
