### ISSUE TITLE
pueden hacerse visibles las carreras/ sesiones en la pagina principal de chamilo?

### ISSUE THREAD

**Issue by Katamiaw1** [chamilo/chamilo-lms#3084]
pueden hacerse visibles las carreras o sesiones en la pagina principal de chamilo en vez de q aparezcan los cursos???

**Comment by ywarnier** [comment]
No existe una manera de hacer esto actualmente. Tampoco intenciones de hacerlo.
Pero si es algo necesario, un equipo con suficiente tiempo podría hacerlo (ver proveedores oficiales de Chamilo)
