### ISSUE TITLE
Error de login usuario nuevo

### ISSUE THREAD

**Issue by cmrojas72** [chamilo/chamilo-lms#3086]
**Describe el problema**
Quiero reportar un error con el login de un usuario estudiante en mi instalación de Chamilo. Todo el proceso de registro funicona bien, pero cuando el usuario intenta ingresar al sitio usando el nombre de usuario elegido y la contraseña, en vez de ingresarlo y mostrarle la sección mis cursos, lo lleva al siguiente enlace http://www.175filmsmedia.com/education/src/course_panel.php y le muestra la página de error 404.

Esto solo sucede con los usarios en modo estudiante y profesor, si el usario es adminitrador puede ingresar sin ningún problema.

**Capturas de pantalla**
![imagen](https://user-images.githubusercontent.com/60983910/74366763-39e58e00-4d96-11ea-8e17-929209a829a5.png)

**Escritorio 
 - Sistema operativo : Windows 10
 - Navegador Firefox (última versión)

**Servidor
 - Sistema operativo : Linux
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 5.6.40

**Comment by vgpastor** [comment]
Acabo de tener el mismo error, en mi caso al registrarse el usuario nuevo a través del LDAP

Al hacer login el nuevo usuario le redirije siempre a la ruta `src/course_panel.php` y ese fichero obviamente no existe..

Alguna idea?

**Comment by AngelFQC** [comment]
Related to #1500

**Comment by AngelFQC** [comment]
Please, check 9363d32d19094e736bb3b304457bc889d362c196
