### ISSUE TITLE
how to register user in chamilo from laravel in background 

### ISSUE THREAD

**Issue by estonerahul** [chamilo/chamilo-lms#3088]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by estonerahul** [comment]
when user is register from laravel , user should automatically get register in chamilo-lms webstite how to achieve that

**Comment by ywarnier** [comment]
@estonerahul you can create users from a distant web application through web services. Check https://github.com/chamilo/chamilo-lms/wiki/webservices
