### ISSUE TITLE
Course export - empty

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#3091]
Suddenly when I export a course with quiz and survey, the only thing that is in zip file is course_info.dat file and nothing more. Same thing is when I export qti quiz, there is a file qti2export_12.xml with info 'ims_qtiasiv2p1.dtd' error.
A hint of what might have caused this and can I fix it ?

Chamilo ver: 1.10.6

**Comment by ywarnier** [comment]
Version 1.10.6 is quite old, now. Please upgrade.

The course_info.dat contains all the objects definitions, so for a quiz and a survey that do not contain any image or audio/video, this is normal.

For the error with QTI, I'm not sure, but 1.11.12 (we're fighting to release this one as soon as possible) comes with a lot of improvements for QTI in comparison with 1.10.6, so the fix will be to just update to the latest stable version (if I remember well, 1.11.10 already contains a lot of fixes for QTI).

**Comment by xam1234** [comment]
@ywarnier Your're right course_info.dat contains it, but the qti is broken, I'll wait till 1.11.12 is out, 1.11.10 has some bugs in quiz, which is fixed in your online version.
