### ISSUE TITLE
Administration page blocks navigation for a while when lacking direct internet access

### ISSUE THREAD

**Issue by sebastiendu** [chamilo/chamilo-lms#3096]
**Description**
On Chamilo instances installed on a server that does not have direct access to remote resources such as https://version.chamilo.org/news/latest.php, the administration page appears but blocks any subsequent navigation for a while.

**To Reproduce**
1. Install Chamilo on a server behind a firewall that block outgoing http requests.
2. Login as administrator and open the Administration page (/main/admin/index.php)
3. Don't wait and click on "User list", "Session list" or any other link.

**Expected behavior**
User list should appear within a reasonable delay.

**Server**
 - Chamilo 1.11.x of 2020-02-04
 - no access to remote https locations

**Additional context**
Setting $_configuration['proxy_settings'] (on servers that have an HTTP proxy available) does not seem to help.

**Comment by sebastiendu** [comment]
(not verified hypothesis)

The HTML page generated by /main/admin/index.php and admin/settings_index.tpl
contains a call to /main/inc/ajax/admin.ajax.php?a=get_latest_news

admin.ajax.php first loads /main/inc/global.inc.php, which indirectly calls start_session();
then admin.ajax.php calls function getLatestNews() without first closing the PHP open session.
While a PHP session is open, it is locked. Through start_session(), other pages wait for the lock to be released to proceed.

https://github.com/chamilo/chamilo-lms/blob/85c425f910f42f16108f001dead3038eb14caf0e/main/inc/ajax/admin.ajax.php#L244

**Comment by sebastiendu** [comment]
3 years ago, the same issue was fixed for
/main/inc/ajax/admin.ajax.php?a=version

https://github.com/chamilo/chamilo-lms/commit/c5120d60dbc60432580da375ccc70a484a965328

**Comment by ywarnier** [comment]
Fixed by PR
