### ISSUE TITLE
question field for multiple choice increase.

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3098]
**Is your feature request related to a problem? Please describe.**
With A multiple choice question the question field is a single flexible width line.
As soon as you extend text beyond this line the text is not shown a user need to scroll to see the rest of the text. Also formatting the text is difficult as well since you can't make a new line.

**Describe the solution you'd like**
Would it be an idea to extend this a little ? I personal would like to a switch option like, when you fill in a answer you hit the little arrow to get a more extended editor.

IF this is by design and users should create a short question then add to it in the description (advanced field). This is however a bit odd since sometimes the question is just a large question for example:
> You are traveling on highway nax21 at a speed of 90 miles a hour. A red car overtakes you at 100 miles a hour. On what side should the red car overtake you?
> a left
> b right
> c none

**Extra feature request. If wanted i can create a new issue for it din't want to flood.**
Allow for reporting/marking of questions in quiz for review if they are deemed incorrect by a user,

**Describe the solution you'd like**
Simple "report this question to teacher". mark/button.

**Comment by ywarnier** [comment]
Hi @spacecabbie 
Usually, we use the "Description" field for a long question, and then use the "Question" field to just put a short title. Wouldn't that work in your case?

**Comment by spacecabbie** [comment]
> Hi @spacecabbie
> Usually, we use the "Description" field for a long question, and then use the "Question" field to just put a short title. Wouldn't that work in your case?

Yes we work like this. Was just giving it here to for a futher version to adjust it a bit to txt wrap or limit input.
