### ISSUE TITLE
LTI: Error while Importing students from Chamilo LMS for Github Classroom

### ISSUE THREAD

**Issue by rajeekum** [chamilo/chamilo-lms#3099]
**Describe**
I have enabled Github Classroom in my Course. Added Required setting [ Keys and URL]
After that connect to Github Classroom from Chamilo LMS also works fine. But when I try to Import students from your LMS, I am getting following error:
 "GitHub Classroom does not have access to your course roster on your learning management system. Please ensure that you've allowed GitHub Classroom to retrieve your course membership from your learning management system and try again. "

**To Reproduce**
1. Install Plugins IMS/LTI --> Enable it
2. Create a course
3. Goto Course Settings -- Click on LMS/LTI - external configuration and provide - consumer key, shared secret and Launch URL. Save settings.
4. Try to connect to Github Class after logging as LMS user.
5. Connection successful.
6. After that try to import studetns/user by clicking on Github Classroom "Import students from your LMS", it is throwing following error-
"GitHub Classroom does not have access to your course roster on your learning management system. Please ensure that you've allowed GitHub Classroom to retrieve your course membership from your learning management system and try again. "

**Expected behavior**
I should be able to import users successfully

**Screenshots**

![image](https://user-images.githubusercontent.com/55356819/75098939-fe429380-55e1-11ea-92aa-88dd0084025f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, firefox, safari

**Server
 - OS: Ubuntu 18.04
 - Version of Chamilo:  1.11.10
 - Version of PHP: 7.2

**Additional context**
NA

**Comment by ywarnier** [comment]
Hi @rajeekum 
You may want to wait for the release of Chamilo 1.11.12 as it comes with support for LTI Advantage. I believe LTI 1.1 (as we support it in Chamilo 1.11.10) does not have support for user creation (although honestly I'm not the best person to tell you that with certainty).

**Comment by AngelFQC** [comment]
Chamilo 1.11.10 doesn't have support for Names and Roles Provisioning for LTI 1.1.

1.11.12 comes with support LTI 1.3 and LTI Advantage services (names and roles provisioning included).

But as indicated on the help page from GitHub Classroom, it requires:
- LTI version 1.0 and/or 1.1
- LTI Names and Roles Provisioning 1.X

**Comment by rajeekum** [comment]
Thanks ywarnier and AngelFQC for the update.

Please let me know, When is version 1.11.12 expected ?

**Comment by rajeekum** [comment]
Hi Team,

Any update on availability 1.11.12 for LTI 1.3 and LTI Advantage services.

**Comment by rajeekum** [comment]
Any update on this, please ?

**Comment by ywarnier** [comment]
Hi, we are currently aiming at around ~20th of July 2020 for 1.11.12
