### ISSUE TITLE
Quiz: Add option to prevent going back to previous questions

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3100]
At the moment it's impossible to block the user from going back in an exercise, except in the new (still unreleased) exercise mode "Direct feedback as pop-up", but this one shows a popup and forces us to display feedback and whether the user got it right or not.
However, this means that we already have code (and language variables) preventing the user to go back.

We need a new *option* for v2.0, but we also need it for a specific customer case in 1.11.12, so:
* add a $_configuration['quiz_prevent_backwards_move'] = false; option to configuration.php
* add SQL documentation to add the field c_quiz.prevent_backwards (0 by default)
* add the option (checkbox) at the end of the quiz edition page with lang var: 
$QuizPreventBackwards = "Prevent moving backwards to previous questions";
* make sure users cannot go back (with the "back" arrow in the browser) and cannot see the "Previous" button

I have already created the language variable.

**Comment by lonesomewalker** [comment]
Hello Yannick,

will this also be documented in the default configuration file?

Thanks, Alex

**Comment by jmontoyaa** [comment]
It is possible to test in 11.chamilo.org

**Comment by ywarnier** [comment]
That was perfect. Thanks.
@lonesomewalker yes, this is now available in 1.11.x (will be in 1.11.12) by executing a query on c_quiz and enabling an option (found in main/install/configuration.dist.php).
You can see that here:
https://github.com/chamilo/chamilo-lms/commit/9486bad7f2894e9ef6115d03affb29865e90640b#diff-328f990606e44bf8b5f1c0851fd15498R1394
