### ISSUE TITLE
importing quiz ims/qti  missing answers. 

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3104]
**Describe**
Exporting quiz ims/qti. When importing the quiz back it skips the answers for half of auestions.
as 1 ok 2 missing answers 3 ok 4 missing answers.

**To Reproduce**
Export and import i have included the file on this ticked.

**Expected behavior**
When importing none of date should be lost.

**Desktop (please complete the following information):**
windows 10
 - Browser brave Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)
(tested in chrome as wel),

**Server
 - OS: System => Linux web0114.zxcs.nl 2.6.32-954.3.5.lve1.4.64.el6.x86_64 #1 SMP Wed May 15 12:53:53 EDT 2019 x86_64
 - Version of Chamilo:  [1.11.10]
 - Version of [PHP Version => 7.1.33]

**Additional context**
Most likely due to special characters
I know the instructor that creates the questions like to "format" his questions and answers.
The answers are in the xml there just not imported i wil have another look this weekend if i can find the culprit if someone doesn't beat me to it :)

As always access to the system (only for official repository maintainers) is possible if wanted.
Alsop looked at https://github.com/chamilo/chamilo-lms/issues/2890 seems not related (ea: quiz imports fine no errors and they are multiple choice.

**Comment by ywarnier** [comment]
@spacecabbie since you've been reporting a few of these, could I ask you to check on https://11.chamilo.org each time to confirm the issue still exists? You can create your own user or enter as admin/admin. This platform is updated every once in a while (as opposed to version 1.11.10 which is from May last year), so it avoids us looking for a bug that might already have been solved (and we've worked a bit on QTI since 1.11.10, so it would make sense if it was already fixed)

**Comment by spacecabbie** [comment]
> @spacecabbie since you've been reporting a few of these, could I ask you to check on https://11.chamilo.org each time to confirm the issue still exists? You can create your own user or enter as admin/admin. This platform is updated every once in a while (as opposed to version 1.11.10 which is from May last year), so it avoids us looking for a bug that might already have been solved (and we've worked a bit on QTI since 1.11.10, so it would make sense if it was already fixed)

Sorry for the late reaction been so busy.

Message understood and will do. I have tested this issues and as of today its not working on 11.chamilo.org as well it imports but answers get lost like described above.

Ps. How can i keep my platform uptodate like 11.chamilo.org or is that not recommended in live servers.

**Comment by spacecabbie** [comment]
One more additional information i managed to figure out what's going on i think.
the questions that have commends behind answer are the ones that are empty.
@ywarnier any change you could confirm its indeed a bug or a inability of qti ?

**Comment by AngelFQC** [comment]
I can't reproduce the issue: 
I have this file [Exporting and importing from QTI](https://github.com/chamilo/chamilo-lms/files/4996577/qti2_export_13.zip) and I have imported it in https://11.chamilo.org/main/exercise/admin.php?cidReq=1209&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=444

**Comment by ywarnier** [comment]
> Ps. How can i keep my platform uptodate like 11.chamilo.org or is that not recommended in live servers.

It is not recommended on production environments.
You can set it up with a small script if you have initially installed Chamilo from Git (only in that case) with a PHP script like this, that is called by cron on a regular basis (and that you would put in the folder just above the Chamilo root folder - although you could put it directly in your Chamilo root folder with one or two changes):
```
<?php
/**
 * Update this development installation of Chamilo
 * Launched via cron (0 * * * * www-data /usr/bin/php /var/www/portal/chamilo-update.php > /dev/null)
 */
if (PHP_SAPI != 'cli') {
  die('Not allowed');
}
$dir = __DIR__.'/chamilo';
chdir($dir);
exec('git reset --hard origin/1.11.x');
exec('git pull origin 1.11.x');
exec('composer -q -n update');
exec('rm -rf '.$dir.'/var/cache');
include $dir.'/app/config/configuration.php';
exec('mysql -h '.$_configuration['db_host'].
    ' -u '.$_configuration['db_user'].
    ' -p`cat '.__DIR__.'/.pdb` '.
    $_configuration['main_database'].' '.
    '-e "UPDATE settings_current '.
    'set selected_value = \'My campus ['.date('YmdHi').']\' '.
    'where variable = \'siteName\'"');
echo "Done";
```

This is not perfect, but it should be enough to update your portal automatically every time the script is called by cron, and change the title (siteName) of your portal to reflect when it was last updated.

**Comment by ywarnier** [comment]
@spacecabbie we need an example (either the QTI file or a link to a course in 11.chamilo.org) to test this today, otherwise we won't be able to find a fix in time for 1.11.12.

**Comment by spacecabbie** [comment]
I will do this asap but i am swamped with issues in my private life.

This has been 2 months of disaster for me. Translation also has yet to be
finished.
I will try to make some time tonight or this weekend.

Met vriendelijke groeten / Live Long and Prosper,
Hans
*ps. ivm dyslexie kan het zijn dat ik worden oversla of spelfouten maak.*

**Comment by ywarnier** [comment]
@spacecabbie No worries, good luck with your stuff!

**Comment by spacecabbie** [comment]
[qti2_export_34.zip](https://github.com/chamilo/chamilo-lms/files/5044673/qti2_export_34.zip)

At this point i can't even import it. I am sure this is due to extensive formatting in the text IIRC that's what i traced it down to last time I worked on it. it says invalid file. If you wish to see the source test ( i cant move it to 11.chamillo.org) happy to provide credentials on our system.

**Comment by spacecabbie** [comment]
I am closing this to open a new correct one later witch proper information.,
