### ISSUE TITLE
Impossible de dupliquer un cours créé avec un logiciel auteur tiers

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#3105]
**Décrivez le problème**
Un cours importé depuis un logiciel auteur fonctionnant sur lé plate-forme ne peut pas être dupliqué..

**Comment le reproduire**
Pour le reproduire, il faut:
1. Créer un cours dans lequel est importé la ressource SCORM (1.2). LP fonctionnel
2. Créer un cours vide
3. Dans Maintenance du cours fonctionnel, utiliser l'option "Dupliquer" et sélectionner le cours vide en cible
4. Aller dans le cours vide, le contenu SCORM n'a pas été importé
Note : le test du cours source est bien importé dans le cours cible. En allant dans le répertoire SCORM du cours cible, il n'y a qu'index.php, le contenu SCORM n'est pas copié

**Comportement attendu**
Le cours cible devrait contenir l'ensemble des éléments du cours source (notamment le contenu SCORM dans le LP)

**Bureau (à compléter au mieux):**
 - Windows 10 en local
- Chamilo 1.11.10 (fonctionnelle :) )
- Un membre du forum a le même souci : Prb Import/export ou copie de cours avec SCORM

**Serveur
 - Windows 10
 - Version de Chamilo:  1.11.10
 - WAMP server - service lancé au démarrage
PHP7.x

**Comment by NicoDucou** [comment]
Bonjour @Coursenligne 

Par defaut les paquets scorms d'un cours ne sont pas exportés pour des raisons de sécurité car on ne peut pas être certain de leur contenu.

Pour activer l'import et l'export des scorms dans l'export/import de cours de Chamilo il faut activer une option de configuration dans app/config/configuration.php

```
// Allow SCORM packages when importing a course
$_configuration['allow_import_scorm_package_in_course_builder'] = true;
```

Normalement ça répond au besoin. Merci de confirmer pour pouvoir fermer la tâche si tout est bon avec cette option.

**Comment by Coursenligne** [comment]
Bonjour @NicoDucou,
Merci beaucoup pour cette réponse.
Cela fonctionne parfaitement. J'update le forum....
Le cas peut être passé en closed.
Merci de la rapidité de la réponse !
