### ISSUE TITLE
Messagerie - champ "Envoyer à" inaccessible si la plate-forme est en italien

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#3107]
**Décrivez le problème**
Bien que mis dans l'objet, le réseau social (envoi de mail) fonctionne correctement quand la langue de la plate-forme est en anglais et en français. Si je passe la plate-forme en italien, impossible d'accéder au champ "Envoyer à".

Référence sur le forum (en anglais...) : http://forum.chamilo.org/viewtopic.php?f=52&t=11086&sid=5de1dcad206c7078bca29fd1a1bb8237

**Comment le reproduire**
Pour le reproduire, il faut:
1. Sur la page de login, sélectionner Italiano comme langue
2. Se connecter comme d'habitude (nom/mot de passe)
3. Aller dans "Social Network" et essayer d'écrire un message

Le champ "Envoyer à" est plus haut que pour les autres langues, il semble qu'il est inclus dans un autre champ ET si je tape les 3 premiers caractères dans le champ, rien ne se passe

**Comportement attendu**
A la saisie des 3 premiers caractères du nom, une liste devrait apparaitre, permettant de sélectionner le contact à qui envoyer le message.

**Captures d'écran**
Voir le forum (suivre le lien donné).

J'ai fait le test sur ma plate-forme locale (Win10 // WAMP server en service automatique). Version 1.11.10 de Chamilo (j'attends la 1.11.12 avec une fébrilité débordante :) )

Pas de message d'erreur. Si je repasse la plate-forme en anglias ou en français, le comportement redevient normal.
Je n'ai pas testé d'autres langues, mais je confirme qu'en italien, le souci apparaît.
Bon courage !!!

**Comment by ywarnier** [comment]
Bien vu. Ça vient du fait que la variable de langue "Select an option" est traduite comme "Seleziona un'opzione" qui contient une apostrophe qui n'était pas échappée.

C'est corrigé dans https://github.com/chamilo/chamilo-lms/commit/dbdb238f130adfc27a97b2ee30b845b215457888

**Comment by Coursenligne** [comment]
Merci Yannick.
Fonctionne parfaitement quand modifié :)
