### ISSUE TITLE
copy paste code in exercise.

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3112]
Referring to an old post of mine: [https://github.com/chamilo/chamilo-lms/issues/2752](url)

I was wondering about this code:

https://github.com/chamilo/chamilo-lms/blob/4ca170bc00bf798d65b2dd57c0c32ac4f3f89d92/public/main/exercise/exercise_result.php#L72

In my Original question i never specified an alternative option, Like the quiz protection for copy and paste works perfect. 

But I cannot find the setting for it in the main interface I can only find "block_copy_paste_for_students-group" witch does not seem to have any effect.

Could some one give me a pointer about this code will it stay and ifso is there or wil there be a toggle for it in the interface ?

**Comment by AngelFQC** [comment]
Hi @spacecabbie 

Change this setting in the `app/config/configuration.php` file.

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/install/configuration.dist.php#L578

**Comment by spacecabbie** [comment]
> Hi @spacecabbie
> 
> Change this setting in the `app/config/configuration.php` file.
> 
> https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/install/configuration.dist.php#L578

Top one ! thanks.
So atm there is no "gui" switch ?

**Comment by ywarnier** [comment]
Nope. When adding new features that would normally require an interface option where we need an additional field in the database, we cannot change the database between minor versions so we add the settings in main/install/configuration.dist.php temporarily, and later move them into the interface at a later date (with the next major version).
