### ISSUE TITLE
Error on the acces visualization on the details session page for a user

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3119]
**Describe**

On a user follow up page when entering the details of a session, for example here :1234: 
https://11.chamilo.org/main/mySpace/myStudents.php?student=66&details=true&course=TESTPREREQUISENTRESESSION&origin=resume_session&id_session=21#infosStudent

When clicking on the See accesses buton to open https://11.chamilo.org/main/mySpace/access_details.php?student=66&course=TESTPREREQUISENTRESESSION&origin=resume_session&cidReq=TESTPREREQUISENTRESESSION&id_session=21

it shows this error : 
`Fatal error: Uncaught Error: Call to undefined function convert_to_string() in /furanet/sites/11.chamilo.org/web/htdocs/main/mySpace/access_details.php:142 Stack trace: #0 {main} thrown in /furanet/sites/11.chamilo.org/web/htdocs/main/mySpace/access_details.php on line 142`

Reproduced on 11.chamilo.org on the 10/03/2020

**Comment by jmontoyaa** [comment]
Fixed with 

https://github.com/chamilo/chamilo-lms/commit/9a2c8bda63b50a5089ebe1735539ae9c7e346299

**Comment by NicoDucou** [comment]
All good now
