### ISSUE TITLE
Error al subir y calificar tareas

### ISSUE THREAD

**Issue by R0sy** [chamilo/chamilo-lms#3120]
Tengo instalada la versión de plataforma 1.11.10 la versión de php es: 5.6.4, al instalar no hubo problema, pero a la hora de subir una tarea y querer calificarla da el siguiente error: "Fatal error: Call to undefined function mime_content_type() in /home/epmerida/public_html/campusvirtual/main/work/work.lib.php on line 143", la plataforma esta montada en un servidor de hosting de Bluehost. 

A continuación adjunto imagen del error.
Alguien me podría ayudar a resolver el error. 
![Captura de pantalla 2020-03-10 a la(s) 18 08 22](https://user-images.githubusercontent.com/42190653/76369751-30e6ce80-62fa-11ea-9b5a-071a18f9aec8.png)

**Comment by fcampiglia** [comment]
Tuve el mismo problema. Había echo una instalación desde 0, tuve que cambiar la versión de PHP a 7.2 y se terminaron los problemas.
Espero te sirva.
Saludos.

**Comment by kikesandi** [comment]
Yo tengo php 7.2 y tengo ese problema... alguna otra idea?

**Comment by ywarnier** [comment]
Hola @R0sy,
otro usuario reportó un problema similar, que debería provenir (como en su caso) de la falta de la extensión "php-fileinfo" en tu servidor.

Hemos modificado la documentación de Chamilo para reportar esta dependencia: https://github.com/chamilo/chamilo-lms/commit/affe0b799d61ec0e183423be1ade1d208990a906#diff-9cfb980ad885d9b99b527d196aef7aedR78

**Comment by R0sy** [comment]
He actualizado el servidor a php 7.2 y he vuelto a montar la plataforma desde cero pero ahora cuando quiero configurar la base de datos me arroja el siguiente error: **Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /home/epmerida/public_html/campusvirtual/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php on line 16** y no solo ese sino que también me manda esta advertencia: **Warning: Unsupported declare 'strict_types' in /home/epmerida/public_html/campusvirtual/vendor/sonata-project/block-bundle/src/Resources/stubs/symfony2.php on line 3.**

Alguna solución por favor.

**Comment by ywarnier** [comment]
Existen varios paquetes distintos para Chamilo, uno para cada versión de PHP (o casi). Podrías especificar qué paquete de Chamilo usaste para "volver a montar la plataforma"? (o si te quedaste con el código de antes de PHP 7.2)

**Comment by R0sy** [comment]
Instale nuevamente la versión de chamilo para php7, esperando que con esta versión funcionará, pero me salen esos errores.

**Comment by ywarnier** [comment]
No debería.
Has instalado por encima del código anterior, o has borrado lo anterior antes de instalar?

**Comment by R0sy** [comment]
He borrado los archivos anteriores e instalado desde cero.

**Comment by ywarnier** [comment]
No se que decir. Algo tiene que provenir de algún problema de caché, porque el paquete de Chamilo 1.11.10 para PHP 7.2, junto con una instalación de PHP 7.2, funciona muy bien en numerosas instalaciones.
Quizás pon un "<?php phpinfo();" dentro de un archivo temporalmente y cárgalo para ver si efectivamente es PHP 7.2 que está corriendo para la web. A veces puede haber varias versiones funcionando en un servidor y no ser la que piensas que corra...

**Comment by ywarnier** [comment]
Sigue siendo el mismo error Parse error: syntax error, unexpected 'const', verdad?

**Comment by ywarnier** [comment]
Alguna noticia?
