### ISSUE TITLE
Mail improvements

### ISSUE THREAD

**Issue by HiHighs** [chamilo/chamilo-lms#3125]
**Is your feature request related to a problem? Please describe.**

 I'm always frustrated ....

- when I cant switch in emails, like previous and next

- when I want to delete multiple emails, selecting multiple emails and deleting them doensn't work

**Describe the solution you'd like**

- buttons for previous mail and next mail when you have opened an email

- emails deleting together works

**Comment by ywarnier** [comment]
Bulk deletion works in 1.11.12 (to be released soon).
The other request to add previous and next buttons or icons is great. Thanks for suggesting it.

**Comment by ywarnier** [comment]
Work in progress in https://github.com/chamilo/chamilo-lms/pull/3325

**Comment by carlangas159** [comment]
PR #3325

**Comment by ywarnier** [comment]
Tested and approved (with little style changes)
