### ISSUE TITLE
Iconos de las opciones de administración no aparecen.

### ISSUE THREAD

**Issue by Luisriveraa** [chamilo/chamilo-lms#3130]
**Describe el problema**
Una descipción concisa y clara del problema.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a '...'
2. Dar clic en '....'
3. Bajar hasta '....'
4. Ver el error que dice '...'

**Comportamiento esperado**
Una descripción concisa y clara de lo que esperabas que ocurriera.

**Capturas de pantalla**
![CapturaONS](https://user-images.githubusercontent.com/10029356/77125746-cbd75b00-6a14-11ea-9188-81e0e86933b0.JPG)
![CapturaONS](https://user-images.githubusercontent.com/10029356/77125771-e578a280-6a14-11ea-8edd-e05a09337102.JPG)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
@Luisriveraa Podrías obtener la URL de alguna de las imágenes que *no* cargan, por favor?

**Comment by Luisriveraa** [comment]
Gracias por su respuesta,

Opté por instalar la versión más reciente de Chamilo, ahí está funcionando
bien.

Atentamente.

*Luis Rivera Almeyda.*
Informática & Sistemas
Cel. 999 6262 77 - RPM #999 6262 77


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ywarnier** [comment]
Perfecto, gracias.
