### ISSUE TITLE
[import learning path] exercices broken

### ISSUE THREAD

**Issue by jeroenbrussich** [chamilo/chamilo-lms#3132]
**Describe**
A teacher created a learning path with exercises. One? of those exercises gives feedback on the answers by checking the input of the student against the answer provided by the teacher. That exercise works flawlessly.

If, however, we export the learning path to a zip-file and then upload that zip-file into another course, the learning path gets uploaded but the exercise no longer gives feedback by checking the answer. The imported exercise seems to be broken.

**To Reproduce**
import the scorm file attached to this bug report

**Expected behavior**
exercise _Naamgeving_ tells me what names I spelled wrong.

**Screenshots**
**WORKING EXAMPLE**

![afbeelding](https://user-images.githubusercontent.com/245972/77317706-f7578f80-6d0b-11ea-99ff-bc1f796ca72e.png)

**IMPORTED EXAMPLE - NOT WORKING**

![afbeelding](https://user-images.githubusercontent.com/245972/77317770-1bb36c00-6d0c-11ea-9b56-5854a6da0e1d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome, firefox, edge

**Server
 - OS: ubuntu 19.04
 - Version of Chamilo:  1.11.10
 - Version of PHP: 7.2
[remediering-hoofdstuk-2.zip](https://github.com/chamilo/chamilo-lms/files/4369370/remediering-hoofdstuk-2.zip)

**Comment by ywarnier** [comment]
To make such copies, please do not export as SCORM but use the course maintenance tool to take a partial course backup.
The SCORM export feature only exports a subset of the question types as these have to be fully supported in SCORM format (which requires us to write a lot of JS code, which is not going to happen as a community effort).
