### ISSUE TITLE
Add DKIM support in e-mails

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3133]
Mails sent by Chamilo often get trapped in the SPAM folder of large providers like gmail and hotmail (mostly hotmail, though). This could be improved by supporting DKIM for additional authenticity information.

https://en.wikipedia.org/wiki/DomainKeys_Identified_Mail

PHPMailer, the library we use to send e-mails, seem to support it (testing required), so it should not be too difficult to implement.

Configuration parameters can go to app/config/mail.conf.php, commented out by default, and be checked in main/inc/lib/api.lib.php::api_mail_html(), right before the call to $mail->Send(), here: 
https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/api.lib.php#L9048

**Comment by ywarnier** [comment]
Research so far:
PHPMailer doesn't really seem to support DKIM.
The mail.conf.dist.php could be augmented with
```
$platform_email['DKIM'] = 0; //enable DKIM by setting this to 1
$platform_email['DKIM_SELECTOR'] = 'chamilo'; // an indicator of the application sending the e-mail through this specific DKIM key
$platform_email['DKIM_DOMAIN'] = 'mydomain.com'; //the domain for e-mail sending, not necessarily api_get_path(WEB_PATH)
$platform_email['DKIM_PRIVATE_KEY'] = '/path/to/private/key'; // the *path* to the private key (not the private key itself). It has to be readable by www-data, which is not the case by default for private keys in /etc/ssl/private
```
In order for the e-mail sending to work, you *have to* ensure that the addresses sending all e-mails is from the given domain. The best way to enforce this is to set $platform_email['SMTP_UNIQUE_SENDER'] to 1.

Next, the api.lib.php has to be modified (as suggested above, before $mail->Send()) to include:
```
    // Enable DKIM headers if DKIM config is set
    if (!empty($platform_email['DKIM']) &&
        !empty($platform_email['DKIM_DOMAIN']) &&
        !empty($platform_email['DKIM_SELECTOR']) &&
        !empty($platform_email['DKIM_PRIVATE_KEY'])) {
        $mail->DKIM_selector = $platform_email['DKIM_SELECTOR'];
        $mail->DKIM_domain = $platform_email['DKIM_DOMAIN'];
        $mail->DKIM_private = $platform_email['DKIM_PRIVATE_KEY'];
    }
```

Then, obiously, a record has to be defined in the DNS. For example if the selector is "chamilo", we could have a TXT record like this:
```
chamilo._domainkey.[mydomain.com] IN TXT "v=1; k=rsa; s=chamilo; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDU4FzkdVE68lJcbHtJz59aZZQ0gHDbkRHRETyC130SAymWvaNvWsJ3lD0vWOaPI0PKTvkBFw9wVuY9wX4OKvhFPy3NWxu7Lp0Jqxf9vl6/20znJUjIJytLmQSzd7ym+Vhz1RIlYxjQbAbuhPI6klq3aHNYvs4rnkotnxZ+5CWk6wIDAQAB"
```
This can be checked with a DNS checker like https://www.whatsmydns.net/#TXT/

Finally, the signing and sending can be checked through some DKIM checker like https://appmaildev.com/en/domainkey

So far my tests have been unsuccessful, even when trying to use the default SHA1 (which should not be used anymore).
It seems like something is failing at the signature syntax level.

**Comment by ywarnier** [comment]
There's a PHP-DKIM library (and another one) somewhere, but not sure PHPMailer doesn't support it already. They all seem to have taken inspiration from PHPMailer anyway.

**Comment by lonesomewalker** [comment]
I'm just curious why this needs this effort...?
DKIM is done best on SMTP side.
Chamilo supports SMTP, and almost ALL providers have email accounts (even Office365).

**Comment by ywarnier** [comment]
A lot of people start Chamilo installations with a new domain, purchased on the hosting system where they install Chamilo. This does not always include DKIM, and *many* corporate teams requesting a Chamilo server do not have access (permissions) to request SMTP access. I guess it's just a matter of context.
Also, Office365 is incredibly slow for SMTP. When you have to send an announcement to thousands of users at once (portail maintenance or stuff like that) and sending *one* mail takes 3s, you understand you need better solutions.

**Comment by lonesomewalker** [comment]
That's a valid point.

**Comment by ywarnier** [comment]
As reported by @jmontoyaa in the PR, some customizations had been made in the original PHPMailer library, which will need to be transfered in this issue.

**Comment by ywarnier** [comment]
DKIM support has been added, tested on several production systems and working well.
Furthermore, previous customizations of the phpmailer library have been reviewed with no apparent critical change needed in the new version. This closes this new feature request.

**Comment by ywarnier** [comment]
A side note: although with this library we can now completely support SPF, DKIM and DMARC, hotmail & co (outlook, live.com, etc) still tend to consider e-mails from Chamilo as SPAM.
A good practice is to ask your first users with one of those addresses to immediately tell those e-mail platforms that the e-mail *is* legitimate and to get it out of the SPAM folder, so those platforms "learn" from their mistakes.
Either way, there seems to be great improvements for both Yahoo and Gmail when using DKIM.
