### ISSUE TITLE
/log/ generate files every min

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3134]
**Describe**
Tue-Mar-24-07:23:01-CET-2020.log
Tue-Mar-24-07:24:01-CET-2020.log
Tue-Mar-24-07:25:01-CET-2020.log
Tue-Mar-24-07:26:01-CET-2020.log
Tue-Mar-24-07:27:01-CET-2020.log
log files are created every min empty.

**Expected behavior**
I am unsure if this expected.

**Server
 - OS: centos 7.7
 - 1.11.x fresh install "git pull origin 1.11.x" dev version
 - 7.3

**Additional context**
This was also the case in the release version.
IF this is expected then should clear cache clean these ?

**Comment by ywarnier** [comment]
@jmontoyaa can you enlighten us on how those log files should behave normally?

**Comment by jmontoyaa** [comment]
Chamilo doesn't have a /log/ folder.
There's a folder /app/logs but is not currently used.

**Comment by spacecabbie** [comment]
> Chamilo doesn't have a /log/ folder.
> There's a folder /app/logs but is not currently used.

Ok fair this can be closed then clearly not related. File generation has stopped when i deleted that directory. Source process was not found .
