### ISSUE TITLE
multi_url for multi organizations

### ISSUE THREAD

**Issue by mesoshqip** [chamilo/chamilo-lms#3144]
Can you help me for this feature? Where can I activate this? And each url has its own admin and administration page?

**Comment by lonesomewalker** [comment]
https://docs.chamilo.org/en/admin/global_features/multi-url/

**Comment by mesoshqip** [comment]
in /app/config/configuration.php there is:
// Session lifetime
$_configuration['session_lifetime'] = 360000;
// Activation for multi-url access
// When enabling multi-url, settings can be configured by multi-url using a simple
// sub-element. E.g. $_configuration['session_lifetime'][1] = true; could be turned into
// something like $_configuration['session_lifetime'][2] = false; to affect only URL
// with ID 2. The ID can be found in the access_url table.
//$_configuration['multiple_access_urls'] = true;

For the apache configuration I am clear, but here in configuration file, what is needed to do?
1. step: o uncomment  "$_configuration['multiple_access_urls'] = true;" 
else?
Thank you
.:

**Comment by lonesomewalker** [comment]
Yes, uncomment this, then you get another menu point in the admin backend.
The pictures and description as shown in documentation.
