### ISSUE TITLE
Importer un exercice via Excel : errreur calcul du score maximum

### ISSUE THREAD

**Issue by michel3141** [chamilo/chamilo-lms#3145]
**Décrivez le problème**
J'importe un QCM de type UNIQUE_ANSWER par l'import excel
Le score maximun = somme des scores 
Avec des scores négatifs pour les mauvaises réponses c'est différent du score max

**Comment le reproduire**
- Je crée le Quizz au format XLS

Quiz | MyQuizz |  
-- | -- | --
Question | MyQuestion |  
Answer1 | MyAnswer1 | -1
Answer2 | MyAnswer2 | x
Answer3 | MyAnswer3 | -1
Answer4 | MyAnswer4 | -1
Score |   | 3
Category | MyCat |  
EnrichQuestion | MyEnrichQuestion |  
QuestionType |   | 1

- J'importe dans l'interface
Mes Cours/MonCours/Exercices/Importer un exercice via Excel/Importer le fichier

- J'obtiens 

Questions|Type|Catégorie|Difficulté|Score maximum|Action
-- | -- | -- | -- |--| --
MyQuestion|Question à réponse unique (QRU)|MyCat|1|0|
  

**Comportement attendu**

Questions|Type|Catégorie|Difficulté|Score maximum|Action
-- | -- | -- | -- |--| --
MyQuestion|Question à réponse unique (QRU)|MyCat|1|3|

**Serveur**
 - Version de Chamilo:  `$_configuration['system_version'] = '1.11.10';`

**Contexte additionnel**

- Pour résoudre mon problème, j'ai modifié `chamilo/main/exercise/upload_exercise.php` 
```
433c433
<                                 $total += (float) $score;
---
>                                 if ($correct) $total += (float) $score;

```
- Après l'import, l'édition et la validation de la question (*sans modification*) calcule le score maximum correctement.

- L'utilisation de 'Utiliser le score sur mesure pour toutes les questions' lors de l'import ne change rien, ou je n'ai pas trouvé comment m'en servir

**Comment by ywarnier** [comment]
Assigned to @AngelFQC for review.

**Comment by AngelFQC** [comment]
Fix confirmed
