### ISSUE TITLE
Supprimer question orpheline

### ISSUE THREAD

**Issue by michel3141** [chamilo/chamilo-lms#3148]
**Décrivez le problème**
Si on supprime une question orpheline de la banque de questions, cela peut supprimer une question dans un exercice

**Comment le reproduire**
- créer un exercice : 'Exercice #1'
- créer une question dans 'Exercice #1' : 'Question #1'
- créer un autre exercice : 'Exercice #2'
- ajouter 'Question #1' dans 'Exercice #2' à l'aide de la banque de questions
- supprimer 'Exercice #2' 
- Aller dans la banque d'exercice, on voit deux questions qui sont certainement :
  - 'Question #1'  de 'Exercice #1'
  - 'Question #1' supprimée de 'Exercice #2'
- afficher uniquement les questions orphelines.
- Supprimer la question orpheline

'Exercice #1' n'a plus de question

**Comportement attendu**
au choix :
- Quand on supprime une question orpheline ça ne détruit pas question dans les exercices
- Si une questions est utilisée dans plusieurs exercices, supprimer un exercice ne la rend pas orpheline

**Serveur**
 - Version de Chamilo:  `$_configuration['system_version'] = '1.11.10';`

**Comment by ywarnier** [comment]
@michel3141 d'abord merci d'avoir rapporté le problème.
Nous l'avons a priori corrigé, et notre processus normal est de demander à l'utilisateur de vérifier par lui-même si la correction est satisfaisante. Pour éviter les soucis de mise à jour avec un patch git, au cas où tu ne serais pas compétent avec Git, nous avons un portail de test https://11.chamilo.org/ sur lequel on peut se connecter comme admin/admin pour les tests (portail nettoyé fréquemment).

Auras-tu l'occasion de tester dans les prochains jours?

**Comment by michel3141** [comment]
Résolu.
Le comportement correspond au comportement attendu :
> Si une questions est utilisée dans plusieurs exercices, supprimer un exercice ne la rend pas orpheline

Merci
