### ISSUE TITLE
web.config IIS Chamilo 1.11

### ISSUE THREAD

**Issue by rozepeda** [chamilo/chamilo-lms#3152]
Hola a todos, me he pasado un rato tratando de hacer una migración de Chamilo 1.11 (Ubuntu Server 18.04/Apache 2.4) -> Chamilo 1.11 (Windows Server 2019/IIS 10) y creo que casi lo he logrado.

En principio quiero comentar que poca información hay sobre el uso de Chamilo con Windows/PHP/MySql, lo que ha complicado aun mas mi tarea.

Siguiendo un poco tutoriales, y documentación (oficial y no oficial) casi lo tengo a punto y con respecto a eso quiero comentar que:

La documentación de configuración de re-dirección de IIS que proponen en la web oficial (https://11.chamilo.org/documentation/installation_guide_es_ES.html) no esta completo, hay algunos detalles. Por lo que me gustaría compartir mi archivo web.config (probado y funcionando), seguro a alguien le ayudará y le ahorrará mucho tiempo.

(con esta configuración, resolví problemas de error 404, o el mensaje de error "Lo sentimos, no le está permitido acceder a esta página o su conexión ha caducado. Para volver a la página anterior pulse el enlace inferior o haga clic en el botón Atrás de su navegador."

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>

        <httpRedirect enabled="false" destination="" httpResponseStatus="Permanent" />
        <rewrite>
            <rules>
                <rule name="rule 1v" stopProcessing="true">
                    <match url="^certificates/$" />
                    <action type="Rewrite" url="certificates/index.php?id=%1" appendQueryString="false" />
                </rule>
                <rule name="rule 2v" enabled="true" stopProcessing="true">
                    <match url="^courses/([^/]+)/?$" />
                    <action type="Rewrite" url="main/course_home/course_home.php?cDir={R:1}" appendQueryString="true" />
                </rule>
                <rule name="rule 3v" enabled="true" stopProcessing="true">
                    <match url="^courses/([^/]+)/index.php$" />
                    <action type="Rewrite" url="main/course_home/course_home.php?cDir={R:1}" />
                </rule>
                <rule name="rule 4v" stopProcessing="true">
                    <match url="^courses/([^/]+)/scorm/(.*([\.js|\.css|\.png|\.jpg|\.jpeg|\.gif]))$" />
                    <action type="Rewrite" url="app/courses/{R:1}/scorm/{R:2}" />
                </rule>
                <rule name="rule 5v" stopProcessing="true">
                    <match url="^courses/([^/]+)/scorm/(.*)$" />
                    <action type="Rewrite" url="main/document/download_scorm.php?doc_url=/{R:2}&amp;cDir={R:1}" />
                </rule>
                <rule name="rule v6" stopProcessing="true">
                    <match url="^courses/([^/]+)/document/certificates/(.*)$" />
                    <action type="Rewrite" url="app/courses/{R:1}/document/certificates/{R:2}" />
                </rule>
                <rule name="rule v7" stopProcessing="true">
                    <match url="^courses/([^/]+)/document/(.*)$" />
                    <action type="Rewrite" url="main/document/download.php?doc_url=/{R:2}&amp;cDir={R:1}" />
                </rule>
                <rule name="rule v8" stopProcessing="true">
                    <match url="^courses/([^/]+)/upload/course_home_icons/(.*([\.js|\.css|\.png|\.jpg|\.jpeg|\.gif]))$" />
                    <action type="Rewrite" url="app/courses/{R:1}/upload/course_home_icons/{R:2}" />
                </rule>
                <rule name="rule v9" stopProcessing="true">
                    <match url="^courses/([^/]+)/upload/([^/]+)/(.*)$" />
                    <action type="Rewrite" url="main/document/download_uploaded_files.php?code={R:1}&amp;type={R:2}&amp;file={R:3}" />
                </rule>
                <rule name="rule v10" stopProcessing="true">
                    <match url="^courses/([^/]+)/work/(.*)$" />
                    <action type="Rewrite" url="main/work/download.php?file=work/{R:2}&amp;cDir={R:1}" />
                </rule>
                <rule name="rule v11" stopProcessing="true">
                    <match url="^courses/([^/]+)/course-pic85x85.png$" />
                    <action type="Rewrite" url="main/inc/ajax/course.ajax.php?a=get_course_image&amp;code={R:1}&amp;image=course_image_source" appendQueryString="true" />
                </rule>
                <rule name="rule v12" stopProcessing="true">
                    <match url="^courses/([^/]+)/course-pic.png$" />
                    <action type="Rewrite" url="main/inc/ajax/course.ajax.php?a=get_course_image&amp;code={R:1}&amp;image=course_image_large_source" appendQueryString="true" />
                </rule>
                <rule name="rule v13" stopProcessing="true">
                    <match url="^courses/([^/]+)/(.*)$" />
                    <action type="Rewrite" url="app/courses/{R:1}/{R:2}" appendQueryString="false" />
                </rule>
                <rule name="rule v14" stopProcessing="true">
                    <match url="^session/(\d{1,})/about/?$" />
                    <action type="Rewrite" url="main/session/about.php?session_id={R:1}" appendQueryString="false" />
                </rule>
                <rule name="rule v15" stopProcessing="true">
                    <match url="^course/(\d{1,})/about/?$" />
                    <action type="Rewrite" url="main/course_info/about.php?course_id={R:1}" appendQueryString="false" />
                </rule>
                <rule name="rule v16" stopProcessing="true">
                    <match url="^badge/(\d{1,})" />
                    <action type="Rewrite" url="main/badge/issued.php?issue={R:1}" appendQueryString="false" />
                </rule>
                <rule name="rule v17" stopProcessing="true">
                    <match url="^skill/(\d{1,})/user/(\d{1,})" />
                    <action type="Rewrite" url="main/badge/issued_all.php?skill={R:1}&amp;user={R:2}" appendQueryString="false" />
                </rule>
                <rule name="rule v18" stopProcessing="true">
                    <match url="^badge/(\d{1,})/user/(\d{1,})" />
                    <action type="Rewrite" url="main/badge/issued_all.php?skill={R:1}&amp;user={R:2}" appendQueryString="false" />
                </rule>
                <rule name="rule v19" stopProcessing="true">
                    <match url="^main/exercice/(.*)$" />
                    <action type="Rewrite" url="main/exercise/{R:1}" appendQueryString="true" />
                </rule>
                <rule name="rule v20" stopProcessing="true">
                    <match url="^main/newscorm/(.*)$" />
                    <action type="Rewrite" url="main/lp/{R:1}" appendQueryString="true" />
                </rule>
                <rule name="rule v21" stopProcessing="true">
                    <match url="^service/(\d{1,})$" />
                    <action type="Rewrite" url="plugin/buycourses/src/service_information.php?service_id={R:1}" appendQueryString="false" />
                </rule>
                <rule name="rule v22" stopProcessing="true">
                    <match url="^lti/os$" />
                    <action type="Rewrite" url="plugin/ims_lti/outcome_service.php" appendQueryString="false" />
                </rule>
                <rule name="rule v23" stopProcessing="true">
                    <match url="^([^/.]+)/?$" />
                    <action type="Rewrite" url="user.php?{R:1}" appendQueryString="false" />
                </rule>
                <rule name="rule v24" stopProcessing="true">
                    <match url="^(tests|.git)" ignoreCase="false" />
                    <action type="Rewrite" url="/-" />
                </rule>
            </rules>
        </rewrite>
  </system.webServer>
</configuration>`

Espero que esta información ayude a la comunidad.

Saludos desde México

**Comment by ywarnier** [comment]
Hola @rozepeda 
Gracias por tu contribución. Aquí somos muchos linuxeros, así que *intencionalmente* pasar de Ubuntu a Windows Server es algo que tendremos dificultades en entender :-)
Pero enhorabuena... si dices que funciona, te creemos.

En todo caso, mencionas que "casi lo [has] logrado". Que es lo que falla todavía?

**Comment by ywarnier** [comment]
Tu contribución ha sido incluida en la documentación (varias cosas que corregiste eran simplemente faltas de actualización de la documentación)

**Comment by AngelFQC** [comment]
También se incluyó en el archivo ẁeb.config` que ya existe.

**Comment by ywarnier** [comment]
Looks good to me now.
