### ISSUE TITLE
Error en asignar ejercicios como componente de evaluación online (en sesión)

### ISSUE THREAD

**Issue by aragonc** [chamilo/chamilo-lms#3153]
Algo curioso me ha pasado, no quiero crear componentes de evaluación y ejercicios en el curso base, para eso quiero crearlos directamente en la sesión.

Pero no me deja asignar los componentes de evaluación en la sesión de un ejercicio creado en la misma sesión.

Ejemplo. en la siguiente pantalla estoy en una sesión, y no tengo ningún ejercicio creado de un ejercicio base, solo el ejercicio creado en una sesión (por el icono de la estrella)

![ejercicio](https://user-images.githubusercontent.com/2940509/77968670-8b49ce00-72ad-11ea-9bcf-b94c970c05d6.png)

Ahora me voy a la herramienta de evaluaciones de la misma sesión, y voy  a asignar un componente de evaluación en linea, pero no me deja seleccionar el componente.

![componente](https://user-images.githubusercontent.com/2940509/77968802-d8c63b00-72ad-11ea-9e54-87142cbd703e.png)

Solo ocurre cuando no tengo ejercicios de cursos bases creados... si existe un ejercicio base creado si se activa. mucho cuidado con eso.

Saludo.

**Comment by ywarnier** [comment]
Si existe un ejercicio en el curso base, te mostrará los dos (curso base y curso-sesión). A cambio, si solo existe un ejercicio en la sesión, no te mostrará nada. Bug confirmado.
