### ISSUE TITLE
how to hide notification tab?

### ISSUE THREAD

**Issue by Nellmat** [chamilo/chamilo-lms#3154]
Friends, can anyone in good faith help?
how to hide the info window that appears when logging in at the bottom of the footer.

[janela](https://user-images.githubusercontent.com/22569234/78063128-996c1d00-7387-11ea-83c7-2f8506157768.png)

**Comment by Nellmat** [comment]
Friends, can anyone in good faith help?
how to hide the info window that appears when logging in at the bottom of the footer.

![janela](https://user-images.githubusercontent.com/22569234/78063454-231bea80-7388-11ea-86a1-3510db08656c.png)

**Comment by ywarnier** [comment]
Well, contributing something to Chamilo would be a good way to get people to answer you. This is not really urgent, is it? (asking because you posted your message twice)
There is an option called admin_chamilo_announcements_disable which you have to set to true in app/config/configuration.php:
```
// Disable Chamilo.org announcements at the top of the admin page
$_configuration['admin_chamilo_announcements_disable'] = true;
```

**Comment by Nellmat** [comment]
Hey guys;
Can someone please help. my students whenever they receive an email from the chamilo portal, at the top there is a visible code

{ "@context": "http://schema.org", "@type": "EmailMessage", "description": "Chamilo Mail Notification", "potentialAction": { "@type": "ViewAction", "target": "" } }
![Captura de ecrã 2021-06-22, às 00 16 20](https://user-images.githubusercontent.com/22569234/122839168-69dc6400-d2ef-11eb-8939-14247c0e1407.png)

**Comment by Diketsosetho16** [comment]
You can edit the file to remove the text the file is in chamilo_1.11.x/main/template/default/mail/mail.tpl
