### ISSUE TITLE
Parameter 'platform_language' not found in category 'language'

### ISSUE THREAD

**Issue by Fenn-CS** [chamilo/chamilo-lms#3155]
**Describe**
After a successful installation of the system (Though it did not show a success message, I just checked the logs), opening index.php returns Parameter 'platform_language' not found in category 'language'. It's worth noting that, I am doing this installation inside a docker container running on `php:7.2-apache`

**To Reproduce**
Fresh install on docker `php:7.2-apache`

**Expected behavior**
Open homepage

**Screenshots**
![Screenshot from 2020-03-31 23-56-54](https://user-images.githubusercontent.com/14317775/78082770-bca8c380-73ab-11ea-9dc5-2a8aca7cc458.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS docker on  Linux Ubuntu 18.04
 - Version : development fork
 - Version of PHP: 7.2

**Comment by ywarnier** [comment]
From the screenshot, you are trying to install from Git, from the master branch.
The master branch is still in development. Please use the 1.11.x branch for a functional system.
