### ISSUE TITLE
Updates to Installation guide & php extension check page

### ISSUE THREAD

**Issue by serhio-w02** [chamilo/chamilo-lms#3160]
**Is your feature request related to a problem? Please describe.**
complete the php extensions check page, at least fileinfo is missing, update install guide

**Describe the solution you'd like**
work.lib.php is using mime_content_type() if extension is not present, it breaks half of the work tool functions; upload diagnostics is false negative for student , grading is not possible, ....

**Additional context**
should be at noted in installation guide

be well, Mark111

**Comment by ywarnier** [comment]
I'm not leaving this for review as the changes are pretty basic.
Thanks for reporting, @serhio-w02
