### ISSUE TITLE
Wrong  file list order on last_sent  column in Dropbox

### ISSUE THREAD

**Issue by mk111** [chamilo/chamilo-lms#3162]
**Describe**
at the time, the order relies on an assumption that order of the real date is the same as produced by Display::dateToStringAgoAndLongDate($dropbox_file->last_upload_date);

! - order does not depend on logic but on localization (string translation)
! - order changes by the time 

examp. 1:
1 year ago                             // this is ok y>m>d
1 month ago
1 day ago

if you add "1 hour ago"  the order becomes wrong (left asc /d<h<m<y/, right desc /y>m>d>h)
```
day ago     <--                   year ago
hour ago   <--                    month ago
month ago                         hour ago    <--
year ago                          day ago  <--
```

(: after a year of no posting the order is correct ... more than 1 year  ago (i believe decade is not used ?)

5 min fix is not possible, since current  implementation of sortabletable does not support column mappings for events (sort/asc/dec is implemented on dateAgo values as is seen on page, hidden column with real date will be welcome to sort on when clicked on datAgo),  alternative would be rendering dateAgo with javascript on real date values ... 

**Version**
Chamilo 1.11.-

**Comment by ywarnier** [comment]
Yes, this is a widespread issue I've seen in other tables too. Should be fixed with a hidden column data or something like that (or simply returning to numeric dates, although dd/mm/yyyy will not help with the sorting)

**Comment by carlangas159** [comment]
PR #3332
