### ISSUE TITLE
Test/Random questions - no End test button

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#3175]
When you create a test, e.g. from 3 questions.
In options set:
- Questions per page: One question by page
- Question selection type to: Random
- Random questions: 2

Start test, on last (2) question you see button "Next question" instead of "End test" button.

See here: https://11.chamilo.org/main/exercise/exercise.php?cidReq=TESTQ1&id_session=0&gidReq=0&gradebook=0&origin=&

Tested on 11.chamilo.org (09.04.2020)

**Comment by mk111** [comment]
related/duplicated/ with #3013 and #3116 .

**Comment by xam1234** [comment]
Sorry about that. Something is gone bad with questions since 1.11.10-1.11.x.
It should be priority to fix this before 1.11.12.

**Comment by mk111** [comment]
@xam1234  (:  +1:
