### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getAdminUrl() 

### ISSUE THREAD

**Issue by mesoshqip** [chamilo/chamilo-lms#3182]
Hi
1. error
I had enabled plugin:
Teacher notes:
Jcapture Screencast v 1.0

If I am not enabled any regions there is not an error, but if I enabled any regions I have an error:

when iI went in the administration menu  there is an error:
Fatal error: Uncaught Error: Call to a member function getAdminUrl() on null in /var/www/chamilo/www/main/admin/index.php:685 Stack trace: #0 {main} thrown in /var/www/chamilo/www/main/admin/index.php on line 685

2. error
I had also "Enable external Pixlr services=Yes" but there is this error:
Blocked by X-Frame-Options Policy

An error occurred during a connection to pixlr.com.

Firefox prevented this page from loading in this context because the page has an X-Frame-Options policy that disallows it

Same thing also with Chrome
What can I Do?

**Server
 - OS: Linux Ubuntu 18.04
 - Version of Chamilo:  1.11.10
 - Version of PHP:  7.2,

**Comment by ywarnier** [comment]
Closing. No review by reporter in 30 days
