### ISSUE TITLE
Error en Catalogo de Cursos

### ISSUE THREAD

**Issue by 2020luisangel** [chamilo/chamilo-lms#3185]
No funciona esta opcion y me saca de la plataforma, sin permitirme buscar un curso para inscribirme en el.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a '...'
2. Dar clic en '....'
3. Bajar hasta '....'
4. Ver el error que dice '...'

**Comportamiento esperado**
Una descripción concisa y clara de lo que esperabas que ocurriera.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
Cerrando. No respeta los elementos mínimos de reporte de error
