### ISSUE TITLE
 This portal is currently experiencing database issues. Please report this to the portal administrator. Thank you for your help.

### ISSUE THREAD

**Issue by carrazco** [chamilo/chamilo-lms#3187]
ESTA APARECIENDO ESTE MENSAJE EN LA PLATAFORMA, This portal is currently experiencing database issues. Please report this to the portal administrator. Thank you for your help.. 
Y SE EXPERIMENTA LENTITUD PARA ENTRAR Y TRABAJAR EN LA MISMA.

**Comment by Jimro12** [comment]
Hola, alguien respondió a tu pregunta?. Me pasa lo mismo... HELP!!!

**Comment by jaguirre021** [comment]
Hola, alguien respondió a tu pregunta?. Me pasa lo mismo... HELP!!!

**Comment by ywarnier** [comment]
Hola a todos. Si hablan de campus.chamilo.org, es el resultado de una sobrecarga temporal debido a que tenemos alrededor de 3 veces el tráfico usual en este portal, y que es un servicio gratuito financiado por la generosas donaciones (a la Asociación Chamilo), que lamentablemente son muy pocas en números. Les invitamos a que apoyen económicamente a la Asociación Chamilo para darle más recursos y que pueda invertir más en esta infraestructura.

Si se trata de otros portales, entonces usualmente (y en particular durante la crisis del COVID-19) se trata de un problema de capacidad de la infraestructura y deberán conversarlo con sus administradores

**Comment by damisio** [comment]
Ese mensaje me muestra a pesar de que mi servidor de Base de datos MariaDB cuenta con suficiente Core disponiv¿bles y memoria RAM.
Asi que inicie a TUNEAR MariaDB, incrementando numero de conexiones.

**1. Ruta del archivo a configurar:**

vi /etc/my.cnf

`[mysqld]`
`max_connections=250`

**2. Recursos para informarse mejor como incrementar Numero de Conexiones** 

- [Recurso: Variables de configuracion, tome lo que nesecite](https://www.amadourias.com/optimiza-y-tunea-mysql-o-mariadb-en-tu-servidor-vps/)

- [Como configurar my.cnf](https://stackedcloud.eu/index.php?rp=/knowledgebase/41/Aumentar-las-conexiones-a-MySQL.html)

Buena suerte :-)

**Comment by Damianbull77** [comment]
@ywarnier, aun la plataforma sigue teniendo este inconveniente? ya que tengo este mismo error en mi sitio pero empezó así hace aproximadamente 20 días, agradecería si pudiera indicarme como solucionar este error, gracias.
