### ISSUE TITLE
settings_current.selected_value must be text

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3188]
In some plugin or other long configuration settings (including lists of URLs separated by commas), the 255 varchar field selected_value is not large enough to store the values we need.

Change it to TEXT during the migration from 1.11 to 2.0.

alter table settings_current CHANGE COLUMN selected_value selected_value text default null;

**Comment by jmontoyaa** [comment]
It's already the case.

https://github.com/chamilo/chamilo-lms/commit/0c8670d2eb990b45b25d973a5e1dcaf135d8b787

**Comment by AngelFQC** [comment]
No encontré el cambio en la migración, así que mandé un cambio en Version20.php
