### ISSUE TITLE
Limit speed of user searches in social network

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3191]
In the social network and the message sending (/main/social/search.php?q=some+user+name and main/messages/new_message.php), the search for users is made in a way that each keystroke (javascript event onkeyup, I think), a search is sent in the users table to find the corresponding users.

This (the onkeyup) is too fast. It should at least wait one second before sending each request (wait for the accumulation of keystrokes for one second or more), otherwise the server gets flooded, risking the user to be blocked by firewalls.

On portals with a very high number of users (more than 10.000, for example), each search request can last several seconds to come back with all the matching results, which is slower than the rate of requests sent, which creates a queue which can overload a server.

Version 1.11.x of 20200417

**Comment by AngelFQC** [comment]
In `message.ajax.php` exists a limit in the query when searching usernames... 
like `a=find_users&q=baggins&page_limit=10`

**Comment by ywarnier** [comment]
OK, but the SQL search is still on all the users... So slowing down the reaction time is needed

**Comment by ywarnier** [comment]
Or searching on less fields...

**Comment by ywarnier** [comment]
Tested and approved
