### ISSUE TITLE
Suivi (détails de l'apprenant dans le cours)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3193]
**Votre demande est liée à un problème en particulier? Décrivez-le nous...**
Une fonctionnalité est apparue récemment (non présente dans ma version 1.11.2) : la "visualisation des accès" de l'apprenant. C'est très utile.
Dans le même esprit, sans aller aussi loin que les points que j'évoquais ici  #2239,  il serait peut-être possible d'améliorer légèrement la vue des détails de l'apprenant en ajoutant 2 informations précieuses :
=> Le nombre d'accès au cours
=> La date/heure du dernier accès au cours (et pourquoi pas également pour le premier accès au cours ?). Dans le contexte d'un cours, cela me semble au moins aussi intéressant que le dernier accès à la plateforme.
 (cf ci-dessous sur l'image, entourés en rouge).

**Décrivez la solution que vous aimeriez trouver dans Chamilo**
Voici ce que cela pourrait donner :
![Capture - Copie - Copie](https://user-images.githubusercontent.com/24507698/79632589-9b442780-8160-11ea-8216-303c5e335581.JPG)

**Contexte additionnel**
Cela permettrait d'améliorer le suivi des apprenants et d'avoir les informations utiles sur le même écran (sans avoir à revenir au tableau général du suivi sur lequel figure le dernier accès au cours, sans l'heure, ce qui pourrait être également un petit plus...).

**Comment by ywarnier** [comment]
Je ne suis pas trop pour l'augmentation des rapports (mieux vaut rester simple) mais ici ça m'a l'air d'être simple et utile.

**Comment by AngelFQC** [comment]
Added

![imagen](https://user-images.githubusercontent.com/1697880/82600702-f3ad8100-9b73-11ea-97c0-f566f0d58e4d.png)

**Comment by tanchon** [comment]
@AngelFQC : parfait ! C'est exactement conforme à ma demande ! Merci !

Je trouve qu'ainsi la vue des détails a plus de pertinence (infos "accès au cours" vs "accès plateforme"). 

@Yannick : dans un contexte universitaire de "cours en ligne" intensifs comme en ce moment, les enseignants ont un énorme besoin de "suivi" :

- j'ai souvent constaté que des rapports fins d'utilisation des ressources du cours par les apprenants (tels ceux offerts par Claroline, ancienne version : cf #2239 sont de formidables outils pour permettre aux enseignants d'améliorer leurs pratiques pédagogiques. Pour des activités telles que la formation à la gestion de projet par les "projets tuteurés", ce suivi est un réel facteur clé de succès (c'est ainsi que malgré son grand âge, nous continuons à utiliser Claroline pour les cours nécessitant un fort suivi (bien que Chamilo lui soit très supérieur d'une façon générale et que le fait de "jongler" entre les deux plateformes présente des inconvénients).
- cela peut permettre d'identifier le plus tôt possible les éléments "décrocheurs", et ainsi susciter une réaction lorsqu'il est encore temps. Mais aussi permettre de conseiller de façon plus pertinente n'importe quel apprenant par rapport à son usage des outils.

Ceci juste pour défendre l'idée de rapports de suivi plus fins, sachant que moi et mes collègues, mais aussi nos étudiants, apprécions effectivement énormément Chamilo pour sa puissance mais aussi sa grande convivialité et simplicité d'utilisation (ce qui n'est pas le cas de Moodle et n'est plus le cas de Claroline "Connect", en ce qui concerne les deux derniers points).

Pour en revenir au sujet, je pense que l'on peut clore l'issue #3193 !

Merci à l'équipe pour ce formidable travail !

Tanchon.

**Comment by tanchon** [comment]
Pour info, voilà le résultat sur 1.11.10 (avec format date long). Je me permets de fermer l'issue. Merci !

![Capture](https://user-images.githubusercontent.com/24507698/82753548-bb51b100-9dc6-11ea-9df7-82f000977c40.JPG)

**Comment by tanchon** [comment]
Peut-être serait-il tout de même utile de repréciser le titre de l'étiquette ? : j'ai l'impression que le résultat de la requête est le nombre de connexions sur des jours différents, plutôt que le nombre total de connexions ? C'est une information pertinente, mais l'intitulé est un peu trompeur.

Merci !

Tanchon

**Comment by tanchon** [comment]
@AngelFQC : la mise en page est en effet nettement meilleure ainsi ! C'est plus logique, avec les informations importantes (celles relatives au cours) en haut !

Cependant, je pense toujours que l'intitulé de l'indicateur devrait modifié, pour ne pas introduire de confusion par rapport à l'information affichée dans "access_details" : dans l'exemple ci-dessous, l'étudiant s'est connecté en tout 19 fois au cours (c'est l'indicateur donnée dans access details), sur 3 jours différents (c'est désormais ce qui apparait sur my students. 

Les deux indicateurs sont intéressants, mais je pense qu"il faut trouver un intitulé pour l'indicateur apparaissant dans my students.
Illustration :
![Capture5](https://user-images.githubusercontent.com/24507698/82794046-26a48d00-9e72-11ea-97c7-e82ea6034c1b.JPG)

**Comment by ywarnier** [comment]
@tanchon Pourrais-tu mettre les nouvelles propositions d'amélioration dans une nouvelle tâche? Nous essayons autant que possible de bien séparer les sujets et de ne pas prolonger une tâche dont la solution au problème initial a été fournie (sinon on n'en finit jamais, ce qui est très frustrant pour les développeurs).
