### ISSUE TITLE
Remplir les blancs avec permettre la permutation des réponses autorisée coché

### ISSUE THREAD

**Issue by alexiye** [chamilo/chamilo-lms#3195]
### Résultat actuel
Remplir les blancs avec permettre la permutation des réponses autorisée coché

100 % de réussite avec seulement une réponse bonne sur les trois (quand je remplis un seul blanc sur les trois).
exemple si je remplis un seul blanc (6+2 par exemple) et que je laisse les deux autres blancs vides, j'obtiens un résultat de 100% au lieu de 33%
Normalement pour avoir 100% on doit rentrer 3 réponses : 
7+1
6+2
5+3
### Résultat attendu
Calcul correct du score
###  Étapes pour reproduire
https://11.chamilo.org/main/exercise/overview.php?cidReq=BILLARD&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=161
![billard](https://user-images.githubusercontent.com/24505996/70860551-5a72a280-1f23-11ea-83d3-6871ae6c95b0.png)

###  Version de Chamilo
1.11.X en ligne

**Comment by ywarnier** [comment]
En effet, ce n'est pas normal. Merci de l'avoir rapporté.

**Comment by AngelFQC** [comment]
![imagen](https://user-images.githubusercontent.com/1697880/82273075-0e98af00-9942-11ea-9d71-dc755ab65fa4.png)

**Comment by alexiye** [comment]
Bravo à tous pour votre travail.

**Comment by alexiye** [comment]
Je viens de réessayer en ligne sur 1.11.x et l’erreur est toujours présente.

**Comment by AngelFQC** [comment]
I found the problem when the option "Allow answers order switches" is enabled.

**Comment by alexiye** [comment]
It’s Ok ! Thanks. 
Just for fun , music from France :
https://youtu.be/p6piYJcDu1g?fbclid=IwAR3msuH8QfUFnCB5e4x5Uv9Vc1H0eUNbXKkbxU8OIXgDJiiJKtkCQZKG1QI
