### ISSUE TITLE
No reproducen los videos en la plataforma Chamilo

### ISSUE THREAD

**Issue by CesarAToro** [chamilo/chamilo-lms#3196]
Buenos dias a toda esta comunidad.
Hemos venido realizando pruebas con chamilo para implementarlo en nuestra red local, nos hemos visto con algo de problemas (no soy muy experto), pero que con mucha lectura y ayuda de estos foros, hemos logrado solucionar casi todos.
El proble radica, es que cuando creamos el curso y queremos subir un video local (no de youtube), se realizan los pasos para subir el archivo al servidor en la respectiva carpeta del curso, pero este video no se reproduce, apesar de estar en formato mp4. 
 
Realizo los pasos de la siguiente manera:
1. Me dirijo a la carpeta del curso, luego a docuemntos y despues a videos:
![ch1](https://user-images.githubusercontent.com/36610503/79644270-75714f80-816d-11ea-8249-c28a78c4256f.png)

2. en la carpeta videos realizo los pasos para crear un documento, le doy un titulo y luego voy al boton video:
![image](https://user-images.githubusercontent.com/36610503/79644383-45767c00-816e-11ea-91ef-d3888df838ce.png)

3. Luego voy a la primera opcion "ver servidor" con la opcion "mp4" y me dirijo a la carpeta "videos" que la cree anteriormente y subo el video en formato mp4 que pesa al rededor de 16MB y que esta en mi pc.
![image](https://user-images.githubusercontent.com/36610503/79648558-2e3b8c80-8176-11ea-86fa-b998f7864e31.png)

4. Despues de crear el documento "video" me dirijo a el para reproducirlo pero me da el siguiente error en la pantalla de reproduccion despues de presionar play:
![image](https://user-images.githubusercontent.com/36610503/79651512-06005d80-8177-11ea-9c82-84c3389bdc64.png)

Si el formato que estoy subiendo esta en .mp4 deberia de reproducir sin problemas, o hay que agregarle algun permiso en la carpeta donde se aloja el archivo?

Mi pc desde donde accedo a chamilo tiene:
 - Sistema operativo : Windows 10 pro
 - Navegador : google chrome Versión 80.0.3987.163 (Build oficial) (64 bits)

**Servidor
 - Sistema operativo : Windows 10 pro
 - Versión de Chamilo: 1.11.10
 - Versión de PHP: 7.2.29
 - Apache 2.4.43
 - xampp-windows-x64-7.2.29-0-VC15-installer
 
Agradeceria la ayuda para ver donde esta el error, o mi falla!

**Comment by salvadorperezmejia** [comment]
Ese mismo problema tengo yo.

**Comment by ywarnier** [comment]
Hola @CesarAToro, @salvadorperezmejia 
Usamos una librería Javascript común para reproducir los videos. Las únicas razones que me vienen a la mente son que la combinación de navegador + sistema operativo no permita reproducir el vídeo, o que el servidor web no reconozca el formato como mp4 y esté mandando otra cabecera al navegador.
Para la primera posibilidad, lo mejor sería probar la misma página con Firefox y con Edge.
para la segunda, hay que abrir las herramientas de desarrollo de Chrome, pestaña "Red" y ver si el mp4 se muestra en la lista, y qué cabeceras envía como "Content-Type"

**Comment by Roger-Sa-H** [comment]
Buenos dias.
Pudieron solucionar el error, ya probe en los navegadores Firefox, Edge y el error continua.
Gracias de antemano.
