### ISSUE TITLE
Onglets "Page d'accueil" et "Mes cours" : éléments parasites (certificats)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3198]
**Décrivez le problème**
En tant qu'administrateur je paramètre dans les paramètres de configuration "activer outil compétences" : **NON**.

Pourtant, lorsque l'on se connecte (ici un étudiant) on voit apparaitre en accueil des éléments liés aux compétences : 
![Nouvelle image (4) - Copie](https://user-images.githubusercontent.com/24507698/79693283-fdd51a80-8269-11ea-94e3-82e8ceaab24e.jpg)

**Comportement attendu**
Les 2 éléments en rouge ne devraient pas apparaitre je pense puisque l'administrateur ne souhaite pas "gérer les compétences".

**Serveur
Concerne toutes les versions Chamilo (au moins depuis 1.11.2)

**Comment by ywarnier** [comment]
Les certificats et les compétences, bien qu'utilisant tous deux l'outil "Cahier de notes" dans le cours, ne sont pas liés (il n'est pas nécessaire d'avoir un certificat pour avoir une compétence, et vice-versa).

**Comment by tanchon** [comment]
OK . Le voyant apparaitre dans le bloc "compétences", j'avais fait un lien. Mais j'ai également désactivé tous les éléments liés aux notes. Donc cela pourrait être intéressant de faire "disparaitre" les liens "Mes certificats" lorsque l'on n'en n'a pas besoin.
Merci Yannick !

**Comment by tanchon** [comment]
Finalement, j'ai pu faire disparaitre les "certificats" et le bloc compétences en activant une ligne du fichier configuration (que j'ai passée de false à true) : 
$_configuration['hide_my_certificate_link'] = true;
Le résultat correspond à mes attentes !
