### ISSUE TITLE
La página este muy lenta y presenta muchos errores

### ISSUE THREAD

**Issue by jalopezte** [chamilo/chamilo-lms#3202]

**Comment by ywarnier** [comment]
Hola @jalopezte 
Si hablas de campus.chamilo.org, estamos recibiendo mucho más consultas que de costumbre en este momento y estamos haciendo mejoras progresivas cada día para reducir los tiempos de espera.

**Comment by jalopezte** [comment]
Si del campus. Mil gracias. Son una excelente plataforma.
