### ISSUE TITLE
Image uploaded to profile is not reflecting

### ISSUE THREAD

**Issue by rajeekum** [chamilo/chamilo-lms#3204]
**Describe**
Goto - UserProfile and upload image. I see i mage is not reflected in profile.
**To Reproduce**
1. Go to 'Edit Profile", Browse Image and select your image to upload.
2. After image is uploaded successfully, I don't see it's been reflected. Earlier it was working fine.
3. when i try to see source of image 
app/upload/users/2/220/220_5ea16bc8d8c29_Kannu.jpg?rand=5ea16bfaf3332
404 Not Found
The resource requested could not be found on this server!

**Expected behavior**
Image should be uploaded and reflected in user profile.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, firefox.

**Server
 - OS: Linux Ubuntu 18.04
 - Version of Chamilo:  1.11.10
 - Version of PHP: 7.2

**Comment by ywarnier** [comment]
Define "earlier"... when was it working?

**Comment by rajeekum** [comment]
Same release of Chamilo: 1.11.10. I am not sure, what went wrong as I didn't make any modifications.

**Comment by rajeekum** [comment]
I tried to debug using inspect component.
I am getting error as mentioned below. Files are present at /app/upload/users/1/103
attached screenshot for
small_103_5ea3b964aa7a1_Kannu.jpg:1 Failed to load resource: the server responded with a status of 404 ()
**Please note:** I have performed Cache and temp Cleanup.

![File_not_Available1](https://user-images.githubusercontent.com/55356819/80285080-16e53c00-8740-11ea-8e03-36246cb76b71.png)

**Comment by rajeekum** [comment]
Fixed this issues. Permission issue.
