### ISSUE TITLE
Update symfony packages in 1.11.x 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3205]
**Is your feature request related to a problem? Please describe.**
Old symfony libs, block installation of other new packages.

**Describe the solution you'd like**
Update old symfony 2.8 libs in composer.json

**Comment by jmontoyaa** [comment]
I tried to update the packages, but I'm blocked by this lib:

https://packagist.org/packages/toin0u/digitalocean

It looks it has been abandoned.

And I'm also blocked by the PHP version, meaning other updated packages have as requirement PHP 7.0, they abandoned PHP 5.6. 

So we are still stuck with this composer.

**Comment by jmontoyaa** [comment]
I updated chash packages in a new branch here:

https://github.com/chamilo/chash/commit/47f67f3c9a3ed07bb44472ea73d01a84ade9473b

**Comment by jmontoyaa** [comment]
In other words, we cannot update composer.json with new libs if we still have support for PHP 5.6.

**Comment by ywarnier** [comment]
The digitalocean package could be removed for now (we could add a note in the small script that uses it to say you need to download it separately). I don't think anyone uses it but I would hate to loose the nice work that we did in BBB around that.

For the rest, I'm very reticent about bumping our PHP requirement to 7(.2) as a minimum. Hopefully we can avoid that for this minor version.

@AngelFQC will be checking if we can use an older version of the API that generates those dependency changes.

**Comment by ywarnier** [comment]
Moving to 2.0 (which will actually have an even higher version of Symfony anyway) as the requirements were too difficult to meet in 1.11

**Comment by jmontoyaa** [comment]
This is already fixed in v2.0

**Comment by ywarnier** [comment]
Then I'm closing it. It's an internal task, so no need to have external feedback.
