### ISSUE TITLE
Multiple errors with CKeditor

### ISSUE THREAD

**Issue by rajeekum** [chamilo/chamilo-lms#3207]
**Describe**
I am facing multiple error with CKeditor because of that functionality like:
Who is Online:
Course Content: Adding description not working.
**Please Note:** I performed "Cleanup of Cache and Temporary Files"

**To Reproduce**
1. Go to 'My Course" ---> Description ---> Add description- I see there is no option available at description [content section] - to enter text.
2. I have set "who is online" setting to see who is online at course. But that also is not working.
3. See error

Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/image2_chamilo/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/oembed/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/video/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/wikilink/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/wordcount/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/inserthtml/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/qmarkersrolls/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/youtube/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/asciimath/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/mathjax/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/asciisvg/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/mapping/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
/web/assets/ckeditor/plugins/toolbarswitch/plugin.js?t=H0CF:1 Failed to load resource: the server responded with a status of 404 ()
ckeditor.js:234 Uncaught Error: [CKEDITOR.resourceManager.load] Resource name "image2_chamilo" was not found at "https://app.training-ladder.com/web/assets/ckeditor/plugins/image2_chamilo/plugin.js?t=H0CF".
    at window.CKEDITOR.window.CKEDITOR.dom.CKEDITOR.resourceManager.<anonymous> (ckeditor.js:234)
    at g (ckeditor.js:230)
    at Array.n (ckeditor.js:230)
    at v (ckeditor.js:230)
    at HTMLScriptElement.CKEDITOR.env.ie.e.$.onerror (ckeditor.js:231)

**Expected behavior**
Please help me fix this as this is blocker for my Learning Website. 

**Screenshots**
Screenshot attached.
![CKEditor_Not_Found](https://user-images.githubusercontent.com/55356819/80270416-5d518100-86d5-11ea-923e-ce33ffea5d87.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome, firefox

**Server
 - OS: Linux Ubuntu 18.04
 - Version of Chamilo:  1.11.10
 - Version of PHP: 7.2

**Comment by rajeekum** [comment]
does above fix applicable for this issue also ? I see it's more to do with captcha login fix.

**Comment by AngelFQC** [comment]
> does above fix applicable for this issue also ? I see it's more to do with captcha login fix.

I found the error in the console log when loading https://app.training-ladder.com/

**Comment by rajeekum** [comment]
Do you think it's a problem ? and How to fix this ?

**Comment by rajeekum** [comment]
Hi Angel, 

Need help in fixing issues with my application. I see multiple issues like:
1. Not able to Delete uploaded document
2. Not able to see users online and online in course

Please let me know - How to fix this.  As this is on production - Users are complaining.

**Comment by rajeekum** [comment]
This is working fine after fixing console error.
