### ISSUE TITLE
Question ordonnancement : bonne solution apparaît à l'apprenant

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3209]
Bonjour,
Si le problème a déjà été signalé merci d'effacer ce message (j'ai fait une recherche mais je n'ai pas trouvé).

Sur Chamilo 1.11.2 lorsque l'apprenant fait un retour en arrière sur sa question ordonnancement, ses réponses sont effacées (qu'elles soient bonnes ou mauvaises).

Sur la plateforme 11.chamilo.org (lien ci-dessous) (c'est une version 1.11.10 ?), le retour en arrière sur la question ordonnancement lui fait apparaitre la bonne solution.

**Décrivez le problème**
Testé sur 11.chamilo.org : 

Dans une question "ordonnancement", l'apprenant commet des erreurs. Il passe à la question suivante puis revient à la question précédente (qui est la question à laquelle il avait mal répondu) : il voit alors la bonne solution s'afficher à la place de sa mauvaise proposition (et la question lui sera compté comme étant exacte une fois l'exercice achevé).

Cela se passe aussi bien avec un compte enseignant qu'un compte étudiant.
En revanche, si il commet la même erreur et va au bout de l'exercice sans jamais revenir à la question d'ordonnancement, il n'y a pas de problème : l'exercice lui sera compté faux.

**Comment le reproduire**
=>Exercice paramétré avec "une question par page" et il est laissée la possibilité pour l'apprenant de faire un "retour en arrière" (retour à la question précédente).

1-L'apprenant répond à la question ordonnancement et commet une ou des erreurs
2- Il passe à la ou aux questions suivantes
3- Il revient à la (ou aux) questions précédentes pour revenir à l'exercice d'ordonnancement => il voit alors s'afficher la bonne réponse.

**Comportement attendu**
Lorsque l'apprenant revient à la question ordonnancement, il devrait retrouver sa réponses erronée et ne pas voir la bonne réponse.

**Serveur
Testé sur la version 1.11.10 ? (je crois : cf lien ci-dessous).
Lien vers l'exercice de test ici, sur la plateforme [11.chamilo.org
](https://11.chamilo.org/main/exercise/exercise.php?cidReq=TESTQCM&id_session=0&gidReq=0&gradebook=0&origin=&)

Remarque : sur ma plateforme en 1.11.2 j'ai un problème qui ressemble (mais moins embêtant) : lorsque l'apprenant revient sur sa question ordonnancement par un "revenir à la question précédente", ses choix sont effacés. 

J'ai donc l'impression que le "retour en arrière" pose pb d'une façon générale sur ce type de question.

**Comment by tanchon** [comment]
Je confirme que le bug existe également sur Chamilo 1.11.10 et pas seulement sur la plateforme test 11.chamilo.org.

**Le fait de quitter, puis revenir sur la question ordonnancement fait apparaitre la bonne réponse** : aussi bien dans le sens "question suivante puis question précédente" que "question précédente puis question suivante.

**Comment by NicoDucou** [comment]
Je confirme que le problème persiste sur les questions de type ordonnancement si on va sur https://11.chamilo.org/main/exercise/exercise.php?cidReq=TESTQCM&id_session=0&gidReq=0&gradebook=0&origin=&

On met des réponses au hazard, puis quand on revient en arrière sur la question ordonnancement les réponses que l'on avait saisies sont remplacées par les bonnes réponses.

**Comment by tanchon** [comment]
J'ai fait différents essais sur l'exercice que j'ai mis en référence dans mon 1er post : essais sur 11.chamilo.org. 

Tout semble désormais fonctionner parfaitement ! C'est nickel, merci !

Tanchon
