### ISSUE TITLE
Videoconference plugin 2.7 does not work with bigbluebutton 2.2

### ISSUE THREAD

**Issue by Shibly** [chamilo/chamilo-lms#3210]
I've install chamilo and enabled Videoconference plugin and configured accordingly. But everytime I tried to join a video conference, browser always keeps loading and never responds and I have to restart the apache server. 

I'm using 
macOS Catalina, 
php 7.1 
mysql 5.7
Videoconference version 2.7 
Chamilo LMS 1.11.10 for PHP 7.0.x or later

**Comment by lonesomewalker** [comment]
Please make a screenshot of your settings.

**Comment by Shibly** [comment]
> Please make a screenshot of your settings.
Here is my settings page screenshot. Thank you. 
https://prnt.sc/s66hv5

**Comment by Shibly** [comment]
[https://prnt.sc/s66hv5](url)

**Comment by lonesomewalker** [comment]
Please change your shared secret now since it has been public now
(on the bbb server "bbb-conf --setsecret HEREGOESYOURNEWSECRET")

Also, please remove
/bigbluebutton/
at the end of your servername.

**Comment by Shibly** [comment]
Perfect ! Let me try. Thank you !

**Comment by ywarnier** [comment]
> Also, please remove
> /bigbluebutton/
> at the end of your servername.

This part now works (in plugin 2.8.1) whether you put /bigbluebutton/ at the end or not.

**Comment by Shibly** [comment]
It works. But I can not enable recording. Am I still missing any settings issues ? Thank you !

**Comment by ywarnier** [comment]
Recording has to be enabled at the course level (course settings -> videoconference section at the end)

**Comment by Shibly** [comment]
My problems are solved. Thank you all.
