### ISSUE TITLE
Actualizar usuarios por CSV modifica la contraseña

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#3211]
**Describe el problema**
Si se quiere actualizar usuarios por CSV, se genera un usuario de manera obligatoria y se actualiza la contraseña.

Sin avisar y sin indicar que los datos se actualizaron.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'main/admin/user_update_import.php'
2. Subir un CSV con columnas "UserName;Email" de usuarios previamente registrados
```csv
UserName;Email
bbaggins;bbaggins.2@example.com
```
3. Comprobar que los usuarios no pueden ingresar

**Comportamiento esperado**
Actualizar sólo los emails en base a usuario indicado.

**Comment by NicoDucou** [comment]
Todo conforme con esto. Acabo de actualizar un usuario y sigue con su contrasena y puede acceder sin problema.
