### ISSUE TITLE
Página inicial no carga algunas partes

### ISSUE THREAD

**Issue by DrRH** [chamilo/chamilo-lms#3214]
Hice una instalación nueva de chamilo 1.11.10 (descargado desde chamilo.org en paquete tar) y cuando termina la instalación voy a mi dominio y me abre de la siguiente manera:

![image](https://user-images.githubusercontent.com/64128983/80622609-a58edd00-8a0e-11ea-9cfb-51ad839b0f91.png)

esta es la información que sale cuando activo modo de desarrollador:

![image](https://user-images.githubusercontent.com/64128983/80622694-c8b98c80-8a0e-11ea-9b18-b98c54c590ef.png)

Cuando digito mi usuario y contraseña y trato de entrar me sale error 404 no found.

![image](https://user-images.githubusercontent.com/64128983/80622886-09190a80-8a0f-11ea-935d-b401250152a9.png)

Servidor:
 - Hosting:  Contabo
 - Sistema operativo : Linux Ubuntu 18.04 con Vestacp
- Versión de Chamilo: 1.11.10
 - Versión de PHP: 7.2

 - DNS administradas por Cloudflare (no se si esto tenga que ver, pero dejo el dato)

cliente:
 - Navegador: chrome

**Comment by DrRH** [comment]
Volví a instalar el sistema operativo centos 7, cambié el panel de control a virtualmin con php 7.3, volví a instalar chamilo con todos las comprobaciones en verde y aún persiste el problema.

**Comment by ywarnier** [comment]
Parece que tienes un problema con la configuración de la URL (subdominio o subcarpeta).
Chamilo trata de cargar cosas donde no están.
Te recomiendo verificar root_sys y root_web en app/config/configuration.php y ver si tienen sentido. Parece que instalaste usando otra URL que la que usas luego de la instalación, o algo parecido.
