### ISSUE TITLE
No se puede ingresar contenido / Texto de introducción / Descripción general (Contenido)

### ISSUE THREAD

**Issue by ricardinis** [chamilo/chamilo-lms#3216]
Al crear el curso, no se puede modificar el texto de introducción porque no aparece la caja para introducir texto, solo aparece el boton Guardar texto de introduccion.

![error1](https://user-images.githubusercontent.com/3543168/80671275-fafad680-8a6e-11ea-8189-67cbf4e902c9.PNG)

pero en un video vi que se presenta de esta forma

![error2](https://user-images.githubusercontent.com/3543168/80671400-4ad99d80-8a6f-11ea-8c35-d2d7d78c0783.PNG)

Hay forma de colocar la caja

 Gracias

 - Versión de Chamilo: 1.11.10
 - Versión de PHP:  7.3

**Comment by ywarnier** [comment]
@ricardinis Parece ser un problema de caché o de Javascript. Podrías usar la opción de limpieza de caché en la página de administración, bloque "sistema" y luego cargar la página de introducción con ctrl+f5?
