### ISSUE TITLE
En la ejecución de ejercicio con "pregunta calculada" al devolverse agrega un ] u otro texto al final

### ISSUE THREAD

**Issue by uft-dti** [chamilo/chamilo-lms#3220]
**Describe**
ocurre cuando se devuelve a preguntas anteriores en el mismo ejercicio (el tipo de pregunta es "pregunta calculada").
En las preguntas que tenían respuesta, agrega un ] u otro texto al final; cuando esa respuesta se registra, estará equivocada.

**To Reproduce**
Adjunto enlace con el video de la secuencia de ejecución https://drive.google.com/file/d/1bpb5DajYSZBEc8sH5NG107p5i-xlt4de/view?usp=sharing

**Expected behavior**
debería poder revisar las preguntas sin sufrir cambios

**Screenshots**
https://drive.google.com/file/d/1bpb5DajYSZBEc8sH5NG107p5i-xlt4de/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Windows 10 / Mac 
 - Browser chrome 81.0.4044.129 (Build oficial) (64 bits)

**Server
 - OS: Centos 7
 - Version of Chamilo: 1.11.10
 - Version of PHP: 7.4

**Comment by ywarnier** [comment]
No llegamos a reproducir este problema. Por favor probar en https://11.chamilo.org si el problema ocurre y mandarnos el enlace. Gracias por reportar y darnos el seguimiento necesario para ayudarte @uft-dti

**Comment by ywarnier** [comment]
No feedback in 9 days and we cannot reproduce it. Closing.
