### ISSUE TITLE
Score de l’exercice erroné

### ISSUE THREAD

**Issue by lzebdi** [chamilo/chamilo-lms#3221]
**Décrivez le problème**
Quand un apprenant passe un exercice, le score affiché est erroné et ne reflète pas le vrai résultat de l’exercice. Ce cas de figure ne se produit qu’avec les questions à réponses multiples (QRM – Combinaison exacte…), pas avec les questions à réponse unique (QRU…). **ET seulement si l’exercice est paramétré avec les réponses désordonnées**.

**Comment le reproduire**
Pour le reproduire, il faut:
1. Créer un nouveau test
2. Paramètres avancés
3. Désordonner les réponses : **Oui**
4. Passer le test
Le score est erroné, tandis que le résultat est correct

**Comportement attendu**
Similitude entre score et résultat de l’exercice.

**Pour reproduire**
https://11.chamilo.org/main/exercise/exercise_report.php?cidReq=UE27S401&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=269

**Comment by tanchon** [comment]
Bonjour,
En suivant le lien j'ai cliqué sur le bouton de recalcul et cela semble fonctionner (100%).
Tanchon.

**Comment by ywarnier** [comment]
@lzebdi quand les questions sont modifiées à posteriori, des résultats de tentatives antérieures peuvent avoir l'air totalement incohérents. L'icône de "recalcul" dans la liste des résultats de l'exercice permet de corriger ça. Étant donné ce que rapporte @tanchon, il semblerait que ça ait été le cas ici...
je clôture donc la tâche (nous gérons plusieurs milliers d'examens par semaine au travers de nos clients et ce problème n'a jamais été rencontré lors d'un usage sans modification de questions à posteriori).
