### ISSUE TITLE
Résultat exercice : export pdf impossible

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3222]
**Décrivez le problème**
Bonjour,
Lorsque je visualise les résultats d'un étudiant dans un exercice (dans exercise_show.php) j'ai un affichage correct à l'écran (qui, soit dit en passant est génial pour l'apprenant car il peut voir ses fautes et les réponses attendues, le tout avec un très beau visuel : bravo !).

Mais, en tant qu'enseignant, je cherche à exporter ce résultat en pdf en cliquant en haut sur l'icone prévue à cet effet  
![Capture2](https://user-images.githubusercontent.com/24507698/80968789-d90ba600-8e18-11ea-9d21-50468fb108c5.JPG)

j'ai bien un fichier pdf qui est généré mais il est corrompu (avec un taille qui semble "normale", quelques centaines de ko) : illisible avec différents lecteurs pdf (Acrobat, Foxit...). Idem si je cherche à le visualiser dans le navigateur.

**Comment le reproduire**
Pour le reproduire, il faut:
1- aller dans la page des résultats de l'exercice passé par les apprenants
2- accéder à la page prévue pour les corrections (exercise_show.php)
3- cliquer sur l’icône d'export pdf en haut à gauche de la page.

**Comportement attendu**
Obtenir un fichier pdf lisible.

**Captures d'écran**
Lorsque je fais le test sur 11.chamilo.org, j'obtiens un message d'erreur (je ne sais pas du tout si c'est lié à l'erreur constatée sur ma plateforme) :
![Capture](https://user-images.githubusercontent.com/24507698/80969174-7a92f780-8e19-11ea-8d37-028b36e0776b.JPG)

**Bureau (à compléter au mieux):**
Windows 10. Problème aussi bien avec Firefox que Edge.

**Serveur
- Linux
- Chamilo 1.11.10
- Php 7.2

Merci !

**Comment by ywarnier** [comment]
@tanchon les deux sont probablement liés, oui. La différence probable étant que sur 11.chamilo.org, on demande à ce que les messages de type "warning" soient affichés, alors que sur ta machine ce n'est probablement pas le cas. Cela signifie que, même si le même problème se produit, il se présente d'une manière différente.

Quoi qu'il en soit, nous ne pouvons pas régler le problème à la source, parce qu'il s'agit d'un élément d'une librairie que nous utilisons, et que nous dépendons d'une correction du côté de la librairie en soi.

Pour ce qui est d'identifier plus précisément si le problème sur ta machine est le même que sur 11.chamilo.org, il faudrait que ton système soit configuré pour envoyer les erreurs vers un log d'erreurs en particulier (en général c'est le cas par défaut et PHP enregistre ça dans les logs d'Apache) et que error_reporting n'exclue pas le niveau "E_WARN". Pour ça il faut faire un peu de recherche, mais en gros ta configuration actuelle correspond probablement déjà. Il nous faudrait donc juste le message qui apparaît dans le log d'Apache...

**Comment by tanchon** [comment]
Renseignement pris auprès de mon hébergeur, je n'ai malheureusement pas accès à ce type d'erreur.  Désolé.

**Comment by ywarnier** [comment]
Pas suffisamment d'informations pour corriger le problème. Je le clôture. Cela devrait être résolu dans la version 2.0 avec des librairies de génération de PDF plus à jour (impossible dans 1.11 à cause d'autres dépendances). Le patch fourni par carlangas ci-dessus permet de réduire une partie des messages d'erreur.
