### ISSUE TITLE
Ejercicios en lecciones se queda pegado al terminar

### ISSUE THREAD

**Issue by elbobyhn** [chamilo/chamilo-lms#3224]
Al terminar un ejercicio incluido en cualquier lección, se queda pegado y no muestra la pantalla final del ejercicio.
Se probo desde diferentes navegadores Chrome, FF, Edge, etc.

### Chamilo Version: 1.11.10 php 7

**Comment by ywarnier** [comment]
No pudimos reproducir este error y hay demasiado poca información (a pesar de una plantilla para reportar issues) para que podamos ayudar.
