### ISSUE TITLE
Ejercicios en celular 

### ISSUE THREAD

**Issue by CZFEBO** [chamilo/chamilo-lms#3225]
**Describe el problema**
No da opción para iniciar los ejercicios en los teléfonos móviles.

¿Cómo se pueden resolver los ejercicios en dispositivos móviles?

![imagen](https://user-images.githubusercontent.com/64813039/81019371-234a5280-8e2c-11ea-8f3a-86335a546835.png)

**Comment by ywarnier** [comment]
Es cuestión del footer que toma demasiado espacio en este portal en particular.
Es un error de diseño, no es un error de Chamilo.
Gracias por reportar. Hemos transmitido a los encargados del estilo de campus.chamilo.org
