### ISSUE TITLE
ERROR EN GENERACIÓN DE CERTIFICADOS

### ISSUE THREAD

**Issue by andreagra** [chamilo/chamilo-lms#3232]
En la opción de evaluaciones cuando hago clic en la lista de certificados sale el siguiente error: Esta página no funciona campus.chamilo.org no puede procesar esta solicitud en este momento.
HTTP ERROR 500
Lo cual significa que es un error del servidor

**Cómo reproducir**
Pasos para reproducir el problema:
(En el campus virtual de Chamilo)
1. Ir a Evaluaciones
2. Dar clic en Lista de Certificados
3. Ver el error que dice: Esta página no funciona campus.chamilo.org no puede procesar esta solicitud en este momento.
HTTP ERROR 500'

**Comportamiento esperado**
Se esperaría poder acceder a todos los certificados de los alumnos en el curso, y poder generar los pendientes.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/64969490/81305860-7139a300-9044-11ea-84d8-96547d255a2d.png)
![image](https://user-images.githubusercontent.com/64969490/81305965-8f070800-9044-11ea-93df-2abc78a6ee14.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador: En todos los navegadores sale el mismo error

**Servidor
 - Sistema operativo : Windows 10
 - Versión de Chamilo:  Chamilo Campus
 - Versión de PHP:

**Comment by ywarnier** [comment]
Hola @andreagra 
Este problema se debe a un exceso de carga en el servidor de campus.chamilo.org.
Debido a que veo que estos ejercicios son relacionados con una empresa mayor, sugeriría contratar con un proveedor oficial de Chamilo (existe uno muy bueno basado en Perú - https://chamilo.org/providers ) en vez de depender de un portal gratuito para la comunidad de Chamilo.
