### ISSUE TITLE
Accès aux cours impossible

### ISSUE THREAD

**Issue by 3buzzz** [chamilo/chamilo-lms#3238]
Bonjour

j'utilise chamilo 1.11.10 sur debian, apache 2.4, fraîchement installé

Lorsque je crée un cours, j'ai une erreur 404 à la première tentative d'accès.

Le module rewrite est bien activé
les paramètres dans mon chamilo.conf d'apache correspondent bien à ce qui est demandé
*********************************
    Options +FollowSymlinks
    AllowOverride All
    Order allow,deny
    Allow from all
*********************************

Le fichier .htaccess semble bien lu, si je fais une redirection basique, elle fonctionne
RewriteRule .* https://github.com

J'ai l'impression que la redirection de courses vers app/courses n'est pas traitée.
RewriteRule ^courses/([^/]+)/(.*)$ app/courses/$1/$2 [QSA,L]

J'ai essayé de la placer en tête du .htaccess, rien ne change

Pour info, le fichier index.php à la racine du cours n'est pas créé mais une liste de dossiers (Documents, dropbox, exercices, etc)

Si j'en crée un manuellement, ça ne fonctionne pas quand même

Je ne sais plus ou chercher, avez vous une idée

Merci

**Comment by ywarnier** [comment]
Bonjour, s'il y a un répertoire "courses/" à la racine (ce qui est souvent un réflexe de débugging quand ça ne marche pas la première fois parce que rewrite n'est pas activé), cela peut fausser la logique (il ne considère plus qu'il y a une absence de courses/ et ne fait plus de redirection). Peut-être que c'est le problème ici?

**Comment by 3buzzz** [comment]
Bonjour

J'avais effectivement essayé cette solution, mais le répertoire "./courses" n'existe plus.

Ne peut il pas y avoir une erreur d'interprétation au niveau des regex de .htaccess ?

Si je crée un index.php à la racine du cours et que j'ajoute le répertoire "app" dans le chemin (/app/courses/TEST/index.php), j'accède bien au fichier.
N'y a-t-il pas un règle qui devrait m'en empêcher ?

Merci de votre écoute

**Comment by 3buzzz** [comment]
J'ai déplacé le répertoire 'chamilo' de /usr/share/ vers /var/www/ et ajusté mon default-ssl.conf

<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/chamilo
...
</IfModule>

<Directory "/var/www/chamilo">
  AllowOverride All
  Order allow,deny
  Allow from all
</Directory>
 
et tout fonctionne !!

Je n'ai pas bien compris pourquoi, je ne maitrise pas bien les virtual hosts.

Est ce qu'en faisant un fichier de conf spécifique dans conf-available (voir ci dessous), ça peut empêcher le fonctionnement des redirections ?

Alias /chamilo /usr/share/chamilo
<Directory /usr/share/chamilo>
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

**Comment by ywarnier** [comment]
Je ne suis pas moi-même certain de ce qui se passe en utilisant un Alias pour le répertoire, mais ce qui est certain c'est que nous recommandons plutôt l'utilisation de sous-domaines que de sous-répertoires. Les sous-répertoires sont prônes à des problèmes plus complexes de configuration et ne permettent pas un contrôle aussi fin, justement au niveau des VirtualHost et peuvent introduire des problèmes de partage de cookies entre applications (ce qui représente une vulnérabilité) si pas bien configurés contre ça.

Le fait d'avoir son VirtualHost dans un fichier spécifique dans conf-available/ ne change rien à ça. Nous utilisons des serveurs avec des dizaines de fichiers dans conf-available, et aucun problème. Par contre, nous n'utilisons pas Chamilo comme sous-répertoire d'un domaine. Toujours comme sous-domaine.

**Comment by ywarnier** [comment]
Je clôture cette issue, qui semble plutôt un aléa de configuration spécifique qu'un problème intrinsèque de Chamilo. Cela dit, pour moi, il n'y a aucun problème à le mettre dans /usr/share/chamilo, du moment que le DocumentRoot et le <Directory> pointent vers ce répertoire et que celui-ci permet l'accès à l'utilisateur du serveur web (www-data, httpd ou nobody, c'est selon...)

**Comment by 3buzzz** [comment]
Bonjour

Merci beaucoup pour votre suivi et vos éclaircissements. Je vais
approfondir mes connaissances des sous domaines...


Le mar. 19 mai 2020 à 03:06, Yannick Warnier <notifications@github.com> a
écrit :
