### ISSUE TITLE
Integración de GeoGebra con Chamilo

### ISSUE THREAD

**Issue by aleran** [chamilo/chamilo-lms#3243]
Saludos, Quisiera saber si hay alguna forma de integrar GeoGebra, o si no la hay sugerir esta funcionalidad ya que aporta muchas actividades para matemáticas

**Comment by ywarnier** [comment]
Al parecer las actividades de Geogebra soportan LTI. No lo hemos probado pero existen conversaciones sobre el tema fácilmente encontrarles con un motor de búsqueda corriente en Internet.
El software geogebra en sí no se puede integrar en Chamilo porque tiene una licencia personalizada que no es compatible con la de Chamilo

**Comment by ywarnier** [comment]
Me olvidé comentar que Chamilo también soporta LTI. Existe un plugin para activar el soporte de LTI
