### ISSUE TITLE
Error en generación de certificados en campus.chamilo.org

### ISSUE THREAD

**Issue by andreagra** [chamilo/chamilo-lms#3247]
URGENTE ESTE ERROR LLEVA 20 DÍAS POR FAVOR
En la opción de evaluaciones cuando hago clic en la lista de certificados sale el siguiente error: Esta página no funciona campus.chamilo.org no puede procesar esta solicitud en este momento.
HTTP ERROR 500
Lo cual significa que es un error del servidor

Cómo reproducir
Pasos para reproducir el problema:
(En el campus virtual de Chamilo)

Ir a Evaluaciones
Dar clic en Lista de Certificados
Ver el error que dice: Esta página no funciona campus.chamilo.org no puede procesar esta solicitud en este momento.
HTTP ERROR 500'
Comportamiento esperado
Se esperaría poder acceder a todos los certificados de los alumnos en el curso, y poder generar los pendientes.

Capturas de pantalla

Escritorio (por favor completa la información siguiente lo mejor posible):

Sistema operativo : Windows 10
Navegador: En todos los navegadores sale el mismo error
**Servidor

Sistema operativo : Windows 10
Versión de Chamilo: Chamilo Campus
Versión de PHP:

**Comment by ywarnier** [comment]
Hola @andreagra 

Creo que estás confundido. Esta aplicación es para reportar inconvenientes a la comunidad de desarrollo de Chamilo. En ninguna manera se trata de un soporte para problemas con los cuales te enfrentas. Recuerda que campus.chamilo.org es una plataforma entregada gratuitamente a la comunidad de Chamilo, que no debería ser usada para casos críticos. Por tu primera frase en mayúsculas, entendemos que es urgente para ti su resolución. Si es así, solo podemos suponer que le estás dando un uso crítico a tu curso. Si deseas una plataforma con un adecuado servicio de soporte con tiempos de respuesta cortos, te invitamos a contratar los servicios de algún proveedor oficial de servicios de Chamilo en https://chamilo.org/providers.

De lo contrario, gracias, hemos registrado el problema y lo estaremos revisando cuando nos de tiempo para hacerlo.
