### ISSUE TITLE
URGENT HELP PLEASE, GENERATION OF CERTIFICATES IS NOT WORKING

### ISSUE THREAD

**Issue by andreagra** [chamilo/chamilo-lms#3248]
THIS MISTAKE HAS BEEN PRESENTED FOR MORE THAN 20 DAYS
When I try to generate the certificates of a course in Evaluations, in the option: view list of certificates the following mistake appears: This page is not working campus.chamilo.org cannot process this request in this moment. HTTP ERROR 500
That means it is a server error

How to reproduce the problem:
(Go to campus.chamilo.org )

Go to Evaluations
Clic on the option "View list of certificates"
The error will appear: This page is not working campus.chamilo.org cannot process this request in this moment. HTTP ERROR 500

Expected behaviour:
I should be able to generate the student's certificates from each course but I am not achieving it.

Sistema operativo : Windows 10
Browser: The mistake appears in EVERY BROWSER

Sistema operativo : Windows 10
Versión de Chamilo: Chamilo Campus
Versión de PHP:

**Comment by ywarnier** [comment]
Already reported in #3247 
This is NOT a proper way to file an issue.
