### ISSUE TITLE
Delete the user folder when deleting a user

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3256]
When deleting a user, the UserManager::delete_user() method is used, and although it does delete the user pictures, it does not delete the user *folder*, which can lead to increased space usage in heavily used portals or in portals where users upload a lot of media.

Modify the delete_user() method to delete the user folder.

https://github.com/chamilo/chamilo-lms/blob/b578a4f069439dc6bf28cba4c4af5d81ffafbab3/main/inc/lib/usermanager.lib.php#L1016-L1024

The following script (now in tests/scripts/ for those having the Git version) does this (from the command line) for user folders that were left after deletion (for older portals), only in the case where the split_users_upload_directory option was set to true:
```
if (PHP_SAPI != 'cli') {
    die('This script can only be executed from the command line');
}
require_once __DIR__.'/../../main/inc/global.inc.php';
$userFolder = $_configuration['root_sys'].'app/upload/users/';
$usersIds = [];
$sql1 = "SELECT id FROM user";
$res1 = Database::query($sql1);
while ($row1 = Database::fetch_array($res1)) {
    $usersIds[$row1['id']] = true;
}
$list = scandir($userFolder);
foreach ($list as $directory) {
    $directory = trim($directory);
    if (substr($directory, 0, 1) == '.') {
        continue;
    }
    if (intval($directory) != $directory) {
        continue;
    }
    echo $userFolder.$directory."\n";
    $subList = scandir($userFolder.'/'.$directory);
    foreach ($subList as $subDirectory) {
        $subDirectory = trim($subDirectory);
        if (substr($subDirectory, 0, 1) == '.') {
            continue;
        }
        if ($subDirectory == 'my_files') {
            continue;
        }
        $fullDirectory = $directory.'/'.$subDirectory;
        if (!empty($usersIds[$subDirectory])) {
            echo "User ".$subDirectory." exists\n";
        } else {
           //echo "User ".$directory." does not exists\n";
            $thisUserFolder = $userFolder.$fullDirectory;
            //echo "Folder exists but user has been deleted: ".$thisUserFolder."\n";
            echo "rm -rf $thisUserFolder\n";
            exec("rm -rf ".$thisUserFolder);
        }
    }
}

```

**Comment by AngelFQC** [comment]
The `tests/scripts/delete_old_users_folder.php` script doesn't remove the `my_files` directory. I assume it is because the user can insert these files (like images) in HTML documents for courses, but there is also the folder of the attached files that the user sent. Both directories (`my_files` and `message_attachments`) are not removed.

**Comment by ywarnier** [comment]
They should be removed too.
When a user is deleted, it makes sense to delete all of its personal content.

**Comment by ywarnier** [comment]
Could you update your commit *and* the script to delete the my_files and message_attachments files too?

**Comment by AngelFQC** [comment]
> Could you update your commit _and_ the script to delete the my_files and message_attachments files too?

Done

**Comment by ywarnier** [comment]
Tested and approved.
