### ISSUE TITLE
Assignment with file only upload error

### ISSUE THREAD

**Issue by ejimor** [chamilo/chamilo-lms#3257]
i get this error message from error log when trying to rate and correct assignment that has the files upload file type selected for assignment but when i use text only error is not there, please i need help on what to do.

[15-May-2020 18:07:45 UTC] PHP Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/deltacar/public_html/elearning/main/work/work.lib.php:143
Stack trace:
#0 /home/deltacar/public_html/elearning/main/work/view.php(10): get_work_data_by_id(261)
#1 {main}
thrown in /home/deltacar/public_html/elearning/main/work/work.lib.php on line 143

**Comment by ywarnier** [comment]
Hi @ejimor 
My method to answer you:
* Go to https://www.php.net/mime_content_type (the name of the function that PHP tells you is "undefined")
* go back up one level in the hierarchy (see breadcrumb navigation) to get to https://www.php.net/manual/en/book.fileinfo.php
* there you can see it is part of a PHP extension called "fileinfo"
* the rest is a bit more complicated: the documentation/dependencies.html file *now* indicates fileinfo as a requirement, but this was done recently (in commit affe0b799d61ec0e183423be1ade1d208990a906 to be precise), as we had previously not realized this was not installed by default (and it only affect subsections of Chamilo)

So, as answer, please install the php-fileinfo extension. You seem to be using something like CentOS, so something like "yum install php-fileinfo" should do...

**Comment by ywarnier** [comment]
Feel free to re-open if this doesn't fix your issue.
Don't forget to restart your webserver after installing php-fileinfo.

**Comment by ejimor** [comment]
thanks for your reply, missing fileinfo was actually the problem but it has
been fixed
