### ISSUE TITLE
Error 404 al crear un documento dentro de una lección

### ISSUE THREAD

**Issue by regredu79** [chamilo/chamilo-lms#3258]
**Describe el problema**
Toda la plataforma me funciona correctamente, creación de usuarios, cursos, lecciones, ejercicios, encuesta, etc., pero al crear un DOCUMENTO dentro de la lección... una vez que creo el contenido, al momento de presionar el botón "CREAR DOCUMENTO", me da error 404.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'LECCIONES CREADAS'
2. Dar clic en 'CREAR DOCUMENTO'

al rastrear el error 404, la rutá que intentó seguir al presionar el botón es:

https://ferojeda.com/edu/main/lp/lp_controller.php?cidReq=001&id_session=0&gidReq=0&gradebook=0&origin=&action=add_item&lp_id=1&path_item=&view=&id=

**Comportamiento esperado**
Que se cree el documento.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/63536276/82177540-5e726a00-989f-11ea-8e20-6ddd3f846559.png)

Las funciones crear texto, lección, etc.... todas funcionan.

Tampoco funciona al intentar crearlo desde DOCUMENTOS, sin entrar a lecciones.
![image](https://user-images.githubusercontent.com/63536276/82179432-f07c7180-98a3-11ea-8f91-27675d67aa91.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10/ MAC (pc de usuario administrador)
 - Navegadores Chrome, Edge

**Servidor
 - Sistema operativo : Linux  
    Cpanel:86.0 (build 20)
    Apache 2.4.43
    PHP 7.0.33
  
 - Versión de Chamilo:  1.11.10  

**Contexto adicional**
(considerar que en el mismo hosting tengo, en diferentes directorios, 2 instalaciones de Chamilo, en el otro, todo va bien, mientras que en este, se da ese único fallo)

**Comment by ywarnier** [comment]
El error 404 significa que no se encontró la página. En el caso de la herramienta de documentos, no hay ninguna redirección así que si te sale un 404, significa que no encuentra el script (en el caso de la creación directa desde la herramienta de documentos, se trata de main/document/create_document.php). Podrías verificar que este script efectivamente está en la carpeta?
Hemos visto anteriormente que, cuando se suben archivos por FTP, pueden haber pérdidas en el proceso. Por eso es importante verificar la existencia del archivo. En todo caso, acabo de probar en una instalación de Chamilo y me funciona bien sin error 404.
Te recomiendo a parte comparar el listado de archivos en main/document/ dentro de este portal y dentro del otro portal que sí te funciona, porque quizás tengas ahí otros archivos faltantes.
Si se trata de una instalación en producción y crítica, habrá que hacer una comparación de *todos* los archivos en main/, src/, y app/Resources/, porque podrías tener más sorpresas malas ahí...

**Comment by regredu79** [comment]
Muchas gracias por tu respuesta y me disculpo por la demora (temas de la emergencia sanitaria).

Revisando tus sugerencias, te comento:
1)
"main/document/create_document.php). Podrías verificar que este script efectivamente está en la carpeta?"
>>REVISADO, EL ARCHIVO SI EXISTE.  LO ADJUNTO (CONVERTIDO A TXT) EN CASO LO REQUIERAS.

2)
"cuando se suben archivos por FTP, pueden haber pérdidas"
>>EN MI CASO TENGO 4 CHAMILO INSTALADOS, TODOS POR SOFTACULOS DIRECTO EN MI HOSTING.  NO HE INSTALADO POR FTP

3)
"te recomiendo comparar el listado de archivos en main/document/"
>> HE COMPARADO EL DETALLE DE ARCHIVOS EN ESTA CARPETA:
    - CHAMILO con FALLO:  34 archivos, seguridades en 0644
    - CHAMILO OK:              34 archivos, seguridades en 0644

4)
"habrá que hacer una comparación de todos los archivos en main/, src/, y app/Resources/,"

main/:                   54 carpetas y 1 archivo,  TODO IGUAL en ambos
src/:                      Ambos tienen solo la carpeta chamilo/
                             Dentro de chamilo/     14 capetas  (no se si requiera revisar el contenido de todas)
app/Resources/:   Igualmente revisé 3 niveles de carpetas, todo igual en ambos,
                             Archivos no hay hasta ese nivel.



Como puedes ver, al parecer todo está igual en los dos,  mi única diferencia en estas 2 plataformas instaladas es que la una está en un nivel de directorios diferente a la otra.  Me explico:
Cuando contrato el hosting (CLUBACTIVADOS), pido en el 2 dominios, y me entregan el uno en la raiz (OK) y el otro dentro del la carpeta public html (FALLO):

FALLO:  home/clubactivados/upgrader-team.com/edu/
OK:        home/clubactivados/public_html/ferojeda.com/edu

Si no me equivoco en un issue anterior hace un tiempo, en este u otro portal, no podía insertar imágenes y me guiaron para cambiar en un archivo html, para redirigir la selección a la subcarpeta y no a la raiz, y funcionó?

Será que en algun otro archivo debo aplicar la misma solución?  Cómo saber en cuál?

Muchas gracias por su ayuda.



[create_document.txt](https://github.com/chamilo/chamilo-lms/files/4690889/create_document.txt)

**Comment by ywarnier** [comment]
Hola @regredu79 
En el archivo app/config/configuration.php,verifica que el parámetro root_sys esté configurado correctamente (incluyendo el "public_html"). Si este portal es una copia del otro, puede que en realidad esté buscando archivos en la otra carpeta.

**Comment by estefany51** [comment]
Buenos días, yo recién estoy manejando Linux (este caso Rocky 9) y me sale el mismo error, pero no sé a qué dirección debo ir o qué revisar para solucionar ese problema. si alguien me pudiera ayudar por favor. 
![Captura de pantalla (203)](https://github.com/chamilo/chamilo-lms/assets/140168845/d19d8001-12b6-4c22-b72e-e4b8105a47f6)
