### ISSUE TITLE
No me permite configurar la foto de perfil de los usuarios

### ISSUE THREAD

**Issue by afromerot** [chamilo/chamilo-lms#3260]
**Describe el problema**
La plataforma funciona muy bien, pero al subir la foto de perfil en los roles de profesor y estudiante y poner guardar cambios esta no se muestra en la plataforma, he intentado configurarla tanto en perfil personal y de administración y no aparece, la única cuenta que permitió configurar la imagen fue la del administrador

**Cómo reproducir**
EL paso a paso que estoy realizando para configurar la foto es:
- en el rol de administración ingreso a lista de usuarios
- editar la información de usuario
- agregar imagen
- Recortar 
- Guardar cambios
- No se muestra la imagen seleccionada

**Comportamiento esperado**
Que se muestre la imagen de perfil tal como se logro con la cuenta principal de administrador

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/65642763/82406026-34e64980-9a2b-11ea-8128-7af904e02b79.png)
![image](https://user-images.githubusercontent.com/65642763/82406040-3dd71b00-9a2b-11ea-922b-743ded233421.png)
![image](https://user-images.githubusercontent.com/65642763/82406049-4596bf80-9a2b-11ea-96b9-dedfea948160.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : macOS Catalina
 - Navegador: Chrome

**Servidor
- 
 - Versión: Chamilo 1.11.10
 - Versión de PHP: 7.0.33

Agradezco la ayuda de la comunidad

**Comment by ywarnier** [comment]
Sin validar nada todavia, te comento que la versión 7.0 en particular tiene problemas y no la soportamos. Si tienes la posibilidad de pasar a 7.2, por ejemplo, sería ideal para evitar falsos negativos y buscar mucho más para algo que al final solo sería (potencialmente) la versión de php.
En todo caso, las fotos se guardan en la carpeta app/upload/users/ dentro de Chamilo, así que tienes que asegurarte que esta carpeta permita escritura por el servidor web, pero en principio si lo hace para algunos usuarios, debería hacerlo para otros.

**Comment by cahewi** [comment]
tengo el mismo problema, lograste solucionar, y como lo hiciste ayúdame por favor

**Comment by ywarnier** [comment]
@cahewi si das clic para obtener la URL de la imagen rota, qué diferencia hay entre ella y la URL de la página de lista de usuarios? Algo debe estar mal en las URLs o en la librería de conversión de imágenes para que resulte así.

**Comment by afromerot** [comment]
Hola Cahewi, yo gracias a la ruta que me dio ywarnier entre al administrador de archivos y busque las imagenes, es un tema de permisos, le cambie manualemente la configuración basandome en la configuración que me servia que era la del administrador, si mal no recuerdo 755 esto me funciono y mostro la imagen pero aun tengo el problema de que siempre que se cree un usuario debo cambiarle estos permisos manualmente y no lo hace el sistema automaticamente.

Espero te ayude y quedo atento a tu solución y si encuentras la manera de arreglarlo de raiz

**Comment by cahewi** [comment]
Gracias por su tiempo a cada uno de ustedes el chamilo esta instalado en Ubuntu y VPS ya lo di permiso y nada, varias semanas estoy con este problema

**Comment by ywarnier** [comment]
@cahewi no respondes a mi pregunta

**Comment by chininguitar** [comment]
SOLUCION(en mi caso)... Cambiar los permisos a la carpeta "app/upload/users" , setearlo como 755, y q este cambio afecte a todas las carpetas contenidas en esta carpeta. Pero el cambio es solo a las carpetas, NO a los archivos(los archivos tienen otro permiso). La forma mas facil de cambiar a todas las carpetas, es haciendolo desde FTP(Mozilla), ya q te d mas opciones como la de elegir hacerlo para todas las carpetas dentro.En mi Cpanel no me permitia hacerlo a todas en una sola vez. Saludos de Peru.
