### ISSUE TITLE
Lentitud para generar archivos ZIP desde el modulo de tareas

### ISSUE THREAD

**Issue by uft-dti** [chamilo/chamilo-lms#3263]
He detectado cuando se ejecutan procesos donde se generan archivos comprimidos, por ejemplo work/downloadfolder.inc.php, no se ve un alto uso de CPU.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Estar con perfil de profesor
2. Ira a un curso que contenga tareas resueltas con archivos adjuntos
3. hacer click en tareas
4. en la lista de tareas hacer click en el icono de guardar

**Comportamiento esperado**
Si realizo el zip por linea de comando en el servidor web se demora menos de 30 segundos en generar el zip, ejecutandolo por web se demora cerca de 5 horas
 
**Capturas de pantalla**
https://drive.google.com/file/d/1KDaL_rWlkRqyjlO4tspPq70vinO76n6n/view?usp=sharing

Navegador Chrome Versión 83.0.4103.61 (Build oficial) (64 bits)

**Servidor
características de cada uno de los 5 nodos
vps Centos 7 sobre vcenter
16 CPU
16 GB ram
Disco SSD
Apache 2.4
Con OpCache activado
Php versión 7.4 (también probe con 7.0 al 7.3)
Chamilo 1.11.10

No existe sobre demanda de CPU o de RAM

**Contexto adicional**
https://forum.chamilo.org/viewtopic.php?f=15&t=11201&p=37059#p37059

**Comment by ywarnier** [comment]
El foro es el lugar adecuado para conversar de esto. No veo problema ninguno en nuestros sistemas. Asegúrate que el aplicativo zip esté instalado en el servidor. Si no lo está, Chamilo usará el aplicativo PCLZip que puede ser mucho más lento.
