### ISSUE TITLE
Encuesta

### ISSUE THREAD

**Issue by jalopezte** [chamilo/chamilo-lms#3266]
**Describe el problema**
Como profesor realice una encuesta para que mis estudiantes la diligenciaran pero aparece el siguiente mensaje "Se ha producido un error. Por favor, consulte con el administrador del sistema"

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'encuestas'
2. Dar clic en 'en el nombre de la encuesta'
3. Bajar hasta 'empezar encuesta'
4. Ver el error que dice 'Se ha producido un error. Por favor, consulte con el administrador del sistema'

**Comportamiento esperado**
Que los estudiantes pudieran hacer la encuesta propuesta

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/48501877/82753574-43ff2b80-9d8c-11ea-959a-4f01fa757c12.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador chrome, versión 81.0.4044.138 (Build oficial) (64 bits)

**Servidor
 - Sistema operativo : Windows 10
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
@jalopezte en preparación para la versión 1.11.12 hemos hecho muchos ajustes en la herramienta de encuestas. Como no podemos reproducir el problema reportado, suponemos que en realidad ya ha sido corregido. Si deseas estar seguro, puedes crear cuentas, cursos y encuestas en nuestro espacio de validación https://11.chamilo.org/ y reportar si es que sigue sin funcionar, pero sino, cerraremos este reporte dentro de 7 días
