### ISSUE TITLE
Las categorías no seleccionan todas las preguntas asignadas

### ISSUE THREAD

**Issue by lopezsalexander** [chamilo/chamilo-lms#3268]
Al momento de hacer un ejercicio (Exportado desde Aiken, Excel o pregunta a pregunta) creo las respectivas categorías y le asigno a cada pregunta su respectiva categoría, pero en las opciones avanzadas, al poner la cantidad de preguntas que deben ir en el ejercicio desglosadas por categoría, estas no se reflejan y los puntajes se descuadran.

**Pasos para reproducir el problema**

1. Ir a Ejercicios
2. Crear un ejercicio con varias categorías, [Aquí un ejemplo](<https://www.dropbox.com/scl/fi/4wna7y64vxxi12dpomhld/Prueba.xls?dl=0&rlkey=26fdjaooy205j3lmjor5gr6k4>)
3. Modificar el ejercicio e ir a Parámetros Avanzados
4. En **Selección de preguntas** seleccionar cualquier opción bajo el menú de Usando Categorías
5. Organizar la cantidad de preguntas que deben ir por categoría, en este caso 
![Captura de pantalla de 2020-05-26 23-48-26](https://user-images.githubusercontent.com/5233755/82978966-7cc91b80-9fab-11ea-8cc2-1b47e92397e5.png)
6. Guardar los cambios
7. Realizar el ejercicio y verificar si están todas las preguntas asignadas.

**Comportamiento esperado**
Al momento de mostrar las preguntas en el ejercicio, debe mostrar la cantidad de preguntas asignadas para cada categoría, sin embargo no lo hace y por ende no calcula bien los puntajes.

**Capturas de pantalla**

Aquí calculando mal los puntajes de la prueba (Debería dar 100)
![Captura de pantalla de 2020-05-27 00-00-52](https://user-images.githubusercontent.com/5233755/82979714-5efcb600-9fad-11ea-9f08-366be6c3296a.png)

Al final del ejercicio, debería mostrar 25 preguntas que se configuraron, y solo muestra 19
![Captura de pantalla de 2020-05-27 00-01-56](https://user-images.githubusercontent.com/5233755/82979744-763ba380-9fad-11ea-8e83-913311e8100d.png)

**Servidor**
 - Sistema operativo : Linux Ubuntu 18.04.4
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 7.2.24
 - Version base de datos: 1.11.0.6

**Comment by ywarnier** [comment]
Seems slightly related to #3265

**Comment by carlangas159** [comment]
Hola @lopezsalexander,

Te agradesco el archivo de ejemplo que nos falicistaste, he intentado reproducirlo en 11.chamilo.org, en el siguiente enlace 
[https://11.chamilo.org/courses/CURSO5CATEGORIAS/](https://11.chamilo.org/courses/CURSO5CATEGORIAS/)  sin embargo observo que la cantidad de preguntas esta ajustado a los numeros que he colocado 
![image](https://user-images.githubusercontent.com/18097392/88436343-b65ead00-cdc9-11ea-8358-694da806a71f.png)

para facilitar observar las preguntas las he colocado todas en la misma pantalla.


tambien me fije en el monto total que debe dar, 
![image](https://user-images.githubusercontent.com/18097392/88436541-1ce3cb00-cdca-11ea-8911-eacba91d66a4.png)

Cargando el archivo que facilitaste, me da 100. 


¿Podrias tratar de replicar ese error en [https://11.chamilo.org](https://11.chamilo.org) ?

**Comment by ywarnier** [comment]
Es igual de mi lado: no llego a reproducir el error. Uso la misma configuración hecha por @carlangas159 en base a tu archivo @lopezsalexander .

Aquí se puede notar que estoy en la última pregunta con la pregunta 25:
![cat-ok](https://user-images.githubusercontent.com/609839/88489232-62072900-cf93-11ea-91ee-a885740c7656.png)

Aquí se ve que los resultados contant con las 5 categorías y que respondí 25 preguntas.
![cat-ok-2](https://user-images.githubusercontent.com/609839/88489234-64698300-cf93-11ea-923a-dd19bc0832e6.png)
Intenté con una pregunta por página y con todas las preguntas en la misma página. Todo bien en ambos casos.

Es probable que el problema que reportas haya sido corregido ya en el código de Chamilo "post-1.11.10", por lo que estoy cerrando esta tarea. Si deseas añadir alguna información relevante que nos permita reproducir el problema en la URL mencionada por @carlangas159 , no dudes en hacerlo.
