### ISSUE TITLE
Problemas Generación de Certificados

### ISSUE THREAD

**Issue by regredu79** [chamilo/chamilo-lms#3269]
COPIO HILO DE ISSUE REPORTADO EN UNA SECUENCIA DESDE EL 12 DE ABRIL, COMO ISSUE NUEVO.

Saludos a todos, por lo visto aun hay problemas en este tema de certificados.  Entiendo que algunos sean de configuracion....html al exportar, etc.  Pero en general en la herramienta EVALUACIONES, yo tengo 2 problemas:

2) No genera los certificados de forma automática a pesar de tener la configuración para hacerlo

En el archivo adjunto constan las pruebas realizadas y evidencias,

Versión actual que tengo: "Su versión está actualizada: Chamilo 1.11.10"

Gracias
[problemas evaluaciones.docx](https://github.com/chamilo/chamilo-lms/files/4466055/problemas.evaluaciones.docx)

[problemas evaluaciones.docx](https://github.com/chamilo/chamilo-lms/files/4466052/problemas.evaluaciones.docx)

_Originally posted by @regredu79 in https://github.com/chamilo/chamilo-lms/issues/2194#issuecomment-612581560_

**Comment by ywarnier** [comment]
Creo que @nosolored es la persona más adecuada para revisar esto, dado que se trata de su plugin, pero el correctivo no podrá ser parte de la 1.11.12.

**Comment by AngelFQC** [comment]
> Creo que @nosolored es la persona más adecuada para revisar esto, dado que se trata de su plugin, pero el correctivo no podrá ser parte de la 1.11.12.

En el archivo docx se indica que el plugin de certificado personalizado no está activo.

Pero lo que se indica en el documento, creo yo, es el procedimiento normal de Chamilo. Ya que el certificado se genera manualmente por el profesor del curso o cuando el estudiante ingresa a la herramienta de evaluaciones. En la página de "Mis certificados" sólo se muestra la lista de certificados generados pero ahí no se generan.

**Comment by nosolored** [comment]
Como comenta @AngelFQC los certificados solo se generan si el estudiante accede a evaluaciones o el profesor pulsa en generar certificados, ese comportamiento es el que hemos visto siempre en Chamilo.
Esto es independiente del plugin de certificado personalizado.

**Comment by regredu79** [comment]
Gracias a todos por su aporte,

Lo curioso es que en un lugar funcione diferente que en otro. en todo caso,
establecí como procedimeinto para el alumno que primero abra Evaluaciones y
desde ahi el certificado.

Roberto.

**Comment by AngelFQC** [comment]
> Como comenta @AngelFQC los certificados solo se generan si el estudiante accede a evaluaciones o el profesor pulsa en generar certificados, ese comportamiento es el que hemos visto siempre en Chamilo.

En lecciones, hay un tipo de documento que es "certificado" y genera un certificado de la categoría de evaluaciones en la que esté asignadad esa lección. El certificado se puede generar automáticamente cuando el usuario visualiza ese item de la lección, y claro, si esta lección está asociada a una evaluación.
