### ISSUE TITLE
iOS devices like iPhone - Registration and login pages are not aligned correctly

### ISSUE THREAD

**Issue by rajeekum** [chamilo/chamilo-lms#3270]
**Describe**
Use Apple iPhone and try to access homepage or sign-up page.
I see screen and texts are overlapping.

**To Reproduce**
1. Use Apple iPhone and try to access url:
https://<myapp>/index.php [Application Homepage]
https://<myapp>/main/auth/inscription.php [Application Sign-up]

I see screen and texts are overlapping.
4. See error: attached are screen shots.

**Expected behavior**
No overlapping of text and image. And Web Application should properly adjusted and aligned to work on iOS devices.

**Screenshots**
![IMG-20200526-WA0028](https://user-images.githubusercontent.com/55356819/82995571-63fb4d00-a021-11ea-9a50-8f35d5278285.jpg)
![IMG-20200526-WA0029](https://user-images.githubusercontent.com/55356819/82995640-76758680-a021-11ea-95c0-7a54f6ee3454.jpg)

**Desktop (please complete the following information):**
 - OS: iOS for iPhone
 - Browser: chrome, firefox, and safari

**Server
 - OS: Linux Ubuntu 18.04
 - Version of Chamilo: 1.11.10
 - Version of PHP: 7.2

**Comment by rajeekum** [comment]
@AngelFQC, Do we have fix for this ? Please let me know.

**Comment by ywarnier** [comment]
I can reproduce it on an iPad (in both FF and Safari)

**Comment by AngelFQC** [comment]
Hi @rajeekum 

Please make a test with the chages introduced by @carlangas159 in https://github.com/chamilo/chamilo-lms/pull/3430/files

**Comment by ywarnier** [comment]
To me (iPhone + Safari) it still looks like this (aligned but the radio button still appears), but this seems to be the best we can do with the current HTML structure, so let's leave it like this for now. Sorry we can't do it better for the very-soon-to-be-published 1.11.12

![ios](https://user-images.githubusercontent.com/609839/89658068-5c341080-d8ce-11ea-8468-f3ee5b54ab6b.jpeg)
![ios2](https://user-images.githubusercontent.com/609839/89658071-5ccca700-d8ce-11ea-8be5-76a41fcbf4b1.jpeg)
