### ISSUE TITLE
  error con scorm exe_learning en chrome ultimo

### ISSUE THREAD

**Issue by jlgac50** [chamilo/chamilo-lms#3271]
Hola a todos
ya lo he puesto en el foro de chamilo, tenia que haberlo puesto aqui primero, lo siento...
Desde la ultima actualización del navegador Chrome. hay un problema en la lectura de los scorm de exe_learning. No cuenta el tiempo dentro del scorm ni lo marca como realizado...
bien, la solución es que hay que cambiar dentro de la carpeta main/lp creo que en versiones antiguas es main/newscorm (yo utilizo una versión antigua, pero lo he testado en una versión actual y falla tambien):

aicc_api.php
documentapi.js
storageapi.js
lpcontroler.php
scorm_api.php

hay que cambiar todos los async: false "a" async: true

con esto se arregla el problema, o al menos se me ha arreglado a mi....

Disculpa pero no quiero alarmar. creo que es un problema generalizado ya que la ultima versión de chrome (con chrome digo chromium o sea también entrara Edge que es el navegador de microsoft) ha cambiado su forma de gestionar las peticiones. Seguramente ahora Chamilo este fallando en otras cosas. creo que este fallo va a traer de cabeza a mas de uno... no es solo el scorm el que esta fallando... hay mas de 120 variables async: en toda chamilo que hay que repasar y poner a true (cuidado, solo algunas)... por lo que he visto en FireFox va todo bien....
un fuerte abrazo y muchisimas gracias a vosotros. lamento no tener mas tiempo para ayudar mas....

**Comment by ywarnier** [comment]
Hola @jlgac50 efectivamente, la última versión de Chrome cambia unos comportamientos que afectan el soporte de Scorm de parte de Chamilo. Ya hemos aportado correcciones en la versión de desarrollo de Chamilo (ver enlaces anteriores a este mensaje) , que saldrán como parte de la versión 1.11.12 dentro de unas semanas.

**Comment by jlgac50** [comment]
genial, muchas gracias...
