### ISSUE TITLE
track_e_attempt table : size seems to be huge

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3273]
**Describe**
After just some weeks of use of my 1.11.10 platform, I'm very surprised about the track_e_attempt_table size (and c_quiz_question).
![Capture](https://user-images.githubusercontent.com/24507698/83331592-66ff7300-a297-11ea-96e7-d7e0635a17b6.JPG)

**Expected behavior**
Is there a way to reduce the size ? By changing the fields type ? "answer" and "teacher comment" are defined in long text  : would it be correct if i change it for "text" or "mediumtext"

**Additional context**
All my exercises include answers that are very short.

Thanks !

**Comment by tanchon** [comment]
Hi,

In my organization, I discovered that trainers never clean their results.

It is linked to a lack with the management of exam results : trainers don't have the possibility to easily backup the examsheets  (see #3264).

Tanchon.

**Comment by ywarnier** [comment]
c_quiz_question stores questions titles and descriptions in HTML. If teachers paste images in base64 in the questions, it increases considerably the space used in the table.
track_e_attempt stores all answers. If answers are with an existing answer option, only the id is stored, but if it is a free answer, the whole text of the answer is stored. As such, base64 images and that kind of thing can considerably increase used space.
I'm considering this issue closed as I see nothing strange here
