### ISSUE TITLE
Survey: Removing the last option in a question does not save the question title (minor)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3279]
- Create a survey
- Create a question (second type)
- Create 3 options
- Save
- Edit the question
- Change the question's text
- Change the first option's text
- Remove the last option (using the "Remove" button)
- The first option's change has been saved, but not the question title's change

**Comment by ywarnier** [comment]
Still valid issue, although now none of the buttons to remove an answer actually work.

**Comment by christianbeeznest** [comment]
Corregido en este PR https://github.com/chamilo/chamilo-lms/pull/4329

**Comment by ywarnier** [comment]
Checked and confirmed this is fixed. Thanks!
