### ISSUE TITLE
Agenda - Importando ICS queda con fechas erradas

### ISSUE THREAD

**Issue by cvnino** [chamilo/chamilo-lms#3280]
La agenda no permite personalizar mucho los eventos cuando son recurrentes. 
He realizado la prueba creando un evento de calendario, que es repetitivo todos los lunes del mes de Junio, genero el archivo ics y luego lo importo a la agenda global. El resultado da la misma cantidad de eventos pero en fechas erradas. Asi mismo lo hice un un ics descargado donde tengo todos los festivos de Colombia y al importarlo se coloca exactamente una dia anterior. 

**Cómo reproducir**
1. Descargar en formato ics los festivos de un pais, en mi caso Colombia
2. Importarlo a la agenda
3. Verificar que las fechas y los dias concuerden

**Comportamiento esperado**
Las fechas deben quedar el dia que es, la zona horaria esta correctamente configurada

![image](https://user-images.githubusercontent.com/66498781/83929579-8431b700-a759-11ea-88f6-504d89929870.png)

![image](https://user-images.githubusercontent.com/66498781/83929596-914ea600-a759-11ea-8491-87c177e6c75d.png)

**Comment by AngelFQC** [comment]
Parece ser un problema del propio archivo generado.

El formato para las fechas esperado por la librería `sabre/vobject` es algo como `DTSTART;TZID="America/Chicago":20111008T193000` y sin embargo el archivo de calendar tiene una fecha en formato `DTSTART;VALUE=DATE:20190801`

**Comment by cvnino** [comment]
Gracias Angel por tu respuesta! Con respecto a lo que mencionas veo que puntualmente el parámetro TZID no aplica para la zona horaria que me encuentro Bogota UTC y en vez de ese se usa DATE, acá te muestro lo que encontré al respecto:

The "TZID" property parameter MUST NOT be applied to DATE properties and DATE-TIME or TIME properties whose time values are specified in UTC.

Estoy haciendo el intento de simplemente crear un evento directamente en la agenda de Chamilo y luego exportarlo como un evento publico o privado, con el fin de ver el contenido; pero no obtengo el archivo, queda cargando caché y luego se refresca la pagina pero no descargo ningun archivo.

**Comment by cvnino** [comment]
Creo que ahora estoy comenzando a entender lo que me dices:
 
 DTSTART:19970714T133000            ;Local time
  DTSTART:19970714T173000Z           ;UTC time
  DTSTART;TZID=US-Eastern:19970714T133000    ;Local time and time
                     ; zone reference

Tome un archivo creado en mi calendario y modifique unicamente el valor DSTART como em indicaste, lo subi a Chamilo y lo creo bien en el dia que es, sin embargo, no solo hay que manipular ese parametro para que el evento se cree correctamente. Ya que no puedo generar mi archivo podrias copiar como debe ser una estructura con un archivo de ejemplo?

Ahora, no deberia entrar a entender la logica de la programacion ICS para lograr subir exitosamente un evento importando a Chamilo, valide la estructura del ics de este caso en esta pagina https://icalendar.org/validator.html y esta bien, ese mismo archivo lo importo en el calendario de mi celular, de una mac, hasta de outlook y funciona, pero no sirve para Chamilo

**Comment by ywarnier** [comment]
@cvnino nos podrías dejar aquí un ejemplo de ICS que falla?

**Comment by NicoDucou** [comment]
Lo acabo de probar con el ics que se decarga aqui : https://dias-festivos.co/festivos/colombia/
Lo importe en el agenda personal del usuario admin en https://11.chamilo.org/main/calendar/agenda_js.php?type=personal&
Los eventos estan en la fecha correcta : 
![image](https://user-images.githubusercontent.com/6579268/88030027-070ca680-cb3b-11ea-831b-9e267b13f467.png)

**Comment by cvnino** [comment]
> @cvnino nos podrías dejar aquí un ejemplo de ICS que falla?

Claro, el archivo ICS con el cual intenté esta adjunto en el caso, pero este es el contenido:

BEGIN:VCALENDAR
VERSION:2.0
PRODID: https://dias-festivos.co/
METHOD:PUBLISH
CALSCALE:GREGORIAN
NAME:Festivos Colombia 2020
X-WR-CALNAME:Festivos Colombia 2020
DESCRIPTION:
X-WR-CALDESC:
BEGIN:VEVENT
UID:colombia--2020-1@dias-festivos.co
DTSTAMP:20200101T000000
DTSTART;VALUE=DATE:20200101
DTEND;VALUE=DATE:20200101
SUMMARY:Año Nuevo 
DESCRIPTION:festivo nacional en Colombia | dias-festivos.co. All data without guarantee! / Alle Angaben ohne Gewähr!
STATUS:CONFIRMED
END:VEVENT
BEGIN:VEVENT
UID:colombia--2020-2@dias-festivos.co
DTSTAMP:20200106T000000
DTSTART;VALUE=DATE:20200106
DTEND;VALUE=DATE:20200106
SUMMARY:Día de los Reyes Magos 
DESCRIPTION:festivo nacional en Colombia | dias-festivos.co. All data without guarantee! / Alle Angaben ohne Gewähr!
STATUS:CONFIRMED
END:VEVENT
................................
Contenido borrado para evitar que el mensaje sea muy largo
..............................
BEGIN:VEVENT
UID:colombia--2020-19@dias-festivos.co
DTSTAMP:20201225T000000
DTSTART;VALUE=DATE:20201225
DTEND;VALUE=DATE:20201225
SUMMARY:Navidad 
DESCRIPTION:festivo nacional en Colombia | dias-festivos.co. All data without guarantee! / Alle Angaben ohne Gewähr!
STATUS:CONFIRMED
END:VEVENT
END:VCALENDAR

**Comment by cvnino** [comment]
> Lo acabo de probar con el ics que se decarga aqui : https://dias-festivos.co/festivos/colombia/
> Lo importe en el agenda personal del usuario admin en https://11.chamilo.org/main/calendar/agenda_js.php?type=personal&
> Los eventos estan en la fecha correcta :
> ![image](https://user-images.githubusercontent.com/6579268/88030027-070ca680-cb3b-11ea-831b-9e267b13f467.png)

Es exactamente lo que hago, pero no me queda bien en la agenda. Incluso yo misma creo un evento en mi portátil y lo subo pero continua quedando al día siguiente. Voy a intentarlo en un sitio de prueba y seguir haciendo pruebas. Alguna sugerencia adicional?  la zona horaria? estoy trabajando con multiurl, no tiene porque afectar pero se puede sumar a las variables adicionales. 

Gracias por los aportes

**Comment by ywarnier** [comment]
@cvnino Las multi-url no deberían afectar. Hay varios lugares donde se puede configurar la hora:
* el servidor (si es Linux, ver con el comando "date" y configurar con tzdata o timedatectl)
* la configuración date.timezone de PHP (en php.ini o el vhost de apache)
* la configuración global de la plataforma en Chamilo (opciones de zonas horarias en los parámetros de configuración)
* la configuración personal de zona horaria (si es activada por el administrador)

Cada uno de estos puede influir sobre tu configuración final. En principio los últimos tienen más importancia para Chamilo que los primeros.
