### ISSUE TITLE
No puedo crear reunión con bigbluebutton despues de cambiar de servidor

### ISSUE THREAD

**Issue by cocaco-dev** [chamilo/chamilo-lms#3281]
Tengo chamilo version 1.11.10 funcionando con un servidor bigbluebutton 2.2, todo funcionaba perfectamente hasta que decidí cambiar de servidor de bbb por uno con mas caracterisiticas de hardware. Cuando se realizó el cambio, se uso el mismo dominio solo que con diferente IP del nuevo servidor. Pero ahora el Chamilo cuando crea reuniones, al entrar al enlace se queda cargando en una página blanca y el chamilo se vuelve lento por unos momentos. Primero pensé que era problema del servidor BBB nuevo, pero instalando sus apis de prueba funciona perfectamente.
Alguien que haya tenido este problema?? ya busqué en todos lados pero no encuentro la solución.

les dejo el enlace del resultado de bbb-config --debug [Debug BBB](https://gist.github.com/cocaco-dev/88f9351ae38cb6bd282e6199af2f90b1)

**Comment by aragonc** [comment]
Cuando hiciste el cambio de ip al dominio esperaste al menos 24horas para que se actualicen las dns a esa nueva ip de tu servidor nuevo, porque parece que aun el dominio este apuntando a la otra ip por eso el chamilo se pone lento, me ha pasado eso cuando no encuentra respuesta de la ip

**Comment by cocaco-dev** [comment]
Ya lo resolví, en el archivo /lib/systemd/system/bbb-web.service  modificar la línea LimitNOFILE de 1024 a lo que necesites y probema resuelto!

**Comment by orlynk** [comment]
Hola Amigos . Alguien podria ayudarme ...tengo instalado chamilo 1.11.10 y un servidor bbb cuando lo integro en chamilo siempre me lanza un error cundo trato de iniciar video conferencia:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

no se si alguien pueda ayudarme casi no tengo experiencia con esto
