### ISSUE TITLE
Paypal Commission

### ISSUE THREAD

**Issue by Leonardolms** [chamilo/chamilo-lms#3287]
Hello @ywarnier @jmontoyaa ,

I am testing a Chamilo commission feature, and when adding the payee, it appears that no Paypal account was found. Where do I set up the Paypal account of the beneficiaries on the platform?

![image](https://user-images.githubusercontent.com/66574858/83981453-44530700-a8f4-11ea-93d9-1a865cbf6778.png)

Chamilo Version:  1.11.10
Server: Linux

Sincerely.

**Comment by ywarnier** [comment]
The account you set as payee (email address) has to exist on PayPal. The plugin should check by itself, with PayPal...

**Comment by Leonardolms** [comment]
Does the beneficiary's account have to be only with CNPJ or can it only be CPF (personal)?
