### ISSUE TITLE
Static plugin cuts texts

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3289]
**Describe**
Static module cuts the html content.

**To Reproduce**
enable static plugin.
Enter large text atleast 300.
Save and part of it gets cut.

**Expected behavior**
When saved the full content created with ckeditor to be visable and saved.

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser: chrome

**Server
 - OS: centos 10
 - Version of Chamilo:  1.11.x  updated from github
 - Version of PHP: 7.3

**Additional context**
Tried to trouble shoot it my self can't figure it out. I suspect quickform cuts it somewhere but unsure why or where.
There is also no consitancy to it its not like its cutting at exactly xx char or xx lines or xx tags.

**Comment by AngelFQC** [comment]
Related to #3188

**Comment by spacecabbie** [comment]
Alrighty thats quite helpfull sad i was looking completly wrong direction. I have no clue how that impacts the plugin but oh wel lots to learn.
Should i close this btw ?
Ps. is there an updated eta for chamilo2 ? I belive it was due for around may ?

**Comment by ywarnier** [comment]
Hi @spacecabbie yes, if you believe the notes have helped you find an answer to your question or a fix to the issue, then please close it (I will do that for you here). Ideally, make sure you explain clearly what the solution was in your case, so others searching issues can benefit.
Chamilo 1.11.12 should be released (hopefully) around early July.
Chamilo 2.0 is only probably going to be released by the end of 2020.
