### ISSUE TITLE
Getting warning every time creating a test

### ISSUE THREAD

**Issue by iftekhar90** [chamilo/chamilo-lms#3306]
**Describe**
I am getting this warning everytime I try creating a test or add a question. I can't log out or delete the test when this happens. Matching question doesn't work as well.

Warning: Declaration of Matching::return_header($exercise, $counter = NULL, $score = NULL) should be compatible with Question::return_header(Excercise $exercise, $counter = NULL, $score = Array) in /home3/iftekhar/public_html/lms/main/exercise/matching.class.php on line 16

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home3/iftekhar/public_html/lms/main/exercise/matching.class.php:16) in /home3/iftekhar/public_html/lms/main/inc/lib/chamilo_session.class.php on line 98
Help

**To Reproduce**
Go to 'https://aukkhor.com/lms/main/exercise/admin.php?cidReq=ENGLISH1STPAPER&id_session=0&gidReq=0&gradebook=0&origin='

**Expected behavior**
i believe it supposed to just create the test and not show any warning, log out function should work

.

**Screenshots**
![warning 1](https://user-images.githubusercontent.com/67021902/84828299-ab389480-b047-11ea-94d8-0c05aeecbdb6.jpg)

**Desktop:**
 - Windows 10
 - Chrome

**Server**
 - OS: Linux
 - Version of Chamilo:  1.11.10
 - Version of PHP: 5.4.45

**Comment by jmontoyaa** [comment]
That was already fixed here:

https://github.com/chamilo/chamilo-lms/commit/f6b16777cae4ed42b10a023def7594046b8910e2

**Comment by ywarnier** [comment]
If your version of PHP is really 5.4, you should have bigger eggs to fry, my friend. Support ended like in 2007 or something like that... And Chamilo 1.11 doesn't support officially under 5.6
