### ISSUE TITLE
Export de vcard non-fonctionnel

### ISSUE THREAD

**Issue by meuhland** [chamilo/chamilo-lms#3309]
Depuis le commit https://github.com/chamilo/chamilo-lms/commit/76fbb2b8799510136c8502bb6e1e6e333f065819

Il est impossible pour users non admin de télécharger les "Cartes de visite" via le page sociale.
main/social/home.php

Je cherche à comprendre pourquoi en amont ce n'est pas bloqué si jamais il y a une raison valable pour mettre "api_protect_admin_script()" dans le php.

**Comment by ywarnier** [comment]
En effet, ça n'a pas beaucoup de sens de le limiter exclusivement aux admins, mais il faudrait tout de même la protéger contre tous ceux qui n'ont pas accès au "profil partagé" de l'utilisateur (tous ceux qui ne sont pas amis sur le réseau social), de telle sorte qu'on ne publie pas à tous vents l'e-mail de l'utilisateur.

Je note que le changement précis qui gène, c'est https://github.com/chamilo/chamilo-lms/commit/76fbb2b8799510136c8502bb6e1e6e333f065819#diff-0f07b7ac0e4d6d952476ea2d3c608e74R17

**Comment by ywarnier** [comment]
Et a priori il faudrait retirer l'icône de vcard en plus de vérifier les permissions (sinon on est induit en erreur par le fait qu'il y a un truc à faire en cliquant dessus, et au final rien ne se passe).

**Comment by meuhland** [comment]
Exact dans notre cas c'étais la demande d'un professeur de pouvoir accèder à la vcard de ses élèves. Alors peut-être y aller avec une relation if student_is_tutored_by() et sont-ils-amis?

**Comment by meuhland** [comment]
Je te reviens si on à des dispo pour traiter le potentiel pull request à l'interne. (Je suis de retour après mon congé de paternité)

**Comment by ywarnier** [comment]
Félicitations en attendant 🎊

**Comment by meuhland** [comment]
@ywarnier C'est de plus en plus bizarre plus je creuse dans l'issue... 

setSocialUserBlock à un paramètre qui s'appelle show_full_profile et un commentaire est mis 
        //If not friend $show_full_profile is False and the user can't see Email Address and Vcard Download Link

Mais il y a aucune utilisation du paramètre et aucune logique apparante d'attaché outre le fait qu'il est toujours true. :)

**Comment by ywarnier** [comment]
@meuhland j'ai considérablement modifié ton PR, mais en l'essence je l'ai laissé faire ce que tu voulais.
Sinon, un autre PR corrige le problème d'accès par un RH

**Comment by meuhland** [comment]
@ywarnier L'idée était que ça permette au prof ou à un "supérieur" de la personne d'avoir accès à la VCard le PR c'étais mon interprétation... de quelqu'un qui fais que du php rarement. :)
