### ISSUE TITLE
Base de datos no disponible "Database is Unavaible"

### ISSUE THREAD

**Issue by Diego-Bonilla** [chamilo/chamilo-lms#3311]
Hola a todos:

Tengo mi plataforma Chamilo funcionando hace año y medio sin ningún problema, sin embargo, en este momento al entrar a la página principal me aparece el siguiente mensaje: "This portal is currently experiencing database issues. Please report this to the portal administrator. Thank you for your help."

Esto se presentó cuando reinicié el servidor en el cual se encontraba alojado mi Chamilo, lo cual hago con frecuencia sin ningún problema. Mirando los archivos de log, me di cuenta que el servidor donde se encontraba el SO se había quedado sin espacio, luego, solucioné el problema del espacio pero el error sigue, lo que me lleva a pensar que uno de los archivos de configuración quedó corrupto.

Ya verifiqué que el archivo configuration.php que se encuentra en /chamilo/app/config/ estuviera apuntando a la ip indicada.

¿Alguno tiene idea de cómo solucionar este problema? de antemano muchas gracias

Servidor:
 - Máquina Virtual en Google Cloud
 - Sistema operativo :Debian 9 - Linux
 - Versión de Chamilo:  1.11.x 
 - Versión de PHP 7.0.33

**Comment by ywarnier** [comment]
Hola @Diego-Bonilla 
Varias cosas me vienen a la mente pero la descripción de como pasó no tiene relación directa con lo que sigue (no veo nada que lo explique de manera concreta).
1) la versión 7.0 es la más problemática. Quizás al reiniciar hayas activado una versión específica de PHP que hasta ahí había sido actualizada pero no activada. En la medida de lo posible, yo actualizaría a 7.2 o 7.3. Para Debian, se puede hacer con el repo de sury.org
2) una forma de probar la conexión a mysql de manera relativamente simple es mover temporalmente el archivo configuration.php de otro lado para que Chamilo piense que todavía no está instalado, y vuelva a darte el proceso de instalación en el cual está la página de prueba de la db. No termines la instalación, sino borrará tu base de datos, pero quizás la página de prueba de la db te de alguna información adicional. Una vez visto si hay algo más, vuelve a poner configuration.php en su lugar para que Chamilo regrese a la normal
3) si tienes acceso al error log de Php, deberías poder ver alguna info adicional
4) desde la línea de comando, tratar de conectarte a la base de datos con el cliente mysql: mysql -h localhost -u el-usuario-de-Chamilo -p base-de-datos-de-chamilo
Debería decirte algo más preciso de porqué no deja Chamilo conectarse

En esencia, el mensaje que ves en rojo en Chamilo simplemente expresa que hubo "algún problema" en la conexión, pero pueden ser muchas cosas

**Comment by Diego-Bonilla** [comment]
Muchas gracias por tu respuesta @ywarnier , haciendo la prueba de conexión a la base de datos tanto por linea de comando como por el mismo instalador de Chamilo, el error dice"ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")"

He intendado lo siguiente:

1 Copiar el archivo socket de otra instalación en la ubicación indicada, luego el error cambia un poco y dice "Connection refused". 

2 Haciendo una copia de las carpetas:

/var/www/html/chamilo/
/var/lib/mysql

Borrar mysql del S.O  volver a instalarlo, volver a instalar chamilo revisando que haya conexión con la  base de datos, la cual tiene el mismo nombre y contraseña y luego reemplazar las carpetas, al intentar cargar  la página no conecta

Se me ocurre que lo que me puede ayudar a volver a conectar la base de datos correctamente es actualizando chamilo, ya que tengo el 1.11.8, pero al correr la versión 10 dice que no encuentra una instalación anterior de chamilo aún indicando la ruta correcta y siguiento las indicacioes de la guía de actualización.

**Comment by ywarnier** [comment]
No indicaste si llegaste a conectarte desde la línea de comando. Sabes como hacerlo? (quizás tu hosting no lo permita)

**Comment by damisio** [comment]
Te has fijado en el consumo de recursos de tu servidor, tal vez han alcanzado mas del 90% y el servidor apache no acepta mas conexiones.
