### ISSUE TITLE
Language menu shows wrong flag for Bosnian language

### ISSUE THREAD

**Issue by esmin** [chamilo/chamilo-lms#3323]
**Describe**
Language menu shows wrong flag for Bosnian language.

**To Reproduce**
1. Click language select menu on login
2. See error (shows Bahamas flag instead of Bosnian)

**Expected behavior**
Bosnian flag next to "Bosanski" 
![image](https://user-images.githubusercontent.com/6398941/85227204-40d37b80-b3dc-11ea-8beb-392d74f5fc31.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6398941/85227215-55177880-b3dc-11ea-9174-a3b5a4eb1944.png)

**Additional context**
Correct css class for menu is "flag-icon flag-icon-ba" instead of current "flag-icon flag-icon-bs"

**Comment by ywarnier** [comment]
Hi @esmin,

Thanks for reporting this.
The commit above should fix this in 1.11.12.

![flag-bosanski](https://user-images.githubusercontent.com/609839/85237669-eca2b880-b428-11ea-8eb9-fdb01a09cc01.png)
