### ISSUE TITLE
Responsables de RRHH no reciben copia de los mensajes

### ISSUE THREAD

**Issue by gmartin50** [chamilo/chamilo-lms#3333]
Responsables de RRHH no reciben copia de los mensajes

**To Reproduce**
- Envía un anuncio en un curso a un alumno en particular
- Marca la casilla de "enviar copia a responsable de recursos humanos"
- enviar el anuncio
- El responsable de RRHH no recibe copia del anuncio.

**Comment by ywarnier** [comment]
Fixed by PR

**Comment by gmartin50** [comment]
> Fixed by PR

Thanks a lot
