### ISSUE TITLE
Integración con Google calendar

### ISSUE THREAD

**Issue by damisio** [chamilo/chamilo-lms#3337]
La herramienta agenda de chamilo esta cerrado y no acepta integracion con Google calendar u otro.

La solucion seria que se pueda integrar o sincronizar con calendario de google

Esta funcionalidad potenciaria aun mas CHAMILO ya que normalmente en google calendar se puede programar videollamadas con Google Meet.

Dios bendiga su trabajo Comunidad Chamilo.

**Comment by AngelFQC** [comment]
Hola @damisio 
Google Calendar permite exportar tus eventos de tu calendario en un archivo ICS. Y en Chamilo puedes importar este archivo en la agenda de tu plataforma (por ejemplo desde /main/calendar/agenda.php?action=importical&type=personal).

**Comment by damisio** [comment]
@AngelFQC  muchas gracias por las aclaraciones

**Comment by ywarnier** [comment]
We might develop a deeper integration with Google Calendar in the future, but it's not in the short term plans.
