### ISSUE TITLE
Language - Flag Icon Showing wrong Country

### ISSUE THREAD

**Issue by vimobe** [chamilo/chamilo-lms#3339]
**Describe**
Language for Malaysia (Bahasa Melayu) showing as Australia Flag

**To Reproduce**
1. Select and enable Bahasa Melayu (Malaysia)
2. Showing as Australia Flag in Home Page
3. See error

**Expected behavior**
Suppose showing Malaysia Flag, but home page selection shown as Australia Flag

![language](https://user-images.githubusercontent.com/66951235/85885495-007a6000-b817-11ea-8ce2-b1c8333641ef.jpg)

**Comment by ywarnier** [comment]
Hi @vimobe 
Thank you for reporting this error and sorry if we offended anyone over there.

This is how it looks now.
![bahasa-melayu](https://user-images.githubusercontent.com/609839/86189340-9ed13300-bb41-11ea-887b-82dad896b4ee.png)

According to https://en.wikipedia.org/wiki/Malaysia, this is the right flag now, so I'm considering this fixed (it will be in 1.11.12)
