### ISSUE TITLE
Plugin de mantenimiento en Chamilo (eliminar archivos _DELETED_)

### ISSUE THREAD

**Issue by disgregador** [chamilo/chamilo-lms#3341]
**Tu solicitud está relacionado con alguna molestia? Describe...**
Añadir plugin de mantenimiento en Chamilo para tareas como eliminar contenido de cursos antiguos, usuarios, borrar definitivamente archivos marcados como _DELETED_, etc.

**Describe la solución que te gustaría encontrar**

En /test/scripts existen varios archivos que por consola (php-cli) permiten realizar tareas de mantenimiento como eliminar contenidos de cursos antiguos, usuarios, etc.

delete_old_courses.php (Add script to delete old unused courses)
delete_old_courses_even_not_empty.php
delete_old_users_folder.php

¿Se ha pensado en integrarlos como un plugin de mantenimiento general en Chamilo para ser ejecutado desde navegador Web al igual que hace el script de Limpieza de caché y archivos temporales (main/admin/archive_cleanup.php)?

Sería de gran utilidad así como uno que revisara los archivos de Chamilo que se marcan como _DELETED_ para ser eliminados y no ocupar espacio en disco.

Saludos.

**Comment by ywarnier** [comment]
Hola @disgregador deberías revisar la herramienta de línea de comando Chash en https://github.com/chamilo/chash (rama 0.1 para Chamilo 1.11). Ya tiene mucho de lo que pides. La razón por la cual no integramos estas funcionalidades en la interfaz es que muchas veces los límites asignados a PHP en su "SAPI" web no permiten correr procesos lentos e intensivos en el disco.

Los scripts que existen en /tests/scripts/ solo vienen con las versiones Git (no están en el paquete oficial) y sirven para desarrolladores o admins que tienen que hacer unos tratamientos especiales, pero usualmente todos se tienen que actualizar algo para ser útiles.

Por ahora y por las razones expuestas, no tenemos intención de añadir estas opciones en la interfaz web, pero si deseas emprender el gran esfuerzo de hacerlo y mandarnos un Pull Request con todo esto, con gusto lo revisaremos para integrarlo.
Caso contrario: usar chash.
Para no dejar esta tarea en limbo, la estaré cerrando dentro de 7 días si no hay más sobre el tema hasta entonces.

**Comment by disgregador** [comment]
Agradecido @ywarnier

Lo lamento pero mis conocimientos son limitados.

No es habitual disponer de acceso SSH en hosting para instalar clash y ejecutar los scripts de mantenimiento.
Cuando se elimina un fichero desde Chamilo se marca como _DELETED_ pero realmente no se suprime y permanece en el aula ocupando espacio adicional (a veces varios Gigas).
Una opción válida sería añadir un mensaje al borrar el fichero desde navegador y si se quiere eliminar definitivamente o renombrarlo a _DELETED_ para que no se muestre.

Muchas gracias.

**Comment by ywarnier** [comment]
Sí, estoy de acuerdo con el hecho que nuestro método no es ideal. Sin embargo, solo representa varios GBs cuando se trata de un servidor grande, para el cual debería existir un rol de administrador de sistemas que tenga acceso SSH al servidor.

En la versión 2.0 tendremos un sistema de tacho de basura para decidir si borrar por completo o recuperar estos archivos. El estado actual del mecanismo de DELETED es para permitir un rescate de última hora si es que alguien se equivocó y no hay backup.

Una forma de borrarlo si se tiene un acceso SSH pero no a Chash es lanzar un find:
```
find app -name '*_DELETED_*' -delete
```

Por ahora consideraré que este issue es un duplicado de #2872 que también registraste tu hace más de un año (y al cual acabo de asignar como roadmap la versión 2.0).

Claro que a futuro se podrán agregar más funcionalidades de mantenimiento e incorporar los scripts que tenemos en tests/scripts/ en una interfaz web, pero hay *mucho* trabajo ahí para soportar a todos los contextos técnicos posibles, y no está en ninguna proyección prioritaria. Repito que asumo que a partir del momento que necesites estos scripts de mantenimiento es que estás gestionando un portal grande ya, y que para esto deberías tener una persona responsable del portal a nivel técnico. Que queramos hacer la vida más fácil a *esta* persona no es el objetivo principal de Chamilo. El objetivo principal de Chamilo es "mejorar la disponibilidad de una educación de calidad en todo el mundo". Si un portal grande de estos tiene este tipo de problema, es que hay un equipo detrás, y necesita menos de nuestra ayuda que un profesor aislado que gestiona una plataforma por el mismo.
