### ISSUE TITLE
La búsqueda en Documentos no funciona correctamente

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3352]
**Describe el problema**
Chamilo 1.11.10 - En la herramienta Documentos, el buscador únicamente funciona en la carpeta raíz.
Si buscamos documentos de una subcarpeta no se encuentran, ni aunque se acceda a esa carpeta y se realice la búsqueda en ella.

**Cómo reproducir**
Puede verse en https://11.chamilo.org/main/document/document.php?cidReq=TESTINGDOCUMENTSHIDDENFOLDER&id_session=0&gidReq=0&gradebook=0&origin=&id=2820
En esa carpeta hay dos documentos, uno de ellos es city.mp4.
Si en el buscador escribimos "city", la búsqueda no devuelve nada, y se vuelve a la carpeta raíz de Documentos

**Comportamiento esperado**
Lo ideal es que el buscador pudiese localizar documentos tanto en la carpeta actual como en sus subcarpetas, pero si no pudiera ser así, que al menos se realice la búsqueda en la carpeta actual y no siempre en la raíz

**Comment by ywarnier** [comment]
He aprobado el PR de @carlangas159 
Básicamente lo único que veo potencialmente problemático es que no indica en qué carpeta se encontró, pero cuando uno le da clic a alguno de los resultados, se muestra en su contexto.
Os dejo revisar y confirmar, @nosolored

**Comment by nosolored** [comment]
La búsqueda ya funciona correctamente.
Es cierto que en la parte de arriba se muestra la carpeta raíz Documentos, pero la bùsqueda en subcarpetas si va bien ya, muchas gracias.
