### ISSUE TITLE
Agregar filtros a clases

### ISSUE THREAD

**Issue by iruizsur** [chamilo/chamilo-lms#3369]
**Tu solicitud está relacionado con alguna molestia? Describe...**
En pasadas versiones dentro de CLASES se podían filtrar los resultados para definir cuántas clases se podían ver, al seleccionar visualizar TODOS era fácil con Ctrl+F localizar una clase dada, pero esta función desapareció en la 1.11.10 por lo que es complicado estar dando "siguiente página" hasta encontrar lo que buscas. (además el órden alfabético no se respeta).

**Describe la solución que te gustaría encontrar**
Sería útil además de regresar la función de establecer cuántas desplegar, contar con **categorías** de clases, para poder filtrar por tipo, útil en casos que tengas muchos cursos de diferentes niveles, ej : primaria, secundaria, diferentes grados primero, segundo, tercero etc o diferentes tipos de cursos como empresariales , capacitación, sabatinos etc. Esto sirve mucho para multicampus. (si los cursos tienen categorías, porqué no las clases).

**Contexto adicional**
Eso o una casilla de búsqueda.

**Comment by ywarnier** [comment]
Quizás esta funcionalidad no haya estado en 1.11.10 en particular, pero en la versión por llegar (1.11.12) sí está el filtro para mostrar una cantidad X de filas dentro de la lista de clases.

![class-filter](https://user-images.githubusercontent.com/609839/87475886-d05bfb00-c625-11ea-92c7-1ba3a8648d5f.png)
![class-filter2](https://user-images.githubusercontent.com/609839/87475889-d2be5500-c625-11ea-8148-14cb27c53a70.png)

La solicitud de añadir categorías es interesante, pero tendrás que registrarla en una solicitud separada, ya que solo podemos eficázmente tratar una necesidad por solicitud.
