### ISSUE TITLE
Integración con nube

### ISSUE THREAD

**Issue by iruizsur** [chamilo/chamilo-lms#3370]
**Tu solicitud está relacionado con alguna molestia? Describe...**
En esta pandemia los maestros han encontrado utilidad con google classroom porque pueden solicitar actividades rápidamente con su teléfono y se integra todo por medio de google. Sería útil un botón o función que permita adjuntar trabajos, tareas, documentos desde la nube, lo cual haría eficiente también el uso del espacio.

**Describe la solución que te gustaría encontrar**
Me gustaría que Chamilo incorporara plugins o botones para conectarse a dropbox, onedrive, google drive o google docs, que las cosas se pudieran guardar o extraer y visualizar de la nube, ya sea para maestros o alumnos.

**Contexto adicional**
Esto le daría mayor funcionalidad al sistema, ahora que hay tantas opciones para seleccionar, pero chamilo brinda una ventaja organizativa que herramientas como google classroom no tienen.

**Comment by ywarnier** [comment]
Solicitud interesante pero mucho demasiado ámplia.
En Chamilo vamos integrando cada vez más funcionalidades, pero solicitar "incorporara plugins o botones para conectarse a dropbox, onedrive, google drive o google docs" representa trabajo de cientos de horas y es muy poco probable que la comunidad de Chamilo pueda dedicar el tiempo necesario a este tipo de integraciones en un futuro cercano.

Cierro esta solicitud por demasiado imprecisa, pero adelante con abrir solicitudes con *un* conector a la vez, describiendo exactamente las interacciones buscadas.
