### ISSUE TITLE
Ejercicios aleatorios no eligen las preguntas o cantidades correctas.

### ISSUE THREAD

**Issue by iruizsur** [chamilo/chamilo-lms#3384]
**Describe el problema**
Al realizar un ejercicio y ordenar por categorías y al azar, se establecen cuántas preguntas tomar de cada categoría pero no se respetan y además se filtra (a cierta candidad) la lista de preguntas dentro del listado del ejercicio. 

**Cómo reproducir**
Pasos para reproducir el problema:
1. Crear al menos tres categorías (Cat A, Cat B, Cat C)
2. En Cat A crear al menos dos preguntas con la misma dificultad (1).
3. En Cat B  crear cuatro preguntas: dos de cierta dificultad (1), dos de otra dificultad (2).
4. En Cat C crear una pregunta de mayor dificultad (3) ej abierta.
5. Crear el ejercicio y establecer preguntas sorteadas por categorías desordenadas con preguntas al azar.
6. Al revisar si existen suficientes cantidades de preguntas escribir:
Cat A: 1 (quiero que tome una pregunta)
Cat B; 2 (debería tomar 2 equilibrando grado de dificultad: no lo hace)
Cat C: -1 (debe tomar esa pregunta, no la toma).

Al hacer el ejercicio pasan varias cosas:
1) A cada alumno le sale distinta cantidad de preguntas, aunque deberían salirle 1 CatA, 2 CatB y CatC.
2) El ejercicio no agrega necesariamente la pregunta C, puede agarrar de otras categorías  y no debería.
3) Si ingreso a la lista de preguntas del ejercicio, desaparecen varias (aunque sigue diciendo que mi examen contiene 7).
Para que el punto 3 se corrija, debo elegir Ordenar preguntas aleatorias (sin categoría) escoger todas o 7 y guardar... vuelven a aparecer todas . Después ya puedo poner lo de ordenar por categorías y parece que ya no desaparecen, pero el error 1 y 2 continúan.

**Comportamiento esperado**
Poder agregar pares de preguntas con el mismo grado de dificultad dentro de cada categoría y que Chamilo fuera seleccionando la cantidad que puse de preguntas y si pongo -1 a una categoría que a fuerza tome la pregunta.
Ejemplo:

CAT A
     Preg A1: Dificultad 1
     Preg A2: Dificultad 1
CAT B
   Preg B1: Dificultad 1
   Preg B2: Dificultad 1
   Preg B3: Dificultad 2
   Preg B4: Dificultad 2
CAT C
   Preg C1: Dificultad 3 

Crear ejercicio. Ordenar por categoria al azar. Seleccionar :
CAT A: 1
CAT B: 2
CAT C: -1 (todas=1)

Crearía distintos examenes, todos con 4 preguntas y deseablemente balancear la dificultad para que ningún examen sea más complicado o fácil que otro pero si sean diferentes:
Examen 1: Preg A1+Preg B1+Preg B3+Preg C1
Examen 2: Preg A2+Preg B2+Preg B3+Preg C1
Examen 3: Preg A1+Preg B1+Preg B4+Preg C1 etc.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.
Debería agregar la pregunta Abierta
![image](https://user-images.githubusercontent.com/16807565/87844807-afdeab80-c886-11ea-91b6-95e556a124cf.png)

En ninguno de los intentos la incluyó y tampoco respetó el límite de cada categoría. Como se puede ver hay categorías que no incluyó y además hizo un examen de 8 preguntas porque omitió categorías.
![image](https://user-images.githubusercontent.com/16807565/87844883-4e6b0c80-c887-11ea-8d3b-2ab28141f8a0.png)

No tengo la pantalla de como me filtró la lista de preguntas porque ya lo corregí, pero si puedo ayudarles a reproducir el error si gustan. De inicio no tendría porqué tenerse que guardar primero con aleatorio y luego ya usar categorías aleatorias.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador Chrome

**Servidor
 - Sistema operativo : Linux
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 7.2

**Contexto adicional**
El examen con que probé no tiene 3 categorías  sino 11 y 27 preguntas, yo deseaba que salieran varios examenes diferentes de 13 preguntas (equivalentes por los grados de dificultad que estipulé)

**Comment by NicoDucou** [comment]
Hola @iruizsur 

Acabo de reproducir este caso en : https://11.chamilo.org/main/exercise/admin.php?cidReq=3384&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=436
Todo funciona bien, solo anotar que el campo dificultad no esta usado en la reparticion. El campo Dificultad es mayormente para la informacion, no se usa para la reparticion. Como se puede ver en el screenshot debajo cuando se realiza este ejercicio se presenta bien 4 preguntas (1 A, 2 B y 1 C) : 
![image](https://user-images.githubusercontent.com/6579268/88366959-de7aeb80-cd8a-11ea-9fcc-0cf371c2cf9b.png)

Puedes acceder a este Chamilo de prueba con el usuario admin/admin si quieres probar o crear un caso que no funciona.
Esperamos tu confirmacion para cerra la tarea.

Saludos

**Comment by ywarnier** [comment]
Confirmo lo dicho por  @NicoDucou :
La dificultad de las preguntas en un elemento contraintuitivo que no hace nada sino mostrar un nivel de dificultad. La funcionalidad existe desde antes de las categorías de preguntas, y servía esencialmente para que el docente que elabora la prueba pudiera recordar que todas no son normalizadas.
Luego se desarrollaron las categorías de preguntas, con un soporte de un solo nivel de categoría, pero no se incluyó ninguna lógica compleja con niveles de dificultad.
Está pendiente para nosotros añadire la gestión de subcategorías en los ejercicios, con las cuales se podría establecer subcategorizaciones que representan la dificultas ("Categoría 1 - nivel básico" sería una subcategoría de la "Categoría 1").
Pero por ahora no existe esto, así que cierro este issue.

**Comment by iruizsur** [comment]
Gracias @NicoDucou @ywarnier  Aprecio mucho que se hayan tomado el tiempo para hacer la prueba, en mi site no se comporta igual (traté de entrar a chamilo11, pero mi cuenta caducó) pero al funcionar con ustedes está perfecto porque es probable que en la actualización ya no me pase. Muchas gracias.
