### ISSUE TITLE
Chamilo: 1.11.10 problem on PHP 7.4.7

### ISSUE THREAD

**Issue by LolaCapitani** [chamilo/chamilo-lms#3385]
Hi!
For a server upgrade, we have update PHP from 7.1.33 to version 7.4.7
We have noticed several Chamilo platform failures, including graphics (even the icons get smaller, the graphics lose their parameters...).
We are now back to PHP version 7.1.
I wanted to report it to you. 
In your opinion, what is the best and most stable PHP version for Chamilo 1.11.10?
Thank you for your work, from all of us!

Lola
(=^ ◡ ^=)

---------------------------

    OS: Linux Ubuntu 18.04 / Windows 10(64bit), Win 7(32 bit)
    Browser CHROME 80.0.3987.87 , FIREFOX 78.01

Server

    OS: Linux 3.10.0, LiteSpeed V7.6,
    Version of Chamilo: 1.11.10
    Version of PHP: PHP 7.4.7

**Comment by ywarnier** [comment]
The most stable, to my knowledge, is PHP 7.2. It works well on 7.3 (we have many customers in 7.3) but we don't have any *production* system on PHP 7.4 (although several of our developers use 7.4).
7.0 created a lot of issues. 7.1 was much less efficient than 7.2.
This being said, it should work fine with 7.4 but if you upgrade an existing production portal, you should execute the "composer update" command once PHP has been upgraded. This will update all dependencies according to the version of PHP.

**Comment by ywarnier** [comment]
This is a development space. For simple questions, please use https://forum.chamilo.org/

**Comment by NicoDucou** [comment]
Just to confirm that this week I did an update from php 5.6 to php 7.4 and at the same time an update from Chamilo 1.10.4 to Chamilo 1.11.x (from github) and after a composer update everything is working fine.

**Comment by jmontoyaa** [comment]
I'm using PHP 7.4, and I don't see such problems, maybe the server should be set to hide PHP notices (display_errors = 0)

**Comment by NicoDucou** [comment]
As indicated by Julio, this might be the solution. On infomaniak I had to add a .user.ini file in the root directory of Chamilo with 
`display_errors=off
`

**Comment by LolaCapitani** [comment]
Hi @ywarnier ,
thanks for your advice.

I didn't mean to bother you here. I'm sorry. 
I asked for advice on the best version of PHP for Chamilo, as it gives me and other teachers problems with the upgrade to PHP 7.4.7.

Sorry if I write again, but the problem is not small for us "normal" teachers who use Chamilo mainly because of COVID.

Providers do not like platforms running on older versions of PHP, as they formally report that there might be security issues.

When school directors receive these update notes from providers, they tell us teachers: "update this e-learning platform!" There are children on the platform, so any security issues are seen as a danger.

That said, to give my small contribution, I have made a video.

https://mega.nz/file/PdkFzQYZ#tW9IXFqan7mEo8CDB7ZJx-HZAuhWCQlKOE2IqQPpKbk

In this video you can see for example the problem it causes to emails...

Another example of non-compatibility.

In these two pictures you can see for example that: 

- (photo1 - with PHP 7.4.7) dots appear in the menu and everything is closer together:

![photo1_7 4 7](https://user-images.githubusercontent.com/67590937/90771166-2b52d300-e2f3-11ea-955f-a19c42f0c63f.jpg)


- (photo2 - with PHP 7.1) menu with correct layout

![photo2_7 1](https://user-images.githubusercontent.com/67590937/90771224-3efe3980-e2f3-11ea-9c7c-7e522b7a91d9.jpg)


My colleagues also suffer from all these problems with 7.4.7. 
They have the same server configuration as me.


No problem for now, let's go to 7.2. I tell my director that it's all ok.



Thanks again for your attention! And sorry for the disturbance!



Lola
(=^ ◡ ^=)

**Comment by ywarnier** [comment]
As a side note, PHP 7.3 will be fully supported security-wise until the 6th of December of 2021, by which time we hope most users will have migrated to the (still not released) Chamilo 2.0 which will fully support PHP 7.4 without (normally) configuration changes needed.
https://www.php.net/supported-versions.php

**Comment by LolaCapitani** [comment]
thanks! @ywarnier
