### ISSUE TITLE
Radio button with no indication in the administration panel (Tools)

### ISSUE THREAD

**Issue by LolaCapitani** [chamilo/chamilo-lms#3386]
Hi!
I'm setting the platform in the admin panel...

In the page Amministrazione / Configurazione Piattaforma / Strumenti / (Administration / Configuration Settings / Tools (fad/main/admin/settings.php?category=Tools) in the penultimate position there is a field where no indication appears (I enclose the image). 

![nessuna indicazione](https://user-images.githubusercontent.com/67590937/87854817-b287e200-c914-11ea-9408-feebed1f994d.jpg)

The default platform puts me "no".
What is it?
Thank you!

Lola
(=^ ◡ ^=)

Desktop (please complete the following information):

    OS: Linux Ubuntu 18.04 / Windows 10(64bit), Win 7(32 bit)
    Browser CHROME 80.0.3987.87 , FIREFOX 78.01

Server

    OS: Linux 3.10.0, LiteSpeed V7.6,
    Version of Chamilo: 1.11.10
    Version of PHP: PHP 7.1

**Comment by aelalfey** [comment]
@LolaCapitani 

![p1](https://user-images.githubusercontent.com/33488577/87884125-68822780-ca0c-11ea-8776-3862467fe9fc.jpg)

**Comment by ywarnier** [comment]
Might be due to a translation missing or badly formed. Nothing we can do on our side. To increase translations support, register to https://translate.chamilo.org/ and ping me here to enable your account.

**Comment by jmontoyaa** [comment]
It's because the translation it should be fixed now with:

https://github.com/chamilo/chamilo-lms/commit/2e24eba9be5bd77ef09d604a9cc7ad8815b0ef38

**Comment by ywarnier** [comment]
Checked and approved.
