### ISSUE TITLE
Agenda: Repeated "All day" events show on full day span after first occurence

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3394]
**Describe**
When I created a repeated "All day" event in a course agenda, the first event is created great, but the others span the whole day (instead of appearing as an all day item at the top) in "Week" view.

**To Reproduce**
1. Create a course
2. Go to agenda
3. Click "Create event"
4. Give a name, leave the date/time alone, mark "All day" and mark "Repeat", leave it at "Daily" and mark the last repetition 2 or 3 days later
5. Save
6. Go to the "Week" view
7. Only the first event is marked as an "All day" event. The others are event that span from 00:00 to 23:59

**Expected behavior**
All the repetitions of an "All day" event should appear as "All day" events.

**Screenshots**
![agenda-form](https://user-images.githubusercontent.com/609839/88187350-ae223880-cc36-11ea-99a1-6ed1a37017f4.png)
![events](https://user-images.githubusercontent.com/609839/88187356-af536580-cc36-11ea-96b1-886e1d54d343.png)

Version 1.11.x of today.

**Comment by carlangas159** [comment]
The way to evaluate the event for the whole day was not being taken correctly, therefore, after inserting the first event, the all_day field was left at 0
![image](https://user-images.githubusercontent.com/18097392/88218404-a0b08280-cc25-11ea-9a55-feffb7aee94d.png)

**Comment by ywarnier** [comment]
Checked and approved. Thanks!
