### ISSUE TITLE
Assessments Tool Bug (list view)

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3408]
Dears @NicoDucou @ywarnier @AngelFQC ,

**Description:** If I click on "list view" inside the assessments tool to view student/s progress, the main assessments categories and its content is not alignment correctly.

![87873190-bd4b8100-c9bf-11ea-8eb4-404404629273](https://user-images.githubusercontent.com/33488577/88478777-4aa44d80-cf4b-11ea-8adc-f6579ac9f285.jpg)
![87873224-0ac7ee00-c9c0-11ea-838b-143e874faf3d](https://user-images.githubusercontent.com/33488577/88478778-4c6e1100-cf4b-11ea-9103-d04406d3ada6.jpg)

The above listed pcitures shows the problem on my site. However i can't reproduce the issue on https://11.chamilo.org/ because this module "List View" is totally changed and totally looks different.

Below picture shows the same page on https://11.chamilo.org/main/gradebook/gradebook_flatview.php?cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&selectcat=170 but in this case the table looks fine and everything is aliged correctly. So this means you fixed this issue in the next version.

![Bug 14](https://user-images.githubusercontent.com/33488577/88478891-fd74ab80-cf4b-11ea-845e-a8e45ca35b24.jpg)

**So is there a way to fix this on the current version of Chamilo. I can provide access to my website in case you need to investigate more.**

Thank you once more for your help.
Regards

**Comment by ywarnier** [comment]
@aelalfey we're only a few days away from releasing 1.11.12, so a little patience should solve this.
In other cases, 11.chamilo.org is just an image of the latest development version here (branch 1.11.x) so you can keep your software updated through Git, but that requires good Git and PHP skills.

**Comment by aelalfey** [comment]
@ywarnier 

Thank you for your reply and for clearing things out. Sure i will wait.
