### ISSUE TITLE
Learning Path View on Mobile Not working

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3409]
Dears @NicoDucou @ywarnier @AngelFQC , 

**Description:** When i view learning path on PC or Tablet it works just fine as in the picture below.

I have recreated the case at https://11.chamilo.org/main/lp/lp_controller.php?cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=229&isStudentView=true

**PC View** everything works just fine.

![Bug 15](https://user-images.githubusercontent.com/33488577/88479124-411be500-cf4d-11ea-8775-a41dfacfe69b.jpg)

**Mobile View** right side is totaly invisible.

![Bug 16](https://user-images.githubusercontent.com/33488577/88479229-ecc53500-cf4d-11ea-8b49-25795712e496.jpg)

**One more thing** that i found while testing this on https://11.chamilo.org/main/lp/lp_controller.php?cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=229&isStudentView=true When i tried to click on "Upload my assigment" button under "MAC assig. No 1" on the learning path, It is not working at all "the button is not even clickable"

![Bug 17](https://user-images.githubusercontent.com/33488577/88479320-8a206900-cf4e-11ea-893d-46ba517731fd.jpg)

Thank you once more for your help.
Regards

**Comment by NicoDucou** [comment]
Hi @aelalfey 
> **One more thing** that i found while testing this on https://11.chamilo.org/main/lp/lp_controller.php?cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=229&isStudentView=true When i tried to click on "Upload my assigment" button under "MAC assig. No 1" on the learning path, It is not working at all "the button is not even clickable"
> 
> ![Bug 17](https://user-images.githubusercontent.com/33488577/88479320-8a206900-cf4e-11ea-893d-46ba517731fd.jpg)

It works for me as you can see here :
![image](https://user-images.githubusercontent.com/6579268/88530678-0627b900-d002-11ea-9b09-9fd0488bc648.png)

We will now focus in this task on the other problem.

**Comment by NicoDucou** [comment]
> **Description:** When i view learning path on PC or Tablet it works just fine as in the picture below.
> 
> I have recreated the case at https://11.chamilo.org/main/lp/lp_controller.php?cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=229&isStudentView=true
> 
> **PC View** everything works just fine.
> 
> ![Bug 15](https://user-images.githubusercontent.com/33488577/88479124-411be500-cf4d-11ea-8775-a41dfacfe69b.jpg)
> 
> **Mobile View** right side is totaly invisible.
> 
> ![Bug 16](https://user-images.githubusercontent.com/33488577/88479229-ecc53500-cf4d-11ea-8b49-25795712e496.jpg)

Normaly on smartphone we are able to swipe from left to right to see the menu or the content.
I just tried and I confirm that there is a problem, we can note swipe to see the right side.

**Comment by Haboubi92** [comment]
a temporally solution is to use external embed view
![image](https://user-images.githubusercontent.com/48198054/88975742-68fba780-d2c3-11ea-8b33-4ebee990b501.png)


as a substitute for Chamilo learning path
you can convert PowerPoint slides to a SCORM package generated with ispring (there is a [free version](https://www.ispringsolutions.com/ispring-free)) which has an excellent view for mobile devices
it's also possible to use [H5P](https://h5p.org/)

**Comment by AngelFQC** [comment]
In #3418 I'm changing the behaviour for learning path in mobile views. See the animation in https://github.com/chamilo/chamilo-lms/pull/3418#issue-458748968

**Comment by NicoDucou** [comment]
Thank you @AngelFQC
I just tested it on https://11.chamilo.org/main/lp/lp_controller.php?cidReq=MACCOURSE&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=229&isStudentView=true and it all works fine for me.

@aelalfey I let you confirm and close the issue.

Best regards

**Comment by ywarnier** [comment]
Closing. Solution provided. No feedback received but internal feedback approves it.

**Comment by aelalfey** [comment]
Hi all,

Sorry for late reply. Thank you all for your hard work. It works great. Thank you once more.

Regards
