### ISSUE TITLE
Paypal Commission

### ISSUE THREAD

**Issue by Leonardolms** [chamilo/chamilo-lms#3415]
Hello @ywarnier @jmontoyaa ,

I am testing a Chamilo commission feature, and when adding the payee, it appears that no Paypal account was found. Where do I set up the Paypal account of the beneficiaries on the platform?

Chamilo Version: 1.11.10
Server: Linux

Does the beneficiary's account have to be only with CNPJ or can it only be CPF (personal)?

**Comment by ywarnier** [comment]
I don't think the beneficiary's account needs a seller account, no. We're just sending a small payment without the need for an invoice or anything. Any PayPal account should allow that.
