### ISSUE TITLE
fatal Error during install

### ISSUE THREAD

**Issue by VapeDaddy** [chamilo/chamilo-lms#3422]
During final part of the install process i get a patal error
```
Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'root-4e4f'@'%' to database 'courses313137c8f7' in /home/sites/11a/e/e863179ca0/public_html/courses/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:41 Stack trace: #0 /home/sites/11a/e/e863179ca0/public_html/courses/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(41): PDO->exec('CREATE DATABASE...') #1 /home/sites/11a/e/e863179ca0/public_html/courses/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1060): Doctrine\DBAL\Driver\PDOConnection->exec('CREATE DATABASE...') #2 /home/sites/11a/e/e863179ca0/public_html/courses/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(1030): Doctrine\DBAL\Connection->executeUpdate('CREATE DATABASE...') #3 /home/sites/11a/e/e863179ca0/public_html/courses/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(412): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql('CREATE DATABASE...') #4 /home/sites/ in /home/sites/11a/e/e863179ca0/public_html/courses/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 93
```
I dont think there are any steps other than complete install 

My camillo version is 1.11.10

**Comment by lonesomewalker** [comment]
How about NOT using root to access your database? :-)
Better create a new user and grant this all rights to the Chamilo database.

**Comment by ywarnier** [comment]
In any case, the message is clear: access denied for user root-4e4f, so something is wrong with your permissions definition. Nothing to do with Chamilo there.
Try connecting directly from the command line using a mysql command-line client, like `mysql -h [the-db-host] -u root-4e4f -p` and see if your connection is accepted, then try to connect to database courses313137c8f7 inside the client with `use courses313137c8f7`.
Until this works, Chamilo won't work either.
