### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by cloudinfonet** [chamilo/chamilo-lms#3423]
Hi,

when I am trying to install Chamilo 1.11.10 php7 in my own domain hosting, I am getting the following error in the last step

Please help to solve this.

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'cloudinfonet'@'%' to database 'chamilo' in G:\PleskVhosts\e-learning.cloudinfonet.com\httpdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:41 Stack trace: #0 G:\PleskVhosts\e-learning.cloudinfonet.com\httpdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(41): PDO->exec('CREATE DATABASE...') #1 G:\PleskVhosts\e-learning.cloudinfonet.com\httpdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(1060): Doctrine\DBAL\Driver\PDOConnection->exec('CREATE DATABASE...') #2 G:\PleskVhosts\e-learning.cloudinfonet.com\httpdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\AbstractSchemaManager.php(1030): Doctrine\DBAL\Connection->executeUpdate('CREATE DATABASE...') #3 G:\PleskVhosts\e-learning.cloudinfonet.com\httpdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\AbstractSchemaManager.php(412): Doctrine\DBAL\Schema\AbstractSchemaManager->_execSql('CREATE DATABASE...') #4 G:\P in G:\PleskVhosts\e-learning.cloudinfonet.com\httpdocs\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 93

**Comment by lonesomewalker** [comment]
Looks like two issues:
you use Windows which should/could work, but recommended are *nix-systems. But this is not the main issue.

Other thing is, your database connection seems to be wrong.

**Comment by lonesomewalker** [comment]
Also, when i check your installer, you have a lot to solve:
- Internationalization Support
- Cookie HTTP Only | ON | OFF
- Maximum upload file size | >= 10M | 2M
- Maximum post size

You should also fix that for a good running system.

**Comment by ywarnier** [comment]
`Access denied for user 'cloudinfonet'@'%' to database 'chamilo'` says it all: you need to fix the access of user cloudinfonet to the database 'chamilo' before you can continue. This is not Chamilo-related.
