### ISSUE TITLE
Show course in user's language bug for Russian language

### ISSUE THREAD

**Issue by roelvisje** [chamilo/chamilo-lms#3426]
When main course is in english, but user with russian language as main language logs in,  the names underneath the icons still remain russian even though the "Show course in user's language" is activated in course settings.
When pressing buttons the language does change, so only on main course page the icons still keep their english version.
For dutch language the change does work. So bug is for Russian in this case specific.
Also for learning path it still keeps english language after selecting. See in screenshots below for more detail.

**Expected behavior**
change of language

**Screenshots**
![russian](https://user-images.githubusercontent.com/51987964/89393482-23980980-d70b-11ea-8d30-9bc6ca628c73.jpg)

**Comment by NicoDucou** [comment]
Hi @roelvisje 

I confirm the problem.
It's because the translation is not present in russian so Chamilo uses the term in english by default.

This is what we have for tool in Russian

```
root@ThinkPad-E570:/var/www/chamilo111x.loc/main/lang/russian# rgrep Tool
trad4all.inc.php:$CsvPutIntoDocTool = "Файл \"users.csv\" был помещен в раздел Документы.";
trad4all.inc.php:$ToolIntro = "Введение в инструмент";
trad4all.inc.php:$AdministrationTools = "Инструменты управления";
trad4all.inc.php:$CourseCreateActiveToolsTitle = "Активные модули при создании курса";
trad4all.inc.php:$CourseCreateActiveToolsComment = "Какие инструменты должны быть активированы (видимы) по умолчании при создании нового курса?";
trad4all.inc.php:$TechnicalTools = "Технический";
trad4all.inc.php:$ShowToolShortcutsTitle = "Ярлыки инструментов";
trad4all.inc.php:$ShowToolShortcutsComment = "Показывать ярлыки инструментов на баннере?";
trad4all.inc.php:$Tool = "инструмент";
trad4all.inc.php:$EnableToolIntroductionTitle = "Включить вводную информацию по инструментам";
trad4all.inc.php:$EnableToolIntroductionComment = "Включить вводную информацию для каждого инструмента домашней страницы";
trad4all.inc.php:$GroupTools = "Инструменты";
trad4all.inc.php:$Tools = "Инструменты";
trad4all.inc.php:$ToolIsNowVisible = "Инструмент сейчас видим (активен)";
trad4all.inc.php:$ToolIsNowHidden = "Инструмент сейчас не активен";
trad4all.inc.php:$ToolName = "Импортировать курсы в системе Blackboard";
trad4all.inc.php:$ToolsAccess = "Доступ к инструментам";
trad4all.inc.php:$CountToolAccess = "Количество подсоединений к этому курсу";
trad4all.inc.php:$ToolTitleToolnameColumn = "Название инструмента";
trad4all.inc.php:$ToolTitleUsersColumn = "Щелчки пользователей";
trad4all.inc.php:$ToolTitleCountColumn = "Общее количество щелчков";
trad4all.inc.php:$LoginsAndAccessTools = "Входы и доступы к инструментам";
trad4all.inc.php:$ViewToolList = "Просмотреть список всех инструментов";
trad4all.inc.php:$ToolList = "Список всех инструментов";
trad4all.inc.php:$AdminToolName = "Статистика управления";
trad4all.inc.php:$PlatformToolAccess = "Доступ к инструментам";
trad4all.inc.php:$OtherTools = "Другие инструменты";
trad4all.inc.php:$ToolsMostUsed = "Наиболее часто используемые инструменты";
trad4all.inc.php:$MdCallingTool = "Документы";
trad4all.inc.php:$EditToolOptions = "Редактировать параметры инструмента";
```

We are missing at least those translations : 

```
trad4all.inc.php:$ToolCourseDescription = "Course description";
trad4all.inc.php:$ToolDocument = "Documents";
trad4all.inc.php:$ToolLearnpath = "Learning path";
trad4all.inc.php:$ToolLink = "Links";
trad4all.inc.php:$ToolQuiz = "Tests";
trad4all.inc.php:$ToolAnnouncement = "Announcements";
trad4all.inc.php:$ToolGradebook = "Assessments";
trad4all.inc.php:$ToolGlossary = "Glossary";
trad4all.inc.php:$ToolAttendance = "Attendances";
trad4all.inc.php:$ToolCalendarEvent = "Agenda";
trad4all.inc.php:$ToolForum = "Forums";
trad4all.inc.php:$ToolDropbox = "Dropbox";
trad4all.inc.php:$ToolUser = "Users";
trad4all.inc.php:$ToolGroup = "Groups";
trad4all.inc.php:$ToolChat = "Chat";
trad4all.inc.php:$ToolStudentPublication = "Assignments";
trad4all.inc.php:$ToolSurvey = "Surveys";
trad4all.inc.php:$ToolWiki = "Wiki";
trad4all.inc.php:$ToolNotebook = "Notebook";
trad4all.inc.php:$ToolBlogManagement = "Projects";
trad4all.inc.php:$ToolTracking = "Reporting";
trad4all.inc.php:$ToolCourseSetting = "Settings";
trad4all.inc.php:$ToolCourseMaintenance = "Backup";
trad4all.inc.php:$ToolCourseProgress = "Course progress";
```

I don't know if you have an account on https://translate.chamilo.org/ to contribute to the Russian translation. Otherwise you can create one and we will give you access to the russian translation.
Other wise just copy here the missing translation and we will put them in Chamilo.

We are publissing the new Chamilo version in a few days so answer rapidly so that we can include it in this new version.
 
Best regards

**Comment by roelvisje** [comment]
Hi Nico,

I asked my wife to translate them for you:

trad4all.inc.php:$ToolCourseDescription = "Описание курса";
trad4all.inc.php:$ToolDocument = "Документы";
trad4all.inc.php:$ToolLearnpath = "Курс обучения";
trad4all.inc.php:$ToolLink = "Ссылки";
trad4all.inc.php:$ToolQuiz = "Тесты";
trad4all.inc.php:$ToolAnnouncement = "Объявления";
trad4all.inc.php:$ToolGradebook = "Оценки";
trad4all.inc.php:$ToolGlossary = "Глоссарий";
trad4all.inc.php:$ToolAttendance = "Присутствие";
trad4all.inc.php:$ToolCalendarEvent = "Календарь";
trad4all.inc.php:$ToolForum = "Форумы";
trad4all.inc.php:$ToolDropbox = "Dropbox";
trad4all.inc.php:$ToolUser = "Пользователи";
trad4all.inc.php:$ToolGroup = "Группы";
trad4all.inc.php:$ToolChat = "Чат";
trad4all.inc.php:$ToolStudentPublication = "Задания";
trad4all.inc.php:$ToolSurvey = "Опросники";
trad4all.inc.php:$ToolWiki = "Вики";
trad4all.inc.php:$ToolNotebook = "Дневник";
trad4all.inc.php:$ToolBlogManagement = "Проекты";
trad4all.inc.php:$ToolTracking = "Отчетность";
trad4all.inc.php:$ToolCourseSetting = "Настройки";
trad4all.inc.php:$ToolCourseMaintenance = "Backup";
trad4all.inc.php:$ToolCourseProgress = "Прогресс по курсу";

**Comment by NicoDucou** [comment]
Hi @roelvisje 

I just updated the russian language in Chamilo with the translation you just send us.
Now the tools appear in russian as we can see here : 
![image](https://user-images.githubusercontent.com/6579268/89660898-47597c00-d8d2-11ea-8ef9-5ab181069e3a.png)

If you want you can add more translation to the russian part of Chamilo. As we can see on translate.chamilo.org there is only 40% of the variables that are translated to russian in Chamilo : 
![image](https://user-images.githubusercontent.com/6579268/89658599-0744ca00-d8cf-11ea-84ee-c923f21018c4.png)

So you are welcome to create an account on https://translate.chamilo.org/ and we will give you access to the russian translation so that you can contribute. Just indicate what is you username.

**Comment by ywarnier** [comment]
@roelvisje It would be great to have more translations to Russian. We can also send you an Excel file if you like to speed up the process of translation.
