### ISSUE TITLE
Learning path scrolling when using "make impression / maak indruk" mode.

### ISSUE THREAD

**Issue by roelvisje** [chamilo/chamilo-lms#3427]
As seen below I selected the "make impression / maak indruk" mode for the learning path.
![lp](https://user-images.githubusercontent.com/51987964/89408153-4680e880-d720-11ea-9d4c-d31688e4a140.jpg)

The "problem" I noticed myself and also colleagues/students is the way to browse through the pages when using a mouse. (they dont notice you can also go left and right with keyboard)

Basically people tend to click on the greyed out slide and expect it to be activated. but this only happens when you click either on the top or the utmost side of the slide. It isn't clear for people and they start clicking at random on the pages and become frustrated that it is only in those small area's that it works.

Possible solutions:
1) Make the whole slide to be clickable for the intended action? 
2) on the bottom a horizontal scrollbar so people can use that for scrolling to next slides / quicker to a slide?

**Comment by AngelFQC** [comment]
![Updated impress view](https://user-images.githubusercontent.com/1697880/89468215-92418b00-d73c-11ea-8026-d6901d40ec0a.png)

**Comment by roelvisje** [comment]
Tested in edge: clicking on the next slide/ mising slide next to it: works like a charm. the scroll bar though now gives the following in edge: so no scroll bar seen below like in yours even though it looks very nice, but the scroll bar is in side the slide. 

![lp new](https://user-images.githubusercontent.com/51987964/89501975-86011080-d7c4-11ea-84ac-b33839b0c2ae.jpg)

Also when logged in as student then the browsing capability you usually see above the slide is gone. So a student cannot go back to lets say the course starting page.

**Comment by AngelFQC** [comment]
It seems like a CSS cached.

Please update your css styles in `/chamilo/web/css/base.css` with  https://github.com/chamilo/chamilo-lms/commit/9f72601a0d25ac9bb0a7973a64c48e442d974d46#diff-8b186ddd6e577c60ef19e31036be3b37

If you are using composer, then try `composer update-css` or `comporser install`

And force the reload in the browser with _Ctrl + F5_

**Comment by AngelFQC** [comment]
@roelvisje you can test now here https://11.chamilo.org/main/lp/lp_impress.php?lp_id=240&cidReq=TESTING&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by roelvisje** [comment]
@AngelFQC 

I confirm it works nicely in chrome; clear slides etc.
autoplay also functions. is there also a setup for the amount of time between the slides? not that is currently important, since the main idea of browsing now works. Clicking on the slide you deleted i think?
What you still miss is an option to go back to the main coursepage/learning path page. since the slides now take over.

what I do see is that in "edge" the slides are blurry as you can see below.
edge gives a very brief message:
Your browser doesn't support the features used by impress.js, so you are presented with a simplified version of this presentation
for best experiences use chrome, Firefox or safari.
So i don't know if it is my side or just a limitation of edge...

![blurry](https://user-images.githubusercontent.com/51987964/89569427-fa6b9c00-d824-11ea-8e7a-1a81a7781aa4.jpg)

**Comment by AngelFQC** [comment]
@roelvisje what versión of MS Edge?

**Comment by ywarnier** [comment]
@roelvisje Please register a new issue with all the details (including the Edge version). We are closing this one to consider it fixed in 1.11.12 (as per the initial bug reported). Thanks!
