### ISSUE TITLE
Exercise result per question, incoherent data

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3428]
In the Exercise report per question in the column "number of student that selected this" we only count student account but in the following columns we integrate all the result of all types of user.
So or we need to change the column "number of student that selected this" to show all type of user and not only student or in the following column just consider the students for the statistics.

Can be seen on https://11.chamilo.org/main/exercise/stats.php?cidReq=GITHUB3177&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=451
I have done the exercise 4 times as a teacher/admin so there is 0 in the number of student column but we can see statistics in the following columns : 

![image](https://user-images.githubusercontent.com/6579268/89437776-4ac0fc00-d748-11ea-98f3-1207d7b241ab.png)

tested on Chamilo 1.11.x of 05/08/2020

**Comment by ywarnier** [comment]
We can change the title to "number of users having selected this one", and the filter should be to show all users always. This is not a critical report as in other cases (it helps design better questions, it doesn't define the future of a student), and it is important to include all users independantly from their roles (in future versions, a platform admin could be a simple student in a course).

**Comment by NicoDucou** [comment]
It did not follow the comment of Yannick but now it takes only the students in all the calculation. So it is coherent now.

But doing this test I've seen another incoherence that I report here not to forget.
In the number of student the calculation take into account the number of student that selected one answer, but if the user did many attempt and all the time the same answer it only shows one time in the number of student that selected this answer but in the medium score it take into account all the attemps

Here is an explanation with a specific test case with 2 students (the first student did 2 attemps at the test and the second student did only 1 attemp).
![image](https://user-images.githubusercontent.com/6579268/89998309-a716a500-dc8d-11ea-8fa7-be23f0d4c95b.png)

**Comment by carlangas159** [comment]
With the change that is made in the PR #3445 , the average is counted by all the attempts made by the students.

If the student performs the exercise 2 times, the progress bar shows 1 /? where the question is the number of students enrolled in the course and the average is calculated based on the 2 attempts.Con el cambio que se realiza, el promedio se cuenta por todos los intentos realizados por los estudiantes.

**Comment by ywarnier** [comment]
@NicoDucou Indeed, that's another issue. Let's leave it at this for now. Please register another issue (for 2.0) with the new bug you found. In my opinion, there is no way to reduce these values to simply "the number of students" who picked the answer, because any student having more than 1 attempt would mess this up (if not mess up the value shown, it would mess up the meaning of it). Instead, we should change the text and say "Number of times this answer was selected / Number of times the test was passed" (i.e. number of attempts by all students).
In the end, if you want something super precise, you should always limit your exercises to one attempt.
