### ISSUE TITLE
Cursos con SCORM no guardan el avance en 1.11.10 oficial.  Pero sí en 11.chamilo.org

### ISSUE THREAD

**Issue by Cerebrando** [chamilo/chamilo-lms#3436]
**Describe el problema**
Al cargar lecciones scorm (generadas en cualquier herramienta de autor) o incluso crearlas directamente en Chamilo 1.11.10 el avance no se guarda.  Pero al probar en https://11.chamilo.org/ todo funciona perfectamente.  Hay algún cambio que se haya realizado en 11.chamilo.org que no tenga la versión oficial disponible para descarga?

**Cómo reproducir**
En versiones 1.11.10: 
1.- Cargar archivo scorm 
2.- Ingresar como estudiante al curso, avanzar 2 o 3 pantallas, quitar el curso, ya sea desde chamilo o cerrando el navegador.
3.- Revisar el reporte del curso y verificar el tiempo del participante.
4.- No se encuentra tiempo ni acceso marcados.
5.- Si el estudiante vuelve a ingresar no muestra ningún avance.

En la versión para test 11.chamilo.org funciona perfectamente y al ingresar nuevamente al curso mantiene la última posición.

**Comportamiento esperado**
Se espera que el usuario final pueda llevar el curso a su ritmo y retomarlo cuando lo necesite, incluso cerrando la ventana del navegador debiera guardar los avances.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Cualquier sistema operativo
 - Navegador:  Chrome 84.0, 

**Servidor
 - Sistema operativo : linux
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 7.3.6

**Contexto adicional**
Lo que me intriga es funciona muy bien en 11.chamilo.org

Quedo atento a su apoyo para entender y tomar las medidas necesarias para solucionarlo.

**Comment by ywarnier** [comment]
@Cerebrando la versión 1.11.12 estará publicada dentro de unos días y lo más probable es que arregle el problema (es lo que tenemos en 11.chamilo.org).
