### ISSUE TITLE
It was not possible to install the chamilo version 1.11.12 betas.

### ISSUE THREAD

**Issue by bassuma** [chamilo/chamilo-lms#3443]
Hello.
I was unable to install the chamilo to test. I tried both betas.
https://github.com/chamilo/chamilo-lms/tree/v1.11.12-beta.1
https://github.com/chamilo/chamilo-lms/tree/v1.11.12-beta.2
Error in subdomain and domain.
vps
php7.4
mariadb 10.4
apache 2.4
Follows image of the error.
beta1
![beta 1](https://user-images.githubusercontent.com/25286516/90009942-614de280-dc75-11ea-9ade-89e5bce933fa.png)

or
beta2
![beta 2](https://user-images.githubusercontent.com/25286516/90009997-788cd000-dc75-11ea-8bbb-bfd2ec8b79b0.png)

greetings

**Comment by AngelFQC** [comment]
I test with beta2 tar.gz
Installation work with 7.4.3

**Comment by ywarnier** [comment]
@bassuma it's counter-intuitive, I know, but the packages prepared by Github do not work. You have specifically to download the one that's called chamilo-1.11.12-beta.2-php7.3.tar.gz and it should work with 7.3 and 7.4 (although you might get aa few warnings, but not a fatal error).
Thanks for testing!

**Comment by ywarnier** [comment]
In "Assets" here: https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.12-beta.2

**Comment by shabsshab** [comment]
How can we upgrade from 1.11.10 to 1.11.12 without lossing the configuratiton and data?
In System its still shows "Your version is up-to-date: Chamilo 1.11.10" how we can get the notification of latest upgrade here ?

**Comment by ywarnier** [comment]
@shabsshab the upgrade is very easy: overwrite your setup with the files from 1.11.12, then change 'software_version' in app/config/configuration.php to 1.11.12.

The 1.11.12 version is ready but has not officially been announced yet (we leave a few additional days for users to report critical issues). Once it is announced, we will update our servers to show that 1.11.12 is the latest stable version.

**Comment by bassuma** [comment]
Hello.
To all.
I managed to install the chamilo.
Thank you
