### ISSUE TITLE
Gamification feature seemingly changes nothing

### ISSUE THREAD

**Issue by CrowCakes** [chamilo/chamilo-lms#3447]
**Describe**
Gamification features seemingly not appearing

**To Reproduce**
1. Activate gamification mode from administration panel
2. Go to an existing course, or create a new course
3. Inspect an existing learning path, or create a new learning path and populate it
4. In the learning path menu, click on the gamification button (trophy icon)

**Expected behavior**
Seemingly nothing changed from the regular interface, whether in teacher or student view or logged in as an enrolled student.

**Server
 - Version of Chamilo:  1.11.10

What exactly are the features of gamification?

EDIT:
I reactivated table of contents on a learning path and saw a change: four stars above the progress bar and the sum of all quiz scores. Are there any other features of gamification?

**Comment by ywarnier** [comment]
Hi @CrowCakes 
Not really any additional thing, no. This is an incomplete implementation in our view (although it suited the people asking for it just fine as it is).
What it does (saying that from what I can remember) is it assumes you have at least 3 chapters in your learning path, with a quiz at the end of each chapter. If you "pass" all tests, you get 3 stars. The only way to get 4 stars is to pass the average of all tests with more than 80% or so.

**Comment by ywarnier** [comment]
I want to add that the initial goal of the project was to give you "points" (number of stars) for all activities in Chamilo and then rank you in a scale of types of users (sailor, captain, ...) on the social network, but there were considerable issues we didn't manage to solve in a timely manner, like what happens with very old "points" (do you forget about them after a certain time?) or do you want the types of users to be based on the type of course (do "marketing" courses put you in the same ranking as "computer science" courses?), etc
