### ISSUE TITLE
 Created classes but not listed in the class page

### ISSUE THREAD

**Issue by shabsshab** [chamilo/chamilo-lms#3448]
I have created classes but its not listing in the class page but the same classes wil be visibe from course page 

Created classes but not listed here .
From Administrator Tab--> Under users, Classes--> Create Class
https://prnt.sc/tyrktn

The created class is visible inside course
Open Course page-->Users-->Select Classes Tab.
https://prnt.sc/tyrl3i

**Comment by ywarnier** [comment]
Thanks for reporting. This was introduced very recently when fixing another issue, and it slipped between our tests.
I have made an emergency re-packaging and the 1.11.12 package now available is updated with a fix to that.

**Comment by ywarnier** [comment]
Fixed with one added word here, by the way: c8f638b78c70229a38de27787500709c201f0920 (so you could patch it manually instead of downloading the whole package again)

**Comment by shabsshab** [comment]
Thank you.
Iam going to upgarde from 1.11.10 to 1.11.12.So will fix in that upgrade

I have made an emergency re-packaging and the 1.11.12 package now available is updated with a fix to that.==>Do you hav the updated link to download for beta.3  : https://github.com/chamilo/chamilo-lms/tree/v1.11.12-beta.3

To upgrade to 1.11.12 , Can I Just replace all files and folder in the Chamilo root folder with v1.11.12 files except install folder.

**Comment by shabsshab** [comment]
Thank you.
Iam going to upgarde from 1.11.10 to 1.11.12.So will fix in that upgrade

I have made an emergency re-packaging and the 1.11.12 package now available is updated with a fix to that.==>Do you hav the updated link to download for beta.3 

To upgrade to 1.11.12 , Can I Just replace all files and folder in the Chamilo root folder with v1.11.12 files except install folder.

**Comment by ywarnier** [comment]
Yes. Even the install folder can be there, it's just a recommendation to remove it but there's code in place to avoid issues.

**Comment by shabsshab** [comment]
Do you hav the updated link to download for 1.11.12 package

**Comment by ywarnier** [comment]
Sure: https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.12 pick the format you want from the first 4. The last 2 are built automatically based on git and do *not* have all the required file to work as a standalone system.

**Comment by shabsshab** [comment]
Thank you so much .....

**Comment by shabsshab** [comment]
I have upgraded and all existing class is visible now.

But Issues now:
1. We cannot add new classes by admin/session administration
2.Created classes can be seen by only admin but not by session administrator

Error in page while creating new classes : HTTP ERROR 500
Error in /var/log/httpd error_log : 

PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'author_id' in 'field list' in /home/live.4stechnologies.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127\nStack trace:\n#0 /home/live.4stechnologies.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(127): PDOStatement->execute(Array)\n#1 /home/live.4stechnologies.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(153): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /home/live.4stechnologies.net/main/inc/lib/database.lib.php(483): Doctrine\\DBAL\\Statement->execute(Array)\n#3 /home/live.4stechnologies.net/main/inc/lib/model.lib.php(191): Database::insert('usergroup', Array, false)\n#4 /home/live.4stechnologies.net/main/inc/lib/usergroup.lib.php(1331): Model->save(Array, false)\n#5 /home/live.4stechnologies.net/main/admin/usergroups.php(92): UserGroup->save(Array)\n#6 {main}\n\nNext Doctrine\\DBAL\\Driver\\PDOException: SQLSTATE[42S22]: **Column** not found: 1054 Unknown column 'author_id' in 'field l in /home/live.4stechnologies.net/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 60, referer: https://live.4stechnologies.net/main/admin/usergroups.php?action=add

**Comment by shabsshab** [comment]
I have reistallled completely now its  works

**Comment by ywarnier** [comment]
It is likely you previously enabled this setting without executing its SQL requirement:
```
// Teachers can CRUD classes
// ALTER TABLE usergroup ADD author_id INT DEFAULT NULL;
//$_configuration['allow_teachers_to_classes'] = false;
```

**Comment by shabsshab** [comment]
Yes  I  remember it was enabled 
Great Thank you
