### ISSUE TITLE
add_users_to_usergroup gives a blank page

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3453]
**Describe**
I get a blank page when I add a learner/s to a class
"add_users_to_usergroup"

**To Reproduce**
1. Administration
2. Click on 'Classes'
3. Select users and click Subscribe users to class

**Expected behavior**
The status of the subscribed students

**Screenshots**
Blank white page

Desktop (please complete the following information):
    Browser waterfox (firefox) version 2020.07.01 (64bit)

**Server
OS Linux CENTOS 7.8 64 bit
    Version of Chamilo: 1.11.12 (Updated from 1.11.10)
    Version of PHP: 7.2

**Additional context**
When I refresh the page I see the updated names.
On the error log - nothing reported.

**Comment by ywarnier** [comment]
I don't see that issue. For me it works correctly. Adding the users adds them and returns me to the classes list.

**Comment by kemoche** [comment]
Thanks Warnier,
I have realized it the clockworksms plugin that was causing the error. I have disabled it and all is well on both issues posted.
Thanks for time.
Cheers
--------------------
Warning: Use of undefined constant CONFIG_SECURITY_API_KEY - assumed 'CONFIG_SECURITY_API_KEY' (this will throw an Error in a future version of PHP) in /home/xxxx/public_html/lms/plugin/clockworksms/lib/clockworksms.lib.php on line 103

Warning: Cannot modify header information - headers already sent by (output started at /home/xxxx/public_html/lms/plugin/clockworksms/lib/clockworksms.lib.php:103) in /home/xxxx/public_html/lms/main/inc/lib/template.lib.php on line 1647

Warning: Cannot modify header information - headers already sent by (output started at /home/xxxx/public_html/lms/plugin/clockworksms/lib/clockworksms.lib.php:103) in /home/xxxx/public_html/lms/main/inc/lib/template.lib.php on line 1649

Fatal error: Uncaught Error: Call to a member function send() on null in /home/xxxx/public_html/lms/plugin/clockworksms/lib/clockworksms.lib.php:114 Stack trace: #0 /home/xxxx/public_html/lms/main/inc/lib/api.lib.php(9266): Clockworksms->send(Array) #1 /home/xxxx/public_html/lms/main/inc/lib/usermanager.lib.php(625): api_mail_html('Test Account', 'ah@xxx.co.ke', '[MIC E-Learning...', '<p>Dear Test Ac...', 'System Administ...', 'webmaster@xxxx...', NULL, NULL, NULL, Array, '') #2 /home/xxxx/public_html/lms/main/auth/inscription.php(736): UserManager::create_user('Test', 'Account', 5, 'ah@xxx.co.ke', 'ah@xxx.co.ke', 'xxxx', '11223344', 'english', '0700112233', NULL, 'platform', Object(DateTime), 1, 0, Array, NULL, true, false, '', false, Object(FormValidator)) #3 {main} thrown in /home/xxxx/public_html/lms/plugin/clockworksms/lib/clockworksms.lib.php on line 114
----------------------
