### ISSUE TITLE
Timepicker Increment enabled/ Getting wrong date in agenda

### ISSUE THREAD

**Issue by shabsshab** [chamilo/chamilo-lms#3457]
**Describe**
While adding schdule in  Agenda by defualt we will have :00 and :30 in the time picker.
I need  other times in the timepicker like :15 or multiple of 5 and adjusted the value in configuration file "timepicker_increment", this is causing wrong calculation while creating repeat event for weekly/monthly/ yearly

**To Reproduce**
1.Uncomment below in the configuration file
$_configuration['timepicker_increment'] = 15;

2.Create Agenda inside course ,select custom range ,repeat event ,weekly for 1 month  and then add Event
3.You can see the created times and dates  are wrong and its seeme like that increment is getting added 

Chamilo Version : 1.11.12

**Comment by NicoDucou** [comment]
I just tried to reproduce this issue and it works fine for me on a Chamilo 1.11.x updated today as you can see below, all the repeated element are with the correct time : 
![image](https://user-images.githubusercontent.com/6579268/90651542-6abee800-e23d-11ea-900b-9516d4e62c70.png)

**Comment by shabsshab** [comment]
Yes you have tried Daily and it will work
I have mentioned only repeat event for weekly/monthly/ yearly.

Please check once again

**Comment by shabsshab** [comment]
Screenshot : https://prntscr.com/u2b6ac

**Comment by NicoDucou** [comment]
Hi @shabsshab 
I just tried weekly and monthly repetition and it worked fine as you can see below : 
![image](https://user-images.githubusercontent.com/6579268/90665606-8ed5f580-e24c-11ea-8067-9ad0646be1a9.png)

**Comment by ywarnier** [comment]
Sorry @shabsshab , we cannot reproduce this. If you manage to have a more precise use case where we are likely to be able to repeat the conditions to generate this issue, please re-open and let us know.
