### ISSUE TITLE
Invalid date.timezone value ''Africa/Nairobi';

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3458]
**Describe**
When I attempt to create an agenda, I get a blank page. 
Running on test server mode I have the below error:
_
> Warning: mktime(): Invalid date.timezone value ''Africa/Nairobi';', we selected the timezone 'UTC' for now. in 
/home/xxx/public_html/main/inc/lib/api.lib.php on line 4032
> Warning: date_default_timezone_get(): Invalid date.timezone value ''Africa/Nairobi';', we selected the timezone 'UTC' for now. in /home/xxx/public_html/main/inc/lib/internationalization.lib.php on line 596
_

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser latest Waterfox, chrome, firefox

**Server
 - OS: CENTOS 7.8
 - Version of Chamilo:  1.11.12
 - Version of PHP: 7.3

**Additional context**
Nairobi is +3 GMT.

**Comment by ywarnier** [comment]
This seems to be a simple typo. The error message reports your date.timezone is `Africa/Nairobi';'` instead of `Africa/Nairobi`.
Please make sur you type them in correctly in your php.ini (or wherever else you are configuring those)

**Comment by kemoche** [comment]
Thanks - found the 'Africa/Nairobi'; quoted in both php.ini and user.ini, which I have deleted.
Its working fine now. Thanks - appreciate great your assistance.
