### ISSUE TITLE
No guarda puntuación de pregunta tipo "Abierta"

### ISSUE THREAD

**Issue by damisio** [chamilo/chamilo-lms#3460]
**Describe**
Al "corregir y puntuar" no guarda la puntuación y comentario.

**1. DOCENTE - AL VER EXAMEN DE ESTUDIANTE**
Al abriri el examen de un extudiante  el sistema muestra el siguiente mensaje: **_Nota temporal: 1 pregunta(s) abierta(s) no corregida(s) todavía._**

**2. DOCENTE - MOMENTO DE  PUNTUAR**
- El docente ha procedido en "corregir y puntuar"; agrego el comentario "no tiene respuesta" y asigno el pontaje 0.
- Al momento de guardar. Se observa que no ha sido guardado correctamente y sigue mostrando el siguiente mensaje: **_Nota temporal: 1 pregunta(s) abierta(s) no corregida(s) todavía._**
- Y sigue mostrando (?) en la nota

![Selección_094](https://user-images.githubusercontent.com/10108808/90806880-43225b00-e2e3-11ea-89db-6d7faf3cb528.png)

- En el punto (1) Al calificar y guardar sigue mostrando  (?)
- En el punto (2) no guarda comentario asignado
- En el punto (3) no se guarda la puntuacion asignada

**Desktop (please complete the following information):**
 - Browser [chrome]

**Server

 - Version of Chamilo:  [1.11.10]

**Comment by ywarnier** [comment]
Hola @damisio 
Esto solo sucede al darle una nota de 0, verdad?

**Comment by damisio** [comment]
Hola @ywarnier
Así es, eso solo sucede al darle 0. Como puedo resolverlo para que al darle 0 y al agregar una descripción se guarde. Y ya no muestre el mensaje  
**Nota temporal: 1 pregunta(s) abierta(s) no corregida(s) todavía.**

Saludos,
Joel

**Comment by AngelFQC** [comment]
Puede que en la versión actual esté corregido

![imagen](https://user-images.githubusercontent.com/1697880/91622928-00095d00-e95f-11ea-8be4-8b4bb2af9a38.png)

**Comment by ywarnier** [comment]
Hola @damisio 
Parece que en la última versión está corregido. Estaremos publicando una versión 1.11.14 dentro de unos días. Esperamos corrija el problema para ti. Sino, no dudes en volver a abrir esta tarea y darnos más información para poder reproducirlo.
