### ISSUE TITLE
Ampliar reporte en informe de plataforma

### ISSUE THREAD

**Issue by carlangas159** [chamilo/chamilo-lms#3461]
Una nueva funcionalidad que Permita ampliar el informe en la sección de plataforma, la cual genere la cantidad de estudiantes inscritos en una lección por entidad.

ir a  "Administración" en la sección "Plataforma" entrar en  "Informes"
 
Se genere un reporte "Informe de usuario por entidad" y "Informe registrados por leccion por autor"  que pueda ser exportado a csv
 
![image](https://user-images.githubusercontent.com/18097392/90831271-fcdff280-e308-11ea-988a-19af4854d49f.png)

***Chamilo  1.11.x***

**Comment by ywarnier** [comment]
Implementado y aprobado por el usuario final
