### ISSUE TITLE
Consider Replacing Webserver based url rewrite in favour of PHP based routing

### ISSUE THREAD

**Issue by otobio** [chamilo/chamilo-lms#3467]
At the moment, some setups of nginx and apache still get 404 errors after a course is created. with various possible reasons for this. This kind of issue should really _only_ be as a result of undefined route.

I think moving away from webserver rewrite might solve this issue once and for all

see links below for report of this issue;
https://forum.chamilo.org//viewtopic.php?f=44&t=7677
https://support.chamilo.org/issues/8198

Just to list a few

**Comment by ywarnier** [comment]
Hi @otobio 
Both reports are more than 4 years old. Considerable improvements have been made in both the installation guide and the installation procedure to prevent these issues in current versions.
Using PHP-based redirections (like in most modern frameworks) uses web server redirections anyway, so your suggestion doesn't seem like a solution to me, but good try.
