### ISSUE TITLE
Archivos adjuntos en Tareas (Assignments)

### ISSUE THREAD

**Issue by iruizsur** [chamilo/chamilo-lms#3469]
Solicitud:
La herramienta TAREAS (assignments) no tiene una opción para ADJUNTAR archivos por parte del profesor. Es complicado para el profesor porque si necesita proporcionar a un alumno algún archivo para la tarea, hay que hacerlo con enlaces y son muchos pasos para ponerlos como links.

Solución:
Que la herramienta TAREAS tuviera al menos un botón para adjuntar archivos por parte del profesor, deseablemente un archivo local, un archivo que se encuentre cargado en documentos o inclusive un enlace a un archivo en nube.

**Contexto adicional**
Creo que anexar archivos es una función esencial (ahora es muy complejo, la mayoría de LMS lo contemplan). Tareas de chamilo integrado con assignments de google (disponible con LTI)  o algo que sea muy similar sería excelente.
![issuetareas](https://user-images.githubusercontent.com/16807565/90971293-4466aa00-e4d4-11ea-97e3-aa6ce953aac9.png)

**Comment by ywarnier** [comment]
Esto ya es posible. Cuando has creado la tarea, dale clic al título de la tarea, y luego en el segundo icono (después de la flecha azul hacia la izquierda) "Añadir documento". Te da un navegador de archivos de la herramienta de documentos.

**Comment by iruizsur** [comment]
Gracias, la verdad no se nos había prendido el foco de salir y hacerlo así... llevamos muchos años usando Chamilo. Nos gustaría colaborar en ampliar la documentación de cosas que no están en el manual.
