### ISSUE TITLE
Exercises - inactive settings buttons !

### ISSUE THREAD

**Issue by xam1234** [chamilo/chamilo-lms#3470]
**Describe**
After adding diffrent type of questions some options buttons become inactive.

![obraz](https://user-images.githubusercontent.com/32258255/91031546-074c0600-e601-11ea-8709-8bb702b277b4.png)

**To Reproduce**
Add two questions "multiple choice" and "multiple answers" -> edit test settings (two options are inactive) -> change feedback to "Direct feedback as pop-up" save and edit (multiple options are inactive)
Check it on: 
https://11.chamilo.org/main/exercise/exercise_admin.php?cidReq=TEST1122&id_session=0&gidReq=0&gradebook=0&origin=&modifyExercise=yes&exerciseId=456

I've tested it on chamilo 1.11.12 and 11.chamilo.org (24.08.2020)

**Comment by ywarnier** [comment]
This is as expected. Those types of tests do not support all question types (a very limited subset, actually). I won't get into the details (because there's a very long and logical explanation to this), but this is a feature, not a bug.
