### ISSUE TITLE
Portal News Mail are From: Admin <admin@example.com>

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3473]
**Describe**
I have noticed from the server end - Mail Delivery Reports - that the email sent from the articles/items posted in the Portal News indicate they are from Admin <admin@example.com>  - which is misrepresentation.

**To Reproduce**
1. Administration -> Portal news -> New
2. Click on 'Send mail'
3. No error

**Expected behavior**
Mail to be sent from email address-> System Administrator<webmaster@mydomain.ac.ke> which Portal Administrator: e-mail.

**Mail Headers** 
Date: | Mon, 24 Aug 2020 12:46:20 +0000 -- | --
From: | Admin <admin@example.com>
To: | Online Student <info@mydomain.ac.ke>
Subject: | =?us-ascii?Q?You_have_a_new_message_from_System_Administrato?=  =?us-ascii?Q?r?=
Content-Transfer-Encoding: | 8bit
Content-Type: | multipart/alternative;  boundary="b1_SVaxsiEBuVrJgu5eqB0E5lau0fIMVySkEbFCYr8A"
Delivered-To: | info@mydomain.ac.ke
Delivery-date: | Mon, 24 Aug 2020 15:46:20 +0300
Envelope-to: | info@mydomain.ac.ke
Errors-To: | webmaster@mydomain.ac.ke
Message-ID: | <SVaxsiEBuVrJgu5eqB0E5lau0fIMVySkEbFCYr8A@mydomain.ac.ke>
MIME-Version: | 1.0
Received: | from xxx.mydomain.co.ke  by xxx.mydomain.co.ke with LMTP  id K8flFJy2Q19LHAAAhmIAmg  (envelope-from <admin@example.com>)  for <info@mydomain.ac.ke>; Mon, 24 Aug 2020 15:46:20 +0300
Received: | from miconlineac by xxx.mydomain.co.ke with local (Exim 4.93)  (envelope-from <admin@example.com>)  id 1kABrg-0001sk-6u  for info@miconline.ac.ke; Mon, 24 Aug 2020 15:46:20 +0300
Reply-To: | System Administrator <webmaster@mydomain.ac.ke>
Return-Path: | <admin@example.com>
Return-path: | <admin@example.com>
X-Mailer: | PHPMailer 6.1.7 (https://github.com/PHPMailer/PHPMailer)
X-PHP-Originating-Script: | 1006:PHPMailer.php
X-PHP-Script: | mydomain.ac.ke/main/admin/system_announcements.php for IP 154.70.50.86
X-Priority: | 3

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - Browser waterfox, chrome, firefox

**Server
 - OS: [e.g. Linux CentOS 7
 - Version of Chamilo:  1.11.12
 - Version of PHP: 7.2

**Additional context**
How do I change <admin@example.com> to <webmaster@mydomain.ac.ke>
I have checked both in the DB + both the /main/lang/english/trad4all.inc.php & /main/admin/system_announcements.php and could not locate the email address <admin@example.com>.

**Comment by ywarnier** [comment]
You can change the e-mail sending configuration through the app/config/mail.conf.php file.
This gives you a relatively large number of possibilities (unique_sender being the one you probably want, together with admin_mail)
