### ISSUE TITLE
Error on Admin Report View Dials 

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3474]
**Describe**
As recent as Saturday 23/08, from the Admin Reporting tab, I could see the total number of students registered on the Followed students dial.  Today the it shows 0 Followed students.
I have compared the 2 databases backups and attached is the dashboard view on 18/08/2020 and today 24/08/2020

**To Reproduce**
1. Go to Admin Reporting
2. Look at the dashboard
3. See error

**Expected behavior**
I expected to see the number of registered students on the Followed students - dial

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser waterfox, chrome, firefox - latest version

**Server
 - OS: CentOS 7
 - Version of Chamilo:  1.11.812
 - Version of PHP: 7.2

**Additional context**
All the dials show 00 - which should not be the case.
I have also checked the error logs - I find nothing after the Invalid date.timezone value ''Africa/Nairobi'; which we resolved.
![Report view 1808](https://user-images.githubusercontent.com/69464866/91073244-71859a80-e643-11ea-962a-43e6414e82d8.jpg)
![Report view 2408](https://user-images.githubusercontent.com/69464866/91073248-734f5e00-e643-11ea-9130-6a45c0e04b39.jpg)

**Comment by ywarnier** [comment]
Followed students are either the number of students in a course where you are a teacher, or (another dial) the number of students for which you have been selected as a follower (privilege only accessible to admins and HR managers).

**Comment by ywarnier** [comment]
Please check on our forum https://forum.chamilo.org if an issue you think is an issue is really one, or whether it is because you don't know Chamilo well yet.
This space is not a support forum. It is open to report bugs or request features, but we assume our users to have sufficient previous knowledge of Chamilo.
Please read our manual at https://docs.chamilo.org/
