### ISSUE TITLE
Anuncios no llegan al correo del usuario

### ISSUE THREAD

**Issue by Missgarner** [chamilo/chamilo-lms#3478]
**notificación no llega a correo**
Al confeccionar un anuncio en cada curso este no llega con copia a los correos de los alumnos. Sucede en algunos cursos. 

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'curso'
2. Dar clic en 'anuncios' 'nuevo anuncio' 'enviar este anuncio por correo electrónico'

No salta ningún error, pero no llegan los anuncios correspondientes

**Comportamiento esperado**
Confeccionar un anuncio y que llegue notificaciones a correos

**Capturas de pantalla**
No sé adjuntan porque no muestra msj de error

**Escritorio**
 - Sistema operativo : todos
 - Navegador todos

**Servidor
 - Sistema operativo : CentOS 7
 - Versión de Chamilo:  1.11.10
 - Versión de PHP: 7

**Comment by PapaChino** [comment]
Hola, Tengo 3 plataformas instaladas y recientemente actualizadas a la última versión 1.11.12, también se reproduce el mismo inconveniente en 2 de ellas, sólo una puede enviar una copia a los correos de los destinatarios de los anuncios.

**Comment by ywarnier** [comment]
Buenas @Missgarner, @PapaChino ,
Nos ha tomado un tiempo responder. Hemos observado también una mayor tasa de correos que no llegan este año, pero después de darles mil vueltas, solo llegamos a una conclusión: se trata de los servidores de correos de llegada, que tienen reglas más y más estrictas cada vez. Usando servicios como MailJet, MailGun, SendInBlue, MailChimp, etc desde Chamilo (reconfigurando app/config/mail.conf.php), estos correos siempre llegan.

Usando un servidor de correos dedicado y en una IP con buena reputación también siempre llegan (aunque a veces en el buzón de SPAM).

Hemos trabajado mucho también en las funcionalidades adicionales de firma de correos (DKIM, DMARC) en mail.conf.php para poner todas las oportunidades de nuestro lado, pero nada de esto es tan importante como la reputación del servidor de envío.

Por tanto, cierro esta tarea, sabiendo con tranquilidad que ya no podemos hacer nada del lado de Chamilo.
