### ISSUE TITLE
No muestra resultados en los ejercicios 

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [chamilo/chamilo-lms#3479]
Hola buenas tardes.

Tengo un problema con visualizar los resultados de los ejercicios, en el apartado de ejercicios, estaba usando un chamilo en versión 1.11.10 y no me mostraba ningún tipo de error en este apartado, actualice a la ultima versión de hoy mismo (25 de agosto 2020) que es 1.11.12, pero ya no me muestra los resultados de los ejercicios, ni en lo nuevos que creo, ni de los antiguos que tenia en los cursos. 

![image](https://user-images.githubusercontent.com/41083269/91221899-063fd500-e6e4-11ea-9cdb-60181c46595b.png)

Cuando le doy al boton recalcular me muestra el siguiente mensaje.

![image](https://user-images.githubusercontent.com/41083269/91221967-1ce62c00-e6e4-11ea-9ff3-507b80c7e735.png)

Ya borre cache, del cahmilo, actualice composer, borre cache de composer, tengo los permisos adecuados en la carpeta y sigo sin verlos.

Algo curioso es que si los puedo visualizar desde el apartado de informes, donde veo a alumno por alumno pero desde el apartado de ejercicios nada. 

![image](https://user-images.githubusercontent.com/41083269/91222027-38513700-e6e4-11ea-97fa-972eaf76b4c3.png)

Tengo que configurar algo mas ahora que actualice chamilo.

Actualmente esta bajo un servidor Ubuntu server y la base de datos esta en mariadb.

Gracias por su ayuda.

**Comment by aragonc** [comment]
@CamiloPerezOrtiz Es un error detectado, también me paso..

**Comment by CamiloPerezOrtiz** [comment]
Aplicando la prueba y error encontré este error, que me manda el framework, dando inspeccionar en el navegador este archivo estaba mandando un error, ruta del archivo main/inc/ajax/model.ajax.php el cual es lo siguiente:

![image](https://user-images.githubusercontent.com/41083269/91234280-8708cc00-e6f8-11ea-91eb-ac6d823fd43e.png)

Seguiré checando haber si logro encontrar mas detalles del error

**Comment by CamiloPerezOrtiz** [comment]
Buenas tardes.

Gracias @AngelFQC  ya me muestra los resultados de los examenes otra vez, tanto de los viejos como de los nuevos que se crea. 

De igual manera ya realice pruebas y hasta el momento no ha fallado, tanto en grupos nuevos, como en grupos viejos.

![image](https://user-images.githubusercontent.com/41083269/91623506-5d061280-e961-11ea-9bb5-5aa414072312.png)

Gracias
Cierro el problema.
