### ISSUE TITLE
Problema de chequeo de Encuesta (Survey) cumplida

### ISSUE THREAD

**Issue by Cerik2005** [chamilo/chamilo-lms#3482]
**Describe el problema**
Tras la actualizacion a version LMS 1.11.12 las encuestas no se chequean en el reporte  al cumplirlas ,   antes aparecían en el reporte 0 / 1 o 1 / 1 ahora solo aparece 0 / 0 . 

Las encuestas están asignadas a los alumnos 
El alumno puede acceder sin problemas a las encuestas y cumplirlas pero no se chequean si se cumplen

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'Informes' en cualquier curso
2. Ver columna 'Encuesta'

**Comportamiento esperado**
Columna 'Encuesta' debe marcar 0 /1 si no se ha cumplido y 1 / 1 si ya se cumplio 

**Capturas de pantalla**

Antes
![2020-08-26_19-14-32](https://user-images.githubusercontent.com/3900919/91365983-7e83c480-e7d0-11ea-8274-3d83f289b7b3.png)

Ahora 
![2020-08-26_19-07-40](https://user-images.githubusercontent.com/3900919/91365903-39f82900-e7d0-11ea-9b59-91171a62e487.png)

**Comment by AngelFQC** [comment]
Hi @Cerik2005 
I sent a fix in 0dc038e343e0e97f7b6c69ce2ff10cc5324ac789

**Comment by Cerik2005** [comment]
thanks , it's fixed
