### ISSUE TITLE
Broken images and certificate unresolved variables on fresh installations

### ISSUE THREAD

**Issue by LolaCapitani** [chamilo/chamilo-lms#3484]
Hello to everyone!

Every time we install Chamilo (fresh install) there is a problem with the visualization of the images and some problems with variables not solved in the course certificate.

https://mega.nz/file/eINUCIJb#GDY5ifCWbvxUKvoZhjg7fL43DhRaIQ4g7iYNHgXgSS4

As you can see from the video, neither the .PNGs of the templates nor those of the certificate are loaded. 

Also, if I insert the certificate inside a module, variables (e.g.: user_firstname; user_lastname; gradebook_institution; etc etc.) are not resolved.

I suppose it's an installation "path" problem that is not "recognized" in these pages.

We install with Softaculous in a folder dedicated to the platform, so not in the main root. Maybe this is the problem?

We are solving temporarily replacing by hand with absolute paths, but this creates other problems (i.e. the pdf of the certificate is missing images)!

Thank you!

Lola
(=^ ◡ ^=)

Desktop

OS: Linux Ubuntu 18.04 / Windows 10(64bit), Win 7(32 bit)
Browser CHROME 80.0.3987.87 , FIREFOX 78.01

Server

OS: Linux 3.10.0, LiteSpeed V7.6,
Version of Chamilo: 1.11.10
Version of PHP: PHP 7.2

**Comment by lonesomewalker** [comment]
To be honest: i never did an installation with softaculous.

But this looks like a problem with your server rewrite rules.

Have a look in your .htaccess (root folder installation of chamilo)
Is there any line which says
`RewriteBase .....`

Also, what does your app/config/configuration.php say with this setting:
`$_configuration['url_append'] = '';`

**Comment by LolaCapitani** [comment]
Hi @lonesomewalker ,
thank you for your kind answer.

Softacolous (softaculous.com) is on practically every "low cost" server. 

Chamilo is an official application installed by Softacolous! 
$_configuration['packager'] = 'Softaculous';  ----> /app/config/configuration.php

I believe that the majority of "normal" users like me have installed Chamilo through this server application which is available by default from most providers.

The convenience of Softacolous is that, for non-technical users like me, just press a button to have Chamilo installed and go.

I tried to install Chamilo via Softacolous  on two different servers, but the story is always the same. You can see the story perfectly in my video.

Other friends of mine, teachers in other schools, have also had the same problem. They don't see the template images and in the certificate they don't see both the images and the variables resolved (the latter problem only when the certificate is inserted in a module).

I have inserted the installation folder in the string on the file **$_configuration['url_append'] = '';** in **app/config/configuration.php**, now is: **$_configuration['url_append'] = 'cham';**

Thanks to your suggestion, we have taken a step forward. By entering the installation folder in **$_configuration['url_append'] = '';** now the **templates** are seen, the path is now read correctly!

This is therefore a Softacolous error that I will report on their forum. 

_But as for the path of the certificate images [/main/img/...png], nothing to do..._

In the  .htaccess file on root folder of Chamilo, there is not a string  which says RewriteBase .....

How can I do it?

This is my .htaccess file:

https://pastebin.com/iK3Jj8gn


Thank you very much for your help...

Lola
(=^ ◡ ^=)



Desktop

OS: Linux Ubuntu 18.04 / Windows 10(64bit), Win 7(32 bit)
Browser CHROME 80.0.3987.87 , FIREFOX 78.01

Server

OS: Linux 3.10.0, LiteSpeed V7.6,
Version of Chamilo: 1.11.10
Version of PHP: PHP 7.2

**Comment by lonesomewalker** [comment]
Hello @LolaCapitani 
well, running a LMS on a low cost server gives you a lot of issues... :-)

But i don't think this is a Softaculous error.
It is reccomended to install Chamilo in a root folder of a (sub)domain, so you better switch to:

https://www.hereyourlmsdomain.tld
or
https://chamilo.hereyourlmsdomain.tld
(as example)

Then the installation should not have issues like the ones you describe.

**Comment by AngelFQC** [comment]
Hi @LolaCapitani 

When you install Chamilo in a subdirectory, you must edit the `app/config/configuration.php` file to change the `url_append` configuration setting.

`$_configuration['url_append'] = 'chamilo_directory';` around the line 53.

---

On the other hand, in the video you are adding a certificate in the learnin path. I assume you want the certificate to be displayed at the end of the lesson, or something like that. But the way to show a certificate in the lesson is to add it through the "Certificate tab".
![imagen](https://user-images.githubusercontent.com/1697880/91908177-c7c09200-ec70-11ea-895d-c0bbf4cc0edd.png)


And also this learning path must be assigned in the gradebook.
