### ISSUE TITLE
Question type fill in blanks or form change blanks marker causes bug in question

### ISSUE THREAD

**Issue by roelvisje** [chamilo/chamilo-lms#3485]
When you create a fill in blanks type of question you use  [...] to create a part where a student can answer a question.
Today i was showing some teachers this feature and also wanted to show you can change the [...] part into something different
but when you use that option, the question bugs that the already used  [...] is gone…
the refresh terms button is also not working.
You cannot change back to the original setting since select a blanks marker is not working anymore.

before change
![fill in blanks or form](https://user-images.githubusercontent.com/51987964/91456847-0971c700-e884-11ea-8aaa-624f332f04e0.jpg)

after change
![bugged](https://user-images.githubusercontent.com/51987964/91456960-25756880-e884-11ea-85ff-26a8ce2dfcb8.jpg)

/edit/

ah, i see it is not a bug but sort a mistake in my case: the brackets also need to change form.
since i changed from [ -> (.. now and it works again… the text above didn't change so i thought it still needed the [] instead of ().. maybe that can be feature/enhancement then? the below (please define also still says [...]..

**Comment by roelvisje** [comment]
ah, i see it is not a bug but sort a mistake in my case: the brackets also need to change form.

since i changed from [ -> (.. now and it works again… the text above didn't change so i thought it still needed the [] instead of ().. maybe that can be feature/enhancement then? the below (please define also still says [...]..

**Comment by ywarnier** [comment]
@roelvisje We could reproduce the issue and have hopefully fixed it through the commit 4c57f126379b3870468fa60b515046b1f1dd70a4
If you know how to apply a commit on your installation and can report back to us, we'd love that very much. Otherwise, this issue will be considered fixed in 5 days from now (Wednesday).

**Comment by roelvisje** [comment]
@ywarnier i can confirm it works and is fixed by the commit.
