### ISSUE TITLE
Extra Field: "Lista desplegable con campo de texto" no muestra las opciones introducidas *Bug* *Chamilo 1.11.x*

### ISSUE THREAD

**Issue by carlangas159** [chamilo/chamilo-lms#3486]
**Describe el problema**
Estoy generando un campo extra para usuarios de tipo "Lista desplegable con campo de texto" 
![image](https://user-images.githubusercontent.com/18097392/91470703-a881c900-e85a-11ea-97e9-96ae296aea6a.png)

Luego le añado un conjunto de valores para mostrarlo en la lista
![image](https://user-images.githubusercontent.com/18097392/91470792-c6e7c480-e85a-11ea-8a72-c16adb986851.png)

Sin embargo, cuando accedo al perfil de usuario para establecer estos datos no muestra contenido alguno.
![image](https://user-images.githubusercontent.com/18097392/91470935-f8609000-e85a-11ea-9db5-9be98f0eeca1.png)

**Comportamiento esperado**
Se muestre la lista de elementos que he ajustado para mostrarse
![image](https://user-images.githubusercontent.com/18097392/91471055-22b24d80-e85b-11ea-9d78-9089b0e38bd0.png)

**Comment by ywarnier** [comment]
Se ve bien y veo que ya fue integrado a Chamilo. Bien!
