### ISSUE TITLE
Search Custom fields not working in user_list.php

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3488]
#3283 

In reference to above. Not sure if it went unnoticed but custom fields are not searchable as of 24-08-2020 (unless it was fix in between) So creating a new issue for this.

Describe
Created a User field made it filterable and enabled:

the error:
> $_configuration['user_search_on_extra_fields'] = ['extra_fields' = > ['variable1', 'variable2']];
> There is an error there that crashed the site imho the space in: ['extra_fields' = > ['variable1 should not be there removed it site 

was fixed in https://github.com/chamilo/chamilo-lms/commit/9aa5718a402a40b56685a6e7a833760a0ed55847

But extra field is not searchable. In advanced i can select the user field to search for but it will list all users.

Expected behavior
Enable the option and to be able to search/list extra user fields

Desktop (please complete the following information):

OS: win 10
Browser Chrome 83.0.4103.97 (Official Build) (64-bit)
**Server

OS: Centos 7
Version of Chamilo: 1.11.10 (updated via git pulls)
Version of PHP: 7.3

Additional context
Any more info on the extra fields options in general:
like user_field_field_order it does not do much.

**Comment by AngelFQC** [comment]
What is the extrafield type you are using?

**Comment by spacecabbie** [comment]
I have found out this was due to corruption in my local installation possibly relating the old issue it is working now it looks like
