### ISSUE TITLE
Error al instalar con xampp chamilo 1.11.12

### ISSUE THREAD

**Issue by yanamachay** [chamilo/chamilo-lms#3489]
estoy tratando de instalar en windows chamilo version 1.11.12 con xamp version 7.3.21  a la hora de querer instalar me sale este error y no me deja avanzar, alguien me da ayuda.

Fatal error: Cannot redeclare normalizer_is_normalized() (previously declared in C:\xampp\htdocs\vendor\symfony\polyfill-intl-normalizer\bootstrap.php:15) in C:\xampp\htdocs\vendor\patchwork\utf8\src\Patchwork\Utf8\Bootup\intl.php on line 20

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo :Windows 10
 - Navegador Google chrome Versión 85.0.4183.83 (Build oficial) (64 bits)

**Servidor
 - Sistema operativo : Windows server 2012
 - Versión de Chamilo:  1.11.12
 - Versión de PHP 7.3.21

Uso xampp
![Captura](https://user-images.githubusercontent.com/68559937/91648925-66f84600-ea33-11ea-9ff0-1de985de495b.PNG)

**Comment by dvadell** [comment]
Hola

Mismo problema con:
* Sistema Operativo: linux Ubuntu 20.04
* Navegador: Firefox 80
Servidor
* Linux Debian 10.3
* Version de Chamilo: 1.11.12-php7.2
* Version de PHP: 7.4.3

**Comment by dvadell** [comment]
Ya lo solucione: instale las extesiones de php: intl, gd, y curl.

**Comment by yanamachay** [comment]
gracias @dvadell

**Comment by ywarnier** [comment]
> Ya lo solucione: instale las extesiones de php: intl, gd, y curl.

Como indicado en el instalador, sí.

**Comment by ywarnier** [comment]
> gracias @dvadell ya logre instalar, ahora tengo el siguiente error
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in C:\xampp\htdocs\vendor\doctrine\orm\lib\Doctrine\ORM\UnitOfWork.php on line 2640

Como indicado en el manual, el uso de PHP 7.3 requiere desactivar el display de los errores de tipo warning. Ya se solucionará con un cambio de dependencias en Chamilo para la versión 2.0.
