### ISSUE TITLE
Course setting page cant access after migration

### ISSUE THREAD

**Issue by shabsshab** [chamilo/chamilo-lms#3491]
Cant access the page  Administaration-->configuration settings-->Course,  after migrating the server ,
Remaining all configuration settings page can access

Page : mydomian.com/main/admin/settings.php?category=Course

Error : This page isn’t workinghiraonlinemadrasa.in is currently unable to handle this request.
HTTP ERROR 500

httpd error log ;
[Tue Sep 01 02:37:52.706410 2020] [php7:error] [pid 3719] [client 13.234.238.75:18961] PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /home/mydomain.in/main/admin/settings.lib.php:1946\nStack trace:\n#0 /home/mydomain.in/main/admin/settings.php(107): generateSettingsForm(Array, Array)\n#1 {main}\n  thrown in /home/mydomain.in/main/admin/settings.lib.php on line 1946, referer: https://mydomain.in/main/admin/settings.php

**Comment by shabsshab** [comment]
@ywarnier , Ihave registered under forum as per your request for support enquiry  3 weeks before but still account not activated.
PLease assist to activate
usernam : shabeerkaruvattil
The specified username is currently inactive. If you have problems activating your account, please contact a board administrator.

**Comment by ywarnier** [comment]
@shabsshab Account enabled. Sorry about the delay. We're not used to this form of username and thought it was not legitimate.

**Comment by shabsshab** [comment]
THank you.

**Comment by shabsshab** [comment]
@jmontoyaa  , Please assist on the error message

**Comment by jmontoyaa** [comment]
I just added a fix

**Comment by shabsshab** [comment]
which fix added ?

issue is URL cannot access : https://mydomain.com/main/admin/settings.php?category=Course

**Comment by ywarnier** [comment]
Please see the link just above jmontoyaa's comment "I just added a fix". Github gives a meaningful history of changes in issues, but you still have to use it if you want to use the latest fixes.

**Comment by shabsshab** [comment]
Thank you its working...
