### ISSUE TITLE
Remote Chamilo Rapid config: a follow-up

### ISSUE THREAD

**Issue by CrowCakes** [chamilo/chamilo-lms#3492]
> You can actually setup a remote LibreOffice system *but* you will still require an installation of Chamilo there. I don't remember the details on how to do it, though. I think you just install another Chamilo on the remote server and point the Rapid system to that URL, and that's it... any chance you have time to try that out?
> 
> _Originally posted by @ywarnier in https://github.com/chamilo/chamilo-lms/issues/3102#issuecomment-594491048_

I've finally managed to test this out.

I have two installations, both on 1.11.12. Chamilo A is running on a Google Cloud VM, while Chamilo B is running on a commercial shared hosting site. Chamilo A's VM has a running instance of OpenOffice running in screen as specified in the docs. I entered Chamilo A's host URL on Chamilo B's config page, saved it, then attempted to convert a PPT file on Chamilo B. An error message then appears, saying that the conversion failed for an unknown reason. Chamilo A can use its Chamilo Rapid without errors.

No logs appeared on Chamilo A's or B's environment. The Google Cloud Project holding Chamilo A has a firewall rule to allow incoming TCP and UDP traffic on port 2002. I would have installed LibreOffice on Chamilo B's environment, but I don't have root access to the server.

**EDIT: nmap results on Chamilo A indicate that port 2002 is closed, apparently. Will do some configuration on Google Cloud's side and see if that fixes it.**

**EDIT #2: Configuring Chamilo A's Apache webserver to listen on port 2002 breaks the functionality, causing it to load forever on the conversion page. Checking the Apache error logs say "SEVERE: disconnected unexpectedly" after the connection to the LibreOffice was dropped**

**EDIT #3: Setting up an entirely different Google Cloud VM and a headless LibreOffice server then putting its host IP into Chamilo A results in the original problem that occurred in Chamilo B. Next step will be to setup a dummy Chamilo installation on this third VM, and open its port 2002.**

**EDIT #4: I've changed the soffice parameters on the dummy Chamilo, specifically the connection string, changing host from localhost to 0.0.0.0. This opened the port 2002 to external traffic, but attempting to use dummy's URL on the Chamilo Rapid on Chamilo A fails with the same error as in the screenshot below. Chamilo A error logs produces this message: "Chamilo SOAP call error: Unable to parse URL: ..."
The same problem arises when replacing the dummy Chamilo with the standalone LibreOffice server with the same adjustments made to it**

**To Reproduce**
0. Have 1 source Chamilo installation and 1 remote installation, both hosted on different platforms.
1. Setup OpenOffice on remote installation of Chamilo, as indicated in the documentation.
2. Setup Chamilo Rapid on both remote and source installation of both Chamilos. Remote installation sets host to "localhost," while source installation sets host to the URL of the remote installation.
3. Save the config on remote, then on source.
4. Attempt to use Chamilo Rapid on the source installation.
5. See attached screenshot below for the error message that will appear.

**Expected behavior**
On success, be brought to the learning path editing page.

**Screenshots**
![image](https://user-images.githubusercontent.com/21997146/92064456-16d10900-edd0-11ea-92be-f2b277ee19ec.png)

**Desktop (please complete the following information):**
Win 10, Google Chrome latest ver.

**Server**
Chamilo A
 - OS: Linux Debian 10 Buster
 - Version of Chamilo:  1.11.12
 - Version of PHP: 7.3

Chamilo B
- OS: Red Hat Linux (ver. no. unknown)
 - Version of Chamilo:  1.11.12
 - Version of PHP: 7.2

**Comment by CrowCakes** [comment]
I have tried this again on 1.11.10 builds.

An HTTP error 500 occurs after Chamilo B (now on an Ubuntu 18, Microsoft Azure) attempts to use Chamilo A's (Ubuntu 10, Google Cloud) LibreOffice service. In addition, on a 1.11.12 build, Chamilo B failed to use its own LibreOffice server, only working when I used a 1.11.10 build.

**Comment by ywarnier** [comment]
Hi @CrowCakes 
Sorry about the bad experience and the lack of feedback on our side. This is really a fringe setup we use once every few years maybe. The last time I personally set this up, it worked, but it's been several years ago and I don't remember the details.

I would say in any case (intuitively): don't focus on port 2002. The purpose of installing Chamilo on your Chamilo A is that Chamilo (on Chamilo A) will be the one answering and asking LibreOffice to do the conversion. As far as I remember, Chamilo B doesn't connect directly to LibreOffice on Chamilo A.

The related code for the call (from Chamilo B) is located here: https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/lp/openoffice_document.class.php#L302
As you will see checking this function, it connects to Chamilo on Chamilo A through SOAP, calling a service called `wsConvertPpt`.

If you look into the code for `wsConvertPpt`, you will find that Chamilo A answers the SOAP call through `main/webservices/additional_webservices.php`, and then simply converts what it got and returns the files (you can set an IP address filter in `app/config/configuration.php` called `ppt2lp_ip_filter`, but it is disabled by default). By adding a few lines of debug to this additional_webservices.php file, you should be able to find the issue for you.

Given the fact that *many* elements can fail in the way (between the two Chamilo's, like the size of POST requests, the memory limit, the ports, etc), I'm not sure this is really a Chamilo issue, but if you find it is, please re-open this issue and let us know.
