### ISSUE TITLE
Datos de usuario que se muestran sin haberse autenticado en la plataforma

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3493]
**Describe el problema**
Si se accede a la página https://11.chamilo.org/main/inc/ajax/user_manager.ajax.php?a=get_user_popup&course_id=125&user_id=20
Directamente, mediante la URL, se muestra la fotografía del usuario, y en caso de ser profesor  en la versión 1.11.10 se muestra también su nombre, sin necesidad de loguearse en la plataforma, y hasta puede ser indexado por buscadores.

**Cómo reproducir**
Ejemplos:
https://11.chamilo.org/main/inc/ajax/user_manager.ajax.php?a=get_user_popup&course_id=125&user_id=20
https://11.chamilo.org/main/inc/ajax/user_manager.ajax.php?a=get_user_popup&course_id=105&user_id=230

**Comportamiento esperado**
Esta información no debería ser accesible sin estar registrado.

**Servidor
 - Versión de Chamilo:  1.11.10 y 1.11.12

**Comment by ywarnier** [comment]
Agrego que debería ser posible ver esta información si el catálogo de cursos es público y se usa en mostrar los profesores, pero en este caso debe ser verificado que efectivamente son únicamente para los cursos que aparecen en el catálogo, y solamente para los profesores de este curso (ahora da la sensación que se puede variar el user_id y escanear todo).

**Comment by AngelFQC** [comment]
Hola @nosolored 
Podrías aplicar los cambios del PR #3495 para ver si está corregido?

**Comment by nosolored** [comment]
Ya no está visible esa información, es correcto.
Y si publicamos el catálogo y se hace clic en el profesor sí se muestra la información correctamente. Lo único en este caso es que la imagen del usuario no carga, y en el código fuente lo que aparece es img src(unknown) en el lugar donde debe mostrarse la imagen.

**Comment by AngelFQC** [comment]
En https://11.chamilo.org/main/auth/courses.php el catálogo está público y la imagen (por defecto) del profesor de los curos sí se muestra.
