### ISSUE TITLE
Display of the Users List (from Admin panel)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3496]
**Describe**
The users list isn't correctly displayed in Chamilo 1.11.12 : the 'action' column is too narrow => so, the rows are too high and the display of the list isn't easy to read on the screen (see the screenshot).

**To Reproduce**
1. Connect you as admin
2. Click on 'administration' tab
3. Click on 'users list'

**Screenshots**
![Capture2](https://user-images.githubusercontent.com/24507698/92301554-0aca8000-ef65-11ea-8fc3-c194fd3456a1.JPG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - FF / Chrome / Edge (last versions)

**Server
 - OS: Linux
 - Version of Chamilo:  1.11.12
 - Version of PHP: 7.4 

**Additional context**
On the same server, it works perfectly with chamilo 1.11.10
With Chamilo 1.11.12, the problem occurs whatever is the PHP version on the server (7.2 ; 7.3 ; 7.4) or whatever is the borwser on the desktop.

**Comment by AngelFQC** [comment]
Hi @tanchon 
The styles for tables in chamilo 1.11.12 are being fixed. Check 14bd40a23a545f8179da4fb7db17aeceea96faac 09be551d224ee9bff9e65220b9709ff57101c30b  7d0b021c115f3173f7d486cf34ec9e1ac13f5ebb

**Comment by tanchon** [comment]
Hi AngelFQC,
The user list is perfectly displayed now ! (and some other tables, as the standard course list which had the same problem...).

Everything seems to be ok ! Thanks a lot because it is now much more practical to use these tables !

Tanchon
