### ISSUE TITLE
Error al ejecutar composer update en Chamilo 1.11.12

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3497]
**Describe el problema**
Al ejecutar la instrucción de composer update en consola, devuelve este error:

PHP Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /var/www/html/chamilo-1.11/vendor/ocramius/package-versions/src/PackageVersions/Installer.php on line 34

Ocurre tanto en PHP 7.2 como en PHP 7.3 (también 5.6 y 7.1)
En PHP 7.4 ya no se muestra este error

**Cómo reproducir**
En un servidor con PHP inferior a 7.4 aunque compatible con Chamilo, clonar mediante git la rama 1.11 de Chamilo y ejecutar composer update en consola

**Comment by nosolored** [comment]
Hola.¿ Sabéis el motivo? 
El composer update no funciona en PHP 5.6, 7.1, 7.2, 7.3
solamente en PHP 7.4 genera vendor y web @jmontoyaa @ywarnier

**Comment by jmontoyaa** [comment]
El composer update funciona bien en esas versiones de PHP

https://travis-ci.org/github/chamilo/chamilo-lms/builds/725079305

**Comment by nosolored** [comment]
Mil disculpas. 
Ahora si lo genera. Gracias @jmontoyaa y @jwarnier 
Debía de ser caché del vendor y web. Ocurría en varias versiones de PHP salvo la 7.4. que lo generaba correctamente.
