### ISSUE TITLE
Doodle : datetime defined by trainer is wrongly considered by Chamilo

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3499]
**Describe**
When the trainer define datetime availbility, it is not correctly considered by Chamilo.  The Doodle isn't avalaible at the datetime defined by the teacher.

**To Reproduce**
1. Make adjustments to have datetime instead of date for the Doodle parameters : database (avail from/to fields) ; csurvey.php file (date =>datetime for avail from/to) and configuration.php file (allow_survey_availability_datetime => true)
2. Create a Doodle with datetime avaibility
3. The Doodle isn't avalaible at the correct datetime (there is a difference of 2 hours).

**Screenshots**
![Capture4](https://user-images.githubusercontent.com/24507698/92322374-27cc8500-f031-11ea-8cf0-4af866194d3b.JPG)

![Capture30](https://user-images.githubusercontent.com/24507698/92322377-2bf8a280-f031-11ea-8b03-e89a174c12bc.JPG)

**Server
Chamilo 1.11.12

**Additional context**
In my administration panel, i defined Europe/Paris as timezone.

**Comment by carlangas159** [comment]
hi @tanchon 

you can check fix for https://github.com/carlangas159/chamilo-lms/commit/15aa262bea7934ab252ebd3dc6b88ab164cf8ebe https://github.com/carlangas159/chamilo-lms/commit/51451bf40f8fb7e8409baf839b743b846d72aeab https://github.com/carlangas159/chamilo-lms/commit/b7a971d558120be0211f9ac1ab9eba88d47c4a2e 

this wraps the date when stored in the database to use the utc time correctly and wraps it in the table to use the local time properly.

**Comment by tanchon** [comment]
Hi @carlangas159 ,

Thank you. I've implemented  your fixes in my 1.11.12 platform, but strangely it seems that the problem remains =>there is still a difference... but a difference of 4 hours  ! (2 hours initially : see my first post).

The Doodle as i set it (21h22 ; 12h00)
![Capture4000](https://user-images.githubusercontent.com/24507698/93511726-8ba15880-f923-11ea-9138-eb366b7fdb64.JPG)

In the edit mode (17h22 ; 8h00) 

![Capture5000](https://user-images.githubusercontent.com/24507698/93511742-922fd000-f923-11ea-85c5-fb18a673c578.JPG)

In my database, it is stored like it is displayed in edit mode (17h22 ; 8h00).

Timezone defined in my Chamilo plaform is Europe/Paris.

Thanks !

Tanchon

**Comment by carlangas159** [comment]
Hello @tanchon 

I have made some changes, with this the correct time would be observed both in the edition and in the list, could you please verify it?

https://github.com/carlangas159/chamilo-lms/commit/67a0b710fe011c7308e9fe82969701fa501c75d7

**Comment by tanchon** [comment]
Hi @carlangas159 

Now, i find a 2 hours difference : [see this little video](https://youtu.be/4cyV06PES_c)
I hope this video can give you informations...
In the Database, datetimes stored are : 20h57 / 10h00 (as in the edit mode).

May be i didn't made correct changes to the csurvey.php file ? In the configuration.php file it is written :

// Allows to set the date and time of availability for surveys. Requires DB changes:
// ALTER TABLE c_survey CHANGE avail_from avail_from DATETIME DEFAULT NULL, CHANGE avail_till avail_till DATETIME DEFAULT NULL;
// Requires change the Doctrine type from date to datime in CSurvey::$availFrom and CSurvey::$availTill

I activate this line :
$_configuration['allow_survey_availability_datetime'] = true;

I have a doubt about how to interpret this sentence : "// Requires change the Doctrine type from date to datime in CSurvey::$availFrom and CSurvey::$availTill" ???

Thank you very much

Tanchon

**Comment by carlangas159** [comment]
Thank you very much, I was certainly focusing on editing the course after entering it, I just uploaded a change, which adjusts the local time of the model before displaying it in edit_meeting.php. When saving it also does it correctly.

**Comment by tanchon** [comment]
It works perfectly !

Thank you for your reactivity... and patience !

Tanchon
