### ISSUE TITLE
Preguntas v/f certeza y no sé

### ISSUE THREAD

**Issue by iruizsur** [chamilo/chamilo-lms#3502]
**Describe el problema**
Se genera una pregunta de este tipo (V/F con grado de certeza o V/F no sé), que por default tiene 4 respuestas pero si deseas más y habías escrito ya las opciones, al agregar otra respuesta, todo se borra.

**Cómo reproducir**
Pasos para reproducir el problema:
Generar una pregunta V/F con grado de certeza (o v/f no sé)
Rellenar el espacio de la pregunta, descripción, parámetros avanzados, etc.
Llenar 4 posibles preguntas con su retroalimentación.
Dar click a "añadir respuesta" porque se desea agregar una quinta.
Todo se borra. De hecho si antes de agregar se guarda la pregunta y luego se edita para agregar la siguiente, todo se borra. La única manera es agregar los espacios primero y luego rellenar.

**Comportamiento esperado**
Que al agregar se conserven los datos, mucho más si ya estaban guardados.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador Chrome

**Servidor
 - Sistema operativo : Linux
 - Versión de Chamilo:  1.11.12
 - Versión de PHP: 7.3

**Comment by ywarnier** [comment]
@iruizsur gracias por reportar. Los cambios enviados serán parte de la 1.11.14.
