### ISSUE TITLE
Coundnt Disable the Plugins 

### ISSUE THREAD

**Issue by sadagoban** [chamilo/chamilo-lms#3507]
Hello there,

Recently I have installed Chamilo 1.11.12,  I activated a few plugins named "Embed Registry" & Course Notification.

Now, I couldn't disable those plugins, and that action redirecting me to a broken page.  I have enclosed the image below for your reference. I seek your help in this regard. Thanks in advance 

![Capture Plugin issue](https://user-images.githubusercontent.com/36124429/92591805-2f538e80-f2bc-11ea-838f-c0712abbc6fd.JPG)

**Comment by ywarnier** [comment]
Hi @sadagoban you probably missed a cache cleaning or something like that.
In any case, you can disable any plugin by going to your database, into the settings_current table and search for lines with "category = 'Plugins'", then delete the "status" line where the "subkey" column is the name of the plugin.

For example:
`SELECT variable, subkey, category, selected_value from settings_current where category = 'Plugins';`

Then
`DELETE FROM settings_current WHERE subkey = 'embed_registry' AND variable = 'status';`
