### ISSUE TITLE
Attendance Filter Selection Issue  - Reg

### ISSUE THREAD

**Issue by sadagoban** [chamilo/chamilo-lms#3511]
Hello there,

I have recently encountered another issue with my Chamilo 1.11.12 with an attendance filtering. I could see the filter section is corrupted after the recent updates and it becomes unusable.  I am using shared hosting - Godaddy. 

I am a pharmacist ( academician - not a coder) and based on my previous understandings I came to know through Mr. Yannick Warnier this might be a cache cleaning issue.  If so, I need stepwise guidance to resolve this problem.  I have enclosed the image also for your references. 

We love your product and its really helpful for us to conduct classes during this unprecedented COVID-19 situation. Thanks to the Chamilo Team for your great work.  Wishes from India. 
![Capture Attendance JPG](https://user-images.githubusercontent.com/36124429/92911284-60f86100-f446-11ea-835c-d773c7cad2a3.JPG)

**Comment by sadagoban** [comment]
Additionally, I tried the followings,

1. Admin - Clean Cache - It fails to execute the command and it was redirected to another page

2. From the root, cleaned the app/cache/twig - Not resolved the problem.

**Comment by sadagoban** [comment]
Hello Carlangas159,  I made all changes but no change or improvement.

**Comment by carlangas159** [comment]
hi @sadagoban 

sorry for the late,  you must run "composer install" or "composer update" to update the "web" folder.

They are css adjustments so that the selectors are correctly noticed in certain parts of the chamilo

**Comment by sadagoban** [comment]
Thats ok. Can you tell me how to do a composer update? I am sorry for this question and seeking your help.

**Comment by carlangas159** [comment]
As you have chamilo installed, you probably only need to go to the console, then you locate the address where chamilo is installed and you must execute "composer install"
![image](https://user-images.githubusercontent.com/18097392/93354561-bd6ece00-f802-11ea-8836-7ae7d3dc48a8.png)
with this, it will execute the cleaning of the cache of the css and js

**Comment by aelalfey** [comment]
Thank you @carlangas159 for the fix. It worked.

**Comment by kettgun** [comment]
I have the same problem. I use vps with Ubuntu and cd the root directory of chamilo (site) where the files of composer.json and composer.lock present. I tried to execute with command ..../site# composer install but the response is " bash: composer: command not found". I also tried with composer update, but I received the same response (composer not found). How to solve this problem? Thank you in advance.

**Comment by nosolored** [comment]
@kettgun 
Installation - Linux / Unix / macOS -> https://getcomposer.org/doc/00-intro.md#installation-linux-unix-macos

**Comment by kettgun** [comment]
Thank you nosolored. I think I successfully installing Composer:  Composer version 1.10.13 2020-09-09 11:46:34
But when executing command of compose or composer update. I got the following response:

==============
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Could not scan for classes inside "main/install" which does not appear to be a file nor a folder
> Chamilo\CoreBundle\Composer\ScriptHandler::deleteOldFilesFrom19x
Loading composer repositories with package informatiUpdating dependencies (including require-dev)

Package operations: 39 installs, 13 updates, 0 removals
  - Updating doctrine/dbal (2.10.2 => 2.10.4): Downloading (100%)
  - Updating gedmo/doctrine-extensions (v2.4.41 => v2.4.42): Downloading (100%)
  - Updating composer/semver (1.5.1 => 1.7.1): Downloading (100%)
  - Updating seld/jsonlint (1.8.1 => 1.8.2): Downloading (100%)
  - Updating symfony/process (v3.4.43 => v3.4.45): Downloading (100%)
  - Updating knplabs/gaufrette (v0.9.0 => v0.10.0): Downloading (100%)
  - Updating phpseclib/phpseclib (2.0.28 => 2.0.29): Downloading (100%)
  - Updating zendframework/zend-soap (2.6.0 => 2.8.0): Downloading (100%)
  - Updating symfony/service-contracts (v2.1.3 => v2.2.0): Downloading (100%)
  - Updating symfony/expression-language (v4.4.11 => v4.4.15): Downloading (100%)
  - Updating guzzlehttp/promises (v1.3.1 => 1.4.0): Downloading (100%)
  - Updating guzzlehttp/psr7 (1.6.1 => 1.7.0): Downloading (100%)
  - Installing symfony/css-selector (v3.4.45): Downloading (100%)
  - Installing behat/mink (v1.7.1): Downloading (100%)
  - Installing behat/gherkin (v4.6.2): Downloading (100%)
  - Installing behat/behat (v3.5.0): Downloading (100%)
  - Installing behat/mink-extension (2.3.1): Downloading (100%)
  - Updating symfony/dom-crawler (v3.4.43 => v3.4.45): Downloading (100%)
  - Installing symfony/browser-kit (v4.4.15): Downloading (100%)
  - Installing fabpot/goutte (v3.2.3): Downloading (100%)
  - Installing behat/mink-browserkit-driver (v1.3.4): Downloading (100%)
  - Installing behat/mink-goutte-driver (v1.2.1): Downloading (100%)
  - Installing instaclick/php-webdriver (1.4.7): Downloading (100%)
  - Installing behat/mink-selenium2-driver (v1.4.0): Downloading (100%)
  - Installing sebastian/version (2.0.1): Downloading (100%)
  - Installing sebastian/type (1.1.3): Downloading (100%)
  - Installing sebastian/resource-operations (2.0.1): Downloading (100%)
  - Installing sebastian/recursion-context (3.0.0): Downloading (100%)
  - Installing sebastian/object-reflector (1.1.1): Downloading (100%)
  - Installing sebastian/object-enumerator (3.0.3): Downloading (100%)
  - Installing sebastian/global-state (3.0.0): Downloading (100%)
  - Installing sebastian/exporter (3.1.2): Downloading (100%)
  - Installing sebastian/environment (4.2.3): Downloading (100%)
  - Installing sebastian/diff (3.0.2): Downloading (100%)
  - Installing sebastian/comparator (3.0.2): Downloading (100%)
  - Installing phpunit/php-timer (2.1.2): Downloading (100%)
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)
  - Installing phpunit/php-file-iterator (2.0.2): Downloading (100%)
  - Installing theseer/tokenizer (1.2.0): Downloading (100%)
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Downloading (100%)
  - Installing phpunit/php-token-stream (3.1.1): Downloading (100%)
  - Installing phpunit/php-code-coverage (7.0.10): Downloading (100%)
  - Installing doctrine/instantiator (1.3.1): Downloading (100%)
  - Installing phpdocumentor/reflection-common (2.2.0): Downloading (100%)
  - Installing webmozart/assert (1.9.1): Downloading (100%)
  - Installing phpdocumentor/type-resolver (1.4.0): Downloading (100%)
  - Installing phpdocumentor/reflection-docblock (5.2.2): Downloading (100%)
  - Installing phpspec/prophecy (1.12.1): Downloading (100%)
  - Installing phar-io/version (2.0.1): Downloading (100%)
  - Installing phar-io/manifest (1.0.3): Downloading (100%)
  - Installing myclabs/deep-copy (1.10.1): Downloading (100%)
  - Installing phpunit/phpunit (8.5.8): Downloading (100%)
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
sebastian/global-state suggests installing ext-uopz (*)
phpunit/phpunit suggests installing phpunit/php-invoker (^2.0.0)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package emojione/emojione is abandoned, you should avoid using it. No replacement was suggested.
Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead.
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
Package sonata-project/core-bundle is abandoned, you should avoid using it. No replacement was suggested.
Package sylius/translation is abandoned, you should avoid using it. No replacement was suggested.
Package twig/extensions is abandoned, you should avoid using it. No replacement was suggested.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package zendframework/zend-config is abandoned, you should avoid using it. Use laminas/laminas-config instead.
Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.
Package zendframework/zend-http is abandoned, you should avoid using it. Use laminas/laminas-http instead.
Package zendframework/zend-hydrator is abandoned, you should avoid using it. Use laminas/laminas-hydrator instead.
Package zendframework/zend-loader is abandoned, you should avoid using it. Use laminas/laminas-loader instead.
Package zendframework/zend-server is abandoned, you should avoid using it. Use laminas/laminas-server instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package zendframework/zend-uri is abandoned, you should avoid using it. Use laminas/laminas-uri instead.
Package zendframework/zend-validator is abandoned, you should avoid using it. Use laminas/laminas-validator instead.
Package zendframework/zend-soap is abandoned, you should avoid using it. Use laminas/laminas-soap instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files


  [RuntimeException]
  Could not scan for classes inside "main/install" which does not appear to be a file nor a folder


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

root@srv:/var/www/clients/client32/web35/web/web#

=============

**Comment by kettgun** [comment]
Sorry.. I use folder "web".  In Attendance Filter of Chamilo, no change

**Comment by nosolored** [comment]
@kettgun 
You got an error in :
`[RuntimeException]
Could not scan for classes inside "main/install" which does not appear to be a file nor a folder`

The process has not finished correctly. It seems that composer did not create "vendor" and "web" folders.
You should check the content of "main/install" folder.

**Comment by kettgun** [comment]
Folder "vendor" and "web" exist, located in the root directory of chamilo. Folder "main" is also in the root directory, but there is no "install" folder.

**Comment by ywarnier** [comment]
The directory "install" should be located under the "main" directory. If it is not present, then it is probably because the person who installed the system followed a suggestion that we have at the end of the install process, that it is safer to just delete it (but this is not mandatory as mechanisms are in place to avoid abuses).
If you want to put it back, download the Chamilo package in the same version that you are using it, and extract the main/install folder and just copy it over your current running installation directory (*just* the main/install folder). That should work.
If you're using Git, you could just issue "git checkout main/install" to restore it.

**Comment by kettgun** [comment]
Yes I think, because of Auto Installer. It removed the "install" folder automatically.  I have tried your suggestion, but failed. Then, I reinstalled chamilo manually. It works perfectly without updating or installing composer. Anyway, thank you very much for the support

**Comment by kettgun** [comment]
I have a strange issue. When I was struggling to get a correct attendance (automatic) list, I clicked many times to try. Then the attendance filter feature returned to the above problem.  I tried to reinstall a php composer, and run composer update, it still does not work in Firefox. But it works in Chrome. I use a laptop for this. But when I use a desktop, it does not work in both browsers. My question is how to solve this problem? Is there a patch file for this? In the Chamilo documentation I found that the Attendances should be managed manually. Is there a way to make it automatically, for example, through online user? Thank you.

**Comment by kettgun** [comment]
Currently, using Chrome navigator in my laptop also faces the same problem. My filter section is now becoming the same as what mentioned in the first post of this thread (see the image above). I have tried to execute command "composer install" and "comnposer update" but nothing change. Please help...

**Comment by ywarnier** [comment]
Release 1.11.14 will be out in a few days and has the fix included. Please update when it's out.
