### ISSUE TITLE
multi_url bug.

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3516]
**Describe**
If you enable "access_urls"
en the main url differs from: "settings_InstitutionUrl"

Example: site is under https://site.com
but in access_urls you set https://www.site.com

You wil get login issues (password not accepted but when you hit back in browser you are logged in)
This is because of following error: `Blocked by CORS policy : No 'Access-Control-Allow-Origin' header is present on the requested resource`

**To Reproduce**
set 2 different base urls for setting: "access_urls" and "settings_InstitutionUrl"

**Expected behavior**
Ideally "settings_InstitutionUrl" is i think a leading variable and should be automatically filled in here.
**Screenshots**

**Server
Chamilo updated 1 week ago.
7.3 on centos 8

**Comment by ywarnier** [comment]
Fixed here: 0287acb3124dac54f808310bcc111c99cfc828aa
