### ISSUE TITLE
cronjobs

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3518]
**Is your feature request related to a problem? Please describe.**
https://github.com/chamilo/chamilo-lms/issues/1493

**Describe the solution you'd like**
Its unclear from that issue what the recommended cronjob Approach is for chamilo.
I would like to update the documentation witch strongly recommend a cronjob but does not specify how.

**Additional context**
As far as i can see this little howto from @jderriks should still function. If there is no objections from the devs i like to at that to the manual.
`Steps to create crontab:
crontab -e
add lines:
#min hour date mon weekday command
#example: cleanup at 03:07 every morning an keep a log of the size.
7 3 * * * (cd /web/yourchamilo/; du -sh app/cache; rm -rf app/cache/*) >> $HOME/cronjobs.log`

**Comment by ywarnier** [comment]
The best way to clean the cache automatically for now is to install chash: https://github.com/chamilo/chash
```
cd /tmp
git clone -b 0.1 https://github.com/chamilo/chash
cd chash
composer update
php -d phar.readonly=0 createPhar.php
chmod +x chash.phar
sudo mv chash.phar /usr/local/bin/chash
```
Then, from your cron, something like this:
```
7 3 * * * root cd /web/yourchamilo/; /usr/local/bin/chash -n fct
```

There are many variations to this last command (notably to avoid alerts on the output of the command or to change the user executing it), but in general this should work and you can find out the rest.

If you want to know the details of Chash (which uses several stuff from Symfony), check https://github.com/chamilo/chash/blob/0.1/src/Chash/Command/Files/CleanTempFolderCommand.php#L56
