### ISSUE TITLE
Migrate an installation to another server

### ISSUE THREAD

**Issue by Leonardolms** [chamilo/chamilo-lms#3520]
Good afternoon,

I will need to place the chamilo on another server, however when changing the server files and connecting the database, the layout was out of shape.

What is the correct procedure to migrate an installation to another server?

Thank you very much in advance.

Chamilo: 1.11
Server: Linux

**Comment by lonesomewalker** [comment]
If your installation is under /var/www/chamilo

`cd /var/www`
`tar cvfzp chamilo.tar.gz chamilo/`
`mysqldump -u hereyourchamilodbuser -p hereyourchamilodbname > chamilo.sql`
You will be asked for the database password. Enter it.

Transfer the chamilo.tar.gz and chamilo.sql to the new server.
Extract with:
`cd /var/www`
`tar xvfzp chamilo.tar.gz`
Correct your app/config/configuration.php to the new settings of your installation (maybe changed path or new database credentials)
Additionally you might have to change owner of the transfered files (like `chown -R www-data:www-data chamilo/` )

Fill database with:
`mysql -u hereyourchamilodbuser -p hereyourchamilodbname < chamilo.sql`
Again you will be asked for database password, enter it.

Now you should be able to enter your portal.

If you changed your URL from your portal then you have to do additional database replacements.
This also applies to changed paths.

**Comment by Leonardolms** [comment]
@lonesomewalker Thanks for the explanations.

I did the procedure, but I'm still flawed. I believe it is due to the URL change.

Where should I fix it in this case where the URL was modified?

Thank you very much in advance

**Comment by ywarnier** [comment]
@Leonardolms 
In case the URL was modified, you need to update *at least* app/config/configuration.php at line with root_web (and probably root_sys). You can also run a complex combination of `find` and `sed` to replace all URLs in your chamilo folder files, and just `sed` to replace it in your database dump *before* you restore it.
