### ISSUE TITLE
ERROR EN INSTALACIÓN DE VERSIÓN 1.11.12

### ISSUE THREAD

**Issue by R0sy** [chamilo/chamilo-lms#3523]
Buen día, al instalar la versión 1.11.12, en cuanto se le da al botón de instalar arroja el error de:

Fatal error: Cannot redeclare normalizer_normalize() (previously declared in /var/www/html/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:18) in /var/www/html/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 21

El error se muestra cuando se inicia el install Chamilo, nos arroja directamente el error, he asignado los permisos de acuerdo a la guía de instalación que la página de https://campus.chamilo.org, he configurado los requisitos solicitados para la instalación, además de que he borrado y subido nuevamente los archivos.  

El servidor que estoy utilizando para esta instalación es de Amazon, con sistema Operativo Ubuntu, Apache 2, PHP 7.2 y MYSQL 5.5

A continuación comparto captura de pantalla del error. 

![Captura de pantalla 2020-09-14 a la(s) 18 38 29](https://user-images.githubusercontent.com/42190653/93274438-fade4780-f77f-11ea-94f6-b9d499764cf2.png)

Sin más quedo atenta a sus comentarios. 
Saludos.

**Comment by ywarnier** [comment]
Hola @R0sy 
No hemos encontrado este error previamente. El mensaje "Cannot redeclare" sugiere que hay un proceso de declaración de métodos que se hace dos veces, lo cual no tiene mucho sentido.
Es una máquina (virtual) nueva o hay otras cosas en la misma?

**Comment by R0sy** [comment]
Hola Yanik, si la máquina es nueva, y solo contiene almacenada la plataforma, en cuanto se le da install chamilo arroja el error, entonces no sé si necesite algo más ya que se instalo lo que el manual indica.

**Comment by carlangas159** [comment]
hola @R0sy 

Acabo de realizar una instalación limpia de chamilo, lo que se encuentra en la carpeta vendor son complementos que se instalan por composer y no se podría modificar directamente por chamilo. 

En mi caso, efectivamente vi este error, el problema es que se nombra dos veces una funcion, asi que ya se encuentra definida

Lo que hice fue, editar el archivo "vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php" y le he colocado una validación si existe la funcion.  **if (!function_exists('normalizer_is_normalized')) {** me parece que son solo dos.

if (!function_exists('normalizer_is_normalized')) {
    function normalizer_is_normalized($s, $form = s\Normalizer::NFC)
    {
        return s\Normalizer::isNormalized($s, $form);
    }
}
if (!function_exists('normalizer_normalize')) {

    function normalizer_normalize($s, $form = s\Normalizer::NFC)
    {
        return s\Normalizer::normalize($s, $form);
    }
}


con esto previene el error que te muestra sin afectar nada del sistema.

**Comment by kemoche** [comment]
Hi,
This what I did....

Chamilo 12 Error
Fatal error: Cannot redeclare normalizer_is_normalized() (previously declared in /public_html/chamilo12/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15) in /public_html/chamilo12/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 20

Solution: Commenting on lines 20&21 as below on file public_html/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php
/*function normalizer_is_normalized($s, $form = s\Normalizer::NFC) {return s\Normalizer::isNormalized($s, $form);}
function normalizer_normalize($s, $form = s\Normalizer::NFC) {return s\Normalizer::normalize($s, $form);}*/

Hope it works for you :)

**Comment by R0sy** [comment]
Buen día he realizado las posibles soluciones compartidas, y me arrojan los siguientes errores:

![Captura de pantalla 2020-09-19 a la(s) 11 35 16](https://user-images.githubusercontent.com/42190653/93671873-3c1a7400-fa6c-11ea-9d59-312f427f5cd8.png)

![Captura de pantalla 2020-09-19 a la(s) 11 37 56](https://user-images.githubusercontent.com/42190653/93671950-a6331900-fa6c-11ea-9927-e7d3dc973185.png)

Quedo atenta a sus comentarios. 
Gracias.

**Comment by kemoche** [comment]
```
See the attached

![bootup-intl](https://user-images.githubusercontent.com/69464866/93708864-53c42c00-fb42-11ea-8947-c333d1f473a9.jpg)

**Comment by ywarnier** [comment]
@R0sy quizás descargando otra versión del paquete de Chamilo (.tar.gz en vez de .zip), te ayude. La verdad no entiendo porqué os sale esto a ti y a @carlangas159, pero quiero evitar que sea un problema para otros, si es posible.

**Comment by R0sy** [comment]
@kemoche  he comentado las líneas que has comentado pero el error que genera es el siguiente: 
![Captura de pantalla 2020-09-19 a la(s) 11 37 56](https://user-images.githubusercontent.com/42190653/93787126-b75b6180-fbf5-11ea-95e0-896c21ecdbf9.png)

@ywarnier he instalado la versión de chamilo 1.11.10 y en cuanto le doy install me muestra el siguiente error:

![Captura de pantalla 2020-09-21 a la(s) 10 38 42](https://user-images.githubusercontent.com/42190653/93788837-bd057700-fbf6-11ea-8933-5878adf64b85.png)

No sé si me falte algún archivo o alguna extensión ya que no entiendo porque muestra el error.

Sin más por el momento quedo pendiente de sus comentarios.

**Comment by ywarnier** [comment]
@R0sy A este punto parece más ser un problema de extensión de PHP que no estaría instalada, pero me sorprende que suceda en un sistema Ubuntu, que es el que usamos nosotros internamente como base para redactar el manual de instalación.
Puede que AWS tenga sus imágenes Ubuntu alteradas, o que hayas elegido una que supuestamente viene preparada para aplicaciones PHP y en la práctica esté distinta de las "estandar" de Ubuntu.

Vayamos más allá.
Primero, podrías pegar aquí la salida de `dpkg -l |grep php`?

Luego, podrías asegurarte de instalar todos los paquetes siguientes en tu Ubuntu?
```sudo apt install apache2 libapache2-mod-php php-pear php-dev php-gd php-curl php-intl php-mysql php-mbstring php-zip php-xml php-cli php-apcu git unzip```

y volver a intentar la instalación de 1.11.12?

**Comment by R0sy** [comment]
Claro comparto imagen de salida de dpkg -l |grep php

![Captura de pantalla 2020-09-21 a la(s) 15 51 35](https://user-images.githubusercontent.com/42190653/93820179-64e46a00-fc22-11ea-9518-7f221fe3bd4e.png)

**Comment by ywarnier** [comment]
OK, sí, te faltan muchas extensiones de PHP. Con el comando que te puse deberías poder complementar esto y ojalá salga mejor. El php-pear quizás ya no esté de aplicación. Si te dice que no existe, lo puedes ignorar.

**Comment by R0sy** [comment]
Buen día he realizado nuevamente la instalación de chamilo 1.11.12 después de instalar el comando que me han compartido pero ahora me muestra el siguiente error, no sé si haya otra extensión que nos haga falta instalar. 

![Captura de pantalla 2020-09-23 a la(s) 10 05 13](https://user-images.githubusercontent.com/42190653/94039922-ee647b00-fd8d-11ea-99f1-44ff39c28eb9.png)

**Comment by R0sy** [comment]
Buen día intente nuevamente instalar la plataforma de chamilo, usando el paquete tar.gz, pero el error que muestra es el siguiente, he instalado nuevamente las extensiones que me compartieron anteriormente pero el error sigue siendo el mismo, porque lo me gustaría saber si hay alguna otra forma de poder solucionar mi problema, ya que tengo tiempo sin poder instalar esta nueva versión y las anteriores también me generan errores. 

Sin más quedo al pendiente de sus comentarios Gracias. 

![Captura de pantalla 2020-09-30 a la(s) 11 54 50](https://user-images.githubusercontent.com/42190653/94720988-ce4b3380-031a-11eb-84bf-5e134176518b.png)

**Comment by atarallo** [comment]
Seguimos esta directiva y pudimos completar la instalacion de chamilo 1.11.12 en centos 8. 

We followed this directives and completed the install on Centos 8. 

Andrés 

> hola @R0sy
> 
> Acabo de realizar una instalación limpia de chamilo, lo que se encuentra en la carpeta vendor son complementos que se instalan por composer y no se podría modificar directamente por chamilo.
> 
> En mi caso, efectivamente vi este error, el problema es que se nombra dos veces una funcion, asi que ya se encuentra definida
> 
> Lo que hice fue, editar el archivo "vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php" y le he colocado una validación si existe la funcion. **if (!function_exists('normalizer_is_normalized')) {** me parece que son solo dos.
> 
> if (!function_exists('normalizer_is_normalized')) {
> function normalizer_is_normalized($s, $form = s\Normalizer::NFC)
> {
> return s\Normalizer::isNormalized($s, $form);
> }
> }
> if (!function_exists('normalizer_normalize')) {
> 
> ```
> function normalizer_normalize($s, $form = s\Normalizer::NFC)
> {
>     return s\Normalizer::normalize($s, $form);
> }
> ```
> 
> }
> 
> con esto previene el error que te muestra sin afectar nada del sistema.

**Comment by carlangas159** [comment]
hola @R0sy 

Basado en lo que envias de imagen, es probable que no esten todos los elementos instalados, en tu caso, aparte de haber instalado las extensiones como comento  @ywarnier tambien deberias hacer "composer install" para instale todas las dependencias, date cuenta que todo lo que esta en la carpeta vendor se instala por composer, en tu caso, "/var/www/html/vendor/ircmaxell" parece ser que no esta instalado y puede resolverse por composer install

> Buen día intente nuevamente instalar la plataforma de chamilo, usando el paquete tar.gz, pero el error que muestra es el siguiente, he instalado nuevamente las extensiones que me compartieron anteriormente pero el error sigue siendo el mismo, porque lo me gustaría saber si hay alguna otra forma de poder solucionar mi problema, ya que tengo tiempo sin poder instalar esta nueva versión y las anteriores también me generan errores.
> 
> Sin más quedo al pendiente de sus comentarios Gracias.
> 
> ![Captura de pantalla 2020-09-30 a la(s) 11 54 50](https://user-images.githubusercontent.com/42190653/94720988-ce4b3380-031a-11eb-84bf-5e134176518b.png)

**Comment by R0sy** [comment]
Buen día ya he instalado composer, e instale ircmaxell, pero aún mi error sigue apareciendo, no sé si tenga que agregar algo más.

Quedo al pendiente de comentarios. 

Gracias.

**Comment by lizardopc** [comment]
lo solucione instalando la extension intl

**Comment by R0sy** [comment]
Buenas Tardes, he logrado solucionar mi problema de instalación, pero una vez que esta instalada la plataforma no me muestra los estilos, ni bootstrap, así que revisando el problema me indica: Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure stylesheet '<URL>'. This request has been blocked; the content must be served over HTTPS.
Por lo que pido de su apoyo para poder saber como hacer la conversión de https a http ya que sin esta la plataforma no respeta los estilos a continuación comparto una imagen de como se visualiza la plataforma y los errores que muestra:
Agradezco su atención. 

![Captura de pantalla 2020-10-28 a la(s) 15 50 10](https://user-images.githubusercontent.com/42190653/97502526-e4a7d780-1938-11eb-9ecd-3cc1ef20732f.png)

**Comment by nosolored** [comment]
Hola.

Si la instalación inicial de Chamilo la has realizado por http ese fichero se ha creado con esa dirección.

Revisa el archivo /app/config/configuration.php en la línea
```
// URL to the root of your Chamilo installation, e.g.: http://www.mychamilo.com/
$_configuration['root_web']  
```
comprueba si la dirección empieza por http. Se aconseja cambiarla a https.

Es aconsejable también forzar todo el tráfico http hacia https bien en Apache o .htaccess

Saludos.

**Comment by ywarnier** [comment]
Sin feedback por un tiempo. Cerrando.

**Comment by chininguitar** [comment]
La solucion que indica nuestro amigo @kemoche  lo soluciona. Osea comentar las lineas 20 y 21 . 
Verificar la version de PHP que tienen. Yo la estoy probando con la 7.2. Ah! tmb estoy instalando la version 1.11.14 de Camilo y funciono.

**Comment by luiselmer** [comment]
> Buenas Tardes, he logrado solucionar mi problema de instalación, pero una vez que esta instalada la plataforma no me muestra los estilos, ni bootstrap, así que revisando el problema me indica: Mixed Content: The page at '' was loaded over HTTPS, but requested an insecure stylesheet ''. This request has been blocked; the content must be served over HTTPS.
> Por lo que pido de su apoyo para poder saber como hacer la conversión de https a http ya que sin esta la plataforma no respeta los estilos a continuación comparto una imagen de como se visualiza la plataforma y los errores que muestra:
> Agradezco su atención.
> 
> ![Captura de pantalla 2020-10-28 a la(s) 15 50 10](https://user-images.githubusercontent.com/42190653/97502526-e4a7d780-1938-11eb-9ecd-3cc1ef20732f.png)

Hola R0sy Cómo lo solucionaste

**Comment by GspindolaB** [comment]
A mi me salió el siguiente error:

![errorCHAMILO](https://user-images.githubusercontent.com/16752224/104794038-c8af1780-576a-11eb-8073-e74a23fdb1c2.PNG)

Me dejo seguir con la instalación comentando esas líneas en el archivo mencionado en el error

![image](https://user-images.githubusercontent.com/16752224/104794055-e8ded680-576a-11eb-9d16-8d7405e0e7e6.png)

Espero pueda servirle.

**Comment by R0sy** [comment]
> > Buenas Tardes, he logrado solucionar mi problema de instalación, pero una vez que esta instalada la plataforma no me muestra los estilos, ni bootstrap, así que revisando el problema me indica: Mixed Content: The page at '' was loaded over HTTPS, but requested an insecure stylesheet ''. This request has been blocked; the content must be served over HTTPS.
> > Por lo que pido de su apoyo para poder saber como hacer la conversión de https a http ya que sin esta la plataforma no respeta los estilos a continuación comparto una imagen de como se visualiza la plataforma y los errores que muestra:
> > Agradezco su atención.
> > ![Captura de pantalla 2020-10-28 a la(s) 15 50 10](https://user-images.githubusercontent.com/42190653/97502526-e4a7d780-1938-11eb-9ecd-3cc1ef20732f.png)
> 
> Hola R0sy Cómo lo solucionaste

La solución es modificar el archivo /app/config/configuration.php modificas el http por https.
