### ISSUE TITLE
Multi URL move or assign users to an other multi URL unassigns users higher than 998

### ISSUE THREAD

**Issue by Bavarianspirit** [chamilo/chamilo-lms#3526]
**Describe**
We can not move or assign users to an subportal in MultiURL configuration if there are more than 998 Users in the subportal assigned.

![Screenshot_1 Kopie](https://user-images.githubusercontent.com/35309163/93529698-a6cc9200-f93c-11ea-9296-e14bccba8eec.jpg)

Look at the screenshot. on the left side there are all users assigned in the portal. the right side there is a subportal in MultiURL configuration.
It doesn't matter if i try to assign one user more or remove one user or only press "ändere Benutzer URL".
Users above 998 will be removed from this subportal. The useres are not deleted but they stay unassigned. The output after pressing the button is, that this users are removed from the portal: user1;user2;user3;... and so on.

after the last update we deleted about 2000 or more users, but it's not possible to reduce users under 998.

**Desktop (please complete the following information):**
that doesn't matter

**Server
 - OS: Debian
 - Version of Chamilo:  1.11.12
 - Version of PHP: 7.3

**Additional context**
At this time, the only way is to create a new user at the subportal. MultiURL usermanagement is only usable if there are less than 998 users in one subportal.

**Comment by ywarnier** [comment]
Hallo @Bavarianspirit 
There is no hard limit in Chamilo, but you might want to check your max_input_vars setting in your PHP configuration. It is set to 1000 by default and limits the number of variables sent through a form. In your case, it is 998 + 2 variables sent by Chamilo, so that seems to match.
This is a common issue on portals with more than 1000 users.

**Comment by Bavarianspirit** [comment]
thanks a lot. this works perfectly
