### ISSUE TITLE
reported free space is calculated wrongly

### ISSUE THREAD

**Issue by roelvisje** [chamilo/chamilo-lms#3527]
As seen in the picture in "settings" at a newly created course, the reported space is negative. 

![space](https://user-images.githubusercontent.com/51987964/93564050-592a4680-f989-11ea-813b-d438fc7b7bca.jpg)

default hd space should be 3gb and default groupspace should be 1 gb.

seen with latest up to date chamilo version

**Comment by roelvisje** [comment]
so i noticed today that due to the fact negative space available it is also not possible to upload files.. 
When going to course list and editing the negative amount to a positive amount solves it for the course.
i also noticed when i change the platform setting from 3000mb to 300mb and default groupsace from 1000mb to 100mb the course was created normally with a positive amount.. so the workaround is to go to courselist in administration, then edit the course, then change the negative value to a positive amount you need/want..

**Comment by roelvisje** [comment]
i think i narrowed the problem to the following file:
main/admin/course_add.php

in it there are 2 lines: 
$values['disk_quota'] = round(api_get_setting('default_document_quotum') / 1024  / 1024, 1);

$course['disk_quota'] = $course['disk_quota'] * 1024 * 1024;

replacing the first line the 1024 numbers by e.g. 4096 (4x 1024), then the reported disk space available instead of 3000mb is 187,5.. after going to the course and going to settings i can see that same value reported.. so not a negative value as when the default line is used.. 

When replacing the numbers in the 2nd line by 4096 (so it becomes: $course['disk_quota'] = $course['disk_quota'] * 4096 * 4096;
and redoing the numbers in the first line back to 1024, the reported document space is negative:

-1207959552B

so here is the problem narrowed down to some calculational problems i think.

**Comment by ywarnier** [comment]
Hi @roelvisje 
We cannot reproduce this issue. My first intuition is there must be something wrong with your configuration of PHP or something similar.
I've tried setting the global limit to 3000MB
![config-size](https://user-images.githubusercontent.com/609839/100424931-9b10f080-308e-11eb-97c5-a052d6d56ec4.png)

Then creating a course (you can see the number of MB is correct)
![course-size-create](https://user-images.githubusercontent.com/609839/100424961-a7954900-308e-11eb-952a-54efe7e7cf7f.png)

Then going into the course > settings tool
![course-size](https://user-images.githubusercontent.com/609839/100424987-b2e87480-308e-11eb-82b0-0b839bca8a65.png)

I also tried setting 3000000 MB just in case you would have used the wrong multiple
![course-size2](https://user-images.githubusercontent.com/609839/100425026-c562ae00-308e-11eb-8b72-7610e4cffa38.png)

But nothing gets into negative numbers as in your case. I'm leaving this open for more info, but removing it from the 1.11.14 target.
