### ISSUE TITLE
Problemas en la funcionalidad de la carga de archivos en Chamilo

### ISSUE THREAD

**Issue by jolguer** [chamilo/chamilo-lms#3531]
Presenta error al tratar de subir archivo a los cursos

**Cómo reproducir**
Pasos para reproducir el problema:
1. Al subir archivos (word, excel) en  "MIs archivos" no permite 
2. No sube la imagen en "Añadir imagen del curso" muestra un mensaje como que el proceso fue exitoso, pero no muestra la imagen.
3. Tampoco permite la importacion de evaluaciones. ( muestra un mensaje que, no encuentra el xml que está dentro del zip) , pero he comrobado que el xml si se encuentra dentro.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [Windows 10]
 - Navegador [ chrome 85.0.4, firefox 80.0.1]

**Servidor
 - Sistema operativo : [CentOS 7, Dedicated 16GB: 8 CPU, 320GB Storage, 16GB RAM]
 - Versión de Chamilo:  [1.11.0.6]
 - Versión de PHP: [7.2]

**Contexto adicional**
Chamilo lo he instalado sobre Cpanel (servidor dedicado)

Quedo atento a su amable respuesta.

saludos

**Comment by carlangas159** [comment]
hola @jolguer 

Muchisimas gracias por tus comentarios, observo que presentas 3 problemas diferentes totalmente, si bien, agradecemos el tiempo para hacer el reporte, es conveniente crear un issue para cada uno, asi es posible trabajarlo de manera ordenada.

te comento que para el primer comentario, ya ha sido reportado algo similar, puedes verificarlo en el siguiente commit https://github.com/carlangas159/chamilo-lms/commit/8aa8179203153a535091ce41f2c57f0f0ab14983 por lo tanto, no será tratado en este issue

Para el segundo elemento "No sube la imagen en "Añadir imagen del curso" muestra un mensaje como que el proceso fue exitoso, pero no muestra la imagen." he realizado una prueba en una instalacion local, le he asignado al curso una imagen 

![image](https://user-images.githubusercontent.com/18097392/95262286-6f415f00-07f1-11eb-99dd-a8ef7637f489.png)

En la configuracion del curso, se muestra correctamente
![image](https://user-images.githubusercontent.com/18097392/95262366-9ef06700-07f1-11eb-9756-1d98fcf1e604.png)

y se muestra correctamente en la lista de cursos
![image](https://user-images.githubusercontent.com/18097392/95262422-b7f91800-07f1-11eb-929d-4cc2deddba58.png)

**Puedes llegar a ser mas especifico para llegar a replicar el fallo que reportas?**

Sobre el tercer elemento "Tampoco permite la importacion de evaluaciones. ( muestra un mensaje que, no encuentra el xml que está dentro del zip) , pero he comrobado que el xml si se encuentra dentro." puedes abrir otro issue y de ser posible, con un ejemplo de carga para tratarlo de forma adecuada?

**Comment by ywarnier** [comment]
Sin feedback por más de 1 mes. Cerrando.

**Comment by ingppalacioshack** [comment]
No es la imagen, cuando se sube a Documentos un archivo, lo vez en la carpeta pero en la web Chamilo no lo muestra
