### ISSUE TITLE
Not Found Most popular courses images

### ISSUE THREAD

**Issue by Leonardolms** [chamilo/chamilo-lms#3532]
Olá, quando adiciono uma foto de capa ao curso, ao mostrar em cursos populares, não é carregado a imagem quando não está logado, apenas quando realizo login que é mostrada a imagem.

Como configuro para aparecer a foto em ambas as opções (logado e não logado)?

Att.

Leonardo

Hello, when I add a cover photo to the course, when showing in popular courses, the image is not loaded when not logged in, only when I login that the image is shown.

How do I configure the photo to appear in both options (logged in and not logged in)?

Chamilo Version: 1.11.10
Server: Linux

Most popular courses

![image](https://user-images.githubusercontent.com/66574858/93939689-908a5180-fd01-11ea-9bf9-9dbbf0507db0.png)

Sincerely

**Comment by Leonardolms** [comment]
I located the login via facebook, this error appeared when loading the image.

I disabled the login via facebook and the image came back.

Activating the login plug, what configuration do I do to display the image?


![image](https://user-images.githubusercontent.com/66574858/93941028-fa0b5f80-fd03-11ea-99a0-ad5e4be5ff35.png)

**Comment by ywarnier** [comment]
@Leonardolms I believe we fixed this issue in 1.11.14 (to be published this month). If you update to 1.11.14 and it is not fixed, please reopen this issue.
