### ISSUE TITLE
Sobrecarga del servidor de chamilo

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [chamilo/chamilo-lms#3533]
Hola buenas tardes.
Espero me puedan ayudar, actualmente tengo un chamilo 1.11 (actualizado) instalado en ubuntu server versión 18.04.4 LTS, configurado con apache en version 2.4.29, con php en version 7.2 y la base de datos de MariaDB en la versión Distrib 10.3.22-MariaDB.
El detalle es que el servidor se esta sobrecargando demasiado, hay alrededor de 2000 usuarios aproximadamente y en concurrencia aproximadamente 700 usuarios.
![image](https://user-images.githubusercontent.com/41083269/93942496-215b3000-fcf6-11ea-925c-c02462f35ebc.png)

La configuración del servidor es la siguiente: 

- Un servidor con 12 nucleos de Xeon E5-2667 a 2.9GHz
- 12 GB de memoria RAM
- 4GB de Swap

Cabe mencionar que la base de datos esta en otro servidor.
El servidor de la base de datos la configuración es la siguiente:

- Un servidor con 8 nucleos de Xeon E5-2667 a 2.9GHz
- 8 GB de memoria RAM
- 4GB de Swap

El ancho de banda es de 100MG de un enlace dedicado.

El detalle es que el servidor tarda en contestar cuando hay aproximadamente 700 usuarios, esto se presenta mas cuando esta el plugin de BBB activado, de igual manera el servidor del BBB esta en otro maquina alojada en Google Cloud ese servidor no esta saturado, el que se satura es el servidor de Chamilo, seguí la configuración que recomienda chamilo para apache pero no se si me hace falta algo mas, o solamente incrementar mas los recursos, pero creo que de recursos esta bien o al menos eso pienso si me podrían ayudar gracias.

**Comment by ywarnier** [comment]
Hola @CamiloPerezOrtiz 
Lamento el retraso en la respuesta, estuvimos bajo una increíble carga de trabajo y recién podemos atender las consultas de muchos.

El problema que reportas no es un problema de código, es más bien una consulta. Este espacio (Github) no es para consultas, sino para reportar problemas con el software. Te recomiendo el uso del foro de Chamilo para este tipo de consultas: https://forum.chamilo.org. Hubieras recibido una respuesta más rápida.

Excepcionalmente, te contesto por aquí:
 - existe un archivo documentation/optimization.html dentro de cualquier instalación Chamilo, que da una larga serie de recomendaciones de optimización
 - usando `htop`, puedes ver la ocupación de cada procesador, pero te pierdes un valor importante de `top` que es el `wa` (wait), que indica si tu sistema está agotado por los I/O (`wa` alto) o por otras cosas. Supongo que ya habrás encontrado otra solución, pero por lo menos tomalo en cuenta para la próxima. Los I/O pueden ser el disco del servidor web o la espera de la base de datos.
 - cuando esto pasa (o mejor dicho *antes* de que pase), activa los slow_queries dentro de la configuración de MySQL/MariaDB. En particular si tienes 700 usuarios activos, es probable que tu base de datos esté *contínuamente* bajo una alta cantidad de solicitudes. Los queries lentos te ayudarán a entender si hay partes específicas de Chamilo que están bajo sobrecarga (documentos, leccions, ejercicios, etc).
 - usar PHP 7.3 puede aliviar ya una parte de la carga a nivel de PHP, usar opcache y apcu puede aliviar considerablemente otras partes.

El optimization.html es tu mejor aliado. Luego de esto, acudir a proveedores oficiales de Chamilo también te puede ayudar (son empresas que se especializan en servicios de Chamilo desde años atrás y han visto muchas cosas).

**Comment by CamiloPerezOrtiz** [comment]
Hola @ywarnier  gracias por los comentarios y las sugerencias que me describes, voy a checar el documento que me mencionas de optimization.html para mejorar esa parte. Gracias
