### ISSUE TITLE
Problemas en Red social / Mis archivos

### ISSUE THREAD

**Issue by leandrotaborda** [chamilo/chamilo-lms#3535]
Problemas para subir archivos .pdf en la sección Red Social / Mis archivos, librería elFinder, este problema se presento luego de actualizar a la última versión.
El error que me da es el siguiente, cuando quiero subir un archivo .pdf, me sale el siguiente error.
![image](https://user-images.githubusercontent.com/70673073/94067915-e411a380-fdc4-11ea-9b5f-81f9acd1a428.png)

Pero como se puede ver en la siguiente imagen, antes lo podía hacer sin problemas.

![image](https://user-images.githubusercontent.com/70673073/94068267-54b8c000-fdc5-11ea-99e6-9d7601f291a1.png).

Me pasa lo mismo en el aula de Chamilo LMS

![image](https://user-images.githubusercontent.com/70673073/94088796-bf7af300-fde7-11ea-825a-789ded0e112a.png)

En las preferencias de la librería elFinder, no esta habilitado el archivo .pdf

Antes creo estaba de esta manera.

![image](https://user-images.githubusercontent.com/70673073/94089383-6c09a480-fde9-11ea-8617-5a8829927bad.png)

Espero respuestas que me puedan ayudar. Muchas Gracias !!!

**Comment by leandrotaborda** [comment]
@ywarnier disculpas las molestias y mi atrevimiento, podrías ayudarme que necesito que los alumnos puedan subir esos tipos de archivos.
Muchas gracias.

**Comment by carlangas159** [comment]
hola @leandrotaborda 

Este es un problema similar a https://github.com/chamilo/chamilo-lms/issues/3545, para ello he realizado un ajuste para permitir la carga de pdf en la red social.

**Comment by leandrotaborda** [comment]
Hola @carlangas159, Carlos funcionó prefecto, agradezco tu ayuda. 
Agregué algunos que necesitaba también como los documentos de office, guiándome con este archivo de la librería elFinder.
https://github.com/Studio-42/elFinder/blob/master/php/mime.types  

Saludos.

**Comment by leandrotaborda** [comment]
Perdón Cerré sin querer, disculpen ¿Tengo que cerrar yo, ya que se solucionó el problema?

**Comment by ywarnier** [comment]
@leandrotaborda si estás satisfecho con el correctivo, puedes cerrar, sí. Hay una propuesta de cambio que se maneja de otro lado para su inclusión en Chamilo, así que la operación correcta si tu reportaste el problema es que lo cierres cuando esté arreglado según tu.
