### ISSUE TITLE
Additional field request

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3537]
**I wish on the Learners reporting list, to have two additional field when exporting/downloading to excel to minimize confusion with learners with two similar names**

When 2 or more learning have similar names it creates confusion and time wasting to differentiate. I would wish the OfficialCode & PhoneNumber were included in this report printing to minimize the confusion.

**Comment by ywarnier** [comment]
@kemoche could you specify the URL of the report you are referring to?

**Comment by ywarnier** [comment]
This is a duplicate (by the same user) of #3578 
PLEASE @kemoche do not register twice the same requests. We have very little time to spare to attend the community, so if you start registering things twice, it just means less time for us to do something useful.
