### ISSUE TITLE
List of users (in a course) : displaying the total number of enrolled users (when there is less than one page of users)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3539]
Hi

I have a very little suggestion to make, in order to help teachers to identify problems with their list of users : it should be very useful to have the total number of enrolled users displayed at the top of the list.

![Capture20](https://user-images.githubusercontent.com/24507698/94288533-cc1e5900-ff57-11ea-9b97-fbce36bc8475.JPG)

Indeed, sometimes users are missing and the total number of users can help the teacher to quickly identify the problem and its cause...

Thanks

Tanchon

**Comment by ywarnier** [comment]
Hi @tanchon 
On your screenshot, this is the "40" in 1 - 40 / *40*.
Granted, you also give the number of active users, but the info for the total number of students is already there, at least.

**Comment by tanchon** [comment]
Hi Yannick !

Yes but the total number of users is only displayed when there is more than one page to display( i forgot to give this information in my first post : i edit the title).

In the configuration.php file i set this parameter : $_configuration['table_default_row'] = 250 because my teachers prefer that.

So, in my user list, the problem occurs when there is less than 250 users enrolled in the course : see this new screenshot => there is no information about the total number of users :

![Capture](https://user-images.githubusercontent.com/24507698/94356871-b44bef80-0093-11eb-84ba-8f2b0fc6b7d1.JPG)

Thanks.

Tanchon.

**Comment by ywarnier** [comment]
Good point, I hadn't noticed that. I guess we assumed that if it's the default of 20 per page, you can easily count them if there's less than one page, but you're right.

**Comment by tanchon** [comment]
👍  

There is the same issue with the user list (admin)
![Capture](https://user-images.githubusercontent.com/24507698/94366795-c9983c80-00da-11eb-8e07-6dfda174cb8f.JPG)

**Comment by tanchon** [comment]
Hi,

I deleted 2 lines in the sortable_table.class.php.
Now, whatever is the number of items and the maximum number of items that  i defined, the total number of items is always displayed à the top of the table.

![Capture5](https://user-images.githubusercontent.com/24507698/94988612-c552a000-056e-11eb-9371-80d18c9f4111.JPG)

See the result here : in the short term, that solves my problem. See the result with  $_configuration['table_default_row'] = 500 and 400 users to display  :
![Capture](https://user-images.githubusercontent.com/24507698/94988694-722d1d00-056f-11eb-8c96-d299c66e5f72.JPG)

Thanks

**Comment by ywarnier** [comment]
Seems fair to me to integrate this change. I don't see where it would create an issue.

**Comment by ywarnier** [comment]
In time for inclusion into 1.11.14. Thanks.
