### ISSUE TITLE
Uploaded Videos inside Rich media content files placed on Learning path "Full screen" not working

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3546]
As in the title we created Rich media content inside Documents and uploaded a video file to be played inside the Rich media document. Later we placed this document to a learning path. When we play the video and click on full screen the video enters full screen mode for 1 second then automaticly turn back to normal mode. No matter what we do it keeps doing this.

What can be the cause of the problem. I tried to recreate the issue at 11.chamilo but it worked just fine!!

Chamilo 1.11.12

**Comment by ywarnier** [comment]
I believe this has been fixed (or at least observed) by @AngelFQC

**Comment by AngelFQC** [comment]
This was related to mediaelement/mediaelement#2644.

I sent a pull request to fix it, but it could return when the assets are updated again.

**Comment by ywarnier** [comment]
We can probably avoid it by updating only one asset at a time and checking what's different.
