### ISSUE TITLE
Force use of Viwer.js for viewing PDF files on learning path

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3549]
Dears,

Teachers are adding uploaded PDF files directly to the learning path which works great on all devices except Mobile IOS devices because the pdf file is embed inside html iframe, it shows only the first page as an image and there is no way to download or view the rest of the PDF file. 

So is there a way to force downloading the file directly instead of opening it on the browser or forcing it to use Viwer.JS to view the file instead.

Kindly advice.

**Comment by ywarnier** [comment]
There is. This should be in your configuration.php. If not, feel free to add it:
```
// Activate the view with ViewerJS for PDF files within the lessons for IPad and IPhone
// $_configuration['allow_pdf_viewerjs_in_lp'] = false;
```
To enable the feature, remove the "// " at the beginning of the second line, and change false to true.
