### ISSUE TITLE
Control de entradas y salidas de BBB

### ISSUE THREAD

**Issue by EsMapachito** [chamilo/chamilo-lms#3552]
**Describe el problema**
En el control de entradas y salidas de BBB, cuando utilizamos el cron, va actualizando correctamente los tiempos de conexión y desconexión, pero cuando finalizamos la reunión mediante la opción correspondiente en la sala abierta, lo que ocurre es que actualiza todas las horas del cierre de conexión, de la sala que cerramos y de todas las salas de los dias anteriores, es decir, de toda la base de datos, y esto es un problema, porque el control de accesos se pierde y con ello la funcionalidad que pretendemos.
El funcionamiento debería ser que el cron va actualizando los abandonos parciales y cuando se produce el cierre de reunión se modificaría la hora de abandono de los últimos que permanecieran en el meeting.
Imagino que cuando el plugin corre la rutina de actualización con la instrucción de cierre, no hace bien la discriminación y actualiza el campo "out_at" en toda la tabla y no solo en el meeting y los registros que estén afectados.
Si pudieramos resolver esto, el funcionamiento sería perfecto, ya que de este modo mediante informes podríamos extraer los tiempos de conex y desconex a una videoconferencia ("Clase virtual"), a efectos de auditorias de asistencia.

**Comportamiento esperado**
Explicado más arriba.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10]
 - Navegador: cualquiera.

**Servidor
 - Sistema operativo : Windows Server 2019.
 - Versión de Chamilo:  última versión actual.
 - Versión de PHP: 7.2.

**Comment by ywarnier** [comment]
Gracias @EsMapachito , lo vamos a verificar (y corregir si es el caso)

**Comment by nosolored** [comment]
@EsMapachito, no conseguimos reproducir ese error.
¿estás usando la última versión del plugin? En julio realizamos unos cambios que mejoraban todo el tema de registros de acceso:
https://github.com/chamilo/chamilo-lms/pull/3348

**Comment by ywarnier** [comment]
Nota: estos cambios de versión de plugin también requieren cambios de base de datos que están documentados en el README de cada plugin

**Comment by EsMapachito** [comment]
Gracias, lo revisaré quizá sea por los cambios de la db.
