### ISSUE TITLE
REQ: separate documents for quiz

### ISSUE THREAD

**Issue by spacecabbie** [chamilo/chamilo-lms#3553]
**Is your feature request related to a problem? Please describe.**
Uploading images/documents used in quizes are stored in course documents this causes problems when you want to hide them cause then there also hidden in quiz.

**Describe the solution you'd like**
A separate central location to store images/documents for quizzes ideally linked to its perspective question.

**Comment by ywarnier** [comment]
You can hide documents but enable their display in exercises by placing the documents as "visible" *inside a folder that is invisible*. This way, students cannot get into the folder, but direct access to the file is still allowed from within the course.

**Comment by ywarnier** [comment]
Not sure if you want to reformulate this, or if, with that info, I could close this issue...

**Comment by spacecabbie** [comment]
> Not sure if you want to reformulate this, or if, with that info, I could close this issue...
That tip is quite useful thanks for that. I do think it's still a falit feature but it is the ends it's up to you of course.
My memory fails me occasionally I do apologize but i already made a better request about this: 
https://github.com/chamilo/chamilo-lms/issues/3616
