### ISSUE TITLE
Quiz : bug with immediate feedback or feedback as popup (linked with admin setting :  enable quiz scenario)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3555]
Hi,

When i create an exercise and i set "adaptative test  with immediate feedback" or "direct feedback as popup", a fatal error is displayed in the edit mode.

**To Reproduce**
1. create a new exercise (or edit an old exercise)
2. Choose immediate feedback or direct feedback
3. The next screen is the edit mode with fatal error message.

**Screenshots**
Message for "adaptative test  with immediate feedback" 
![adaptatif immediat feedback](https://user-images.githubusercontent.com/24507698/95655641-17646a00-0b09-11eb-8ef6-b3984d065ffa.JPG)

Message for "direct feedback as popup"
![popup](https://user-images.githubusercontent.com/24507698/95655694-5f838c80-0b09-11eb-86f3-87d09358eaf5.JPG)

**Server
Chamilo 1.11.12 ; PHP 7.3 (i made tests with 7.1, 7.2 and 7.4 : no change).

**Additional context**
Despite the fatal error, it is possible for teacher to create questions and then for students to access to the exercise and to make it. But for the teacher it is impossible to edit the questions (they are hidden).

If i defined display_errors = Off, the questions are hidden 
![Capture](https://user-images.githubusercontent.com/24507698/95650841-94cab300-0ae6-11eb-87fa-bb5c5dd31590.JPG)

I've got 2 chamilo platforms : they have the same issue.

Thanks

Tanchon.

**Comment by tanchon** [comment]
As we can see in this video, despite the error, it is possible to create questions and to execute the exercises : https://youtu.be/zeOlAcJuF6A

The only way to edit the questions is to define another feedback choice (see at 1'23'' : feedback at the end)...and after the edit, we have to define the popup feedback : it seems to work.

So, evertything seems to work, except that the error message avoid us to edit questions with immediate or popup feedback.

**Comment by tanchon** [comment]
I reproduced the bug in 11.chamilo.org (see this exercise : https://11.chamilo.org/main/exercise/admin.php?exerciseId=468&cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&)

It is linked with one admin setting : ENABLE QUIZ SCENARIO.
If it is set to "NO", then the bug occurs.

I don't know if it's a normal behaviour...

Tanchon

**Comment by ywarnier** [comment]
@NicoDucou This is fixed, right?

**Comment by tanchon** [comment]
HI @ywarnier 

I think it's ok now : when we set ENABLE QUIZ SCENARIO to NO, the options in the exercise settings are desactivated and there is no more bugs.

Thank you for that.

Tanchon

**Comment by NicoDucou** [comment]
Thank you @tanchon for the feedback
