### ISSUE TITLE
Checkbox deshabilitado en EJERCICIOS

### ISSUE THREAD

**Issue by damisio** [chamilo/chamilo-lms#3557]
**Describe el problema**
En las opciones del "Ejercicio" en la sección de "retroalimentacion" por cosas que no entiendo los CHECKBOX se han deshabilitado y convertido en (x). Lo que no deja realizar modificaciones.

![Selección_128](https://user-images.githubusercontent.com/10108808/95772117-d6439580-0c81-11eb-9373-d67f2b09e3c5.png)

**Cómo reproducir**
- Crear un EJERCICIO con sus valores predeterminados. Esto incluye  "Retroalimentación inmediata como pop-up" (habilitada para esta nueva version)
- Modificar configuracion del EJERCICIO

**Comportamiento esperado**
- Que los CHECKBOX dentro de la  configuracion del ejercicio se encuentren habilitadas.

**Capturas de pantalla**
![Selección_128](https://user-images.githubusercontent.com/10108808/95772117-d6439580-0c81-11eb-9373-d67f2b09e3c5.png)

**Contexto adicional**
Se esta utilizando SESIONES, dentro de ellas se asignan los cursos. Este inconveniente se ha producido casi en el 100% de los ejercicios creados por los profesores

**Comment by xam1234** [comment]
@damisio check this: https://github.com/chamilo/chamilo-lms/issues/3470

**Comment by carlangas159** [comment]
Buen dia @damisio 

Este es un comportamiento esperado, como lo comenta @ywarnier en el siguiente comentario del issue #3470 

https://github.com/chamilo/chamilo-lms/issues/3470#issuecomment-679417262

> Esto es como se esperaba. Esos tipos de pruebas no admiten todos los tipos de preguntas (en realidad, un subconjunto muy limitado). No entraré en detalles (porque hay una explicación muy larga y lógica para esto), pero esta es una característica, no un error.

Actualmente es parte del comportamiento normal de chamilo.
