### ISSUE TITLE
No permite guardar respuesta en Ejercicios

### ISSUE THREAD

**Issue by damisio** [chamilo/chamilo-lms#3560]
**Describe el problema**
No permite guardar respuesta en pregunta y no permite avanzar a la siguiente pregunta.

**Cómo reproducir**
Iniciamos en resolver el ejercicio, al momento de pasar las primeras preguntas todo va normal. De pronto al continuar con el ejercicio  al pasar a la siguiente pregunta con el boton "Siguiente pregunta" al csotado derecho se muestra un icono ROJO.

**Comportamiento esperado**
Al momento de hacer click en "Siguiente pregunta" deberia de mostrse un icono de disquette, guardarse la respuesta y pasar a la siguiente pregunta.

**Capturas de pantalla**
![IMG-20201013-WA0002](https://user-images.githubusercontent.com/10108808/95886178-e15efa00-0d43-11eb-8329-db4e6534b3da.jpg)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador chrome

**Comment by carlangas159** [comment]
hola @damisio 

Lo que comentas, posiblemente es debido que ingresaste en otra pestaña al sistema, ya que se limpia la información del curso. 

Puedes intentar replicarlo en 11.chamilo.org , normalmente si estas haciendo una evaluación en una pestaña o ventana, ingresas a otra parte del sistema en otra ventana o pestaña y regresas al examen, no puedes guardar.

**Comment by ywarnier** [comment]
Sin feedback en un mes. Cerrando.
