### ISSUE TITLE
Test: Student submit an answer for one of the questions but the answer is not saved

### ISSUE THREAD

**Issue by aelalfey** [chamilo/chamilo-lms#3561]
**Describe**
Our teachers are now using Chamilo tests to create quizzes for their students. Some teachers and students reporting that they submitted an answer for one of the Multiple choice or fill in the blank questions "and they are sure the answer is right" but when they finish the quiz the system tells them the answer is wrong for that question because the system didn't record their answer for that part of the quiz at all. As you can see in the picture below the answer of the student is not even recorded in the system "we are sure he did submit an answer for that question:

![11](https://user-images.githubusercontent.com/33488577/95948555-08273a00-0df1-11eb-8866-c906fc0f68c7.jpg)

![2](https://user-images.githubusercontent.com/33488577/95948570-0fe6de80-0df1-11eb-9314-4aa8ae7dea73.jpg)

This happens randomly in different tests for different users and different types of questions.

Do you have an explanation for that behavior and what might be the reason for that because teachers started losing trust in the quizzes/test section and its results.

Desktop:
 - OS: Windows 10
 - Browser: Chrome latest version

Server
 - OS: Plesk (CentOS) 18.0 on CentOS 7.7
 - Version of Chamilo: 1.11.12
 - Version of PHP: 7.3.23

**Comment by aelalfey** [comment]
Complaints are keep rising from different students that the same issue is happening on different types of questions "Multiple choice - Matching" but in this case students submit an answer but in the review page the system shows another answer "lets say student choose A and the right answer is A, the system shows that the student choose B which he didn't. 

Is there an explanation for that?!!

**Comment by aelalfey** [comment]
@ywarnier @NicoDucou @AngelFQC 

I am sorry for keep asking but this problem is now confirmed in all type of questions. The system randomly doesn't record student answers as mentioned above. Do you have any explanation/solution for this or do you need me to provide any further information to be able to investigate more.

Thank you in advance.

**Comment by rsprasad2001** [comment]
@aelalfey  Did you get the solution?. I am also facing the same issue

**Comment by aelalfey** [comment]
Hello @rsprasad2001 

I believe I am not having this issue anymore and in most cases it was due to low internet connection from the user side or even students try to blame the system for not saving their answers "which they didn't answer at all because they simply don't know the answer". 
Also choose "one question per page" option while creating the quiz to insure that the system saves each question answer before moving to the next. In all cases @ywarnier @NicoDucou are the right persons to direct your question to. 

Regards.

**Comment by rsprasad2001** [comment]
@ywarnier @NicoDucou please help me. None of the tests answers are getting saved. This is happening when a user is attempting without registering and just by accessing exercise url  like one below. It was working fine earlier.
https://www.iitianacademy.com/account/main/exercise/overview.php?cidReq=C10PHYNEMCQ&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=118&preview=1

**Comment by ywarnier** [comment]
Hi @rsprasad2001 
We don't support third party installations through our open channel. From what I can see, you are using version 1.11.8 of Chamilo, so I doubt anything on Chamilo's side would have suddendly changed your portal in a way that would have stopped working recently. Maybe check your network, your web server logs or your database logs to see if anything wrong appears there.
I tried your link and I can reproduce the issue, but your version is more than 3 years (and probably thousands of changes) old, so any observation would be irrelevant to current Chamilo code. It is possible that upgrading your Chamilo installation might be enough to fix it.
