### ISSUE TITLE
Session: Cuando se inactiva un usuario y este tiene la sesion activa, puede seguir navegando por el tiempo de la sesion

### ISSUE THREAD

**Issue by carlangas159** [chamilo/chamilo-lms#3566]
**Describe el problema**
Si inactivo un usuario, este puede seguir accediendo al curso hasta que se elimine la sesión en php

**Cómo reproducir**
Pasos para reproducir el problema:

Iniciar una sesión con un usuario
Como administrador, Ir a administración
Buscar el usuario y desactivarlo 
Con el usuario iniciado anteriormente, ejecutar acciones normales.

**Comportamiento esperado**
Al momento de desactivar el usuario, debe bloquearse los accesos a los cursos

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/18097392/96293169-f344d500-0faf-11eb-879e-29d94b3a6a48.png)

**Comment by ywarnier** [comment]
Implementado en 1.11.14
