### ISSUE TITLE
Plugin: BuyCourses: Añadir posibilidad de filtrar por categoría de sesiones al momento de comprar en catalogo de sesiones

### ISSUE THREAD

**Issue by carlangas159** [chamilo/chamilo-lms#3572]
Seria importante poder filtrar las sesiones por las categorías asignadas, de modo que al momento de filtrar no solo sea por nombre, precio mínimo y máximo, sino también, a la categoría que se le asigne a una sesión.

Esto se puede observar en https://campus.chamilo.org/plugin/buycourses/src/session_catalog.php
![image](https://user-images.githubusercontent.com/18097392/96748854-b9991300-138f-11eb-8da8-52c619cec06f.png)

Se puede aplicar la solución para poder modificar el plugin de compra de curso para añadir la posibilidad de filtrado por categorías.

**Comment by ywarnier** [comment]
Added to 1.11.14
