### ISSUE TITLE
upload Assignment option for open questions under Tests

### ISSUE THREAD

**Issue by shabsshab** [chamilo/chamilo-lms#3576]
Iam using chamilo 1.11.2

Can we add the upload option  ( https://prnt.sc/v5btvl  & https://prnt.sc/v5br8f  ) into open questions ( https://prnt.sc/v5bohs ) instead using ckeditor image upload ( https://prnt.sc/v5dxqg ) ?

**Comment by ywarnier** [comment]
No :-)

**Comment by shabsshab** [comment]
Thank you,
THis is very much require for lower standard kids those are not comfortable with screen typig for long question answers.

Also for language subjects(Arabic,hindi,, Urdu ,malayalam,........) will be difficult write in the keyborad , so write the answers  in a notebook and upload in the question
