### ISSUE TITLE
500er course_home.php => PHP Fatal error: Call to undefined method Exercise::cleanSessionVariables()

### ISSUE THREAD

**Issue by 22phuber** [chamilo/chamilo-lms#3577]
**Describe**
Opening a course leads to a 500 error. 

**To Reproduce**
1. Upgraded my Docker based chamilo lms installation from 1.11.10 to 1.11.12.
2. Login as admin or user (doesn't matter)
3. Navigated to one of the courses
4. Receive a 500er

`php_errors.log`: 
```
[23-Oct-2020 17:55:53 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to undefined method Exercise::cleanSessionVariables() in /var/www/chamilo/main/course_home/course_home.php:531
Stack trace:
#0 {main}
  thrown in /var/www/chamilo/main/course_home/course_home.php on line 531
```

**Expected behavior**
Course page opens normally 

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser chrome and Version 86.0.4240.111 (Offizieller Build) (x86_64)

**Server**
 - OS: Debian GNU/Linux 10 (buster)
 - Version of Chamilo: v1.11.12
 - Version of PHP: PHP 7.3.23 (cli) (built: Oct 13 2020 10:32:53) ( NTS )

**Additional context**
To temporarily fixing the issue i commented out line `531` in `course_home.php`:
```
…
530 api_remove_in_gradebook();
531 // Exercise::cleanSessionVariables();
532 DocumentManager::removeGeneratedAudioTempFile();
…
```
This allows to open the course without receiving a 500error

Could this be related to using php 7.3 instead of php 7.2 ?

**Comment by ywarnier** [comment]
How are you upgrading from 1.11.10 to 1.11.12? Through Git or through a download of the online package?
Yes, it can be linked to the change in PHP version if you are upgradring through Git and not issuing "composer update" at the root of Chamilo, before clearing the cache.
The Chamilo package already comes prepared with the update of dependencies, while a Git pull will need to be accompanied by a composer update and a cache cleaning operations.

**Comment by 22phuber** [comment]
Hi @ywarnier
I'm building a base image with chamilo lms. Downloading the `chamilo-1.11.12-php7.2.tar.gz` and unpack it. So there shouldn't be any artefacts from previous installations.
i'll try to build everything again with php7.2-apache image.

**Comment by 22phuber** [comment]
I still have the same error:
```
[root@xyz ec2-user]# docker exec -it e71258546f92 bash
root@e71258546f92:/var/www/chamilo# tail -f /var/log/php/php_errors.log
#0 {main}
  thrown in /var/www/chamilo/main/course_home/course_home.php on line 531
[24-Oct-2020 18:09:10 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to undefined method Exercise::cleanSessionVariables() in /var/www/chamilo/main/course_home/course_home.php:531
Stack trace:
#0 {main}
  thrown in /var/www/chamilo/main/course_home/course_home.php on line 531
[24-Oct-2020 18:09:13 Europe/Zurich] PHP Fatal error:  Uncaught Error: Call to undefined method Exercise::cleanSessionVariables() in /var/www/chamilo/main/course_home/course_home.php:531
Stack trace:
#0 {main}
  thrown in /var/www/chamilo/main/course_home/course_home.php on line 531
^C
root@xyz:/var/www/chamilo# php -v
PHP 7.2.34 (cli) (built: Oct 13 2020 11:32:15) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.34, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by 22phuber** [comment]
I've fixed the 500er issues. ✅ 
It's not related to the chamilo-lms code at all. It was a poorly developed custom plugin 🙈  which isn't compatible with the chamilo-lms v1.11.12. 
closing this
