### ISSUE TITLE
Replace "name" with "title" fields in tables

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3581]
Chamilo 2.0 is a great opportunity to clean the mess up a little bit in our database structure.
At the moment, there is a mix between fields called "name" and fields called "title", where they all represent the textual name of the item represented by the table row.

Move all "name" fields to "title", to sanitize this.

Making this a standard with help with the capability to predict the field name and, as such, will improve development speed in the long run.

Beware that some of these fields are also indexed. Indexes should be modified too.

Tables with "name":
* [x] block.name
* [x] branch_sync.branch_name
* [x] c_attendance.name
* [x] c_blog.blog_name
* [x] c_dropbox_category.cat_name
* [x] c_exercise_category.name
* [x] c_forum_category.cat_title
* [x] c_forum_forum.forum_title
* [x] c_forum_post.post_title
* [x] c_forum_thread.thread_title
* [x] c_glossary.name
* [x] c_group_info.name
* [x] c_link_category.category_title
* [x] c_lp.name
* [x] c_lp_category.name
* [x] c_online_link.name
* [x] c_quiz_question_option.name
* [x] c_role.role_name
* [x] c_survey_group.name
* [x] c_tool.name
* [x] career.name
* [x] chat_video.room_name
* [x] class_item.name
* [x] course_category.name
* [x] course_module.name
* [x] course_type.name
* [x] grade_model.name
* [x] gradebook_category.name
* [x] gradebook_evaluation.name
* [x] gradebook_linkeval_log.name
* [x] mail_template.name
* [x] promotion.name
* [x] sequence.name
* [x] sequence_row_entity.name
* [x] sequence_type_entity.name
* [x] sequence_variable.name
* [x] session.name
* [x] session_category.name
* [x] skill.name
* [x] skill_level.name
* [x] skill_level_profile.name
* [x] skill_profile.name
* [x] specific_field.name
* [x] ticket_category.name
* [x] ticket_priority.name
* [x] ticket_project.name
* [x] ticket_status.name
* [x] usergroup.name

So that's 48 changes, vs 39 'title' fields (and 38 pure "name" fields).

**Comment by christianbeeznest** [comment]
Request is done in this PR https://github.com/chamilo/chamilo-lms/pull/4706

**Comment by ywarnier** [comment]
Retaking your list here:

* [ ] fos_group is OK because we don't know yet what we're going to do with that table (probably remove it)
* [ ] c_shortcut
* [ ] c_wiki_category
* [ ] c_chat_conversation -> updated now
* [ ] illustration
* [ ] resource_type
* [ ] resource_format
* [ ] tool (It is strange because in the code there is already references to tool.title instead of tool.name
* [ ] skill_level (We have a title field and then a short_name field, I think it should be transformed to short_title)
* [ ] track_e_hotpotatoes (we have exe_name but in the c_quiz table it is called "title" now so I think it should be "exe_title")
* [ ] resource_tag
* [ ] lti_external_tool

**Comment by ywarnier** [comment]
Fixed through https://github.com/chamilo/chamilo-lms/commit/faeca062624e4fa0c0eba86e54c25e490c000f49
