### ISSUE TITLE
Human Resource Managers don't have access to course videoconference when there are groups

### ISSUE THREAD

**Issue by MAMEK70** [chamilo/chamilo-lms#3583]
**Describe**
When assigned to a course, HRM have access to course videoconference. But when groups are created in the course, HRM is (in some instances) not shown the "join conference" button in the videoconference page.

**To Reproduce**
1. Create a course attended by two groups.
2. As Moderator or teacher go to the course videoconference page, select one of the two groups and start a videoconference. 
3. As HRM, to whom the course is assigned, go to the course videoconference.
4. "Join conference" button is NOT shown to HRM.

**Expected behavior**
HRM should be able to see group selection box and "Join conference" button, and be able to join conference. 
By the way, if the Moderator starts the conference without selecting a group, the HRM is shown the "Join conference" button, as one would expect.

**Server:**
 - OS: Linux Ubuntu 16.04
 - Version of Chamilo:  1.11.12
 

**Additional context**

**Comment by ywarnier** [comment]
Agreed that the HRM that has this course assigned should be able to join any conference inside that course (even if it is in a group).

**Comment by MAMEK70** [comment]
I have tested the correction, and it solves the issue raised. HRM can join conferences in courses assigned to him.
Please note that not only HRM has access as a conference moderator (instead of a simple user),  but he can start the conference (just like the course teacher). For our usage, this is fine. But I am not sure everyone would agree!
Thanks a lot.
