### ISSUE TITLE
Learning path with prerequisites bug

### ISSUE THREAD

**Issue by LolaCapitani** [chamilo/chamilo-lms#3584]
Hello, everyone.
I have a problem: **my students can bypass the tests with one click to finish the modules.**

I just followed the manual ( https://docs.chamilo.org/teacher-guide/structure_learning_paths/prerequisites ) in which you read: 

_"This allows the teacher to require the learner to have completed another task in the learning path (e.g. the preceding task) before they can access this element, and also, **e.g. in the case of a test or assessment, to have achieved a given minimum score**"._

I can not solve this problem, which in my opinion is a bug, in this case I would like a possible solution since the courses are online and our work as teachers would be frustrated ...

Let's start with order.

I created a teaching module is composed of a test and an html page.

The html page has the test as a prerequisite, passing 80 out of 100.

If I click on the menu of the html page without having passed the test, the message "Item test One Block this step" appears.

Here in my opinion there is the bug.

The problem is that if I take the test, and I make a mistake, the progress bar goes 100%. 

**In this way the student passes the module even if he made a mistake in the questions of the test. And even if he never displayed the html page.** 

This is obviously a disaster, how can I do it?

Help us, we absolutely need that the student doesn't pass the teaching module without passing the test (i.e. the exam!).

Here are all the screenshots. I created the test **"Test prerequisites"** on the test platform 

https://11.chamilo.org

Test prerequisites
Lola Capitani

Thank you all, I am desperate, I do not know where I am wrong and how to solve the problem. Thank you, have patience, thank you again...

![01](https://user-images.githubusercontent.com/67590937/97211555-7ee41000-17bf-11eb-9cc6-7a2268b31a3c.png)

![02](https://user-images.githubusercontent.com/67590937/97211561-80add380-17bf-11eb-805a-ba673988bc93.png)

![03](https://user-images.githubusercontent.com/67590937/97211563-81466a00-17bf-11eb-8fd8-246d25aec728.png)

![04](https://user-images.githubusercontent.com/67590937/97211565-81df0080-17bf-11eb-8cb4-07a8b510a986.png)

![05](https://user-images.githubusercontent.com/67590937/97211571-82779700-17bf-11eb-8f85-699a1da10b00.png)

![06](https://user-images.githubusercontent.com/67590937/97211575-83a8c400-17bf-11eb-964b-eedb37c00d90.png)

![07](https://user-images.githubusercontent.com/67590937/97211578-84415a80-17bf-11eb-9676-269cd8e4a5c6.png)

**Comment by ywarnier** [comment]
@NicoDucou do you have any input to give us on this one?

**Comment by NicoDucou** [comment]
> @NicoDucou do you have any input to give us on this one?

No I do not have any input about this, I only reproduced a similar situation for another user, but still working on it to explain or understand how to reproduce it.

**Comment by NicoDucou** [comment]
I just reproduced the problem opening as admin https://11.chamilo.org/main/lp/lp_controller.php?cidReq=TESTPREREQUISITES&id_session=0&gidReq=0&gradebook=0&origin=learnpath&action=view&lp_id=259&lp_item_id=1157&exeId=710&fb_type=0#atoc_1157

I click on the second item "Learning fruits colours" I did not have access, then clicked back on the first item and started the exercise and did it wrong and it then passed the all learningpath to 100%

![image](https://user-images.githubusercontent.com/6579268/100221340-d689ae80-2f18-11eb-828c-7f2ba278821c.png)

And it is confirmed if you go now on https://11.chamilo.org/main/lp/lp_controller.php?action=list&cidReq=TESTPREREQUISITES&id_session=0&gidReq=0&gradebook=0&origin=&
![image](https://user-images.githubusercontent.com/6579268/100221605-2ff1dd80-2f19-11eb-97a2-34b602be9136.png)

So I confirm there is a problem here.

And I have a similar issue in the learningpath here https://11.chamilo.org/main/lp/lp_controller.php?cidReq=COURSTESTBT17841&id_session=0&gidReq=0&gradebook=0&origin=&action=view&lp_id=282&isStudentView=true where the last item that depends on the realisation of the exercise just before is marked as done whereas I never did the exercise. I just went from item Introduction to item Validation 1 then to item Validation 2 and got back to validation 1 and it marked the last item as done even if I can not see the item.
![image](https://user-images.githubusercontent.com/6579268/100222344-3c2a6a80-2f1a-11eb-92f2-9170dda698a7.png)

I tried on both case with Firefox 83.0 and user admin

**Comment by ywarnier** [comment]
This should be fixed by the latest changes sent by @jmontoyaa and included in 1.11.14 (to be released in a few minutes). Feel free to re-open if that is not the case.

**Comment by gigiotibaduiza** [comment]
El problema persiste y no si es necesario abrir otro item, los prerquisitos hacen que se bloquee totalmente la plataforma, estoy trabajando con 1.11.14 
![image](https://user-images.githubusercontent.com/13460342/135927040-39e647c7-3e4e-440b-9c96-3fdafebcef5d.png)
![image](https://user-images.githubusercontent.com/13460342/135927064-011e3c3e-8847-42ad-8e86-e7c5a5020e75.png)
