### ISSUE TITLE
Reuniones de Google Meet se muestran en todas las sesiones de un curso

### ISSUE THREAD

**Issue by damisio** [chamilo/chamilo-lms#3589]
**Tu solicitud está relacionado con alguna molestia? Describe...**
He creado dos sesiones , en cada sesión se ha incluido un curso. Ejemplo: Matemática 01.

SESION 01 - Seccion A:
Matematica 01 (Prof. Jose Perez)

SESION 02 - Seccion B:
Matematica 01 (Prof. Ana Peralta)

Cuando los profesores Jose y Ana crean una reunión de GOOGLE MEET en su SESION correspondiente. Las reuniones creadas por los profesores, todas se muestran en el cursos sin importar en que sesion se encuentren.

**Describe la solución que te gustaría encontrar**
Las reuniones creadas por el docente le deberían de aparecer solo en su SESION y no todas las sesiones creadas por diferentes usuarios.

**Contexto adicional**
De la misma manera como los enlaces, tareas, documentos. Las reuniones de Google Meet deberian mostrarse solo en la sesion y curso creada de un docente.

**Comment by aragonc** [comment]
@damisio gracias por reportarlo, enviare una actualización...

**Comment by ywarnier** [comment]
@aragonc quedan 5 días para el empaquetamiento de 1.11.14...

**Comment by ywarnier** [comment]
Fixed.
