### ISSUE TITLE
Error en timezone

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [chamilo/chamilo-lms#3590]
Hola que tal espero me puedan ayudar, estoy trabajando con un chamilo en versión 1.11.12 pero tengo un porblema con la hora de sistema, me marcar una hora erronea a la cual tengo asiganda, ya revise la base de datos, y la hora del sistema operativo pero  chamilo me esta mostrando otra hora.
Sistema Tue Oct 27 23:15:17 CST 2020
Base de datos: 

![image](https://user-images.githubusercontent.com/41083269/97395343-61d83b80-18aa-11eb-8530-135e848a1dd1.png)
 
En la parametros de configuracion de chamilo me marca esta hora

![image](https://user-images.githubusercontent.com/41083269/97395387-7a485600-18aa-11eb-856c-e73e92d484a3.png)

De igual manera el php.ini esta configurado a America/Mexico_City es un php7.2

No se si me falta configurar algo mas.
Por su ayuda gracias

**Comment by solvetechec** [comment]
Hola Camilo, intenta forzando timezone de MariaDB en el config file. 

Por ejemplo;

[mariadb]
default_time_zone = 'America/Mexico_City'

en el /etc/my.cnf.d/server.conf

Luego reinicia mariadb,

systemctl restart mariadb

**Comment by CamiloPerezOrtiz** [comment]
Gracias @solvetechec  si force el archivo de mariadb y ya me respeta la hora correcta gracias, cierro el tema.
