### ISSUE TITLE
Import error for XLS questions with empty answer

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3593]
When importing a quiz with a empty answer row, I get this error:
```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'answer' cannot be null in /var/www/x.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:141
Stack trace:
#0 /var/www/x.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(141): PDOStatement->execute()
#1 /var/www/x.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(160): Doctrine\\DBAL\\Driver\\PDOStatement->execute()
#2 /var/www/x.com/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php(279): Doctrine\\DBAL\\Statement->execute()
#3 /var/www/x.com/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(966): Doctrine\\ORM\\Persisters\\BasicEntityPersister->executeInserts()
#4 /var/www/x.com/www/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(335): Doctrine\\ORM\\UnitOfWork->executeInserts()
#5 /var/www/x.com/www/vendor/doctrine/orm/lib/Doctrine/ORM/EntityMa in /var/www/x.com/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 125, referer: https://x.com/main/exercise/upload_exercise.php?cidReq=EXAM&id_session=0&gidReq=0&gradebook=0&origin=
```

There should be some kind of check before (or when) triggering this exception, to avoid a blank page for the final user.
Ideally, saying which question could not be inserted would be great.
The question itself should not be inserted if one of the answers is empty and a message should appear: "The following question(s) could not be inserted because of an empty answer".

**Comment by carlangas159** [comment]
Hello @ywarnier 

Could you give me more information about this failure? Note that I have downloaded the example xls of chamilo, I have deleted the second column from the answers to some questions, I have eliminated the score, I have also left only one answer but I have not been able to replicate this problem.

Could you give me an example file to try?

I attach the test file that I have used without succeeding in repeating this failure.
[quiz_template.zip](https://github.com/chamilo/chamilo-lms/files/5497257/quiz_template.zip)

**Comment by ywarnier** [comment]
We did not catch the complete stack trace in time here, so it's a bit difficult to find the particular part of upload_exercise.php that failed, so we cannot fix it this time. Closing but watching out for it.
If anybody finds the same error, please upload the failing xls file here.
