### ISSUE TITLE
Missing course selector in Learning paths exercises results list

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3594]
When on https://11.chamilo.org/main/tracking/question_course_report.php?view=admin as admin there is a message indicating 
`Please select a course`
But there is no selector for courses before the Filter button so the report can not be used.

![image](https://user-images.githubusercontent.com/6579268/97676063-55add300-1a90-11eb-9e25-9304624c91bf.png)

Tested on 1.11.x of 2020/10/29

**Comment by lcubas** [comment]
https://github.com/chamilo/chamilo-lms/pull/3637

**Comment by ywarnier** [comment]
@NicoDucou did you check this fix in practice?

**Comment by NicoDucou** [comment]
> @NicoDucou did you check this fix in practice?

I just checked now and the report works, you can select courses and session and get a page with the report. I do not know what the report is supposed to show but it is possible to use it.

So I close this task.
