### ISSUE TITLE
Error 500 al intentar enviar mensaje

### ISSUE THREAD

**Issue by da-rodriguez** [chamilo/chamilo-lms#3597]
**Describe el problema**
Actualicé la plataforma a la v 1.11.12 y ahora resulta imposible enviar mensajes. El error que aparece es este

`PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 8192 bytes) in /var/www/aulavirtual/vendor/phpmailer/phpmailer/src/PHPMailer.php on line 2658, referer: https://aulavirtual.epet1.edu.ar/user_portal.php`

Sea cual fuere el valor ingresado al memory_limit de PHP siempre resulta insuficiente. En el error del ejemplo el valor estaba definido a 1024M :shock:

**Cómo reproducir**
Pasos para reproducir el problema:
1. Instalar Chamilo LMS 1.11.12 for PHP 7.2.x or 7.3.x
2. Ir a Bandeja de Entrada
3. Intentar enviar un mensaje
4. Ver el error 500 que aparece

**Comportamiento esperado**
Que el mensaje fuese enviado

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo: Linux Mint 20
 - Navegador: Chromium 84.0.4147.135

**Servidor
 - Sistema operativo : Debian 10
 - Versión de Chamilo:  1.11.12
 - Versión de PHP: 7.3

**Comment by ywarnier** [comment]
@da-rodriguez instalaste o actualizaste? Es probable que, por la actualización, necesites limpiar el caché (hay un enlace en la página de administración para hacerlo) porque justamente hemos cambiado la versión de PHPMailer en 1.11.12 y es posible que tu portal Chamilo esté confundiendo ambas versiones (y tenga dos carpetas con versiones distintas instaladas).
Debería solucionarse con una limpieza de caché.

**Comment by da-rodriguez** [comment]
Había hecho una instalación limpia, pero debido a varios inconvenientes
tuve que volver atrás.

**Comment by ywarnier** [comment]
@da-rodriguez todavía te pasa este problema o en qué situación estás ahora?

**Comment by da-rodriguez** [comment]
Volví a la versión que tenía anteriormente

**Comment by ywarnier** [comment]
OK listo. Cerrando porque no lo podemos reproducir. No te olvides limpiar el caché cada vez cuando actualizas (primera entrada en el bloque "Sistema" de la página de administración), aunque no creo que haya tenido relación en este caso.
