### ISSUE TITLE
Categorías en lecciones bloquea la vista de los datos de avance.

### ISSUE THREAD

**Issue by Cerebrando** [chamilo/chamilo-lms#3598]
### Current behavior / Resultado actual / Résultat actuel
Los administradores y profesores no pueden ver el resultado de sus alumnos en las lecciones.  Es necesario registrar a los alumnos en la categoría que contiene a la lección para que los datos se hagan visibles.

### Expected behavior / Resultado esperado / Résultat attendu
Los resultados deberías ser visibles sin la necesidad de registrar a los usuarios en la categoría.

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire
Crear una categoría, incluir una lección dentro y automáticamente los datos de resultados de la lección dejan de ser visibles.  Si luego retiran el curso de la categoría los datos vuelven a verse.

Reproducido en:  https://11.chamilo.org/main/lp/lp_controller.php?cidReq=15553&id_session=0&gidReq=0&gradebook=0&origin=&action=switch_scorm_debug&lp_id=163

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.12

![image](https://user-images.githubusercontent.com/69426550/97951017-b5dd9700-1d66-11eb-98bf-02bcb32cbab7.png)

**Comment by jmontoyaa** [comment]
Corregido
