### ISSUE TITLE
Multiple delete function broken in documents

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3605]
* in a course
* in documents
* create several documents (all in the same directory) (can be several PDFs uploaded, for example)
* mark all those documents together and select the drop-down action box at the bottom to "Delete" those selected documents
* two alert (red) messages appear:
  * "No archive has been selected"
  * "Operation impossible"

The files should all be deleted. I'm not sure what's broken. This used to work.

**Comment by carlangas159** [comment]
Hello @ywarnier 
I have verified the operation, I have placed a validation so that when it goes to replace a file there is no action variable. Thus leaving the batch action process with normal operation

**Comment by ywarnier** [comment]
Works for me. Thanks.
