### ISSUE TITLE
Quiz: Order of categories in categories tables appear randomly ordered

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3606]
* Create 4 quiz categories (you can do it in this order or any order, it doesn't really matter)
  * Cat 1
  * Cat 2
  * Cat 3
  * Cat 4
* Create a quiz
* Select "order by categories alphabetically, questions random"
* the list of categories appear, but not in alphabetical order (they look very random)

This doesn't (and shouldn't) depend on the mode of questions selection. Those categories should *always* appear ordered alphabetically in this table of main/exercise/exercise_admin.php. Also, they should appear ordered alphabetically in the results page (main/exercise/exercise_result.php).
I believe this *was* the case before, but I'm not sure.

**Comment by tanchon** [comment]
Hi Yannick,

I confirm that in the exercise_admin.php page, questions are not correcty ordered in the list  (but when the student exercute the test, everything is ok and questions are ordered as the teacher has defined in the exercise_admin.php page : see #3265 )

![Capture](https://user-images.githubusercontent.com/24507698/98901476-28abe800-24b4-11eb-95a4-f79ea143e37d.JPG)

Tanchon

**Comment by ywarnier** [comment]
fixed
