### ISSUE TITLE
Quiz: Max score shown to teacher is wrong when using categories

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3608]
**To Reproduce**
1. Create 4 quiz categories
2. Create 1 question in each category, with a max value of 10 points
3. Copy each question 4 times (so you have 5 questions in each category)
4. Configure the exercise to use 1 question per category (category ordered alphabetically, questions random)
5. Save
6. When looking at the list of questions, the message at the top says: "20 questions, for a total score (all questions) of 40".

"40" is the total score considering there is only 1 question per category, and 4 categories (and each question has a score of 10). However, the message is super confusing.

The number "40" should be "200" (20 questions of score 10), and there should be an *additional* message (see below) stating that the exercise is configured to pick 4 questions for a total score of 40.

This second message should *only* appear if we use another setting for the exercise than "Ordered by user".
$XQuestionsSelectedWithTotalScoreY = "Only %d questions will be selected based on the test configuration, for a total score of %d."

**Comment by AngelFQC** [comment]
With the PR

For questions by category:
![imagen](https://user-images.githubusercontent.com/1697880/100381844-e3290800-2fe7-11eb-87fa-2284ed3c2b2d.png)

For question with random selection:
![imagen](https://user-images.githubusercontent.com/1697880/100381791-bffe5880-2fe7-11eb-9f9c-3f46af5ae71f.png)
(second message already displayed)

**Comment by ywarnier** [comment]
:heart_eyes: 
Excellent. It becomes a bit too chattery in the second case but that's OK, it's much better now than it was before.
