### ISSUE TITLE
Forum: Remove nested view type from creation form

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3611]
When creating a forum in main/forum/index.php, there are 3 possible "Default view type": Flat, Threaded and Nested.
However, in a previous change this year, we removed the "Threaded" view, so offering the "Threaded" option does not make sense anymore.

Edit the forum creation form and remove the Threaded option.

**Comment by AngelFQC** [comment]
This requires a DB changes to remove the options related to `default_forum_view` settings in the `settings_options` table

**Comment by ywarnier** [comment]
> This requires a DB changes to remove the options related to `default_forum_view` settings in the `settings_options` table

I have authorized the removal of the option from the form only. We'll clean the database option when we have the opportunity.
