### ISSUE TITLE
Se confunden los nombres en Lista de cursos/Gestión administrativa

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3618]
**Tu solicitud está relacionado con alguna molestia? Describe...**
En la pantalla **Administración/Lista de cursos/Gestión administrativa**, cuando hay varios profesores se confunden los nombres y apellidos, porque están todos separados por comas.
Ejemplo en la captura de pantalla adjunta:
Nombre 1: **Ferrero, José Luis**.
Nombre 2: **Martin, Gustavo**.
Cómo se ven: **Ferrero, José Luis, Martín, Gustavo**.

**Describe la solución que te gustaría encontrar**
Cada nombre y apellido separado por punto, punto y coma u otro signo diferente de coma.
Con el ejemplo anterior: 
**Ferrero, José Luis; Martín, Gustavo**.
**Ferrero, José Luis. Martín, Gustavo**.

**Contexto adicional**
Chamilo Chamilo 1.11.12

![separar-con-punto-y-coma](https://user-images.githubusercontent.com/40075497/98469728-20a42d80-21c0-11eb-8cae-56cb4d42712a.jpg)

**Comment by ywarnier** [comment]
Me parece buena idea. Quizás con una parte extensible por si hay muchos (para que no rompan el equilibrio de toda la tabla).

**Comment by AngelFQC** [comment]
Con el PR la columna de profesores quedaría así

![imagen](https://user-images.githubusercontent.com/1697880/101098593-2dcef500-3591-11eb-8b1a-cc4c0180dd96.png)

**Comment by jolufe** [comment]
Se ve muy bien. Ahora es claro quién es quién. Disculpa @AngelFQC  pero soy nuevo en esto. No sé si me corresponde a mí cerrar el tema o qué acción debería tomar. Agradeceré tus indicaciones al respecto.

**Comment by AngelFQC** [comment]
@jolufe Usted tendría que aplicar los cambios de https://github.com/chamilo/chamilo-lms/pull/3695/files en los archivos de su portal

**Comment by jolufe** [comment]
Cambios aplicados. Funciona correctamente. Gracias.
