### ISSUE TITLE
Documents (in a course) : show system folders (and visibility of default multimedia folders)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3621]
Hi,

In the course settings, there is the "Show system folders" setting.

As it is configured, it is not very useful for the teacher. But i think it should be.
Indeed, it should be useful if this setting would have an effect on the "multimedia folders visibility". 

With Chamilo 1.11.12, only the admin platform can define it with "show default multimedia folders" setting in the admin panel. 

On my platform, i defined "show default multimedia folders" to "true" because it was a request from some teachers. 
But some others don't wan't to see these multimedia folders : if they set "Show system folders"  to "NO" it has no effect (the multimedia folders are visible).

**Describe the solution you'd like**
It should be great if there was a 3rd option for the admin platform with the  "show default multimedia folders" : yes, no, 'teacher choice'.
If the admin would choose the third choice, then the teachers could use "Show System folders" setting to define the visibility of multimedia folders.

**Additional context**
There is no consensus among teachers about  multimedia folders visibility. Teachers should have the choice.

Thanks.

Tanchon

**Comment by tanchon** [comment]
HI, 

In the short term, i found solution that seems to be ok for my needs.

I think that there is an issue with this setting in a course : 
![Capture4](https://user-images.githubusercontent.com/24507698/100192997-3c633f80-2ef3-11eb-873e-d7c0441f03d8.JPG)

Whatever is the teacher choice, it has no effect (whatever is the admin choice with "showing multimedia folders"). Only the admin can define the visibility.

On my platform, as admin,  I defined "show default multimedia folders" to "true" because it was a request from some teachers. But i want teachers have a way to hide these folders if they want (some teachers love it, some others hate it : they must have the choice).

I modified the "is_folder_to_avoid" in the document.lib.php file. By default, the function is 
![Capture1](https://user-images.githubusercontent.com/24507698/100192277-f2c62500-2ef1-11eb-841b-95a85cc9239b.JPG)

I dont know why, but despite     if ($systemFolder == 1) {$foldersToAvoid = [];}, the teacher choice has no effect.

The function with little adjustments :
![Capture](https://user-images.githubusercontent.com/24507698/100192479-55b7bc00-2ef2-11eb-992d-9ce647b33d68.JPG)

It has exactly the effects i want, and teachers have the choice (moreover, this adjustment gives utility to the "show system folders" setting). I always hide the "flash" folder, because teachers don't need it.

I made this adjustment some days ago and it seems to be ok for everybody.

Thanks.

Tanchon.

**Comment by ywarnier** [comment]
Nice. Thanks for the patch suggestion.

**Comment by AngelFQC** [comment]
Hi @tanchon 

I sent a pull request with your suggestion, except for the flash folder because it is a default directory and your suggestion is a use case very specific

**Comment by tanchon** [comment]
Hi @AngelFQC   : I copy here my answer made into the pull request (by mistake).

Thanks @AngelFQC !

It is more logical now
1- if the admin platform decide to hide system folders, teachers haven't the choice
2- if admin platform decide to show system folders, teachers have the choice.

May be that it could be relevant to hide the setting in the infocours.php in the case 1 (because in this case, whatever the choice of the teacher is, it will change nothing). But it's a detail and the adjustment is perfect from my point of view !

Thanks.

Tanchon.

**Comment by ywarnier** [comment]
Implemented
