### ISSUE TITLE
Portfolio tool

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3626]
One item is considered missing from Chamilo, although we kind of have it anyway: a Portfolio tool.

A portfolio, as described in https://www.clarke.edu/academics/careers-internships/student-checklist/resume-writing-and-portfolios/what-is-a-portfolio/, is a "compilation of materials that exemplifies your beliefs, skills, qualifications, education, training and experiences. It provides insight into your personality and work ethic.".

Of course, there are many other types of portfolio (a designer's collection of art pieces, a portfolio of investments, etc) but in our contect, this is something like is described above.

In Chamilo, there is an administration option called "Extended profile". We're going to rename it "Portfolio".
![portfolio-option](https://user-images.githubusercontent.com/609839/99044373-f7084f00-258f-11eb-91fb-efccc4abc13e.png)

It comes with a series of options (4 "fields") that are only related to the registration process. There's nothing to do about these.
![portfolio-options2](https://user-images.githubusercontent.com/609839/99044379-f96aa900-258f-11eb-92ba-0fdabfe0253d.png)

When enabling the "Extended profile", a set of 5 new fields appear in my profile:
![profile](https://user-images.githubusercontent.com/609839/99044735-857cd080-2590-11eb-8b60-602ee33643a7.png)

These fields are:
- My competences
- My diplomas
- What I am able to teach
- My productions (file attachment - could be your CV)
- My personal open area

They are enough to express:
- your beliefs (my personal open area)
- your skills (my competences)
- your qualifications (my diplomas)
- your education (diplomas)
- your training (diplomas)
- your experiences (what I am able to teach)

To make it clear that these components represent a *portfolio* (which apparently is not clear to most people) we will make a series of arrangements:
- create a special entry in my social network menu that says "My portfolio" (that shows the portfolio-related fields in a "view" (not edition) mode)
- create a special entry in my friends' social menu called "Portfolio" (with ?u=x&p=1 for "portfolio=enabled") that opens a new view in the central column that shows the same portfolio-related fields in view mode

![shared-profile-link](https://user-images.githubusercontent.com/609839/99045662-fa9cd580-2591-11eb-8e5b-9d575f5b9da2.png)

To make the fields clearer, we will add a few language variables to describe each of the portfolio fields in edition mode. I have added the corresponding terms in the Chamilo translation.

On the "shared profile" page, those fields already appear in the right column. They can stay there for now, this is not the current focus. This being said, the code in main/social/profile.php ~lines 182-236 can almost be re-used "as is" (only CSS styling should be changed, I think) for the new view.

**Comment by ywarnier** [comment]
I have already sent 2 commits, one of them labelled with the wrong issue ID: de93ab5c23293133b75586f0e3e83735b09bc5f6

**Comment by carlangas159** [comment]
hello @ywarnier 

Could you tell us if this problem has been solved? or also, we can improve it

**Comment by ywarnier** [comment]
Yes, sorry, solved! Thanks.
