### ISSUE TITLE
Quiz : hotspot results are not always correctly displayed

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3629]
Hi,

There is an issue with Hospot questions on my Chamilo 1.11.12 platform (reproduced with 11.Chamilo.org)

**Describe**
if the question isn't fully answered (with wrong or good answers)  on hotspot questions, the exercise_result.php and exercise_show.php display incoherent solution.

If the student finished the question (all objects have been placed), whatever the score is, then everything is ok (see here with a 100% score) 
![Capture0](https://user-images.githubusercontent.com/24507698/99124995-8438bb80-2603-11eb-9ad7-6d9376dd2846.JPG)

If he **he did not complete the exercise**, there are some issues, due to some missing objects :
![Capture2](https://user-images.githubusercontent.com/24507698/99125233-e72a5280-2603-11eb-9943-35319232fbbc.JPG)

If no question has been answered, there are some issues :
![Capture1](https://user-images.githubusercontent.com/24507698/99125245-eabdd980-2603-11eb-893e-39db8a867ed0.JPG)

**Server
Chamilo 1.11.12 (php 7.3)

Thanks

Tanchon

**Comment by AngelFQC** [comment]
Related (maybe) to #3508

**Comment by ywarnier** [comment]
Thanks for reporting the issue. It is unlikely we will be able to provide a fix for this in 1.11.14, but it is noted.

**Comment by AngelFQC** [comment]
> Hi,
> 
> There is an issue with Hospot questions on my Chamilo 1.11.12 platform (reproduced with 11.Chamilo.org)
> 
> **Describe**
> if the question isn't fully answered (with wrong or good answers) on hotspot questions, the exercise_result.php and exercise_show.php display incoherent solution.
> 
> If the student finished the question (all objects have been placed), whatever the score is, then everything is ok (see here with a 100% score)

Ok.

> 
> If he **he did not complete the exercise**, there are some issues, due to some missing objects :

Fixed with 1.11.14

> 
> If no question has been answered, there are some issues :

It shoudl be fixed with ae14fbf from 1.11.x from now

> 
> **Server
> Chamilo 1.11.12 (php 7.3)
> 
> Thanks
> 
> Tanchon

**Comment by tanchon** [comment]
HGi @AngelFQC 

It's great ! Your fix works perfectly as you can see below !

![Capture10](https://user-images.githubusercontent.com/24507698/100788179-03f0c380-3415-11eb-8c28-353d7738d34d.JPG)


![Capture50](https://user-images.githubusercontent.com/24507698/100788191-081ce100-3415-11eb-9989-3f59f93eb692.JPG)


Thanks a lot : with this adjustment, the exercise show reach the perfection :-)

Tanchon.
