### ISSUE TITLE
Time finished

### ISSUE THREAD

**Issue by EloFran** [chamilo/chamilo-lms#3630]
**Describe**
When you quit exercising before time runs out and you don't finish it, it won't let you do it again.
**To Reproduce**
1. start exercise with time'...'
2. leave without ending the time and without including any questions..'
3. when you come back in the exercise, it won't let you repeat it
4. See mensage 
![image](https://user-images.githubusercontent.com/37640520/99143899-a6f9bd00-2661-11eb-95c1-1df3c35f31dc.png)

**Expected behavior**
That the student can start the course again
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, firefox, ]

**Server
 - OS: [Linux Ubuntu 18.04]
 - Version of Chamilo:  [1.11.12]
 - Version of PHP: [7.2, ...]

**Comment by ywarnier** [comment]
This is the intended behavior: the time counter *continues* counting down while the student disconnected. This is to prevent students from leaving the exam, checking the answers then coming back to the exam.
Not a bug.
If you want your students to be able to "continue", don't put a time limit.
If you want your students to be able to take the test several times, add multiple attempts
