### ISSUE TITLE
Nav bar CSS 

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#3632]
I wish to re-adjust the navbar to accommodate more announcements - (see current navbar1 and desired nav-bar3 attached). 
Using the browser (firefox) inspect element its possible to adjust the css padding to get the desired adjustments but I am not able to get the same effect from the css file /home/.../public_html/web/assets/bootstrap/dist/css/bootstrap.css:4062.

Using the browser (firefox) inspect element, it shows that the css file to be adjusted is .../web/assets/bootstrap/dist/css/less/nav.less.css - which does not exist. 

Upon highlighting from the browser (firefox) inspect element, one sees the referenced file as .../web/assets/bootstrap/dist/css/less/nav.less.css but when you copy and paste, the file url copied is .../web/assets/bootstrap/dist/css/bootstrap.min.css - which line:11 that one is expected to adjust does not exist.

**Expected behavior**
As shown in nav-bar3.jpg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox, safari/waterfox latest

**Server
 - OS: CENTOS 7.9
 - Version of Chamilo: Chamilo 1.11.12
 - Version of PHP: 7.2

**Comment by spacecabbie** [comment]
Did you clear cache ? `https://docs.chamilo.org/admin-guide/system/archive_directory_clean-up`

**Comment by kemoche** [comment]
Yes, I have cleared the cache and no change.

**Comment by spacecabbie** [comment]
Righto wel the css shown is afaik generated via the cache looking at https://docs.chamilo.org/developer-guide/theming_through_css/the_cascading_structure it should be the std default css file witch on my install hold the navbar-* tags.
If that doesn't work then hopefully a dev can pickup here but they are rather bussy so it might take a bit.

**Comment by kemoche** [comment]
Successful @spacecabbie. Thanks.
I made changes on ../web/assets/bootstrap/dist/css/bootstrap.min.css.
Appreciate the direction.
