### ISSUE TITLE
Migrar instalación Chamilo manual (sin git) a git/composer

### ISSUE THREAD

**Issue by disgregador** [chamilo/chamilo-lms#3640]
Saludos.

En https://github.com/chamilo/chamilo-lms/tree/1.11.x se informa como instalar Chamilo con git/composer.

¿Existe ayuda para migrar un Chamilo previo instalado sin git para que se gestionen las actualizaciones con git/composer?

¿De qué manera se podría realizar en líneas generales?

Sería de gran ayuda para aquellas plataformas que se instalan manualmente o mediante alguna utilidad de paneles con Softaculous u otras.

Gracias.

**Comment by ywarnier** [comment]
Actualizar composer debería poder hacerse de todas maneras. De lo que yo sepa, los paquetes estables incluyen un composer.json que es lo único que necesitas para esto.

Del lado de Git es muy distinto. Nosotros voluntariamente eliminamos la carpeta ".git" del paquete estable, para que no revele directamente la versión precisa y para que no ocupe tanto espacio en el disco (si se incluye todo, son varios GB de historial adicionales).

Sin embargo, existe un método más o menos experimental para partir de una versión estable y actualizar a una versión de desarrollo:
 - determina tu versión exacta de Chamilo
 - encuentra en https://github.com/chamilo/chamilo-lms/releases esta versión y, al costado (columna izquierda) deberías encontrar el código hash de esta versión (este commit) en Git (por ejemplo para 1.11.12 es "c4cd72d")
 - en una carpeta separada (paralela a tu instalación), haz un clone de Chamilo `git clone -b 1.11.x https://github.com/chamilo/chamilo-lms clone"
 - entra en la carpeta "clone" y posiciona tu repositorio en el commit que encontraste arriba. Por ejemplo: `cd clone; git reset c4cd72d` (no estoy seguro, de memoria, de este comando - habrá que verificarlo)
 - esto debería poner este repositorio en un estado donde se encuentra en el commit que equivale al de la versión estable que instalaste
 - ahora copia toda la carpeta `.git` desde la carpeta "clone" a la carpeta de tu instalación estable de Chamilo
 - desde la carpeta estable de Chamilo, deberías ahora poder hacer `git pull origin 1.11.x` y obtener la última versión de desarrollo
 - antes de usar tu Chamilo, no te olvides hacer  `composer update` y luego limpiar el caché (hay un enlace para esto en el bloque "sistema" de la página de administración de Chamilo.
