### ISSUE TITLE
BuyCourses Culqi V2

### ISSUE THREAD

**Issue by solvetechec** [chamilo/chamilo-lms#3641]
Hi! 

I wonder if the Culqi payment method is still working on Chamilo 1.11.12 and BuyCourses V5. I dug on the code and I found that the Culqi API version is V1, even though Culqi's customer support says they are not supporting V1 anymore. Could this be a problem when using Culqi V2 on  Chamilo 1.11.12 and BuyCourses V5? 

I also found that the README file on the BuyCourses V5 plugin says "currently only PayPal works" and this text has not changed since 2016. However, I remember Culqi payment method working on those versions.

Thanks.

Hola!

Me gustaría saber sin Culqi aún funciona como método de pago en Chamilo 1.11.12 y el plugin BuyCourses V5. Encontre en el código que la versión actual sigue conectando con la V1 de la API de Culqi. Hable soporte al cliente de Culqi y me dicen que la V1 de Culqi esta descontinuada. ¿Podría causar algún inconveniente usar Chamilo 1.11.12 y BuyCourses V5 con Culqi V2?

También caí en cuenta que el texto del README en la V5 de BuyCourses dice que solo funciona con Paypal. Este texto no ha sido modificado desde el 2016. Sin embargo, recuerdo funcionando bien a Culqi como método de pago en estas versiones.

Gracias.

**Comment by ywarnier** [comment]
True. We haven't updated Culqi as we should have.
Culqi v1 was implemented but never really tested in production as far as we know.
Feel free to update to v2 and submit a PR, we'd gladly integrate it.

**Comment by solvetechec** [comment]
Thanks for the quick reply @ywarnier. Should Culqi credentials on V1 work on BuyCourses V5? or was it disabled/limited by code?

**Comment by ywarnier** [comment]
I have absolutely no idea. I guess they should work. There's been no effort to actively disable Culqi v1 on our side, at least.
