### ISSUE TITLE
New plugin: Positioning

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3644]
Nous avons besoin d'un plugin (pour lequel Damien va nous aider un peu) qui se "plugge" sur l'outil d'exercices mais qui s'affiche, dans le cours, comme un nouvel outil appelé "Positionnement".

Quand le prof entre dans l'outil, il y voit un texte explicatif (voir ci-dessous le dictionnaire des termes) + une liste des exercices qui correspondent à quelques critères:
 - ils ont des questions réparties sur *au moins* 3 catégories de questions
 - ils utilisent le nouveau mode d'affichage des résultats "Radar" (générés par chartjs)

Il peut alors sélectionner l'exercice qui agira comme "test de positionnement initial" et un autre qui agira comme "test de positionnement final".

Quand l'apprenant entre dans le cours avec un test de positionnement initial actif, et si le plugin a été configuré (au niveau global) de cette manière, aucun des outils du cours n'est accessible (blocage par layer CSS) jusqu'à ce qu'il ait passé le test de positionnement initial.

Quand il clique sur l'icône de l'outil positionnement, il voit une page qui lui indique (avec un graphique fourni par Damien) qu'il y a 3 étapes dans le cours:
 - compléter le test de positionnement initial
 - passer les parcours au-delà d'un certain pourcentage moyen (par défaut 75%)
 - compléter le test de positionnement final (initialement bloqué, jusqu'à ce qu'on ait 75%)

Sur la droite de la page, il voit le graphique radar, qui montre les différentes catégories (combinées des deux tests) de questions et le score maximal atteignable pour chacune. Ce graphique a 3 états:
 - vide: l'apprenant n'a encore rien fait
 - initial: l'apprenant a passé le test de positionnement initial et on ne voit que ce résultat, en orange
 - final: l'apprenant a passé le test initial *et* final, et on voit ses deux résultats (initial en orange et final en vert)

## En termes d'implémentation

Dans l'outil d'exercices, rajouter un mode d'affichage des résultats appelé "Radar", qui montre seulement un radar des scores (pourcentage) par catégorie ramenés sur une échelle de 0 à 10 (en plus de la fiche normale de l'apprenant). Voir dictionnaire des termes pour l'option d'affichage.

Le plugin "positioning" est un plugin de cours, on peut y configurer trois choses (voir dictionnaire des termes):
 - enable/disable
 - si le test initial est bloquant ou pas pour accéder au reste du cours
 - le pourcentage de progrès moyen dans les parcours à partir duquel le test final est débloqué

Sur la page du plugin dans le cours, pour les utilisateurs *enseignants*:
 - montrer la liste des exercices qui correspondent (faire une fonction qui les détecte):
 -- au moins 3 catégories de questions (avec une question au moins par catégorie)
 -- mode d'affichage radar
 -- une seule tentative autorisée
 - pour chaque exercice qui correspond, montrer 2 icônes grises: marquer comme test initial + marquer comme test final
 - un test initial ne peut pas être en même temps un test final, et on ne peut sélectionner qu'un test initial et un test final à la fois (jamais 2 tests initiaux)
 - sous la liste des tests, il faut montrer un radar global pour tous les élèves *qui ont passé un test* (ne pas prendre en compte les tests non terminés)
 - optionnel (peut être implémenté dans un second temps): aussi montrer une liste des apprenants (dans un onglet chargé en AJAX?) avec leur graphique chacun (en petit) et une pagination

Pour l'apprenant:
 - si l'option du plugin est activée et qu'un test de positionnement initial a été sélectionné, la page principale du cours se bloque et on affiche l'icône de l'outil positionnement uniquement (modale grise)
 - dans l'outil positionnement, on affiche le design des étapes sur la gauche et le graphique radar sur la droite. La première étape du design de gauche est le test de positionnement
 - si le test initial a déjà été passé, il ne s'affiche plus comme un lien (simple texte non-clicable)
 - le test final apparaît comme simple texte non-clicable *jusqu'à* ce qu'on ait atteint le pourcentage défini comme moyenne de progrès des parcours. À ce moment, le lien du test final devient un lien vers le test final.
 - une fois qu'on a tout passé, il n'y a plus de lien clicable, seulement le design de gauche (rien n'est clicable) et le graphique en radar à droite avec les deux séries (orange et verte).

### Exercices

```
$ExerciseCategoriesRadarMode = "Only show a radar of scores by category, instead of a table of categories. Do not show individual scores or feedback.";
```

### Plugin

README.md
```
Positioning
======
This plugin adds a positioning test tool in every course.
Positioning tests should be used before and after any course. One initial test should be taken before anything else is used in the course, and a final test (usually a copy of the same test) should be used at the end. A radar-chart will show the differences between the initial test and the final test for each learner.

For a test to be used as initial or final test, it has to match 3 criteria:
 - use at least 3 question categories
 - use the "radar" type result page
 - have only one available attempt
```

lang/english.php
```
$strings['plugin_title'] = "Positioning";
$strings['plugin_comment'] = "Adds positioning tests to the course homepage";
$strings['tool_enable'] = "Enable plugin";
$strings['BlockOtherTools'] = "Block other course tools";
$strings['BlockOtherToolsHelp'] = "When this option is enabled, if an initial positioning test has been configured, the learner will not be able to use the rest of the course on the course homepage until he/she has completed the initial test.";
$strings['EndTestUnlockThreshold'] = "End test unlock threshold";
$strings['EndTestUnlockThresholdHelp'] = "Learners *must* have an average progress of at least this percentage (e.g. '75' for a 75% progress required) in the combined learning paths of this course.";
$strings['PositioningIntroduction'] = "Please select one initial test and one final test below. Only tests that match the 3 following criteria will be available for selection: use at least 3 question categories, use the radar report mode *and* have only one possible attempt allowed. Once these are selected, the student will only be able to pass the final test if he/she has completed the average of all learning paths in this course to %S or more.";
$string['SelectAsInitialTest'] = "Select as initial test";
$string['UnselectAsInitialTest'] = "Unselect as initial test";
$string['SelectAsFinalTest'] = "Select as final test";
$string['UnselectAsFinalTest'] = "Unselect as final test";
$string['InviteToTakePositioningTest'] = "Please take this positioning test before you start. This will help us measure the quality of this course.";
$string['InitialTest'] = "Initial test";
$string['YouMustCompleteAThresholdToTakeFinalTest'] = "You must complete at least %s of progress on average for all learning paths to unlock the final test.";
$string['FinalTest'] = "Final test";
```

**Comment by ywarnier** [comment]
In a previously-existing course, after enabling the plugin (and running composer install), when I enter the plugin page, I get a weird error on $table->set_header() being called on a string... (I only have one exercise that does not match the criteria in my course).
```
PHP Fatal error:  Uncaught Error: Call to a member function set_header() on string in /var/www/chamilo111x/plugin/positioning/start.php:85
Stack trace:
#0 {main}
  thrown in /var/www/chamilo111x/plugin/positioning/start.php on line 85, referer: http://my.chamilo111.net/courses/COURSE1/index.php?id_session=0
```

**Comment by ywarnier** [comment]
When there is at least one test that matches the conditions, the page appears normally.

**Comment by ywarnier** [comment]
The LP progress doesn't reflect in the plugin page. I have 100% progress but the plugin page with the initial and end test show 0% progress. Not sure if this is linked already...
In any case, the rest is pretty much working as expected. Congrats!

**Comment by jmontoyaa** [comment]
I just fixed the fatal error and also I fixed the LP progress (I was showing the score instead of progress).

**Comment by ywarnier** [comment]
Officially tested and delivered! :-)
