### ISSUE TITLE
Caja de texto no se muestra (ckeditor)

### ISSUE THREAD

**Issue by damisio** [chamilo/chamilo-lms#3645]
**Describe**
No muestra caja de texto (ckeditor) al momento de agregar una descripcion en una  tarea. Al parecer los plugin de ckeditor no se encuentran. 

Realize :
composer update

Y no tuve resultados
**To Reproduce**
Al momento de crear una tarea, no me muestra la caja de texto para agregar la descripcion

**Expected behavior**

**Screenshots**
![Selección_014](https://user-images.githubusercontent.com/10108808/99659326-b5afed80-2a2e-11eb-8b93-9bf7c9cafb07.png)

**Comment by ywarnier** [comment]
Hola @damisio, la información que das es demasiado poca para poder ayudar, pero se trata de soporte y no de un bug.
Lo más probable es que hayas hecho un cambio de algún tipo (cambiado de ruta, de subcarpeta o algo así) y no hayas limpiado el caché de chamilo, lo cual se puede hacer desde el enlace correspondiente en el bloque "Sistema" de la página de administración.
Mira la ruta en tu consola JS y verifica (cargando la URL a mano) si efectivamente estos archivos se encuentran ahí (tanto en el servidor como si el navegador puede cargarlos o no). Te ayudará entender el problema.
Para solicitudes de soporte como esta, tu mejor amigo es el foro de Chamilo en https://forum.chamilo.org, no Github donde se reportan bugs o solicitudes de nuevas funcionalidades. Gracias y suerte!
