### ISSUE TITLE
Quiz : question timer and the copy of questions

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3646]
Hi,

**Is your feature request related to a problem? Please describe.**
I tried the "question timer" on my 1.11.12 platform (in real conditions) and it works very well ! Thank you for that, because it"s very useful.

But there is a little lack, not directly due to the timer itself. **When the teacher wants to copy questions or exercises, the values stored in the extra-field "time" are not copied** => the teacher has to enter the values of "time" for each question copied (it's a tedious task !).

**Describe the solution you'd like**
It would be very nice if the values stored for each question in the "time" extra-field, would be copied with the question and/or exercise (as for other settings of the questions).

**Additional context**
The "copy" of a question or exercise is often used by teachers and it would be a great saving of time to have this enhancement put in place.

Thanks.

Tanchon.

**Comment by ywarnier** [comment]
Hi @tanchon 
Are you copying inside the same course (reusing) or copying from one course to another (real copy)? Asking for a friend...

**Comment by tanchon** [comment]
HI @ywarnier 

It is : 
- inside the same course: when you click on the icon "copy of the exercise" .
-  or inside the same exercise, when you click on the icon copy of the question.

The most important is the first point : the copy of the exercise (inside the same course). The copy of the exercise is very useful for teachers because the "copy" is a always perfect clone of the base exercise you copied : everything is exactly reproduced... except the time you defined for each question : in the "copy", the value for the timer is "null".

Thanks.

Tanchon.

**Comment by jmontoyaa** [comment]
That's because the copy of extra fields has not been implemented. I will add a fix when copying an exercise.

**Comment by jmontoyaa** [comment]
The concept of question/exercise extra fields are quite new in 1.11.x

**Comment by tanchon** [comment]
@jmontoyaa 

I've just tried this fix : it works perfectly when i copy a question into an exercise or when i copy an exercise into a course.

Thanks a lot !

PS : this question timer has a great success among teachers : they adopted it very quickly (it has less success among students :-))

**Comment by jmontoyaa** [comment]
@tanchon great to hear that!!! :)
