### ISSUE TITLE
Error al actualizar usuarios por csv

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [chamilo/chamilo-lms#3652]
Hola
Estoy usando la opción de actualizar usuarios por csv de chamilo en en la version 1.11, carga el archivo csv sin problemas pero cuando intento acceder ya desde el nuevo numero de usuario no me deja incluso no me marca ningun error. 

![image](https://user-images.githubusercontent.com/41083269/99841841-6c49c600-2b34-11eb-80c6-4803cf1dca54.png)

solo se recarga la pagina y hasta ahí se queda, no se si tenga que hacer algo mas en el archivo csv llene los campos necesarios y desde ahí no hay problema incluso desde el perfil de admin si se ve que actualizó el usuario, pero no da accesos cuando ya trato de hacer el login.

**Comment by ywarnier** [comment]
Hola @CamiloPerezOrtiz 
Podrías compartir un ejemplo de tu archivo CSV con solo 2 líneas (puedes modificar los valores para anonimizarlos, pero no cambies la estructura)?

**Comment by CamiloPerezOrtiz** [comment]
Hola @ywarnier 
Claro que si anexo una captura del archivo

![image](https://user-images.githubusercontent.com/41083269/100291307-09489c80-2f43-11eb-9579-0d8f007568ff.png)

Los campos que solo estoy colocando son estos: 
UserName
LastName
FirstName
Email
NewUserName
Password
AuthSource

Las instrucciones de la pantalla donde se realiza la carga del csv me indica que estos son los obligatorios, no se si estoy cargando los campos correctos o en efecto tengo que agregar todos los demas campos que hay menciona, el objetivo que quiero realizar es solo hacer el cambio del usuario por otro.

**Comment by carlangas159** [comment]
Hola @CamiloPerezOrtiz 

Te comento que he hecho una importacion con el iguiente archivo
[unico.zip](https://github.com/chamilo/chamilo-lms/files/5631851/unico.zip)

Solo tome el ejemplo que esta por defecto en chamilo 
LastName;FirstName;Email;UserName;Password;AuthSource;OfficialCode;PhoneNumber;Status;Courses
Mcfly 3;Marty 3;marty3@example1.com;marty3;secret;platform;12345678;001-123-456-789;user;COURSE1|COURSE2|COURSE3

Pude ingresar correctamente con marty3 y clave secret, Puedes adjuntarme un archivo con una linea de codigo? puede ser compreso en zip como el que he colocado aqui.

Tambien podrias revisar el archivo en cuestion por notepad, date cuenta que es posible que excel establezca la separacion como tabulador, pero en este caso, seria requerido el ; , si es el caso, puedes reemplazar las tab con ; y poder intentarlo de nuevo, por los momentos, 
![imagen](https://user-images.githubusercontent.com/18097392/100927395-d4909400-34b2-11eb-83e7-f12b6ff25900.png)
te muestro la carga de usuario
![imagen](https://user-images.githubusercontent.com/18097392/100927447-e6723700-34b2-11eb-976f-00407c798b88.png)
y el ingreso exitoso

**Comment by CamiloPerezOrtiz** [comment]
Hola @carlangas159 gracias por la respuesta solo que tengo un par de dudas, en donde quiero subir el archivo csv es en actualizar usuarios por csv, no en importar (crear usuarios), cheque el archivo que me mandas de ejemplo y por la estructura que este trae creo que es para importar (crear usuarios) y no para actualizar, o no se si el ejemplo que esta en actualizar usuarios por csv este mal.

![image](https://user-images.githubusercontent.com/41083269/100947132-9901c400-34ca-11eb-9dda-739b0d64100e.png)


De igual manera si he checado el archivo que no contenga espacias o tabulaciones de mas, los trabajo con libre office Calc y al final de generar el archivo los abro con sublime text para asegurarme de que en efecto no se haya pasado un carácter extra.

![image](https://user-images.githubusercontent.com/41083269/100947705-cf8c0e80-34cb-11eb-85b5-025a677a9016.png)

Cuando subo este archivo no me marca ningun error y si me hace el cambio de usuario, pero cuando intento ingresar con el nuevo usuario, no me deja y no me marca ningún error, solo se actualiza la pagina de login pero no me da acceso o alguna notificación, incluso en el confguracion de chamilo ya he colocado el servidor en desarrollo para ver si me muestra algo pero nada.

![image](https://user-images.githubusercontent.com/41083269/100948236-06165900-34cd-11eb-851c-ff4371382bf5.png)

De igual manera agrego en el zip el archivo csv que estoy utilizando

[ejemplo.zip](https://github.com/chamilo/chamilo-lms/files/5632920/ejemplo.zip)

**Comment by carlangas159** [comment]
Buen dia @CamiloPerezOrtiz 

He revisado el archivo que ha enviado de ejemplo, efectivamente le faltan elementos para el logueo del usuario, el campo AuthSource se utiliza para determinar el tipo de ingreso al sistema, date cuenta que en el archivo que envias falta este campo, normalmente se usa *platform*
Te adjunto una imagen comparativa, entre los campos que tienes, los campos que existen en chamilo y los campos del archivo de ejemplo.
![imagen](https://user-images.githubusercontent.com/18097392/101195566-99ff3680-362d-11eb-98f4-1151e769ec85.png)

En este particular, te recomendaria ir a la edicion de cada usuario y actualizar su contraseña, ya que esta no se actualizaria por esta via. La contraseña seria para nuevos elementos.

Tambien debo acotar que el campo NewUserName no esta entre la variables de chamilo, por lo tanto no tiene efecto. 
los campos se pueden observar en la seccion de importacion, debajo del boton Importar.
![imagen](https://user-images.githubusercontent.com/18097392/101196808-370e9f00-362f-11eb-8fbf-05ef3e1a2bff.png)

**Comment by CamiloPerezOrtiz** [comment]
Hola @carlangas159 gracias por la aclaración si en efecto me falta el campo de AuthSource ya que en el archivo lo tenia en blanco y al colocar el valor de platform ya se logro cargar el archivo. Gracias, cierro el detalle.
