### ISSUE TITLE
LP : bug with the "move" button item in the item list

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3653]
Hi,

There is a little issue on my 1.11.12 Chamilo platform ([reproduced with 11.chamilo.org : see here](https://11.chamilo.org/main/lp/lp_controller.php?cidReq=COURSTANCHON&id_session=0&gidReq=0&gradebook=0&origin=&action=add_item&type=step&lp_id=271&isStudentView=false)).

Sometimes, an error message is displaying after clicking on the move button, in the item list.

Here, with 11.chamilo.org  

![Nouvelle image - Copie](https://user-images.githubusercontent.com/24507698/99936809-4f93d500-2d64-11eb-8365-ac9e90ea943d.jpg)

After clicking on the button, this message appears :

![Capture](https://user-images.githubusercontent.com/24507698/99936828-5a4e6a00-2d64-11eb-9628-4c76d36f8093.JPG)

Here the message on my platform :
![Capture2](https://user-images.githubusercontent.com/24507698/99936876-84a02780-2d64-11eb-93a3-abde01987a58.JPG)

**To Reproduce**
1. Go into the edit mode in a lp
2. Click on an item in the item list, on the move button
3. The error message is displaying

**Expected behavior**
This message displays with documents and links, but not if the item is an exercise.  It should be possible to use the button with documents and links to.

**Server
Linux. Chamilo 1.11.12
Reproduced on 11.chamilo.org

Thanks.

Tanchon.

**Comment by tanchon** [comment]
Hi @jmontoyaa 

I tried your fix and it partially solved the issue : with documents, it's perfect. 

But the issue remains for links from the tool links* (here an image from 11.chamilo.org when i try to move the wikipedia link... it is the same thing on my platform).

![Capture](https://user-images.githubusercontent.com/24507698/100394122-3fb61280-303c-11eb-8024-15d54e185e72.JPG)

I don't know if there is a link with that problem but i have another issue with links from tool links : #3665.

Thanks.

Tanchon

*i tried with cloud links, but it seems impossible to use it into a LP.

**Comment by jmontoyaa** [comment]
Thanks for the feedback, I just added some more fixes.

**Comment by tanchon** [comment]
I made some tests with these fixes : it seems to be ok.  There is no more error message neither with the documents, nor with the links.

Thanks !
