### ISSUE TITLE
Groups : csv file import => file example is wrongly named

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3663]
**Describe**
Hi,

Into a Group, when we want to import groups by csv, the file example is bad (named "1" instead of "example.csv). For teachers, it is annoying.

This issue has been reproduced on 11.chamilo.org (and is present in 1.11.12).

![Capture](https://user-images.githubusercontent.com/24507698/100101856-1726f080-2e63-11eb-9f5f-951d4b107a76.JPG)

![Capture2](https://user-images.githubusercontent.com/24507698/100101884-1ee69500-2e63-11eb-8859-bc53ccc7eb02.JPG)

**Expected behavior**
When we click on the link, the file example downloaded is correctly named.

**Additional context**
If we add ".csv" to the name file downloaded, everything is ok : it is just little issue with the name (but teachers think that the file is corrupted and sometimes, they are very confused, particularly if they never import groups by csv).

Thanks.

Tanchon.

PS : here is the file as it is downloaded (i had to put it into a zip)
[zip.zip](https://github.com/chamilo/chamilo-lms/files/5590232/zip.zip)

**Comment by ywarnier** [comment]
Thanks for reporting.
This was due to a bad configuration of the `download=` HTML attribute. This is fixed now.
