### ISSUE TITLE
Links tool (in a course) : after moving a link into a category, other links disappear (RESOLVED)

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3665]
Hi,

In the tool link, there is an issue i reproduced on 11.chamilo.org :[ see this course ](https://11.chamilo.org/main/link/link.php?cidReq=COURSTANCHON&id_session=0&gradebook=0&origin=&gidReq=0)

**Here is a short video to understand the issue**, because it is hard to explain it : it is a very strange behavior : [see the video here](https://youtu.be/7bEbHkzsNBA). You can play the video from the 40''... 

**To Reproduce**
1. Go to the links tool into a course
2. Create some links
3. create some categories
4. move a 1st link into a category : it's ok (see the video from 50'' to 60'' : Google link moved into the "Repertoire 1"
)
5- move a 2nd link into another folder  (see the video from 1'00 to 1'10'' : Wikipedia link moved into the "Repertoire 2". You can see that the 1st link has disappeared from the "Repertoire 1" !
6- After that : i move the Wikipedia link from Repertoire 2 to the root and then i move it into the Repertoire 1... and the Google link reappear ! (see the video from 1'50 to 2'05)
7- After that, when i move the Google link... it is the Wikipedia link that disappeared !

**Expected behavior**
Links should always  stay visible.

**Additional context**
This issue is very confusing for teachers and learners because when links disappeared teachers create another link to face the issue and when the "old link" reappeared, there are multiple similar links into the tool.

Thanks.

Tanchon.

**Comment by tanchon** [comment]
Hi,

Today, i discovered that what we see into the video is normal (but not optimal for users)  : there is no bug, just some confusions due to the way elements are displayed by default.

 I made an adjustment to change the default view. and it is more intuive now, as you can see in this 2nd video (i've made the same operations as in the first video above, by moving links into folders) : https://youtu.be/Mm5phLus2FA (you can compare with the default situation : https://youtu.be/7bEbHkzsNBA?t=40)

Indeed, by default, when categories are created, elements are displayed with the flat view. This flat view is far to be optimal.

With this flat view, the content of a category is displayed only if you activate it by clicking on it. 
**Moreover, this flat view cannot display the content of multiple categories** : if you click on a category, the latter is activated and displayed => the category that was previously activated is disactivated.
When we move a link into a category, the latter is activated : that explains why we have the impression that other links (into the previously activated category) "disappeared".

With the nested view, there is no confusion : all the content of all categories is displayed.

That's why i modified the default view with this little adjustment on my platform (into the link.phph file) :
![Capture](https://user-images.githubusercontent.com/24507698/100517220-70579280-3189-11eb-8476-0d6988e28fb1.JPG)

Thanks

Tanchon

**Comment by tanchon** [comment]
PS : i suggest something for the flat view => when a category is desactivated (its content isn't displayed), there should be a visual effect (like a "green +") to make the user aware that the content of the category is hidden and that he can display it by clicking on the category.

Thanks.

**Comment by ywarnier** [comment]
PR #4478 should fix this

**Comment by ywarnier** [comment]
There's still a lot to do to put this tool back into shape, but at least the links do not disappear and the default view is nested in Chamilo 2.0
