### ISSUE TITLE
QUIZ : impossible to go to the next question after update [SOLVED]

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3684]
Hi, 

With the last version (1.11.14), everything seems to be ok, for the moment (except with some plugins see #3685 ). But i have one issue on my platform : when i execute an exercise it is impossible to go to the next question.

The issue seems to be caused by exercise.ajax =>  if i comment these lines, everything is ok :

![Capture](https://user-images.githubusercontent.com/24507698/100709299-1f74b380-33ae-11eb-82e8-6aeaf8e7e67f.JPG)

**To Reproduce**
1. Go to quiz
2. Execute it
3. It is possible to make the first question
4. Click on "next"
5. We can see the little wheel that is spinning endless... impossible to reach the second question, even after a long time.

**Server
Linux. Chamilo 1.11.14 (from 1.11.12). PHP 7.3

**Additional context**
I cannot reproduce the issue on chamilo.org. When the "hook" lines are commented, everything is ok.

Thanks.

Tanchon.

**Comment by ywarnier** [comment]
Hi @tanchon 
How did you update from 1.11.12 to 1.11.14? Git pull? If so, you *need* to execute `composer update` after the install (and it cannot show messages in red, which are usually permissions related errors)

**Comment by ywarnier** [comment]
Just tested a fresh Chamilo 1.11.14 install (which is prepared to run on PHP 7.1) with PHP 7.4 (the most distant possible from the expected version) on a clean server and cannot reproduce this error. I really think this is an upgrade procedure issue.

**Comment by AngelFQC** [comment]
hi @tanchon 
If you have installed from github, then you need execute `composer update` maybe

**Comment by ywarnier** [comment]
Then (if not using git) try to clear the cache, then (Administration -> System -> Clean cache). This might generate issues of old JS stuck in the site or your browser's cache.

**Comment by tanchon** [comment]
Hi @ywarnier  @AngelFQC 

Thanks for your advices. 

I installed Chamilo on a 1.11.12 plaform with the method of the "zip file" ([see here](https://docs.chamilo.org/v/1.11.x-fr/guide-administrateur/installation_et_configuration/mise_a_jour_de_la_plateforme_chamilo)). This platform is a "clone" on my main platform.
@ywarnier yes, i cleaned the cache before and after...
I didn't use git.

There is an evolution : i've tried one more time this evening, with the zip file => I don't know why, but my plugins issue is solved ! (#3685)

But my problem with the exercise remains.
=> for information , I just had to adjust the Cquiz.php and the CExerciseCategory.php files with "@orm" because i use the exercise categories (and after the update i had an error message due to these files when i opened the exercises tool). No more problem with exercise categories now.
In order to verify if it could be these categories that causes the issue of "question stucking", I tried to desactivate exercise categories in the configuration.php file but it doesn't change anything to this issue.

I'll try another install with the tar.gz file this week. But in the short term, my solution is to comment the "hook lines" into the exercise.ajax.php file, and it works.

Except that, evertything seems to be ok  ! (but i haven't do a general check-up). It is the only issue i'm facing !

Thanks !

Tanchon

PS :

**Comment by tanchon** [comment]
Hi,

I have some news. I was in a bad track : exercise.ajax isn't the cause of the issue. I made simultaneous modifications... and i thought it was due to the exercise.ajax because of my commented lines (about hook). 

**In fact, i'm sure my issue is due to the question timer** : when i desactivate the option in the configuration.php file, i have no more problem = i tried to verifiy with 11.chamilo.org, but if i created the extra field "time", it isn't possible for me to activate the question timer into the configuration.php file.
I tried to delete the extra-field and after to re-create it : but it is the same issue :-(

Could you tell me if this issue can be reproduced now, please ?

Thanks a lot !

Tanchon.

**Comment by tanchon** [comment]
Hi,

After a good night... i solved the issue in some minutes : i had incomplete informations into my configuration.php file.
I had the first version of the file, after the Timer creation by @jmontoyaa  :
// Allow time per question. Requires a question text extra field called "time", value in seconds.
//$_configuration['allow_time_per_question'] = true;

... as i should had :
// Allow time per question. BT#17791
// Requires a question text extra field called "time", value in seconds.
// ALTER TABLE track_e_attempt ADD COLUMN seconds_spent INT;
//$_configuration['allow_time_per_question'] = true;

Just before the Chamilo upgrade i made manipulations to activate the question timer on this platform (allow_time_per_question => true AND the time extra-field). But, due to incomplete informations into my configuration file, **I forgot to modify the DB (to take into account the time spent on the question)**. i didn't made tests before the upgrade : if i did, i would have become aware of the issue (i missed the database adjustment).

The latter was totally independent from the process upgrade. I am sorry for the time I wasted you.

Thanks a lot for your advices and for the remarkable work made on this version !

Tanchon

**Comment by AngelFQC** [comment]
Good. Thanks for the info.
