### ISSUE TITLE
Admin (plugins panel) : error message when i open the admin panel

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3685]
Hi,

With the new version, when i open the panel "plugins" from the admin panel i can see an error message due to some new plugins 
- exercise signature
- positioning
- xapi
I don't have any issue with check_extra_field_author_company or other plugins.

For example, with exercise signature
![100710730-72e80100-33b0-11eb-9a5b-72ed8d096e50](https://user-images.githubusercontent.com/24507698/100713003-f22b0400-33b3-11eb-9d9b-8825b734a2ed.JPG)

There is no more error message into this panel if i add this line into the plugin.php file : require_once __DIR__.'/lib/ExerciseSignature.php'; (it is the same issue with positioning, xapi....)

**Server
Linux. 1.11.14 (from 1.11.12)

**Additional context**
Exercise signature generates another issue when i execute an exercise : at the end of the exercise, an error message is displaying, similar as to the screenshot above : chamilo doesn't find the class  (i have to comment the exercise signature lines in some exercise files to have no more error messages : exercise.class, exercise result...).

I think it is due to the same cause, so i don't open another issue.

Thanks

Tanchon

PS : i didn't try to install any plugin. The error messages seems to be independant from the installation.

**Comment by AngelFQC** [comment]
Please, try execute `composer update`

**Comment by tanchon** [comment]
Hi,

I installed Chamilo on a 1.11.12 plaform with the method of the "zip file" ([see here](https://docs.chamilo.org/v/1.11.x-fr/guide-administrateur/installation_et_configuration/mise_a_jour_de_la_plateforme_chamilo)). I didn't use git.

I tried  one more time this evening : I don't know why, but this issue is solved : no more issue with plugins (but my problem with the exercise remains).

Thanks !

Tanchon
