### ISSUE TITLE
Problema en anuncios para subir imagenes en Ckeditor

### ISSUE THREAD

**Issue by iruizsur** [chamilo/chamilo-lms#3689]
**Describe el problema**
Al intentar subir una imagen para que esté en portada, aparece el error 406. "No se ha podido conectar con el backend".

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a Administración/Anuncios de la plataforma/Anuncio/
2. Dar clic en icono "Subir imagen" en ckeditor.
3. Al intentar subir un recurso aparece el error.

**Comportamiento esperado**
Poder subir imágenes para anuncios en la página principal. El error sucede en un hosting compartido probablemente por cuestión de permisos pero no se sabe qué permiso modificar. En un servidor dedicado, este error no sucede y entonces la única manera de subir imagenes es primero subiéndolas a un curso u otro lugar para poner el enlace. Sería deseable que hubiera una carpeta en main/imgs/ general donde se subieran cosas y no en la de determinado usuario.

**Capturas de pantalla**
![ckeditorError](https://user-images.githubusercontent.com/16807565/100774062-4b506300-33c7-11eb-897b-78171129d16e.PNG)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Linux
 - Navegador Chrome pero el error se da en cualquiera.

**Servidor
 - Sistema operativo :Linux , CentOS
 - Versión de Chamilo: 1.11.12
 - Versión de PHP: 7.2

**Contexto adicional**
Solo sale el error si el servicio no es dedicado (hostgator).

**Comment by ywarnier** [comment]
Este problema no es de Chamilo. Tampoco creo que sea para *todos* los sistemas de hosting compartido. Seguro es un problema de permisos.
Por favor consultar en https://forum.chamilo.org/

**Comment by ywarnier** [comment]
Mientras agradecemos los reportes de fallas de Chamilo, me permito recordarles que este espacio *no es* un foro de soporte. Mientras no estés *seguro* que se trata de un error de Chamilo, gracias por consultar *primero* en el forum de Chamilo, que sí es un espacio de soporte.
