### ISSUE TITLE
No puedo subir archivos de audio

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3691]
**Describe el problema**
Cuando intento subir un archivo mp3, directamente a una carpeta o mediante un ejercicio con audio, la plataforma devuelve un mensaje de "formato no permitido". Si creo un documento html e inserto un archivo mp3, lo hace correctamente.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Subir un archivo mp3 a cualquier carpeta de un curso.
2. O grabar un audio desde un ejercicio y finalizar el mismo.

**ACLARACIÓN**
Probé en el servidor de Chamilo y este error no ocurre. Mi pregunta específica es si hay alguna variable o configuración dentro de Chamilo que pueda producir este problema en mi instalación.
Pregunté en el foro, pero nadie respondió hasta ahora.
Consulté con mi proveedor de hosting y luego de hacer varias pruebas me dicen que el problema está en la plataforma y no en el host. 

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 7 Service Pack 1 (Build 7601) (Probado también con Windows 7 64 bits).
 - Navegador:  Vivaldi | 3.4.2066.106 (Stable channel).

**Servidor**
 - Sistema operativo : Linux (no tengo otros datos).
 - Versión de Chamilo: 1.11.12
 - Versión de PHP: 7.3
 
**Para probar el error**
URL: [uttamayoga.com/campus/](https://uttamayoga.com/campus)
Usuario: github
Contraseña: github
Prueba 1: responder un ejercicio con grabación de audio (está en el área de ejercicios). Da error.
Prueba 2: intentar subir un archivo mp3 a una carpeta. Da error.

Muchas gracias.

**Comment by AngelFQC** [comment]
Siguiendo los pasos para reproducir el issue, encontré un error para el cual he enviado un commit con la corrección.

Pero no he podido reproducir el error de "formato no permitido", ni desde la herramienta Documentos ni Ejercicios.

**Comment by jolufe** [comment]
Muchas gracias @AngelFQC por tu pronta respuesta.
A mí me sigue apareciendo el error, no sé cuál será la diferencia entre tu prueba y la mía. :question: 
Adjunto dos capturas de pantalla que tal vez ayuden.

Muchas gracias. :smile: 

************

**Esta es la pantalla del ejercicio recién grabado, pero sin terminar**

![2020-12-02 17 09 43 uttamayoga com fe9172a426d0](https://user-images.githubusercontent.com/40075497/100926273-ee85a300-34c1-11eb-8bcb-373a9f5ded07.jpg)

**************

**Este es el mensaje que me aparece al hacer clic en "Terminar ejercicio"**
El ejercicio se guarda, pero el archivo de audio no.

![2020-12-02 17 10 24 uttamayoga com 4810ff2fad43](https://user-images.githubusercontent.com/40075497/100926371-1a088d80-34c2-11eb-81ec-a720df9b6b99.jpg)

**Comment by jolufe** [comment]
Adjunto error_log de main/exercise

[main_exercise_error_log.zip](https://github.com/chamilo/chamilo-lms/files/5632308/main_exercise_error_log.zip)

**Comment by jolufe** [comment]
El problema era que en la whitelist de extensiones de archivos no estaban las extensiones de audio. Ahora funciona correctamente.
Gracias.

**Comment by jolufe** [comment]
El problema era que en la whitelist de extensiones de archivos permitidas no estaban las extensiones de audio. 
Ahora funciona correctamente.
Gracias.
