### ISSUE TITLE
Reporting (tool in a course) : bug when clicking on "LP generic stats" button

### ISSUE THREAD

**Issue by tanchon** [chamilo/chamilo-lms#3700]
Hi,

I note a little bug on my 1.11.14 platform and 11.chamilo.org.

In a course => Reporting => click on the LP generic stats, at the top of the page => the error occurs.

See images below :
![Capture10](https://user-images.githubusercontent.com/24507698/101451299-35452400-392c-11eb-966b-c797aadf75a2.JPG)

![Capture1000](https://user-images.githubusercontent.com/24507698/101451330-43934000-392c-11eb-9561-19a831bd2dfc.JPG)

Thanks !
Tanchon

**Comment by jmontoyaa** [comment]
It's because this change:

https://github.com/chamilo/chamilo-lms/commit/d6b7c4b801cd2bf6e71fe29c2d3ea8e15b4151d9#diff-d0096d167e09d3a70905caf7daf8966fe18f0a027f483b1acd0bfd09bca10e17R12210

**Comment by tanchon** [comment]
Thanks @jmontoyaa  for this quick fix ! It works !
