### ISSUE TITLE
Dropbox : pagination broken

### ISSUE THREAD

**Issue by mk111** [chamilo/chamilo-lms#3720]
**Describe**
the whole dropbox content is shown as  a single (in my case very) long page,  there is no paging controls for the chosen page length, nor info related to the number of files shown at the page ( -1 ?)

**To Reproduce**
see as admin user (course DropBoxTest11)
 https://11.chamilo.org/main/dropbox/index.php?cidReq=00DPT&id_session=0&gidReq=0&gradebook=0&origin=&view=received, dec.16. 2020
()
**Expected behavior**
paginated list

**Screenshots**

**Server
 - OS: https://11.chamilo.org
 - Version of Chamilo: 
 - Version of PHP

**Additional context**

**Comment by christianbeeznest** [comment]
Thank you @mk111 

It is added a fix about it inside #3748

**Comment by mk111** [comment]
#3748 fixes this one too. I'm closing this issue.
