### ISSUE TITLE
SkillsWheel: Rueda responsiva, Tamaño de iconos de competencia correctos, Colores de competencia equivocados

### ISSUE THREAD

**Issue by carlangas159** [chamilo/chamilo-lms#3731]
La rueda de competencias tiene algunos problemas, por una parte, cuando eres administrador y te dirijes a */main/admin/skills_wheel.php*, de haber obtenido una competencia como administrador, sale marcada en verde

![imagen](https://user-images.githubusercontent.com/18097392/103035903-5580ff80-4536-11eb-94c3-f872d3af1620.png)
El problema se presenta a que la leyenda no contiene esta informacion y puede causar confusion, por ello, es necesario evitar que se muestre esta caracteristica.

Por otra parte, por unos pocos pixeles, el icono de las competencias cuando se encuentra en *main/social/skills_wheel.php*
![imagen](https://user-images.githubusercontent.com/18097392/103036042-c2949500-4536-11eb-9238-7dcaa6daa8c8.png)

Y otro detalle que tiene esta vista, es que la rueda no es responsiva, cosa que puede observarse fallos al momento de redimensionar la vista.
![imagen](https://user-images.githubusercontent.com/18097392/103036299-6d0cb800-4537-11eb-8e31-cf82b88ae18b.png)

**Comment by ywarnier** [comment]
The badges alignment is still not perfect, but good enough for now. Closing.
![skill-align](https://user-images.githubusercontent.com/609839/168832328-45b9a251-9753-4c07-841c-46531b260f49.png)
