### ISSUE TITLE
When Adding a new User Expire Calendar Year is set by Default to year 2031 

### ISSUE THREAD

**Issue by oliveiraped** [chamilo/chamilo-lms#3742]
When Adding a new User Expire Calendar Year is set by Default to the year 2031 

Picture attached.

![image](https://user-images.githubusercontent.com/676000/103757890-553e3500-5009-11eb-9751-43a124b2e26e.png)

Best Regards

Pedro

**Comment by ywarnier** [comment]
By default, we auto-expire users after 10 years. Not a bug. How would you make it better?

**Comment by oliveiraped** [comment]
Hi Yannick,

Thanks, it's true. We can Close this issue.

Best

Pedro
