### ISSUE TITLE
Greek Flag is not the right one

### ISSUE THREAD

**Issue by makatsis** [chamilo/chamilo-lms#3746]
**Describe**
As you can see at the following screenshot the greek flag is not the right one. Chamilo 1.11.14 

<img width="643" alt="Στιγμιότυπο 2021-01-11, 2 30 53 μμ" src="https://user-images.githubusercontent.com/2492623/104183087-1863ab00-541a-11eb-9746-6f43314922eb.png">

**Comment by ywarnier** [comment]
![greek-flag](https://user-images.githubusercontent.com/609839/168803222-4cf811df-d2ba-401b-a7d7-7275b358603c.png)

Greek flag is now correct
