### ISSUE TITLE
Document tool : pagination broken

### ISSUE THREAD

**Issue by mk111** [chamilo/chamilo-lms#3748]
**Describe**
the whole document folder content is shown as a single (in my case very) long page, there is no paging controls for the chosen page length, nor info related to the number of files shown at the page ( -1 ?)

**To Reproduce**
see
https://11.chamilo.org/main/document/document.php?id=0&cidReq=00DPT&id_session=0&gidReq=0&gradebook=0&origin=&

**Expected behavior**
pagination working

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
https://11.chamilo.org
chamilo 1.11.14

**Additional context**
related to #3720 
possible mulfunction on sortable table since all alike tables suffer from the same symptom(s)

**Comment by mk111** [comment]
here's the problem: 

SortableTableFromArrayConfig.php:

     /**
     * Get total number of items.
     *
     * @see SortableTable#get_total_number_of_items
     */
    public function get_total_number_of_items()
    {

        return count($this->table_data);
        /*
        if (isset($this->total_number_of_items) && !empty($this->total_number_of_items)) {
            return $this->total_number_of_items;
        } else {
            if (!empty($this->table_data)) {
                return count($this->table_data);
            }

            return 0;
        }
		*/
    }

i can't fix this, since i can't figure out logic behind; where to use number of items that differ from all.

**Comment by mk111** [comment]
nad second half of the problem :
SortableTableFromArrayConfig.php:  array_slice is commented out .... instead a whole table is returned

   /**
     * Get table data to show on current page.
     *
     * @see SortableTable#get_table_data
     */
    public function get_table_data(
        $from = 1,
        $per_page = null,
        $column = null,
        $direction = null,
        $sort = true
    ) {
        $table = TableSort::sort_table_config(
            $this->table_data,
            $this->column,
            'ASC' === $this->direction ? SORT_ASC : SORT_DESC,
            $this->column_show,
            $this->column_order,
            SORT_REGULAR,
            $this->doc_filter
        );

//        return array_slice($table, $from, $this->per_page);
        return $table;
    }

**Comment by mk111** [comment]
large uniform list with no pagination can be intentional; ??  (modern 'mobile' listings with touch to control; i like the idea, but not from the teacher perspective and not with the dropbox ....

**Comment by christianbeeznest** [comment]
As method get_table_data from main/inc/lib/SortableTableFromArray.php the data should be returned this way **return array_slice($content, $from, $this->per_page);**  taking into account the table data passed to SortableTableFromArrayConfig is an array too  and no a function name.

public function get_table_data(
        $from = 1,
        $per_page = null,
        $column = null,
        $direction = null,
        $sort = true
) {
	$table = TableSort::sort_table_config(
		$this->table_data,
		$this->column,
		'ASC' === $this->direction ? SORT_ASC : SORT_DESC,
		$this->column_show,
		$this->column_order,
		SORT_REGULAR,
		$this->doc_filter
	);        
	return array_slice($table, $from, $this->per_page);
}
I'm not sure if that line was commented intentionally for 1.11.x

**Comment by christianbeeznest** [comment]
Relationed with commit https://github.com/chamilo/chamilo-lms/commit/b7801d78adc4cc2a8d5f5fe29ea61df488fadfaa "Fix exercise pagination" , it was fixed when data is not sent to sortable for pagination (it is done using queries to database), but it is affecting to other tools where data is sent.

I just added the validation for both cases

**Comment by jmontoyaa** [comment]
By the way, I added a fix in master in order to hide the pagination when is no needed:

https://github.com/chamilo/chamilo-lms/commit/1c9776d6eacf7f83860915155313e9818c42d71f#diff-b4e989a079cbd2ba99ba10fde666b48f47919c43874dedcde5b19ced718a3175R401

**Comment by AngelFQC** [comment]
Maybe it's better to add a way to do the pagination in the method that returns the data
https://github.com/chamilo/chamilo-lms/blob/167870fc9062134f6d7da5722c1f958404a129ea/main/inc/lib/document.lib.php#L536-L544

Because it's always getting the entire document list on each page.

**Comment by ywarnier** [comment]
@mk111 Any chance you could give us a validation on this on https://11.chamilo.org before we package 1.11.16? (later today or in the following days, depending on how we go with other issues).

**Comment by mk111** [comment]
i tested all the tools related to the documents and i can confirm that pagers are back and functional. Amount selection is working too, can be chosen from {10,20,All}, default as 20 files per page. This issue can be closed.

**Comment by NicoDucou** [comment]
Thanks @mk111 for the feedback.
