### ISSUE TITLE
Corrupt source in master branch? 

### ISSUE THREAD

**Issue by Craftoncu** [chamilo/chamilo-lms#3756]
**Describe**
Installation not possible due composer(php compile) error.

**To Reproduce**
- follow readme in master branch

**Expected behavior**
- Partly functional software ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/55136417/104829952-993b0080-5879-11eb-9bec-a324fe66a63d.png)

 - OS: deb 10 buster

**Comment by lonesomewalker** [comment]
How about NOT using the master branch (because, if you would have read...)

```Chamilo 2.0 is still in development stage. This install procedure is for reference only. For a stable Chamilo, please install Chamilo 1.11.x. See the 1.11.x branch README.md for details.```

**Comment by Craftoncu** [comment]
had already read it.
still wanna use it.

aycs I wrote "Partly functional software"

**Comment by Craftoncu** [comment]
So back to the error. 
Is there a quick fix?

**Comment by lonesomewalker** [comment]
If you use master, you should be able to fix it.

**Comment by Craftoncu** [comment]
That's what I wanted to know

**Comment by lonesomewalker** [comment]
> That's what I wanted to know

Really, stick to 1.x latest, you will take some time to get master working.
tbh, i don't think this will be a "fast" process, because there are so many loose strings...
(and yes, my "advice" was kinda sarcastic ;-)

**Comment by Craftoncu** [comment]
Still okay, I have too much too little time :)

I actually have no specific reason to use 2.0. Has the issue with the courses been resolved in the 11 branch?

**Comment by Craftoncu** [comment]
#3693

**Comment by jmontoyaa** [comment]
"Corrupt" is a big word, try updating your PHP version to 7.4, then it should work.

**Comment by jmontoyaa** [comment]
v2 requires PHP 7.4 

https://github.com/chamilo/chamilo-lms/commit/4aec423b9db95c7d4f17476b655ae3cf5e399913
