### ISSUE TITLE
Support sublanguages in 2.0 and migration from 1.11 to 2.0

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3761]

**Comment by ywarnier** [comment]
@christianbeeznest is currently working on this. There are a few scripts in https://github.com/chamilo/chamilo-lms/tree/master/tests/scripts/lang (the first one is probably best) to help in this task.

**Comment by NicoDucou** [comment]
All good, here just one problem with Quechua that is migrated as a sub language and included in var/translations/messages.es_quechua.po when it is already in translation/messages.qu_PE.po
So there is this specific case to solve and all will be good here

**Comment by christianbeeznest** [comment]
> All good, here just one problem with Quechua that is migrated as a sub language and included in var/translations/messages.es_quechua.po when it is already in translation/messages.qu_PE.po So there is this specific case to solve and all will be good here

Fixed with last commit.

**Comment by NicoDucou** [comment]
All good now
