### ISSUE TITLE
Error con plugin Venta de Cursos - 1.11.14

### ISSUE THREAD

**Issue by Asier97** [chamilo/chamilo-lms#3772]
Saludos y siento cualquier inconvinencia con este post

Me dirijo a ustedes pues he instalado en un servidor la versión 1.11.14 de Chamilo. Uno de los plugins que quiero es el de "Venta de Cursos", plugin que he instalado sin problema previamente en 1.11.12 si mal no recuerdo. 

https://i.ibb.co/KjL1HHL/1.png

Al habilitarlo obtengo un error:

https://i.ibb.co/NLnW57y/2.png

El error dice lo siguiente: 
_An exception occurred while executing 'SHOW COLUMNS FROM plugin_buycourses_global_config WHERE Field = 'info_email_extra'':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table '***********.plugin_buycourses_global_config' doesn't exist, referer: http://localhost/proyectos/chamilo/**********/main/admin/settings.php?category=Plugins&sec_token=f487b784ad2e576f9fa87b29c8fa4105_

**Los ****** los he añadido yo para proteger la identidad de mi cliente**

Sin embargo, el plugin parece instalarse "correctamente"

https://i.ibb.co/ZHZFbGM/3.png

Al querer acceder al plugin para configurar, por ejemplo, PayPal, obtengo error

https://i.ibb.co/pQbP71j/4.png

Este es el error:
_An exception occurred while executing 'SELECT * FROM plugin_buycourses_currency ':\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table '********.plugin_buycourses_currency' doesn't exist, referer: http://localhost/proyectos/chamilo/*******/plugin/buycourses/index.php_

**Revisando en PhpMyAdmin veo que las tablas a las que quiere dirigirse no existen. El problema es, ¿porqué? ¿Cómo lo arreglo?**

Cualquier ayuda es bienvenida, muchas gracias de antemano.

**Comment by angelart07** [comment]
lo solucioné ingresando a PHPMYADMIN del CPANEL, ubiqué la base de datos y agregué la siguientes sentencias SQL:

https://pastebin.com/kmisW6bh

**Comment by angelart07** [comment]
También es necesario agregar la siguiente sentencia SQL:

ALTER TABLE plugin_buycourses_global_config ADD COLUMN info_email_extra TEXT;

**Comment by Asier97** [comment]
¡Muchas gracias! Doy por cerrado el problema
