### ISSUE TITLE
Positioning plugin crash all execises

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#3778]
**Describe**
When install, enable and setting all, create 2 exercises, all done. So, after that, all exercises at the platform does not work anymore, not save.

**To Reproduce**
1. Install plugin
2. Enable/block course
3. Create 2 exercises
4. Set the Initial test and Final test
5. Test now any exercise, and not save anymore

**Server
 - OS: CentOS
 - Version of Chamilo:  1.11.14
 - Version of PHP: 7.4 / nginx

**Comment by christianbeeznest** [comment]
Hello @fabiowoj 

Positioning tests should be used before and after any course, if you don't pass the first test the other exercises won't be saved 
For a test to be used as initial or final test, it has to match 3 criteria: - use at least 3 question categories - use the "radar" type result page - have only one available attempt

**Comment by ywarnier** [comment]
We can still not reproduce this. Assuming this has been fixed in the meantime.
