### ISSUE TITLE
Extra field image/file

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3788]
Move from Asset to a "Private" asset.

**Comment by jmontoyaa** [comment]
It's already implemented as an Asset (which is public) but it needs to be save as another entity that allow user permissions.

**Comment by jmontoyaa** [comment]
A new field in the table `extra_field_values` should be added too.

**Comment by jmontoyaa** [comment]
This should work now. The session image is saved as extra field of image type, can be tested in: 

https://2.chamilo.org/main/session/session_add.php

**Comment by christianbeeznest** [comment]
The request is added in this commit https://github.com/chamilo/chamilo-lms/commit/0f1c8c594f287e5175cb5c7478cd1812afc8e3dc#diff-2aadbf2d53cecd44b68c66404d5284b57cb1437cd50ddd985d9e91142a062ae7

Asset::EXTRA_FIELD
