### ISSUE TITLE
Exercises - Question teacher audio file location

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3790]
Similar to #3789 but related to the teacher if settings:

```
$allowRecordAudio = 'true' === api_get_setting('enable_record_audio');
$allowTeacherCommentAudio = true === api_get_configuration_value('allow_teacher_comment_audio');

```

**Comment by christianbeeznest** [comment]
This request is added in this commit https://github.com/chamilo/chamilo-lms/commit/58898573015a97e8f49dc2fa4ef26a198b35da4c
Assets exercise_feedback
