### ISSUE TITLE
Certificates in v2

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3791]
Save certificate file in the "my files" tools (Personal files) see #3792

**Comment by ywarnier** [comment]
Possibly implemented through PR #4677

**Comment by NicoDucou** [comment]
When using the branch [GH#2834 and after a composer update I get this error :
```
root@testing:/var/www/testing25.beeznest.com/www# php bin/console doctrine:schema:update --force
                                                                                                                        
 [WARNING] Not passing the "--complete" option to "doctrine:schema:update" is deprecated and will not be supported when 
           using doctrine/dbal 4                                                                                        
                                                                                                                       
In MappingException.php line 364:
                                                                                                    
  Class "Chamilo\CoreBundle\Entity\GradebookCategory" is not a valid entity or mapped super class.  
                                                                                                    
doctrine:schema:update [--em EM] [--complete] [--dump-sql] [-f|--force]
```
I have the same error when trying to loggin.

So I could not test and validate this issue

**Comment by NicoDucou** [comment]
@BorjaSanchezBeezNest 
Can you check this issue to be able to update Chamilo with you branch and not have the error reported that do not enable us to test it.

**Comment by ywarnier** [comment]
PR https://github.com/chamilo/chamilo-lms/pull/4677 has been merged, but there are a number of issues remaining, described in #5074. However, these should not affect files structure anymore.

**Comment by ywarnier** [comment]
PR https://github.com/chamilo/chamilo-lms/pull/4677 has been merged, but there are a number of issues remaining, described in #5074. However, these should not affect files structure anymore.
