### ISSUE TITLE
"My files" in v2 (Personal files)

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3792]
Migrate my files from 1.11.x to a new tool my files

**Comment by jmontoyaa** [comment]
New "my files" page can be found in: https://2.chamilo.org/resources/personal_files/

**Comment by jmontoyaa** [comment]
Permission validations need to be checked.

**Comment by christianbeeznest** [comment]
Te request is added in this commit https://github.com/chamilo/chamilo-lms/commit/fcabbcc1efab16a80681ec806f5df3c5ec544cba , It is checked permissions validations.
