### ISSUE TITLE
Badge image file location 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3797]
Migrate badge images in v2 using Asset or Illustration entities.

**Comment by jmontoyaa** [comment]
Default location in 1.11.x

`api_get_path(SYS_UPLOAD_PATH).'badges/'`

**Comment by christianbeeznest** [comment]
the request is added in this commit https://github.com/chamilo/chamilo-lms/commit/cbd5fc1d3bcfa8c4672b47b6ff1984df0c4f5a90
