### ISSUE TITLE
Messages audio file location

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3799]
Add the audio file location as a message attachment or save it as a Resource

**Comment by jmontoyaa** [comment]
When adding a file to a message or adding an audio to a message, does files are added using the Resources. 
The entities used are Message -> MessageAttachment -> ResourceNode -> ResourceFile

**Comment by christianbeeznest** [comment]
The request is added in this commi https://github.com/chamilo/chamilo-lms/commit/b315eb76e31fe5688db6963c128799ab74a7767e#diff-d5bcb1cf527991b5c34f11808bbc526c4a06611d45923a821687f987cff8bc16

$fileToUpload = new UploadedFile($meta['uri'], $fileName, $file['type'], null, true);
