### ISSUE TITLE
Course category image

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3801]
Save file in new location using Asset? Illustration? Add as a Resource?

File location in 1.11.x

`api_get_path(SYS_UPLOAD_PATH).'course_category;`

**Comment by jmontoyaa** [comment]
A new Asset will be added because CourseCategory is not a resource.

**Comment by ywarnier** [comment]
In 1.11.x, there is an option to enable images for course_category with a new field `image`.
```
// Show course category list on My Courses page before the courses. Requires a DB change
//ALTER TABLE course_category ADD image varchar(255) NULL;
//ALTER TABLE course_category ADD description LONGTEXT NULL;
//$_configuration['my_courses_list_as_category'] = false;
```

The validation requires to check that the migration indeed changes the file in 1.11 to an asset in 2.0 and that the images are working in Chamilo 2.0.

**Comment by christianbeeznest** [comment]
It is added in migration file in this commit https://github.com/chamilo/chamilo-lms/commit/4cd9798949d3f6af4061396f8010e1c482971612#diff-28df239037694e2bcdd55bb752432b8a51c325c28f772a3754771aaa2b2cfe32  in Version20191101132000.php file
