### ISSUE TITLE
Schedule announcements new file location in v2

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3802]
Migrate files from this tool:

`api_get_path(SYS_UPLOAD_PATH).'scheduled_announcement/';`

As an Asset/Resource/Illustration?

**Comment by christianbeeznest** [comment]
This request is added in this commit https://github.com/chamilo/chamilo-lms/commit/6ad7d141b7030e77faf43a94206ca8c6461b7f55#diff-96669b4811b1d35746a887d0d1e16e0fab3c693df30c3200a00aea14c587b723

Asset::EXTRA_FIELD  (ef)
