### ISSUE TITLE
UserGroup (Social/Class) image file location in v2

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3805]
File location in 1.11.x is ` api_get_path(SYS_UPLOAD_PATH).'groups'` this needs to be migrated (using Illustration/Asset?)

**Comment by jmontoyaa** [comment]
This was migrated in order to use Illustrations

https://2.chamilo.org/main/admin/usergroups.php?action=add

**Comment by christianbeeznest** [comment]
I just checked and confirmed is fixed , it is added in migration too.

**Comment by christianbeeznest** [comment]
This request is implemented in this commit https://github.com/chamilo/chamilo-lms/commit/3078deed833e089dd217292776ce93f4248b3c9c

Tested and confirmed.
