### ISSUE TITLE
User productions in v2

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3806]
User productions are uploaded in the user path in 1.11.x

It should be deprecated or migrated to v2 in the new personal files tool see #3792

**Comment by jmontoyaa** [comment]
@ywarnier User productions will be deprecated?

**Comment by ywarnier** [comment]
Should be deprecated

**Comment by christianbeeznest** [comment]
It is deprecated with this PR https://github.com/chamilo/chamilo-lms/pull/4452

**Comment by ywarnier** [comment]
Reviewed, tested and approved.
