### ISSUE TITLE
Error de redirección al crear un nuevo curso en Nginx con Chamilo 1.11.14

### ISSUE THREAD

**Issue by aguito1877** [chamilo/chamilo-lms#3812]
**Describe el problema**
Cuando se crea un curso nuevo hay un problema en la redirección y sale un error 404. Si revise la documentación pero no me queda clara y probé creando un archivo nginx.conf y traduciendo las reglas del .htaccess 

Entonces si tal vez hay alguien que me pueda ayudar estaría muy agradecido.

**Cómo reproducir**
Se crea el curso con los parámetros que se deben ingresar
Al dar en guardar y al querer mostrar la vista del curso
Sale un error 404

**Comportamiento esperado**
Ver la vista del curso que se ha creado

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Linux 
 

**Servidor
 - Sistema operativo : Linux
 - Web Server: nginx/1.18.0
 - Versión de Chamilo:  1.11.14
 - Versión de PHP: 7.4.14

**Comment by fabiowoj** [comment]
@aguito1877 , el problem es la configuracion de redireccion. 

[Nginx configuration](https://11.chamilo.org/documentation/installation_guide.html#16._Rewrite)

Coloque la configuraccion en /etc/nginx/conf.d/ssl.conf
Despues de salvar, reinicie el server

**Comment by ywarnier** [comment]
@aguito1877 te ayudó la respuesta de @fabiowoj ?

**Comment by Miguelgamer812** [comment]
@fabiowoj Me ayudaste muchisimo!!
