### ISSUE TITLE
Configure home page in v2 

### ISSUE THREAD

**Issue by jmontoyaa** [chamilo/chamilo-lms#3813]
Create a new structure to allow custom pages (block) as in 1.11.x:

https://11.chamilo.org/main/admin/configure_homepage.php?action=edit_top&language=french

**Comment by NicoDucou** [comment]
On https://2.chamilo.org/home we can see the "Welcome to Chamilo" page but we can not edit it, it blocks when opening https://2.chamilo.org/resources/pages/edit?id=/api/pages/1 and stays with a blanck page. If we go through the administration page we get to the list of page but we can not edit them : https://2.chamilo.org/resources/pages


On https://testing24.beeznest.com/home we can not see the pages even if they are created here : https://testing24.beeznest.com/resources/pages
On this Chamilo they can be modified for example here : https://testing24.beeznest.com/resources/pages/edit?id=/api/pages/1
We do not see on the home page the global annoucement neither which are visible on 2.chamilo.org

I've seen the setting "Display categories on home page" in the display category of the configuration setting but it was set to no on both platform and when I set it to yes on testing24 it does not change anything.

The page of index category appears only on the homepage when I'm note authentified but not once logged in.

Also on the page editing page we should be able to indicate that we want to use the same page for all the locale or be able to select various locale.

**Comment by ywarnier** [comment]
> On https://2.chamilo.org/home we can see the "Welcome to Chamilo" page but we can not edit it, it blocks when opening https://2.chamilo.org/resources/pages/edit?id=/api/pages/1 and stays on a blank page. If we go through the administration page we get to the list of page but we can not edit them : https://2.chamilo.org/resources/pages

This is fixed. Edition can be done through admin pages and the pages appear on the homepage (or in the demo and faq sections) in the right language.

> On https://testing24.beeznest.com/home we can not see the pages even if they are created here : https://testing24.beeznest.com/resources/pages On this Chamilo they can be modified for example here : https://testing24.beeznest.com/resources/pages/edit?id=/api/pages/1 We do not see on the home page the global annoucement neither which are visible on 2.chamilo.org

Pages and announcements now appear in the correct languages. Announcements cannot be shown for non-logged-in users, so I'm creating issue #5200 about that.

> I've seen the setting "Display categories on home page" in the display category of the configuration setting but it was set to no on both platform and when I set it to yes on testing24 it does not change anything.
> 
> The page of index category appears only on the homepage when I'm note authentified but not once logged in.

The course categories do not appear on the homepage indeed. I've created #5201 for that.

> Also on the page editing page we should be able to indicate that we want to use the same page for all the locale or be able to select various locale.

I think there should rather be another mechanism (because already in 1.11 it would create copies) to just say "Copy to another language". In the meantime, it seems acceptable not to have this feature in the early 2.0 release.

This closes the current issue.
