### ISSUE TITLE
LDAP ext LDAP configuration not found

### ISSUE THREAD

**Issue by bayusky** [chamilo/chamilo-lms#3817]
I got this error when I authenticate LDAP user

"PHP message: Chamilo Authentication file defined in $extAuthSource could not be found - this might prevent your system from doing the corresponding authentication process"

**To Reproduce**
1. I can add LDAP user
2. when I try to authenticate, I got those error

this was the extAuthSource line

$extAuthSource["extldap"]["login"] = $_configuration['root_sys']."main/auth/external_login/login.ldap.php";
$extAuthSource["extldap"]["newUser"] = $_configuration['root_sys']."main/auth/external_login/newUser.ldap.php";

**Expected behavior**
login success

 - OS: [MacOS BigSur]
 - Browser [safari]

**Server
 - OS: [e.g. Linux Ubuntu 20.04/Windows 10]
 - Version of Chamilo:  1.11.14
 - Version of PHP: 7.2

**Comment by christianbeeznest** [comment]
Hello @bayusky 

could you confirm if your users ldap in chamilo have the "auth_source" = "extldap" in the table user ? , other way the paths $extAuthSource["extldap"]["login"] and $extAuthSource["extldap"]["newUser"] won't load correctly so $extAuthSource could not be found.
