### ISSUE TITLE
Total Score Question

### ISSUE THREAD

**Issue by SerpikoIT** [chamilo/chamilo-lms#3834]
Hello every time I import the file from Aiken the question score is set to 0.08 I would like each correct answer to be 1 point how can I do ??? obviously by importing the file that I prepare earlier

248 questions, for a total score (on all questions) of 20.

![score](https://user-images.githubusercontent.com/75452931/112939253-6fc90b80-912b-11eb-84ca-f3186ba176e7.jpg)

But then it's such a disaster, but can I change the total ???

Thx

**Comment by nosolored** [comment]
Hello,
When you import an Aiken file, you must indicate the total score for the exercise and in the importation process, the platform assign the average value corresponding to each question (20/248).
If you want each question to have 1 as score, you must indicate 248 as total score when you import the file.
Or after importation, you can edit each question and change the individual score, as you prefer.

**Comment by SerpikoIT** [comment]
But when I print the questions don't choose me any total score, it just tells me the file to upload and that's it

**Comment by nosolored** [comment]
In the importation screen, you should find a field to indicate the total weight:
![aiken_score](https://user-images.githubusercontent.com/5868981/112962604-d871b180-9146-11eb-8bb0-e7fd50304906.jpg)

**Comment by SerpikoIT** [comment]
Ok very very gooodd
