### ISSUE TITLE
Search_Course plugin not working with localhost port

### ISSUE THREAD

**Issue by DrMickArtisan** [chamilo/chamilo-lms#3836]
First, I don't know if it's the right place to report a bug on a plugin, but I can't find a specific repository.

**Describe**
Upon activating the search_course plugin, nothing appears in the selected region.
The reason is quite simple : I use a localhost  with a not standard port number (something like http://forma.serveurmick.fr:856).
And in the search_course_widget.class.php file, the two methods 
`is_user_portal()` 
or 
`is_homepage()` 
just check the SERVER_NAME, which does not include the port value.
` $url = self::server('SERVER_NAME').$url;`
(lines 61 and 79)
The fix is quite simple : in the two methods, replace SERVER_NAME by HTTP_HOST.

**Comment by ywarnier** [comment]
I submitted your patch (in your name) here: d2b83af8c0d88b9002cfc2156b44c8f2cdef8830
Thank you for reporting the issue and the fix.
