### ISSUE TITLE
Fatal error: Cannot redeclare normalizer_is_normalized() (previously declared in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.14\vendor\symfony\polyfill-intl-normalizer\bootstrap.php:15) in C:\xampp\htdocs\chamilo\chamilo-lms-1.11.14\vendor\patchwork\utf8\src\Patchwork\Utf8\Bootup\intl.php on line 20

### ISSUE THREAD

**Issue by mmaous** [chamilo/chamilo-lms#3838]
**Describe**
![1](https://user-images.githubusercontent.com/17799273/113507220-77cce500-9549-11eb-90d8-fd35560402e9.jpg)
![2](https://user-images.githubusercontent.com/17799273/113507222-7996a880-9549-11eb-9b79-293b068b160c.jpg)

**To Reproduce**
1. Go to 'localhost/chamilo'
2. Click on 'Install.'
3. See error

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser brave V1.22.71, firefox  V87.0 (64bit)

**Server
 - OS: [Windows 10]
 - Version of Chamilo:   1.11.14
 - Version of PHP: [7.3.27]

**Comment by lonesomewalker** [comment]
Confirmed, even for not localhost and PHP7.4 and running on Debian

**Comment by ywarnier** [comment]
php-intl is mentioned as a dependency in https://campus.chamilo.org/documentation/dependencies.html (it is linked from the installation guide in your installer)

**Comment by ywarnier** [comment]
Sorry, I was a bit fat to close it. Could you confirm installing php-intl solves the issue?

**Comment by mmaous** [comment]
Actually, I give up on xampp 
I switched to Wamp and works perfectly
