### ISSUE TITLE
Missing Start Recording button from Oral Expression

### ISSUE THREAD

**Issue by harismateen** [chamilo/chamilo-lms#3841]
**Describe**
Start Recording is missing from Oral Expression - screenshot: https://prnt.sc/115ifdf
**To Reproduce**
1. Go to '...' Teacher Added new question as "Oral Expression"
2. Click on '.... Student Open Test and unable to see Start Recording button'
Error screenshot: https://prnt.sc/115ikvh

**Expected behavior**
Start Recording button must need to be display

**Additional context**
Chamilo 1.11.06

**Comment by lonesomewalker** [comment]
Recommend to use ssl certificates...

**Comment by harismateen** [comment]
Thanks - could you share instructions on how to install SSL on ubuntu? via
Lets Encrypt?

**Comment by lonesomewalker** [comment]
```apt install certbot``` and you need another package, depending on your webserver (nginx, apache2?)

But i just tried at a fresh portal of mine:
```Got error 'PHP message: An exception occurred while executing '':\n\nSQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty'```

There might be some more issues...

**Comment by ywarnier** [comment]
The "manual" procedure (not using too much automated help from certbot) is `apt install certbot` indeed, then `certbot certonly -d yourdomain`(the DNS needs to be configured correctly and you need to know which folder your Chamilo is installed into).

This will give you the paths to the certificate and the key, which you then need to add to your web server configuration (which might be a bit tricky to do correctly, but let us know about that if you are stuck).

After everything is configured, you will need to change the web_root setting in your Chamilo's config file at app/config/configuration.php

All WebRTC (Web Real Time Communication), like recording audio without a flash plugin, require HTTPS nowadays (the browsers themselves block the use of WebRTC without HTTPS). This is why you are not seeing the audio recording widget on HTTP.

**Comment by harismateen** [comment]
@ywarnier thanks alot - can you please me to assist on pointing IP address to sub-domain -
I am seeing this root folder right after i follow below configuration: screenshot: https://prnt.sc/11e68ui

To Reproduce
Steps to reproduce the behavior:

Updated "configuration.php" --> $_configuration['root_web'] = 'http://subdomain.domain.com/';
Updated apache 2 --> ServerName http://subdomain.domain.com/
Reloaded apache2 and restarted
Root folder is showing - https://prnt.sc/11e68ui
Expected behavior
It should run the chamilo as working on IP

Screenshots
https://prnt.sc/11e68ui

**Comment by harismateen** [comment]
I have manged to done it - 
But seems like image are still coming from IP instead of sub-domain - 
how to change this also? 
screenshot: https://prnt.sc/11k41qh

**Comment by harismateen** [comment]
@ywarnier Also - i still unable to upload the recording - Mange to record but giving me this  error " There is not enough space to upload this file."

I have increased the upload size also as below configuration under php.ini

post_max_size = 1024M
upload_max_filesize = 1024M
memory_limit = 1024M
max_execution_time = 300

**Comment by ywarnier** [comment]
This seems related to #3942

**Comment by NicoDucou** [comment]
Hi @harismateen 

The space problem seems to be related to the course quota and this is the same as in#3942 so you can have a look at my last comment here : https://github.com/chamilo/chamilo-lms/issues/3942#issuecomment-898497890

**Comment by ywarnier** [comment]
@harismateen any update on this. Should we keep this issue open or did you solve it?
