### ISSUE TITLE
Plugins page error

### ISSUE THREAD

**Issue by Sensooji** [chamilo/chamilo-lms#3843]
**Describe**
La page plugins ne fonctionne pas

**To Reproduce**
1. Go to Administration
2. Click on Plugins
3. See error

**Expected behavior**
Affichage de la page Plugins

**Screenshots**
[https://bit.ly/3mntw2w]

**Desktop (please complete the following information):**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
**Server
 Linux clim.o2switch.net 4.18.0-147.8.1.el7h.lve.1.x86_64 #1 SMP Mon Jun 29 09:05:02 EDT 2020 x86_64

  | [DB] | chamilo_database_version | 1.11.0.6 | 
  | [CONFIG] || 1.11.12
  | [CONFIG] || 1.11.12 stable 

 - Version of PHP: 7.4.16

**Additional context**
none

**Comment by ywarnier** [comment]
@Sensooji ça se produit parfois avec des plugins qui entrent en conflit les uns avec les autres ou des plugins qui ont besoin de librairies additionnelles qui ne sont pas là. C'est un peu compliqué de ressortir de cette situation, mais il est possible de désactiver les plugins un par un depuis la table settings_current dans la base de données (les derniers enregistrements contiennent généralement un "enable" pour le plugin qui introduit le problème. Il suffit normalement de le remettre à false pour débloquer la situation.

**Comment by Sensooji** [comment]
Merci beaucoup !
Je vais essayer :-)

Le mer. 7 avr. 2021 à 11:03, Yannick Warnier ***@***.***> a
écrit :

**Comment by Sensooji** [comment]
Bonsoir,
Voici ce que je trouve dans settings_current d'une installation clonée
précédemment qui posait exactement le même problème (3 images)[image:
sqlplugins3.png]
[image: sqlplugins2.png]
[image: sqlplugins1.png]


Pensez-vous que je puisse tenter des modifs sur cette base de données pour
parvenir à reprendre la main sur l'installation et le fonctionnement des
plugins ?
(il est à noter aussi que je ne peux pas, pour tout nettoyer, upgrader
Chamilo via Softaculous pour cPanel mais c'est probablement un autre
problème)
Si ce n'est pas envisageable, j'attendrai une période calme
pédagogiquement, pour faire une installation sans plugins cette fois :-)
Merci de votre attention,
M.L.

Le mer. 7 avr. 2021 à 11:37, Rai Jin ***@***.***> a écrit :
>
> Merci beaucoup !
> Je vais essayer :-)
>
> Le mer. 7 avr. 2021 à 11:03, Yannick Warnier ***@***.***> a
écrit :
>>
>> @Sensooji ça se produit parfois avec des plugins qui entrent en conflit
les uns avec les autres ou des plugins qui ont besoin de librairies
additionnelles qui ne sont pas là. C'est un peu compliqué de ressortir de
cette situation, mais il est possible de désactiver les plugins un par un
depuis la table settings_current dans la base de données (les derniers
enregistrements contiennent généralement un "enable" pour le plugin qui
introduit le problème. Il suffit normalement de le remettre à false pour
débloquer la situation.

**Comment by Sensooji** [comment]
> @Sensooji Pourrais-tu envoyer les images que tu as visibilement tenté d'associer à ton dernier message?

Bonjour, 
Voici les images que j'avais envoyées
![sqlplugins3](https://user-images.githubusercontent.com/10753663/119000726-a719a300-b98b-11eb-96b7-6aa5f80011f8.png)
![sqlplugins2](https://user-images.githubusercontent.com/10753663/119000728-a7b23980-b98b-11eb-806e-f62cc351bf8d.png)
![sqlplugins1](https://user-images.githubusercontent.com/10753663/119000730-a84ad000-b98b-11eb-91d4-13a638f65ae8.png)
(je ne sais pas si elles visibles cette fois)
Merci,
Cordialement,
M.L.

**Comment by Sensooji** [comment]
Bonjour,
Merci beaucoup,
Je vais changer tout ça et je donne des nouvelles !
Bonne journée :-)

Le jeu. 12 août 2021 à 23:14, Yannick Warnier ***@***.***> a
écrit :

**Comment by Sensooji** [comment]
Bonjour,
J'ai fait progressivement les modifs plugin par plugin, un seul plugin à la
fois, puis tous ensemble. Comme rien n'y a fait, je compte effectuer une
nouvelle installation.
J'essaierai d'être plus vigilant encore sur la chronologie des
modifications que j'apporterai à cette nouvelle installation pour déceler
les causes de dysfonctionnements éventuels.
Merci bien :-)
M.L.
