### ISSUE TITLE
Unable to rename "Test" to "Quiz"

### ISSUE THREAD

**Issue by harismateen** [chamilo/chamilo-lms#3849]
**Describe**
Hi, I am unable to rename "Test" to "Quiz", but i can rename to any other name except "Quiz" 

**To Reproduce**
1. Go to My Course and Edit course
2. Click on Edit icon
3. Rename "Test" to "Quiz" 
4. Still showing "Test" instead of "Quiz"

**Expected behavior**
Should need to  show "Quiz" as text instead of "Test"

**Screenshots**
https://prnt.sc/11bit15
https://prnt.sc/11bivew
https://prnt.sc/11biwqk
https://prnt.sc/11bix8e

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS:inux Ubuntu 18.04
 - Version of Chamilo:  11.06

**Comment by ywarnier** [comment]
Hi @harismateen (got your e-mail, will answer soon)
Do you know how to use sub-languages? The names of the tools is translated if a similar language variable can be found, and in your case there is probably a translation from variable "Quiz" to string "Test". You should change that in a sub-langage.
https://docs.chamilo.org/admin-guide/platform_administration/chamilo_configuration_settings/languages/creating_a_sub-language

**Comment by ywarnier** [comment]
You could also try renaming to "My quiz", to confirm.
