### ISSUE TITLE
Error al enviar tarea , - Enviar Simple - No sube el archivo

### ISSUE THREAD

**Issue by developer703** [chamilo/chamilo-lms#3850]
Hola, tengo una instalacion de Chamilo
Chamilo version 1.11.4
php 7.2

Me e encontrado con una falla, cuando el estudiante o algun usuario intenta enviar un archivo usando la opcion envio simple el archivo no se adjunta , y aunque la tarea llega al profesor llega sin arhivo, e estado buscando pero no encunetro solucion, me pueden indicar como solucionar gracias
![imagen](https://user-images.githubusercontent.com/70910446/114742417-57531680-9d11-11eb-8858-068805afa396.png)

En el siguiente ejemplo se muestra una tarea enviada desde el envio normal, y las siguientes 2 desde envio simple
![imagen](https://user-images.githubusercontent.com/70910446/114742615-8bc6d280-9d11-11eb-9fb1-adcf235261e3.png)

estube revisando la base de datos y la url llega vacia a diferencia del otro metodo.

Espero me puedan indicar como solucionar.

Gracias

**Comment by ywarnier** [comment]
Tu versión es realmente 1.11.4 o es 1.11.14?

**Comment by developer703** [comment]
Esta es la informacion que aparece en el archivo readme

# Chamilo 1.11.x

[![Build Status](https://travis-ci.org/chamilo/chamilo-lms.svg?branch=1.11.x)](https://travis-ci.org/chamilo/chamilo-lms)
[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/chamilo/chamilo-lms/badges/quality-score.png?b=1.11.x)](https://scrutinizer-ci.com/g/chamilo/chamilo-lms/?branch=1.11.x)
[![Code Coverage](https://scrutinizer-ci.com/g/chamilo/chamilo-lms/badges/coverage.png?b=1.11.x)](https://scrutinizer-ci.com/g/chamilo/chamilo-lms/?branch=1.11.x)
[![Bountysource](https://www.bountysource.com/badge/team?team_id=12439&style=raised)](https://www.bountysource.com/teams/chamilo?utm_source=chamilo&utm_medium=shield&utm_campaign=raised)
[![Code Consistency](https://squizlabs.github.io/PHP_CodeSniffer/analysis/chamilo/chamilo-lms/grade.svg)](http://squizlabs.github.io/PHP_CodeSniffer/analysis/chamilo/chamilo-lms/)
[![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/166/badge)](https://bestpractices.coreinfrastructure.org/projects/166)
[![Codacy Badge](https://api.codacy.com/project/badge/Grade/88e934aab2f34bb7a0397a6f62b078b2)](https://www.codacy.com/app/chamilo/chamilo-lms?utm_source=github.com&utm_medium=referral&utm_content=chamilo/chamilo-lms&utm_campaign=badger)

## Installation






y esta es la informacion que aparece en el archivo configuration.php
<?php
// Chamilo version 1.11.4
// File generated by /install/index.php script - Tue, 06 Mar 2018 17:01:06 -0500
/* For licensing terms, see /license.txt */
/**
 * Campus configuration
 *


Gracias, quedo atento

**Comment by developer703** [comment]
> 
> 
> Tu versión es realmente 1.11.4 o es 1.11.14?
```

Esta es la informacion que aparece en el archivo readme
Chamilo 1.11.x

Build Status
Scrutinizer Code Quality
Code Coverage
Bountysource
Code Consistency
CII Best Practices
Codacy Badge
Installation

y esta es la informacion que aparece en el archivo configuration.php

<?php
// Chamilo version 1.11.4
// File generated by /install/index.php script - Tue, 06 Mar 2018 17:01:06 -0500
/* For licensing terms, see /license.txt */
/**
 * Campus configuration
 *


```

**Comment by christianbeeznest** [comment]
Hola @developer73 , en la version 1.11.14 no se ve el error, he intentado como profesor y alumno inclusive activando la opcion "allow_only_one_student_publication_per_user" dentro del archivo configuration.php, se puede ver el archivo enviado en cada tarea
![Screenshot.png…]()
