### ISSUE TITLE
Point IP to sub-domain

### ISSUE THREAD

**Issue by harismateen** [chamilo/chamilo-lms#3851]
**Describe**
Hi, can you please assist me on pointing IP to sub-domain -
I am seeing this root folder right after i follow below configuration: screenshot: https://prnt.sc/11e68ui
 
**To Reproduce**
1. Updated "configuration.php" --> $_configuration['root_web'] = 'http://subdomain.domain.com/';
2. Updated apache 2 --> ServerName http://subdomain.domain.com/
3. Reloaded apache2 and restarted
4. Root folder is showing - https://prnt.sc/11e68ui

**Expected behavior**
It should run the chamilo as working on IP 

**Screenshots**
https://prnt.sc/11e68ui

**Desktop (please complete the following information):**
 - OS:Linux Ubuntu 

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo: 1.11.06

**Comment by harismateen** [comment]
I have manged to done it - 
But seems like image are still coming from IP instead of sub-domain - 
how to change this also? 
screenshot: https://prnt.sc/11k41qh

**Comment by ywarnier** [comment]
Seems like your "root_sys" parameter is not pointing to the right folder (it should include the "/chamilo/" subfolder at the end.
In your second comment, you mention images are broken. This is become the broken image in your screenshot was edited through the WYSIWYG editor, which may save the full path to the image. Just update that HTML section to update the path to your image.

The fact that the header and the language icon are shown correctly prove that your configuration is now correct. It is only the *content* that is still with the wrong path.
