### ISSUE TITLE
Students cannot connect to Zoom Videoconference

### ISSUE THREAD

**Issue by jubach2020** [chamilo/chamilo-lms#3852]
### Current behavior
A profile has been created in Zoom (paid), the configuration is as marked by the Plugin documentation. Once the configuration is done, an attempt has been made to perform tests, the Teacher starts the videoconference, and the students are added to the session. Chamilo indicates that the session is not active and does not allow progress.

### Expected behavior
At the point of session creation by the teacher, students will have to be added to the session started, and this is not the case.

### Steps to reproduce
- Configure the Zoom plugin in Chamilo according to the README (with a payment account would be ideal)
- Start a video conference session
- As a student add yourself to the logged in session, theoretically with the current version you will not be able to login.

### Chamilo Version 
Chamilo ver. 1.11.14

In the image the result of Entering the videoconference
![WhatsApp Image 2021-04-15 at 09 18 13](https://user-images.githubusercontent.com/61415342/114829708-b4ab9e00-9dcb-11eb-9fcd-0f3919952cb3.jpeg)

**Comment by NicoDucou** [comment]
I just tried it on an up to date Chamilo (git installation from today) and it works fine in a base course and in a session.
The teacher starts the zoom instantaneous session and the learner can enter.
The teacher must be in the zoom room and not have closed it for the zoom session to be accessible.
So for me there is no more problem here and it can be closed.

**Comment by jubach2020** [comment]
I have found more data, if the user is a teacher + administrator, joining the video conference is active. If, on the other hand, the user is Student / Student, he cannot join the videoconference ("Conference not available"), there is the error.

**Comment by kolynn86** [comment]
![3FA36603-B72D-499F-B70E-AF75C55EDF40](https://user-images.githubusercontent.com/65718735/127685605-f089d09d-e248-41bb-94fd-d383bd0190aa.jpeg)

A teacher has set up a zoom meeting but the student cannot join

**Comment by aprenred** [comment]
Hi ! Any news ? 
No funciona para mi tampoco.

Sí, los administradores pueden entrar en la sala

Pero los alumnos no..... :( 

Alguna novedad ?

**Comment by evandro-asd** [comment]
same error on my chamilo... (1.11.12)
and the file "/plugin/zoom/endpoint.php" returns HTTP ERROR 500

**Comment by evandro-asd** [comment]
Achei o erro, exatamente como descrito pelo @AngelFQC it is necessary to register the url of the endpoint.php in the zoom and enable the items.

**Comment by ywarnier** [comment]
@AngelFQC could you add those instructions to the README.md of the plugin ? (I don't see them there)

**Comment by evandro-asd** [comment]
@ywarnier the instructions are on configuration area of the plugin, but in README.md i don't see too

**Comment by AngelFQC** [comment]
I just added the instructions to README file. Here 4e7c71f3b9523c779b9e4f5e2d26fd2256c0afed

**Comment by ywarnier** [comment]
@jubach2020 as far as our testing shows, this is not an issue with the software but rather with the configuration. I am closing this issue, but feel free to re-open or comment if you feel this hasn't solved it.

**Comment by ywarnier** [comment]
And thank you for pushing us to improve our documentation.
