### ISSUE TITLE
Mover Chamilo a un subdominio

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3853]
**Tu solicitud está relacionado con alguna molestia? Describe...**
No es una molestia sino más bien una consulta. Necesito mover la instalación de Chamilo desde una carpeta del sitio a un subdominio del mismo sitio. Tengo varios cursos activos y mucha información de los alumnos que no puedo perder. No encuentro cómo hacerlo (si es posible).

**Describe la solución que te gustaría encontrar**
Se me ocurren dos opciones:

- Mover la instalación actual completa al subdominio.
- Hacer una instalación nueva en el subdominio y copiar los cursos, usuarios, etc. desde la instalación actual, para luego eliminarla. El tema es que no debería perder ninguna información. No sé si es posible hacer que la instalación nueva apunte a la base de datos actual, o copiar los datos de una base a la otra.

**Contexto adicional**
Chamilo 1.11.14
Instalado mediante Softaculous Apps Installer
Servidor Linux (no sé qué versión)
Tengo acceso al server con CPanel.

Muchas gracias.

**Comment by ywarnier** [comment]
Hola @jolufe 
Es un proceso que lamentablemente (por una serie de razones que no quiero detallar ahora) es muy complicado si no tienes el control al 100% de tu servidor y buenos conocimientos de Linux.
En resumen, hay que:

- suspender el servicio
- tomar un backup (dump) de la base de datos
- remplazar, en el archivo del dump, toda ocurencia de la URL con subcarpeta por la URL con subdominio
- restaurar la base de datos (ahí, dependiendo de lo que puedas hacer en términos de espacio y de tiempo de suspención del servicio, variará la forma de hacerlo)
- tomar una copia de los archivos
- modificar toda ocurencia de la URL con subcarpeta por la URL con subdominio en todos los archivos
- verificar/corregir manualmente el archivo app/config/configuration.php

Para ser sincero, es un servicio profesional que damos a nuestros clientes, porque la complejidad del proceso (dependiendo del tipo de acceso y la cantidad de datos a tratar) se puede disparar al cielo.
