### ISSUE TITLE
Forum notification subscription not resetted when user unsubscribe from course

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3854]
In Chamilo 1.11.x of 20210412 when a user was subscribed to a course and in this course it subscribed to forum notification, there is a record in "c_forum_notification".

When the user unsubscribe from the course, the notification registration in "c_forum_notification" is not removed so the user still receive forum notification.

CF BT#18654

**Comment by christianbeeznest** [comment]
I have tried to unsubscribe users as admin and user and saw the records related with that user in c_forum_notification table is removed , I saw  unsubscribe user button didn{t work in home and sort courses pages , they are ok now.
