### ISSUE TITLE
Capacidad de Chamilo - Limites? - Soluciones ?

### ISSUE THREAD

**Issue by developer703** [chamilo/chamilo-lms#3857]
Hola, esta es una consulta sobre chamilo, tengo la version 1.11.4 (asi lo indica el archivo configuration.php)

mi consulta es que cuando los usuarios superan los 200 simultaneos (haciendo actividades o tareas) el servidor se empiza a colapsar o a presentar lentitud
caracteristicas servidor
8  cores
ram 16
banda ancha de 400 MB
Linux - Apache
----------------
Chamilo trae limites? 
pensando que era el banda ancha los monte en un servidor con 2GB de banda ancha y logre notar algo similar cuando superaba los 200 usuarios

---------------------
Hay que configurar algo en el servidor?
Hay que configurar algo en el Chamilo?
que hay que configurar para que no se presenten estas fallas?, ya que cuando ocurren se les empieza a caer el sistema a los usuarios.
o que caracteristicas debe tener el servidor?

usuarios estandar 500-700  normal mente en plataforma

Quedo atento

**Comment by ywarnier** [comment]
Hola @developer703 
Primer paso: revisar documentation/optimization.html en tu carpeta de Chamilo. Puedes consultarlo en línea en https://campus.chamilo.org/documentation/optimization.html
Segundo paso: una vez revisada esta documentación y aplicadas las optimizaciones que, en tu caso, se pueden aplicar (no todo sirve para todos), analizar los elementos que generan lentitud.

Por lo general, una primera oportunidad de tener 200 usuarios simultaneos afecta principalmente el número de usuarios en línea. Esto lo puedes desactivar en los parámetros de configuración (hay 3 posibles elecciones - público, privado global y otra más -> desactivarlas todas).

Por lo general también, al tener muchos usuarios simultáneos, aparecerán unos patrones de queries lentos en tu base de datos. Analízalos para saber qué parte de tu base de datos está más usada por los usuarios en *tu caso particular* (Chamilo tiene más de 20 herramientas, y los casos de uso varían - algunos usan mucho los ejercicios, otros usan mucho los docuemntos, etc). Con esto deberías poder ir hacia más optimizaciones.

Recuerda que Chamilo es como un "framework". Te provee un sistema base, pero su hosting y las optimizationes que le apliques dependen de ti, de las condiciones de *tu* servidor y del comportamiento de *tus* usuarios. Existen proveedores oficiales de Chamilo que se encargan de esta complejidad si prefieres delegar este trabajo. Estos proveedores contribuyen *activamente* al proyecto Chamilo.
