### ISSUE TITLE
Activating the custom page puts the sub footer in the middle

### ISSUE THREAD

**Issue by TOH2F** [chamilo/chamilo-lms#3861]
hello I activated on chamilo 1.11.14 the custom page index-unlogged.php and now I have the footer in the middle of the solutions page?

![image](https://user-images.githubusercontent.com/60504041/116877236-f8046a00-ac1d-11eb-99a1-6607e26ed6ca.png)

**Comment by ywarnier** [comment]
I remember @jmontoyaa helped me fix that one, but I don't remember what it was (a bug in the official 1.11.14 release, that only activates under certain very specific conditions, I believe)

**Comment by TOH2F** [comment]
thank you, do you have the solution?

**Comment by matiasr2503** [comment]
> thank you, do you have the solution?

Hi! you can fix this manually by navigating to `../chamilo_folder/app/ Resources/public/css/themes/`

Search enter the folder of your theme configured in chamilo (eg cool blue): `../cool_blue/`

Edit the `default.css` file

Find the block `body> main footer.footer`

And edit the parameter `position`, change the value `absolute` to `fixed`

Example:

![image](https://user-images.githubusercontent.com/21975246/126683655-8dfd9ba6-f0ef-4511-9c56-66c33df9c14a.png)

Regards!
