### ISSUE TITLE
Cusom icon in learnpath

### ISSUE THREAD

**Issue by TOH2F** [chamilo/chamilo-lms#3862]
Hello,
Is it possible to customize the icon of a route in chamilo?

![image](https://user-images.githubusercontent.com/60504041/116913104-5bf05800-ac49-11eb-8786-591c88c42f29.png)

in learnpath parameter is empty

![image](https://user-images.githubusercontent.com/60504041/116913171-6f032800-ac49-11eb-8324-1b2975d01818.png)

Thank you

**Comment by NicoDucou** [comment]
To use this functionality you need to import a personalised CSS and add in your CSS a sub folder called "lp_icons".
The "icône" selector will show all the available icons in this folder : 
![image](https://user-images.githubusercontent.com/6579268/118962664-e7662a80-b965-11eb-9827-33453c6d442d.png)

Once selected it will show the corresponding icon for the LP : 
![image](https://user-images.githubusercontent.com/6579268/118962969-3d3ad280-b966-11eb-94cd-12cc69688eec.png)
