### ISSUE TITLE
Error visualizando curso en catálogo

### ISSUE THREAD

**Issue by Asier97** [chamilo/chamilo-lms#3866]
**Describe el problema**
Cuando la descripción del curso contiene un enlace la previsualización se ve mal

**Cómo reproducir**
Pasos para reproducir el problema:
1. Crear un curso
2. Poner un texto de introducción que contenga un enlace (_en mi caso es un mailto:_)
3. Previsualice el curso desde el catálogo de cursos
4. Ver el error

**Comportamiento esperado**
Al visualizar el curso accediendo desde el catálogo debería verse la introducción donde corresponde y no encima de la cabecera.

**Capturas de pantalla**
Captura de la descripción del curso:
![image](https://user-images.githubusercontent.com/26870658/117282605-38095e00-ae65-11eb-8ece-d40907161419.png)

(Nótese donde está el enlace)

Catálogo de cursos (sin iniciar sesión)
![image](https://user-images.githubusercontent.com/26870658/117282720-596a4a00-ae65-11eb-84d8-83c60825d899.png)

Le damos al del personal de hipermercados y:
![image](https://user-images.githubusercontent.com/26870658/117282820-74d55500-ae65-11eb-84b5-7b6a70bcc39a.png)

Vemos que el texto se pone encima de la cabecera y empieza justo donde comienza el hipervínculo. En el apartado donde debería aparecer no sale nada

**Escritorio**
 - Sistema operativo : Windows 10
 - Navegador: Microsoft Edge 90.0.818.51

**Servidor**
 - Sistema operativo : Linux Ubuntu 18.04
 - Versión de Chamilo:  1.11.14
 - Versión de PHP: 7.X

**Contexto adicional**
Es el Chamilo de un cliente, no tengo acceso a muchos datos, podría sacar la versión de PHP si es necesario pero poco más

**Comment by Asier97** [comment]
Buenas, vengo a añadir algo:

Resulta que no es el texto que se pone donde indico en la captura nº 1, es el que se pone desde _Descipción general_

![image](https://user-images.githubusercontent.com/26870658/117284646-5b350d00-ae67-11eb-8210-0668b04e753a.png)

Quitando el enlace el problema se soluciona pero ahora no me sale nada

![image](https://user-images.githubusercontent.com/26870658/117284732-70aa3700-ae67-11eb-9386-436c3ca05f3b.png)

Sin embargo me gustaría tener en enlace, pues ese es el motivo de que haya abierto este issue.

### **A propósito, la versión es 1.11.8, no 1.11.14**

**Comment by nosolored** [comment]
Hola Asier,
Ese comportamiento no ocurre en las últimas versiones, así que lo aconsejable sería actualizar.
No puedo saber si en la 1.11.8 era un error, ya no utilizamos esa versión, es bastante antigua.
