### ISSUE TITLE
Error al modificar número de intentos de ejercicio

### ISSUE THREAD

**Issue by Neorilas** [chamilo/chamilo-lms#3868]
Buenas.

Estoy intentando modificar el número de intentos en un ejercicio. Voy a ejercicios dentro del curso. Selecciono el botón de "modificar ejercicio" despliego el panel de "Parametros avanzados" y el número de intentos o bien no aparece o aparece como no editable.

Utilizo la versión de Chamilo 1.11.14

Un saludo.

**Comment by Asier97** [comment]
Buenas. ¿El ejercicio se encuentra dentro de una lección o insertado en algún otro lado? Los ejercicios que añado a lecciones no me deja editarlos.

Si no es eso entonces no puedo ayudarte

**Comment by Neorilas** [comment]
Si, está dentro de una lección, pero puedo modificar todo salvo el número de intentos.

**Comment by christianbeeznest** [comment]
Hola @Neorilas , mientras la opción "force_edit_exercise_in_lp" este "false" en el archivo de configuración (configuration.php) algunas opciones del ejercicio añadido en una lección no pueden ser modificados, 
el caso de "Maximos intentos", "Control de tiempo", "Revisar mis respuestas", "Preguntas aleatorias" y "Propagar los resultados negativos entre preguntas".
