### ISSUE TITLE
learning_path bloqueado

### ISSUE THREAD

**Issue by Asier97** [chamilo/chamilo-lms#3870]
**Describe el problema**
Buenas. **Siento infinitamente abrir otro error**, pero no he encontrado información sobre esto en ningún lado. Un cliente nos ha llamado diciendo **que no pueden ver las lecciones** (ver foto 1). Echando un vistazo desde 'Ver servidor' al insertar una imagen hemos visto que learning_path está bloqueado (ver foto 2). Según él, algunas lecciones se ven y otras no, pero yo no visualizo ninguna, lo que me lleva a pensar que antes se visualizaban y han tocado algo. **En resumen: learning_path está bloqueado y no sé como desbloquearlo**. Revisando los permisos desde el gestor de archivos del hosting está todo en orden (ver foto 4 y 5)

**Cómo reproducir**
1. Crear una lección SCROM.
2. Crear un elemento con texto y/o imágenes (ver foto 3)
3. Visualizar la lección y toparse con el error

**Comportamiento esperado**
Que se vea la sección de la lección

**Capturas de pantalla**
**1.** "**Documento protegido**" al visualizar la lección
![image](https://user-images.githubusercontent.com/26870658/117683472-631ce600-b1b4-11eb-9573-ff46e3767992.png)

**2.** learning_path bloqueado (lo visualizo desde la opción de Ver servidor)
![image](https://user-images.githubusercontent.com/26870658/117683663-96f80b80-b1b4-11eb-81b2-859dee1d13b6.png)

**3.** Editando la lección de la imagen 1
![image](https://user-images.githubusercontent.com/26870658/117684185-0968eb80-b1b5-11eb-8ef0-9743c78813d7.png)

**4.** Permisos de las carpetas en el servidor
![image](https://user-images.githubusercontent.com/26870658/117684806-a2980200-b1b5-11eb-84fc-ec85d9a6a9b6.png)

**5.** Permisos de las carpetas en el servidor
![image](https://user-images.githubusercontent.com/26870658/117684888-b6436880-b1b5-11eb-9200-2cbb229f9178.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10 Pro
 - Navegador: Microsoft Edge 90.0.818.51

**Servidor**
 - Sistema operativo : Linux Ubuntu
 - Versión de Chamilo:  1.11.14
 - Versión de PHP: 7.4.18

**Contexto adicional**
Siento que este no es un error como tal, he probado antes en Chamilo forums pero no recibo respuesta, siento si este problema molesta o entorpece vuestro trabajo. **Soy consciente de que es un problema de permisos y que puede ser problema del hosting del cliente**, pero se me hace raro que learning_path sea la única carpeta bloqueada. Sé que los clientes estuvieron urgando en documentos y en permisos pese a que dicen no haber tocado nada. Soy consciente que para mostrar el error utilizo una funcionalidad de Chamilo que utiliza elfinder, he buscado el origen del problema en su código pero no he visto nada raro.

**Comment by christianbeeznest** [comment]
Hola @Asier97

El permiso de lectura y bloqueado que ves en el editor al insertar una imagen es distinto a los permisos que le das a los ficheros en tu servidor desde consola (ejemplo 775), en el caso del editor cuando esta bloqueado quiere decir que no puedes subir ningún archivo a esa carpeta desde ahí, asi la carpeta tenga permisos 777 el editor puede bloquearlo desde su configuración
En este caso la carpeta learning_path esta configurado como solo lectura en el editor (restringido a subir ficheros) para que no se pueda almacenar mas archivos ahí puesto que esa carpeta es especial para las lecciones creadas desde la plataforma.
Puedes dar los permisos 775 (lectura / escritura) desde tu servidor sin problemas, lo que ves en el editor al insertar imagen es otra configuración que afecta solo cuando usas el editor.

**Comment by Asier97** [comment]
Hola @christianbeeznest 

Gracias por dedicar tiempo a responder. Sin embargo, yo sí puedo subir cosas a learning_path, lo que no puedo es visualizar las lecciones (excepto editándolas, ahí sí las veo). Pero aunque fuera el caso, ¿cómo lo soluciono? ¿Dónde está esa configuración de la que hablas?

Muchas gracias

**Comment by christianbeeznest** [comment]
Hola @Asier97 , los permisos que te decia es validado por el buscador (elfinder) pero eso depende directamente de las carpetas en el servidor, tienes que dar permisos de escritura a la carpeta app/courses para que puedas agregar imagenes en la carpeta documents  , segui los pasos que mensionas para reproducir el error pero no lo veo, si puedo subir la imagen y visualizarlo.

Gracias por confirmar.

**Comment by Asier97** [comment]
Será problema del servidor de nuestros clientes, sumado a que son muy restrictivos. No tiene sentido mantener este error abierto así que lo cierro, muchas gracias por su tiempo
