### ISSUE TITLE
Teachers cant hear audio responses in exercises

### ISSUE THREAD

**Issue by ebiscarlata** [chamilo/chamilo-lms#3873]
### Current behavior / Resultado actual / Résultat actuel

Hi! I have a chamilo platform, I have had it for almost a year, during this month I wanted to do exercises that had answers to record audio. When the students enter, they record their audio, it gives you the option to download it and everything, but when you finish the exercise the teachers can not hear the audios, in fact it comes out as if the student had not recorded anything because the duration time it's 00:00. Please can someone guide me what is happening?

**Comment by AngelFQC** [comment]
Hi @ebiscarlata 

Please complete the template for bug report when creating a new issue https://github.com/chamilo/chamilo-lms/issues/new?template=en-bug-report.md
This helps us to know the version of software you are using, for example.

**Comment by ebiscarlata** [comment]
**Describe**
exercises that had answers to record audio does not work, When the students enter, they record their audio, it gives you the option to download it and everything works to this point, but when you finish the exercise and the teachers want to rate it they can not hear the audios, in fact it comes out as if the student had not recorded anything because the duration time it's 00:00.

**To Reproduce**
1.- enter an exercise( it has only two questions), 
2.- start answering
3.- the first questions is open answer, it works perfectly
4.- second questión  requires to record an audio.
5.- you record your audio, you can even listen to it again or download it
6.- finish your test.
------ after all that when the teachers try to grade the exercise:
7.-you enter the student exercise and the audio apears in time 00:00, 8.-if you push play nothing hapens. (this last part is the issue)

I cant give you access to the platforme since it´s al ready working. 

**Expected behavior**
when the teachers try to grade the exercise: play the audio redorded by the students.

**Screenshots**
![s01](https://user-images.githubusercontent.com/26977154/118339095-78a84d80-b4dd-11eb-87d9-d80f0d956305.png)
![s02](https://user-images.githubusercontent.com/26977154/118339101-7a721100-b4dd-11eb-9b92-75ff5c636f13.png)
![s03](https://user-images.githubusercontent.com/26977154/118339105-7ba33e00-b4dd-11eb-9506-ec977d00451a.png)


**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Server
 - OS:  Linux Ubuntu 18.04
 - Version of Chamilo:  1.11.14
 - Version of PHP: 7.3

**Comment by lonesomewalker** [comment]
1. what does your error log say?
2. do you have all green here: https://your-campus-url/main/admin/system_status.php
3. do you have ssl enabled?

**Comment by NicoDucou** [comment]
Hi @ebiscarlata 
Did you applied the recent security patch (https://support.chamilo.org/projects/chamilo-18/wiki/Security_issues) to your Chamilo installation ? 
Because the problem you report his corresponding to a problem that appeared because of the application of one of the security patch.

The commit to fix this is : https://github.com/chamilo/chamilo-lms/commit/0d42cb938be03b558b6252664503498fbd237fc9

Best regards

**Comment by ebiscarlata** [comment]
> 1. what does your error log say?
> 2. do you have all green here: https://your-campus-url/main/admin/system_status.php
![image](https://user-images.githubusercontent.com/26977154/118989497-b37c0c80-b947-11eb-8124-854465f35feb.png)

> 3. do you have ssl enabled? yes i do

**Comment by ebiscarlata** [comment]
> Hi @ebiscarlata
> Did you applied the recent security patch (https://support.chamilo.org/projects/chamilo-18/wiki/Security_issues) to your Chamilo installation ?
> Because the problem you report his corresponding to a problem that appeared because of the application of one of the security patch.
> 
> The commit to fix this is : [0d42cb9](https://github.com/chamilo/chamilo-lms/commit/0d42cb938be03b558b6252664503498fbd237fc9)
> 
> Best regards

Thanks a lot! I edited the files as recommended but it still doesn't work, the error keeps the same.

**Comment by NicoDucou** [comment]
> > Hi @ebiscarlata
> > Did you applied the recent security patch (https://support.chamilo.org/projects/chamilo-18/wiki/Security_issues) to your Chamilo installation ?
> > Because the problem you report his corresponding to a problem that appeared because of the application of one of the security patch.
> > The commit to fix this is : [0d42cb9](https://github.com/chamilo/chamilo-lms/commit/0d42cb938be03b558b6252664503498fbd237fc9)
> > Best regards
> 
> Thanks a lot! I edited the files as recommended but it still doesn't work, the error keeps the same.
After applying the change you should clear the cache and archive directory of your Chamilo entering the "Limpieza de caché y archivos temporales" of the "Sistema"'s bloc from the administration page.
You should also clear the cache of your browser to make sure the modified ajax file is loaded.
Finally did you try to record a new audio ?
The past audio will not appear you have to redo the exercise and do a new audio answer for it to work.
Best regards

**Comment by ywarnier** [comment]
Closing for lack of user feedback
