### ISSUE TITLE
uncaught doctrine

### ISSUE THREAD

**Issue by Gazzxy** [chamilo/chamilo-lms#3875]
**Describe**
so i manage to install once.. but shortly after something was up-loaded the error returned.. 
usually i don't get past install as this message turns up at the install process

[php7:error] [pid 2026] [client ] PHP Fatal error: Uncaught Doctrine\ORM\Mapping\MappingException: Class "Chamilo\CoreBundle\Entity\Language" is not a valid entity or mapped super class. in /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:346\nStack trace:\n#0 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php(95): Doctrine\ORM\Mapping\MappingException::classIsNotAValidEntityOrMappedSuperClass()\n#1 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(155): Doctrine\ORM\Mapping\Driver\AnnotationDriver->loadMetadataForClass()\n#2 /var/www/chamilo/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(306): Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata()\n#3 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(82): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata()\n#4 /var/www/chamilo/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractCl in /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php on line 346

tried getting a fresh package  but otherwise i duno where to go with this if i get past the install the site eventually comes down with a http500 error with this in the server log

**Expected behavior**
to work

**Desktop (please complete the following information):**
 - OS: e.g. Linux Ubuntu 20 and windows 10 - Browser e.g. chrome, firefox...... yes

**Server
 - OS: ubuntu 20
 - Version of Chamilo:  1.11.14
 -  php 7.4
 - apache2.4
- sql... laest

**Comment by Gazzxy** [comment]
oh sorry this is a different error to what i normally get

usually its

**Comment by Gazzxy** [comment]
[php7:error] [pid 2026] [client ] PHP Fatal error:  Uncaught Doctrine\\ORM\\Mapping\\MappingException: Class "Chamilo\\CoreBundle\\Entity\\Language" is not a valid entity or mapped super class. in /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:346\nStack trace:\n#0 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/AnnotationDriver.php(95): Doctrine\\ORM\\Mapping\\MappingException::classIsNotAValidEntityOrMappedSuperClass()\n#1 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(155): Doctrine\\ORM\\Mapping\\Driver\\AnnotationDriver->loadMetadataForClass()\n#2 /var/www/chamilo/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(306): Doctrine\\ORM\\Mapping\\ClassMetadataFactory->doLoadMetadata()\n#3 /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(82): Doctrine\\Persistence\\Mapping\\AbstractClassMetadataFactory->loadMetadata()\n#4 /var/www/chamilo/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractCl in /var/www/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php on line 346

**Comment by Gazzxy** [comment]
If i get it to isntall it seem that it kick the error back out if i restart apache... unless that was coincidence this time

**Comment by jmontoyaa** [comment]
I think the error appear because some PHP files were in the server cache.
The apache restart cleaned that.

I suggest to do a "composer update" and then restart apache

**Comment by Gazzxy** [comment]
tried that.. eventually got composer to actually do the update but  same error

**Comment by NicoDucou** [comment]
Hi @Gazzxy 
Can you confirm if this is a new installation or if you are doing an upgrade ?
Also can you tell us if it's a installation from a packaged Chamilo or from git ?
Can you give us the link of the packaged you downloaded ?

**Comment by Gazzxy** [comment]
It was a fresh install from the zip file on the website.. 

got it working now just made a separate VM so its running on its own webserver instead of sharing with a few other bits and pieves
