### ISSUE TITLE
Remove default_course_document/flash

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3879]
In the migration process from 1.11.x to 2.0, remove this folder entirely

**Comment by jmontoyaa** [comment]
This was already deleted here 

https://github.com/chamilo/chamilo-lms/commit/f0e964f744b0fb729e1c1a08eb9ced9e3589fbc9#diff-818e4829375a3e2932a2a96935618e2096c18143ae893c76fb157b5474847d98

and also I removed some really old assets:

https://github.com/chamilo/chamilo-lms/commit/ba300d04210f6966653d1823ad52dc61427a74cc
