### ISSUE TITLE
[Course copy] Agregar un texto de ayuda en el selector de curso de destino para la copia de curso

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3881]
En un curso en la herramienta de "Mantenimiento del curso" entrar en la opcion "Copiar el curso"
Se ve un campo "Seleccionar el curso de destino". De bajo de este selector, agregar un mensaje de ayuda para indicar : 
* EN : You can only copy to course for which you are a teacher
* ES : Solamente se puede copiar a cursos en el cual estas profesor
* FR : Vous pouvez copier uniquement vers un cours dans lequel vous êtes professeur.

Por ejemplo en esta pagina (el texto no debe estar en rojo, es solo para visualisarlo facilmente en el screenshot) :
https://11.chamilo.org/main/coursecopy/copy_course.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=
![image](https://user-images.githubusercontent.com/6579268/119109859-d7138580-ba21-11eb-86e0-e323742330ed.png)

**Comment by nosolored** [comment]
Hola, muy buena idea, sólo una pequeña corrección para el texto en Español:
"Solamente se puede copiar a un curso en el que seas profesor"
