### ISSUE TITLE
[Document tool] 1 ajax call to calculate the size of all the folders instead of 1 call per folder

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3882]
At the moment when opening the document tool you get the list of documents and folder. The page load quickly to show the list of document and in the background the size of all the subfolders are calculated and appear one by one.
We can see in the network tab of the browser console calls like this : 
* https://11.chamilo.org/main/inc/ajax/document.ajax.php?a=get_dir_size&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&path=/learning_path/Word

The problem is that if we have many subfolders (for example 40) then it generate many calls and each call is a new connexion to the database. On some cloud hosting, to avoid DDOS there is a limit on the number of connexion from one host to the database. So if there are 40 calls from one page it might be over the limit and it generates an error.

To avoid this error we would need to change this organisation. Instead of doing one call per subfolder, we should do one call with the main folder in parameter and it should return the size of all the subfolder and display all of them at once.

To test it you can go to https://11.chamilo.org/main/document/document.php?id=1610&_qf__selector=&cidReq=NICODU&id_session=0&gidReq=0

You will see that the size column is getting field one by one and there are many ajax calls. After this development it should be filled all in one and there should be only one Ajax call.

**Comment by ywarnier** [comment]
This PR has been merged. The feature has been implemented.
