### ISSUE TITLE
Fatal error:  Cannot redeclare normalizer_is_normalized()

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3896]
**Describe el problema**

Tengo dos instalaciones de Chamilo en el mismo servidor, porque estoy migrando de un campus a otro.
En una carpeta está instalada la versión 1.11.12 (en uso actualmente) y en un subdominio la versión 1.11.14 (destino de la migración). 

Sin haber hecho ningún cambio, ambas instalaciones dejaron de funcionar repentinamente, con el siguiente mensaje de error:

Fatal error:  Cannot redeclare normalizer_is_normalized() (previously declared in /home/uttama/public_html/campusvirtual/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15) in /home/uttama/public_html/campusvirtual/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 20

OBSERVACIÓN:
El error_log de la carpeta principal de Chamilo arroja periódicamente el mensaje:

PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /home7/uttama/public_html/campus/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2640

Pero eso lo hace siempre, con la plataforma funcionando, y supongo que no tiene nada que ver con la falla actual.

COMENTARIOS:
Los responsables técnicos del hosting sostienen que el servidor no tuvo ningún cambio y que el problema es de la plataforma. Me parece imposible que así sea, pero no tengo más argumentos que el sentido común para discutirlo. Ellos dicen que es un "problema de código", pero ningún código deja de funcionar por arte de magia, y mucho menos en dos instalaciones al mismo tiempo.

Lo que hice para salir del paso fue comentar las líneas 20 y 21 de
public_html/campusvirtual/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php

LINEAS COMENTADAS EN intl.php
20) // function normalizer_is_normalized($s, $form = s\Normalizer::NFC) {return s\Normalizer::isNormalized($s, $form);}
21) // function normalizer_normalize($s, $form = s\Normalizer::NFC) {return s\Normalizer::normalize($s, $form);}

Aparentemente, la llamada a la función en public_html/campusvirtual/vendor/symfony/polyfill-intl-normalizer/bootstrap.php:15 se ejecuta antes que las que comenté en intl.php. O sea, que las funciones que no tienen if(!function_exists()) se ejecutan en segundo lugar y eso genera el error. Lo que habría que explicar es por qué lo hace ahora si hasta ayer funcionaba todo bien.

LLAMADAS CON CONDICIONAL EN bootstrap.php
if (!function_exists('normalizer_is_normalized')) {
    function normalizer_is_normalized($s, $form = p\Normalizer::NFC) { return p\Normalizer::isNormalized($s, $form); }
}
if (!function_exists('normalizer_normalize')) {
    function normalizer_normalize($s, $form = p\Normalizer::NFC) { return p\Normalizer::normalize($s, $form); }
}

Aguardo opiniones y comentarios.
Muchas gracias.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10 64 bits
 - Navegador: Vivaldi 3.8.2259.37

**Servidor
 - Sistema operativo : Linux
 - Versión de Chamilo:  1.11.12 y 1.11.14
 - Versión de PHP:  7.3 (ea-php73)

**Comment by christianbeeznest** [comment]
Hola @jolufe

El problema es con la libreria patchwork /home/uttama/public_html/campusvirtual/vendor/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 20

¿Tienes la extensión php-intl instalada correctamente? Por lo general, este error ocurre si ese no es el caso

A lo mejor su servidor se ha actualizado y no instalo esa libreria correctamente , puedes verificarlo en tu php.ini

Sería genial que la misma libreria pudiera verificar la extensión antes de encontrar este error bastante críptico. O tener una página de solución de problemas que contenga esta información. Aunque esta libreria está abandonado y ya no se mantiene. El autor sugiere usar el paquete symfony/polyfill-mbstring o symfony/string en su lugar  https://packagist.org/packages/patchwork/utf8

**Comment by jolufe** [comment]
Hola @christianbeeznest 

Muchas gracias por la respuesta. Por el momento hice un cambio de versión php a 7.4 y verifiqué que esté instalada la extensión intl. Me faltaría descomentar las líneas del script y ver qué pasa. Es evidente que algo pasó en el servidor, pero ahora es historia.
Espero que en las versiones futuras de Chamilo cambien de librería, supongo que sería lo mejor.

Un cordial saludo.

**Comment by ywarnier** [comment]
En Chamilo 2.0 soportaremos PHP a partir de versión 8.0 únicamente, y esto implica un refresco completo de muchas librerías. Por ahora estamos algo atrapados entre versiones 7.1 y 7.4 de Chamilo, para las cuales las distintas librerías que usamos no tienen un soporte idéntico todas, y esto es el tipo de problemas que causa.
En tu caso, es muy probable que la versión de PHP en tu servidor haya pasado de 7.2 a 7.3 sin avisarte, ya que la 7.2 dejó de ser soportada a fines del 2020 (https://www.php.net/supported-versions.php). El mensaje de "break" es típicamente un problema al cambiar de estas versiones.
