### ISSUE TITLE
El tutor no ve en la sesión los ejercicios del curso base

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#3898]
**Describe el problema**
Cuando se crea un ejercicio en un curso y se deja invisible para los alumnos de las sesiones, tampoco es visible para los tutores.
Si el ejercicio se hace visible y luego se vuelve invisible nuevamente, entonces los tutores lo pueden ver en la sesión.
En cualquiera de los casos el ejercicio se puede agregar a una lección, y allí sí es visible para todos.

**Cómo reproducir**

1. Crear una sesión de un curso.
2. En el curso base, hacer visible el área "Ejercicios"
3. En Ejercicios crear un ejercicio cualquiera y dejarlo invisible (esto es importante).
4. Ingresar a la sesión como alumno.
5. Ingresar al área de Ejercicios.
6. El ejercicio no se ve. **Esto está bien.**
7. Ingresar a la sesión como tutor.
8. Ingresar al área de Ejercicios.
9. El ejercicio no se ve. **Esto no está bien** (el tutor debería verlo).
10. Volver al curso base.
11. Hacer el ejercicio visible e inmediatamente invisible nuevamente.
12. Repetir pasos 7 y 8.
13. Ahora el ejercicio es visible en la sesión (para los tutores). **Esto está bien**.
14. El ejercicio sigue siendo invisible para los alumnos. **Esto está bien**.

**Comportamiento esperado**
Que un ejercicio invisible en el curso base sea visible para los tutores de sesión e invisible para los alumnos.
Esto sin necesidad de hacer lo descripto en el paso 11 explicado anteriormente.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : probado en Windows 7 y Windows 10
 - Navegador: probado en Vivaldi y en Firefox

**Servidor
 - Sistema operativo : Linux
 - Versión de Chamilo:  probado en 1.11.12 y 1.11.14
 - Versión de PHP: 7.4

**Comment by ywarnier** [comment]
> 1. Crear una sesión de un curso.
> 2. En el curso base, hacer visible el área "Ejercicios"
> 3. En Ejercicios crear un ejercicio cualquiera y dejarlo invisible (esto es importante).

Nuestra lógica es que si el ejercicio es invisible en el curso base, significa que el profesor principal (el que establece el material por ser usado por todos los demás) ha decidido que su ejercicio todavía no está listo (o ya no debería usarse). Por lo tanto, es lógico (en nuestro sistema) que al ingresar como tutor en una sesión con este curso, no puedas ver el ejercicio.

> 9. El ejercicio no se ve. **Esto no está bien** (el tutor debería verlo).

Sí está bien porque el tutor de sesión es "sometido" (me falta un vocabulario más preciso pero seguro me entiendes) a la autoridad del profesor del curso base para el material "correcto" a usar.

> 10. Volver al curso base.
> 11. Hacer el ejercicio visible e inmediatamente invisible nuevamente.
> 12. Repetir pasos 7 y 8.
> 13. Ahora el ejercicio es visible en la sesión (para los tutores). **Esto está bien**.

No, aquí es donde *no* está bien, porque no tiene sentido en nuestra lógica. Tampoco debería estar visible dentro de las lecciones, porque el profesor del curso base decidió que este ejercicio no estaba listo.

> **Comportamiento esperado**
> Que un ejercicio invisible en el curso base sea visible para los tutores de sesión e invisible para los alumnos.

Esta no es nuestra lógica. Entiendo el deseo, pero así no lo podemos hacer sin cambiar cientos de partes de código en Chamilo (porque así no fue diseñado).
A cambio, si es visible en el curso base, el tutor de sesión lo puede hacer invisible para preparar su sesión.

Creo que quizás esperas algo que no es de las sesiones de Chamilo... La idea es que haya un profesor que haga el material (incluyendo las lecciones), y tutores que hagan alteraciones menores a este material según el tipo de alumnos que tiene (adaptar el contenido a su público, pero de una manera ligera).
Si lo que quieres es simplemente compartir material (del curso base) entre profesores (repartidos como tutores en distintas sesiones), deberías esperar Chamilo 2.0+ que tendrá progresivamente más funcionalidades para compartir recursos entre profesores sin duplicarlos (y perder su sincronización cuando están duplicados).

Conclusión: el error aquí (por revisar de nuestro lado todavía) es que al hacerlo visible e invisible en el curso base, empiece a aparecer para el tutor de sesión.

**Comment by jolufe** [comment]
Muchas gracias @ywarnier por la respuesta y la información. 
Entiendo la lógica del mecanismo y me parece razonable.
Restaría saber si el comportamiento incorrecto es algo de Chamilo o de mi instalación.
Saludos.

**Comment by NicoDucou** [comment]
He creado un ejercicio en el curso base que se llama "Ejercicio en el curso base" y lo he dejado invisible aqui : https://11.chamilo.org/main/exercise/exercise.php?cidReq=VISIBILIDADEJERCICIOSENSESIONESYLEC&id_session=0&gidReq=0&gradebook=0&origin=&
Despues he creado una sesion con este curso y como tutor de la sesion voy a la herramienta de ejercicio y el ejercicio esta disponible pero no lo puedo modificar porque es un ejercicio del curso base y esta marcado como invisible para los alumnos : 
https://11.chamilo.org/main/exercise/exercise.php?cidReq=VISIBILIDADEJERCICIOSENSESIONESYLEC&id_session=107&gradebook=0&origin=&gidReq=0
![image](https://user-images.githubusercontent.com/6579268/129374851-37d25cf7-6280-4257-bfea-668f154947b9.png)
No lo puedo marcar para que sea visible en la sesion porque en el curso base esta marcado como invisible.

Ahora regreso al curso base y pongo en ejercicio visible. Ahora cuando voy en la sesion en la herramienta de ejercicios se ve el ejercicio como visible pero todavia no lo puedo modificar porque es un ejercicio del curso base : 
![image](https://user-images.githubusercontent.com/6579268/129375271-6e120784-fc14-4e14-b132-ba7d480282e8.png)

Pongo de nuevo el ejercicio como invisible en el curso base.
En la sesion creo una leccion y encontro el ejercicio disponible para integrarlo como item de mi leccion.

Este comportamiento me parece logico porque un ejercicio invisible en el curso base puede ser incluido en una leccion del curso base justamente porque un profesor no quiere que los alumnos vean el ejercicio que  ha preparado para integrarlo en un LP.

@ywarnier quieres que cambiemos el comportamiento ? Por el momento en 11.chamilo.org funciona como lo queria Jolufe. Creo que era por un pedido de Aix que Julio lo ha cambiado asi.

**Comment by jolufe** [comment]
Hola @ywarnier y @NicoDucou 

Quisiera agregar algo más. 

En mi experiencia, como un curso base puede tener varias sesiones (creo que esa es la idea), es muy probable que las necesidades de las sesiones sean diferentes. Por ejemplo: en una sesión puede ser útil que los alumnos accedan a los ejercicios directamente en el área "Ejercicios", pero en otra puede ser necesario que lo hagan solamente dentro de una lección. No es posible predecir eso de antemano con total certeza, máxime teniendo en cuenta que los tutores pueden tener distintas formas de encarar las tareas. 

Entiendo que el "dueño" del curso es el profesor que diseña el curso base, pero sería lógico que una sesión de tres alumnos se maneje diferente a una de treinta, por poner un ejemplo. Creo que sería muy bueno que los tutores de sesión tengan la funcionalidad de mostrar o no el área de ejercicios, o los ejercicios en forma individual. También podría ser una característica que el profesor pueda conceder o no a los tutores, dependiendo de las necesidades y el criterio del grupo de docentes.

Saludos.

**Comment by ywarnier** [comment]
@jolufe entiendo esto, pero tenemos que respetar un balance entre flexibilidad de la herramienta frente a los usuarios finales, sencillez de uso (como explicar estos posibles modos a los usuarios sin que tengan que descubrirlos ellos mismos), la mantenibilidad de la aplicación (a más casos, más difícil mantener) y el peso (a más opciones, más variaciones en la base de datos y por tanto más peso a cada consulta). Sería bueno registrar esta solicitud en un nuevo issue, tratando de ser lo más conciso sobre lo que tiene que ocurrir para que sea posible tener esta flexibilidad. De ahí lo estaríamos revisando en un par de versiones (1.11.16 y 2.0 tienen sus hojas de ruta ya muy cargadas).

**Comment by ywarnier** [comment]
@NicoDucou Está bien. Dejémoslo así por ahora. Gracias por el análisis. Servirá en algún momento más tarde.
