### ISSUE TITLE
Ldap config email won't fill with userprincipalname

### ISSUE THREAD

**Issue by Mariu7** [chamilo/chamilo-lms#3899]
**Describe**
Chamilo won't import userprincipalname to email field (it work's with lastname for some reason).
'email' => 'userprincipalname'

**Screenshots**
![image](https://user-images.githubusercontent.com/25581906/120764009-735c8280-c520-11eb-892d-8341fd745e29.png)
![image](https://user-images.githubusercontent.com/25581906/120764097-866f5280-c520-11eb-834c-81413ab2978a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 

**Server
 - OS:  Linux centos
 - Version of Chamilo: 1.11.14,
 - Version of PHP 7.4
 - 
**Additional context**

**Comment by Mariu7** [comment]
Update: It's visual bug

**Comment by Lucklock90** [comment]
Hi, How are you? I have a problem, with Search user over LDAP and i wonder is posible you can help me.
Thank You.

![image](https://github.com/user-attachments/assets/280f5e77-a550-4ef4-8952-c106710c00a9)

![image](https://github.com/user-attachments/assets/fac3aa72-46b0-447a-8eb3-c7962ee33269)
