### ISSUE TITLE
User list sorting (RegistrationDate or LatestLogin)

### ISSUE THREAD

**Issue by DrMickArtisan** [chamilo/chamilo-lms#3901]
**Describe**
While in administrator -> user list panel, i'm trying to sort user list by registration date.
And in fact the list is sorted by Active/inactive state (which is the preceding column)
This is linked to : 
1/ configuration with login_is_email true
2/ use of column number in sort link.
In fact, when login_is_email is set to true, the 6th column (email) is not displayed. So Registration Date column is counted as 8, but somehow still 9th while  ordering users in sql query (i guess)
**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Browser : firefox 89.0

**Server
 - Version of Chamilo: 1.11.14
 - Version of PHP: 7.4

**Comment by christianbeeznest** [comment]
It is fixed with this PR :

https://github.com/chamilo/chamilo-lms/pull/3902/commits/a51f1fe67709813c016a94bac664b4aae569a497

**Comment by DrMickArtisan** [comment]
Ok, it works well, thanks !

DrMick
