### ISSUE TITLE
Bug Nuevo campo de usuario Formulario de Registro

### ISSUE THREAD

**Issue by chechitowon** [chamilo/chamilo-lms#3906]
**Describe**
Lo que quiero hacer es agregar un campo nuevo en el formulario de inscripción, un campo de tipo selección doble, donde al momento de seleccionar un departamento automáticamente se despliegue sus correspondientes municipios es un campo anidado, esto se puede realizar en:
**To Reproduce**
1) el menú de Administración/gestionar campos de usuarios.
2) añadir y seleccionamos tipo de campo: Campo de tipo selección doble
3) El Ejemplo no muestra que hay que agregar los valores de la siguiente manera: IBM:Eng;Analyst|Transifex:CEO donde al escoger IBM (padre) te mostrara su campo dependiente (hijos) que serian: Eng y Analyst, Asi como el padre seria Transifex y su hijo seria CEO
4) es por ello que yo agregue de la siguiente manera: La Paz: Murillo;Coroico|Cochabamba: Cercado; Villa Tunari

El problema es que solo me esta mostrando La Paz y Cochabamba que serian los departamentos y no asi sus campos dependientes que seria los municipios.....

Estoy con la ultima versión de Chamilo
![ConsultaCampoTipoSeleccionDoble](https://user-images.githubusercontent.com/25621501/121435958-bf0e9200-c94d-11eb-8cc3-2bb71cb05b35.JPG)

**Comment by ywarnier** [comment]
Prueba sin espacios entre "La Paz:" y "Murillo;" (y los demás). El formato de selección doble es muy sensible a los espacios.

**Comment by ywarnier** [comment]
Cerrando, después de verificar que la imagen de ejemplo muestra un ejemplo de formato a usar, que no incluye espacios.
