### ISSUE TITLE
Can I integrate a ReactJS web app with Chamilo through RestAPI 

### ISSUE THREAD

**Issue by shiddugmail** [chamilo/chamilo-lms#3907]
**Describe**
I want build a reactjs web App as front end for end user and use the Chamilo as backend. 

Is it possible, anyone has done already, please through some light. 

Thank you,
Regards,
Shiddu

**Comment by shiddugmail** [comment]
@NicoDucou Thank you very much for your response.  I will check it that's really helpful.
Sorry I saw your message so late.
 Thank you,
 Regards,
 Shiddu

**Comment by ywarnier** [comment]
Also, @shiddugmail, we are currently developing Chamilo 2.0 (master branch, still in development, release planned around early 2022) with native support for API Platform, a platform to provide access to most of the entities in Chamilo through different types of web services. So, for the current version of Chamilo (1.11.*), you should have a look at the main/webservices/ folder (in particular main/webservices/api/v2.php which is currently used by our mobile app at https://github.com/chamilo/mobile)

**Comment by shiddugmail** [comment]
> Also, @shiddugmail, we are currently developing Chamilo 2.0 (master branch, still in development, release planned around early 2022) with native support for API Platform, a platform to provide access to most of the entities in Chamilo through different types of web services. So, for the current version of Chamilo (1.11.*), you should have a look at the main/webservices/ folder (in particular main/webservices/api/v2.php which is currently used by our mobile app at https://github.com/chamilo/mobile) and for future versions it will be relatively different (although we might continue supporting the current REST API for a while, for compatibility reasons).

Thank you very much. I was held up with regular projects - so delay in replying.
