### ISSUE TITLE
Estadísticas genéricas de lecciones

### ISSUE THREAD

**Issue by gcamachoj** [chamilo/chamilo-lms#3910]
**Describe**
Agradezco si me pueden ayudar con este error en mis pruebas de la plataforma Chamilo:

Al entrar al listado de cursos, y y posteriormente a las estadisticas, el boton de "Estadisticas de lecciones", genera el error:

Fatal error: Uncaught ArgumentCountError: Too few arguments to function learnpath::getLpList(), 1 passed in C:\xampp\htdocs\learn\main\tracking\lp_report.php on line 23 and at least 2 expected in C:\xampp\htdocs\learn\main\lp\learnpath.class.php:12252 Stack trace: #0 C:\xampp\htdocs\learn\main\tracking\lp_report.php(23): learnpath::getLpList('1') #1 {main} thrown in C:\xampp\htdocs\learn\main\lp\learnpath.class.php on line 12252

**To Reproduce**
1. Go to 'Administracion '
2. Click on 'Cursos'
3. Scroll down to 'Seleccionar curso'
5. Clic en "Estadisticas de lecciones"

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
**Server
 - OS: [Windows10]
 - Version of Chamilo:  [e.g. 1.11.14]
 - Version of PHP: [7.4.19.]

**Additional context**
Tengo nociones básicas php, instalé xampp y sobre este luego instalé chamilo descargandolo de la pagina chamilo.org para realizar las pruebas.

**Comment by christianbeeznest** [comment]
Hola @gcamachoj 

El bug esta corregido en este ticket #3700 para la version 1.11.x
