### ISSUE TITLE
EmailMessage

### ISSUE THREAD

**Issue by Nellmat** [chamilo/chamilo-lms#3917]
Hey guys;
Can someone please help. my students whenever they receive an email from the chamilo portal, at the top there is a visible code

{ "@context": "http://schema.org", "@type": "EmailMessage", "description": "Chamilo Mail Notification", "potentialAction": { "@type": "ViewAction", "target": "" } }

**Comment by CamiloPerezOrtiz** [comment]
Hi @Nellmat 
You can edit the file to remove the text the file is in chamilo_1.11.x/main/template/default/mail/mail.tpl
![image](https://user-images.githubusercontent.com/41083269/125148134-c44e3080-e0f5-11eb-8ba5-e5089b22b078.png)

**Comment by ywarnier** [comment]
Thanks @CamiloPerezOrtiz for the answer. Seems like a good solution. It is likely the text shows because the mail client doesn't support ld+json. We should probably add an option in mail.conf.php to omit this header (which is useful in some contexts).

**Comment by ywarnier** [comment]
PR #4288 solves this (to be added to Chamilo 1.11.18)
