### ISSUE TITLE
Survey export to pdf error with open questions

### ISSUE THREAD

**Issue by DrMickArtisan** [chamilo/chamilo-lms#3920]
**Describe**
Error while exporting to pdf a survey global report. No pdf is created.

**To Reproduce**
1. Create a survey with at least one open type question. 
2. go to the Global report of the survey
3. Try to export to pdf
4. nothing happens

**Expected behavior**
A pdf report to download

**Screenshots**
 - Browser firefox 89.0.1
**Additional context**
Javascript console shows that error occurs in svg2pdf function : 
Uncaught (in promise) TypeError: element is null
In main/survey/reporting.php, line 194 we see :
` var svg = divs[i].querySelector("svg");
        svg2pdf(svg, pdf, {
              xOffset: 10,
              yOffset: positionY +  10,
              scale: 0.45
        });
`
Error occurs because  we're trying to read an svg element .. and there are no such element in open question answers !
A workaround will be to add a test on svg existence. 
`        var svg = divs[i].querySelector("svg");
        if (svg != null ) {
            svg2pdf(svg, pdf, {
                xOffset: 10,
                yOffset: positionY +  10,
                scale: 0.45
            });
        }
`
This allow pdf generation but this is not sufficient as answers to the question will not be displayed in pdf

**Comment by ywarnier** [comment]
Tried with FF 99 and Chromium 101. Cannot reproduce. Only one open question in the survey (also tried with one single choice question + one open, no problem either).
Could you provide us with more context and/or try to reproduce it on a common portal like https://11.chamilo.org/

![survey-global-report-pdf](https://user-images.githubusercontent.com/609839/166915952-0bd0d3ff-1c05-4165-802a-1cf75916d6b9.png)

**Comment by DrMickArtisan** [comment]
Hi,
I just create an example and run in the the same bug  :
https://11.chamilo.org/main/survey/reporting.php?cidReq=SURVEYTEST101&id_session=0&gidReq=0&gradebook=0&origin=&action=questionreport&survey_id=85&single_page=1

**Comment by ywarnier** [comment]
This seems to be a JS error in calling JSPDF. I get this in the JS console: 
```
Uncaught (in promise) Error: Invalid argument passed to jsPDF.scale
    at A.scale.A.__private__.scale (jspdf.umd.min.js:67:8439)
    at A.__private__.getHorizontalCoordinate (jspdf.umd.min.js:67:47616)
    at A.__private__.getHorizontalCoordinateString.A.getHorizontalCoordinateString (jspdf.umd.min.js:67:47855)
    at Object.v (jspdf.umd.min.js:96:4527)
    at t.addImage (jspdf.umd.min.js:96:7765)
    at reporting.php?cidReq=SURVEYTEST101&id_session=0&gidReq=0&gradebook=0&origin=&action=questionreport&survey_id=85:250:25
    at async exportToPdf (reporting.php?cidReq=SURVEYTEST101&id_session=0&gidReq=0&gradebook=0&origin=&action=questionreport&survey_id=85:247:13)

**Comment by AngelFQC** [comment]
Hi @DrMickArtisan 
Try to apply the last commit https://github.com/chamilo/chamilo-lms/commit/9c6c3381476da63ce36f5476aeb7bf658f60356a

**Comment by ywarnier** [comment]
Worked for me (I haven't updated 11.chamilo.org but I could reproduce the issue locally, and now it's gone).

**Comment by DrMickArtisan** [comment]
Ok, works for me locally, thanks !
