### ISSUE TITLE
Question: How to add meta for index.html

### ISSUE THREAD

**Issue by 22phuber** [chamilo/chamilo-lms#3923]
**Question**
How can i add `<meta name="robots" content="noindex, follow">` to the login index page?

Couldn't find any setting related to this in the `configuration.php` file.

Target version: Chamilo LMS v1.11.12

**Comment by 22phuber** [comment]
👋  Hello? Is there anybody out there?

**Comment by lonesomewalker** [comment]
Sorry, this is not the q&a section.
Github is for bugs or serious requests.

For questions only, maybe you get faster help here:
https://forum.chamilo.org/

**Comment by AngelFQC** [comment]
@22phuber Try installing the "No search index" plugin

**Comment by 22phuber** [comment]
Installed the plugin, but the `<meta name=​"robots" content=​"noindex">​` element is not in the `<head>` section where it should be regarding to https://www.w3schools.com/tags/tag_meta.asp and https://stackoverflow.com/questions/1447842/what-happens-if-the-meta-tags-are-present-in-the-document-body. This looks like a bug  to me. Also it appears two times 🤷‍♂️ .

![Bildschirmfoto 2021-07-30 um 14 29 16](https://user-images.githubusercontent.com/17426101/127653527-7afbda68-6087-4875-b1d0-3534a889a7ca.png)

**Comment by lonesomewalker** [comment]
Regarding that you offer services related to Chamilo (stoneageit.ch/dienstleistung/e-learning) you should be able to get this running yourself...

Otherwise use the forum or an official provider.

**Comment by 22phuber** [comment]
@lonesomewalker Wie bist du denn drauf. Ich habe hier nur gefragt ob es eine Lösung gibt und jetzt gesehen das es ein Bug gibt. Ich krieg dies schon zum laufen, das ist nicht das Problem.

**Comment by lonesomewalker** [comment]
Eigentlich gehe ich nicht auf Getrolle ein, aber:
erstens meckerst Du oben rum, das keiner antwortet.
Zweitens, ich nenne Dir ein Plugin, das Deine Anforderungen mit etwas Anpassung ermöglicht.
Drittens: für Kunden Services anbieten, diese aber nicht leisten können.

Schadet dem Projekt Chamilo.

So what?

**Comment by 22phuber** [comment]
Du musst neu sein.

**Comment by lonesomewalker** [comment]
https://media.giphy.com/media/VbbKTXH8zaJsQOkfau/giphy.gif als einer der offiziellen Provider glaube ich das dann eher doch nicht...
