### ISSUE TITLE
Error update error 1.11.8 a 1.11.14

### ISSUE THREAD

**Issue by gabynavarro** [chamilo/chamilo-lms#3930]
After updating, the following error occurred.
I can't change styles, they all throw the same error.
Every time I change style it doesn't show me the  #changes.
Don't edit any styles, I don't have plugins installed. 

php7.2,
server linux
 Help please

**Comment by gabynavarro** [comment]
hello I corrected the problem now I have the problem in the lesson template, the footer keeps appearing in the middle. I tried to change the css to fixed but it remains the same. Any help I would appreciate.
 <img src="http://escuela4054.com.ar/basura/imageChamilo.png" alt="">

**Comment by ywarnier** [comment]
This second issue has been reported by a few people already (you might find them scanning through the issues). We should be releasing 1.11.16 in a week or so, which should be fixing this issue (which happened as a side effect of the update to 1.11.14, sorry about that).

**Comment by ywarnier** [comment]
Here you go: #3861 
You will find a solution to that bar there
