### ISSUE TITLE
Line breaks (alignments) lost after editing document

### ISSUE THREAD

**Issue by mk111** [chamilo/chamilo-lms#3938]
**Describe**
if a piece of programming code is  part of an online document created with wysiwyg editor, alignment made with line breaks are lost on saving with (external) filtering. Any "code" entered in such a document becomes unreadable.

**To Reproduce**
create new document
use 'preformated' block and enter some code wtih line breaks etc ...
save document
view document : content should be ok (aligned, with line breaks
now edit such a document and save it again; alignments and line breaks are lost

**Expected behavior**
a would like to see my 'code' formated

**Additional context**
documents/edit_document.php contains a code for removing line breaks; in the same time create_document.php does not !

proposing change like in #3937

**Comment by ywarnier** [comment]
Change accepted and merged into Chamilo. Closing.
Thanks for submitting both the report and the fix.
