### ISSUE TITLE
Move session.id_coach + session.session_admin_id to session_rel_user

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#3949]
In 1.11.x, the session table contains id_coach (general coach) and session_admin_id (session admin), which limits to only one user  of each kind linked to the session.

Move those identifiers to the session_rel_user table with a specific status, so they can easily be obtained through the same queries as normal users and coaches.

**Comment by christianbeeznest** [comment]
Currently it is added those identifiers to the session_rel_user table with relation_type = 3 for coach_id and relation_type = 4 for session_admin_id, checked in code and migration.

**Comment by christianbeeznest** [comment]
It is added in this commit https://github.com/chamilo/chamilo-lms/commit/b965ee5b31c8e304dd18493cf8139f930cb3a9fc .
Tested and confirmed.
