### ISSUE TITLE
falla con los ccs

### ISSUE THREAD

**Issue by atorresa** [chamilo/chamilo-lms#3954]
**Describe el problema**
al parametrizar el chamilo, en el menu administracion/ hojas de estilo

sale en un cuadro rojo la leyenda 

/var/www/chamilo/www/app/Resources/public/css/themes/no se puede escribir

esto no me permite cambiar el logo  o actualizar las plantillas ccs

el servidor lo tengo en digital ocean en version 1.11.10

**Comment by ywarnier** [comment]
Hola @atorresa disculpa la demora en responder. Solo basta con cambiar los permisos de esta carpeta para que funcione. Si tu servidor web usa el usuario `www-data` para los permisos, haz lo siguiente:
```sudo chown -R www-data: /var/www/chamilo/www/app/Resources/public/css/themes/```
La funcionalidad de subida de estilos requiere acceso en escritura ahí y en la carpeta web/, pero se considera una posible vulnerabilidad poder subir archivos ahí, razón por la cual no recomendamos dejar este permiso siempre abierto.
