### ISSUE TITLE
Problema al importar evaluaciones del curso base en una sesión

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#3960]
**Describe el problema**
Al crear una sesión y agregar cursos existe la opción de importar las evaluaciones del curso base a la sesión.
La importación se realiza pero si las evaluaciones en el curso base tienen creadas categorías, éstas son ignoradas y se importan los diferentes ítems de evaluación pero sin categorías.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 11.chamilo.org
2. Crear nueva sesión desde la administración
3. En el paso de inscribir cursos en la sesión, elegir el curso denominado Pruebas SCORM (ya contiene evaluaciones con categorías) y marcar las opciones de importar tareas y evaluaciones desde el curso base
4. Acceder luego al curso desde la sesión, a la herramienta de evaluaciones, y comprobar que las categorías existentes en el curso base no se han creado aunque sí los ítems de evaluación con sus ponderaciones

**Comportamiento esperado**
Se deberían importar todos los elementos incluyendo las categorías y respetando la jerarquía de elementos dentro de cada categoría.

**Servidor
 - Versión de Chamilo:  1.11.16

**Contexto adicional**
En este curso hay creadas categorías en evaluaciones y se puede utilizar para las pruebas:
https://11.chamilo.org/courses/PRUEBASSCORM/index.php?id_session=0

Esta sesión se ha creado siguiendo los pasos descritos y se puede ver que no se han creado las categorías:
https://11.chamilo.org/courses/PRUEBASSCORM/index.php?id_session=108

**Comment by christianbeeznest** [comment]
Corregido en este PR https://github.com/chamilo/chamilo-lms/pull/4261

**Comment by ywarnier** [comment]
> Corregido en este PR #4261

Tested, reviewed and merged.
