### ISSUE TITLE
AYUDA - email de bienvenida chamilo - error URL's

### ISSUE THREAD

**Issue by tharseo** [chamilo/chamilo-lms#3966]
![image](https://user-images.githubusercontent.com/90417150/132746378-ce29d2d7-8312-4931-9c6a-be931bfa625f.png)
Me pueden ayudar a corregir este error? en vez de que imprima: 'https://localhost', necesito que figure el link de mi plataforma de Chamilo. No encuentro que configuración cambiar para corregir este problema.

**Comment by NicoDucou** [comment]
Hola

Es probable que tu configuracion en app/config/configuration.php no este correcta.
En especial revisa esta configuration :
`$_configuration['root_web'] = 'http://localhost';`
No deberia ser localhost pero tu dominio.

Saludos

**Comment by ywarnier** [comment]
Falta de reacción. Cerrando.
