### ISSUE TITLE
Different number of user between class administration and class in group tool in a course BT#19091

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#3967]
in main/admin/usergroups.php the number of user in the class is correct.
in main/user/class.php

The problem is that in main/user/class.php it takes all the registry of usergroup_rel_user even if relation_type = 4.
This relation type 4 correspond to GROUP_USER_PERMISSION_PENDING_INVITATION_SENT_BY_USER which correspond to a closed social group in which the user has requested its inscription.
So this relation type 4 should not exist in a class context.

Since there should not be any registry with relation_type = 4 for usergroup of type class group_type = 0 then we can remove all the incorrect registry with :

`delete from usergroup_rel_user where relation_type = 4 and usergroup_id in (select id from usergroup where group_type = 0);`

So we did not find the origin of the problem but it was solve like this.

**Comment by christianbeeznest** [comment]
Fixed in this PR https://github.com/chamilo/chamilo-lms/pull/4260
