### ISSUE TITLE
competencias si hacer ningún curso

### ISSUE THREAD

**Issue by chatitosky** [chamilo/chamilo-lms#3969]
en la actualizacion que hicimos de nuestra plataforma de pruebas, detectamos una curiosidad que antes no aparecía:

en la version de chamilo 1.11.16 que actualizamos, los usuarios que recién se inscriben en la plataforma, el sistema los marca con competencias que ya tenemos definidas, sin estar en ningún curso.
al ver el curso, marcaba uno en especial, (fisiología clínica) que no tenía marcada ninguna competencia a desarrollar, y chamilo le asignaba hasta 3 competencias a los usuarios que recién se inscribían.
borramos el curso marcado solo para ver que ocurría y de nuevo, volvían a aparecer las competencias en los usuarios que se iban inscribiendo, ahora de otro curso que tampoco tiene asignada competencias a desarrollar.

no pudimos encontrar la causa.
¿como borrar la competencia del usuario?, aunque no lo recomiendo, si no sabes como hacerlo, se tiene que tocar la base de datos mysql en la tabla skill_rel__user y ver el id_user en su número para borrar la competencia asignada.

deshabilitamos la herramienta de competencias, aún volviéndola a activar, de nuevo muestra ese comportamiento con los usuarios que se van inscribiendo, no encontramos la causa.

si tienen alguna idea sobre que comportamiento tiene esta asignación de competencias, sin hacer ningún curso, o de donde proviene, para corregirlo en nuestra plataforma de pruebas, antes de ponerlo en la de desarrollo.
muchas gracias

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.10
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: Linux Ubuntu 18.10
 - Version of Chamilo:  1.11.16
 - Version of PHP: 7.2.

**Comment by ywarnier** [comment]
No me suena a nada conocido este error. Habéis hecho alguna modificación en su plataforma anteriormente, o es el puro Chamilo?
