### ISSUE TITLE
Imported courses document links and tests not working

### ISSUE THREAD

**Issue by RoagAcademy** [chamilo/chamilo-lms#3981]
**Describe**
Im on Chamilo 1.11.16.
1. I started a new course on a new installation on a new site(first time usage on a new installation on a new server)
2. I imported a complete course  from a backup, working correctly on Chamilo 1.11.8.(backed up as a full course)
3. All seems to be imported: When i go to individual menus like documents, tets etc, all is there: learning paths, documents, tests, test questions, assignments etc
4. But 
 a. when I go into the learning path, and i go to a test within the learning path and click "start" it gives me a pink block error: There are no questions for this exercise. and Sorry, you are not allowed to access this page, or maybe your connection has expired. Please click your browser's "Back" button or follow the link below to return to the previous page. Yet under tests the test and questions are there
**Screenshots**
![image](https://user-images.githubusercontent.com/90917520/133802028-a1453e7b-338e-474f-9e5d-9b8ca882ebf3.png)

b. Also when I click on a pdf link within an assignment, in my learning path, although the document is on the server it gives me a 500error. But if i load the document as direct part of the learning path, it displays correctly.(in other words: the assignment in the learning path will say something like "download your assignment papers HERE" where the word here got a link to the papers(pdf).
**Screenshots**
![image](https://user-images.githubusercontent.com/90917520/133801861-b9fce3df-af2b-425c-91a2-50844c369e6d.png)

**Comment by stefleininger** [comment]
Yes !!! there is a issue with import function since version 1.11.16. Someone can work on that ?

**Comment by abelpz** [comment]
I have the same issue.

**Comment by ywarnier** [comment]
@stefleininger Is this specific to version 1.11.16?

**Comment by RoagAcademy** [comment]
Not sure about other versions, I opened a new campus and install the newest download 1.11.16

**Comment by stefleininger** [comment]
I've found how to correct the issue but I don't remember where !!!
I'll try to give you the changes quickly.

**Comment by stefleininger** [comment]
In file /src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php :

Line 1845 : 
`if (!in_array('id', $columns)) {` to `if (!in_array('id', array_keys($columns))) {`

Line 2029 :
`if ($new_id && $idColumn) {						
                $sql = "UPDATE $table_que SET id = iid WHERE iid = $new_id";
                Database::query($sql);		 
            } else {															  
                return 0;
            }` to `if ($new_id) {
                // If the ID column is still present, update it, otherwise just
                // continue
                if ($idColumn) {
                    $sql = "UPDATE $table_que SET id = iid WHERE iid = $new_id";
                    Database::query($sql);
                }
            } else {
            	// If no IID was generated, stop right there and return 0
                return 0;
            }`

In file /src/Chamilo/CourseBundle/Component/CourseCopy/CourseRestorer.php :

Line 954 :
`WHERE question_id = {$obj->id}";` to `WHERE question_id = {$obj->iid}";`

Line 1045 :
`$sql = 'SELECT * FROM '.$table_ans.' WHERE question_id = '.$obj->id;` to `$sql = 'SELECT * FROM '.$table_ans.' WHERE question_id = '.$obj->iid;`

**Comment by Bavarianspirit** [comment]
Second file is CourseBuilder.php

**Comment by ywarnier** [comment]
Thanks @Bavarianspirit

**Comment by gastonlaga** [comment]
I've got the same issue on my two Chamilos: 1.11.14 (schoolserver) and 1.11.16 (local installation). In both cases scorm course backups are empty and I get the same error message as described above by [RoagAcademy].  Same issue with Exercices backups: empty too.  On my two Chamilos backups contain only files such as doc. pdf. pnp jpf and also all the names of scorm or exercices - but no scorm and no exercices.

**Comment by ywarnier** [comment]
@gastonlaga did you get a chance to test the latest changes in the history above ? If not, you will have to wait for version 1.11.18 to be released to try it out.

**Comment by ywarnier** [comment]
Just to be clear before closing this issue: those changes above were all added by our team to Chamilo after 1.11.16. The code was already included in what will become 1.11.18. Thanks @stefleininger for specifying the exact code excerpts necessary to patch 1.11.16 installs.
The corresponding commits are:
- https://github.com/chamilo/chamilo-lms/commit/d3e4b92890a608adfeca1093332a6a94a1881cea
- https://github.com/chamilo/chamilo-lms/commit/dc4d2b7f39a226f34a492b10a10deec95b8f8ba4
- https://github.com/chamilo/chamilo-lms/commit/38432d1e303f93ebf9510bee45a5e0e0cee3895d
