### ISSUE TITLE
PLUGINS ZOOM - VARIAS REUNIONES

### ISSUE THREAD

**Issue by miguelon1234** [chamilo/chamilo-lms#3985]
Buenos días.
Soy Miguel Angel, de PERÚ.
Quisiera hacer una consulta, sobre el plugin de ZOOM en chamilo.
Quisiera saber si es posible manejar más de una cuenta ZOOM con el mismo plugin. De ser posible esto, ¿Qué configuración se tendría que hacer?
Hago esta consulta, porque en los colegios, hay varias aulas abiertas simultáneamente, y el plugins solo gestiona una cuenta a la vez.
O existe un plugin de terceros que maneje mas de una cuenta zoom?

Saludos.
Miguel Angel.

**Comment by ywarnier** [comment]
Hola Miguel Angel,
Deberías hacer tu pregunta en el foro de Chamilo. Aquí es un espacio para reportar bugs o solicitar el desarrollo de nuevas funcionalidades.
El plugin Zoom funciona con *una* cuenta Zoom que tiene una suscripción que permite varias aulas (rooms) como tienes aquí: https://zoom.us/pricing/zoom-rooms
En efecto, las cuentas gratuitas no permiten hacer una gestión automatizadas a partir de un portal como Chamilo. Simplemente no permiten el control por otra herramienta, ni el uso de varias salas.
Si buscas una solución más económica, quizás deberías mirar más hacia BigBlueButton. Algunos proveedores como https://www.mynaparrot.com/packages te permite tener tu propio servicio de videoconferencia y conectarlo con el plugin BigBlueButton para armar una cantidad ilimitada de salas (solo te limita la cantidad de usuarios simultáneos según el plan elegido).
