### ISSUE TITLE
CSS file can not be imported (form action incorrect)

### ISSUE THREAD

**Issue by DrMickArtisan** [chamilo/chamilo-lms#3988]
**Describe**
Css file cannot be imported, because action url in the form is incorrect

**To Reproduce**
1. Go to main/admin/settings.php?category=Stylesheets
2. Choose a file, name the new css style
3. click on "import file" button
4. page is now redirected to main/admin/admin/settings.php?category=Stylesheets and nothing happens.

**Expected behavior**
page redirected to main/admin/settings.php?category=Stylesheets and new stylesheet file imported

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo: 1.11.16
 - Version of PHP: 7.4.23

**Additional context**
The bug is in main/admin/settings.lib.php, line 400 : 
        api_get_path().'admin/settings.php?category=Stylesheets#tabs-3'
should be 
        api_get_path().'settings.php?category=Stylesheets#tabs-3'

**Comment by NicoDucou** [comment]
Hi @DrMickArtisan 
This already fixed with commit e07f106124aa5090167ef8a916174682c24eb2ed
Also an other error appeared once this first error was corrected and it was fixed in issue #3975
So I'm closing this issue
Best regards
