### ISSUE TITLE
ERROR EN MIGRAR RESULTADOS DE EVALUACIONES DE ALUMNOS  

### ISSUE THREAD

**Issue by Royer17** [chamilo/chamilo-lms#4005]
HICE UNA MIGRACION DE CHAMILO 1.9.X A 1.11.16 . 
AL MOMENTO DE MIGRAR LOS RESULTADOS DE LAS EVALUACIONES NO FIGURAN EN LA ACTUALIZACION 

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a versión CHAMILO 1.9.10.2 -- CREAR CURSO -- CREAR EVALUACION - ALUMNO COMPLETA EVALUACION ( 2 intentos ) nota , figura en informes de alumno  que completo las tareas imagen :  https://prnt.sc/1u4xo3y
2. actualizar versión 1.11.16 ( renombrar carpetas newscorm y exercice -> newcorm_old y execicce_old ,se crean las carpetas por defecto lp y exercise)
3. despues de actualizar  ; ir a informes de alumno imagen despues de actualizar : https://prnt.sc/1u4ya9c
4. Error es que no figuran las evaluaciones como estaba en la version anterior 

**Comportamiento esperado**
Se visualice las evaluaciones correctamente 

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.
https://prnt.sc/1u4xo3y   --- antes de actualizar (v 1.9.10.2)
https://prnt.sc/1u4ya9c  ---- despues de actualizar (v 1.11.16) 

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : SO: ‪CentOS 6.9 ‬  Producto: Plesk Obsidian 18.0.31 
 - Navegador  chrome Versión 94.0.4606.61 

**Servidor
 - Sistema operativo : ‪CentOS 6.9 
 - Versión de Chamilo:  1.11.16
 - Versión de PHP:7.3 

**Contexto adicional**
SERVIDOR DEDICADO PLESK

**Comment by ywarnier** [comment]
Hola @Royer17 
No se si viste la nota en la guía de instalación de Chamilo y en el changelog, pero si es que actualizas desde una versión anterior a 1.11.0, hay que correr un script (puesto a disposición). La información está aquí: https://11.chamilo.org/documentation/installation_guide.html#3._Upgrade

**Comment by Royer17** [comment]
hola, lo acabo de agregar fix_quiz_id_to_iid.php a la ruta : ..main/inc/ 
y sigue el mismo problema

**Comment by Royer17** [comment]
SOLUCIONADO .... GRACIAS
