### ISSUE TITLE
No guarda tiempo de lección SCORM

### ISSUE THREAD

**Issue by EsMapachito** [chamilo/chamilo-lms#4008]
### Current behavior / Resultado actual / Résultat actuel: 

En las lecciones SCORM si haces clic en la flecha para volver atrás del navegador o cierras la pestaña, no guarda el tiempo de lección. Si cierras la pestaña de la lección tampoco guarda el tiempo. Sólo se guarda el tiempo que has permanecido en la lección si haces clic en el icono casa (home).

### Expected behavior / Resultado esperado / Résultat attendu: 

Se guarde y actualice indistintamente si interactua el alumno con el botón home o no (cron tab o algo así)

### Steps to reproduce / Pasos para reproducir / Étapes pour reproduire: 

Explicados en resultado actual.

### Chamilo Version / Versión de Chamilo / Version de Chamilo: 

1.11.12

**Comment by ywarnier** [comment]
La versión 1.11.16 mejora este comportamiento, que ha sido alterado por las nuevas versiones de Chrome. Te recomiendo actualizar tu versión, siguiendo el manual de actualización de Chamilo en la carpeta /documentation/ de tu paquete Chamilo 1.11.16.
