### ISSUE TITLE
Convert %s or support them in Vue.js

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4012]
In Chamilo 1, language variables with a variable inside (like "Student `%s` has handed an assignment out") are dealt with through sprintf() and there's a wrapper for that in our Twig functions.

In Chamilo 2, we started using Vue.js, which offers an i18n $t() function to translate strings, but it expects named (not ordered) variables. https://kazupon.github.io/vue-i18n/guide/formatting.html#named-formatting

Find a way to either:
- convert all Chamilo strings to named variables
- develop a named formatting modifier that supports ordered variables with `%s` rather than named variables

**Comment by christianbeeznest** [comment]
Currently is possible to do interpolation with vue-I18n , https://vue-i18n.intlify.dev/guide/essentials/syntax.html#list-interpolation
