### ISSUE TITLE
¿Es posible crear un nuevo question type personalizado desde un plugin?

### ISSUE THREAD

**Issue by abelpz** [chamilo/chamilo-lms#4048]
Estoy pensando en añadir algunos nuevos question types personalizados y tal vez hacer esto a través de un plugin para la versión 1.11.x. Pero antes, me gustaría saber ¿Es posible crear estos nuevos question types a través de un plugin, sin modificar los archivos base de Chamilo?

**Comment by ywarnier** [comment]
Hola @abelpz 
Probablemente sea factible pero para el caso particular de los tipos de preguntas, no lo haría a través de un plugin sino directamente dentro del código (en tu fork, claro) core de Chamilo.
La razón por eso es que agregar un nuevo tipo de pregunta es *relativamente* sencillo. Existen muchos ejemplos, los nuevos tipos solo requieren añadir archivos y una constante (+un icono), y se pueden gestionar de manera totalmente integrada. Además, la estructura de plugins no está hecha para este *tipo* de extensión a Chamilo.
Te recomiendo mirar el reciente cambio enviado aquí, que agrega un nuevo tipo: https://github.com/chamilo/chamilo-lms/commit/8832ddb09bddcb7e7a0c2f9b58ee77faa9ab8920#diff-0d6e4079e36703ebd37c00722f5891d28b0e2811dc114b129215123adcce3605 (file-upload) o este (mucho más antiguo): https://github.com/chamilo/chamilo-lms/commit/a1c4c6fe62c53f39717d485cb7d4b816f3f62355

Ya verás que se añade una clase, una constante, se modifican unos 3-4 archivos y ya está...
