### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by marshel** [chamilo/chamilo-lms#4051]
**Is your feature request related to a problem? Please describe.**
As a worker in elearning industry, there is a trend in gamification and there is no support or plugin in Chamilo.

**Describe the solution you'd like**
As the user progress thru the leaning paths, each of these itens should reward points and 'coins'. Points for completing/accessing the content and coins as a reward for good performance.
The points are used as to measure content consumption and as a stimulus for reaching 'levels' like a role playng game and/or acquiring competency badges.
Coins may be used as a exchange for access new courses/sessions or as currency on a "reward shop" that may contain physical itens or digital assets.

**Additional context**
I see at developer level, a new db field on lp_item for coins and points, a user point and coin field in logs as a registry, or a new table for this, some admin dashboard for setting the configs, a admin page for setting the store itens and its costs, a user area for a highscore section, a reward store area for the user to exchange its prizes.

On the future more grannularity could be given: rewards on the number of forum posts per week, on exercises, number of weekly logins, etc

**Comment by ywarnier** [comment]
Hi @marshel 
There is already a gamification feature, but it is somewhat incomplete and tricky to activate (sorry about that, we work on so many things it's difficult to do everything perfectly).
Let me show you:
![gamification](https://user-images.githubusercontent.com/609839/141318048-4e76878b-4e66-4856-bb2a-2e18db54d6d2.png)
Then:
![gamification2](https://user-images.githubusercontent.com/609839/141318066-86f7d4fb-8561-43e3-8816-c460847c8da0.png)
Then:
![gamification3](https://user-images.githubusercontent.com/609839/141318080-25cf7e25-a65d-40cd-8cac-6bbc567213d8.png)

The rules are fixed and are a bit complex for it to work and allow you to get 4 stars:
* 3 chapters
* 1 test per chapter
* complete the 3 chapters to get 3 starts
* if you get more than (I think it's) 80% to all the tests, you get 4 stars

There is also some code that checks if there is an extra field for the lp_item (I think it's called "points" or something like that) and accumulate points when you finish each item. You'll have to scan the code for "extra" (extra fields) in the main/lp/ folder to get to the bottom of that.

At the global level, I think there is no page where you can see your total score yet, but this would be relatively easy to implement, if you would like to contribute that part.

**Comment by marshel** [comment]
Just passing to thank you for your answer. 
I still need to learn more about developing, but maybe I will try, something  at least ;)

Best regards !
