### ISSUE TITLE
chamilo mail.conf sans smtp_secure

### ISSUE THREAD

**Issue by french225** [chamilo/chamilo-lms#4052]
**Bonjour à tous j'espère que vous allez bien.
J'utilise chamilo 1.11.16 et je fais usage d'un smtp pour l'envoi de mail. Ce smtp utilise authentification (usr et pwd) mais pas de connexion secure (ni ssl ni tls). Alors dans mon mail.conf je remplis toutes les infos mais je laisse smtp_secure vide ce qui rend l'appli dysfonctionnelle parce que les mails ne vont pas et si il s'agit d'envoi de mail ça crash. Quelles modifications puis je faire svp pour que chamilo annule smtp_secure  afin que je puisse l'utiliser sans smtp_secure qui me semble obligatoir dans chamilo en cas d'authentification ?

merci d'avance je suis entièrement dependant de vous.**

**Comment by ywarnier** [comment]
Très bonne question @french225 
Il suffit en fait de mettre la ligne en commentaire dans mail.conf.php comme ceci:
```
///$platform_email['SMTP_SECURE'] = 'tls';
```
D'après le code (dans main/inc/lib/api.lib.php), l'utilisation de cette variable se fait uniquement si elle est définie:
```
        if (isset($platform_email['SMTP_SECURE'])) {
            $mail->SMTPSecure = $platform_email['SMTP_SECURE'];
        }
```
Donc si elle est en commentaire, SMTPSecure ne sera pas défini.

**Comment by french225** [comment]
Bonjour monsieur désolé pour le retard mais j'ai fais la modification et cela ne fonctionne toujours pas

**Comment by ywarnier** [comment]
Bonjour @french225 est-ce qu'en mettant SMTP_DEBUG à 1 et en suivant les logs de PHP (habituellement eux-mêmes dans les logs d'Apache si c'est le serveur web utilisé), tu vois un message intéressant concernant SMTP secure?

Parce que c'est vraiment le seul endroit dans Chamilo où on l'utilise, et par défaut il est désactivé... (donc s'il n'est pas défini dans mail.conf.php, aucune chance qu'il s'active lors de la communication SMTP).

Donc soit l'hébergeur du serveur de mails renvoie une erreur et celle-ci devrait apparaître dans les logs, soit il faudra utiliser un autre serveur de mails.
Il y a aussi une possibilité que ce paramètre n'ait pas été pris en compte encore si le serveur web utilise du caching (par exemple `PHP opcache`), mais les chances sont relativement limitées.

**Comment by french225** [comment]
Bonjour monsieur,
J'utilise le serveur web nginx. et dans error_log j'ai juste le message "can't send mail because of smtp connect failed" et apres plusieurs tests. j'ai pu costater que le probleme est certainement avec smtp secure. je precise que j'ai deja testsé avec un autre serveur qui utilise tls  et ca a tres bien fonctionné. mais je suis contrain à le faire fonctionner sur le serveur smtp qui malheureusement me pose probleme à cause de sa configuration(auth sans securité). Ce serveur appartient à l'entreprise demandeuse et ne changera pas la config pour moi.

**Comment by ywarnier** [comment]
Normalement avec le SMTP_DEBUG activé, il devrait donner un peu + d'information. Si vraiment rien, alors il faudra chercher un peu sur internet autour de la librairie PHPMailer (que nous utilisons) et du message d'erreur qui est affiché. Je n'ai pas d'autre solution (ou alors partir sur un contrat de support avec un des fournisseurs de Chamilo pour qu'il solutionne le problème à votre place). Ce n'est a priori pas un problème de Chamilo directement.

**Comment by french225** [comment]
Bonjour monsieur,
merci pour vos suggestions. je vous ferai un retour sur mes investigations. Bien entendu si elles aboutissent. Cependant, comment puis je joindre l'equipe chamilo facilement ?

**Comment by ywarnier** [comment]
L'équipe de développement de Chamilo, par ici.
Pour les questions (pas les bugs), c'est sur le https://forum.chamilo.org.
Les fournisseurs officiels de services (l'association Chamilo ne fournissant pas de services) sont listés ici: https://chamilo.org/fr/fournisseurs/ (il y a une adresse générique pour les contacter).

**Comment by french225** [comment]
merci monsieur

Le mer. 24 nov. 2021 à 23:24, Yannick Warnier ***@***.***> a
écrit :
