### ISSUE TITLE
No puedo cambiar de leccion

### ISSUE THREAD

**Issue by jusuy4** [chamilo/chamilo-lms#4054]
No puedo navegar entre lecciones.
Hago clic en la siguiente leccion pero solo vuelve a aparecer la leccion anterior en el visualizador.
Podrian ayudarme?
La version de Chamilo es la: 1.11.10
Saludos!

**Comment by ywarnier** [comment]
Hola @jusuy4,

La cantidad de detalles que provees no es suficiente para ayudarte. No hemos tenido reportes anteriores de este problema, y tu versión está relativamente desactualizada (mayo del 2019), por lo que ya no tiene mucho tiempo para nosotros dedicarle tiempo.
Te sugiero reportar este problema en el foro de Chamilo: https://forum.chamilo.org/
