### ISSUE TITLE
Unable to delete permanently notices from Homepage Portal News

### ISSUE THREAD

**Issue by kemoche** [chamilo/chamilo-lms#4065]
We created 2 student lists on the homepage which we delete later BUT have been unable to delete the list and deny access to the created URLs.
URLs
https://miconline.ac.ke/index.php?include=CLASS-1-LIST_english.html
https://miconline.ac.ke/index.php?include=CLASS-2-LIST_english.html
https://miconline.ac.ke/index.php?include=Q3-CLS-3_english.html
https://miconline.ac.ke/index.php?include=Q3-CLS-4_english.html

1. The class lists were deleted from the homepage in Dec 2020.
2. When one types the class lists URLs and or searches via google, one has access to the published class lists.
3. I have deleted the URL ref from the DB - track_e_default
4. I have tried to bar or redirect the URLs access via .htaccess directives as below but in vain.
---------
a. <files index.php?include=Q3-CLS-3_english.html>
        # set up rule order
         order deny,allow
         # default deny
        deny from all
      </files>
b. RewriteRule ^index.php?include=Q3-CLS-3_english.html$ - [F]
c. RewriteRule ^/([^/]+)/?$ include=Q3-CLS-3_english.html?cDir=$1 [QSA,L]
d. Redirect 301 "/old_url.html" "/new_url.html"
----------------
5. Cleared the cache from the Administrators end -> Cleanup of cache and temporary files
6. Have searched the DB and can't find the page created

Kindly assist on how I can pull down these pages...

**Comment by ywarnier** [comment]
This part of the software (the index.php?inclure=...) look for HTML files written in app/home/[possibly-a-subdirectory]/[files].html, so by looking into that folder, you should find what you need and be able to delete them manually.
The rest is .htaccess/Apache rewrite configuration stuff I won't get into (not our responsibility as Chamilo software).

**Comment by kemoche** [comment]
Thanks - it's worked.
The .htaccess that I can sort out.
Cheers

**Comment by ywarnier** [comment]
It is likely that, when you tried to remove the documents from the Chamilo interface, the permissions on those files had changed since creation and Chamilo was unable to delete them, or that you created them in several languages and only removed them in one. Usually, this feature works without issues.
