### ISSUE TITLE
Peformance problem when downloading a folder

### ISSUE THREAD

**Issue by noeldieschburg** [chamilo/chamilo-lms#4083]
**Describe**
When a folder is downloaded, there is a big performance problem. a 900M with 100 files folder is enough to put down a modern server with web file on nfs. (chamilo 1.11)

**To Reproduce**
1. Go to Document
2. Click on download folder (with a pretty big folder)
3. It then works a lot and the server load goes up. Mainly io wait.

What happens there is that he pclzip->add function is called for every file in downloadfolder.inc.php. 

This function actually does the following: 

* create zip file or opens an already exisiting one
* copy the the whole zip file into a app/cacje/pclXXXX.tmp file 
* add the file
* copyback the tmp file to zip file
* rm .tmp file 
* close zip
This makes logically lots of io. 

Here is a patch that fixes that. It works fine (no more load and more than 10 times quicker on 900M and ~100 files folder ) for me but maybe I missed something, please check : 

<pre>
diff --git a/main/document/downloadfolder.inc.php b/main/document/downloadfolder.inc.php
index 8d1585495a..cbe54c976c 100755
--- a/main/document/downloadfolder.inc.php
+++ b/main/document/downloadfolder.inc.php
@@ -122,6 +122,8 @@ if (!empty($groupId)) {
     $groupCondition = " (props.to_group_id = 0 OR props.to_group_id IS NULL ) ";
 }

+$filesToZip=[];
+
 // Admins are allowed to download invisible files
 if (api_is_allowed_to_edit()) {
     // Set the path that will be used in the query
@@ -175,14 +177,15 @@ if (api_is_allowed_to_edit()) {
                 }
             }
         }
+       $filesToZip[]= $sysCoursePath.$courseInfo['path'].'/document'.$not_deleted_file['path'];
+    }
         $zip->add(
-            $sysCoursePath.$courseInfo['path'].'/document'.$not_deleted_file['path'],
+            $filesToZip,
             PCLZIP_OPT_REMOVE_PATH,
             $sysCoursePath.$courseInfo['path'].'/document'.$remove_dir,
             PCLZIP_CB_PRE_ADD,
             'fixDocumentNameCallback'
         );
-    }

     Session::erase('doc_files_to_download');
 } else {
@@ -294,14 +297,15 @@ if (api_is_allowed_to_edit()) {

     // Add all files in our final array to the zipfile
     for ($i = 0; $i < count($files_for_zipfile); $i++) {
+       $filesToZip[] = $sysCoursePath.$courseInfo['path'].'/document'.$files_for_zipfile[$i];
+    }
         $zip->add(
-            $sysCoursePath.$courseInfo['path'].'/document'.$files_for_zipfile[$i],
+            $filesToZip,
             PCLZIP_OPT_REMOVE_PATH,
             $sysCoursePath.$courseInfo['path'].'/document'.$remove_dir,
             PCLZIP_CB_PRE_ADD,
             'fixDocumentNameCallback'
         );
-    }
     Session::erase('doc_files_to_download');
 }
</pre>

**Comment by ywarnier** [comment]
PR applied. Thanks.
