### ISSUE TITLE
Enabling Sell Courses Plugin TINYINT Error

### ISSUE THREAD

**Issue by landNull** [chamilo/chamilo-lms#4098]
Fatal error: Uncaught Error: Undefined class constant 'TINYINT' in /var/www/staredu/plugin/buycourses/database.php:450 Stack trace: #0 /var/www/staredu/plugin/buycourses/src/buy_course_plugin.class.php(168): require_once() #1 /var/www/staredu/plugin/buycourses/install.php(16): BuyCoursesPlugin->install() #2 /var/www/staredu/main/inc/lib/plugin.lib.php(321): require('/var/www/stared...') #3 /var/www/staredu/main/admin/settings.lib.php(943): AppPlugin->install('buycourses') #4 /var/www/staredu/main/admin/settings.lib.php(226): storePlugins() #5 /var/www/staredu/main/admin/settings.php(472): handlePlugins() #6 {main} thrown in /var/www/staredu/plugin/buycourses/database.php on line 450

**To Reproduce**
1. Go to Plugins'
2. Click on 'Sell courses'
3. Click on "Enable the selected plugins''

**Expected behavior**
Sell Courses plugin to enable without errors

**Desktop**
 - OS: Linux Manjaro
 - Browser Brave Version 1.32.113 Chromium: 96.0.4664.45

**Server**
 - OS: Debian 9
 - Version of Chamilo: LMS 1.11.16
 - Version of PHP: 7.3

![Screenshot from 2021-12-09 20-08-13](https://user-images.githubusercontent.com/61285223/145516148-1a7f2310-a5ec-4060-bed2-46716be95041.png)

**Comment by landNull** [comment]
Update:
This seems to be an issue with php7.3's TINYINT support, perhaps.
I edited database.php line 450 from TINYINT to SMALLINT Sell courses enables without errors.

**Comment by NicoDucou** [comment]
Just to indicate that this was fixed in Chamilo on the 23rd of september with commit https://github.com/chamilo/chamilo-lms/commit/e87dfc557414639d910fb56ee4f07d4decefcfe4

So it will be alright in the next version of Chamilo
