### ISSUE TITLE
Error al importar ejercicios de un curso 

### ISSUE THREAD

**Issue by Royer17** [chamilo/chamilo-lms#4106]
Hola, ERROR AL IMPORTAR EJERCICIOS DE UN CURSO 
obtuve un qti2_export_<number>.zip

**REPRODUCIR ERROR**

1. Me dirigo a un curso " x "  
2. Al exportar el archivo ZIP 
3. Al importar el archivo ZIP me sale el siguiente error 500 en la pagina 
4. dentro de mi servidor en error_log = "  mod_fcgid: stderr: #4 /var/www/vhosts/DOMAIN.com/campu in /var/www/vhosts/DOMAIN.COM/vendor/symfony/dom-crawler/Crawler.php on line 1301, referer: https://domain.com/main/exercise/qti2.php?cidReq=MATPELINIVELADVERTENCIA&id_session=0&gidReq=0&gradebook=0&origin= " 

*esperado**
se espera que importe con exito los ejercicios y preguntas con respuestas 

**Screenshots**

**Server
 - OS: CENTOS VPS - PLESK 
 - Version of Chamilo: 1.11.16
 - Version of PHP: 7.3

**Comment by Royer17** [comment]
hice un composer update y se arreglo ... y como tenia php 7.3  https://newbedev.com/php-composer-detected-issues-in-your-platform-your-composer-dependencies-require-a-php-version-7-4-0-you-are-running-code-example ... hacer esto

**Comment by NicoDucou** [comment]
Thank you for indicating the solution you found to your problem.
