### ISSUE TITLE
Fatal error: in agenda reminders

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#4116]
With OS: Linux Ubuntu 20.04
Version of Chamilo chamilo-lms-1.11.x 23-12-2020
Version of PHP: 7.3
and modified files refs BT # 19392 from AngelFQC

I get this error and the event is not saved:
Fatal error: Uncaught Doctrine \\ ORM \\ Mapping \\ MappingException: Class "Chamilo \\ CoreBundle \\ Entity \\ AgendaReminder" is not a valid entity or mapped super class. in /var/www/html/test/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/MappingException.php:348\nStack trace: \ n # 0 / var / www / html / test / vendor / doctrine / orm / lib / Doctrine / ORM / Mapping / Driver / AnnotationDriver.php (95): Doctrine \\ ORM \\ Mapping \\ MappingException :: classIsNotAValidEntityOrMappedSuperClass ('Chamilo \\\\ CoreBun ...') \ n # 1 / var / www / html / test / vendor / doctrine / orm / lib / Doctrine / ORM / Mapping / ClassMetadataFactory.php (155): Doctrine \\ ORM \\ Mapping \\ Driver \\ AnnotationDriver-> loadMetadataForClass ('Chamilo \\ \\ CoreBun ... ', Object (Doctrine \\ ORM \\ Mapping \\ ClassMetadata)) \ n # 2 / var / www / html / test / vendor / doctrine / persistence / lib / Doctrine / Persistence / Mapping / AbstractClassMetadataFactory .php (306): Doctrine \\ ORM \\ Mapping \\ ClassMetadataFactory-> doLoadMetadata (Object (Doctrine \\ ORM \\ Mapping \\ ClassMetadata), NULL, false, Array) \ n # 3 / var / www / html /test/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php(82): D in / var / www / html / test / vendor / doctrine / orm / lib / Doctrine / ORM / Mapping / MappingException .php on l ine 348, referer: https://test.ticformation.ca/main/calendar/agenda_js.php?type=course&cidReq=TESTOOGI&id_session=0&gidReq=0&gradebook=0&origin=

**Comment by andreboivin** [comment]
![reminder](https://user-images.githubusercontent.com/22802716/147583895-0d2614b0-82aa-44a4-90e2-281310599076.jpg)

**Comment by NicoDucou** [comment]
Hi @andreboivin 
I can not reproduce this Fatal error  with an uptodate 1.11.x Chamilo
Can you indicate what I need to do to reproduce it ?
For the image it is just the translation that is wrong. There is nothing supposed to appear where you pointed the arrow.
In english the original translation is "before". The idea is to indicate that it is in you case 1 day before that the notification will be sent. So in french it should be 1 jour avant (without "le")

Best regards

**Comment by NicoDucou** [comment]
But from what is indicated in your Fatal error it seems that you did not add the "@" in the Entity file defining AgendaReminder :

```
root@testing:/var/www/testing4.beeznest.com/www# git diff src/Chamilo/CoreBundle/Entity/AgendaReminder.php 
diff --git a/src/Chamilo/CoreBundle/Entity/AgendaReminder.php b/src/Chamilo/CoreBundle/Entity/AgendaReminder.php
index 539366f0c4..82e2aebec3 100644
--- a/src/Chamilo/CoreBundle/Entity/AgendaReminder.php
+++ b/src/Chamilo/CoreBundle/Entity/AgendaReminder.php
@@ -10,7 +10,7 @@ use Doctrine\ORM\Mapping as ORM;
 /**
  * @ORM\Table(name="agenda_reminder")
  * Add @ to the next line when activatiing the agenda_reminders configuration setting
- * ORM\Entity()
+ * @ORM\Entity()
  */
 class AgendaReminder
 {

```

**Comment by andreboivin** [comment]
Hi Nicolas, I no longer have an error message by adding @ but if I activate the reminders, I no longer see the events in the agenda. Could you tell me where I could find the modified files. For example the version of the agenda.lib.php file is not the one that appears with view file. (see image) I looked in all the branches without finding.
![reminder2](https://user-images.githubusercontent.com/22802716/147763065-7c938b60-82ae-4a1f-a00e-280228e7907f.jpg)

**Comment by NicoDucou** [comment]
Hi @andreboivin 
Since you have a Version of Chamilo chamilo-lms-1.11.x 23-12-2020 There have been many changes since then.
It is hard to tell you what files have been modified since then. I would recommend to to a full update of your Chamilo to use this new functionality because it will be hard unless doing a lot of debugging finding all the part that are necessary.
Best regards

**Comment by andreboivin** [comment]
Indeed, I had forgotten a file
Regards
