### ISSUE TITLE
Duplicate tool visibility option in admin settings

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4118]
The two settings "Modules active upon course creation" and "Tool visible at course creation" seem to be duplicated. We should remove (after checking it is indeed a duplicate) the second option "Tool visible at course creation" from the settings_current table.

**Comment by christianbeeznest** [comment]
Currently chamilo 2.0 is using only a setting "Active tools on create" (active_tools_on_create) , avoiding the duplicate tool visibility , it is added too in migration updating old variable "Modules active upon course creation" from 1.11

**Comment by christianbeeznest** [comment]
active_tools_on_create is set inside CoreBundle/Settings/CourseSettingsSchema.php
