### ISSUE TITLE
Backup import - Quiz is imported but Questions are missing

### ISSUE THREAD

**Issue by Bavarianspirit** [chamilo/chamilo-lms#4124]
**Describe**
If i use the Backup Course function on 1.11.14 and try to import this backup in 1.11.16. all questions are missing.
The quiz will be imported but the questions inside won't be.

If i import the same backup into 1.11.14 everything works correct.

Is there any known issue about?

could be the same like this?
https://github.com/chamilo/chamilo-lms/issues/3981

**Comment by NicoDucou** [comment]
Hi @Bavarianspirit 
Yes it is probably the same as #3981

**Comment by Bavarianspirit** [comment]
Yes it was the same.
The code Change in #3981 works.
