### ISSUE TITLE
Feature request - Add hostname in meta informations for BigBlueButton

### ISSUE THREAD

**Issue by hichamon306** [chamilo/chamilo-lms#4139]
BigBlueButton provide ability to create additional information under meta tag, is it possible to add hostname in meta information, it useful to identify records belonging to hostname in BBB instance managing multiple chamilo.

Thanks in advance 

Hicham

**Comment by ywarnier** [comment]
@hichamon306 How/Where do you expect to get the value back? Do you want to see it somewhere in Chamilo? I suppose not. How do you see it on the BBB server?

**Comment by ywarnier** [comment]
In this PR (https://github.com/chamilo/chamilo-lms/pull/4511) I'm actually adding the full URL, because this is easier from Chamilo's standpoint and will work with both multi-url and non-multi-url setups.

**Comment by ywarnier** [comment]
This has been included for the incoming 1.11.18 release, under the metadata `meta_OriginURL`.

**Comment by hichamon306** [comment]
@ywarnier i’ll get the value back with bigbluebutton api, it will help me to identify the records belonging to specific platform.
Thank you for adding the metadata “meta_OriginURL”.
