### ISSUE TITLE
Missing test questions after upgrade to 1.11.16

### ISSUE THREAD

**Issue by mmaridev** [chamilo/chamilo-lms#4152]
**Describe**
After upgrading from 1.11.12 to 1.11.16, some tests (not all) are missing all questions.

Tried running 1.11.14 and connecting to same database has positive effect, the questions are there again.

**Screenshots**

v. 1.11.16

![Schermata del 2022-01-31 22-09-04](https://user-images.githubusercontent.com/18599077/151873423-445cf45c-0ebd-4f49-8c0b-8fda54a8c9d0.png)

v. 1.11.14 / 1.11.12

![Schermata del 2022-01-30 18-55-13](https://user-images.githubusercontent.com/18599077/151873228-76d8b3bd-d66b-48ce-90aa-b0feaea25c09.png)

**Desktop:**
 - OS: Ubuntu 20.04 (tested also via Debian 10)
 - Browser firefox=96.0+build2-0ubuntu0.21.10.1

**Server**
 - OS: Debian 11
 - Version of Chamilo: 1.11.16
 - Version of PHP: 7.4

**Comment by NicoDucou** [comment]
Hi @mmaridev 
This is a know issue (https://github.com/chamilo/chamilo-lms/issues/3993) and fixed with this script : https://github.com/chamilo/chamilo-lms/blob/1.11.x/tests/scripts/fix_quiz_id_to_iid.php

Let us know if it worked for you.

Best regards

**Comment by mmaridev** [comment]
I can confirm the script fixes the bug, maybe it can be made clear in the docs about updating.

**Comment by ywarnier** [comment]
@mmaridev You mean... something like this :point_down: ?
![upgrade-guide](https://user-images.githubusercontent.com/609839/152060468-49d43d61-fb8b-42cf-8d38-3a05ad118f7b.png)

**Comment by mmaridev** [comment]
@ywarnier where is this screenshot from? Certainly not form https://docs.chamilo.org/admin-guide/installation_and_configuration/readme.3

**Comment by lonesomewalker** [comment]
This is available in every /documentation/ folder:
https://github.com/chamilo/chamilo-lms/blob/1.11.x/documentation/installation_guide.html

There are many other usefull topics ;-)

**Comment by ywarnier** [comment]
Thanks @lonesomewalker 
Indeed @mmaridev, the file linked by lonesomwalker is also linked from the installer wizard (on every page, I believe).
The https://docs.chamilo.org/ guide is a bit outdated in terms of installation. We should probably just put a link to installation_guide.html in there. Noted.
