### ISSUE TITLE
Problem with test2pdf

### ISSUE THREAD

**Issue by an00bo** [chamilo/chamilo-lms#4153]
**Describe** 
I made a quiz with multiple choice questions
1 - inserted an image in a question
2 - create a pdf of the quiz via test2pdf (download questions)
3 - in the pdf that is created I don't see the image

**Screenshot**

![immagine](https://user-images.githubusercontent.com/98835953/152014995-f76171b0-97a9-4094-a804-1e2474ba3c51.png)

**Desktop**
 - OS: GNU/Linux Debian 11 (but with GNU/Linux Mint too) 
 - Browser: Firefox 91.5.0esr (64 bit) or Google Chrome 97.0.4692.99 (64 bit)

**Server**
 - OS: Debian 11
 - Version of Chamilo: 1.11.16
 - Version of PHP: 7.4

**Comment by ywarnier** [comment]
@nosolored is the image inclusion supported by the plugin, or should this be considered a new feature?

**Comment by ywarnier** [comment]
@an00bo if you could test the code sent and provide us with feedback, that would be much appreciated. Otherwise we'll consider this issue fixed as our internal testing shows it works now.

**Comment by an00bo** [comment]
Thank you all for your attention and your work 
now works perfectly 

Andrea 


Da: "Yannick Warnier" ***@***.***> 
A: "chamilo/chamilo-lms" ***@***.***> 
Cc: "an00bo" ***@***.***>, "Mention" ***@***.***> 
Inviato: Lunedì, 25 aprile 2022 16:19:58 
Oggetto: Re: [chamilo/chamilo-lms] Problem with test2pdf (Issue #4153) 





[ https://github.com/an00bo | @an00bo ] if you could test the code sent and provide us with feedback, that would be much appreciated. Otherwise we'll consider this issue fixed as our internal testing shows it works now.
