### ISSUE TITLE
Xajax error on PHP >= 7

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#4157]
Guys, when updated my php to 7.4 the functions using xajax stopped working. After reading about this, the xajax project is discontinued and some guys tells that problem. 

Like this
[https://github.com/Xajax/Xajax/pull/47/files#](https://github.com/Xajax/Xajax/pull/47/files#)

1. Go to 'Add single user to a session'
2. Search user just typing.
3. Nothing happen.

**Server
 - OS: CentOS
 - Version of Chamilo: 1.11.16
 - Version of PHP: 7.4

**Comment by ywarnier** [comment]
Where in particular do you have the issue ? (error message of some kind ?)

**Comment by fabiowoj** [comment]
@ywarnier in /main/session/add_users_to_session.php
Even in single user, or multiple user filtering by letter (lastname)

**Comment by fabiowoj** [comment]
<img width="1401" alt="Captura de Tela 2022-02-08 às 18 49 35" src="https://user-images.githubusercontent.com/36703444/153081564-c9ffc6c5-cf77-4504-ad3a-c50e093aea81.png">

**Comment by AngelFQC** [comment]
@fabiowoj can you inspect the request/response to ad_users_to_session.php with the network panel?

**Comment by ywarnier** [comment]
I just tested with PHP 7.4.26, Chromium and Firefox, and I don't get the error...
From the PR you're pointing to, I see that they modified the constructor, but we've already got that change in Chamilo (we modified version 0.2.4 to fix at least the constructor issue and some others), so my new question is: what version of Chamilo are you using ?

**Comment by fabiowoj** [comment]
@AngelFQC 
<img width="629" alt="Captura de Tela 2022-02-08 às 19 08 26" src="https://user-images.githubusercontent.com/36703444/153084010-48a33f7f-3436-49be-b804-e8d03fd2ab96.png">
<img width="948" alt="Captura de Tela 2022-02-08 às 19 09 19" src="https://user-images.githubusercontent.com/36703444/153084029-57f74dd2-6d32-4a85-b0d5-5df27fa117a1.png">

It works the request and the response, but not appear in the page.

**Comment by fabiowoj** [comment]
@ywarnier 
I tested in my installation with 1.11.16 last git
Tested in Chrome and Firefox

**Comment by fabiowoj** [comment]
Here some updates. The problem is the language. The file of brazilian language, i do some changes, and this is the problem is to be. Because when recover the original the problem solved. But still not know what modification in this file cause the error, just in xajax. No one problem occurs in site.

**Comment by fabiowoj** [comment]
Yes, 
not right where is the problem in lang file. But i started again the personalization and now works. Thanks for help.
