### ISSUE TITLE
Multiple question/quiz errors

### ISSUE THREAD

**Issue by lonesomewalker** [chamilo/chamilo-lms#4158]
**Describe**
First, when adding a quiz, and setting the additional settings to "sequential quiz, not on a single page", the quiz gets created as an "embeddable" object. Already reported this in the past, still an issue. Will upload footage.

But now additionally there is:
```Got error 'PHP message: An exception occurred while executing '':\n\nSQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty', referer: /main/exercise/admin.php?cidReq=COURSENAME&id_session=0&gidReq=0&gradebook=0&origin=&modifyQuestion=0&newQuestion=yes```

**Desktop (please complete the following information):**
 - OS: all of them, Win, Mac, Lin
 - Browser: several, Chrome, Firefox, Edge, all latest version

**Server**
 - OS: Ubuntu 20 latest patched.
 - Version of Chamilo:  latest 1.11.16 git
 - Version of PHP: 7.4-fpm
 - a lot of RAM and CPU

**Comment by lonesomewalker** [comment]
https://user-images.githubusercontent.com/856110/153084009-176efa3e-969a-4b32-ad0e-8833b0948b50.mp4

**Comment by ywarnier** [comment]
@lonesomewalker your video stops at 1:25 and I don't see any malfunction up to that time.
Could you point me to the time in the video where there is something unexpected, please? I really don't get the problem you're having. I checked #2945 and did the test locally as well. Everything works as expected, as far as I see...

**Comment by ywarnier** [comment]
In the "Save answers" config option, I don't have a dropdown box as you do, though.
