### ISSUE TITLE
Vídeo responsive por defecto

### ISSUE THREAD

**Issue by garzy** [chamilo/chamilo-lms#4162]
Hola, quería sugerir una mejora.
Veréis, a la hora de crear una lección con muchos videos, a veces me interesa, para ir más rápido, arrastrar los vídeos diréctamente en la zona de la izquierda y así creo rápidamente la secuencia de vídeos para esa lección.

**El problema es que de esta manera los videos no son responsive, no se adaptan al tamaño del navegador, si no a la resolución del propio vídeo.**

Así que me veo forzado a crear un nuevo documento html por cada vídeo, donde añado el vídeo y en sus propiedades le pongo que sea responsive (witdh: 100%, height: 100%), pero a veces ésto resulta muy pesado y tedioso cuando la lista de vídeos es muy larga 

_¿quizás haya una manera de automatizar esta pesada tarea?, he probado con plantillas pero también se hace muy manual_

Se agradece cualquier tipo de ayuda para reducir este trabajo manual. 

Saludos

**Comment by ywarnier** [comment]
@garzy hemos mandado cambios (listados aquí arriba) para definir responsive por defecto. No se si tienes la posibilidad de probar estos cambios en tu portal Chamilo para probarlos ?
Sino, puedes usar https://11.chamilo.org/ y probarlo ahí.

Nos gustaría tener tu confirmación de que estos cambios agregan la funcionalidad que sugeriste, para así cerrar este issue.

**Comment by garzy** [comment]
Hola, acabo de actualizarme la rama 1.11.x y SÍ, ahora el comportamiento es responsive por defecto. Muchas gracias!!, me habéis ahorrado un montón de trabajo tedioso. Gran trabajo 🥇 . Doy por cerrada la incidencia.
