### ISSUE TITLE
Error al instalar Chamilo con DB en MySQL Azure

### ISSUE THREAD

**Issue by lopezsalexander** [chamilo/chamilo-lms#4164]
**Describe el problema**
En la parte final de la instalación (Paso 7), se produce el siguiente error:

`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'row INT NOT NULL, `column` INT NOT NULL, position VARCHAR(20) NOT NULL, PRIMARY ' at line 1 in /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:132 Stack trace: #0 /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(132): PDO->query('CREATE TABLE co...') #1 /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOQueryImplementation.php(36): Doctrine\DBAL\Driver\PDOConnection->doQuery('CREATE TABLE co...') #2 /var/www/html/chamilo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1295): Doctrine\DBAL\Driver\PDOConnection->query('CREATE TABLE co...') #3 /var/www/html/chamilo/vendor/doctrine/orm/ in /var/www/html/chamilo/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/ToolsException.php on line 34`

**Cómo reproducir**
Pasos para reproducir el problema:
1. Instalar Chamilo en servidor Azure (Centos o Ubuntu)
2. Conectar a un servicio de base de datos Azure (Servidor de Azure Database for MySQL)
3. Realizar instalación, en el paso 7 se presenta el error. Crea la base de datos, pero no puede llenarla, se queda en 4.6mb

**Comportamiento esperado**
Instalar Chamilo con exito

**Servidor
 - Sistema operativo : CentOS 7
 - DB: Servidor de Azure Database for MySQL Versión 8.0.17
 - Versión de Chamilo: 1.11.16
 - Versión de PHP: 7.4

**Comment by ywarnier** [comment]
Parece que el problema proviene de la creación de la table `course_module`, que contiene una columna `row` y una columna `column`. Es probable que esta columna `column` esté detectada como palabra reservada de MySQL, y que de alguna manera el driver no lo esté escapando correctamente.
No observo este problema en un MySQL estándar instalado en Ubuntu. Habría que buscar en la documentación de Azure Database for MySQL, lo que dice sobre "escaping reserved keywords" o algo así... No tengo más ideas por ahora ni configuración con Azure para probar.

**Comment by ywarnier** [comment]
Cerrado por falta de seguimiento del usuario
