### ISSUE TITLE
In positioning tests (plugin), final radar chart is not scaled correctly

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4166]
**Describe**
Configure two positioning tests. Each test has 2 questions per 5 categories (total: 10 questions with max score of 10 for each).
Subscribe 4 students to the course, make one pass the "pre" and "post" tests with varying scores.
The radar chart shown to the student is correct in all cases.
As a teacher, analyze the average radar chart: the chart is off (scores on /3 instead of /10 if only one student)

Latest git version as of today.

**Comment by christianbeeznest** [comment]
Hi @ywarnier , could you send me the link or screenshot to find and reproduce the error as teacher please ?

Thanks in advance.

**Comment by ywarnier** [comment]
Video (in Spanish) explaining how to use the Positioning plugin: https://www.youtube.com/watch?v=7gaOfQwOFfQ 

Now my issue is that, when I have 2 users subscribed to my course and only 1 user has passed the test, I get this radar chart:
![posi-2](https://user-images.githubusercontent.com/609839/155292055-64d84e3a-64fa-4a26-b43b-65f9a529c6cf.png)

If, later on, I add 3 new users (total: 5 users) to my course and no additional user has passed the test, now my radar shows this:
![posi-5](https://user-images.githubusercontent.com/609839/155292137-2655753b-e752-49c7-9e42-0aabb4f72d41.png)

This is due to the values being divided by the number of students. It should, in fact, be divided by the number of students who have *already passed the test* (a different count from track_e_exercises for the initial test and the final test). Otherwise, the scale is incorrect.

So, currently, total average score for init/end test = (sum of all scores / number of students subscribed to the course).

It should be:
 - total average score for init test = (sum of all scores / number of rows of track_e_exercises) for this init test
 - total average score for end test = (sum of all scores / number of rows of track_e_exercises) for this end test

**Comment by christianbeeznest** [comment]
Thanks @ywarnier fo the clarification, the fix is added in this PR https://github.com/chamilo/chamilo-lms/pull/4188

**Comment by ywarnier** [comment]
Checked and approved PR #4188 
Thanks!
