### ISSUE TITLE
Block PDF download certificate, not blocking the button download certificate pdf in learnpath

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#4172]
Block PDF download certificate, not blocking the button download certificate pdf in learnpath

main/gradebook/lib/be/category.class.php
In line 2548

The platform setting even false download PDF, appear in learnpath.

**Comment by ywarnier** [comment]
@fabiowoj you mean this setting, right ?
```
// Hide gradebook "download report in PDF" button
// $_configuration['gradebook_hide_pdf_report_button'] = false;
```

**Comment by ywarnier** [comment]
Nevermind, found it as hide_certificate_export_link_students in the platform settings searching for "certificate".

**Comment by ywarnier** [comment]
This previous commit should fix it

**Comment by ywarnier** [comment]
@fabiowoj any chance you could test this and give us a confirmation ?

**Comment by NicoDucou** [comment]
No feedback in more than 6 month since correction so closing the task
