### ISSUE TITLE
Error about exercise pop-up in learnpath

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#4178]
The feedback pop-up not working in learnpath after the second question.
Using the last git code software.
<img width="1317" alt="Captura de Tela 2022-02-18 às 10 08 18" src="https://user-images.githubusercontent.com/36703444/154688928-ac913ceb-fa57-43cf-9798-2b43210cf895.png">
<img width="1326" alt="Captura de Tela 2022-02-18 às 10 08 07" src="https://user-images.githubusercontent.com/36703444/154688937-5eefff0c-acf8-4e76-a777-dfcdfdd46bf0.png">
<img width="800" alt="Captura de Tela 2022-02-18 às 10 07 40" src="https://user-images.githubusercontent.com/36703444/154688939-dd0f560d-4fa3-4e96-8992-2cb96776047b.png">
<img width="994" alt="Captura de Tela 2022-02-18 às 10 21 35" src="https://user-images.githubusercontent.com/36703444/154690441-a84cf2bf-b451-4404-bfcc-d80e5620bd91.png">

Other type of exercise, works very well.

**Comment by fabiowoj** [comment]
https://user-images.githubusercontent.com/36703444/155155144-0fdc29c7-40da-4e6d-ab9e-253a0673d098.mov

**Comment by AngelFQC** [comment]
Hi @fabiowoj 
I sent two fixes for exercises pop-up in LPs. Can you confirm if these fix the issue?

**Comment by fabiowoj** [comment]
Hello @AngelFQC 
I tested it now and it seems to work flawlessly. Thanks for the answer.
