### ISSUE TITLE
More personalization of Chamilo

### ISSUE THREAD

**Issue by mta92** [chamilo/chamilo-lms#4196]
Hello!
I wish to edit the notification mails and other mails in Chamilo, and the footer of the pages. How can i do it?
Thanks!
![image](https://user-images.githubusercontent.com/95572494/156898993-78328343-22f7-43d7-8b87-bb005b202b2c.png)

**Comment by ywarnier** [comment]
Why? They are soooo sexy! :smile:

**Comment by ywarnier** [comment]
This is categorized as a support request. Support requests are treated by our larger community at https://forum.chamilo.org. Please refer your question there.
You might also find our (somewhat outdated but still working) official documentation useful:
https://docs.chamilo.org/developer-guide/theming_through_templates

I don't think it covers e-mail customization (for which there is a feature documented in main/install/configuration.php): https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/install/configuration.dist.php#L1177
