### ISSUE TITLE
Marking scheme in case of multiple answer correct question 

### ISSUE THREAD

**Issue by mygovernance** [chamilo/chamilo-lms#4201]
This complete request is for multiple choice question with multiple answer correct.

Let's suppose option-1 and option-2 is correct for a question having 3 or more than 3 option.
If student select option-1 and option-2 he will get 3 marks. In any other combination student will get negative marks.

In current scenario-
If I put score-1 for option-1 and score-2 for option-2 . If student select Option-1 only then he is receiving 1 mark or if only option-2 is selected he receive 2 mark.

 this exam pattern is very normal . So It should be very basic features as a LMS.
There is one way to create "Exact select" Type question but negative marking is not configured.

:et me know if there is some thing on platform through which we can achieve above use-case.

**Comment by mygovernance** [comment]
@ywarnier   It would be really helpfull if you can help here. I am also an experienced SDE. Let me know If I can lead this feature.

**Comment by mygovernance** [comment]
I need questype with "Exact Selection" with negative marking.

**Comment by ywarnier** [comment]
Hi @mygovernance 

To be honest I don't understand your use case... Could you explain that differently ?

In multiple answers questions, you can give positive or negative scores for each answer separately, so the total combination of marks is exactly what it sums up to.
In the "exact combination" type, you get 0 if you miss at least one correct answer.

I don't really see a case here you need an arbitrary negative score if you get one answer (or more) wrong. Is that what you want to achieve ?

Isn't that enough to give a 0 when the person answering the test might have answered several answers correctly but just missed one ?

(I don't know what "SDE" means - please don't use acronyms on intercultural spaces).

**Comment by mygovernance** [comment]
Hi @ywarnier , 
Just think about a case for  "exact combination" type with negative score in case of wrong . Right now we are giving 0 score where as I want to give negative score.

I hope I have explain bit it bit clear.

**Comment by Coursenligne** [comment]
Hi to achieve this (I agree with ywarnier, it's quite easy with multiple "standard" choice.
Give for example 1 point to any good question (let's say Q1 and 3 => 2 points if correct) and se any other answer as -3.
Even if I select the 2 corrects answer AND at least a bad one, I get minus score.
I've made a test where in each questions I had a really silly answer. People who wanted to laugh would get -50! Trust me they have 1 round, and them become serious.

**Comment by ywarnier** [comment]
@mygovernance the "exact combination" is not meant as a shortcut to multiple choice but rather as a way to ensure that no wrong answer is selected. We qualify this question type of "sadistic" already, as any little mistake gives you zero. I don't want to argue about the legitimacy of your request, but it would require a considerable amount of time to do something that is, mostly, possible through multiple choice. So no hope to include it as a community contribution (there are already 479 other issues that seem more relevant than that to me). 

If you really want that feature to be included, I suggest you contact one of the Chamilo Official Providers: https://chamilo.org/providers or find someone to develop it for you and submit the code as a pull request.
