### ISSUE TITLE
In my tracking only - as scores

### ISSUE THREAD

**Issue by andreboivin** [chamilo/chamilo-lms#4205]
In my tracking the scores do not appear, only - . Why In tracking.lib.php line 7970 is - 
:   $exercices['title'],
                $attempts,
                '-',
                '-',
                '-',
                '-',

See screenshot 
![bug_chamilo_tracking](https://user-images.githubusercontent.com/22802716/158016846-43e918f1-4b5d-4e1a-a146-d4483a795e91.jpg)

**Comment by lautarobeeznest** [comment]
Hi @andreboivin ,

I was unable to reproduce the error. In my chamilo portal if the scores appear.

Could you provide more information about the problem?
Do you have exercises and quizzes that have already been completed by students?
If possible some screenshots would help a lot.

Thank you very much in advance!

**Comment by andreboivin** [comment]
Désolé, avec les modif pour le suivi dans myStudents.php, c'est ce qui cause ce problème, je ne l'ai pas avec la version originale. On accède aux détails via myStudents.php où tous les cours de l'apprenant sont listés.
![suivi](https://user-images.githubusercontent.com/22802716/166934882-8bc44e4a-a12e-4307-9254-6bdd936d0008.jpg)
