### ISSUE TITLE
Statistics Zombies error

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#4223]
Hello,

when enter in Statistics/Zombies, getting page error.

/main/admin/statistics/index.php?report=zombies

The new installation getting error (1.11.16)
<img width="952" alt="Captura de Tela 2022-03-24 às 17 14 08" src="https://user-images.githubusercontent.com/36703444/160002266-1f2c5df0-020a-409e-9995-5bd92d8488d8.png">

The older 1.11.12 works normal.

**Comment by ywarnier** [comment]
And to get there: Administration page > Platform block > Statistics > Users column > Zombies

**Comment by ywarnier** [comment]
Hi @fabiowoj 
If you get a chance to check the code sent above, that would be lovely. Otherwise we'll consider this issue fixed by default.

**Comment by ywarnier** [comment]
Tested and approved. No feedback after 3 days. Closing.
