### ISSUE TITLE
Survey : Multiple choice with free text (Add option button do not work)

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4225]
In a survey, when creating a question of type "Multiple choice with free text" it is only possible to set 2 options. When clicking on "+ Add option" the page reload but nothing happens there is still only 2 options. There should be 1 more option presented.

Can be reproduced here : https://11.beeznest.com/main/survey/question.php?action=add&type=multiplechoiceother&survey_id=4&question_id=&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=

Also there is a problem with the icon that do not appears in the title.

![image](https://user-images.githubusercontent.com/6579268/160083338-b615c805-55fc-4113-a48f-60c6f35b50d3.png)

Tested  on Chamilo 1.11.x of 25/03/2022

**Comment by NicoDucou** [comment]
I've just seen that the icon problem occurs also for question type "Selective display" for example here :
https://11.beeznest.com/main/survey/question.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&action=add&type=selectivedisplay&survey_id=4

**Comment by lautarobeeznest** [comment]
@NicoDucou I can see that in the "main/survey/survey_question.php" route they are doing the following:

`if (isset($_POST['buttons']) && isset($_POST['buttons']['add_answer'])) {`
`ㅤㅤㅤㅤif (isset($_REQUEST['type']) && 'multiplechoiceother' === $_REQUEST['type']) {`
`ㅤㅤㅤㅤㅤㅤㅤㅤ$counter--;`
`ㅤㅤㅤㅤ}`
`ㅤㅤㅤㅤ$counter++;`
`ㅤㅤㅤㅤSession::write('answer_count', $counter);`
`}`

What is the point of `$counter--`?

**Comment by NicoDucou** [comment]
@AngelFQC you closed the issue but it still does not work for me.
With your commit [81a5365](https://github.com/chamilo/chamilo-lms/commit/81a5365d322e3eb18090ac346207521de48cd6d4) the image problem is solved but the main issue here is the fact that when clicking on the "Add option" icon it does not generate a new option.

@lautarobeeznest you indicate that you had a fix for this, can you send your PR so that we can test it and validate it ?
