### ISSUE TITLE
Wrong flag - Vietnam

### ISSUE THREAD

**Issue by amayard** [chamilo/chamilo-lms#4231]
### Current behavior / Resultado actual / Résultat actuel
The current flag for vi.svg which is displayed as the vietnamese flag is the Virgin Islands flag, which also acronyms as V.I. put generates wrong display of flag for the vietnamese users.

### Expected behavior / Resultado esperado / Résultat attendu
Here's a free svg from wikipedia for the correct flag : 
![vi](https://user-images.githubusercontent.com/88547891/161046779-469973a2-3db8-498d-a9ae-a92a7a36b830.svg)

### Chamilo Version / Versión de Chamilo / Version de Chamilo
1.11.x

**Comment by ywarnier** [comment]
Tested and approved.
