### ISSUE TITLE
Las imágenes no se muestran 

### ISSUE THREAD

**Issue by Illargi** [chamilo/chamilo-lms#4235]
Cuando inserto imágenes siguiente la ruta:
Mis cursos – Crear un documento – Insertar imagen
La imagen se inserta en el documento pero no está visible. 

![image](https://user-images.githubusercontent.com/19992876/161504437-51707cae-8c66-4511-b826-5e197df29568.png)
![Captura 1 - Reporte bug](https://user-images.githubusercontent.com/19992876/161504744-ade20585-9a77-406a-92ee-63c46c7e2b99.png)
![Captura 2 - Reporte bug](https://user-images.githubusercontent.com/19992876/161504762-5aae4f55-7e58-4f2a-902f-e41edc4af359.png)

**Cómo reproducir**
Pasos para reproducir el problema:
1. Mis cursos
2. Crear documento
3. Insertar imagen
4. Se muestra el título de la imagen pero esta no se muestra. Lo mismo me sucede si intento utilizar alguna de las plantillas prediseñadas.

Capturas de pantalla
URL de la captura de pantalla 1: https://lurcursos.com/chamilo/main/document/edit_document.php?cidReq=EPMPQ&id_session=0&gidReq=0&gradebook=0&origin=&id=1198 

 
URL Captura de pantalla 2: https://lurcursos.com/chamilo/main/document/edit_document.php?cidReq=EPMPQ&id_session=0&gidReq=0&gradebook=0&origin=&id=1198 

**Sistema Operativo: Windows 10 Home
Versión	21H2
Navegador: Chrome versión Versión 100.0.4896.60 (Build oficial) (64 bits)
 
**Servidor
Versión Apache	2.4.52
Versión PHP	8.0.16
Versión MySQL	10.5.15-MariaDB-cll-lve
Arquitectura	x86_64
Sistema operativo	linux
Dirección IP compartida	212.1.210.101
Ruta de acceso a Perl	/usr/bin/perl
Versión Perl	5.16.3
Versión Kernel	4.18.0-305.17.1.lve.el7h.x86_64
Versión de Chamilo: 1.11.16

Muchas gracias de antemano por la ayuda que puedan brindarme.

**Comment by Illargi** [comment]
Buenos días, muchas gracias por contestar.
Esta es la URL de una de las dos imágenes que subí de prueba y que no se ve
tal y como la obtengo en "propiedades de la imagen":

/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol2.png

Este es el código HTML con las dos imágenes que no se muestran:

<!DOCTYPE html>
<html>
<head>
<title></title>
<meta charset="UTF-8" />
</head>
<body dir="ltr">
<p style="text-align: center;"><img alt="" class="img-responsive"
src="/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol.png" /></p>

<p class="text-center"><img alt="Etiqueta 1-propanol - Ejemplo"
class="img-responsive" height="17"
src="/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol.png" width="226"
/></p>

<p>&nbsp;</p>

<p class="text-center"><img alt="Etiqueta 1 propanol"
class="img-responsive" height="300"
src="/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol2.png" width="400"
/></p>


<p>&nbsp;</p>
</body>
</html>

Mil gracias por su ayuda.

Atentamente,
Illargi Uzcanga

**Comment by ywarnier** [comment]
@Illargi el código HTML que mandas proviene de un documento que se encuentra *dentro* del curso con código EPMPQ, verdad?

**Comment by ywarnier** [comment]
Cuando cargas la URL /courses/EPMPQ/document/Imagenes/etiqueta-1-propanol2.png directamente, te aparece la imagen ?
Misma pregunta sobre las URLs siguientes:
/app/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol2.png
/chamilo/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol2.png
/chamilo/app/courses/EPMPQ/document/Imagenes/etiqueta-1-propanol2.png

**Comment by ywarnier** [comment]
Podrías darnos el valor de la variable `$_configuration['url_append'] ` dentro de tu archivo app/config/configuration.php ?

**Comment by Illargi** [comment]
En ninguno de los casos puedo ver la imagen; sin embargo cuando copio la URL de una imagen subida en otro sitio web sí se ve

**Comment by Illargi** [comment]
Mil gracias por tu apoyo. Esta es la línea tal y como aparece en el archivo que envío adjunto.

 

$_configuration['url_append'] = '';

 

Un abrazo

**Comment by Illargi** [comment]
¡Hola! Perdona la demora.

Es correcto

**Comment by ywarnier** [comment]
> $_configuration['url_append'] = '';

Hola @Illargi 
Creo que este es tu problema, supongo. Como has instalado Chamilo en una subcarpeta (por la ruta que aparece en tu primera captura de pantalla y las URLs que citas después), este url_append debería contener la subcarpeta ("chamilo") así:

`$_configuration['url_append'] = 'chamilo';`

Luego recargar la página.
No se como llegaste a esta situación, pero lo más probable es que hayas hecho la instalación con una ruta y luego la hayas cambiado. A Chamilo no le gusta mucho este tipo de cambios.

Avísanos si esto resuelve tu problema, para poder pasar a otra cosa.

**Comment by Illargi** [comment]
Hola Yannick:

Mil gracias por tu ayuda. Incluí la subcarpeta en la expresión y ahora sí se muestran las imágenes que subo.

De verdad, muchísimas gracias por tu valioso apoyo.

Un abrazo

**Comment by ywarnier** [comment]
Buena noticia.
