### ISSUE TITLE
Survey with no end date

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4240]
A survey needs to have an end date, it is mandatory, it can not be left blank.
But now that a survey can be created in the base course and used in all the sessions that use that course, it would be useful to be able to leave the end date as null so that it would always be available.
For the moment if can be set to 31/12/2027 so we have a bit of time but it still means there will be a problem at the end of 2027.
Reference to BT#19854

**Comment by ywarnier** [comment]
Added to 1.11.x.
@NicoDucou if you have the opportunity to test this... (then please do and close the issue)

**Comment by NicoDucou** [comment]
All correct for me. I close this issue
