### ISSUE TITLE
Hide tools from teacher doesn't work in Administration

### ISSUE THREAD

**Issue by dauzeine** [chamilo/chamilo-lms#4256]
When an administrator of a platform wants to hide one or several tools from teacher, he desactivates these in the "configuration settings",  "Tools" menu, half way.
But this doesn't work : tested in 1.11.12, 14 and 16, both with old courses and new courses.

**Comment by lautarobeeznest** [comment]
Hi @dauzeine ,

When you try to test if the tool was disabled for the teacher, do you do it through the same administrator account?

I tried to create an account as a teacher, I disabled a tool (with another admin account) and the teacher could no longer see it but the admin could.

**Comment by dauzeine** [comment]
Hi,
true! It's working conveniently, sorry for the bad report. I'll post your answer in the forum.
