### ISSUE TITLE
Exercises of the base course could be deleted using the options of the exercises list at a session

### ISSUE THREAD

**Issue by juan-cortizas-ponte** [chamilo/chamilo-lms#4281]
If we access to the exercises list from a session, it is possible to delete exercises of the base course using the delete bulk action. This could be described as a bug since it would not have to be possible to delete exercises from the base courses If we accessed from a session

Si accedemos  a la lista de ejercicios  desde una sesión, es posible eliminar ejercicios que pertenecen al curso base utilizando la opción de borrado masivo del listado. Podriamos describirlo como un bug ya que no tendría qué  ser posible eliminar ejercicios que son del curso base accediendo desde una sesión.

![imagen](https://user-images.githubusercontent.com/48205899/168260380-0cb33615-d1ef-4519-b55c-8e9e8bc49585.png)

**Comment by NicoDucou** [comment]
This should be fixed with this commit : a07bd45aec0df3a49fb14db9567c46bbacbe4f00
Now it will only proceed with exercise that are in the same session as the current session.
@juan-cortizas-ponte Could you confirm it is all good for your use case and close the task ?

**Comment by ywarnier** [comment]
This works for me. I tried deleting the base-course test alone with the multiple selector option, then a base-course test *and* a session test at the same time. In both cases, the base-course test remained present and a message indicated the base-course test was not deleted.
