### ISSUE TITLE
SQL-Error while attempting full course backup

### ISSUE THREAD

**Issue by ljorzick** [chamilo/chamilo-lms#4285]
**Describe**
Course Backup: When attempting to backup a full course, I get an error message "An error has occured, contact System Administrator".

**To Reproduce**
1. Go to 'Example Course'
2. Click on 'Maintenance'
3. Scroll down to 'Create Backup'
4. Pick either 'Full Backup' or Choose all in 'Pick Course Parts'
5. See error message

**Expected behavior**
Would expect to be presented with a download of the Course backup.

**Screenshots**
![Bildschirmfoto 2022-05-16 um 13 05 00](https://user-images.githubusercontent.com/68810295/168580158-dce53e81-13ca-437c-ae5d-91f534abfbcf.png)

**Desktop (please complete the following information):**
 - OS: MacOS 15
 - Browser Firefox 100.0

**Server
 - OS: Ubuntu Linux 22.04 LTS
 - Version of Chamilo:  1.11.x of 2021-08-25
 - Version of PHP: 7.2

**Additional context**
Detailed Error from Apache2 Error-Logfile: 

[Mon May 16 13:04:55.710966 2022] [php7:notice] [pid 53710] [client 10.15.48.x:46214] An exception occurred while executing 'SELECT * FROM c_quiz_answer\n                                WHERE question_id = ':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2, referer: https://chamilo.xxxx.de/main/coursecopy/create_backup.php?cidReq=BEISPIELKURS&id_session=0&gidReq=0&gradebook=0&origin=

Looks to me like there is an error when backing up quiz data from the db...any help is appreciated!

**Comment by ywarnier** [comment]
Hi @ljorzick 
Your database might have a few inconsistencies as it tries to get answers (c_quiz_answer table) from a question_id that is empty.
If your Chamilo version is 1.11.16 (it looks like that based on the date you mention, which was also the release date for 1.11.16) and you have *upgraded* from a previous version (and the system was first installed with 1.11.10 or earlier) you are probably facing the "iid" issue. In this case, please read the upgrade guide carefully: https://campus.chamilo.org/documentation/installation_guide.html#3._Upgrade (section 3.1, last ~10 lines).

**Comment by ywarnier** [comment]
Closed for lack of feedback.
