### ISSUE TITLE
Destacar en informe de alumno que no se ha cubierto el tiempo mínimo en la lección

### ISSUE THREAD

**Issue by contidos** [chamilo/chamilo-lms#4299]
**Situación actual**

Actualmente en Chamilo 1.11.x, cuando accedes al informe de actividad de un alumno, puedes ver el tiempo que ha estado en cada lección. Pero si esa lección tiene un tiempo mínimo asignado para poder superarse, desde la vista de informes no puedes verlo y por tanto para un tutor es complicado saber si el alumno no puede avanzar porque no ha llegado al tiempo mínimo o si existe otro problema. 

**Propuesta de mejora**

Como propuesta de mejora sugiero que cuando el tiempo requerido para superar una lección no haya sido alcanzado, el tiempo en la columna "Hora" se muestre en rojo. De este modo se le da una pista visual al tutor de que a ese alumno le falta completar el tiempo en esa lección. 

NOTA para equipo Chamilo: asignar a Juan Cortizas de Contidos Dixitais.
![tiempos_lecciones](https://user-images.githubusercontent.com/30044847/170212250-3b78ff99-e9b5-4d94-9550-36e0c33a76c3.png)

**Comment by ywarnier** [comment]
Para que esto funcione, hay que activar la opción `lp_minimum_time` en configuration.php (y seguir las instrucciones correspondientes). El reporte en la captura proviene de la herramienta de seguimiento en el curso + la opción "detalles" al costado de un alumno.

**Comment by ywarnier** [comment]
El PR correspondiente ha sido incluido, dejando funcional este nuevo modo de presentación.
![lp-new-highlight-missing-time](https://user-images.githubusercontent.com/609839/209737753-97c52f5d-45ae-428f-99b7-4d986c4d7bbc.png)
