### ISSUE TITLE
Replace *_session_id fields with session_id in track_e_* tables

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4318]
In track_e_* tables, we are using fields representing session IDs with a name that is a form of prefixed *_session_id.

This makes it more difficult to identify what is really a session ID and what isn't.

Rename all those fields to `session_id`, simply, to avoid confusion.

Other "prefixed" fields should be renamed as well, but this would already be a good first step.

**Comment by christianbeeznest** [comment]
This request is done in this PR https://github.com/chamilo/chamilo-lms/pull/4323

Thanks for confirmation.

**Comment by ywarnier** [comment]
I see that the document download action does not register anything in track_e_download anymore, but this is not directly related to this issue and PR.

**Comment by ywarnier** [comment]
Reviewed, approved and tested.
