### ISSUE TITLE
Forum post move functionnality do not work anymore

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4320]
When viewing forum posts in the course tool there is on the left hand side an icon to move the post but when clicking on it nothing happens.

![image](https://user-images.githubusercontent.com/6579268/173376284-33203f3f-34bf-4a78-a4f0-9a5c1a51ec5a.png)

Tested on Chamilo 1.11.x on the 13/06/2022 here : https://11.beeznest.com/main/forum/viewthread.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&forum=26&thread=3&search=

**Comment by BorjaSanchezBeezNest** [comment]
Hi @NicoDucou 

This issue is already solved, whit @ywarnier 's help. Its waiting to review the pull request.


Bye!

**Comment by ywarnier** [comment]
Reviewed and approved.
