### ISSUE TITLE
No encuentra usuarios ni profesores en caja de texto en página new_message.php en el campo enviar a

### ISSUE THREAD

**Issue by soporteLecciona** [chamilo/chamilo-lms#4355]
**Describe el problema**
Buenas, no se encuentran usuarios ni profesores en caja de texto enviar en la página new_message.php. Al acceder a redactar mensaje, escribimos los tres caracteres que se piden, pero la búsqueda no encuentra resultados. Solo funciona cuando el usuario se busca a si mismo, por lo que no se pueden enviar emails desde esa página ni siquiera a los profesores. El resto de envío de emails, y la busca genérica de la cabecera, funciona bien. El módulo Xapian no está instalado.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a redactar, en la página principal.
2. Dar clic en campo de texto Enviar a
3. Introducir tres caracteres para buscar usuarios o profesores. 
4. aparece el mensaje No se encontraron resultados, por lo que no se puede enviar el email

**Comportamiento esperado**
encontrar los email de los profesores en el campo enviar a, en la página new_message.php al introducir los tres caracteres. Actualmente solo se encuentra al mismo usuario que está logado he intenta enviar el email, por lo que no se puede enviar ni a los profesores de los cursos de un usuario alumno ni a otros alumnos

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/109804032/180729603-cd2952ca-63e2-478c-b2e2-49f7ba1ea073.png)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : Ubuntu 20.04
 - Versión de Chamilo:  1.11.8
 - Versión de PHP: PHP 7.4

**Contexto adicional**
Gracias

**Comment by ywarnier** [comment]
Cerrando por falta de respuesta
