### ISSUE TITLE
Questions list disappear from all exercises

### ISSUE THREAD

**Issue by fabiowoj** [chamilo/chamilo-lms#4361]
Hello everyone.

I have some issues about question list like image below.
<img width="1165" alt="Captura de Tela 2022-07-28 às 15 11 38" src="https://user-images.githubusercontent.com/36703444/181608806-d7f78b5d-d5c4-46ac-a09e-f3a060027af1.png">
I have two installations and both getting the same problem. One of them its new, and to solve that i reinstall the platform. Mas but the other i have a lot of users, so i have to fix. All exercises already created, its normally working, but all of them isn't possible to edit/delete questions.

Anyone have this problem?

My installation is 1.11.16 with CentOS and MariaDB

**Comment by fabiowoj** [comment]
After searching this error, I finally found it.

Need to edit /main/exercise/question.class.php at line 71
Just comment the line
`//UPLOAD_ANSWER => ['UploadAnswer.php', 'UploadAnswer'],`
Some error occurrs when load object in UPLOAD_ANSWER.
But i cannot found an error(still searching) in /main/exercise/UploadAnswer.php

This hack fix the problem.

**Comment by NicoDucou** [comment]
You probably just need to do a "composer dumpautoload" to update the information to have the new class type (or may be a composer install is needed).

**Comment by ywarnier** [comment]
Lacking feedback. Closing.
