### ISSUE TITLE
Create a backup

### ISSUE THREAD

**Issue by ashishkpaul** [chamilo/chamilo-lms#4365]
**Describe**

**To Reproduce**
1. Go to 'Course'
2. Click on 'backup'
2022/08/08 17:14:43 [error] 756933#756933: *152413 FastCGI sent in stderr: "PHP message: An exception occurred while executing 'SELECT * FROM c_quiz_answer
                                WHERE question_id = ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2" while reading upstream, client: 223.229.128.51, server: courses.aashah.com, request: "POST /main/coursecopy/create_backup.php?cidReq=FCJR&id_session=0&gidReq=0&gradebook=0&origin= HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "courses.aashah.com", referrer: "https://courses.aashah.com/main/coursecopy/create_backup.php?cidReq=FCJR&id_session=0&gidReq=0&gradebook=0&origin="

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Browser [e.g. chrome, firefox, safari] and version

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  [e.g. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Version of PHP: [e.g. 5.6, 7.2, ...]

**Additional context**

**Comment by Coursenligne** [comment]
Hi,
I see 5.6 as PHP version. Chamilo 1.11 only works with 7.x version and I'm currently testing 1.11.16 with PHP8, but when I encouter issues, I revert to 7. and so far I don't have that much issues.
I however have to get rid of email sending issue, but this is another story.

**Comment by ywarnier** [comment]
The error message refers to PHP 7.4.
@ashishkpaul , the information you provide is not enough to help you out, but there seems to be something wrong with your query (not mentioning the question_id).
