### ISSUE TITLE
Move session image extra field to the session table

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4366]
As indicated in #3788, the session extra field for image has been converted to an asset, but this really should become part of the session entity (session table) instead of being an extra field.

**Comment by christianbeeznest** [comment]
It is moved the session image extra field to the session table as asset in this PR https://github.com/chamilo/chamilo-lms/pull/4588
Thanks for confirmation.

**Comment by ywarnier** [comment]
Merge incorporado.

**Comment by ywarnier** [comment]
@NicoDucou do you have a way to check the maintenance of accessibility of session images (illustration of the session itself) from 1.11 to 2.0?

**Comment by NicoDucou** [comment]
> @NicoDucou do you have a way to check the maintenance of accessibility of session images (illustration of the session itself) from 1.11 to 2.0?

On My sessions page https://CHAMILO/sessions the image is used and on a migrated plateforme we have the session's image presented on the page.

We can also see the image in the session resume page main/session/resume_session.php

So I would say that this is all correct or do you (@ywarnier) think of something different that needs to be checked ?

**Comment by ywarnier** [comment]
I think it is all correct. Feel free to close.
