### ISSUE TITLE
The phrase 'target language' crashes Chamilo

### ISSUE THREAD

**Issue by beniza** [chamilo/chamilo-lms#4374]
**Describe**
Chamilo crash if it find the word `target language` in the body text.

**To Reproduce**
1. Create a new document and give it a title name
2. Add the text 'target language' (without quotes) in the body
3. Save the document

**Expected behavior**
I expected it to save the document

**Screenshots**
![image](https://user-images.githubusercontent.com/4908971/187011710-dd1df2ce-ac61-4a71-a6f7-6e70db453309.png)
![image](https://user-images.githubusercontent.com/4908971/187012007-f798672f-8bcc-427e-9569-1a4442378e92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  1.11.16
 - Version of PHP: 8.0.2

**Additional context**
Webserver is Apache. Hosted on DreamHost. I've also noted that the /install folder isn't removed.

**Comment by BorjaSanchezBeezNest** [comment]
Hi @beniza,

I've tried to reproduce the issue, but I can't get it to happen.

My server:

- Ubuntu 22.04
- Apache
- Chamilo 1.11.x

I have done the following steps:

- Create a new course and new empty document (following your steps)
- Test in English and other languages (platform and course)
- Test with PHP 7.4 and PHP 8.0.24
- Try with various HTML tags or special characters in the text editor

Are you currently having the same error? Maybe it could be from the hosting server (DreamHost)?

If you provide us with any more relevant information, it may help us to detect the error.

Greetings!
