### ISSUE TITLE
Problemas al importar y exportar ejercicios con QTI2 y Aiken

### ISSUE THREAD

**Issue by saragaes** [chamilo/chamilo-lms#4378]
**Describe el problema**
He intentado importar ejercicios usando un archivo QTI2 y en formato Aiken, pero surgen errores.

**Cómo reproducir importar ejercicio via QTI2**
Pasos para reproducir el problema:
1. Exportar un ejercicio ya creado en Chamilo utilizando el botón para descargarlo en archivo QTI2
2. Sin modificar el archivo QTI2, importarlo como un nuevo ejercicio
3. Ver el error que dice "El archivo que quiere subir no es válido"
![Captura de Pantalla 2022-09-07 a la(s) 11 25 01 a  m](https://user-images.githubusercontent.com/113041169/188933110-6511ff0b-2526-41e0-806d-d1e4a9fca3d2.png)

**Comportamiento esperado**
Un ejercicio exportado en un archivo QTI2 directamente desde Chamilo se debería poder importar como un nuevo ejercicio, pues es la misma plataforma quien genera el archivo QTI2 para ser importado más adelante.

**Cómo reproducir importar ejercicio en formato Aiken**
Pasos para reproducir el problema:
1. Hacer click en botón para importar ejercicio en formato Aiken
2. Antes de importar el ejercicio, crear un archivo .txt con el ejemplo del formato Aiken que sugiere Chamilo 
![Captura de Pantalla 2022-09-07 a la(s) 11 39 12 a  m](https://user-images.githubusercontent.com/113041169/188933143-c25a54fb-2c06-49d1-be5a-ec5465a07493.png)
3. Importar el archivo .txt
4. Ver el error que dice "Hubo un error desconocido en su archivo. Por favor revise su formato e intente nuevamente."

**Comportamiento esperado**
Un archivo .txt con el mismo ejemplo que sugiere Chamilo debería poder importarse sin problema. Intenté también modificar las preguntas y respuestas en nuevos archivos .txt, pero ninguna prueba funcionó. 

**Escritorio:**
 - Sistema operativo : macOS Catalina versión 10.15.7
 - Navegador: Chrome versión 105.0.5195.102

**Servidor
 - Versión de Chamilo: 1.11.16

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by BorjaSanchezBeezNest** [comment]
Hola @saragaes 

Gracias por reportar la incidencia.

He intentado replicar, siguiendo los pasos que ha descrito, el error, pero no me sucede. Las exportaciones / importaciones, usando ambos sistema, la hace correctamente.

Mi servidor:

-Ubuntu 22.04
-Apache
-Chamilo 1.11.x
-PHP 7.4

¿El problema actualmente le sigue sucediendo?

Algunas cosas que podrías probar son las siguientes:

- Para le exportación e importación en formato QTI2, asegurase que al importar, se importa el archivo .zip generado, no el .xml
- Si le sigue sucediendo y no es inconveniente, nos podrías compartir el archivo .zip que genera en su plataforma para poder probarlo
- Para la importación en formato Aiken, comprobar que en el .txt no haya ningún carácter especial que pueda estar afectando a la estructura esperada

Igualmente, cualquier dato mas que pudiera proporcionar para intentar replicar el problema o determinar que le puede estar sucediendo, bienvenido es.

Capturas:

![Captura desde 2022-10-10 12-10-30](https://user-images.githubusercontent.com/114572427/194843408-9cc7c43d-19cd-43d4-b9df-af30873c2996.png)

![Captura desde 2022-10-10 12-10-47](https://user-images.githubusercontent.com/114572427/194843431-a4266aac-ab29-4ef9-bb79-c74afb66bbb2.png)


Un saludo!

**Comment by saragaes** [comment]
Hola @BorjaSanchezBeezNest!

Gracias por la respuesta. 

Intenté crear un nuevo ejercicio en un curso test sin estudiantes. Exporté el archivo en formato QTI2 y re-importé el archivo .zip, pero surge una alerta que dice "No se encontró ningún archivo XML en el zip. Se requiere uno para este tipo de importación.", aunque cuando lo descomprima si existe un archivo XML. 

Dejo adjunto el archivo .zip que estoy intentando importar y capturas de pantalla:

[qti2_export_201048.zip](https://github.com/chamilo/chamilo-lms/files/9749386/qti2_export_201048.zip)


![Captura de Pantalla 2022-10-10 a la(s) 4 27 15 p  m](https://user-images.githubusercontent.com/113041169/194955404-85628721-6d86-442a-a7f8-213a5d9a5cae.png)
![Captura de Pantalla 2022-10-10 a la(s) 4 28 24 p  m](https://user-images.githubusercontent.com/113041169/194955411-281beb4a-7031-4f67-883b-202ad7f5d8b4.png)

Gracias nuevamente y un saludo!

**Comment by BorjaSanchezBeezNest** [comment]
Buenas @saragaes 

He descargado y probado el .zip que adjuntaste, y ha importado correctamente el contenido:

![Captura desde 2022-10-13 11-25-13](https://user-images.githubusercontent.com/114572427/195558590-dc3cab09-847b-481e-8547-e074b2280059.png)

Podrías probar a hacer la importación en el entorno de desarrollo de Chamilo, teniendo precaución de no borrar algún otro recurso, ya que pueden haber mas usuarios testeando:

https://11.chamilo.org/main/exercise/exercise.php?cidReq=19089&id_session=0&gidReq=0&gradebook=0&origin=

User: admin
Pass: admin

De esta manera, podamos descartar fallos en la generación o importación del fichero.

Un saludo.
