### ISSUE TITLE
Pour enseignant et Admin, possibilité d'éditer tous les certificats d'un cours

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#4381]
**Votre demande est liée à un problème en particulier? Décrivez-le nous...**
Lorsqu'un certificat est généré, seul l'apprenant (étudiant) a accès à son certificat.
S'il ne retourne pas dans cahier de notes, il n'obtient pas son certificat.
Pour pouvoir lui envoyer, il est alors nécessaire de se connecter en tant que l'apprenant pour lui éditer son certificat.
Avoir la possibilité de voir l'ensemble des certificats générés permettrait de faire un envoi grouper sans avoir à faire des connexions multiples.

**Décrivez la solution que vous aimeriez trouver dans Chamilo**
Dans la partie "Certificats" de cahier de notes : avoir un bouton du style "visualiser les certificats obtenus".

**Contexte additionnel**
Version actuelle de Chamilo : 1.11.16
OS basé sur Linux (mais fonctionne pareil sous Windows)

**Comment by NicoDucou** [comment]
Bonjour @Coursenligne 

Dans le cahier de notes, comme professeur du cours il y a l'icône 
![image](https://user-images.githubusercontent.com/6579268/203338343-88079d4c-3ad4-4c8e-acfe-39c3fe5242bf.png)
Qui amène à la page main/gradebook/gradebook_display_certificate.php qui montre tous les certificats des apprenants de ce cours.
Il y a en haut l'icône 
![image](https://user-images.githubusercontent.com/6579268/203338568-4b9ab442-caa1-441d-b87d-7435591853e5.png)
 qui permet de générer les certificats des apprenants qui ne seraient pas encore généré alors qu'ils ont validé le cours.

Merci de confirmer que cela correspond à la demande et de la fermer si c'est le cas.

**Comment by Coursenligne** [comment]
Bonjour @NicoDucou 
Merci de la précision.
Je clos le sujet car effectivement, cela répond à la demande.
Désolé de ma réponse tardive.
Bonnes fêtes à toute l'équipe de Chamilo !
