### ISSUE TITLE
troubles editing learning path in 1.11.16 with php8

### ISSUE THREAD

**Issue by Morepizza1** [chamilo/chamilo-lms#4382]
Editing the learning paths in version 1.11.16 with php8 doesn't work correct. 

E.g. it is impossible to put a pdf document from the document folder in the learning path, because the document folder has no documents in the learning path. There are also other problems with the learning path.

 - OS: W7
 - Browser: Opera latest

**Server
 - OS: Linux ...
 - Version of Chamilo:  1.11.16
 - Version of PHP: 8.1

**Comment by nosolored** [comment]
Chamilo 1.11.16 is not fully compatible with PHP 8, PHP 7.4 is recommended
More info: https://forum.chamilo.org/viewtopic.php?f=52&t=11844

**Comment by AngelFQC** [comment]
I tried with the tar.gz package in a docker container configured for PHP8 and the PDF files were uploaded correctly
Then I tried with a container for PHP8.1 I can't use Chamilo due to dependency issues

**Comment by xam1234** [comment]
@jwarnier @AngelFQC Any final date for 1.11.18 release ?

**Comment by xam1234** [comment]
@ywarnier @AngelFQC Any final date for 1.11.18 release ?

**Comment by ywarnier** [comment]
Not yet :-)

**Comment by Morepizza1** [comment]
With chamilo 1.1.16 and php 8.0, there is also a problem with changing existing multiple choice questions. 
The possible answers are not more visible if you want to edit them.

**Comment by Coursenligne** [comment]
Php 8 is not really recommended with 1.11 :)
I installed 1.11.20 under php 7.4 and switched to php 8.1.
I have to perform extra tests but it seems working fine.
If needed, I revert to PHP 7.4, which fully works.
