### ISSUE TITLE
BUG : Uncopied test questions in copied course

### ISSUE THREAD

**Issue by oneill78** [chamilo/chamilo-lms#4383]
Hello,

I looked at the documentation and I couldn't find an explanation for the bug found.

### Current result
When copying a course into a new empty course created beforehand, the tests (exercises) are created but the questions are not.
This observation is valid for exercises that have been incorporated into a course or left in direct access in "exercises".
In the case of a course, the exercise appears well as well as the button "Start the test" but when you click, it specifies "There are no questions in this exercise".

### Expected result
That the questions that make up the exercise in the original course are also copied into the exercise of the copied course.

### Steps to reproduce
1) create one or more exercises in a course
2) create an empty course to make a copy
3) in the initial course, make a copy by going to "maintenance" and selecting the empty course. Option checked: "copy all course sections" or "choose sections...". In both cases the result is the same.
4) check the exercises in the copied course and note that the questions are non-existent when you go to edition or when you launch the test.

FYI, I reproduced the procedure in 2 different chamilo platforms and the malfunction is the same.

While digging into the problem, I examined the database and in the "c_quiz_rel_question" table the "question_id" fields are all 0 for the copied questions. They are therefore not recognized by Chamilo.
In the "c_quiz_question" table, the "id" fields of the copied questions are all "NULL".

I hope this additional information will help you find the problematic line of code in order to fix this bug.

### Chamilo version
1.11.16

Thanks in advance for your feedback and how to fix this.
Lionel

_________________________________

Message en français
Bonjour,

J'ai regardé la documentation et je n'ai pas trouvé d'explication au bug constaté.

### Résultat actuel
Lors de la copie d'un cours dans un nouveau cours vide créé préalablement, les tests (exercices) sont bien créés mais les questions ne le sont pas.
Ce constat est valable pour les exercices qui ont été incorporés dans un parcours ou laissés en accès direct dans "exercices". 
Dans le cas d'un parcours, l'exercice apparait bien ainsi que le bouton "Démarrer le test" mais lorsqu'on clique, cela précise "Il n'y a aucune question dans cet exercice".

### Résultat attendu
Que les questions qui composent l'exercice dans le cours initial soient également copiées dans l'exercice du cours copié.

### Étapes pour reproduire
1) créer un ou plusieurs exercices dans un cours
2) créer un cours vide pour faire une copie
3) dans le cours initial, faire une copie en allant dans "maintenance" et en sélectionnant le cours vide. Option cochée : "copier toutes les sections du cours" ou "choisir les sections...". Dans les 2 cas le résultat est le même.
4) vérifier les exercices dans le cours copié et constater que les questions sont inexistantes lorsqu'on pass en édition ou qu'on lance le test.

Pour info, j'ai reproduit la procédure dans 2 plateformes chamilo différentes et le dysfonctionnement est le même.

En creusant le problème, j'ai examiné la base de données et dans la table "c_quiz_rel_question" les champ "question_id" sont tous à 0 pour les questions copiées. Elles ne sont donc pas reconnues par Chamilo.
Dans la table "c_quiz_question" les champs "id" des questions copiées sont tous "NULL".

J'espère que cette information complémentaire vous permettra de trouver la ligne de code qui pose problème afin de corriger ce bug.

### Version de Chamilo
1.11.16

Merci par avance de votre retour et de la façon de corriger cela.
Lionel

**Comment by oneill78** [comment]
On creusant le problème, j'ai examiné la base de données et dans la table "c_quiz_rel_question" les champ "question_id" sont tous à 0 pour les questions copiées. Elles ne sont donc pas reconnues par Chamilo.
Dans la table "c_quiz_question" les champs "id" des questions copiées sont tous "NULL".
Lorsque j'affecte le n° "id" identique à celui du champ "iid" et que je fais la même chose dans la table "c_quiz_rel_question", les questions apparaissent dans le cours copié !

J'espère que cette information complémentaire vous permettra de trouver la ligne de code qui pose problème afin de corriger ce bug.

**Comment by Coursenligne** [comment]
Voir **Imported courses document links and tests not working #3981**, où il y a une solution fonctionnelle.
Espérant que c'est le même souci.

**Comment by NicoDucou** [comment]
Comme indiqué au dessus on voit l'explication dans l'issue référencée et la correction est présente dans 1.11.x et le sera donc dans 1.11.18 à sa sortie.
