### ISSUE TITLE
La mejor manera de eliminar una sesión

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#4391]
Hola.
Quisiera saber si al eliminar una sesión se elimina toda la información de la base de datos o si es mejor eliminar previamente los usuarios, ejercicios, lecciones, etc. para que no se acumulen en la DB registros innecesarios.
Saludos.

Chamilo 1.11.16

**Comment by BorjaSanchezBeezNest** [comment]
Hola @jolufe,

Al eliminar una sesión, solo se elimina dicha sesión. Los usuarios, ejercicios, lecciones, etc. inscritos en esa sesión, no se eliminan al borrar la sesión, ya que son independientes, aunque estén "agrupados" en la sesión.

Para borrar un curso, tendrá que borrar dicho curso en su sección correspondiente, lo mismo par aun usuario, etc.

Entonces, para el caso que comentas, puedes eliminar la sesión, y posteriormente, eliminar aquellos cursos, usuarios, lecciones, etc. que también desees eliminar.

Un saludo.

**Comment by jolufe** [comment]
Hola @BorjaSanchezBeezNest 

Muchas gracias por tu respuesta. Entiendo la necesidad de eliminar por separado las sesiones, los usuarios y los cursos.

Lo que no me queda claro es si al eliminar una sesión se eliminan también todos los componentes propios de esa sesión. 

Por ejemplo: en una sesión puede haber lecciones, foros, grupos, chats, documentos, respuestas a ejercicios y encuestas que no pertenecen a un curso sino solamente a la sesión. ¿Todo eso se elimina automáticamente de la DB eliminando la sesión?

**Comment by BorjaSanchezBeezNest** [comment]
Hola de nuevo, @jolufe 

En el caso de los componentes propios de una sesión, es algo mas complejo.

Aunque si se eliminan varios de los elementos creados dentro de ella, algunos se mantienen, si son compartidas por otras partes, o se quedan "residuales" en BBDD, ya que tienen un proceso de validación final mas extenso. Esto se mejorará en las futuras versiones de Chamilo.

Te dejo la linea de código donde comienza el eliminado de una sesión, donde puedes comprobar que elimina:

https://github.com/chamilo/chamilo-lms/blob/1.11.x/main/inc/lib/sessionmanager.lib.php#L1827

Así como una explicación detallada, en francés, de las sesiones en Chamilo:

https://beeznest.com/fr/2016/08/11/chamilo-tips-quest-ce-quune-session

Saludos!

**Comment by jolufe** [comment]
Muchas gracias @BorjaSanchezBeezNest 

Muy buena y clara la información. Es lo que necesitaba saber.

Un cordial saludo.
