### ISSUE TITLE
Bug affichage Création Exercices Dans Parcours

### ISSUE THREAD

**Issue by melimelo45** [chamilo/chamilo-lms#4397]
**Describe**
Quand je me rends sur la page de modification d'un parcours dans un cours, l'affichage se décale sur la droite de l'écran et je n'ai plus accès aux champs proposés. 

**To Reproduce**
1. Go to MonCours
2. Click on Parcours
3. Click on Editer

**Screenshots**
![image](https://user-images.githubusercontent.com/84734994/192066576-277a202d-c5f2-4cd4-919c-2a8826cef22b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  : 
        - chrome Version 105.0.5195.127 (Build officiel) (64 bits)
        - Firefox 
        - Edge

**Server
 - Version of Chamilo:  1.11.16

**Additional context**
Quand j'affiche l'inspecteur de la page, que je décoche min width du fieldset ça remet l'affichage au milieu de page

**Comment by NicoDucou** [comment]
Bonjour @melimelo45 
Le problème ne se reproduit pas sur la plateforme de test 11.chamilo.org, Je pense que c'est lié à un problème avec la feuille de style qui ne s'applique pas bien.
On peut voir sur https://11.chamilo.org/main/lp/lp_controller.php?action=add_item&type=step&lp_id=360&cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin= que tout s'affiche correctement :
![image](https://user-images.githubusercontent.com/6579268/206155427-d18bee0a-e1ff-4872-b4b6-0cad62507613.png)

Je te laisse revenir vers nous si tu reproduis le problème sur 11.beeznest.com (accès avec admin comme login et comme mot de passe).

**Comment by ywarnier** [comment]
Closing (no feedback)

**Comment by JanaKora** [comment]
Im experiencing exactly the same problem as described above. 
My OS is Linux - Ubuntu 
Browser: Firefox
Server: I have installed Chamilo on our server.
Thanks for any ideas.
