### ISSUE TITLE
Error para obtener un certificado dentro de una lección

### ISSUE THREAD

**Issue by saragaes** [chamilo/chamilo-lms#4400]
**Describe el problema**
Creé un curso con tres lecciones. Cada sección contiene 1 documento y 1 ejercicio, con configuración de elemento anterior como prerequisito. En última lección (lección #3) incluí al final el certificado del curso, para que los alumnos puedan descargarlo desde la vista de estudiante allí mismo en la lección, una vez completen las tres lecciones con sus documentos y ejercicios.

En la sección de evaluaciones, incluí esas tres lecciones como un componente de evaluación en línea, cada una con ponderación del 33.33, y activé la opción de generar un certificado cuando se completen las lecciones con puntuación mínima del 80%. 

No obstante, cuando curso las tres lecciones en la vista de estudiante y las completo con una puntuación del 100% , en la lección #3 al llegar al certificado, aparece un mensaje de error (ver abajo), donde en teoría debería salir la opción de "descargar certificado". Únicamente aparece la opción para "descargar certificado" desde la vista de estudiante si voy a la sección de evaluaciones.

**Capturas de pantalla**
![screenshot error certificado](https://user-images.githubusercontent.com/113041169/192821774-4b718c09-d6ac-4270-8c6d-10218cd94327.png)

**Escritorio:**
Sistema operativo : macOS Catalina versión 10.15.7
Navegador: Chrome versión 105.0.5195.102

**Servidor:**
 Versión de Chamilo: 1.11.16

**Comment by NicoDucou** [comment]
Hola @saragaes 
El certificado incluido en la leccion solo funciona si se pone como requisitos en herramienta de evalucion solo esta leccion. No se puede poner otras cosas que no sea la leccion misma.
En tu caso deberia de poner una dependencia entre las lecciones, es decir la leccion 2 depende de la leccion 1 y la leccion 3 depende de la leccion 2 y en la evaluacion solo poner la leccion 3 como componente de evaluacion en linea.

Seria una nueva funcionalidad si permitimos el uso de otro comportamiento.

Saludos
