### ISSUE TITLE
Migrando Chamilo de un proveedor de hosting a otro

### ISSUE THREAD

**Issue by astrorawson** [chamilo/chamilo-lms#4411]
Tengo una instalación de Chamilo Versión 1.11.10 funcionando en un servidor perteneciente a un proveedor de servicio de hosting. 
Como el servicio de este proveedor es muy malo, contraté otro proveedor y realicé la migración de la instalación al nuevo servidor siguiendo las instrucciones de [este post.](https://github.com/chamilo/chamilo-lms/issues/3520)

Como  el viejo sitio aún está operativo, el nuevo server tiene un URL distinto al original. Además, poe restricciones impuestas por el nuevo proveedor, la base de datos tiene un nombre distinto al de la instalación original, pero modifiqué el archivo app/config/configuration.php para contemplar esas diferencias.

El problema es que cuando intento acceder a Chamilo en el nuevo server, sólo aparece una página en blanco que si la inspecciono con las herramientas del navegador, se debe a que se ha producido un error 500 (Internal Server Error)

Para saber si es posible acceder a la base de datos, hice una pequeña aplicación que se conecta con la base de datos y muestra un par de columnas de la tabla **user**, y eso funciona sin problemas, lo que indica que la base de datos está accesible en el nuevo server (localhost, puerto 3306), y que usando el nuevo nombre de la base de datos,  el nombre de usuario y password del usuario administrador de la base de datos que definí en  app/config/configuration.php, Chamilo debería poder conectarse también.

Quisiera saber si es posible habilitar algún tipo de debugging o si existe algún archivo de log donde pudiese ver qué es lo que está sucediendo, y en caso de no ser posible, si alguien podría darme alguna indicación que cómo seguir.

Muchas gracias!

**Comment by ywarnier** [comment]
El error 500 es poco probable que esté relacionado con la base de datos.
El error 500 debería también darte mensajes en el archivo de log de errores del servidor web (en tu panel de hosting o, si tienes acceso a una terminal, en algo de /var/log/apache/ o /var/log/httpd/.
Debido a la operación que has realizado, es probable que el problema sea las variables root_sys y root_web dentro de tu configuration.php.
Ojo que, como comenté en la #3520, será necesario también modificar archivos y el contenido de la base de datos con la nueva URL, que esto requiere comandos complejos como "sed" en linux (remplazo masivo entre distintos archivos).

**Comment by astrorawson** [comment]
Hola Yannick, muchas gracias por tu respuesta.
Efectivamente, en la migración introduje no uno sino dos problemas en la variable root_sys del archivo configuration.php: El primer error era que el path absoluto es totalmente diferente al del antiguo servidor de hosting y yo había cambiado sólo una  componente de dicho path, basándome en la información que me entregó el nuevo proveedor de hosting.
Para averiguar por mí mismo el path absoluto, tuve que crear un archivo llamado abs_path.php en el nuevo servidor, con el siguiente contenido:

<?php echo __FILE__; ?>

Al acceder a través del navegador,  esto devuelve un string con el path absoluto a este archivo, así es que lo copié y lo coloqué  en la variable root_sys del archivo configuration.php
El segundo error fue que olvidé colocar el "/" final del path absoluto, con lo cual el error 500 continuó hasta que me dí cuenta, viendo el uso de la variable root_sys más abajo en el archivo configuration.php.
Luego de corregir este segundo error, el error 500 desapareció y Chamilo ya muestra la página de login.
Creo que se puede cerrar esta consulta.
Muchas gracias nuevamente y saludos!
