### ISSUE TITLE
When hiding a language the course using this language should be set to the default plateform language.

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4418]
at the moment on the page main/admin/languages.php if you dsactivate a language (clicking on the open eye in the property column) it verifies if a user is using this language and if it is the case it show a message at the top of the page to indicate :

> There are users using this language. Do you want to disable this language and set all this users with the default portal language?
>  Make unavailable

This message correspond to the language variable  "ThereAreUsersUsingThisLanguageYouWantToDisableThisLanguageAndSetUsersWithTheDefaultPortalLanguage".

The problem is that it does not verifies if a course is using this language and this generate problem. So we should check if a course is using the language we are about to make unavailable and if so indicate to the user the those course will be associated to the default plateform language.

To do so we have the stop using the actual language variable and create a new one to indicate the users and courses would be updated to the portal language and then make the change for both users and courses.

**Comment by ywarnier** [comment]
Variables added to the language pack and PR merged.
@NicoDucou can you test it and close the issue ?

**Comment by NicoDucou** [comment]
@BorjaSanchezBeezNest 
I just created a course in indonesian and then went to the plateform language management page and disabled indonesian. It show the message indicating there are users or courses with this language. I validate to make the language unavailable and I get a 500 errors and in the logs we can see :

`[Wed Nov 23 15:01:31.858096 2022] [php7:error] [pid 1249723] [client 2a01:e0a:3d7:8680:e5b1:4562:4093:fd8a:50652] PHP Fatal error:  Uncaught TypeError: Return value of CourseManager::updateAllCourseLanguages() must be of the type bool, object returned in /var/www/testing4.beeznest.com/www/main/inc/lib/course.lib.php:5087\nStack trace:\n#0 /var/www/testing4.beeznest.com/www/main/admin/languages.php(244): CourseManager::updateAllCourseLanguages()\n#1 {main}\n  thrown in /var/www/testing4.beeznest.com/www/main/inc/lib/course.lib.php on line 5087, referer: https://testing4.beeznest.com/main/admin/languages.php`

I just tested it with this course : https://testing4.beeznest.com/main/course_info/infocours.php?cidReq=COURSEININDONESIAN&id_session=0&gidReq=0&gradebook=0&origin=
The course language is correctly changed it is just the 500 error that makes it incorrect.

**Comment by BorjaSanchezBeezNest** [comment]
Hi @NicoDucou. Thanks for reporting. I have done a PR fixing the issue (fixing the return type of a implicated function).

**Comment by NicoDucou** [comment]
It is now all good with the last PR. I just accepted it so we can close this issue now.
