### ISSUE TITLE
Switch menu items location for RTL language

### ISSUE THREAD

**Issue by guymass** [chamilo/chamilo-lms#4433]
I am working on translating the Chamilo system to Hebrew language which is currently running on my site at
learn.feisafe.com

I will gladly share the language file once I am done. However I noticed that even when switching to RTL language like Hebrew I still have an issue with the main top menu where the items remain in their respective english location, thus making the "Home" button appear last in the row. I would very much like to change the order of the items to better reflect our RTL language.

Best regards and thank you for an amazing script, God bless you.

**Comment by guymass** [comment]
OK finally the translation to fully Hebrew system is done, home this helps, please let me know if there is anything else needs changing/fixing. I tested it on my site and it works fine. Here is the language file for the  Hebrew language.
[trad4all.inc.php.zip](https://github.com/chamilo/chamilo-lms/files/10060503/trad4all.inc.php.zip)

**Comment by ywarnier** [comment]
I added an additional fix here: https://github.com/chamilo/chamilo-lms/commit/2a2a5fc24fc3449906562f7f569cc2132fb5bebe

**Comment by ywarnier** [comment]
Forgot to say: this will be part of the Chamilo 1.11.18 release, soon.
