### ISSUE TITLE
RTL Hebrew translation of top menu

### ISSUE THREAD

**Issue by guymass** [chamilo/chamilo-lms#4434]
I am translating the system to Hebrew RTL and notices the two menu items of "Administration" and "Reporting" do not accept the translation string. Here is a screen shot.

![Screen Shot 5783-01-29 at 21 49 24](https://user-images.githubusercontent.com/58882903/197603004-96b6b38f-1bce-467c-b352-c7124f65b79c.jpg)

Also I would like to replace the menu items position to reflect better the RTL language.

**Comment by ywarnier** [comment]
Are you translating locally on your install ? It would be great to have your final translation file to integrate officially to Chamilo.

**Comment by guymass** [comment]
Yes my site is running locally on my computer at the moment but once I finish the translation I can upload the file here and someone can add it to the main branch.
