### ISSUE TITLE
Error trying to connect with mobile app

### ISSUE THREAD

**Issue by guymass** [chamilo/chamilo-lms#4437]
I am trying to use the mobile app to connect to my site but I get an error indicating the app cannot connect to the server.

Site is running on https and I have access from any browser so maybe im just new to this system and forgot to enable something or there some other issue I am not aware of.

What would be the server name in the mobile app and is there something I need to enable beforehand?

**Comment by ywarnier** [comment]
What mobile app are you using ? There is no "official" Chamilo app at the moment, only code to be compiled from the chamilo/chamilo-mobile project.

**Comment by guymass** [comment]
The one that appears on the Google store.

**Comment by ywarnier** [comment]
This one is hardcoded to point to https://campus.chamilo.org. you can contact the editors at nosolored.com to ask for a customized version, or compile your own following the instructions at https://github.com/chamilo/chamilo-mobile

**Comment by guymass** [comment]
OK much thanks for the info.
