### ISSUE TITLE
No password verification in csv import and save_user webservice 

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4446]
Since a few weeks we changed the default configuration in Chamilo to make the password check mandatory when creating a user because the variable CHECK_PASS_EASY_TO_FIND is set to true by default in app/config/profile.conf.php
This applies now to all kind of user creation.
This is a problem when creating a lot of users based on an external source that does not have the same password criteria.

So the aim is to set by default that there should not be a password verification for users creation when creating a user through CSV import (main/admin/user_import.php) and also through rest webservice (https://github.com/chamilo/chamilo-lms/wiki/rest-webservices#save_user)

Tested on Chamilo 1.11.x on 2022/10/15

**Comment by ywarnier** [comment]
I don't find any reference to a password checker in the `main/admin/user_import.php` script, and the SAVE_USER WS uses UserManager::create_user() as well, which doesn't put a check on the password's complexity.
Could you elaborate on how to reproduce ?

**Comment by NicoDucou** [comment]
I just check the original task and I can not find more details.
I tried to reproduce the problem and it does not occur for me.
Checking the code I could not find neither how it could happen.
I've asked more details in the original task but I close this issue because I do not see how to reproduce.
