### ISSUE TITLE
New checkbox in CSV importation to force user password change on first login

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4447]
In app/config/configuration.php it is possible to activate this option :
```
// Ask user to renew password at first login.
// Requires a user checkbox extra field called "ask_new_password".
//$_configuration['force_renew_password_at_first_login'] = true;
```

If this option is activated then on the page to import user through CSV (main/admin/user_import.php) add a checkbox "force renew password at first login".
If this checkbox is marked then for all the user that will be imported the extra field  "ask_new_password" should be set to true so that the user will have to renew it's password.

**Comment by ywarnier** [comment]
Sent through 64830792a89e85686cadb3b267ab1cdbf19cbe27
