### ISSUE TITLE
Visibilidad de secciones en las sesiones

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#4467]
Hola.

Quisiera saber si, dentro de una sesión, hay alguna manera de que algunas secciones sean visibles para el profesor y no para los alumnos, como ocurre en un curso base.

Puntualmente, necesito que en una sesión el profesor pueda acceder a las secciones Ejercicios, Documentos y Enlaces, pero que no estén visibles para los alumnos.

Gracias.

Chamilo 1.11.16
S .O. Windows 10

**Comment by NicoDucou** [comment]
Hola @jolufe 
Ya existe esta funcionalidad, se tiene que activar en app/config/configuration.php con la opcion siguiente :
```
// Course tools visibility edition in sessions
$_configuration['allow_edit_tool_visibility_in_session'] = true;
```
Esto permite que en la sesion se vea solo las herramientas visibles del curso base y cada herramienta tenga el ojo para poder reducir en la sesion las herramientas visibles por los alumnos.

Saludos
