### ISSUE TITLE
Bloqueo al Terminar el ejercicio / Exercises are blocked at the end

### ISSUE THREAD

**Issue by aperet** [chamilo/chamilo-lms#4479]
ES: A algunos usuarios cuando realizan los ejercicios se les bloquean al terminarlos. Les sale un icono de un candado. Los usuarios hacen los ejercicios desde diversas plataformas. Utilizan cable y wifi

EN: Some users when they perform the exercises are blocked when they finish them. They get an icon from a padlock. Users do the exercises from various Os systems . They use cable and wifi

Servidor
 - Sistema operativo : Windows Server 2019 Datacenter Edition (64 Bit)
 - Versión de Chamilo:  Last
 - Versión de PHP: 7.4.32

**Comment by NicoDucou** [comment]
Hola @aperet 

Cuando indicas la version e Chamilo "Last" esto queire decir desde github en la rama 1.11.x o la version del paquete 1.11.16 ?
No creo que sea relacionado con la version por lo que indicas pero es solo para estar seguro.
Por lo que indicas puede ser un problema de connexion al momento de enviar el final del ejercicio o tal vez que los usuarios se han ido a otra sesion y/o curso en otra ventana y Chamilo no tiene el contexto correcto para guardar la informacion del ejercicio.

Se tendria que hacer una analisis especifica porque como lo indicas es solo para algunos usuarios entonces Chamilo responde bien el la mayoria de los casos y ha algo especifico que pasa para que no funcione. Intentar verificar lo indicado arriba para tratar de indentificar lo que esta succediendo.

Es algo especifico a su integracion parece porque no se produce cuando lo probo.
Si logras a ubicar un caso especifico que se puede reproducir podremos tal vez encontrar una manera de evitarlo.
Esperamos tus comentarios para poder reproducir el caso.

Saludos

**Comment by aperet** [comment]
Gracias Nico, tengo la última versión, la 16. Había enfocado que el problema era por desconexión momentánea de wifi del alumno, pero por lo que me comentas ¿también suele suceder por cambio de ventana o utilización de otros recursos del portal?

**Comment by NicoDucou** [comment]
Si puede pasar cuando el contexto cambia y entonces Chamilo no lograr guardar los datos porque el contexto que se tiene en la sesion PHP no corresponde a lo del ejercicio y entonces no se encontra el ejercicio.
lo dejo cerrar la tarea si con estas indicaciones es suficiente para usted.
Saludos

**Comment by aperet** [comment]
Buenas.
Llevo 3 días con la nueva versión 18 y va bien.
