### ISSUE TITLE
Enabling the 2 LTI plugins generate a conflict

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4504]
When enabling the 2 plugins LTI : 
* ims_lti
* lti_provider

Then when you go to the lti_provider admin page (plugin/lti_provider/admin.php), the link on the "Add external tool" redirect to the wrong plugin  : "/plugin/ims_lti/create.php" but this only happens if both plugins are enabled.

The plateform keys link is also wrong, same thing it redirects to the other plugin : plugin/ims_lti/platform.php

Tested today on an updated Chamilo 1.11.x (20221222) can be tried here : https://testing1.beeznest.com/plugin/lti_provider/admin.php

**Comment by christianbeeznest** [comment]
Hi @NicoDucou ,

I see the template twig wasn't updating, I had to remove the cache from of app/cache to see the current changes. It is Ok now.

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 
Now it shows the correct link on the page https://testing1.beeznest.com/plugin/lti_provider/admin.php
But the problem occurs on https://testing1.beeznest.com/plugin/ims_lti/admin.php where the links are https://testing1.beeznest.com/plugin/lti_provider/create.php and https://testing1.beeznest.com/plugin/lti_provider/provider_settings.php

So by generating the twig again it generated it the other way round, but there is still a problem.

**Comment by christianbeeznest** [comment]
Hi @NicoDucou 

It is fixed that conflict with this PR https://github.com/chamilo/chamilo-lms/pull/4517

Thanks for confirmation

**Comment by ywarnier** [comment]
Reviewed, tested and approved.
