### ISSUE TITLE
Add color(varchar(20)) field to sys_calendar

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4514]
...and reduce field size of personal_agenda.color and c_calendar_event.color to varchar(20) too (through install and upgrade from 1.11). It is currently a 7 chars field representing a CSS color like  `#458b00`.

This is required to add control on color to the global agenda events as attempted in #4206.

**Comment by christianbeeznest** [comment]
The request is added in this PR https://github.com/chamilo/chamilo-lms/pull/4522
Thanks for confirmation.

**Comment by ywarnier** [comment]
PR approved
