### ISSUE TITLE
Problems when trying to import courses in chamilo from version 1.9.6 to 1.11.16

### ISSUE THREAD

**Issue by carloskehoe** [chamilo/chamilo-lms#4516]
I have problems when trying to import courses in chamilo from version 1.9.6 to 1.11.16. I do the export from the older version but when importing it from the newer version it only creates the title of the course and the rest is empty. no files or users

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a la versión antigua
2. Dar clic en administración
3. Bajar hasta exportar curso
4. seleccionar curso de la lista
5. Descargar el curso
6. Ir la version nueva
7. Dar clic en administración
8. Bajar hasta importar curso desde un fichero
9. Seleccionar el fichero
10. Importar el fichero
11. En la versión nueva ir a "Mis cursos"
12. Seleccionar el importado anteriormente
13. Abrirlo para ver los archivos.

**Comportamiento esperado**
Se espera que el curso contenga todos las lecciones, documentos y usuarios que tiene en la versión más antigua

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador chrome

**Servidor
 - Sistema operativo :  Linux Ubuntu 18.04
 - Servidor NGINX
 - Versión de Chamilo:  1.9.6 a 1.11.16]
 - Versión de PHP: 5.6

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
Hola @carloskehoe 
Es muy probable que esto simplemente no funcione por la "distancia" entre versiones, que implica muchos cambios de base de datos.
El procedimiento más confiable sería actualizar tu 1.9.6 a 1.10.8 (https://github.com/chamilo/chamilo-lms/releases/tag/v1.10.8) y luego a 1.11.16 (o .18 dentro de unos días). El problema de este proceso es más que todo que van con versiones distintas de PHP, pero con un poco de manipulación debería funcionarte. Siempre existen proveedores oficiales de servicios sobre Chamilo como último recurso.

No puedo considerar esto como una falla, porque pasaron literalmente 8 años entre 1.9.6 y 1.11.16, pero es probable que con el camino sugerido puedas recuperar los cursos. No digo que tenga que ser sin dificultades, pero si son cursos críticos, seguro vale la pena (siempre haciendo backups a cada paso).
