### ISSUE TITLE
Validación de plugin de Zoom

### ISSUE THREAD

**Issue by tegarduna** [chamilo/chamilo-lms#4537]
EL plugin de Zoom dejará de funcionar porque es de tipo JWT y es necesario que se cambie el modo de validación de la aplicación.
Nos indican esto de Zoom:
"The JWT app type will be deprecated on June 1, 2023. After this date, you will no longer be able to use your JWT apps.
We recommend that you create Server-to-Server OAuth or an OAuth app to replace the functionality of a JWT app in your account.
Read more about the change https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements/#support-for-x-www-form-urlencoded-content-type-headers and how to do OAuth via the Authorization header https://marketplace.zoom.us/docs/guides/auth/oauth/#step-2-request-access-token."

**Comment by ywarnier** [comment]
Should be working now.
