### ISSUE TITLE
RTC audio recorded should pass the course and session as parameters and not use the PHP session information

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4547]
In an exercise with an oralexpression type question it open the rtc recording javascript to launch and save the file.
The rtc recording audio in main/inc/lib/javascript/record_audio/record_audio.js is calling the file main/inc/ajax/record_audio_rtc.ajax.php
But it does not have the course nor the session in the parameters so it uses the course and session information from the PHP session and generate an incorrect path and filename to save the audio.
This makes that when the exercise is saved the audio is not associated to the attempt.

The course and session information should be passed to the call to main/inc/ajax/record_audio_rtc.ajax.php to make sure it will be for the correct course and correct session.

To reproduce the problem, start an exercise with an oralexpression question, leave the tab open and in another tab open a new course. Get back to the original tab and record your audio. The audio will be saved in the new course instead of the exercise course.

Tested on https://testing4.beeznest.com/main/exercise/overview.php?cidReq=NICODU&id_session=0&gidReq=0&gradebook=0&origin=&exerciseId=329 with Chamilo 1.11.x of today 2023/01/18

**Comment by christianbeeznest** [comment]
Hi @NicoDucou ,

The request is done in this PR https://github.com/chamilo/chamilo-lms/pull/4550

Thanks for confirmation.

**Comment by NicoDucou** [comment]
All good for me after testing and clearing cache on server and in the browser.
