### ISSUE TITLE
Delete  a copy of question

### ISSUE THREAD

**Issue by SerhiiPavlyk** [chamilo/chamilo-lms#4555]
After adding the question using "Recycle existing questions", it is impossible to remove it from test where it was added.

1. Go to "new test"
2. Click on 'edit'
3. Click on 'Recycle existing questions'
4. Add question from "old test"
6. See error, you can't delete copy of question in "new test".

This is added question from "old test", there is not delete button
![image](https://user-images.githubusercontent.com/86359703/213888544-8a46b936-94bd-46f9-baaa-31bf54f3ecbe.png)
This new question created in "new test", it can be deleted
![image](https://user-images.githubusercontent.com/86359703/213888594-1e36c8e7-ef94-41a7-b4c7-193cd8b7aa4d.png)

Server
campus.chamilo.org

**Comment by ywarnier** [comment]
I guess that would be in 1.11.18 then (if it's from just now on campus.chamilo.org)

**Comment by SerhiiPavlyk** [comment]
I hope it will happen as soon as possible. It is very difficult to work without this fix

**Comment by ywarnier** [comment]
Hi @SerhiiPavlyk 
We've just uploaded the following changes which should fix this issue. Let us know (if you can apply the patch and test it).
https://github.com/chamilo/chamilo-lms/commit/fdb5df8e0967dff6af4b73e2105a9f7c8dff162f
https://github.com/chamilo/chamilo-lms/commit/0f2cef4e5fb2e32200bf736cbc462608cf9e40b0
https://github.com/chamilo/chamilo-lms/commit/03c2cc020bef01d64a52916c6bc246ed0a47c8ea
https://github.com/chamilo/chamilo-lms/commit/27326a28940044b83eb4c01e7a0cf57ab2a8c7e2

**Comment by SerhiiPavlyk** [comment]
@ywarnier 
I'm gleeful to hear that you managed to fix this issue, but unfortunately I'm using campus.chamilo.org and I think I can't update campus.chamilo.org )))

**Comment by ywarnier** [comment]
@SerhiiPavlyk campus.chamilo.org has been updated for you to try...

**Comment by SerhiiPavlyk** [comment]
@ywarnier, yep, I saw. I tried it works. Thanks for much.
