### ISSUE TITLE
Chamilo upgrade from v1.11.16 to v1.11.18

### ISSUE THREAD

**Issue by GaneshKandu** [chamilo/chamilo-lms#4558]
**Describe**

There is a database changes in [v1.11.18](https://github.com/chamilo/chamilo-lms/releases/tag/v1.11.18) compared to v1.11.16
table ``c_attendance_result_comment`` and ``signature`` column in ``c_attendance_sheet`` table.

I am trying to upgrade chamilo from v1.11.16 to v1.11.18 using upgrade document mentioned here
[3.1 Upgrading from Chamilo 1.11.x (Minor version)](https://campus.chamilo.org/documentation/installation_guide.html#3._Upgrade)

Upgrade method doesn't update database according to v1.11.18 after upgrade 
no ``c_attendance_result_comment`` table were created and ``signature`` column in were created in ``c_attendance_sheet`` table.

**To Reproduce**
1. upgrade chamilo from v1.11.16 to v1.11.18

**Expected behavior**
``c_attendance_result_comment`` table should be created and ``signature`` column should be added in ``c_attendance_sheet`` table. after upgrade

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Firefox

**Server
 - OS: Centos 7.9
 - Version of Chamilo:  1.11.8
 - Version of PHP: 7.2.34

**Additional context**
No error

**Screenshot***

![image](https://user-images.githubusercontent.com/12833130/214225155-8e106cde-9280-487c-87b4-8b7a981205bd.png)

Can you check and let us know if Database should be updated after upgrade or not

**Comment by ywarnier** [comment]
Hi @GaneshKandu 
The table changes should not be made automatically (a new installation should not add those table+field either). Do you see them in an installation from scratch ?

**Comment by GaneshKandu** [comment]
Got it, Thanks !

**Comment by ywarnier** [comment]
The creation in a new install shouldn't be there, but it's acceptable considering there's a check.
The next major version, Chamilo 2.0, in preparation for later this year, should sanitize all these minor differences and ensure the database schema is exactly the same.
Thanks for reporting, in any case (and for being so proactive about supporting new versions).
