### ISSUE TITLE
Error en plugin Zoom Chamilo 1.11.18

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#4570]
**Describe el problema**
Los estudiantes no pueden acceder a la conferencia.
Si se programa la sesión de Zoom sin marcar la opción de firmar asistencia, cuando el estudiante quiere acceder le aparece el mensaje de "Conferencia no disponible"
Si se marca la opción de firmar asistencia lo que obtiene el usuario es un error 500 y en el log PHP aparece este aviso:
Fatal error: Uncaught Error: Call to a member function getSignature() on null in /plugin/zoom/join_meeting.php:56 Stack trace: #0 {main} thrown in /plugin/zoom/join_meeting.php on line 56

**Cómo reproducir**
Pasos para reproducir el problema:
Es necesario disponer de una cuenta profesional de Zoom.
Activar el plugin de Zoom y programar una sesión de videoconferencia en un curso, probar marcando la opción de firmar asistencia y sin marcarla.
Abrir la sala con un profesor o administrador
Intentar acceder con un alumno

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo :  Windows 10
 - Navegador: Chrome, Firefox, ultimas versiones

**Servidor
 - Sistema operativo : Linux Debian
 - Versión de Chamilo:  1.11.18 (actualizado con los últimos cambios de github, y tras composer update)
 - Versión de PHP: 7.4

**Contexto adicional**
Al acceder con el administrador no se produce ningún error y se abre Zoom perfectamente.
En otra plataforma Chamilo con el código de la 1.11.x de octubre 2022 ocurre lo mismo, y hay que decir que en esa plataforma estaba funcionando perfectamente el plugin de Zoom, incluyendo la opción de firmar asistencia, hasta hace unos días, que falló de repente sin modificaciones en la plataforma.

**Comment by nosolored** [comment]
Gracias, @AngelFQC , hemos probado los cambios y ya no devuelve ese error con la firma, aunque al alumno le sigue mostrando el mensaje de que la conferencia no está disponible y no puede entrar. Debe haber alguna otra cosa fallando.

**Comment by AngelFQC** [comment]
Hola, @nosolored
Me parece que el estudiante no puede iniciar porque el profesor no ha empezado aún la videollamada.
Probaron el acceso del estudiante habiendo entrado el profesor antes?

**Comment by nosolored** [comment]
Hola, sí, lo hemos tenido en cuenta y todas las pruebas las hemos hecho abriendo antes la sala el profesor, siempre lo hacemos así, pero sigue apareciendo el mensaje de conferencia no disponible.

**Comment by AngelFQC** [comment]
Hola, @nosolored 

He probado y no reproduzco el problema

Como estudiante veo la página de la videollamada y me permite firmar la asistencia
![Screenshot 2023-02-09 at 17-58-22 My Organisation - My campus - New Zoom - 88430171080](https://user-images.githubusercontent.com/1697880/217958690-217fb864-4ab7-4d17-a838-0c0efc4ae814.png)

Después de firmar la asistencia, veo el botón de entrar a la videollamada
![Screenshot 2023-02-09 at 17-59-08 My Organisation - My campus - New Zoom - 88430171080](https://user-images.githubusercontent.com/1697880/217958797-17d7dcf6-3302-42a0-a7a1-7c92bd3a5a7b.png)

Y el botón de unirme, me deja ingresar a Zoom 
![Screenshot 2023-02-09 at 17-59-25 Videoconferencias conferencias web seminario web uso compartido de pantalla](https://user-images.githubusercontent.com/1697880/217958955-48f26cef-5b84-4cb9-8c17-99de3c827390.png)


![Screenshot 2023-02-09 at 18-01-38 Testing access](https://user-images.githubusercontent.com/1697880/217959000-8b26cb5d-3d42-498f-8030-6bfd22bf9644.png)

Lo que podrían revisar es si el webhook está bien configurado para que actualice el estado del meeting/webinar en la base de datos de chamilo. Para que los estudiantes puedan ver el botón de unirse, el status debe estar en `started`. De lo contrario, en Chamilo no están llegando los datos desde zoom  hacia `plugin/zoom/endpoint.php`
![Screenshot from 2023-02-09 17-58-12](https://user-images.githubusercontent.com/1697880/217959150-6ad3b552-6bb7-4779-9865-ddfecebc3afa.png)

**Comment by nosolored** [comment]
Hola
En status siempre se nos muestra "waiting".
Lo tenemos configurado con JWT.
¿Lo estáis probando vosotros con Oauth?

**Comment by AngelFQC** [comment]
> ¿Lo estáis probando vosotros con Oauth?
Sí. Ahora tenemos esa configuración (para probar la nueva versión). Pero, tengo entendido que JWT sigue funcionando incluso con sus Event Subscriptions

**Comment by nosolored** [comment]
Hemos tratado de configurar también por Oauth pero en Zoom no sabemos qué URL hay que indicar en el apartado "Redirect URL for Oauth", y si ponemos la dirección de la plataforma seguida de /plugin/zoom/endpoint.php nos dice que la URL no es válida y no permite crear la app. Tampoco encontramos dónde está el "Account ID" que pide Chamilo en los parámetros.
¿Sabéis qué debemos poner en esos apartados? En las instrucciones del plugin no lo vemos.

**Comment by AngelFQC** [comment]
Y logran validar la URL del endpoint?

![imagen](https://user-images.githubusercontent.com/1697880/218148189-06e4bbdc-d7ad-4433-a46d-30bedc07eedc.png)

**Comment by nosolored** [comment]
No, en JWT no valida la URL, indica "URL validation failed"

**Comment by AngelFQC** [comment]
Si no lo valida, es porque no coinciden los token que está enviando Zoom con los que chamilo está generando. Quizás el secret token no es correcto.

**Comment by ywarnier** [comment]
Con autorización de @nosolored, cierro esta tarea. El problema no se llega a definir con más precisión pero sigue para el caso único que tienen.
