### ISSUE TITLE
Filling the Course Information part

### ISSUE THREAD

**Issue by alextomasoa** [chamilo/chamilo-lms#4581]
Hi, how can I fill this Course Information part, I have tried to use the intro text but it is not the place for the intro text. Thanks.

![image](https://user-images.githubusercontent.com/64377180/216113472-fb2924b1-a5fc-4f69-8018-5c0db253960d.png)

**Comment by ywarnier** [comment]
Hi @alextomasoa. Use the "Course description" tool inside the course itself.

**Comment by alextomasoa** [comment]
Hi @ywarnier, thank you. I found it.
