### ISSUE TITLE
Chamilo 1.1.18 souci import avec ancienne sauvegarde

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#4584]
**Décrivez le problème**
Sur une plateforme mise à jour de 1.11.16 à 1.11.18, je souhaite importer une sauvegarde de cours complète.
Tout semble importé (description, certificats, exercice), sauf le contenu du LP.
L'idée était de faire un "simple" test d'import.
Pour que cela fonctionne, il faut exporter depuis la version 1.11.18 et l'import est alors possible.

**Comment le reproduire**
Pour le reproduire, il faut:
- faire une sauvegarde complète d'un cours depuis une version 1.11.16 (pas testé avec des versions antérieures)
- importer la sauvegarde sur 1.11.18
- le LP n'est pas présent
Si le cours existe toujours sur 1.11.18, la sauvegarde puis l'import fonctionne !

**Comportement attendu**
pouvoir importer une sauvegarde des cours avec rétrocompatibilité de 1.11.x

Test Window // Chamilo 1.11.18 : mise à jour de 1.11.16 sur serveur Ubuntu

**Comment by christianbeeznest** [comment]
Hi @ywarnier,

It had an issue when lp prequerisite is null, I just fixed with this PR https://github.com/chamilo/chamilo-lms/pull/4593

Thanks for confirmation.

**Comment by Coursenligne** [comment]
Hi @christianbeeznest is there a way I can test the solution please?
I may have to revert to previous version on at least a computer.
Generaly speaking there are strange issues with export/import.
I need to ensure the solution did fix the issues :)
Thanks in advance.

**Comment by Coursenligne** [comment]
OK I went to the fix and modified the line accordingly.
I was then able to upload an "old" course.
I turn the issue as closed.
Thanks guys !
