### ISSUE TITLE
AI helper plugin should generate a test with results shown

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4589]
In 1.11.x, the AI helper plugin generates a visible test with no feedback.
The test should be invisible when generated, and should use the first option of results display (not the "exam: do not show any results" option).

This is a minor change but it should help make the test generation more practical.

The last option of the AI helper form section in the exercises tool should fill automatically with the number of questions that were asked. If you ask for 5 questions, it should suggest giving a total score of 5.

**Comment by christianbeeznest** [comment]
Hi @ywarnier , the request is done in this PR https://github.com/chamilo/chamilo-lms/pull/4592

Thanks for confirmation.

**Comment by ywarnier** [comment]
Tested and approved.
