### ISSUE TITLE
Vu sur le forum - feedback - pas de lien pour passer à la question suivante

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#4596]
**Décrivez le problème**
Lorsque l'on crée un auto-test avec feedback immédiate, une question par page, le popup ne possède pas de lien pour passer à la question suivante.
Il est impossible de faire le test

**Comment le reproduire**
Créer un test avec feedback immédiat (3 questions par exemple)
Passer le test. La première question fonctionne et le popup donnant le commentaire ne possède pas de lien pour continuer.
Cette fenêtre étant modale, il est impossible de cliquer sur le bouton continuer, même s'il est visible.
Le popup ne possédant pas de croix de fermeture, l'apprenant ne peut répondre qu'à la première question.

**Comportement attendu**
Pouvoir répondre à toutes les questions avec feedback à chaque fois.

Chamilo 1.11.18 mise à jour de 1.11.16
tous OS
---------
J'ai testé sur 1.11.18 et ai le même souci

**Comment by AngelFQC** [comment]
Hi @Coursenligne 

I have set up the following exercise and can see and continue to the next question until I finish the exam

![Screenshot 2023-02-10 at 01-42-11 My Organisation - My campus - Survey tests - Question _ Answer management](https://user-images.githubusercontent.com/1697880/218116649-f6b73ef1-df62-4fa8-9510-1371dc4747b8.png)

![Screenshot 2023-02-10 at 01-42-38 My Organisation - My campus - Survey tests - Question _ Answer management](https://user-images.githubusercontent.com/1697880/218116647-a3e84e70-12d3-4df8-86ff-fd469e5be8ef.png)

![Screenshot 2023-02-10 at 01-42-56 My Organisation - My campus - Survey tests - Question _ Answer management](https://user-images.githubusercontent.com/1697880/218116646-9ab59a2e-20f5-421f-aa3c-f25b6df46f59.png)

![Screenshot 2023-02-10 at 09-28-23 My Organisation - My campus - Survey tests](https://user-images.githubusercontent.com/1697880/218116639-fed30da6-aa37-4b7f-9f7e-ddfb1e9d8fe4.png)

![Screenshot 2023-02-10 at 09-30-34 My Organisation - My campus - Survey tests](https://user-images.githubusercontent.com/1697880/218116978-70232806-7212-4cb9-bcf8-bd9e788dab0e.png)

**Comment by Coursenligne** [comment]
Hi,
Your exercise doesn't look at all as a normal one in Chamilo.
I've never seen target course nor target question, nor try again tick box.
1.11.18 as the exact same look as ever since 1.10 (and even 1.9 branch).
I can tell that if you create 3 unique answer questions and set immediate feedback you don't have the link to go to next question after answering the first one
![3_questions](https://user-images.githubusercontent.com/32436850/218152971-8125c29c-af00-4562-a0ff-526d363d23fd.png)
![answer q1](https://user-images.githubusercontent.com/32436850/218152972-85731d78-fc49-4d1b-b936-b678411a5d21.png)

**Comment by AngelFQC** [comment]
Ok. I was confusing it with immediate feedback

Please, try with the changes from the commit c33fe2b

**Comment by ywarnier** [comment]
@Coursenligne À tester rapidement sur https://11.chamilo.org si tu veux valider (ou l'inverse).

**Comment by Coursenligne** [comment]
Bonjour Yannick,
Testé vis https://11.chamilo.org/courses/TESTFEEDBACKIMMEDIAT/index.php?id_session=0 où j'ai simplement mis l'exercice (pas de cours), cela fonctionne correctement !
Impeccable en ce qui me concerne.
Merci beaucoup pour le fix...

**Comment by Coursenligne** [comment]
Juste une remarque// Sorry, I swap in English...
Just tried on a test platform localy installed.
As soons as exercise_submit_modal.php is modify, the popup is not displayed.
11.chamilo works fine, but it's worth ensuring there is not a silly issue that happens with extra files.
I hope this helps.
Thanks again guys.
