### ISSUE TITLE
Lien dans un LP pris en compte dans la progression

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#4598]
Dans une page (document) du LP, si je crée un lien pour passer à la page suivante (ex : bouton Next auquel j'attribue l'URL du document suivant), la progression ne bouge pas. En revanche si je clique sur le titre du document dans le sommaire, la progression fonctionne.
Ceci rend compliqué l'affichage sans sommaire avec passage à la page suivante dans le module si celui-ci est créé avec le logiciel auteur intégré

Soit détecter si le lien revoie dans le module, soit avoir un outil qui génère le lien vers le document suivant pour faire fonctionner la progression en masquant la table des matières (lien ou bouton inséré dans le document).

**Contexte additionnel**
Cela rejoint l'idée du mode impress qui ne fait pas bouger la progression (certainement à cause du lien interne).
La certification prenant en compte et le % de progression dans le cour et le résultat de test(s), si la progression reste à 0, l'apprenant ne sera jamais certifié.

**Comment by NicoDucou** [comment]
Bonjour @Coursenligne 

Je n'ai pas testé le problème pour essayer de le reproduire, mais peut-être il existe une autre méthode qui convient.
En effet il est possible de masquer le sommaire et ensuite de forcer l'affichage des icones du menu dans lequel on retrouve les boutons suivant et précédent qui permettent de naviguer.

![image](https://user-images.githubusercontent.com/6579268/217560923-974163ef-ba2f-4fd5-9053-b95a7ff8346c.png)

Il y a les options suivantes à mettre dans app/config/configuration.php qui permettent de configurer la présentation des parcours à adapter en fonction de votre besoin : 

```
// LP view custom settings
/*$_configuration['lp_view_settings'] = [
    'display' => [
        'show_reporting_icon' => true,
        'hide_lp_arrow_navigation' => false,
        'show_toolbar_by_default' => false,
        'navigation_in_the_middle' => false,
        'add_extra_quit_to_home_icon' => false,
    ],
];*/

// LP view menu location. Options: "left" or "right"
// $_configuration['lp_menu_location'] = 'left';

```

**Comment by Coursenligne** [comment]
Je vais investiguer dans ce sens...
Cela répond partiellement :)

**Comment by ywarnier** [comment]
Manque de suivi de la part de l'utilisateur :wink: . Je clôture.
