### ISSUE TITLE
El orden de los items de los learning path generados con openAI no es correcto

### ISSUE THREAD

**Issue by FraGoTe** [chamilo/chamilo-lms#4604]
**Describe el problema**
Cuando se generan los learning paths usando el helper de openAI para generación automática el orden los learning path, en el ejemplo adjunto se peude ver que la introducción está al final cuando debería estar al inicio.

**Comportamiento esperado**
La introducción debería ir al inicio y conclusion al final.
**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/1095778/218209741-8810e3da-af31-45ce-bc53-db746a6b4d1c.png)
![image](https://user-images.githubusercontent.com/1095778/218210416-bce65a7d-4a1a-4b6c-9075-d24ed1916778.png)

**Comment by ywarnier** [comment]
Merge validado.
