### ISSUE TITLE
Generación de Learning Path usando OpenAI

### ISSUE THREAD

**Issue by FraGoTe** [chamilo/chamilo-lms#4606]
**Tu solicitud está relacionado con alguna molestia? Describe...**
Actualmente la generación de cada item del learning path es un HTML sin nada de CSS:

`In the context of "%s", generate a document with HTML tags in "%s" with %d words of content or less, about "%s"'`

**Describe la solución que te gustaría encontrar**
Estuvimos probando y podríamos generar un documento en HTML basado en bootstrap con el siguiente prompt:

`In the context of "%s", generate a landing page with HTML, CSS and bootstrap with the class container-fluid and the title in the center "%s" with %d words of content or less, above "%s"`

Sin Estilos:
![image](https://user-images.githubusercontent.com/1095778/218215073-09bed6cc-a30a-4810-b97e-3eaaedbf6244.png)
![image](https://user-images.githubusercontent.com/1095778/218215101-165d71a2-4fc9-4b97-8f1e-320fef6b02ba.png)

Con Estilos:
![image](https://user-images.githubusercontent.com/1095778/218215141-2fce0d3a-7c2a-4690-af78-8b4b00c6688b.png)

**Comment by ywarnier** [comment]
El problema de esta solicitud es que introduce una dependencia a Bootstrap desde una fuente externa. Algo así:
```
<link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet" />
```
No queremos esto, queremos que lo incluya desde Chamilo. De una porque ya lo tenemos potencialmente en caché, de dos porque así usamos la misma versión de Bootstrap que la que tenemos en Chamilo.

Por eso, creo que debería ser hecho en post-processing: después de haber recuperado la respuesta de OpenAI, se agregaría el div container-fluid y el link hacia boostrap.min.css en el header.

**Comment by FraGoTe** [comment]
@ywarnier desde que los LP son documentos exportables me parece que no es necesario forzar a que use los archivos estáticos de la plataforma, de hecho mientas más standalone sean mejor ¿no?

**Comment by ywarnier** [comment]
> @ywarnier desde que los LP son documentos exportables me parece que no es necesario forzar a que use los archivos estáticos de la plataforma, de hecho mientas más standalone sean mejor ¿no?

Tengo que revisar como lo hacemos. Más standalone, sí (podemos juntar el bootstrap.min.css al export), pero no podemos depender de una fuente externa. Trae 3 problemas potenciales:
- carga de datos (con cookies) desde un proveedor del cual no avisamos al usuario que sus datos son tratados por el (es conocido que las fuentes que Google comparte libremente sirven para analizar qué usuario está en qué sitio web)
- si el usuario usa Chamilo en modo offline (escuela remota sin internet), tendrá contenido que intenta siempre cargar un recurso inalcanzable
- seguridad (en realidad hay dos asuntos aquí): según la configuración del navegador y del servidor, puede que la carga de cualquier cosas desde otro dominio no sea autorizada *y* la fuente externa apunta a una versión fija de Bootstrap (en este caso Bootstrap 4.0.0) que puede tener fallas, que no serán revisadas por nosotros.

Al usar (inteligentemente, incluyendo en el export) las librerías ya incluidas en Chamilo, se evitan todos estos problemas.

**Comment by christianbeeznest** [comment]
Hola @ywarnier 

El pedido esta hecho en este PR https://github.com/chamilo/chamilo-lms/pull/4620

Gracias por confirmar.

**Comment by ywarnier** [comment]
Marco esta como completada, porque por lo que veo cumple con el objetivo de @FraGoTe , solo que de una manera más chamila ;-)

**Comment by FraGoTe** [comment]
Si, se ve genial acabo de probarlo gracias!
