### ISSUE TITLE
Add tests to AI Helper - LP integration

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4608]
It is now possible to generate learning paths with the help of the AI Helper plugin. It is also possible to generate simple tests in the quiz tool with the same plugin.

It would be nice to integrate both, because usually, we want a learning path's items to be split by a few auto-evaluation tests to make sure the user understands what (s)he has just read.

Add two options to the learning paths generation form:
- Add evaluation tests after each page (checkbox, unchecked by default)
- Number of questions per test (minimum 1, default=2, and maximum 5 because it doesn't make much sense to have more)

When the checkbox is selected, in the "while" loop to generate the learning path pages, add a step to ask for a test in Aiken format with the topic being the topic of the page, and the number of questions being the number given (the score is also 1 point per question).

Additionally, when the option for tests is checked (and *only* when the option is checked), make all steps a prerequisite of the following step (including normal pages). The prerequisite on a test should be set at 50% of the maximum score (this can be modified by the teacher afterwards).

Finally, add a last step of type "End of learning path" with the default text.

**Comment by christianbeeznest** [comment]
Hello @ywarnier,

It is added this request in this PR https://github.com/chamilo/chamilo-lms/pull/4609

Thanks for confirmation.

Some langs to add:

$NroQuestionsFromXToY = "Number of questions per test from %s to %s";
$AddTestsAfterEachPage = "Add evaluation tests after each page":

**Comment by ywarnier** [comment]
Reviewed, tested and approved.
