### ISSUE TITLE
AI Helper token limit per month per user

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4611]
In https://github.com/chamilo/chamilo-lms/commit/159e8ee075cc1d3b8d2cba68e98d05cc705ed3e5, we introduced the notion of "AI tokens limit". This is to avoid users (teachers, mostly, given the AI connector will work by institution and students cannot create quizzes or learning paths) going overboard by making hundreds of queries just for fun.

But this limit is not used in practice yet. This issue is to add support for this limit. This will work in the following way.

1. We have the date of each query in plugin_ai_helper_requests, so for any user wanting to query the AI helper, sum up the number of tokens of their queries over the current month
2. If the number of tokens used is below the `tokens_limit`, let the query run
3. If the number of tokens used is greater than the `tokens_limit`, then show the following message: "Sorry, you have reached the maximum number of tokens or requests configured by the platform administrator for the current calendar month. Please contact your support team or wait for next month before you can issue new requests to the AI Helper."
4. Add the following to the translation files:
English:
```
$strings['tokens_limit_help'] = 'Limit the maximum number of tokens each user has available per month, to avoid high costs of service.';
``` 
French:
```
$strings['tokens_limit_help'] = 'Limiter le nombre maximum de jetons disponibles pour chaque utilisateur, par mois, pour éviter des frais de service surdimensionnés.';
``` 
Spanish
```
$strings['tokens_limit_help'] = 'Limitar la cantidad máxima de tokens disponibles por usuario por mes para evitar un alto costo de servicio.';
``` 

In the future, we could probably add some feature in the plugin interface to clear one user's total tokens for the month, but for now adding the limit should be enough (sysadmins could either increase the limit for all, or remove a few records from the plugin_ai_helper_requests table.

**Comment by christianbeeznest** [comment]
Hi @ywarnier 

It is added this request in this commit https://github.com/chamilo/chamilo-lms/pull/4609/commits/21bd5455e998f9feb47c768c06993ea2506e23c8 

Thanks for confirmation.

**Comment by ywarnier** [comment]
Tested, reviewed and approved.
