### ISSUE TITLE
Mejora del aviso de "Eliminar relaciones previas"

### ISSUE THREAD

**Issue by contidos** [chamilo/chamilo-lms#4612]
En la sección de administración >> Sesiones >> Importar lista de directores RRHH en las sesiones aparace un botón para seleccionar la ubicación del archivo a importar y justo debajo un checkbox que pone "Eliminar relaciones previas". 

Podría ser una buena idea agregar un texto más extenso en esa zona que deje más claro para el usuario de a pié qué es exactamente lo que va a hacer ese botón. Yo sugiero lo siguiente: 

 Eliminar relaciones previas (Se eliminará el usuario RRHH de todas las sesiones que tiene asignadas actualmente)

Y también sería ideal, si fuese posible, que si la persona selecciona el checbox, le salga un mensaje pidiéndole que confirme si está seguro de que quiere eliminar al usuario RRHH de todas las sesiones en las que está inscrito actualmente. 

Esta propuesta de mejora viene tras observar el comportamiento de varios usuarios que por error marcan la casilla y con esto quitan al usuario RRHH de las sesiones que ya ha realizado hasta esa fecha,

**Comment by ywarnier** [comment]
Para la parte "mejorar el aviso" creo que está bien ahora (no use tu texto sino uno un poco más largo).
Para la parte de la validación con un mensaje que le aparece, esto tendrá que esperar otra versión.

**Comment by ywarnier** [comment]
![Capture d’écran du 2023-03-04 01-34-00](https://user-images.githubusercontent.com/609839/222860772-637d0dd7-ec54-4862-9bcb-8d34ac98dff8.png)

Quizás haya una pequeña mejora que hacer en "lo que no existe". Ya me dirás...

**Comment by contidos** [comment]
Yo lo sigo viendo un poco complejo de entender por el usuario. Esa sección está disponible sólo para cargar de manera masiva el perfil de rrhh, por lo que yo creo que el texto podría hacer referencia a ellos sin problema. Propongo: 

"Marcando esta casilla, eliminas todas las asignaciones previas del responsable de recursos humanos en otras sesiones o cursos. Si lo que quieres es conservar las relaciones que ya tiene ese perfil en tu campus, NO marques esta casilla".

¿Cómo lo ves?

**Comment by ywarnier** [comment]
Está bien

**Comment by ywarnier** [comment]
Actualizado en translate. Se añadirá a Chamilo antes de la 1.11.20

**Comment by ywarnier** [comment]
Fixed and integrated in 1e0231f5cffb780d8f983
