### ISSUE TITLE
Ocultar estrella amarilla a los alumnos

### ISSUE THREAD

**Issue by jolufe** [chamilo/chamilo-lms#4627]
Hola.
Quisiera saber si hay alguna manera de ocultarle a los alumnos las estrellas amarillas que aparecen en los elementos propios de una sesión, para distinguirlos de los elementos del curso base.

Es una información irrelevante para un alumno y puede resultar confusa.

![image](https://user-images.githubusercontent.com/40075497/222450295-d5fde136-0d26-4818-8ca2-edb6a7f6c511.png)

Chamilo 1.11.18

Gracias.

**Comment by ywarnier** [comment]
En realidad los alumnos no ven la estrella. Es verdad que la ves en modo "Vista estudiante", y no se debería ver ahí, pero el estudiante real no la ve.
Esto se debe a que el código para mostrar esta estrella está ubicado en la función api_get_session_image() en main/inc/lib/api.lib.php (por ahí de la línea ~2980) y lo primero que hace es verificar si eres estudiante (de verdad) o no. Si eres estudiante no devuelve ninguna estrella.
El modo "Vista estudiante" funciona de una manera un poco distinta: el sistema te ve como profesor pero aplica unos filtros para no mostrar botones.
Estoy de acuerdo, en sí, que no se debería mostrar tampoco si es que estás en vista estudiante, así que lo he corregido. Este cambio estará en 1.11.20.

**Comment by NicoDucou** [comment]
I just checked it in the document tool, test tool and LP tool and it works now fine for me.

I'm closing this issue
