### ISSUE TITLE
Crear copia de curso

### ISSUE THREAD

**Issue by kawsayv** [chamilo/chamilo-lms#4642]
**Describe el problema**
ingreso al curso y en mantenimiento intento crear copia de un curso
la pantalla queda en blanco

mi proveedor me indica este error

AH01071: Got error 'PHP message: PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function Chamilo\CourseBundle\Component\CourseCopy\Resources\CourseCopyLearnpath::__construct(), 31 passed in /var/www/vhosts/academiadeseguridad.com/httpdocs/src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php on line 1503 and exactly 32 expected in /var/www/vhosts/academiadeseguridad.com/httpdocs/src/Chamilo/CourseBundle/Component/CourseCopy/Resources/CourseCopyLearnpath.php:127\nStack trace:\n#0 /var/www/vhosts/academiadeseguridad.com/httpdocs/src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php(1503): Chamilo\CourseBundle\Component\CourseCopy\Resources\CourseCopyLearnpath->__construct()\n#1 /var/www/vhosts/academiadeseguridad.com/httpdocs/src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php(265): Chamilo\CourseBundle\Component\CourseCopy\CourseBuilder->build_learnpaths()\n#2 /var/www/vhosts/academiadeseguridad.com/httpdocs/main/coursecopy/create_backup.php(56): Chamilo\CourseBundle\Component\...', referer: https://academiadeseguridad.com/main/coursecopy/create_backup.php?cidReq=1&id_session=0&gidReq=0&gradebook=0&origin=

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  1.11.18 actualizado de la 16
 - Versión de PHP: 7.4

**Comment by NicoDucou** [comment]
Hola @kawsayv 
He ingresado a la herramineta de backup y he creado un backup completo sin problema.

Por lo que se indica en el mesage de error parece que falta un parametro que es lo que se agrego recientemente con los prerequisitos de lecciones con el commit aqui : https://github.com/chamilo/chamilo-lms/commit/748992184776fb9de8ea56d1573ae020c82f597a

Veo que habia un error con esto al momento de restorar el backup que se ha arreglado aqui : https://github.com/chamilo/chamilo-lms/commit/b3595c87ddb9b92392977000823e5ee8f3dff21a

@christianbeeznest podria ser que sea necesario hacer lo mismo en src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php de forzar el casting con (int) antes de $obj->prerequisite para esta seguro que haya un parametro en la class CourseBuilder ?

No he logrado ha reproducir el problema asi que no estoy seguro por eso te pregunto como has trabajado en esto.

**Comment by christianbeeznest** [comment]
Hola @NicoDucou,

Segun el mensaje de error en la descripcion del issue no parece tener la misma version de 1.11.18 en src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php , en la linea 1553 hasta 1586 se pasa los 32 parametros que requiere \Resources\CourseCopyLearnpath::__construct() , en el mensaje de error de la descripcion mensiona desde la linea 1503 , /var/www/vhosts/academiadeseguridad.com/httpdocs/src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php on line 1503  and exactly 32 expected .

Podria solucionarlo agregando valor por defecto al argumento $prerequisite pasado en \CourseCopyLearnpath::__construct() , pero si no tiene la misma version de 1.11.18 podria salir otros errores. 

Podrian confirmar si esta bien la copia de migracion porfavor?, necesitariamos confirmar esos 2 archivos src/Chamilo/CourseBundle/Component/CourseCopy/CourseBuilder.php  y  \Resources\CourseCopyLearnpath.php

Gracias.

**Comment by NicoDucou** [comment]
Gracias Christian
@kawsayv nos podrias confirmar tu version y en particular los archivos que indica Christian en su comentario ?

**Comment by kawsayv** [comment]
ok lo que hice fue reinstalar la ultima version y se soluciono
