### ISSUE TITLE
Rest WebServices - Desuscribir de curso

### ISSUE THREAD

**Issue by FerminAlvarez** [chamilo/chamilo-lms#4646]
**Problema**
Estoy utilizando la API REST V2 y unsubscribe_user_from_course tiene la misma acción que subscribe_user_to_course, por lo que no puedo desuscribir a un usuario de un curso mediante la API.

**Cómo reproducir**
Pasos para reproducir el problema:
1. Intentar desuscribir a un usuario con lo que dice la documentación: https://github.com/chamilo/chamilo-lms/wiki/Rest-WebServices#unsubscribe_user_from_course

**Comportamiento esperado**
Se espera que al utilizar la acción que indica el usuario pierda la suscripción a un curso. Como es la misma acción que el de suscribir lo que hace es suscribir al usuario al curso, totalmente opuesto a lo esperado.

**Comment by ywarnier** [comment]
Lacking feedback. Closing.
