### ISSUE TITLE
Rest WebServices - Quitar usuarios de sesión

### ISSUE THREAD

**Issue by FerminAlvarez** [chamilo/chamilo-lms#4647]
Estoy utilizando la API REST V2 para automatizar algunos procesos de chamilo y si bien puedo automatizar agregar usuarios a una sesión, no puedo hacer lo contrario.

Me gustaría una acción que permita quitar usuarios de una sesión. Sería el caso contrario a lo que hace https://github.com/chamilo/chamilo-lms/wiki/Rest-WebServices#add_users_session.

**Comment by ywarnier** [comment]
Acabo de añadir los servicios correspondientes aquí: https://github.com/chamilo/chamilo-lms/commit/8aac38b77fc4a7b4e0ce3f90b897df3bf12fc011

Viéndolo con un poco de reflexión, no había razón por la que estos servicios no estuvieran ahí. Era sencillo añadirlos y coherente con nuestra voluntad de ayuda a la automatización. Existían en SOAP, pero no en REST todavía, y la API REST es la que queremos promover.

Estarán en la 1.11.20 (por ser publicada esta semana).
