### ISSUE TITLE
[C2] Document tool: actions menu

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4684]
This is the documents menu in C1.11:

![document-actions](https://user-images.githubusercontent.com/609839/233042283-e9954acb-069f-43f3-b5ef-e9e7807eb1e6.png)

As you can see currently in the C2 documents tool, it has been simplified a lot (too much).

![c2-document-actions](https://user-images.githubusercontent.com/609839/233042829-b719ed50-cb8b-400e-abac-522da1dc9abf.png)

It also adds text, which is nice, but in mobile view this text should disappear in favor of only showing icons. This is why the choice of icons is very important. Some of these actions, we are dropping support for temporarily, but the rest is listed below to re-instate.

This is the list of things to do:
- [ ] First button should be "Back" which only appears if you are in a subdirectory, and sends you back to the document tool's root folder (icon from Material Design Icons: arrow-left-bold-box)
- [ ] Second button should be the "New document" button (currently the second button, icon is ok)
- [ ] Third should be disabled for now (it will depend on a system setting) but still show a "New drawing" button (icon: drawing)
- [ ] Fourth should be a "Record audio" button (icon: drawing)
- [ ] Fifth should be the "Upload" button (currently third button, icon is fine)
- [ ] Sixth should be "New folder" (currently first button, icon is fine)
- [ ] Seventh should be disabled (it will depend on a system setting) but still show "New cloud file" (icon: cloud-plus)
- [ ] Eight button should only appear if there is at least one image in the current folder (the subfolders don't count) and show "Slideshow" and send to the view mode of the first image available (when you upload an image and click on it in the list, it shows the image with a dark background on top of the screen and a "play" button allows you to slide to other images automatically. This is not an exact replica of the feature in 1.11, which normally sent you to a preview of all images in thumbnails on the same screen, but it will do for now. (icon: view-gallery)
- [ ] Nineth button should show "Usage" and show a stats modal window (there is no theming for that one yet, so use the same type of modal you use for the edition of icons on the course homepage screen, for example). See below for the type of info that is shown in C1.11 (icon: chart-donut)
- [ ] Tenth button should only show at the root level and show "Download all" and allow for a zip download of all the files and folders of this courses in the documents tool (there is a feature for that in C1.11 so there should be a function available, although probably not yet offered through the API) (icon: download-box)

**Comment by daniboygg** [comment]
In the list of things to do, the delete button is not mentioned. Should the button "Delete selected" disappear from the actions menu?

**Comment by ywarnier** [comment]
In Chamilo 1.11, we have an option to select items in the table (list of documents) and then a drop-down under the table to select some actions. I liked this option better (used less space for actions that are uncommon, like the actions that affect several items at a time). The "Deleted selected" button was added to recover that feature quickly, but I would prefer to put that button inside a dropdown of possible actions, if it is not too complex to do.

To give you an idea:

![Capture d’écran du 2023-05-26 15-43-30](https://github.com/chamilo/chamilo-lms/assets/609839/dc5f2582-2a3d-4169-b790-c829cbdaccb4)

It doesn't have to be exactly the same, but it would help to have a common mechanism for all group actions everywhere where we have a list of items that we can select with checkboxes.
