### ISSUE TITLE
[C2] Document tool: Upload view display/behaviour fixes

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4685]
The documents upload process in Chamilo 2 has been integrated quickly through an external library, but it lacks a bit of visual integration.

Currently, it looks like this:

![c2-doc-upload1](https://user-images.githubusercontent.com/609839/233092884-00f117bb-5693-49ce-9a51-beec256273eb.png)

When you upload one file, it asks for confirmation, and then shows you this:

![c2-doc-upload2](https://user-images.githubusercontent.com/609839/233093036-a058452a-6fdc-4b25-8eb8-525bf1a4c3e9.png)

In Chamilo 1.11, this looks like this (in the "simple" upload form), and we should maintain part of that, although it could be less visible, like through a modal window accessible through a cog icon somewhere on the right side of the upload area):

![c1-file-upload](https://user-images.githubusercontent.com/609839/233094873-727cac14-27a8-47db-bed2-58be6b046efd.png)

So, the changes required are: 

- [ ] When the upload is done, it should automatically return to the page from where the user clicked "Upload" (the sub-folder where the user was, not just the root of the document tool) (don't wait for the user to press the "Done" button)
- [ ] Add option to "Uncompress" a Zip file in all its subcomponents (just check the box and all .zip files uploaded will be uncompressed on the fly). I assume that, due to the new upload process, this feature has been lost, but it is important. In Chamilo 1.11, it is handled through the PCLZip library, which is probably not supported in PHP 8 anyway(?)
- [ ] There should be an option to decide what to do in case the file has the same name as a file already present: (1) overwrite previous file, (2) Rename the uploaded file (add a suffix like "-1"), (3) Do nothing (ignore the upload in case there is another file with this name). These options are set by default to a global configuration setting
- [ ] The icons for "My Device" and "Camera" should come from Material Design Icons "folder-open" and "camera".

The options to set the file title and comment can be dropped. This can still be changed afterwards by the user in the documents list.

**Comment by daniboygg** [comment]
The interface made in the pull request is something like this, I copied more or less the structure of chamilo 1. The button with the cog icon cand show or hide the advanced options

![image](https://github.com/chamilo/chamilo-lms/assets/50702276/2c2b3d19-94d9-4dc1-8104-856852edc67d)
