### ISSUE TITLE
H5P plugin breaks jquery ui addons

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#4689]
The plugin re-adds the jquery-ui.min.js and this affects the other addons (datetimepicker, for example)

Chamilo already loads jquery-ui for all pages. So there should be no need to add it back.

Reference 
https://github.com/chamilo/chamilo-lms/blob/ce529e8557cb365d2d0d7858f1d756472ac66d37/plugin/h5p/index.php#L22

**Comment by ywarnier** [comment]
@LudiscapeXApi

**Comment by LudiscapeXApi** [comment]
This H5P engine is no longer valid, but here is a correction
`$fh .= '<script>if (!jQuery.ui) {';
 $fh .= "$('body').append('<script src=\"".$webPath."web/assets/jquery-ui/jquery-ui.min.js\"></script>');}</script>";`
https://github.com/LudiscapeXApi/chamilo-lms/blob/patch-16-jqueryui/plugin/h5p/index.php

**Comment by ywarnier** [comment]
Seems fixed with the proposed patch. Sent here: https://github.com/chamilo/chamilo-lms/commit/0ab027d377b8c505d2c43a08ca389c4614774a3f
Thanks!
Closing.
