### ISSUE TITLE
Next button after license does not allow installation to proceed

### ISSUE THREAD

**Issue by trevorh13** [chamilo/chamilo-lms#4693]
**Describe**
I am trying to install Chamilo but am running into a problem at step 3 (License). I accept the license, fill in the form and then click Next. However I am not taken to step 4. Nothing happens.

If I do not accept the license, clicking the Next button results in a message box prompting me to do so.

**Expected behavior**
I expected to be taken to step 4 so i could proceed with the installation

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Edge

Have also tried from Android and Opera

**Server
 - OS:Linux Ubuntu 22.04
 - Version of Chamilo: 1.11.18
 - Version of PHP: 8.1

**Additional context**
Please note I am a lowly Windows Admin who has worked significantly with Linux in quite some time. Also I have zero experience of PHP beyond installing it and editing the odd file as told to do!

**Comment by Coursenligne** [comment]
Hi,
You posted a request on the forum the 2nd May using nick name [trhopkins]
I understand you would love an answer, but, as you can imagine, if such an issue would exist, it would have been solved right away due to the number of users.
Could you use 7.x php version rather than 8.1 as a test?

**Comment by ywarnier** [comment]
The PHP version is very likely to be the biggest problem here, indeed.
If you are installing from a Git clone (rather than from the stable package), you will have to do the composer update command using PHP 7.2, 7.3 or 7.4, too.

**Comment by trevorh13** [comment]
Thank you. ywarnier

**Comment by ywarnier** [comment]
> Thank you. ywarnier

Did this fix your issue ?

**Comment by trevorh13** [comment]
Hi Ywarnier,

All sorted - thank you very much for the advice. :-)

**Comment by eh-techy** [comment]
Same issue here
