### ISSUE TITLE
Error al cargar pagina principal de los Cursos

### ISSUE THREAD

**Issue by soportecncbarcenas** [chamilo/chamilo-lms#4695]
Hola!
Cree mi aula con Chamilo hace ya bastantes meses en mi servidor y todo ha ido perfecto hasta ahora. Todo parece funcionar bien menos el acceso a la pantalla principal de los cursos, me aparece una pantalla en blanco con el texto "File not found"

El error me aparece desde el área de MIS CURSOS y cualquier otra zona que intento cargar el curso, si puedo modificar sus características, nombre del curso, apuntarle alumnos, ver informes.... 

Esta es la URL desde la que debería cargar el curso:
https://discoveryuav.com/aulavirtual/courses/CATEGORIAABIERTASUBCATEGORIAA2/index.php

Debería cargar la pantalla principal de curso para poder modificar la descripción, contenido...

Capturas de las zonas que si van bien:
![image](https://user-images.githubusercontent.com/132339466/235612536-61a3391b-dbfb-41ad-a65a-4d58d13dd0ba.png)
![image](https://user-images.githubusercontent.com/132339466/235612624-9cd17b2e-2214-4eb0-85c3-64e445da40e9.png)

Version de PHP del servidor 7.4.33. Servidor Linux.

El problema ocurre en todos los navegadores.

Hasta hoy todo iba perfecto.

**Comment by ywarnier** [comment]
Gestionas el servidor tu mismo ?
Hay una actualización de seguridad reciente de Apache que altera la manera de hacer las redirecciones en caso estas contengan un espacio.
Para verificarlo, quizás podrías verificar con un curso que no tenga espacio en su título ? (normalmente solo afecta los documentos, pero es una pista como otra)

**Comment by soportecncbarcenas** [comment]
Hola! Si, he probado con otros sin espacios y el error es el mismo, el error de los espacios si lo he notado en los archivos que tuve que corregirlos uno a uno pero este fallo no lo he podido solucionar quitando espacios. Muchisimas gracias por la respuesta.

**Comment by ywarnier** [comment]
El acceso a la pantalla principal del curso hace uso de una redirección, definida en el .htaccess (https://github.com/chamilo/chamilo-lms/blob/1.11.x/.htaccess#L26-L27).

Esta redirección requiere que tu Apache autorice los .htaccess (que tenga el módulo Rewrite instalado y "AllowOverride all" sobre la carpeta raíz de tu Chamilo. No veo otra razón para que te diga "File not found"...

**Comment by soportecncbarcenas** [comment]
Buenos días. Acabo de revisar el código del .htaccess y las líneas de redirección de los COURSES no estaban. Las he añadido y todo perfecto ahora.
Muchas gracias.
