### ISSUE TITLE
page plugin qui ne s'affiche pas

### ISSUE THREAD

**Issue by Haitam6** [chamilo/chamilo-lms#4703]
**Décrivez le problème**
j'ai un problème lorsque j'essaye d'activer un plugin ça m'affiche la page suivante avec comme erreur : Uncaught ReferenceError: $ is not defined at settings.php?category=Plugins&sec_token=533af9e5fe54f4427e70140e3ff4b260:2:17

**Serveur
 - Version de Chamilo:  [1.11.18]

**Comment by Coursenligne** [comment]
Avez-vous activé le plugin de vente en ligne ?
Il génère un souci et doit donc être activé en dernier.
De mémoire le souci est réglé dans la version 1.11.18.
Pouvez-vous tenter une mise à jour ?

**Comment by Haitam6** [comment]
Effectivement, c'était bien ça le problème. 
  
Merci pour votre aide !
