### ISSUE TITLE
El e-mail de registro en el campus adjunta el CSV de importación con todos los datos

### ISSUE THREAD

**Issue by nosolored** [chamilo/chamilo-lms#4711]
**Describe el problema**
Cuando el tutor de una sesión adjunta un CSV para importar usuarios y marca la opción de enviar el e-mail de registro a los mismos, el mensaje llega con todo el texto pegado, sin formatear, y además el mensaje adjunta el CSV utilizado en la importación, con los datos de todos los usuarios importados, con el consiguiente problema de privacidad y protección de datos personales.

**Cómo reproducir**
Pasos para reproducir el problema:
1. En los parámetros de configuración de Chamilo, activar la opción de "Tutores pueden asignar estudiantes a sesiones" (add_users_by_coach)
2. En la plataforma debe existir alguna sesión o crear una nueva
3. Acceder a la plataforma con el usuario Coach o profesor principal de la sesión
4. Entrar en el apartado de Informes del menú superior, luego hacer click en "sesiones seguidas"
5. Aparece un listado de las sesiones en las que el usuario está. Hacer clic en detalles de la sesión en la que el usuario es el coach principal
6. En la parte superior derecha se mostrará el enlace de importar usuarios desde un CSV
7. Realizar la importación marcando la opción de enviar correo a los usuarios

**Comportamiento esperado**
Debería llegar un correo de registro a cada usuario, con sus datos de acceso y sin adjuntos, pero el mensaje llega con todo el texto en una sola línea continua sin espacios y con el CSV como adjunto.

**Capturas de pantalla**

![cg1](https://github.com/chamilo/chamilo-lms/assets/5868981/1db5a5f4-7536-40e1-867c-f47aa3142b69)
![cg2](https://github.com/chamilo/chamilo-lms/assets/5868981/a4caf0b0-e3ac-4471-ac92-fe3ed190a127)
![cg3](https://github.com/chamilo/chamilo-lms/assets/5868981/be185021-ad81-4291-a1d8-b2e1155cc0e0)
![cg4](https://github.com/chamilo/chamilo-lms/assets/5868981/2473d847-ad16-4c89-ab2b-c1cb77cfd413)
![cg5](https://github.com/chamilo/chamilo-lms/assets/5868981/e50f9f3f-65ea-4f23-a9fb-448193939309)

**Servidor
 - Sistema operativo : Linux Debian
 - Versión de Chamilo:  1.11.18 (actualizada con Github)
 - Versión de PHP: 7.4

**Contexto adicional**
- Probado también en versiones anteriores, hasta la 1.11.12, con igual comportamiento.

**Comment by ywarnier** [comment]
El parche fue aplicado. Gracias por tu contribución @nosolored !
