### ISSUE TITLE
Multi URL course assignment not working in unique inscription mode

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4721]
In a multi URL context, on the page main/admin/access_url_edit_courses_to_url.php?add_type=unique&access_url_id=1 you can select courses one by one to add them in the right column.
When a course is added to the right column, it appears correctly but the value option of the field is set to the course code instead of the course id. So the process for course inscription to the URL gives an error because it is expecting a course ID.
The ajax insertion of the course in the right column should be corrected to set the value to the course ID then the process will work again.

at the moment we have something like :
`<option value="COURSECODE">course Title (COURSECODE)</option>`

We should have 
`<option value="c_id">course Title (COURSECODE)</option>`

On chamilo 1.11.x on 20230526

**Comment by ywarnier** [comment]
Fixed
