### ISSUE TITLE
Erreur pour affichage : Catalogue de cours / Sessions

### ISSUE THREAD

**Issue by sofiagor** [chamilo/chamilo-lms#4723]
Lorsqu'on souhaite afficher Catalogue de cours / Sessions dans son profile on obtient l'erreur "Une erreur s'est produite. Veuillez contacter l'administrateur."

Dans le fichier **php_log** on trouve :  

An exception occurred while executing 'SELECT session_id, date_end FROM session_rel_user INNER JOIN sessionON id = session_id  WHERE user_id = '1' AND date_end >= '2023-01-01' ORDER BY  `date_end` desc ':

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '= session_id  WHERE user_id = '1' AND date_end >= '2023-01-01' ORDER BY  `dat...' at line 1

Mais aussi :   

PHP Warning:  A non-numeric value encountered in /../vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11

**Comment by ywarnier** [comment]
@sofiagor qu'elle est votre version de Chamilo ? L'erreur est un problème d'espace entre "session" et "ON", mais je n'ai pas souvenir d'avoir vu ça dans Chamilo...

**Comment by sofiagor** [comment]
Version 1.11.16 et 1.11.18.
![chamilogithub](https://github.com/chamilo/chamilo-lms/assets/664427/17eb8cec-38c6-48b3-878d-9d10d639a42a)

**Comment by sofiagor** [comment]
![chamilogit2](https://github.com/chamilo/chamilo-lms/assets/664427/0a9588d3-e555-489d-9c5e-569a869a59d2)

**Comment by ywarnier** [comment]
Bonjour @sofiagor 
Merci d'avoir rapporté le problème. Je ne suis pas certain du contexte dans lequel ce problème apparaît (on dirait qu'il y a quelque chose à voir avec l'activation possible d'un plugin) mais en tout cas le problème était bien là (dans la requête SQL) et n'avait pas bougé depuis 2015, donc il semble que le cas particulier qui activait ce code n'était pas très fréquent.

Ça devrait maintenant être réglé grâce à l'insertion d'un petit espace (voir le lien du commit pour application manuelle, et sinon mettre à jour à 1.11.20 quand elle sera publiée).
