### ISSUE TITLE
Admin page : Skills block have incorrect links

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4740]
On the administration page (https://testing24.beeznest.com/admin) in the Skills block there are the following entries with incorrect links :
* skills wheel that redirect to https://testing24.beeznest.com/main/admin/skills_wheel.php whereas it should redirect to https://testing24.beeznest.com/main/skills/skills_wheel.php
* skills import that redirect to https://testing24.beeznest.com/main/admin/skills_import.php whereas it should redirect to https://testing24.beeznest.com/main/skills/skills_import.php
* Manage skills that redirect to https://testing24.beeznest.com/main/admin/skill_list.php whereas it should redirect to https://testing24.beeznest.com/main/skills/skill_list.php 
* Manage skills levels that redirect to https://testing24.beeznest.com/main/admin/skill.php whereas it should redirect to https://testing24.beeznest.com/main/skills/skill.php 
* Skills and assessments that redirect to https://testing24.beeznest.com/main/admin/skills_gradebook.php whereas it should redirect to https://testing24.beeznest.com/main/skills/skills_gradebook.php

The only correct link is for : 
* Skills ranking that redirect to https://testing24.beeznest.com/main/social/skills_ranking.php
The strange situation is that in the file public/main/admin/index.php there is the correct information for the links creation for every entry with :

```
        $items[] = [
            'url' => api_get_path(WEB_CODE_PATH).'skills/skills_wheel.php',
            'label' => get_lang('Skills wheel'),
        ];
        $items[] = [
            'url' => api_get_path(WEB_CODE_PATH).'skills/skills_import.php',
            'label' => get_lang('Skills import'),
        ];
        $items[] = [
            'url' => api_get_path(WEB_CODE_PATH).'skills/skill_list.php',
            'label' => get_lang('Manage skills'),
        ];
        $items[] = [
            'url' => api_get_path(WEB_CODE_PATH).'skills/skill.php',
            'label' => get_lang('Manage skills levels'),
        ];

        $items[] = [
            'url' => api_get_path(WEB_CODE_PATH).'social/skills_ranking.php',
            'label' => get_lang('Skills ranking'),
        ];
        $items[] = [
            'url' => api_get_path(WEB_CODE_PATH).'skills/skills_gradebook.php',
            'label' => get_lang('Skills and assessments'),
        ];
```
So there must be an incorrect convertion made at some point

**Comment by christianbeeznest** [comment]
Hi @NicoDucou 

The request is done in this PR https://github.com/chamilo/chamilo-lms/pull/4748

Thanks for confirmation.

**Comment by NicoDucou** [comment]
All good here
