### ISSUE TITLE
LP ordering

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4742]
In Chamilo master, in the LP tool, in the "Authoring options" column there are arrows to order the LPs but this generates an error because the functionality is not implemented. It should be implemented using the functionality implemented in the resource ordering #3787

**Comment by christianbeeznest** [comment]
Hi  @NicoDucou,

could you validate and merge this PR https://github.com/chamilo/chamilo-lms/pull/4746 to have the resource order in master please ? so I can add this request too.

Thank you.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

I've just acdepted the PR even if I can not test it because we need a use case and also because it does not break anythin from what I've seen.. Since the use case with course tool reordering might take a bit of time, let's try here with the LP's and in anaycase it will be corrected when testing the use case.

**Comment by christianbeeznest** [comment]
Hi @NicoDucou ,

The request is added in this PR  https://github.com/chamilo/chamilo-lms/pull/4750

Thanks for confirmation.

**Comment by NicoDucou** [comment]
I've accepted the PR and closing this task because it works fine.
