### ISSUE TITLE
Compatibilité SCORM 2004

### ISSUE THREAD

**Issue by Coursenligne** [chamilo/chamilo-lms#4749]
Bonjour à tous,
Même si je vous accorde que SCORM 2004 ne respecte pas la norme, cela étant, nombre de logiciels auteurs tiers exportent dans cette version, même si vous spécifiez SCORM 1.2.

Est-il envisageable d'ajouter la compatibilité 2004, tout en gardant SCORM1.2 comme norme par défaut ?
xAPI n'ayant pas été au rendez-vous (je considère xAPI comme IP V6, on en parle pendant 20 ans mais on reste sur l'ancien modèle :) ), avoir le compatibilité 1.2 et 2004 me semble une bonne opportunité d'emprise de Chamilo sur le marché.

Après, il n'y a pas forcément d'urgence ;)
Bon courage !

**Comment by LudiscapeXApi** [comment]
J'intègre assez facilement des contenus SCORM 2004 dans Chamilo. La version actuellement possède les et comprends les verbe de scorm 2004. Regarde plutôt si ton logiciel auteur a la bonne interface.

**Comment by Coursenligne** [comment]
Salut Damien,
Je sais que tu l'intègres "assez facilement", mais hélas, quand tu exportes avec un LA en scorm 2004, Chamilo te génère une erreur.
J'avais eu le souci et d'ailleurs, Yannick avait confirmé que Chamilo est compatible 1.2 uniquement (en l'état).
Après si tu as un mode opératoire simple (et compréhensible pour un néophyte comme moi) pour faire marcher le truc, je veux bien essayer.
En revanche cela ne peut pas passer par "envoie le paquet, je le modifie..." il y a de la confidentialité là-dessous :)
Et si "c'est simple", il doit donc bien y avoir un plugin pour faire ça...
En tout cas, merci de ta réponse :)
Et si tu passes par chez moi, fais-moi signe !

**Comment by Coursenligne** [comment]
Merci cher ami.
Last (but not least), si je modifie est-ce que les packages SCORM 1.2 continueront de fonctionner, ou dois-je prévoir de faire des allers et retours de versions en fonction du package ?
MERCI :)

**Comment by LudiscapeXApi** [comment]
Sur cette partie :
`var API = new APIobject(); //for scorm 1.2
var api = API;
//var API_1484_11 = new APIobject();  //for scorm 1.3
//var api_1484_11 = API_1484_11;`

Cela ajoute un nouvel objet API_1484_11 et api_1484_11  (mais n'enlève pas l'ancien) qui appelle la même API au final.

Sinon tu peux renommer dans l'interface scorm.js de ton LA l'objet api_1484_11 en API simple ce qui revient au même.

**Comment by Coursenligne** [comment]
Ce serait donc intéressant de l'intégrer directement à notre chère LMS :)
Bon il faut vraiment que je creuse l'affaire !

**Comment by LudiscapeXApi** [comment]
Il suffit juste de décommenter la ligne. Par contre je ne sais pas pourquoi elle est en mode commentaire par défaut.

**Comment by ywarnier** [comment]
Elle est en commentaire par défaut parce que le développement a été démarré un jour (il y a plus de 10 ans si ma mémoire est bonne) mais abandonné. Je ne suis vraiment pas fan de SCORM 2004. Ça rajoute une complexité que personne n'utilise (la possibilité de faire des parcours adaptatifs) et une large liste de fonctionnalités similaires (mais pas exactement les mêmes) à SCORM 1.2, ce qui génère beaucoup de travail pour pas grand chose. Et les trucs inefficaces/inutiles, on n'aime pas beaucoup ici :wink: (on préfère investir dans des choses plus utiles).

La plupart des gens regardent d'ailleurs xAPI (dont CMI5) comme remplacement à SCORM maintenant, donc c'est plus ou moins mort pour SCORM 2004.

À moins qu'une grande organisation finance ce développement, l'équipe de volontaires du projet et les fournisseurs officiels de Chamilo ne risquent pas d'y dédier le temps nécessaire. On peut supporter les bases de SCORM 2004 dans Chamilo (en faisant une petite modif), mais officiellement on ne supporte pas cette version parce que notre implémentation est incomplète.

Je ferme cette tâche.
