### ISSUE TITLE
[C2] My sessions page 

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#4762]
There are no session appearing on the my session page (https://2.chamilo.org/sessions)
It should be presented in each of the blocks (Past, Current, Upcoming, and each category) the corresponding session

To reproduce the issue :
create sessions in main/session/session_add.php and assign them to yourself with dates like this
* 1 session with dates in the past (starting and finishing dates < now)
* 1 session with dates around now (starting date < now and finishing date > now)
* 1 session with dates in the future (Starting date > now)
* 1 session named "in cat 1" with dates around now
* 1 session named "in cat 2" with dates around now

Create session categories in main/session/session_category_add.php :
* Cat sess 1
* Cat sess 2

Assign sessions to categories  on main/session/add_many_session_to_category.php
* Assign session "in cat 1" to category "Cat sess1"
* Assign session "in cat 2" to category "Cat sess2"

When entering the page in the menu Courses -> My sessions we should see all the sessions created in the correct block.

Issue in branch Master on the 2023/06/23

**Comment by NicoDucou** [comment]
HI @daniboygg 

I've just accepted your PR, all works fine. Just a little details to make it better.
When the sessions are without categories then we should not see the "No category" title.
Just don't show it if there is no category.
Could you just change this and it will be perfect.
![image](https://github.com/chamilo/chamilo-lms/assets/6579268/b77daf6a-a317-4bae-92c5-2b23975e6f37)

**Comment by NicoDucou** [comment]
Hi @daniboygg 
I did not accept your PR because it does not attend the issue.
The No category label should never appear. The sessions that do not have category should appear but the title 'No category" should not appear, it is not needed.
Best regards

**Comment by daniboygg** [comment]
Oh, my bad, I didn't understand it well. I updated the pull request.

**Comment by NicoDucou** [comment]
All good now.
I accepted the PR and I'm closing this issue.
