### ISSUE TITLE
Mail not sending since 1.11.20

### ISSUE THREAD

**Issue by RobinKal** [chamilo/chamilo-lms#4764]
**Describe**
After the migration from 1.11.18 to 1.11.20, mails stopped to be sent.
PHPMailer works as intended, we tried with a test script file.

**To Reproduce**
1. Use the same configuration (app/config/mail.conf.php) on both versions 
2. Send a mail through the app
3. Check web server logs

**Expected behavior**
Mails being sent to the destinator

**Screenshots**
Nothin is being sent, error is : 
Got error 'PHP message: ERROR: mail not sent to testmail testmail (*) because of SMTP connect() failed.

**Server
 - OS: Linux Ubuntu 18.04 AND 20.04
 - Version of Chamilo:  1.11.20
 - Version of PHP: 7.4

**Comment by AngelFQC** [comment]
Hi @RobinKal 
Can you try with the changes from 9180710?

**Comment by RobinKal** [comment]
Hi,
I applied the fix and it works !
Thank you

**Comment by Coursenligne** [comment]
Hi I confirm, it works fine.
Many thanks for the fix.

**Comment by riesaau** [comment]
I am also having this issue on my mac with mail not being sent since upgrading to 1.11.20
I have not applied the fix as yet.  That will be technically difficult for me so I'm waiting to see if my host can do it.

**Comment by riesaau** [comment]
I applied the fix (my host did it for me since I am not a programmer).  The reset password no longer gives me a failed message but the email never arrives. Also the announcement tool will only send emails to myself and not to the other emails that it was meant to send to.
This issue now seems similar to this one.  https://github.com/chamilo/chamilo-lms/issues/3625

**Comment by riesaau** [comment]
There was a delay but the email reset message eventually came through okay. so it is only the announcement tool which fails to send to anyone else except myself.

**Comment by riesaau** [comment]
One person on the announcement got the email from the tool besides myself.  so I will have to look into the issue more.

**Comment by riesaau** [comment]
I think it is all working now since the fix.   Thank you.
