### ISSUE TITLE
while searching google for a solution to a problem I have, I came across this post on multiple vulnerabilities in version 1.11.18

### ISSUE THREAD

**Issue by riesaau** [chamilo/chamilo-lms#4806]
and thought it might be of interest:-

https://www.randorisec.fr/chamilo-1.11.18-multiple-vulnerabilities

**Comment by ywarnier** [comment]
Yes, these are known and fixed in 1.11.20, and a few other ones are fixed in 1.11.22 (coming soon).
Thanks.
