### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to learnpath::categoryIsVisibleForStudent() must be an instance of Chamilo\CourseBundle\Entity\CLpCategory

### ISSUE THREAD

**Issue by elbobyhn** [chamilo/chamilo-lms#4809]
Error:

Fatal error: Uncaught TypeError: Argument 1 passed to learnpath::categoryIsVisibleForStudent() must be an instance of Chamilo\CourseBundle\Entity\CLpCategory, null given, called in /var/www/html/main/inc/lib/course_home.lib.php on line 728 and defined in /var/www/html/main/lp/learnpath.class.php:4827 Stack trace: #0 /var/www/html/main/inc/lib/course_home.lib.php(728): learnpath::categoryIsVisibleForStudent() #1 /var/www/html/main/inc/lib/course_home.lib.php(1715): CourseHome::get_tools_category() #2 /var/www/html/main/inc/lib/course_home.lib.php(1834): CourseHome::getCourseAdminBlocks() #3 /var/www/html/main/course_home/activity.php(67): CourseHome::getUserBlocks() #4 /var/www/html/main/course_home/course_home.php(468): require('/var/www/html/m...') #5 {main} thrown in /var/www/html/main/lp/learnpath.class.php on line 4827

**Describe**
No se puede visualizar el curso.

**To Reproduce**
Al cambiar los iconos de las lecciones.

**Expected behavior**
Acceder al curso.

**Server
 - OS: Ubuntu 22.04
 - Version of Chamilo: 1.11.20
 - Version of PHP: 7.4

**Additional context**

**Comment by ywarnier** [comment]
Gracias @elbobyhn, reporte bien acertado!

@AngelFQC, el problema está vinculado con el commit 4a587707 (que tiene que ver con aumentar la seguridad en Chamilo en general).
El problema es que se filtra ese path de icono custom del home de curso con `html_filter` de manera obligatoria en `$form->addText()` (en main/course_info/tools.php), lo cual transforma `&` en `&amp;` pero después no hay conversión inversa al momento de usar el link.

En main/inc/lib/course_home.lib.php on line 724, retoma este link con `&amp;` y al momento de hacer el parse_str() para recuperar los parámetros, no recupera 'id' sino 'amp;id', lo cual resulta en una categoría de LP nula (si el icono era para una categoría), lo cual genera el error reportado.

El hecho de haber puesto este `$this->applyFilter($name, 'html_filter');` en main/inc/lib/formvalidator/FormValidator.class.php 219 hace que se filtra demasiado para estos enlaces.

El problema real de remplazo de `&` ocurre en main/inc/lib/formvalidator/FormValidator.class.php 2013 donde se llama a kses() que aplica de manera ciega a kses_normalize_entities(), que hace un remplazo ciego de `&` por `&amp;`. En nuestro caso, esto no va, porque necesitamos el verdadero enlace después (no su versión normalizada para texto HTML).

El elemento "Url" tampoco va porque requiere un protocolo y un dominio.

Como tenemos varios lugares así donde usamos un elemento 'text' para realmente validar una URL interna (sin prefijo de dominio, como es el caso para editar los iconos del home de un curso), he añadido un elemento "InternalUrl" (un híbrido entre Text y URL) a FormValidator, que usa kses() para filtrar, pero no usa kses_normalize_entities() que genera el problema aquí.

Arreglado con este commit: 14798e4314

Ojo @elbobyhn las URLs de iconos modificados que tuvieron este problema tendrán que ser modificadas a mano. Si es que no puedes acceder al curso mismo, puedes hackear la URL para tener algo así: https://mychamilo.com/main/course_info/tools.php?cidReq=ABCD&id_session=0&gidReq=0&gradebook=0&origin=
donde remplazarías el protocolo, el dominio y el código del curso en "cidReq=...". Debería permitirte ver la página de edición, editar (quitar la parte "amp;" detrás de cada "&")y guardar, y de ahí deberías poder acceder al home del curso.
