### ISSUE TITLE
Plugin Resubscription

### ISSUE THREAD

**Issue by sofiagor** [chamilo/chamilo-lms#4825]
Activation de plugin Resubscription produit l'erreur d'affichage des sessions

**Comment le reproduire**
Pour le reproduire, il faut:
1. Activer plugin Resubscription
2. Cliquer sur 'Mes cours/Catalogue de cours/Liste des sessions '
3. Visualiser l'erreur qui dit 'Une erreur s'est produite. Veuillez contacter l'administrateur.'

**Comportement attendu**
Voir les sessions et pouvoir limiter l'inscription à la seule session dans l'année.

**Contexte additionnel**
**Dans les logs :** 
 
### php_log (il manque de champ date_end dans la table session_rel_user) : 

An exception occurred while executing 'SELECT session_id, date_end FROM session_rel_user INNER JOIN session ON id = session_id  WHERE user_id = '1' AND date_end >= '2023-01-01' ORDER BY  `date_end` desc ':

Column not found: 1054 Unknown column 'date_end' in 'field list'

**Après l'ajout du champ date_end en format date encore une autre erreur :**  

Integrity constraint violation: 1052 Column 'id' in on clause is ambiguous  : **dans HookResubscription.php sur la ligne 48 il faut indiquer la table devant id :   $join = " INNER JOIN ".Database::get_main_table(TABLE_MAIN_SESSION)." ON id = session_id";**

**Après l'ajout du nom de la table l'erreur disparait mais le champ  date_end reste NULL et plugin ne fonctionne pas : on peut s'insrire à l'infini.**

**Comment by ywarnier** [comment]
Bonjour @sofiagor,
Merci pour ce rapport d'erreur. Il a été revu et corrigé ci-dessus. La correction sera incluse dans Chamilo 1.11.22 (à paraître bientôt), mais sinon le lien ci-dessus pointe directement vers la correction. Seules les quelques modifications du fichier HookResubscription.php sont nécessaires, donc cette correction peut facilement être appliquée manuellement si tu es pressé(e).

Si possible, merci de confirmer que le problème est effectivement résolu (sans quoi nous fermerons cette tâche manuellement dans quelques jours).

**Comment by sofiagor** [comment]
Bonjour,

Merci pour ce message. Je confirme que le problème est résolu.
En revanche, je n'ai pas compris pour le numéro de version - j'ai la
version 1.11.20 et c'est indiqué que c'est la dernière. J'ai râté quelque
chose et entre temps il y avait 1.11.21 ?

Cordialement,
Sofia

Le mer. 2 août 2023 à 14:32, Yannick Warnier ***@***.***> a
écrit :

**Comment by NicoDucou** [comment]
Bonjour Sofia,
Merci pour la confirmation de correction
Vous n'avez rien manqué le numéro de version avance toujours de 2 en 2 pour avoir des numéros pairs.
Dans quelques jours la 1.11.22 va sortir et vous pourrez faire la mise à jour.
Je ferme donc le ticket
Cordialement
