### ISSUE TITLE
IDOR leads to read any other users Private Messages [HIGH]

### ISSUE THREAD

**Issue by agrawalsmart7** [chamilo/chamilo-lms#4847]
To Reproduce the attack - 

1. Login to your account
2. Visit this URL http://localhost/dashboard/chamilo/main/messages/new_message.php?forward_id=
3. Change the forward ID to other users message ID, hence you will be able to read other users messages. Even a low priv user can read admin level messages.

**Comment by ywarnier** [comment]
Fixed in a4561d7efa62a238e9e30765d3ec5aeefb9cfb61
Please use security@chamilo.org for security vulnerabilities disclosures
