### ISSUE TITLE
Import/export des Lp en format Chamilo dysfonctionne depuis 1.11.22

### ISSUE THREAD

**Issue by yverhenne** [chamilo/chamilo-lms#4872]
Depuis le passage en 1.11.22 et 1.11.24, l'import d'un LP en format Chamilo dysfonctionne. Ces LP contiennent un document créé avec CKEditor et un exercice. Le système récupéré les données d'un exercice mais pas le document. Lorsque on lance le parcours, on a l'indication document protégé et le document n'est pas visible. Ce dernier ne semble pas être trouvé.
Le log m'indique:
Course copy generated an ignorable error while trying to copy /home/u********/domains/*******.fr/public_html/app/cache/course_backups/CourseArchiver_64fc3fd0022db/document/learning_path/CERTIFICATION-PRIX-DE-VENTE/RAPPEL.html: origin file not found

Pour reproduire:
1-Exporter un parcours/LP au format Chamilo
2-Importer ce LP dans un autre LP via le menu maintenance du cours/importer les informations de sauvegarde

Ces Lp ont été créés avec la versions 1.11.20. J'ai essayé plusieurs combinaisons export/import:
1.11.20 vers 1.11.20, tout fonctionne
1.11.20 vers 1.11.22, ça ne fonctionne pas
1.11.20 vers 1.11.24, ça ne fonctionne pas
1.11.24 vers 1.11.24, ça ne fonctionne pas
1.11.24 vers 1.11.20, cela fonctionne

Merci pour votre aide

**Comment by yverhenne** [comment]
L'import/export de cours complet connait le même bug

**Comment by yverhenne** [comment]
Après pas mal de recherches, tests, j'ai trouvé le fichier qui pose problème.

Il s'agit d'une modification lors du passage à 1.11.22:
[2023-07-13] (dc7bfce4) Security: Rename htaccess file by replacing case-insensitively
[url]https://github.com/chamilo/chamilo-lms/commit/dc7bfce429fbd843a95a57c184b6992c4d709549[/url]

J'ai remis le fichier concerné (main/inc/lib/fileUpload.lib.php) de la version 1.11.20 et tout refonctionne.
Par contre il s'agit d'une mise à jour de sécurité et je ne sais pas si cela est dangereux, mais ne travaillant qu'avec l'import/export, je n'ai pas d'autre solution.
Un avis d'un expert?

**Comment by NicoDucou** [comment]
@yverhenne 
Merci pour l'analyse et l'indication.
Je confirme le problème et ça casse également l'importation de Scorm qui contiennent des sous dossiers avec des majuscules.
Je viens de demander au développeur si la correction de retirer la ligne avec strtolower était acceptable par rapport à son fix de sécurité en faisant un commentaire directement ici : https://github.com/chamilo/chamilo-lms/commit/dc7bfce429fbd843a95a57c184b6992c4d709549#r127629622
On vous tient au courant quand la correction sera mise à disposition.

**Comment by NicoDucou** [comment]
bonsoir @yverhenne 

Finalement le choix a été fait de corriger le problème en conservant la sécurité avec ce commit : https://github.com/chamilo/chamilo-lms/commit/f680d7dec1c01f1899886ec1929ba3a1b54e2d84

@yverhenne si tu peux nous confirmer si ce changement règle bien ton problème ?
De mon côté les tests sont bons.

Cordialement

**Comment by NicoDucou** [comment]
Parfait, merci pour cette confirmation, donc on peut fermer la tâche.

**Comment by yverhenne** [comment]
Je pense que tu peux fermer aussi la #4844 qui au final est liée à celle ci

**Comment by NicoDucou** [comment]
> Je pense que tu peux fermer aussi la #4844 qui au final est liée à celle ci

Bien vu, je viens de la fermer.
