### ISSUE TITLE
Les questions de compréhension à la lecture déclenche une erreur générale

### ISSUE THREAD

**Issue by yverhenne** [chamilo/chamilo-lms#4878]
Lorsqu'une question de compréhension à a lecture est lancée, cela déclenche une erreur générale. Testé sur 1.11.20 et 1.11.24
Avec 1.11.24
[12-Sep-2023 07:24:13 UTC] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in ******/public_html/main/exercise/ReadingComprehension.php on line 111

avec 1.11.20
[12-Sep-2023 07:32:33 UTC] PHP Fatal error:  Maximum execution time of 120 seconds exceeded in ******t/public_html/main/exercise/ReadingComprehension.php on line 97

correspond dans les 2 cas à la ligne:
$text = substr_replace($text, $tagStart, $firstIndex, 0);
du fichier main/exercise/ReadingComprehension.php

**Comment by yverhenne** [comment]
Il semblerait que l'erreur vienne de la modification de la fonction construct dans le fichier main/exercise/ReadingComprehension.php

on passe de la fonction en 1.11.20:
    public function __construct()
    {
        parent::__construct();
        $this->type = READING_COMPREHENSION;
        $this->isContent = $this->getIsContent();
    }
à la fonction en 1.11.24:
  public function __construct()
    {
        parent::__construct();
        $this->type = READING_COMPREHENSION;
        $this->isContent = $this->getIsContent();
        $customSpeeds = api_get_configuration_value('exercise_question_reading_comprehension_extra_speeds')['speeds'];
        if (!empty($customSpeeds) && is_array($customSpeeds)) {
            $this->allSpeeds = self::$speeds;
            foreach ($customSpeeds as $speed) {
                $this->allSpeeds[] = $speed;
            }
            asort($this->allSpeeds);
        }
    }
Tout refonctionne lorsque je remet le code de la 1.11.20
Par contre de où cela vient??? je laisse faire les experts

**Comment by yverhenne** [comment]
Bonsoir Yannick,
Testé sur 1.11.24 et tout est ok.
Merci pour la modification et surtout pour l'ensemble du travail fait sur Chamilo!
Je ne suis pas allé sur le configuration.php. Sauf erreur, on peux déjà modifier la vitesse de lecture dans ce type de question.

Cordialement

**Comment by ywarnier** [comment]
On peut choisir entre 5 vitesses différentes par défaut, mais elles sont pré-établies dans Chamilo. Pour augmenter le choix, il faut utiliser l'option ci-dessus (ce qui permet, entre autres, de s'accoupler à des référentiels éducatifs nationaux ou régionaux qui utilisent la vitesse de lecture comme l'un de leurs critères).

**Comment by ywarnier** [comment]
La version 1.11.26 vient d'être publiée et elle contient le patch en question ici.
