### ISSUE TITLE
Error al actualizar Chamilo 1.11.18 a 1.11.24

### ISSUE THREAD

**Issue by ir0nb1t** [chamilo/chamilo-lms#4887]
**Describe el problema**
Intente actualizar la versión de Chamilo de la 1.11.18 a la 1.11.24, segun la guia para actualizar se debe descargar la nueva versión descomprimir y copiar todo el contenido sobre la carpeta donde esta instalado Chanmilo, sobre escribiendo todo.
Hasta ahi todo bien, luego de que al ir al asistente de instalación en el segundo paso al elegir **Actualizar Chamilo**  al final de la pagina tengo el mensaje de error

Error!
Chamilo 1.9.0|1.9.2|1.9.4|1.9.6|1.9.6.1|1.9.8|1.9.8.1|1.9.8.2|1.9.10|1.9.10.2|1.9.10.4|1.9.10.6|1.10.0|1.10.2|1.10.4|1.10.6|1.10.8 no ha sido encontrado en este directorio. 

Y no me deja continuar con la instalación de la actualización

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'descargar actualización 1.11.24 del enlace oficial de github, descomprimir, copiar todo el contenido de la nueva versión sobre la carpeta donde esta instalado chamilo, ir al asistente de instalación'
2. Dar clic en 'en actualizar chamilo'
3. Bajar hasta 'hasta el final de la pagina'
4. Ver el error que dice 'Error!
Chamilo 1.9.0|1.9.2|1.9.4|1.9.6|1.9.6.1|1.9.8|1.9.8.1|1.9.8.2|1.9.10|1.9.10.2|1.9.10.4|1.9.10.6|1.10.0|1.10.2|1.10.4|1.10.6|1.10.8 no ha sido encontrado en este directorio. 
'

**Comportamiento esperado**
Que Chamilo actualice su versión a la 1.11.24

**Capturas de pantalla**
![imagen](https://github.com/chamilo/chamilo-lms/assets/128157041/648f5b86-111c-4981-8db1-fc963788f3cb)

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : Windows 10
 - Navegador chrome, firefox y edge

**Servidor
 - Sistema operativo : Redhat Enterprise 8
 - Versión de Chamilo:  1.11.18
 - Versión de PHP: 7.4.33

**Comment by nosolored** [comment]
Hola @ir0nb1t 

Lo que planteas está descrito aquí https://github.com/chamilo/chamilo-lms/issues/4860

Revisa ya que no es el procedimiento para actualizar dentro de la misma rama. El punto 4 es para versiones 1.9 y 1.10. No para la 1.11.x

Un saludo.

**Comment by ir0nb1t** [comment]
Gracias! me quedo mas claro
