### ISSUE TITLE
Access to scrutinizer.yml 

### ISSUE THREAD

**Issue by ir0nb1t** [chamilo/chamilo-lms#4895]
**Describe el problema**
Por una revision de seguridad me reportaron que el archivo scrutinizer.yml es accesible al consultar por mi portal de Chamilo

https;//midominio.com/.scrutinizer.yml

si elimino el archivo o restrinjo quitandole permisos (chmod 000) afectara en algo el funcionamiento de chamilo ?

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a 'a la url de chamilo por ej. https://midominio.com/.scrutinizer.yml'
2. Dar clic en 'solamente ingresar en la direccion del navegador'
3. Ver el error que dice 'muestra todo el contenido del archivo scrutinizer.yml'

**Comportamiento esperado**
El archivo no deberia mostrarse publicamente 

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : RedHat 8 Enterprise
 - Versión de Chamilo:  1.11.24
 - Versión de PHP: 7.4.33

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by ywarnier** [comment]
Hola @ir0nb1t 
No, no afectará tu portal para nada. Es un archivo usado para las pruebas automatizadas de Chamilo (es decir para el proceso de desarrollo), pero regresará con tu próxima actualización de Chamilo. Puedes también prohibir el acceso al archivo a través de reglas de Apache. Algo como lo que encuentras en la línea 96 de tu .htaccess:
```
# Deny access
RewriteRule ^(tests|.git) - [F,L,NC]
```
que prohibe el acceso a las carpetas tests y .git.

Te han dicho porqué consideran que es inseguro ?

**Comment by ir0nb1t** [comment]
Gracias por la respuesta.

Mencionaron que divulga información (no muy relevante pero si se puede saber conocer algunas carpetas del webserver), ya que el archivo cargaba en texto plano al entrar a la URL, desde internet.
