### ISSUE TITLE
Course categories creation breaks

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#4916]
**Describe**
In newly installed 1.11.26 (and possibly 1.11.24) or systems updated where vendor/ and composer.lock was deleted before a composer update, there is an error when creating a new course category.

The error message is:
Fatal error:  Uncaught Error: Call to undefined function html_filter() in main/inc/lib/course_category.lib.php:191

The html_filter() function is present in FormValidator.class.php (but not part of the FormValidator class), but apparently it doesn't get picked up.

Apparently, this is *not* present in systems where vendor/ and composer.json are a bit older, suggesting to me that something might have changed in the composer update process that removed the mapping of the html_filter() function in the autoload files.

**To Reproduce**
1. Install a fresh 1.11.26 *or* remove composer.lock and vendor/ from an existing system, then "composer update"
2. Go to admin > Courses categories > "Create" icon > Input something > Save.

**References**

- https://forum.chamilo.org/viewtopic.php?f=15&t=12034

**Server
 - Version of PHP: 7.4

**Comment by Coursenligne** [comment]
Hi,
Strange as I made some tests.
2 platforms upgraded under Linux environment ; no problem.
Fresh install under windows : no problem either.

I occured sometimes that you get different behaviour if you use .zip or .tgz version, would this be a clue?

**Comment by nosolored** [comment]
> Hi, Strange as I made some tests. 2 platforms upgraded under Linux environment ; no problem. Fresh install under windows : no problem either.
> 
> I occured sometimes that you get different behaviour if you use .zip or .tgz version, would this be a clue?

We got the error in 3 fresh installations of Chamilo 1.11.26 under Linux Debian, using Git (not using .zip or .tgz) and doing composer update.
Also we tried:
`rm composer.lock
rm -rf web/ vendor/
composer clear-cache
composer update`
After installation, but it doesn't fix the problem

**Comment by nosolored** [comment]
We think the origin of this problem was this commit:
https://github.com/chamilo/chamilo-lms/commit/c263933d1d958edee3999820f636c8cb919d03d1

Changes made in 191 line and 304 line

**Comment by nosolored** [comment]
More test in Windows 11 with Xampp (Apache/2.4.54 (Win64) OpenSSL/1.1.1p PHP/7.4.33, 10.4.27-MariaDB)

**1 .Zip file download - https://github.com/chamilo/chamilo-lms/releases/download/v1.11.26/chamilo-1.11.26.zip**

Fatal error: Uncaught Error: Call to undefined function html_filter() in C:\xampp\htdocs\main\inc\lib\course_category.lib.php:191 Stack trace: #0 C:\xampp\htdocs\main\admin\course_category.php(61): CourseCategory::addNode('1', '1', 'TRUE', '') #1 {main} thrown in C:\xampp\htdocs\main\inc\lib\course_category.lib.php on line 191

**2. Tar.gz file download: https://github.com/chamilo/chamilo-lms/releases/download/v1.11.26/chamilo-1.11.26.tar.gz**

Fatal error: Uncaught Error: Call to undefined function html_filter() in C:\xampp\htdocs\main\inc\lib\course_category.lib.php:191 Stack trace: #0 C:\xampp\htdocs\main\admin\course_category.php(61): CourseCategory::addNode('1', '1', 'TRUE', '') #1 {main} thrown in C:\xampp\htdocs\main\inc\lib\course_category.lib.php on line 191

**3. git/composer**
Fatal error: Uncaught Error: Call to undefined function html_filter() in C:\xampp\htdocs\main\inc\lib\course_category.lib.php:191 Stack trace: #0 C:\xampp\htdocs\main\admin\course_category.php(61): CourseCategory::addNode('1', '1', 'TRUE', '') #1 {main} thrown in C:\xampp\htdocs\main\inc\lib\course_category.lib.php on line 191

**Comment by nosolored** [comment]
More info:
We get the same error if we try to edit the name of a language:
PHP Fatal error:  Uncaught Error: Call to undefined function html_filter() in .../main/admin/languages.php:198\nStack trace:\n#0 {main}\n  thrown in .../main/admin/languages.php on line 198, referer: .../main/admin/languages.php?action=edit&id=36

**Comment by Coursenligne** [comment]
Just removed and reinstalled chamilo1.11.26 and I also get an error.
I suspect a cache that wasn't empty.
The error I get is 500 => Page not available

**Comment by Coursenligne** [comment]
> 

I'm not sure, but there must be somwhere a cache that was persistant as after removing and reinstalling the issue arises.
The strange thing is I made an upgrade on a production server and I don't get it (obiously I don't want to generate it.
I just have on all platforms the issue of LP exports that becomes impossible to modify as seen (when re-imported) as an external SCORM packet.
This is for the moment the biggest issue....

**Comment by LudiscapeXApi** [comment]
SI lors de la copie de vos cours ou l'import export les SCORMs / Editeur Studio sont vides :
Il faut simplement mettre allow_import_scorm_package_in_course_builder dans app/config/configuration.php à mettre à true

**Comment by LudiscapeXApi** [comment]
SI lors de la copie de vos cours ou l'import export les SCORMs / Editeur studio sont vides :
Il faut simplement mettre allow_import_scorm_package_in_course_builder dans app/config/configuration.php à la valeur true

> > 
> 
> I'm not sure, but there must be somwhere a cache that was persistant as after removing and reinstalling the issue arises. The strange thing is I made an upgrade on a production server and I don't get it (obiously I don't want to generate it. I just have on all platforms the issue of LP exports that becomes impossible to modify as seen (when re-imported) as an external SCORM packet. This is for the moment the biggest issue....

**Comment by Coursenligne** [comment]
Hello Damien,
I'm the same Coursenligne that on the forum :)
I already activated this option, but here, the story is different.
I had te categories working on one  of the platforms after upgrade (and it still seems to work) and I suspect something that was in cache and therefore persistent.
I did a fresh install on my own PC yesterday and can confirm the bug.

**Comment by nosolored** [comment]
Thank you @christianbeeznest , it works fine with this fix.
