### ISSUE TITLE
actualizar chamilo desde 1.11.6 a 1.11.26 da Error! Chamilo 1.9.0|1.9.2|1.9.4|1.9.6|1.9.6.1|1.9.8|1.9.8.1|1.9.8.2|1.9.10|1.9.10.2|1.9.10.4|1.9.10.6|1.10.0|1.10.2|1.10.4|1.10.6|1.10.8 no ha sido encontrado en este directorio.

### ISSUE THREAD

**Issue by alejandroalmarza** [chamilo/chamilo-lms#4947]
**Describe el problema**
Tengo una plataforma chamilo corriendo y me encuentro que repentinamente se pierde todo el orden y queda de la siguiente forma:
![image](https://github.com/chamilo/chamilo-lms/assets/53192446/3bd9db71-29a7-420a-be3d-f4255a6b8685)

decido intentar actualizar para ver si se corrige e error. Originalmente tenia la version 1.11.6 pero al intentar instalar la version 1.11.26 me arroja este error:
![image](https://github.com/chamilo/chamilo-lms/assets/53192446/3e91859f-8949-41b4-8381-5f586b405685)

**Cómo reproducir**
Pasos para reproducir el problema:
1. Tener instalado chamilo 1.11.6
2. Copiar el contenido de la zip de chamillo 1.11.26 y sobreescribir
3. ingresar en el URL de instalacion
4. Hacer clic en actualizar 

**Comportamiento esperado**
Deberia empezar a actualizar sin problemas

**Escritorio (por favor completa la información siguiente lo mejor posible):**
VPS de godaddy

**Comment by nosolored** [comment]
Hola.

Revisa https://github.com/chamilo/chamilo-lms/issues/4860 donde se comenta.
Lo que estás utilizando es para actualizar versiones de 1.9, 10, ese proceso no es válido para la rama 1.11.x

Un saludo.

**Comment by ywarnier** [comment]
Cerrando por falta de feedback
