### ISSUE TITLE
Chamillo pierde toda la estructura

### ISSUE THREAD

**Issue by alejandroalmarza** [chamilo/chamilo-lms#4948]
**Describe el problema**
Al ingresar a mi portal chamilo 1.11.6 me encuentro con que se ve asi:
![image](https://github.com/chamilo/chamilo-lms/assets/53192446/d24d2d2b-ebf6-44c1-9c55-f9cac850ca2e)

no se cual podria ser el problema intente actualizando pero no se ha solucionado

**Cómo reproducir**
Pasos para reproducir el problema:
1. Ir a '...'
2. Dar clic en '....'
3. Bajar hasta '....'
4. Ver el error que dice '...'

**Comportamiento esperado**
Una descripción concisa y clara de lo que esperabas que ocurriera.

**Capturas de pantalla**
Si aplicable, agrega capturas de pantalla para ayudar a ubicar el problema.

**Escritorio (por favor completa la información siguiente lo mejor posible):**
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Navegador [ej. chrome, firefox, safari] y su versión

**Servidor
 - Sistema operativo : [ej. Linux Ubuntu 18.04/Windows 10]
 - Versión de Chamilo:  [ej. 1.11.8, 1.11.x of 2018-12-01, ...]
 - Versión de PHP: [ej. 5.6, 7.2, ...]

**Contexto adicional**
Añade cualquier elemento adicional de contexto aquí.

**Comment by alejandroalmarza** [comment]
Problema parcialmente solucionado. Originalmente tenia el servicio en HTML pero mi servidor lo cambio a htmls por tanto daba error al intentar solicitar elementos por html

**Comment by ywarnier** [comment]
Hola @alejandroalmarza 
HTTP a HTTPS, dirás.
Tienes que modificar el `$_configuration['root_web']`, más o menos en la línea 29 de tu app/config/configuration.php
Otra cosa : si realmente tienes 1.11.6 y tu portal está expuesto en internet, te recomiendo (mucho) actualizar a 1.11.26, pues la 1.11.6 ahora está fuera de soporte de nuestro lado y tiene varias fallas de seguridad críticas.
