### ISSUE TITLE
Edición de usuarios: Excepción no controlada si Fecha de expiración activada y datepicker vacío

### ISSUE THREAD

**Issue by juancp-contidosdixitais** [chamilo/chamilo-lms#4953]
**Descripción**
Al editar un usuario si eliminamos el contenido del datepicker de "Fecha de expiración" cuando tenemos marcada la opción "Activada" provocará una excepción devolviendo la siguiente traza:

> Fatal error: Uncaught Error: Call to a member function setTimeZone() on string in /furanet/sites/demo.xxxxxxx.com/web/htdocs/app/DoctrineExtensions/DBAL/Types/UTCDateTimeType.php:32 Stack trace: #0 /furanet/sites/demo.xxxxxxx.com/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2096): Application\DoctrineExtensions\DBAL\Types\UTCDateTimeType->convertToDatabaseValue('', Object(Doctrine\DBAL\Platforms\MySQL57Platform)) #1 /furanet/sites/demo.xxxxxxx.com/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2129): Doctrine\DBAL\Connection->getBindingInfo('', Object(Application\DoctrineExtensions\DBAL\Types\UTCDateTimeType)) #2 /furanet/sites/demo.xxxxxxx.com/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2226): Doctrine\DBAL\Connection->resolveParams(Array, Array) #3 /furanet/sites/demo.xxxxxxx.com/web/htdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1541): Doctrine\DBAL\Connection->handleE in /furanet/sites/demo.xxxxxxx.com/web/htdocs/app/DoctrineExtensions/DBAL/Types/UTCDateTimeType.php on line 32

Este error solo ocurre al editar un usuario ya existente, NO al crear un usuario, en este caso si se ha marcado como "Activada" la "Fecha de expiración" y se elimina el datepicker creará de todas formas el usuario con una fecha de expiración.

**Cómo reproducir**
1. Ir a /main/admin/user_list.php y seleccionar cualquier usuario
2. En "Fecha de expiración" marcar activado y en el datepicker eliminar la fecha que aparece
3. Guardar

**Comportamiento esperado**
Debería controlarse que si el datepicker está vacío aborte la operación y muestre un mensaje indicando el error, para ello propongo modificar para que en la validación del formulario, en /main/admin/user_edit.php, se compruebe si hay una fecha de expiración en caso de que se hubiese marcado la opción "Activado", se podría utilizar donde actualmente se asigna el valor del formulario a la variable $expiration_date:

Fragmento original
```
    $expiration_date = null;
    if (!$user_data['platform_admin'] && $user['radio_expiration_date'] == '1') {
        $expiration_date = $user['expiration_date'];
    }
```

Propuesta modificación
```
    $expiration_date = null;
    if (!$user_data['platform_admin'] && $user['radio_expiration_date'] == '1') {
        if (empty($user['expiration_date'])) {
            Display::addFlash(Display::return_message(get_lang('EmptyExpirationDate')));
            header('Location: '.api_get_self().'?user_id='.$user_id);
            exit();
        }
        $expiration_date = $user['expiration_date'];
    }
```

**Datos adicionales**
 - Testado en Chamilo: 1.11.20 y 1.11.24

**Comment by juancp-contidosdixitais** [comment]
Revisando este issue me he dado cuenta que las instrucciones para la reproducción del error estaba mal. Acabo de editar las instrucciones con las indicaciones correctas

**Comment by ywarnier** [comment]
PR aceptado. Gracias!

**Comment by ywarnier** [comment]
This PR https://github.com/chamilo/chamilo-lms/pull/4971
