### ISSUE TITLE
LP view + iPhone/iPod/iPad/Safari : Opción deshabilitar botón "Abrir contenido en una nueva pestaña"

### ISSUE THREAD

**Issue by juancp-contidosdixitais** [chamilo/chamilo-lms#4954]
**Descripción.**
Cuando cargamos una lección, los dispositivos iOS o MacOS + Safari muestran en la esquina superior izquierda un botón con el texto "Abrir contenido en una nueva pestaña", al pulsar sobre este botón se abre una nueva pestaña cargando el contenido del SCORM fuera del iframe de la lección, en esta nueva ventana el contenido abierto queda "desconectado" del LMS.

Se nos ha dado el caso más de una vez, sobre todo en lecciones cuyo contenido es video largo que se debe visualizar durante varias horas, de que el usuario pulsa ese botón de abrir contenido en una nueva pestaña y cierra la pestaña donde estaba cargada la lección (la vista donde está el propio botón) aún indicándoles que no lo hagan. Esto nos provoca incidencia ya que el SCORM cargado fuera de la vista de lección queda desconectado del LMS, provocando frustración a nuestros usuarios ya que no se recoge el tiempo que han estado visualizando el contenido.

**Posible solución**
Hemos llegado a la conclusión que, salvo otra sugerencia, para evitar este problema deberíamos tener una opción en configuration.php poder ocultar el botón de "Abrir contenido en una nueva pestaña"

**Capturas**

Botón "Abrir contenido en una nueva pestaña"
![image](https://github.com/chamilo/chamilo-lms/assets/93096561/9fa08134-f6d3-49ea-aa01-137f648c63f0)

Mensaje de error abrir el contenido pulsando el botón anterior, este mensaje de error esta generado por el propio SCORM al no poder conectar con el LMS, no por Chamilo
![image](https://github.com/chamilo/chamilo-lms/assets/93096561/6d1606bf-9033-421f-94e6-1caf5e777947)

**Comment by ywarnier** [comment]
Me parece bien.
Por favor usar la definición siguiente en configuration.dist.php:
```
// Hide the "Open in new window" button in learning paths when viewing long content (using the button disconnects SCORM tracking - more details in #4954)
//$_configuration['lp_ios_hide_open_in_new_window_button'] = false;
```

**Comment by ywarnier** [comment]
PR #4970 aceptado (commit eb6e4d30edf9a12206a2f23410768b81a46032ba). Gracias.
