### ISSUE TITLE
Problema con los usuarios iniciando sesion 

### ISSUE THREAD

**Issue by ZAAC15** [chamilo/chamilo-lms#4967]
Yo tengo una pagina creada, con ciertos usuarios y presento un error donde cada que intentan ingresar les sale este error.
**No está autorizado a ver esta página o su conexión ha caducado.**
Quiero saber si me podiran ayudar o decirme com osolucionarlo.
Gracias.

**Comment by ywarnier** [comment]
Hola @ZAAC15 
Por el nivel de detalle que provees, solo puedo suponer que no tienes mucha experiencia en este campo todavía. Te sugeriría hacer la pregunta en el foro de Chamilo (https://forum.chamilo.org). Este espacio (Github) es para reportar errores acertados con bastante detalles técnicos, y creo que vamos a necesitar mucho tiempo para llegar a estos detalles (y este no es el espacio para este tipo de interacción). Por favor pide una cuenta en forum.chamilo.org, haz tu pregunta ahí, averigua con nuestra comunidad todo lo necesario para entender mejor el problema, y si efectivamente es un error de Chamilo, con gusto te estaremos leyendo nuevamente, esta vez con detalles.

Ojo que existe una plantilla de reporte de error, que te pasaste por completo y que hubiera podido ayudarnos bastante en ayudarte. Pero como decidiste hacerlo directo, lamentablemente no tenemos ninguna pista ahora.

**Comment by edufinci** [comment]
Hola a mi me paso los mismo y he perdido acceso a mis cursos 
alguna sugerencia mas
