### ISSUE TITLE
The graphs of the results from gradebook (flat-view) are not shown

### ISSUE THREAD

**Issue by mk111** [chamilo/chamilo-lms#4974]
*Apache 2.4 / no compatibility module used or available
* Chamilo 1.11.26

**Describe**
(not actual bug, but ...)

picture(s) of graphs are generated into /app/cache but can't be accessed due .htaccess restrictions
results in empty picture placeholder after results table

**Comment by ywarnier** [comment]
We've seen that one as well, indeed. This is due to a recent contributed change that we thought was working fine, but indeed, it's failing for some contexts. Thank you for the PR, we will try and test it this week before integrating (but it looks good at first sight).
