### ISSUE TITLE
Migrate course tools from plugins to tool + c_tool

### ISSUE THREAD

**Issue by AngelFQC** [chamilo/chamilo-lms#5073]
And remove the Mobidico and VideoConference tools to allow create shortcuts

**Comment by ywarnier** [comment]
@AngelFQC what's the status of this?
@NicoDucou will soon do a large migration again. Is the code already there to deal with the migration of plugin icons on course homepages?

**Comment by AngelFQC** [comment]
>  what's the status of this?

Reviewing the code, shortcuts are only for resources. Plugin tools are not resources.
Plugins have to create a record in the `tool` table and then create the record in `c_tool`
However, the migration deletes records in `c_tool` that are not related with `tool`. Getting into a contradiction?

**Comment by ywarnier** [comment]
I've checked the code and I can see no issue there, but it is difficult for me to test it, so I'm assigning the testing to @NicoDucou

**Comment by ywarnier** [comment]
#5088

**Comment by NicoDucou** [comment]
I can see that after migrating a plateform with the plugin BBB and the plugin Mobidico activated to tools still appears in the course and they are registered with a resource_node_id so in the new organisation and there is a registry in the tool table for each plugin.

So every thing seems correct here.
