### ISSUE TITLE
C2: Make anonymous users auto-provisioning optional

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5079]
In C2, the automated creation of new anonymous users based on IP addresses is enabled by default.
This should be an option (disabled by default) in settings_current, in the "Security" section, called "anonymous_autoprovisioning" (or something that matches the setting for max number of anonymous users).

The default behaviour should be to use the anonymous user (status 6 / role ANONYMOUS) for any anonymous user trying to connect. When the option is enabled, new users are created (this is how it works in C1).

**Comment by NicoDucou** [comment]
All good for this task
