### ISSUE TITLE
C2: Review terms + GDPR

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5121]
Make sure terms & conditions and the GDPR section in profile are working correctly.

**Comment by NicoDucou** [comment]
I activated the parameter for terms and conditions and the link appears in the plateform block on the administration page and enable to go to /resources/terms-conditions. On this page I have a warning indicating : 
> You should create the Term and Conditions for all the available languages.
But I do not have a boton to create a new term and condition.

For the page /resources/users/personal_data it seems correct but I need to be able to create terms and condition to finalize the validation

**Comment by christianbeeznest** [comment]
Hi @NicoDucou ,

Check it now please, the button in the toolbar is fixed now.

**Comment by christianbeeznest** [comment]
Hi @NicoDucou , It is fixed in this commit https://github.com/christianbeeznest/chamilo-lms/commit/f813d40e5f0e03fd9a8e762475f27549d302d1f6

Thanks for confirmation.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

It is nearly all good.
The only missing part is the Protection of Personal data block on the administration page with in this block an entry "user list" which is a link to the page main/admin/user_list_consent.php 

I checked all the other indication and they are all correct : 

> I did some testing and I could go a bit futher but there are still corrections to be done. Here is the list of things to fix :
>     * The terms and Conditions after login should be in the user's language
Ok

>     * On the terms and conditions edit page there should be all the language in the select field.
Ok
 
>     * The check box with "IHaveReadAndAgree" on top of the button "Register User Ok" should be present also for HTML type terms and conditions. For the moment it only appears for link page type/
Ok

>     * The "Protection of Personnal data" block should appear in the administration page and the page  main/admin/user_list_consent.php should be available from there to deal with the legal agreement deletion and account deletion queries from users.
I do not see the Protection of Personnal data block on the administration page.
 
>     * when clicking on deletion of legal aggreement and deletion of account a notification should be send to the data officer using the officer email parameter and if not set then the notification should be sent to all plateform admins in the Chamilo messaging system.
Ok and the message contains the link to manage the request on the page main/admin/user_list_consent.php and all is fine on this page.

**Comment by christianbeeznest** [comment]
Hi @NicoDucou 

You deberia have false this settings profile.disable_gdpr , depend on that setting to show or not the link 

// Data protection
            if ('true' !== $this->settingsManager->getSetting('profile.disable_gdpr')) {
                $json['data_privacy'] = [
                    'editable' => false,
                    'items' => $this->getItemsPrivacy(),
                ];
            }
            
Thanks for confirmation

**Comment by NicoDucou** [comment]
That was the issue so it's all good now.
