### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by Davischristleraj** [chamilo/chamilo-lms#5136]
Dear Sirs,

I've recently installed chamilo on my cpanel but I'm getting an error at the final step due SQL database. I've attached the snapshot for reference. Please assist. 
![IMG-20240205-WA0002](https://github.com/chamilo/chamilo-lms/assets/158503367/c786ffd5-c650-450a-865a-d88d968c3574)

**Comment by jgnosolored** [comment]
Hello.

The reason is indicated in the screenshot you send. It displays a message indicating that the user does not have permissions to create the database.

In Cpanel, create the database before with the name, username and password. Then follows the Chamilo installation process.

Regards.

**Comment by Davischristleraj** [comment]
Thank you so much sir, it worked...

Now I'm facing an issue in file upload. I've attached the snapshot, can you please assist? 
![Uploading IMG-20240206-WA0006.jpg…]()
