### ISSUE TITLE
no visualizo imagenes en chamilo instalado en windows

### ISSUE THREAD

**Issue by kifrim** [chamilo/chamilo-lms#5166]
tengo instalado desde la raiz /htdocs/  chamilo
Una descipción concisa y clara del problema.
chamilo version 1.11.0.6 , 
apache 2.4.17 
 php 5.6.23

al momento de editar un curso las imagenes se muestran a nivel profesor, cuando se visualiza a nivel alumno no se visualiza las imagenes 

vista del alumno
![no se imagen](https://github.com/chamilo/chamilo-lms/assets/28078328/0e9bc540-bb2d-493d-b453-bd193d60696f)

si la imagen sola la abro desde el navegador
![sin acceso](https://github.com/chamilo/chamilo-lms/assets/28078328/9a1cfcc8-52c6-407f-aa57-298cf8572c1f)

cuando a la ruta de la iamgen le aumento  /app/ cours... delante de todo, si se visualiza 

![se ve](https://github.com/chamilo/chamilo-lms/assets/28078328/663ca414-c4c5-4ab3-a7c5-201f85c62bbb)

me gustaria que me ayude con el error, ya que las imagenes no se muetran a nivel alumno, mi chamilo lo instale a nivel raiz, por tanto mi    **$_configuration['url_append'] = '';** se instalo asi.

**Comment by ywarnier** [comment]
Hola @kifrim
Parece que el problema proviene del soporte del archivo .htaccess por parte de tu Apache.
Si no lo has hecho, verifica la parte "Apache" dentro de la guía de instalación de Chamilo, en tu carpeta chamilo/documentation/installation_guide.html (hay una versión en español referenciada en la intro).
Esencialmente, nunca deberías ver la ruta "/app/courses", solo "/courses" y tu servidor web debería encargarse de hacer lo necesario para que funcione así.
