### ISSUE TITLE
Blank page when creating category

### ISSUE THREAD

**Issue by Kptainflintt** [chamilo/chamilo-lms#5193]
Fresh install, first course created and everithing fine instead of I'm unable to add or modify a category.

Steps :
1. Go to Administration page
2. Click on Course categories
3. Create a category
4. Get a blank page on validation

URL ends with : main/admin/course_category.php?category=&action=add&id=

I don't know if it's normal, but it seem to miss something right?

 - OS: Windows & Linux tested
 - Browser : all 

**Server
 - OS: CentOS7
 - Version of Chamilo:  1.11.26
 - Version of PHP: 7.4

**Comment by Kaneda-1** [comment]
https://github.com/chamilo/chamilo-lms/discussions/5163

**Comment by Kptainflintt** [comment]
Hi,

Right, got shit in my eyes, my bad and sorry...

Thank you, I've downloaded the course_category.lib.php be5bc90 file from github and replace the existing one.
Now, everyting is OK, I close
