### ISSUE TITLE
C2: Visual placeholders for Courses menu and breadcrumb

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5230]
When loading a page, the main "Course" entry of the left menu and the breadcrumb sometimes take a bit of time to load. There should be a placeholder for these while they are loading (like the tools on the course homepage).

![Capture d’écran du 2024-03-11 13-03-02](https://github.com/chamilo/chamilo-lms/assets/609839/f572612b-f829-4794-9267-3d161a3dad48)

**Comment by daniboygg** [comment]
Could I get an example of a URL (or is loading any page?) where I can see the current behavior?

I need to replicate this to know where to change things. I would like some environment where I can experiment this, or at least, what kind of data I need to set in my local environment to notice this.

**Comment by ywarnier** [comment]
For the left menu part, loading https://testing25.beeznest.com/ and logging in will send you to https://testing25.beeznest.com/home and you can see that the "Course" item in the left menu takes about 2 seconds to load.
