### ISSUE TITLE
C2: Convert sys_calendar to use CCalendarEvent

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5270]
The system calendar (global events) is still in legacy code and does not use the new structure around CCalendarEvent.
Convert the interface and underlying code to enable a unified management of these events, then drop the sys_calendar table once we are sure events are migrated correctly.

This is an extension of #5145

**Comment by ywarnier** [comment]
All good, but the global calendar events have to be marked in *red color* by default.

**Comment by christianbeeznest** [comment]
These are the default values now:

$defaultColors = [
    'platform' => 'red',
    'course' => '#458B00',
    'session' => '#00496D',
    'personal' => 'steel blue',
];

In case there are values in the setting agenda.agenda_colors, they will be replaced with those.
