### ISSUE TITLE
C2 : when editing an administrator account missing active and expiricy date and automatically desactivating the user

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#5295]
On C2 of 2024/03/26 when editing an administrator account on main/admin/user_edit.php?user_id=??? the Account field and the Expiration date field do not appear.

When saving the form the user's active field is set to -2 and the user can not logged in anymore.

The 2 fields should be present in the form and the account should not get desactivated.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 
It solve an issue but it generates other issues so this commit should be removed.
The problem with your commit is that if an admin has been desactivated if we edit its account then automatically it becomes activated again and this should not happen.

So what we want is : 
* In the user edition form main/admin/user_edit.php?user_id=XXX if the user is an admin the fields  Account field (to set active or inactive) and the Expiration date field should appear the same way as it appears for the other users.
* if the loggin user edit is own account then in this case the fields Account field (to set active or inactive) and the Expiration date field should not appear but the values should not be changed, so it could be passed as hidden to make sure they stay the same.

**Comment by christianbeeznest** [comment]
Thank you @NicoDucou , it is fixed in the last commit.

**Comment by NicoDucou** [comment]
Hi @christianbeeznest 

It's nearly all good. It works as we want but when an admin edit his own account it does not show the account and the expiration date fields which is correct but when validating the form it generates this error : 
```
Chamilo\CoreBundle\Entity\User::setExpirationDate(): Argument #1 ($expirationDate) must be of type ?DateTime, string given, called in /var/www/testing24.beeznest.com/www/public/main/inc/lib/usermanager.lib.php on line 920
ExceptionLogs 2Stack Trace
TypeError
in src/CoreBundle/Entity/User.php (line 1133)
    public function getExpirationDate(): ?DateTime    {        return $this->expirationDate;    }    public function setExpirationDate(?DateTime $expirationDate): self    {        $this->expirationDate = $expirationDate;        return $this;    }
User->setExpirationDate()
in public/main/inc/lib/usermanager.lib.php (line 920)
UserManager::update_user()
in public/main/admin/user_edit.php (line 452)
```

**Comment by christianbeeznest** [comment]
Thank you @NicoDucou , It is fixed with the last commit.

**Comment by NicoDucou** [comment]
All good with this now
