### ISSUE TITLE
C2: Create var/upload/scheduled_announcement on install or migration (now going through C2's assets system)

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5314]
The "allow_scheduled_announcements" feature can now be selected directly from the admin, so the requirement of creating a directory "app/upload/scheduled_announcement/" in C1 must be translated into an existing directory in C2.

This is from C1:
```
// Allow scheduled emails to session users.
//CREATE TABLE scheduled_announcements (id INT AUTO_INCREMENT NOT NULL, subject VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, date DATETIME DEFAULT NULL, sent TINYINT(1) NOT NULL, session_id INT NOT NULL, c_id INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
// sudo mkdir app/upload/scheduled_announcement
// Uncomment and set the following setting to true before moving on
//$_configuration['allow_scheduled_announcements'] = false;
// Add "attachment" file upload extra field label in: main/admin/extra_fields.php?type=scheduled_announcement&action=add
// Add "send_to_coaches" checkbox options field label in: main/admin/extra_fields.php?type=scheduled_announcement&action=add
// Add the list of emails as a bcc when sending an email.
// Configure a cron task pointing at main/cron/scheduled_announcement.php
```

We must make sure that everything is ready to enable this feature, so the "attachment" and "send_to_coaches" extra fields for sessions must be there as well (on install and migration, if it is not there).

**Comment by christianbeeznest** [comment]
Extra fields for "attachment" and "send to coaches" have been added through migrations and fixtures to ensure their availability from installation or update.

File attachment management is integrated through C2's asset system using ExtraField::FIELD_TYPE_FILE , eliminating the need to manually create the "app/upload/scheduled_announcement/" directory as in C1. 

the setting allow_scheduled_announcements, table and cron are already added in C2 too .
