### ISSUE TITLE
[C2] Error creating a social group

### ISSUE THREAD

**Issue by daniboygg** [chamilo/chamilo-lms#5382]
**Describe**
Trying to create a social group gives an error in the browser console, but no feedback is given to user

**To Reproduce**
1. Login in Chamilo
2. Goes to Social network
3. Go to Social groups
4. Click on Create a social group
5. Fill in the data
6. Click on Add button

**Expected behavior**
A social group should be created 

**Additional context**
The line where error happens is this https://github.com/chamilo/chamilo-lms/blob/master/assets/vue/views/usergroup/List.vue#L238, it seems that the form does not gather permissions correctly

**Comment by christianbeeznest** [comment]
I can't reproduce it now, it seems already was fixed.
