### ISSUE TITLE
C2 : user image appears in big in the Chamilo messaging system

### ISSUE THREAD

**Issue by NicoDucou** [chamilo/chamilo-lms#5389]
Add a picture to your profile, then send a message to someone in Chamilo.
Go to the sent message page and open the message.
You will see that the user picture image is not resized and appears in big : 
![image](https://github.com/chamilo/chamilo-lms/assets/6579268/53aede52-7ece-4692-bbf8-615a5aae3cf6)

If yyou connect as the receiver, and open the received message you will also see the user picture in big.
It should always be resized to appear in standard small size the same as the default user picture image.

**Comment by NicoDucou** [comment]
Yes it would be good to have the name and surname to identify the user

**Comment by daniboygg** [comment]
In vue the things available for every person involved in messages is the username but not first and last name

![image](https://github.com/chamilo/chamilo-lms/assets/50702276/73ff81db-4ece-4d3a-8a2f-7decc58cb14c)

@AngelFQC Do I need to fetch this information for every user, or is there another way to retrieve this information?

**Comment by daniboygg** [comment]
I modify the course list as well according to figma, because was related to this issue. Changes are in the same pull request. 
Going from this 

![image](https://github.com/chamilo/chamilo-lms/assets/50702276/a35475d9-04ea-4479-905b-2f189f1998e2)


to this 

![image](https://github.com/chamilo/chamilo-lms/assets/50702276/fe3aadb7-f598-4cf9-9de5-6794877a8eed)

**Comment by AngelFQC** [comment]
> In vue the things available for every person involved in messages is the username but not first and last name
> 
> @AngelFQC Do I need to fetch this information for every user, or is there another way to retrieve this information?

@daniboygg You can now get the user's full name for sender and receivers with the Messages API

```json
"receiversTo": [
  { 
    "@id": "/api/message_rel_users/10",
    "@type": "MessageRelUser",
    "receiver": {
      "@id": "/api/users/1",
      "@type": "http://schema.org/Person",
      "illustrationUrl": "/img/icons/32/unknown.png",
      "id": 1,
      "username": "admin",
      "fullName": "Pérez, Juan"
```

**Comment by ywarnier** [comment]
I haven't looked into the details of how to get a better image, but when you have not uploaded a picture yet, your social network profile looks like this:
![Capture d’écran du 2024-04-26 09-55-38](https://github.com/chamilo/chamilo-lms/assets/609839/974aac38-57d3-4bd0-937c-f2380530e68b)

**Comment by daniboygg** [comment]
In the last pull request I made, the profile image expands to full size (the whole size of the gray circle shown by @ywarnier). Right now the image has low quality, but expands ok. If someone can change backend to send an image with more resolution, the problem will be fixed.

![image](https://github.com/chamilo/chamilo-lms/assets/50702276/116c4389-544f-40e1-b04f-c4d343b74924)

**Comment by ywarnier** [comment]
Ok, will do

**Comment by NicoDucou** [comment]
The image stills appears in big when answering a message :
![image](https://github.com/chamilo/chamilo-lms/assets/6579268/269c4b35-2813-41de-87c7-7c52735cf73b)

**Comment by daniboygg** [comment]
@NicoDucou you are right! My bad, I didn't update the reply view with the new component. Thanks to notice. I submitted a PR with the changes need to fix this. 

This is how supposed to look now

![Screenshot from 2024-04-30 12-52-12](https://github.com/chamilo/chamilo-lms/assets/50702276/fa9d5d39-7437-4488-b2be-46616fffc2c6)


There is a component that uses the old component, but I don't know how to show this to see if I need to modify it. How these tags in myReceiver are created from interface?

```vue
    <div class="flex justify-end gap-2">
      <div v-if="myReceiver">
        <BaseChip
          v-for="tag in myReceiver.tags"
          :key="tag['@id']"
          :value="tag"
          is-removable
          label-field="tag"
          @remove="onRemoveTagFromMessage(tag)"
        />
      </div>

      <BaseAutocomplete
        v-if="item.sender && item.sender['@id'] !== securityStore.user['@id']"
        id="search-tags"
        v-model="foundTag"
        :label="t('Tags')"
        :search="onSearchTags"
        option-label="tag"
        @item-select="onItemSelect"
      />
    </div>
```

**Comment by NicoDucou** [comment]
Hi @daniboygg 
For the tags, you need to open a message that you received and on the right hand side you will see a box titled "tags" that enables you to create or assign existing tags.
But I see that there is a problem because if the word does not exist as a tag it should offer you to create it and it does not do it at the moment. That's why you can not create tags from the interface.
![image](https://github.com/chamilo/chamilo-lms/assets/6579268/74774d55-2e8c-413f-90b0-9d946be84881)
@AngelFQC implemented those tags so he should know why it does not enable the creation now.
