### ISSUE TITLE
[C2] Duplicate messages on upgrade from 1.11 to 2.0

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5511]
- Messages with status=4 should be deleted on upgrade (status = received by destination) to avoid duplicate

(ref BT#21611)

**Comment by NicoDucou** [comment]
In chamilo 1.11.x in main/inc/lib/api.lib.php there is : 
```
define('MESSAGE_STATUS_UNREAD', '1');
define('MESSAGE_STATUS_OUTBOX', '4');

```
And for every message send to a user we have 2 registery in the message table with the same 5 fields :
* user_sender_id
* user_receiver_id
* send_date
* title
* content

But there is 1 registry with msg_status = 1 and 1 registry with msg_status = 4.
In Chamilo 2 each message is shown directly in inbox and outbox of the other user so we decided to delete the registry with msg_status = 4 before doing the conversion of message from the structure in 1.11 to the new structure in master. So it should be done before all other migration of messages to be sure not to use those registries.

The query to identify all the doubled messages with msg_status = 4 to know the list of messages to be deleted is :

`select distinct(m1.id) from message m1, message m2 where m1.id != m2.id and m1.user_sender_id = m2.user_sender_id and m1.user_receiver_id = m2.user_receiver_id and m1.send_date = m2.send_date and m1.title = m2.title and m1.content = m2.content and m1.msg_status = 4;`

So now @christianbeeznest I let you prepare the migration to delete those messages before processing all the message table for structure conversion.

**Comment by NicoDucou** [comment]
In a new migration there is no double message in the inbox nor in the outbox. It seems all good so I close this task
