### ISSUE TITLE
[C2] Rename "settings_current" table to just "settings"

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5567]
Not an essential task, but would definitely improve predictability of the Chamilo database structure, and the changes are minimal (about 12 places it is used "as is" in the code).

Doing this in an early pre-alpha stage of Chamilo 2 would be super cool.

**Comment by ywarnier** [comment]
Requires changes in the entities, fixtures and migrations, as well as in the code of some plugins. Simply search for "settings_current". Not necessary to change the constant name TABLE_MAIN_SETTINGS_CURRENT to TABLE_MAIN_SETTINGS, but feel free to do it to if that's not too much work.

**Comment by ywarnier** [comment]
Then re-assign me the issue to update the changelog, please.

**Comment by christianbeeznest** [comment]
It is implemented in this PR https://github.com/chamilo/chamilo-lms/pull/5572 , it requires testing before merging
