### ISSUE TITLE
[C2] Rename ROLE_RRHH constant to ROLE_HR

### ISSUE THREAD

**Issue by ywarnier** [chamilo/chamilo-lms#5660]
This is a small change to increase understandability of the code, but it is necessary to do it pre-alpha as it potentially changes the string un user.roles for a few users.

The ROLE_RRHH constant name stems from Spanish where abbreviations for plurals (like Human Resource*s*) is written in duplicate letters (so RRHH for Recursos Humanos).

This is confusing while reading it for a non-Spanish speaker and we have conventions for all-English code and comments, so... let's apply that while we can.

- Change constant name everywhere
- Add a Migration to update the user.roles string to replace ROLE_RRHH by ROLE_HR

Also, we'll slowly remove the notion of "Manager" in some of the terms we use around HR. The HR role is not only for the HR manager but for the whole HR team, potentially. But these changes will be added progressively (and later).

**Comment by christianbeeznest** [comment]
It is merged to master for testing. Thanks for confirmation :)

**Comment by ywarnier** [comment]
`php bin/console doctrine:migrations:execute Chamilo\\CoreBundle\\Migrations\\Schema\\V200\\Version20240713125400`
probably also necessary for this one

**Comment by ywarnier** [comment]
Looks good!
