### ISSUE TITLE
Your script doesn't have write access to the config directory

### ISSUE THREAD

**Issue by jose123b** [chamilo/chamilo-lms#5741]
Chamilo 1.11.26

![da](https://github.com/user-attachments/assets/526f6b0f-2a80-4704-a7fc-198fe7fc103c)

Buenas noches, tengo este problema cada que intento instalar Chamilo 1.11.26, dicho archivo hasta el paso 6 no existe en carpeta conf, en el paso 7 aparece, pero muestra error de escritura a pesar que la carpeta incluso tiene todos los permisos. Me podrían ayudar por favor, gracias

**Comment by NicoDucou** [comment]
Hola @jose123b 
Como indicado en tu screenshot, si estas seguro que los permisos estan correctos entonces tienes que revisar el segundo punto revisando si PHP esta en Safe-Mode.
Saludos

**Comment by jose123b** [comment]
Aún no se puede, modifique el archivo **ini** y agregue **save_mode=off** pero a pesar de eso siguen saliendo los mismos errores.

**Comment by jose123b** [comment]
Porfin logre instalar correctamente (eso espero)

**Comment by ywarnier** [comment]
Suponiendo que este problema está definitivamente resuelto. Cerrando.
@jose123b siempre piensa en los demás: al encontrar una solución, regresa para indicar cual fue, o cual fue tu error, para que otros con el mismo problema puedan más fácilmente encontrar una solución a futuro. Gracias!
