### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by zentery** [chamilo/chamilo-lms#5770]
When I installed chamilo-lms 1.11.12, when I got to the last step of the installation, an internal server error occurred. What is the problem and how can it be solved?
![Snipaste_2024-09-02_19-32-28](https://github.com/user-attachments/assets/83d8905e-8d68-4106-949c-32e64bdf83c0)

**Comment by ywarnier** [comment]
This is a duplicate of #5772. Closing.
