### ISSUE TITLE
Gamification 1.11.26

### ISSUE THREAD

**Issue by Moigaston** [chamilo/chamilo-lms#5820]
ne fonctionne pas. L'option est activée dans la configuration de la plateforme, mais le résultat reste sur une étoile. dans le parcours ce sont des exercices au format scorm qui sont utilisés.

**Comment by Coursenligne** [comment]
Je n'ai plus en tête toutes les conditions (de mémoire elles sont données dans la partie gamification).
Chaque étape donne une étoile, donc si vous avez 1 exercice, vous aurez 1 étoile.
En revanche, votre parcours devrait vous donner également une étoile...

**Comment by NicoDucou** [comment]
Bonjour
Attention première remarque le système de gamification n'est pas compatible avec les scorms, on considère uniquement les exercices de Chamilo, de l'outil exercice du cours.
De plus les règles pour l'avancement des étoiles et des scorres correspond à une règle fixe qui n'est pas paramétrable pour le moment.
La règle est la suivante :
![image](https://github.com/user-attachments/assets/08a7891d-777a-4b1d-8fc4-c33b7340d3b5)

**Comment by Moigaston** [comment]
Merci beaucoup pour vos rapides réponses Coursenligne et NicoDucou et pour les renseignements précieux. J'ai fait une copie de l'image.
