### ISSUE TITLE
Compilatio plugin not working (2024 API changes)

### ISSUE THREAD

**Issue by zentery** [chamilo/chamilo-lms#5839]
How can I enable this module main/plagiarism/compilatio/? I have tried the application page many times but couldn't find a place to enable it. Can anyone help me? Thank you very much!

**Comment by ywarnier** [comment]
Hi @zentery 
Compilatio has changed its API. We're updating our code soon to reflect that. Sorry about this issue. We haven't been warned.

**Comment by ywarnier** [comment]
Sorry, I should have written "we will *hopefull* update this soon". It still depends on a few things clicking. This won't be part of Chamilo 1.11.28 though, so you might need to wait a bit and apply some changes manually.

**Comment by ywarnier** [comment]
Should be fixed in 1.11.28 (to be released in hours from now).
Mostly fixed by this https://github.com/chamilo/chamilo-lms/commit/97a6bab4a5a2aa11339ac8ef3a0d27d9fd4f43cc (but there are other small changes after that, that may affect the support).
