### ISSUE TITLE
Not able to "create" a BigBlueButton meeting in some sessions

### ISSUE THREAD

**Issue by GhaziTriki** [chamilo/chamilo-lms#5862]
**Describe**

This is more a question to understand the current behaviour.

In some sessions when we click on "Join videoconference" button, the meeting is not created.

It is not really clear when a meeting can be created and when it is not.

**Comment by ywarnier** [comment]
Hi @GhaziTriki 
A teacher or session coach can create a meeting. Other users should not be able to create one...
I'm not sure if you're observing any other behaviour, but if the meeting gets closed between the moment the user loads the BBB page and the moment (s)he clicks the "Join videoconference", joining will not work.

**Comment by ywarnier** [comment]
Feel free to re-open if you have more data that evidences that something is broken

**Comment by GhaziTriki** [comment]
Hello,

Here the current config. Anything wrong?
![image](https://github.com/user-attachments/assets/84a380a1-d152-425d-becb-7200d8d14992)
