### ISSUE TITLE
The PDF reader no longer appears and is replaced by a download button

### ISSUE THREAD

**Issue by oneill78** [chamilo/chamilo-lms#5907]
### Discussed in https://github.com/chamilo/chamilo-lms/discussions/5905

<div type='discussions-op-text'>

<sup>Originally posted by **oneill78** November  4, 2024</sup>
Bonjour,
J'ai mis à jour Chamilo à la version 1.11.28 et les PDF qui apparaissaient dans le parcours ne sont plus visibles.

A la place il y a un bouton "télécharger" qui apparait.
Si je clique le PDF apparait mais je ne comprends pas pourquoi le lecteur PDF ne fonctionne plus automatiquement comme dans la version 1.11.26.

Ce problème apparait sur plusieurs plateformes Chamilo mise à jour de 1.11.26 en 1.11.28 

Je vous remercie pour votre aide afin de corriger ce dysfonctionnement

Lionel

english version :
Hello,
I updated Chamilo to version 1.11.28 and the PDFs that appeared in the course are no longer visible.

Instead, a "download" button appears.
If I click, the PDF appears but I don't understand why the PDF reader no longer works automatically as in version 1.11.26.

This problem appears on several platforms Chamilo updated from 1.11.26 to 1.11.28

Thank you for your help in correcting this malfunction

Lionel</div>

**Comment by NicoDucou** [comment]
Bonjour : Hello

Ce problème a été réglé dans la tâche  #5917
This problem has been solved in issue  #5917 

Cordialement / Best regards
