### ISSUE TITLE
PDF reader does not display document in 1.11.28

### ISSUE THREAD

**Issue by oneill78** [chamilo/chamilo-lms#5917]
Hello,
The PDF reader does not display the document in 1.11.28, while it worked correctly in 1.11.26.
There is a "download" button that appears at the top of the page in the learning path but not the PDF reader.

For information, the PDF is directly added in the left menu in the path.

How can I fix this?

This is important because the learning paths are mostly made up of PDFs

Thank you for your answer

**Comment by AyaMaksoud** [comment]
Same as #5907

We have the same issue. Rendering pdf is necessary. 
So in order to unlock the situation untel the correction is made, I removed the pdf from being downloaded, so it is always displayed.

In main\lp\learnpath.class.php, I removed "pdf" from the list $extensionsToDownload.

**Comment by NicoDucou** [comment]
Hi all
The correction from @AyaMaksoud is correct.
We just modified yesterday in the following commit : https://github.com/chamilo/chamilo-lms/commit/54d55b59b46e727aeafbe2243bcf85db09d09289

So apply this commit and it should work as before.

Best regards

**Comment by Bavarianspirit** [comment]
works for me.
Thanks

**Comment by oneill78** [comment]
Hello,
Thanks for the fix. Everything works fine.
Lionel
