### ISSUE TITLE
Added text in the Announcements

### ISSUE THREAD

**Issue by sxbala** [chamilo/chamilo-lms#5993]
Each of my announcements has a random phrase "data-cke-67648c1f86ea9-" inserted into the middle of my text. 

**To Reproduce**
1. Create an announcement
2. Write in both the title and description boxes
3. Switch to student view and view the announcement

**Expected behavior**
An unadulterated announcement

**Screenshots**

<img width="1357" alt="Screenshot 2024-12-19 at 3 18 24 PM" src="https://github.com/user-attachments/assets/975410c6-967d-4396-9b51-9a88f09223aa" />

<img width="1357" alt="Screenshot 2024-12-19 at 3 18 49 PM" src="https://github.com/user-attachments/assets/82856f69-f69e-417c-877c-643497c50ab7" />

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - safari + brave

**Server
 - OS: [e.g. Linux Ubuntu 18.04/Windows 10]
 - Version of Chamilo:  1.11.8
 - Version of PHP: 7.4

**Comment by ywarnier** [comment]
Hi, this is a known bug, fixed by https://github.com/chamilo/chamilo-lms/commit/82cc07edd8ef316e6b36da7c501120d5c0aeb151
It will be included in 1.11.30 (we're trying to release it before the end of the year).

**Comment by sxbala** [comment]
thanks, I'm new to the platform
